### ISSUE TITLE
Slicing error - Unable to slice

### ISSUE THREAD

**Issue by Larks007** [Ultimaker/Cura#15202] opened 2023-04-10 12:27 UTC
### Application Version

5.2.1

### Platform

Windows 11 Home

### Printer

Creality CR10

### Reproduction steps

Loaded a file - Barlyway Cottage Roof from Printable Scenery.

Clicked the slice button and had an error reported shortly after pushing the button. 
"Slicing failed with an unexpected error. "
![Cura 5 2 1 slicing error](https://user-images.githubusercontent.com/29157908/230900589-68467b5f-a4d2-424e-b18e-a9dd56449b1e.png)

GPU is a Nvidia 3080Ti with latest graphics drivers downloaded and installed. I rebooted my windows to a fresh start and retried to slice with the same error. 

### Actual results

https://www.dropbox.com/scl/fo/mzgnhsrzg9n1sis4mo4mu/h?dl=0&rlkey=g4dlh0tzdr2z83k9g4hnpjc6r

### Expected results

https://www.dropbox.com/scl/fo/mzgnhsrzg9n1sis4mo4mu/h?dl=0&rlkey=g4dlh0tzdr2z83k9g4hnpjc6r

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

https://www.dropbox.com/scl/fo/mzgnhsrzg9n1sis4mo4mu/h?dl=0&rlkey=g4dlh0tzdr2z83k9g4hnpjc6r

**Comment by Vandresc** [comment] 2023-04-28 10:23
Hi @Larks007, I could indeed reproduce the error in 5.3, the issue is now fixed in 5.4 (future release). Thank you so much for your feedback.

**Closed by Vandresc** 2023-04-28 10:23 UTC
Labels: Type: Bug, Status: Triage
