### ISSUE TITLE
cura 5.0 beta won't start on ubuntu 22.04

### ISSUE THREAD

**Issue by piontec** [Ultimaker/Cura#12081] opened 2022-05-04 06:37 UTC
### Application Version

5.0 Linux x64 AppImage

### Platform

ubuntu 22.04

### Printer

Ender 3 pro

### Reproduction steps

Start the app with `QT_QPA_PLATFORM=wayland cura-beta`

### Actual results

The following log
```
➜  QT_QPA_PLATFORM=wayland cura-beta
PyInstaller/loader/pyimod03_importers.py:495: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
/tmp/.mount_cura-bCMTwJn/Ultimaker-Cura: symbol lookup error: /lib/x86_64-linux-gnu/libEGL_mesa.so.0: undefined symbol: wl_proxy_marshal_flags
```

### Expected results

App runs

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

It was running OK on ubuntu 21.10.

**Comment by fvrmr** [comment] 2022-05-04 07:48
Hi @piontec thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11856, so I will close this issue.

**Closed by fvrmr** 2022-05-04 07:48 UTC
Labels: Type: Bug
