### ISSUE TITLE
Add Print Profile filter to show only setting overrides.

### ISSUE THREAD

**Issue by presto87** [Ultimaker/Cura#10049] opened 2021-06-29 12:58 UTC
### Is your feature request related to a problem?

It is difficult to quickly view print profile settings that are over-ridden.

### Describe the solution you'd like

I suggest adding a filter that shows all profile overrides regardless of whether they are set to visible or hidden (similar to how searching for a profile works).  This could be setup as a separate filter in the profile drop-down and/or configured to show over-ridden profiles when "override" is typed in the setting search bar.

### Describe alternatives you've considered

This can be viewed using the HTML settings export plugin, but having to save and open the settings in an HTML file is cumbersome.

### Affected users and/or printers

All advanced users who are creating profiles customized for specific part applications will benefit from this.

**Comment by fvrmr** [comment] 2021-07-01 11:57
Hi @presto87 thank you for your feature request.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/3713 and we had this issue for a long time on our backlog but got removed because it is not our priority to add right now.
I will close this issue as a duplicate but a pull request is always welcome. Hope you understand.

**Closed by fvrmr** 2021-07-01 11:57 UTC
Labels: Type: New Feature
