### ISSUE TITLE
Cura 2.5beta How to change language? Question

### ISSUE THREAD

**Issue by karabas** [Ultimaker/Cura#1619] opened 2017-03-31 08:04 UTC
Languige setting does not affect anything.
How to change?

**Comment by fieldOfView** [comment] 2017-03-31 08:10
Duplicate of https://github.com/Ultimaker/Cura/issues/1568
There's a bug in the 2.5 beta, which I think has been fixed for the final version.

**Closed** 2017-03-31 08:25 UTC

**Comment by nallath** [comment] 2017-03-31 08:41
It has been fixed. Also note that the beta usually has poor translation due to changes in the strings that have not yet passed the translators.
