### ISSUE TITLE
[4.7.0-B] Is math Possible

### ISSUE THREAD

**Issue by FlailAway** [Ultimaker/Cura#8171] opened 2020-08-10 22:26 UTC
> **Is your feature request related to a problem? Please describe.**

I'd like to use the Marlin look-ahead temp

**Describe the solution you'd like**
Within the Start/End GCode?

`
;  M109 S210 B230 F1  ; autotemp PLA

M109 S{material_print_temperature}    **B{material_print_temperature}  + 20**    F1
OR
M109 S{material_print_temperature}    **B{material_print_temperature + 20}**    F1
`
**Describe alternatives you've considered**
None, too lazy

**Affected users and/or printers**
All/Any probably running Marlin

**Additional context**
Takes too many lines to make the green "Submit" button become active. ;)

**Comment by fieldOfView** [comment] 2020-08-11 10:34
No, it is not possible to use math in the start/end gcode snippets.

**Comment by FlailAway** [comment] 2020-08-11 12:43
Ummm, thanks, I know that. It is a feature request and pretty sure that would exclude existing features.

**Comment by Ghostkeeper** [comment] 2020-08-11 15:25
Duplicate of https://github.com/Ultimaker/Cura/issues/4611.

**Closed by Ghostkeeper** 2020-08-11 15:25 UTC
Labels: Type: New Feature

**Comment by fieldOfView** [comment] 2020-08-11 15:36
> Ummm, thanks, I know that.

Hey, I am sorry; the subject of your issue - while missing a questionmark - sounds like a question. I answered that question.
