### ISSUE TITLE
Narrow horizontal slot shell processing bug

### ISSUE THREAD

**Issue by Dabihu** [Ultimaker/Cura#4317] opened 2018-09-02 14:44 UTC
Cura 3.4.1
windows 10 x64
Marlin

Steps to Reproduce:
If a horizontal slot is in the model, the Shell/ Top/Bottom Thickness could cause empty/infilled layers.
Condition: The slot is less than Top/Bottom Thickness.

The attached sample file has a 0.8 mm height slot:
[Sample.zip](https://github.com/Ultimaker/Cura/files/2343450/Sample.zip)

Layer height: 0.2,  Top/Bottom Thickness: 0.8 mm (slot = thickness: good)
![sample08](https://user-images.githubusercontent.com/17223373/44957158-1a72e200-aecf-11e8-8c35-3a076f07a61b.png)
Layer height: 0.2,  Top/Bottom Thickness: 1.6 mm (slot < thickness: bad)
![sample16](https://user-images.githubusercontent.com/17223373/44957160-28c0fe00-aecf-11e8-8436-d39d5e659734.png)

**Comment by diegopradogesto** [comment] 2018-09-04 07:36
Easily reproducible, sounds like a bug. Thanks for sharing!

**Comment by diegopradogesto** [comment] 2018-09-04 08:50
Devs.: CURA-5689

**Comment by rburema** [comment] 2018-09-13 14:08
Hi @Dabihu,

It turns out that this currently is expected _(default)_ behaviour, but you can change this by unchecking 'Ignore Small Z Gaps' in the settings. Given your model, this'll increase both slicing and printing time only by a very manageable amount. On more complex models though, it can change (especially) slicing time by more than 10%.

The team will discuss whether to flip the default behaviour shortly (since you brought it to our attention again), but otherwise I'll close the issue.

If this persists despite unchecking 'Ignore Small Z Gaps', feel free to reopen.

cheers, Remco.

**Closed** 2018-09-13 14:10 UTC
Labels: Category: Engine, Status: In Progress, Type: Bug

**Comment by Dabihu** [comment] 2018-09-18 20:58
It's working fine. Thank you!
