### ISSUE TITLE
Support for custom gcode per filament type to optimize print quality.

### ISSUE THREAD

**Issue by Andrethetech** [Ultimaker/Cura#12766] opened 2022-07-15 11:43 UTC
### Is your feature request related to a problem?

I use the Klipper firmware and often I need to readjust the pressure advance setting for different filaments. The problem is that Cura does not implement the control for Klipper's pressure advance and there is no way to store this in the filament profile or the print profile.

### Describe the solution you'd like

If i was able to store custom gcode for either the filament or the print profile I could put in the pressure advance I want.
I found that PrusaSlicer has that feature but I am used to Cura and would hate to have to switch get that feature.

### Describe alternatives you've considered

I considered the Coasting feature but it does not interact with the firmware also the linear advance is not implemented in Klipper , it has it's own pressure advance that is similar.

### Affected users and/or printers

All the Klipper firmware users.

**Comment by Ghostkeeper** [comment] 2022-07-15 13:07
Coasting is not a replacement for Linear Advance, indeed. We do have a replacement planned for 5.2 I believe, based on a research project I did around the start of the year.

Did you try the Linear Advance plug-in from the Marketplace? I believe it adds support for Linear Advance.

Ultimaker itself is unlikely to implement support for Linear Advance since their printers don't support it. I will close this as a duplicate of the previous issue that requested it: https://github.com/Ultimaker/Cura/issues/8156

**Closed by Ghostkeeper** 2022-07-15 13:07 UTC
Labels: Type: New Feature
