### ISSUE TITLE
Additional Wall-Inner being generated and overlaps previously printed.

### ISSUE THREAD

**Issue by mzhu1113** [Ultimaker/Cura#8978] opened 2020-12-20 05:21 UTC
**Application version**
4.8, Unknown if this happens in prior versions

**Platform**
Win 10 x64

**Printer**
N/A

**Reproduction steps**
Attached STL, feature that presents the problem. The feature is 3 nozzle widths thick (0.4mm nozzle size).
Only setting that prevents the issue is to tweak the wall width.
[ProblemSTL.zip](https://github.com/Ultimaker/Cura/files/5720576/ProblemSTL.zip)

**Actual results**
2 outer walls, 2 inner overlapping each other.
Generated gcode has an extra Inner Wall overlapping the previously printed one. Causes backup and jam of extruder which in turn either forces a grind or motor stall.

**Expected results**
2 generated outer walls and 1 inner.

**Comment by Ghostkeeper** [comment] 2020-12-23 09:49
Duplicate of https://github.com/Ultimaker/Cura/issues/6401.

**Closed by Ghostkeeper** 2020-12-23 09:49 UTC
Labels: Type: Bug
