### ISSUE TITLE
Marketplace causes hang on MacOS

### ISSUE THREAD

**Issue by jswadley** [Ultimaker/Cura#9967] opened 2021-06-11 12:48 UTC
### Application Version

4.9.1

### Platform

MacOS 11.4

### Printer

Voxelab Aquila

### Reproduction steps

Open the Marketplace.

### Actual results

The entire app hangs for 10-15 seconds and makes the whole app unresponsive.

### Expected results

Marketplace opens instantly like any other part of the app.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Thanks!

**Comment by fvrmr** [comment] 2021-06-11 13:26
Hi @jswadley thank you for your report.
Could you also share your log file? You can find your log file here: `$USER/Library/Application Support/cura/<Cura version>/cura.log`

**Comment by jswadley** [comment] 2021-06-11 13:30
Sure! Sorry, wasn't sure it'd be useful.
[cura.log](https://github.com/Ultimaker/Cura/files/6638735/cura.log)

**Comment by fieldOfView** [comment] 2021-06-11 13:33
Duplicate of https://github.com/Ultimaker/Cura/issues/7071. It is not just MacOS.

**Comment by nallath** [comment] 2021-06-11 15:09
We're planning to do a full refactor of the marketplace soon. The slowness is one of the main reasons for it. So no worries, we expect to fix this soon!

**Closed by nallath** 2021-06-11 15:09 UTC
Labels: Type: Bug
