### ISSUE TITLE
not slicing

### ISSUE THREAD

**Issue by dxmu** [Ultimaker/Cura#14639] opened 2023-02-22 18:12 UTC
### Application Version

5.2.2

### Platform

wimdows 10

### Printer

creality 10 s4

### Reproduction steps

tried to slice a model

### Actual results

cura shows a error message and cant slice the model

### Expected results

cura slices the model

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

v

**Comment by MariMakes** [comment] 2023-02-23 13:19
Hey @dxmu,

Welcome to the Ultimaker Cura Github 🚀 


Is it possible that your printjob is located at 0, 0, 0, and it slices if you move it a little away from the center of the buildplate? 
Then it might be a duplicate of https://github.com/Ultimaker/Cura/issues/13643
The new Cura 5.3 Beta contains the fix for this. 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0-beta.1

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Closed** 2023-03-10 12:06 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage, Slicing Error :collision:
