### ISSUE TITLE
Problems with Z-seam alignment randomness

### ISSUE THREAD

**Issue by viper0078** [Ultimaker/Cura#8498] opened 2020-10-05 11:49 UTC
I'm going to raise this again because the problem has been closed, even though it hasn't been resolved.
See the original post for the details of the process.

I hope that the random setting of the Z-seam alignment will be fixed so that it works well.

_Originally post
https://github.com/Ultimaker/Cura/issues/8464#issuecomment-703528295_

**Comment by Ghostkeeper** [comment] 2020-10-05 13:32
Duplicate of #8464. We'll close this here to encourage keeping discussions together with their context. Feel free to respond to the closed ticket. Sounds to me like you're asking for a feature to actively spread the Z seam around evenly rather than randomly.

**Closed by Ghostkeeper** 2020-10-05 13:32 UTC
