### ISSUE TITLE
Flying Structures then using Tree Support

### ISSUE THREAD

**Issue by Alex031544** [Ultimaker/Cura#8609] opened 2020-10-24 13:27 UTC
**Application version**
4.7.1

**Platform**
- Ubuntu 18.04.5 LTS 64-bit
- AMD® Ryzen 7 2700x eight-core processor × 16
- Radeon RX Vega
- GNOME 3.28.2
- 32 GB RAM

**Printer**
- CR10v2

**Reproduction steps**
1. choosing tree type support
2. trying wall line counts (1-3)

**Screenshot(s)**
[
![Screenshot from 2020-10-24 15-05-48](https://user-images.githubusercontent.com/12674675/97082602-35eb5a80-160b-11eb-834a-436009b25b0d.png)
](url)
The result with a wall line count of 3 for the tree support shows flying structures, which also placed on different, not consecutive layers
![Screenshot from 2020-10-24 15-37-45](https://user-images.githubusercontent.com/12674675/97083433-44884080-1610-11eb-8913-5c7f72f11cc3.png)

**Actual results**
The screenshots show that the algorithm starts to split the base branch into two separated branches. But the structure in the centre is not printable, because the structure is flying and does not have support.

**Expected results**
Then branching the tree all upcoming layers need to be supported by earlier layers. It seems that there is no check within the algorithm. Some bridging structures make sense there. 

**Project file**
[CCR10_housing.zip](https://github.com/Ultimaker/Cura/files/5432934/CCR10_housing.zip)

**Logfile**
not relevant

**Additional information**
none

**Comment by Ghostkeeper** [comment] 2020-10-27 13:05
Duplicate of https://github.com/Ultimaker/Cura/issues/4342

This is caused by tree branches closing in on multiple sides. Because tree support has 0% infill density by default, there is nothing really that catches it, although usually it repairs itself after a few layers.

**Closed by Ghostkeeper** 2020-10-27 13:05 UTC
Labels: Type: Bug
