### ISSUE TITLE
Importing profile successful but profile not visible 

### ISSUE THREAD

**Issue by VapeN3D** [Ultimaker/Cura#8303] opened 2020-09-02 14:59 UTC
**Application version**
4.7

**Platform**
Windows 10, Nvida GTX, 16gb RAM
**Printer**
Ender 2

**Reproduction steps*

**Screenshot(s)**

**Actual results**
No profile visible 

**Expected results**
Profile should be visible and useable 

**Project file**

**Log file**

**Additional information**
(Extra information relevant to the issue.)

**Comment by VapeN3D** [comment] 2020-09-02 14:59
[cura.log](https://github.com/Ultimaker/Cura/files/5163088/cura.log)
![Ninja](https://user-images.githubusercontent.com/56501113/92000351-55fe4c00-ed35-11ea-8598-dcee35c6a349.JPG)

**Comment by VapeN3D** [comment] 2020-09-03 07:35
Rolled back to the previous version of Cura and now I can see the Ninjaflex profile

**Comment by Ghostkeeper** [comment] 2020-09-03 14:58
Duplicate of https://github.com/Ultimaker/Cura/issues/8260 and https://github.com/Ultimaker/Cura/issues/8229 .

We're planning to change the wording of this dialogue if the imported profile is not applicable to the current configuration.

**Closed by Ghostkeeper** 2020-09-03 14:58 UTC
Labels: Type: Bug
