### ISSUE TITLE
Failed to slice after fresh install.

### ISSUE THREAD

**Issue by levikknight** [Ultimaker/Cura#18984] opened 2024-04-29 21:18 UTC
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Ender 3

### Describe your model

Dnd human figure

### Add your .zip here ⬇️

[3e4b47b5b05b4585b05e6a7a0ba476cc.zip](https://github.com/Ultimaker/Cura/files/15155058/3e4b47b5b05b4585b05e6a7a0ba476cc.zip)

**Comment by GregValiant** [comment] 2024-04-29 22:14
There were issues in 5.6.0 that would keep good models from slicing.  A lot of those problems have been fixed in 5.7.0 and 5.7.1.
A problem is that this model is not watertight and looks like it has internal errors.  They would need to be fixed or you may got odd results in the print.
Install 5.7.1 and see if the problem is resolved.
I'll mark this as a duplicate report involving 5.6.0 and I'll go ahead and close this report.

The model sliced for me in 5.7.1.  MS 3D Builder didn't have any trouble repairing it.
![image](https://github.com/Ultimaker/Cura/assets/64202104/9a576a77-c6dc-4413-9410-776a1bd872a6)

**Closed by GregValiant** 2024-04-29 22:14 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error :collision:
