### ISSUE TITLE
3.1beta can't change support overhang angle and some other values

### ISSUE THREAD

**Issue by caoxiangfish** [Ultimaker/Cura#2862] opened 2017-11-27 15:27 UTC
I install the 3.1beta.
Iin the support settings, I want to change overhang angle, but the value is always 45°.
And support density...distance...and some other values can't change too.

**Comment by caoxiangfish** [comment] 2017-11-27 15:34
i have install both 3.04 and 3.1beta

**Comment by ChrisTerBeke** [comment] 2017-11-27 16:06
Duplicate of https://github.com/Ultimaker/Cura/issues/2846. Fixed for 3.1 stable release.

**Closed by ChrisTerBeke** 2017-11-27 16:06 UTC
