### ISSUE TITLE
REstore backup not working

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#10037] opened 2021-06-26 16:19 UTC
### Application Version

4.10 beta

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

1.  Create backup in 4.8
2. Open 4.10 beta and restore backup

### Actual results

Cura is restored to defaults and gives you the welcome screen again, making you add your first printer etc.

### Expected results

The printers which I had added in 4.8 should be present along with all the saved profiles etc.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/6720366/cura.log)

Let me know what to include for recreating the backup file if you cannot reproduce this.

I've tried this because [some user said he couldn't get backups to work](https://www.reddit.com/r/3Dprinting/comments/o87nxp/best_slicing_software_for_someone_that_comes_from/h33kafk?utm_source=share&utm_medium=web2x&context=3), so the problem might be bigger than this one incident.  

(This was done on my home PC.)

**Comment by fvrmr** [comment] 2021-06-28 09:21
Hi @BagelOrb thank you for your bug report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9905 that's why I will close this issue as a duplicate.

**Closed by fvrmr** 2021-06-28 09:21 UTC
Labels: Type: Bug
