### ISSUE TITLE
When saving a .gcode file the name no longer pre-populates with the job name

### ISSUE THREAD

**Issue by TangoDeltaDelta** [Ultimaker/Cura#13639] opened 2022-10-24 15:09 UTC
### Application Version

5.2.1

### Platform

Linux (not modern)

### Printer

Creality Ender 3

### Reproduction steps

1. Import a model - e.g. "TestPrint.stl"
2. Note the job name populates with "CE3_TestPrint"
3. After previewing, click "Save to Disk"

### Actual results

Note that the file save dialog file name area is empty. 

### Expected results

Previously it would populate with the job name + ".gcode"
e.g. "CE3_TestPrint.gcode" would be pre-loaded into the file name save dialog.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This I think actually started with the 5.0.0 versions

**Comment by MariMakes** [comment] 2022-10-25 08:33
Hey @TangoDeltaDelta,

Thanks for your report 👍 
I'm having some trouble recreating on my side.

Could it be that you unchecked this setting in your preferences by accident?
![image](https://user-images.githubusercontent.com/40423138/197724313-1826c4f8-9e6d-4821-9668-a20f5500a65e.png)

Or did you recently install the [Printjob Naming Plugin](https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/CustomJobPrefix) and altered your preferences there?

**Comment by fieldOfView** [comment] 2022-10-25 08:58
This is a duplicate of https://github.com/Ultimaker/Cura/issues/12659, see my comment here:
https://github.com/Ultimaker/Cura/issues/12659#issuecomment-1173046597

**Closed by fieldOfView** 2022-10-25 08:58 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage

**Comment by MariMakes** [comment] 2023-03-31 09:21
Quick update on our side. 

We might have a fix for this issue. 🎉 
It's a bit hard for us to test, but we have a nightly build available. 
Can you please try it out and let us know if it resolves your issue? 

[You can find the download links and the discussion here. ](https://github.com/Ultimaker/Cura/discussions/15098)
