### ISSUE TITLE
4.11 Support for nothing and support blockers not working

### ISSUE THREAD

**Issue by Raiden38** [Ultimaker/Cura#10511] opened 2021-09-24 16:16 UTC
### Application Version

4.11

### Platform

Windows 10

### Printer

Anet A8

### Reproduction steps

Added support, added support blockers. Tested on MAC and PC.

### Actual results

Some support are supporting nothing (there is no part over the support, it's just a tower of plastic with nothing on it. 
Support blocker show in gray, but they don't block anything in preview mode and in print.

### Expected results

Supports only when there is part to be supported
Supports removed when support blocker is active.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Capture](https://user-images.githubusercontent.com/6731214/134707766-fe1bb548-52c3-4c38-bfca-9ddbfcf585aa.PNG)
![Capture2](https://user-images.githubusercontent.com/6731214/134707768-3750ad7a-b6ef-4b70-ae28-2022f320bede.PNG)
![Capture3](https://user-images.githubusercontent.com/6731214/134707770-8876aefc-51d3-4176-812a-96c3ec232c00.PNG)
![Capture4](https://user-images.githubusercontent.com/6731214/134707772-0f7ece69-0fcc-4017-a7b8-74e9fe3b4049.PNG)
![Capture5](https://user-images.githubusercontent.com/6731214/134707775-5f360c40-15ed-467f-bf24-ee4aa5586bc9.PNG)
[Apple_TV_Mount.zip](https://github.com/Ultimaker/Cura/files/7227139/Apple_TV_Mount.zip)

**Comment by Asterchades** [comment] 2021-09-26 02:57
Try turning off the Use Towers option under Support. I've found it likes to generate little, superfluous towers when there's narrow objects which may (or may not) need support.

Support Blockers are to be used on where the supports are being generated _to_, not from. There's an area further up the model which the supports believe they're attaching to which is why they're still being generated.

**Comment by Ghostkeeper** [comment] 2021-10-01 12:02
Duplicate of https://github.com/Ultimaker/Cura/issues/7487.

**Closed by Ghostkeeper** 2021-10-01 12:02 UTC
Labels: Type: Bug
