### ISSUE TITLE
Per Model Setting modifying Z seam alignment for overlaps triggers solid top and bottom

### ISSUE THREAD

**Issue by tokamac** [Ultimaker/Cura#10908] opened 2021-11-23 11:45 UTC
### Application Version

4.12.1

### Platform

macOS 12.0.1

### Printer

Prusa i3 MK3S

### Reproduction steps

Hollow model set to 0% infill, 3 perimeters. 
Z Seam Alignment: Shortest.

When "Per Model Settings" is used with a modifier "Modify Settings for overlaps" on some part of the model, with the only settings : "Cutting Mesh" and "Z Seam Alignment: Sharpest Corner"

### Actual results

Then the top and bottom section of the modifier print a solid horizontal top and bottom interface within the model.
And adding the modifier settings "Top Surface Skin Layers" to 0 and "Top/Bottom Thickness" to 0.0 mm do not change it at all, the horizontal top and bottom solids stay there real and thick for both.

### Expected results

The infill density or top+bottom thickness should not be modified from the general settings nor even be triggered when a modifier only modifies another unrelated setting on some part of the model, here the Z Seam Alignment.
Plus, the top/bottom interface density should correctly disappear to 0 when specified so for the modifier, instead of staying there with a certain thickness.

### Additional information & file uploads

No need to upload any log file or model as the bug speaks for itself and is easily replicable.

**Comment by fvrmr** [comment] 2021-11-23 12:43
Hi @tokamac thank you for your report.
With your reproduction steps I am not able to reproduce your issue.
![Screenshot (305)](https://user-images.githubusercontent.com/77000924/143025982-6dd4e73f-87f5-4927-9fa0-a2f4a74bc9c7.png)


Could you share a project file (file - save project)?

**Comment by tokamac** [comment] 2021-11-23 14:22
You can't reproduce the issue if you specify that you do not want any Top & Bottom shell for the whole model, and that's what you did in the main print settings highlighted in orange a the upper right corner of your screenshot.
Plus, I see your modifier created new perimeters inside your cube, which is also abnormal. Why are these additional internal walls there? They should not be. 

I want my model to have a top and bottom shells, so these should be set in the main print settings, e.g. Top/Bottom Thickness = 0.8 mm. No internal additional walls neither. Just an outer shell, with 3-perimeter walls, top and bottom shell. Nothing else inside. 
Now, when one adds a modifier to such a model, it creates another top & bottom shells WITHIN the structure of the hollow model, which is not normal, see my screenshot below.

<img width="1297" alt="pyramid" src="https://user-images.githubusercontent.com/3685009/143041037-370b9515-1966-453f-9d74-43e5045820e4.png">

**Comment by tokamac** [comment] 2021-11-23 14:57
I eventually managed to get rid of the additional internal Top/Bottom shells at the interface of the modifier, adding all these settings to the modifier, see newest screenshot below.

<img width="1297" alt="pyramid2" src="https://user-images.githubusercontent.com/3685009/143047318-510cab15-bda9-41db-8d23-d32efe3afedb.png">

But in the end, the Z-seam alignment modifier doesn't work at all anymore. It is still "shortest" really, and not "Sharpest corner".

I know it because I have a "scar" appearing on another very specific hollow model of mine which appears only when I choose "shorter" for the Z-seam alignement. I cannot use another Z-seam alignment setting on that whole specific model, because those settings create another artefact, some bad under-extrusions due to much longer travel moves, so I must keep "shorter" (or "random" which creates bits on whole surface that I don't want either). 

Plus, it is easily observable unsticking the Shell box for Line Type: the travels are unaffected by the modifier.

Initially I had the idea to modify the Z-seam alignment to "sharpest corner" only in the area where the scar appears on the complicated model (using "shortest" otherwise everywhere else) in order to offset the seam and force it to be stitched along the edge of the model, and not on its face.

**Comment by tokamac** [comment] 2021-11-23 15:12
Below I show how such modifier does not work at all. The big modifier encompasses the upper half of the model.

First, look at the travel paths for the model where the seam is put on the sharpest corner, and the modifier is the same also. Clean paths:
<img width="1509" alt="pyramid-sharpest-corner" src="https://user-images.githubusercontent.com/3685009/143049727-304a4383-6918-4371-8c9a-c3187650de41.png">
Now, look at the travel moves for the same model when the seam is put at Random alignments, but the modifier asks for that seam to be at the sharpest corner for the upper part of the model: The modifier does nothing! The travel paths and the seam keeps being random.
<img width="1509" alt="pyramid-random" src="https://user-images.githubusercontent.com/3685009/143050005-5019ef8c-51ca-42a3-b186-d2f12fc2b25c.png">
!

**Comment by smartavionics** [comment] 2021-11-23 21:29
> Alas no, GitHub does not allow to attach 3MF files to bug reports and messages. That's ridiculous BTW!

ZIp it up or rename the .3mf to .zip

**Comment by tokamac** [comment] 2021-11-23 21:32
Of course! Here it is (zipped)
[pyramid.zip](https://github.com/Ultimaker/Cura/files/7591139/pyramid.zip)

**Comment by Ghostkeeper** [comment] 2021-12-02 11:09
This is expected behaviour. Not really desired in your case, but expected because the cutting model indeed cuts the model into separate pieces, each of which get separate walls and skin. You're not bothered by the separate walls here (because your model is cut horizontally only) but you are bothered by the separate skin here. The Top Layers and Bottom Layers settings are set to 4 here, so it'll add 4 layers at the top of where the model is cut, and 4 layers at the bottom of the cutting mesh, resulting in 8 layers of boundary. Then a centimetre higher, it'll add another 4 layers at the top of the cutting mesh and 4 layers at where the piece of the real pyramid starts again.

It can be prevented by adding another cutting mesh to change the top/bottom layers for the bottom side of the top of the pyramid, and setting the Top/Bottom Layers to 0 for the cutting mesh. In your case you can even set the Top Layers to 0 because the pyramid should never get any top layers. Here is an example: [pyramid_no_topbottom.zip](https://github.com/Ultimaker/Cura/files/7641360/pyramid_no_topbottom.zip)

I'd say that this is a duplicate of this feature request then, which requests looking at where cutting meshes cut away from the mesh and preventing skin from being generated there: https://github.com/Ultimaker/Cura/issues/9218

**Closed by Ghostkeeper** 2021-12-02 11:09 UTC
Labels: Type: Bug
