### ISSUE TITLE
Archlinux - could not probe OpenGL

### ISSUE THREAD

**Issue by mantielero** [Ultimaker/Cura#12538] opened 2022-06-16 09:03 UTC
### Application Version

5.0.0

### Platform

ArchLinux

### Printer

Creality Ender-3 V2 

### Reproduction steps

It just fails to start

### Actual results

I get a pop-up message:
```
Failed to probe OpenGL

Could not probe OpenGL. This program requires OpenGL 2.0 or higher. Please check your video card drivers.
```

In the command line, it appears:
```
PyInstaller/loader/pyimod03_importers.py:495: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
libGL error: MESA-LOADER: failed to open radeonsi: /tmp/.mount_UltimakZZgXQ/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/dri/radeonsi_dri.so) (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi: /tmp/.mount_UltimakZZgXQ/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/dri/radeonsi_dri.so) (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /tmp/.mount_UltimakZZgXQ/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/dri/swrast_dri.so) (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
```

### Expected results

I would expect the application to start.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

```
$ lspci -k | grep -A 2 -E "(VGA|3D)" 
lspci: Unable to load libkmod resources: error -2
01:00.0 VGA compatible controller: NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] (rev a1)
	Subsystem: Lenovo Device 3a81
	Kernel driver in use: nvidia
--
05:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne (rev c5)
	Subsystem: Lenovo Device 3a81
	Kernel driver in use: amdgpu
$ glxinfo | grep AMD   
    Vendor: AMD (0x1002)
    Device: AMD RENOIR (LLVM 13.0.1, DRM 3.42, 5.15.47-1-lts) (0x1638)
OpenGL vendor string: AMD
OpenGL renderer string: AMD RENOIR (LLVM 13.0.1, DRM 3.42, 5.15.47-1-lts)
    GL_AMD_conservative_depth, GL_AMD_depth_clamp_separate, 
    GL_AMD_draw_buffers_blend, GL_AMD_framebuffer_multisample_advanced, 
    GL_AMD_gpu_shader_int64, GL_AMD_multi_draw_indirect, 
    GL_AMD_performance_monitor, GL_AMD_pinned_memory, 
    GL_AMD_query_buffer_object, GL_AMD_seamless_cubemap_per_texture, 
    GL_AMD_shader_stencil_export, GL_AMD_shader_trinary_minmax, 
    GL_AMD_texture_texture4, GL_AMD_vertex_shader_layer, 
    GL_AMD_vertex_shader_viewport_index, GL_ANGLE_texture_compression_dxt3, 
    GL_AMD_conservative_depth, GL_AMD_depth_clamp_separate, 
    GL_AMD_draw_buffers_blend, GL_AMD_framebuffer_multisample_advanced, 
    GL_AMD_multi_draw_indirect, GL_AMD_performance_monitor, 
    GL_AMD_pinned_memory, GL_AMD_query_buffer_object, 
    GL_AMD_seamless_cubemap_per_texture, GL_AMD_shader_stencil_export, 
    GL_AMD_shader_trinary_minmax, GL_AMD_texture_texture4, 
    GL_AMD_vertex_shader_layer, GL_AMD_vertex_shader_viewport_index, 
    GL_AMD_framebuffer_multisample_advanced, GL_AMD_performance_monitor, 

```

**Comment by nallath** [comment] 2022-06-16 09:36
Duplicate of #11856

**Closed as completed by nallath** 2022-06-16 09:36 UTC
Labels: Type: Bug, Status: Duplicate
