### ISSUE TITLE
issue when starting cura

### ISSUE THREAD

**Issue by jakel89** [Ultimaker/Cura#428] opened 2015-09-24 22:11 UTC
The program stop and display the following text

Version: 15.06.03
Platform: Windows-7-6.1.7601-SP1
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "cura_app.py", line 9, in <module>
  File "c:\dev\uranium\UM\Application.py", line 329, in getInstance
  File "c:\dev\cura\cura\CuraApplication.py", line 56, in __init__
  File "c:\dev\uranium\UM\Qt\QtApplication.py", line 48, in __init__
  File "c:\dev\uranium\UM\Application.py", line 67, in __init__
  File "c:\dev\uranium\UM\Preferences.py", line 56, in readFromFile
  File "c:\dev\uranium\UM\Preferences.py", line 122, in _loadFile
  File "c:\dev\python34\lib\configparser.py", line 672, in read
  File "c:\dev\python34\lib\configparser.py", line 1088, in _read
configparser.ParsingError: Source contains parsing errors: 'C:\\Users\\JE/AppData/Local/cura\\cura.cfg'
	[line 16]: 'material;platform_adhesion;resolution;speed;support\n'

**Comment by Ghostkeeper** [comment] 2015-09-24 22:21
Probably a duplicate of #346, which was caused by writing to the config file with Python while the program was exiting/crashing and by having multiple instances of Cura write to that config file at the same time.

This is fixed in version 15.10, which is currently in beta (though the fix is still causing some other trouble). But for now, your fix is to delete that file (cura.cfg). It is corrupt. Cura will recreate it, but your configuration settings will be lost.

**Closed** 2015-09-24 22:22 UTC
Labels: bug
