### ISSUE TITLE
Tree Supports not supporting small overhanging part

### ISSUE THREAD

**Issue by KenLucke** [Ultimaker/Cura#8843] opened 2020-11-27 22:23 UTC
**Application version**
4.62 through 4.8 (did not check earlier versions)

**Platform**
Mac OSX 15.5.7

**Printer**
N/A

**Reproduction steps**

1. Load a file with portion that needs support hanging in midair.
2. Slice using Standard supports - part is supported.
3. Reslice using Tree supports - part is not supported (I used several profiles to experiment, and tried changing virtually every setting pertaining to supports [including angles from 1° to 89°], with no change in result)

**Screenshot(s)**
Below  is a cross section of the model,  showing the "hanging" part, and resulting slices with Regular and Tree supports, showing the center is not supported when Tree supports  are enabled.

![Niger Thistle Sock Feeder (Single) Cover - Ultimaker Cura 2020-11-27 10-12-44](https://user-images.githubusercontent.com/57936294/100487073-b6debb80-30bb-11eb-94b0-28e4b94a9273.jpg)

**Actual results**
Center "midair" part has no support

**Expected results**
part should be supported

**Project file**

https://www.dropbox.com/s/a6a9jmt5raw5j6j/Niger%20Thistle%20Sock%20Feeder%20%28Single%29%20Base.3mf

**Log file**

**Additional information**
(Extra information relevant to the issue.)

**Comment by Asterchades** [comment] 2020-11-28 05:32
Judging by the colours in your screenshots, you're using a Support Interface. There's known interaction issues between Interfaces and Tree Supports at present, meaning you'll likely see better results without the Interface.

**Comment by KenLucke** [comment] 2020-11-28 07:57
> Judging by the colours in your screenshots, you're using a Support Interface. There's known interaction issues between Interfaces and Tree Supports at present, meaning you'll likely see better results without the Interface.

I believe I mentioned that I changed virtually every setting in an attempt to solve this.  That includes using/not using a support interface.

**Comment by Ghostkeeper** [comment] 2020-12-01 09:38
The project file you provided seems to be a different model? It has no such small overhanging area.
![image](https://user-images.githubusercontent.com/2448634/100722483-f3aef900-33c0-11eb-8ef7-ff8225b674e5.png)

Flipping the model upside-down sort of produces a little ring like you describe, but tree support seems to support that ring fine:
![image](https://user-images.githubusercontent.com/2448634/100722769-412b6600-33c1-11eb-81aa-9c0d262b137c.png)

Could you share a project file that reproduces the problem?

**Comment by KenLucke** [comment] 2020-12-01 17:30
Oop, sorry.  I have the base and the cover for this niger seed bird feeder.  I shared the base accidentally.  Here's the cover:

https://www.dropbox.com/s/wro8nf5xuu3jpyu/Niger%20Thistle%20Sock%20Feeder%20%28Single%29%20Cover.3mf

**Comment by KenLucke** [comment] 2020-12-01 17:47
Here's another, similar one (this is for a larger, triple sock version of the feeder).  Does the same thing.

https://www.dropbox.com/s/e3638ejaeq40ml0/Niger%20Thistle%20Sock%20Feeder%20Cover.3mf

**Comment by Ghostkeeper** [comment] 2020-12-03 11:28
Yeah, with that project file the problem reproduces (I tried the first of the two anyway). I don't know what the difference is why this problem occurs with that model but not with the upside-down version of the previous model. But it does. I tried to change the settings that could influence this (just like you) but it never seems to want to support that little ring for some reason.

**Comment by KenLucke** [comment] 2020-12-03 11:34
> Yeah, with that project file the problem reproduces (I tried the first of the two anyway). I don't know what the difference is why this problem occurs with that model but not with the upside-down version of the previous model. But it does. I tried to change the settings that could influence this (just like you) but it never seems to want to support that little ring for some reason.

Glad it wasn't just me :).

**Comment by Ghostkeeper** [comment] 2020-12-07 10:20
(Developers, refer to CURA-7913.)

**Comment by MariMakes** [comment] 2023-05-16 12:15
Hey all,

Quick update from our side. 
To be able to focus on the most requested and needed features and bug fixes from our community and from Ultimaker, we are cleaning up our open issues. I stumbled upon your issue with tree supports and I can confirm that will this will be resolved in the next release. 

We are introducing new tree support, and your floating island seems to be fixed. 
![image](https://github.com/Ultimaker/Cura/assets/40423138/9e5d2083-1911-4782-84a6-7d73858e943c)

To me, it doesn't seem like a bug in Ultimaker Cura, since we have a solution in place. 
Apologies for any inconvenience caused by our delayed response. 
I'll be closing this issue. I hope you understand.

**Closed by MariMakes** 2023-05-16 12:15 UTC
Labels: Type: Bug
