### ISSUE TITLE
slicing does not work

### ISSUE THREAD

**Issue by timlitw** [Ultimaker/Cura#10982] opened 2021-12-01 21:08 UTC
### Application Version

4.12.1

### Platform

Windows 10

### Printer

Snapmaker 2 A250

### Reproduction steps

added several (5) small bell files to build plate
click slice now

### Actual results

it changes to slicing
no progress bar
an hour later it is still the same

### Expected results

slicing finishes snapmaker luban takes about 15 seconds
then I can review and either send to a printer or to USB drive to carry to printer

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

this is where it fails
```
2021-12-01 13:58:26,605 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._onStartSliceCompleted [510]: Sending slice message took 1.8052833080291748 seconds
2021-12-01 13:58:27,445 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] [libprotobuf ERROR C:\build\env\master-20211117\build\Protobuf-MinGW-prefix\src\Protobuf-MinGW\src\google\protobuf\io\coded_stream.cc:193] A protocol message was rejected because it was too big (more than 524288000 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in third_party/protobuf/src/google/protobuf/io/coded_stream.h.
2021-12-01 13:58:27,445 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] [ERROR] Failed to parse message:
2021-12-01 13:58:27,445 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] ï¹¡ß
2021-12-01 13:58:27,445 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] ¥ FÀÆ¦Xè¤ F°I³À
```

**Comment by timlitw** [comment] 2021-12-01 21:09
[cura.log](https://github.com/Ultimaker/Cura/files/7637094/cura.log)

**Comment by timlitw** [comment] 2021-12-01 21:12
![still normal](https://user-images.githubusercontent.com/11441935/144314730-e8621338-a3f1-4609-a2cd-09930942a168.jpg)
![stays here for hours - ie never finishes](https://user-images.githubusercontent.com/11441935/144314734-1d9abeaf-2218-45db-90ba-e7376874d83b.jpg)

**Comment by fvrmr** [comment] 2021-12-02 09:21
Hi @timlitw thank you for your bug report.
Could you also share your project file?

**Comment by timlitw** [comment] 2021-12-02 15:04
trying a link instead

I've linked 1 file to this email:
S2A_name-bells.zip 
<https://www.dropbox.com/s/y7098cr0mi29j4o/S2A_name-bells.zip?dl=0>(167 
MB)Dropbox 
<https://www.dropbox.com/>https://www.dropbox.com/s/y7098cr0mi29j4o/S2A_name-bells.zip?dl=0

**Comment by timlitw** [comment] 2021-12-02 16:31
I have been doing some testing.
If I only add 3 of the bell models to the build plate cura will slice.  But it fails when I add the 4th.

**Comment by timlitw** [comment] 2021-12-02 16:37
I followed the instructions here https://support.ultimaker.com/hc/en-us/articles/360013007080-How-can-I-completely-reset-my-Ultimaker-Cura-installation-
for a complete reset, removed all plugins etc. 
I still can not add more than 3 models to the build plate.

**Comment by fvrmr** [comment] 2021-12-07 13:09
Hi @timlitw your project file does not contain your models. I tried slicing a simple cube and that works with your project. Could you share again a project file with 4 models that will cause your issue?

**Comment by timlitw** [comment] 2021-12-07 14:55
I've linked 6 files to this email:
andres.stl 
<https://www.dropbox.com/s/mjqw93rbbuslwta/andres.stl?dl=0>(195 
MB)Dropbox 
<https://www.dropbox.com/>https://www.dropbox.com/s/mjqw93rbbuslwta/andres.stl?dl=0
alex.stl <https://www.dropbox.com/s/es0tqfmgmi2qk72/alex.stl?dl=0>(195 
MB)Dropbox 
<https://www.dropbox.com/>https://www.dropbox.com/s/es0tqfmgmi2qk72/alex.stl?dl=0
audrey.stl 
<https://www.dropbox.com/s/fsooi6nw5jvrt3c/audrey.stl?dl=0>(195 
MB)Dropbox 
<https://www.dropbox.com/>https://www.dropbox.com/s/fsooi6nw5jvrt3c/audrey.stl?dl=0
S2A_bells.3mf 
<https://www.dropbox.com/s/tahu0c53z7m187k/S2A_bells.3mf?dl=0>(220 
MB)Dropbox 
<https://www.dropbox.com/>https://www.dropbox.com/s/tahu0c53z7m187k/S2A_bells.3mf?dl=0
bonnie.stl 
<https://www.dropbox.com/s/98ob6ayamkw1dvp/bonnie.stl?dl=0>(195 
MB)Dropbox 
<https://www.dropbox.com/>https://www.dropbox.com/s/98ob6ayamkw1dvp/bonnie.stl?dl=0
barb.stl <https://www.dropbox.com/s/icoljzefipf2ccq/barb.stl?dl=0>(195 
MB)Dropbox 
<https://www.dropbox.com/>https://www.dropbox.com/s/icoljzefipf2ccq/barb.stl?dl=0

**Comment by Ghostkeeper** [comment] 2021-12-13 13:19
It looks like this is a duplicate of https://github.com/Ultimaker/Cura/issues/3105 .

The bells, when compressed, are not 500MB yet but their expanded vertex and face data is.

A solution from our side would be to break up the slice command message in multiple pieces of at most 500MB.

A workaround for now is to reduce the resolution of the mesh. Cura will typically reduce the resolution down to the Maximum Resolution and Maximum Deviation settings anyway, because the printer's CPU is not able to keep up with too many tiny g-code commands.

**Closed** 2021-12-13 13:19 UTC
Labels: Type: Bug
