### ISSUE TITLE
Cura 2.5 no name when opening STL from Windows Explorer

### ISSUE THREAD

**Issue by GerryH6** [Ultimaker/Cura#1814] opened 2017-05-11 01:50 UTC
If you open an STL file from Windows Explorer, it doesn't automatically pick up the name of the file.  Which if you don't catch it causes you to save the gcode file with an empty file name.

Opening the STL file inside Cura works as expected.

**Comment by fieldOfView** [comment] 2017-05-11 06:42
Duplicate of https://github.com/Ultimaker/Cura/issues/1703, fixed for Cura 2.6

**Closed** 2017-05-11 09:11 UTC

**Comment by Wisnaeme** [comment] 2017-05-14 09:21
I've had this since updating to 2.5.0.
Quite annoying as I need to rename every export.
