### ISSUE TITLE
File naming not updating when opening multiple files from Explorer

### ISSUE THREAD

**Issue by dmitche3** [Ultimaker/Cura#9654] opened 2021-04-22 14:41 UTC
### Application Version

4.8-4.9

### Platform

Windows 10

### Printer

Creality 3 V2

### Reproduction steps

I open a lot of files through out the day.  After opening several I find that the title or file name is not changing to show the proper file. This is a major PITA when saving G-Codes as they are all over-written the one file.
This happens quite frequently.

### Actual results

as mentioned above

### Expected results

When loading a file the name of the file should remove the old name and replace it with the proper name.

**Comment by fvrmr** [comment] 2021-04-22 14:53
Hi @dmitche3 thank you for your bug report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9189
As I explained there we won't fix this as this is not the expected behaviour. 
Hope you understand.

**Closed** 2021-04-22 14:54 UTC
Labels: Status: Duplicate, Type: Bug
