### ISSUE TITLE
[4.1.0] "Print as support" does nothing

### ISSUE THREAD

**Issue by Kuchenmampf** [Ultimaker/Cura#5899] opened 2019-06-14 18:28 UTC
Precondition:
- A model was loaded into cura version 4.1.0

Action:
- Select model
- Add a support blocker
- Select "Per model settings" and change the mesh type of the blocker cube mesh to "print as support"
- Press "Slice" button

Expected:
- The blocker model is printed as support -> a cube shaped support structure is visible at the position of the support blocker model

Result:
- There is no effect. Nothing happens to the blocker mesh

![P1](https://user-images.githubusercontent.com/51834176/59530073-fc68f200-8ee2-11e9-819b-8b9d727242be.jpg)
![P2](https://user-images.githubusercontent.com/51834176/59530077-fffc7900-8ee2-11e9-98d5-b9d52b55c929.jpg)

**Comment by smartavionics** [comment] 2019-06-14 19:29
This is a known regression, I believe.

**Comment by ultradyran** [comment] 2019-06-14 19:30
experiencing same here

**Comment by Ghostkeeper** [comment] 2019-06-17 10:37
Duplicate of https://github.com/Ultimaker/Cura/issues/5813.

**Closed by Ghostkeeper** 2019-06-17 10:37 UTC
Labels: Type: Bug
