### ISSUE TITLE
Crash on pressing scale in Linux appimage

### ISSUE THREAD

**Issue by Ken-2018** [Ultimaker/Cura#9830] opened 2021-05-14 16:04 UTC
### Application Version

4.9.1

### Platform

linux 4.9.1 appimage / Feren OS

### Printer

Creality CR-10

### Reproduction steps

Trying to resize a 3d file by scale causes Cura to crash hard. I tried it 20 times go to scale the 3mf formatted file and the application closes.

### Actual results

It closes dropping your window crashes hard.

### Expected results

Restart saying an error was detected?

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none

**Comment by smartavionics** [comment] 2021-05-14 16:24
See #9709.

**Comment by fvrmr** [comment] 2021-05-17 06:58
I am closing this issue because it is a duplicate of #9709

**Closed by fvrmr** 2021-05-17 06:58 UTC
Labels: Type: Bug
