### ISSUE TITLE
Cura 5.0.0-beta+1  High CPU load at idle

### ISSUE THREAD

**Issue by Anathema-Device** [Ultimaker/Cura#12003] opened 2022-04-28 01:00 UTC
### Application Version

5.0.0-beta+1

### Platform

Windows 10

### Printer

Generic

### Reproduction steps

Start Cura 5
Open a slice a simple model (.stl)
Save the gcode file
Leave Cura 5 running 

### Actual results

The CPU demand by Cura is very high on a Windows 10 machine with i7 and 16GB of memory
![Uploading Cura5-highCPU.PNG…]()

### Expected results

The CPU demand by Cura when there is nothing happening should be close to zero, there is no reason for it to be drawing enough to cause the cooling fan on the computer to be running.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no additional information

**Comment by Yuccax** [comment] 2022-04-29 06:53
I have similar problem when IDLE 
![image](https://user-images.githubusercontent.com/92692027/165896669-9ac7f891-754c-486c-b951-8be811f87746.png)
issue is bit different when window is minimized by a button
![image](https://user-images.githubusercontent.com/92692027/165897382-39f42a13-cdd4-4eab-ab06-4b604644d057.png)
most of load goes to CPU

**Comment by SkyBeam** [comment] 2022-04-29 07:52
I mainly noticed the same for GPU. My GPU does not downclock in Cura 5.0.0-beta+1 when the window is just open and idling. In Cura 4.13 both GPU and CPU were idle when not doing anything.

I suspect there is some kind of loop re-drawing the window contents also when there is no update to be done.

I noticed the load is dropped to 0 when minimizing the Cura window. So I really suspect Cura 5 is just not properly stopping the update loop when the window is in foreground.

**Comment by fvrmr** [comment] 2022-05-02 14:50
Hi @Anathema-Device thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11975, so I will close this issue.

**Closed by fvrmr** 2022-05-02 14:50 UTC
Labels: Type: Bug
