### ISSUE TITLE
[3.3.1] Project Summary Box Problem

### ISSUE THREAD

**Issue by fatalelieberi** [Ultimaker/Cura#3835] opened 2018-05-19 02:43 UTC
**Application Version**
3.3.1

**Platform**
Windows 10

**Printer**
Tevo Tornado - Custom FDM
[MyPrinter.curaproject.zip](https://github.com/Ultimaker/Cura/files/2019056/MyPrinter.curaproject.zip)

**Steps to Reproduce**
1. Open menu File -> Save Project

**Actual Results**
Unclear writings inside the Project Summary
![summary of cura project](https://user-images.githubusercontent.com/19477587/40264213-ff179e80-5b48-11e8-87a3-cd022f1038e4.png)

**Comment by ianpaschal** [comment] 2018-05-22 08:28
Indeed. No doubt this is caused by the dialog having a fixed size dialog which can't fit 8 extruders. Simple fix is putting the summary in a small scroll area.

**Comment by ianpaschal** [comment] 2018-05-22 11:42
Internal ticket created, devs see CURA-5385.

**Comment by ianpaschal** [comment] 2018-05-28 06:47
We've fixed this; will be in 3.4 released in June.

**Closed by ianpaschal** 2018-05-28 06:47 UTC
Labels: Category: Cura, Status: Fixed/Solved, Type: Bug
