### ISSUE TITLE
Cura 15.06.02 Crash in Windows 8.1

### ISSUE THREAD

**Issue by milkok** [Ultimaker/Cura#148] opened 2015-07-16 09:36 UTC
Run Cura 15.06.02 first time,I have to add printer.Whether I choose any one of the options, click "Next", the software will stop working. If I click "Cancle",it won't stop.

**Comment by awhiemstra** [comment] 2015-07-16 09:43
Does it also crash when you choose the Ultimaker Original? If it does not, it might be the same bug as #96

**Comment by Ghostkeeper** [comment] 2015-07-17 23:12
I just tried this and couldn't reproduce it. I also use Windows 8.1.

I had an install of 15.06.01 already, so I went to AppData and deleted Cura's settings. Then I installed 15.06.02 and at startup it asked me if I wanted to add printers. I chose Ultimaker 2 and successfully added a printer.
So apparently, it doesn't always occur or doesn't occur on all Windows 8.1 machines.

**Comment by milkok** [comment] 2015-07-18 00:20
I found it ! There's something wrong in the json files. The "platform_texture" doesn't work.

**Comment by awhiemstra** [comment] 2015-07-22 10:13
That suggests it is indeed the same issue as #96, so closing this as duplicate.

**Closed by awhiemstra** 2015-07-22 10:13 UTC
Labels: duplicate
