### ISSUE TITLE
Start up bug 

### ISSUE THREAD

**Issue by BlackCatControlSystems** [Ultimaker/Cura#13463] opened 2022-10-03 22:21 UTC
### Application Version

5.1.0

### Platform

Win 11

### Printer

None. prior to start

### Reproduction steps

On open

### Actual results

Traceback (most recent call last):
  File "cura_app.py", line 94, in <module>
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\mike\\AppData\\Roaming\\cura\\stderr.log'

### Expected results

no idea

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no file available

**Comment by MariMakes** [comment] 2022-10-04 09:23
This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13422
We have our developers working hard on a solution. 
Apologies for any inconvenience 😞 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/13422

**Closed by MariMakes** 2022-10-04 09:23 UTC
Labels: Type: Bug, Status: Triage
