### ISSUE TITLE
Slicer fails with apparently sound model.

### ISSUE THREAD

**Issue by sgparry** [Ultimaker/Cura#16821] opened 2023-09-25 22:17 UTC
### Cura Version

5.4.0

### Operating System

Ubuntu 22.04 (KDE Neon)

### Printer

Vertex Delta K8800

### Name abnormal settings

Fails with standard High profile.

### Describe model location

Managed to get a slice just once by combining several moves and rotations and fixes. Could not reproduce.

### Describe your model

Mesh check says it is watertight; tried mesh fix - no change

### Add your .zip here ⬇️

[VDK_Bohrschablone.3mf.gz](https://github.com/Ultimaker/Cura/files/12719705/VDK_Bohrschablone.3mf.gz)
mmm

**Comment by GregValiant** [comment] 2023-09-26 10:47
Thanks for the report.
The model has problems.  It looks like it was changed in CAD and the previous features weren't completely overwritten.

Here you can just make out an oval shape around what is now a round hole.  
![image](https://github.com/Ultimaker/Cura/assets/64202104/fa3b18c7-6cef-431f-8acb-e84f28bd20f0)

Here it is sliced in PrusaSlicer.  As you can see...it's a mess.  (Kind of a cool looking face on that one boss though!).
![image](https://github.com/Ultimaker/Cura/assets/64202104/e9c36d15-2278-4988-aff0-61963daac726)

This is a situation where it's really impossible to tell if the "no-slice" is caused by the model errors or a bug.  I was not able to repair the model with my usual tools.

So I'll go ahead and remove the bug label and close this as the model needs a re-work in CAD.  I hope you understand.

**Closed by GregValiant** 2023-09-26 10:47 UTC
Labels: Type: Discussion, Status: Under Investigation

**Comment by sgparry** [comment] 2023-09-26 10:58
Thanks. I wish people would post the original models on Thingiverse, not just the STLs - it's a lot easier to correct then.

On 26 September 2023 11:47:38 BST, GregValiant ***@***.***> wrote:
>Thanks for the report.
>The model has problems.  It looks like it was changed in CAD and the previous features weren't completely overwritten.
>
>Here you can just make out an oval shape around what is now a round hole.  
>![image](https://github.com/Ultimaker/Cura/assets/64202104/fa3b18c7-6cef-431f-8acb-e84f28bd20f0)
>
>Here it is sliced in PrusaSlicer.  As you can see...it's a mess.  (Kind of a cool looking face on that one boss though!).
>![image](https://github.com/Ultimaker/Cura/assets/64202104/e9c36d15-2278-4988-aff0-61963daac726)
>
>This is a situation where it's really impossible to tell if the "no-slice" is caused by the model errors or a bug.  I was not able to repair the model with my usual tools.
>
>So I'll go ahead and remove the bug label and close this as the model needs a re-work in CAD.  I hope you understand.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Ultimaker/Cura/issues/16821#issuecomment-1735289695
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by GregValiant** [comment] 2023-09-26 11:10
I always check for errors because they are often the problem.  Fixing errors is just an extension of that.
In this case it's just a really bad model.  I used formware.co/OnLineSTLRepair and MS 3D Builder and neither could repair this model.  MS 3D Builder is a problem because it's also my main tool for altering STL's.
If I really needed this piece I would convert it to a DXF file and draw a new model in AutoCAD using the DXF as a template.
