### ISSUE TITLE
Custom profiles are not showing up in the profiles list

### ISSUE THREAD

**Issue by juliusbangert** [Ultimaker/Cura#1689] opened 2017-04-14 12:48 UTC
When I create a new profile from the 'create profile from current settings' option under settings>profile; it seems to save it but invisibly.. If I ever select one of the 'protected profiles' I can never go back to my custom profile. You can see in the screen shots than on the right hand pull down I have a profile called M200, but this is neither selectable in the preferences or the pulldown itself.

The same applies to when you import a profile file.

![screen shot 2017-04-14 at 12 45 33](https://cloud.githubusercontent.com/assets/3276957/25043482/4daed548-2118-11e7-84b6-3f700f6c3469.png)
![screen shot 2017-04-14 at 12 58 59](https://cloud.githubusercontent.com/assets/3276957/25043483/4daf3e34-2118-11e7-8c58-2e61b7ce582b.png)

Hope that all makes sense.
Cheers for the excellent software.

**Comment by nallath** [comment] 2017-04-14 12:49
Could you share: log file, project file & what version of Cura you are using?

**Comment by nallath** [comment] 2017-04-14 12:51
I've just tried it with the maylan m180 (when running it form source), and there it seems to work.

**Comment by juliusbangert** [comment] 2017-04-14 13:37
It's the recent update to 2.4. How do I share log file and project file?

**Comment by nallath** [comment] 2017-04-14 14:01
Host it somewhere so we can reach it. 

Another option would be to try the 2.5 BETA and see if that still has the issue. Do backup your local files before doing so though.

**Comment by Ghostkeeper** [comment] 2017-04-18 08:23
The log file can be found by going in Cura to Help -> Show Configuration Folder. The log should be there.

A project file can be created by goint into File -> Save Project. This saves the models on the build plate as well as the current machine, material, profiles and settings that you use, so that hopefully a slice is completely reproduced.

If you put the files in a .zip you can drop it in the comment box of this thread and Github will host it for you. If it's too big for Github, either trim the log file or host it on Mega instead.

**Comment by mikosik** [comment] 2017-06-01 08:11
I have very similar issue on cura 2.5.0 on Linux manjaro.
Preferences -> profile is completely empty even though I've just saved profile "perunlabs_next" by choosing settings -> profile -> "create profile from current settings/overrides".

![screenshot](https://cloud.githubusercontent.com/assets/4783806/26669565/a7ceca72-46ae-11e7-8765-38d9b6eb0ce3.png)

logfile:
[cura.log.zip](https://github.com/Ultimaker/Cura/files/1044041/cura.log.zip)

project file:
[cura_project_file.zip](https://github.com/Ultimaker/Cura/files/1044047/cura_project_file.zip)

**Comment by Ghostkeeper** [comment] 2017-06-05 22:29
> 2017-06-01 09:51:51,746 - WARNING - cura.Settings.ExtruderManager.getMachineExtruders [404]: Tried to get the extruder trains for machine Ultimaker 2+, which doesn't exist.

Seems to be that weird 404 error again... Still don't know how to reproduce that.

**Comment by ChrisTerBeke** [comment] 2017-11-14 20:56
Is this still an issue?

**Comment by Ghostkeeper** [comment] 2017-11-23 23:24
Yes, loading Mikosik's project reproduces this bug in 3.0.4.

**Comment by Ghostkeeper** [comment] 2017-11-23 23:34
I think this arose from defining a custom material type: PLA/PHA. This material type then has no profiles, but a quality profile was activated nonetheless. You can create a custom profile which then gets based off that quality type. The profile manager displays a list of profiles until restarting Cura. After restarting the list becomes empty.

**Comment by Ghostkeeper** [comment] 2018-01-01 16:17
Our project manager removed this item from our planning because it's older than 12 weeks. Still broken though even with the refactors we had for 3.1.

**Comment by Ellecross** [comment] 2018-04-11 12:19
Hi @juliusbangert and @mikosik! 

So it's been a year, :D but I'm happy to let you know that we checked your reported issues and found them fixed in 3.3 Beta. The custom profiles are now visible in the profile drop-down menu and in the profile manager window.  

This fix will also be in the final release of 3.3. 

Here's a screenshot with the custom profile from @mikosik's project file. 
![image](https://user-images.githubusercontent.com/32929710/38616095-2128a704-3d93-11e8-864d-5d7a8f0c5055.png)

If you find other issues related, let me know.

**Closed by Ellecross** 2018-04-11 12:19 UTC
Labels: Category: Cura, Type: Bug
