### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by schlundl** [Ultimaker/Cura#13369] opened 2022-09-24 01:55 UTC
### Application Version

5.1.1

### Platform

y

### Printer

creality

### Reproduction steps

sliced and error pops 

### Actual results

/j

### Expected results

/j

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

/,/bbb

**Comment by GregValiant** [comment] 2022-09-24 02:19
Without a project file and Cura log file nothing can be done about your problem.  Properly filling out the form and providing documentation of the issue is necessary so an investigation can take place.
I'll close this as it provides no information that can be used to duplicate the problem.

**Closed by GregValiant** 2022-09-24 02:19 UTC
Labels: Type: Bug
