### ISSUE TITLE
Wrong speed for "Z Hop When Retracting"

### ISSUE THREAD

**Issue by xenatis** [Ultimaker/Cura#5922] opened 2019-06-21 10:25 UTC
[CE3_Lego_Servo_Arm.gcode.txt](https://github.com/Ultimaker/Cura/files/3314132/CE3_Lego_Servo_Arm.gcode.txt)
[CE3_Lego_Servo_Arm.3mf.txt](https://github.com/Ultimaker/Cura/files/3314134/CE3_Lego_Servo_Arm.3mf.txt)

**Application Version**

4.1.0

**Platform**

Windows 7

**Printer**

Ender 3 Pro

**Steps to Reproduce**

Generate Gcode with "Z Hop When Retracted" option checked

**Actual Results**

G1 F17987547480000 Z1.2
G0 F1800 X107.705 Y48.493 Z1.2
G1 F17987547480000 Z0.2

**Expected results**

using G0 for Z hop, or using G1 with a consistant speed value.

**Additional Information**

**Comment by Ellecross** [comment] 2019-06-24 08:44
Hey @xenatis thanks for your report .. and for attaching the gcode and 3MF file!! :D I'll share this with Cura team.

**Comment by Ghostkeeper** [comment] 2019-06-26 05:43
This is a duplicate of https://github.com/Ultimaker/Cura/issues/5753.

**Closed by Ghostkeeper** 2019-06-26 05:43 UTC
