### ISSUE TITLE
Incorrect slicing

### ISSUE THREAD

**Issue by baerni** [Ultimaker/Cura#15990] opened 2023-07-03 18:05 UTC
### Application Version

5.3

### Operating System

MacOS

### Printer

Creality Ender 3 V2 Neo

### Reproduction steps

1. Slice 3D model
2. Look at the layers 

### Actual results

I have a problem with version 5.3. The program generates models incorrectly. When I went back to version 5.2.2 everything works fine. I am sending a screenshot to show the problem. I am also sending a [link](https://www.printables.com/pl/model/384924-small-clip-with-teeth/files) to the 3D model.
![5 2 2](https://github.com/Ultimaker/Cura/assets/17702073/a55273c7-5baa-4d3f-91de-a8c43a951112)
![5 3](https://github.com/Ultimaker/Cura/assets/17702073/17e4f12f-7a9a-432d-a846-88bebda8697f)

### Expected results

In version 5.2.2 it works fine

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Screenshots posted above

**Comment by rondlh** [comment] 2023-07-05 04:29
How about Cura 5.3.1? This could be kind of an edge case. Make sure all settings (including nozzle size) are the same.

**Comment by baerni** [comment] 2023-07-05 05:18
All settings are the same. I checked version 5.3.1 and 5.4 - it's bad everywhere. The last working version is 5.2.2.

**Comment by MariMakes** [comment] 2023-07-26 20:47
Hey @baerni,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 

I think I recognize this issue, in Cura 5.3 we introduced a different approach super detailed walls. The result was that the wall threshold for a hole being too small slightly changed. Luckily there is an easy solution to this which is checking the Print Thin Walls setting. You can also see it as print thin gaps.  If you change this setting your model will look like this: 
![image](https://github.com/Ultimaker/Cura/assets/40423138/c28c4de9-d143-4787-911e-3eec3db4887e)

To me, it doesn't seem like a bug in Ultimaker Cura, since we have a solution in place. 
Apologies for any inconvenience caused by our delayed response. 
I'll be closing this issue. I hope you understand.

**Closed by MariMakes** 2023-07-26 20:47 UTC
Labels: Type: Bug, Status: Triage
