### ISSUE TITLE
object NOT over bed plate cura doesn't create support 

### ISSUE THREAD

**Issue by bucefalo2** [Ultimaker/Cura#8740] opened 2020-11-12 11:43 UTC
**Application version**
4.8 

**Platform**
windows 10
**Printer**
Ender 3 pro

**Reproduction steps**
1. lifted item from bed plat of 2 mm in Z in cura 
2. enabled in SUPPORT -> GENERATE SUPPORT
3. SLICE  

**Screenshot(s)**
[http://www.simiweb.net/cura_problem.jpg](http://www.simiweb.net/cura_problem.jpg)

**Actual results**
0 minutes printing time.. objected won't be sliced 
**Expected results**
by moving on Z by 2mm and generate support i'd expect cura to create a support to fill that 2 mm gap !

**Project file**
[www.simiweb.net/CE3_tyre_2.3mf](https://www.simiweb.net/CE3_tyre_2.3mf)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**

**Comment by nallath** [comment] 2020-11-12 12:19
It's a known issue that adaptive layer height doesn't work when the object isn't touching the buildplate.

**Comment by bucefalo2** [comment] 2020-11-12 13:42
> It's a known issue that adaptive layer height doesn't work when the object isn't touching the buildplate.

i didn't know ! i made a test now DISABLED " use adaptive layers " and i could get the support , look : 
[www.simiweb.net/support.jpg](url)

**Comment by Ghostkeeper** [comment] 2020-11-17 17:41
Duplicate of https://github.com/Ultimaker/Cura/issues/3183.
Slicing stops on the first empty layer there. That's a bug.

**Closed by Ghostkeeper** 2020-11-17 17:41 UTC
Labels: Type: Bug
