### ISSUE TITLE
Not retracting when moving between part(s) and prime tower

### ISSUE THREAD

**Issue by pouncingiguana** [Ultimaker/Cura#1353] opened 2017-01-16 13:31 UTC
When using dual extrusion with cura 2.3.1 or 2.4 beta, it is not retracting before it moves to change nozzels. GCODE below shows normal printing, then the move away from the object without retracting first, then it does the retract,then changes nozzels. Can it be changed to do a normal retract before moving away from the part?

GCODE:
`G1 X6.149 Y40.09 E1101.8247`
`G1 X5.918 Y40.566 E1101.8412`
`G1 X5.688 Y41.043 E1101.85771`
`G1 X5.457 Y41.52 E1101.87429`
`G0 F9000 X7.247 Y36.946`
`G1 F3000 X6.817 Y36.515 E1101.90593`
`G0 F9000 X6.693 Y37.066`
`G1 F1800 E1100.40593`
`G1 Z6.8`
`G0 F9000 X30 Y30 Z6.8`
`G1 F3000 E1084.90593`
`G92 E0`
`T1`
`G92 E0`
`M109 S205`

**Comment by Ghostkeeper** [comment] 2017-01-22 20:51
Did you happen to have retraction disabled?
We have an open bug in our tracker that says "Tool retraction being done after moving to the switch (When retraction is disabled)".

**Comment by pouncingiguana** [comment] 2017-01-23 14:24
I do not have retraction disabled. It's retracting properly at all other places in the print, but not when it does the initial move away from the part towards the priming tower, or moves away from the priming tower on it's way back.

**Comment by Ghostkeeper** [comment] 2017-01-24 10:32
I can't reproduce this. For me it produces this g-code with a dual extrusion print when prime tower is enabled (I added comments):

    G1 F1800 X121.773 Y97.814 E157.81042 ;Last line of skin.
    M204 S2812
    M205 X18
    G1 F1500 E151.31042 ;Retracts here!
    G0 F10312.5 X124.885 Y99.854 ;Moving to switching bay.
    G0 X127.285 Y102.481
    G0 X213 Y189
    G1 F1200 E141.81042
    G92 E0
    
    T0 ;Extruder switch.
    G92 E0
    
    M109 S190
    G1 F1200 E9.5 ;Prime to retracted position.
    M104 T1 S100
    M106 S85
    G1 Z2.421
    G0 F10312.5 X167.5 Y186.5 Z2.42 ;Moving to prime tower.
    G1 Z0.42
    G0 X173.226 Y186.246
    M104 S200
    M204 S2000
    M205 X15
    ;TYPE:SUPPORT
    G1 F1500 E16 ;Unretract.
    G1 F1800 X174.216 Y187.236 E16 ;First line of prime tower.

**Comment by pouncingiguana** [comment] 2017-01-26 21:49
Hmmmm. We've been able to reproduce this over Windows and Linux (2.4 beta2). Only possible difference I can think of is that our printers are circular bed with 0,0 at center.

**Comment by Ghostkeeper** [comment] 2017-01-27 08:59
Perhaps it's an idea to export your project and upload it here so that we can reproduce it. It's under File -> Save Project. It saves the model along with all profiles, printers and settings that you're using. New feature of 2.4.

**Comment by BagelOrb** [comment] 2017-03-08 14:30
Perhaps you set the switch_extruder_retraction_amount at zero?

**Comment by ianpaschal** [comment] 2018-02-27 09:48
Closing for inactivity, irreproducibility, and the fact that we won't be making any changes fo versions below 2.7.

**Closed by ianpaschal** 2018-02-27 09:48 UTC
Labels: Category: CuraEngine, Type: Bug
