### ISSUE TITLE
Print sequence order selection

### ISSUE THREAD

**Issue by bart989** [Ultimaker/Cura#11619] opened 2022-03-07 10:53 UTC
### Is your feature request related to a problem?

When I'm printing parts one by one I can't chose order. Order is chosen by the order of imported parts, same as object list, but reversed (up most part prints last). I didn't find a way to change it. I cant add part and edit order in queue.

### Describe the solution you'd like

I would like to have simple arrows to change order of parts in object list. Maybe a drag and drop feature. My point would be to object list serve also as queue

![Screenshot_6](https://user-images.githubusercontent.com/26008029/157017652-db6aa458-e919-4aa5-a186-d2c92a6ab41c.png)

### Describe alternatives you've considered

To select a part and write somewhere number of print in queue

### Affected users and/or printers

Everyone who prints multiple prints on single bed. Especially usefull whed you prind 3d printed planes as this is an issue i ran doing this task.

**Comment by fvrmr** [comment] 2022-03-10 14:47
Hi @bart989 thank you for your request.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/4835
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2022-03-10 14:47 UTC
Labels: Type: New Feature
