### ISSUE TITLE
no "skin overlap" when "top surface skin layers" enabled

### ISSUE THREAD

**Issue by MrStump** [Ultimaker/Cura#10147] opened 2021-07-17 23:18 UTC
### Application Version

4.10

### Platform

win 10

### Printer

CoreXY

### Reproduction steps

enable "top surface skin layers" and there is't "skin overlap" at any percent

### Actual results

no overlap

### Expected results

Expected that there will be "skin overlap"

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

in 4.9 it did't work too, but in 4.9 it overlap skin layers **under** the "top skin", but don't in 4.10

**Comment by fvrmr** [comment] 2021-07-19 11:27
Hi @MrStump the skin overlap percentage is available for me even if the top surface skin layers are 0. Can you post a screenshot or share a project file, maybe there is something changed in your profile.

**Comment by MrStump** [comment] 2021-07-19 11:43
It's available, but didn't work, at all, it didn't overlap. I'll post project little later

**Comment by Ghostkeeper** [comment] 2021-07-26 10:06
We already have this issue in our backlog (CURA-6550). It is a duplicate of https://github.com/Ultimaker/Cura/issues/5758.

**Closed by Ghostkeeper** 2021-07-26 10:06 UTC
Labels: Status: Needs Info, Type: Bug
