### ISSUE TITLE
I Can't open Ultimaker Cure.app 4.6.1 on my Mac running OS Catalina 10.15.4 

### ISSUE THREAD

**Issue by HomeBoxG** [Ultimaker/Cura#7801] opened 2020-05-21 18:44 UTC
**Application version**
Ultimaker_Cura-4.6.1-Darwin

**Platform**
OS Catalina 10.15.4 
Quad-Core Intel Core i5

**Reproduction steps**
1 download the app from Ultimaker
2 dragging it in to the APP folder
3 clicking on the Cure App
4 pop up saying can't open because apple can't check for malicious software. 
![Schermafbeelding 2020-05-21 om 20 36 35](https://user-images.githubusercontent.com/63612405/82593418-c75d2900-9ba2-11ea-8933-f831a71739e9.png)

Ultimaker Cura:

  Versie:	4,6
  Afkomstig van:	Ontwikkelaar waarvan de identiteit bekend is
  Laatst gewijzigd:	29/04/2020 11:24
  Ondertekend door:	Developer ID Application: Ultimaker B.V. (V4B3JXRRQS), Developer ID Certification Authority, Apple Root CA
  Locatie:	/Applications/Ultimaker Cura.app
  Soort:	64-bits

**Comment by 64Florian** [comment] 2020-05-22 00:04
Hello,
Has I remember you have to "allow" the software in "FireVault"
Sorry my screenshot are in french and on MacOS Sierra but it should be the same 
In application folder: 
![Capture d’écran 2020-05-22 à 01 54 24](https://user-images.githubusercontent.com/34726380/82617126-70ba1400-9bcf-11ea-8397-0d5245b63095.png)
![Capture d’écran 2020-05-22 à 01 54 34](https://user-images.githubusercontent.com/34726380/82617127-7152aa80-9bcf-11ea-9534-c46e1a2e02d6.png)
![Capture d’écran 2020-05-22 à 01 54 41](https://user-images.githubusercontent.com/34726380/82617128-7152aa80-9bcf-11ea-91d7-adb23b61e0b3.png)
On the last screen (after your message only) you should have a button to allow Cura 

Please let me know if you still have this issue I'll try on another OS if it's needed

**Comment by 64Florian** [comment] 2020-05-24 16:30
I saw this ticket #6700...
If my last message doesn't help, you may try the @smartavionics build...

**Comment by Ghostkeeper** [comment] 2020-05-25 13:27
Duplicate of https://github.com/Ultimaker/Cura/issues/7389.

The problem is that since Catalina we'd need to sign Cura twice, with both an older signing system and with a newer signing system. Apple isn't very friendly towards its developers. There are ways around it though to still run it (and then you will still run into our Qt version not properly supporting Catalina either, but it runs for the most part).

We're still working on this, but we have been running into account management issues that even Apple Support was baffled about. I quote: "that should never happen" :smile:

**Closed by Ghostkeeper** 2020-05-25 13:27 UTC
Labels: Type: Bug
