### ISSUE TITLE
Top/Bottom

### ISSUE THREAD

**Issue by cemiyetadami** [Ultimaker/Cura#12085] opened 2022-05-04 11:38 UTC
### Application Version

5.0.0-beta+1

### Platform

Windows 10

### Printer

Ender3v2

### Reproduction steps

under top/bottom  Top/Bottom pattern and Bottom Pattern Initial Layer have no effect 
when i make selection cura forces e to slice again but no difference. allways bottom layer and initial layer in concentric pattern

### Actual results

making selection doesnt chance pattern

### Expected results

making selection must chance pattern

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/17948476/166673849-0308d1dd-415b-4c56-9a78-24329c29172e.png)
![image](https://user-images.githubusercontent.com/17948476/166673956-cd07c3a4-3978-478e-9e64-f26e0a6451bb.png)

**Comment by GregValiant** [comment] 2022-05-04 12:00
@cemiyetadami Can you provide a project file (File | Save Project).  I can't duplicate this as switching back and forth works for me.

**Comment by Asterchades** [comment] 2022-05-05 05:23
It does this when Spiralize Outer Contour is enabled. Everything related to the Bottom Layer/s is ignored in 5.0b1 - you get one (1) layer with a concentric pattern for the base and that's all, as opposed to previous versions where the base would still be printed using the given settings.

This is a duplicate of https://github.com/Ultimaker/Cura/issues/12075.

**Closed** 2022-05-23 15:17 UTC
Labels: Type: Bug, Status: Needs Info

**Comment by PhilBaz** [comment] 2022-05-26 16:50
Ive made additional entries in my duplicate https://github.com/Ultimaker/Cura/issues/12075 if anyone is watching this.
