### ISSUE TITLE
4.9 Sliced preview freezes computer

### ISSUE THREAD

**Issue by jatenk** [Ultimaker/Cura#9719] opened 2021-04-29 03:58 UTC
### Application Version

4.9.0

### Platform

macOS 10.13.6

### Printer

Monoprice Select Mini

### Reproduction steps

1. Import any file (for example, a 2.9MB .stl file = file doesn't have to be big for the problem to occur).
2. Without changing any settings away from the default ones, click Slice and then Preview (or in the other order - either process alone finishes without issues).
3. When the second action has been performed, the preview-building progress bar jumps a lot, the app window might blank out several times, the rest of the computer becomes unresponsive, the app window has content again if you switch between fullscreens but...
4. ...eventually, without showing the actual built sliced preview, the app either crashes or, in some cases, freezes the entire computer, requiring a forced shutdown (hold power button for 10 seconds). The mouse can still be moved across the screen, but nothing else reacts. This plus the blank window makes me believe that the issue lies with a GPU incompatibility.

4.8 still works; it's slow and progress jumps a lot too, but the app never froze the entire computer and the app only sometimes crashed (rarely enough to be workable).

Computer this is happening on is a 2011 iMac. (Don't judge me, I'm poor.)

### Actual results

App crashes after a low two-digit amount of seconds or computer freezes.

### Expected results

Sliced preview is shown, in the best case without any freezes, no computer crashes.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/6396232/cura.log)

[sculpt.stl.zip](https://github.com/Ultimaker/Cura/files/6396233/sculpt.stl.zip)

**Comment by fvrmr** [comment] 2021-04-29 12:41
Hi @jatenk thank you for your bug report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9631 
So I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-04-29 12:41 UTC
Labels: Type: Bug
