### ISSUE TITLE
[4.8.0] Cubic Subdivision overlaps Extra Infill Walls

### ISSUE THREAD

**Issue by JohnTasto** [Ultimaker/Cura#9108] opened 2021-01-11 10:52 UTC
4.8.0
Windows 10
Heavily modified BIBO 2

When `Infill Pattern = Cubic Subdivision` and `Extra Infill Wall Count > 0`, the infill lines and the extra infill walls overlap. It can be compensated with `Infill Overlap [Percentage] < 0`, but that causes a gap if `Infill Pattern` is later changed away from `Cubic Subdivision`.

`Infill Overlap` also affects supports, and a negative value here will cause a gap in support structures since `Cubic Subdivision` is not an option for supports. There should probably be a separate `Infill Overlap` setting for supports, since they often use different extruders.

The following screenshots have `Extra Infill Wall Count = 2`.

`Infill Pattern = Cubic Subdivision`
`Infill Overlap Percentage = 10%` (default, excess overlap)
![Infill Cubic Subdivision Overlap](https://user-images.githubusercontent.com/5026892/104170908-b4f46180-53b6-11eb-930b-844824d306c2.png)

`Infill Pattern = Cubic Subdivision`
`Infill Overlap Percentage = -190%` (compensated)
![Infill Cubic Subdivision Compensated](https://user-images.githubusercontent.com/5026892/104171081-f5ec7600-53b6-11eb-9ccd-4c84125b540e.png)

`Infill Pattern = Cubic`
`Infill Overlap Percentage = -190%` (gap)
![Infill Cubic Gap](https://user-images.githubusercontent.com/5026892/104171144-13214480-53b7-11eb-9608-da02134621e3.png)

Project file (same as #9110):
[hole-small.zip](https://github.com/Ultimaker/Cura/files/5795243/hole-small.zip)
Printer definition:
[bibent.zip](https://github.com/Ultimaker/Cura/files/5795246/bibent.zip)

**Comment by fvrmr** [comment] 2021-01-12 11:44
Thank you, I got the same. Will discuss this issue with the team.

**Comment by fvrmr** [comment] 2021-01-18 12:27
We will defer this for now, it is not our priority because not many people are using this option.

**Comment by jellespijker** [comment] 2021-01-19 17:28
The bug you reported can indeed be reproduced. But it would require relatively a lot of effort to fix it. At the moment we have a few different priorities. One of these is priorities is the new experimental engine Arachne. The way that infill area's are calculated differs compared with the "old" way 4.8 etc. The part of the code where the surfaces are generated in the new experimental Arachne engine are due to be rewritten. We will keep this behaviour in to account at that time.
For now I will close this issue. Thank you for reporting it tho.

**Comment by Ghostkeeper** [comment] 2021-01-28 09:37
Let's keep these things open then. It's not a priority due to the rarity of the case, but it is a real issue and we should know that it exists.

**Comment by JohnTasto** [comment] 2021-01-29 11:49
Issue 1210 is a question about IDEs from 2016. I don't understand the connection - am I missing something?

**Comment by Ghostkeeper** [comment] 2021-02-05 10:51
Ah, sorry. Broken link. That should be Ultimaker/CuraEngine#1210.

**Comment by Ghostkeeper** [comment] 2021-12-14 11:13
This is now fixed, since https://github.com/Ultimaker/CuraEngine/pull/1210 is merged.

**Closed by Ghostkeeper** 2021-12-14 11:13 UTC
Labels: Type: Bug, Status: Deferred
