### ISSUE TITLE
Having blank start/stop gcode regenerates default start/stop gcode on restart.

### ISSUE THREAD

**Issue by JohnBaumb** [Ultimaker/Cura#9595] opened 2021-04-17 10:42 UTC
### Application Version

4.8.0

### Platform

Windows 10

### Printer

Ender 3 / CR10 S5

### Reproduction steps

Open Cura
Check printer start/end gcode, delete (using klipper, don't need it).
Restart Cura
default gcode reappears.

May be related to having multiple printers defined (I have 3 defined, two ender 3's and a CR10 S5).

Able to mitigate this issue by simply adding a semicolon for each category.

### Actual results

Since there is no notification, you can export sliced gcode and it will work correctly, but the next time you use cura, your gcode will contain the default gcode. Thereby creating undesired results without any notifications to the user that something has changed.

### Expected results

Blank gcode should stay blank, perhaps have a button for reverting default gcode if necessary.

**Comment by GregValiant** [comment] 2021-04-17 11:02
As a work around, have you tried leaving 1 comment in?
**;**Klipper

**Comment by JohnBaumb** [comment] 2021-04-17 11:03
Yes, I mentioned that in my submission, and it appears to work.

**Comment by fvrmr** [comment] 2021-04-19 08:06
Hi @JohnBaumb thank you for your bug report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9576 that's why I will close this issue. 
The work around that @GregValiant is suggesting works. But I am not able to reproduce this issue unfortunately.

**Closed by fvrmr** 2021-04-19 08:06 UTC
Labels: Type: Bug
