### ISSUE TITLE
[4.8 Beta] Not slicing when using adaptative layers and model is not touching build plate

### ISSUE THREAD

**Issue by MrEd88** [Ultimaker/Cura#8713] opened 2020-11-08 06:25 UTC
**Application version**
4.8 Beta 

**Platform**
Linux Mint 20 - GTX 1050TI

**Printer**
Custom printer

**Reproduction steps**
1. Load model, raise it any distance from bed and enable supports
2. Enable and adjust adaptative layers
3. Slice and review

**Screenshot(s)** 
![image](https://user-images.githubusercontent.com/19942461/98458482-2c133c80-215f-11eb-9abf-a43e2be2a9f0.png)

**Actual results**
Cura seems to slice in a quarter of a second but result in no slicing at all.
If adaptative layers is disabled it slices normally.
If model is moved to touch the build plate leaving enabled adaptative layers, it slices normally.

**Expected results**
Slice normally 

**Project file**
N/A. Any model with any profile doing the steps mentioned before.

**Additional information**
Did not test in older versions, currently using only the beta works for most of my needs.

**Comment by konskarm** [comment] 2020-11-11 16:23
This is now in our backlog. Devs see CURA-7835.

**Comment by bucefalo2** [comment] 2020-11-12 14:41
exactly same problem i faced today ! thank you !!!

**Comment by Ghostkeeper** [comment] 2020-11-17 10:57
Correction for developers: The actual issue is CURA-6513. We already had this in our backlog.

This issue is a duplicate of https://github.com/Ultimaker/Cura/issues/3183. Please continue discussion there.

**Closed by Ghostkeeper** 2020-11-17 10:57 UTC
Labels: Type: Bug
