### ISSUE TITLE
[4.5 beta]Scale Issue

### ISSUE THREAD

**Issue by SivaasPlays** [Ultimaker/Cura#7142] opened 2020-02-21 05:03 UTC
**Application version**
(The version of the application this issue occurs with.)
4.5 beta and 4.4.1
**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)
win 10 and nvidia 2080
**Printer**
(Which printer was selected in Cura?)
ender 3
**Reproduction steps**
1. load an stl 
2. rotate model  90 degrees on X axis
3. go to scale in y or z

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
![cura bug](https://user-images.githubusercontent.com/46896346/75004889-8c910b00-5464-11ea-8aec-c8ff5776696f.PNG)

**Actual results**
(What happens after the above steps have been followed.)
adjusting the Y size changes the Z % and changing the Z size instead changes Y % and vice-versa
it also does a strange multiplying effect if you type in a % in say the Y it will make the Y size and the Z % shoot way up.

**Expected results**
(What should happen after the above steps have been followed.)
should just scale properly
**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)
No logs looked relevant to this situation. 

**Additional information**
(Extra information relevant to the issue.)
na

**Comment by nallath** [comment] 2020-02-21 08:47
This is a duplicate of https://github.com/Ultimaker/Cura/issues/4136

**Closed by nallath** 2020-02-21 08:47 UTC
Labels: Status: Duplicate, Type: Bug
