### ISSUE TITLE
Unable to import 2.5 Profiles

### ISSUE THREAD

**Issue by AndriesMuylaert** [Ultimaker/Cura#2723] opened 2017-11-04 10:12 UTC
Hello,

I'm unable to import old ini profiles in Cura 3.0.4.
[Profiles.zip](https://github.com/Ultimaker/Cura/files/1443126/Profiles.zip)

**Comment by ChrisTerBeke** [comment] 2017-11-04 14:51
This is a known issue and we're working on resolving it.

**Comment by AndriesMuylaert** [comment] 2017-11-04 15:01
Ok thanks,

Meanwhile I found a workaround by installing 2.5, importing there,
exporting with new fileformat, reinstalling 3.0, importing the new
fileformat.

Best regards,

Andries

Op za 4 nov. 2017 om 15:51 schreef ChrisTerBeke <notifications@github.com>

**Comment by nickthetait** [comment] 2017-11-08 18:10
Duplicate of https://github.com/Ultimaker/Cura/issues/2117
@ChrisTerBeke can you comment on the main issue that this is a WIP, don't want someone wasting their time trying to fix this if Ultimaker already is... 
Also, hooray that this will be taken care of! This (currently broken) feature is a major hurdle for people upgrading to the Qt version of Cura.

**Comment by ChrisTerBeke** [comment] 2017-11-08 20:51
Done. Closing this since it's a duplicate.

**Closed by ChrisTerBeke** 2017-11-08 20:51 UTC
Labels: WIP
