### ISSUE TITLE
Cura 3.1 No adherence to the platform 

### ISSUE THREAD

**Issue by joselauro** [Ultimaker/Cura#2978] opened 2017-12-14 01:43 UTC
I don't know what hapened, but since I updated to the new version it completely stop adherence. I just moved back to the old version.

**Comment by Vandrasc** [comment] 2017-12-14 08:23
Hi @joselauro, could you give us more information? Is it possible to save the project and share it with us so we can see what the problem is? Thank you!

**Comment by ChrisTerBeke** [comment] 2017-12-14 11:47
Sounds like one of those cases were settings don't get applied. Did you use the 3.1 beta before using the stable? Can you send your user data folder to us as well?

**Comment by joselauro** [comment] 2017-12-14 18:18
Dear Vandrasc and CrisTerBeke.
Well, I am printing a chess set. I had printed 29 pieces, and than now, when I was going to print another black knight it starts doing this. The material just don't get adherence to the platform, like eggs in a teflon skillet. Then I tried a dice I still had the gcode, and that I had printed beffor, and it worked. The only thing I had changed was the version of cura. I donwload the old version, install it, and it starts printing again. I am printing with ABS, using 230ºC, 80ºC, but the printer never gets to 80ºC. It is a Monoprice Select Mini V2.

**Comment by ChrisTerBeke** [comment] 2017-12-14 18:44
Can you post your machine settings here? Preferably a project file (file -> save as project) so we can reproduce your problem and hopefully fix it.

**Comment by fieldOfView** [comment] 2017-12-15 00:03
Probably related to temperatures not being set correctly for single extruder printers.

**Comment by joselauro** [comment] 2017-12-15 03:44
Dear ChrisTerBeke.
Here go the gcodes.
[gcodes.zip](https://github.com/Ultimaker/Cura/files/1561500/gcodes.zip)]
The .3mf files are bigger than 10MB even when zipped. How can I send them?

Thank you.

Dear fieldOfView.
I think both versions set extruder temperature to 230ºC with ABS.

**Comment by joselauro** [comment] 2017-12-15 03:48
_"Did you use the 3.1 beta before using the stable? "_

No. I didn't. I used 3.04 and before a very old version which cames with the printer. I don't remember the version but I completely uninstall that one.

**Comment by Ghostkeeper** [comment] 2018-01-02 09:47
Comparing the two I see that the 3.1 one has set Extra Skin Wall Count to 1 instead of 0. Maybe you could try setting that back to 0?

**Comment by ChrisTerBeke** [comment] 2018-05-23 19:13
No new info, plus can't reproduce. Closing.

**Closed by ChrisTerBeke** 2018-05-23 19:13 UTC
Labels: Status: Needs Info
