### ISSUE TITLE
Cura 3.1.0 "material_print_temperature" not working correctly

### ISSUE THREAD

**Issue by kr15uk** [Ultimaker/Cura#3074] opened 2018-01-01 16:27 UTC
Cura 3.1.0, macOS 10.13.2
Material with set temperature of 270c
Start gcode:
"M104 S{material_print_temperature}
M109 S{material_print_temperature}"

Exported gcode:
"M104 S210
M109 S210"

It kicks in correctly to "M104 S270" in line 1126 but thats too late...

Bed temp "M190 S{material_bed_temperature}" works correctly, only issue with hotted temp.

Happy to provide gcode file and material file.

Thanks.

**Comment by fieldOfView** [comment] 2018-01-01 16:36
Duplicate of #3061, #3032, #1296 and others. Will be fixed in Cura 3.2

**Comment by ChrisTerBeke** [comment] 2018-01-01 17:02
Indeed duplicate of above mentioned, please check existing issues before filing a new issue.

**Closed by ChrisTerBeke** 2018-01-01 17:02 UTC
