### ISSUE TITLE
In custom print settings, arrow handles on section headings don't open/close properly

### ISSUE THREAD

**Issue by jacix** [Ultimaker/Cura#8355] opened 2020-09-09 16:37 UTC
**Application version**
4.7.1

**Platform**
MacOS 19.6.0 Darwin Kernel Version 19.6.0

**Printer**
Creality Ender 3 Pro and Creality CR10S Pro

**Reproduction steps**
1. In the "Prepare" workspace, go to custom print settings and open any of the section headings.  The arrows on the right don't reorient.  This started with version 4.7. 

**Screenshot(s)**
After starting Cura without any project loaded:
![Screen Shot 2020-09-09 at 12 35 34 PM](https://user-images.githubusercontent.com/7086662/92627305-29988180-f299-11ea-92f0-244fc74308ef.png)

Loading a recent project then clearing everything by selecting "new project":
![Screen Shot 2020-09-09 at 12 29 44 PM](https://user-images.githubusercontent.com/7086662/92626748-58fabe80-f298-11ea-82d7-3cabc409c76d.png)

**Actual results**
The arrows don't open or close.

**Expected results**
The arrows should open and close.

**Project file**
This happens whether I have a project file loaded or not.

**Log file**
Nothing appears in the log file when I see this behavior.  

**Additional information**
(Extra information relevant to the issue.)

**Comment by konskarm** [comment] 2020-09-10 07:44
I can reproduce this issue in windows. Thanks for the report.

**Comment by Ghostkeeper** [comment] 2020-09-10 07:53
Duplicate of #8283.

**Closed by Ghostkeeper** 2020-09-10 07:53 UTC
Labels: Type: Bug
