### ISSUE TITLE
Bad slicing result

### ISSUE THREAD

**Issue by GMagician** [Ultimaker/Cura#15076] opened 2023-03-29 13:07 UTC
### Application Version

5.3.0

### Platform

Windows 11

### Printer

Custom Bear 2.1

### Reproduction steps

Just slice attached project

### Actual results

There are some weird, uncompleted, top layers

### Expected results

Correctly filled top layer

### Checklist of files to include

- [x] Log file
- [X] Project file

### Additional information & file uploads

![Senza nome](https://user-images.githubusercontent.com/3684609/228544582-12b98128-9400-41e7-bebf-d19c4f4ee019.png)
[Lid.zip](https://github.com/Ultimaker/Cura/files/11101171/Lid.zip)

**Comment by GMagician** [comment] 2023-03-29 16:33
Not sure log may help here

**Comment by MariMakes** [comment] 2023-04-05 15:06
Hey @GMagician,

Thanks for your report 👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/15028
There we learned that you can resolve it by increasing the Skin Expand Distance, that also works for your case. 
![image](https://user-images.githubusercontent.com/40423138/230122980-0614546b-9ef0-4aa8-b8ff-e7809e05bc29.png)

We'll still discuss it with the team because it might be an indicator that something else is broken.
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/15028

**Closed by MariMakes** 2023-04-05 15:06 UTC
Labels: Type: Bug, Status: Triage
