### ISSUE TITLE
lingua

### ISSUE THREAD

**Issue by Maxtitan68** [Ultimaker/Cura#13598] opened 2022-10-19 08:16 UTC
### Application Version

5.2.0

### Platform

windows 10

### Printer

ultimaker  5

### Reproduction steps

manca la lingua italiana, quando scelgo italiano mi da il francese

### Actual results

viene francese

### Expected results

mi aspetto che venga italiano

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

d

**Comment by MariMakes** [comment] 2022-10-19 13:38
Mi dispiace, non parlo italiano ma penso di poterti aiutare.

We are aware of a translation issue in Cura 5.2.0, we are working hard to fix this as soon as possible. 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13592
We have a ticket on our backlog with the intent to improve this behavior.
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/13592

**Closed by MariMakes** 2022-10-19 13:38 UTC
Labels: Type: Bug, Status: Triage
