### ISSUE TITLE
Z Seam Alignment does not work in Cura 4.6

### ISSUE THREAD

**Issue by BERT-LZ** [Ultimaker/Cura#7600] opened 2020-04-26 09:50 UTC
Z Seam Alignment does not work in Cura 4.6
Z Seam Alignment - Sharpest Corner, Seam Corner Preferenz does not work in Cura 4.6.
But it works in Cura 4.5
I have already deleted the Cura folder on Appdata, and reconfigured Cura - the error is still there.

**Comment by smartavionics** [comment] 2020-04-26 10:24
Duplicate of https://github.com/Ultimaker/Cura/issues/7557.

**Closed** 2020-04-28 11:17 UTC
Labels: Type: Bug
