### ISSUE TITLE
Crashes when i slice

### ISSUE THREAD

**Issue by Mastache86** [Ultimaker/Cura#14318] opened 2023-01-18 01:48 UTC
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Ender 3 pro

### Reproduction steps

Slow speed down to 50mm/s print bed 25./210 
hit slice

### Actual results

bug code comes out and sends me here to send report
![Screenshot 2023-01-17 204417](https://user-images.githubusercontent.com/118086395/213060773-c3b2587c-5fe6-4a26-a796-158a89db3391.png)

### Expected results

Have file sliced to continue foward

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

n/a

**Comment by MariMakes** [comment] 2023-01-20 12:24
HEy @Mastache86,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

Is it possible that your printjob is located at 0, 0, 0, and it slices if you move it a little away from the center of the buildplate? 
Then it might be a duplicate of https://github.com/Ultimaker/Cura/issues/13643

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Closed** 2023-02-03 12:37 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage, Slicing Error :collision:
