### ISSUE TITLE
Font is not displaying correctly. Works fine with 4.13.0

### ISSUE THREAD

**Issue by russemi** [Ultimaker/Cura#12028] opened 2022-04-30 05:07 UTC
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ender 5+

### Reproduction steps

Nothing

### Actual results

![ScreenShot Font](https://user-images.githubusercontent.com/104666050/166091879-5a8e58cc-bef3-4400-a6f3-a44a9d5f38e0.jpg)

### Expected results

Should display clearly, as in 4.13.0
![ScreenShot Font 4 13 0](https://user-images.githubusercontent.com/104666050/166091972-a152799d-28d8-422f-a043-fd536eb0378b.jpg)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

All are uploaded

**Comment by fvrmr** [comment] 2022-05-02 09:54
Hi @russemi thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11957, so I will close this issue.

**Closed by fvrmr** 2022-05-02 09:54 UTC
Labels: Type: Bug
