### ISSUE TITLE
Slicing error on opening file and slicing

### ISSUE THREAD

**Issue by joryvd** [Ultimaker/Cura#17560] opened 2023-12-08 12:53 UTC
### Cura Version

5.6.0

### Operating System

Windows 10 19045.3693 with GTX 780

### Printer

Custom Printer, Creativity ELF

### Describe your model

Downloaded from printables: https://www.printables.com/model/32460-beastmode-travel-hangboard

### Add your .zip here ⬇️

[TravelHaangboard v9.zip](https://github.com/Ultimaker/Cura/files/13614181/TravelHaangboard.v9.zip)

**Comment by 5axes** [comment] 2023-12-11 00:37
An other **Print Thin Wall** Issue : https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-7790452
![image](https://github.com/Ultimaker/Cura/assets/11015345/185c3a50-44c1-415d-a2cb-ebf97d187a21)

**Comment by MariMakes** [comment] 2024-01-18 15:33
Hi @joryvd,

Quick update from our side 👋
We are introducing a new tool to analyze slicing crashes like the one you reported. 💪

Even with the changes we made in the latest versions of Cura we still see that your model crashes. 🫤 But we have added your project file to our analyzing tool and found there were at least 5 crashes that were similar to yours, which helps us to narrow down what the cause is of your crash so we can resolve this for you and others.
Hopefully, we can find a solution soon 🤞

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/17679

**Closed by MariMakes** 2024-01-18 15:33 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:
