### ISSUE TITLE
[4.4.0] Changes to material list (duplicate, remove) not updating until material management dialogue is closed and re-opened

### ISSUE THREAD

**Issue by dyyys1** [Ultimaker/Cura#6762] opened 2019-12-05 16:21 UTC
4.4.0

Windows 10 Pro 64 bit
Prusa i3 MK3S

**Reproduction steps**
1. Open material selection drop box
2. Click Manage Materials
3. Select "Generic - PLA" or other material
4. Click "Duplicate" or Remove

**Actual results**
Material list does not update (new profile does not appear or selected profile does not disappear).

**Additional information**
After closing material manager and repeating steps 1 and 2, the material list is correct.

**Comment by Ghostkeeper** [comment] 2019-12-06 15:10
Duplicate of https://github.com/Ultimaker/Cura/issues/6714.

**Closed by Ghostkeeper** 2019-12-06 15:10 UTC
