### ISSUE TITLE
[Feature Request] - Numerical Rotation Angle Input

### ISSUE THREAD

**Issue by KenLucke** [Ultimaker/Cura#8899] opened 2020-12-07 19:06 UTC
**Is your feature request related to a problem? Please describe.**
Rotation is forced to 1° increments (even when "Snap Rotation" is disabled), and must be done by dragging model in the build space.

**Describe the solution you'd like**
The ability to set rotation precise angles, for all three axes, instantly via dialog boxes/numerically to any degree, including fractional ones.  Position and Scale  have numerical input  ability via text boxes, why does Rotation not have the same function?  For instance, 22.5° is a common angle for many things (half of a 45° angle).  There is NO way I have found to set that precise of an angle, which does affect some slicing results.

**Describe alternatives you've considered**
Allowing the drag method to use .5° and .25° increments rather than simple whole numbers, but this would be nowhere as convenient as simply entering the number in a box.

**Affected users and/or printers**
People who need precision. :)

**Additional context**

**Comment by Ghostkeeper** [comment] 2020-12-09 10:59
> Rotation is forced to 1° increments (even when "Snap Rotation" is disabled),

This is not true. The granularity of rotation is limited only by the pixel resolution of the mouse. However in the label where you're seeing how far it's rotating we round the angle to whole degrees (which is usually good enough). It is actually rotating more accurately.

I'll close this issue as a duplicate of https://github.com/Ultimaker/Cura/issues/2779.

**Closed by Ghostkeeper** 2020-12-09 10:59 UTC
Labels: Type: New Feature
