### ISSUE TITLE
3.0.4 Z Seam Alignment > "Random" option is with bug

### ISSUE THREAD

**Issue by Ando120** [Ultimaker/Cura#2785] opened 2017-11-15 08:59 UTC
Z Seam Alignment > "Random" option is with bug
Example with layer height 0.1 bug appears on layers 29-34
Dont travel along object("Combing Mode" is "All" )
Visible with some cylinder objects
![z_seam_alignment_random](https://user-images.githubusercontent.com/24602185/32827187-edf5b632-c9f3-11e7-9cf6-4c54784b7669.png)

**Comment by smartavionics** [comment] 2017-11-15 09:21
Looks like https://github.com/Ultimaker/CuraEngine/issues/625

**Comment by smartavionics** [comment] 2017-11-15 09:39
Hi @Ando120, if you set combing mode to "no skin" do the buggy travels go away?

**Comment by Ando120** [comment] 2017-11-15 11:05
With "no skin" travels are with retracton. So all is fine with "random"+ "no skin"
but I don't want to use it because too much retractions with some objects.

Made more tests and that height was related with that specific object.
Looks that bug appear only with thin wall.
![z_seam_alignment_random2](https://user-images.githubusercontent.com/24602185/32832749-3b691cae-ca05-11e7-8e35-eda93ffdcd4a.png)

If I redesign my object then I can avoid that bug.

**Comment by Ghostkeeper** [comment] 2017-11-25 14:08
I can't reproduce this bug. I'm using a little tube that I made to look like yours: [Tube.zip](https://github.com/Ultimaker/Cura/files/1503123/Tube.zip)
But it doesn't create any such travel moves through the object if Combing Mode is set to All.

**Comment by Ando120** [comment] 2017-11-27 07:25
Resize your object to 110% then it appear.

**Comment by Ghostkeeper** [comment] 2017-12-05 22:08
Indeed it does! Seems like we've found some good reproduce steps for https://github.com/Ultimaker/CuraEngine/issues/625 then. But I'll close this as a duplicate. Indeed it seems to be the same bug.

**Closed by Ghostkeeper** 2017-12-05 22:08 UTC
