### ISSUE TITLE
Bed temperature being set after Build Plate Temperature set to 0

### ISSUE THREAD

**Issue by galamdring** [Ultimaker/Cura#989] opened 2016-09-14 13:27 UTC
Running Cura 2.3.0-Beta.
In any profile, I set Build Plate Temperature to 0. In the GCode, M190 S60.000000 is still being added as the first step.

**Comment by nallath** [comment] 2016-09-15 07:37
This should be fixed for the next version. Could you try to set it to 20 degrees to see if that works? There was an issue with setting it to 0.

**Comment by Ghostkeeper** [comment] 2016-09-15 07:45
Probably a duplicate of #960. This has since been fixed.

**Closed** 2017-11-14 20:31 UTC
Labels: help wanted
