### ISSUE TITLE
Wrong Initial Layer Height in Gcode

### ISSUE THREAD

**Issue by drchopper** [Ultimaker/Cura#4218] opened 2018-08-09 16:18 UTC
**Application Version**
Cura 3.4.1

**Platform**
Tevo Tarantula

**Printer**
Tevo Tarantula

**Steps to Reproduce**
Set Initial Layer Height to 0.3mm

**Actual Results**
G0 F4800 X35.935 Y86.1 Z0.36

**Expected results**
G0 F4800 X35.935 Y86.1 Z0.30

**Additional Information**
The Initial Layer Height in the Gcode is always increased by 20% compared to the Initial Layer Height set in Cura 3.4.1

**Comment by ChrisTerBeke** [comment] 2018-08-09 21:31
Can you share a project file (.curaproject.3mf) that contains all the settings? Otherwise we can't debug this.

**Comment by drchopper** [comment] 2018-08-10 14:33
[bug.zip](https://github.com/Ultimaker/Cura/files/2278244/bug.zip)

**Comment by Ghostkeeper** [comment] 2018-10-11 13:38
This seems to be fixed in 3.5. I don't reproduce the issue. Here's a few lines of g-code where the initial layer's Z coordinate is set:

    ;LAYER_COUNT:99
    ;LAYER:0
    M107
    G0 F3600 X89.623 Y89.349 Z0.3

Can you also try this in 3.5, Drchopper?

**Comment by diegopradogesto** [comment] 2019-09-13 14:45
Indeed, this is fixed now.

**Closed by diegopradogesto** 2019-09-13 14:45 UTC
