### ISSUE TITLE
perspective vs orthographic view in CURA

### ISSUE THREAD

**Issue by darkdvd** [Ultimaker/Cura#3159] opened 2018-01-20 11:43 UTC
Please add to CURA a button to switch between perspective and orthographic view, because "perspective" is unusable to fine move a model.

**Comment by Ghostkeeper** [comment] 2018-01-20 12:19
Duplicate of https://github.com/Ultimaker/Cura/issues/2545.

The problem with this is that we'd need a different way to zoom as well.

**Closed by Ghostkeeper** 2018-01-20 12:19 UTC

**Comment by darkdvd** [comment] 2018-01-20 12:26
Excuse me Ghostkeeper but I don't understand why you need a diffrent way to zoom ?

**Comment by Ghostkeeper** [comment] 2018-01-20 12:31
Currently we zoom by moving the camera closer. The thing about orthographic projections is that things don't become larger when they get closer. So zooming like we do now has no effect at all.

**Comment by darkdvd** [comment] 2018-01-20 12:58
For perspective : move the camera closer
For othographic : change the camera view angle

**Comment by darkdvd** [comment] 2018-01-20 13:07
the bad idea in "CameraTool.py"

#   Note that zooming is performed by moving closer to or further away from the origin ("dolly")
#   instead of changing the field of view of the camera ("zoom")

**Comment by fieldOfView** [comment] 2018-01-20 15:08
And it is not just zooming that would need a “doover”; panning would need to change too.

**Comment by krz4tw** [comment] 2019-03-13 13:31
Was about to add a feature request on this as well. Id like to have it to be able to postion supportblockers precisely.

The zooming and panning should be quite easy to implement if you only enable orthographic in Top down, left, right,.... mode when you choose them via the little cube icons in the top right corner. Those 3-side projections are by far the most useful way for orthographic projection. I don´t need to orbit around in orthographic view.

**Comment by jmsaltzman** [comment] 2019-03-13 17:37
For reference, coming from an engineering and CG camera background: when you move the camera in and out, call it "dolly." When you change the view itself, call it "zoom." Makes these discussions much easier.

**Comment by darkdvd** [comment] 2019-03-13 18:04
And let's keep in mind that perspective view is about representing the object as we see it, while orthographic view is about representing the object as it is.

**Comment by MoonCactus** [comment] 2019-03-19 13:55
Also, having an ortho view makes it much easier to layout multiple parts on the printbed: checking the empty margin around multiple parts from above is not easy. Only layer views can help here but it is not convenient.
BTW, I would certainly not call this feature request a duplicate of #2545 which really is about measuring the part (as the titles tell: measurement vs. orthographic). They might arguably be related, but closing this one by redirecting it to the other (deferred) feature request is wrong imho.

**Comment by Ghostkeeper** [comment] 2019-03-20 08:07
It is considered a duplicate, because in an ideal world an issue addresses a problem rather than proposing a solution to the problem. That ticket addresses a need: Some way to measure stuff.

**Comment by MoonCactus** [comment] 2019-03-21 19:50
But in a real world, they are just two feature requests ("measure stls" is not a trivial functional duplicate of "have an orthographic projection"). Only the comments may converge: one of the way #2545 _could_ be implemented _might_ help implement this one as well, but not necessarily. This is far from obvious tousers that might keep asking for this projection (now, #5426 and possibly #4806 are real duplicates of this #3159 imo, but #2545 looks like another tool). No biggie :)

**Comment by darkdvd** [comment] 2019-07-16 15:03
Thank You for the **Orthographic** view !!!!!!

**Comment by darkdvd** [comment] 2019-07-16 15:09
![DVHMwt2X4AAccE1](https://user-images.githubusercontent.com/16816760/61306147-5adc0580-a7ec-11e9-8654-2184855cd961.gif)

**Comment by fpdotmonkey** [comment] 2021-04-04 01:12
For posterity, this feature was added with https://github.com/Ultimaker/Cura/pull/5768
