### ISSUE TITLE
5.3.1 profiles not appearing/importing into 5.4.0 stable 

### ISSUE THREAD

**Issue by EoinLX** [Ultimaker/Cura#16011] opened 2023-07-05 10:05 UTC
### Application Version

5.4.0

### Operating System

Windows 11

### Printer

Elegoo 3 Plus & Creality 5 pro

### Reproduction steps

Upgraded to 5.4.0
Noticed profiles weren't there.
Exported from 5.3.1
Attempted import into 5.4.0 was unsuccessful.

### Actual results

Results are that all my profiles for both printers won't import to 5.4

### Expected results

That the profiles should import or carry over from previous versions.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[5.3.1 cura.log](https://github.com/Ultimaker/Cura/files/11956635/5.3.1.cura.log)
[5.4.0 cura.log](https://github.com/Ultimaker/Cura/files/11956637/5.4.0.cura.log)

**Comment by Jo-Con-El** [comment] 2023-07-30 07:11
I'm having the same problem.  I can upload a zip with my profiles from 5.3 so you can see that the upgrade is not working.

**Comment by karol-wojcik** [comment] 2023-08-04 11:19
Same thing on my end

**Comment by MariMakes** [comment] 2023-08-08 11:57
Hey @EoinLX,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

We've seen more reports of something wrong with the Elegoo Profiles upon installing. 
We are looking into this, but we are having some trouble finding what is happening.

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/16007
There are instructions for a workaround to get unstuck for now. 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/16007

**Closed by MariMakes** 2023-08-08 11:57 UTC
Labels: Type: Bug, Status: Triage
