### ISSUE TITLE
Sign in button does not work.

### ISSUE THREAD

**Issue by erickwill** [Ultimaker/Cura#12232] opened 2022-05-17 17:25 UTC
### Application Version

5.0.0

### Platform

Arch Linux Rolling
Desktop Manager: GNOME Shell 42.1
Issue with AppImage file.
### Printer

Tronxy X5SA

### Reproduction steps

Try to Sign in using Arch Linux or other distribution along with GNOME Shell 42.1.

### Actual results

It does not open any web browser allowing the log in process.
I also tried to open external link on Cura and it did also failed. I tried in 3 different laptops running Arch with similar configurations and same results.

### Expected results

It should open a web browser and allow the log in process. I tried with multiple web browsers.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8710373/cura.log)

**Comment by erickwill** [comment] 2022-05-18 13:30
> What are you using as a desktop environment (KDE/Gnome etc.)?
> 
> Can you try any other external link, such as the links under the app switcher menu?

I'm using Gnome. I also tried to open external link on Cura and it did also failed. I tried in 3 different laptops running Arch with similar configurations and same results.

**Comment by fvrmr** [comment] 2022-05-18 14:26
Are you using the AppImage?

**Comment by erickwill** [comment] 2022-05-18 15:21
> Are you using the AppImage?

Yes, I'm using the appimage.

**Comment by jellespijker** [comment] 2022-05-19 09:16
@MariskaMaas  FYI

**Comment by fvrmr** [comment] 2022-05-19 11:15
We discussed this with the team and will create a ticket for this.

**Comment by erickwill** [comment] 2022-05-19 11:26
Thanks! Looking forward for a fix.

**Comment by slabua** [comment] 2022-07-09 07:13
Still no go? I'm stuck with v4 because of this issue.

**Comment by fieldOfView** [comment] 2022-07-10 08:14
> I'm stuck with v4 because of this issue.

You don't *have to* sign in to use Cura.

**Comment by slabua** [comment] 2022-07-10 08:20
> > I'm stuck with v4 because of this issue.
> 
> You don't _have to_ sign in to use Cura.

Uh? I don't even have a Cura account.
All links are not working, plugins, update checker, everything that would open an url in the browser just does nothing, making v5 completely unusable for my workflow.

**Comment by slabua** [comment] 2022-07-10 08:22
Also not sure why issue 12527 has been closed in favour of the present one, since 12527 is actually the more general case.

**Comment by fieldOfView** [comment] 2022-07-10 09:42
Sorry, this issue is specifically about the sign in button, and you did not mention (before, in this issue) that you were having issues with other buttons.

I guess the other issue was closed as a duplicate because it shares the same underlying problem that a browser window is not opening.

**Comment by slabua** [comment] 2022-07-10 11:16
I see. I commented here because the other one was closed.
Then I guess it shouldn't have been closed as duplicate of this.
Waiting for a fix.

**Comment by MariMakes** [comment] 2022-08-22 14:23
Hey all.  

This should be fixed in Ultimaker-Cura-5.1.0-linux-modern.AppImage.asc
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.1.0

Thanks for reporting!

**Closed by MariMakes** 2022-08-22 14:23 UTC
Labels: Type: Bug, Status:  On Backlog
