### ISSUE TITLE
Not selecting multiple files

### ISSUE THREAD

**Issue by waln24** [Ultimaker/Cura#16196] opened 2023-07-18 02:07 UTC
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Creality Ender - 3 Pro

### Reproduction steps

Trying to add multiple files to the build plate area to slice

### Actual results

does not allow multiple file selection. Organize drop has multiple options greyed out.

### Expected results

should allow for multiple file selection

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/28719770/7aa5032f-c296-420f-a880-74b85d9a30bd)

**Comment by GregValiant** [comment] 2023-07-18 09:41
Thanks for the report.
The "Open" dialog doesn't allow multiple files and it's a bug that has been previously reported.  The Cura team is aware of this and it should be fixed in the next release.
In the meantime you can still select multiple files in explorer and drag them onto the Cura build plate.
I'll mark this as a duplicate of #16052 and go ahead and close it.  I hope you understand.

**Closed by GregValiant** 2023-07-18 09:41 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation
