### ISSUE TITLE
The numbers overlapping measurement units

### ISSUE THREAD

**Issue by JUSTDO1** [Ultimaker/Cura#9704] opened 2021-04-26 13:06 UTC
### Application Version

4.9.0

### Platform

win 10

### Printer

S2+

### Reproduction steps

Just open the program

### Actual results

The numbers overlapping measurement units

### Expected results

The numbers overlapping measurement units

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/19169685/116086978-0ea04380-a6a9-11eb-87aa-1a38091f15d6.png)
gdf

**Comment by fvrmr** [comment] 2021-04-26 13:22
Hi @JUSTDO1 thank you for your report.
This is a duplicate of #9667 that's why I will close this issue.
Hope you understand!

**Closed by fvrmr** 2021-04-26 13:22 UTC
Labels: Type: Bug
