### ISSUE TITLE
Multiply objects causes covering objects

### ISSUE THREAD

**Issue by quiiiebong** [Ultimaker/Cura#14672] opened 2023-02-25 07:41 UTC
### Application Version

5.3.0-beta.2

### Platform

Windows 11

### Printer

Anycubic i3

### Reproduction steps

Load object. right click, multiply object, amount:1

EDIT: issue also occurs when opening multiple Objects at once

### Actual results

the new object is not separated but covers the source object

### Expected results

Objects shall be separated. worked well with cura 5.2.2

screenshot of wrong behaviour
![cura_5 3 0-beta 2_covering objects](https://user-images.githubusercontent.com/89332264/221345189-f54625ca-7e0d-4e48-becc-c35a8c8d3940.png)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Object: https://www.thingiverse.com/thing:950452/files -> wind wheel mount

**Comment by MariMakes** [comment] 2023-03-07 13:07
Hey @quiiiebong,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

I was able to reproduce your behavior.
But they did not overlap once I had the "Ensuer Models are kept Apart" checked in the preferences:
![image](https://user-images.githubusercontent.com/40423138/223430385-0d57fc3d-54b5-4a49-b2bd-c2742f97c17d.png)

To me, it doesn't seem like a bug in Ultimaker Cura anymore, since there is a solution in place. 
Would you still like to keep this issue open or do you agree that we can close it?

**Comment by quiiiebong** [comment] 2023-03-07 16:44
Hello @MariMakes !

First - Thank You! - for having a look on the issue.

I confirm that with setting that switch the objects are now kept apart. However, in 5.2.2 it worked in default settings without activating this option. 5.3 does not deliver a printable result with the default installation settings. This should be the case.

Also, the placing is much worse than in 5.2.2. I opened the same set of objects in 5.2.2 and 5.3. While the result of 5.2.2 is usable without manual action, the result of 5.3 is not (the switch suggested by you enabled...)

  
Cura 5.2.2 (expected behaviour):
![Ashampoo_Snap_Dienstag, 7  März 2023_17h31m29s_005_](https://user-images.githubusercontent.com/89332264/223489137-09f0d0b3-6631-4cfe-8087-c10cfdecd1c9.jpg)

Cura 5.3
![Ashampoo_Snap_Dienstag, 7  März 2023_17h30m33s_004_](https://user-images.githubusercontent.com/89332264/223489134-2a3269a6-e51b-468a-8efb-311613b85de3.jpg)

The behaviour changed to the worse, so I would still see it as a bug.

**Comment by MariMakes** [comment] 2023-03-20 17:16
Hey @quiiiebong,

Sorry, it took us a while to get back to you 😞 
We've seen more reports of this. 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/14112
We have a ticket on our backlog with the intent to improve this behavior.

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/14112
Thanks for your report 👍

**Closed by MariMakes** 2023-03-20 17:16 UTC
Labels: Type: Bug, Status: Triage
