### ISSUE TITLE
Slicing failed on all files - tried debugging myself

### ISSUE THREAD

**Issue by johnneerdael** [Ultimaker/Cura#18846] opened 2024-04-08 00:13 UTC
### Cura Version

5.7.0 / 5.6.0

### Operating System

Windows 11

### Printer

FLSUN V400

### Name abnormal settings

Slicing fails with custom and stock settings/profiles

### Describe model location

No changes do not affect slicing

### Describe your model

Yes, in older cura versions

### Add your .zip here ⬇️

[cura.zip](https://github.com/Ultimaker/Cura/files/14899495/cura.zip)
File contains whole config folder as well and error files

**Comment by johnneerdael** [comment] 2024-04-08 00:14
Already disabled most plugins and even some stock ones that showed errors. Trying to rollback to 5.5.0 to see if that works.

**Comment by johnneerdael** [comment] 2024-04-08 00:23
I can confirm that slicing in 5.5 works without issues.

**Comment by HellAholic** [comment] 2024-04-08 12:16
Hey @johnneerdael ,
I looked at the log files you've provided, the error seems to be caused by missing a setting `prime_tower_enable="False"` which causes the error:
`[error] Trying to retrieve setting with no value given: prime_tower_mode`

Could you check a few steps to see if the issue will be resolved in 5.6/5.7?

- Close all cura versions (if any)
- Go to the configuration folder
- Delete the 5.6 and 5.7 folders but keep the 5.5 working version
- Start Cura 5.7
- Load the project and slice

If the above steps resolved the issue:
- Could you please specify how you added the profiles for your printer?

There might be a upgrade script step missing, hence my question.
Note that I can slice the project using your configuration and model, so I'm wondering what steps I'm missing or could be the cause.


Cheers!

**Closed** 2024-04-22 12:49 UTC
Labels: Type: Bug, Status: Needs Info, Slicing Error :collision:
