### ISSUE TITLE
Cura crashes while adding monoprice printer

### ISSUE THREAD

**Issue by cf5000cf** [Ultimaker/Cura#3290] opened 2018-02-12 02:38 UTC
Cura 3.2.0 crashes while adding any Monoprice printer on Windows 10

**Comment by jackha** [comment] 2018-02-12 08:46
The issue should be fixed in the 3.2 release version.

Is it the 3.2.0 or the beta? Did you use the beta? In that case you should delete the cache directory: https://github.com/Ultimaker/Cura/wiki/Cura-Preferences-and-Settings-Locations

Duplicate of #3246

**Closed** 2018-02-12 08:54 UTC

**Comment by syadnom** [comment] 2018-03-08 03:54
3.2.1 still does it.

**Comment by jackha** [comment] 2018-03-08 15:57
I started clean (in linux, but that shouldn't matter), added both the Monoprice V1 and V2 without problems.

Did you clean your user folder after crashing? Does it still crash? If so, please share the logs with us so we can have a look at it.

**Comment by syadnom** [comment] 2018-03-08 15:59
Started 100% fresh.  I can only get the mini delta's profile to run in 3.0.4, which is acknowledged on the monoprice download site for the profile.
