### ISSUE TITLE
Cura 4.8.0-Beta Omits Tree Support If Support X/Y Distance Is Too Large.

### ISSUE THREAD

**Issue by mbmast** [Ultimaker/Cura#8655] opened 2020-10-29 22:56 UTC
Cura 4.8.0-Beta

Windows 10

CreateBot D600 Pro printer, but I don't think the printer is relevant.

You can see from the first screenshot that when Support X/Y Distance is set to 2, tree support is generated that supports backside of the brim of the hat: 

![Cura 4 8 Screen Shot Support  XY Distance 2](https://user-images.githubusercontent.com/15057985/97640371-d1127480-19fd-11eb-917f-193ca4a31f7f.png)

Now when Support X/Y Distance is set to 3, part of the tree support for the backside of the hat brim is lost:

![Cura 4 8 Screen Shot Support  XY Distance 3](https://user-images.githubusercontent.com/15057985/97640398-dc65a000-19fd-11eb-9403-36b990d7b055.png)

And finally, when Support X/Y Distance is set to 4, none of the tree support for the backside of the hat brim is generated.

![Cura 4 8 Screen Shot Support  XY Distance 4](https://user-images.githubusercontent.com/15057985/97640407-e12a5400-19fd-11eb-8e51-93053e425b81.png)

Steps to reproduce:

Use the provided .STL file and provided Cura profile, both contained in the attached zip file:

[Thanksgiving Turkey.zip](https://github.com/Ultimaker/Cura/files/5461661/Thanksgiving.Turkey.zip)

Simply performing a Slice with the Support X/Y Distance set to 2, 3 and 4 reproduces the problem.

Expected results:

I expect tree support generated for the backside of the hat brim regardless of the Support X/Y Distance setting.

**Comment by Ghostkeeper** [comment] 2020-11-02 12:33
Duplicate of https://github.com/Ultimaker/Cura/issues/8614.

**Closed by Ghostkeeper** 2020-11-02 12:33 UTC
Labels: Type: Bug
