### ISSUE TITLE
Unable to open any STL in 4.7

### ISSUE THREAD

**Issue by tslater2006** [Ultimaker/Cura#8235] opened 2020-08-25 17:13 UTC
**Application version**
4.7

**Platform**
Windows 10

**Printer**
Creality Ender 5

**Reproduction steps**
1. Open Cura 4.7
2. Open STL file

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/1731714/91206127-42ffd200-e6cc-11ea-982c-c959fcc5ebe8.png)

**Actual results**
Cura crashes

**Expected results**
It to not crash and to load the STL for printing.

**Project file**
N/A

**Log file**
I've submitted via the "Send Report"

**Comment by mrzottel** [comment] 2020-08-25 17:51
Any chance you are using octolapse and have the octolapse script in the starting gcode of your printer?

**Comment by tslater2006** [comment] 2020-08-25 17:55
I sure do.

[image: image.png]

**Comment by mrzottel** [comment] 2020-08-25 18:10
I added another issue with cura 4.7 not beeing able to cope with "=" signs in custom gcode, as used by this script. My workaround for now (aside from going back to 4.6.1 I used before) is either loosing the script for now and configuring octolapse by hand before each print or disable octolapse.

Unfortunately, I could only get cura 4.7 into an usable state again by removing all configuration from %appdata%/cura/4.7 and redo all my config.

**Comment by fieldOfView** [comment] 2020-08-25 18:14
This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/8230

**Comment by fieldOfView** [comment] 2020-08-25 18:21
> Unfortunately, I could only get cura 4.7 into an usable state again by removing all configuration from %appdata%/cura/4.7 and redo all my config.

That is somewhat unfortunate. I could have helped you remove just the offending =-signs in a text editor.
In the `definition_changes` folder, there are a couple of .inst.cfg files that you can open in a text editor to edit the custom start gcode you entered in Cura.

**Comment by tslater2006** [comment] 2020-08-25 18:26
I'm not convinced its a duplicate? the error message is referring to USB printer stuff, and this is when opening the model, not slicing it, why would whatever is in the start gcode (as referenced in #8230) have an effect at the point of just opening the STL.

**Comment by mrzottel** [comment] 2020-08-25 18:36
> > Unfortunately, I could only get cura 4.7 into an usable state again by removing all configuration from %appdata%/cura/4.7 and redo all my config.
> 
> That is somewhat unfortunate. I could have helped you remove just the offending =-signs in a text editor.
> In the `definition_changes` folder, there are a couple of .inst.cfg files that you can open in a text editor to edit the custom start gcode you entered in Cura.

Don't worry, it was not that much configuration, and most of it came from 4.6 backups and external text files. But I also tried to remove the = signs during testing, but that did not help much. It recovered the printer settings, but there seem to be follow up issues introduced (all materials were gone, which most likely causes the list index out of range issue in the crash). I guess this comes from loading and parsing the configuration with = signs and then saving the "broken" configuration again (opening and closing cura without loading a stl and causing the crash)

**Comment by starlord1980** [comment] 2020-08-25 23:45
Same problem here on Mac:
![Screenshot 2020-08-26 at 00 45 17](https://user-images.githubusercontent.com/28816350/91238651-70cd3100-e735-11ea-9217-5718bf94985e.png)

**Comment by fieldOfView** [comment] 2020-08-26 06:23
> I'm not convinced its a duplicate?

I have changed the wording above from "seems to be a duplicate"  to "could be a duplicate". However, the issue I linked to does also mention the crash when loading an STL. So I am fairly certain that it is indeed the same issue, and that it can be fixed by editing the files in `definition_changes` like I said above.

**Comment by Ghostkeeper** [comment] 2020-08-27 14:54
We have a fix for this issue (see [the PR](https://github.com/Ultimaker/Uranium/pull/633)). We hope to release it somewhere next week. Thanks for the reports!

It turns out that this had the same root cause as https://github.com/Ultimaker/Cura/issues/8230, although the symptoms were different.

**Closed by Ghostkeeper** 2020-08-27 14:54 UTC
Labels: Type: Bug

**Comment by Merkya87** [comment] 2020-08-27 15:43
Hello @Ghostkeeper I am having the exact same issue can i just pull the updates somehow now before waiting for the fix to be released?

Thanks in advance!

**Comment by fieldOfView** [comment] 2020-08-27 15:45
That depends how you installed Cura and what OS you are running it on.

**Comment by Merkya87** [comment] 2020-08-27 15:47
> That depends how you installed Cura and what OS you are running it on.

I had Cura 4.6 previously, I have windows 10. I removed my old 4.6 version but kept the configurations.

**Comment by fieldOfView** [comment] 2020-08-27 15:54
It is not *very* easily hackable, but it is possible. The following instructions come with no warranty, perform at your own risk.

* Download this file: https://raw.githubusercontent.com/Ultimaker/Uranium/4.7/UM/FastConfigParser.py
* From `C:\Program Files\Ultimaker Cura 4.7\` copy `python35.zip` to your desktop
* Open `python35.zip` in a decent zip application (eg 7zip)
* Navigate to the folder `UM` and remove the file `FastConfigParser.pyc`
* In its place, put the file you downloaded in the first step. Note that it is named `.py`, not `.pyc`. Keep it that way
* Close the zip application, and copy the zip back into the `C:\Program Files\Ultimaker Cura 4.7\` folder

That should do it. Or it could blow up your kitchen. Or something inbetween.

**Comment by Merkya87** [comment] 2020-08-27 16:11
> It is not _very_ easily hackable, but it is possible. The following instructions come with no warranty, perform at your own risk.
> 
> * Download this file: https://raw.githubusercontent.com/Ultimaker/Uranium/4.7/UM/FastConfigParser.py
> * From `C:\Program Files\Ultimaker Cura 4.7\` copy `python35.zip` to your desktop
> * Open `python35.zip` in a decent zip application (eg 7zip)
> * Navigate to the folder `UM` and remove the file `FastConfigParser.pyc`
> * In its place, put the file you downloaded in the first step. Note that it is named `.py`, not `.pyc`. Keep it that way
> * Close the zip application, and copy the zip back into the `C:\Program Files\Ultimaker Cura 4.7\` folder
> 
> That should do it. Or it could blow up your kitchen. Or something inbetween.

Awesome it works now thanks so much!

**Comment by fieldOfView** [comment] 2020-08-27 16:30
Did you check your kitchen?

**Comment by mrzottel** [comment] 2020-08-27 16:53
I repeated those steps and can confirm it works now. Thanks a lot!

**Comment by Merkya87** [comment] 2020-08-27 16:56
> Did you check your kitchen?

Kitchen is fine, my Ender 3 Pro is running good :)

**Comment by mrzottel** [comment] 2020-08-27 16:59
> Did you check your kitchen?

Mine is a wasteland - but thats caused by an uncatched exception in wife.dll ;)

**Comment by starlord1980** [comment] 2020-08-28 22:06
Doesnt seem to work on macOS. Replacing this file in:
/Applications/Ultimaker\ Cura.app/Contents/Resources/lib/python3.5/UM/FastConfigParser.pyc
just causes it to fail to launch. Restored the original from backup and it runs again.

I also noticed the linked file above is text, wheras the one in the Cura app package is not. Probably has something to do with it?

**Comment by mrzottel** [comment] 2020-08-28 22:39
.pyc is "compiled" python, while .py is the pure source code. 

If you just replace the FastConfigParser.pyc with FastConfigParser.py make sure, that you do not accidently rename FastConfigParser.py to FastConfigParser.pyc, because in this case, Python expects compiled code but gets uncompiled one.

**Comment by craig-dae** [comment] 2020-08-29 12:12
@Merkya87's solution confirmed to work for me

**Comment by PDServices** [comment] 2020-08-30 19:43
Works for me too, thanks

**Comment by derekslenk** [comment] 2020-08-31 14:14
I have this issue, but none of my start g-code even ported over so I don't have any remove to even test

**Comment by Ghostkeeper** [comment] 2020-09-01 13:31
> I have this issue, but none of my start g-code even ported over so I don't have any remove to even test

Try changing it to anything. Due to the same bug, the start g-code itself also gets cut off. Then the cut off part is reinterpreted as something else which causes the crash. If you change it, it should re-save the profile and hopefully fix the problem.

**Comment by derekslenk** [comment] 2020-09-01 17:39
> 
> 
> > I have this issue, but none of my start g-code even ported over so I don't have any remove to even test
> 
> Try changing it to anything. Due to the same bug, the start g-code itself also gets cut off. Then the cut off part is reinterpreted as something else which causes the crash. If you change it, it should re-save the profile and hopefully fix the problem.

I had to delete my old 4.6 folder from %APPDATA%\cura to get anything to work. I tried deleting the start code but that didn't fix it. I also uninstalled 4.7, removing preferences, and reinstalling didn't fix the issue without deleting the old APPDATA first.
