### ISSUE TITLE
Skin Overlap does not apply to Top Surface Skin Layers

### ISSUE THREAD

**Issue by geoffrey-young** [Ultimaker/Cura#10459] opened 2021-09-15 20:12 UTC
### Application Version

4.11.0

### Platform

OSX

### Printer

Voron 2

### Reproduction steps

slice a model with some perimeters, with at least one Top Surface Skin Layer, and an unusually large Skin Overlap value

### Actual results

the actual overlap of the Top Surface Skin Layer with the walls remains unchanged no matter what the value of Skin Overlap.  even if walls are not considered skin, this happens with or without Extra Skin Wall Count > 1.  for reference, all Top Layers that are not Top Surface Skin Layers behave appropriately.

### Expected results

the Top Surface Skin Layers should overlap in proportion to the Skin Overlap value, equal to the overlap that occurs in the non-Top Surface Skin Layers

### Checklist of files to include

- [x] Log file
- [X] Project file

### Additional information & file uploads

[2mm_washer.3mf.zip](https://github.com/Ultimaker/Cura/files/7172972/2mm_washer.3mf.zip)

<img width="1718" alt="Screen Shot 2021-09-15 at 4 07 58 PM" src="https://user-images.githubusercontent.com/1334642/133502244-a124d226-bf6c-4be6-95b2-792b902dae01.png">
<img width="1710" alt="Screen Shot 2021-09-15 at 4 06 09 PM" src="https://user-images.githubusercontent.com/1334642/133502245-e2b4b4be-1feb-43d8-a535-7ebab98e1d9d.png">

for reference, this is a lower Top Layer, showing the proper overlap
<img width="629" alt="Screen Shot 2021-09-15 at 4 14 02 PM" src="https://user-images.githubusercontent.com/1334642/133503146-f8c4b9e9-276d-445b-8186-e70a59890fbb.png">

**Comment by konskarm** [comment] 2021-09-21 15:15
Hi @geoffrey-young. Thank you for the report. I can reproduce the issue so I'll bring it up with the team for discussion.

**Comment by evtrados** [comment] 2021-09-22 08:43
Hello @geoffrey-young,

We discussed this issue with the team and we already had it on our backlog for some time. For the Cura devs, please check the internal ticket CURA-6550.

**Comment by Ghostkeeper** [comment] 2021-09-22 11:31
That makes this a duplicate of https://github.com/Ultimaker/Cura/issues/5758 then.

**Closed by Ghostkeeper** 2021-09-22 11:31 UTC
Labels: Type: Bug
