### ISSUE TITLE
Part failed to slice in front corner of build plate

### ISSUE THREAD

**Issue by RLute** [Ultimaker/Cura#17898] opened 2024-01-04 15:00 UTC
### Cura Version

5.6.0

### Operating System

Windows 10 enterprise

### Printer

fusion F410

### Name abnormal settings

set infill to 70%

### Describe model location

it slices when I move it towards the middle of the build plate 

### Describe your model

yes

### Add your .zip here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/46653285/4a42853a-81f1-4632-8858-8b391b09257f)
[Upper Wheel Adj Bushing rev2.zip](https://github.com/Ultimaker/Cura/files/13831448/Upper.Wheel.Adj.Bushing.rev2.zip)

**Comment by 5axes** [comment] 2024-01-04 15:09
looks like an other Tree Support issue : https://github.com/Ultimaker/Cura/issues/17741#issuecomment-1868413301

@ThomasRahm is it an issue already solved in your PR ?

**Comment by ThomasRahm** [comment] 2024-01-04 15:16
Is solved by it (It is the race condition one). It is a duplicate of https://github.com/Ultimaker/Cura/issues/17655 and https://github.com/Ultimaker/Cura/issues/17578 and https://github.com/Ultimaker/Cura/issues/17597

**Closed as completed** 2024-01-19 13:15 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:

**Comment by MariMakes** [comment] 2024-01-19 16:31
Even better news 😊, this fix is also included in the 5.7 Alpha, which has been released to analyze the incoming slicing crashes.
If this crash is blocking you in any way you can download the nightly build to continue printing (and to help us analyze the slicing crashes) 

You can find the downloads here https://github.com/Ultimaker/Cura/discussions/18080

**Comment by HellAholic** [comment] 2024-04-03 13:22
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
