### ISSUE TITLE
[Feature Request] Purge Line Option

### ISSUE THREAD

**Issue by KenLucke** [Ultimaker/Cura#9041] opened 2020-12-29 23:16 UTC
**Is your feature request related to a problem? Please describe.**
I know that I can create a purge line with my printer’s start-code.  In fact, I have the following start code:

```
; Machine Setup
M201 X500.00 Y500.00 Z100.00 E5000.00 ; Setup machine max acceleration
M203 X500.00 Y500.00 Z10.00 E50.00 ; Setup machine max feedrate
M204 P500.00 R1000.00 T500.00 ; Setup Print/Retract/Travel acceleration
M205 X8.00 Y8.00 Z0.40 E5.00 ; Setup Jerk
M220 S100 ; Reset Feedrate
M221 S100 ; Reset Flowrate
; End Machine Setup

G28 ; Home

M420 S1 Z5 ; use stored mesh, bed level on, fade height 5mm

; Purge Line Code
G92 E0 ; Reset Extruder
G1 Z2.0 F3000 ; Move Z Axis up
G1 X10.1 Y30.0 Z0.28 F5000.0 ; move away from clip
G1 X50.0 Y30.0 Z0.28 F5000.0 ; move around clip
G1 X50.0 Y5.0 Z0.28 F5000.0 ; Move to start position
G1 X250.0 Y5.0 Z0.28 F1500.0 E11 ; Draw the first line
G1 X250.0 Y5.3 Z0.28 F5000.0 ; Move back a little
G1 X50.0 Y5.3 Z0.28 F1500.0 E23 ; Draw the second line
G92 E0 ; Reset Extruder
G1 Z2.0 F3000 ; Move Z Axis up
; End Purge Line Code
```

However, there are times and models with which I do not want to create a purge line, but yet I want to leave the acceleration/jerk/etc settings in place, which requires me to either temporarily edit my start gcode, or manually edit the file after slicing.

**Describe the solution you'd like**
I’d like to see a “Create Purge Line” option, which would enable it to be easily turned on and off for each model. There should be options for Placement (Front, Back, Left or Right), Distance From Edge, and Length (the line would be centered [Distance from Edge] along whichever edge chosen).  

**Describe alternatives you've considered**
Continuing to manually edit either the machine setup each time (RPITA), creating another machine profile without the purge line, which requires creating all the other profiles associated with a machine, or manually editing the file after slicing.

**Comment by Ghostkeeper** [comment] 2021-01-06 13:55
Duplicate of https://github.com/Ultimaker/Cura/issues/9040. Probably accidentally clicked a button twice or Github has been having server issues again. Happens sometimes.

**Closed by Ghostkeeper** 2021-01-06 13:55 UTC
Labels: Type: New Feature
