### ISSUE TITLE
Custom bed logo not showing

### ISSUE THREAD

**Issue by JdeV987** [Ultimaker/Cura#19949] opened 2024-11-24 11:37 UTC
### Cura Version

5.9.0 (running from AppImage)

### Operating System

 Linux Mint 20.3 x86_64 

### Printer

Custom

### Reproduction steps

On 5.8.0 all 3 my custom bed logos are visible.
On 5.9.0 they are only visible when looking from the bottom.

### Actual results

Bed logos not visible when viewed from above.

### Expected results

Bed logos must be visible when viewed from above.

### Add your .zip and screenshots here ⬇️

When viewed from above on 5.8.0:
![bed-good](https://github.com/user-attachments/assets/aab642ae-6aad-4d76-bddd-9f36e4bc8658)

When viewed from above on 5.9.0:
![bed-top-wrong](https://github.com/user-attachments/assets/ffde58d1-ea15-4626-a61c-f3336f508802)

When viewed from below on 5.9.0:
![Bed-bot](https://github.com/user-attachments/assets/79cb6d8c-c383-4d54-8660-d2b74e3a1f37)

**Comment by GregValiant** [comment] 2024-11-24 21:36
Thanks for the report.
This appears to be a duplicate of #19935 .  There are some discussions on that thread that may help you.

I'll mark this as a duplicate and close it.  Let me know if you feel that your problem is different and this can be re-opened.

**Closed by GregValiant** 2024-11-24 21:36 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation
