### ISSUE TITLE
Strange preview result (like sunrays everywhere)

### ISSUE THREAD

**Issue by altimac** [Ultimaker/Cura#11274] opened 2022-01-16 11:50 UTC
### Application Version

4.12.1

### Platform

MacOS

### Printer

FLSun Speed Race

### Reproduction steps

Open the given STL
Slice
Preview

### Actual results

<img width="709" alt="image" src="https://user-images.githubusercontent.com/778986/149658696-9c117068-80d5-4228-9ec6-1669c71afe90.png">

### Expected results

A much more normal preview

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Here is the STL file [Mac_SE30_Nano_Dock_-_Thingiverse.stl.zip](https://github.com/Ultimaker/Cura/files/7876877/Mac_SE30_Nano_Dock_-_Thingiverse.stl.zip)

**Comment by GregValiant** [comment] 2022-01-16 13:43
Nice!
I don't get any of that.  I'm thinking it's an error in the visual representation.  If you create a Gcode from that slice, clear the build plate, and then open the Gcode in Cura how does it look?  Does it show those "Rainbow" moves?

**Comment by altimac** [comment] 2022-01-16 14:17
I do not know how to create gcode from a slice, but I quit Cura and reopen de same STL file... and it worked as expected 🤷‍♂️

**Comment by altimac** [comment] 2022-01-16 14:18
Note that I already had this bug with another STL file few days ago.

**Comment by GregValiant** [comment] 2022-01-16 14:54
After you slice the button will say "Save to Disk".  When you do that a gcode file will be created.  Just open it in Cura.
It does sound like a video system problem though.  Maybe you can update the video drivers?

**Comment by fvrmr** [comment] 2022-01-17 10:47
Hi @altimac thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/10387 so I will close this issue. 
Please continue the thread there.

**Closed by fvrmr** 2022-01-17 10:47 UTC
Labels: Type: Bug
