### ISSUE TITLE
Cura 4.7.1 individual scaling of models does not work

### ISSUE THREAD

**Issue by LordIshmael** [Ultimaker/Cura#8339] opened 2020-09-07 17:44 UTC
Cura 4.7.1
(The version of the application this issue occurs with.)

Windows 10 x64
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)

Formbot T-Rex 3.0
(Which printer was selected in Cura?)

**Reproduction steps**
0. rotated the model along Y-axis for 90°
1. deselect uniform scaling of model
2. typed in X-value
3. typed in y-value
4. typed in Z-value --> X-value jumps to some value
5. every time clicking on X or Z-value the other value jumps and the model increases size without control

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
the model should scale as entered without any problems

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by nallath** [comment] 2020-09-07 17:48
Duplicate of https://github.com/Ultimaker/Cura/issues/4136

**Closed by nallath** 2020-09-07 17:48 UTC
