### ISSUE TITLE
What I see is NOT what I get

### ISSUE THREAD

**Issue by Ex-Pilot** [Ultimaker/Cura#5524] opened 2019-03-28 09:33 UTC
I printed an STL file but what I got was not what I saw in Cura and in FreeCAD for that matter. Unfortunately I can't attach my STL file.

Without the possibility to attach the file it's difficult to explain my problem.

**Comment by smartavionics** [comment] 2019-03-28 09:37
OK, so what would be good is if you could save the project file (File -> Save), then zip up the .3mf file and attach the zip to this issue. Thanks.

**Comment by Ex-Pilot** [comment] 2019-03-28 10:58
[CCR10S_SS_TopDeck_V2.zip](https://github.com/Ultimaker/Cura/files/3017554/CCR10S_SS_TopDeck_V2.zip)

File attached.

In the final print I miss the two rings around the gun turrets. They should measure 1x1 mm. Instead I get a wall with a thickness of 2 mm.

**Comment by smartavionics** [comment] 2019-03-28 11:05
Thanks for the project file. Just sliced it and it looks like I would expect, a wall with a wider top and the required support. What's wrong with that?

![Screenshot_2019-03-28_11-02-48](https://user-images.githubusercontent.com/585618/55152913-3975e180-5149-11e9-930a-304397c9bc8e.png)

![Screenshot_2019-03-28_11-05-03](https://user-images.githubusercontent.com/585618/55152992-5b6f6400-5149-11e9-9325-7ac64a6a906c.png)

**Comment by Ex-Pilot** [comment] 2019-03-28 11:10
I hate this. I didn't ask for support as it's not needed for this print but it must have been activated without my notice.

**Comment by smartavionics** [comment] 2019-03-28 11:12
Well, it's no good complaining to me, you need the support department (hahahahaha!)

**Comment by Ex-Pilot** [comment] 2019-03-28 11:16
Oh my God. I'm still laughing. Thank you for your help. The image you provided showed it all.

Support department!! Well, yes - of course.

**Comment by Ghostkeeper** [comment] 2019-03-29 09:41
As far as I can see from that 3MF file, support was activated manually by the user. It's not enabled from any of the profiles of that printer.

**Comment by diegopradogesto** [comment] 2019-05-03 11:14
Closing this issue then, since it's expected behaviour.

**Closed by diegopradogesto** 2019-05-03 11:14 UTC
