### ISSUE TITLE
Pause at layer - Wrong layer

### ISSUE THREAD

**Issue by tlhintoq** [Ultimaker/Cura#7106] opened 2020-02-15 21:42 UTC
Pause at height - setting the layer - is wrong by 2 layers.

Seems like its for two reasons.

1. The display is 1-indexed.  Meaning the display starts at layer 1.  But the code, and gGcode, is 0-indexed meaning the first layer is layer zero.  This causes the pause to be off by a layer compared to what the user is looking at on screen.
2. The verbiage doesn't match the logic.  The terms used in the UI is "Pause **at** layer ___".  'At' meaning the start of.  But in reality the pause takes place **after** the layer specified is done.  Its really "Pause **after** layer ____" - so there is a second layer descripancy between what the user is looking at, and when the pause takes place.

I'm just used to it and automatically find the layer I want the new color to start on, then subtract 2 when I set up the plug-in.  But new users have to be getting frustrated with this waste of time and material.

**Comment by Ghostkeeper** [comment] 2020-02-18 13:00
Duplicate of https://github.com/Ultimaker/Cura/issues/5085.

**Closed by Ghostkeeper** 2020-02-18 13:00 UTC
Labels: Type: Bug
