### ISSUE TITLE
[4.6.2] Settings Dialog Doesn't Properly Inherit Desktop Theme

### ISSUE THREAD

**Issue by will-janz** [Ultimaker/Cura#8110] opened 2020-07-25 22:40 UTC
**Application version**
4.6.2 AppImage

**Platform**
Kubuntu 20.04

**Printer**
N/A

**Reproduction steps**
1. Run Cura AppImage in Kubuntu 20.04 with Breeze Dark theme
2. Open preferences 
3. Some text has extremely low contrast (materials section is especially egregious)

**Screenshot(s)**
![Screenshot_20200725_162948](https://user-images.githubusercontent.com/6629321/88467472-ca231580-ce94-11ea-886f-3d7f4cfbd96a.png)
(Using Ultimaker Dark theme)

**Actual results**
Certain sections are completely unreadable.

**Expected results**
Readable dark mode text.

**Project file**
N/A

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/4976801/cura.log)

**Additional information**
Problem persists in Ultimaker Dark and Colorblind Assist Dark.

**Comment by will-janz** [comment] 2020-07-25 23:29
System dark theme with Ultimaker Dark:
![Screenshot_20200725_165946](https://user-images.githubusercontent.com/6629321/88468076-87187080-ce9b-11ea-9bca-95e531da9217.png)


System light theme with Ultimaker Dark:
![Screenshot_20200725_171644](https://user-images.githubusercontent.com/6629321/88468070-7bc54500-ce9b-11ea-99d3-26abb86173cf.png)

It seems like some backgrounds aren't getting the correct color settings. I'm not familiar with this ecosystem, but if someone would like to point out what files to look at (I've poked around and I'm completely lost,) I'd like to help.

**Comment by nallath** [comment] 2020-07-27 14:47
These pages can be found here https://github.com/Ultimaker/Cura/tree/master/resources/qml/Preferences

**Comment by Ghostkeeper** [comment] 2020-07-28 09:59
Duplicate of https://github.com/Ultimaker/Cura/issues/5490.

See also the workarounds they posted there.

**Closed by Ghostkeeper** 2020-07-28 09:59 UTC
Labels: Type: Bug
