### ISSUE TITLE
Cura 4.1.0 crashes after slicing

### ISSUE THREAD

**Issue by allenlawrence** [Ultimaker/Cura#5990] opened 2019-07-08 16:59 UTC
Every time I load up stl and slice it while saving gcode as soon as I click "Save" the whole software crashes. Please, devs look into the issue.
[cura.log](https://github.com/Ultimaker/Cura/files/3369425/cura.log)

**Comment by allenlawrence** [comment] 2019-07-08 17:01
![Untitled5](https://user-images.githubusercontent.com/52664272/60828470-150db480-a1d0-11e9-8c4b-233f0be97871.png)

**Comment by Ghostkeeper** [comment] 2019-07-09 07:33
Duplicate of https://github.com/Ultimaker/Cura/issues/5937

**Closed by Ghostkeeper** 2019-07-09 07:33 UTC
Labels: Type: Bug
