### ISSUE TITLE
[5.4.0] Can't preview slicing with custom filament

### ISSUE THREAD

**Issue by RudahXimenes** [Ultimaker/Cura#16048] opened 2023-07-07 14:09 UTC
### Cura Version

5.4.0

### Operating System

Acer Aspire 5, Ryzen 7 5700u, Arch Linux, using Cura via Flatpak

### Printer

Stock Anycubic i3 Mega S; Printer doesn't matter to this bug

### Reproduction steps

1. Go to `Preferences`
2. Go to `Materials` and `Create new`
3. Fulfill everything
4. Slice anything with the new filament selected

### Actual results

It keeps forever at `Processing layers 99%`

![https://i.imgur.com/muUsKeE.png](https://i.imgur.com/muUsKeE.png)

However it still generate properly the GCode and I can use it to print

The issue is that I can't preview my slicing

### Expected results

Allow me to preview my slicing before send to printing

### Add your .zip and screenshots here ⬇️

[Cura.zip](https://github.com/Ultimaker/Cura/files/11982816/Cura.zip)

**Comment by MariMakes** [comment] 2023-08-08 11:52
Hey @RudahXimenes,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/14080
We have a ticket on our backlog with the intent to improve this behavior.
Your testcase is super helpful because we thought it was only happening on specifically BiQu printers. 
Thanks for the extra info. 

Do you have a project file for us? It contains the printer and settings we can use for testing a potential fix. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser. 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/14080

**Closed by MariMakes** 2023-08-08 11:52 UTC
Labels: Type: Bug, Status: Triage
