### ISSUE TITLE
Cura ignores overlap settings when printing One at a Time

### ISSUE THREAD

**Issue by reneroth** [Ultimaker/Cura#11119] opened 2021-12-23 15:07 UTC
### Application Version

4.12.1

### Platform

Mac OS

### Printer

Ender 5 Pro

### Reproduction steps

1. loaded model into Cura
2. loaded second model to act as overlap setting modifier
3. adjusted infill density setting for the overlap

### Actual results

Cura ignores the setting modifier

### Expected results

overlapping parts should have the changed infill density

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This happens with all settings, they all get ignored, no matter if I choose "Infill mesh only" or "Cutting mesh". Tried different models for setting the overlap too, made no difference.
It DOES work as expected when using one of the blocks created by adding a "Support Blocker", not with other STLs.

<img width="1731" alt="Screenshot 2021-12-23 at 16 04 39" src="https://user-images.githubusercontent.com/11065422/147258456-6f2d12a1-d2e5-44d3-8260-fbe97d7f3cbd.png">

**Comment by GregValiant** [comment] 2021-12-24 16:59
It works for me with Infill Mesh and two STL's.  Save a project file, Zip it and post it.
![image](https://user-images.githubusercontent.com/64202104/147365801-0d1cdc5b-f522-4e34-b401-224e45926ea3.png)

**Comment by reneroth** [comment] 2021-12-25 08:47
Amended the ticket title to add important information I just found out - this only happens if the print sequence is set to "One at a Time", at which point only the blocks created by the support blocker will have any effect.

Thank you for looking into this, and Merry Christmas!

[overlap-bug.3mf.zip](https://github.com/Ultimaker/Cura/files/7775644/overlap-bug.3mf.zip)

**Comment by fieldOfView** [comment] 2021-12-25 11:04
The workaround is to group the model and the modifier.

**Comment by fieldOfView** [comment] 2021-12-25 11:13
Meshes created by the support blocker tool are "parented" to the mesh you add them to. So CuraEngine sees that they belong together.

**Comment by reneroth** [comment] 2021-12-25 15:29
> The workaround is to group the model and the modifier.

Thank you! This helps tremendously - still think it's a bug so keeping this ticket open :) 

Also just using the opportunity to thank you for the wealth of Cura plugins you've provided us with <3

**Comment by Ghostkeeper** [comment] 2021-12-31 14:07
Duplicate of https://github.com/Ultimaker/Cura/issues/9219.

**Closed by Ghostkeeper** 2021-12-31 14:07 UTC
Labels: Type: Bug
