### ISSUE TITLE
support brim

### ISSUE THREAD

**Issue by niccolobagnaroli** [Ultimaker/Cura#15383] opened 2023-04-28 20:31 UTC
### Application Version

5,3

### Platform

windows 11

### Printer

flsun super racer

### Reproduction steps

selected support brim
tried different brim widths

### Actual results

never created an actual support brim, with supports starting from layer 2 therefore not adhering to the buildplate

### Expected results

the brim should be created improving support adhesion

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

the problem persists changing bottom distance to 0

**Comment by GregValiant** [comment] 2023-04-29 01:02
Thanks for the report.
This is a duplicate of a couple of other reports about problems (#14983) with the support brim.  It seems there is an interference between the "Build Plate Adhesion" and the Support Brim.  If you set the Build Plate Adhesion to Skirt or Brim you should get the Support Brim.  You can set the "Brim Distance" to 1 or 2mm and the brim will not touch the part.
The Cura team is aware of this bug so I'll go ahead and close this.  I hope you understand.

**Closed by GregValiant** 2023-04-29 01:02 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation
