### ISSUE TITLE
Show Z height in preview mode

### ISSUE THREAD

**Issue by guestisp** [Ultimaker/Cura#5364] opened 2019-02-26 11:25 UTC
In preview mode, please add Z height in addition to layer number, like Slic3r.

Sometimes is usefull to see which height is related to which layer or viceversa

**Comment by Ghostkeeper** [comment] 2019-02-26 12:48
Duplicate of https://github.com/Ultimaker/Cura/issues/2536

**Closed by Ghostkeeper** 2019-02-26 12:48 UTC
