### ISSUE TITLE
[4.6.1] Tree support z distance not right

### ISSUE THREAD

**Issue by berberic2** [Ultimaker/Cura#7861] opened 2020-06-02 12:54 UTC
**Application version**
4.6.1

**Platform**
Linux

**Printer**
Monoprice Delta Mini

** Report**
If _**Tree Support**_ is selected (and normal support diabled) the distance between support and object is too big. As far as I can tell it’s add one layer to the normal distance calculated from _**Z Support Distance**_.
With _**Support Interface**_ enabled it gets even worse.

**Comment by mahtDFR** [comment] 2020-06-03 08:14
Please save a project file (File -> Save...), zip up the .3mf file and attach to this issue so I can try to reproduce it with the same settings as you.

**Comment by mahtDFR** [comment] 2020-06-03 08:21
Ah, looks like your right. I reproduced it in Windows 10 using the MP Mini Delta profile that ships with Cura.
Is that the profile you used?

![image](https://user-images.githubusercontent.com/17821912/83613317-e33dd300-a583-11ea-9c88-1ebde11a11a0.png)

**Comment by Ghostkeeper** [comment] 2020-06-03 14:37
Duplicate of https://github.com/Ultimaker/Cura/issues/5759. There are some more examples there and analysis of what's causing this.

**Closed by Ghostkeeper** 2020-06-03 14:37 UTC
Labels: Status: Needs Info, Type: Bug
