### ISSUE TITLE
Ironing on Different Layers

### ISSUE THREAD

**Issue by skl111** [Ultimaker/Cura#12519] opened 2022-06-14 15:30 UTC
### Is your feature request related to a problem?

I would like to enable Ironing on select surface layers as some need it and some do not on some of my models. Currently It can only be enabled on the all or just the top layer.

### Describe the solution you'd like

I would like and option to specify the layers at which ironing can be enabled instead of selecting all layers.

### Describe alternatives you've considered

None that I know of to consider

### Affected users and/or printers

Anyone who uses ironing would benefit from this.

**Comment by nallath** [comment] 2022-06-15 11:26
Duplicate of #12519

**Closed by nallath** 2022-06-15 11:26 UTC
Labels: Type: New Feature
