### ISSUE TITLE
Does not like tree supports

### ISSUE THREAD

**Issue by rw-donaldp** [Ultimaker/Cura#17023] opened 2023-10-18 13:50 UTC
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Anycubic Chiron

### Name abnormal settings

It's failing when I try to add tree supports. Slices OK without supports or normal supports.

### Describe model location

Still fails when not near edge  but seems OK rotate away from edge.

### Describe your model

Slices OK with normal supports.

### Add your .zip here ⬇️

[AC_PUG RH CON ROD BB-OFFSET.zip](https://github.com/Ultimaker/Cura/files/13026344/AC_PUG.RH.CON.ROD.BB-OFFSET.zip)

**Comment by GregValiant** [comment] 2023-10-18 14:11
Thanks for the report.
The model has some serious errors.  When top surfaces are colored red it means that the surfaces are inside-out.  When that is the case Cura can't figure out where the inside of the model is.
![image](https://github.com/Ultimaker/Cura/assets/64202104/6fe311e9-029d-4cf1-8476-b270c067df3d)

So your model needs repair.  MS 3D Builder is available in the Microsoft store and it's pretty good at making repairs.

There is a bug in 5.4.0 that can often be fooled by moving, rotating the model or changing the Initial Layer Height by a little bit.  The bug seems to be more prevalent in Windows 11 systems.
I'll go ahead and close this as it is either a duplicate of an often reported bug, or the problem is the model.  I'll close this as well.  I hope you understand.
This is the repaired model in 5.4.0.
![image](https://github.com/Ultimaker/Cura/assets/64202104/ac4e11b3-20ed-41fa-8373-c6293f2f407c)

**Closed by GregValiant** 2023-10-18 14:11 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error :collision:
