### ISSUE TITLE
Supports inside model

### ISSUE THREAD

**Issue by Randy1727** [Ultimaker/Cura#11273] opened 2022-01-16 08:17 UTC
### Application Version

4.13

### Platform

Windows 11

### Printer

CR-10 MAx

### Reproduction steps

Tree supports being placed inside model. 
![image](https://user-images.githubusercontent.com/78997080/149652454-1a5219fb-67a3-43c2-a483-b4ebdd467f71.png)

![image](https://user-images.githubusercontent.com/78997080/149652428-e9ff1533-d0fa-4cdb-9e35-71c2d64f250b.png)
![image](https://user-images.githubusercontent.com/78997080/149652431-0a3df8ff-c424-4552-8f51-f735934d2ceb.png)

### Actual results

Supports printed inside model

### Expected results

Tree supports outside model. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

After slicing with tree supports in 4.13 it places some supports inside model where not needed and never utilized.

**Comment by fvrmr** [comment] 2022-01-17 10:13
Hi @Randy1727 thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11258 and we have a ticket on our backlog for this.
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2022-01-17 10:13 UTC
Labels: Type: Bug
