### ISSUE TITLE
CR30 vents

### ISSUE THREAD

**Issue by Kingpin1983** [Ultimaker/Cura#17548] opened 2023-12-07 10:12 UTC
### Cura Version

5.6.0

### Operating System

windows 11

### Printer

creality ender 3 s1

### Describe model location

centered on buil plate

### Describe your model

replacement vents for cr30

### Add your .zip here ⬇️

[cr-30-printmill-fan-cowl-s.zip](https://github.com/Ultimaker/Cura/files/13598603/cr-30-printmill-fan-cowl-s.zip)

**Comment by GregValiant** [comment] 2023-12-07 14:26
Thanks for the report.
This might be a problem with Cura's interaction with Windows 11.
Try moving the models, rotating the models, changing the initial layer height and they might slice.  I didn't have any trouble on my Win10 machine.

I'll mark this as a duplicate of the growing pile of "won't slice" reports and the Cura team will take a look.

**Comment by Kingpin1983** [comment] 2023-12-07 14:28
I managed to get it to slice by spamming the slice button... 😕
________________________________

**Comment by GregValiant** [comment] 2023-12-07 15:02
Nice job on the workaround.  I'll go ahead and close this then.

**Closed by GregValiant** 2023-12-07 15:02 UTC
Labels: Type: Bug, Status: Under Investigation, Slicing Error :collision:
