### ISSUE TITLE
[4.2.1] Color problem with Settings-GUI on linux and dark KDE/QT-theme (Breeze dark)

### ISSUE THREAD

**Issue by esopalumpa** [Ultimaker/Cura#6195] opened 2019-08-12 13:44 UTC
**Application version**
4.2.1 probably older versions too.

**Platform**
Linux, KDE, Theme “Breeze Dark”

**Printer**

Independent of printer

**Reproduction steps**

Start Cura on a KDE-system with Breeze dark theme and go to settings.

**Actual results**

Parts of the settings dialog are unreadable, because the colors of background and text have way to less contrast

**Expected results**

A readable settings-dialog.

**Additional information**

This is probably the result of setting some, but not all, colors directly (by rgb-values) in the settings-GUI.

**Comment by esopalumpa** [comment] 2019-08-12 20:21
![Screenshot_20190812_221212](https://user-images.githubusercontent.com/39732563/62895591-7edd2900-bd4f-11e9-916c-bb4a77e51eeb.png)
![Screenshot_20190812_221233](https://user-images.githubusercontent.com/39732563/62895593-7edd2900-bd4f-11e9-85c8-5bbe36288262.png)

**Comment by Ghostkeeper** [comment] 2019-08-14 08:48
Duplicate of https://github.com/Ultimaker/Cura/issues/5490.

**Closed by Ghostkeeper** 2019-08-14 08:48 UTC
Labels: Type: Bug
