### ISSUE TITLE
Slicing stays in 'Slicing...' state without any progress

### ISSUE THREAD

**Issue by Triffen** [Ultimaker/Cura#13517] opened 2022-10-10 11:33 UTC
### Application Version

5.2.0 Beta (using modern appimage)

### Platform

Manjaro Linux, KDE Plasma

### Printer

Ender 3 V2

### Reproduction steps

1. Open Cura 5.2 Beta
2. Drop any stl inside
3. Click 'Slice'

### Actual results

It says 'Slicing...' without progress. If I press "Cancel" or delete the model, it says "Slicing failed" and recommends to report a bug. If I try to slice again, it shows "Unable to slice".

### Expected results

I expect it to slice.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Freshly opened Ultimaker-Cura-5.2.0-beta-linux-modern.AppImage with STL dragged and dropped inside and 'Slice' clicked:
![image](https://user-images.githubusercontent.com/4696816/194856296-a49e0314-e501-4456-8063-73d5ef8c99c5.png)

After clicking 'Cancel':
![image](https://user-images.githubusercontent.com/4696816/194856580-cc74a1d0-7a1e-471c-bddf-8839a152a89a.png)

'Unable to slice' state:
![image](https://user-images.githubusercontent.com/4696816/194856030-c305c125-6a42-4a69-885e-4d18b7f4356c.png)

Project file:
[filament clip miniUnableToSliceCura5-2beta.zip](https://github.com/Ultimaker/Cura/files/9745521/filament.clip.miniUnableToSliceCura5-2beta.zip)

**Comment by GregValiant** [comment] 2022-10-10 12:18
Thanks for the report and the project file.
There was a bug in the Windows version of Cura 5.1 that prevented certain models from slicing unless they were moved on the build plate and/or rotated.  It seems that the bug fix for Windows may have transferred that bug to Mac and Linux.  Your project sliced quickly on my Windows system.
Someone from the Cura team will take a look.  (This appears to be a duplicate of #13483.)

**Comment by Triffen** [comment] 2022-10-10 13:03
Thanks!
I have tried to move and rotate the model but it's all the same.

**Comment by jellespijker** [comment] 2024-01-14 13:24
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.
I'm closing this issue as fixed for the 5.7.0 release

![image](https://github.com/Ultimaker/Cura/assets/8535734/ab538822-92f6-41b0-ae20-3cfd49b01a85)

**Closed by jellespijker** 2024-01-14 13:24 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error :collision:, PreRelease :bug:
