### ISSUE TITLE
Keyboard focus in left-side controls (position, rotation, etc) is lost after mouse selection

### ISSUE THREAD

**Issue by daniels220** [Ultimaker/Cura#13160] opened 2022-08-30 02:58 UTC
### Application Version

5.1.0

### Platform

macOS Big Sur

### Printer

Creality CR-10S

### Reproduction steps

Select a model and triple-click in one of the X/Y/Z position fields.

### Actual results

The contents of the field are selected, but the field does not have focus, so typing doesn't work.

### Expected results

The field should have focus as well as selection.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This is a regression from Cura 4, and I believe from the Arachne betas as well.

**Comment by MariMakes** [comment] 2022-09-01 15:49
Hey @daniels220,

Thanks for your report. 👍 
This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12131 (which is a duplicate of https://github.com/Ultimaker/Cura/discussions/11842#discussioncomment-2653797)

We created a ticket on our backlog with the intention to resolve it. 
I'm closing this ticket as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/discussions/11842#discussioncomment-2653797

**Closed by MariMakes** 2022-09-01 15:49 UTC
Labels: Type: Bug, Status: Duplicate
