### ISSUE TITLE
Unable to scroll/view full hint when mouse over a configuration item

### ISSUE THREAD

**Issue by javaman-888** [Ultimaker/Cura#12079] opened 2022-05-03 23:01 UTC
### Application Version

5.0.0-beta+1

### Platform

Windows 10

### Printer

Creality Ender 3 v2

### Reproduction steps

1. Import an STL file
2. Go to Print Settings
3. Search for Infill Pattern
4. Mouse over "Infill Pattern" - tooltip/hint is displayed to the left, with vertical scroll bar
5. Try to move mouse cursor over the tooltip window to scroll - c

### Actual results

The tooltip/hint disappears, unable to grab the scroll bar/arrows to see full explanation of the feature

### Expected results

Tooltip window stays on, allows user to scroll to read full description

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

na

**Comment by fvrmr** [comment] 2022-05-04 07:23
Hi @javaman-888 thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11834, so I will close this issue.

**Closed by fvrmr** 2022-05-04 07:23 UTC
Labels: Type: Bug
