### ISSUE TITLE
New features suggested IMHO

### ISSUE THREAD

**Issue by StefanoV1989** [Ultimaker/Cura#6484] opened 2019-10-05 11:23 UTC
Cura is my main slicer since when I got my first 3D printer... but sometime I need to use other slicers (or support software) because of this functions:

- Adaptive layer manually: in slic3r for example I can choose where increase or decrease layer height. In cura it decides by itself.
- Cutter: with cura I've to put my model under the plain to cut...a plain cutter will be amazing.
- Ruler: sometime my clients say: can I have this model print on 15cm tall? Ok ... but if the model has some "arms" or other thing, cura calculate the size using that part of model. So everytime I have to create a "custom support block". Resize it like what I wanna measure and look at the size and increase it manually trying. A customizable ruler on the model will be a solution.

Thanks 😅

**Comment by Ghostkeeper** [comment] 2019-10-07 13:10
It's really hard for us to track / find / close issues when multiple issues are being posted in one ticket and the templates are not being used. We're lucky this time though because all of your suggestions have been suggested before so I can simply do your research and close the combined ticket as duplicate :smile:

The first suggestion is a duplicate of this one: https://github.com/Ultimaker/Cura/issues/4295

The second suggestion is a duplicate of this one: https://github.com/Ultimaker/Cura/issues/2472

The third suggestion is a duplicate of this one: https://github.com/Ultimaker/Cura/issues/2545

Please continue the conversation there.

**Closed by Ghostkeeper** 2019-10-07 13:10 UTC
Labels: Type: New Feature
