### ISSUE TITLE
Tree support assertion failure / crash

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#9265] opened 2021-02-11 09:05 UTC
**Application version**
current master / the UMH-... branch

doesn't reproduce on 4.8

**Platform**
WSL

**Printer**
UM3

**Reproduction steps**
1. load 
[UM3_cube_cm_bug.3mf.renamed.zip](https://github.com/Ultimaker/Cura/files/5963985/UM3_cube_cm_bug.3mf.renamed.zip)

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/8895761/107617554-6b669300-6c50-11eb-8872-89130ce20b12.png)

**Actual results**
```
CuraEngine: /mnt/c/Development/CuraApp/CuraEngine/src/TreeSupport.cpp:684: const cura::Polygons& cura::ModelVolumes::calculateCollision(const RadiusLayerPair&) const: Assertion `ret.second' failed.
```

**Expected results**
No tree support, no crash

**Additional information**
Unlikely this is related to the fact that I'm on a feature branch, because that branch is concerned with infill only.

**Comment by fvrmr** [comment] 2021-02-11 12:30
Hi @BagelOrb thanks for your report. Will discuss it with the team!

**Comment by Ghostkeeper** [comment] 2021-02-11 12:50
I'm not getting a crash with that project file on master.

It produces no infill since the infill pattern is undefined (part of your project which is not in the master branch), but setting that back to Triangles everything looks fine.
![image](https://user-images.githubusercontent.com/2448634/107638606-1c305a80-6c70-11eb-8819-947155e1b173.png)

**Comment by BagelOrb** [comment] 2021-02-11 16:52
You might want to take a second look at the code where the assertion failure happens. Otherwise we could just clost this issue as non-reproducible...

**Comment by fvrmr** [comment] 2021-02-12 12:09
Hi @BagelOrb we couldn't reproduce this.
So I will close this issue.

**Closed by fvrmr** 2021-02-12 12:09 UTC
Labels: Type: Bug

**Comment by Ghostkeeper** [comment] 2021-02-18 16:34
The assertion in question tests that the collision volume is not empty on that layer, basically, after having offset the mesh with the collision radius. Perhaps it would be colliding with the model if that collision volume should not be empty?
