### ISSUE TITLE
When Z hop is active vertical speed value is invalid in G-code

### ISSUE THREAD

**Issue by arifg** [Ultimaker/Cura#5867] opened 2019-06-06 20:31 UTC
Cura produces an invalid feedrate value in the g-code when Z-hop is activated. The command looks like this:
G1 F17987547480000 Z9.93

Looks like uninitialized variable.

**Comment by Ghostkeeper** [comment] 2019-06-07 08:30
Duplicate of https://github.com/Ultimaker/Cura/issues/5753.

**Closed by Ghostkeeper** 2019-06-07 08:30 UTC
Labels: Type: Bug
