### ISSUE TITLE
Cura Mac Application crash

### ISSUE THREAD

**Issue by PyroNyzen** [Ultimaker/Cura#307] opened 2015-08-31 03:38 UTC
Version: master
Platform: Darwin-14.3.0-x86_64-i386-64bit
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "/cura-build/build/dist/Cura.app/Contents/Resources/__boot__.py", line 77, in <module>
  File "/cura-build/build/dist/Cura.app/Contents/Resources/__boot__.py", line 62, in _run
  File "/cura-build/build/dist/Cura.app/Contents/Resources/cura_app.py", line 17, in <module>
  File "cura/CuraApplication.pyc", line 169, in run
  File "UM/Application.pyc", line 261, in setActiveMachine
  File "UM/Signal.pyc", line 102, in emit
  File "UM/Scene/Platform.pyc", line 49, in _onActiveMachineChanged
AttributeError: 'NoneType' object has no attribute 'getMeshData'

**Comment by Ghostkeeper** [comment] 2015-08-31 08:20
This is a duplicate of issue #274. A fix has been found and will be implemented soon.

**Closed by Ghostkeeper** 2015-08-31 08:20 UTC
