### ISSUE TITLE
La base de impresión de Tevo Tarantula Pro no coincide con el plano X,Y

### ISSUE THREAD

**Issue by rplana94** [Ultimaker/Cura#8266] opened 2020-08-28 18:08 UTC
Hi,
When I upload my Tevo Tarantula Pro Printer, the build platform does not match the X, Y plane. The base is perpendicular to the plane.
In the previous version v6.4, it was OK.
![Plano Tevo](https://user-images.githubusercontent.com/70404040/91601471-0a7d2400-e96a-11ea-872f-410052e34559.png)

**Comment by nallath** [comment] 2020-08-28 20:36
Duplicate of https://github.com/Ultimaker/Cura/issues/8234

**Closed by nallath** 2020-08-28 20:36 UTC
Labels: Type: Bug
