### ISSUE TITLE
Unable to slice error w/o further details

### ISSUE THREAD

**Issue by thesec** [Ultimaker/Cura#2427] opened 2017-09-13 20:19 UTC
Cura 2.7.0 / Mac OS shows me "Unable to slice with the current settings. the following settings have errors:" The dialog ends here, there are no settings highlighted in the "Print Setup" (which would be a nice feature btw :) ) nor seems there to be any other source to gather the failing settings from?!

:/

**Comment by nallath** [comment] 2017-09-14 14:49
Could you share your logs and your project file?

**Comment by thesec** [comment] 2017-09-18 08:44
Where to find the logs?
Am able to reproduce it when changing the layer height from .2 to .2x.

Am using the profiles provided in https://drive.google.com/file/d/0BwSHq9qaQ0euSmJKRElfM1NvWjQ/view.

**Comment by Ghostkeeper** [comment] 2017-09-24 14:40
Wow, that printer has a whopping 1.8MB of quality profiles in there.

**Comment by Ghostkeeper** [comment] 2017-09-24 14:43
It doesn't reproduce for me. I'm loading the Sigma printer in, at 0.4mm Brass, PLA, Draft Quality. Then changed the layer height to 0.23mm. I had a small cube loaded, and that sliced fine.

**Comment by Ghostkeeper** [comment] 2017-09-24 14:46
In Cura, you can go to Help -> Show Configuration Folder to get to the directory where the logs are located. Alternatively, you can navigate to `$User/Library/Application Support/cura/<Cura version>/cura.log`.

Nallath also asked for a project file. That could help. You can create a project file in Cura by going to File -> Save project. This should save all of your settings, your printer, profiles, and your model. Save it while you're having the error. Put it in a .zip and upload it here on Github. Maybe we can reproduce the issue then.

**Comment by thesec** [comment] 2017-11-12 16:47
Just happened again, chaning only the layer height from .2 to .25mm ...

Does the log reveal to you what (might have) happened?
[cura.log.zip](https://github.com/Ultimaker/Cura/files/1464881/cura.log.zip)

The error did not happen with other models and the very same model reloaded.

OT: 
2017-11-12 17:35:14,704 - DEBUG - UM.Backend.Backend._backendLog [93]: [Backend] [WARNING] Couldn't load extruder.def.json file for extruder 1. Index out of bounds.
What might cause such? Does not show in the UI :/

**Comment by Ghostkeeper** [comment] 2017-11-20 00:21
This seems to be the relevant error in that log:

    2017-11-12 17:35:19,498 - WARNING - CuraEngineBackend.StartSliceJob._checkStackForErrors [74]: Setting infill_sparse_thickness is not valid, but ValidatorState.MinimumError. Aborting slicing.

Your Infill Layer Thickness setting is less than 1 in a per-object setting?

**Comment by Ghostkeeper** [comment] 2017-11-20 01:07
Thanks to @thesec's log I was able to make a fix for this bug: https://github.com/Ultimaker/Cura/commit/6d2bcd9b3e6acc7ae690c18758e9f6b6dd8beabb

Adding logs helps, folks :smile:

**Closed** 2017-11-20 09:24 UTC

**Comment by thesec** [comment] 2017-11-20 14:13
@Ghostkeeper yay - glad I could help and thanks for your swift support!

> Your Infill Layer Thickness setting is less than 1 layer in a per-object setting?
The layer infill in the project is set to .2mm but with the first extruder and not per object.

**Comment by thesec** [comment] 2017-11-20 14:21
@Ghostkeeper just re-read the description and it seems I might have been mislead by the "mm" label in the layer thickness input. If the input indeed is rather a factor (is it?) the label should imo not be "mm" but "factor" or "x" ... or have the entry in percent plus "%" to keep it consistent with other.

**Comment by Ghostkeeper** [comment] 2017-11-27 21:43
The setting is intended to sound like millimetres to the user. In that text box you enter some mm of layer thickness.

Under water this is converted to a number of layers that it must combine together. This is why we can't handle a value that's lower than one layer height. The setting should become red if you try that. There's also a hard maximum of 8 layers because of implementation limitations.
