### ISSUE TITLE
Slicing bug appearing in preview

### ISSUE THREAD

**Issue by si-hb** [Ultimaker/Cura#11177] opened 2021-12-31 21:14 UTC
### Application Version

4.13.0 Beta

### Platform

Linux

### Printer

UM3

### Reproduction steps

Sliced a model, reviewed preview.

### Actual results

I get a strange effect when previewing, a layer halfway through the model that renders on the plane of the build plate instead of the plane of the layer. On the plane of the layer, a gap appears. Afraid to actually print model for fear of the result. 

I attached a video and the model. The effect is clear.

Issue is not there in 4.12.1

https://user-images.githubusercontent.com/1800110/147838705-16513e9f-71ff-42ab-8ed6-8e6cddd331d2.mp4
[model.zip](https://github.com/Ultimaker/Cura/files/7797047/model.zip)

### Expected results

no preview issues

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

include
[model.zip](https://github.com/Ultimaker/Cura/files/7797048/model.zip)

https://user-images.githubusercontent.com/1800110/147839108-bb77a792-eebe-4871-80a8-00cd764e181a.mp4

d

**Comment by fvrmr** [comment] 2022-01-03 15:47
Hi @si-hb thank you for your bug report. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/7412 and we have a ticket on our backlog for this.
It seems to be a visualization bug, to double check you can save the gcode and load the gcode back in Cura. 

I will close this issue since it is a duplicate.

**Closed by fvrmr** 2022-01-03 15:47 UTC
Labels: Type: Bug
