### ISSUE TITLE
Buttons of the top right corner menu aren't working

### ISSUE THREAD

**Issue by Triffen** [Ultimaker/Cura#12424] opened 2022-06-01 18:46 UTC
### Application Version

5.0 appimage

### Platform

Linux Manjaro

### Printer

Ender 3

### Reproduction steps

Open Cura 5 appimage.
Click menu button in the top right corner.
Click any of the buttons inside.

### Actual results

Nothing happens.

### Expected results

Something should open I guess :) One of those buttons is "Report a bug" and it doesn't work either. Seems to be Linux and/or appimage bug.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Cura5ButtonsNotWorking](https://user-images.githubusercontent.com/4696816/171479580-7bf4a3a8-bcf5-4171-aec6-6a6c99868f84.png)

**Comment by MariMakes** [comment] 2022-08-22 14:24
Hey! 

Thanks for reporting. This seems to be a duplicate of
https://github.com/Ultimaker/Cura/issues/12232

This should be fixed in Ultimaker Cura 5.1.0 Linux modern.AppImage.asc
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.1.0

I'm closing this issue but please let me know if the issue is still present.

**Closed by MariMakes** 2022-08-22 14:24 UTC
Labels: Type: Bug, Status: Triage

**Comment by Triffen** [comment] 2022-08-22 14:53
It wasn't working for me in Cura 5.1 appimage. I have installed xdg-desktop-portal and now the buttons work, also save/open dialogues for files, projects and profiles also work.

**Comment by MariMakes** [comment] 2022-08-22 15:11
Huzzah! 🎉

**Comment by bprzybytkowski** [comment] 2022-10-19 12:16
The buttons still doesn't work for me using both 5.1 and 5.2 appimage on SteamOS (Arch Linux). This applies to `Import` button in Profiles window as well which hurts most as I am unable to import my profiles used on Windows machine

**Comment by Triffen** [comment] 2022-10-19 12:27
@bprzybytkowski Have you tried my solution above? It fixed this kind of problems to 5.1 and to 5.2 (5.2 won't slice for me though but that's a different issue).
