### ISSUE TITLE
Kvantum Style missing in AppImage 

### ISSUE THREAD

**Issue by pulponair** [Ultimaker/Cura#12728] opened 2022-07-10 17:01 UTC
### Application Version

5.0.0

### Platform

Linux mint 21

### Printer

Ender 3v2

### Reproduction steps

export QT_STYLE_OVERRIDE=kvantum
Start Cura

### Actual results

You ll get an error that the style is not supported and only windows and fusion is inkluded.

It worked with the 4.x Appimages (e.g. 4.13.1)

### Expected results

Cura should start using the Kvantum Style e.i. whatever you set your Kvantum to.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no additional information

**Comment by MariMakes** [comment] 2022-08-24 16:12
Hey @pulponair.

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12940
I'm closing this one to keep order in the chaos.

You can follow the progress here: https://github.com/Ultimaker/Cura/issues/12940

**Closed by MariMakes** 2022-08-24 16:12 UTC
Labels: Type: Bug, Status: Duplicate
