### ISSUE TITLE
Octoprint not working on Cura 4.2

### ISSUE THREAD

**Issue by Mariovali** [Ultimaker/Cura#6089] opened 2019-07-30 16:18 UTC
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by elloco054** [comment] 2019-07-30 20:35
Yes, same issue here ...
Plug in installed and when I open parameters / printers / manage. There is no new button to connect to Octoprint. Just before with Cura 4.1, all was good ...
:(

**Comment by iwittkau** [comment] 2019-07-30 20:58
I have a fresh install of Cura 4.2.0 and the latest [Octoprint plugin](https://github.com/fieldOfView/Cura-OctoPrintPlugin) and it connected successfully.

**You need to update your Octoprint plugin to the latest available version! Otherwise the plugin itself reports it is not compatible with Cura 4.2.0 and will not be loaded.**

**Comment by linhartr22** [comment] 2019-07-31 03:37
I've uninstalled and reinstalled the Octoprint plugin. Is the one you link to newer than the one on the Marketplace?

**Comment by dreward** [comment] 2019-07-31 05:28
Same problem. Octoprint was working and is no longer. I have uninstalled octoprint plugin and reinstalled to no effect. Not sure if this is relevant but I checked the  plugins folder (which I have never looked in before) and octoprint plugin is not listed but I am guessing it is located elsewhere
All suggestions welcome

**Comment by fieldOfView** [comment] 2019-07-31 06:35
A version of the OctoPrint Connection plugin compatible with Cura 4.2 is awaiting review. In the mean time you can download it here:
http://files.fieldofview.com/cura/OctoPrintPlugin-v6.0.0-2019-07-18T12_32_22Z.curapackage

Download the file and drop it in a running Cura application.

**Comment by nallath** [comment] 2019-07-31 08:33
Duplicate of https://github.com/Ultimaker/Cura/issues/6088

**Closed by nallath** 2019-07-31 08:33 UTC
