### ISSUE TITLE
[4.2/4.2.1] I can't click on materials

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#6137] opened 2019-08-02 12:47 UTC
**Application version**
4.2 and 4.2.1

**Platform**
Win10 x64

**Printer**
Creality cr-10s

**Reproduction steps**
I try to open the material tab

**Actual results**
I can't select any material, not from the favourites nor from its real dropdown. Trying to select a favourite material will select its dropdown menu. Trying to select a material from its dropdown won't do anything.

**Expected results**
Clicking on a material should let me able to edit it.

**Additional information**
https://youtu.be/uDgGOQsFy8g?t=31
Watch it from 0:31

**Comment by REBU47** [comment] 2019-08-02 15:45
Application version 4.2 and 4.2.1  Platform Win10 x64  Printer Anycubic Mega S  I have the same problem. I can not choose any material. Everything was OK in CURA 4.1

**Comment by fieldOfView** [comment] 2019-08-02 21:08
Do either of you have the Material Settings plugin installed? If so, please try if disabling that plugin and restarting Cura fixes the issue.

**Comment by Liger0** [comment] 2019-08-02 22:17
Unfortunately, in Cura 4.x there is no way to uninstall installed plugins. Even tho they result installed, the work "install" still appears instead of the word "uninstall".

**Comment by fieldOfView** [comment] 2019-08-03 06:09
In the Marketplace dialog, there’s an “Installed” tab (top right). There you can disable (uncheck) but also uninstall plugins. 

So you are saying you do have that plugin installed?

**Comment by Liger0** [comment] 2019-08-03 12:22
Yes, I have it installed. But as I said, since 4.x there is no button to uninstall plugins

**Comment by Vandrasc** [comment] 2019-08-05 09:41
You can uncheck the box but you always need to restart Cura in order to make the changes in the packages. But yes, I can confirm that when the Material Setting plugin is installed the materials cannot be selected anymore and when removing the plugin the materials are selectable and editable again. 

@fieldOfView , do we need to align on this? Does the plugin need an update? Thank you:)

**Comment by fieldOfView** [comment] 2019-08-05 11:08
The plugin needs an update. https://github.com/Ultimaker/Cura/commit/914d2e98e977131b67a85131ba29aadf63fb4f91#diff-7350e9d08a06d9246ab8a568e3becc2b broke the plugin.

**Comment by Liger0** [comment] 2019-08-05 12:26
I do not see any checkbox. :(

**Comment by Vandrasc** [comment] 2019-08-05 12:30
Preferably to Uninstall the plugin, but if you want to give it a quick try...Marketplace > Installed and on the left side of the plugin description, you have the checkbox. 

![checkbox](https://user-images.githubusercontent.com/26549794/62464649-7738e580-b78d-11e9-8d66-361209f62a1f.png)

**Comment by nallath** [comment] 2019-08-05 12:59
> The plugin needs an update. [914d2e9#diff-7350e9d08a06d9246ab8a568e3becc2b](https://github.com/Ultimaker/Cura/commit/914d2e98e977131b67a85131ba29aadf63fb4f91#diff-7350e9d08a06d9246ab8a568e3becc2b) broke the plugin.

Hmm, but that fix ensured that there was no longer a difference between the first start of the preference window and clicking the material slot (eg; In the first start it got a different item as the currentItem you got when clicking the slot).

**Comment by fieldOfView** [comment] 2019-08-05 13:34
@nallath, the plugin contains a modified MaterialsPage.qml, (*) based on the one from 4.2. I did not notice the file had been modified in 4.2.1, so the copy contained in the plugin does not have the setExpandedActiveMaterial function.

(*): Replacing the whole MaterialsPage with a patched one is the only way the plugin can replace the Print Settings widget with less naive ones that properly display floats, include validation, etc.

**Comment by fieldOfView** [comment] 2019-08-05 15:28
See also https://github.com/fieldOfView/Cura-MaterialSettingsPlugin/issues/3

**Comment by nallath** [comment] 2019-08-06 06:59
Ah, right. That makes sense.

**Comment by Ghostkeeper** [comment] 2019-08-08 12:04
Closing this as duplicate of https://github.com/fieldOfView/Cura-MaterialSettingsPlugin/issues/3 then.

**Closed by Ghostkeeper** 2019-08-08 12:04 UTC
Labels: Type: Bug
