### ISSUE TITLE
Cura Quit Unexpectedly on Macbook Pro M2 Pro

### ISSUE THREAD

**Issue by skorecki** [Ultimaker/Cura#16171] opened 2023-07-16 16:43 UTC
### Cura Version

5.4.0

### Operating System

MacOS Ventura (13.4.1)

### Printer

Creality Ender 3 v2

### Reproduction steps

Cura application is running on MacOS without any active end user input

### Actual results

Cura 5.4 unexpectedly quits.

### Expected results

The application should remain running without incident

### Add your .zip and screenshots here ⬇️

[cura.log](https://github.com/Ultimaker/Cura/files/12064595/cura.log)

**Comment by skorecki** [comment] 2023-08-04 21:23
This continues to happen regularly.  Frequently, when waking up the laptop from sleep, there is a message about Cure unexpectedly quitting.

**Comment by MariMakes** [comment] 2023-08-08 12:45
Hey @skorecki,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you and to hear your Cura keeps crashing😞

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/15161
We have a ticket on our backlog with the intent to improve this behavior.
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/15161

**Closed by MariMakes** 2023-08-08 12:45 UTC
Labels: Type: Bug, Status: Triage
