### ISSUE TITLE
Center model function resets orientation as well

### ISSUE THREAD

**Issue by dtwrv6** [Ultimaker/Cura#1801] opened 2017-05-06 18:35 UTC
Windows version - same bug in 2.5 and 2.4

After rotating a model and positioning it, select "Center model on platform".  Not only does it center the model, it resets all orientation changes.  This should be a separate function.

**Comment by nallath** [comment] 2017-05-08 07:26
I can't reproduce this. Center model only changes the position for me.

**Comment by Ghostkeeper** [comment] 2017-05-10 11:23
Perhaps it only happens with grouped models or something?

**Comment by BagelOrb** [comment] 2017-07-21 12:45
I can reproduce a bug (2.6 on Windows) which is liklely to be what the OP is experiencing.

Try out some weird orientations and try using the mirror tool. Then centering also does some flipping or rotating by 180 degrees.

**Comment by ChrisTerBeke** [comment] 2018-01-03 15:25
Fixed in https://github.com/Ultimaker/Cura/commit/e0c2a9e4c7780addc043859369edad400b63a1b0.

**Closed by ChrisTerBeke** 2018-01-03 15:25 UTC
Labels: bug
