### ISSUE TITLE
Display progressive preview when printing

### ISSUE THREAD

**Issue by darrenoakey** [Ultimaker/Cura#10820] opened 2021-11-12 22:27 UTC
### Is your feature request related to a problem?

the printing monitoring screen is really boring

### Describe the solution you'd like

It seems that given you've already built the code to render a preview - rendering it by layers is trivial - so displaying on the screen where the print is up to would just enhance the experience heaps with very little cost.

### Describe alternatives you've considered

none really

### Affected users and/or printers

everyone

**Comment by fvrmr** [comment] 2021-11-15 16:23
Hi @darrenoakey thank you for your feature request.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/6020
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-11-15 16:23 UTC
Labels: Type: New Feature
