### ISSUE TITLE
Incomplete raft

### ISSUE THREAD

**Issue by Tettink** [Ultimaker/Cura#13353] opened 2022-09-22 06:58 UTC
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Ultimaker s5

### Reproduction steps

1.Loading in files, merge and position them x0 y0 z0
2. Generate with default settings + raft ultimaker ABS material black and grey.

### Actual results

Ultimaker skips half of the 3e layer of the raft
![S5 Cura 5 1 0](https://user-images.githubusercontent.com/114135887/191677549-9ede03cf-15d6-4a8b-88e5-2d8bd84efa68.PNG)

### Expected results

![S5 Cura 5 1 0 2](https://user-images.githubusercontent.com/114135887/191677895-ae5da3ea-ebad-4e4c-b771-0f9fc269df1b.PNG)
The only way for me to fix this with this particular file is turning it a bit.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Files.zip](https://github.com/Ultimaker/Cura/files/9623130/Files.zip)

**Comment by GregValiant** [comment] 2023-01-07 00:08
There is [this thread](https://community.ultimaker.com/topic/30374-2nd-layer-above-raft-is-missing/#comment-317178) on the UM Forum that also describes this behavior.  Once again, moving the model on the Cura build plate caused the problem to go away.
Here is the project file from that thread.
[Partial Raft Settings.zip](https://github.com/Ultimaker/Cura/files/10364615/Partial.Raft.Settings.zip)

**Comment by Tettink** [comment] 2023-01-07 01:42
Hi,

Yes it indeed it did, sorry for not responding earlier.

________________________________
Van: GregValiant ***@***.***>
Verstuurd: zaterdag 7 januari 2023 01:08
Aan: Ultimaker/Cura ***@***.***>
CC: Tettink ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Ultimaker/Cura] Incomplete raft (Issue #13353)


There is this thread<https://community.ultimaker.com/topic/30374-2nd-layer-above-raft-is-missing/#comment-317178> on the UM Forum that also describes this behavior. Once again, moving the model on the Cura build plate caused the problem to go away.
Here is the project file from that thread.
Partial Raft Settings.zip<https://github.com/Ultimaker/Cura/files/10364615/Partial.Raft.Settings.zip>

**Comment by MariMakes** [comment] 2023-01-09 14:36
Hey @GregValiant and @Tettink,

Thanks for your report 👍

@GregValiant, I double-checked but could not resolve the issue by moving it away from the center of the buildplate. Do you have a screenshot or video of the project file where we can see that the top layer of the raft becomes complete again when you move the model? 😇 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12276
We have a ticket on our backlog with the intent to improve this behavior.
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12276

**Closed by MariMakes** 2023-01-09 14:36 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error💥
