### ISSUE TITLE
[4.7.1.AppImage] Segmentation Fault 

### ISSUE THREAD

**Issue by ljkenny** [Ultimaker/Cura#8453] opened 2020-09-27 08:13 UTC
**Application version**
4.7.1.AppImage

**Platform**
Dell Precision 5500

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS

**Printer**
N/A - Cura doesn't even start

**Reproduction steps**
```
~$ ~/Downloads/Ultimaker_Cura-4.7.1.AppImage 
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig warning: line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 8: unknown element "description"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 76: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 76: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 84: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-fonts-persian.conf", line 34: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/65-fonts-persian.conf", line 35: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/69-unifont.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/69-unifont.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/80-delicious.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/80-delicious.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 5: unknown element "its:translateRule"
qml: TableViewSelection: index out of range
qml: TableViewSelection: index out of range
Segmentation fault (core dumped)
```

**Screenshot(s)**
N/A

**Actual results**
As above

**Expected results**
It should start.

**Project file**
N/A

**Log file**
As above

**Additional information**
None

**Comment by nallath** [comment] 2020-09-28 09:19
Could you also share the log file (as described in the bug template)

**Comment by ljkenny** [comment] 2020-09-28 09:24
Certainly:

```
2020-09-26 16:44:56,418 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin FileLogger
2020-09-26 16:44:56,427 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin FirmwareUpdateChecker
2020-09-26 16:44:56,436 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin FirmwareUpdater
2020-09-26 16:44:56,442 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin GCodeGzReader
2020-09-26 16:44:56,449 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin GCodeGzWriter
2020-09-26 16:44:56,455 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin GCodeProfileReader
2020-09-26 16:44:56,474 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin GCodeReader
2020-09-26 16:44:56,481 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin GCodeWriter
2020-09-26 16:44:56,493 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin ImageReader
2020-09-26 16:44:56,500 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin LegacyProfileReader
2020-09-26 16:44:56,508 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin LocalContainerProvider
2020-09-26 16:44:56,520 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin LocalFileOutputDevice
2020-09-26 16:44:56,529 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin MachineSettingsAction
2020-09-26 16:44:56,538 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin ModelChecker
2020-09-26 16:44:56,547 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin MonitorStage
2020-09-26 16:44:56,566 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin PerObjectSettingsTool
2020-09-26 16:44:56,577 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin PostProcessingPlugin
2020-09-26 16:44:56,584 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin PrepareStage
2020-09-26 16:44:56,590 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin PreviewStage
2020-09-26 16:44:56,599 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin RemovableDriveOutputDevice
2020-09-26 16:44:56,646 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin SentryLogger
2020-09-26 16:44:56,672 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin SimulationView
2020-09-26 16:44:56,683 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin SliceInfoPlugin
2020-09-26 16:44:56,695 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin SolidView
2020-09-26 16:44:56,706 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin SupportEraser
2020-09-26 16:44:56,740 - WARNING - [MainThread] UM.Logger.logException [106]: Exception: Failed to load packages for Marketplace
2020-09-26 16:44:56,742 - WARNING - [MainThread] UM.Logger.logException [110]: NoneType: None
2020-09-26 16:44:56,745 - WARNING - [MainThread] UM.Logger.logException [106]: Exception: Failed to load packages for Marketplace
2020-09-26 16:44:56,747 - WARNING - [MainThread] UM.Logger.logException [110]: NoneType: None
2020-09-26 16:44:56,749 - WARNING - [MainThread] UM.Logger.logException [106]: Exception: Failed to load packages for Marketplace
2020-09-26 16:44:56,751 - WARNING - [MainThread] UM.Logger.logException [110]: NoneType: None
2020-09-26 16:44:56,753 - WARNING - [MainThread] UM.Logger.logException [106]: Exception: Failed to load packages for Marketplace
2020-09-26 16:44:56,755 - WARNING - [MainThread] UM.Logger.logException [110]: NoneType: None
2020-09-26 16:44:56,759 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin Toolbox
2020-09-26 16:44:56,768 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin CameraTool
2020-09-26 16:44:56,780 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin MirrorTool
2020-09-26 16:44:56,795 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin RotateTool
2020-09-26 16:44:56,808 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin ScaleTool
2020-09-26 16:44:56,815 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin SelectionTool
2020-09-26 16:44:56,827 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin TranslateTool
2020-09-26 16:44:56,835 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin TrimeshReader
2020-09-26 16:44:56,847 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin UFPReader
2020-09-26 16:44:56,858 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin UFPWriter
2020-09-26 16:44:56,959 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin UM3NetworkPrinting
2020-09-26 16:44:56,988 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin USBPrinting
2020-09-26 16:44:56,995 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin UltimakerMachineActions
2020-09-26 16:44:57,004 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin UpdateChecker
2020-09-26 16:44:57,005 - INFO - [Thread-1] UpdateChecker.UpdateCheckerJob.run [40]: Checking for new version of cura
2020-09-26 16:44:57,023 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin VersionUpgrade21to22
2020-09-26 16:44:57,031 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin VersionUpgrade22to24
2020-09-26 16:44:57,039 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin VersionUpgrade25to26
2020-09-26 16:44:57,048 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin VersionUpgrade26to27
2020-09-26 16:44:57,056 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin VersionUpgrade27to30
2020-09-26 16:44:57,063 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin VersionUpgrade30to31
2020-09-26 16:44:57,071 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin VersionUpgrade32to33
2020-09-26 16:44:57,080 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin VersionUpgrade33to34
2020-09-26 16:44:57,087 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin VersionUpgrade34to35
2020-09-26 16:44:57,093 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin VersionUpgrade35to40
2020-09-26 16:44:57,099 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin VersionUpgrade40to41
2020-09-26 16:44:57,107 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin VersionUpgrade41to42
2020-09-26 16:44:57,114 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin VersionUpgrade42to43
2020-09-26 16:44:57,120 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin VersionUpgrade43to44
2020-09-26 16:44:57,128 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin VersionUpgrade44to45
2020-09-26 16:44:57,135 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin VersionUpgrade45to46
2020-09-26 16:44:57,142 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin VersionUpgrade460to462
2020-09-26 16:44:57,149 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin VersionUpgrade462to47
2020-09-26 16:44:57,156 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin SimpleView
2020-09-26 16:44:57,172 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin X3DReader
2020-09-26 16:44:57,179 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin XRayView
2020-09-26 16:44:57,200 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin XmlMaterialProfile
2020-09-26 16:44:57,202 - DEBUG - [MainThread] UM.PluginRegistry.loadPlugins [373]: Loading all plugins took 1.0431492328643799 seconds
2020-09-26 16:44:57,208 - INFO - [MainThread] UM.VersionUpgradeManager.upgrade [163]: Looking for old configuration files to upgrade.
2020-09-26 16:44:57,215 - INFO - [MainThread] UM.VersionUpgradeManager.upgrade [175]: Checking and performing updates took 0.007718801498413086
2020-09-26 16:44:57,219 - INFO - [MainThread] UM.Qt.QtApplication.startSplashWindowPhase [226]: The preferences file cannot be found or it is corrupted, so we will use default values
2020-09-26 16:44:57,225 - INFO - [MainThread] UM.Qt.QtApplication.startSplashWindowPhase [235]: The preferences file 'None' cannot be found, will use default values
2020-09-26 16:44:58,792 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.loadAllMetadata [361]: Loading metadata into container registry took 1.535536527633667 seconds
2020-09-26 16:44:58,806 - DEBUG - [MainThread] cura.Scene.CuraSceneController.setActiveBuildPlate [142]: Select build plate: 0
2020-09-26 16:44:58,812 - INFO - [MainThread] cura.CuraApplication.run [781]: Initializing machine error checker
2020-09-26 16:44:58,817 - INFO - [MainThread] cura.CuraApplication.run [786]: Initializing machine manager
2020-09-26 16:44:58,825 - INFO - [MainThread] cura.CuraApplication.run [791]: Initializing container manager
2020-09-26 16:44:59,083 - WARNING - [MainThread] LocalContainerProvider.LocalContainerProvider._saveCachedDefinition [295]: The definition cache for definition fdmprinter failed to pickle.
2020-09-26 16:44:59,102 - DEBUG - [MainThread] UM.Scene.Camera._preferencesChanged [255]: Changing perspective mode to perspective.
2020-09-26 16:44:59,166 - DEBUG - [MainThread] UM.Qt.Bindings.Theme.load [158]: Loading theme file: /tmp/.mount_Ultimae4mzcv/usr/bin/resources/themes/cura-light/theme.json
2020-09-26 16:44:59,901 - DEBUG - [MainThread] UM.Qt.Bindings.Theme.load [246]: Loaded theme /tmp/.mount_Ultimae4mzcv/usr/bin/resources/themes/cura-light
2020-09-26 16:45:01,175 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin._createView [336]: Creating post processing plugin view.
2020-09-26 16:45:01,187 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: ChangeAtZ
2020-09-26 16:45:01,189 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: ColorMix
2020-09-26 16:45:01,190 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: DisplayFilenameAndLayerOnLCD
2020-09-26 16:45:01,191 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: DisplayProgressOnLCD
2020-09-26 16:45:01,193 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: FilamentChange
2020-09-26 16:45:01,194 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: InsertAtLayerChange
2020-09-26 16:45:01,199 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: PauseAtHeight
2020-09-26 16:45:01,202 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: RetractContinue
2020-09-26 16:45:01,203 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: SearchAndReplace
2020-09-26 16:45:01,209 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: Stretch
2020-09-26 16:45:01,211 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: TimeLapse
2020-09-26 16:45:01,212 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: UsePreviousProbeMeasurements
2020-09-26 16:45:01,383 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin._createView [346]: Post processing view created.
2020-09-26 16:45:02,156 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService._parseJWT [100]: There was no auth data or access token
2020-09-26 16:45:02,286 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService._parseJWT [100]: There was no auth data or access token
2020-09-26 16:45:02,288 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService._parseJWT [100]: There was no auth data or access token
2020-09-26 16:45:02,416 - DEBUG - [MainThread] UM.Controller.setActiveStage [180]: Setting active stage to PrepareStage
2020-09-26 16:45:02,554 - DEBUG - [MainThread] cura.Machines.Models.NozzleModel._update [28]: Updating NozzleModel.
2020-09-26 16:45:02,559 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [406]: file:///tmp/.mount_Ultimae4mzcv/usr/bin/resources/qml/Menus/ConfigurationMenu/ConfigurationMenu.qml:143: TypeError: Cannot read property 'hasRemoteConnection' of null
2020-09-26 16:45:02,674 - DEBUG - [MainThread] UM.Controller.setActiveView [108]: Setting active view to SolidView
2020-09-26 16:45:02,693 - DEBUG - [MainThread] ModelChecker.ModelChecker._createView [117]: Creating model checker view.
2020-09-26 16:45:02,707 - DEBUG - [MainThread] ModelChecker.ModelChecker._createView [126]: Model checker view created.
2020-09-26 16:45:02,709 - DEBUG - [MainThread] SliceInfoPlugin.SliceInfo._createDialog [76]: Creating dialog [MoreInfoWindow.qml]
2020-09-26 16:45:02,776 - DEBUG - [MainThread] Toolbox.src.Toolbox._makeRequestByType [544]: Requesting [updates] metadata from server.
2020-09-26 16:45:02,779 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService.getAccessToken [124]: No auth data to retrieve the access_token from
2020-09-26 16:45:02,781 - WARNING - [MainThread] UM.Logger.warning [128]: Cannot add authorization to Cloud Api request
2020-09-26 16:45:02,790 - DEBUG - [MainThread] cura.CuraApplication.run [830]: Booting Cura took 12.255805969238281 seconds
2020-09-26 16:45:02,790 - DEBUG - [Thread-2] cura.Machines.ContainerTree.run [174]: Started background loading of MachineNodes
2020-09-26 16:45:02,793 - DEBUG - [Thread-2] cura.Machines.ContainerTree.run [185]: All MachineNode loading completed
2020-09-26 16:45:02,808 - DEBUG - [MainThread] cura.Machines.Models.CustomQualityProfilesDropDownMenuModel._update [33]: Updating CustomQualityProfilesDropDownMenuModel.
2020-09-26 16:45:02,810 - DEBUG - [MainThread] cura.Machines.Models.CustomQualityProfilesDropDownMenuModel._update [38]: No active GlobalStack, set CustomQualityProfilesDropDownMenuModel as empty.
2020-09-26 16:45:02,813 - DEBUG - [MainThread] cura.Machines.Models.QualityProfilesDropDownMenuModel._update [62]: Updating QualityProfilesDropDownMenuModel.
2020-09-26 16:45:02,815 - DEBUG - [MainThread] cura.Machines.Models.QualityProfilesDropDownMenuModel._update [74]: No active GlobalStack, set quality profile model as empty.
2020-09-26 16:45:02,998 - DEBUG - [MainThread] UM.Qt.QtRenderer._initialize [210]: Support for Vertex Array Objects: True
2020-09-26 16:45:03,009 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [112]: Initialized OpenGL subsystems.
2020-09-26 16:45:03,011 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [113]: OpenGL Version:  4.6 (Core Profile) Mesa 20.0.4
2020-09-26 16:45:03,014 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [114]: OpenGL Vendor:   Intel
2020-09-26 16:45:03,016 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [115]: OpenGL Renderer: Mesa Intel(R) HD Graphics P530 (SKL GT2)
2020-09-26 16:45:03,019 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [116]: GLSL Version:    4.60.0
2020-09-26 16:45:03,021 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [/tmp/.mount_Ultimae4mzcv/usr/bin/resources/shaders/default.shader]...
2020-09-26 16:45:03,027 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [/tmp/.mount_Ultimae4mzcv/usr/bin/resources/shaders/selection.shader]...
2020-09-26 16:45:03,031 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [/tmp/.mount_Ultimae4mzcv/usr/bin/resources/shaders/select_face.shader]...
2020-09-26 16:45:03,035 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [/tmp/.mount_Ultimae4mzcv/usr/bin/resources/shaders/default.shader]...
2020-09-26 16:45:03,039 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [/tmp/.mount_Ultimae4mzcv/usr/bin/resources/shaders/composite.shader]...
```

**Comment by nallath** [comment] 2020-09-28 09:29
Hmm. It seems to stop at the moment that it's trying to load a bunch of shaders. But it would be strange if that caused it, since a few of them are already loaded.

We have had issues with SSL connections in the past. What happens if you start Cura with your internet connection disabled?

**Comment by ljkenny** [comment] 2020-09-28 09:37
Disabling networking appears to have no affect.

**Comment by nallath** [comment] 2020-09-28 09:40
Thanks for checking. I'll discuss it with the rest of the team, maybe one of them has an idea.

**Comment by Ghostkeeper** [comment] 2020-09-29 11:37
Well, after it's done loading those shaders it's going to create the main interface. It crashes there without error message to the user, so that means that Qt had an internal crash somewhere.

Maybe you could try executing this in a command line?

    env -u DESKTOP_SESSION -u KDE_FULL_SESSION -u XDG_CURRENT_DESKTOP /bin/cura

**Comment by nallath** [comment] 2020-09-29 13:23
Well, it's not quite _done_ loading those shaders. For me, it continues on for a bit with a few more shaders.

**Comment by ljkenny** [comment] 2020-09-29 13:37
> Maybe you could try executing this in a command line?
> 
> ```
> env -u DESKTOP_SESSION -u KDE_FULL_SESSION -u XDG_CURRENT_DESKTOP /bin/cura
> ```

Same result.

**Comment by rburema** [comment] 2020-09-30 10:31
A thing you could try is `force_empty_shader_cache = True`, under the `[view]` heading in `cura.cfg` (normally this is a preference, but since it won't start you have to add it manually).

If that doesn't work: You could try to put `opengl_version_detect = force_legacy` (also under the `[view]` heading in `cura.cfg`). This will of course be a workaround, but it'll try to load the legacy shaders, so if the problem is indeed the shaders, there's another change to get it working (and confirm that it's the shaders). It'll lack certain features that way though (preview will show up as lines and 'lay face flat on buildplate' won't work anymore).

**Comment by ljkenny** [comment] 2020-09-30 10:58
Neither of those options, either together nor on their own worked.

**Comment by rburema** [comment] 2020-09-30 13:17
That;s a shame....

The fontconfig errors remind me of [this](https://github.com/Ultimaker/Cura/issues/7836) issue though, which wasn't a crash, but the error message is similar, and there are a few workarounds already. (Though you may have to scroll a bit...)

**Comment by JoePater** [comment] 2020-11-07 14:18
I also got a segfault, on Fedora 33 running their packaged version (4.7.1). Attached is the standard out and standard error. No idea if it's related. The segfault happens every time I close Cura.
[cura.zip](https://github.com/Ultimaker/Cura/files/5504873/cura.zip)

**Comment by nallath** [comment] 2020-11-09 08:26
> I also got a segfault, on Fedora 33 running their packaged version (4.7.1). Attached is the standard out and standard error. No idea if it's related. The segfault happens every time I close Cura.
> [cura.zip](https://github.com/Ultimaker/Cura/files/5504873/cura.zip)
> It doesn't really affect me as it only happens on exit, but you might want to take a look at it. I'll open a separate issue if you want.

So you didn't use the appimage? We only support the appimage. If it works with the appimage and it doesn't work with the fedora packaged variant, you will have to contact the fedora maintainers.

**Comment by danfoster** [comment] 2021-02-02 22:40
Hi @ljkenny  - I'm not sure if you're still having this problem? I had a very similar issue on 4.8.0. You might want to check out #9220 in case it helps?

**Comment by ljkenny** [comment] 2021-02-03 08:39
To be 100% frank with you, I've moved to Prusa Slicer, as it runs beautifully on Linux.

**Comment by MariMakes** [comment] 2023-10-19 14:22
Quick update from our side 👋

We are cleaning up our open issues, so we can focus on the most requested and needed features and bug fixes from our community and from UltiMaker, and we've introduced a lot of changes since this report. I'll be closing this issue. I hope you understand.

You can download the latest version of Cura with a bunch of improvements and a new QT version here:
[https://github.com/Ultimaker/Cura/releases/tag/5.5.0-beta.1](https://github.com/Ultimaker/Cura/releases/tag/5.5.0-beta.1)

Apologies for any inconvenience caused by our delayed response.
Thanks again, and please let us know if you run into any other issues 💪

**Closed by MariMakes** 2023-10-19 14:22 UTC
Labels: Type: Bug
