### ISSUE TITLE
Does not open the program version 5.2

### ISSUE THREAD

**Issue by NunoFilipePereira** [Ultimaker/Cura#13599] opened 2022-10-19 09:06 UTC
### Application Version

5.2

### Platform

MacOs 10.15.7

### Printer

Flsun, biqu, Tevo, ender

### Reproduction steps

Does not open the program version 5.2

### Actual results

The latest version 5.0 says it is compatible with Mac Os 10.14. But it's not true. Since version 5.0 this system has never worked properly. Do I need to take into account things other than just installing the program?

### Expected results

Does not open the program version 5.2

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Does not open the program version 5.2

**Comment by x40-Community** [comment] 2022-10-19 11:09
Read the changelog!
Cura 5.1.1 => MacOS 10.15 is no longer supported.

**Comment by NunoFilipePereira** [comment] 2022-10-19 12:19
> Read the changelog!
> Cura 5.1.1 => MacOS 10.15 is no longer supported.
> https://github.com/Ultimaker/Cura/blob/5.2/resources/texts/change_log.txt

Then they should review the information requirements. They're wrong. but version 5.1.1 I can install. version 5.2 is not.

**Comment by MariMakes** [comment] 2022-10-19 13:37
Hey @NunoFilipePereira,

@x40-Community is correct. Unfortunately, we cannot support macOS 10.15.7 anymore, since the tools that we use to build Cura is also dropped their support for these OS versions. 

Sorry for any inconvenience. 😞 
[You can read more about it here. ](
https://support.ultimaker.com/hc/en-us/articles/360011889579-On-what-operating-systems-is-Ultimaker-Cura-available-
)

Since this is expected behavior I'll be closing this issue.

**Closed by MariMakes** 2022-10-19 13:37 UTC
Labels: Type: Bug, Status: Triage
