### ISSUE TITLE
[4.0] Infill layer thickness and wall gap

### ISSUE THREAD

**Issue by Block137** [Ultimaker/Cura#5832] opened 2019-06-02 17:37 UTC
**Application Version**
4.0 (probably any version)

**Steps to reproduce**
1. Set infill layer thickness to multiple the layer thickness
2. Enable "Connect infill lines"

**Actual Results**
There is a gap between wall and infill.
When "Connect infill lines" is enabled, the output appears to think that those lines are actually wider (as visible in layer view)

**Expected results**
Infill actually touching wall (visually overlapping in layer view OR don't render thick lines wider)

**Additional Information**
0.08 layer thickness + 0.24 infill thickness + "Connect infill lines" enabled
![Screenshot (55)](https://user-images.githubusercontent.com/23495338/58764931-7fab4f00-8597-11e9-807a-cdeece0dc0e4.png)

0.08 layer thickness + 0.24 infill thickness + "Connect infill lines" disabled
Note the overlap
![Screenshot (56)](https://user-images.githubusercontent.com/23495338/58764937-9c478700-8597-11e9-9c5c-6c6657084583.png)

**Comment by Ghostkeeper** [comment] 2019-06-03 13:02
Duplicate of https://github.com/Ultimaker/Cura/issues/5345.

**Closed by Ghostkeeper** 2019-06-03 13:02 UTC
Labels: Type: Bug
