### ISSUE TITLE
cura 4.5  does not set the correct material temperature...

### ISSUE THREAD

**Issue by manvalan** [Ultimaker/Cura#7293] opened 2020-03-17 19:24 UTC
cura 4.5

W10
Geeetech A10

Cura 4.5 do not set the correct material temperature but reset to 215 (extrusor) 55 (plate)

**Comment by Vandrasc** [comment] 2020-03-17 20:04
Hi @manvalan , could you please fill in the bug template, this way we will receive enough information in order to help you. Thank you!

**Comment by Ghostkeeper** [comment] 2020-03-19 15:03
I'm getting 200:
![image](https://user-images.githubusercontent.com/2448634/77081604-2cf23500-69fb-11ea-9f3c-4abf9ac44826.png)
That's being defined by Generic PLA, so it seems to be correct.

**Comment by Alvgon** [comment] 2020-03-19 20:06
May be he has still active the post processing scripts installed with v4.5 Winx64, changing extruder temp every 25 layers ...

**Comment by fieldOfView** [comment] 2020-03-20 08:57
Or, more likely, he has a quality_changes profile that includes a temperature which overrides whatever is set in the material. We won't know unless @manvalan posts a project file.

**Comment by fjgo** [comment] 2020-03-22 20:23
Hi.
I faced the same problem and the error is in the profile, in the **Start G-Code** the temperature settings are included.

**Comment by mahtDFR** [comment] 2020-03-23 14:15
I can confirm it's 215 by default in the profile:

![image](https://user-images.githubusercontent.com/17821912/77325545-ce89c700-6d18-11ea-9407-8cca4ece865f.png)

As a workaround I'd suggest altering the start Gcode.

We don't maintain third party machine profiles and are reluctant to do so, so I we won't make any fixes to the definition from here.

**Comment by fieldOfView** [comment] 2020-03-23 14:36
That's a bad workaround. Because the {material_bed_temperature_layer_0} and {material_print_temperature_layer_0} replacement patterns are not found in the start gcode, Cura will prepend its own heat up sequence. So you end up having two heatup sequences in the start gcode.

**Comment by manvalan** [comment] 2020-03-23 14:41
In Cura 4.5 for OS X the setting of material bed temperature and the extruder material temperature are correct… it seems to be a bug in the windows version

**Comment by fieldOfView** [comment] 2020-03-23 14:46
> it seems to be a bug in the windows version

I doubt that. It is much more likely an issue with a setting or a stored profile. We won't know unless you save a project (File -> Save as) and upload it here (you may have to zip it first).

**Comment by Ghostkeeper** [comment] 2020-03-24 08:57
Indeed, Cura's printing/bed settings don't have any effect since it's being overwritten by the start g-code.

Would you like to make an adjustment here, @amitlobo ? You were the author of these profiles. We can't test any changes that we make here, so I'd like a user of Geeetech printers to make these changes.

**Comment by Ghostkeeper** [comment] 2020-03-24 12:21
This is probably fixed for the M10 and M20 here: https://github.com/Ultimaker/Cura/issues/7280

**Comment by Jaki1091** [comment] 2020-04-14 14:08
I have the same problem with my Geeetech A10 (Marlin 1.1.8). 
This is my start g-code in Cura 4.5:

G28
G1 Z15 F300
M107
G90
M82
M104 S215
M140 S55
G92 E0
M107
G0 X10 Y20 F6000
G1 Z0.8
G1 F300 X180 E40
G1 F1200 Z2
G92 E0
G28

No matter what material/temperature I set, the printer will only print at 215°C. Any clues why?

**Comment by mahtDFR** [comment] 2020-04-14 14:56
> M104 S215

This is a gcode command to heat up the nozzle to 215 C. Try changing it to a different value.

[This](https://reprap.org/wiki/G-code#M104:_Set_Extruder_Temperature) is a useful resource.

**Comment by Jaki1091** [comment] 2020-04-14 15:53
@mahtDFR yes, I am currently changing that value in order to print different materials, but I guess it's not the correct way. Whatever material I select (ABS, TPU, PC, PLA) or whatever temperature I set in the "material" tab, the printer will always print with the value written in the start g code (i.e. M104 S215)

**Comment by mahtDFR** [comment] 2020-04-15 14:45
What if you substitute this:

>M104 S{material_print_temperature}

If I have got this correct, then it will take the value from your material print temperature and substitute it here to the nozzle heat up sequence in your start gcode.

**Comment by Jaki1091** [comment] 2020-04-15 16:31
@mahtDFR I tried what you said but the printer didn't extrude anything (the extruder gear did't rotate).
This the gcode Cura created after the edit in the start gcode (I set the temperature at 220°C in the material tab)

M140 S60
M105
M190 S60
M82 ;absolute extrusion mode
G28
G1 Z15 F300
M107
G90
M82
M104 S220	
M140 S60
G92 E0
M107
G0 X10 Y10 F6000
G1 Z0.8
G1 F300 X180 E40
G1 F1200 Z2
G92 E0
G28
G92 E0
G92 E0
G1 F2400 E-4

**Comment by mahtDFR** [comment] 2020-04-16 08:46
Most of these E moves are 0 except for these two:

> G1 F300 X180 E40
> G1 F2400 E-4

So there should be something happening there at least. Unfortunately I dont have a GeeTech machine to test. If you remove the substitution, does it stop this behaviour?

**Comment by Jaki1091** [comment] 2020-04-16 08:54
@mahtDFR thnk you for the support, just solved the problem by removing from the start gcode 
M104 S215
M140 S60
I thought that by removing these two comands the printer would have extruded at room temperature, instead it reads the temperature set in the material tab.
Cheers

**Comment by mahtDFR** [comment] 2020-04-16 09:04
Ah, good to hear you have a solution!

**Comment by Hotled** [comment] 2020-04-30 22:43
This is not a fix.
It is an issue if your using a Geeetech a10. 
Copy all your settings and use a profile from an Ender3.
Something has bugged the Geeetech profiles.

**Comment by mahtDFR** [comment] 2020-05-01 07:54
> Something has bugged the Geeetech profiles.

Maybe you can share a project file with me so I can reproduce your issue?

**Comment by mahtDFR** [comment] 2020-05-01 08:01
@Hotled We would ask that the contributor makes a fix for this, we don't maintain the profiles and can't test them either. Is it just the start gcode or is there more?

**Closed** 2020-06-19 16:04 UTC
Labels: Status: Needs Info
