### ISSUE TITLE
Top / Bottom Thickness field loses focus when edited

### ISSUE THREAD

**Issue by sc0tt** [Ultimaker/Cura#13733] opened 2022-11-04 18:17 UTC
### Application Version

5.2.1

### Platform

Windows 10

### Printer

N/A

### Reproduction steps

1. Focused the "Top / Bottom Thickness" field (with a current value of 0.8)
![image](https://user-images.githubusercontent.com/915870/200044753-9c791594-50e3-49ba-a56f-15ea6dbdef35.png)

2. Hit backspace once. The field loses focus and turns yellow
![image](https://user-images.githubusercontent.com/915870/200045063-be713832-50a3-4333-9eea-9bb7f5677284.png)

3. Focus the "Top / Bottom Thickness" field
4. Pressed backspace until the field was cleared
5. Entered "1". The field loses focus.
![image](https://user-images.githubusercontent.com/915870/200045291-6b3ba6f7-071e-4c28-8aba-10c209e3b559.png)

5. Focus the "Top / Bottom Thickness" field
6. Hit backspace once
7. Added ".2" to make the final thickness "1.2"

### Actual results

In steps 2 and 5, the "Top / Bottom Thickness" field lost focus when it should not have.

### Expected results

Ideally focus wouldn't be lost. It seems like it's happening since that now makes the field error out. It would make sense not to lose focus while actively editing, even if value results in an error since. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Video of issue:
https://user-images.githubusercontent.com/915870/200046601-bb8f59c6-56d0-42fc-abf1-a7cfdbb277ea.mp4

STL if useful:
[new_base.zip](https://github.com/Ultimaker/Cura/files/9941064/new_base.zip)

**Comment by MariMakes** [comment] 2022-11-07 10:48
Hey @sc0tt,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12949
We have a ticket on our backlog with the intent to improve this behavior, it helps to collect 
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12949

**Closed by MariMakes** 2022-11-07 10:48 UTC
Labels: Type: Bug, Status: Triage
