### ISSUE TITLE
[4.3] Unable to select cloud connected printer (removed selection screen)

### ISSUE THREAD

**Issue by Quasardian** [Ultimaker/Cura#6578] opened 2019-10-25 07:06 UTC
**Application version:**
4.3.0

**Platform:**
Windows 10

**Printers:**
Ultimaker S5 (3x)

**Reproduction steps:**
Have multiple printers connected to the cloud
Print over network
No selection screen to choose what printer to use

**Expected results:**
By default have the option to select what printer to use.
Possibility to disable it all together in the settings.

**Additional information:**
This function is vital for our way of using the printers, some others on the forums are complaining about this issue as well. For the time being we had to roll back to Cura 4.2.

**Comment by ChrisTerBeke** [comment] 2019-10-25 07:32
Duplicate of https://github.com/Ultimaker/Cura/issues/6433.

**Closed by ChrisTerBeke** 2019-10-25 07:32 UTC
Labels: Type: Bug

**Comment by Quasardian** [comment] 2019-10-25 08:18
@ChrisTerBeke Thank you I wasn't able to find a duplicate.
