### ISSUE TITLE
slicing issue with custom supports

### ISSUE THREAD

**Issue by legocomputerguy** [Ultimaker/Cura#16006] opened 2023-07-04 21:19 UTC
### Application Version

UltiMaker Cura 5.4.0-beta.1

### Operating System

Windows 10 

### Printer

Ender 3 S1 Pro

### Reproduction steps

i first started out by making a bed-level test 
it worked perfectly

but when I tried slicing a big model of mine it didn't 
the problem is bec I used custom supports 
please fix this so I can use the custom supports add on 

after slicing the model, it gives me an error: "Slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker"

### Actual results

after slicing the model, it gives me an error: "Slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker"

### Expected results

it should slice properly and allow me to download it 

### Checklist of files to include

- [x] Log file
- [x] Project file

### Additional information & file uploads

![CE3S1PRO_glove ins - UltiMaker Cura 7_4_2023 2_16_15 PM](https://github.com/Ultimaker/Cura/assets/132730851/a6176e3f-16d1-4644-9143-0531243ab67d)

**Comment by MariMakes** [comment] 2023-07-26 09:26
Hey @legocomputerguy,

I recognize this issue. 🔎
This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/15836, where using custom supports would result in a slicing crash. 

It's resolved in the 5.4 stable release, you can download the Cura version with the fix here: https://github.com/Ultimaker/Cura/releases/tag/5.4.0
I'll close this issue since it's a duplicate and resolved. 

Thanks again, and please let us know if you run into any other issues 💪

**Closed by MariMakes** 2023-07-26 09:26 UTC
Labels: Type: Bug, Status: Triage
