### ISSUE TITLE
Layer on wrong z position

### ISSUE THREAD

**Issue by SirTremblor** [Ultimaker/Cura#11062] opened 2021-12-13 05:33 UTC
### Application Version

4.12.1

### Platform

Windows 10

### Printer

Ai3M

### Reproduction steps

1. Loading an stl object into the slicer
2. Taking my properties
3. Slicing

### Actual results

The 23th layer is visualizised (maybe also printed, doesn't tested) at z position 0mm

### Expected results

The layer at the right spot

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[Anycubic.zip](https://github.com/Ultimaker/Cura/files/7701227/Anycubic.zip)
[2021-12-13 06-40-24.zip](https://github.com/Ultimaker/Cura/files/7701259/2021-12-13.06-40-24.zip)

**Comment by fvrmr** [comment] 2021-12-13 09:21
Hi @SirTremblor thank you for your report.
I can't reproduce your issue but with your video it show your issue clearly. 
It is only a visualization bug, see https://github.com/Ultimaker/Cura/issues/7412. And we have a ticket on our backlog for this. 

I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-12-13 09:21 UTC
Labels: Type: Bug
