### ISSUE TITLE
Arrange All Not Working Properly

### ISSUE THREAD

**Issue by minimal3dp** [Ultimaker/Cura#12038] opened 2022-04-30 18:12 UTC
### Application Version

5.0.0 

### Platform

Mac Monterey

### Printer

CR 6 SE

### Reproduction steps

I have this model on the bed https://www.thingiverse.com/thing:1543152/files  

I multiplied it 3x so I have a total of 4 copies on the bed. When I use the context menu "Arrange All Models" it tells me it can't find a location. I didn't have to do anything crazy to fit all models just moved them onto the bed.

### Actual results

Can't arrange models on the bed

### Expected results

Arranged Models

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CCR6SE_DampeningFeet2020.3mf.zip](https://github.com/Ultimaker/Cura/files/8597570/CCR6SE_DampeningFeet2020.3mf.zip)

**Comment by fvrmr** [comment] 2022-05-02 14:00
Hi @minimal3dp thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9793, so I will close this issue.

**Closed by fvrmr** 2022-05-02 14:00 UTC
Labels: Type: Bug
