### ISSUE TITLE
Custom FFF printer with 1.75 filament - weak print

### ISSUE THREAD

**Issue by WalkerLarry** [Ultimaker/Cura#4593] opened 2018-10-17 10:08 UTC
**Application Version**

Cura 3.5.1

**Platform**

MacOS 10.14 (64bit)
Debian 9.5 (64bit)

**Printer**

zonestar p802qr2

**Steps to Reproduce**

Add local printer "Custom FFF printer" and set the filament thickness to 1,75

**Actual Results**

The print is soft, and the plastic quantity do not suffice.
I think the diameter of the input filament stays set to 2.85, thus the extruded filament is too thin.
I use a 0.4 extruder and a 1.75 PLA filament.

**Expected results**

Normally, the shell should be strong and the skin full.

**Additional Information**

In order to check if this is not a problem with my printer, I re-printed an old design I sliced with Cura 2.7.0.
The print was OK so my printer work OK.

**Comment by diegopradogesto** [comment] 2018-10-17 10:19
Duplicate of #4582

**Closed by diegopradogesto** 2018-10-17 10:19 UTC
