### ISSUE TITLE
[5.0 beta]  Reloading a project after overwriting imports models incorrectly

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#12089] opened 2022-05-04 14:27 UTC
### Application Version

5.0 beta

### Platform

win10

### Printer

custom fff

### Reproduction steps

1 Load the project.
2 Save project and overwrite the same file.
3 Click reload

### Actual results

All models are now duplicates of the same model when using the reload function.

With import or drag&drop, it works as intended.

### Expected results

Should work as it does with import or drag&drop.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Project:
![1](https://user-images.githubusercontent.com/32172100/166701520-ed98293a-eedf-405c-8c10-564e32c52855.jpg)
Export and overwrite project, then hit "reload":
![2](https://user-images.githubusercontent.com/32172100/166701641-d1fa33ad-979e-461d-b3eb-ff6e67e23f41.jpg)
Result:
![3](https://user-images.githubusercontent.com/32172100/166701673-a782d712-655c-4b84-9479-9b4093da7375.jpg)
[OpticoolerFunels.3mf.zip](https://github.com/Ultimaker/Cura/files/8621134/OpticoolerFunels.3mf.zip)

**Comment by GregValiant** [comment] 2022-05-04 20:44
That's an odd one.
If Reload is hit right after saving then one or more models is replaced.  If the build plate is cleared after the "reload" and the file is opened in a regular way then it opens correctly.

**Comment by printingotb** [comment] 2022-05-05 08:48
Hmm, If I first clear the buildplate and then hit Reload, no objects at all appear on the buildplate. It stays clear. Nothing in the object list either.

**Comment by fvrmr** [comment] 2022-05-05 12:45
Hi @printingotb thank you for your report.
I can reproduce this so I will bring it up with the team. Keep you posted!

**Comment by fvrmr** [comment] 2022-05-09 14:18
It seems like that this behaviour is not defined. We have ticket on our backlog for this, devs see CURA-7339

**Comment by MariMakes** [comment] 2024-01-31 13:37
Quick update from our side 👋

I believe this issue is resolved with this pull request from the community: https://github.com/Ultimaker/Cura/pull/16610 which will be available with the next release. 

We recently released a Nightly version, which already includes this fix, so if you want to you can already try it out here https://github.com/Ultimaker/Cura/discussions/18080

To me, it doesn't seem like a bug in Ultimaker Cura, since we have a solution in place. Apologies for any inconvenience caused by our delayed response. I'll be closing this issue. I hope you understand.

**Closed by MariMakes** 2024-01-31 13:37 UTC
Labels: Type: Bug, Status:  On Backlog
