### ISSUE TITLE
Slicing Failed (Ultimaker-Cura-5.2.0-beta)

### ISSUE THREAD

**Issue by leoheck** [Ultimaker/Cura#13464] opened 2022-10-04 01:20 UTC
### Application Version

Ultimaker-Cura-5.2.0-beta-linux-modern.AppImage

### Platform

Ubuntu 22.04

### Printer

Ender-3

### Reproduction steps

click Slice it =-> Fails

### Actual results

nothing happens

### Expected results

to see the slices

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/1277920/193714028-b64cf41b-b8a5-485c-bb04-ad01b1f322bd.png)

**Comment by MariMakes** [comment] 2022-10-04 09:25
Thanks for the report!

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13422
We have our developers working hard on a solution.
Apologies for the inconvenience 😞 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/13422

**Closed by MariMakes** 2022-10-04 09:25 UTC
Labels: Type: Bug, Status: Triage

**Comment by leoheck** [comment] 2022-10-04 14:10
Is there anything else I can do to give you better idea on what is happening or do they already know why this is happening?

**Comment by leoheck** [comment] 2022-10-04 18:17
hm, nice, thank you @MariMakes, I can't wait to test it!

**Comment by leoheck** [comment] 2022-10-06 14:26
Thanks, it worked for me.
