### ISSUE TITLE
[3.5] Brim inside the model while set to external only

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#4775] opened 2018-11-10 15:37 UTC
**Application Version**
3.5.0

**Platform**
Windows 10 x64

**Printer**
Cr-10s

**Steps to Reproduce**
Use the benchy file.

**Actual Results**
Inside the D letter there is the brim.

**Expected results**
Only the external brim should exist

**Additional Information**
![brim internal](https://user-images.githubusercontent.com/20385116/48303146-ec310480-e506-11e8-9f05-2aaf9cd9a5be.png)
[CCR10S_3DBenchy.zip](https://github.com/Ultimaker/Cura/files/2568523/CCR10S_3DBenchy.zip)

**Comment by smartavionics** [comment] 2018-11-10 17:34
Duplicate of https://github.com/Ultimaker/Cura/issues/3482.

**Comment by diegopradogesto** [comment] 2018-11-11 10:47
Also duplicate of #4222. That one is still open, so you can keep tracking of that issue.

**Closed by diegopradogesto** 2018-11-11 10:47 UTC
