### ISSUE TITLE
[3.2.1] Startup Crash Corrupted Machine Files

### ISSUE THREAD

**Issue by chepo92** [Ultimaker/Cura#3643] opened 2018-04-10 01:51 UTC
**Application Version**
3.2.1

**Platform**
Win7 

**Display Driver**
Intel HD 3000 

**Printer**
Not conected printer, but had left an arduino UNO (with GRBL) conected over USB

**Steps to Reproduce**
Just start cura, loading window and crashed, "problem starting cura, had two options restore defaults or close, first chose close, tried disconecting USB devices, retry... crash again, close, reboot pc... retry, crash, close, retry, chose restore defaults then all config lost, but cura started

**Actual Results**
Configurations and machine profiles lost, it said it would backup configs, still looking for backup files 

Attached log. 
[crash.txt](https://github.com/Ultimaker/Cura/files/1892535/crash.txt)

Edit: Found backups
**Steps to Reproduce**
restored "quality" and "definition_changes" folders to Cura folder, no issues. Then restored "machine_instances" and crashed again, will try to identify wich one is causing trouble (have more than 1 machine). 

Edit2: For some reason all machine profiles and extruders are corrupt, hopefully had some of them from V3.1

[machine_instances(3.2.1 corrupt).zip](https://github.com/Ultimaker/Cura/files/1892590/machine_instances.3.2.1.corrupt.zip)
[machine_instances(from 3.1).zip](https://github.com/Ultimaker/Cura/files/1892591/machine_instances.from.3.1.zip)

[extruders.zip](https://github.com/Ultimaker/Cura/files/1892626/extruders.zip)

**Comment by Vandrasc** [comment] 2018-04-10 10:32
@LipuFei, Is this what we already addressed in 3.3? Thank you!

**Comment by LipuFei** [comment] 2018-04-10 11:13
Hi @chepo92 , looks like you have some corrupted data somehow. I don't know how they got there. I think if you remove the following corrupted files it should fine. If you check those files, you can find they only contain bytes `\x00`

In `machine_instances` directory:
```
MMK+HB.global.cfg
MMK+2x.global.cfg
Prusa+i3.global.cfg
Multimaker+S.global.cfg
```

In `extruders` directory:
```
custom_extruder_1+%234.extruder.cfg
custom_extruder_6+%236.extruder.cfg
custom_extruder_8+%233.extruder.cfg
Prusa+i3+fdmextruder.extruder.cfg
custom_extruder_8+%235.extruder.cfg
custom_extruder_7+%235.extruder.cfg
custom_extruder_7+%234.extruder.cfg
custom_extruder_3+%232.extruder.cfg
custom_extruder_5+%232.extruder.cfg
custom_extruder_1+%233.extruder.cfg
custom_extruder_4+%236.extruder.cfg
custom_extruder_2+%233.extruder.cfg
custom_extruder_5+%236.extruder.cfg
custom_extruder_8+%236.extruder.cfg
custom_extruder_5+%235.extruder.cfg
custom_extruder_2+%234.extruder.cfg
custom_extruder_1+%235.extruder.cfg
custom_extruder_2+%236.extruder.cfg
custom_extruder_7+%233.extruder.cfg
custom_extruder_4+%233.extruder.cfg
custom_extruder_3+%236.extruder.cfg
ultimaker_original_dual_2nd+%232.extruder.cfg
custom_extruder_2+%232.extruder.cfg
custom_extruder_3+%235.extruder.cfg
custom_extruder_5+%234.extruder.cfg
custom_extruder_1+%236.extruder.cfg
custom_extruder_6+%235.extruder.cfg
custom_extruder_2+%235.extruder.cfg
ultimaker_original_dual_1st+%232.extruder.cfg
custom_extruder_6+%234.extruder.cfg
custom_extruder_7+%232.extruder.cfg
custom_extruder_3+%234.extruder.cfg
custom_extruder_4+%232.extruder.cfg
custom_extruder_4+%235.extruder.cfg
custom_extruder_8+%234.extruder.cfg
```

**Comment by Ghostkeeper** [comment] 2018-05-01 13:28
Duplicate of https://github.com/Ultimaker/Cura/issues/3561

**Closed by Ghostkeeper** 2018-05-01 13:28 UTC
Labels: Category: 3rd-Party, Category: Cura, Status: Needs Info, Type: Bug
