### ISSUE TITLE
Unable to connect to moonraker with 5.4.0

### ISSUE THREAD

**Issue by Myklt8** [Ultimaker/Cura#16056] opened 2023-07-07 16:52 UTC
### Cura Version

5.4.0

### Operating System

Windows11

### Printer

Creality Ender 3

### Reproduction steps

Sliced the file
upload to printer
takes a long time but then times out

### Actual results

Fails to connect to moonraker
![Screenshot 2023-07-07 114656](https://github.com/Ultimaker/Cura/assets/126296783/a0caab0d-6f4d-4e18-b1c9-0f95ee689f5b)

### Expected results

should have uploaded to the printer
I am seeing this issue a lot on FB and groups are telling people to roll back

### Add your .zip and screenshots here ⬇️

No Data log exists

**Comment by MariMakes** [comment] 2023-07-26 21:22
Hey @Myklt8,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 

As an UltiMaker employee, I don't have access to Moonraker 3D Printers, so I can't really help with troubleshooting your issue. Could it be related to the plug-in you are using? Are you using the latest version? You can download it here: https://github.com/emtrax-ltd/Cura2MoonrakerPlugin

To me, it doesn't seem like a bug in Ultimaker Cura.
Apologies for any inconvenience caused by our delayed response. 
I'll be closing this issue. I hope you understand.

**Closed by MariMakes** 2023-07-26 21:22 UTC
Labels: Type: Bug, Status: Triage

**Comment by Casperdme** [comment] 2023-08-25 12:23
I have the exact same issue.

**Comment by MariMakes** [comment] 2023-08-28 14:58
@Casperdme, don't forget to reach out to the plug-in creator here https://github.com/emtrax-ltd/Cura2MoonrakerPlugin/issues/new

If it turns out to be an issue in Cura, I'm happy to take another look

**Comment by Casperdme** [comment] 2023-08-28 17:19
Thank you for this information.



Op ma 28 aug. 2023 16:58 schreef Mariska ***@***.***>:
