### ISSUE TITLE
Cannot slice with 5.4 after loading STL file

### ISSUE THREAD

**Issue by gliderpilotmp** [Ultimaker/Cura#16693] opened 2023-09-08 09:48 UTC
### Cura Version

5.4

### Operating System

Windows 10

### Printer

Anycubic i3 Mega S

### Name abnormal settings

No

### Describe model location

Yes, both. If rotated or moved it works

### Describe your model

No

### Add your .zip here ⬇️

It works with Ultimaker Version 5.2.2
[AI3MSPRO_RPIcam_01i__partno_02_top-plate.zip](https://github.com/Ultimaker/Cura/files/12558047/AI3MSPRO_RPIcam_01i__partno_02_top-plate.zip)

**Comment by GregValiant** [comment] 2023-09-08 14:11
Thanks for the report and the file.
There is an often reported bug in 5.4.0 (and 5.3.1) that can keep a good model from slicing.  There are three workarounds that can often fool the bug and allow the model to slice.

- Move the model away from the mid-point of the Cura build plate.
- Rotate the model in Cura.
- Change the initial Layer Height by just a bit (Ex: from .20 to .23).

I was able to slice the model after I rotated it so I'll mark this as a duplicate of those many other reports and I'll go ahead and close this as the Cura team has lots of examples of this behavior and they continue to work on this problem.  I hope you understand.

BTW - 5.2.2 does not have this particular bug.

![image](https://github.com/Ultimaker/Cura/assets/64202104/817690d0-a7b8-4b13-b476-5139fcde5af9)

**Closed** 2023-09-08 14:12 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error :collision:
