### ISSUE TITLE
i get an unexpected error when trying to slice

### ISSUE THREAD

**Issue by toshimaro** [Ultimaker/Cura#17750] opened 2023-12-23 16:27 UTC
### Cura Version

5.6.0

### Operating System

windows11

### Printer

anycubic kobra neo

### Describe your model

no

### Add your .zip here ⬇️

[unexpextederrorproject.zip](https://github.com/Ultimaker/Cura/files/13759623/unexpextederrorproject.zip)

**Comment by 5axes** [comment] 2023-12-23 16:41
An other "Print thin walls" issue : https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-7790452
![image](https://github.com/Ultimaker/Cura/assets/11015345/48ffea5e-0c8e-4623-98b6-02924f3ede0a)
or with tree support.
![image](https://github.com/Ultimaker/Cura/assets/11015345/1db58adf-f4bb-4f1c-827e-995b4f5bb8b1)

Duplicate : Slice Failed due to **Print Thin Walls**

https://github.com/Ultimaker/Cura/issues/17725
https://github.com/Ultimaker/Cura/issues/17679
https://github.com/Ultimaker/Cura/issues/17676
https://github.com/Ultimaker/Cura/issues/17671
https://github.com/Ultimaker/Cura/issues/17606
https://github.com/Ultimaker/Cura/issues/17560
https://github.com/Ultimaker/Cura/issues/17528
https://github.com/Ultimaker/Cura/issues/17503
https://github.com/Ultimaker/Cura/issues/17499
https://github.com/Ultimaker/Cura/issues/17470
https://github.com/Ultimaker/Cura/issues/17467
https://github.com/Ultimaker/Cura/issues/17457
https://github.com/Ultimaker/Cura/issues/17456
https://github.com/Ultimaker/Cura/issues/17496
https://github.com/Ultimaker/Cura/issues/17478
https://github.com/Ultimaker/Cura/issues/17439
https://github.com/Ultimaker/Cura/issues/17438
https://github.com/Ultimaker/Cura/issues/17410
https://github.com/Ultimaker/Cura/issues/17367
https://github.com/Ultimaker/Cura/issues/17344
https://github.com/Ultimaker/Cura/issues/17177
https://github.com/Ultimaker/Cura/issues/16688
https://github.com/Ultimaker/Cura/issues/16515
https://github.com/Ultimaker/Cura/issues/16417

**Comment by toshimaro** [comment] 2023-12-23 18:08
How can I slice without encountering an "unexpected error"?

**Comment by 5axes** [comment] 2023-12-23 18:17
This error is due to the parameter "Print Thin Walls" . You just have to unset this parameter.

**Comment by toshimaro** [comment] 2023-12-23 18:28
![image](https://github.com/Ultimaker/Cura/assets/154691516/e822a10e-86fb-4e7d-bc6f-366770184b9d)
I've unset "Print Thin Walls," but I'm still getting an "unexpected error" when slicing. Why is this happening?

**Comment by 5axes** [comment] 2023-12-23 18:40
Could be an other issue as you are running Cura under Windows 11. Many user have also reprorted some issue on this OS.  You will have to wait for a deaper analyse from the developpent team.

**Comment by toshimaro** [comment] 2023-12-24 06:23
I am having trouble locating the 'Print Thin Walls' parameter in Cura. I have tried looking under the Custom settings but cannot find it. Can someone guide me to the exact location of this setting in the latest version of Cura? Any help would be greatly appreciated. Thank you!

**Comment by toshimaro** [comment] 2023-12-24 07:46
thx i found it!!

**Comment by MariMakes** [comment] 2024-01-18 15:30
Hi @toshimaro,

Quick update from our side 👋
We are introducing a new tool to analyze slicing crashes like the one you reported. 💪

Even with the changes we made in the latest versions of Cura we still see that your model crashes. 🫤 But we have added your project file to our analyzing tool and found there were at least 10 crashes that were similar to yours, which helps us to narrow down what the cause is of your crash so we can resolve this for you and others.
Hopefully, we can find a solution soon 🤞

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/17438

**Closed by MariMakes** 2024-01-18 15:30 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:

**Comment by HellAholic** [comment] 2024-04-03 13:11
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
