### ISSUE TITLE
Error en la informacion de los tiempos

### ISSUE THREAD

**Issue by secheve** [Ultimaker/Cura#1941] opened 2017-06-06 15:02 UTC
![image](https://cloud.githubusercontent.com/assets/29232405/26835898/aa302796-4ad9-11e7-8827-70a287b7fdca.png)

**Comment by ChrisTerBeke** [comment] 2017-09-28 08:45
Closing since we cannot reproduce and no further information has been provided. Please comment if this is still an issue for you.

**Closed by ChrisTerBeke** 2017-09-28 08:45 UTC
Labels: bug

**Comment by Ghostkeeper** [comment] 2017-10-03 09:55
Looks like this is a duplicate of #1912 actually. Please look there for more conversation.
