### ISSUE TITLE
Slicing failed with unexpected error

### ISSUE THREAD

**Issue by leeroywking** [Ultimaker/Cura#14430] opened 2023-01-31 06:02 UTC
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Creality Ender-3 Pro

### Reproduction steps

Tried to slice a ventilation snorkle I designed in F360

### Actual results

"Slicing failed with unexpected error. Please consider reporting a bug on our issue tracker"

### Expected results

Create a file for printing. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[CE3PRO_snorkle.zip](https://github.com/Ultimaker/Cura/files/10543312/CE3PRO_snorkle.zip)

**Comment by MariMakes** [comment] 2023-02-03 16:08
Hey @leeroywking,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13643.
Where models would not slice if they were in the complete center of the buildplate. 

It has been resolved and I was able to slice your model with an internal version. As a workaround you can move it away from the center of the buildplate. 
![image](https://user-images.githubusercontent.com/40423138/216650747-ffaae462-a222-43fd-9019-6bbf0c9a0b36.png)

I'll close the issue, thanks again for your report 👍

**Closed by MariMakes** 2023-02-03 16:08 UTC
Labels: Type: Bug, Status: Triage
