### ISSUE TITLE
[Feature request] Different Layer Height for Inner and Outer Walls (say, 0.05mm for outer, 0.3mm for inner walls)

### ISSUE THREAD

**Issue by megablue** [Ultimaker/Cura#5341] opened 2019-02-21 20:24 UTC
The idea is to use finer layer heights for the outer wall(s), and thicker layer heights on the inner walls and infills, hence you get the best of both worlds, reduce print time of the thick layers, improved print quality for the finer layers.

You can pretty much look at it as Combine Infill in s3d or Infill layer thickness in cura but this also apply to the inner walls instead of just the infills. 

![image](https://user-images.githubusercontent.com/164641/53199119-34f56f00-3659-11e9-910f-cc4a0ed1f86c.png)

![image](https://user-images.githubusercontent.com/164641/53199142-4474b800-3659-11e9-8250-a25e5dd6306e.png)

example print: https://imgur.com/a/pHXrZtf

**Why?**
drastically speed up the fine layers prints and maintaining the strength of a print 

**Flaws/Challenges**
the flaw is the finer layers and thicker layers will sometimes overlap with each other, but it can be solved by doing 2 tracks on the finer layers and/or having a gap between the outer and inner wall. the slicer will need to workout the how to deal with the colliding slopes

a longer and pointier nozzle will work better as it can deal with overlapping slopes better.
the challenge will be to figure out the collisions, this is usually not a problem if the slopes are not too steep.

allow the user to specify the nozzle “angle” so that calculation can be done on the limits of the slopes - as per layer height differences.

**Comment by Ghostkeeper** [comment] 2019-02-22 08:57
We've looked at this before (it was my original idea for achieving variable layer height), but you can't just combine walls like you could for infill because you can't guarantee that walls that are above each other align perfectly in X/Y. That is to say, walls are almost never exactly on top of each other. Also there was the suspicion that a change in flow so close to the surface would be very visible on the outside.

I'm going to close this now as a duplicate of https://github.com/Ultimaker/Cura/issues/2982.

**Closed by Ghostkeeper** 2019-02-22 08:57 UTC
