### ISSUE TITLE
Cura 4.12.0 installation

### ISSUE THREAD

**Issue by hanheik** [Ultimaker/Cura#10851] opened 2021-11-16 21:30 UTC
### Application Version

4.12.0

### Platform

Windows 10

### Printer

Artillery Sidewinder X2

### Reproduction steps

Install 4.12.0

### Actual results

i was asked to keep the configs of the previous version, but the mousepointer was automatically on "no" when i pushed the mousebutton, so i lost my settings

### Expected results

mousebutton to be automatically on "yes" keep settings

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

nothing additional

**Comment by fvrmr** [comment] 2021-11-19 13:50
Hi @hanheik thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/8233
And this is linked to a ticket on our backlog to make this more clear to users. 
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-11-19 13:50 UTC
Labels: Type: Bug
