### ISSUE TITLE
CURA crashes when I try to load a file.

### ISSUE THREAD

**Issue by bulrich2455** [Ultimaker/Cura#9757] opened 2021-05-03 13:05 UTC
### Application Version

4.9.0

### Platform

Windows 10

### Printer

Ender 5 plus

### Reproduction steps

I open CURA as normal.

### Actual results

It crashes as soon as I try to import the file.

### Expected results

Work like it used to before the new version.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I can't.

**Comment by fvrmr** [comment] 2021-05-03 14:17
Hi @bulrich2455 thank you for your bug report. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9668 you can find there a work around.
Since it is a duplicate I will close this issue.

**Closed by fvrmr** 2021-05-03 14:17 UTC
Labels: Type: Bug
