### ISSUE TITLE
Feature blowing mode for hanging parts

### ISSUE THREAD

**Issue by Goodfeat** [Ultimaker/Cura#6848] opened 2019-12-24 04:40 UTC
Hello. 

Is it possible to add a function for blowinghanging parts.

Some parts can be printed without supports. However, in long sections of overhanging parts without supports, the plastic is twisted upward.

The program has a similar setting

![image](https://user-images.githubusercontent.com/44455128/71393811-0fab0600-265a-11ea-9a34-289e9f6d9afe.png)

But this setting only works on existing supports.
Is it possible to add a function for blowing hanging parts without support?

Thanks

**Comment by Ghostkeeper** [comment] 2019-12-24 06:31
There is one, sort of. It's the [Bridging Fan Speed setting](https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/experimental/bridge_fan_speed.md). It's under Experimental, and can be seen once the extra bridging settings are enabled.

**Comment by Goodfeat** [comment] 2019-12-24 06:34
Well, I will try it if I find it.
I just don’t use bridge setup

**Comment by Goodfeat** [comment] 2019-12-24 07:02
Unfortunately this is not quite what I need
This setting only works at extreme angles.
when plastic is in the air
![image](https://user-images.githubusercontent.com/44455128/71399038-1cd1f000-266e-11ea-8b46-2f03e9bdb126.png)

The program has two more settings

![image](https://user-images.githubusercontent.com/44455128/71399179-923dc080-266e-11ea-9622-e5e68173665d.png)

These settings are clearly related to the dangling elements.
Is it possible to add here the third setting for blowing the hanging elements?

**Comment by smartavionics** [comment] 2019-12-24 07:20
If you install one of my Cura builds you get these settings...

![Screenshot_2019-12-24_07-19-07](https://user-images.githubusercontent.com/585618/71400135-bc1ac700-261d-11ea-8d94-6d77aa532361.png)

You can find my builds at https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0. Please read the README.md there.

**Comment by Ghostkeeper** [comment] 2019-12-24 07:56
Ah right, this is a duplicate of https://github.com/Ultimaker/Cura/issues/6656 then. Please continue the discussion there!

**Closed by Ghostkeeper** 2019-12-24 07:56 UTC
Labels: Type: New Feature
