### ISSUE TITLE
3.2 Beta Won't launch

### ISSUE THREAD

**Issue by Patrick804** [Ultimaker/Cura#3180] opened 2018-01-24 23:13 UTC
![3 2 launch error](https://user-images.githubusercontent.com/35784853/35362122-e55df832-015b-11e8-96e1-1004d3a6c1f2.png)

**Application Version**
<3.2 Beta>

**Platform**
<Windows 10 -->

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by ChrisRiddell** [comment] 2018-01-24 23:37
Duplicate of #3170

**Comment by Patrick804** [comment] 2018-01-24 23:39
I got it to launch. My first time here so I neglected to read previous posts. I deleted the roaming files and it started right up.

**Closed** 2018-01-24 23:39 UTC

**Comment by fieldOfView** [comment] 2018-01-25 07:12
Deleting the config should not be necessary though, so it is still a bug. But it is a duplicate of some other reports.

**Comment by jackha** [comment] 2018-01-25 13:49
We've created an issue to fix this problem before the upcoming release. Devs: CURA-4868

**Comment by LipuFei** [comment] 2018-01-29 09:58
Hi @Patrick804 , could you upload your cura directory so we can check what happened? It's located in `C:\Users\<your-username>\AppData\Roaming\cura`. Thanks
