### ISSUE TITLE
Cura 4.6.1 Change Filament gcode extrudes when should retract

### ISSUE THREAD

**Issue by edster99** [Ultimaker/Cura#7650] opened 2020-05-01 20:02 UTC
**Application version**
4.6.1

**Platform**
Windows 10

**Printer**
Ender 3 Pro

**Reproduction steps**
1. Sliced a simple file - square with a letter on
2. Slected 'change filament' post processing gcode
3. Selected 30mm initial retraction
4. Gcode created with 30mm extrusion, not retraction 

**Screenshot(s)**
N/A

**Actual results**
This line created 
M600 E30.00 L300.00 X20.00 Y20.00 ; Generated by FilamentChange plugin

**Expected results**
M600 G10 30.00 L300.00 X20.00 Y20.00 ; Generated by FilamentChange plugin
I think that's whats needed, I am not a gcode expert. 

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
Nothing really : swap the extrude code for retract code.

[SingleZLabel Generic PLA lw 0.4mm lh 0.2mm if 15% ext1 210C bed 60C.gcode.txt](https://github.com/Ultimaker/Cura/files/4566095/SingleZLabel.Generic.PLA.lw.0.4mm.lh.0.2mm.if.15.ext1.210C.bed.60C.gcode.txt)

**Comment by Ghostkeeper** [comment] 2020-05-07 00:31
Duplicate of https://github.com/Ultimaker/Cura/issues/7502

The gist of the matter seems to be that different firmware handles this differently and you basically need to guess which direction your firmware is using.

**Closed by Ghostkeeper** 2020-05-07 00:31 UTC
Labels: Type: Bug
