### ISSUE TITLE
The problem of using brim and the full printable area of the printer for narrow bases

### ISSUE THREAD

**Issue by saf-yg** [Ultimaker/Cura#13993] opened 2022-12-08 08:54 UTC
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Ghost 5

### Reproduction steps

![113130](https://user-images.githubusercontent.com/15922576/206397639-b0fcce17-9857-4f81-b008-8f8ce81bdbe2.png)
Brim (scirt,..) size affects print margins. Cannot use full printable area with brim for narrow bases. If you print without a brim, the model falls off.

### Actual results

If you change to resize the model, slicing of layers is not possible.
![2022-12-08 114506](https://user-images.githubusercontent.com/15922576/206400655-2ce6f051-53ca-4b79-b242-c41d8d1142a2.png)

### Expected results

I would like that the size of the calculated model would be correctly taken into account or after the warning there would be an opportunity to continue working with slicing at your own risk.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

It seems to me that additional files are not needed to form an idea about this problem.

**Comment by GregValiant** [comment] 2022-12-09 20:14
Thanks for the report.
This has come up before and @Ghostkeeper did a nice writeup on why this is the behavior.  I was unable to find the reference but it boils down to...
When you bring any model onto the Cura build plate all Cura really knows are the dimensions of the bounding box that contains the model.  The measurements of the bounding box are X x Y x Z.  If the X and Y + build plate adhesion runs out of bounds then Cura won't slice.  The only way to determine that the features on Layer:0 are within the allowed area of the build plate are to slice the model and then do an analysis of the outside dimensions of the skirt/brim/raft.
There are workarounds for this that involve making the Cura build plate larger and then adding an M206 line to the very end of the StartUp Gcode to adjust the Home Offsets and move the print to the center of the printers real build plate.  An M206 should also be added to the beginning of the Ending Gcode to reset the Home Offset.

The Cura team will decide on this but right now what you see is expected behavior.  The last time this came up I think it was deferred.

**Comment by Bzzz** [comment] 2024-11-12 19:47
Probably related to #10166?
I just stumbled across this when scaling up a calibration cube for the printer of a friend that is said to have build plate adhesion issues. Just doing some silly 45°ish hollow tower thing as a simple benchmark of adhesion.
The scaled and tilted version slices fine with no or little brim, but once the brim is scaled too large, it fails slicing. According to 10166 (Cura 5.3), brims that exceed the build plate should just be discarded without error messages, since a partial large brim is still better than a smaller brim. Cura 5.8 however fails to slice.

30mm
![Screenshot_20241112_204247](https://github.com/user-attachments/assets/f2de7837-b35c-4a13-bfd1-68584b8c9774)
40mm (same model size)
![Screenshot_20241112_204300](https://github.com/user-attachments/assets/9a2cbe4b-eee5-4fa7-b4f2-fac42a26174f)

**Comment by GregValiant** [comment] 2024-11-13 09:48
Without a project file it's not possible to determine exactly why that happened.
This is in 5.8.0 with the print sequence "All at Once".
![image](https://github.com/user-attachments/assets/095a929e-c153-424d-9dbb-202e147b92b6)

The only change here is to One at a Time.
![image](https://github.com/user-attachments/assets/9d2f501c-c3ac-4cf1-bccc-d78faf86a573)

**Comment by Bzzz** [comment] 2024-11-13 20:06
That is correct.
Running this sample with brim 10mm will slice, while with 20mm it won't.
Unless I set print sequence to all at once, then even a full-plate 300mm brim will do. Any partial brim is clipped at the edge of the print area as it should.

[cura13993.zip](https://github.com/user-attachments/files/17738654/cura13993.zip)

**Comment by GregValiant** [comment] 2024-11-13 23:54
The rules for One-at-a-Time are different as the machine head dimensions come into play.  If you are only printing a single part then set Cura to All-at-Once.
You can't print multiples of that test part in one-at-a-time so just set Cura to All-at-Once.

I'll remove the bug label from this and close it as what you are seeing is expected behavior given your settings.  I hope you understand.

**Closed by GregValiant** 2024-11-13 23:54 UTC
Labels: Type: Discussion, Status: Under Investigation

**Comment by Bzzz** [comment] 2024-11-14 00:34
I don't, since I would expect the edge cases "all 1 items at once" and  "the only one at a time" to yield the exact same results - but if that is how it works, well, go ahead. Nobody is talking about multiple items in that build volume, slicing fails with one item once the brim is enlarged. It is entirely non-obvious that this is due to a multi-part setting when no multi-part setup is even active.

Maybe a suitable hint can be added in the "unable to slice" notification, though.

**Comment by GregValiant** [comment] 2024-11-14 23:58
This is a reason I start every new project by re-selecting my custom profile and discarding all changes.  It's way to easy to forget that I've enabled Remove all Holes or moved the Zseam or turned on Z-hops for a specific model, etc.  The Print Sequence setting is just another example.  You can slice a single tall model in One-at-a-Time because the gantry height is ignored for a single model.  If it was not, then it would be a visible clue (on those machines with low gantry heights) that One at a Time is enabled.
But there is also "Bridge Settings" and "Support" which aren't required for every model and yet them might be turned on.
