### ISSUE TITLE
Elapsed time in preview view

### ISSUE THREAD

**Issue by MarcinOrlowski** [Ultimaker/Cura#8851] opened 2020-11-28 18:06 UTC
It'd be extremely useful if preview view could also show us elapsed time from beginning of the print. Sometimes you print a model that you know can be tricky and you would like to pay closer attention at the moment given area is being printed. Knowing, even roughly, how long would it take to get there by printer would be extremely handy.

**Comment by Ghostkeeper** [comment] 2020-12-01 13:00
Duplicate of https://github.com/Ultimaker/Cura/issues/7683.

**Closed by Ghostkeeper** 2020-12-01 13:00 UTC
Labels: Type: New Feature
