### ISSUE TITLE
Support generated even though he overhang angle is set higher than 45 degrees

### ISSUE THREAD

**Issue by bergie5737** [Ultimaker/Cura#4740] opened 2018-11-06 12:06 UTC
**Application Version**

Cura 3.5.1
**Platform**

Windows 10
**Printer**

Wanhoa I3 clone
**Steps to Reproduce**

Turn on support to touch everywhere. 
**Actual Results**

Support for this model are generated regardless of overhang angle.
**Expected results**

Support should be generated only near the top layers
**Additional Information**

I am attaching a box I want to print. The lip for the box lid, has an angle of 45 degrees all round on the inside. Above where the lid will slide in, the is a 90 degree lip (upper lip) that should be supported. I turned on "support everywhere" with an angle of 70 degrees so that only the upper 90 degree lip should be supported. This angle has no effect and supports are generated under the 45 degree lip as well. One side of the box does not have the 90 degree lip, and no overhangs are printed on that 45 degree lower lip. 
I edited the file in Fusion 360 to make the lower lip much wider than the upper, and removed the fillet in the corner below the lip, but still the supports are generated. The "support blocker" also has no effect unless the blocker goes through upper lip as well. I did print this type of box in an older version of Cura, but does not have the file anymore. I am not sure if I broke the original design in Fusion 360, or if this Cura causing an error.

[Box.zip](https://github.com/Ultimaker/Cura/files/2553074/Box.zip)

**Comment by nallath** [comment] 2018-11-06 12:45
I think this is a duplicate of https://github.com/Ultimaker/Cura/issues/4583

**Closed** 2018-11-06 12:45 UTC
Labels: Status: Duplicate
