### ISSUE TITLE
Cura 3.5 Preset profile issue (Ender 3)

### ISSUE THREAD

**Issue by Cura3-5BUGS** [Ultimaker/Cura#4471] opened 2018-10-03 20:09 UTC
**Application Version**
 Cura 3.5

**Platform**
 All Operating Systems.

**Printer**
The Cura Provided Ender 3 Profile

**Steps to Reproduce**

The Stock Ender 3 Profile is full of configuration errors that did not seem to be there previously.
 ISSUE #1 Filament diameter is set to 2.85, It SHOULD be 1.75. 
#2 0.1 Resolution is mistakenly replace with a second 0.15 layer height resolution.
**Actual Results**

With the current profile is will under extrude significantly causing print failures.
**Expected results**

A Ender 3 / Cura user may expect the preset profile to function quite well, when it doesn't work at all it may lead to frustration. 

**Additional Information**

![capture1](https://user-images.githubusercontent.com/43827988/46436301-5d61e880-c70d-11e8-99ee-0e6b1e2d6434.JPG)

**Comment by ChrisTerBeke** [comment] 2018-10-03 20:32
Duplicate of https://github.com/Ultimaker/Cura/issues/4468, which was opened just a few hours ago...

**Closed by ChrisTerBeke** 2018-10-03 20:32 UTC
