### ISSUE TITLE
Unexpected error when ironing thin models with concentric pattern

### ISSUE THREAD

**Issue by Cryztalzone** [Ultimaker/Cura#14065] opened 2022-12-16 22:52 UTC
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Anycubic Kobra Max

### Reproduction steps

1. Load a very big but flat .stl file (200x200x2mm)
2. Upscale all dimensions by 200%
3. Downscale vertical axis back down to 100% (4mm -> 2mm)
4. Enable Ironing with concentric pattern

### Actual results

Slicing fails with an unexpected error

### Expected results

Gcode for sliced model should be available

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[AKMAX_cascade.zip](https://github.com/Ultimaker/Cura/files/10249863/AKMAX_cascade.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/10249868/cura.log)

If the model thickness isn't scaled back down (4mm instead of 2mm) everything works fine
It also works with Zig Zag pattern at 2mm

**Comment by GregValiant** [comment] 2022-12-17 20:06
Thanks for the report and the files.
Try rotating the model 90° CCW.  I got it to slice that way.  Sometimes moving it around on the build plate can fool the bug.

This is a duplicate of several (many) other reports about this behavior.  Hopefully it will be fixed in 5.3.
I'll mark this as a duplicate and close it as the Cura team has a lot of these reports to work with to fix the bug.

For the Cura team - from the OP's log file:  "Backend exited abnormally with return code 3221225477!"

**Closed by GregValiant** 2022-12-17 20:06 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error💥

**Comment by MariMakes** [comment] 2023-02-23 14:20
Hey @Cryztalzone,

Thanks for your report 👍

Return code 3221225477, is actually a super generic error, even though it doesn't sound generic 😅 
In the Cura 5.3 Beta, we made a fix that should solve a number of these errors. 
Can you download the Beta and retry your slice? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0-beta.1

If that's it still doesn't work, please let us know 🙏
