### ISSUE TITLE
Initialization crash on multi monitor setup

### ISSUE THREAD

**Issue by Tomaschewski** [Ultimaker/Cura#3165] opened 2018-01-23 14:33 UTC
When I start up Cura 3.1, it crashes if the last window position was not on the main monitor (e.g. when "window_left" in the cura.cfg is set to a higher value than the main monitors width). As soon as I change the window_left value to zero, everything works fine again.

**Comment by fieldOfView** [comment] 2018-01-23 14:38
Do you have multiple GPUs, or a single GPU with multiple displays?

**Comment by Tomaschewski** [comment] 2018-01-23 14:46
It's a multi GPU setup, using the graphics chip on the CPU and a dedicated graphics card. :)

**Comment by fieldOfView** [comment] 2018-01-23 15:24
I can't help you there, because I don't have such a setup :-/

**Comment by ianpaschal** [comment] 2018-03-05 12:35
Since the author didn't use the issue template to provide relevant information, and I don't think any of us in Cura team can trouble shoot this (wrong set-up), I'm closing this.

**Closed by ianpaschal** 2018-03-05 12:35 UTC
Labels: Status: Needs Info

**Comment by ianpaschal** [comment] 2018-03-05 12:36
Possible duplicate of #3170

**Comment by PhotoJoeCA** [comment] 2024-02-24 19:16
February 2024 Checking in using 5.4.0 and this is still an issue -- Multi-monitor system - Program hangs on launch.
