### ISSUE TITLE
Cutting mesh modifier changes wall settings for unknown reasons

### ISSUE THREAD

**Issue by BloodyRain2k** [Ultimaker/Cura#10424] opened 2021-09-09 17:01 UTC
### Application Version

4.11

### Platform

Win 7 x64

### Printer

CR-6

### Reproduction steps

I was trying to only turn off the ironing setting for a certain height of the model, so I added a support blocker to have a mesh for override modifiers.

But when I changed it from "Infill Only" to "Cutting" I immediately got the weird result below.

### Actual results

![image](https://user-images.githubusercontent.com/1014362/132729832-aadbb103-f296-4601-bf59-2cd225dd92ac.png)

### Expected results

Walls without gaps.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[SlideCutter.zip](https://github.com/Ultimaker/Cura/files/7138435/SlideCutter.zip)

**Comment by BloodyRain2k** [comment] 2021-09-09 17:17
I've just checked this back in 4.9.1 and there the problem also exists, and it looks like the walls inside the overlapping mesh get printed thinner, for whatever reason...

**Comment by fvrmr** [comment] 2021-09-10 13:20
Hi @BloodyRain2k thank you for your report.
This is expected behaviour with a cutting mesh. You can change the wall thickness for the cutting mesh but than you still have walls on the other model. I would see this as a feature request then, I will bring it up with the team. Keep you posted!

**Comment by BloodyRain2k** [comment] 2021-09-10 20:11
I fail to see this as expected behaviour when I have NOT chosen to change the wallthickness...
Worse: even IF I choose to do so, the values that create the walls outside the mesh create a different result inside the cutting mesh...

**Comment by Ghostkeeper** [comment] 2021-09-14 09:16
This is indeed not expected behaviour. I think they misunderstood what your actual issue was.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9083.

As a workaround you can disable the Enable Bridge Settings setting for this print.

**Closed** 2021-09-14 09:16 UTC
Labels: Type: New Feature
