### ISSUE TITLE
Cura 5.2.2 crashes

### ISSUE THREAD

**Issue by Vyrgolia** [Ultimaker/Cura#14563] opened 2023-02-15 10:37 UTC
### Application Version

5.2.2

### Platform

windows 10

### Printer

Voxelab Aquila S2

### Reproduction steps

Cura repeatedly crashes when I try to slice a more complex stl model. 

### Actual results

The application crashes.

### Expected results

The model should be sliced. 

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10741898/cura.log)

**Comment by GregValiant** [comment] 2023-02-17 03:22
Thanks for the report.
This is a duplicate of many other reports.  This line is in your Cura.log.
Backend exited abnormally with return code 3221225477!
That has come up a lot.  Someone from the Cura team will take a look.

**Comment by MariMakes** [comment] 2023-02-23 14:17
Hey @Vyrgolia,

Thanks for your report 👍

Return code 3221225477, is actually a super generic error, even though it doesn't sound generic 😅 
In the Cura 5.3 Beta, we made a fix that should solve a number of these errors. 
Can you download the Beta and retry your slice? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0-beta.1

If that's it still doesn't work, we'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Closed** 2023-03-10 01:12 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage, Slicing Error :collision:
