### ISSUE TITLE
two printhead print cant save

### ISSUE THREAD

**Issue by rupsimrd** [Ultimaker/Cura#10161] opened 2021-07-21 07:10 UTC
### Application Version

4.9.1

### Platform

Windows 10

### Printer

custom

### Reproduction steps

1. imported models, selected which head prints what, merged models
2. sliced model without problems
3. tried to save to computer, got this error
![image](https://user-images.githubusercontent.com/87750161/126445861-77d40941-a244-4cb4-be10-63cb682ce550.png)
4. tried to save project, got the same error
5. tried to save to sd card, got empty 0B gcode file

### Actual results

error 
0

### Expected results

saved gcode

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log.1.zip](https://github.com/Ultimaker/Cura/files/6853473/cura.log.1.zip)

**Comment by nallath** [comment] 2021-07-21 07:13
The only error that I see in the log is about one of the wall line width settings being zero.

**Comment by rupsimrd** [comment] 2021-07-21 07:25
> width

all line widths are set correctly for both toolheads

**Comment by nallath** [comment] 2021-07-21 09:58
Okay, could you share a project that reproduces this?

**Comment by fvrmr** [comment] 2021-07-21 10:04
Seems like this is a duplicate of https://github.com/Ultimaker/Cura/issues/10157 and is probably related to the Linear Advance Setting plugin. Could you try to disable the plugin and see if that resolves your issue. 
I will close this issue, but please continue the thread in the other issue.

**Closed by fvrmr** 2021-07-21 10:04 UTC
Labels: Type: Bug

**Comment by rupsimrd** [comment] 2021-07-21 10:15
yup that was it thanks!
