### ISSUE TITLE
Closing Outer Shell Gaps

### ISSUE THREAD

**Issue by CCPlusIT** [Ultimaker/Cura#14995] opened 2023-03-22 09:22 UTC
### Application Version

5.3.0

### Platform

Windows 10

### Printer

CR6 SE

### Reproduction steps

After upgrading to new version from previous version and slicing a file previously used in older versions of Cura the gap between to faces has been removed and no longer prints the gap but makes it all one

![image1](https://user-images.githubusercontent.com/5461857/226855079-564609b5-047a-43cf-850b-6fa541ff5eb8.png)

![image2](https://user-images.githubusercontent.com/5461857/226854889-59f3c432-392a-41ac-afe5-5588e40e11ae.png)

Attached is the STL to try...

[Example-File.zip](https://github.com/Ultimaker/Cura/files/11038310/Example-File.zip)

It appears that something has changed since your previous release or some setting. Help would be appreciated.

### Actual results

![image1](https://user-images.githubusercontent.com/5461857/226855079-564609b5-047a-43cf-850b-6fa541ff5eb8.png)

### Expected results

![image2](https://user-images.githubusercontent.com/5461857/226854889-59f3c432-392a-41ac-afe5-5588e40e11ae.png)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I have attached a zip with the stl I have been using with previous versions with no issue.

**Comment by CCPlusIT** [comment] 2023-03-23 13:57
This seems to be just on the Creality printer profiles

**Comment by MariMakes** [comment] 2023-04-03 14:45
Hey @CCPlusIT,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I have the solution for you. 
You have to check the Print Thin Walls setting, it's not enabled by default. 
![image](https://user-images.githubusercontent.com/40423138/229544637-9f0e8b05-2bdf-4832-a6fa-6c60deec0e40.png)

I know it's not intuitive, but it works for thin gaps as well.  😅 

To me, it doesn't seem like a bug in Ultimaker Cura, since we have a solution in place. 
Apologies for any inconvenience caused by our delayed response. 
I'll be closing this issue. I hope you understand.

**Closed by MariMakes** 2023-04-03 14:45 UTC
Labels: Type: Bug, Status: Triage
