### ISSUE TITLE
show more details in the preview tab

### ISSUE THREAD

**Issue by moham96** [Ultimaker/Cura#10587] opened 2021-10-08 11:34 UTC
### Is your feature request related to a problem?

When doing calibration tests for temperature, retraction speed, retraction distance,speed...etc, either using an stl and the "ChangeAtZ" script or using a plugin like [Calibration-shapes](https://github.com/5axes/Calibration-Shapes), a user may need to verify his changes to the variables using the gcode preview, unfortunately going through the model layer by layer doesn't show if these variables where changed at all.

### Describe the solution you'd like

it would be nice if we have a widget in the cura gcode preview that shows some settings at the exact layer that is selected:
some variables that it may show:
- temperature
- retraction speed,distance
- flowrate
- speed
- fan speed

### Describe alternatives you've considered

I realize that some of these variables speed and flow can be visualized by the color scheme, still it would be nice to have numerical representation of these variables 

### Affected users and/or printers

it will affect anyone how is trying to calibrate and tune their printer

**Comment by fvrmr** [comment] 2021-10-12 14:25
Hi @moham96 thank you for your feature request.
We have had request for Arachne, where you could see the line width in a tooltip. https://github.com/Ultimaker/Cura/discussions/9388#discussioncomment-1233975
There was also mentioned this could be used for fan speed etc. 

Let me know if this is something that could work.

**Comment by Ghostkeeper** [comment] 2021-10-15 09:43
Thanks for the clarification! This is a duplicate of https://github.com/Ultimaker/Cura/issues/5744 then.

However I don't agree with showing speed, which is already a colour scheme in layer view and may be widely different across the layer. I also think Fan Speed would be more visual as a colour scheme (which is a different open feature request). Retraction Speed and Retraction Distance don't vary so those are just a repetition of the setting list, really.

It would be good to add your ideas of what to show to the existing ticket.

**Closed as completed by Ghostkeeper** 2021-10-15 09:44 UTC
Labels: Status: Duplicate, Type: New Feature
