### ISSUE TITLE
Weird Layer infill 

### ISSUE THREAD

**Issue by mydavydiv** [Ultimaker/Cura#11060] opened 2021-12-12 20:04 UTC
### Application Version

4.12.1

### Platform

windows 10

### Printer

ender 3 pro

### Reproduction steps

tried to print original cura file "retraction tower" but i realized that it does the same problem with personal files as well 
![444](https://user-images.githubusercontent.com/78267742/145727648-65ec46b6-84ba-42d6-9a39-7d033edff74f.jpg)

### Actual results

![333](https://user-images.githubusercontent.com/78267742/145727652-4cf48cb4-2754-4792-86e8-2dde94b30b78.JPG)

### Expected results

![111](https://user-images.githubusercontent.com/78267742/145727659-c4047936-6391-4fa5-a7e6-5480c83fe5ed.JPG)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

youtube video link 

https://youtu.be/v1VLsamQt5g

**Comment by fvrmr** [comment] 2021-12-13 09:30
Hi @mydavydiv thank you for your report. 
I am not able to reproduce your issue. Could you share a project file (file - save project)?

**Comment by Ghostkeeper** [comment] 2021-12-23 15:20
This looks like a duplicate of https://github.com/Ultimaker/Cura/issues/4576. A project file would clarify that, because the Top Surface Skin Layers setting can't be seen in the video (though other Top Surface Skin settings are visible, so it is probably >0).

**Closed** 2021-12-27 09:48 UTC
Labels: Type: Bug, Status: Needs Info
