### ISSUE TITLE
Cannot Sign In in Cura 5.0 on linux App image

### ISSUE THREAD

**Issue by frankyriventek** [Ultimaker/Cura#12300] opened 2022-05-21 22:02 UTC
### Application Version

5.0

### Platform

Linux App Image

### Printer

Snapmaker 

### Reproduction steps

When I click on the Sign In button on the menu, the Sign In dialog appears but when I click it nothing happens and I cannot sign in. 

### Actual results

No laucnh of web browser to sign in.

### Expected results

When clicking the Sign in button in the dialog, then the browser is launched to log in and get the OAuth token

.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8748412/cura.log)

**Comment by Vandresc** [comment] 2022-05-31 11:28
Duplicate of https://github.com/Ultimaker/Cura/issues/12291.

**Closed by Vandresc** 2022-05-31 11:28 UTC
Labels: Type: Bug
