### ISSUE TITLE
Elegoo Neptune 3 Pro Nozzle & Material Profiles corrupt or gone after update

### ISSUE THREAD

**Issue by austinKesler** [Ultimaker/Cura#16087] opened 2023-07-09 22:13 UTC
### Cura Version

5.4.0

### Operating System

MacOS Ventura

### Printer

Elegoo Neptune 3 Pro

### Reproduction steps

1. Updated to Cura 5.4 from 5.3.1
2. Tried to set up a print.

### Actual results

3. Nozzle and Material profiles/configurations are being reported as corrupt or nonexistent. UI states there are no profiles (when there formerly were profiles) for the nozzle and materials.

### Expected results

4. Prints that were formerly running as expected are no longer produced with the expected quality.

### Add your .zip and screenshots here ⬇️

<img width="1284" alt="Screenshot 2023-07-09 at 6 10 26 PM" src="https://github.com/Ultimaker/Cura/assets/38263596/8fbc34de-316e-43dc-9487-6301000cd886">

**Comment by MariMakes** [comment] 2023-07-26 12:39
Hey @austinKesler,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/16007
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/16007

**Closed** 2023-07-26 12:40 UTC
Labels: Type: Bug, Status: Duplicate
