### ISSUE TITLE
Slicing fails when object positioned a certain way

### ISSUE THREAD

**Issue by reederda** [Ultimaker/Cura#15681] opened 2023-06-06 04:21 UTC
### Cura Version

5.3.0

### Operating System

Windows 10

### Printer

Rostock Max V3.2

### Describe model location

Model is placed flat on buildplate. It seems to work if the model is rotated 90 degrees.

### Describe your model

The bottom half of a raspberry pi display case. 

### Add your .zip here ⬇️

[SRMAXV32_casebottom.zip](https://github.com/Ultimaker/Cura/files/11659858/SRMAXV32_casebottom.zip)

**Comment by GregValiant** [comment] 2023-06-06 10:43
Thanks for the report.
This is a duplicate of numerous reports on this behavior.  The Cura team is aware of it and it should be fixed in 5.4.  (I hope).
I'll mark this as a duplicate and go ahead and close this as the bug has been reported many times.  I hope you understand.

**Closed by GregValiant** 2023-06-06 10:43 UTC
Labels: Type: Bug, Status: Under Investigation, Slicing Error :collision:
