### ISSUE TITLE
Cura_15.06.01 Crash at its startup

### ISSUE THREAD

**Issue by s-marashi** [Ultimaker/Cura#127] opened 2015-07-09 12:49 UTC
As I try to run it on Windows 7 32Bit it crash at its first time startup it shows splash window then master window and add printer window is shown but immediately after that it crash which I can't select my printer type and windows application crash pops up and my only selection is to close program.
As you mentioned in #125 I tried to run in admin mode and from command line  but everything goes in the same way.

**Comment by nallath** [comment] 2015-07-09 13:02
Then isn't this the same issue?

**Comment by s-marashi** [comment] 2015-07-09 13:06
No, as in #125 it crash when he wants to slice layers but in this one it crashes at application startup..

**Comment by nallath** [comment] 2015-07-09 13:10
Allright, could you post the log file?

**Comment by s-marashi** [comment] 2015-07-09 13:13
I expected it creates one when I run it as admin but it didn't so there is nothing to send.

**Comment by nallath** [comment] 2015-07-09 13:18
Could you run it in command prompt and copy paste what displays there?

**Comment by s-marashi** [comment] 2015-07-09 13:21
Again it didn't produce any thing.

**Comment by nallath** [comment] 2015-07-09 13:24
So you start the software and it does nothing? Not even when running it from console?

**Comment by s-marashi** [comment] 2015-07-09 13:25
Yes, It just shows splash , master and add printer window then crash.

**Comment by BagelOrb** [comment] 2015-07-09 13:26
Did you try running Cura as administrator?

**Comment by nallath** [comment] 2015-07-09 13:26
Could you check in user/appdata/local/cura? Should be a log file there.

**Comment by s-marashi** [comment] 2015-07-09 13:27
Yes, I run it as admin from both explorer and command prompt.

**Comment by s-marashi** [comment] 2015-07-09 13:29
Logs was there:
2015-07-09 17:58:42,361 - INFO - Loaded plugin FileLogger
2015-07-09 17:58:42,648 - INFO - Loaded plugin LocalFileStorage
2015-07-09 17:58:42,661 - INFO - Loaded plugin LayerView
2015-07-09 17:58:42,675 - INFO - Loaded plugin MeshView
2015-07-09 17:58:42,689 - INFO - Loaded plugin WireframeView
2015-07-09 17:58:42,697 - INFO - Loaded plugin OBJReader
2015-07-09 17:58:42,702 - INFO - Loaded plugin STLReader
2015-07-09 17:58:42,711 - INFO - Loaded plugin STLWriter
2015-07-09 17:58:42,717 - INFO - Loaded plugin GCodeWriter
2015-07-09 17:58:42,730 - INFO - Loaded plugin CameraTool
2015-07-09 17:58:42,743 - INFO - Loaded plugin MirrorTool
2015-07-09 17:58:42,784 - INFO - Loaded plugin RotateTool
2015-07-09 17:58:42,799 - INFO - Loaded plugin ScaleTool
2015-07-09 17:58:42,811 - INFO - Loaded plugin SelectionTool
2015-07-09 17:58:42,825 - INFO - Loaded plugin TranslateTool
2015-07-09 17:58:42,844 - INFO - Checking for new version of cura
2015-07-09 17:58:42,845 - INFO - Loaded plugin UpdateChecker
2015-07-09 17:58:42,872 - INFO - Loaded plugin USBPrinting
2015-07-09 17:58:42,877 - INFO - Loaded plugin CuraEngineBackend
2015-07-09 17:58:43,783 - INFO - Could not establish connection on COM3: 'Failed to enter programming mode'. Device is not arduino based.
2015-07-09 17:58:44,228 - DEBUG - Loaded theme D:/Cura_15.06.01/resources/themes/cura
2015-07-09 17:58:44,664 - INFO - Started engine process: D:\Cura_15.06.01\CuraEngine.exe

**Comment by s-marashi** [comment] 2015-07-09 13:44
Now, do you have any idea how should I launch it or it is a bug?

**Comment by nallath** [comment] 2015-07-09 13:46
I don't see anything that could give an indication as to why it crashes.

**Comment by s-marashi** [comment] 2015-07-09 13:50
Does it open serial ports just on startup?
As it said "Could not establish connection on COM3"
Or it just have problem with arduino IDE?
Excuse me but I really want to run it.

**Comment by nallath** [comment] 2015-07-09 13:56
That's the USBPrinting plugin that tries to open all USB devices to check if they are 3D printers. It can't open it, so its probably not a printer.
I might have one idea why it doesn't work; Could you post your driver / video card info?

**Comment by s-marashi** [comment] 2015-07-09 14:00
But nothing is not connected to USB ports.
Where should I search for video card info?

**Comment by s-marashi** [comment] 2015-07-09 14:03
I think it should be:"Mobile Intel(R) 4 Series Express Chipset Family"

**Comment by awhiemstra** [comment] 2015-07-09 14:23
This sounds like a duplicate of #96

**Comment by s-marashi** [comment] 2015-07-09 14:30
I think so, now do I should close this issue and follow #96?

**Comment by nallath** [comment] 2015-07-09 14:45
Yes

**Closed by nallath** 2015-07-09 14:45 UTC
