### ISSUE TITLE
[3.2.1] Sub-menus do not highlight correctly

### ISSUE THREAD

**Issue by yeowjoon99** [Ultimaker/Cura#3720] opened 2018-04-25 15:55 UTC
**Application Version**
3.2.1 onwards

**Platform**
Windows 10

**Qt**

**PyQt**

**Display Driver**
Nvidia Geforce 940mx

**Printer**
Not relevant to glitch

**Steps to Reproduce**
1) Click on any main setting e.g. File, Edit, View, Settings, Extensions, Material list on panel at the right
2) Move mouse over sub setting with arrow
3) Sub setting turns blue and opens up a sub sub setting on the right of the arrow
4) Move mouse over sub sub setting
5) Sub sub setting doesn't turn blue and instead mouse appears to select whatever is behind the sub sub setting

**Actual Results**

![image](https://user-images.githubusercontent.com/38730785/39257212-9270b798-48e3-11e8-9e24-74bb138d67eb.png)
As seen in the above picture the sub setting turns blue but with the mouse hovering over the sub sub setting, the monitor button is the one that appears to be hovered over. Also when i click with the mouse over the sub sub setting, which in this case was 'Modify G-Code' (although it applies to all sub sub settings), the one that appeared to be hovered over, in this case 'Monitor', was the one that's clicked. 

**Expected results**
The sub sub setting should be the one turning blue and being hovered over

**Additional Information**
Also worth mentioning that if i use arrow keys from the moment i click on the main setting, in this case 'Extensions', and start using my arrow keys to select the setting, it works perfectly fine

**Comment by Ghostkeeper** [comment] 2018-05-11 11:48
This is a duplicate of https://github.com/Ultimaker/Cura/issues/3358.

**Closed by Ghostkeeper** 2018-05-11 11:48 UTC
Labels: Category: Uranium, Platform: Windows, Type: Bug
