### ISSUE TITLE
Cura 5 beta crashes during USB print on Ender 3 Pro

### ISSUE THREAD

**Issue by snillor200** [Ultimaker/Cura#11944] opened 2022-04-24 17:40 UTC
### Application Version

5.0.0-beta+1

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

I use the slicer to generate g-code for my Ender 3 Pro 3D printer.
When I export the file to an SD card, it runs fine.
If I choose to print to the Ender 3 Pro using the USB connection, it crashes.
When the software crashes I get a USB error, sometimes it can be seen appearing repeatedly (possibly dozens of times) until Cura 5 beta crashes and closes on its own.
This has happened 5 times and usually happens within the first 3 layers of the print.

### Actual results

I recover by stopping the print on the Ender 3 Pro using the button on the display panel.
This aborts the print and I can clean the print bed.
Afterward I can re-try or print from a file on the SD card.

The G-Code generated can be opened by my Cura 4.13 software and I can print via USB using the sliced G-Code from Cura 5 beta with no issues.

### Expected results

I expected to print via USB connection without crashing.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I'll get a screenshot of the USB crashing error and upload it on a subsequent bug report.
I did not get a screenshot previously.

**Comment by fvrmr** [comment] 2022-04-25 16:26
Hi @snillor200 thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11896 so I will close this issue.

**Closed by fvrmr** 2022-04-25 16:26 UTC
Labels: Type: Bug
