### ISSUE TITLE
Spliced Brim Count not matching Settings Brim Count after Part Merge

### ISSUE THREAD

**Issue by Mule-Kick** [Ultimaker/Cura#16055] opened 2023-07-07 16:42 UTC
### Cura Version

5.3.1

### Operating System

Window 10

### Printer

Ultimaker S5 firmware 8.1.2

### Reproduction steps

1. Load all files
2. Change text and outline to extruder 2 leaving internal part on extruder 1. Using Normal Print settings no adjustments.
    Extruder 1 White Tough PLA AA0.4 nozzle
    Extruder 2 Black Tough PLA AA0.4 nozzle
3. Select all and merge
4. Slice at current settings (brim setting count:18; spliced brim count: 2)
5. Enable Prime Tower (brim setting count:18; spliced brim count: 18)
![image](https://github.com/Ultimaker/Cura/assets/138901710/7e223eef-5836-4ff4-9269-c2697098d8f1)
![image](https://github.com/Ultimaker/Cura/assets/138901710/3c5c8812-4ab7-48b8-9fd4-70e07483ba9f)
![image](https://github.com/Ultimaker/Cura/assets/138901710/55d27350-11c7-4b38-93c6-361a75390a53)

### Actual results

Spliced brim count is only 2 after multiple part merger.

### Expected results

Spliced brim count matching settings brim count

### Add your .zip and screenshots here ⬇️

[10 Foot Green.zip](https://github.com/Ultimaker/Cura/files/11984149/10.Foot.Green.zip)
![image](https://github.com/Ultimaker/Cura/assets/138901710/4ac4f3aa-5b4d-4eaf-8985-1b1d62aecc88)
![image](https://github.com/Ultimaker/Cura/assets/138901710/f691112e-4003-4c15-acd5-832322ee537d)
![image](https://github.com/Ultimaker/Cura/assets/138901710/a44528de-0614-4cce-8e14-0472959d1d6d)

**Comment by MariMakes** [comment] 2023-07-26 12:35
Hey @Mule-Kick,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I recognize your issue. I've encountered it aswell. 
It seems to be related to the Buildplate Adhesion Extruder not being defined by default, a change we introduced in Cura 5.3.
![image](https://github.com/Ultimaker/Cura/assets/40423138/e7679e81-c544-470b-9f8a-12fa4cc0a88f)
![image](https://github.com/Ultimaker/Cura/assets/40423138/0d395c58-0336-4b23-bcff-fadf482e1538)

This issue is very similar https://github.com/Ultimaker/Cura/issues/16151
This should resolved in the upcoming 5.5 stable release. 

To me, it doesn't seem like a bug in Ultimaker Cura, since we have a solution in place. 
Apologies for any inconvenience caused by our delayed response. 
I'll be closing this issue. I hope you understand.

**Closed by MariMakes** 2023-07-26 12:35 UTC
Labels: Type: Bug, Status: Triage
