### ISSUE TITLE
(5.3.0) Weird mouse/tablet behavior in viewport and settings

### ISSUE THREAD

**Issue by krekr** [Ultimaker/Cura#15268] opened 2023-04-17 12:39 UTC
### Application Version

5.3.0

### Platform

macos 12.6.3 (21G419)

### Printer

UMO

### Reproduction steps

While navigating Cura, I cannot reliably use my Wacom Bamboo tablet which I use as a mouse-input for my pc. Almost all times, left-clicks are completely not registered. Right-mouse and hold (to rotate the 3D view) 'sticks': I cannot get the rotation to stop by releasing the button, even after multiple clicks. Only restarting the software works.
The MBP trackpad works as expected, but also can't 'release' the sticky rotation. Also, there is no other software where I have this issue (except for Creality slicer which is a cura fork). The behavior started from v4 onwards iirc

I suspect other people might have this problem when using non-apple/native input methods (e.g. remote desktop).
Since this might be tied to the wacom driver, I'm using this: https://github.com/thenickdude/wacom-driver-fix
I'll try at my work laptop which uses a current wacom and see if I can reproduce.

### Actual results

Input not registered

### Expected results

Input registered same as using a normal mouse or trackpad

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/11250180/cura.log)

**Comment by MariMakes** [comment] 2023-05-05 13:13
Hey @krekr,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12554
We have a ticket on our backlog with the intent to improve this behavior and we even have a developer with a wacom who can reproduce the behavior. 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12554
Thanks for the report, they really help us with troubleshooting. 😊

**Closed by MariMakes** 2023-05-05 13:13 UTC
Labels: Type: Bug, Status: Triage
