### ISSUE TITLE
Cannot centre camera view for an Ultimaker 2 model in Cura 2.6.2

### ISSUE THREAD

**Issue by dtims1** [Ultimaker/Cura#2081] opened 2017-07-07 08:40 UTC
The option to "Center camera  when item is selected", is unavailable in Preferences >General settings.
How do I restore this function? 
[Cura 2.6.2 Camera View Issue.docx](https://github.com/Ultimaker/Cura/files/1130451/Cura.2.6.2.Camera.View.Issue.docx)

**Comment by nallath** [comment] 2017-07-07 09:17
Duplicate of #1811, #1772 & #1566

**Closed by nallath** 2017-07-07 09:17 UTC
