### ISSUE TITLE
Publish the newest version of cura to winget package manager

### ISSUE THREAD

**Issue by rbarbrow** [Ultimaker/Cura#10610] opened 2021-10-13 01:58 UTC
### Is your feature request related to a problem?

when doing a "winget install ultimaker.cura" it still downloads version 4.9.1

### Describe the solution you'd like

it should install the current version 4.11.x

### Describe alternatives you've considered

not sure. maybe add it to your build workflow

### Affected users and/or printers

any windows users that use winget package manager

**Comment by fvrmr** [comment] 2021-10-14 08:48
Hi @rbarbrow thank you for your request.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/8439
I will close this issue as a duplicate.

**Closed by fvrmr** 2021-10-14 08:48 UTC
Labels: Type: New Feature
