### ISSUE TITLE
[master] Crashes on material creation

### ISSUE THREAD

**Issue by G-Pereira** [Ultimaker/Cura#3905] opened 2018-06-06 23:14 UTC
https://pastebin.com/EKFADEyk

Seems to be a issue with Qt.
I start on a fresh install I follow the initial setup to configure a new printer and then the material list is empty and crashed when I try to create one

**Comment by Appesteijn** [comment] 2018-06-07 08:28
Are you running from source? What OS?

**Comment by LipuFei** [comment] 2018-06-07 10:58
Hi @G-Pereira , looks like you are using Qt 5.12? We haven't tries anything above Qt 5.10.1 yet. The latest Qt + PyQt combination we know that works is Qt 5.10.1 + PyQt 5.10.

**Comment by Perlovka** [comment] 2018-06-12 11:55
Seems like this is not Qt problem.
When fdm_materials are not installed/found, cura will fail upon creating material with the following error:
```
2018-06-12 14:48:45,401 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2018-06-12 14:48:45,402 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
2018-06-12 14:48:45,402 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/lib64/python3.5/site-packages/cura/Machines/MaterialManager.py", line 528, in createMaterial
2018-06-12 14:48:45,402 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self.duplicateMaterial(material_group.root_material_node,
2018-06-12 14:48:45,402 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: AttributeError: 'NoneType' object has no attribute 'root_material_node'
```

Looks like it tries to duplicate nonexistent material and crashes (obviously). There should be some check before this.

**Comment by clytle374** [comment] 2018-06-22 16:53
I have had the same problem from source for a month.  Never got the materials to show up either.  From source on Gentoo linux.  Will try and help if someone has questions. 

Cory

**Comment by Perlovka** [comment] 2018-06-24 08:42
@clytle374 cura-3.3.1 been merged into gentoo tree some time ago, including materials

**Comment by clytle374** [comment] 2018-06-24 22:18
About a week after I finally got it built from source. lol, figures. Not sure why the materials don't show up, but I'll post another thread if I don't figure it out.

**Comment by Ghostkeeper** [comment] 2018-08-07 14:58
You may need to clone this repository into the `resources` directory and rename it to `materials`: https://github.com/Ultimaker/fdm_materials.git

Or better yet, clone it somewhere else and symlink it to the `resources` directory.
That should get the materials to show up again.

**Comment by nallath** [comment] 2019-04-04 18:33
Just tried to reproduce this and it no longer happens.

**Closed by nallath** 2019-04-04 18:33 UTC
Labels: Category: Cura, Status: Needs Info
