### ISSUE TITLE
Slice error

### ISSUE THREAD

**Issue by toennee** [Ultimaker/Cura#14365] opened 2023-01-23 16:36 UTC
### Application Version

5.2.1

### Platform

windows 11

### Printer

ender 3

### Reproduction steps

Have tried to change veriables but nothing helps.

### Actual results

I have tried to change variables but nothing helps. Nothing helps.

### Expected results

Just that it would slice so it can be printed.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Nothing else to add.

**Comment by MariMakes** [comment] 2023-02-03 12:38
Hey @toennee,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 
Is it possible that your printjob is located at 0, 0, 0, and it slices if you move it a little away from the center of the buildplate? 
Then it might be a duplicate of https://github.com/Ultimaker/Cura/issues/13643

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Closed** 2023-02-18 00:18 UTC
Labels: Type: Bug, Status: Duplicate, Status: Needs Info, Status: Triage
