### ISSUE TITLE
File Save Dialog on Ubuntu 22.04

### ISSUE THREAD

**Issue by bieber** [Ultimaker/Cura#12438] opened 2022-06-04 00:23 UTC
### Application Version

5.0.0

### Platform

Ubuntu 22.04

### Printer

Voron

### Reproduction steps

Running the latest 5.0.0 AppImage on Ubuntu (with the LD_PRELOAD fix from issue #12359) and I've noticed that the save file dialog after slicing is behaving oddly.  To reproduce, just slice a model and hit the "Save to Disk" button

### Actual results

First, instead of the file selector dialog popping up and taking focus, I just get a system notification that it's ready. 

![Screenshot from 2022-06-03 20-21-49](https://user-images.githubusercontent.com/191601/171969015-04e87cfd-f66f-4d5f-8788-beafb41c9368.png)
 
Clicking the notification takes me to the file dialog, which is now missing the prefilled suggested file name

![Screenshot from 2022-06-03 20-21-06](https://user-images.githubusercontent.com/191601/171968999-700ff6cb-93e4-4b28-b8fc-4e967e331879.png)

### Expected results

The file select dialog should pop up and take focus on its own, and it should prepopulate with a suggested file name

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Nothing pops up in the terminal when opening the save dialog, but here's my command line in case there's anything helpful there

```
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 /home/bieber/bin/Ultimaker-Cura-5.0.0-linux.AppImage
PyInstaller/loader/pyimod03_importers.py:495: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
Cyclic dependency detected between "file:///tmp/.mount_UltimaTNDJry/share/cura/resources/qml/Actions.qml" and "file:///tmp/.mount_UltimaTNDJry/share/cura/resources/qml/Actions.qml"
```

**Comment by bieber** [comment] 2022-06-04 01:13
I've also just realized that if I overwrite an existing file, I have to confirm it twice--one confirmation from the system file select dialog, and then a second confirmation dialog from Cura

**Comment by AonoZan** [comment] 2022-06-09 15:57
I dont even get notification, pressing button does nothing. I'm on Xubuntu so I probably don't have that type of notification popup, I have notification in top-bar but that gives nothing. Previous version of Cura 4.12 had every filedialog working, you could open files and save them no issue.

**Comment by nallath** [comment] 2022-06-10 11:38
Duplicate of #12266

**Closed by nallath** 2022-06-10 11:38 UTC
Labels: Type: Bug, Status: Triage
