### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by raul7321** [Ultimaker/Cura#13585] opened 2022-10-17 22:48 UTC
### Application Version

5.1.1.

### Platform

Windows 10

### Printer

Prusa i3

### Reproduction steps

Press "Slice" button

### Actual results

An unexpected error

### Expected results

The result of slice process

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[PI3_Dual.zip](https://github.com/Ultimaker/Cura/files/9804993/PI3_Dual.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/9805000/cura.log)

**Comment by MariMakes** [comment] 2022-10-18 10:56
Hey @raul7321,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report. I can reproduce your issue in Cura 5.2.

I'll have someone from the Cura team take a look at the crash. 

I noticed that if you select a different layerheight, you can slice the model.
I hope that helps you to get unstuck.
![image](https://user-images.githubusercontent.com/40423138/196411171-b8310ef8-2299-477f-be86-cddc5ebc9d2b.png)

**Comment by jellespijker** [comment] 2024-01-14 13:33
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.
I'm closing this issue as fixed for the 5.7.0 release

![image](https://github.com/Ultimaker/Cura/assets/8535734/a9dbef88-c3f6-4863-a593-0ac4c3fa3ce0)

**Closed by jellespijker** 2024-01-14 13:33 UTC
Labels: Type: Bug, Status: Under Investigation, Slicing Error :collision:
