### ISSUE TITLE
Wacom tablet not working with cura

### ISSUE THREAD

**Issue by wchairy** [Ultimaker/Cura#13707] opened 2022-11-02 00:59 UTC
### Application Version

5.2.1

### Platform

mac

### Printer

Ultamaker 3

### Reproduction steps

Installed new version of cura. I haven't been using it for a few months because of moving. I'm disabled, and I use a Wacom tablet as a pointing device. It completely does not work at all with cura, 

### Actual results

I can't click on anything. I can't drag anything. Other than moving the cursor around on the screen, which I believe is just a function of the operating system it won't interact with the tool at all. So frustrating. What are they thinking?

### Expected results

Expected it would work with a common pointing device. It has for years why is it stop now

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

One of the most comprehensive additive printers out there, and I feel like I am being taken for a ride

**Comment by MariMakes** [comment] 2022-11-02 10:23
hey @wchairy,

Welcome to the Ultimaker Cura Github 🚀 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12554
We are working on a way to reproduce the issue on our side so we can start resolving it. 
It's clear to us that it's impacting quite a number of users, but we can't work on it if we can't check the fix that we propose. 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12554

**Closed by MariMakes** 2022-11-02 10:23 UTC
Labels: Type: Bug, Status: Triage
