### ISSUE TITLE
Slicer crashes when slicing Bed Leveling Test

### ISSUE THREAD

**Issue by lessan12** [Ultimaker/Cura#10613] opened 2021-10-13 17:38 UTC
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Ender 6

### Reproduction steps

-Open Project (attached)
     - Original STL (Also attached) was scaled 150%x, 180%y
- Try to Slice
[Bed Leveling Crash Issue.zip](https://github.com/Ultimaker/Cura/files/7340250/Bed.Leveling.Crash.Issue.zip)

### Actual results

Slicer Crashes, no slicing perform
![Cura Slicer Crash -- Cura Window](https://user-images.githubusercontent.com/92465631/137184442-bb0850a6-0060-4c23-9ca5-41019b8f6a5c.png)
![Cura Slicer Crash](https://user-images.githubusercontent.com/92465631/137184443-79ad9867-4d87-42bc-8bb9-be905918f617.png)
[cura.log](https://github.com/Ultimaker/Cura/files/7340272/cura.log)
ed

### Expected results

Slicing would have occurred so I can print it

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Files are attached above.

**Comment by fvrmr** [comment] 2021-10-14 08:34
Hi @lessan12 thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/10394 and is probably happening because your model is lower than the initial layer height. I couldn't reproduce it myself with your 3mf because your printer settings were missing.

I will close this issue because it is a duplicate.

**Closed by fvrmr** 2021-10-14 08:34 UTC
Labels: Type: Bug
