### ISSUE TITLE
3MF about multi-material

### ISSUE THREAD

**Issue by SWAssassin** [Ultimaker/Cura#3592] opened 2018-03-29 11:16 UTC
Hello，
I am making a multi-material 3D printer that uses Stereo lithography Appearance. I want to know if 3MF includes more than one material information. The CURA shows only one material.  Can I get a multi-material slice through CURA for secondary development?
THANK YOU !

**Comment by alekseisasin** [comment] 2018-03-29 14:10
Hi @SWAssassin , Answering to your question, Cura shows only one material. In Cura after loading we do not read any object properties from the meshe. After loading Cura applies Extruder settings which comes together with Cura. 
If you have proposal or solution for this feature you can create a Pull Request where you describe its functionality. Together with other people we might come to nice solution and this feature will be added to Cura.

**Comment by ChrisTerBeke** [comment] 2018-03-29 14:13
Duplicate of https://github.com/Ultimaker/Cura/issues/2539.

**Closed by ChrisTerBeke** 2018-03-29 14:13 UTC
Labels: Status: Needs Info
