### ISSUE TITLE
Model merge and layout issues in 4.8.0

### ISSUE THREAD

**Issue by hexxxx** [Ultimaker/Cura#8765] opened 2020-11-14 01:14 UTC
**Application version**
4.8.0

**Platform**
Win 10 Enterprise

**Printer**
UM S5

**Reproduction steps**
1. Import two STLs 
2. Assign one STL to Extruder 2
3. Select both models 
4. Right click -> Merge Models

**Screenshot(s)**
<img width="923" alt="before" src="https://user-images.githubusercontent.com/12835780/99133706-049df300-25e9-11eb-8e2e-97a14c5fe973.png">
<img width="966" alt="after" src="https://user-images.githubusercontent.com/12835780/99133710-0667b680-25e9-11eb-83d4-db1f853f1745.png">
![2NargAJhRc](https://user-images.githubusercontent.com/12835780/99133895-c6550380-25e9-11eb-87e2-32afea7ea6bd.gif)

**Actual results**
Position of merged model is way, way off. It's off the build platform, rotating the model spins the merged parts around in a circle with a radius seemingly larger than the build volume, and no amount of manual adjustment can make Cura recognize the print as being within bounds. 

**Expected results**
Models merge appropriately, experience no exaggeration of required print volume, and are printable.

**Project file**
[bug report project file.zip](https://github.com/Ultimaker/Cura/files/5539935/bug.report.project.file.zip)

**Log file**
[log excerpt.txt](https://github.com/Ultimaker/Cura/files/5539964/bug.log.excerpt.txt)

**Additional information**
I tested with 4.7.1 and had no issues with merge. This was happening to some extent in the previous version of Cura, but this is much more dramatic.

**Comment by nallath** [comment] 2020-11-16 09:44
Could you also share the STL files to reproduce this (This is the only case where we actually need the STL's instead of the project ;))

**Comment by Ghostkeeper** [comment] 2020-11-17 21:55
I could reproduce this issue by exporting the models from that project file to STL and then loading those back in. Here are STLs that reproduce the problem: [positioning_bug.zip](https://github.com/Ultimaker/Cura/files/5556416/positioning_bug.zip)

**Comment by hexxxx** [comment] 2020-11-17 22:05
Original STLs [here](https://www.dropbox.com/s/lno34g6ol1wdf9m/positioning_bug_original_stls.zip?dl=0)! Sorry for the delay.

**Comment by Vandrasc** [comment] 2020-11-23 16:35
Devs see CURA-7873 for our own internal reference.

**Comment by hexxxx** [comment] 2020-11-26 23:23
Worth noting that I'm having the same issues with different STLs of similar type and complexity, while attempting the same merge operations.

**Comment by Ghostkeeper** [comment] 2021-05-21 12:01
This happened when a model is transformed (scaled or rotated) before merging. The reason it started happening more in Cura 4.8 is because the new arrange algorithm automatically rotated models when loading them in. The bug will be fixed in #9884, set for merger in 4.10. As a workaround, you can reset all transformations before merging.

**Closed** 2021-06-08 10:37 UTC
Labels: Category: Cura, Type: Bug
