### ISSUE TITLE
Cura reboots arduino board

### ISSUE THREAD

**Issue by SignallerK** [Ultimaker/Cura#5709] opened 2019-05-07 14:24 UTC
I use stand alone printer which means I download my files to sd card and then put it to printer. But Cura can automatically connect to 3d printer via com port which is awesome, however there is an issue.
I have another device (just a regular arduino-nano on com5) with arduino bootloader connected to my PC and each time I open Cura, it tries to "find printer" and reboots my device. 
Unfortunately, I don't see any option to turn off automatic connect or com-port selection in program. So, this behavior seems a bug.
**Application Version**
Cura 3.6.0

**Platform**
Windows 7.0

**Expected results**
1. It is possible to turn off automatic connect function.
2. It is possible to select com-port manually.

**Comment by Ghostkeeper** [comment] 2019-05-08 07:24
Duplicate of #5207, #5202, #4039, #1478 and #70.

**Closed by Ghostkeeper** 2019-05-08 07:24 UTC
