### ISSUE TITLE
[4.2.1] Pause at height resuming at the wrong height

### ISSUE THREAD

**Issue by lokster** [Ultimaker/Cura#6372] opened 2019-09-18 08:11 UTC
**Application version**
4.2.1

**Platform**
Does not matter

**Printer**
Custom FFF Printer

**Reproduction steps**
Use the "Pause at height" post processing script to add pause at some height. Wait for the actual pause to happen, and then resume the print.

**Actual results**
The printing resumes at the wrong height

**Additional information**
Here's what I've found. For example, if we set it to pause at layer 3 (actually the 4th layer, because layers in the gcode start from layer0), the pause at height gcode is inserted AFTER we have moved the Z axis to layer 3 Z location (Z=0.8mm). Then the script adds it's own Z movements, which move the Z axis 1mm up to Z=1.8mm (and then goes to Z=15mm if we are pausing below Z=15mm).
When we resume the print, the hotend moves back to the Z location, which is 1mm higher than the actual layer (e.g. to Z=1.8mm), and starts printing in the air.
Example gcode with my comments:
```
;MESH:NONMESH
G0 F600 X102.519 Y116.662 Z0.8 ; <<< this moves us to "Layer 3" Z location.
G0 F12000 X103 Y117
;TIME_ELAPSED:75.890732
;TYPE:CUSTOM
;added code by post processing
;script: PauseAtHeight.py
;current layer: 3
M83
G1 F1500 E-3
G1 F300 Z1.8 ; <<< Z axis moves 1mm higher than the current layer
G1 F9000 X190 Y190
G1 F300 Z15 ; <<< Z axis moves to 15mm absolute height
M104 S215; standby temperature
M0;Do the actual pause
M109 S215; resume temperature
G1 F1500 E3
G1 F1500 E-3
G1 F300 Z1.8 ; <<< Z axis moves back to 1mm higher than the current layer
G1 F9000 X117 Y117
G1 F1500 E3
G1 F9000
M82
G92 E75.67543
;LAYER:3
;TYPE:WALL-INNER
;MESH:test.STL
G1 F3300 X117 Y117 E76.14107 ; <<< the printing resumes, but the Z height is WRONG

```
In comparison, in Cura 3.6 we do a G0 move to the layer start X/Y/Z coordinates after the ";MESH:test.STL" line, which moves us to the correct Z location.

**Comment by Ghostkeeper** [comment] 2019-09-18 09:51
Duplicate of https://github.com/Ultimaker/Cura/issues/5924. It should be fixed in 4.3 (try the beta!)

**Closed by Ghostkeeper** 2019-09-18 09:51 UTC
Labels: Type: Bug
