### ISSUE TITLE
Missing grid on build plate

### ISSUE THREAD

**Issue by batzkass** [Ultimaker/Cura#2682] opened 2017-10-25 20:26 UTC
I tried Cura 3.0.3 AppImage on Ubuntu 16.04 and 17.10, I got the same bug.
The newly featured grid on the build-plate is missing, living a full white plate.
Here is an illustration :

![virtualbox_ubuntu 17](https://user-images.githubusercontent.com/1590208/32021250-232ea5e2-b9d3-11e7-98e4-ce8e41488927.png)

And a full terminal output :

Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
QObject::connect: Parentheses expected, signal MainWindow::
QObject::connect: Parentheses expected, signal MainWindow::
QObject::connect: Parentheses expected, signal MainWindow::
QObject::connect: Parentheses expected, signal MainWindow::
file:///tmp/.mount_fsW7A7/usr/bin/resources/themes/cura-light/styles.qml:197:17: QML Item: Binding loop detected for property "width"
qml: TableViewSelection: index out of range
qml: TableViewSelection: index out of range
file:///tmp/.mount_fsW7A7/usr/bin/plugins/plugins/UM3NetworkPrinting/DiscoverUM3Action.qml:282: TypeError: Cannot read property 'clusterSize' of null
QOpenGLShader::compile(Fragment): 0:20(28): error: could not implicitly convert operands to arithmetic operator
0:20(28): error: operands to arithmetic operators must be numeric
0:20(22): error: no matching function for call to `fract(error)'; candidates are:
0:20(22): error:    float fract(float)
0:20(22): error:    vec2 fract(vec2)
0:20(22): error:    vec3 fract(vec3)
0:20(22): error:    vec4 fract(vec4)
0:20(22): error: operands to arithmetic operators must be numeric
0:20(18): error: no matching function for call to `abs(error)'; candidates are:
0:20(18): error:    float abs(float)
0:20(18): error:    vec2 abs(vec2)
0:20(18): error:    vec3 abs(vec3)
0:20(18): error:    vec4 abs(vec4)
0:20(18): error:    int abs(int)
0:20(18): error:    ivec2 abs(ivec2)
0:20(18): error:    ivec3 abs(ivec3)
0:20(18): error:    ivec4 abs(ivec4)
0:20(62): error: could not implicitly convert operands to arithmetic operator
0:20(55): error: no matching function for call to `fwidth(error)'; candidates are:
0:20(55): error:    float fwidth(float)
0:20(55): error:    vec2 fwidth(vec2)
0:20(55): error:    vec3 fwidth(vec3)
0:20(55): error:    vec4 fwidth(vec4)
0:20(18): error: operands to arithmetic operators must be numeric
0:21(23): warning: `majorGrid' used uninitialized
0:21(36): warning: `majorGrid' used uninitialized
0:23(1): error: `frag_color' undeclared
0:23(1): error: value of type vec4 cannot be assigned to variable of type error

*** Problematic Fragment shader source code ***
#define lowp
#define mediump
#define highp
#line 1

uniform lowp vec4 u_plateColor;
uniform lowp vec4 u_gridColor0;
uniform lowp vec4 u_gridColor1;

varying lowp vec2 v_uvs;

void main()
{
vec2 coord = v_uvs.xy;

// Compute anti-aliased world-space minor grid lines
vec2 minorGrid = abs(fract(coord - 0.5) - 0.5) / fwidth(coord);
float minorLine = min(minorGrid.x, minorGrid.y);

vec4 minorGridColor = mix(u_plateColor, u_gridColor1, 1.0 - min(minorLine, 1.0));

// Compute anti-aliased world-space major grid lines
vec2 majorGrid = abs(fract(coord / 10 - 0.5) - 0.5) / fwidth(coord / 10);
float majorLine = min(majorGrid.x, majorGrid.y);

frag_color = mix(minorGridColor, u_gridColor0, 1.0 - min(majorLine, 1.0));
}
***

**Comment by fieldOfView** [comment] 2017-10-25 20:34
Duplicate of #2630

**Closed** 2017-10-26 08:39 UTC
