### ISSUE TITLE
Material selection of extr2 gets in extr1

### ISSUE THREAD

**Issue by ZeroScars** [Ultimaker/Cura#2220] opened 2017-08-07 06:32 UTC
2.6.2
Choose Settings -> Extruder 2 -> Material -> [and select a material]

You'll see that this material for extruder 2 is loaded into extruder 1

**Comment by fieldOfView** [comment] 2017-08-07 07:26
Duplicate of https://github.com/Ultimaker/Cura/issues/1641
As a workaround, use the sidebar instead of the menus.

**Closed** 2017-08-08 08:49 UTC
Labels: duplicate
