### ISSUE TITLE
Parameters text fields have changed to 'from right to left'

### ISSUE THREAD

**Issue by YukaiP** [Ultimaker/Cura#9759] opened 2021-05-03 15:44 UTC
### Application Version

4.9.0

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

No steps needed

### Actual results

I encountered this issue first in this version - all of the parameters have been switched to stick the integers to the right side, instead of the left.
My default system language is English, however my locale is Israel, so that might have something to do with the problem.

![image](https://user-images.githubusercontent.com/54648556/116898364-f5663c80-ac3e-11eb-9c08-69343b78962b.png)

### Expected results

Numbers should be on the left of course.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Any needed docs will be happily attached. Didn't see a reason to attach any.

**Comment by fvrmr** [comment] 2021-05-04 07:29
Hi @YukaiP thank you for your bug report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9667 that's why I will close this issue.

**Closed by fvrmr** 2021-05-04 07:29 UTC
Labels: Type: Bug
