### ISSUE TITLE
Cura 2.4 OS X - Custom materials not loading after restart

### ISSUE THREAD

**Issue by Maxx84** [Ultimaker/Cura#1508] opened 2017-03-08 01:28 UTC
Custom materials are not loaded after I close and reopen Cura.

The custom material is created in the following way:
Material -> Manage materials...
Click e.g. on PLA -> Duplicate
Click on the new PLA item -> Edit -> Change some properties and name it PLA-edit
Activate PLA-edit

Now, if I close and restart Cura, the selected material is still PLA-edit (and its properties are still loaded), but the material does not appear anymore from the drop-down menu or from the list of materials.

Cura Version: 2.4.0
OS X Version: 10.11.6

[cura.log.zip](https://github.com/Ultimaker/Cura/files/826348/cura.log.zip)

**Comment by Ghostkeeper** [comment] 2017-03-08 10:44
This is a duplicate of #1104, #1404, #1410, #1452 and #1471.

**Closed by Ghostkeeper** 2017-03-08 10:44 UTC
