### ISSUE TITLE
[3.1] S{material_print_temperature_layer_0} gives incorrect data

### ISSUE THREAD

**Issue by MaxRink** [Ultimaker/Cura#2971] opened 2017-12-13 05:48 UTC
As you are able to see here https://i.imgur.com/fE8xK22.jpg the variable for the first layer temp gives an incorrect result. THe Temp for the first layer is set to 230°C, but the value in the GCODE is 210. This V alue is entered nowhere, neither in the specific filament settings nor elsewhere for this print

**Comment by ChrisTerBeke** [comment] 2017-12-13 08:34
Duplicate of https://github.com/Ultimaker/Cura/issues/1296.

**Closed by ChrisTerBeke** 2017-12-13 08:34 UTC

**Comment by fieldOfView** [comment] 2017-12-13 10:28
Yeah, no, not really a duplicate. It may be the same underlying issue, but Cura 3.1 broke all start gcode using {material_print_temperature*} for single extrusion printers.

As a workaround, a user can remove the lines with {material_print_temperature*} and CuraEngine will insert its own heatup sequence before the start gcode, but that is not an option for people who need to eg turn on their PSU before heating up.

**Comment by ChrisTerBeke** [comment] 2017-12-13 16:44
It's the same underlying issue, it's now just more visible as single extrusion machines also have an extruder stack. It's definitely back on the urgent to fix list as well. To keep all discussion about the issue in one place, I marked this as duplicate.

**Comment by alexwhittemore** [comment] 2018-01-30 22:11
Well, at least I'm not crazy.
