### ISSUE TITLE
table view can be flicked which makes no sense for a desktop GUI

### ISSUE THREAD

**Issue by coreyoconnor** [Ultimaker/Cura#15984] opened 2023-07-03 02:25 UTC
### Application Version

5.3.1

### Operating System

all

### Printer

doesn't matter

### Reproduction steps

1. open "configure settings visibility"
2. scroll

### Actual results

Scrolls like a dumb drunk

### Expected results

Actually scrolling and stopping when I stop scrolling.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no

**Comment by MariMakes** [comment] 2023-07-26 20:38
Hey @coreyoconnor,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12110
We have a ticket on our backlog with the intent to improve this behavior.
We already tried a couple of fixes, but it's tricky because scrolling is both different on different operating systems and on different mouses/trackpads and a fix needs to work on all of them. 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12110

**Closed by MariMakes** 2023-07-26 20:38 UTC
Labels: Type: Bug, Status: Triage
