### ISSUE TITLE
Cura crashes at the same point consistently with USB print from computer

### ISSUE THREAD

**Issue by MLocke13** [Ultimaker/Cura#11942] opened 2022-04-24 17:08 UTC
### Application Version

5.0

### Platform

Windows 11

### Printer

Ender 3 Max with CR Touch

### Reproduction steps

Started print like normal WITH USB and crashes about 15 minutes in and can replicate consistently. 
Replicated 4 times 

### Actual results

Cura closes, and flashes crash report but it auto closes

### Expected results

Not crash haha

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8550135/cura.log)

**Comment by fvrmr** [comment] 2022-04-25 16:29
Hi @MLocke13 thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11896, so I will close this issue.

**Closed by fvrmr** 2022-04-25 16:29 UTC
Labels: Type: Bug
