### ISSUE TITLE
Cura 5.0 Beta App Crash on Windows

### ISSUE THREAD

**Issue by tspezia** [Ultimaker/Cura#12051] opened 2022-05-02 00:23 UTC
### Application Version

5.0 Beta

### Platform

Nvida Super 2080; windows 10

### Printer

Ender 3 Pro

### Reproduction steps

Printing got through 9 layers,  App crashed, printer left actively heating but stalled  (5 hours)
[Cura5Beta.zip](https://github.com/Ultimaker/Cura/files/8599950/Cura5Beta.zip)
Windows event viewer

See attached Log
2022-05-01 12:02:55,113 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2022-05-01 12:02:55,113 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: TypeError: unable to convert a Python 'float' object to a C++ 'int' instance
2022-05-01 12:02:55,131 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2022-05-01 12:02:55,131 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: TypeError: unable to convert a Python 'float' object to a C++ 'int' instance
[cura.log](https://github.com/Ultimaker/Cura/files/8599997/cura.log)
[Cura5Beta.zip](https://github.com/Ultimaker/Cura/files/8600020/Cura5Beta.zip)

### Actual results

Went back to Cura 4.13 and will un install 5.0 beta

### Expected results

previously tested print

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

2022-05-01 12:02:55,113 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2022-05-01 12:02:55,113 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: TypeError: unable to convert a Python 'float' object to a C++ 'int' instance
2022-05-01 12:02:55,131 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2022-05-01 12:02:55,131 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: TypeError: unable to convert a Python 'float' object to a C++ 'int' instance
[CE3PRO_Avocado_Bucket_MKII.zip](https://github.com/Ultimaker/Cura/files/8600016/CE3PRO_Avocado_Bucket_MKII.zip)

**Comment by fvrmr** [comment] 2022-05-02 09:07
Hi @tspezia thank you for your report. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11896, so I will close this issue.

**Closed by fvrmr** 2022-05-02 09:07 UTC
Labels: Type: Bug
