### ISSUE TITLE
Crash on macOS Big Sur DP1

### ISSUE THREAD

**Issue by gothickitty93** [Ultimaker/Cura#8036] opened 2020-07-06 19:23 UTC
(I know that macOS 11 Big Sur is still beta, so if this is an invalid bug right now, please close it)

**Application version**
4.6.1

**Platform**
2018 Mac Mini running macOS 11 Big Sur DP1

**Printer**
MP Select Mini v2

**Reproduction steps**
1. Download Cura from website
2. Attempt to launch

**Actual results**
Application does not launch. Appears and then disappears in dock.

**Expected results**
Application should launch.

**Log file**
No log file was created

Please let me know what commands and such you need me to run to help diagnose the issue.

**Comment by mahtDFR** [comment] 2020-07-07 07:25
Duplicate of #7970
Thanks for reporting

**Closed by mahtDFR** 2020-07-07 07:25 UTC
Labels: Type: Bug
