### ISSUE TITLE
Cura crashing when I tried to slice in Mirror Mode

### ISSUE THREAD

**Issue by Woodchuckcan** [Ultimaker/Cura#13573] opened 2022-10-17 09:04 UTC
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Sovol SV04

### Reproduction steps

Just loaded this ( https://www.thingiverse.com/thing:27053 ) and selected mirror mode. Chose my normal settings. Clicked slice and keep getting the same error, "Slicing Failed with an unexpected error".
Tried shrinkning the print, which did not work.

Tried to slice in copy mode which works.

### Actual results

Error in mirror mode

### Expected results

It should work.?

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9798709/cura.log)
[stderr.log](https://github.com/Ultimaker/Cura/files/9798712/stderr.log)
[stdout.log](https://github.com/Ultimaker/Cura/files/9798713/stdout.log)

**Comment by GregValiant** [comment] 2022-10-17 12:03
Thanks for the report.
I can't duplicate the problem and it sliced fine for me when mirrored.
There is a bug in the Windows version of Cura 5.1 that can keep some models from slicing.  A possible workaround is to move the model on the build plate and/or rotate the model.  Try those and see if they work for you.
This is likely a duplicate of many reports about the behavior (which appears to have been fixed in 5.2beta).  I'll leave this open so you can respond.  Let us know if the workaround did the trick and allowed it to slice.

**Closed** 2022-10-31 12:07 UTC
Labels: Type: Bug, Status: Duplicate, Status: Needs Info, Status: Under Investigation, Slicing Error💥
