### ISSUE TITLE
open stl file generated with Solidworks 2016 unit mm

### ISSUE THREAD

**Issue by claude1000** [Ultimaker/Cura#2681] opened 2017-10-25 18:34 UTC
- Exporting the stl file from Solidworks 2016 unit in **mm** 
- Importing into Cura the file is in **Meter !** 

thanks

![support](https://user-images.githubusercontent.com/33101288/32016035-23d54ad8-b9c3-11e7-8f20-3a86acf116aa.jpg)

**Comment by ChrisTerBeke** [comment] 2017-10-25 19:58
Are you using the Solidworks plugin? If not, in Solidworks you probably have an option to set the units when exporting? Cura looks at the units described in the STL file, so if they're incorrect this is the result. If you do use it please let us know so we can check the plugin functionality.

**Comment by claude1000** [comment] 2017-10-25 20:36
I tried with / whitout
With the same issue

Le mer. 25 oct. 2017 à 21:58, ChrisTerBeke <notifications@github.com> a
écrit :

**Comment by ChrisTerBeke** [comment] 2017-10-26 08:41
Can you upload the STL file here so we can check the STL contents? I think the Solidworks side of the plugin uses the same exporter for STL as the normal export to STL functionality, and as Cura probably doesn't have a bug with importing STLs (the most used feature in the software) I think it's somewhere in that exporter.

**Comment by fieldOfView** [comment] 2017-10-26 08:55
> Cura looks at the units described in the STL file, so if they're incorrect this is the result.

Cura does not look at the units described in the STL file, because there is no unit described in the STL file. Cura always assumes the units are in mm when opening an STL. If SolidWorks exports in another unit, it has no way of specifying that in the STL file unfortunately.

**Comment by ChrisTerBeke** [comment] 2017-10-26 08:57
A, got confused with 3MF a bit there. Indeed STL is just vector and we assume it's sizes are in mm. This confirms my suspicion that the issue is actually in Solidworks.

**Comment by fieldOfView** [comment] 2017-10-26 08:58
Could the plugin use 3MF instead of STL to mitigate this problem?

**Comment by ChrisTerBeke** [comment] 2017-10-26 09:07
@Appesteijn something to take into account for the Solidworks plugin improvements in the future?

**Comment by claude1000** [comment] 2017-10-26 09:27
I think Solidworks export rtl files in meter ? Could you confirm ?
 I just open a ticket by SW

thanks

2017-10-26 10:41 GMT+02:00 ChrisTerBeke <notifications@github.com>:

**Comment by ChrisTerBeke** [comment] 2017-10-26 10:31
I'm not familiar with the Solidworks source code, so can't really confirm. We have a meeting with them planned though so we'll probably bring it up.

**Comment by claude1000** [comment] 2017-10-26 10:35
Have you load my attached file in Cura 3.0.3?


2017-10-26 12:31 GMT+02:00 ChrisTerBeke <notifications@github.com>:

**Comment by ChrisTerBeke** [comment] 2017-10-26 10:44
I don't see any attached files. That probably doesn't work when replying over email.

**Comment by claude1000** [comment] 2017-10-26 10:44
here the file

2017-10-26 12:44 GMT+02:00 ChrisTerBeke <notifications@github.com>:

**Comment by ChrisTerBeke** [comment] 2017-10-26 11:07
>  doesn't work when replying over email

To add a file, login to GitHub and add a comment with attachment from there please.

**Comment by ChrisTerBeke** [comment] 2017-10-26 11:11
Also, we're updating the Macro to export Solidworks files instead of STL files and the Cura plugin can already read them. This will fix the export dimensions when using the Macro export. The STL export dimension issue is something that Solidworks has to fix themselves.

**Comment by claude1000** [comment] 2017-10-26 11:18
let me in touch while the magro is ready

have a nice day
claude

2017-10-26 13:11 GMT+02:00 ChrisTerBeke <notifications@github.com>:

**Comment by claude1000** [comment] 2017-10-26 16:33
Hi
all the file attached SW , rtl , jpg



[bouton cuisine faiencerie.zip](https://github.com/Ultimaker/Cura/files/1419208/bouton.cuisine.faiencerie.zip)

**Comment by Appesteijn** [comment] 2017-10-26 16:41
The new version of the plugin will be available tomorrow. Please let us know if your problem is then solved!

**Comment by claude1000** [comment] 2017-10-26 16:41
sure

**Comment by Appesteijn** [comment] 2017-10-27 07:41
The new version is online.

**Comment by claude1000** [comment] 2017-10-27 11:01
nice
could you give me the link and plugin name


2017-10-27 9:41 GMT+02:00 Mark <notifications@github.com>:

**Comment by Appesteijn** [comment] 2017-10-27 11:04
You can find it in the plugin browser in Cura

**Comment by claude1000** [comment] 2017-10-27 11:08
i guess the name is Solidworks integration ?

2017-10-27 13:05 GMT+02:00 Mark <notifications@github.com>:

**Comment by Appesteijn** [comment] 2017-10-27 11:12
Yes

**Comment by ChrisTerBeke** [comment] 2017-10-31 12:28
Fixed in the solidworks integration. STL exporting has to be fixed in solidworks itself.

**Closed by ChrisTerBeke** 2017-10-31 12:28 UTC
