### ISSUE TITLE
When deleting a input box entry and entering a new one, Cura will not correctly record new box content.

### ISSUE THREAD

**Issue by aviphysics** [Ultimaker/Cura#261] opened 2015-08-16 16:09 UTC
After deleting or backspacing the contents of an input box, Cura will let you type in new characters and they will appear in the input box as typed; however, the slicer may leave out some or all of the new characters. Switching to and from another profile or reloading Cura will show what Cura actually recorded.

This was observed in the Windows 7 15.06.03 version.

**Comment by fieldOfView** [comment] 2015-08-18 12:41
Sounds like a duplicate of https://github.com/Ultimaker/Cura/issues/169, which may have recently gotten fixed (after the release of 15.06.03)

**Closed** 2015-09-15 09:53 UTC
Labels: bug
