### ISSUE TITLE
When using right to left regional format settings ( like Israel ) , number change side , units dont

### ISSUE THREAD

**Issue by itayguy** [Ultimaker/Cura#9947] opened 2021-06-08 07:32 UTC
### Application Version

4.9.0

### Platform

windows 10

### Printer

custom

### Reproduction steps

set in windows Regional Format to Israel

### Actual results

numbers change side to right , units stay right , number and units are one over each other 

### Expected results

units change side to the left

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/4155188/121142416-a070a400-c844-11eb-86dd-a3f7bdf94e66.png)
![image](https://user-images.githubusercontent.com/4155188/121142485-b2524700-c844-11eb-9785-34c2129209e7.png)

**Comment by nallath** [comment] 2021-06-08 08:48
Duplicate of https://github.com/Ultimaker/Cura/issues/9667

**Closed by nallath** 2021-06-08 08:48 UTC
Labels: Type: Bug
