### ISSUE TITLE
move part

### ISSUE THREAD

**Issue by Rick-TRIGGER** [Ultimaker/Cura#9140] opened 2021-01-17 18:18 UTC
**Application version**
(The version of the application this issue occurs with.)
CURA 4.8

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)
MAC Big sur

**Printer**
(Which printer was selected in Cura?)
Creality ender 3 et cr10s Pro V2

1. je ne peux pas selectionner la piece afin de la tourner.
2. je selectione la piece par le nom du fichier et quand je tente de bouger la piece avec les fleche ,la piece se deselectione

**Comment by fvrmr** [comment] 2021-01-18 10:43
Can you explain this in English please? 
Can you share your log file and maybe some screenshots of what is happening? 
You can find your log file here: `$USER/Library/Application Support/cura/<Cura version>/cura.log`

**Comment by Ghostkeeper** [comment] 2021-01-25 16:15
Duplicate of https://github.com/Ultimaker/Cura/issues/8745

**Closed by Ghostkeeper** 2021-01-25 16:15 UTC
Labels: Status: Needs Info, Type: Bug
