### ISSUE TITLE
Support Blocker/Modify Overlaps change not working with Fuzzy Skin

### ISSUE THREAD

**Issue by KenLucke** [Ultimaker/Cura#8853] opened 2020-11-29 01:53 UTC
**Application version**
4.8 (and earlier, tested back to 4.6.2)

**Platform**
Mac OSX 10.15.7

**Printer**
N/a

**Reproduction steps**

1. Load model
2. Select Fuzzy Skin
3. Use a support blocker/modify overlaps to turn OFF Fuzzy Skin in an area
4. Slice
5. Preview

[this has been confirmed both ways:  Main model Fuzzy Skin, Support Blocker/Modify  Overlaps Fuzzy off, and main model no Fuzzy, overlap with Fuzzy turned on..  In both cases the main model's settings are used for the entire model.

**Screenshot(s)**
![Smooth Bulb - Ultimaker Cura 2020-11-28 17-16-15](https://user-images.githubusercontent.com/57936294/100530035-03042b80-31a2-11eb-9685-141322aefcda.jpg)

**Actual results**
Entire model is still Fuzzy Skin

**Expected results**
Area within support blocker/modify overlaps should not be fuzzy.

**Project file**
https://www.dropbox.com/s/7a5qexyssu7la6x/Fuzzy%20Bulb.3mf

**Log file**

**Additional information**

**Comment by Ghostkeeper** [comment] 2020-12-01 13:14
That's because your mesh is set to only modify infill. It'd create non-fuzzy walls inside the infill if the infill mesh wouldn't be set to have 0 walls (and that area of the mesh is too thin to have infill anyway).

Setting the mesh to be a cutting mesh causes it to affect the rest of the print as well instead of just infill.
![image](https://user-images.githubusercontent.com/2448634/100745288-5a430f80-33df-11eb-9504-c1ed1280de0d.png)

This is expected behaviour, so we'll close the issue.

**Closed by Ghostkeeper** 2020-12-01 13:14 UTC
Labels: Type: Bug

**Comment by KenLucke** [comment] 2020-12-01 17:32
OK, thanks for that explanation.  :)

**Comment by mingyew1994** [comment] 2021-06-18 02:59
Hi i'm having the same issue, i did change the Overlap to cutting mesh but the slicing isn't coming out with the fuzzy skin.
not sure if anyone is able to help me with this.

https://drive.google.com/file/d/1GbrfzBP5RIs3-oiFvDe2Rdu8kuL8Aw95/view?usp=sharing
https://drive.google.com/file/d/1b0KO0MhCBfMLffQmCKx9OWkkGlimPOAk/view?usp=sharing

**Comment by Ghostkeeper** [comment] 2021-06-25 13:32
Both those Google Drive links are not public. They require a log-in. I can't access them.

Fuzzy Skin still works fine as a per-object setting with a cutting mesh, from what I can tell.
![image](https://user-images.githubusercontent.com/2448634/123432275-7e0fb200-d5ca-11eb-8230-8b2a254d95ee.png)

**Comment by mingyew1994** [comment] 2021-06-26 06:13
Hi Ghostkeeper

could you try these 2 links? sorry for the trouble
https://drive.google.com/file/d/1GbrfzBP5RIs3-oiFvDe2Rdu8kuL8Aw95/view?usp=sharing
https://drive.google.com/file/d/1b0KO0MhCBfMLffQmCKx9OWkkGlimPOAk/view?usp=sharing

**Comment by Ghostkeeper** [comment] 2021-07-05 09:49
> Hi Ghostkeeper
> 
> could you try these 2 links? sorry for the trouble
> https://drive.google.com/file/d/1GbrfzBP5RIs3-oiFvDe2Rdu8kuL8Aw95/view?usp=sharing
> https://drive.google.com/file/d/1b0KO0MhCBfMLffQmCKx9OWkkGlimPOAk/view?usp=sharing

Your problem is that the Print Sequence is set to One at a Time. In that case, the cutting mesh doesn't work at all. The bug about that is here: https://github.com/Ultimaker/Cura/issues/9219

As a workaround, try setting that to All at Once.

**Comment by mingyew1994** [comment] 2021-07-06 03:39
Thank you very much ! sorry i didn't realise that was the issue !
