### ISSUE TITLE
Tree Support in Cura 4.8.0 is buggy

### ISSUE THREAD

**Issue by BERT-LZ** [Ultimaker/Cura#8879] opened 2020-12-03 10:38 UTC
Tree Support in Cura 4.8.0 is buggy: Distance to the bevel is much too big, so it makes no sense at all:
 
![image](https://user-images.githubusercontent.com/64354748/100998203-81bee700-355b-11eb-9f56-57aa387628fa.png)

If you switch to normal instead of tree support, the set distance will fit:
 
![image](https://user-images.githubusercontent.com/64354748/100998266-926f5d00-355b-11eb-9a6b-9d8cd7b3f7e1.png)

With the same settings with Cura 4.5.0 it still worked correctly:
![image](https://user-images.githubusercontent.com/64354748/100998552-f5f98a80-355b-11eb-9721-d96a53fd2af0.png)

**Comment by BERT-LZ** [comment] 2020-12-03 10:41
[treesupport-testfile.zip](https://github.com/Ultimaker/Cura/files/5635482/treesupport-testfile.zip)

**Comment by BERT-LZ** [comment] 2020-12-03 11:19
This gap remains if Z and X/Y distance is set to 0 for test purposes. Why does this gap remain? There is a huge bug here, because it makes the tree support almost unusable!

![image](https://user-images.githubusercontent.com/64354748/101007189-a74eef00-3561-11eb-9313-f49ee3e14db6.png)

**Comment by Asterchades** [comment] 2020-12-03 14:03
Turn off the Support Interface - at least on the top. It's already well known that 4.7 and beyond trees and the interface don't work well together when it comes to horizontal (X/Y) proximity.

**Comment by Ghostkeeper** [comment] 2020-12-04 10:25
Duplicate of https://github.com/Ultimaker/Cura/issues/8622.

This didn't occur yet in 4.7 as far as we know. It's new to 4.8.

**Closed by Ghostkeeper** 2020-12-04 10:25 UTC
Labels: Type: Bug
