### ISSUE TITLE
Will

### ISSUE THREAD

**Issue by Salty-Doug** [Ultimaker/Cura#10763] opened 2021-11-08 02:19 UTC
### Application Version

4.11.0

### Platform

Mac OSx 11.6 Big Sur

### Printer

Monoprice Select i3 Plus (Wanhao i3 Plus)

### Reproduction steps

I have several one layer .stl files that I use for the first layer clearance. Version 4.11 will not generate a proper GCODE file from this one layer .stl file.

I drag the "Print-Z_Test 0.20 v2.stl" file into Cura 4.11 to create a GCODE file for my MPMP i3 Plus 3D printer. I use Octoprint to manage the printer so I drag the newly created GCODE file to Octoprint in my browser. I start the print from Octoprint and the square doesn't print.

If I drag the same "Print-Z_Test 0.20 v2.stl" file into Cura 4.10 to create a GCODE file for my MPMP i3 Plus 3D printer. I use Octoprint to manage the printer so I drag the newly created GCODE file to Octoprint in my browser. I start the print from Octoprint and the square prints.

[Print-Z_Archive.zip](https://github.com/Ultimaker/Cura/files/7493738/Print-Z_Archive.zip)
e
[cura.log.zip](https://github.com/Ultimaker/Cura/files/7493817/cura.log.zip)
[cura.cfg.zip](https://github.com/Ultimaker/Cura/files/7493819/cura.cfg.zip)
.

### Actual results

Other multi-layer .stl files are sliced correctly and print correctly.

I have compared the two GCODE files and the the 4.11 file is missing the layer 0 commands.

I have included a .ZIP file with the .stl file, a GCODE file from Cura 4.10 that works and a Cura 4.11 GCODE file that doesn't.

Thanks in advance.

### Expected results

Cura 4.11 should generate a proper GCODE file the will print the one layer part.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

I have included a .ZIP file with the .stl file, a GCODE file from Cura 4.10 that works and a Cura 4.11 GCODE file that doesn't.

I have also included the log file and the .cfg file.

**Comment by fvrmr** [comment] 2021-11-08 12:14
Hi @Salty-Doug thank you for your bug report. 
This is a duplicate of #10394 and is probably happening because your model is lower than the initial layer height. This is fixed in 4.12 Beta. You can download the beta here: https://github.com/Ultimaker/Cura/releases/tag/4.12-beta

I will close this issue because it is a duplicate.

**Closed by fvrmr** 2021-11-08 12:14 UTC
Labels: Type: Bug
