### ISSUE TITLE
Fruit Basket fails when "Connect Top/Bottom Polygons" enabled

### ISSUE THREAD

**Issue by Londo-Mollari** [Ultimaker/Cura#15977] opened 2023-07-02 12:16 UTC
### Cura Version

5.4.0-beta.1

### Operating System

MacOS Ventura 13.4

### Printer

Creality Ender-3 Pro

### Name abnormal settings

Top Surface Skin/Top/Bottom/Bottom Pattern Initial Layer all set to "concentric" "connect polygons" turned on

### Describe model location

Centered

### Describe your model

A fruit basket

### Add your .zip here ⬇️

[CE3PRO_cai ro Fruit Basket hoc co khi.3mf.zip](https://github.com/Ultimaker/Cura/files/11929470/CE3PRO_cai.ro.Fruit.Basket.hoc.co.khi.3mf.zip)

As soon as "connect top/bottom polygons" is deselected, the model will slice.  With it on, Cura throws an error after a few seconds of slicing.

**Comment by MariMakes** [comment] 2023-07-05 15:52
Hey @Londo-Mollari,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

I recognize this issue. 🔍  This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/15797, where Connect Top/Bottom Polygons would cause a slicing crash. 

It's resolved in the 5.4 stable release, you can download the Cura version with the fix here: https://github.com/Ultimaker/Cura/releases/tag/5.4.0
I'll close this issue since it's a duplicate and resolved. 

Feel free to create a ticket if you encounter more issues, together we can make Cura better 💪

**Closed by MariMakes** 2023-07-05 15:52 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:
