### ISSUE TITLE
Open Part Crash

### ISSUE THREAD

**Issue by mattnelson84** [Ultimaker/Cura#9844] opened 2021-05-16 06:21 UTC
### Application Version

4.9.1

### Platform

Windows 10

### Printer

Anycubic i3 Mega

### Reproduction steps

1. Open File
2. It closes Cura while open file dialog is open, or sometimes if fast enough you can open the file but then it will close cura seconds after. 

### Actual results

It closes cura when ever trying to open a file to put in. 

### Expected results

File should open and business as ussual.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I can drag and drop files inside without a problem, but it doesn't like the explorer window, or even once explorer is closed and its opening a file it will soon crash.

**Comment by fvrmr** [comment] 2021-05-17 08:33
Hi @mattnelson84 thank you for your bug report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9668
There you can find a work around to solve this.
Since this issue is a duplicate I will close this issue.

**Closed by fvrmr** 2021-05-17 08:33 UTC
Labels: Type: Bug
