### ISSUE TITLE
Max Min Coordinates as Export Variable

### ISSUE THREAD

**Issue by Julius971** [Ultimaker/Cura#10375] opened 2021-09-01 15:15 UTC
### Is your feature request related to a problem?

No there is no problem problem

### Describe the solution you'd like

Id like to receive the maximum and minimum coordinates of the print as a usable Variable for the start and end gcode. 
Usage would be awesome for mesh bedleveling, to limit the probing area to the area that is used by the print. 
Shouldn't be hard to implement, as similar informations are already given, like the model position (prepare) and size (preview).

### Describe alternatives you've considered

The alternative is to calculate the values by hand. :D Kind of annoying

### Affected users and/or printers

Everyone and everything

**Comment by fvrmr** [comment] 2021-09-02 14:16
Hi @Julius971 thank you for your feature request. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/7270 and this was deferred because it wouldn't have much value for Ultimaker printers. 
I will close this one as a duplicate. I hope you understand.

**Closed by fvrmr** 2021-09-02 14:16 UTC
Labels: Type: New Feature
