### ISSUE TITLE
Slicing part in surface mode with spiralize enabled doesn't spiralize correctly

### ISSUE THREAD

**Issue by PaulMurrin** [Ultimaker/Cura#1469] opened 2017-02-22 22:11 UTC
After printing each layer correctly spiralized, the z-screw rewinds 1 layer and then moves back up again (1 layer). This leaves a z-scar. This model is sliced with Cura 2.4.0.

The mesh can be found here: https://www.youmagine.com/designs/tube-11_11

**Comment by smartavionics** [comment] 2017-02-23 09:57
This is a known problem. As a short term fix set outer wall wipe distance to zero.

**Comment by Ghostkeeper** [comment] 2017-02-24 10:33
Duplicate of https://github.com/Ultimaker/Cura/issues/1396.

**Closed by Ghostkeeper** 2017-02-24 10:33 UTC
