### ISSUE TITLE
[4.0.0] pause at height plugin

### ISSUE THREAD

**Issue by uwezi** [Ultimaker/Cura#5539] opened 2019-03-30 19:55 UTC
**Application Version**
Cura 4.0.0

**Platform**
windows 10 64bit

**Printer**
Wanhao i3

**Steps to Reproduce**
try to place a "pause at height" at a certain layer number, repeating 1 layer

**Actual Results**
apart from the inconsistent layer numbering [0..n-1] in gcode and [1..n] in the UI the placement of the actual pause appears to be "random" but probably this is only caused by a wrong number of layer repetitions 

**Expected results**
when selecting a pause at layer #26 I would expect a pause before or after that layer number and then a repetition of the last layer printed after the pause

**Additional Information**
Actual gcode created shows that the pause is inserted **after layer #25** which correctly corresponds to layer 26 from the UI, but then after the pause not layer #25 is repeated but layer #24... 
When selecting to repeat 0 layers then correctly no layer is repeated.

`;TIME_ELAPSED:1739.161717
;LAYER:24
;MESH:.stl
G0 X105.812 Y57.838 Z5
;TYPE:FILL
G1 F3600 X106.357 Y58.394 E1900.5697
....
;TIME_ELAPSED:1901.450097
;LAYER:25
;MESH:.stl
G0 X105.697 Y57.926 Z5.2
;TYPE:FILL
G1 F3600 X106.189 Y58.394 E2061.14027
....
G0 X106.66 Y55.254
;TIME_ELAPSED:1956.845606
;TYPE:CUSTOM
;added code by post processing
;script: PauseAtHeight.py
;current layer: 26
M83
G1 F1500 E-15
G1 F300 Z6.2
G1 F9000 X190 Y190
G1 F300 Z15
M104 S200; standby temperature
M0;Do the actual pause
M109 S210; resume temperature
G1 F1500 E15
G1 F199.998 E3
G1 F1500 E-15
G1 F300 Z6.2
G1 F9000 X105.812 Y57.838
G1 F1500 E15
G1 F9000
M82
G92 E1900.5697
;LAYER:24
;MESH:.stl
G0 X105.812 Y57.838 Z5
;TYPE:FILL
G1 F3600 X106.357 Y58.394 E1900.5697
....
![20190330_cura4_pause](https://user-images.githubusercontent.com/8582807/55280941-f07e8280-532c-11e9-8eea-fb897a224713.jpg)
`

**Comment by Ghostkeeper** [comment] 2019-04-01 13:15
Duplicate of #5085.

**Closed by Ghostkeeper** 2019-04-01 13:15 UTC
