### ISSUE TITLE
Detect previous version

### ISSUE THREAD

**Issue by lin-ycv** [Ultimaker/Cura#13654] opened 2022-10-26 07:39 UTC
### Is your feature request related to a problem?

New version installs won't detect previously installed versions, sometimes a computer ends up with multiple versions installed.

### Describe the solution you'd like

have the installer detect previous versions and offer an option to uninstall the previous versions.

### Describe alternatives you've considered

or simply overwrite the previous version and don't add version number to the folder in program files?

### Affected users and/or printers

all users that updates cura

**Comment by MariMakes** [comment] 2022-11-01 14:06
Hey @lin-ycv,

Thanks for your report 👍

We've been getting a lot of requests about this. 
This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13446
We have a ticket on our backlog with the intent to improve this behavior.
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/13446

**Closed by MariMakes** 2022-11-01 14:06 UTC
Labels: Type: New Feature
