### ISSUE TITLE
Objects won't multiply

### ISSUE THREAD

**Issue by MonPaul** [Ultimaker/Cura#10728] opened 2021-11-03 02:59 UTC
### Application Version

4.11.0

### Platform

MacOSMonterey

### Printer

Ender5

### Reproduction steps

I right clicked object
I clicked on multiply

### Actual results

I get a block that opens up that says placing objects and multiplying and placing objects. But the meter never moves to show progress

### Expected results

The object should have multiplied.
<img width="810" alt="Screen Shot 2021-11-02 at 9 57 51 PM" src="https://user-images.githubusercontent.com/93631852/140004311-d19e5969-2fe2-46c4-8cf3-5697c4a036f1.png">
d!

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

If you need something else please let me know. I also deleted download and tried a new one and had the same problem.

**Comment by nallath** [comment] 2021-11-03 10:04
Duplicate of #10249

**Closed by nallath** 2021-11-03 10:04 UTC
Labels: Type: Bug
