### ISSUE TITLE
Cura 4.5 Added new material doesn't show on the material list

### ISSUE THREAD

**Issue by AESilva-IPFN** [Ultimaker/Cura#7326] opened 2020-03-22 04:21 UTC
**Application version**
Cura 4.5

**Platform**
Win10

**Printer**
Alfawise U20 One

**Reproduction steps**
1. Installed Copper3D PLActive material from Marketplace
2. Restarted Cura

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/31952829/77242152-49f15880-6bf3-11ea-8144-5e6921fb5c31.png)
![image](https://user-images.githubusercontent.com/31952829/77242185-96d52f00-6bf3-11ea-8c59-bbe53afc18de.png)

**Actual results**
The new material doesn't show on the material list and I can't use it (second image). But if I go to the marketplace manager it says it is installed (first image).

**Expected results**
I would expect to have the chance to choose the new material from the material list.

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by fieldOfView** [comment] 2020-03-23 07:20
The materials on the Marketplace are targeted at Ultimaker printers, which use 2.85mm material. Since your printer uses 1.75mm material, Cura filters out the display of the materials from the Marketplace since the 2.85 mm variant would not fit in your printer anyway.

**Comment by Ghostkeeper** [comment] 2020-03-23 08:47
Duplicate of https://github.com/Ultimaker/Cura/issues/6236.

We intend to add information in the Marketplace as to which printers these material profiles are compatible with. They are indeed not showing up since your extruder accepts only 1.75mm filaments.

**Closed by Ghostkeeper** 2020-03-23 08:47 UTC
Labels: Type: Bug

**Comment by AESilva-IPFN** [comment] 2020-03-23 18:35
Thank you for the information.
