### ISSUE TITLE
[3.3.1] Menu items not responding

### ISSUE THREAD

**Issue by alicemouse** [Ultimaker/Cura#3881] opened 2018-06-03 20:06 UTC
**Application Version**
Cura 3.3.1

**Platform**
windows 10

**Printer**
Custom FDM printer (Flyingbear p902)

**Steps to Reproduce**
In the extension tab, you can not select any plug-ins. When you hover the cursor, they do not respond and do not click.

**Actual Results**
Nothing

**Expected results**
The plugin should be selected and opened. Specifically, the model's auto-orientation

**Additional Information**
![image](https://user-images.githubusercontent.com/39886134/40890524-554751a4-6780-11e8-846a-6785ee64a515.png)

**Comment by ChrisTerBeke** [comment] 2018-06-03 20:48
Seems more like a UI issue than the plugins themselves not working (otherwise they would not appear in the menu). Do other menu items work properly for you?

**Comment by alicemouse** [comment] 2018-06-03 21:04
Now checked and yes, the entire interface of the top menu does not define additional sub-items.

**Comment by ChrisTerBeke** [comment] 2018-06-03 21:13
Could you try switching your Cura language to English and try again? (trying to exclude sources here, we've had some issues with Russian rendering before).

**Comment by alicemouse** [comment] 2018-06-03 21:42
I tried, but it did not work.

**Comment by alicemouse** [comment] 2018-06-03 21:43
Sometimes all work, but I haven't idea on what it depends

**Comment by Ghostkeeper** [comment] 2018-07-13 10:52
This is a duplicate of https://github.com/Ultimaker/Cura/issues/1940.

**Closed by Ghostkeeper** 2018-07-13 10:52 UTC
Labels: Status: Needs Info

**Comment by Ghostkeeper** [comment] 2018-07-13 10:53
In particular, RegenboogViske has found an apparent workaround: Reset the registry key `/HKEY_CURRENT_USER/Control Panel/Desktop/MenuShowDelay` to its default value of 400.
