### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by theyoungmind** [Ultimaker/Cura#14557] opened 2023-02-14 07:43 UTC
### Application Version

5.2.2

### Platform

Windows 10

### Printer

CR10spro

### Reproduction steps

Tried slicing

### Actual results

Slicing failed...

### Expected results

Sliced gcode

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

![Screenshot 2023-02-14 130243](https://user-images.githubusercontent.com/125345630/218671188-a965179c-3613-4fd2-8486-76887ff21e7e.jpg)

**Comment by MariMakes** [comment] 2023-02-21 09:57
Hey @theyoungmind,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Is it possible that your printjob is located at 0, 0, 0, and it slices if you move it a little away from the center of the buildplate? 
Then it might be a duplicate of https://github.com/Ultimaker/Cura/issues/13643

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Closed** 2023-03-07 12:20 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage, Slicing Error :collision:
