### ISSUE TITLE
[5.0b1] High GPU usage (Win10, Dell 9570)

### ISSUE THREAD

**Issue by galfridus** [Ultimaker/Cura#12148] opened 2022-05-09 13:42 UTC
### Application Version

5.0b1

### Platform

Windows 10

### Printer

Ender 3 V2

### Reproduction steps

1. Open Cura with any model

### Actual results

2. Fan speed goes up, GPU usage goes up

### Expected results

GPU usage and fan speed should be much lower (evidenced on Cura 4.13.1)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

N/A

**Comment by SkyBeam** [comment] 2022-05-10 10:08
Duplicate of https://github.com/Ultimaker/Cura/issues/11975

**Closed** 2022-05-10 11:25 UTC
Labels: Type: Bug
