### ISSUE TITLE
Slotty Skull And Bow

### ISSUE THREAD

**Issue by dejanmaksa** [Ultimaker/Cura#16316] opened 2023-07-29 10:13 UTC
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Ender CR-10

### Describe model location

Slice didn't work in Cura 5.4.0 but did work in Cura 5.3.1

### Describe your model

Slotty Skull And Bow

### Add your .zip here ⬇️

[SlottySkullAndBowl.zip](https://github.com/Ultimaker/Cura/files/12206835/SlottySkullAndBowl.zip)

**Comment by GregValiant** [comment] 2023-07-29 10:56
Thanks for the report.
The model has errors and that might be why it won't slice for you.  You can try moving the model on the Cura build plate, rotating the model, or changing the Initial Layer Height by a little bit.
I didn't have any trouble slicing this so I can't reproduce the problem.
I'll mark this as a duplicate as there are reports that show this behavior is a Cura problem.  I'll go ahead and close it as well as the Cura team has a lot of examples of this behavior.  I hope you understand.
![image](https://github.com/Ultimaker/Cura/assets/64202104/bf859fcd-0bd1-4033-a818-22dea0c48774)
![image](https://github.com/Ultimaker/Cura/assets/64202104/4c72d5a1-5e58-4d34-bced-215f66a95e26)

**Closed by GregValiant** 2023-07-29 10:56 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:
