### ISSUE TITLE
Setting textboxes overlap when OS is configured with right-to-left language locale

### ISSUE THREAD

**Issue by Ramzor-1** [Ultimaker/Cura#9667] opened 2021-04-23 10:54 UTC
### Application Version

4.9.0

### Platform

Windows 10

### Printer

FBG5

### Reproduction steps

Just install the latest version 4.9.0 
Bad visual displaying of numbers and units. Looks like they badly justified and overlaid on each other.
See attached file

![Cura4 9 Overlay BUG](https://user-images.githubusercontent.com/83068992/115860166-ccbd9600-a439-11eb-84bc-001334c5476b.PNG)

### Actual results

Just install the latest version 4.9.0 
Bad visual displaying of numbers. Looks like they are overlaid on each other.
See attached file

### Expected results

Bad visual displaying of numbers. Looks like they are overlaid on each other.

**Comment by jellespijker** [comment] 2021-04-23 17:11
This might be a duplicate of #9643

**Comment by happysleeper** [comment] 2021-04-24 07:43
I have the same annoying problem

**Comment by fvrmr** [comment] 2021-04-26 09:59
Hi @Ramzor-1 it looks like a duplicate indeed of #9643 but I would like to keep this open since you've posted screenshots.
Could you also provide me a log file? Maybe we can find something there.

**Comment by SnowflakeSolutions** [comment] 2021-04-26 17:04
I have the same Issue, attached the log file
[cura.log](https://github.com/Ultimaker/Cura/files/6378860/cura.log)

**Comment by fvrmr** [comment] 2021-04-30 11:17
I can reproduce this issue when I set the language of my computer to a RTL language like Arabic. I will discuss this issue with the team. Keep you posted!

**Comment by fvrmr** [comment] 2021-05-03 10:05
I have discussed it with the team. And we've created a ticket on our backlog.
Developers see CURA-8206.

**Closed** 2021-06-07 16:01 UTC
Labels: Type: Bug
