### ISSUE TITLE
travellers in the sliced design also laying down material

### ISSUE THREAD

**Issue by mdeans** [Ultimaker/Cura#2683] opened 2017-10-26 03:46 UTC
Tried printing a model which was hollow and had material strung across inside which seemed to correlate with the travellers in the sliced design. It was a print in one iris box design and prevented it to move when finished. The ones in dark blue are the ones that caused the issue as they ran over a couple of the moving layers
![travellers](https://user-images.githubusercontent.com/33110897/32034137-b6284668-b9de-11e7-9de7-3d4aac15ee53.jpg)

**Comment by smartavionics** [comment] 2017-10-26 05:53
Those dark blue lines are travel with no retraction. If you turn off combing, do they become light blue?

**Comment by mdeans** [comment] 2017-10-26 15:29
I didn’t have the combing setting on I don’t think. It wasn’t an option I chose to adjust. I’ll tinker with it a little and see what i can find. I’ll let you know.

Thanks for the quick response 

Regards

Mark

**Comment by smartavionics** [comment] 2017-10-26 15:31
Hi, I think that it is on by default (not 100% sure of that!)

**Comment by mdeans** [comment] 2017-10-26 17:52
Looks like combing mode off would fix it, no dark blue lines on the sliced model

Thanks!

**Comment by smartavionics** [comment] 2017-10-26 17:59
Thanks for the confirmation i already have an issue open for possibly the same bug (direct line travels that cross air that should have either have used retraction or taken another path).

**Comment by fionnb** [comment] 2017-10-30 15:35
I can confirm that sometimes v3 lays a line when traveling where it should not. It is especially problematic on the first layer, where the unwanted line often collides with the layer fill and makes the whole thing come off the bed. I can provide an example project to show this if you wish.

**Comment by smartavionics** [comment] 2017-10-30 15:36
Please do provide an example so I can investigate.

**Comment by filipgoc** [comment] 2017-10-31 01:28
Hm. I have also just discovered an intensely strange combing issue. Just posted it in Cura repo: https://github.com/Ultimaker/Cura/issues/2704
Looks like another beast, but it very well could have the same root!

**Comment by Ghostkeeper** [comment] 2017-11-06 01:03
This seems to be a duplicate of https://github.com/Ultimaker/CuraEngine/issues/625.

**Closed by Ghostkeeper** 2017-11-06 01:03 UTC
