### ISSUE TITLE
no permite duplicar objetos ya cargados en pantalla

### ISSUE THREAD

**Issue by gasperar** [Ultimaker/Cura#16013] opened 2023-07-05 13:39 UTC
### Cura Version

4.11.0

### Operating System

macOS 12.6.6 Monterey

### Printer

Hellbot Hidra Plus

### Reproduction steps

colocar un objeto stl, intentar duplicarlo y queda congelada la ventana superpuesta.

### Actual results

colocar un objeto stl, intentar duplicarlo y queda congelada la ventana superpuesta.

### Expected results

colocar un objeto stl, intentar duplicarlo y queda congelada la ventana superpuesta.

### Add your .zip and screenshots here ⬇️

colocar un objeto stl, intentar duplicarlo y queda congelada la ventana superpuesta.

**Comment by MariMakes** [comment] 2023-07-05 15:39
Hey @gasperar,

Lo siento, no puedo hablar español, pero creo que puedo ayudarte.

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

Cura 4.11 is from September 7, 2021.
We've made a lot of changes in Cura since then. 

Can you download the latest version of Cura for us and let us know if you can still reproduce it? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.4.0

If you can still see it, it would help if you could provide a picture or a video of your issue, or at least fill in the template/
That makes it easier to troubleshoot and resolve. 

Gracias 🙏

**Comment by gasperar** [comment] 2023-07-05 17:51
Thank you! I update the application and worked
regards
Gaston Perez

**Comment by MariMakes** [comment] 2023-07-06 13:48
Hey @gasperar,

So glad to hear 😄 
I'll close the issue 

Please let us know if you run into any other issues 💪

**Closed by MariMakes** 2023-07-06 13:48 UTC
Labels: Type: Bug, Status: Triage
