### ISSUE TITLE
Break up supports in chunks - doesn't break up anything

### ISSUE THREAD

**Issue by tlhintoq** [Ultimaker/Cura#14700] opened 2023-02-27 00:40 UTC
### Application Version

5.3.0-Alpha or beta

### Platform

Windows10x64, 21H2

### Printer

All - Not printer specific

### Reproduction steps

Put in a model.  
Support it
Choose to break up supports.

### Actual results

Supports are clearly not getting broken up into chunks.  One massive wall of support as shown.

### Expected results

There should be chunks of supports as the name implies.  Broken into segments (aka 'chunks') that can be removed indivually.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

See attachements and screen shots. No crash so no log attached.
![ChunksNotChunking](https://user-images.githubusercontent.com/11351506/221447688-af2d5a47-a16c-44d2-bec2-6a6147835b07.jpg)
[ChunksNotChunking.zip](https://github.com/Ultimaker/Cura/files/10835204/ChunksNotChunking.zip)

**Comment by MariMakes** [comment] 2023-04-03 14:19
Hey @tlhintoq,

Sorry, it took us a while to get back to you 😞 

Break support up on chunks is not a setting I use often so I had to ask around.

I've been told that the setting breaks up long zig zag support. See image without and with (see red arrows) attached to this thread. It indicates after how many zigzag infill lines it will remove a connecting zigzag line. It works best if your support wall is 0. 

![image (54)](https://user-images.githubusercontent.com/40423138/229537209-4aafef1a-e289-464a-827f-c3138af66346.png)
![image (55)](https://user-images.githubusercontent.com/40423138/229537215-e65fbc41-c57f-4c7f-89f3-ac18a48832ce.png)

It still works as intended in Cura 5.3.
Apologies for any inconvenience caused by our delayed response. 
I'll be closing this issue. I hope you understand.

**Closed by MariMakes** 2023-04-03 14:19 UTC
Labels: Type: Bug, Status: Triage

**Comment by MariMakes** [comment] 2023-04-04 09:54
Hey @tlhintoq,

Currently the tooltip reads: 
_"Skip some support line connections to make the support structure easier to break away. This setting is applicable to the Zig Zag support infill pattern.",_

How would you improve it?

**Comment by tlhintoq** [comment] 2023-04-04 19:36
You're right it does.  I stand corrected.
