### ISSUE TITLE
[4.2.0] and up octoprint no longer working , or even appearing in the menu.

### ISSUE THREAD

**Issue by nerdguy1338** [Ultimaker/Cura#6133] opened 2019-08-01 23:01 UTC
4.1= octoprint works fine, loads files, send to octo, runs great,

update to 4.2, no more octoprint anywhere, reinstall from the market, restart cura, still nothing.
still not fixed as of 4.2.1

**Comment by ArtieH** [comment] 2019-08-02 00:56
Same here. Backed out to 4.1

**Comment by JohnEdwa** [comment] 2019-08-02 02:57
https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues/120#issuecomment-516718924

**Comment by fieldOfView** [comment] 2019-08-02 07:12
Duplicate of #6088

**Closed** 2019-08-02 07:27 UTC
Labels: Type: Bug
