### ISSUE TITLE
Multiply Selected x1 does not work 

### ISSUE THREAD

**Issue by pastera** [Ultimaker/Cura#11897] opened 2022-04-22 23:45 UTC
### Application Version

5.0.0-Beta+1

### Platform

Windows 10

### Printer

Tronxy X5SA Pro and Creality Ender 3

### Reproduction steps

Place single STL on buildplate
Right click and select "Multiply Selected" 
Leave quantity at 1 - Select Okay

### Actual results

Result: no new object

### Expected results

Object is copied

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

If you change the quantity to anything other than 1 it works correctly even if you return the value to 1

**Comment by fieldOfView** [comment] 2022-04-23 08:53
Good catch! Fixed in https://github.com/Ultimaker/Cura/pull/11906

**Comment by fvrmr** [comment] 2022-04-25 11:41
Closing this issue because it is a duplicate of https://github.com/Ultimaker/Cura/issues/11894

**Closed by fvrmr** 2022-04-25 11:41 UTC
Labels: Type: Bug
