### ISSUE TITLE
Cura 5 Appimage wont remember path of last used folder 

### ISSUE THREAD

**Issue by MrEd88** [Ultimaker/Cura#12647] opened 2022-06-30 22:57 UTC
### Application Version

5.0.0

### Platform

Linux Mint 20.2

### Printer

Modified Ender 3

### Reproduction steps

1. Open model file
2. Try to add another model

### Actual results

Last used folder is not remembered, the file picker window defaults to home folder.

### Expected results

Same thing happend when saving the gcode.
File picker should remember the las used path.
Issue was not present on cura 4.13 and arachne beta.
Noticed file picker windows is different in those versions and Cura 5. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

CURA V4.13 and Arachne Beta window

![cura4 and beta](https://user-images.githubusercontent.com/19942461/176791607-a5c6be66-ce5b-4e42-bb67-7b65e203e1df.png)

Cura V5 window

![cura5](https://user-images.githubusercontent.com/19942461/176791612-e8189107-0cf7-43e2-ac15-fb4e9853237b.png)

**Comment by MariMakes** [comment] 2022-08-23 14:00
Hey @MrEd88 

Thanks for reporting this issue.
It seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12295 which we already have on our backlog with the intent to resolve. Fingers crossed 🤞 

I'm closing this one as a duplicate and you can follow any progress in https://github.com/Ultimaker/Cura/issues/12295

**Closed by MariMakes** 2022-08-23 14:00 UTC
Labels: Type: Bug, Status: Triage
