### ISSUE TITLE
Wrong temperatures in 2.6 beta

### ISSUE THREAD

**Issue by stampedeboss** [Ultimaker/Cura#1955] opened 2017-06-09 00:10 UTC
When switching between different materals the generated GCode is not picking up the proper Printing Temperature and Print Temp Initial Layer.  Regardless of the material temps set I generates 210 for both.  Bed Temp does change however.

Running 2.6 on Mint 18.1 KDE addition using the AppImage.

**Comment by Ghostkeeper** [comment] 2017-06-10 23:24
Did you also take a look at the Initial Printing Temperature and the Final Printing Temperature?

Perhaps you could save a project file and upload it here so that we can try to reproduce it for you. When I'm exporting a simple cube model just now it seems to create the correct temperatures.

**Comment by ethanspitz** [comment] 2017-06-11 06:07
I also have this issue. No matter what temperature I set (I have initial and final temperature also set) it seems to want to program me down to 200.

**Comment by Ghostkeeper** [comment] 2017-06-19 07:01
Perhaps you could share a project file with us, that shows the issue. I can't reproduce it; it sets the temperature correctly to the initial layer printing temperature initially, even if I overwrite it to 206 instead of 205.

**Comment by ethanspitz** [comment] 2017-06-19 07:22
I just tried, but the save functions don't work for me either.

**Comment by maukcc** [comment] 2017-06-19 07:30
Is this on a multi extruder setup?
We had this problem as well in the start gcode. 
Because Cura does not know which extruder is going to be used 1st when inserting the start gcode it takes the default temp.

**Comment by ethanspitz** [comment] 2017-06-19 07:36
Single extruder, using custom printer though, so I'm not sure if Cura handles that as a n-extruder setup or not. (Monoprice Maker Ultimate/Wanhao Duplicator 6).

**Comment by maukcc** [comment] 2017-06-19 07:53
can you post your start_gcode?

**Comment by maukcc** [comment] 2017-06-19 07:55
It does the same for me too: 200 no matter what.
with custom printer and unchanged start gcode

**Comment by maukcc** [comment] 2017-06-19 07:58
if you add these codes to the start gcode it will work fine:
M190 S{material_bed_temperature_layer_0}
M109 S{material_print_temperature}

still: this is a bug!

**Comment by maukcc** [comment] 2017-06-20 07:28
The thing that ethanspitz is seeing is a different issue then what stampedeboss is reporting.
The ethanspitz issue is also addressed here : #1993

**Comment by stampedeboss** [comment] 2017-06-20 23:47
Actually it is the same.  It appears that it is picking up the values from the extruder profile instead of the material entries.

**Comment by fieldOfView** [comment] 2017-06-22 08:34
The issue reported by @ethanspitz and @maukcc is fixed in #2009 
@stampedeboss, are you also using a "Custom FDM Printer" with 1 extruder?

**Comment by stampedeboss** [comment] 2017-06-22 10:05
Yes

**Comment by fieldOfView** [comment] 2017-06-22 10:15
Great, then this issue is fixed with #2009

**Comment by ethanspitz** [comment] 2017-06-23 01:56
Confirmed here that #2007/#2009 fixed my issue.

**Closed** 2017-06-23 08:15 UTC
