### ISSUE TITLE
Slicing Failed Error

### ISSUE THREAD

**Issue by sigmar93** [Ultimaker/Cura#14484] opened 2023-02-05 11:52 UTC
### Application Version

5.2

### Platform

Windows 10

### Printer

Anycubic Kobra

### Reproduction steps

Hi, I was trying to slice the project. With the basic settings there are no problems, when I use the settings recommended by the vendor the slice stops with an error message

### Actual results

Unexpeted Error

### Expected results

Slice correctly

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[AK_945-1-1_hull_front_FDM (repaired).zip](https://github.com/Ultimaker/Cura/files/10610868/AK_945-1-1_hull_front_FDM.repaired.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/10610873/cura.log)
![Screenshot (226)](https://user-images.githubusercontent.com/20780492/216816827-fe929c44-4608-4a92-a3bf-e0dd7eeef553.png)
[945-CURA Settings.pdf](https://github.com/Ultimaker/Cura/files/10610877/945-CURA.Settings.pdf)

**Comment by GregValiant** [comment] 2023-02-05 15:04
Thanks for the report and the file.
I couldn't get it to slice either.  I moved it, rotated it, but it wouldn't slice until I change the layer height to 0.16.  It's a 54 hour print.
This appears to be a duplicate of numerous other reports of this behavior.  The bug has been addressed and should be fixed in the next release of Cura.
I'll mark this as a duplicate slicing error and since a fix is in place I'll close this report. I hope you understand.

**Closed by GregValiant** 2023-02-05 15:04 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error :collision:
