### ISSUE TITLE
[4.6.0] Non-Ultimaker Printers not listed

### ISSUE THREAD

**Issue by mnswamp1** [Ultimaker/Cura#7614] opened 2020-04-28 02:40 UTC
**Application version**
4.6.0

**Platform**
Windows 10 OS version 1903 build 18362.778

**Printer**
None - that's the issue in a nutshell

**Reproduction steps**
1. New install of Cura 4.6 from Ultimaker website.  (New Cura user, too)
2. Completed install, accepting defaults.
3. Launch Cura.
4. Preferences - Printers - Add printer
 
** Screenshot**
![cura printer](https://user-images.githubusercontent.com/64115026/80440619-cc45fa00-88ce-11ea-9bca-955b559e4743.png)
6. Tried to twist toggle, etc.  
7. uninstall/reinstall - no joy

** Expected result**
select Creality Ender 3 printer

**Log files** 

[stderr.log](https://github.com/Ultimaker/Cura/files/4543065/stderr.log)
[stdout.log](https://github.com/Ultimaker/Cura/files/4543066/stdout.log)

**Additional information**
(Extra information relevant to the issue.)

**Comment by fieldOfView** [comment] 2020-04-28 05:45
There is a scrollbar, but it is hidden untill you use it.

**Comment by Ghostkeeper** [comment] 2020-04-28 08:14
Duplicate of https://github.com/Ultimaker/Cura/issues/6299.

**Closed by Ghostkeeper** 2020-04-28 08:14 UTC
Labels: Type: Bug

**Comment by mnswamp1** [comment] 2020-04-28 14:10
Wow.  You really, really have to dig for that one.  Thanks so much for quickly ID'ing the issue.
