### ISSUE TITLE
Cura is Cool!

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Cura#4000] opened 2018-06-29 08:39 UTC
I just wanted to mention that. 
Feel free to close this issue.

**Comment by fieldOfView** [comment] 2018-06-29 08:40
I could not let issue #4000 be just some random issue.
🍰 🍾 🍪

**Comment by Appesteijn** [comment] 2018-06-29 09:17
w00t w00t! Thanks :)

**Comment by diegopradogesto** [comment] 2018-06-29 09:17
I agree!!!

**Comment by Ghostkeeper** [comment] 2018-06-29 09:21
Duplicate of https://github.com/Ultimaker/Cura/issues/3796?

**Comment by filipgoc** [comment] 2018-07-04 19:47
Hahaha. This issue should be tagged as a _constant Improvement_

**Closed** 2018-11-26 22:29 UTC
Labels: Category: 3rd-Party, Category: Cura, Category: Cura-Build, Category: Engine, Category: Hardware, Category: Settings, Category: Translations, Category: UX, Category: Uranium, Status: Fixed/Solved, Status: In Progress

**Comment by nallath** [comment] 2018-11-27 13:40
Cura is no longer cool :(

**Comment by fieldOfView** [comment] 2018-11-27 13:48
> 1. To make clear we (the Cura team) is not going to do this and don't give any false hopes that we will do this in some distant future. Of course someone else can implement this, but we don't have the time.
> 2. To clean up the issue list so we can focus on the things that are critical and need to be fixed.
