### ISSUE TITLE
Cura 2.3.1 not showing model in layer view

### ISSUE THREAD

**Issue by TheUnHumanZone** [Ultimaker/Cura#1459] opened 2017-02-21 10:53 UTC
I've had this problem a long time and don't know how to fix it.

**Comment by fieldOfView** [comment] 2017-02-21 11:20
2.4 has just been released. It might fix your issue. If not, we need your logs.

**Comment by MatteoRagni** [comment] 2017-08-27 12:11
I'm experiencing the same problem.

[the log](https://gist.github.com/MatteoRagni/7b0c286435b397ffad9e4bd541043ff8)

and an image of what is happening:

If all layers are selected to be visible everything is ok:
![before](https://user-images.githubusercontent.com/4260219/29749662-895604c6-8b31-11e7-9862-e319939d401d.png)
but if I remove even one layer:
![after](https://user-images.githubusercontent.com/4260219/29749667-99a55d36-8b31-11e7-98e2-70397fd48ce1.png)

**Comment by Ghostkeeper** [comment] 2017-09-02 17:15
This doesn't reproduce on my end.

**Comment by ChrisTerBeke** [comment] 2018-01-22 20:46
Unable to reproduce and no comments for almost a year. Closing until re-opened.

**Closed by ChrisTerBeke** 2018-01-22 20:46 UTC
