### ISSUE TITLE
Cura 3.0.3: Black raster on black buildplate (and color issues)

### ISSUE THREAD

**Issue by 7eggert** [Ultimaker/Cura#2652] opened 2017-10-21 17:59 UTC
System: Debian/Jessie, KDE, Oxygen theme.
Cura version(s): 3.0.3 AppImage

The Cura build plate does not show the 1 mm / 10 mm lines but it is completely black.

My printer is configured as Prusa I3 (Anet A8).

Also while writing this, I noticed that the drop down input elements are displayed with light-gray text on lighter-gray background.

**Comment by fieldOfView** [comment] 2017-10-22 08:33
This first issue is a duplicate of https://github.com/Ultimaker/Cura/issues/2630

Could you add a screenshot of the second issue?

**Comment by Ghostkeeper** [comment] 2017-10-31 00:02
A screenshot is often difficult with drop-downs on KDE.

We might mix up some system theming with our own theming somewhere, but as far as I know we don't theme the drop-down menus at all (apart from what they drop down from).

**Comment by 7eggert** [comment] 2017-11-03 10:22
![cura-dropdown](https://user-images.githubusercontent.com/924567/32369376-3fd25e2a-c089-11e7-8bf1-3cfe7863a927.jpg)
![cura-plate](https://user-images.githubusercontent.com/924567/32369375-3fb554ce-c089-11e7-90c0-953aeea4f013.jpg)

**Comment by ChrisTerBeke** [comment] 2017-11-03 10:25
Please check the newly released 3.0.4 version to see if the build plate issue was fixed. The dropdown menus aren't styled indeed.

**Comment by 7eggert** [comment] 2017-11-03 12:43
Download failed in Opera 12 / no cookies, no third-party-cookies, no referrer, no script except ultimaker + Cloudfront; Used vivaldi instead (not my main browser until it supports privacy).

Blach build plate is fixed.

**Comment by ChrisTerBeke** [comment] 2017-11-03 13:23
The download is not arranged by the Cura team but by the web team. Closing since the black build plate is fixed now.

**Closed by ChrisTerBeke** 2017-11-03 13:23 UTC
