### ISSUE TITLE
Cura 3.2.1 freeezes when slicing

### ISSUE THREAD

**Issue by abj80** [Ultimaker/Cura#3334] opened 2018-02-16 10:19 UTC
**Application Version**
3.2.1

**Platform**
Windows 10 64 bit

**Steps to Reproduce**
After loading a model, pressing the "Prepare" button freezes Cura. I even did a clean install (removed all the files related to older Cura versions) but I still get the same result, even with the default settings.

I have attached the log file.

Thank you!

[cura.log](https://github.com/Ultimaker/Cura/files/1730902/cura.log)

**Comment by smartavionics** [comment] 2018-02-16 10:48
Hi, I don't know what is the cause but in your log file you have the following error:
````
2018-02-16 12:11:29,367 - DEBUG - [(10236)-Thread-12] UM.Backend.Backend._backendLog [90]: [Backend] [ERROR] Arcus Fatal Error (2, native 10013): Could not connect to the given address
2018-02-16 12:11:29,431 - DEBUG - [(7376)-MainThread] CuraEngineBackend.CuraEngineBackend._onBackendQuit [722]: Backend quit with return code 0. Resetting process and socket.
````

Hopefully, an Ultimaker person can advise you as to what is wrong.

**Comment by abj80** [comment] 2018-02-16 11:00
It seems that the culprit was the firewall. After some adjustments, everything works fine now.

**Comment by smartavionics** [comment] 2018-02-16 11:01
Great, please close the issue if everything is now OK. Cheers.

**Closed** 2018-02-16 11:02 UTC
