### ISSUE TITLE
[3.3] Custom materials and quality profiles

### ISSUE THREAD

**Issue by ChrisRiddell** [Ultimaker/Cura#3792] opened 2018-05-09 07:33 UTC
**Application Version**
3.3

**Platform**
Windows 10 

**Printer**
Ultimaker 2+

**Steps to Reproduce**
This is more a question I think I'm trying to update my Colorfabb PETG profiles https://github.com/ChrisRiddell/CuraProfile-ColorFabb-PETG-Eeconomy/tree/3.3

**Actual Results**
When I select the meterial from the drop down its just giving me the stock set of quality profiles not the ones I have made.

Here is the log
[cura.log](https://github.com/Ultimaker/Cura/files/1986780/cura.log)

**Expected results**
It to show the quality profiles I have made I'm not sure if I have missed anything with the change from 3.2 to 3.3 I looked at other profiles to make sure I made the right changes.

I have set the `material = colorfabb_petg` and `variant = 0.4 mm`

**Comment by jackha** [comment] 2018-05-09 08:48
Hi @ChrisRiddell . Thanks for the report. It's a duplicate of https://github.com/Ultimaker/Cura/issues/3728
You can also find a workaround there.

**Closed by jackha** 2018-05-09 08:48 UTC
