### ISSUE TITLE
error on slice command for valid 3MF model

### ISSUE THREAD

**Issue by staffert** [Ultimaker/Cura#14986] opened 2023-03-21 15:23 UTC
### Application Version

5.3.0

### Platform

windows 10 pro

### Printer

Custom (AON3D M2+)

### Reproduction steps

Imported a valid, manifold, 3MF file that has been used countless times....
Pressed slice.
error generated.

### Actual results

![image](https://user-images.githubusercontent.com/79226213/226652665-14b292bd-b277-495e-ad90-2ee8868eeb72.png)

### Expected results

expected to see a slice (even a bad one)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/79226213/226653152-659e6094-c87d-48da-b90a-4262bf73d46a.png)
[cura.log](https://github.com/Ultimaker/Cura/files/11029922/cura.log)

**Comment by MariMakes** [comment] 2023-03-23 10:45
Apologies for any inconvenience caused by our delayed response. 
Without more information about the project file, I cannot help you with troubleshooting. 
I'll be closing this issue. I hope you understand.

**Closed by MariMakes** 2023-03-23 10:45 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:
