### ISSUE TITLE
Slice failed (fixed by rotating and moving model)

### ISSUE THREAD

**Issue by koivuns** [Ultimaker/Cura#19094] opened 2024-05-18 06:42 UTC
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Creality Ender 3 Pro (i have a 3 neo v2 but Pro profile is said to work

### Name abnormal settings

Tree support causes the slicing error

### Describe model location

Yes it worked when i rotated and then moved it

### Describe your model

Slices fine with generic support, it should be watertight but i didnt personally design it. No i havent tried mesh fix i didnt know that was a thing thats cool

### Add your .zip here ⬇️

[CE3PRO_Ikea_CupHolder_v1.zip](https://github.com/Ultimaker/Cura/files/15360344/CE3PRO_Ikea_CupHolder_v1.zip)

**Comment by GregValiant** [comment] 2024-05-18 10:23
Thanks for the report.
This was a well known bug in Cura 5.5 and 5.6.  A lot of work was done and 5.7 and now 5.7.1 don't show anywhere near the problems of the two previous versions.  I suggest you install 5.7.1 and see if the problem is gone.

I'll mark this as a duplicate and go ahead and close this as it appears to have been fixed.

**Closed by GregValiant** 2024-05-18 10:23 UTC
Labels: Type: Bug, Status: Under Investigation, Slicing Error :collision:
