### ISSUE TITLE
Ultimaker 2 prints only 500MB of Gcode file

### ISSUE THREAD

**Issue by msiccha** [Ultimaker/Cura#3935] opened 2018-06-15 09:05 UTC
**Application Version**
Cura 3.3.1

**Platform**
Windows 10

**Printer**
Ultimaker 2+ (upgraded UM2)

**Steps to Reproduce**
Generate a gcode file larger than 500MB and print it

**Actual Results**
Print result is incomplete, the last X levels are not printed

**Expected results**
Full print

**Additional Information**
I cannot attach a project file as this would be very large, but there is a photo of an example icomplete print of a large model.
![incomplete print](https://user-images.githubusercontent.com/40291898/41460075-bc2aeb6a-708b-11e8-8514-675f73d43291.jpg)

**Comment by Vandrasc** [comment] 2018-06-15 13:28
Hi @msiccha, does the gcode looks complete?

[Save to File > Save as type Gcode]

And, did you tried to load the gcode back into Cura and verify the layer view? Does your model look complete? Thanks!

**Comment by msiccha** [comment] 2018-06-15 14:17
Hi @Vandrasc ,
I cannot look at the gcode at the moment (no editor installed that can view files that large) but if I reload the model from the GCODE file to Cura it is complete and the layer view shows nothing suspicious.

**Comment by ianpaschal** [comment] 2018-07-10 11:35
If you are seeing the whole gcode in Cura after slicing and reloading the gcode then this appears to be a problem with the printer. Normally that is very hard for us to diagnose but since this is a UM printer we can try to take a look. Would be useful to have your model and project file when possible.

**Comment by Ghostkeeper** [comment] 2018-08-24 07:59
I asked one of our firmware engineers and he hadn't heard of this problem before. He thinks that you might have a good chance of getting an answer from the [Ultimaker forum](https://community.ultimaker.com/forum/109-firmware/).

For now this looks like a problem in the UM2 firmware rather than in Cura. Alternatively, you could also shoot in an issue at [their repository](https://github.com/Ultimaker/UM2.1-Firmware/issues). In any case, we'll close it here.

**Closed by Ghostkeeper** 2018-08-24 07:59 UTC
Labels: Status: Needs Info

**Comment by ckielstra** [comment] 2018-08-24 11:05
The issue is already closed here, but as a comment from the firmware team: 
We have tested the UM2(+) with files up to 1.3Gb working flawlessly. Files larger than 500Gb are used by many people without problems.

Reading all information, my suspicion is something odd with your memory card. There are many brands and models of memory cards, perhaps you have an incompatible card. What is the brand/model you are using?

Workaround: use another brand/model memory card.

**Comment by DDDirk** [comment] 2018-08-24 12:16
Of format the card. This solved a similar issue for me once.
