### ISSUE TITLE
new cura print time increase

### ISSUE THREAD

**Issue by PrintingTom** [Ultimaker/Cura#6205] opened 2019-08-15 11:03 UTC
**Application version**
4.2.1.
**Platform**
windows 10 
**Printer**
Which printer was selected in Cura? If possible, please attach project file as ENDER 3

**Reproduction steps**
updated to new cura 4.2.1. 

**Actual results**
i sliced a model that i used before with cura 4.1, i imported the settings file so nothing changed and the print time went from 51min to 1H19. The main difference in settings is that i cant set Z hop max speed anymore but apart from that i do not understand how i can slice it so that it prints so much slower
**Expected results**
i cant give you the print file for IP reasons unfortunately

**Comment by Ghostkeeper** [comment] 2019-08-15 19:41
It is more or less expected that the print time was increased with the 4.2 release for Ender printers. The profiles have been tuned much more towards quality than towards speed.

> i imported the settings file so nothing changed

That's incorrect. The profiles only store the settings that you changed over the defaults. In the new release, it puts new defaults underneath for all the settings that you didn't change in your profile.

> The main difference in settings is that i cant set Z hop max speed anymore

We changed that to a setting called Z Hop Speed.

I'm closing this because it's expected behaviour. Sorry! If you have any improvements to the default profiles, we'd love to hear them.

**Closed by Ghostkeeper** 2019-08-15 19:41 UTC
Labels: Type: Bug
