### ISSUE TITLE
Dragging the Cura window from a Retina display to a non-Retina display has unexpected effects

### ISSUE THREAD

**Issue by yourhead** [Ultimaker/Cura#2493] opened 2017-09-26 19:00 UTC
Using macOS with two displays: one retina and one standard (a very common setup for any user with a recent model macBook and an external display).

If you open Cura on the retina display then move the window to the standard display (e.g. you open it on your MacBook internal display and then drag it to your larger external monitor)…

The camera view seems to zoom in. Pushing the origin of the workspace to the upper-right. However it is not merely zoomed. Cura still thinks the origin is way up there off the screen somewhere. So Cura is unusable.

There are workarounds to get cura over to the other monitor by launching it with different display setups of the MacBook -- but it's quite the pain. Would be great if it just behaved like other apps.

Here are a couple screenshots.  The first is on a retina display (note the scrambled fonts -- that's another bug also filed):

<img width="774" alt="pasted_image_9_26_17__1_59_pm" src="https://user-images.githubusercontent.com/98634/30878674-eea75458-a2c2-11e7-907c-2b1730149ef8.png">

and here's the same window after dragging it to the external display:

![pasted_image_9_26_17__1_59_pm](https://user-images.githubusercontent.com/98634/30878690-fd485458-a2c2-11e7-9657-0f062b6d43ef.png)

Note the model, which is centered in the workspace is zoomed off to the upper left.

**Comment by nallath** [comment] 2017-09-27 11:24
@Appesteijn; Could you check if you could reproduce this?

**Comment by Appesteijn** [comment] 2017-09-27 11:47
We are currently implementing a fix for this, it is expected to be put live at 17 October (3.0.0). But I think we still only calculate the screen pixel density at startup, so dragging Cura to another screen might use a wrong DPI setting.

**Comment by fieldOfView** [comment] 2017-09-27 11:51
On OSX it the DPI setting is always the same between all displays. OSX renders everything at the DPI that is the highest between the connected displays, and then scales the window on the other DPI screens transparently. However, it is very likely that the opengl viewport does not "like" this.

**Comment by ChrisTerBeke** [comment] 2017-09-27 14:53
As this only affects a very specific edge case where you drag between different DPI monitors, and only on Mac, I think it's too small to fix. I'm not even sure if we can detect whether a window has changed to another monitor and then do something with that info.

**Comment by yourhead** [comment] 2017-09-27 15:39
NSWindowDidChangeBackingPropertiesNotification when properties like the screen depth of a window change.
https://developer.apple.com/documentation/appkit/nswindowdidchangebackingpropertiesnotification?language=objc

Both NSWindow and NSScreen have a backingScaleFactor property that provides the specific depth information about any window or screen.
https://developer.apple.com/library/content/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/APIs/APIs.html

**Comment by ChrisTerBeke** [comment] 2017-09-27 15:52
Please note that we're using Python and currently have not implemented any way to use Cocoa native elements. I've seen several solutions to get appkit libraries connected to python but that's a bigger change in the code base that needs internal discussion first. Will leave this ticket open for future reference.

**Comment by awhiemstra** [comment] 2017-09-28 08:26
The relevant Qt API you are looking for is http://doc.qt.io/qt-5/qwindow.html#screenChanged . Still, I think it would be better to try and get the Qt 5.6 high-DPI support working, since that should support things like this natively.

**Comment by ianpaschal** [comment] 2018-05-08 11:30
This has seen no activity for 7+ months and is not really a big problem. There's no glitch or crash or freeze or anything; just gotta zoom out a bit. I don't think we'll bother fixing this.

**Closed by ianpaschal** 2018-05-08 11:30 UTC
Labels: Category: Uranium, Type: Improvement
