### ISSUE TITLE
Feature Request - Measurment tools

### ISSUE THREAD

**Issue by Aeroengineer1** [Ultimaker/Cura#3777] opened 2018-05-05 03:56 UTC
When scaling models, or aligning multiple models having some basic measurement tools would be very handy to ensure that models scaled to the correct size or to ensure proper spacing.  

While I recognize that it may be hard to have tools that would recognize radius features and such with a STL mesh, but having the ability to select nodes, lines, and faces and use them as measurement references would be enabling.

**Comment by ianpaschal** [comment] 2018-05-05 20:55
Duplicate of 2545

**Closed by ianpaschal** 2018-05-05 20:55 UTC
Labels: Status: Duplicate
