### ISSUE TITLE
Layer slider, see how high the layer is.

### ISSUE THREAD

**Issue by Zogar89** [Ultimaker/Cura#9809] opened 2021-05-11 04:58 UTC
### Is your feature request related to a problem?

No

### Describe the solution you'd like

With the layer slider, Cura only shows the number of the selected layer. It would be very useful to also be able to see the height at which this layer is located.

Cases where it would be useful:
+Some printers only display the print height and not the layer number.
+If you want to relate a measurement on an object to a layer in the slicer.
+When you do color change with different prints at different heights.

![imagen](https://user-images.githubusercontent.com/11767960/117760705-810e3900-b1fc-11eb-8129-d9ab23e1c9b6.png)

**Comment by fvrmr** [comment] 2021-05-11 07:48
Hi @Zogar89 thank you for your feature request.
This is a duplicate of #7576 that's why I will close this issue.

**Closed by fvrmr** 2021-05-11 07:48 UTC
Labels: Type: New Feature
