### ISSUE TITLE
Mostruo

### ISSUE THREAD

**Issue by carrfel** [Ultimaker/Cura#17503] opened 2023-12-03 09:01 UTC
### Cura Version

UltiMaker Cura 5.6.0

### Operating System

Windows 11

### Printer

Tevo Tornado

### Name abnormal settings

??

### Describe model location

Dragón

### Describe your model

Dragón

### Add your .zip here ⬇️

[Drakon361_ring_LR.zip](https://github.com/Ultimaker/Cura/files/13538434/Drakon361_ring_LR.zip)

**Comment by 5axes** [comment] 2023-12-05 18:44
Guass What ?   **Print Thin Walls**

![image](https://github.com/Ultimaker/Cura/assets/11015345/3d5f9668-214c-4e79-a728-1b2d50d6d71e)

**Comment by MariMakes** [comment] 2024-01-18 15:29
Hi @carrfel,

Quick update from our side 👋
We are introducing a new tool to analyze slicing crashes like the one you reported. 💪

Even with the changes we made in the latest versions of Cura we still see that your model crashes. 🫤 But we have added your project file to our analyzing tool and found there were at least 10 crashes that were similar to yours, which helps us to narrow down what the cause is of your crash so we can resolve this for you and others.
Hopefully, we can find a solution soon 🤞

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/17438

**Closed by MariMakes** 2024-01-18 15:29 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:
