### ISSUE TITLE
Cura locks out other com ports

### ISSUE THREAD

**Issue by blair9095** [Ultimaker/Cura#7063] opened 2020-02-04 12:34 UTC
I often work with my arduino while printing.  If I start Cura before opening a com port in arduino (either a monitor or upload programming) the Arduino interface reports that it cannot connect to the assigned com port.

**Comment by mahtDFR** [comment] 2020-02-05 13:51
Duplicate of #5207

**Closed by mahtDFR** 2020-02-05 13:51 UTC
Labels: Type: Bug
