### ISSUE TITLE
First layer bed temperature issue on Cura for Lulzbot

### ISSUE THREAD

**Issue by enricotoso96** [Ultimaker/Cura#2969] opened 2017-12-12 14:06 UTC
Changing the first layer temperature in Cura for Mac is not reflected in the gcode. It is for the window's version. For instance, setting an initial bed temperature of 60 will still save M140 S110.

**Comment by ChrisTerBeke** [comment] 2017-12-12 14:12
Duplicate of https://github.com/Ultimaker/Cura/issues/1296.

**Closed by ChrisTerBeke** 2017-12-12 14:12 UTC
