### ISSUE TITLE
Slicing FAiled with Unexpected Error

### ISSUE THREAD

**Issue by tasif520** [Ultimaker/Cura#15099] opened 2023-03-31 12:28 UTC
### Application Version

5.3.0

### Platform

macOS Monetery

### Printer

Ultimaker 3

### Reproduction steps

Tried to slice a student project - just like I have many times before

### Actual results

<img width="505" alt="Screenshot 2023-03-31 at 13 21 36" src="https://user-images.githubusercontent.com/129515426/229119282-4c0030d7-4439-424e-aeeb-e96dad93395d.png">

### Expected results

should have sliced & given time for print

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[UM3_keychain-david Gheneim.3mf.zip](https://github.com/Ultimaker/Cura/files/11121781/UM3_keychain-david.Gheneim.3mf.zip)

**Comment by MariMakes** [comment] 2023-04-05 16:15
Hey @tasif520,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

I can reproduce your crash, this is definitely a model that shouldn't crash. 
Luckily our most common workaround seems to work for this model. 
I can slice the model if I rotate it 90 degrees, that solves a number of slicing errors. 
![image](https://user-images.githubusercontent.com/40423138/230141278-abf50755-51cd-4197-b7bb-8b7858fafcba.png)

I apologize for the inconvenience. 
I'll have someone from the team take a look at the slicing error.

**Comment by jellespijker** [comment] 2024-01-14 16:32
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.
I'm closing this issue as fixed for the 5.7.0 release
![image](https://github.com/Ultimaker/Cura/assets/8535734/2961f5b1-a58d-4f23-a381-82be8637aa17)

**Closed by jellespijker** 2024-01-14 16:32 UTC
Labels: Type: Bug, Status: Under Investigation, Slicing Error :collision:
