### ISSUE TITLE
[4.6.1] Scaling updates incorrect values after rotation

### ISSUE THREAD

**Issue by Mearman** [Ultimaker/Cura#7946] opened 2020-06-18 11:40 UTC
After rotating the model and updating the absolute scale for the Z axis, the scale percentage updates on the Y axis.

![image](https://user-images.githubusercontent.com/1331872/85015978-cfd45f80-b160-11ea-8447-9b32c1a3556c.png)

**Comment by jellespijker** [comment] 2020-06-18 21:04
Yes. this is probably a duplicate of #4136

**Comment by nallath** [comment] 2020-06-19 11:31
It is.

**Closed by nallath** 2020-06-19 11:31 UTC
Labels: Status: Duplicate, Type: Bug
