### ISSUE TITLE
STL File will not load

### ISSUE THREAD

**Issue by dnbernier** [Ultimaker/Cura#16257] opened 2023-07-24 12:32 UTC
### Cura Version

5.4.0

### Operating System

MAC OS 11.7.8

### Printer

Creality S1 PRO

### Reproduction steps

When I open an stl file, it does not load. This happened in ver 5.2 5.3 and 5.4. I looked at the log file. There were many errors regarding USB trying to connect. I then disabled the USB printing plugin. All models now load correctly. Is there something I am doing wrong? I don't print using USB so that is not an issue, but something is not correct.

### Actual results

 I looked at the log file. There were many errors regarding USB trying to connect. I then disabled the USB printing plugin. All models now load correctly. Is there something I am doing wrong? I don't print using USB so that is not an issue, but something is not correct.

### Expected results

STL loads correctly

### Add your .zip and screenshots here ⬇️

[cura.log.zip](https://github.com/Ultimaker/Cura/files/12145851/cura.log.zip)

**Comment by MariMakes** [comment] 2023-07-27 11:58
Hey @dnbernier,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/16249
We are still trying to figure out what is going wrong, the linked ticket contains a workaround but it's not working for everyone. 🤔 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/16249

**Closed by MariMakes** 2023-07-27 11:58 UTC
Labels: Type: Bug, Status: Triage
