### ISSUE TITLE
Cura constantly crashing

### ISSUE THREAD

**Issue by DALEKCHANNEL** [Ultimaker/Cura#15569] opened 2023-05-19 19:34 UTC
### Application Version

5.3.1

### Platform

Windows11

### Printer

CR-6 SE but I tried to set it for CR-6 Max please add that as one of the printer extensions please

### Reproduction steps

I opened Cura looking at a model and was editing the print settings and it started to freeze the application so I closed it and opened the model again it worked fine until I started using the print settings and it crashed again it has done this 3 times and on the last one it didn't even wait for me to do anything, and it just froze after a few seconds after it opened.
<img width="920" alt="Screenshot 2023-05-19 233316" src="https://github.com/Ultimaker/Cura/assets/71641995/941bc03c-3a2b-4387-b5a6-204eaf2cc882">

### Actual results

I have it opened now without the model and it seems fine I haven't touched anything, but I don't know if it will freeze again.

### Expected results

The screen might freeze

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

*

**Comment by MariMakes** [comment] 2023-05-22 12:43
Hey @DALEKCHANNEL,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13820
More people reported slowness with Cura and Windows 11. I personally upgraded my Windows to 11 to reproduce, but I haven't experienced it.

We might have a fix for this issue. It's a bit hard for us to test, but we have a nightly build available.
Can you please try it out and let us know if it resolves your issue?
You can find the download links and the discussion here: https://github.com/Ultimaker/Cura/discussions/15098

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/13820

**Closed by MariMakes** 2023-05-22 12:43 UTC
Labels: Type: Bug, Status: Triage
