### ISSUE TITLE
Taking stupidly long to slice large files

### ISSUE THREAD

**Issue by LDHUGS2406** [Ultimaker/Cura#16376] opened 2023-08-03 21:26 UTC
### Cura Version

5.3.1

### Operating System

Windows10

### Printer

Ultimaker S5

### Reproduction steps

Sliced a file at 100% scale fine quickly with no issues.
Sliced the same file at 219% to fill the build plate, goes stupidly slow 40mins + to slice any large STL files.

### Actual results

I have a High spec PC and other slicers really dont struggle anywhere close to how much Cura does. (Have tried older versions & Newest version of Cura, slightly faster on the new version but think I could beat it drawing by hand)

### Expected results

Model should slice withing a minute or two.

### Add your .zip and screenshots here ⬇️

.

**Comment by MariMakes** [comment] 2023-11-16 13:02
Hey @LDHUGS2406,

Sorry, it took us a while to get back to you 😞 
Did you check the setting Optimize Wall Printing Order?
Than it might be a duplicate of https://github.com/Ultimaker/Cura/issues/17104

To troubleshoot this, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Closed** 2023-12-01 00:19 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage
