### ISSUE TITLE
Sovol SV02 can not slice with prime tower enabled

### ISSUE THREAD

**Issue by spe-ciellt** [Ultimaker/Cura#17295] opened 2023-11-12 15:11 UTC
### Cura Version

5.5.0

### Operating System

Ubuntu Linux 22.04

### Printer

Sovol SV02

### Reproduction steps

Use printer "Sovol SV02 (Legacy)"
1.  Have two objects that uses separate extruders
2. Enable prime tower
3. Slice

### Actual results

Error Message
> "Unable to slice with the current settings. The following settings have errors: Prime Tower Minimum Volume"

Enable and check settings for Prime Tower Minimum Volume. The field is empty and have a red-ish background color.

### Expected results

Happy slicing ;)

I  searched the Issues and saw issue #14707 

I then triaged between releases and did some `git blame` on the line that is mentioned in the bug report above.

Before 5.3.0 release the line was 
```
"prime_tower_min_volume": { "value":  "((resolveOrValue('prime_tower_size') * 0.5) ** 2 * 3.14159 * resolveOrValue('layer_height'))/2"},
```
The 5.3.0 release contained the line
```
"prime_tower_min_volume": { "value": "((reveOrValue('layer_height'))/2" },
```
And the fix in #14707 mentioned above was
```
"prime_tower_min_volume": { "value": "((resolveOrValue('layer_height'))/2" },
```

So the fix in #14707 was probably insufficient.

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/1024245/c67d77d9-0e45-483b-b9c8-516ef913cabc)

![image](https://github.com/Ultimaker/Cura/assets/1024245/a494e133-0d00-461e-8f10-ab685da09f4f)

**Comment by GregValiant** [comment] 2023-11-13 11:46
Thanks for the report.
This is not the only problem with the definitions for Sovol printers.
That line is still in error.  The fix I mentioned in #14707 was not applied correctly as the misspelling wasn't the only problem.
There is an extra "(" and so Cura won't except the syntax.  The Cura.log file notes it as:

2023-11-13 06:11:37,262 - ERROR - [MainThread] UM.Settings.SettingFunction._safeCompile [75]: Parse error in function (((resolveOrValue('layer_height'))/2) for setting: **'(' was never closed** (eval, line 1)

The problem is unequal opening/closing parentheses.
"prime_tower_min_volume": { "value": **"((resolveOrValue('layer_height'))/2"** }
it should be:
"prime_tower_min_volume": { "value": **"resolveOrValue('layer_height')/2"** }

You can make the change locally in your SV02 definition file ("SV02.def.json" line 62).

See pull request #17304 

I'll go ahead and close this as the PR should fix the problem

**Closed by GregValiant** 2023-11-13 11:46 UTC
Labels: Type: Bug, Status: Under Investigation, PR: Printer Definitions :factory:
