### ISSUE TITLE
Slicing error

### ISSUE THREAD

**Issue by WildIsDead** [Ultimaker/Cura#13641] opened 2022-10-24 17:09 UTC
### Application Version

5.2.1

### Platform

windows 10

### Printer

Creality Ender-3/ Ender -3 v2

### Reproduction steps

1. I uploaded a file of a print onto Cura.
2. I adjusted the sizes slightly 
3. I clicked slice

### Actual results

It stopped slicing and said the was an error

### Expected results

It should have sliced the miniature.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[Peter Griffin.zip](https://github.com/Ultimaker/Cura/files/9853782/Peter.Griffin.zip)

**Comment by GregValiant** [comment] 2022-10-24 17:33
Thanks for the report.
Here is a view of your model in Mesh Mixer.  The red balls indicate errors in the model.
![image](https://user-images.githubusercontent.com/64202104/197587729-e716db9d-ee31-46a6-bf24-9d374b703bd9.png)

--> 64 Non-manifold edges (?)
--> 63 Inverted faces (?)
--> 8 Degenerate faces (?)

Once you repair the model it will slice.  Ms 3D Builder is included with Windows and didn't have any trouble making the repair.
![image](https://user-images.githubusercontent.com/64202104/197588639-4c6cea66-f24a-47ca-9b2d-d529bf280e47.png)

This is a model issue rather than a bug.  I'll close this report.  If you think that is premature.  We can always re-open it.

**Comment by MariMakes** [comment] 2022-11-10 13:19
To me, it doesn't seem like a bug in Ultimaker Cura, since it's a faulty mesh. 
Apologies for any inconvenience caused by our delayed response. 
I'll be closing this issue. I hope you understand.

**Closed by MariMakes** 2022-11-10 13:19 UTC
Labels: Type: Discussion, Status: Under Investigation
