### ISSUE TITLE
cura show not allow windows to enter sleep

### ISSUE THREAD

**Issue by pabloandresm** [Ultimaker/Cura#7338] opened 2020-03-24 03:24 UTC
When Windows reaches the timeout to go to sleep (energy settings), it sends messages to all applications. Cura should listen to that message and answer to abort sleep mode.

If that happens in the middle of a USB print, then the printer pauses, mid-print, keeps x/y/z nozzle position, bed heated, and nozzle temperature. Print object goes to the bin.

**Comment by Ghostkeeper** [comment] 2020-03-25 10:09
Duplicate of https://github.com/Ultimaker/Cura/issues/4968.

**Closed by Ghostkeeper** 2020-03-25 10:09 UTC
Labels: Type: New Feature
