### ISSUE TITLE
Application UI broken

### ISSUE THREAD

**Issue by rgbmonkey** [Ultimaker/Cura#6045] opened 2019-07-23 02:31 UTC
![image](https://user-images.githubusercontent.com/22285218/61678348-2ecaf380-acc8-11e9-8d06-b3b03ebf74db.png)

**Application Version**

4.1 and 4.2
**Platform**

Windows 10
**Printer**

Ender 3
**Steps to Reproduce**

Every time I launch the app
**Actual Results**

**Expected results**

**Additional Information**

Deleted
C:\Users\123\AppData\Roaming\cura
C:\Users\123\AppData\Local\cura
Same issue

Uninstalled and reinstalled and same issue
installed 4.2 fixed until I closed and reopened.

No plugin installed

**Comment by rburema** [comment] 2019-07-23 07:36
@rgbmonkey Could you maybe attach the logs (`%appdata%/cura/<version>/cura.log`)? Hopefully there are some clues there as to what's going on here.

**Comment by Ghostkeeper** [comment] 2019-07-23 09:10
Duplicate of https://github.com/Ultimaker/Cura/issues/6006. Try updating or reinstalling your graphics drivers.

**Closed by Ghostkeeper** 2019-07-23 09:10 UTC
Labels: Status: Needs Info
