### ISSUE TITLE
Only one plugin will show on the marketplace.

### ISSUE THREAD

**Issue by N0edL** [Ultimaker/Cura#11853] opened 2022-04-21 20:32 UTC
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ender 3 V2

### Issue it self

I clicked on the marketplace and only **Barbarian Units** is there.

_Does Someone else have this or a solution for it._

### Image's

![image](https://user-images.githubusercontent.com/88205753/164547544-ba92c233-1627-4915-ae87-a23f40b7aaf6.png)

![image](https://user-images.githubusercontent.com/88205753/164548145-9d095599-38ef-45fa-9414-bd3f7cb518c8.png)

**Comment by N0edL** [comment] 2022-04-21 20:37
someone?

**Comment by jellespijker** [comment] 2022-04-21 20:55
This Cura version has a major SDK increase. Plugin maintainers have to change and fix their code to ensure their plugin is compatibel with Cura 5.0.

This is because we upgraded from PyQt5 to PyQt6 for our graphical interface

**Comment by nallath** [comment] 2022-04-22 07:40
See also https://github.com/Ultimaker/Cura/issues/11858

**Comment by fvrmr** [comment] 2022-04-25 09:20
Closing this as a duplicate of #11858

**Closed by fvrmr** 2022-04-25 09:20 UTC
Labels: Type: Bug
