### ISSUE TITLE
Generated support is floating in the air

### ISSUE THREAD

**Issue by discharged-spider** [Ultimaker/Cura#4703] opened 2018-10-31 19:30 UTC
**Application Version**
3.5.1

**Platform**
Linux

**Printer**
Creality CR-10

**Steps to Reproduce**
Slice model with selected settings

**Actual Results**
![workspace 1_075](https://user-images.githubusercontent.com/4742057/47813478-46d69d80-dd5c-11e8-90d1-dceffce65c2f.png)

**Expected results**
Generated support should touch model/buildplate

**Additional Information**
[CCR10_Professor_McDuckley_bug.3mf.zip](https://github.com/Ultimaker/Cura/files/2536053/CCR10_Professor_McDuckley_bug.3mf.zip)

**Comment by diegopradogesto** [comment] 2018-11-01 15:38
Yes, I think it's a duplicate. Since the liked issue is a regression, I checked in 3.4.1 and it worked as expected:
**3.4.1**
![image](https://user-images.githubusercontent.com/15830521/47861935-47bb0e00-ddf4-11e8-964d-af7f4a92563e.png)

**Closed** 2018-11-01 15:40 UTC
Labels: Status: Duplicate
