### ISSUE TITLE
Slicing Object as Thin as Layer Height

### ISSUE THREAD

**Issue by zwu513** [Ultimaker/Cura#10721] opened 2021-11-02 01:44 UTC
### Application Version

4.110

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

1. Import very thing file
2. Attempt to slice it

### Actual results

Slicing failed

### Expected results

A single layer of filament 

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Additional information & file uploads

My initial layer height is 0.2mm and the object is also 0.2mm. Changing the object to become 0.21mm thick fixes it and because cura rounds down, it works. 
[Thin.zip](https://github.com/Ultimaker/Cura/files/7457184/Thin.zip)

**Comment by fvrmr** [comment] 2021-11-02 08:25
Hi @zwu513 thank you for your bug report.
This is a duplicate of #10394 and is probably happening because your model is lower than the initial layer height. This is fixed in 4.12 Beta. You can download the beta here: https://github.com/Ultimaker/Cura/releases/tag/4.12-beta

I will close this issue because it is a duplicate.

**Closed by fvrmr** 2021-11-02 08:25 UTC
Labels: Type: Bug
