### ISSUE TITLE
Modify G-Code doesn't work

### ISSUE THREAD

**Issue by punkattack** [Ultimaker/Cura#3695] opened 2018-04-22 03:03 UTC
****

Cura 3.2.1
Modify G-Code doen't wotk (@ Extensions=>Post Processing). 
Check for update either, 9@ Extensions=> Update Checher)

**Comment by fieldOfView** [comment] 2018-04-22 09:46
We need more info:
* What OS do you use?
* What do you mean by "doen't wotk"? Do you mean like in this video? https://www.youtube.com/watch?v=y81V_boWOs0 In that case this is a duplicate of https://github.com/Ultimaker/Cura/issues/3358

**Comment by ianpaschal** [comment] 2018-04-23 07:30
Please fill out the template including steps to reproduce and expected and actual results, or else this issue will have to be closed.

**Closed** 2018-04-25 08:30 UTC
Labels: Status: Needs Info

**Comment by fieldOfView** [comment] 2018-04-25 09:01
As mentioned, this is a duplicate and can be closed
