### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by terrygene1966** [Ultimaker/Cura#9839] opened 2021-05-15 21:48 UTC
### Application Version

4.9.1

### Platform

Windows 10

### Printer

Anycubic i3 Mega

### Reproduction steps

Tried to load a file

### Actual results

Program closes

### Expected results

it should let me choose a file to load into the program

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no

**Comment by fvrmr** [comment] 2021-05-17 07:57
Hi @terrygene1966 I think this is a duplicate of https://github.com/Ultimaker/Cura/issues/9668 
There you can find a work around to solve this. 
Because it is a duplicate I will close this issue.

**Closed by fvrmr** 2021-05-17 07:57 UTC
Labels: Type: Bug
