### ISSUE TITLE
Cura5: Text boxes for GCODE don't support text selection by keyboard anymore

### ISSUE THREAD

**Issue by Triangulix** [Ultimaker/Cura#12420] opened 2022-06-01 14:15 UTC
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Custom

### Reproduction steps

Try to select some text in text boxes like the ones for start and end GCODE by holding shift and pressing the arrow keys.

### Actual results

Nothing happens.

### Expected results

Text selection like in Cura 4 and most other Windows applications.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Nothing to add.

**Comment by nallath** [comment] 2022-06-10 08:46
Duplicate of #12286

**Closed by nallath** 2022-06-10 08:46 UTC
Labels: Type: Bug, Status: Duplicate
