### ISSUE TITLE
Profile Settings are not  fully updated in "Preferences" on change

### ISSUE THREAD

**Issue by NilsRo** [Ultimaker/Cura#7950] opened 2020-06-19 06:20 UTC
**Application version**
4.6.1

**Platform**
Windows 10 X64

**Printer**
Anycubic I3 Mega s

**Reproduction steps**
1. Open Preferences
2. Show Profiles
3. Select another profile with diffrent settings

**Screenshot(s)**
![2020-06-19 08_07_35-AI3M_Razor_Holder_Wide - Ultimaker Cura](https://user-images.githubusercontent.com/51311453/85102627-56db1380-b205-11ea-9d96-32d0018fa1d7.png)

**Actual results**
The settings shown are changed to the selected profile partly. E.g. the layer thickness but some other settings not like the temperatur. 

**Expected results**
Settings of the profile selected should be shown. This make it easier to compare profiles.

**Project file**
-

**Log file**
-

**Additional information**
-

**Comment by nallath** [comment] 2020-06-19 07:28
What do the settings in the extruder tab 1 say (in the preferences window)

**Comment by Ghostkeeper** [comment] 2020-06-26 09:23
The extruder tab is currently empty due to a different bug. I can already tell you that.

**Comment by Ghostkeeper** [comment] 2020-06-26 09:27
Looks like this is a duplicate of https://github.com/Ultimaker/Cura/issues/7626.

We haven't been able to reproduce the issue so far. Or rather, we could reproduce it by loading in a modified configuration folder, but that modification shouldn't be possible through the GUI. We don't know yet how to reproduce the problem from scratch.

**Closed by Ghostkeeper** 2020-06-26 09:27 UTC
Labels: Type: Bug
