### ISSUE TITLE
Simple circular skirt taking 259hrs and off build plate

### ISSUE THREAD

**Issue by sproutdesign** [Ultimaker/Cura#4294] opened 2018-08-28 06:56 UTC
**Application Version**
<Mac 3.4.1>

**Platform**
<Mac OS 10.13.6>

**Printer**
<Ultimaker 3 Extended. Project file IP not shareable>

**Steps to Reproduce**
<changing infill %>

**Actual Results**
<This file would break the printer so we are not printing this>

**Expected results**
<No skirt expected, especially one taking 99% of the build time>

**Additional Information**
< ![screen shot 2018-08-28 at 07 41 38](https://user-images.githubusercontent.com/42764077/44705826-a59b4480-aa97-11e8-886b-d4a81e80f432.jpg)>

**Comment by sproutdesign** [comment] 2018-08-28 06:57
Just in case this demonstrates that the travels off the build plate are arbitary:
![screen shot 2018-08-28 at 07 47 07](https://user-images.githubusercontent.com/42764077/44705962-04f95480-aa98-11e8-8ef3-c95348e0a585.jpg)

**Comment by diegopradogesto** [comment] 2018-08-31 07:35
Duplicate of https://github.com/Ultimaker/Cura/issues/4009

This is fixed in the next release! Thanks for reporting.

**Closed by diegopradogesto** 2018-08-31 07:35 UTC
