### ISSUE TITLE
bug in thr box settings

### ISSUE THREAD

**Issue by kak121** [Ultimaker/Cura#9881] opened 2021-05-20 15:29 UTC
### Application Version

4.9.1

### Platform

windws 10

### Printer

CR-10 S PRO 

### Reproduction steps

![bug 2](https://user-images.githubusercontent.com/64870886/119006484-18ac1e00-b999-11eb-9ed3-385a29194277.png)

### Actual results

![Uploading bug 2.png…]()

### Expected results

no glich in the boxes settings 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

![bug 2](https://user-images.githubusercontent.com/64870886/119006665-3d07fa80-b999-11eb-847c-c2c1d2da484c.png)

look in the settings boxes

**Comment by kak121** [comment] 2021-05-20 15:34
I hope that the problem was not from me 

please tell me 

I appresiate to fed me bake abuot thes issue 

think you

**Comment by kak121** [comment] 2021-05-20 16:01
hi 

ammmm I think I now way thes happened maybe because my computer language is (Arabic).Arebic wrote from right to left

**Comment by kak121** [comment] 2021-05-20 16:39
It is indeed the problem (Computer language Arabic), I changed it to English and it all Looks good. 

Please fix it

**Comment by fvrmr** [comment] 2021-05-21 08:51
Hi @kak121 thank you for your report.
This is indeed happening because of the compute language. 
It is a duplicate of https://github.com/Ultimaker/Cura/issues/9667 that's why I will close this issue. 
We have a ticket on the backlog for this issue.

**Closed by fvrmr** 2021-05-21 08:51 UTC
Labels: Type: Bug
