### ISSUE TITLE
Cura not Booting

### ISSUE THREAD

**Issue by markbot2000** [Ultimaker/Cura#9970] opened 2021-06-12 02:35 UTC
### Application Version

4.9.1

### Platform

Windows 10

### Printer

Creality Ender 3

### Reproduction steps

1. Opened Cura

### Actual results

Cura freezes on "Initializing build volume" on boot

### Expected results

Cura should load

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[cura.zip](https://github.com/Ultimaker/Cura/files/6641534/cura.zip)
Log File

Screenshots
![image](https://user-images.githubusercontent.com/59100265/121762639-e5266480-cafc-11eb-9068-fe464593f114.png)
![image](https://user-images.githubusercontent.com/59100265/121762649-f53e4400-cafc-11eb-8972-675f6aef9dc5.png)

**Comment by markbot2000** [comment] 2021-06-12 03:27
[Traceback.zip](https://github.com/Ultimaker/Cura/files/6641589/Traceback.zip)
Traceback file

**Comment by fieldOfView** [comment] 2021-06-12 06:37
This crash seems to be caused by you having logged in to an Ultimaker account before, and now Cura not being able to contact the ultimaker server to confirm your account status. That bug has been fixed for the next release of Cura (https://github.com/Ultimaker/Cura/pull/9903).

To solve it for you, either make sure the computer that runs Cura is connected to the internet, or:
* open `%APPDATA%\cura\4.9\cura.cfg` in a texteditor (notepad will do)
* remove the line that starts with `ultimaker_auth_data =`
* save the file and restart Cura

This will log you out of your Ultimaker account, but that will not affect the functionality of Cura much.

**Comment by fieldOfView** [comment] 2021-06-12 06:37
Duplicate of https://github.com/Ultimaker/Cura/issues/9847

**Comment by fvrmr** [comment] 2021-06-14 07:20
Closing this issue since it is a duplicate of #9847

**Closed by fvrmr** 2021-06-14 07:20 UTC
Labels: Type: Bug
