### ISSUE TITLE
Sometimes never starts slicing

### ISSUE THREAD

**Issue by Tupptupp** [Ultimaker/Cura#813] opened 2016-06-18 21:58 UTC
particularly after placing multiple objects on the bed to print, cura does not start slicing and I have to restart the program and place all the objects all over again.

**Comment by Ghostkeeper** [comment] 2016-06-20 08:44
It gets stuck on "Preparing to print..."?

**Comment by Tupptupp** [comment] 2016-06-20 19:49
Yes exactly. If
I bring a new part in then delete it it will sometimes slice correctly.
On Jun 20, 2016 1:44 AM, "Ghostkeeper" <notifications@github.com> wrote:

It gets stuck on "Preparing to print..."?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ultimaker/Cura/issues/813#issuecomment-227083364>, or mute
the thread
<https://github.com/notifications/unsubscribe/AI3EIJMGvuuTA8PsBTWhNd8rXk9HB7F4ks5qNlLngaJpZM4I5Cri>
.

**Comment by Ghostkeeper** [comment] 2016-06-21 08:32
I'm going to mark this as a duplicate of https://github.com/Ultimaker/Cura/issues/794 then :smile:

**Closed** 2016-06-21 08:32 UTC
Labels: bug, duplicate
