### ISSUE TITLE
Abort print in Cura shuts down the hotend heater long before Cura stops movement and extrusion.

### ISSUE THREAD

**Issue by Larry4911** [Ultimaker/Cura#16903] opened 2023-10-06 16:55 UTC
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

RepRap Prusa i3 + dual into 1 hotend

### Reproduction steps

Start a print. When it is into the print anywhere, stop the print in Cura. Watch the temperature of your hotend plummet and your extruder and axis keep moving.  

### Actual results

The filament in my hotend gets squashed because it is no longer at the melting point and blocks my hotend up.

### Expected results

Stop all motion and purge the buffer before Cura shuts down the heater/s!

### Add your .zip and screenshots here ⬇️

[log.zip](https://github.com/Ultimaker/Cura/files/12833520/log.zip)

**Comment by GregValiant** [comment] 2023-10-06 17:15
Thanks for the report.
It is intended behavior that the hot end and bed are shut off when a print is aborted so this isn't a bug.  Exactly when the hot end and bed are shut off is a function of the size of the planner buffer in the printer which Cura has no way to know. 
The relevant lines appear to be in "USBPrinterOutputDevice.py".

I'll go ahead and close this and remove the bug label.  You may wish to make this a feature request to change the current behavior.

**Closed by GregValiant** 2023-10-06 17:15 UTC
Labels: Type: Discussion, Status: Under Investigation
