### ISSUE TITLE
Dialog 'open file' without function

### ISSUE THREAD

**Issue by betterwithage** [Ultimaker/Cura#13470] opened 2022-10-04 07:38 UTC
### Application Version

5.2.0-beta

### Platform

Debian Linux 11.5

### Printer

Renkforce RF100 XL

### Reproduction steps

Open a file per button, no reaction.
Open a file per menue, no reaction
Close cura and load file per commandline cura <file> is functioning.
Inspect the logfile and found and error:
_"CuraEngine: error while loading shared libraries: libfmt.so.9: cannot open shared object file: No such file or directory"_
Another error uccured on <STDERR>:
_'Cyclic dependency detected between "file:///tmp/.mount_curalc9Elw/share/cura/resources/qml/Actions.qml" and "file:///tmp/.mount_curalc9Elw/share/cura/resources/qml/Actions.qml" '_

I found on my  Debian 64 installation the version libfmt.so.7.1.3

### Actual results

load a file at commandline possible only

### Expected results

please repair the open dialog ;-)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

2022-10-01 15:27:56,844 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin CuraEngineBackend 1.0.1
2022-10-01 15:27:56,859 - DEBUG - [MainThread] UM.Backend.Backend._logSocketState [192]: Socket state changed to Listening
2022-10-01 15:27:56,870 - INFO - [MainThread] UM.Backend.Backend.startEngine [95]: Started engine process: /tmp/.mount_Ultimal4L0bW/CuraEngine
2022-10-01 15:27:56,873 - DEBUG - [MainThread] UM.Backend.Backend._backendLog [115]: [Backend] Calling engine with: ['/tmp/.mount_Ultimal4L0bW/CuraEngine', 'connect', '127.0.0.1:49674', '']
2022-10-01 15:27:56,875 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [115]: [Backend] /tmp/.mount_Ultimal4L0bW/CuraEngine: error while loading shared libraries: libfmt.so.9: cannot open shared object file: No such file or directory

**Comment by MariMakes** [comment] 2022-10-04 10:11
Hey @betterwithage,

Thanks for your report 👍 
It looks familiar. 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13422
We have our team working hard on a solution. 😤 
Sorry for any inconvenience 😞 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/13422

**Closed by MariMakes** 2022-10-04 10:11 UTC
Labels: Type: Bug, Status: Triage
