### ISSUE TITLE
2 Color Frog IDEX slicing failure

### ISSUE THREAD

**Issue by drewmoseley** [Ultimaker/Cura#17676] opened 2023-12-16 22:18 UTC
### Cura Version

5.6.0

### Operating System

Linux

### Printer

Sovol SV04 Dual Mode

### Describe model location

Bed Center

### Describe your model

2 Color Tree Frog

### Add your .zip here ⬇️

[2color_treefrog_small_solid.zip](https://github.com/Ultimaker/Cura/files/13694114/2color_treefrog_small_solid.zip)

**Comment by 5axes** [comment] 2023-12-17 21:58
AN other "Print Thin Walls" Issue: https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-7790452

 .. on extruder 1 

![image](https://github.com/Ultimaker/Cura/assets/11015345/b1133e48-2e0d-46f3-9368-26cedd7bafa5)

**Comment by MariMakes** [comment] 2024-01-18 15:24
Hi @drewmoseley,

Quick update from our side 👋
We are introducing a new tool to analyze slicing crashes like the one you reported. 💪

Even with the changes we made in the latest versions of Cura we still see that your model crashes. 🫤 But we have added your project file to our analyzing tool and found there were at least 8 crashes that were similar to yours, which helps us to narrow down what the cause is of your crash so we can resolve this for you and others.

Hopefully, we can find a solution soon 🤞

**Comment by HellAholic** [comment] 2024-02-16 09:24
Small update,
Issue is resolved in CURA-11570 and will be part of the next Cura release.

**Closed by HellAholic** 2024-02-16 09:24 UTC
Labels: Type: Bug, Status:  On Backlog, Slicing Error :collision:

**Comment by HellAholic** [comment] 2024-04-03 13:01
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
