### ISSUE TITLE
Backspace don´t delete object

### ISSUE THREAD

**Issue by gomakekit** [Ultimaker/Cura#8282] opened 2020-08-31 16:32 UTC
**Application version**
(The version of the application this issue occurs with.)
Cura 4.7

**Platform**
Mac OS Catalina 10.15.6
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)

**Printer**

Ender 5
**Reproduction steps**

Import any object, press backspace, nothing happens. 

Additional info: There is no delete button on portable macs or smaller keyboard. 

**Screenshot(s)**

**Actual results**
Nothing happens

**Expected results**
Object should be deleted

**Project file**
Any object

**Log file**

**Additional information**
Yes, you can press fn+backspace, but this is not optimal. Suggestion: include backspace for allowing to dele objects

**Comment by nallath** [comment] 2020-09-01 08:17
The odd thing is that we have fixed this a few times over. The last time was in this issue: https://github.com/Ultimaker/Cura/issues/7754

**Comment by Ghostkeeper** [comment] 2020-09-07 11:23
Both of our QA engineers tried this on their Macs and couldn't reproduce the issue. Maybe it happens only on certain types of keyboards? What keyboard are you using?

Maybe we'll be able to tell more if there are more users with this problem.

**Comment by gomakekit** [comment] 2020-09-21 13:10
Hi. It´s the standard keyboard on a macbook pro 13-inch, 2017, macOS Catalina 10.15.6. I have now tested with the latest version of Cura and now the the delete works just fine! Thank you!

**Comment by konskarm** [comment] 2020-09-21 13:18
Perfect! I am closing this again then.

**Closed by konskarm** 2020-09-21 13:18 UTC
Labels: Platform: MacOS, Type: Bug
