### ISSUE TITLE
Cura 5.2.1 crashing when sending sliced print to Octopi

### ISSUE THREAD

**Issue by TripleKiller666** [Ultimaker/Cura#14037] opened 2022-12-13 14:52 UTC
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Artillery Sidewinder x1

### Reproduction steps

Whenever I try to upload a Sliced File via OctoPrint, the Program crashes with error Logs and Tracelogs.
See the logs below for more info.

### Actual results

```
Traceback (most recent call last):
  File "C:\Users\mIpne\AppData\Roaming\cura\5.2\plugins\OctoPrintPlugin\OctoPrintPlugin\UploadOptions.py", line 73, in acceptOptionsDialog
    self._proceed_callback()
  File "C:\Users\mIpne\AppData\Roaming\cura\5.2\plugins\OctoPrintPlugin\OctoPrintPlugin\OctoPrintOutputDevice.py", line 581, in proceedRequestWrite
    if not gcode_writer.write(self._gcode_stream, None):
  File "cura\Utils\Threading.py", line 31, in _call_on_qt_thread_wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Ultimaker Cura 5.2.1\share\cura\plugins\UFPWriter\UFPWriter.py", line 88, in write
    json.dump(self._getSliceMetadata(), setting_textio, separators=(", ", ": "), indent=4)
  File "json\__init__.py", line 179, in dump
  File "json\encoder.py", line 431, in _iterencode
  File "json\encoder.py", line 405, in _iterencode_dict
  File "json\encoder.py", line 405, in _iterencode_dict
  File "json\encoder.py", line 405, in _iterencode_dict
  File "json\encoder.py", line 438, in _iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type SettingFunction is not JSON serializable
```

```
Thread 0x00001da0 (most recent call first):
  File "C:\Users\mIpne\AppData\Roaming\cura\5.2\plugins\OctoPrintPlugin\OctoPrintPlugin\python-zeroconf\zeroconf\_services\browser.py", line 530 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000061ac (most recent call first):
  File "asyncio\windows_events.py", line 788 in _poll
  File "asyncio\windows_events.py", line 439 in select
  File "asyncio\base_events.py", line 1860 in _run_once
  File "asyncio\base_events.py", line 600 in run_forever
  File "asyncio\windows_events.py", line 321 in run_forever
  File "C:\Users\mIpne\AppData\Roaming\cura\5.2\plugins\OctoPrintPlugin\OctoPrintPlugin\python-zeroconf\zeroconf\_core.py", line 494 in _run_loop
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000006c4 (most recent call first):
  File "C:\Program Files\Ultimaker Cura 5.2.1\share\cura\plugins\USBPrinting\USBPrinterOutputDeviceManager.py", line 88 in _updateThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00004eb4 (most recent call first):
  File "threading.py", line 324 in wait
  File "zeroconf\__init__.py", line 2534 in wait
  File "zeroconf\__init__.py", line 1715 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000063c8 (most recent call first):
  File "threading.py", line 324 in wait
  File "threading.py", line 600 in wait
  File "C:\Program Files\Ultimaker Cura 5.2.1\share\cura\plugins\UM3NetworkPrinting\src\Network\ZeroConfClient.py", line 81 in _handleOnServiceChangedRequests
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00001fd8 (most recent call first):
  File "zeroconf\__init__.py", line 1369 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00002de8 (most recent call first):
  File "C:\Program Files\Ultimaker Cura 5.2.1\share\cura\plugins\RemovableDriveOutputDevice\RemovableDrivePlugin.py", line 61 in _updateThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00006560 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000039e8 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00004c34 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x0000679c (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00005978 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00000f08 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000020cc (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000055fc (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000030ec (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000043d4 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00005a58 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00006328 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00004ee4 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00001e6c (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00000c0c (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00004848 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Current thread 0x00004444 (most recent call first):
  File "cura\CrashHandler.py", line 397 in _logInfoWidget
  File "cura\CrashHandler.py", line 182 in _createDialog
  File "cura\CrashHandler.py", line 86 in __init__
  File "cura_app.py", line 165 in exceptHook
  File "UM\Qt\QtApplication.py", line 416 in exec
  File "cura\CuraApplication.py", line 897 in run
  File "cura_app.py", line 239 in <module>
```

### Expected results

The Program should just upload the code like it always did.
The Plugin Creator mentioned here: [OctoPrintPlugin Issues](https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues/303)
That it´s a problem he cant fix himself, and that it would rather be a Cura problem (hence why I post this Bug Report here)
Also see Reddit Thread with same Error Message here:[Cura 5.2.1 crashing when sending Sliced Print to Octopi](https://www.reddit.com/r/Cura/comments/yx72o3/cura_521_crashing_when_sending_sliced_print_to/)

I hope you guys can figure something out together, since it worked pretty flawless all these Months prior.
And it would be a shame to lose such an amazing functionality.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[Cura-Log-and-ProjectFile.zip](https://github.com/Ultimaker/Cura/files/10219067/Cura-Log-and-ProjectFile.zip)

Should be everything you wanted, hope it helps you guys.

**Comment by MariMakes** [comment] 2022-12-13 15:09
Hey @TripleKiller666,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13675
We have a ticket on our backlog with the intent to improve this behavior soon.

Did you try disabling the UFP writer, here? 
![image](https://user-images.githubusercontent.com/40423138/207370060-846a2935-e7f3-490c-9ebe-1f9a2d48da36.png)

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/13675

**Closed by MariMakes** 2022-12-13 15:09 UTC
Labels: Type: Bug, Status: Triage
