### ISSUE TITLE
Nozzle Diameter does not change 

### ISSUE THREAD

**Issue by BunnyTJ** [Ultimaker/Cura#6546] opened 2019-10-16 18:54 UTC
I have changed the nozzle on my Printer but for some reason, CURA does not keep my changed nozzle diameter in the settings. Can someone help me please?

**Comment by nallath** [comment] 2019-10-17 07:37
Please use the bug template to report issues. We would like to have things like reproduction steps. How did you change the nozzle size? What do the logs say if you try to do this?

**Comment by Ghostkeeper** [comment] 2019-10-17 15:20
Also the version in particular. We've had this issue in the past and have so far claimed that it's fixed in the newest version.

**Comment by Alex20129** [comment] 2019-10-19 01:23
Confirmed for Cura 4.3.0 (custom FFF printer)
Monitor->Manage printers->Machine settings->Extruder 1
i try to change "compatible material diameter" but setting always dropping to default "2.85mm"

**Comment by BunnyTJ** [comment] 2019-10-19 15:05
I am using Cura 4.3.0 and my diameter keeps jumping back to 0.4.

I am using the Tevo Tornado Profile for my Tevo Tornado Printer. I went into Settings - Printer - Manage Printers... Machine Settings and then I clicked on Extruder 1 and changed Nozzle Size. But as I Ieave and go back in it jumps back to 0.4.

**Comment by Alex20129** [comment] 2019-10-19 17:49
Additional information: Cura 4.3.0 appimage, OS - Ubuntu 17.10
I think, the reason is that i'm using the "4.3.0 appimage" after "3.6.0 appimage". Maybe i should clean up some files or folders before using the new Appimage.

**Comment by Ghostkeeper** [comment] 2019-10-21 09:45
I did the same thing with the 4.3.0 AppImage file but it didn't reproduce for me. Here is a recording. (I had to blur out the networked printer list because there are printers there with names that reveal Ultimaker's secrets.)

http://dulek.net/work/compatible_diameter.mp4

**Comment by BunnyTJ** [comment] 2019-10-21 15:52
Hi. This I have done but it keeps jumping back to 0.4 Nozzle size

**Comment by jfima** [comment] 2019-10-25 12:22
The same issue Cura 4.3.0 Windows. I can't change nozzle diameter. Preferences->Printers->(Custom Deltabot)->Extruder 1->Nozzle Size 
I want to change from 0.5 to 0.4 and it does not work.

**Comment by fieldOfView** [comment] 2019-10-25 12:34
@jfima: As a test, can you change it to 0.401?

**Comment by jfima** [comment] 2019-10-25 12:41
> @jfima: As a test, can you change it to 0.401?

I checked as you ask. It does not work too. 0.401 0.501 can't save this value

**Comment by Ghostkeeper** [comment] 2019-10-25 12:50
Because that issue was fixed back in August. This report is that the issue is back again (though we haven't been able to reproduce the bug yet on this end).

**Comment by ssavickiy** [comment] 2019-10-25 15:19
the exact same problem #6505

**Comment by ssavickiy** [comment] 2019-10-25 15:20
try using "," or "when entering a value."

**Comment by BorgMcz** [comment] 2019-10-25 19:05
I have the same problem, the board helped change "0.5" to "0,5". The program will correct the "," to "." character after closing the window.  And also saves the correct value and remembers it.

**Comment by Alex20129** [comment] 2019-10-26 08:14
I checked it in "Cura 4.2.1" twice:
*Normal installation under Windows 10
*AppImage under Ubuntu 17.10
In both cases works normally, setting stored. The problem appears in "Cura 4.3.0" only.

**Comment by peterpoetzi** [comment] 2019-10-26 20:21
I can confirm that entering 0.4 does not save while 0,4 does. I am using Cura 4.3.0 under Windows 10, set to German.

**Comment by Ghostkeeper** [comment] 2019-10-28 16:08
That explains why we weren't able to reproduce it. We have been testing with an English locale. Good analysis!

I'll put this up for discussion with the team tomorrow.

**Comment by BorgMcz** [comment] 2019-10-28 17:35
Hello, Windows 7, Cura 4.3.0, english. The same problem. 
Previous version 4.2.1 to it update 4.3.0

**Comment by jabss** [comment] 2020-01-28 10:21
Hi,

Same behaviour in Cura for windows 4.4.1.
Workaround of using comma "," instead of dot "." worked.
Anyoing bug. Please fix.

BR

**Comment by Ghostkeeper** [comment] 2020-01-30 13:31
This is currently in our backlog, by the way.

**Comment by AlexTriada** [comment] 2020-03-03 12:59
4.5.0 - same bug, w10pro

**Comment by martan223** [comment] 2020-03-11 21:54
can confirm - 4.5.0 still here

**Comment by Phoquounet** [comment] 2020-03-14 01:17
Same issue with Cura 4.5, French language, win10 and with two diferents printers profils : alfawise u20 and alfawise u30.

**Comment by Phoquounet** [comment] 2020-03-14 01:24
I try to change nozzle size with the value « 0 » 
That work (but cura can’t slice, normal) and after I write 0.3 and now cura save it correctly... weird bug

**Comment by sergeolkhovik** [comment] 2020-04-09 07:05
Confirming, I have Ukrainian locale on Windows 7 x64, and I had to type "0,5" (comma is decimal separator in UA locale) and it accepted and **saved** the value.

**Comment by NikWas** [comment] 2020-04-25 19:49
Cura 4.6, issue still there. Windows 10, Russian locale, typing the value with comma instead of the dot works.

**Comment by mituritsyn** [comment] 2020-05-15 20:48
4.6.1 Same issue with the filament diameter
Ubuntu 18.04 Russian and English locales.
By deafult it is 2.85 (with dot). Was trying to change to 1.75 or 1,75 - no difference afrer closing it is dropped to 2.85

**Comment by Phoquounet** [comment] 2020-05-15 21:40
> 4.6.1 Same issue with the filament diameter
> Ubuntu 18.04 Russian and English locales.
> By deafult it is 2.85 (with dot). Was trying to change to 1.75 or 1,75 - no difference afrer closing it is dropped to 2.85

Try to write « 3 » and save. 
After, write « 1.75 » and save 

It’s worked for me.

**Comment by Chrissps** [comment] 2020-06-11 12:47
> try using "," or "."when entering a value.

You are my hero 👍

**Comment by OverWorldD** [comment] 2020-10-05 10:18
Same problem still exists in 4.7.1
Obviously it has to do with locale settings for using . or , as decimal separator. My region is set to Swedish(Finland), and my win10 display language is english. Changing from . to , in nozzle settings worked. Annoying bug. Hope it can be fixed.

**Comment by mituritsyn** [comment] 2020-10-05 10:19
> Same problem still exists in 4.7.1
> Obviously it has to do with locale settings for using . or , as decimal separator. My region is set to Swedish(Finland), and my win10 display language is english. Changing from . to , in nozzle settings worked. Annoying bug. Hope it can be fixed.

Seems fixed on Linux systems

**Comment by Ghostkeeper** [comment] 2020-10-06 13:44
> Seems fixed on Linux systems

We didn't change anything here, not on purpose anyway, so I think you may just have different region settings now.

**Comment by mituritsyn** [comment] 2020-10-06 16:39
> > Seems fixed on Linux systems
> 
> We didn't change anything here, not on purpose anyway, so I think you may just have different region settings now.

but it definetely behave differently. invalid value cannot be entered

**Comment by Oximom** [comment] 2020-11-05 09:14
Cura 4.7, win10 same problem. Fixed with changing nozzle diameter to 0 first, save and then set 0,8. It works.

**Comment by spawnrider** [comment] 2020-11-15 14:25
Hi,
Same issue in Cura 4.8.0.
you need to use ',' (tip 0,6 with a comma) to set the nozzle size to 0.6. 
If you tip 0.6 it will not be saved :(

**Closed** 2021-01-19 08:49 UTC

**Comment by nallath** [comment] 2021-01-19 09:02
I just merged the fix from fieldOfView, so this is fixed for the next release. Thanks for your patience (and thanks to FieldOfView for fixing it!)
