### ISSUE TITLE
4.9.1 crash after opening file

### ISSUE THREAD

**Issue by kanawati975** [Ultimaker/Cura#9821] opened 2021-05-13 09:54 UTC
### Application Version

4.9.1

### Platform

Windows 10 

### Printer

DIY

### Reproduction steps

I uninstalled 4.9.0 completely and installed the new 4.9.1

### Actual results

When I go to File > Open File(s) Cura 4.9 hangs for a second and then crashes.

### Expected results

But if I drag the file from other window it works fine without crashing

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/6471728/cura.log)

**Comment by coolgua888** [comment] 2021-05-14 03:10
me too

**Comment by fvrmr** [comment] 2021-05-14 12:01
Hi @kanawati975 thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9668
There you can also find a work around to solve this issue. 
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-05-14 12:01 UTC
Labels: Type: Bug
