### ISSUE TITLE
Strange shapes appear in sliced model on certain layer heights

### ISSUE THREAD

**Issue by KenjiTakahashi** [Ultimaker/Cura#10158] opened 2021-07-19 23:43 UTC
### Application Version

4.10.0

### Platform

Archlinux

### Printer

Ender 3

### Reproduction steps

Just slicing as usual :-). And getting very strange triangular shapes appearing at certain layer height settings. See screenshots below.

### Actual results

Project 1 sliced result:
![slice1](https://user-images.githubusercontent.com/431488/126240945-c662ab95-fa7e-4c01-ab82-9595bf43ce8f.png)
Project 2 sliced result:
![slice2](https://user-images.githubusercontent.com/431488/126240977-ba9edb12-b790-44a2-b493-f7845810cda3.png)

### Expected results

The sliced models to be like the actual models, without artifacts inside.
Project 1 model:
![model1](https://user-images.githubusercontent.com/431488/126241002-b2226e08-e650-4cd7-b549-62699093adda.png)
Project 2 model:
![model2](https://user-images.githubusercontent.com/431488/126241010-a54ddd08-683f-4d5c-8ca2-253965ff1e6a.png)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

First project files: [wth.zip](https://github.com/Ultimaker/Cura/files/6844413/wth.zip) (fails at `0.2`, works at other heights like `.0.16`, `0.24`, etc.).
Second project files: [wth2.zip](https://github.com/Ultimaker/Cura/files/6844433/wth2.zip) (fails at `0.16` and `0.2`, seems to work at higher values).

**Comment by nallath** [comment] 2021-07-20 08:37
I think this might be a duplicate of https://github.com/Ultimaker/Cura/issues/9979

**Comment by fvrmr** [comment] 2021-07-20 09:47
I will close this issue since it is indeed a duplicate as mentioned above. Please continue the thread there, so we keep everything in one place.

**Closed by fvrmr** 2021-07-20 09:47 UTC
Labels: Type: Bug
