### ISSUE TITLE
Bug report in Cura

### ISSUE THREAD

**Issue by DCnation25** [Ultimaker/Cura#14376] opened 2023-01-24 22:13 UTC
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Creality Ender 3 S1 Pro

### Reproduction steps

I out in an stl file to slicer, pressed the "slice button", and it didn't finish slicing as it was interupted by a bug to report.

### Actual results

I cannot slice any more files

### Expected results

The part should've sliced

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

N/A

**Comment by MariMakes** [comment] 2023-02-03 13:11
Hey @DCnation25,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Is it possible that your printjob is located at 0, 0, 0, and it slices if you move it a little away from the center of the buildplate? 
Then it might be a duplicate of https://github.com/Ultimaker/Cura/issues/13643

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Closed** 2023-02-18 00:18 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage, Slicing Error :collision:
