### ISSUE TITLE
[3.5] Layer position

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#4528] opened 2018-10-09 19:22 UTC
**Application Version**
3.5

**Platform**
Windows 10 x64

**Printer**
Cr-10s

**Steps to Reproduce**
Import a cube, use 1 perimeter, no top and bottom layer, no infill

**Actual Results**
A layer is done in a wrong position/order

**Expected results**
A cube should be done

**Additional Information**
[Video](https://youtu.be/CLpRpBeQejY)
[CCR10S_Calibration_Cube.zip](https://github.com/Ultimaker/Cura/files/2461882/CCR10S_Calibration_Cube.zip)

**Comment by smartavionics** [comment] 2018-10-10 06:38
Please save the gcode and either rename to .txt or zip it up and attach to this issue, thanks.

**Comment by fieldOfView** [comment] 2018-10-10 06:56
Unless it is easily reproducable, this looks like a duplicate of https://github.com/Ultimaker/Cura/issues/3815 (which means it is a visualisation issue that does not affect the gcode)

**Comment by Liger0** [comment] 2018-10-10 11:44
I can easily reproduce it.
[CCR10S_Calibration_Cube new gc.zip](https://github.com/Ultimaker/Cura/files/2464489/CCR10S_Calibration_Cube.new.gc.zip)
[CCR10S_Calibration_Cube new project.zip](https://github.com/Ultimaker/Cura/files/2464490/CCR10S_Calibration_Cube.new.project.zip)

**Comment by smartavionics** [comment] 2018-10-10 20:21
Turn off Cooling -> Lift Head.

![screenshot_2018-10-10_21-20-13](https://user-images.githubusercontent.com/585618/46763672-5ff6ac00-ccd2-11e8-902f-9d3f731ca69f.png)

**Comment by Liger0** [comment] 2018-10-10 21:18
> 
> 
> Turn off Cooling -> Lift Head.
> 
> ![screenshot_2018-10-10_21-20-13](https://user-images.githubusercontent.com/585618/46763672-5ff6ac00-ccd2-11e8-902f-9d3f731ca69f.png)

So.. is this a temporary workaround or will it be fixed.

**Comment by smartavionics** [comment] 2018-10-10 21:31
Fixed? Isn't that the expected behaviour when the Lift Head option is enabled? At the end of each layer the nozzle is moved away, movement paused, and then moved back again to start the next layer.

**Comment by Liger0** [comment] 2018-10-10 21:45
> 
> 
> Fixed? Isn't that the expected behaviour when the Lift Head option is enabled? At the end of each layer the nozzle is moved away, movement paused, and then moved back again to start the next layer.

Uhm... The topic is not about that...?

**Comment by smartavionics** [comment] 2018-10-10 21:46
OK, well I don't know what you're talking about then. Sorry, bye.

**Comment by Liger0** [comment] 2018-10-10 22:38
@fieldOfView understood it. It is very clear in the video, it is just a misplaced layer.

**Comment by fieldOfView** [comment] 2018-10-11 12:30
However, @fieldOfView can't reproduce it, neither by following your steps, nor by opening your project file.@Liger0, are you saying that this always happens to you, even when you slice again (eg by moving the model to a slightly different location, or by changing a setting)? To me this still looks like the same thing as reported in #3815

**Comment by Liger0** [comment] 2018-10-11 14:00
> 
> 
> However, @fieldOfView can't reproduce it, neither by following your steps, nor by opening your project file.@Liger0, are you saying that this always happens to you, even when you slice again (eg by moving the model to a slightly different location, or by changing a setting)? To me this still looks like the same thing as reported in #3815

It happens to me very frequently. I just noticed is acts in a strange way. If I don't touch the profile, I can even close cura and do what I want, reopen and I will have the same bug again. If I restart my PC, I won't have it but if I tweak some random settings like the skirt/brim, it will occur again and will only disappear restarting the PC.

**Comment by Ghostkeeper** [comment] 2019-05-28 15:36
Indeed this looks like a duplicate of #3815. However since that issue was closed, please continue the conversation here: #5788.

**Closed by Ghostkeeper** 2019-05-28 15:36 UTC
