### ISSUE TITLE
Support Line and Brim Bug

### ISSUE THREAD

**Issue by MaxThroughput** [Ultimaker/Cura#10864] opened 2021-11-17 18:01 UTC
### Application Version

4.12

### Platform

Windows 10

### Printer

Creality Ender 3 Pro

### Reproduction steps

Generate Support - Yes
Support Pattern - Lines
Support Wall Line Count - 0
Connect Support Lines - No
Enable Support Brim - No
Limit Support Retractions - No

### Actual results

Support brim grid is displayed in cura preview and prints accordingly. There should be no brim printed when disabled.
Line supports appear correctly disjointed in preview. However, when printing the line supports are connected. When the model is sliced with Connect Support Lines - Yes, the preview matches how the printer prints when Connect Support Lines - No.

### Expected results

Lines should be disjointed. Support brim should not be present

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[blank.txt](https://github.com/Ultimaker/Cura/files/7556881/blank.txt)

**Comment by MaxThroughput** [comment] 2021-11-17 18:04
<img width="1134" alt="support-issues" src="https://user-images.githubusercontent.com/36289112/142256915-908849be-1371-47db-bfb4-242b244cb0b4.PNG">

**Comment by MaxThroughput** [comment] 2021-11-17 23:29
Solution:

This behavior was not the result of a bug, but a misconfiguration. In the attached screenshot you can see the blue travel path differentiated from the yellow material. The connections were the result of retractions not occurring in the travel path between support lines. The support density setting is 1.14mm, while the Retraction Minimum Travel value was 1.5mm. When Retraction Minimum Travel < Support Density Line Distance, retractions occur and the result is a disconnected line support pattern.
<img width="1527" alt="support-travel" src="https://user-images.githubusercontent.com/36289112/142298680-67ac76f1-c53b-42f6-99f9-44122f098a41.PNG">
e

**Comment by fvrmr** [comment] 2021-11-23 13:55
Hi @MaxThroughput thank you for your report. 
These lines are not the brim but the grid for the support. Good to know that you've found the solution. 
I will close this issue since your part is solved and the brim part is not a bug but expected. 
But let me know if you have more questions.

**Closed by fvrmr** 2021-11-23 13:55 UTC
Labels: Type: Bug
