### ISSUE TITLE
Cura crash on startup with multi monitors

### ISSUE THREAD

**Issue by Earthinheritor** [Ultimaker/Cura#13291] opened 2022-09-14 17:44 UTC
### Application Version

5.0.0

### Platform

Windows 11

### Printer

Ender 3 V2 EE XL 400

### Reproduction steps

Nvidia Drivers for a EVGA 3080 GPU.
2 Monitors
Start Cura
Splash screen comes up
Grey outline of software appears but no interface and shows as unresponsive indefinatly. 

Soon as i disabled my second monitor the software performs as expected, no crashs.

### Actual results

Full crash, unresponsive grey block window

### Expected results

Cura 5.0 starts as normal even with multi-monitor setups. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I have asked on reddit about this and some people had no issues with multi monitors. So might be an Nviidia driver conflict or specific to this GPUs multi monitors. All other software works as expected. Issue is isolated strickly to Cura 5.0
Before 5.0 software performed as expected.

**Comment by MariMakes** [comment] 2022-09-23 15:22
Hey @Earthinheritor,

Thanks for your report. 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12197
There you can also find a workaround that might be related where you'll have to disable your Nahemic driver. 
We have a ticket on our backlog with the intent to improve this behavior.
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12197

**Closed by MariMakes** 2022-09-23 15:22 UTC
Labels: Type: Bug, Status: Triage
