### ISSUE TITLE
Cura 5.1.0 fails to slice in vase mode

### ISSUE THREAD

**Issue by f-engel-hrs** [Ultimaker/Cura#12814] opened 2022-07-20 19:56 UTC
### Application Version

5.1.0

### Platform

Windoes 11

### Printer

Creality Ender 3

### Reproduction steps

1. Load this STL in Cura: https://media.printables.com/media/prints/34332/stls/339390_b754e881-b09d-4de1-b7bb-c3c5e5adaf7c/9-sided-twist-planter.stl
2. Enable Spiralize Outer Contour
3. Slice and look at the preview

### Actual results

There are strange travel path that mess up the whole object. Also it seems like the nozzle travels around each layer twice

### Expected results

Vase mode prints work just fine (compare screenshots from Cura 4.13.0)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[CE3_9-sided-twist-planter_PETG_03.zip](https://github.com/Ultimaker/Cura/files/9154065/CE3_9-sided-twist-planter_PETG_03.zip)
![image](https://user-images.githubusercontent.com/33716204/180070018-a41d2967-d183-4541-92ac-9ba2d15fc6cd.png)
![image](https://user-images.githubusercontent.com/33716204/180070090-0fea46c6-7d7f-4e33-8471-62449a04e40e.png)

Cura 4.13.0 with the same model:
![image](https://user-images.githubusercontent.com/33716204/180070181-2fafefe4-a820-426c-8afe-9aaff683d6f6.png)
![image](https://user-images.githubusercontent.com/33716204/180070243-0ba3a242-1ab7-4095-9c6b-467ff841416b.png)

**Comment by smartavionics** [comment] 2022-07-20 21:52
Someone will undoubtedly make the comment that models have to be solid (no holes) to be printed in vase mode but that is a regression introduced in 5.x. As you know, 4.13.0 and earlier releases cope just fine with this model.

**Comment by GregValiant** [comment] 2022-07-20 22:57
_"...models have to be solid (no holes) to be printed in vase mode..."_
There ya go.
Turning on "Remove All Holes" in the mesh fixes section will allow this model to be spiralized.

Here it is sliced in 4.12 with Spiralize turned on.  That back and forth shuffle between the inside surface and the outside surface appears to be a seam but if it shows up in a print (and sometimes it does) it is in the XY plane.  The Z does spiralize.
![image](https://user-images.githubusercontent.com/64202104/180093334-72349d74-9c61-4f10-9404-041a67f5b01b.png)

This is 5.1.0 with Remove All Holes turned off.  Cura is able to tell that there is an outside surface facing inwards, and outside surface facing outward, and prints both.  It appears to be extruding strings across the center area.  The Z does not spiralize.  This is what is shown in the OP's images.  I agree it's a mess.
![image](https://user-images.githubusercontent.com/64202104/180093841-d9f27182-f120-4d5d-8d87-109ee31bd48f.png)

5.1.0 with Remove All Holes turned on.  The Z spiralizes up.  The bottom pattern will be concentric no matter how it is set in Cura.
I'll leave this open as a bug report for further comments but it is the new "expected behavior".

![image](https://user-images.githubusercontent.com/64202104/180094145-1a9756a1-0493-4b8e-8f67-338e1a9b9410.png)

**Comment by Ghostkeeper** [comment] 2022-07-21 09:23
Duplicate of https://github.com/Ultimaker/Cura/issues/11843.

**Closed by Ghostkeeper** 2022-07-21 09:23 UTC
Labels: Type: Bug, Status: Under Investigation
