### ISSUE TITLE
Conical Support Reversed 2.5

### ISSUE THREAD

**Issue by seantapscott** [Ultimaker/Cura#1705] opened 2017-04-20 06:13 UTC
Just upgraded to 2.5.0 from 2.4, discovered that Conical Support has been reversed.  The ToolTip description was accurate for 2.4: "Negative angles cause the base of the support to be wider than the top".  But in 2.5, layer view is rendering a non-negative 30 degree support angle as being wider at the bottom.

**Comment by Ghostkeeper** [comment] 2017-04-24 09:30
I'm not able to reproduce this. I used the default 30 degree conical support angle and it made the support narrower at the base than at the top.

**Comment by seantapscott** [comment] 2017-04-24 12:26
I would give you the file i am working on.  2.5 slices it completely differently than 2.4 .  Not sure where/how you upload here

**Comment by Ghostkeeper** [comment] 2017-05-01 15:22
You can put it in a zip-file and then drag it to the comment text area on this page.

**Comment by ianpaschal** [comment] 2018-02-26 13:25
Poster did not respond for almost a year. Closing.

**Closed by ianpaschal** 2018-02-26 13:25 UTC
Labels: Category: CuraEngine, Status: Needs Info, Type: Bug
