### ISSUE TITLE
Open file stl with disable usb printing addons

### ISSUE THREAD

**Issue by luigiamorfini** [Ultimaker/Cura#19822] opened 2024-10-27 19:28 UTC
### Cura Version

5.8.1

### Operating System

Linux Ubuntu 24.04.1

### Printer

Anycubic kroba plus

### Reproduction steps

Hi,  disable usb printing plugin from open stl file's. ?

How to fix permession cura?

Use flatpak version.

I'am italian my english language elementary.

Thanks

### Actual results

open stl file normal.

### Expected results

d'nt write problem

### Add your .zip and screenshots here ⬇️

![disable-cura-usbprinting](https://github.com/user-attachments/assets/12cf9bde-a1ba-4419-8bb9-d425127c0943)

**Comment by GregValiant** [comment] 2024-10-28 10:40
Thanks for the report.
There are feature requests in for this (see #19373 and #19655 ).
Right now it isn't considered a bug because it is "expected behavior".  Some of the older UltiMaker printers require USB printing to be enabled.  The Cura team is aware that it can cause slowdowns and other problems for other printers.  We'll see what comes of the feature requests.
I'll remove the bug label and add the "feature request" label.  I'll go ahead and close this in favor of the previous 'Feature Requests'.

**Closed by GregValiant** 2024-10-28 10:40 UTC
Labels: Type: New Feature, Status: Under Investigation
