### ISSUE TITLE
delete key doesn't work

### ISSUE THREAD

**Issue by jhihn** [Ultimaker/Cura#5198] opened 2019-01-19 22:42 UTC
**Application Version**
3.6.0

**Platform**
OSX (High Sierra and Mojave)

**Steps to Reproduce**
Add an item to the build plate. Then try to remove it with the delete key. It does not delete. 

**Actual Results**
Nothing happens

**Expected results**
The selected item is removed.

**Additional Information**

**Comment by LipuFei** [comment] 2019-02-21 08:07
Closing this due to inactivity.

**Comment by jhihn** [comment] 2019-02-21 18:22
Sorry. I confirmed this. Still an issue for me.

**Comment by Ghostkeeper** [comment] 2019-02-22 08:58
We're still unable to reproduce the issue though.

**Comment by jhihn** [comment] 2019-03-01 21:24
It worked like once, I was surprised, then stopped working for me.  I'll keep playing, but it is a thing.
Is there any debugging I can enable?

**Comment by Ghostkeeper** [comment] 2019-03-04 16:23
Not really. We log the highest logging level anyway in Cura's logs. Maybe it helps to share the Cura log? I'd be surprised if it mentions something though.

**Comment by jhihn** [comment] 2019-03-16 14:28
Video:
https://drive.google.com/open?id=1q9LxxsmhXTOb3vbyHoL5l_-UM9zXOcM2

**Comment by Ghostkeeper** [comment] 2019-03-19 11:08
I believe you, don't worry. But if we can't reproduce the problem on this side we're just stabbing in the blind and can't really fix anything for you.

**Comment by jhihn** [comment] 2020-06-20 13:17
Still a thing in 4.6.1

**Comment by Ghostkeeper** [comment] 2020-06-30 13:32
Yup. There has been some more investigation in https://github.com/Ultimaker/Cura/issues/7754 though, so let's consolidate the information there. I'll close this as a duplicate.

**Closed by Ghostkeeper** 2020-06-30 13:32 UTC
Labels: Category: Cura, Platform: MacOS
