### ISSUE TITLE
why it print the layer at the wrong place

### ISSUE THREAD

**Issue by snuchitp** [Ultimaker/Cura#835] opened 2016-07-01 17:37 UTC
I need to use this version because of my 3D printer. New version not support DeltaBot.
Please do not close my issue. I need some help

I used cura v 15.04.6 to display my model.  From layer 1-9, it looked correct that built each layer up on top. But from layer 10- the end  started to build from the bottom of the model. The detailed lines are different too.

layer 0-9
![screen shot 2016-07-01 at 12 58 50 pm](https://cloud.githubusercontent.com/assets/12837769/16528681/57645856-3f8c-11e6-9dc0-2d558b7e7f1e.png)

layer 10 -14
![screen shot 2016-07-01 at 12 59 06 pm](https://cloud.githubusercontent.com/assets/12837769/16528683/5bf05032-3f8c-11e6-9692-c90ec3e63927.png)

Thanks

**Comment by Ghostkeeper** [comment] 2016-07-03 10:34
Duplicate of issue #834

**Closed by Ghostkeeper** 2016-07-03 10:34 UTC
Labels: duplicate
