### ISSUE TITLE
Working with an wacom intuos pro tablet seems to lock the pointer the view in select model state. 

### ISSUE THREAD

**Issue by GraafSybren** [Ultimaker/Cura#13672] opened 2022-10-27 12:19 UTC
### Application Version

5.1.0

### Platform

mac osx 12.6 MacBookPro18,2 Apple M1 Max

### Printer

S5 

### Reproduction steps

Working with an wacom intuos pro tablet seems to lock the pointer the view in select model state. 

### Actual results

Once the pen of the tablet is on the Cura viewer window. I can only manipulate view and no buttons are selectable. I need to restart cura and use mouse or trackpad only.

### Expected results

normal mouse usage should be expected when working with a pen/tablet input device.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

When needed I can submit a screenrecording of the behaviour

**Comment by MariMakes** [comment] 2022-10-28 12:37
Hey @GraafSybren, 

Welcome to the Ultimaker Cura Github 🚀 


This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12554
We've been collecting more information on this issue, so your report is very welcome 😊.
I'll be closing this issue as a duplicate but you can follow the progress here:  
https://github.com/Ultimaker/Cura/issues/12554

**Closed by MariMakes** 2022-10-28 12:37 UTC
Labels: Type: Bug, Status: Triage
