### ISSUE TITLE
[4.1 Beta] A layer is moved from the middle to the bottom of the model

### ISSUE THREAD

**Issue by extesy** [Ultimaker/Cura#5788] opened 2019-05-27 16:22 UTC
**Application Version**
4.1-BETA

**Platform**
Windows 10 x64

**Printer**
Wanhao i3 Duplicator Plus Mark II

**Steps to Reproduce**
Slice the attached model.

**Actual Results**

Layer 70 is missing in the middle of the model:

![image](https://user-images.githubusercontent.com/65872/58430817-df699d80-805f-11e9-9cfc-e2949307b259.png)
![image](https://user-images.githubusercontent.com/65872/58430829-ee505000-805f-11e9-9926-1c50ff0e943d.png)

In fact, it gets moved to the bottom of the model (below layer 1).

![image](https://user-images.githubusercontent.com/65872/58430967-9c5bfa00-8060-11e9-8913-3d0b1d50c155.png)

Model and generated g-code: [pencil-case.zip](https://github.com/Ultimaker/Cura/files/3224449/pencil-case.zip)

**Expected results**
Normal slicing with layer 70 in its normal position.

**Comment by fieldOfView** [comment] 2019-05-27 18:14
Duplicate of https://github.com/Ultimaker/Cura/issues/3815
This is a sporadic visualisation bug in Layer view. The gcode will print correctly. If you slice the model again, the layer will also be placed correctly.

**Comment by Liger0** [comment] 2019-05-27 22:18
>  If you slice the model again, the layer will also be placed correctly.
No, it won't.

**Comment by extesy** [comment] 2019-05-27 23:10
@fieldOfView In #3815 there was no g-code. In my case, I did save the g-code - maybe that will help with debugging?

**Comment by fieldOfView** [comment] 2019-05-28 08:24
When I load the gcode into Cura (4.1.0 beta), all the layers are in the correct order. There is nothing wrong with the gcode, it will print as expected. It still looks like a duplicate of #3815 to me.

**Comment by Liger0** [comment] 2019-05-28 08:52
Yeah it is for sure, but reslicing wil lstill display the layer in the wrong position. I have this bug frequently and even if I restart the PC and reload the model I still have it until I change some settings (ore more than one, sometimes one is not enough) in the profile

**Comment by nallath** [comment] 2019-05-28 09:36
And provide the reproduction steps, because that's what's stopping us from fixing it.

**Comment by nallath** [comment] 2021-07-07 14:41
Closing this as a duplicate in favor of https://github.com/Ultimaker/Cura/issues/7412

**Closed by nallath** 2021-07-07 14:41 UTC
Labels: Status: Duplicate, Type: Bug
