### ISSUE TITLE
Profiles disappeared if we added new Material

### ISSUE THREAD

**Issue by kirznervadim** [Ultimaker/Cura#7190] opened 2020-02-29 10:16 UTC
**Steps:**
1. Add new Material: See settings ![2102](https://user-images.githubusercontent.com/58177329/75605602-49363c80-5af5-11ea-947a-eb2824669093.png)
2. Press Activate
3. Quit Cura
4. Open Cura and go to 'Profiles' menu 
![2103](https://user-images.githubusercontent.com/58177329/75605659-9ca88a80-5af5-11ea-80d6-4d2d6a4da8c7.png)

**Actual:**
List is blank

**Expected:**
Default profiles displayed

**Comment by Ghostkeeper** [comment] 2020-03-04 14:55
This is because those quality profiles are specified to be specific to the material type. Your new material has a material type of "PET-G". No quality profile claims that it works for "PET-G". If you change that to just "PETG" (without the dash) then it will match on the PETG family of profiles so you will see some profiles to start with.

If using a material where there are no specifically-tuned quality profiles, Cura will show the material in orange and say that it's not supported. You're completely on your own to create profiles then.

This is expected behaviour, so I'll close this issue.

**Closed by Ghostkeeper** 2020-03-04 14:55 UTC
