### ISSUE TITLE
3.6.0 Brim not working as expected.

### ISSUE THREAD

**Issue by OldGaf** [Ultimaker/Cura#5332] opened 2019-02-19 16:49 UTC
**Application Version**

3.6.0
**Platform**

Win7
**Printer**

CR10s
**Steps to Reproduce**

cut out font on the bottom of a print. Turn on brim only on the outside.
**Actual Results**

A brim is added to parts of the font like B's or D's... where the center of the letter is not touching a wall.
This results in the letter being partly filled in on the first layer.
**Expected results**

There should be no brim on these parts.
**Additional Information**

![no_brim](https://user-images.githubusercontent.com/47789457/53032101-8b3d9480-3444-11e9-8b62-1da749b996aa.PNG)

![with_brim](https://user-images.githubusercontent.com/47789457/53032107-8d9fee80-3444-11e9-907e-3ec605ec0258.PNG)

**Comment by rburema** [comment] 2019-02-20 08:09
Duplicate of #4222 and #5324 (at least). There is a ticket for this in our backlog, but we're not sure when we'll get to it.

**Closed** 2019-02-21 15:21 UTC
Labels: Status: Duplicate
