### ISSUE TITLE
Cura 2.5, Post Processing Plugin: gcode does not re-postprocess after changing scripts values

### ISSUE THREAD

**Issue by anton-veretenenko** [Ultimaker/Cura#1856] opened 2017-05-21 20:05 UTC
Slice automatically disabled.

I've sliced model with "Prepare". Then I've added some TweakAtZ instances or other Post Processing scripts. Then used "Save to File" button to save gcode. Gcode appeared post-processed.
Then I go and change some values in tweaks/scripts and use "Save to File" again (no "Prepare" button appear). Gcode file appeared as previous one with previous tweaks.
This is from log:
`
2017-05-22 01:01:08,777 - ERROR - PostProcessingPlugin.PostProcessingPlugin.execute [69]: Already post processed
`

If I force some changes in slicing options to make "Prepare" button appear then it re-postprocess gcode and new tweak values appear in gcode.

**Comment by Ghostkeeper** [comment] 2017-08-20 22:41
It reproduces for me, but our product manager just closed this issue off for being more than 3 months old.

**Comment by d235j** [comment] 2017-10-28 22:00
Filed upstream — this looks like a bug in the PostProcessing plugin.

**Comment by d235j** [comment] 2017-10-30 14:01
Hmm, doesn't seem to reproduce anymore for me.

**Comment by Ghostkeeper** [comment] 2017-10-30 14:04
For me neither. It seems to have been fixed in the meanwhile.

**Closed** 2017-10-30 14:03 UTC
Labels: bug
