### ISSUE TITLE
Cura prints supports before skirt if 'enable support brim' is enabled

### ISSUE THREAD

**Issue by SQL-enwiki** [Ultimaker/Cura#16310] opened 2023-07-29 00:22 UTC
### Cura Version

5.4.0

### Operating System

Garuda Linux (Arch-based), NVidia 3070

### Printer

FLSun Q5, FLSun Super Racer, FLSun v400

### Reproduction steps

Load print on build plate
Select a 5-layer wide skirt
Select 'Generate Supports'
Set up a support brim a few lines wide

### Actual results

Cura printed two of the supports, and then did the skirt, resulting in a print failure.

### Expected results

I expected Cura to draw the skirt first, then do the things inside the skirt

### Add your .zip and screenshots here ⬇️

Support Settings:

![Bugrep1](https://github.com/Ultimaker/Cura/assets/45909509/7b711e45-f20d-463a-b387-ae424f27f6e8)

Printing the support first:

![bugrep2](https://github.com/Ultimaker/Cura/assets/45909509/75578fce-1cd7-44c4-be9e-2b2e7b1bf3dd)

Printing the skirt:
![bugrep3](https://github.com/Ultimaker/Cura/assets/45909509/0416de6a-82fa-484f-92f7-3a2ca552bd7d)

[Project.zip](https://github.com/Ultimaker/Cura/files/12205447/Project.zip)

**Comment by GregValiant** [comment] 2023-07-29 12:55
Thanks for the report.
This is odd.  I get exactly the same results so I can duplicate this with your Super Racer...but not with other printers.
HOWEVER...when I change any printer to "Origin at Center" the problem shows up.
@MariMakes or another member of the Cura team will take a look.

This is an Anycubic printer with "Origin at Center" turned OFF.  This shows the expected behavior of _**Skirt First**_.
![image](https://github.com/Ultimaker/Cura/assets/64202104/32f843fb-c1f3-4578-9e5e-bfa60de1a28f)

The only change I made here was to turn "Origin at Center" ON.  One of the Support Brims goes down first.
![image](https://github.com/Ultimaker/Cura/assets/64202104/a6fac3eb-99c0-460b-953c-4977a5f300e0)

**Comment by SQL-enwiki** [comment] 2023-07-29 15:41
It's entirely possible that I wasn't switching between the printers correctly.

I just looked again, and it for sure does this on the FLSun Q5 (Another Delta), and the FLSun v400 (another delta). 

You are correct - I tried my ender 3 again, and I'm not seeing it there, my bad, I must have had too much going on last night.

**Comment by MariMakes** [comment] 2023-08-07 11:29
Hey @SQL-enwiki,

Welcome to the UltiMaker Cura Github 🚀 
This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/15088

One of our developers has been able to resolve it here: https://github.com/Ultimaker/CuraEngine/pull/1922/files 
So you can expect a fix in the next version of Cura.  It was indeed related to the origin of the printer being in the middle or on the side. 

Great find! 👍

**Closed by MariMakes** 2023-08-07 11:29 UTC
Labels: Type: Bug, Status: Under Investigation

**Comment by Thisismydigitalself** [comment] 2023-10-16 12:51
Same here - runnning Cura 5.4.0. supports are printed before skirt.
was this solved in later versions?..

**Comment by GregValiant** [comment] 2023-10-16 14:36
Yes.  This appears to be fixed in 5.5beta.

This is 5.4.0 with Support Brim enabled at 5mm width, and Bed Adhesion set to "None".  With the Support Brim missing the support on the next layer was essentially printing over air.
![image](https://github.com/Ultimaker/Cura/assets/64202104/e88cdb26-7b70-412c-ba0a-ccff2e15fb36)

This is 5.5beta with the same model and same settings.  Looks fixed to me.
![image](https://github.com/Ultimaker/Cura/assets/64202104/47ad25a7-e7a9-4d50-9558-bce42bc0f758)

**Comment by DK4YA** [comment] 2024-01-17 14:21
I print with a delta and a cXY. The problem that the support is printed before the skirt occurs with the Delta, but not with the cXY. Everything under Cura 5.4.
