### ISSUE TITLE
Profiles are missing (but exists)

### ISSUE THREAD

**Issue by spanzetta** [Ultimaker/Cura#8818] opened 2020-11-22 16:24 UTC
After update from 4.7 to 4.8 I noticed that all profiles are not listed..
Also I noticed an orange triangle with question mark (an error?) close to the material name.. what is it? 
See all screenshots attached 

I already edited manually all files (under %AppData%\Roaming\cura\4.8\quality_changes) and replaced "quality_type = not_supported"
with "quality_type = standard"
How to fix the problem?
Thanks

![profile list](https://user-images.githubusercontent.com/49818743/99909220-69db9d80-2ce7-11eb-94d9-26ec90d5c78f.jpg)
![error](https://user-images.githubusercontent.com/49818743/99909221-6a743400-2ce7-11eb-92b8-5f8cd6e47b70.jpg)
![profiles list empty](https://user-images.githubusercontent.com/49818743/99909222-6b0cca80-2ce7-11eb-9914-62b9c179dbb0.jpg)

**Comment by nallath** [comment] 2020-11-23 10:00
Duplicate of #8229

**Closed by nallath** 2020-11-23 10:00 UTC
Labels: Type: Bug
