### ISSUE TITLE
Interleaving layers on a single model with support printing with second extruder.

### ISSUE THREAD

**Issue by Shlykov1** [Ultimaker/Cura#15354] opened 2023-04-25 11:38 UTC
### Application Version

5.3.1

### Platform

Windows 10

### Printer

Custom fdm

### Reproduction steps

1. Have a dual extruder printer
2. Load a single model with supports
3. Configure supports for the second extruder
4. Slice it

### Actual results

Interleaving layers on a single model with supports.

### Expected results

All layers should be with the same height.

### Checklist of files to include

- [x] Log file
- [x] Project file

### Additional information & file uploads

> Figure 1.

![image](https://user-images.githubusercontent.com/90396436/234221564-c9e64bdd-6110-4988-99c3-c41f7c8c3f73.png)
![image](https://user-images.githubusercontent.com/90396436/234221744-7eb9bbc9-17d8-4c33-9471-7e7a37054f3f.png)

> Figure 2

![image](https://user-images.githubusercontent.com/90396436/234221956-0f5c6253-6cac-4794-a20d-99c9380bb82d.png)

Cura cannot slice correctly with 2 extruders when there is one model with support on the print bed, if there are more than one model, then everything prints correctly. The essence of the problem is that cura alternates layers, as shown in Figure 1, one layer is normal, and the second is reduced. I also opened the gcode sliced with cura in an ideamaker 3d and it shows that the layers alternate in the 
same way as on the presented models in Figure 2.
[cura_bug.zip](https://github.com/Ultimaker/Cura/files/11321393/cura_bug.zip)

**Comment by nallath** [comment] 2023-04-25 13:09
Thanks for the extensive issue. This helps a lot with debugging this!

I do see from your logs that you have a number of plugins that might influence the Z height, which could be the cause of this. Could you confirm for me if they are enabled for this print? 

If that's not the issue, I believe that it is probably caused by the raft. My rationale for that is that most of the Ultimaker profiles don't use rafts and the case that you describe is something that we tested with our profiles (but without a raft). It could well be that the "weird" layerheights that a raft can have are not correctly taken into consideration for support, causing the interlaced affect that you are seeing.

**Comment by Shlykov1** [comment] 2023-04-25 13:25
Thanks for fast answer! I have installed z_offset plugin, but wasnt used it. If we consider on this print, there is only a "thumb nail" plugin.

**Comment by nallath** [comment] 2023-04-25 14:44
In that case, it's likely the raft that is the culprit here. I will discuss it with the rest of the team!

**Comment by Shlykov1** [comment] 2023-04-25 14:46
Thanks a lot, i'll be looking forward to the new patch!

**Comment by Shlykov1** [comment] 2023-04-26 16:28
Hello! I found the problem, it was not on your side. Apparently, I have a backlash in the screw-nut pair that moves the table up and down, when the support extruder went down, I had to lower the table lower than in the previous layer, and then raise it back.

**Comment by MariMakes** [comment] 2023-05-08 12:44
Hey @Shlykov1,

Thanks for the update 👍

Since it's not a bug in Ultimaker Cura anymore. 
I'll be closing this issue. 

Happy printing 😄

**Closed by MariMakes** 2023-05-08 12:44 UTC
Labels: Type: Bug, Status: Triage, Status: Under Investigation
