### ISSUE TITLE
Update notification error.

### ISSUE THREAD

**Issue by cmdkill** [Ultimaker/Cura#12167] opened 2022-05-11 05:03 UTC
### Application Version

5.0.0 Beta+1

### Platform

Windows 10

### Printer

CFFFP

### Reproduction steps

![Cura5BetaBug](https://user-images.githubusercontent.com/4532486/167771842-b7e779d0-7d31-44d7-931e-98c59651ab96.jpg)

Installed latest Cura 5.0.0 Beta +1 from Github. Ran program at finish of installer. Notified that there was an update available.

### Actual results

Notification popup.
![Cura5BetaBug](https://user-images.githubusercontent.com/4532486/167772127-d609a5c4-17fb-4caa-8207-f9b5f5bbafdf.jpg)

### Expected results

Notified that update of Beta install completed. No new available.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8666870/cura.log)

No project loaded manually.

4.7 also installed on system.

**Comment by cmdkill** [comment] 2022-05-11 05:10
[cura.log](https://github.com/Ultimaker/Cura/files/8666901/cura.log)

Crash

**Comment by cmdkill** [comment] 2022-05-11 05:18
[cura.log](https://github.com/Ultimaker/Cura/files/8666906/cura.log)
Can't upload gcode file.
Backup and reset cfg.

**Comment by fieldOfView** [comment] 2022-05-11 05:22
Thanks for reporting. This issue has been reported before, and has since been fixed.

**Comment by fvrmr** [comment] 2022-05-11 09:09
Hi @cmdkill thank you for your report.
This is indeed a duplicate of https://github.com/Ultimaker/Cura/issues/11229, so I will close this issue. And this is indeed fix for next beta releases!

**Closed by fvrmr** 2022-05-11 09:09 UTC
Labels: Type: Bug
