### ISSUE TITLE
Arrows Stop Working

### ISSUE THREAD

**Issue by kencole57** [Ultimaker/Cura#4214] opened 2018-08-09 00:12 UTC
**Application Version**
3.4.0 and 3.4.1

**Platform**
Windows 10 64 bit

**Printer**
Creality Cr-10

**Steps to Reproduce**
Arrows to rotate the build plate stop working, left, right, up down. I click the model, choose a function different to the last one i used, so move if I had used scale or vice versa, click off the model and the arrow keys work again, for a while.  When they stop again, I just repeat this process. I have not been able to determine any specific action that stops the arrow keys from working.

**Actual Results**
Arrow key that stopped working start working

**Expected results**
Arrow keys should not stop working

**Additional Information**
Nil

**Comment by ianpaschal** [comment] 2018-08-09 12:30
Unfortunately this doesn't reproduce for me.

**Comment by alekseisasin** [comment] 2018-08-15 07:59
@kencole57 , could you please determine the actions which will lead to not working arrows. 
Probably you had this,  after adjusting the value in the scale field the cursor stays there and pressing "Left" key on keyboard moves the cursor in the input field and not the build plate. After reaching the beginning (or end) of the input field the build plate starts the rotation.

**Comment by diegopradogesto** [comment] 2019-09-11 12:30
Closing the issue because we couldn't reproduce and lack of extra information.

**Closed by diegopradogesto** 2019-09-11 12:30 UTC
Labels: Status: Needs Info
