### ISSUE TITLE
cylinder with side thickness an even multiple of extrusion width leads to very poor slicing

### ISSUE THREAD

**Issue by dejaloomer** [Ultimaker/Cura#2695] opened 2017-10-28 04:13 UTC
I'm not sure which multiples apply but very easy to repro with a cylinder with a wall 3x the line width:
* I used fusion 360 to create a hollow cylinder with a shell thickness of 1.2
* Cura extrusion (line) width = .4
* Cura wall thickness = 1.2
I'd expect multiple layers of 3 smooth rings. Instead the slicing goes bonkers with the head moving all over the place and making tons of straight movement. The results of a print are pretty mangled. The first image shows the head movement. The second image is with line width set to .402 and results in a much more expected slice. Although the inner wall still does some unexpected straight movements.

![lw4 00](https://user-images.githubusercontent.com/3394378/32131128-e4571c76-bb5a-11e7-92a3-d3a4650943a3.PNG)
![lw4 02](https://user-images.githubusercontent.com/3394378/32131129-ef319c3e-bb5a-11e7-9be2-99a259f1e5fb.PNG)

**Comment by smartavionics** [comment] 2017-10-28 06:43
Try reducing the innner wall line width a little.

**Comment by Thisismydigitalself** [comment] 2017-10-28 06:55
Same here. modeling with F360, Printing with a 0.5 nozzle and i get similar results.

**Comment by smartavionics** [comment] 2017-10-28 07:12
Like this...
![screenshot_2017-10-28_08-11-48](https://user-images.githubusercontent.com/585618/32132212-b7bfeb2c-bbb7-11e7-879e-2f18de790e76.png)

**Comment by Thisismydigitalself** [comment] 2017-10-28 07:52
should we "cheat" with thinner inner wall line width?..

**Comment by Thisismydigitalself** [comment] 2017-10-28 07:58
Ok, the 0.49 trick worked for me.
Just tried it and it works. why do i need to do that - that i don't know

![ice_screenshot_20171028-105642](https://user-images.githubusercontent.com/30949968/32132590-d29ce3e8-bbce-11e7-9689-2b4895ee49e0.png)
![ice_screenshot_20171028-105603](https://user-images.githubusercontent.com/30949968/32132591-d2bc3b6c-bbce-11e7-91d8-909e600822ce.png)

**Comment by DDDirk** [comment] 2017-10-28 11:41
My guess is that the cause is that while we may see that it is supposed to be a circle, Cura just sees vertices and lines between them that 'cut corners', resulting in Cura thinking the inner wall won't fit, so it prints infill instead.
Most desirable would be the ability to feed splines to slicers and slicers putting splines in gcode. The resolution of, say, a G3 would then only be limited by the abilities of the printer (resolution of the motors).

Until then, some trickery is needed.

I also often see a conflict between wall line count and wall line width when I want something to be printed only as walls, for which I then fill in a wall count that is way too high (and no infill). Cura then often leaves gaps in the middle that I want filled.
For example, if I slice a cylinder with a wall 1.3 mm thick and in Cura all wall line widths 0.4 mm, I get only 3 walls. Interrestingly, though, if I make the wall 1.4 mm thick I do get 4 walls. So Cura doesn't allways blindly follow the wall line widths.

But it would be nice if Cura could be told to completely fill a model with walls.
Maybe by filling in an inner wall line width of 0. Right now, that gives an error (red field).

Or better, Cura nicely shows what affects what by hovering over a setting (a feature I really like). Right now, the wall line widths affect the wall count. Maybe there should be an option to reverse that. 
Which leaves the question what to do then if the wall line count is set too high to be realistic (eg 10 walls in the above example). Actually do that? Walls 0.13 mm thick? What if it is set at 50? Maybe give an error? Seems the simplest solution.

**Comment by smartavionics** [comment] 2017-10-28 13:00
I have created a PR that should help when walls are made from lines that completely fill the wall width. See https://github.com/Ultimaker/CuraEngine/pull/635.

**Comment by dejaloomer** [comment] 2017-10-29 00:21
Thanks for the quick reply and useful info. Setting inner wall to .39 does indeed result in a nice concentric slice. However the print head does still crisscross the tube in a interesting fashion. This results in a ton of strings across the tube. If I turn off combing the dark blue lines show light(see image). I guess this causes retraction so most of the strings go away but there are still some and a lot of burs and blobs on the inside where the head reversed. A tube with non-integral thickness (1mm) slices cleanly with no head traversal, so there does seem to be something pathological about the multiple case.
![innerwall 39](https://user-images.githubusercontent.com/3394378/32139650-488c7eee-bc04-11e7-9c0d-011164b3c70e.PNG)

**Comment by smartavionics** [comment] 2017-10-29 07:18
If you are using Cura 3, enable the Optimize wall printing order setting that's in the experimental category. Also, to ensure that the z-seams of the red walls are aligned, select either shortest or user specified. Doing these things should ensure that the z-seams of all of the walls are aligned.

**Comment by Ghostkeeper** [comment] 2017-11-06 02:27
The mechanism that causes this is the "Fill Small Gaps" setting.

Since no more walls would fit in the space between these outer walls, it leaves them out. Now there's a gap that has to be filled using the Fill Small Gaps technique, which uses a smaller line width. However, the Fill Small Gaps algorithm has no notion any more of what lines or walls surround those gaps. Instead it just prints parallel lines similar to skin. It then tries to link together small line segments to create a passable result. This fails at two of the sides though since the parallel lines happen to be parallel to the walls as well, which makes those lines long so they can't be linked to the next lines any more.

With that in mind, I don't know a real solution to this that is safe in all cases and efficient to compute.

**Comment by alekseisasin** [comment] 2017-11-27 16:38
@dejaloomer , Do you have additional questions related to your issue, others we would like to close this issue.

**Comment by Ghostkeeper** [comment] 2017-12-11 12:27
The status of this issue is that it's basically the expected result but we know that it's less than optimal.

**Comment by dejaloomer** [comment] 2018-01-13 18:36
@alekseisasin No more questions. Thanks for the info. Is the protocol for me to close the issue because I'm fine with closing it.

**Comment by fieldOfView** [comment] 2018-01-14 14:31
Feel free to close it then.

**Closed** 2018-01-15 08:35 UTC
