### ISSUE TITLE
[5.5.0-b1] Initial layer speed not honored

### ISSUE THREAD

**Issue by stestagg** [Ultimaker/Cura#17010] opened 2023-10-17 11:11 UTC
### Cura Version

5.5.0-b1

### Operating System

Mac Sonoma 14.1

### Printer

Creality Ender-3 S1 (pro, using klipper v0.11.0-299-gb1f597c5)

### Reproduction steps

1. Slice a model
2. Preview the first layer in Speed view

### Actual results

3. Note that the speed of outer walls (on layer 1) matches the outer wall speed, not the initial layer print speed:
I.e. not 15mm/s but 150mm/s

![Screenshot 2023-10-17 at 12 01 37](https://github.com/Ultimaker/Cura/assets/704526/c37f14c5-cac8-45b2-83ca-96e838475f2c)

<details><summary>Extract from the gcode</summary>
<pre>
<code>
...
G92 E0 ;Reset Extruder
G1 Z2.0 F3000 ;Move Z Axis up
G92 E0
G92 E0
G1 F2400 E-0.8
;LAYER_COUNT:39
;LAYER:0
M107
;MESH:wall.stl
G0 F6000 X34.25 Y28.101 Z0.2
G1 F2400 E-0.8
;LAYER_COUNT:39
;LAYER:0
M107
;MESH:wall.stl
G0 F6000 X34.25 Y28.101 Z0.2
;TYPE:WALL-OUTER
G1 F2400 E0
G1 F5930.8 X22.123 Y28.106 E0.61208
G1 F5479.5 X21.867 Y28.152 E0.62629
G1 F5513 X21.637 Y28.451 E0.64677
G1 F5911.3 X15.575 Y38.957 E1.26099
G1 F5479.5 X15.489 Y39.199 E1.27502
G1 F5547 X15.633 Y39.55 E1.29549
G1 F5940.6 X21.703 Y50.053 E1.90675
G0 F6000 X22.096 Y50.447
G0 X22.398 Y51
G0 X22.096 Y51.553
G0 X21.638 Y52.051
G1 F5921.1 X15.575 Y62.557 E2.51999
G1 F5479.5 X15.489 Y62.8 E2.53407
G1 F5547 X15.633 Y63.15 E2.5545
...
</code>
</pre>
</details> 

### Expected results

3. Lines on the initial layer all printed at initial layer print speed

<details><summary>Expected gcode</summary>
<pre>
<code>
...
G92 E0 ;Reset Extruder
G1 Z2.0 F3000 ;Move Z Axis up
G92 E0
G92 E0
G1 F2400 E-0.8
;LAYER_COUNT:39
;LAYER:0
M107
;MESH:wall.stl
G0 F6000 X34.25 Y28.101 Z0.2
;TYPE:WALL-INNER
G1 F2400 E0
G1 F593.1 X22.123 Y28.106 E0.61208
G1 F547.9 X21.867 Y28.152 E0.62629
G1 F551.3 X21.637 Y28.451 E0.64677
G1 F591.1 X15.575 Y38.957 E1.26099
G1 F547.9 X15.489 Y39.199 E1.27502
G1 F554.7 X15.633 Y39.55 E1.29549
G1 F594.1 X21.703 Y50.053 E1.90675
G0 F6000 X22.096 Y50.447
G0 X22.837 Y51
G1 F891.1 X34.25 Y51 E2.29015
G1 F2400 E1.49015
...
</code>
</pre>
</details>

### Add your .zip and screenshots here ⬇️

Stl can be provided if useful

![Screenshot 2023-10-17 at 12 01 37](https://github.com/Ultimaker/Cura/assets/704526/a5c27a1e-b54e-4171-bf4f-74f916ef24df)

**Comment by stestagg** [comment] 2023-10-17 11:13
Just a note, the produced gcode also has these speeds.  

I noticed the issue because my printer was going mad on the first layer, and nothing was sticking.

**Comment by stestagg** [comment] 2023-10-17 11:16
Just retried on 5.4.0 and it works as expected
![Screenshot 2023-10-17 at 12 16 41](https://github.com/Ultimaker/Cura/assets/704526/ca746b1d-7141-4a13-81f9-18dbf9589681)

**Comment by GregValiant** [comment] 2023-10-17 12:12
Thanks for the report.
I can't duplicate this with my Ender 3 Pro.  There may be a setting in your definition file that is affecting this.
Please provide a project file so we can do a comparison.
This is in 5.5beta with the settings as I see in your screenshot.  Everything is at "Initial Layer Speed".
![image](https://github.com/Ultimaker/Cura/assets/64202104/b51abdbb-0cb5-401e-9811-a293e730d952)

**Comment by stestagg** [comment] 2023-10-17 12:20
That's weird.  The attached project file uses a smaller model, but shows the same issue for me
![Screenshot 2023-10-17 at 13 19 06](https://github.com/Ultimaker/Cura/assets/704526/685889d2-1f3a-48fa-b5d0-a3b6449b0f2d)
[wall-mini.3mf.zip](https://github.com/Ultimaker/Cura/files/12928558/wall-mini.3mf.zip)

**Comment by GregValiant** [comment] 2023-10-17 13:12
Thanks for the file.
My "Slow PLA" profile shows exactly as you show - the Initial Layer speed seems to be ignored.
My "Fast PLA" profile shows everything as expected with the Initial Layer speed enforced.
I think what is happening is that the original "Quality" profile that the custom profiles were created from is still having an effect even though settings are overridden.
If I set Cura to "Dynamic" quality with 2 Slower Initial Layers at 10mm/sec I get this:
![image](https://github.com/Ultimaker/Cura/assets/64202104/99591cb9-7d18-4b1d-af09-f1aa467fc618)
With "Super" quality with 2 Slower Initial Layers at 10mm/sec I get this:
![image](https://github.com/Ultimaker/Cura/assets/64202104/d4f22efd-7bc3-4d00-a26b-a56f703271a6)

I haven't been able to find exactly what is causing this.  The Cura team will take a look.
It does appear to be related to the Quality profiles that were provided by Creality as part of the Ender definition files.  That would seem to make it a Creality problem rather than a Cura problem.

**Comment by stestagg** [comment] 2023-10-17 13:15
Thanks for taking the time to look!

For that it's worth, I've just narrowed down the trigger for me: changing the 'Slicing Tolerance' setting back to 'Middle' fixes the problem, but both 'Inclusive' and 'Exclusive' modes cause the fast initial layer problem.

**Comment by MariMakes** [comment] 2023-10-17 13:21
Hi @stestagg,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

This was quite a puzzling issue, but I believe I've figured it out. 
The model you shared seems to be faulty. 
When I loaded it into Microsoft 3D builder, I got prompted a repair message.
In the screenshot, on the right you can see the fixed model, on the left the model you shared.
You can see that the initial layer is green indicating having it's own initial layer speed. 
![image](https://github.com/Ultimaker/Cura/assets/40423138/7a6074ad-40cb-42a4-ba00-90f2a52da563)

This is the repaired model: [CE3S1_wall-mini.zip](https://github.com/Ultimaker/Cura/files/12929344/CE3S1_wall-mini.zip)

To me, it doesn't seem like a bug in Ultimaker Cura, since the error is caused by your model. 
I'll be closing this issue. I hope you understand.

**Closed by MariMakes** 2023-10-17 13:21 UTC
Labels: Type: Bug, Status: Under Investigation

**Comment by stestagg** [comment] 2023-10-17 13:47
Hi, Thanks @MariMakes and @GregValiant, and sorry, I've trained myself to ignore the watertight error message, as it's so common now! but it was telling me there was a problem.

I've checked and it's working for me once the mesh is fixed.

**Comment by Rai80** [comment] 2023-11-01 21:17
I've got the exact same issue. I also start noticing this when after the upgrade to 5.5.0. The initial layer wall speed is too high.
I did do the model fix with 3D builder, but this did not fix the problem. In Cura 5.4.0 i dont have this issue.

![image](https://github.com/Ultimaker/Cura/assets/26062016/4b6cae3d-bcab-4b34-85f5-e0394c093e32)

**Comment by Deplerr** [comment] 2023-11-18 21:20
I can also confirm on my own end that this is only occurring in 5.5.0 and later releases, I've been pulling my hair out trying to solve it and going back to 5.4.0 seems to have fixed the problem.

5.5.0:

![34](https://github.com/Ultimaker/Cura/assets/14834136/752bea4e-1eef-4dde-88d8-b709149a653e)


5.4.0:

![12](https://github.com/Ultimaker/Cura/assets/14834136/71a47811-6794-45b0-8347-4254bc2753c8)

I've tried tweaking every setting to fix this but at the time of writing the only solution seems to be to revert to 5.4.0.

**Comment by lxlolxl** [comment] 2023-11-21 16:14
I got the same problem cura 5.5.0 with my voron2 custom, but with the same model, slice on Flsun Super Racer won't see that problem.

**Comment by GregValiant** [comment] 2023-11-21 17:05
@MariMakes  I would like to re-open this as it is an ongoing problem.  It isn't just an "Initial Layer Speed" problem so maybe changing the report title would be in order.

This is the model submitted by @stestagg on 10-17.  I ran this model through MS 3D Builder and it has no errors.
I have the Print Speed set to 75 and the Flow Equalization is 100% and the line width at 0.65 (0.6 nozzle).  I am achieving the same results in 5.5.0, and 5.6beta2.

You can see that the speed of the mid-wall extrusion is 259mm/sec.
![image](https://github.com/Ultimaker/Cura/assets/64202104/84d66cd1-de95-4356-978f-f2cf5ce8a9b7)

If I change the Flow Equalization to zero% the problem goes away.
![image](https://github.com/Ultimaker/Cura/assets/64202104/e7cab9cb-143c-4fda-8a09-7c26582a4b72)

This behavior appears to involved the wall thickness and the Line Width that will fit between the outer walls. 

This is the same setup in 5.4.0.  You can see that the Flow Equalization at 100% results in a reasonable speed increase to 84mm/sec.
![image](https://github.com/Ultimaker/Cura/assets/64202104/b7149302-874c-4a02-b38c-840a6805c3ef)

This is in 5.2.2.  The speed has been adjusted **_down_** to 57.93 rather than **_up_** to 259.  A 200mm/sec speed difference would seem to indicate that _sumthin' ain't right._
![image](https://github.com/Ultimaker/Cura/assets/64202104/53d9efc2-668b-4667-8f83-3499e3d509d2)

**Comment by lxlolxl** [comment] 2023-11-21 20:13
@GregValiant 
I just found that "Initial Layer Speed" indeed have some problem to solve. 
But it's about the machine's .def.json.

For example, voron2, fine the file :
"UltiMaker Cura 5.5.0\share\cura\resources\definitions\voron2_base.def.json"
Open and delete the line:
"roofing_layer_count": { "value": 1 },
"speed_topbottom": { "value": "math.ceil(speed_print * 0.33)" },

So that I can be sure Initial Layer Speed will work.

**Comment by ole1986** [comment] 2023-12-08 22:16
Does the change  on file `voron2_base.def.json` only applies to the reported "Creality Ender-3 S1" printer model?

**Comment by EmJay276** [comment] 2023-12-08 22:19
> Does the change  on file `voron2_base.def.json` only applies to the reported "Creality Ender-3 S1" printer model?

It's only for Voron based profiles. Have a look at the corresponding Ender file. Sorry I don't know how it is called and can't look it up for you right now.

**Comment by GregValiant** [comment] 2023-12-08 22:58
@ole1986 it does not.  The "creality_base.def.json) file says:
"speed_topbottom": { "value": "speed_print" }
So there is no formula involved like with the Voron.

**Comment by ole1986** [comment] 2023-12-08 23:01
I took a quick look into my related file using the FLsun Q5/QQ and could not quickly figure it out.. so that is why I switched back

**Comment by GregValiant** [comment] 2023-12-09 03:27
5.2.2 would be my choice.

**Comment by Flight** [comment] 2024-02-10 07:24
Getting the same on Sovol SV06, so it not only about Vorons. Flow equalisation and print thin walls options doesn't help.
