### ISSUE TITLE
"Slicing Failed" issue

### ISSUE THREAD

**Issue by Bijongles** [Ultimaker/Cura#14315] opened 2023-01-17 22:11 UTC
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Sovol SV03

### Reproduction steps

I just opened an STL file, that's it.

### Actual results

![Slicing Failure](https://user-images.githubusercontent.com/92131684/213020833-b9441377-d80e-4ea4-bfde-7de4c68cdfb2.png)

### Expected results

For it to produce a detailed map of how the STL file would be sliced.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

It said "Slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker."

**Comment by MariMakes** [comment] 2023-01-20 12:19
Hey @Bijongles,

Welcome to the Ultimaker Cura Github 🚀 

Is it possible that your printjob is located at 0, 0, 0, and it slices if you move it a little away from the center of the buildplate? 
Then it might be a duplicate of https://github.com/Ultimaker/Cura/issues/13643

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Closed** 2023-02-03 12:37 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage, Slicing Error :collision:
