### ISSUE TITLE
TypeError: type SettingFunction doesn't define __round__ method

### ISSUE THREAD

**Issue by goebish** [Ultimaker/Cura#3246] opened 2018-02-07 00:02 UTC
**Application Version**
3.2

**Platform**
Windows

**Steps to Reproduce**
Select Monoprice Select Mini V1 as printer

**Actual Results**
App crash with TypeError: type SettingFunction doesn't define __round__ method in the log

I had no issue with 3.2 beta

**Comment by Vandrasc** [comment] 2018-02-07 07:58
Confirmed, thank you for reporting it! Devs see CURA-4923

**Comment by fieldOfView** [comment] 2018-02-07 08:22
See https://community.ultimaker.com/topic/21397-issue-with-cura-32-and-monoprice-select-mini-v2/?tab=comments#comment-199273

In the definition, value is set to a number (should be a python-interpretable string)

**Comment by Appesteijn** [comment] 2018-02-07 10:15
I searched through all printer definitions and in malyan_m200.def.json, peopoly_moai.def.json, renkforce_rf100.def.json a "value" is used instead of a "default_value" for "material_diameter".

**Comment by jackha** [comment] 2018-02-07 10:25
CURA-4928, working on it and it will be fixed in a bugfix release

**Comment by fieldOfView** [comment] 2018-02-07 10:27
The problem is not "value" or "default_value". The problem is that what comes after it should be a string in the case of "value" and a number in the case of "default_value".

correct:
"value": "1.75" 
or
"default_value": 1.75

incorrect:
"value": 1.75
or
"default_value": "1.75"

**Comment by goebish** [comment] 2018-02-07 10:28
Thanks, adding quotes to my custom definition file fixed the issue.

**Comment by jackha** [comment] 2018-02-07 10:41
We're changing it to default_value as most of the definitions use that. Thanks @fieldOfView for the valuable tip!

**Comment by RichardSerton** [comment] 2018-02-07 23:21
My 'definitions' folder is empty
<img width="519" alt="screen shot 2018-02-07 at 6 21 15 pm" src="https://user-images.githubusercontent.com/36246495/35946945-bf34d7ba-0c33-11e8-81c0-6089de241a4b.png">

Am I missing something here?

**Comment by mherodev** [comment] 2018-02-10 03:48
Is there a hotfix I can do, or should I download the beta?

**Comment by Appesteijn** [comment] 2018-02-10 09:33
We made a test version, it includes some bug fixes and a possible fix for the garbled texts. We have tested this version, but not extensively.
The download location is from my personal could storage, since we don't have another way to distribute 'daily' builds (yet).
Could you try Cura 3.2.1: https://stack.mybacklog.info/s/MgLnKXLL0P9ro4M ?

**Comment by KRAUZAH** [comment] 2018-02-10 18:00
Above fix worked for me. I downloaded Appesteijn's img and overwrote my 'Resource' folder with his and was able to add the printer without crashing. Haven't printed anything yet though.

**Comment by rejas** [comment] 2018-02-11 10:42
I can also confirm that the 3.2.1 test-version fixes the bug. In my case for the Renkforce RF100 printer who crashed with the official 3.2.0 version.

**Comment by mherodev** [comment] 2018-02-12 02:42
Aw, the file is no longer available.

**Comment by Ghostkeeper** [comment] 2018-03-06 08:26
Seems to be fixed now in these definitions.

**Closed by Ghostkeeper** 2018-03-06 08:26 UTC
Labels: Type: Bug
