### ISSUE TITLE
.25" THK BRACKET

### ISSUE THREAD

**Issue by GregECGS** [Ultimaker/Cura#17619] opened 2023-12-12 15:46 UTC
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Ultimaker 2+e

### Name abnormal settings

none that I am aware of

### Describe model location

CENTER OF PLATE

### Describe your model

.25" THICK BENT PLATE BRACKET

### Add your .zip here ⬇️

[FAILED_BRACKET.zip](https://github.com/Ultimaker/Cura/files/13650184/FAILED_BRACKET.zip)

**Comment by GregValiant** [comment] 2023-12-12 22:15
Thanks for the report.
The bracket doesn't have any errors and I didn't have any trouble slicing it in 5.6.0 or 5.5.0.
5.4.0 had issues.  Have you tried moving or rotating the bracket in Cura?  Sometimes changing the initial layer height by a little bit would fool the bug and allow slicing to finish.

This is a duplicate of numerous reports so I'll mark this and close it.

**Closed by GregValiant** 2023-12-12 22:15 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error :collision:
