### ISSUE TITLE
Z-Seam Choice seems to affect quality/extrusion

### ISSUE THREAD

**Issue by c-valentine** [Ultimaker/Cura#12568] opened 2022-06-20 18:32 UTC
### Application Version

5.0.0

### Platform

MacOS 12.4

### Printer

Anycubic Vyper

### Reproduction steps

Printed a simple round pipe model in PLA with Z-Seam Settings Sharpest Corner and Smart Hiding and got low quality of the outer wall around the Z-Seam, mainly slight blob-like overextrusion of the seam itself and some ringing-like irregularity mostly left of the seam. The rest of the print is completely homogenous (Pic 3).
<img width="308" alt="Sliced1" src="https://user-images.githubusercontent.com/107882057/174659771-9cf554ad-bab7-4ece-9783-9f1085ac0fd7.png">
![1](https://user-images.githubusercontent.com/107882057/174658546-5362a99e-3db0-4084-a6d4-f9f7c2b9db72.jpg)
![3](https://user-images.githubusercontent.com/107882057/174659626-b8160307-9bb0-46f6-89fc-16a0c5939da2.jpg)
![4](https://user-images.githubusercontent.com/107882057/174659680-d0b69c12-7c13-45a6-860a-788c91269dab.jpg)

Then printed the model with exactly same setting, only changing from sharpest Corner to User specified and positioning the seam left, where Sharpest Corner had also placed it, but without the minor variances.
<img width="349" alt="Sliced2" src="https://user-images.githubusercontent.com/107882057/174659973-80e8349b-db03-4019-8deb-842df7d0cc39.png">
![5](https://user-images.githubusercontent.com/107882057/174659936-91898b5e-5d5e-47cd-811a-b72cb31766e8.jpg)
![6](https://user-images.githubusercontent.com/107882057/174659955-24435a46-4e36-49ff-ab40-23449b8d1921.jpg)

### Actual results

The quality of the print and Z-Seam changed way beyond simple alignment, also visible esp. on the inner seam. Left Sharpest Corner, right User specified.
![7](https://user-images.githubusercontent.com/107882057/174660027-b332002a-8599-4a7b-b44a-dbba413659d5.jpg)
![8](https://user-images.githubusercontent.com/107882057/174660042-6f774e6c-ecce-43c1-bdf5-14de30d90400.jpg)

### Expected results

Changing seam position should not have such an impact on overall quality or elsewise, quality should not be inferior when having Sharpest Corner on.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

None atm

**Comment by HOLLY-DION** [comment] 2022-06-25 20:47
I also tried to print a round model, choosing the sharpest angle, and the Z-seam setting resulted in a low quality outer wall.
The position of Z-seam is actually the result of using random.
The Z-seam problem in the 5.0 version is a real headache for me.

**Comment by Ghostkeeper** [comment] 2022-07-08 13:01
Which vertex of those layers would you say has the sharpest angle?

Your model, theoretically, has a regular polygon as cross section on those layers. Regular polygons have the same angle at every vertex, and so the sharpest angle is a tie. However the STL vertices and the printed coordinates are both rounded to some finite resolution, which causes some angles to be slightly sharper than others. What's more, the a triangular mesh will not be a regular polygon, nor the same polygon at every layer, since every surface consists of 2 triangles that vary in width in every cross section. Combined with resolution reduction for the g-code output, different vertices will be removed on every layer, causing a meaningful difference in the angle too even beyond rounding errors.

Choosing the sharpest corner of a circle approximation inherently causes an arbitrary vertex to be chosen. The actual results are really what I'd expect.
We do a minor "bias" to the corner by X coordinate to combat rounding errors, but more than rounding errors should not be done.

> Changing seam position should not have such an impact on overall quality or elsewise, quality should not be inferior when having Sharpest Corner on.

I disagree there. If Sharpest Corner was always a superior or equal option, we would remove the entire setting and not allow any other choice to be made. There are always cases where one option is inferior to another. You have such a case for Sharpest Corner. The problem is though that higher up in your model, Sharpest Corner is a better option. So for the print as a whole it becomes a trade-off without more capability to customise it for each part of the print.

I suggest that you try the Shortest option (which is also not ideal, but maybe you get lucky).

We won't fix this since it seems to be behaving as expected.

**Closed by Ghostkeeper** 2022-07-08 13:01 UTC
Labels: Type: Bug, Status: Triage
