### ISSUE TITLE
Support under floating molten filament

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ultimaker/Cura#2415] opened 2017-09-11 18:38 UTC
Can this be avoided?
Can Cura change / add support under Z steps where filament oozes in mid-air?
![ice_screenshot_20170911-213140](https://user-images.githubusercontent.com/30949968/30290772-4de52084-9739-11e7-8f90-5066bb83165e.png)

EDIT:
Problem solved using **Extra Skin Wall Count** in the experimental section:
![ice_screenshot_20170912-123855](https://user-images.githubusercontent.com/30949968/30320663-fb85d616-97bb-11e7-8598-e5085ccb901c.png)

**Comment by smartavionics** [comment] 2017-09-11 19:28
One of the reasons that the Expand Skins Into Infill setting was created was avoid problems caused by skin drooping into the gaps when the infill density is low. I would have thought looking at the image above that the skin was sufficiently expanded to the left to avoid a problem. But if not, all you have to do is increase the skin expand distance. Of course, you could also increase the number of skin layers.

**Comment by Thisismydigitalself** [comment] 2017-09-12 05:39
Thank U.
I played with Expand skins and more layers. This is nice but not what i was looking for as this adds more print time, more material, heavier part but at the end it does not solve this problem. i was under the impression that the infill algorithm would know and structure the support in such a way that it will foresee this and fill the gaps.

"Mind the gap"

**Comment by smartavionics** [comment] 2017-09-12 06:16
I can see that expanding the skins takes longer and weighs more (you don't get something for nothing) but why does it not solve the problem? The finished skin should not show blemishes due to the gaps between the infill.
As far as I am aware, the infill mechanism is not aware of the structure above that it is supporting and so the positioning of the strands of infill is not influenced at all by what is above.

**Comment by konvoj** [comment] 2017-09-12 07:19
I had issues with this feature in the past. If the infill is sparse (say 10%) and there is shallow angle of the top layer, then Expand Skins tend to curl up which can lead to hitting the hotend and losing of steps -> failed print.
Some strategy to add perimeters rather than zig-zag pattern would solve this completely.

**Comment by smartavionics** [comment] 2017-09-12 08:02
> I had issues with this feature in the past. If the infill is sparse (say 10%) and there is shallow angle of the top layer, then Expand Skins tend to curl up which can lead to hitting the hotend and losing of steps -> failed print.

I have never had that happen but I can see how it could be possible with some filaments, maybe temperature related?

> Some strategy to add perimeters rather than zig-zag pattern would solve this completely.

That's an interesting thought.

**Comment by Thisismydigitalself** [comment] 2017-09-12 08:11
> Some strategy to add perimeters rather than zig-zag pattern would solve this completely.
+1

**Comment by smartavionics** [comment] 2017-09-12 08:32
Have you tried setting the Extra Skin Wall Count in the experimental section?

**Comment by Thisismydigitalself** [comment] 2017-09-12 08:53
Didn't know this exists.
Let me check..

**Comment by Thisismydigitalself** [comment] 2017-09-12 09:07
Nice!
This seems to have the potential of meeting the challenge 👍 . What i am missing is a way to animate the gcode to know the sequence and what comes first. How do I know if the inner green wall will take place before zigzag takes place? I've got "Infill before walls" unchecked so hoping this will do the trick for me.

**Comment by smartavionics** [comment] 2017-09-12 09:33
Looking at the code, it should generate the walls before the skin.

I have recently discovered a free slicer that has a really good gcode viewer called CraftWare. You can load your Cura generated gcode into that and wizz through the lines on each layer seeing exactly the order in which stuff is printed.

**Comment by smartavionics** [comment] 2017-09-12 09:35
BTW, they have just moved that setting from the experimental to the wall section so that's where it will be in the next release.

**Comment by Thisismydigitalself** [comment] 2017-09-12 09:43
Cool stuff!
I had CraftWare installed but never really used it as i didn't find it intuitive as Cura is.
You are correct - Gcode shows walls comes before the chicken, Oops... I meant to say the Zigzag.
![ice_screenshot_20170912-123855](https://user-images.githubusercontent.com/30949968/30319065-8ca9f7bc-97b7-11e7-86c5-2cdc85949d1c.png)

Boy, now i wish for Cura to have such an amazing gcode animator.

**Comment by konvoj** [comment] 2017-09-12 10:59
+1
Looks pretty cool.

**Comment by Thisismydigitalself** [comment] 2017-09-13 10:57
I was so blown away by Carftware engine that i tried again to work with it and again.. it just don't talk to me. the GUI looks amazing, the Gcode Animator is nothing less than genius but.. User interface not even remotely close to the intuitive GUI of Cura. I don't know why - Craftware just don't speak my language.

BIG thank you for all those who contribute to Cura. great job. All you need now is to surprise us with a gcode animator :)

**Comment by Ghostkeeper** [comment] 2017-09-20 08:56
Animating the g-code is hard™. They did a good job in Craftware to get that working so efficiently.

**Closed** 2017-09-20 08:56 UTC
