### ISSUE TITLE
Error Slicing Hueforge files

### ISSUE THREAD

**Issue by AnthonyD1204** [Ultimaker/Cura#15889] opened 2023-06-24 01:19 UTC
### Cura Version

5.4.0

### Operating System

Windows

### Printer

Sovol Sv01 Pro

### Describe your model

No, model was created with Hueforge, first time trying to print such file

### Add your .zip here ⬇️

[SSL_rose_Front_180x195.zip](https://github.com/Ultimaker/Cura/files/11854114/SSL_rose_Front_180x195.zip)

Seems like cura will not slice files/models made with the Hueforge software and error message is of no help. Would be useful to have actual reasoning to why the slice fails in future error messages.

**Comment by MariMakes** [comment] 2023-07-17 15:02
Hey @AnthonyD1204,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 
I've not heard about HueForge, that is pretty cool 😍 

This mesh seems faulty, I'm getting an error message:
![image](https://github.com/Ultimaker/Cura/assets/40423138/16202c72-0588-451a-8e19-305640d3e12c)

Have you tried doing a quick mesh fix with the Meshtools Plugin? 
You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that doesn't fix it you can try a more elaborate mesh fixer like https://myminifactory.github.io/Fast-Quadric-Mesh-Simplification/, or https://www.nanodlp.com/repair-3d-stl-file/.
Or you can use the "Make Solid" feature in AutoDesk MeshMixer. https://meshmixer.com/download.html

To me, it doesn't seem like a bug in Ultimaker Cura, since the mesh is faulty and Cura is not built to alter meshes in this way, that's what CAD software is for.

Apologies for any inconvenience caused by our delayed response. 
I'll be closing this issue. I hope you understand.

**Closed by MariMakes** 2023-07-17 15:03 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:
