### ISSUE TITLE
krnalruwili

### ISSUE THREAD

**Issue by Kralruwili** [Ultimaker/Cura#18789] opened 2024-04-01 17:21 UTC
kkkk

**Comment by rburema** [comment] 2024-04-02 07:27
Without a description, or file to reproduce the issue, this is mostly meaningless to us.

In fact, it has been reported as spam, so I'll close the issue.

If something is in fact going on with your Cura installation, please open a new issue and describe to us what the problem is, otherwise we can't help you.

**Closed by rburema** 2024-04-02 07:27 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:
