### ISSUE TITLE
Issues with plugins

### ISSUE THREAD

**Issue by leoheck** [Ultimaker/Cura#12023] opened 2022-04-29 18:50 UTC
### Application Version

5.0

### Platform

Linux

### Printer

none

### Reproduction steps

Launch cura

### Actual results

![Uploading image.png…]()

### Expected results

![image](https://user-images.githubusercontent.com/1277920/166007896-e6d6ad05-94a9-49b7-a32d-0f2d43c7cbf7.png)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/1277920/166007844-d0b6564d-6f7b-4b71-ac28-2d3569eae8f7.png)

**Comment by jedwards1230** [comment] 2022-04-30 04:47
Are you using the latest dev version of the [OctoPrintPlugin](https://github.com/fieldOfView/Cura-OctoPrintPlugin/releases) that supports the Cura 5.0 beta?

**Comment by leoheck** [comment] 2022-05-01 01:22
Curs is asking to uninstall old plugins. This is not working.

**Comment by fvrmr** [comment] 2022-05-02 08:51
Hi @leoheck thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11865, so I will close this issue.

**Closed by fvrmr** 2022-05-02 08:51 UTC
Labels: Type: Bug
