### ISSUE TITLE
"api-ms-win-core-path-l1-1-0.dll is missing"

### ISSUE THREAD

**Issue by The-Watching-Tiger** [Ultimaker/Cura#13415] opened 2022-09-30 12:47 UTC
### Application Version

5.1.1

### Platform

Windows 7 Ultimate

### Printer

Creality Ender 3v 2

### Reproduction steps

I downloaded and installed the Ultimaker Cura 5.1.1 after launching the Software, an error occurs saying: "api-ms-win-core-path-l1-1-0.dll is missing"

### Actual results

I think maybe i should look for a patch for Ultimaker Cura 5.1.1
I tried to uninstall and reinstall the software and i tried the Beta version of cura too.

### Expected results

Maybe some files are dameged or being removed from my system, i could use to install the cura on another computer but i would apriciate your help anyway.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Error](https://user-images.githubusercontent.com/114744495/193272942-4e66ff9a-c343-4a0e-8f7b-38555df7a4f3.png)
![system_error](https://user-images.githubusercontent.com/114744495/193272946-500c4565-1b9f-4488-ba45-0a39dc5b1f13.png)

**Comment by vikmaks1** [comment] 2022-09-30 12:58
It is due to incompatible operating system, newer Python which is used for the current Cura versions does not support Windows 7. So you are either stuck with older versions or use a computer that is upgradable to Windows 10.

**Comment by MariMakes** [comment] 2022-09-30 14:50
Hey all!

@vikmaks1 is right! Windows 7 is indeed not on our supported Operating System list.
For that, you'll have to go back to Cura 4.10.

More about it here:
https://support.ultimaker.com/hc/en-us/articles/360011889579

I'll close the issue since it's expected behavior 
Happy Printing 😄

**Closed by MariMakes** 2022-09-30 14:50 UTC
Labels: Type: Bug, Status: Triage
