### ISSUE TITLE
Slicing failed due to unexpected error

### ISSUE THREAD

**Issue by toto-w** [Ultimaker/Cura#13954] opened 2022-12-02 14:29 UTC
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Prusa based

### Reproduction steps

I Chose "tree support" placed only onto the bed. The I pressed "Slice" button.
If I chose "place everywhere" slicing works.

### Actual results

"unexpected error". No Gcode. 

### Expected results

No error. Gcode.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[PI3MK2_Red_Dragon_Wyrmling.zip](https://github.com/Ultimaker/Cura/files/10141809/PI3MK2_Red_Dragon_Wyrmling.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/10141864/cura.log)

**Comment by MariMakes** [comment] 2022-12-02 16:11
Hy @toto-w,

Thanks for your report 👍

I can reproduce your slicing error but I've also found a workaround.
If you move your model slightly from the center of the buildplate you can slice it with the settings that you want. 
![image](https://user-images.githubusercontent.com/40423138/205335565-740b7089-d7ef-4ae3-b2fb-a2583b603485.png)

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13643
Thanks for the report that, helps us to get to the root cause easier since we've seen a quite a number reports on this issue. 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/13643

**Closed by MariMakes** 2022-12-02 16:11 UTC
Labels: Type: Bug, Status: Triage
