### ISSUE TITLE
I added customer support and it doesn't get slicing

### ISSUE THREAD

**Issue by CalvinYohannes** [Ultimaker/Cura#15807] opened 2023-06-19 11:16 UTC
### Cura Version

5.4.0-beta.1

### Operating System

Windows 11

### Printer

Creality Ender 3 S1

### Name abnormal settings

I added customer support and it doesn't get slicing

### Describe model location

90 degrees

### Describe your model

added customer support

### Add your .zip here ⬇️

[CE3S1_Feet.zip](https://github.com/Ultimaker/Cura/files/11787465/CE3S1_Feet.zip)

**Comment by MariMakes** [comment] 2023-06-21 10:39
Hey @CalvinYohannes 

Welcome to the UltiMaker Cura Github 🚀
Thanks for using the beta and reporting your issues👍

You are not the first person to report this, I'll mark this issue as a duplicate of https://github.com/Ultimaker/Cura/issues/15836
I'm bringing it up to the team to see what they can do to improve it before the Stable release,

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/15836

**Closed by MariMakes** 2023-06-21 10:39 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:, PreRelease :bug:
