### ISSUE TITLE
Raft does not print completely

### ISSUE THREAD

**Issue by yanshengk** [Ultimaker/Cura#12276] opened 2022-05-20 13:22 UTC
### Application Version

5.0.0

### Platform

macOS Monterey 12.4

### Printer

Custom FFF Printer

### Reproduction steps

1. Build Plate Adhesion Type changed to Raft. 
2. Raft Extra Margin changed to 10.0 mm. 
3. Raft Air Gap changed to 0.14 mm. 
4. Sliced the model. 

### Actual results

The third layer of the raft did not print completely. 

Layer 2
<img width="2048" alt="Layer_2" src="https://user-images.githubusercontent.com/83659771/169535108-858d9c61-e790-4e81-806f-cf02d8632e49.png">

Layer 3
<img width="2048" alt="Layer_3" src="https://user-images.githubusercontent.com/83659771/169535130-caa3a178-66fc-4d81-b4d4-84dea3a6d32f.png">

### Expected results

The third layer should be printed completely covering the whole layer 2. 

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Project file and screenshots of the bug were included in the ZIP file.
[Archive.zip](https://github.com/Ultimaker/Cura/files/8740436/Archive.zip)

**Comment by Vandresc** [comment] 2022-05-30 10:56
Hi @yanshengk thank you for your feedback, I could indeed reproduce the issue with your project file. Will bring this up with the rest of the team.

**Comment by Vandresc** [comment] 2022-05-31 09:57
Devs, see CURA-9349 for our internal reference.

**Comment by yanshengk** [comment] 2022-06-02 03:33
> Hi @yanshengk thank you for your feedback, I could indeed reproduce the issue with your project file. Will bring this up with the rest of the team.

Thank you.

**Comment by GregValiant** [comment] 2023-01-09 14:44
Hi @MariMakes 
This is a follow up to your request in #13353 
Here is the project file sliced as I received it.  This is showing layer 3 with the model at X0 Y0
![image](https://user-images.githubusercontent.com/64202104/211334019-959c5e50-8f2e-49dc-8805-d624c3b503c8.png)

Here is layer 3 when moved to X-30 Y0
![image](https://user-images.githubusercontent.com/64202104/211334296-7823ed9a-7bc9-480d-9adc-ab69cb51878a.png)

**Comment by snebragd** [comment] 2023-02-05 15:44
Hej! I ran into this very same problem today. Quite annoying as the top raft layer was hiding the problem in the preview. I only noticed mid print. Cura 5.2.2, MacOs 13.1

![image](https://user-images.githubusercontent.com/6013398/216829293-88c6ff43-f4b3-4cbb-8a6d-c992a2ecbd51.png)

**Comment by MariMakes** [comment] 2023-08-25 13:59
Quick update from our side 👋

Good News! We are cleaning up our open issues and stumbled upon your issue about the raft top layer. We made some improvements in the buildplate adhesion and it seems like we cannot reproduce your issue in the upcoming 5.5 which means that the issue is fixed!

![image](https://github.com/Ultimaker/Cura/assets/40423138/8c03769a-e798-49dd-a18d-b4738e64d243)

I'll be closing this issue, and you can use the fix in the upcoming 5.5 release.

**Closed by MariMakes** 2023-08-25 13:59 UTC
Labels: Type: Bug, Status:  On Backlog
