### ISSUE TITLE
[4.1.0] Red/Blue axis scaling controls swapped on support blocker

### ISSUE THREAD

**Issue by jpcuzzourt** [Ultimaker/Cura#5916] opened 2019-06-20 06:30 UTC
**Application version**
4.1.0 (With Creawsome 'mod' but I don't think it's related)

**Platform**
Windows 10 64 bit

**Printer**
Creawsome Creality Ender 3 pro 

**Reproduction steps**
Add a support blocker. Select the support blocker, and the scaling tool. Turn off 'uniform scaling' and and try to scale vertically with the BLUE axis handle.

**Actual results**
Support blocker scales in the direction of the RED axis.

**Expected results**
Support blocker scales in the direction of the BLUE axis.
[Pi_Cam](https://user-images.githubusercontent.com/15769074/59825900-367f2d00-9303-11e9-9497-918505afae8c.PNG)
[Pi_Cam.3mf.zip](https://github.com/Ultimaker/Cura/files/3309060/Pi_Cam.3mf.zip)

**Additional information**
 Similarly, scaling with the RED handle scales in the BLUE direction. GREEN handle works normally.

**Comment by Ellecross** [comment] 2019-06-20 08:56
Waa! You're right. This is a bug. I'll raise it with Cura team. 
Thanks for bringing this up.

**Comment by jpcuzzourt** [comment] 2019-06-21 04:41
It's the least I can do. And probably also the most!

**Comment by Vandrasc** [comment] 2019-06-21 08:52
Yes, there are indeed some issues related to non-uniform scaling and will be resolved once we implement CURA-5630, which is currently on our backlog.

**Comment by Ghostkeeper** [comment] 2019-06-21 09:21
Sorry, this is a duplicate of https://github.com/Ultimaker/Cura/issues/4136. I'm closing this one. Please continue conversation there.

**Closed by Ghostkeeper** 2019-06-21 09:21 UTC
Labels: Type: Bug
