### ISSUE TITLE
Top layers added even when set to zero for some bodies in print

### ISSUE THREAD

**Issue by emil-e** [Ultimaker/Cura#8028] opened 2020-07-04 07:59 UTC
**Application version**
4.6.1

**Platform**
Windows 10

**Printer**
BLV mgn cube

**Reproduction steps**
1. Set top layers to 0
2. Slice

**Screenshot(s)**
![Annotation 2020-07-04 095726](https://user-images.githubusercontent.com/5737870/86508018-d4de1380-bddc-11ea-8ac3-4e57c48a8f4c.png)

**Actual results**
Top layers are added for some bodies in the print.

**Expected results**
No top layers added.

**Project file**
[CFFFP_Diffusers^digitmodule.zip](https://github.com/Ultimaker/Cura/files/4872263/CFFFP_Diffusers.digitmodule.zip)

**Additional information**
Changing the layer height removes the buggy top layers, for example setting it to 0.21 or 0.25 removes the issue.

**Comment by smartavionics** [comment] 2020-07-05 05:20
This doesn't happen for me using a development version of Cura so perhaps whatever was the problem has been fixed?

![Screenshot_2020-07-05_06-19-12](https://user-images.githubusercontent.com/585618/86526119-9d787100-be87-11ea-95d8-0a964198e353.png)

**Comment by fieldOfView** [comment] 2020-07-05 06:44
I can't reproduce it with Cura 4.6 either

**Comment by Ghostkeeper** [comment] 2020-07-07 09:21
Me neither. I noticed that you had a Linear Advance setting which caused a warning in my log, but also with that plug-in installed the result was the same. I tried several layer heights as you said but I can't reproduce the issue.

I notice though that the settings used while you made that screenshot are somewhat different than what is used in this project file. For one, you're using a skirt but the project file uses a brim.

Was the project file made while the bug was reproducing?

**Comment by emil-e** [comment] 2020-07-13 14:34
How about this one then? In this one, solid layers are added in the middle of the model rather than at the top but I'm suspecting it might be caused by the same thing.

[CFFFP_advanced diffuser.zip](https://github.com/Ultimaker/Cura/files/4913135/CFFFP_advanced.diffuser.zip)

**Comment by emil-e** [comment] 2020-07-13 14:35
![image](https://user-images.githubusercontent.com/5737870/87317088-d4552380-c526-11ea-95ae-39cd27ad4397.png)

**Comment by smartavionics** [comment] 2020-07-13 15:28
Hi, I just sliced this latest model using the same settings from your earlier project file and got no solid layers anywhere apart from the bottom 3 layers.

**Comment by emil-e** [comment] 2020-07-13 15:59
@smartavionics How about this latest project with the settings from that file then?

**Comment by smartavionics** [comment] 2020-07-13 16:14
The file you provided today contains only a model and no settings. You need to do File -> Save, not File -> Export.

**Comment by emil-e** [comment] 2020-07-13 16:16
I’m so sorry, I will get you a saved rather than exported file ASAP.

**Comment by emil-e** [comment] 2020-07-13 17:28
[CFFFP_advanced diffuser project.zip](https://github.com/Ultimaker/Cura/files/4914115/CFFFP_advanced.diffuser.project.zip)

Here you go!

**Comment by emil-e** [comment] 2020-07-13 17:53
Okay, trying it on my machine gives my a missing layer (and thus a solid layer added above that as a bottom layer) no matter what profiles I choose. I even tried a different printer (Ultimaker S5) but that didn't help.

**Comment by smartavionics** [comment] 2020-07-13 17:56
I just sliced that latest project and got no missing layers or solid layers above layer 3.

There must be some difference between Cura 4.6.1 and what I am using here.

**Comment by smartavionics** [comment] 2020-07-13 18:43
You could try with my Cura build. You can find them at https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0. My releases can be installed alongside the UM releases. Please read the README.md file there before installing.

**Comment by Ghostkeeper** [comment] 2020-07-14 14:38
I can see it happening in Cura 4.6 indeed with that last project:
![image](https://user-images.githubusercontent.com/2448634/87438410-c4554680-c5ef-11ea-86bb-38243acf6e92.png)

It seems that this is caused by bugs in the Maximum Resolution algorithm. If I change the maximum resolution to 0.1, the problem disappears. This algorithm was reworked for Cura 4.7, so such bugs should be removed now.

Sorry for the hassle! Fiddle around with the Maximum Resolution a bit until you find a value that works. It'll be fixed in the upcoming release.

**Closed by Ghostkeeper** 2020-07-14 14:38 UTC
Labels: Type: Bug

**Comment by emil-e** [comment] 2020-07-14 18:22
@Ghostkeeper Excellent, thanks for the feedback!
