### ISSUE TITLE
[4.8.0] Preview tab causes total computer crash on new M1 Macs

### ISSUE THREAD

**Issue by apbarratt** [Ultimaker/Cura#9516] opened 2021-04-07 08:39 UTC
**Application version**
4.8.0

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)
macOS Big Sur Version 11.2.3
MacBook Pro (13-inch, M1, 2020)
Chip Apple M1
Memory 16GB

**Printer**
Ender 3 using Octoprint

**Reproduction steps**
1. Slice any model
2. Choose the Preview tab

**Screenshot(s)**
https://imgur.com/a/ltdnsoM
I don't always get an immediate visual error, but this is one of them.

**Actual results**
CURA immediately freezes up, often it's just greyed out but on one occasion I did get the more exciting visual error in the screenshot above.
At this point I'm able to force quit CURA and basic mouse control etc still seems to be working, however, I can no longer interact with my other apps (Safari, Finder etc) and I find myself forced to hold down the power button to turn my machine off and on.
Other than this, CURA seems to be functioning correctly.

**Expected results**
Preview pane should load correctly.

**Project file**
This seems to happen for all STLs I download and attempt to slice.

**Log file**
Sorry, my expertise is not brilliant here.  Perhaps if someone with more experience can recreate the issue they could find this :) 

**Additional information**
Whilst this seems to be a graphics based issue, it doesn't seem to be a problem on the preparation screen.
Also, there are some other issues that seem to mention this, but I can't tell if they're the same as they seem broader in scope (i.e. suggesting it's Big Sur in general, which I found to work correctly before upgrading to this new MacBook Pro).
Either way, I shan't be hurt if you decide to delete this as a duplicate :)

**Comment by nallath** [comment] 2021-04-07 08:56
Duplicate of #8745 

Could you try if the error is still there in the 4.9 beta?

**Closed by nallath** 2021-04-07 08:56 UTC
