### ISSUE TITLE
opening "Setting Visibility" no longer scrolls the selected Category into view

### ISSUE THREAD

**Issue by BloodyRain2k** [Ultimaker/Cura#9896] opened 2021-05-23 17:04 UTC
### Application Version

4.9.1

### Platform

Win 7 x64

### Printer

CR6

### Reproduction steps

Switch from 4.8 to 4.9.1 that's all.

In 4.9.1 opening the "Setting Visibility" dialog through either way, clicking the cog in the Category Header or right clicking a setting and opening it from there, does NO longer scroll to the category in question.

The Arachne Beta however seems to be based on 4.8, as it still does it just like 4.8: scrolling the selected category into view.

### Actual results

Any opening of the "Setting Visibility" dialog shows just the top of the list, regardless of previously selected category.

### Expected results

Scrolling the previously selected category into view, like in 4.8 and Arachne Beta.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

.

**Comment by fvrmr** [comment] 2021-05-25 07:58
Hi @BloodyRain2k thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9621, since it is a duplicate I will close this issue.

**Closed by fvrmr** 2021-05-25 07:58 UTC
Labels: Type: Bug
