### ISSUE TITLE
Cura refuse to load any STL file

### ISSUE THREAD

**Issue by RoyalShooter** [Ultimaker/Cura#7039] opened 2020-01-28 23:01 UTC
**Application version**
4.4.1
(The version of the application this issue occurs with.)

**Platform**
Windows 10 Version 1909
Ryzen 3800X
5700XT
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)

**Printer**
Ender-3
(Which printer was selected in Cura?)

**Reproduction steps**
Load Ender3_Level_Test_v2.gcode to print = success

Load my Body1.stl to print = fail

Export again to see did something gone wrong in the exportation step = fail

Uninstall 4.4.1 and tried to Load my Body1.stl in 4.3.0 = fail

Uninstall 4.3.0 and tried to Load my Body1.stl in 4.2.x = fail

Go back to 4.4.1 and tried other stl file to see if my model corrupted, I make a new simple shape just to see if my body1.stl is too complicated. Body2.stl = fail

Tried to load Single_Layer_Disc.stl from the ender3 levelling file from thingiverse to see if my cura working at all. = fail

**Screenshot(s)**
![capture](https://user-images.githubusercontent.com/22939113/73313042-0247e500-41df-11ea-9d6c-7536462da753.gif)

**Actual results**
Cura fail to load any STL file

**Expected results**
STL should load into cura and shows the model on screen

**Project file**

[Body1.zip](https://github.com/Ultimaker/Cura/files/4125196/Body1.zip)

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/4125200/cura.log)

**Additional information**
I got my new PC last month and today I finally have time to get back into 3d printing. I install the latest cura 4.4.1 and it is not working so I go ahead and delete all my old config transferred from my old PC and reinstall it again. Then I am able to go into the menu screen. I can print out Ender3_Level_Test_v2.gcode, but then I go ahead into fusion 360 and try to make a model and print from stl it fails to load. The loading prompt just keep running. I then go ahead and uninstall(+delete %appdata% cura file) and install 4.3.0 and 4.2.x to tried but both fail to load stl again. Then I try to get back into 4.4.1 and tried with different stl file to see if my file corrupted and the 3 stl file I tested none of those work.

My setup is a ender 3 with OctoPrint
For plugin, I had Auto-Orientation and OctoPrint Connection installed

**Comment by Ghostkeeper** [comment] 2020-01-30 14:23
Hmm, I can load the file fine on this side.

![Screenshot from 2020-01-30 15-20-16](https://user-images.githubusercontent.com/2448634/73457585-28eb5480-4374-11ea-94cc-b54647f3ace0.png)

In the log file it shows also that it loaded the model correctly:

```
2020-01-28 08:52:33,054 - INFO - [Thread-5] STLReader.STLReader.load_file [46]: Using NumPy-STL to load STL data.
2020-01-28 08:52:33,057 - DEBUG - [Thread-5] UM.Mesh.MeshData.calculateNormalsFromVertices [482]: Calculating normals took 0.0 seconds
2020-01-28 08:52:33,058 - DEBUG - [Thread-5] STLReader.STLReader._read [97]: Loaded a mesh with 156 vertices
2020-01-28 08:52:33,062 - DEBUG - [Thread-5] UM.Mesh.MeshData.approximateConvexHull [439]: approximateConvexHull(target_count=1024) Calculating 3D convex hull took 0.0020003318786621094 seconds. 8 input vertices. 8 output vertices.
```

But somehow at the end it doesn't seem to get added to the build plate for some reason?

**Comment by nallath** [comment] 2020-06-22 07:38
Since we've not been able to reproduce this I'm going to close this issue. If this still is an issue, feel free to re-open it or create a new ticket.

**Closed by nallath** 2020-06-22 07:38 UTC
Labels: Type: Bug
