### ISSUE TITLE
Slicing Error

### ISSUE THREAD

**Issue by amjandert** [Ultimaker/Cura#14768] opened 2023-03-04 20:36 UTC
### Application Version

5.2.2

### Platform

windows 11

### Printer

Creality Ender Pro 3

### Reproduction steps

tried to slice 

### Actual results

error

### Expected results

the slice should have worked

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

![Screenshot 2023-03-04 142829](https://user-images.githubusercontent.com/126986271/222927368-7ed3b7d3-3c8d-49ee-8694-d5946dd97f59.jpg)

**Comment by MariMakes** [comment] 2023-03-07 12:36
Hey @amjandert,

Welcome to the Ultimaker Cura Github 🚀 

Is it possible that your printjob is located at 0, 0, 0, and it slices if you move it a little away from the center of the buildplate? 
Then it might be a duplicate of https://github.com/Ultimaker/Cura/issues/13643

The new Cura 5.3 Beta contains the fix for this. 
You can download it here: https://github.com/Ultimaker/Cura/releases/

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Closed** 2023-04-22 00:17 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage, Slicing Error :collision:
