### ISSUE TITLE
GUI: Snap to grid when placing models

### ISSUE THREAD

**Issue by DoctorArr** [Ultimaker/Cura#10697] opened 2021-10-29 01:12 UTC
### Is your feature request related to a problem?

Unable to snap to grid when positioning a model.

https://github.com/Ultimaker/Cura/issues/7383

The sheer arrogance this was dismissed is unbelievable. Get over your selves and just implement it.

### Describe the solution you'd like

Ability to snap to grid in the same way as many mature applications of a similar nature have.
DO NOT dismiss this.

### Describe alternatives you've considered

Swapping to another slicer

### Affected users and/or printers

ALL

**Comment by DoctorArr** [comment] 2021-10-30 13:52
"backlog full of new features"
"could you explain a bit more why this is important to have in Cura"

This is a day one basic feature. It's like having the ability to turn the wheel in a car or being able to control heat when cooking, it's a basic feature.

Show me the list of new features and I'll prioritize them for you because somewhere something has gone wrong.

**Comment by fieldOfView** [comment] 2021-10-30 14:41
> Show me the list of new features

Here's a start: https://github.com/Ultimaker/Cura/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+New+Feature%22

But that list is not exhaustive and does not include most of the features that are prioritized by Ultimaker itself for their own users. Please realize that your priorities may not align fully with my priorities, or the priorities of Ultimaker printer users, so please take that into account when you prioritize that list. Also try to not piss off other github users by deprioritizing their requests. Good luck and thanks for helping out!

**Comment by nallath** [comment] 2021-11-01 11:01
> Show me the list of new features and I'll prioritize them for you because somewhere something has gone wrong.

Our vacancy for Product Owner is already taken, sorry. You can of course suggest / argue why a certain issue has the wrong priority, but the final responsibility for that lies with our Product Owner. Also note that this list is not exhaustive; there are also requests that come from internal stakeholders within Ultimaker that also need to be prioritized.

**Comment by NKT00** [comment] 2021-11-01 11:04
What advantage would snapping the models to the grid even have? It's a slicer, not a CAD package. You just drag them to where you want them, then save if you feel you'll need it in future. It wouldn't save even a second.

**Comment by fvrmr** [comment] 2021-11-01 15:00
Based on the discussion above, I will close this as a duplicate of https://github.com/Ultimaker/Cura/issues/7383

**Closed by fvrmr** 2021-11-01 15:00 UTC
Labels: Type: New Feature
