### ISSUE TITLE
Slicing generates a vertical artifact in cylinder based model

### ISSUE THREAD

**Issue by steveb48** [Ultimaker/Cura#11648] opened 2022-03-11 18:18 UTC
### Application Version

4.13.1

### Platform

macOS 12.2.1

### Printer

Ender 5 Plus

### Reproduction steps

Import model from Fusion 360
Select Ender 5 Plus (same problem if you select Ender 5 Pro)
Slice
Switch to Preview

### Actual results

View the edge of the model and you'll see a vertical line
I wasn't able to find any setting which would change it.
This appears when printed as well.
<img width="672" alt="Screen Shot 2022-03-11 at 10 08 29 AM" src="https://user-images.githubusercontent.com/15385293/157925215-44decd83-da6d-41ed-87ed-3db30f434c92.png">
[Cylinder artifact problem.3mf.zip](https://github.com/Ultimaker/Cura/files/8234354/Cylinder.artifact.problem.3mf.zip)

### Expected results

No artifacts 

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Not sure what's required here. Project and Screenshot were uploaded above.

**Comment by 64bittuning** [comment] 2022-03-11 18:44
That is the seam. Cura isnt doing anything wrong.

**Comment by steveb48** [comment] 2022-03-11 18:51
Thanks for the speedy reply.

What seam are you referring to? If I model a cylinder in Fusion 360 (just an extruded circle), import it into Cura 
I see this “seam”. Simplify3d doesn’t appear to have the same issue although I’ve only viewed it on screen, not printed it.

Steve

**Comment by 64bittuning** [comment] 2022-03-11 20:22
Each layer has to start and end somewhere. 

![image](https://user-images.githubusercontent.com/47930605/157955903-3e05e660-702c-40a9-9636-b76e2e13784d.png)

**Comment by 64bittuning** [comment] 2022-03-11 20:23
Every layer has to start and stop somewhere...

https://www.youtube.com/watch?v=NU1kYEE3qrQ

**Comment by steveb48** [comment] 2022-03-11 21:02
Great video! Now I understand. 

thanks,
Steve

**Comment by fvrmr** [comment] 2022-03-14 09:20
Closing this issue since this is not a bug. 
Thank you @64bittuning for responding.

**Closed by fvrmr** 2022-03-14 09:20 UTC
Labels: Type: Bug
