### ISSUE TITLE
Cura will not allow selecting/modifying models more than once - Mac OS 11.0.1

### ISSUE THREAD

**Issue by cosworth99** [Ultimaker/Cura#8947] opened 2020-12-14 18:21 UTC
**Application version**
4.8.0

**Platform**
Mac OS 11.0.1 20B29

**Printer**
Tevo Tornado

**Reproduction steps**
1. Open Cura, modify loaded part and or settings.
2. Deselect part.
3. Cannot reselect part by clicking on it.
4. Can select part by using "select all" but cannot use left sidebar tools, part deselects.
5. Restarting application solves issue until step 1 and 2 are repeated.

**Screenshot(s)**
None needed since screenshot will not represent problem.

**Actual results**
Parts cannot be selected or modified after first selection or modification.

**Expected results**
Parts should be able to be selected via mouse and/or modified more than once.

**Project file**
None needed since bug is not represented by a file.

**Log file**
See attached log file. Last line:

2020-12-14 10:19:01,176 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [406]: file:///Applications/Ultimaker Cura.app/Contents/MacOS/plugins/plugins/PerObjectSettingsTool/PerObjectSettingsPanel.qml:221:47: Unable to assign [undefined] to qulonglong

[cura.log](https://github.com/Ultimaker/Cura/files/5690792/cura.log)

**Additional information**
N/A

**Comment by konskarm** [comment] 2020-12-15 08:20
We've had similar reports about issues with selecting objects on the buildplate on MacOS Big Sur. Closing this as a duplicate of https://github.com/Ultimaker/Cura/issues/8745.

**Closed by konskarm** 2020-12-15 08:20 UTC
Labels: Type: Bug
