### ISSUE TITLE
No Seam Corner Preference Cura 5.9

### ISSUE THREAD

**Issue by Btl64** [Ultimaker/Cura#19957] opened 2024-11-26 23:06 UTC
### Cura Version

5.9

### Operating System

Windows 10

### Printer

Elegoo Neptune

### Reproduction steps

Seam Corner Preference is disabled when User Specified is picked in Walls in Cur 5.9, but is available on previous versions, i.e., 5.7 & 5.8

### Actual results

Not able to choose Smart Hiding

### Expected results

I would expect it to be available like earlier versions.

### Add your .zip and screenshots here ⬇️

![Seam Corner Preference 1](https://github.com/user-attachments/assets/2c2d3b95-a984-4ef8-9f71-dbce7232d2fa)
![Seam Corner Preference 2](https://github.com/user-attachments/assets/c7bc0274-b0a9-4458-8902-60a128d4a4b5)

**Comment by GregValiant** [comment] 2024-11-26 23:58
Thanks for the report.
A lot of work was done to the Z-seam.  The new settings for "Scarf Seam" are in the Experimental section.
"Seam Corner Preference" is only available when "Sharpest Corner" is selected.  For a couple of the others "Z-Seam on Vertex" has taken it's place.  If you select "Random" then there is no option to pick a corner.

This looks like "expected behavior" as it is the way the settings are called out in fdmprinter.def.json.  I'll remove the bug label and close this.  I hope you understand.

**Closed by GregValiant** 2024-11-26 23:58 UTC
Labels: Type: Discussion, Status: Under Investigation

**Comment by Btl64** [comment] 2024-11-27 02:23
I have a couple of models that I was able to create amazing seams when
sliced with the earlier versions in the way I described.  I haven't been
able to replicate the look with 5.9.  I'll just keep using the older
versions.

**Comment by GregValiant** [comment] 2024-11-27 12:54
The setting "Zseam on Vertex" was supposed to take it's place.  That one seems odd to me.
I've played with "Scarf Seam" and after some trial and error it appears to be working well.  They don't stick out which makes mating parts (like threads in particular) fit together better.
