### ISSUE TITLE
Slicer bug : Supports stop without adding value

### ISSUE THREAD

**Issue by JVaassen** [Ultimaker/Cura#17221] opened 2023-11-04 16:29 UTC
### Cura Version

5.3.0

### Operating System

Windows 11

### Printer

Ender 5

### Reproduction steps

Uploaded the model to Cura
Sliced it

### Actual results

The output is generated, but it doesn't make sense

### Expected results

Support continued to the top, or long support not even printed, just local support next to the notches.

### Add your .zip and screenshots here ⬇️

[CE5_Case_v2.zip](https://github.com/Ultimaker/Cura/files/13257164/CE5_Case_v2.zip)
![image](https://github.com/Ultimaker/Cura/assets/31225457/30a4067c-38b3-440b-87bd-34dae571fb6c)

**Comment by GregValiant** [comment] 2023-11-04 19:52
Thanks for the report.
The "Support Horizontal Expansion" of 1.0, and the "Support XY Distance" of 1.2 are coming into conflict.
The support within the slots is growing outward and that support structure is going up to meet it also has 1.0 HE so there is an overlap.
The only change I made here was to make the Support Horizontal Expansion 0.8.  That avoids the conflict and the support no longer needs to come up from the bed.
![image](https://github.com/Ultimaker/Cura/assets/64202104/18b8be12-64fc-4278-8921-402371908ec0)

Going the other way - this is with the Support Horizontal Expansion at 2.0. The greater width allows the structure coming up to merge with the slot structure.
![image](https://github.com/Ultimaker/Cura/assets/64202104/55bc6fa2-fe66-424b-b3fb-ca4f6e828d1c)

Given your settings this looks like expected behavior to me.  I'll go ahead and close this.  Let us know if you think that is premature.

**Closed by GregValiant** 2023-11-04 19:52 UTC
Labels: Type: Discussion, Status: Under Investigation
