### ISSUE TITLE
Cura is unusable after the last upgrade (4.9.0)

### ISSUE THREAD

**Issue by andreixk** [Ultimaker/Cura#9739] opened 2021-05-01 10:25 UTC
### Application Version

4.9.0

### Platform

Mac OS X Catalina: 10.15.7

### Printer

FLSUN QQ-S

### Reproduction steps

1. Update Cura
2. Open it.

### Actual results

Opening the app takes about 20s (before the update, it took 3-5s).
Panning/viewing the model is very laggy/choppy.
Scrolling through the settings is also very laggy.
Opening menus takes a couple of seconds.
When scrolling through printers menu, the scroll jumps and lags.
It also randomly crashes

### Expected results

Should work as before.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/6409390/cura.log)

I tried adding  the project file, the window shows error that you do not support them.

I downgraded to 4.8.0 - at least now I can use my printer again.

**Comment by fvrmr** [comment] 2021-05-03 12:06
Hi @andreixk thank you for your report.
What version of MacOS are you using?

**Comment by andreixk** [comment] 2021-05-03 12:08
> Hi @andreixk thank you for your report.
> What version of MacOS are you using?

Catalina: 10.15.7

**Comment by nallath** [comment] 2021-05-03 13:22
Do you have the sidebar plugin enabled?

**Comment by fieldOfView** [comment] 2021-05-03 13:26
The cura.log that was included suggests SidebarGUI is not involved.

**Comment by andreixk** [comment] 2021-05-03 14:02
> Do you have the sidebar plugin enabled?

I don't know, but I didn't install or enable any plugins since starting to use the app.

**Comment by nallath** [comment] 2021-05-04 07:52
The logs indicate that booting cura took ~7 seconds. I'm also not seeing anything in the logs that would indicate any slowdown.

**Comment by andreixk** [comment] 2021-05-04 09:45
> The logs indicate that booting cura took ~7 seconds. I'm also not seeing anything in the logs that would indicate any slowdown.

i'm not sure how long is the "boot" technically, but i count it from the time i click the app icon to the time i can start using it.

**Comment by nallath** [comment] 2021-05-04 11:09
The boot time is all the loading right before the UI is created. This is generally the slowest bit, but in your case it seems like it's the UI generation that is much slower.

**Comment by Ghostkeeper** [comment] 2021-05-13 22:28
Duplicate of https://github.com/Ultimaker/Cura/issues/6589.

**Closed by Ghostkeeper** 2021-05-13 22:28 UTC
Labels: Type: Bug
