### ISSUE TITLE
Print Setting Window

### ISSUE THREAD

**Issue by viper0078** [Ultimaker/Cura#8850] opened 2020-11-28 14:36 UTC
The print settings have so many items that it's hard to scroll through them.
I think it would be faster to divide it into tabbed pages for each section for quick access.

Depending on the settings, there are options that are hidden from view.
Instead of hiding them, why not gray them out?
Just change the color and the editing is possible.

**Comment by Ghostkeeper** [comment] 2020-12-01 12:54
Duplicate of https://github.com/Ultimaker/Cura/issues/8121.

We have tabs where it's still possible to view multiple tabs at the same time. And we have visibility presets that limit the length of the settings list.

Only some people like to make all settings visible and open all tabs, and then complain that the settings list is too long.

**Closed by Ghostkeeper** 2020-12-01 12:54 UTC
Labels: Type: New Feature

**Comment by viper0078** [comment] 2020-12-01 23:23
The tab I'm imagining is shown below.
![無題](https://user-images.githubusercontent.com/69872727/100808418-798d7b80-3477-11eb-8d47-c47e7ea546eb.png)

It depends on whether you need the visualization presets or not.
If people say it's too long, are they saying they don't need the parameters?
For those people, I guess you can use the presets.
I don't need the presets.
I can hide the ones I don't need by myself.

There is a search function, but for me it is not useful.
When adjusting parameters, I need to look at the values in each section from top to bottom to see if there are any relevant ones.
I don't use it in the list of search results because I'm likely to miss something.

I simply think it would be easier to access if each section was separated by tabbed pages, my personal preference.
I'm not complaining.
