### ISSUE TITLE
Very long Slicing time / Low Resource Utilization using supports with Ryzen

### ISSUE THREAD

**Issue by GiroroG66** [Ultimaker/Cura#12875] opened 2022-07-27 08:50 UTC
### Application Version

5.1.0

### Platform

Windows 10 Pro 64 bit 21H2 build 19044.1826

### Printer

Custom Printer (Anycubic Kobra Max)

### Reproduction steps

Slicing a large model (307.3mm x 276 x 406) with 0.1mm layer height, tree supports and infill supports in a high end consumer desktop PC (Ryzen 5900X, RX 6900, 32GB DDR4 3600, Hynix P41 nvme SSD)

### Actual results

Time to slice model is in excess of 30 minutes. My CPU fan spins up, but my HW Monitor shows <5% overall CPU utilization. GPU is essentially idle. 
I think the majority of this process is a single thread that is being repeatedly passed around the cores in a single CCX, but I am unable to find the bottleneck by monitoring my system utilization. 

### Expected results

I expect faster slicing times, or at least much higher resource utilization/Parallelization while the model is processing. 

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Project file share: [https://we.tl/t-WNn8ZAikoM](url)
[cura.log](https://github.com/Ultimaker/Cura/files/9196645/cura.log)
[polysculpt.com_2ears2teeth.zip](https://github.com/Ultimaker/Cura/files/9196649/polysculpt.com_2ears2teeth.zip)

**Comment by MariMakes** [comment] 2022-08-25 12:23
Hey @GiroroG66,

Thanks for your report 🎉 

I took a look at your amazing project file. I used a windows machine on Cura 5.1 to slice your model and for me it takes only 56 seconds to slice. When enabling tree support it takes twice as long.

I think your issue is related to: https://github.com/Ultimaker/Cura/issues/6066
We have an issue on our backlog to enable multi threading for tree support. 
It's been on our backlog for a while, so 🤞 fingers crossed that we have time to work on it. 

I'm closing this issue since it's a duplicate of https://github.com/Ultimaker/Cura/issues/6066 you can follow the progress there.

**Closed by MariMakes** 2022-08-25 12:23 UTC
Labels: Type: Bug, Status: Triage
