### ISSUE TITLE
Z Seam Alignment issue

### ISSUE THREAD

**Issue by scubamario** [Ultimaker/Cura#8704] opened 2020-11-06 14:15 UTC
**Application version**
Cura 4.8 Beta

**Platform**
Window 10

**Printer**
Ender 5 Plus

**Reproduction steps**
1. I was thinking of printing the little Among Us characters from Thingiverse for my Son (https://www.thingiverse.com/thing:4615103) and decided to give it a try with the new Cura 4.8. I was using the same Z Seam profile (Z Seam Alignment:User Specified / Z Seam Position:Back / S Seam X:175.0 / Z Seam Y:350) from the previous Cura 4.7.1 and when the print was done, I noticed in the back of the print, the Z Seam was diagonal on both parts.
2. I decided to print the same file but with Cura 4.7.1 and the seam was perfect.

**Screenshot(s)**
![IMG_20201106_090410_7](https://user-images.githubusercontent.com/71041079/98375259-e4ca6600-200f-11eb-9724-553ca1d16f49.jpg)
![IMG_20201106_090355_9](https://user-images.githubusercontent.com/71041079/98375266-e562fc80-200f-11eb-8de7-4a20d77e4d33.jpg)
![IMG_20201106_090447_1](https://user-images.githubusercontent.com/71041079/98375267-e5fb9300-200f-11eb-8f96-c6342b6d9922.jpg)
![IMG_20201106_090426_0](https://user-images.githubusercontent.com/71041079/98375270-e6942980-200f-11eb-98c5-722d9fb29dad.jpg)

**Actual results**
Better Z Seam Alignment with version of Cura 4.7.1

**Expected results**
Align Z Seam and not random with Cura 4.8

**Project file**
N/A

**Log file**
Sorry, I tried to find it but no luck. Instructions are not very clear.

**Additional information**
N/A

**Comment by konskarm** [comment] 2020-11-06 15:28
I believe this is related to an issue we had, where the Z seam was being placed halfway through a straight wall. This issue is fixed in https://github.com/Ultimaker/CuraEngine/pull/1344, so it should be there in 4.8 stable. Nevertheless, could you please provide a project (.3mf) file that displays this issue? I cannot reproduce it locally.

To generate a project file go to "File"->"Save Project...". You need to zip it before uploading it in GitHub.

**Comment by scubamario** [comment] 2020-11-07 02:53
[Among_us_helmet.zip](https://github.com/Ultimaker/Cura/files/5504203/Among_us_helmet.zip)

**Comment by konskarm** [comment] 2020-11-09 09:57
I think I see the problem. By default, the printer has set the `Z Seam Alignment` to `User Specified`, and the `Z Seam Position` is set to `(175,350)`. 

![image](https://user-images.githubusercontent.com/19388042/98519798-8c929e80-2271-11eb-8ecf-53f88c9bcc8a.png)

This just ensures that the Z seam will be somewhere in the back, but since the user-specified z seam position is so far from the model itself (due to the Y Seam position), it cannot force the Z Seam to be aligned in the Z direction. 

I can see two ways to fix this (**Note:** I enabled coasting so that the Seam is visible on the model. It won't actually look like that when printed.)

- Select a `Z Seam position` as `(175,175)`, so that the Y is close to the model and the starting point of each layer will be selected close to that Y
![image](https://user-images.githubusercontent.com/19388042/98526237-cf587480-2279-11eb-9e9d-0eaf0cf9eda1.png)

- Change the `Z Seam Alignment` to `Sharpest Corner` and let the `Seam Corner Preference` as `Hide Seam`. 
**Back**:
![image](https://user-images.githubusercontent.com/19388042/98526314-e5663500-2279-11eb-9461-b04dc1317c38.png)

**Front**:
![image](https://user-images.githubusercontent.com/19388042/98526352-f151f700-2279-11eb-8483-5e3c72073814.png)

In any case, this isn't really a bug, but rather a settings issue.

**Comment by scubamario** [comment] 2020-11-09 21:19
Hi,

The parameters of the version 4.7.1 and 4.8 was exactly the same for the Z Seam position (X & Y) so they should be identical on both prints, right???

**Comment by konskarm** [comment] 2020-11-10 07:56
It should indeed. When I open the file in 4.7 and slice it without changing any settings, I get exactly the same result to the 4.8-beta (again coasting enabled for visualization)

![image](https://user-images.githubusercontent.com/19388042/98645640-8f08fd00-2332-11eb-9d3b-7dc99d28220a.png)

Am I missing something here?

**Comment by Ghostkeeper** [comment] 2020-11-10 16:01
It's placing the seam across the diagonal since the flat back face is comprised of 2 triangles with an edge in the middle there. The edge is closest to the seam position so the seam gets placed there.

I'd expect the edge to be removed by the simplification algorithm though. That would be the actual bug then?

**Comment by konskarm** [comment] 2020-11-11 11:10
That is indeed true. It should be removed by the new simplify. I'll look into why it doesn't.

**Comment by konskarm** [comment] 2020-11-11 15:43
After closer inspection, it turns out that the three vertexes in the back are not exactly colinear. As an example, layer 50 in the back looks like this in a scatter plot:
![image](https://user-images.githubusercontent.com/19388042/98830681-fc07ba00-243a-11eb-9130-6aa1465252ec.png)

The 3 highlighted points actually have a small angle between them, so the middle point isn't removed by simplify. Now since its an angle barely greater than 180 degrees, it is always selected by the "Hide Z Seam" Seam Corner Preference leading to that diagonal.

Changing the Seam Corner Preference to anything other than "Hide Z Seam" should not create the diagonal. As an example, having "Smart Hiding":  
![image](https://user-images.githubusercontent.com/19388042/98832222-d8de0a00-243c-11eb-8389-f3fb1d2fab4c.png)

All-in-all, I would say this is expected behavior, although I am unsure how desired it may be.

I am still unsure though how you got different results for 4.7.1 and 4.8 without changing any settings.

**Comment by Ghostkeeper** [comment] 2020-11-17 10:27
Yes, I agree. This is expected behaviour then. It's not removed by simplification since the segments are longer than the Maximum Resolution. It's being selected as an option since the corner is actually the inner corner closest to the desired seam position.

Smart Hiding won't change that since the alignment is user-specified, so it must always be the closest seam position that matches the corner preference. Fixing the model so that the front is actually flat would resolve the problem, or selecting "shortest" or "sharpest corner" as seam location.

**Closed by Ghostkeeper** 2020-11-17 10:27 UTC
Labels: Type: Bug
