### ISSUE TITLE
app image is broken at Ubuntu 22.04 because of wrong libstdc++.so version that leads to swrast errors

### ISSUE THREAD

**Issue by antonkulaga** [Ultimaker/Cura#12329] opened 2022-05-23 17:01 UTC
### Application Version

5.0.0

### Platform

Ubuntu 22.04

### Printer

any

### Reproduction steps

run it

### Actual results

OpenGL errors, like:

libGL error: MESA-LOADER: failed to open radeonsi: /usr/lib/dri/radeonsi_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast

### Expected results

runs fine

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I found the bug issue - wrong libstdc++ version in the image that does not work properly at ubuntu 22.04 I simply rebuild the image with proper ( libstdc++.so.6.0.30 ) version and things work

**Comment by nallath** [comment] 2022-05-23 17:46
Duplicate of #11856

**Closed by nallath** 2022-05-23 17:46 UTC
Labels: Type: Bug
