### ISSUE TITLE
Forever slicing

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#6164] opened 2019-08-06 14:00 UTC
**Application version**
4.2.1

**Platform**
Linux

**Printer**
UM S5

**Reproduction steps**
Load project

**Actual results**
Slicing halts at 20%

**Expected results**
Slicing finishes

**Additional information**
I set the infill to 100%, which actually seems to matter. On normal UM s% profile it doesn't halt.

[UMS5_Sample_2__forever_slicing.3mf.renamed.zip](https://github.com/Ultimaker/Cura/files/3472614/UMS5_Sample_2__forever_slicing.3mf.renamed.zip)

![image](https://user-images.githubusercontent.com/8895761/62546196-5773f100-b863-11e9-84b7-a106d9a3082a.png)

**Comment by nallath** [comment] 2019-08-06 15:30
It also happens for me. There is no crash going on and the engine just keeps using 25% of my CPU.

**Comment by BagelOrb** [comment] 2019-08-09 09:02
Did you actually wait to see if it actually finishes the combing even once?

There might still be an infinite loop inside the combing algorithm!

**Comment by rburema** [comment] 2019-08-09 09:30
@LipuFei said during the CCB where we discussed the ticket that it finishes the 2500 case after about half an hour (if I remember correctly) (I think that might be for one layer??)

**Comment by LipuFei** [comment] 2019-08-09 09:49
@BabelOrb I did. I started the slice and went to a meeting. When I came back (around 2 hours later), I saw that the slice finished.

**Comment by BagelOrb** [comment] 2019-08-09 09:52
Ok good. Then it's just an unfortunately slow slice.
________________________________

**Comment by Ghostkeeper** [comment] 2019-08-11 22:42
> Because the time complexity of the algorithm is quadratic, this will take ~forever.

It's quartic actually, as in, `O(N^4)`.

**Comment by BagelOrb** [comment] 2019-08-12 06:53
Perhaps this has to do with some code I saw recently which accurately measures the combing travel time when deciding on the print order?

That would certainly cause forever slicing if the combing code is quartic!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by smartavionics** [comment] 2019-08-12 10:58
Coming late to the party here. It's not actually the combing that is working too hard. It's the wall order optimization that has the problem. With that disabled and the combing enabled it slices in less than 5 seconds.

I will investigate and report back.

**Comment by BagelOrb** [comment] 2019-08-12 12:27
@LipuFei It seems the bug wasn't in combing after all. Take better care in testing next time.

**Comment by smartavionics** [comment] 2019-08-12 12:34
TBH, I cannot yet say with 100% certainty exactly where the problem lies. At the moment it looks like there could be substantial time going into the ordering of the holes which could be related to combing but also there appears to be appreciable further time going into the processing of those holes. On layer 2 of that print, there's 2455 holes and as has been pointed out above, some of the calculations are at least O(n^2). I continue to investigate.

**Comment by smartavionics** [comment] 2019-08-12 22:51
I have discovered where the time is going and will submit one or more PRs in due course. Of course, Cura is always going to struggle with this model given how it handles walls. To satisfy my curiousity, I sliced it using thin walls (my Cura, not Ultimaker's) and the result looks very good. This was printed on a delta in less than 6 minutes. The challenge will be getting it off the blue tape in one piece!

![IMG_20190812_234559503](https://user-images.githubusercontent.com/585618/62903822-e8fbcb00-bd5b-11e9-915e-5a3b1f389974.jpg)

**Comment by BagelOrb** [comment] 2019-08-13 09:42
That print looks good!

Is this really a single extrusion line?

I would expect more defects in the intersection locations where 3 lines come together.
________________________________

**Comment by smartavionics** [comment] 2019-08-13 10:05
> Is this really a single extrusion line?

Yes.

> I would expect more defects in the intersection locations where 3 lines come together.

Looks like this...

![Screenshot_2019-08-13_11-03-52](https://user-images.githubusercontent.com/585618/62933499-3c9d0180-bdba-11e9-8003-7fd87dbdb715.png)

**Comment by smartavionics** [comment] 2019-08-14 17:38
Here's an oddity. If I slice this project with combing turned off (just so that it slices quickly) I get substantially different print time estimates depending on the value of Max Resolution. Using the value in the profile (0.8333) gives a print time of 36 mins but using a much smaller value (0.1) gives a print time of 16 mins. Huh?

![Screenshot_2019-08-14_18-34-23](https://user-images.githubusercontent.com/585618/63042728-896bff80-bec2-11e9-858f-e0344f94054c.png)

![Screenshot_2019-08-14_18-33-59](https://user-images.githubusercontent.com/585618/63042729-8a049600-bec2-11e9-9d91-61d4d32f3940.png)

**Comment by smartavionics** [comment] 2019-08-14 17:46
Oh, cripes! Using a smaller max resolution value actually causes fewer line segments to be output. It's the opposite to what I would expect. I would have thought that using a coarser resolution would cause fine details to be removed but it's the converse that appears to be happening!

**Comment by smartavionics** [comment] 2019-08-14 17:53
Here's a couple more images so you can see the difference changing the max resolution makes...

![Screenshot_2019-08-14_18-51-26](https://user-images.githubusercontent.com/585618/63043690-a570a080-bec4-11e9-9f91-a188a2105744.png)

![Screenshot_2019-08-14_18-50-55](https://user-images.githubusercontent.com/585618/63043691-a570a080-bec4-11e9-981d-ad6059f1c769.png)

WTF?

**Comment by BagelOrb** [comment] 2019-08-14 20:26
That sounds like a separate issue and it sounds quite important.

There used to be a bug which caused super high poly input to be simplified more than low poly input, but this bug seems to be a different one.

You think it only affects the merging of infill lines for thin walls?

It might even be related to the bug which just got fixed: https://github.com/Ultimaker/Cura/issues/5445

Either way: please make a separate new bug report.

**Comment by smartavionics** [comment] 2019-08-14 20:35
> You think it only affects the merging of infill lines for thin walls?

No, I don't think it's related to thin walls at all. In fact, I have checked that setting the max resolution to 0.1 or 0.8 doesn't make a big change to the output when it is sliced using thin walls so I think the problem is somehow with the normal walls. Maybe the insets are getting mashed up when the resolution is smaller? I don't know.

**Comment by smartavionics** [comment] 2019-08-17 12:53
> Either way: please make a separate new bug report.

Maybe it's related to #6215.

**Comment by nallath** [comment] 2019-12-16 11:50
The pull request for smartavionics fixes this (and just got merged)

**Closed by nallath** 2019-12-16 11:50 UTC
Labels: Status: Deferred, Type: Bug

**Comment by BagelOrb** [comment] 2019-12-16 16:37
Fixes what?

The max resolution issue, or the slicing time problem?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by smartavionics** [comment] 2019-12-16 16:50
> The max resolution issue, or the slicing time problem?

It fixes the slicing time problem (along with another PR). 

The max resolution issue should be fixed by a pending PR (https://github.com/Ultimaker/CuraEngine/pull/1114). That PR fixes multiple bugs in simplify().

**Comment by smartavionics** [comment] 2019-12-16 17:06
Actually, I'm wrong there. The max resolution issue mentioned above is not fixed by the pending PR. Further investigation required.

**Comment by smartavionics** [comment] 2019-12-16 17:21
I think the walls going away as the resolution is reduced is because the wall widths are so very close to the wall line width setting (0.4 in the profile) that, at times, the walls get removed and that just happens more when the max res value is reduced. If I use a wall line width that is only 10um smaller (i.e. 0.39), all the walls are included even when max res is small (i.e. 0.05). So I think this is a non-issue.

**Comment by nallath** [comment] 2019-12-17 08:39
The forever slicing one. Since that's the title of the issue (and one thread should contain one issue) i closed it.
