### ISSUE TITLE
Manage step/mm by filament/setting

### ISSUE THREAD

**Issue by Shine753** [Ultimaker/Cura#9984] opened 2021-06-15 23:22 UTC
### Is your feature request related to a problem?

As far as I can see, there is no way to adjust the extruder step/mm by filament.
One can add a gcode command into the printer settings before the start of a print, but this changes depending on the filament you use : step/mm is not the same for one extruder if you use PLA or a soft TPU.
This should be changed into the settings of a print, as well as one can change the extrusion percentage.

### Describe the solution you'd like

Being able to change the value of steps/mm into the print settings. And add a default one into the filament settings.

### Describe alternatives you've considered

Did not find any solution that could be daily used. But this can be done by changing EACH TIME the pre-processing gcode into the machine settings.

### Affected users and/or printers

Everyone who use a printer and search for a good and accurate print quality.

**Comment by Asterchades** [comment] 2021-06-16 11:51
This looks to be pretty much a duplicate of https://github.com/Ultimaker/Cura/issues/9924

**Comment by nallath** [comment] 2021-06-16 11:53
Agreed. This is a duplicate. Closing this in favor of #9924

**Closed by nallath** 2021-06-16 11:53 UTC
Labels: Status: Duplicate, Type: New Feature

**Comment by Shine753** [comment] 2021-06-16 14:50
Not exactly, but well, ok. I commented in #9924
