### ISSUE TITLE
Oooze sheild - select extruder.

### ISSUE THREAD

**Issue by HarryThePotter** [Ultimaker/Cura#11164] opened 2021-12-30 11:25 UTC
### Is your feature request related to a problem?

I print using PLA/PETG in one extruder and PVA in the second extruder. It is a bowden tube system. As the ooze sheild is only 1 nozzle width wide, the PVA will 95%(ish) of the time NOT stick the the PLA/PETG layer already put down my the other extruder and just end up with a long extruded string wrapped around the Ooze shield. Then the next layer is printed, the extruders swap over and the ooze shiled is printed with the PLA/PETG extruder, but because the PVA layer didn't stick very well, it too print a very thin string that is very loosley attached (mainly by gravety streatching it down before it cools). The result is a very week Ooze shiled that is just layers of string. 

### Describe the solution you'd like

If the OOze sheild was tied to a single extruder (as you can for support material) every layer would be printed from the same extruder. Not only would you get a better shield, but if one extruder is loaded with expensive 'feature filament' (like the ones that have metal particles), it would save wasting expensive material on something that is a sacrificial part of the print.
I have also put GCode in the 'Extruder end' scripts to move the nozzle to the purge tower before changing the extruder temperature. This allows 'most' of the ooze from the cooling down nozzle to be captured in the center of the tower. It would be nice to have a tick box that handled this for you, but most advanced users can put GCode in the same way I have.

### Describe alternatives you've considered

Being able to print a wider ooze shiled - Nice if you had the option to define its width but uses more material.
Ooze shield printed in a criss cross patern with the criss cross 'routating'' a little bit at a time so the lays 'cross' one another.
Designng a 'helper' part that wraps around the print area and then assigning this part to the main extruder.

### Affected users and/or printers

Ooozing is an issue to some degree with multi extruder systems where the nozzles are on a single carriage. I therefore think that most people who use a 'support' material like PVA would beniffit from this change. Users who load both extruders with the same material in different colours (or different Nozzle widths) would only benefit from the cost saving.

**Comment by fvrmr** [comment] 2022-01-04 13:03
Hi @HarryThePotter thank you for your feature request. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/5693
So I will close this issue and mark it as a duplicate.

**Closed by fvrmr** 2022-01-04 13:03 UTC
Labels: Type: New Feature
