### ISSUE TITLE
Tree Support not working right.

### ISSUE THREAD

**Issue by Ted-Printable** [Ultimaker/Cura#13055] opened 2022-08-17 13:11 UTC
### Application Version

5.1.0.  also saw this issue on ver 5.0.0 already.

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

Hi, this is difficult to explain. 
The two G-code files attached were both generated with the EXACT same print profile settings. The models are also, the exact same models, accept for the second object that is added to the one file.. In the Holder.gcode file you will see there is a extra tree support that is generated in "mid air".

The file shows a clear error with tree support generated in mid air, something that does happen also.
I also had many of these "errors"  with some slices where the supports just are not generated all the places where they should be generated.  

This issue was first seen in ver 5.0. I hoped it would be fixed with 5.1, but it is still coming up regularly.

I realize the issue is not very specific, but I suspect some Bug got into the tree support generator in ver 5.0. 
I hope you can find it with a review of the tree support generator and/or algorithm.

Thank you
[Holder.zip](https://github.com/Ultimaker/Cura/files/9362937/Holder.zip)

### Actual results

Hi, this is difficult to explain. 
The two G-code files attached were both generated with the EXACT same print profile settings. The models are also, the exact same models, accept for the second object that is added to the one file.. In the Holder.gcode file you will see there is a extra tree support that is generated in "mid air".

The file shows a clear error with tree support generated in mid air, something that does happen also.
I also had many of these "errors"  with some slices where the supports just are not generated all the places where they should be generated.  

This issue was first seen in ver 5.0. I hoped it would be fixed with 5.1, but it is still coming up regularly.

I realize the issue is not very specific, but I suspect some Bug got into the tree support generaHi, this is difficult to explain. 
The two G-code files attached were both generated with the EXACT same print profile settings. The models are also, the exact same models, accept for the second object that is added to the one file.. In the Holder.gcode file you will see there is a extra tree support that is generated in "mid air".

The file shows a clear error with tree support generated in mid air, something that does happen also.
I also had many of these "errors"  with some slices where the supports just are not generated all the places where they should be generated.  

This issue was first seen in ver 5.0. I hoped it would be fixed with 5.1, but it is still coming up regularly.

I realize the issue is not very specific, but I suspect some Bug got into the tree support generator in ver 5.0. 
I hope you can find it with a review of the tree support generator and/or algorithm.tor in ver 5.0. 
I hope you can find it with a review of the tree support generator and/or algorithm.

Thank you
[Holer.zip](https://github.com/Ultimaker/Cura/files/9359638/Holer.zip)
.

### Expected results

Tree support should be generated where needed.
Supports that "start" in mid air should be avoided.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Hi, this is difficult to explain. 
The two G-code files attached were both generated with the EXACT same print profile settings. The models are also, the exact same models, accept for the second object that is added to the one file.. In the Holder.gcode file you will see there is a extra tree support that is generated in "mid air".

The file shows a clear error with tree support generated in mid air, something that does happen also.
I also had many of these "errors"  with some slices where the supports just are not generated all the places where they should be generated.  

This issue was first seen in ver 5.0. I hoped it would be fixed with 5.1, but it is still coming up regularly.

I realize the issue is not very specific, but I suspect some Bug got into the tree support generaHi, this is difficult to explain. 
The two G-code files attached were both generated with the EXACT same print profile settings. The models are also, the exact same models, accept for the second object that is added to the one file.. In the Holder.gcode file you will see there is a extra tree support that is generated in "mid air".

The file shows a clear error with tree support generated in mid air, something that does happen also.
I also had many of these "errors"  with some slices where the supports just are not generated all the places where they should be generated.  

This issue was first seen in ver 5.0. I hoped it would be fixed with 5.1, but it is still coming up regularly.

I realize the issue is not very specific, but I suspect some Bug got into the tree support generator in ver 5.0. 
I hope you can find it with a review of the tree support generator and/or algorithm.tor in ver 5.0. 
I hope you can find it with a review of the tree support generator and/or algorithm.

Thank you

**Comment by MariMakes** [comment] 2022-08-26 12:53
Hey @Ted-Printable ,

I took a look at your files.
I could not reproduce your issue in the .3mf you shared but I did find the behavior you described in gcode.
To me it seems like a duplicate of https://github.com/Ultimaker/Cura/issues/12257 which is on our backlog. 

![image](https://user-images.githubusercontent.com/40423138/186907448-cfb035f2-0764-4292-a40c-7e776d4d70f9.png)

I'm closing this issue since it's a duplicate, you can follow the progress at https://github.com/Ultimaker/Cura/issues/12257

**Closed by MariMakes** 2022-08-26 12:53 UTC
Labels: Type: Bug, Status: Triage
