### ISSUE TITLE
Horizontal expansion of the first layer Issue

### ISSUE THREAD

**Issue by gabber130779** [Ultimaker/Cura#12792] opened 2022-07-18 20:09 UTC
### Application Version

5.1.0 Beta

### Platform

Windows 11

### Printer

Anycubic Mega X

### Reproduction steps

Bei der Eingabe von negativen Werten bei "Horizontale Erweiterung der ersten Schicht" wird die erste Schicht größer statt kleiner. Bei eingabe von positiven Werten wird die erste Schicht kleiner Statt größer.

If you enter negative values for "Horizontal expansion of the first layer", the first layer will be larger instead of smaller. If you enter positive values, the first layer will be smaller instead of larger.

### Actual results

![Issue](https://user-images.githubusercontent.com/108513101/179606628-c928ac9a-484c-4954-af1d-dd770e217ddb.png)

### Expected results

Die erste Schicht sollte bei negativen Werten kleiner, bei positiven Werten größer werden.

The first layer should get smaller for negative values and larger for positive values.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9135471/cura.log)
[AI3MX_Körper7.zip](https://github.com/Ultimaker/Cura/files/9135487/AI3MX_Korper7.zip)

**Comment by GregValiant** [comment] 2022-07-18 20:58
Thanks for taking the time to make the report.
Two variables were transposed in the code.  It's been fixed for the next release.
I had to stare at this for a while to see what was going on.  Instead of acting on the first layer and leaving the rest alone, "Initial layer Horizontal Expansion" is leaving the first layer alone and acting on the rest of the layers.  There is no workaround other than setting it to "0".
I'll mark this as a duplicate of #11960 and close it.  If you feel that is premature leave a comment here and I can revisit it.

**Closed by GregValiant** 2022-07-18 20:58 UTC
Labels: Type: Bug, Status: Duplicate
