### ISSUE TITLE
Slicing Failure

### ISSUE THREAD

**Issue by Reviral** [Ultimaker/Cura#13908] opened 2022-11-26 22:34 UTC
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Ender 5

### Reproduction steps

Sliced a model using ultra fine

### Actual results

Failed to slice with an unexpcted error

### Expected results

A sliced model ready to send to the printer
[Problem slice.zip](https://github.com/Ultimaker/Cura/files/10097125/Problem.slice.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10097132/cura.log)

**Comment by GregValiant** [comment] 2022-11-28 03:08
Thanks for the report and the files.
It sliced for me on the first try so I'm unable to duplicate the problem.
There have been numerous reports of a bug that causes slicing to fail on certain hi-resolution models.  If you move and/or rotate the model on the build plate in Cura you can often fool the bug and the model will slice.
For now I'll mark this as a duplicate of the other slicing errors.  Try the workaround and let me know if it works for you.

**Closed** 2022-12-14 12:53 UTC
Labels: Type: Bug, Status: Needs Info, Status: Under Investigation, Slicing Error💥
