### ISSUE TITLE
no support brim even enable it 

### ISSUE THREAD

**Issue by lyj0309** [Ultimaker/Cura#16361] opened 2023-08-02 05:31 UTC
### Cura Version

5.4.0

### Operating System

windows11

### Printer

klp1

### Reproduction steps

    when set "Build Plate Adhesion Type" to none, even checked "enable support brim" 
![image](https://github.com/Ultimaker/Cura/assets/50474995/05d471ed-c908-4dfa-a2a8-3e20f3453199)

### Actual results

 no brim in support

### Expected results

have brim in support  whatever "Build Plate Adhesion Type" is

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/50474995/484db8b7-d567-4067-a9ad-7b0781221678)

**Comment by Asterchades** [comment] 2023-08-02 06:03
This is a known issue and is currently on the developers' backlog. Either a Skirt or Brim must be used on the model itself for the Supports to have a Brim at present.

Duplicate of #14983.

**Closed by Asterchades** 2023-08-02 06:03 UTC
Labels: Type: Bug, Status: Triage
