### ISSUE TITLE
ungroup is not working (disabled)

### ISSUE THREAD

**Issue by bond4u** [Ultimaker/Cura#1423] opened 2017-02-12 14:09 UTC
I'm trying to print "pump hand drill" from tv and "ungroup" option is greyed out in rclick menu.
Not sure why.
![image](https://cloud.githubusercontent.com/assets/66413/22862762/80b99014-f13d-11e6-8da8-784469f2f193.png)

**Comment by fieldOfView** [comment] 2017-02-12 16:56
Did you load these parts as a single file?

Ungrouping only works for models that were grouped inside Cura. It does not break apart submeshes from a single model.

**Comment by peteruithoven** [comment] 2017-02-13 09:24
So to clarify, this issue is on reimplementing the take apart functionality?

**Comment by Ghostkeeper** [comment] 2017-02-13 09:53
The "Split object into parts" function from legacy Cura did this, but it was never ported to Cura 2.

We have this feature on our tracker. Currently planned at 2.6 (but I can give no guarantees on people moving that around).

By the look of the shadows underneath that model, it is indeed just one model file and so Cura is not able to ungroup it. But let's wait for Bond's answer to confirm this first.

**Comment by bond4u** [comment] 2017-02-13 16:58
Yeah, these objects are from single file (http://www.thingiverse.com/thing:731086)
It says "ungroup models", not "ungroup files" ;) so I assumed it can "split" them as old cura did.

**Comment by Ghostkeeper** [comment] 2017-11-20 11:01
Let's mark this as a duplicate of https://github.com/Ultimaker/Cura/issues/2052

**Closed by Ghostkeeper** 2017-11-20 11:01 UTC
Labels: enhancement
