### ISSUE TITLE
Raft Layer Missing Section

### ISSUE THREAD

**Issue by aerospacejosh** [Ultimaker/Cura#13696] opened 2022-10-31 01:27 UTC
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Ender 3 V2

### Reproduction steps

1. Sliced a model with open middle section and raft selected
2. Click preview
3. One part of one middle layer in raft is missing as it abuts against open middle

### Actual results

Skips over one section of layer three (still in raft). This is viewable in both the preview and I verified it actually prints this way as well

### Expected results

Should not skip sections in raft

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[ph11_PETG_1.zip](https://github.com/Ultimaker/Cura/files/9897272/ph11_PETG_1.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/9897279/cura.log)

**Comment by MariMakes** [comment] 2022-10-31 14:12
Hey @aerospacejosh,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12276
We have a ticket on our backlog with the intent to improve this behavior.
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12276

**Closed by MariMakes** 2022-10-31 14:12 UTC
Labels: Type: Bug, Status: Triage
