### ISSUE TITLE
Can flash using Arduino program when Cura program is open

### ISSUE THREAD

**Issue by LuluTchab** [Ultimaker/Cura#7802] opened 2020-05-22 07:43 UTC
**Application version**
4.6.1

**Platform**
Windows 10 x64 1903

**Printer**
Custom (PrimaCreator p120)

**Reproduction steps**
1. Just open Cura, nothing more
1. Open Arduino program
1. Open an Arduino sketch you want to flash on a board
1. Connect the Arduino board.
1. Configure connection infos it using "Tools" menu
1. Click on "Upload" to compile sketch and upload it on Arduino board.
1. There's always an error accessing COM port on which Arduino is connected.
1. Close Cura
1. Go back on Arduino program and click on "Upload" another time and everything works.

**Screenshot(s)**
*none*

**Actual results**
Impossible to upload complied sketch on Arduino board as long Cura program is open

**Expected results**
Cura shouldn't "lock" (or something else) COM ports when it is opened.

**Project file**
*N.A*

**Log file**
*N.A*

**Additional information**
*N.A*

**Comment by Ghostkeeper** [comment] 2020-05-25 13:40
Duplicate of https://github.com/Ultimaker/Cura/issues/5207.

**Closed by Ghostkeeper** 2020-05-25 13:40 UTC
Labels: Type: Bug
