### ISSUE TITLE
Weird infill on walls using exact uneven multiples of Line Width

### ISSUE THREAD

**Issue by regularlabs** [Ultimaker/Cura#5543] opened 2019-03-31 19:39 UTC
(Thought I'd post this here as an issue too. Also posted on the forum: https://community.ultimaker.com/topic/27345-weird-infill-on-04mm-gaps-and-walls)

Using OSX 10.13.6, Cura 4.0.0.

This is pretty much the issue in a nutshell (using Line Width 0.4mm):
![image](https://user-images.githubusercontent.com/13553242/55294035-5fc3a780-53fd-11e9-90b3-d3dee5786dd6.png)

Cura seems to not deal well with walls that are an uneven exact multiple of the Line Width.

Example:

This is a simple object with 3 walls of 2mm thick. With a Line Width of 0.4 and Wall Line Count set to 3, it should just use 5 lines to fill the wall.
Instead it does this! (Also known as a printer-killer!)

![image](https://user-images.githubusercontent.com/13553242/55293984-e1670580-53fc-11e9-98af-45d2b905e5b0.png)

If I set the Line Width to 0.39 I get the desired result:

![image](https://user-images.githubusercontent.com/13553242/55293988-f04db800-53fc-11e9-99b2-10684e37a3dc.png)

But I shouldn't have to do that. This is a rounding/calculation BUG in Cura.

Also, printing a 0.4mm wall (for instance for creating custom supports) does not work.

This is the same object, but I added a cross in the hole with walls of exactly 0.4mm thick.
It now does not matter if I set the Wall Width to 0.4mm or 0.39mm. Cura doesn't want to print that as a single line.
(Yes, the Print Thin Walls option is on)

![image](https://user-images.githubusercontent.com/13553242/55293996-f93e8980-53fc-11e9-9be4-9e06d98666bf.png)

If I change these thin walls to 0.41mm this, Cura does print them as a single line.
So here is the object with 0.41mm walls. And Cura set to 0.39mm Line Width.

![image](https://user-images.githubusercontent.com/13553242/55293998-fe033d80-53fc-11e9-89af-9d0b03d67e29.png)

Again, I shouldn't have to do this to work around issues in Cura.

**Comment by Ghostkeeper** [comment] 2019-04-01 13:27
Duplicate of #5110.

**Closed by Ghostkeeper** 2019-04-01 13:27 UTC
