### ISSUE TITLE
Reloading of changed model affecting only main model, not including multiplied ones

### ISSUE THREAD

**Issue by avashkevich** [Ultimaker/Cura#19061] opened 2024-05-11 21:36 UTC
### Cura Version

5.7.0

### Operating System

Windows 10

### Printer

Anycubic Kobra

### Reproduction steps

1. Add any *.stl model
2. Multiply it
3. Replace model file on disk with its modified version
4. Press "Reload" in Cura

### Actual results

Only main body was updated. Multiplied bodies remains old

### Expected results

All bodies should be updated, including multiplied

### Add your .zip and screenshots here ⬇️

No screenshots or files required, you may use any .stl model to reproduce it.

**Comment by GregValiant** [comment] 2024-05-12 02:05
Thanks for the report.
This is a duplicate of #19031.  Take a look at that one and read @HellAholic's description of why this happens.
He was going to bring it up with the Cura Team and he'll update that first report when more info is received.

I'll mark this as a duplicate and go ahead and close this one in favor of the first report.

**Closed by GregValiant** 2024-05-12 02:05 UTC
Labels: Type: Bug, Status: Under Investigation
