### ISSUE TITLE
Odd behavior with Make Overhangs Printable

### ISSUE THREAD

**Issue by KenLucke** [Ultimaker/Cura#9263] opened 2021-02-10 20:15 UTC
**Application version**
4.8

**Platform**
Mac OS
![image](https://user-images.githubusercontent.com/57936294/107565207-47e01180-6b98-11eb-9e27-08d4ccc68f90.png)

**Printer**
Creality CR-10s (with settings to make CR-10v2)

**Reproduction steps**

1. Loaded model
2. Set slicer settings, including Make Overhangs Printable
3. Sliced

**Screenshot(s)**
Top:  No "Make Overhangs Printable"
Middle: With "Make Overhangs Printable
Bottom: Raw Model
![Gothic Lantern top - Ultimaker Cura 2021-02-10 11-56-07](https://user-images.githubusercontent.com/57936294/107566126-52e77180-6b99-11eb-8b06-770d6b6bf27b.jpg)

**Actual results**
Cura adds a center portion of the body that does not exist

**Expected results**
Shouldn't do that

**Project file**
[Gothic Lantern top.3mf.zip](https://github.com/Ultimaker/Cura/files/5961258/Gothic.Lantern.top.3mf.zip)

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/5961298/cura.log)

**Additional information**
(Extra information relevant to the issue.)

**Comment by nallath** [comment] 2021-02-11 08:24
`Cura adds a center portion of the body that does not exist`

That is exactly what the make overhangs printable setting is supposed to do.

**Comment by fvrmr** [comment] 2021-02-11 13:12
> `Cura adds a center portion of the body that does not exist`
> 
> That is exactly what the make overhangs printable setting is supposed to do.

I will close this issue because it is expected behaviour from Cura. 
Hope you understand. Please let me know if you have questions.

**Closed by fvrmr** 2021-02-11 13:12 UTC
Labels: Type: Bug
