### ISSUE TITLE
Slicing multiple pieces

### ISSUE THREAD

**Issue by tpedry** [Ultimaker/Cura#14416] opened 2023-01-29 22:59 UTC
### Application Version

5.2.1

### Platform

IMac 2017

### Printer

Longer LK5 Pro

### Reproduction steps

1. I added multiple pieces to build plate
2. Scaled each one individually to 120%
3. Right click and selected "Arrange Models"
4. Went to slice
5. Error "Slicing Failed"›
<img width="1954" alt="Screenshot 2023-01-29 at 4 17 34 PM" src="https://user-images.githubusercontent.com/123258763/215358746-1e1e55fc-3866-41a7-ba43-c655fa39d483.png">

### Actual results

I can tried repeatedly, but I cannot slice the objects at 120% scaling based on where Cura arranges the Models. They will slice at 100% scaling where Cura places them

### Expected results

It should slice no problem. Cura should arrange so the objects can be sliced

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

The project file was 52MG

**Comment by MariMakes** [comment] 2023-02-03 15:45
Hey @tpedrym,

Welcome to the Ultimaker Cura Github 🚀 

Is it possible that your printjob is located at 0, 0, 0, and it slices if you move it a little away from the center of the buildplate? 
Then it might be a duplicate of https://github.com/Ultimaker/Cura/issues/13643

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Closed** 2023-02-18 00:18 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage, Slicing Error :collision:
