### ISSUE TITLE
Cura 3.0.4 Profile Import Does Nothing

### ISSUE THREAD

**Issue by mbmast** [Ultimaker/Cura#2739] opened 2017-11-06 00:42 UTC
I import a profile (attached) from Cura 15.04.6 and Cura 3.0.4 reports that the profile was imported successfully.  Yet, it does not show up anywhere nor are any of the settings it contains merged or inserted in any way into my active profile.  It is as though the import does nothing.
[ABS.zip](https://github.com/Ultimaker/Cura/files/1444611/ABS.zip)

**Comment by Ghostkeeper** [comment] 2017-11-06 03:19
Duplicate of https://github.com/Ultimaker/Cura/issues/2117

**Closed by Ghostkeeper** 2017-11-06 03:20 UTC
