### ISSUE TITLE
[4.2.1] Support in air

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#6183] opened 2019-08-09 13:05 UTC
**Application version**
4.2.1

**Platform**
Win10 x64

**Printer**
Cr-10S

**Reproduction steps**
Slice the project with supprots from model

**Actual results**
Support starts in the air

**Expected results**
Support should touch the model

**Additional information**
[support in air.zip](https://github.com/Ultimaker/Cura/files/3486459/support.in.air.zip)
![support in air](https://user-images.githubusercontent.com/20385116/62780940-1e33bf00-bab7-11e9-97a5-13d755801521.png)

**Comment by AbeFM** [comment] 2019-08-11 07:15
Support X/Y distance set to 0 fixes it.

I've asked for YEARS for this to get looked at, and I've been shot down over and over. Maybe it's not my exact issue, but supports work with it off. Set it at a compromise value. I set it to 0.1 and it worked fine.

**Comment by Redsalamander** [comment] 2019-08-13 08:10
Same problem with slicing on all my printers. including my UM2+ the workaround seems to work and generate support on the base layer again.

**Comment by Ghostkeeper** [comment] 2019-08-13 11:11
Setting the Support X/Y Distance to 0 is not a workaround either in this case, though it does make the support extend a few layers further down.

![Screenshot from 2019-08-13 13-09-50](https://user-images.githubusercontent.com/2448634/62937062-f3997d00-bdba-11e9-9bfa-98d837a1a6f9.png)

**Comment by b4545** [comment] 2019-08-18 20:28
I wonder how right I am...that a larger priority is Creality printer integration because they are actually paying Ultimaker.

**Comment by Ghostkeeper** [comment] 2019-08-19 17:33
This problem seems to be with the Minimum Support Area setting.

**Comment by AbeFM** [comment] 2019-08-24 18:31
From another inquiry elsewhere, but perhaps this is related to this issue.

I created a test model:
![image](https://user-images.githubusercontent.com/42385/63641382-274d9000-c662-11e9-85b3-0292ee1907e3.png)

> Ledges are 10, 15, 20 mm apart
> Inner humps are 0, 5, 10 apart.
> Slopes are 15 or 30 degrees
> All orientations match
> 
> 8/8 Roof/Floor
> 
> ![image](https://user-images.githubusercontent.com/42385/63641340-5d3e4480-c661-11e9-977f-6bc8bffa168e.png)
> 
> 1/13
> ![image](https://user-images.githubusercontent.com/42385/63641349-8d85e300-c661-11e9-8549-ef89886bf3ec.png)
> Missing some on bottom as the issue on the forums currently, I think
> Missing on the right, not sure why
> 
> 13/1
> ![image](https://user-images.githubusercontent.com/42385/63641354-b7d7a080-c661-11e9-8a83-fc242b0fc59c.png)
> Missing a lot of bottoms. No idea why.
> 
There may be an object off-plate which I'm actually trying to print, and it will have support floor and roof, but be missing the support infill in between.

[SupportErrorsALL.3mf.txt](https://github.com/Ultimaker/Cura/files/3537474/SupportErrorsALL.3mf.txt)
![image](https://user-images.githubusercontent.com/42385/63641410-b0fd5d80-c662-11e9-9df8-d0e4f59bc426.png)

**Comment by AbeFM** [comment] 2019-08-24 21:11
I exported my test from SmartAvionics' 8/23 build, loaded the 3mf into my copy of 4.2.1

Sliced in 4.2.1
![image](https://user-images.githubusercontent.com/42385/63642712-4d7e2a80-c678-11e9-8130-ae6b2f736144.png)


Same thing sliced in a current version (SmartAvionics' 8/23 build, based on current CURA, I believe)
![image](https://user-images.githubusercontent.com/42385/63642718-70a8da00-c678-11e9-8705-5dec7f63f6f9.png)

Although he has done some *great* work on the minimum x/y spacing, I set all the distances to 0 for this test. I do not feel that is the root cause of the issue as others are seeing it on the official build.

Resliced, 4.2.1 on the left, with 13 floor and 1 roof:
![image](https://user-images.githubusercontent.com/42385/63642738-d8f7bb80-c678-11e9-86cc-f5bcddd4d488.png)
It looks like the floor is being culled, whereas in my organic shapes it seems both floor and infill are removed.

Not sure if it helps, but I hope it does.

**Comment by AbeFM** [comment] 2019-08-24 21:19
> This problem seems to be with the Minimum Support Area setting.

I saw weird issues (not that weird) with Interface Minimum Support Area being larger than the Minimum Support Area - you could get instances of the support infill material stuck to the model, little globs past the last of the (restricted) interface material.
Interface Area: 5, Support Area: 0
![image](https://user-images.githubusercontent.com/42385/63642780-823eb180-c679-11e9-91ab-fa29b3fd4ea9.png)
I circled two areas with the wrong material being used. It should be a seperate ticket, I feel, but the Minimum Support Interface Area should be either restricted to be no greater than the Minimum Support Area, or make it a delta FROM the Minimum Support Area (i,.e. if MSIA is 0.2 and MSA is 0.5, what is the current MSIA would actually be set to 0.3. This could be confusing, but it would work.). If you could just restrict the MSIA value to be =< MSA, I think you'd fix that issue.


With all minimums set to 0, I get:
![image](https://user-images.githubusercontent.com/42385/63642822-2294d600-c67a-11e9-96d9-3835cae57b72.png)

...all the same problems from before. If you can suggest MSA changes to make I will try them.

**Comment by Vandrasc** [comment] 2020-06-23 09:12
Hi @Liger0 , the Support printed in air issue has been addressed and the fix was merged in master, It took us a bit to take the time to address this one but hopefully it works as expected for you now. Please reopen if you still encounter the issue on your side. 

Many thanks!

**Closed by Vandrasc** 2020-06-23 09:12 UTC
Labels: Type: Bug
