### ISSUE TITLE
Cura Window opens halfway off-screen (no matter what settings I use)

### ISSUE THREAD

**Issue by nirurin** [Ultimaker/Cura#13328] opened 2022-09-19 02:34 UTC
### Application Version

5.1.1

### Platform

Windows 11

### Printer

Ender5+

### Reproduction steps

I use two monitors, primary and secondary. 
I open cura. The splash screen always pops up on the secondary monitor (fine, who cares). Then the cura window will pop up on the primary monitor... but it always pops up in the far top-left corner, with half the window off-screen so I have to drag it quite far to the right in order to see the whole window. 

I've tried the setting which is meant to 'remember' the window position, but this does nothing. I've tried it both on and off, makes no difference. 

I've tried altering the window position in cura.cfg, but this also does nothing, it just reverts back to the old value on startup. 

I've tried deleting cura.cfg but this also doesn't fix it. 

### Actual results

Window always appears off-screen

### Expected results

With the setting for remembering window position turned on, it should remember its position and appear where I left it when I shut down the app. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No pictures are really relevant, unles you want a screenshot of my desktop?

**Comment by MariMakes** [comment] 2022-10-04 15:37
Hey @nirurin,

Thanks for your report 👍 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12197
We have a ticket on our backlog with the intent to improve this behavior.
But unfortunately, we are dependent on a third party for the fix. 😞 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12197

**Closed by MariMakes** 2022-10-04 15:37 UTC
Labels: Type: Bug, Status: Triage
