### ISSUE TITLE
Centenas de janelas de erro

### ISSUE THREAD

**Issue by josewmc** [Ultimaker/Cura#12163] opened 2022-05-11 00:00 UTC
### Application Version

5.0.0-Beta+1

### Platform

Windows 11

### Printer

Delta Kossel Mini - Marlin 2.0

### Reproduction steps

Após alguns minutos de impressão, aparecem centenas de janelas de erro e eu não consigo ver, travam meu pc.

### Actual results

Não recebi nenhuma sugestão.

### Expected results

Não recebi nenhuma sugestão.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Não sei onde encontrar os logs

**Comment by fvrmr** [comment] 2022-05-11 10:29
Hi @josewmc thank you for your report.
Please fill in the form in English and attach your log file. You can find your log file here: `C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`

**Comment by josewmc** [comment] 2022-05-12 00:28
Thank you!

**Comment by fieldOfView** [comment] 2022-05-12 08:28
This is a duplicate of #11896, which has been fixed for the final release of Cura 5.0.

**Closed** 2022-05-25 11:16 UTC
Labels: Type: Bug, Status: Needs Info
