### ISSUE TITLE
Selecting and moving item

### ISSUE THREAD

**Issue by Campbellked** [Ultimaker/Cura#11728] opened 2022-03-29 14:03 UTC
### Application Version

4.13.1

### Platform

Mac OS 10.14.6

### Printer

Creality Ender 3 Pro

### Reproduction steps

1. import object to print
2. click on object to select. Nothing happens
3. Go to object list in bottom left of window. Click on object name.  Object shows it is selected.
4. Try to grab an axis arrow to move. Object de-selects and cannot move or rotate.
5. Repeatable

### Actual results

Same

### Expected results

Select object and be able to rotate and move and manipulate.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No other information to provide. Same happens with all models imported into cura.

**Comment by fvrmr** [comment] 2022-03-31 09:30
Hi @Campbellked thank you for your report.
Do you have an external monitor? If so it is a duplicate of https://github.com/Ultimaker/Cura/issues/8745
As a work around you can uncheck the option `restore window position on start` in the preferences.

**Closed** 2022-04-14 10:08 UTC
Labels: Type: Bug, Status: Needs Info
