### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by charnwooduk** [Ultimaker/Cura#11572] opened 2022-02-28 11:51 UTC
### Application Version

4.13.1

### Platform

Windows 11

### Printer

None - fresh install

### Reproduction steps

This version of cura was working previously, not sure why it has stopped. 

I have done a complete uninstall, deleted folders from roaming and local %appdata% folders and reinstalled. Still giving the same issues

Machine is win11 - intel i5-12600k
32gb memory
nvidia 3060ti (driver version 511.23)

### Actual results

Cura load screen appears and then the main Cura window appears for about 0.5 seconds and then disappears. Fatal Python error in logs. 

### Expected results

Cura should be open on the desktop

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

files attache
[cura.zip](https://github.com/Ultimaker/Cura/files/8153069/cura.zip)
d

**Comment by fvrmr** [comment] 2022-03-04 13:00
Hi @charnwooduk thank you for your report.
This looks like a duplicate of https://github.com/Ultimaker/Cura/issues/7584
There the solution was to uninstall and reinstall the graphic driver. Let me know if that works for you.

**Closed** 2022-03-18 14:23 UTC
Labels: Type: Bug, Status: Needs Info
