### ISSUE TITLE
Cura 4.9.0 crashes on Toshiba Chromebook 2015

### ISSUE THREAD

**Issue by mettleh3d** [Ultimaker/Cura#9737] opened 2021-05-01 05:30 UTC
### Application Version

4.9.0

### Platform

Linux

### Printer

Ender 3 Pro

### Reproduction steps

Cura 4.9.0 will crash when

1. Load any .stl file
2. Highlight model
3. Click resize/rescale button
4. Cura will crash

Note: Cura 4.8.0 will not crash with the same steps

### Actual results

Cura 4.9 crashes

### Expected results

Can resize model as expected

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[Curalog.txt](https://github.com/Ultimaker/Cura/files/6408944/Curalog.txt)

**Comment by fvrmr** [comment] 2021-05-03 12:04
Hi @mettleh3d thank you for your report. 
It looks like this is a duplicate of https://github.com/Ultimaker/Cura/issues/9709
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-05-03 12:04 UTC
Labels: Type: Bug

**Comment by mettleh3d** [comment] 2021-05-03 14:03
@fvrmr Thanks!
