### ISSUE TITLE
"Zoom toward mouse direction" feature seems to be broken

### ISSUE THREAD

**Issue by ScruffR** [Ultimaker/Cura#7537] opened 2020-04-20 13:08 UTC
I'm using v4.6.0 beta on Win10 Pro 64bit on a MS Surface Pro 2017.

I recall this feature working as expected, but for some releases now I see that it doesn't seem to make any difference whether the feature in activated or not.

In previous (some time ago) releases when zooming in, the current mouse position was taken as center of the zoom, but now it seems to always be zooming towards the same spot no matter where the mouse is placed.

BTW, I do find the naming of the feature somewhat confusing. 
I'd thing "Zoom toward mouse position" more clear than "Zoom toward mouse direction". A static mouse does only have a position but no direction. 
When the mouse moves it has direction and an ever changing position.

**Comment by Ghostkeeper** [comment] 2020-04-22 20:56
Duplicate of #6775 .

**Closed by Ghostkeeper** 2020-04-22 20:56 UTC
Labels: Type: Bug
