### ISSUE TITLE
Display Z height instead/in addition to layer number on print preview

### ISSUE THREAD

**Issue by AbeFM** [Ultimaker/Cura#6179] opened 2019-08-08 23:57 UTC
**Is your feature request related to a problem? Please describe.**
Being able to find the location  of a critical feature is one of the best uses of the slicing preview. Often, this input can be critical in determining where to make changes. 

This is also of major concern when layer sizes change for any reason (first layer thickness, variable layer heights).

**Describe the solution you'd like**
![MillimetersPlease](https://user-images.githubusercontent.com/42385/62744790-07c92d00-b9fd-11e9-944b-f9842a2c8d8e.png)
I kept it all the same size.

**Describe alternatives you've considered**
In theory the same information could be gathered by importing the model into an external cad program, then offset by the physical placement of the object in the CURA space. Then do the layer heights math.....

One could create a primitive (support blocker) and scale it until it matches the object... But it still can be hard to get the information.

**Affected users and/or printers**
I think it hits a pretty broad swath of people. I'm kinda afraid it's right there in front of me and I'm missing it. :-)

**Additional context**

![image](https://user-images.githubusercontent.com/42385/62743969-62f92080-b9f9-11e9-9c5b-9c7500022469.png)

Brand X:
![image](https://user-images.githubusercontent.com/42385/62744179-4ad5d100-b9fa-11e9-9c19-f1fcef9a7b00.png)

Brand Y:
![image](https://user-images.githubusercontent.com/42385/62744257-9daf8880-b9fa-11e9-9c11-8baa5693775c.png)

**Comment by Vandrasc** [comment] 2019-08-12 10:36
Devs see CURA-6714, for our internal reference.

**Comment by DivingDuck** [comment] 2019-08-14 13:40
+1 
Would be nice having both information available.

**Comment by serial8killer** [comment] 2019-08-30 15:34
Please do this!!!.....

**Comment by Ghostkeeper** [comment] 2019-09-30 12:10
Duplicate of https://github.com/Ultimaker/Cura/issues/5744

**Closed by Ghostkeeper** 2019-09-30 12:10 UTC
Labels: Type: New Feature
