### ISSUE TITLE
Weird resize function

### ISSUE THREAD

**Issue by Hum77** [Ultimaker/Cura#7446] opened 2020-04-07 19:43 UTC
**Application version**
Latest

**Platform**
Win 10 Ryzen 5 2600 16GB ddr5 2x RX570 3x 1TB SSD

**Printer**
FLSUN - qq S

**Reproduction steps**
Put model (disc 1.5 mm x 30mm with inner hole 10mm in my case) and try to resize X and Y automaticaly starts resizing Z too (box for resize all is unchecked)  When I return Z to 100 percent Y sucks to something about 85 percent

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
![image](https://user-images.githubusercontent.com/63316487/78712003-3692fc80-7918-11ea-926c-96b50949e60f.png) 

![image](https://user-images.githubusercontent.com/63316487/78712047-4579af00-7918-11ea-9562-a298a5f3baa4.png)

**Actual results**
Resizing not work.

**Expected results**
when I resize two axis from three I hope that third will stay.

**Project file**
[FQQS_gumove tesneni zaneta.zip](https://github.com/Ultimaker/Cura/files/4446698/FQQS_gumove.tesneni.zaneta.zip)

Thank You for Your SW.

**Comment by Ghostkeeper** [comment] 2020-04-09 14:59
This is a duplicate of https://github.com/Ultimaker/Cura/issues/4136, one of the most commonly-reported issues we have but also pretty hard to solve for us :(

**Closed by Ghostkeeper** 2020-04-09 14:59 UTC
Labels: Type: Bug
