### ISSUE TITLE
Fixed value for initial temperature v 3.1

### ISSUE THREAD

**Issue by carlosjln** [Ultimaker/Cura#2980] opened 2017-12-14 18:05 UTC
When saving a gcode file M109 S{material_print_temperature} is always set to M109 S220 no matter what value I set "Print Temperature".

**Comment by ChrisTerBeke** [comment] 2017-12-14 18:45
Duplicate of https://github.com/Ultimaker/Cura/issues/1296.

**Closed by ChrisTerBeke** 2017-12-14 18:45 UTC
