### ISSUE TITLE
Issue: saving files 

### ISSUE THREAD

**Issue by ljohnsonnsb** [Ultimaker/Cura#4092] opened 2018-07-17 14:38 UTC
**Application Version**

**Platform**
Windows 7 64bit

**Printer**
all

**Steps to Reproduce**
Rename a project via the interface  and then saving to SD or PC 

**Actual Results**
The renamed project is saved as the original name created by Cura..

**Expected results**
Should be saved as the name I provided.

**Additional Information**

**Comment by LipuFei** [comment] 2018-07-18 06:45
Hi @ljohnsonnsb , which Cura version are you using?

**Comment by diegopradogesto** [comment] 2018-07-18 07:13
Probably a duplicate of #4007 . In this case, it is fixed now on master and it will be available in the next release.

**Comment by ianpaschal** [comment] 2018-07-18 09:56
^I think that's safe to say. Sounds exactly the same. Going to close as fixed so we don't forget about it in September.

**Closed by ianpaschal** 2018-07-18 09:56 UTC
Labels: Status: Needs Info
