### ISSUE TITLE
Rotating models

### ISSUE THREAD

**Issue by paul-linked** [Ultimaker/Cura#12046] opened 2022-05-01 15:12 UTC
### Application Version

5.0.0 beta

### Platform

windows 10

### Printer

Artilary Sidewinder x2

### Reproduction steps

Click the rotate button on the left

### Actual results

![image](https://user-images.githubusercontent.com/72354134/166151971-d75d3edc-90d3-40a0-8abc-ebd4a9eacf53.png)

in Cura 5.0 beta i cannot rotate models. tried restarting cura and my machine but the problem wasn't solved

### Expected results

![image](https://user-images.githubusercontent.com/72354134/166152060-5c7be627-1c6d-41d5-9a56-08e740347359.png)

in cura 4.11 rotating works just fine

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Cura didn't crash, so i don't think log files are necessary

**Comment by jellespijker** [comment] 2022-05-01 17:14
Duplicate of #11882 and already fixed for the stable release.
@fvrmr I will close this ticket

**Closed by jellespijker** 2022-05-01 17:14 UTC
Labels: Type: Bug
