### ISSUE TITLE
"One after another" sequencing

### ISSUE THREAD

**Issue by Sophist-UK** [Ultimaker/Cura#7444] opened 2020-04-07 16:26 UTC
**Is your feature request related to a problem? Please describe.**
I wanted to print a small object and a tall object one after the other. Cura said it couldn't because the tall object would impact the gantry when printing the short object.

**Describe the solution you'd like**
Cura should not give this error message if there is only one object which is taller than the gantry size, and should print that object last.

**Describe alternatives you've considered**
None.

**Affected users and/or printers**
Anyone printing multiple items One After Another.

**Comment by Sophist-UK** [comment] 2020-04-08 15:24
Just tried to print a single object with One After Another set and got the same message. **Clearly** there can only be a problem with gantry if there is more than one model.

**Comment by Ghostkeeper** [comment] 2020-04-09 14:42
Your actual issue is a duplicate of https://github.com/Ultimaker/Cura/issues/6627.

But when you have only one model loaded, I'd expect that you'd see your build volume be increased to the normal printer height, rather than the gantry height. That's what I'm seeing in any case. Here is a screenshot of one object (which is taller than the gantry height):

![image](https://user-images.githubusercontent.com/2448634/78907364-e1262f00-7a80-11ea-8e11-fe9f318b5b4a.png)

And here is a screenshot of two objects, where the build volume gets reduced to the gantry height:

![image](https://user-images.githubusercontent.com/2448634/78907490-0fa40a00-7a81-11ea-9198-e3ab9dbe630e.png)

**Comment by Sophist-UK** [comment] 2020-04-09 15:14
Yes - it does appear to be a duplicate of #6627.

**Closed** 2020-04-09 15:14 UTC
Labels: Status: Needs Info, Type: Bug
