### ISSUE TITLE
"Drop model on build plate" not working

### ISSUE THREAD

**Issue by r2deco** [Ultimaker/Cura#1487] opened 2017-03-03 17:18 UTC
I am having issues with my models either floating above my build plate or below. (CURA ver. 2.4 ) I then brought my models in CURA ver. 15.04.6 and they were fine.

I was loading six parts arranged together at first. I then separated them out and imported them individually to CURA 2.4. One part was sunken under the build plate while the others were on top. I then cleared my build plate and brought in just the sunken part. It came in below the plate again. I triple checked my CAD file and all parts are above the CPlane.

If it works in CURA ver. 15.04.6 why not in ver. 2.4?

After writing my post, I tried turning my parts into a mesh before exporting as a .stl.  That worked.  Normally, I don't convert them to a mesh first.

**Comment by nallath** [comment] 2017-03-06 09:16
Could you share a project file where this is the case?

**Comment by BeimEckstein** [comment] 2017-03-06 17:52
I have a similar problem in cura 2.3 and 2.4. As well as with r2deco it was fine in CURA ver. 15.04.6. I shared this problem earlier on the ultimaker forum:
https://ultimaker.com/en/community/33886-first-layer-and-second-layer-dont-fit-together-in-cura231-when-using-support?page=1&sort=#reply-174007
First the object floated about 10 layers above the build plate. Then it was still possible to move it down manually. Now that is sunk into the build plate about 13 to 15 layers manual correction is no longer possible, because moving up the model is impossible.

**Comment by Ghostkeeper** [comment] 2017-03-07 09:46
Does the model have thin pieces at the bottom? Thinner than twice your line width?

If so, what happens is that Cura's front-end neatly places the model down on the build plate with the thin pieces touching the plate. When slicing, Cura discovers that those thin pieces are too small to be printed so they are left out. Normally, the model gets moved downwards then because empty layers at the bottom are always removed. However if you also enabled support, these layers are not empty and the mesh can't get moved downward. You then end up with a model that is floating (though it still has support).

This behaviour is not ideal, but it is sort of expected with the current implementation. A solution could be to check for layers at the bottom that only have support, but then the "drop objects on build plate" is basically always enforced.

**Comment by BeimEckstein** [comment] 2017-03-07 15:42
thanks Ghostkeeper for the reaction!
actually the bottom of the model is completely  flat ( i am glueing two pieces together at this flat plane. so any imperfection here is quite a problem.) There are thin pieces, but they do not go below the flat bottom of  my model. i will add a screenshot of the model with the modell in cura 2.4 where it is sunk into the platform. The brim indicates where the modell really starts to print. moving it up manually is impossible. als u can see here base of the modell consists of quite massive parts.

**Comment by BeimEckstein** [comment] 2017-03-07 15:43
thanks Ghostkeeper for the reaction!
actually the bottom of the model is completely  flat ( i am glueing two pieces together at this flat plane. so any imperfection here is quite a problem.) There are thin pieces, but they do not go below the flat bottom of  my model. i will add a screenshot of the model with the modell in cura 2.4 where it is sunk into the platform. The brim indicates where the modell really starts to print. moving it up manually is impossible. als u can see here base of the modell consists of quite massive parts.

**Comment by BeimEckstein** [comment] 2017-03-07 15:47
![cura 4p4 problem 01](https://cloud.githubusercontent.com/assets/26229456/23664377/b0bd961e-0355-11e7-939a-97a6d293d2de.JPG)

**Comment by BeimEckstein** [comment] 2017-03-07 15:50
![cura 4p4 problem 02](https://cloud.githubusercontent.com/assets/26229456/23664570/2f41e17a-0356-11e7-8035-665779e186a9.JPG)

**Comment by Ghostkeeper** [comment] 2017-03-08 09:50
I tried quite a few models, but it just doesn't reproduce on the models that I have. Is there a way in which you can share your model with us to test with? Or if you don't want to, share the bottom 1cm of your model if that also produces the problem?

**Comment by r2deco** [comment] 2017-03-08 14:40
FYI- It was built in inches.

**Comment by BeimEckstein** [comment] 2017-03-08 17:08
So here is a link to the stl file. after you downloaded it  i will delete the file again.
https://drive.google.com/file/d/0B1yGImITDzckNzk5eFhPTjlxZ1U/view?usp=sharing
thanks for checking!

**Comment by Ghostkeeper** [comment] 2017-03-09 09:27
I've downloaded the file.

**Comment by BeimEckstein** [comment] 2017-03-13 17:35
any ideas what is going on here?

**Comment by r2deco** [comment] 2017-03-13 19:16
I am having success converting my parts from inches to mm in my CAD app (Rhino3d) and then exporting them out as .stl.  Since doing this I haven't had the floating above or below the build plate issue. Here is a link to my file if it didn't go through with my last post.  
https://www.dropbox.com/s/wp6jmgyywq8qp91/2of6.stl?dl=0

**Comment by fieldOfView** [comment] 2017-03-13 20:37
Loading your model into Cura shows that Cura has to scale the model by 10000%. It looks like you have converted inches to cm, instead of inches to mm. I think the issue you are facing is due to rounding errors. Try exporting your stl at a factor 10 larger.

**Comment by r2deco** [comment] 2017-03-13 21:28
In the past I have created my parts in inches and then exported them as an .stl.  I used the old Cura version 15.04.6 and scaled it by entering 25.4 instead of 1.0 the "Scale X" field.  Now with the new 2.4 version of Cura I bring in the part and enter 2540 in the scale % field.  This particular part comes in at 1000% in the 2.4 version of Cura.  As you can see, regardless of the size/scale it still is below the build plate.  Version 15.04.6 comes in right on the build plate correctly.  

I have now changed my technique to change my part from inches to mm.  Then, I export it as a .stl.  This has cleared up my issues.  I hope this helps anyone else working with inches and bringing into Cura 2.4.

**Comment by fieldOfView** [comment] 2017-03-13 21:36
So, just to confirm with the others: does this issue manifest only when the object is scaled in Cura?

**Comment by Ghostkeeper** [comment] 2017-03-14 10:53
Sorry, I hadn't found the time yet to try this at home. I'm in the midst of moving.

**Comment by BeimEckstein** [comment] 2017-03-14 18:07
I have made my model in Rhino and used to rotate it and scale it down to 38% in Cura (see first pictures).
now i tried to rotate and scale it Rhino to the final size. That resulted in the model hovering above the platform instead of dropping below it. 
as next step i tried to scale it up in Rhino (factor 100 had more effect than factor 10) before and then have it scaled down in Cura again. That would minimize the mistake, but i think it is still a bit below the platform, such as it can be seen on the picture that i´ll attach.
![Uploading screenshot problem cura 2.4 skaled up.JPG…]()

**Comment by BeimEckstein** [comment] 2017-03-14 18:15
![screenshot problem cura 2 4 skaled up](https://cloud.githubusercontent.com/assets/26229456/23915481/8d9cb4b4-08e9-11e7-9dd0-a3e3c1bdacb3.JPG)

**Comment by Ghostkeeper** [comment] 2017-12-15 09:29
This is fixed for Cura 3.2.

**Closed by Ghostkeeper** 2017-12-15 09:29 UTC
Labels: bug
