### ISSUE TITLE
Brim support does not generate if Build Plate Adhesion is not also set to brim.

### ISSUE THREAD

**Issue by gilaramirez** [Ultimaker/Cura#16645] opened 2023-09-02 12:03 UTC
### Cura Version

5.4.0-Beta 1

### Operating System

Windows 10

### Printer

Snapmaker A350

### Reproduction steps

1, Enable support brim under supports
2. Select no brim or skirt under build plate adhesion

### Actual results

No brim is created around supports. Support/Brim width or line count has no effect on actual line count/width of support brim.

### Expected results

A brim should have been created around just the supports.  The support/brim width would override the build plate adhesion/brim type. -brim width, or -line count.

### Add your .zip and screenshots here ⬇️

[CFFFP_Body-White-Portal-Gun-3-1.zip](https://github.com/Ultimaker/Cura/files/12503911/CFFFP_Body-White-Portal-Gun-3-1.zip)

**Comment by Asterchades** [comment] 2023-09-03 06:34
This is a known issue and should be fixed with the next Cura release. Until then you will need to use either a Brim or Skirt in order to get the Support Brim to generate properly.

Duplicate of #14983.

**Closed by Asterchades** 2023-09-03 06:34 UTC
Labels: Type: Bug, Status: Triage
