### ISSUE TITLE
Top/Bottom Thickness error thickness if options Use adaptive layers enabled

### ISSUE THREAD

**Issue by lk29** [Ultimaker/Cura#7943] opened 2020-06-16 23:05 UTC
cura  4.6.1 

Win 10/64

Use adaptive layers enabled

If the upper or lower shell coincides with the function of the adaptive layer height, the layer height in mm is not calculated correctly.

Probably a pre-calculated height calculation is used before the function is triggered.

**Comment by mahtDFR** [comment] 2020-06-17 07:59
A project file or screenshot would help here, could you provide these please?

(`File > Save...` to save a project file)

**Comment by rburema** [comment] 2020-06-17 09:04
Sorry, accidentally closed. Wrong issue number in commit!

**Comment by lk29** [comment] 2020-06-17 10:03
![Clipboard03](https://user-images.githubusercontent.com/12291632/84884864-af969900-b0ab-11ea-8090-c8aa8f00d0dd.jpg)
![Clipboard02](https://user-images.githubusercontent.com/12291632/84884871-b0c7c600-b0ab-11ea-9456-65c0a6f42f9a.jpg)
![Clipboard01](https://user-images.githubusercontent.com/12291632/84884875-b1605c80-b0ab-11ea-90ef-97019a8bd4d3.jpg)

**Comment by lk29** [comment] 2020-06-17 10:05
[Cura_BUG_D_VP_Refined_Chamber_03.zip](https://github.com/Ultimaker/Cura/files/4791771/Cura_BUG_D_VP_Refined_Chamber_03.zip)

**Comment by lk29** [comment] 2020-06-17 10:07
Layers 90-93 thickness 0.1 4*0.1 = 0.4 
should be 0.8

**Comment by lk29** [comment] 2020-06-17 10:10
![Clipboard05](https://user-images.githubusercontent.com/12291632/84885611-b7a30880-b0ac-11ea-9395-47720266dfe9.jpg)
![Clipboard04](https://user-images.githubusercontent.com/12291632/84885615-b83b9f00-b0ac-11ea-9faf-a661d472b272.jpg)

**Comment by rburema** [comment] 2020-06-18 09:58
Hi @lk29 

Thanks for the info!

So it turns out this has been a known issue for a while, and is in fact a duplicate of #3913 we have an internal ticket for it, CURA-5104. Other related tickets are #3209 #4396 #5131 and #6188 

This is basically the big issue preventing us from moving adaptive layer heights out of 'experimental', not only because it would require a refactor of the engine in some key parts (possibly the biggest issue), but also because it isn't clear then whether the number of layers or the thickness of the vertically specified setting should be leading (what if the user specifies number of layers vs. thickness of feature in mm. or vice versa, or both).

We hope to start working on this at some point though. It's a matter of prioritisation.

Since this is a duplicate however, and the original ticket is still open, please continue any discussion over there.

**Closed by rburema** 2020-06-18 09:58 UTC
Labels: Status: Duplicate, Type: Bug
