### ISSUE TITLE
Cura 5.0.0 doesn't allow the import of .3mf files.

### ISSUE THREAD

**Issue by Veshraine** [Ultimaker/Cura#11993] opened 2022-04-27 09:22 UTC
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ender 3 V2

### Reproduction steps

Tried dragging and dropping .3mf file from desktop into program. Does not input.

### Actual results

Nothing, file does not input to build plate.

### Expected results

Should be able to drag and drop just like cura 4.9.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

None.

**Comment by fvrmr** [comment] 2022-04-28 08:02
Hi @Veshraine thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11937, so I will close this issue.

**Closed by fvrmr** 2022-04-28 08:02 UTC
Labels: Type: Bug
