### ISSUE TITLE
Support with own groundplane

### ISSUE THREAD

**Issue by BruderTack** [Ultimaker/Cura#3873] opened 2018-06-01 10:37 UTC
Support should have an own closed groundplane separated from the main body for maximum build plate adhesion

**Comment by AbeFM** [comment] 2018-06-04 18:48
There are maybe 5 other threads about exactly this.

It seems not to be a concern for the CURA team, but it seems significant to many of the users.

I feel this is a duplicate topic.

**Comment by Ghostkeeper** [comment] 2018-07-13 11:06
Indeed, this looks like a duplicate of https://github.com/Ultimaker/Cura/issues/3759.

**Closed by Ghostkeeper** 2018-07-13 11:06 UTC
Labels: Status: Needs Info
