### ISSUE TITLE
[4.0] Scaling UI issues after rotation

### ISSUE THREAD

**Issue by cp2004** [Ultimaker/Cura#5599] opened 2019-04-08 21:08 UTC
**Application Version**
4.0
**Platform**
Windows 10, 64bit
**Printer**
Custom FDM Printer (My Tronxy)
**Steps to Reproduce**

Import an object into Cura, rotate it in any axis, and then scale with the X/Y/Z arrows on the model
**Actual Results**

(For model meshes) The scale measurements are right, however the scale factor percentage is in the wrong box. 
(For support blockers) The scale arrows scale in the wrong direction. For X it scales Y, for  Y it scales Z. I think it changes depending on the rotation though.
**Expected results**

All axis scale in the right direction and the UI updates correctly
**Additional Information**

[scalebugreport.zip](https://github.com/Ultimaker/Cura/files/3056251/scalebugreport.zip)

**Comment by rburema** [comment] 2019-04-10 14:19
I can confirm that this happens in current master as well. I didn't need to rotate the support (on an already rotated model) to get the wrong behaviour though. We'll very probably make a ticket for it soon.

**Comment by Ghostkeeper** [comment] 2019-04-12 11:16
Duplicate of https://github.com/Ultimaker/Cura/issues/4136

**Closed by Ghostkeeper** 2019-04-12 11:16 UTC
Labels: Type: Bug
