### ISSUE TITLE
"arrange" funktion not working

### ISSUE THREAD

**Issue by yzorgone** [Ultimaker/Cura#10847] opened 2021-11-16 15:47 UTC
### Application Version

4.12

### Platform

Mac OS Monterey

### Printer

UM S5

### Reproduction steps

- load collection of stls. (specifically a collection where previous versions of cura could do that arrange function on)
- select all
- rightclick -> arrange models

### Actual results

nothing happens. all models stay were they are

### Expected results

all models should be placed next to each other. 
in previous versions of Cura this worked superb.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Project file could not be uploaded..  i zipped the 3mf file. page would tell me "is not included in list"

**Comment by nallath** [comment] 2021-11-17 08:33
Duplicate of #10249

**Closed by nallath** 2021-11-17 08:33 UTC
Labels: Type: Bug
