### ISSUE TITLE
Crash while printing on LulzBot mini 2

### ISSUE THREAD

**Issue by hdelien** [Ultimaker/Cura#12094] opened 2022-05-04 23:43 UTC
### Application Version

5.0

### Platform

Windows 10 pro

### Printer

LulzBot mini 2

### Reproduction steps

Manually added Lulzbot printer and g-code necessary to wipe head and auto level the bed.
G-Code performed perfectly, printer warmed up and began printing. Print was to be approximately 4.5 hours. 15 minutes in the program crashed and shut down.

### Actual results

15 minutes in the program crashed and shut down.

### Expected results

Finish print

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8627982/cura.log)

**Comment by fvrmr** [comment] 2022-05-05 11:18
Hi @hdelien thank you for your report.
Are you printing via USB? If so this is a duplicate of https://github.com/Ultimaker/Cura/issues/11896.
I will close this issue because it sounds like this is the same issue. Let me know if this is not the case.

**Closed by fvrmr** 2022-05-05 11:18 UTC
Labels: Type: Bug
