### ISSUE TITLE
FileNotFoundError: Could not find resource ('Prusa i3.json',)

### ISSUE THREAD

**Issue by hypery11** [Ultimaker/Cura#160] opened 2015-07-21 10:41 UTC
````
Exception:
Traceback (most recent call last):
  File "cura_app.py", line 9, in <module>
  File "c:\dev\uranium\UM\Application.py", line 329, in getInstance
  File "c:\dev\cura\cura\CuraApplication.py", line 56, in __init__
  File "c:\dev\uranium\UM\Qt\QtApplication.py", line 75, in __init__
  File "c:\dev\uranium\UM\Application.py", line 355, in loadMachines
  File "c:\dev\uranium\UM\Settings\MachineSettings.py", line 90, in loadValuesFromFile
  File "c:\dev\uranium\UM\Resources.py", line 50, in getPath
FileNotFoundError: Could not find resource ('Prusa i3.json',) in 2
````

**Comment by nallath** [comment] 2015-07-21 13:24
Duplicate of https://github.com/Ultimaker/Cura/issues/158

**Closed by nallath** 2015-07-21 13:24 UTC
