### ISSUE TITLE
"Center selected models" of merged model centers on "average center" not "geometric center"

### ISSUE THREAD

**Issue by BenoitValin** [Ultimaker/Cura#4194] opened 2018-08-05 02:58 UTC
**Application Version**
3.4.1

**Platform**
OS X

**Printer**
UM3x
[Center Selected Models.3mf.zip](https://github.com/Ultimaker/Cura/files/2260009/Center.Selected.Models.3mf.zip)

**Steps to Reproduce**
1. Add two models of an assembly
2. Merge 
3. "Center selected models" 

**Actual Results**
Assembly is centered around the average center of the multiple models that were merged together  and not the geometric center of the assembly, as when "Center selected models" are done on individual parts.
![what sappens](https://user-images.githubusercontent.com/42104538/43682159-85168ea6-989d-11e8-9df6-997033334153.png)

**Expected results**
The whole assembly should be located in the geometric center of the build plate
![what should happen](https://user-images.githubusercontent.com/42104538/43682160-8544710e-989d-11e8-80c4-c20129c6a33f.png)

**Additional Information**
nothing

**Comment by diegopradogesto** [comment] 2018-08-06 07:53
Thanks for reporting. Sounds like a bug to me, but it's happening for a long time. So maybe in the past it was decided that this is the right behavior. I will discuss with the colleagues.

**Comment by diegopradogesto** [comment] 2018-08-06 09:18
Devs. CURA-5617

**Comment by ianpaschal** [comment] 2018-08-06 09:36
Just to be clear, this is a bit confusing how the internal ticket is written. Currently it appears to move the center towards the center of mass (i.e. the side of the white piece which has the extra bit on it) when in fact it should be moved to the center of the resulting bounding box.

Using the bounding box will ensure that this works for this scenario as well as when two objects are not overlapping.

Also the described behavior refers to grouped models, not merged models, which both snap to the center (probably not the intended behavior but also a separate bug.

**Closed** 2018-08-09 12:31 UTC
Labels: Category: Cura, Status: Fixed/Solved, Type: Bug
