### ISSUE TITLE
Editing start and end G-codes

### ISSUE THREAD

**Issue by teho03** [Ultimaker/Cura#15370] opened 2023-04-27 10:00 UTC
### Application Version

5.3.1

### Platform

Win10 64 bit

### Printer

Ender 3 V2

### Reproduction steps

Going to the Preferences/Printers/Machine settings I found that as soon as I moved the cursor into either the start or end G-code regions the 'help screen' appears over the top of the area making it impossible to edit the G-codes. 

### Actual results

Cannot edit start/end G-codes

### Expected results

Am able to edit start/end G-codes

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Cura_screen_capture](https://user-images.githubusercontent.com/47057663/234829372-e82298f5-64bc-4e36-ac2d-00058d2cae98.jpg)

**Comment by fieldOfView** [comment] 2023-04-27 10:13
The Settings Guide plugin makes the tooltip much bigger than envisioned. You can fix this by disabling the plugin, or disabling its option to put the articles in tooltips.

**Comment by MariMakes** [comment] 2023-05-08 13:19
Hey @Gerhard-59,

Welcome to the Ultimaker Cura Github 🚀

This is related to the Settings Guide Plug-in.
People who don't have that plug-in installed, like me, just see this as tooltip:
![image](https://user-images.githubusercontent.com/40423138/236834518-0edc33f1-4f54-4c13-988b-8c35c21d64c8.png)


You can temporarily disable your plug-in in the marketplace by clicking the gear in the top right corner and then disable.
If you are done editing your gcode you can enable it again.
![image](https://user-images.githubusercontent.com/40423138/236834480-3dbc8b75-b4b1-475a-b8ac-9718742d2b96.png)

It's not a bug in Ultimaker Cura but one in the Settings Guide Plug-in.
I'll be closing this issue. I hope you understand.

**Closed by MariMakes** 2023-05-08 13:19 UTC
Labels: Type: Bug, Status: Triage
