### ISSUE TITLE
Cura 5 Cant Export Profiless

### ISSUE THREAD

**Issue by Toddi3D** [Ultimaker/Cura#12010] opened 2022-04-28 15:19 UTC
### Application Version

Cura 5.0.0 beta

### Platform

Windows 10 64

### Printer

Anycubic Vyper

### Reproduction steps

i cant export my profiles

### Actual results

nothing

### Expected results

nothing

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8584048/cura.log)

**Comment by GregValiant** [comment] 2022-04-28 23:34
Me too.
Click the dropdown and select "Export"
The Save dialog comes up.
Enter a file name and hit save.  The dialog closes but the file does not appear in the folder.
Enter a file name and the ".curaprofile" extension and same thing.  The dialog exits peacefully but no file appears in the folder.

**Comment by fvrmr** [comment] 2022-05-02 08:10
Hi @Toddi3D thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11971, so I will close this issue.

**Closed by fvrmr** 2022-05-02 08:10 UTC
Labels: Type: Bug
