### ISSUE TITLE
Cannot multiply objects

### ISSUE THREAD

**Issue by ukitconsultant** [Ultimaker/Cura#10746] opened 2021-11-05 08:04 UTC
### Application Version

4.12.0-BETA

### Platform

MacOS Monterey

### Printer

Creality Ender 3

### Reproduction steps

Added a STL file by dragging and dropping or by using the file browser. Right clicked on the filename and left clicked on multiply. Typed in "2", then either pressed return or clicked OK. 

### Actual results

A box appears stating that it is"Placing Objects" with the text "Multiplying and placing objects", with an empty progress bar and does not progress. 

After some time exiting the program and restarting it, then re-trying the process results in the same issue.

### Expected results

I had expected the object to be multiplied into 2 identical copies of the same object. 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7481567/cura.log
<img width="2061" alt="CleanShot 2021-11-05 at 08 02 31@2x" src="https://user-images.githubusercontent.com/2316302/140478067-22da0fa8-f9a7-43a7-8b99-53774d819734.png">
<img width="2081" alt="CleanShot 2021-11-05 at 08 02 23@2x" src="https://user-images.githubusercontent.com/2316302/140478080-550c5a2e-6e58-44a5-829e-6942f6b85344.png">
<img width="2073" alt="CleanShot 2021-11-05 at 08 02 07@2x" src="https://user-images.githubusercontent.com/2316302/140478088-52d2150f-84ff-4af4-ae7a-5d316ecffe82.png">
)

This bug also seems to effect 4.11.0, as I updated to the beta in order to see if that resolved the issue, but it did not.

**Comment by ukitconsultant** [comment] 2021-11-05 08:16
Just to add. I am on an 2017 Intel iMac Pro with an Intel 18-Core Xeon 2.3Ghz and 128GB of RAM, as well as the dual Radeon Pro Vega 64 (16GB of GDDR), so I do not think it's a hardware issue. It worked before I updated to Monterey, and appears to have been introduced as an issue, possibly because of some of the core OS changes in Monterey.

**Comment by fieldOfView** [comment] 2021-11-05 08:23
Duplicate of #10249

**Comment by fvrmr** [comment] 2021-11-05 09:58
Closing this issue since it is a duplicate.

**Closed by fvrmr** 2021-11-05 09:58 UTC
Labels: Type: Bug
