### ISSUE TITLE
Using a negative value for horizonal expansion causes infill to not generate in thin walls

### ISSUE THREAD

**Issue by 5o6** [Ultimaker/Cura#19886] opened 2024-11-10 05:35 UTC
### Cura Version

5.8.1

### Operating System

Windows 10

### Printer

Ender 3 (Klipper, All-metal hotend, z probe)

### Reproduction steps

Slice a model with thin walls (less than 3mm) with a horizonal expansion value under 0 (-0.05 in my case). Notice missing infill.

### Actual results

Infill does not generate within the walls 

### Expected results

Infill should generate within the walls

### Add your .zip and screenshots here ⬇️

![Screenshot 2024-11-10 003432](https://github.com/user-attachments/assets/4edae6fe-4a06-46a5-a082-192f0a0bb7f3)
[CE3PRO_Bolt Pinning Jig - Imperial.zip](https://github.com/user-attachments/files/17690339/CE3PRO_Bolt.Pinning.Jig.-.Imperial.zip)

**Comment by GregValiant** [comment] 2024-11-10 12:21
Thanks for the report.
I don't think this really had anything to do with Horizontal Expansion other than it dropped the size of the "model feature" below a point that affected the infill generator filter.  This looks like a duplicate of #19478 (and #19802).
A repair has been made in 5.9.0-beta.2.
This is layer 455 in 5.8.1
![image](https://github.com/user-attachments/assets/f21ea373-edb5-4ad3-83d0-9b7cf2f7bbb6)

And this is layer 455 in 5.9.0-beta.2  (the beta.1 release does not have this fix in it).
![image](https://github.com/user-attachments/assets/4e3f2d63-820e-44ea-afc0-e710d960dc5a)

I'll mark this as a duplicate and go ahead and close it.  I hope you understand.

**Closed by GregValiant** 2024-11-10 12:21 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation

**Comment by 5o6** [comment] 2024-11-10 15:36
Thanks for the quick response, I'll go ahead and use the beta for now then.
