### ISSUE TITLE
2.5 crash after selecting object (STL)

### ISSUE THREAD

**Issue by bartwaw** [Ultimaker/Cura#1607] opened 2017-03-30 07:42 UTC
Version: 2.5.0-BETA
Platform: Windows-10-10.0.14393
Qt: 5.7.1
PyQt: 5.7.1

Exception:
TypeError: unable to convert a C++ 'QVector3D' instance to a Python object

after selecting object
http://antennas.prodrone.pl/klucz8-5-4mm.STL

it happens every time.

**Comment by nallath** [comment] 2017-03-30 09:28
Duplicate of https://github.com/Ultimaker/Cura/issues/1591, https://github.com/Ultimaker/Cura/issues/1594 and https://github.com/Ultimaker/Cura/issues/1566

**Closed by nallath** 2017-03-30 09:28 UTC
