### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by marioejojo** [Ultimaker/Cura#13368] opened 2022-09-23 22:29 UTC
### Application Version

5.1.0

### Platform

windows 10 pro

### Printer

creality ender-3

### Reproduction steps

slice
![slicing failed](https://user-images.githubusercontent.com/114265044/192064650-04b5a945-0efa-4367-8730-c0a76df162c7.jpg)

### Actual results

slice failed

### Expected results

sliced file. ready to 3D print

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![slicing failed](https://user-images.githubusercontent.com/114265044/192065002-13df59a1-ff0b-4414-9a23-6465be537f1f.jpg)

**Comment by GregValiant** [comment] 2022-09-24 02:14
Thanks for the report.
I've seen that model here a few times.  There are so many errors in it that it can't be repaired and therefore is impossible to slice.  The tail in particular is really bad.  There is a similar model called the Crystal Dragon and it has the same issues.
This is a duplicate of #13200.  I'll close this as it is a model error and not a fault with Cura
Here is the view in Mesh Mixer.  The colored balls indicate errors in the model.  You can see that the tail is one big error.
![image](https://user-images.githubusercontent.com/64202104/192075728-9335b791-f0a9-4882-9b3a-ec85a9af4f98.png)

**Closed by GregValiant** 2022-09-24 02:14 UTC
Labels: Status: Duplicate, Status: Under Investigation
