### ISSUE TITLE
Cura Update 4.10 Ultimaker S3 problem

### ISSUE THREAD

**Issue by FabioGS3** [Ultimaker/Cura#10146] opened 2021-07-16 09:18 UTC
### Application Version

4.10

### Platform

Windows 10

### Printer

Ultimaker S3

### Reproduction steps

1. Updated Cura from 4.8.0 to 4.10.0

### Actual results

1. Update worked fine, Cura works besides lost Settings.

### Expected results

1. Problem: After slicing models and wanting to print them, a prompt on the Ultimaker S3 comes up telling me the used Cura Version is outdated, please use Version 4.4 or higher. Models were sliced with Cura 4.10.0. Screenshots attached of Cura
![Screenshot 2021-07-16 111730](https://user-images.githubusercontent.com/87522849/125924487-2f3d606f-9795-4147-9786-b1fb2c54428b.jpg)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

n/a

**Comment by fieldOfView** [comment] 2021-07-16 09:22
Check if there is a firmware update available on the S3.

**Comment by fvrmr** [comment] 2021-07-16 11:02
Duplicate of https://github.com/Ultimaker/Cura/issues/10062

**Closed by fvrmr** 2021-07-16 11:02 UTC
Labels: Type: Bug

**Comment by FabioGS3** [comment] 2021-07-16 11:32
@fieldOfView  Worked, thanks !!!
