### ISSUE TITLE
[4.5] Sliced model missing layers

### ISSUE THREAD

**Issue by jvos1** [Ultimaker/Cura#7316] opened 2020-03-20 19:59 UTC
**Application version**
4.5 but also 4.4

**Platform**
Windows 7

**Printer**
CR10-s5

**Reproduction steps**
Import stl model and slice it.
Tried with different settings but it always seems to make the same error

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/62445746/77201443-c3525380-6aec-11ea-9633-ef3bf8311318.png)

**Actual results**
When trying to print, it only prints the bottom. The top part is failing and becomes a blob of plastic attached to your nozzle. After checking the sliced result in the preview window it was obvious that the gcode was missing layers (See picture)

**Expected results**
Normally it should print it completely, not only the bottom.

**Project file**
[CCR1_BoltForSensorDummy.zip](https://github.com/Ultimaker/Cura/files/4361597/CCR1_BoltForSensorDummy.zip)

**Log file**
Log not needed. It is easy to reproduce.

**Additional information**
I tried slicing it with **slic3r** and there it works fine. Sliced as expected, no missing layers. Also prints normal.

**Comment by Ghostkeeper** [comment] 2020-03-24 12:48
Your model is not manifold. You can see this clearly in X-ray view:
![image](https://user-images.githubusercontent.com/2448634/77426937-cb084580-6dd5-11ea-9bae-51789e2b0e20.png)

That means that somewhere it's missing walls or there are extra walls on the inside. Somewhere there are walls that don't fully enclose a volume. It is then ambiguous what the inside is of the model. In this case, Cura is wrong there on the bottom and in the corner at the top.

I've written an article on this that goes a bit deeper into the geometry of this problem: https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/troubleshooting/missing_parts.md#non-manifold-meshes

In this case the problem is fixed by enabling the "Keep Disconnected Faces" setting. However your model is simply broken so it's better to fix the mesh itself.

**Closed by Ghostkeeper** 2020-03-24 12:48 UTC
Labels: Type: Bug
