### ISSUE TITLE
Font problem, digits overlapped, in 4.9.0 / 4.9.1

### ISSUE THREAD

**Issue by erezgur** [Ultimaker/Cura#9829] opened 2021-05-14 14:17 UTC
### Application Version

4.9.0

### Platform

Windows 10

### Printer

Creality Ender 3

### Reproduction steps

When using cura on a windows machine with Hebrew font installed, or maybe the RTL support (I'm using English + Hebrew keyboard setting).
Open the advanced print settings to display the parameters and values.
![image](https://user-images.githubusercontent.com/7229729/118279480-df286e00-b4d3-11eb-8afb-d60a01a4c346.png)

### Actual results

The digits in the values fields of the print settings are not readable as shown in the picture 
 the numeric values in the print settings dialog are jammed, as if one digit is displayed on another digit, as seen in the attached picture.
![image](https://user-images.githubusercontent.com/7229729/118279354-b86a3780-b4d3-11eb-8db8-edd136e2ca0f.png)

### Expected results

Number (digits) should be displayed correctly as in previous versions (4.8 etc).

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/6479353/cura.log)

**Comment by fvrmr** [comment] 2021-05-14 14:44
Hi @erezgur thank you for your bug report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9667
That's why I will close this issue.

**Closed by fvrmr** 2021-05-14 14:44 UTC
Labels: Type: Bug
