### ISSUE TITLE
Project name changes unexpectedly

### ISSUE THREAD

**Issue by blopa1961** [Ultimaker/Cura#11756] opened 2022-04-02 16:01 UTC
### Application Version

4.13.1

### Platform

Windows 10 Pro 64

### Printer

Ender 5

### Reproduction steps

Prepare 2 files with different shapes so we can distinguish them, let's say "ring.stl" and "box.stl" (samples attached)
Then follow these steps:
open cura
open **box.stl**
slice
save to disk **box.gcode**
file/save project **box.3mf**
clear build plate
open **ring.stl**
slice
file/save project **ring.3mf**
save to disk (renaming file) **ring2.gcode**
file/open project **box.3mf**
slice
save to disk (renaming file) **box2.gcode**
file/save project ... what is the project name now?

### Actual results

after these steps, the project name changed back to **ring** (!)

### Expected results

the project currently open is **box**, I did not expect the project name to change back to **ring**
tough bug to catch, but I did have trouble with my projects and overwrote a couple
I use to change the name of my gcode files while I save them so as to include printing time and PLA weight in the file name, this is how I found this bug

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[BoxAndRing.zip](https://github.com/Ultimaker/Cura/files/8402883/BoxAndRing.zip)

**Comment by fvrmr** [comment] 2022-04-04 08:19
Hi @blopa1961 thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11276 and we have a ticket on our backlog for this. 
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2022-04-04 08:19 UTC
Labels: Type: Bug
