### ISSUE TITLE
An uncaught exception has occurred!

### ISSUE THREAD

**Issue by deladriere** [Ultimaker/Cura#178] opened 2015-07-23 15:01 UTC
Version: 15.06.02
Platform: Darwin-14.4.0-x86_64-i386-64bit
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "/Applications/Cura.app/Contents/Resources/cura_app.py", line 10, in <module>
  File "cura/CuraApplication.pyc", line 176, in run
  File "UM/Application.pyc", line 246, in setActiveMachine
  File "UM/Signal.pyc", line 96, in emit
  File "cura/CuraApplication.pyc", line 503, in _onActiveMachineChanged
  File "cura/BuildVolume.pyc", line 142, in rebuild
TypeError: can't multiply sequence by non-int of type 'float'

**Comment by nallath** [comment] 2015-07-24 06:53
Duplicate of #154

**Closed by nallath** 2015-07-24 06:53 UTC
