### ISSUE TITLE
3.6beta printhead shadow too big

### ISSUE THREAD

**Issue by PeggyB3D** [Ultimaker/Cura#4720] opened 2018-11-03 09:33 UTC
**Application Version**
3.6 beta

**Platform**
 
mac10.13.6

**Printer**
 
S5

**Steps to Reproduce**
 add a small object and use 'one at a time'

**Actual Results**
 shadow of the printhead is huge, multiplying objects is almost impossible

**Expected results**
size should be as in previous versions

**Additional Information**

![cura-3 4 99](https://user-images.githubusercontent.com/44723048/47950517-b5318080-df53-11e8-8693-f2e2f37acbd2.jpg)
![cura-6beta](https://user-images.githubusercontent.com/44723048/47950518-b5318080-df53-11e8-99c5-db9f5ed1f636.jpg)

**Comment by nallath** [comment] 2018-11-06 15:37
We already had this logged on our internal tracker (CURA-5822)

**Comment by LipuFei** [comment] 2018-11-19 07:40
Fixed in https://github.com/Ultimaker/Cura/commit/93bd5fee5387e45ea880ee1fc6125790546e465a

**Closed** 2018-11-19 08:30 UTC
Labels: Category: Cura, Status: In Progress, Type: Bug

**Comment by JeremyDWilliams** [comment] 2019-04-16 16:31
Still seeing this issue with 4.0.0

**Comment by Ghostkeeper** [comment] 2019-04-17 11:30
We'll need some new reproduction steps if you're still seeing it, because I can't reproduce the issue in 4.0 either.
