### ISSUE TITLE
Problem with concentric supports

### ISSUE THREAD

**Issue by VlamirDM** [Ultimaker/Cura#12969] opened 2022-08-07 05:07 UTC
### Application Version

5.0.0 end 5.1.0

### Platform

Windows 10

### Printer

Qidi x-max

### Reproduction steps

1. Loaded the gear model.
2. in the support section set the type of support concentricity
3 . when changing the % density of support, in reality the density does not change
4. slicing

### Actual results

![Снимок 3](https://user-images.githubusercontent.com/110737528/183275925-87573f57-10f1-4e4d-b953-a5755400781b.JPG)

Even when installing additional support separately, nothing changes. everything is bad too

### Expected results

![Снимок 1](https://user-images.githubusercontent.com/110737528/183276058-44b901f3-9a7e-4ca1-885a-ce4d6a374fcb.JPG)

cura v 4.16.0

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

fix this problem as soon as possible.

**Comment by VlamirDM** [comment] 2022-08-07 05:10
I like to use the new version with its new developments. but concentric supports, other types of supports cannot be replaced in my case

**Comment by GregValiant** [comment] 2022-08-07 10:50
Thanks for the report.
This same behavior occurs on my system.  This is a (near) duplicate of #12956 .  Someone from the Cura Team will take a look.

**Comment by GregValiant** [comment] 2022-08-07 11:05
Closed in favor of #12808

**Closed by GregValiant** 2022-08-07 11:05 UTC
Labels: Type: Bug, Status: Duplicate
