### ISSUE TITLE
Cura 4.6.1 Prime Tower - Skipping layers for secondary extruder.

### ISSUE THREAD

**Issue by hinotori74** [Ultimaker/Cura#7977] opened 2020-06-25 03:19 UTC
Hi all,

I use the second extruder to print the supports (PVA - Support Roof Extruder/Support Floor Extruder), but when generating the gcode, it is observed that the printing of the second extruder is not constant in the tower, so it does not have a base on which to print.

![imagen](https://user-images.githubusercontent.com/23563618/85649234-fae71380-b678-11ea-9abe-b0c440d13b0a.png)

I understand this may be to save time and material, but the first extruder must at least fill that space for the second extruder to have a base to print on.

Sorry for my English, i speak spanish.
Thanks

**Comment by BagelOrb** [comment] 2020-06-26 09:03
@hinotori74 please use the issue template when filing a bug report.

**Comment by BagelOrb** [comment] 2020-06-26 09:04
This is a feature, not a bug. This is intended behavior.

We think that a prime tower actually prints well like that. Do you have a photo of a failed prime tower because of this issue?

**Comment by Ghostkeeper** [comment] 2020-07-02 07:10
Duplicate of https://github.com/Ultimaker/Cura/issues/6909.

**Closed by Ghostkeeper** 2020-07-02 07:10 UTC
Labels: Type: Bug
