### ISSUE TITLE
(5.3.1) "Slicing failed with an unexpected error" when slicing

### ISSUE THREAD

**Issue by Nich-K** [Ultimaker/Cura#15896] opened 2023-06-24 08:24 UTC
### Cura Version

5.3.1

### Operating System

Windows 11

### Printer

Anycubic i3 Mega X

### Name abnormal settings

Wall Thickness = 0.8/ Wall Count = 2

### Describe your model

Model gets sliced successfully with wall thickness of 1.2mm/ 3 lines

### Add your .zip here ⬇️

[tower-level-2_project.zip](https://github.com/Ultimaker/Cura/files/11855964/tower-level-2_project.zip)

**Comment by MariMakes** [comment] 2023-07-17 15:10
Hey @Nich-K,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I recognize this issue. 🔎
This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/15836, where using custom supports would result in a slicing crash. 

![image](https://github.com/Ultimaker/Cura/assets/40423138/647e2f22-53f2-42fb-9959-eb27330cceb0)

It's resolved in the 5.4 stable release, you can download the Cura version with the fix here: https://github.com/Ultimaker/Cura/releases/tag/5.4.0
I'll close this issue since it's a duplicate and resolved. 

Thanks again, and please let us know if you run into any other issues 💪

**Closed by MariMakes** 2023-07-17 15:10 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:
