### ISSUE TITLE
Problema con el plugin mks wifi

### ISSUE THREAD

**Issue by ignacioj16** [Ultimaker/Cura#10174] opened 2021-07-23 08:40 UTC
### Application Version

4.10

### Platform

Windows 7

### Printer

Hellbot magna 2 230 dual

### Reproduction steps

1 Instale el plugin mks wifi
2 Reinicie el programa

### Actual results

El plugin MKS WIFI no aparece en las opciones de administrador de impresoras 

### Expected results

Figurar un boton para poder conectar la impresora via wifi

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![foto problema](https://user-images.githubusercontent.com/87852621/126757662-ff4ee370-5e97-41a2-89af-5877a587e9ac.jpg)

**Comment by fvrmr** [comment] 2021-07-26 07:43
Hi @ignacioj16 this is a duplicate of https://github.com/Ultimaker/Cura/issues/10070 and this is not an issue with Cura but with the plugin that is not yet supported for 4.10. 
I will close this issue as a duplicate.

**Closed by fvrmr** 2021-07-26 07:43 UTC
Labels: Type: Bug
