### ISSUE TITLE
Error loading .stl all files save in Solidworks 2016.

### ISSUE THREAD

**Issue by Rodrigo9Barbosa** [Ultimaker/Cura#12493] opened 2022-06-10 19:55 UTC
### Application Version

5.0.0

### Platform

Win 10 Pro

### Printer

Sethi 3d

### Reproduction steps

1. Open .stl file saving on solidworks 2016.
2. error!

### Actual results

![image](https://user-images.githubusercontent.com/107277498/173139375-573cc4b5-245b-4808-9ce7-a9fb8ce91a08.png)

### Expected results

Open file .stl

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Tampa - Caixa Elétrica mk3.zip](https://github.com/Ultimaker/Cura/files/8881901/Tampa.-.Caixa.Eletrica.mk3.zip)

These are the files I tested recently, but the error happens in all. In version 4.7.1 this error does not occur.

**Comment by fieldOfView** [comment] 2022-06-10 21:38
Could you try if it works if you don't use accented characters in the filename?

**Comment by Rodrigo9Barbosa** [comment] 2022-06-11 22:05
Hi, @fieldOfView !

Tks for trying help,
but your suggestion didn't work either...
the mystery continues.

**Comment by fieldOfView** [comment] 2022-06-12 10:03
If that did not work, we really need the Cura.log file, which can be found in the folder that opens when you go to Help -> Show configuration folder...

**Comment by fieldOfView** [comment] 2022-06-12 10:12
I can confirm the STLs don't load in Cura 5.0.
Excerpt from the log:
```
2022-06-12 12:05:26,551 - INFO - [MainThread] cura.CuraApplication.readLocalFile [1751]: Attempting to read file file:///C:/Users/Aldo/Desktop/Tampa - Caixa Elétrica.STL
2022-06-12 12:05:26,556 - INFO - [JobQueueWorker [3]] STLReader.STLReader.load_file [61]: Using legacy code to load STL data.
2022-06-12 12:05:26,558 - DEBUG - [JobQueueWorker [3]] STLReader.STLReader._read [102]: File did not contain valid data, unable to read.
2022-06-12 12:05:26,574 - ERROR - [JobQueueWorker [3]] UM.FileHandler.ReadFileJob.run [80]: Exception: Exception occurred while loading file C:/Users/Aldo/Desktop/Tampa - Caixa Elétrica.STL
2022-06-12 12:05:26,600 - ERROR - [JobQueueWorker [3]] UM.FileHandler.ReadFileJob.run [80]: Traceback (most recent call last):
2022-06-12 12:05:26,601 - ERROR - [JobQueueWorker [3]] UM.FileHandler.ReadFileJob.run [80]:   File "UM\FileHandler\ReadFileJob.py", line 78, in run
2022-06-12 12:05:26,602 - ERROR - [JobQueueWorker [3]] UM.FileHandler.ReadFileJob.run [80]:     self.setResult(self._handler.readerRead(reader, self._filename))
2022-06-12 12:05:26,602 - ERROR - [JobQueueWorker [3]] UM.FileHandler.ReadFileJob.run [80]:   File "UM\Mesh\MeshFileHandler.py", line 36, in readerRead
2022-06-12 12:05:26,602 - ERROR - [JobQueueWorker [3]] UM.FileHandler.ReadFileJob.run [80]:     results = reader.read(file_name)
2022-06-12 12:05:26,603 - ERROR - [JobQueueWorker [3]] UM.FileHandler.ReadFileJob.run [80]:   File "UM\Mesh\MeshReader.py", line 36, in read
2022-06-12 12:05:26,604 - ERROR - [JobQueueWorker [3]] UM.FileHandler.ReadFileJob.run [80]:     if mesh.source_mime_type is None:
2022-06-12 12:05:26,605 - ERROR - [JobQueueWorker [3]] UM.FileHandler.ReadFileJob.run [80]: AttributeError: 'NoneType' object has no attribute 'source_mime_type'
2022-06-12 12:05:26,606 - DEBUG - [JobQueueWorker [3]] UM.FileHandler.ReadFileJob.run [83]: Loading file took 0.1 seconds
```
This is using the official release. 
OT: It is interesting that Numpy STL does not seem to be used at all in Cura 5.0

**Comment by nallath** [comment] 2022-06-13 08:23
Could you share the STL so we can also debug the crash?

I will add this to the discuss list, because numpy-stl not working at the very least is an issue.

**Comment by fieldOfView** [comment] 2022-06-13 09:59
@nallath: Some STLs is included in the zip in the opening post.

**Comment by nallath** [comment] 2022-06-13 13:40
Closing this as a duplicate for #12239 

The numpy-stl issue will be added to our backlog!

**Closed by nallath** 2022-06-13 13:40 UTC
Labels: Type: Bug, Status: Under Investigation

**Comment by fieldOfView** [comment] 2022-06-13 14:10
Ah, so I was close with the filename, but I missed that the model name was also included in the stl file.

As a workaround, you *could* edit the first line of the .stl file in a text editor to only include ASCII characters, or you can make sure the models in Solidworks don't have non-ascii characters in them in the first place.
