### ISSUE TITLE
Speeds are messed up

### ISSUE THREAD

**Issue by stema84** [Ultimaker/Cura#2403] opened 2017-09-08 14:42 UTC
I was using s3d, had a few issues with it so now I'm trying to use cura 2.7. The problem is that it's printing the first layer too fast IMO. In s3d printing speed was 50, and 1st layer 50%, in cure I set 1st layer to 25, but I feel that it does it faster which I don't really like, there are some issues. Any suggestions?
ps. Seems like every speed is messed up, travelling between elements REALLY slowly, than printing at the speed of traveling.. Using stable 2.7

**Comment by smartavionics** [comment] 2017-09-09 19:58
How about attaching a screengrab that shows the speed settings you are using and then maybe someone will be able to make a useful comment?

**Comment by stema84** [comment] 2017-09-10 15:17
you're right, sorry
![speeds](https://user-images.githubusercontent.com/22154797/30250271-be28148a-964b-11e7-8d10-d22843b49f44.png)
I'll post the gcode soon

**Comment by stema84** [comment] 2017-09-10 16:38
here's the g-code, it has 3 kind of models in it (dial knobs, fists, graduation hats), whenever it has finished a layer of a graduation hat, it travelled to the next model extremely slowly on a wierd path, scratching the surface just printed. Then when it did the 1st outer line for one of the knobs that was too fast for my taste.
https://drive.google.com/open?id=0B_LDy_PeVVWmc0x6NG1VU29ldXc

**Comment by smartavionics** [comment] 2017-09-10 17:41
OK, thanks for the data. I can see from the data that you have found the same bug as https://github.com/Ultimaker/Cura/issues/2371 and a fix for that has already been submitted for inclusion in the next release.

**Comment by stema84** [comment] 2017-09-10 17:54
Thank you! It should've been a z-hop but actually it carved a bit into the layer so it haven't lift it (don't know if it lowered it or the carving was because of the heat)

**Comment by smartavionics** [comment] 2017-09-10 17:58
If your printer can handle a higher z speed than 5 mm/s, try entering the speed it can handle into the Maximum Z Speed setting. The problem is that it is using the speed used for the z-hop for the following travel and extrusion moves which is why they happen dog slow. Other than that, the only other option is to turn off the z-hop.

**Comment by stema84** [comment] 2017-09-10 18:00
thank you!

**Comment by Ghostkeeper** [comment] 2017-09-15 12:51
Duplicate of #2371.

**Closed** 2017-09-15 12:50 UTC
Labels: duplicate
