### ISSUE TITLE
When aktivate  Raft,, Draft Shield starts in the Air at second Layer

### ISSUE THREAD

**Issue by Kaicura** [Ultimaker/Cura#10177] opened 2021-07-23 19:24 UTC
### Application Version

4.8, 4.9 , 4.10

### Platform

Win 7

### Printer

SidewinderX1

### Reproduction steps

1 Aktivate Raft , 0,1 or 0,2 Gap, or zero Gap
[Zahnrad_Ratsche.zip](https://github.com/Ultimaker/Cura/files/6870775/Zahnrad_Ratsche.zip)

2. Aktivate Draft Schield.
Draftschield starts at second Partlayer
![0,5_Layer+0,5_gap](https://user-images.githubusercontent.com/65878296/126831011-0d61708d-8240-4ea5-9fde-8d469ca2cb7c.JPG)

### Actual results

Print fails, Draft print in the Air
![Zero_gap](https://user-images.githubusercontent.com/65878296/126831138-20b862ea-7a6d-4a3e-977c-53fc170b414c.JPG)

### Expected results

![0,5_Layer+0,5_gap](https://user-images.githubusercontent.com/65878296/126831268-2db76c3d-d0a7-4e76-b1c1-4bd5c60a1228.JPG)
, Print fails

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Thebug isin Cura 4,10, 4.9.1, 4.8

**Comment by fvrmr** [comment] 2021-07-26 10:12
Hi @Kaicura thank you for your report. This is a duplicate of https://github.com/Ultimaker/Cura/issues/8815 and we have a ticket on our backlog for this. 
I will close this ticket as a duplicate.

**Closed by fvrmr** 2021-07-26 10:12 UTC
Labels: Type: Bug
