### ISSUE TITLE
Wall Ordering not working properly

### ISSUE THREAD

**Issue by Dixitrix** [Ultimaker/Cura#12869] opened 2022-07-27 00:16 UTC
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ender 5

### Reproduction steps

Printing 3 walls. Both setting "Outside To Inside" and "Inside To Outside" both settings print the outer walls first and then the inner wall.
![Cura Wall Issue](https://user-images.githubusercontent.com/110070512/181132855-009c107f-5949-4bf0-bab4-c9608c4d8f1d.png)
 

### Actual results

The Outer Walls print first and it does not matter which of the two settings are selected.

### Expected results

"Outside To Inside" - The Outside walls should print first and then the inner wall
"Inside To Outside" - The Inner wall should print first and then the outer walls

I have tested this in 4.13.1 and it prints the inner walls first and then the outher walls. 

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Giant Stack Tube.zip](https://github.com/Ultimaker/Cura/files/9194007/Giant.Stack.Tube.zip)

**Comment by Vandresc** [comment] 2022-07-28 10:57
hi @Dixitrix , I see this as a duplicate of https://github.com/Ultimaker/Cura/issues/11934. The current wall ordering description text describes Inside to Outside and Outside to Inside. It however does not explain that the Centre line will always be printed last, no matter what order is chosen. The center last line is now plotted with the same color as the inner walls, suggesting that it behaves as an inner wall which is not the case, this is indeed very confusing. For this we do have a ticket in our backlog, to improve the description. Will therefore close as duplicate but please feel free to re-open if you consider that is not the same issue you encounter.

**Closed by Vandresc** 2022-07-28 10:57 UTC
Labels: Type: Bug, Status: Triage
