### ISSUE TITLE
Can`t change machine settings. Cura 4.4

### ISSUE THREAD

**Issue by Nemori27** [Ultimaker/Cura#6780] opened 2019-12-09 13:06 UTC
**Application version**
Cura 4.4

**Platform**
Windows 10

**Printer**
Tevo Tarantula

**Reproduction steps**
1. Go to Settings > printer > mannage printers > machine settings and change nozzle diameter fron 0.4 to 0.2
2. Apply changes, tried with Enter button, close, or Escape button. Every time i reopen settings there is still 0.4 mm nozzle. 

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/58692340/70437672-cde46200-1a94-11ea-81cf-3c345d3b9599.png)
![image](https://user-images.githubusercontent.com/58692340/70437805-1e5bbf80-1a95-11ea-8916-3477e7ad8766.png)

**Actual results**
Nothing happens, every time i reopen settings there are still 0.4 mm nozzle

**Expected results**
0.2 mm nozzle in extruder parameters

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/3939752/cura.log)

**Additional information**
Had no such problem in earlier versions

**Comment by rburema** [comment] 2019-12-10 08:07
What's your locale set to?

**Comment by Nemori27** [comment] 2019-12-10 09:55
> What's your locale set to?
Not shure that i understand you, can you formulate question it another way?

**Comment by rburema** [comment] 2019-12-10 10:04
I asked that because I think it might be a duplicate of #6685. You might want to have a look there as well, to see if it helps you.

Like I say there:
> A 'locale' in the sense that I meant is basically the (collection of) internationalisation settings that (a program or) the OS is set to. For instance, if I set my locale to Dutch (nl_NL), then, not only will the language change, but the default decimal separator will be a `,` while the thousands separator will be a `.` (the opposite of what it is in English (en_EN)).

**Comment by Ghostkeeper** [comment] 2019-12-10 10:21
So basically, what's the language settings of Windows? This includes:
* The language of the operating system.
* The localisation settings (so whether to display time as `MM-DD-YYYY` or `DD-MM-YYYY` and such).
* The keyboard layout.

In particular the second one is probably the one that causes this, as it affects how to display numbers (as `123.456,00` or `123,456.00`).

**Comment by Nemori27** [comment] 2019-12-10 10:36
> So basically, what's the language settings of Windows? This includes:
> 
> * The language of the operating system.
> * The localisation settings (so whether to display time as `MM-DD-YYYY` or `DD-MM-YYYY` and such).
> * The keyboard layout.
> 
> In particular the second one is probably the one that causes this, as it affects how to display numbers (as `123.456,00` or `123,456.00`).

OS language is russian, keyboard layout english, date DD-MM-YYYY

**Comment by Ghostkeeper** [comment] 2019-12-10 10:41
Yeah it looks like this is a duplicate of #6685 then. Please continue discussion/investigation there.

**Closed by Ghostkeeper** 2019-12-10 10:41 UTC
Labels: Status: Needs Info

**Comment by Nemori27** [comment] 2019-12-10 10:43
> Yeah it looks like this is a duplicate of #6685 then. Please continue discussion/investigation there.

Yep, guess youre right, situation seems the same, thank you
