### ISSUE TITLE
Feature request: Custom layer height

### ISSUE THREAD

**Issue by Flo082002** [Ultimaker/Cura#6840] opened 2019-12-22 11:51 UTC
It would be very nice to have an option to set a custom layerheight.
Example:
Layer 1 to 5 : 0.2mm
Layer 6 to 7 : 0.1mm
Layer 8 to 10 : 0.2mm

**Comment by Ghostkeeper** [comment] 2019-12-23 11:54
Duplicate of https://github.com/Ultimaker/Cura/issues/4235.

**Closed by Ghostkeeper** 2019-12-23 11:54 UTC
