### ISSUE TITLE
has_custom_materials does not hide materials by default anymore? 

### ISSUE THREAD

**Issue by filipgoc** [Ultimaker/Cura#3851] opened 2018-05-25 04:55 UTC
Hi, 

Application Version
3.3.1

Platform
Mac

Printer
JellyBOX

It seems that Cura now includes all materials that do not exclude the printer (hardware compatible) by default.

It used to be that when using has_custom_materials, Cura would show _only_ the materials that I explicitly added the printer to. 

**Is this a bug or a new feature?** How is the system designed to work now? 

Thanks!

**Comment by filipgoc** [comment] 2018-05-25 04:58
PS: I can see that there's an option to 'exclude_materials' in the definition file, but this does not hide materials added in the future, and it would be a lot of work to exclude everything (in addition to generics)

**Comment by fieldOfView** [comment] 2018-05-25 06:08
Duplicate of #3603, which has been marked as a bug but has not yet seen progress.

**Closed** 2018-05-25 07:11 UTC
Labels: Status: Duplicate

**Comment by filipgoc** [comment] 2018-05-25 12:41
Right! Sorry for duplication, I missed that bug report.
