### ISSUE TITLE
Plantage Cura 4.9 & OSX.13.6

### ISSUE THREAD

**Issue by orkide11** [Ultimaker/Cura#9649] opened 2021-04-22 09:47 UTC
### Application Version

4.9

### Platform

OSX.13.6

### Printer

Artillery Sidewinder X1

### Reproduction steps

Le logiciel plante systématiquement

### Actual results

Le logiciel plante systématiquement

### Expected results

Le logiciel plante systématiquement

**Comment by fieldOfView** [comment] 2021-04-22 09:54
If the actual results and the expected results match, then what's the issue? Please fill in the issue template in english, and provide details and preferably logs, or there is nothing that we can do to diagnose and fix the issue you have.

**Comment by jwrw** [comment] 2021-04-22 15:15
Noting the O/S version - potentially related to #9631 ?

**Comment by fvrmr** [comment] 2021-04-23 10:03
I will close this issue since @orkide11 commented on that issue.
So this issue is a duplicate of #9631

**Closed by fvrmr** 2021-04-23 10:03 UTC
Labels: Status: Needs Info, Type: Bug
