### ISSUE TITLE
Option to "rev" fans to prevent stalling

### ISSUE THREAD

**Issue by Mr-Figs** [Ultimaker/Cura#8829] opened 2020-11-25 04:24 UTC
**Problem Statement**
My fans don't spin up unless I give them ~50% power or more. They can go lower than that in operation, but only if I rev them up first. Otherwise, they stay in a "stalled" state and make a dreadful noise until you give them a push to get started.

**Proposed Solution**
An advanced option to "rev" the fans to their max speed for a few seconds whenever starting/restarting them from 0%. It's probably best if the extruder idles off to the side during this process, instead of doing it while printing.

**Alternatives**
My current workaround is to use the ChangeAtZ post-processing script to force the 4th layer to always be at 100% speed. It works, but overrides the more nuanced "ramp" behavior that Cura usually provides. It also overrides all successive layers, despite choosing "Target Layer Only", so I have a second instance of the script to hard-code the rest of the print at 35% speed.

It also works to set a high "regular" speed, but this means unnecessary noise and excessive part cooling. Also, I've found that ramping up gradually to a given speed is less reliable than starting cold, so I have to pick even higher speeds with this solution.

**Affected users and/or printers**
I did not have this issue until I installed a custom fan duct with dual 5015 radial fans. I don't think too many stock printers have this issue, but a decent number of enthusiasts have similar setups (i.e. Ender 3 owners). I'm not sure what percentage of that userbase has this particular issue.

**Comment by Ghostkeeper** [comment] 2020-11-27 10:53
Duplicate of https://github.com/Ultimaker/Cura/issues/8221. We consider this somewhat the responsibility of the firmware, truth be told.

**Closed by Ghostkeeper** 2020-11-27 10:53 UTC
Labels: Type: New Feature
