### ISSUE TITLE
Multi extrude gcode doesn't explicitely select start extruder

### ISSUE THREAD

**Issue by MB3Y** [Ultimaker/Cura#2919] opened 2017-12-05 19:58 UTC
Gcode generated for 3 extruders (maybe also 2) doesn't add specifically "T0" as start extruder.
My printer remembers the last used extruder and start print with it.
So my print starts with T0, T1, or T2 in absence of an explicit extruder select cmd.

**Comment by fieldOfView** [comment] 2017-12-05 21:28
Duplicate of #1819 

This will be fixed in Cura 3.2 (the fix in https://github.com/Ultimaker/CuraEngine/pull/640 was not merged in time for Cura 3.1)

**Closed** 2017-12-05 21:42 UTC
Labels: duplicate

**Comment by MB3Y** [comment] 2017-12-05 22:13
Nice!
Unfortunately the workaround indicated in #1819 is not possible for me, since the Geeetech Rostock 301 has mixing features that are to be selected before the print starts. Putting T0 in my start script would overrule this feature.
I'll be patiently awaiting R3.2 ;)

**Comment by stuartpb** [comment] 2018-01-01 23:26
Well, *some* of Ultimaker/CuraEngine#640 must have been merged, because all my multi-extruder G-code starts with `T0` already in 3.1, and I'm not using the RepRap or Griffin flavor.
