### ISSUE TITLE
Curved walls problem

### ISSUE THREAD

**Issue by MrWho900913** [Ultimaker/Cura#8397] opened 2020-09-16 21:49 UTC
I was struggling with some mostly round object, and i had artifacts on walls. So i got into it and possibly found a cause. Cura sometimes generates some extra tiny moves(+-0.025mm), that can cause my printer(and possibly others too) to slow down or even stop temporarily, as it tries to process them. I made a "simple" model to show this behavior. I looked into the gcode with gcode.ws with transparent move lines in 2D, and it showed me that there are some radiuses/curves, where these tiny moves are generated and where is corresponding artifact. To be more concrete, Cura generates in that model something like two sets of radial lines of line starts, which rotate in opposite direction when changing layers, and when theres minimal gap between them, stuttering and artifacts are present.
I bet this rotation leads to better surface finish, but... BUT.

My setup? Cartesian printer made from Ender3 - Fysetc S6 mainboard, Marlin 2.0.5.4(without display, all control over USB)           
Printing via Octoprint on win notebook - tried Repetier host, (havent tried Cura, since it has 32bit CPU), if something changes - same result, SDCard not available for me.
Cura 4.7.1

To minimize comm delays I configured HUGE buffers in marlin(32KB...), ramped comm speed to 1M plus played with some other settings that could have some impact. Same result.

Played around with with slicing resolution and deviation and some other parameters, still same problem.

[Stuttering.zip](https://github.com/Ultimaker/Cura/files/5235161/Stuttering.zip)

**Comment by rburema** [comment] 2020-09-17 05:37
I think this issue is a duplicate of #8321 (One of the issues pinned at the top of the issues page.) The stuttering is caused by a bug in the simplification algorithm (which is responsible for adhering to resolution and deviation parameters), introduced (and present) in 4.7.x

We're aware of this serious problem, and are working hard to make sure 4.8 will not suffer from this problem.

I'm closing this one as a duplicate. Please continue any discussion in #8321 (We close duplicates so we can easily reference the available information instead of hunting through different issues.)

**Closed by rburema** 2020-09-17 05:37 UTC
Labels: Status: Duplicate, Type: Bug
