### ISSUE TITLE
Windows 10 dark themes

### ISSUE THREAD

**Issue by promacjoe** [Ultimaker/Cura#6421] opened 2019-09-25 21:10 UTC
**Application version** 
Cura 4.2.1

**Platform**
Windows 10, current version, fully updated.

**Printer**
CR-10S.
"This is a GUI Issue. "

**Reproduction steps**
When using Windows 10 Accessibility, dark themes 1,  Cura, Preferences settings.
 Preferences menu barely readable. 
 Printer type, barely readable. 
 material settings, not readable. 
 Profile settings, not readable.

**Actual results**
Can't set these properties without  resetting  Windows 10 display settings. Since I'm legally blind, this makes these settings barely readable. Checkbox menus are perfect. Please do not change them.

**Expected results**
Make all Menus follow the Windows 10 display settings. 

**Additional information**
You're halfway there now,, you just need to be consistent with all your menus.
Also, this thing takes forever to load. Please work on It.

**Comment by Ghostkeeper** [comment] 2019-09-26 11:24
Duplicate of https://github.com/Ultimaker/Cura/issues/5490 and https://github.com/Ultimaker/Cura/issues/4826.

The material management screen is our next candidate for converting to Cura's theme (rather than your system theme). It's on the planning.

**Closed by Ghostkeeper** 2019-09-26 11:24 UTC
Labels: Type: Bug
