### ISSUE TITLE
Cura 3.1.0 can't set temp with "M109 S{material_print_temperature_layer_0}"

### ISSUE THREAD

**Issue by yanivg101** [Ultimaker/Cura#3011] opened 2017-12-18 16:42 UTC
Hi,
this is the setting of the material and the printer:
![image](https://user-images.githubusercontent.com/6355171/34116934-b2cb7648-e422-11e7-93f0-37ef6e74d1f9.png)

and this is the gcode I got in the begining:

```
;FLAVOR:Marlin
;TIME:9243
;Filament used: 7.80936m
;Layer height: 0.3
;Generated with Cura_SteamEngine 3.1.0
M190 S60
M82 ; absolute extrusion mode
M109 S210 ; wait for extruder temp
M109 S210

G32; Run Auto bed leveling
M82; Absolute Extrusion
G90; Absolute Positioning
```

why I get 210c deg instead of 260c?

(also I want to know if Cura can produce M109 with 1000c deg, I'm trying to 3D print with Glass)

**Comment by ChrisTerBeke** [comment] 2017-12-18 17:46
Duplicate of https://github.com/Ultimaker/Cura/issues/1296.

**Closed by ChrisTerBeke** 2017-12-18 17:46 UTC
