### ISSUE TITLE
STL file opend, shutdown

### ISSUE THREAD

**Issue by albatross9** [Ultimaker/Cura#10959] opened 2021-11-29 17:21 UTC
### Application Version

4.12.0

### Platform

windows10

### Printer

ender5

### Reproduction steps

1. install cura 4.12.0
2. add printer ender5
3. open stl file
4. shutdown

### Actual results

when open any STL file just shutdown
but other is working

i add for cura.cfg  opengl_version_detect = force_legacy[view]
and disable plugin - {"disabled": ["USBPrinting", "RemovableDriveOutputDevice"], "to_install": {}, "to_remove": []}

### Expected results

not privew

2021-11-30 02:11:47,437 - INFO - [MainThread] cura.Machines.MachineErrorChecker._setResult [213]: Error check finished, result = False, time = 1.9s
2021-11-30 02:11:47,790 - INFO - [MainThread] cura.CuraApplication.readLocalFile [1764]: Attempting to read file file:///C:/Users/asdfasdf.stl
2021-11-30 02:11:47,793 - INFO - [JobQueueWorker [1]] STLReader.STLReader.load_file [53]: Using NumPy-STL to load STL data.
2021-11-30 02:11:47,797 - DEBUG - [JobQueueWorker [1]] UM.Mesh.MeshData.calculateNormalsFromVertices [558]: Calculating normals took 0.0 seconds
2021-11-30 02:11:47,797 - DEBUG - [JobQueueWorker [1]] STLReader.STLReader._read [105]: Loaded a mesh with 15402 vertices
2021-11-30 02:11:47,818 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2021-11-30 02:11:47,820 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]: AttributeError: 'NoneType' object has no attribute 'close'
2021-11-30 02:11:47,941 - WARNING - [JobQueueWorker [1]] UM.Mesh.MeshData.createConvexHull [515]: Loaded model may be low-dimensional, apply QJ to make it full dimensional.
2021-11-30 02:11:47,944 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2021-11-30 02:11:47,946 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
2021-11-30 02:11:47,948 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]:   File "C:\build\Cura\4.12-exe\build\inst\lib\python3.8\site-packages\UM\Mesh\MeshData.py", line 512, in createConvexHull
2021-11-30 02:11:47,949 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]:   File "qhull.pyx", line 2433, in scipy.spatial.qhull.ConvexHull.__init__
2021-11-30 02:11:47,951 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]:   File "qhull.pyx", line 270, in scipy.spatial.qhull._Qhull.__init__
2021-11-30 02:11:47,952 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]:   File "messagestream.pyx", line 36, in scipy._lib.messagestream.MessageStream.__init__
2021-11-30 02:11:47,953 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]: OSError: Failed to open file b'C:\\Users\\\xec\x86\xa1\xec\x83\x81\xed\x98\x84\\AppData\\Local\\Temp\\scipy-t83i_rrp'
2021-11-30 02:11:47,956 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]: 
2021-11-30 02:11:47,959 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]: During handling of the above exception, another exception occurred:
2021-11-30 02:11:47,961 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]: AttributeError: 'NoneType' object has no attribute 'close'
2021-11-30 02:11:48,022 - ERROR - [JobQueueWorker [1]] UM.Logger.logException [112]: Exception: Couldn't construct convex hull around mesh (using faux hull instead)
2021-11-30 02:11:48,023 - ERROR - [JobQueueWorker [1]] UM.Logger.logException [116]: Traceback (most recent call last):
2021-11-30 02:11:48,025 - ERROR - [JobQueueWorker [1]] UM.Logger.logException [116]:   File "C:\build\Cura\4.12-exe\build\inst\lib\python3.8\site-packages\UM\Mesh\MeshData.py", line 512, in createConvexHull
2021-11-30 02:11:48,026 - ERROR - [JobQueueWorker [1]] UM.Logger.logException [116]:   File "qhull.pyx", line 2433, in scipy.spatial.qhull.ConvexHull.__init__
2021-11-30 02:11:48,027 - ERROR - [JobQueueWorker [1]] UM.Logger.logException [116]:   File "qhull.pyx", line 270, in scipy.spatial.qhull._Qhull.__init__
2021-11-30 02:11:48,029 - ERROR - [JobQueueWorker [1]] UM.Logger.logException [116]:   File "messagestream.pyx", line 36, in scipy._lib.messagestream.MessageStream.__init__
2021-11-30 02:11:48,030 - ERROR - [JobQueueWorker [1]] UM.Logger.logException [116]: OSError: Failed to open file b'C:\\Users\\\xec\x86\xa1\xec\x83\x81\xed\x98\x84\\AppData\\Local\\Temp\\scipy-t83i_rrp'
2021-11-30 02:11:48,031 - ERROR - [JobQueueWorker [1]] UM.Logger.logException [116]: 
2021-11-30 02:11:48,033 - ERROR - [JobQueueWorker [1]] UM.Logger.logException [116]: During handling of the above exception, another exception occurred:
2021-11-30 02:11:48,034 - ERROR - [JobQueueWorker [1]] UM.Logger.logException [116]: 
2021-11-30 02:11:48,035 - ERROR - [JobQueueWorker [1]] UM.Logger.logException [116]: Traceback (most recent call last):
2021-11-30 02:11:48,037 - ERROR - [JobQueueWorker [1]] UM.Logger.logException [116]:   File "C:\build\Cura\4.12-exe\build\inst\lib\python3.8\site-packages\UM\Mesh\MeshData.py", line 517, in createConvexHull
2021-11-30 02:11:48,038 - ERROR - [JobQueueWorker [1]] UM.Logger.logException [116]:   File "qhull.pyx", line 2433, in scipy.spatial.qhull.ConvexHull.__init__
2021-11-30 02:11:48,039 - ERROR - [JobQueueWorker [1]] UM.Logger.logException [116]:   File "qhull.pyx", line 270, in scipy.spatial.qhull._Qhull.__init__
2021-11-30 02:11:48,041 - ERROR - [JobQueueWorker [1]] UM.Logger.logException [116]:   File "messagestream.pyx", line 36, in scipy._lib.messagestream.MessageStream.__init__
2021-11-30 02:11:48,042 - ERROR - [JobQueueWorker [1]] UM.Logger.logException [116]: OSError: Failed to open file b'C:\\Users\\\xec\x86\xa1\xec\x83\x81\xed\x98\x84\\AppData\\Local\\Temp\\scipy-8lsa51x5'
2021-11-30 02:11:48,044 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2021-11-30 02:11:48,046 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
2021-11-30 02:11:48,047 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]:   File "C:\build\Cura\4.12-exe\build\inst\lib\python3.8\site-packages\UM\Mesh\MeshData.py", line 512, in createConvexHull
2021-11-30 02:11:48,049 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]:   File "qhull.pyx", line 2433, in scipy.spatial.qhull.ConvexHull.__init__
2021-11-30 02:11:48,050 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]:   File "qhull.pyx", line 270, in scipy.spatial.qhull._Qhull.__init__
2021-11-30 02:11:48,051 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]:   File "messagestream.pyx", line 36, in scipy._lib.messagestream.MessageStream.__init__
2021-11-30 02:11:48,053 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]: OSError: Failed to open file b'C:\\Users\\\xec\x86\xa1\xec\x83\x81\xed\x98\x84\\AppData\\Local\\Temp\\scipy-t83i_rrp'
2021-11-30 02:11:48,054 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]: 
2021-11-30 02:11:48,234 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]: During handling of the above exception, another exception occurred:
2021-11-30 02:11:48,236 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
2021-11-30 02:11:48,237 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]:   File "C:\build\Cura\4.12-exe\build\inst\lib\python3.8\site-packages\UM\Mesh\MeshData.py", line 517, in createConvexHull
2021-11-30 02:11:48,239 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]:   File "qhull.pyx", line 2433, in scipy.spatial.qhull.ConvexHull.__init__
2021-11-30 02:11:48,240 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]:   File "qhull.pyx", line 270, in scipy.spatial.qhull._Qhull.__init__
2021-11-30 02:11:48,241 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]:   File "messagestream.pyx", line 36, in scipy._lib.messagestream.MessageStream.__init__
2021-11-30 02:11:48,243 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]: OSError: Failed to open file b'C:\\Users\\\xec\x86\xa1\xec\x83\x81\xed\x98\x84\\AppData\\Local\\Temp\\scipy-8lsa51x5'
2021-11-30 02:11:48,244 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]: 
2021-11-30 02:11:48,245 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]: During handling of the above exception, another exception occurred:
2021-11-30 02:11:48,247 - CRITICAL - [JobQueueWorker [1]] cura.CrashHandler.__init__ [69]: AttributeError: 'NoneType' object has no attribute 'close'

[cura.log](https://github.com/Ultimaker/Cura/files/7619931/cura.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

cpu - ryzen Cezanne 5700G
gpu - radeon graphics
mainboard - [MSI] MAG B450M 
win10

**Comment by nallath** [comment] 2021-11-30 09:20
Duplicate of #9644

**Closed by nallath** 2021-11-30 09:20 UTC
Labels: Type: Bug
