### ISSUE TITLE
Cura creates Gcode files  feedrates with size quadrillion

### ISSUE THREAD

**Issue by PrintingTom** [Ultimaker/Cura#5952] opened 2019-06-30 09:55 UTC
When slicing my file with cura 4.1 it creates a faulty gcode file. I have tried multiple files. It seems to be linked to retract and z hop, i reinstalled cura 4.1 and with the standard 15 mm setting, without any custom adjustments, it created again a gcode file with faulty feedrates.

result is that my printer is getting jammed for about 10 seconds and then continues

[CE3_Multi_Hanger_1.0.zip](https://github.com/Ultimaker/Cura/files/3342756/CE3_Multi_Hanger_1.0.zip)

**Application version**
Cura 4.1

**Platform**
windows 10

**Printer**
ender 3

**Reproduction steps**
printer got stuck, checked the gcode file. gcode files contains the following:

G1 X71.714 Y73.76 E395.14792
G1 F2400 E390.14792
G1 F17987547480000 Z1.2
G0 F900 X73.766 Y76.378 Z1.2
G1 F17987547480000 Z0.2
G1 F2400 E395.14792
G1 F1800 X73.852 Y76.512 E395.15427
G1 X74.222 Y77.129 E395.18299
G1 X74.572 Y77.79 E395.21284

**Actual results**
see above

**Expected results**
the feedrate should be around 7000 or less

**Additional information**

**Comment by smartavionics** [comment] 2019-06-30 10:32
Duplicate of #5753.

**Closed** 2019-07-01 12:39 UTC
Labels: Type: Bug
