### ISSUE TITLE
[3.5] Temperature is not correct in the GCode

### ISSUE THREAD

**Issue by lwbsbde** [Ultimaker/Cura#4469] opened 2018-10-03 19:40 UTC
I Have the following entry in the Start GCode 
 "M104 S{material_print_temperature}"

but no matter what I set as Temperature (200 or 240 )
in the generated GCode is always  "M109 S210 "

with Cura 3.4.1 the temperature was taken over correctly

![screenshot 1](https://user-images.githubusercontent.com/43827576/46436457-21ed0b80-c759-11e8-86b5-3eba99cd63ea.png)

**Comment by ChrisTerBeke** [comment] 2018-10-03 20:01
Please post your question/issue in English so all the developers can read it.

**Comment by ChrisTerBeke** [comment] 2018-10-03 20:28
Does `M104 S{material_print_temperature, 0}` work for you?

**Comment by lwbsbde** [comment] 2018-10-03 20:32
Thank you , it works  :-)

**Comment by ChrisTerBeke** [comment] 2018-10-03 20:34
Thanks for testing. It does seem we have a regression then because 0 should be the default... @Vandrasc

**Comment by LazaroFilm** [comment] 2018-10-04 00:37
Had the same issue here. Yes, adding the `, 0` solved it, but why did this change behavior in the first place?

**Comment by fieldOfView** [comment] 2018-10-04 06:41
@LazaroFilm, do you also have a multi-extrusion printer?

What is the adhesion extruder set to?

**Comment by ChrisTerBeke** [comment] 2018-10-04 11:16
@LazaroFilm it shouldn't have, that's why I mentioned a regression occured.

**Comment by Ketchu13** [comment] 2018-10-04 15:30
> Thanks for testing. It does seem we have a regression then because 0 should be the default... @Vandrasc

Hi,
my printer profile was with 2 extruders, reduced to only one (I don't have anymore dual extrusion installed on the printer)
using `{material_print_temperature, 0}` return the default not the first layer temperature value
using `{material_print_temperature_layer_0, 0}`  return the correct value

**Comment by Appesteijn** [comment] 2018-10-04 18:50
CURA-5793

**Comment by diegopradogesto** [comment] 2018-10-05 14:49
@lwbsbde are you using a custom printer definition? can you provide a project file or your configuration folder to deeply analyse what is going on here?

Thanks.

**Comment by lwbsbde** [comment] 2018-10-06 06:29
yes, I using a custom Printer definition. what folder do you mean?

**Comment by lekoder** [comment] 2018-10-07 10:42
This was a nasty surprise, with temperature defaulting to 210'C this caused my printer to grind trough the filament.

**Comment by gwax** [comment] 2018-10-07 21:17
I can confirm this issue as well. I can also confirm that the suggested workaround of specifying extruder 0 explicitly in the start gcode (`{material_print_temperature_layer_0, 0}`) worked for me.

**Comment by nallath** [comment] 2018-10-08 14:05
Fixed in https://github.com/Ultimaker/Cura/pull/4520

**Closed** 2018-10-08 14:36 UTC
Labels: Category: Cura, Status: In Progress, Type: Bug

**Comment by ctmakro** [comment] 2018-10-08 15:13
so I just ran into the same problem(downloaded 3.5 installer); happy to see it solved an hour ago.
