### ISSUE TITLE
Allow models being moved on positive Z

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#8150] opened 2020-08-05 16:41 UTC
**Is your feature request related to a problem? Please describe.**
Some items downloaded are supposed to be put together for multi-color printing or "chaining", but fail to do so because of being exported incorrectly. So you could still move manually them in the air to pose them, but the model can only touch the bed

**Describe the solution you'd like**
Allow the model to be moved up on the Z, with a checkbox of "touch the build plate" being optional

**Comment by videopilot** [comment] 2020-08-06 03:03
Doesn't turning off the "automatically drop to build plate" preferences option solve this?

**Comment by Liger0** [comment] 2020-08-06 13:15
> 
> 
> Doesn't turning off the "automatically drop to build plate" preferences option solve this?

I don't see that option anywhere, where is it?

**Comment by Ghostkeeper** [comment] 2020-08-06 15:10
It's in the preferences window:
![image](https://user-images.githubusercontent.com/2448634/89548746-b1f1b580-d807-11ea-84b6-55b4a554ebaa.png)

**Comment by Ghostkeeper** [comment] 2020-08-06 15:11
It's enabled by default because otherwise people have lots of failed prints because their models are floating in mid-air.

**Comment by Liger0** [comment] 2020-08-06 20:45
I understand that. It would be useful to have a per-item one anyway to make it selectable when moving it without. Like you can move a piece in the air but the new ones imported will still drop automatically on the build plate.

**Comment by videopilot** [comment] 2020-08-06 21:49
Well, when you turn that option off, new models still import on the build plate. Anything you then move up or down can be placed back to the build plate by typing 0 for its Z position. Seems complicated to make some objects moveable up and down and not others.

**Comment by Ghostkeeper** [comment] 2020-08-07 14:27
I'll close this as duplicate of https://github.com/Ultimaker/Cura/issues/8117 then, where we discuss about overriding this preference for certain models.

**Closed by Ghostkeeper** 2020-08-07 14:27 UTC
Labels: Type: New Feature
