### ISSUE TITLE
4.3     Z Seam bug

### ISSUE THREAD

**Issue by lwbsbde** [Ultimaker/Cura#6471] opened 2019-10-03 06:57 UTC
If I choose "User Specified" , I can not choose the Z Seam position.

**Comment by nallath** [comment] 2019-10-03 11:44
I can't reproduce this (although i did test this in master). I did the following:
1. Add UM3
2. Set "Z Seam Aligment" to 'User Specified' 
3. I can select values in the "Z seam X" and "Z seam Y" setting as well as "Z Seam Position"

**Comment by lwbsbde** [comment] 2019-10-03 13:33
in Cura 4.2.1  it worked too.  after update to 4.3 I have the error

**Comment by lwbsbde** [comment] 2019-10-03 13:35
![Screenshot (14)](https://user-images.githubusercontent.com/43827576/66131266-696bd900-e5f3-11e9-8d38-ec49578f72cf.png)

**Comment by nallath** [comment] 2019-10-03 13:56
Try and also enable the "Z seam X" and "Z seam Y". You probably manually set a value to them. Once you do that, you can't use the overarching (parent) setting anymore

**Comment by jcwebber93** [comment] 2019-10-03 15:30
I have a similar issue, although it is slightly different depending on the printer selected. In all cases I have the following options selected as visible:

- Z Seam alignment
- Z Seam position
    - Z Seam X
    - Z Seam Y
- Seam Corner Preference
- Z Seam Relative

For UM3, When selecting "User Specified" for "Z Seam Alignment", I can use the "Z Seam Position" dropdown (back, back left, etc). I do not seem to have the option to select the X or Y like in 4.2.1.
![Capture1](https://user-images.githubusercontent.com/42392142/66140824-c3a77280-e5d0-11e9-8df0-d5518fa4784d.PNG)

For a custom machine, selecting "User Specified" for "Z Seam Alignment", I can see but cannot use the "Z Seam Position" dropdown, (grayed out), and in addition I do not seem to have the option to select the X or Y like in 4.2.1.
![image](https://user-images.githubusercontent.com/42392142/66140919-edf93000-e5d0-11e9-83bc-28eb6c1a457c.png)

Visible settings for both test cases
![image](https://user-images.githubusercontent.com/42392142/66141157-3b759d00-e5d1-11e9-8d13-8b186be3dd65.png)

**Comment by smartavionics** [comment] 2019-10-03 16:02
I have had similar problems with the X and Y coordinates not being visible even when they should be and I got around it by closing the infill section and then re-opening it. I think it's a QML weirdness.

**Comment by jcwebber93** [comment] 2019-10-03 16:30
> I have had similar problems with the X and Y coordinates not being visible even when they should be and I got around it by closing the infill section and then re-opening it. I think it's a QML weirdness.

Closed all sections while having the custom printer selected, and it added back in the X and Y locations that were previously hidden.  Thanks for the workaround!
![image](https://user-images.githubusercontent.com/42392142/66145864-a4611300-e5d9-11e9-8745-d28142348fec.png)

**Comment by lwbsbde** [comment] 2019-10-03 17:43
Thanks.
 it works

**Comment by Ghostkeeper** [comment] 2019-10-07 11:21
I'm unable to reproduce that problem. Both UM3 and Custom FFF Printer just show the settings and allow me to change them. Maybe you could provide a project file saved when it was happening?

**Comment by Maarten88** [comment] 2019-10-10 23:23
I had the same problem, solved it using the tip in this issue: collapse the settings in and out, and the "Z seam X" and "Z seam Y" items re-appeared.
For reproduction I'd assume this probably happens only after migrating a profile having Z seam alignment set to "User Specified", with X and Y set to some value, from Cura 4.2 to 4.3.

**Comment by Ghostkeeper** [comment] 2019-10-14 09:35
I can't get the Z seam settings to disappear even when importing a profile made in 4.2 that contains those settings. This is the profile that I imported: [zseamprofile.zip](https://github.com/Ultimaker/Cura/files/3723798/zseamprofile.zip)

**Closed** 2020-06-19 20:47 UTC
Labels: Status: Needs Info, Type: Bug
