### ISSUE TITLE
Opening Cura

### ISSUE THREAD

**Issue by bigjthom** [Ultimaker/Cura#13287] opened 2022-09-14 04:08 UTC
### Application Version

5.1

### Platform

win 11

### Printer

Kobra

### Reproduction steps

Opening the application or any files causes cura to open on my second monitor. My second monitor is turned sideways and displays at a 1920x2560 resolution. Upon the application load cura seems to freeze and not recover. Unplugging my second monitor and using my main monitor of 2560x1440 always starts with no issues. I have to assume Cura doesnt like the resolution of the monitor. 

### Actual results

non responding cura everytime

### Expected results

load the cura file/ main application 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/45948856/190057278-54173b32-0773-4753-a4d9-089f881c0e32.png)
![image](https://user-images.githubusercontent.com/45948856/190057356-27c83341-876a-4d6b-b356-d481acff3c57.png)

**Comment by MariMakes** [comment] 2022-09-23 15:14
Hey @bigjthom,

Thanks for the report 👍 
This sounds familiar.

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12197
We have a ticket on our backlog with the intent to improve this behavior.
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12197

A surprising connection was found to some particular audio drivers: https://github.com/Ultimaker/Cura/issues/12197#issuecomment-1157988232
Found (and reported to) a possible bug in Qt, that might affect certain multi-monitor setups: https://bugreports.qt.io/browse/QTBUG-105070

**Closed by MariMakes** 2022-09-23 15:14 UTC
Labels: Type: Bug, Status: Triage
