### ISSUE TITLE
build plate adhesion type: Customizable brim locations

### ISSUE THREAD

**Issue by mathiaspl20** [Ultimaker/Cura#6420] opened 2019-09-25 17:05 UTC
**Is your feature request related to a problem? Please describe.**
When Printing large objects on an open printer I sometimes experience inadequate bed adhesion on sharp corners of my prints. 

**The solution I'd like and alternatives I've considered**
Brims are in many cases not the ideal solution because they can be hard/tedious to remove. I would like to request a feature that lets you place patches of brim for areas that would benefit from having one.

**Affected users and/or printers**
Anyone who is printing large objects or objects with sharp corners or small protruding features could benefit from this. In many cases printing an entire brim or raft would be a waste of both time and material. 

**Additional context**
[Screenshot ](https://i.imgur.com/fIQGZDs.png) of a possible use case, a sharp corner, where a brim would be very useful for adhesion. The Screenshot also shows how it does not work with a support blocker.
I did read #1503 but think many users could benefit from this  for specifically for sharp corners.

**Comment by Ghostkeeper** [comment] 2019-09-26 11:19
This is a duplicate of https://github.com/Ultimaker/CuraEngine/issues/423. It's essentially the "mouse ears" being asked for there. It seems to be a technique stemming from the experimenters with the RepRap project.

**Closed by Ghostkeeper** 2019-09-26 11:19 UTC
Labels: Type: New Feature
