### ISSUE TITLE
Triple click doesn't focus cursor on the desired field

### ISSUE THREAD

**Issue by dhysuiej** [Ultimaker/Cura#13502] opened 2022-10-08 12:50 UTC
### Application Version

5.1.1

### Platform

macOS Catalina 10.15.7

### Printer

Ender 3 v2

### Reproduction steps

1. Write some text in the field you want to edit.
2. Click somewhere else so that the field is no longer focused.
3. Triple click on the same field.

### Actual results

The field is focused momentarily and then the focus is lost, so that it's not possible to write new text to replace the previously selected. Please see the image attached in the field for additional information in this report. 

### Expected results

The expected behavior is that triple click should select the entire text in the field.
Double click only selects some parts of the text, like for instance a single word or the decimal part after the decimal point, and not the entire text, so currently there is no way to select the entire text and replace it by writing something. To do that one has to click or double click on the field and select all the text with a shortcut.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![ezgif-1-aa7eda77b1](https://user-images.githubusercontent.com/82825136/194708387-95aa0497-d4a0-4589-ac4e-643deac9a29f.gif)

**Comment by MariMakes** [comment] 2022-10-10 12:19
Hey @dhysuiej,

Thanks for your report 👍 
I recognize your issue. 😊 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12184
We have a ticket on our backlog with the intent to improve this behavior.

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12184

Thank you again.

**Closed by MariMakes** 2022-10-10 12:19 UTC
Labels: Type: Bug, Status: Duplicate, Status:  On Backlog
