### ISSUE TITLE
[4.5.0] CR10S Pro - Wrong bed size

### ISSUE THREAD

**Issue by ggardet** [Ultimaker/Cura#7433] opened 2020-04-06 14:45 UTC
**Application version**
4.5.0

**Platform**
Any

**Printer**
CR10S Pro

**Reproduction steps**
Check bed size in CR10S Pro settings, it is set to 300 mm x 300 mm, but the actual bed is 310 x 320 mm. 
Setting the size to 310 x 310 is better to center prints on bed, make use of a bigger area and avoid the clips around max Y and min Y. (Maybe print head values requires an update as well?)

**Screenshot(s)**
None

**Actual results**
300 x 300 mm size

**Expected results**
310 x 310 mm size

**Project file**
N/A

**Log file**
N/A

**Additional information**
N/A

**Comment by mahtDFR** [comment] 2020-04-06 14:53
Duplicate of #7252

**Closed by mahtDFR** 2020-04-06 14:53 UTC
Labels: Type: Bug
