### ISSUE TITLE
Strange behavior at startup. 

### ISSUE THREAD

**Issue by iakapulko** [Ultimaker/Cura#425] opened 2015-09-24 07:05 UTC
Before I ran the Cura first, and it was already selected a file for slicing. Today I launched the file directly from the folder and the program behavior was strange: firstly, in the printer settings is not set, and secondly, even after manually selecting the printer slicing does not start automatically. Require changing (any) of the model. Prior to this, .83 was not given messages about the denial of access to .
cfg file, now it happens every time at startup.
 Cura's log:
2015-09-24 12:48:21,504 - INFO - Loaded plugin FileLogger
2015-09-24 12:48:21,527 - INFO - Loaded plugin GCodeWriter
2015-09-24 12:48:21,555 - INFO - Loaded plugin LayerView
2015-09-24 12:48:21,588 - INFO - Loaded plugin LocalFileOutputDevice
2015-09-24 12:48:21,647 - INFO - Loaded plugin PostProcessingPlugin
2015-09-24 12:48:21,716 - INFO - Loaded plugin RemovableDriveOutputDevice
2015-09-24 12:48:21,837 - INFO - Loaded plugin SliceInfoPlugin
2015-09-24 12:48:21,897 - INFO - Loaded plugin CameraTool
2015-09-24 12:48:21,946 - INFO - Loaded plugin MirrorTool
2015-09-24 12:48:21,997 - INFO - Loaded plugin PerObjectSettingsTool
2015-09-24 12:48:22,072 - INFO - Loaded plugin RotateTool
2015-09-24 12:48:22,145 - INFO - Loaded plugin ScaleTool
2015-09-24 12:48:22,214 - INFO - Loaded plugin SelectionTool
2015-09-24 12:48:22,271 - INFO - Loaded plugin TranslateTool
2015-09-24 12:48:22,345 - INFO - Checking for new version of cura
2015-09-24 12:48:22,346 - INFO - Loaded plugin UpdateChecker
2015-09-24 12:48:22,452 - INFO - Loaded plugin USBPrinting
2015-09-24 12:48:22,531 - INFO - Loaded plugin MeshView
2015-09-24 12:48:22,613 - INFO - Loaded plugin WireframeView
2015-09-24 12:48:22,628 - INFO - Started engine process: C:\Program Files (x86)\Cura_15.09.83\CuraEngine.exe
2015-09-24 12:48:22,878 - ERROR - An exception occurred loading Machine Instance: C:\Users\user/AppData/Local/cura\machine_instances\Ultimaker+2.cfg: File C:\Users\user/AppData/Local/cura\machine_instances\Ultimaker+2.cfg is an invalid settings file
2015-09-24 12:48:22,880 - ERROR - An exception occurred loading Profile C:\Users\user/AppData/Local/cura\profiles\Normal+Quality+%28Customised%29.cfg: File C:\Users\user/AppData/Local/cura\profiles\Normal+Quality+%28Customised%29.cfg is an invalid settings file
2015-09-24 12:48:22,884 - DEBUG - Setting value of setting support_enable to False
2015-09-24 12:48:22,884 - WARNING - Tried to set value of non-user setting support_enable
2015-09-24 12:48:22,886 - DEBUG - Setting value of setting support_enable to False
2015-09-24 12:48:22,887 - WARNING - Tried to set value of non-user setting support_enable
2015-09-24 12:48:22,889 - DEBUG - Setting value of setting layer_height to 0.06
2015-09-24 12:48:22,890 - WARNING - Tried to set value of non-user setting layer_height
2015-09-24 12:48:22,891 - DEBUG - Setting value of setting layer_height to 0.1
2015-09-24 12:48:22,891 - WARNING - Tried to set value of non-user setting layer_height
2015-09-24 12:48:22,903 - ERROR - An exception occured while trying to read preferences file: 'general'
2015-09-24 12:48:22,934 - DEBUG - Setting active view to MeshView
2015-09-24 12:48:24,260 - DEBUG - Loaded theme C:\Program Files (x86)\Cura_15.09.83\resources\themes\cura
2015-09-24 12:48:25,717 - DEBUG - Calculating normals took 0.0009999275207519531 seconds
2015-09-24 12:48:25,717 - DEBUG - Loaded a mesh with 5100 vertices
2015-09-24 12:48:25,723 - DEBUG - Loading mesh took 0.13600802421569824 seconds
2015-09-24 12:48:25,880 - DEBUG - Preparing to send slice data to engine.
2015-09-24 12:48:26,240 - DEBUG - Backend connected on port 49674
2015-09-24 12:48:49,083 - DEBUG - Preparing to send slice data to engine.
2015-09-24 12:48:49,110 - DEBUG - Sending data to engine for slicing.
2015-09-24 12:49:10,856 - ERROR - Failed to write Instance to C:\Users\user/AppData/Local/cura\machine_instances\Ultimaker+2.cfg: [WinError 5] Отказано в доступе: 'C:\\Users\\user\\AppData\\Local\\cura\\machine_instances\\tmpktbr3kz_' -> 'C:\\Users\\user/AppData/Local/cura\\machine_instances\\Ultimaker+2.cfg'
2015-09-24 12:49:10,859 - ERROR - Failed to write profile to C:\Users\user/AppData/Local/cura\profiles\Normal+Quality+%28Customised%29.cfg: [WinError 5] Отказано в доступе: 'C:\\Users\\user\\AppData\\Local\\cura\\profiles\\tmplhad3lob' -> 'C:\\Users\\user/AppData/Local/cura\\profiles\\Normal+Quality+%28Customised%29.cfg'
2015-09-24 12:49:10,865 - ERROR - Failed to write preferences to C:\Users\user/AppData/Local/cura\cura.cfg: [WinError 5] Отказано в доступе: 'C:\\Users\\user\\AppData\\Local\\cura\\tmpj51dh_il' -> 'C:\\Users\\user/AppData/Local/cura\\cura.cfg'
2015-09-24 12:54:18,034 - INFO - Loaded plugin FileLogger
2015-09-24 12:54:18,057 - INFO - Loaded plugin GCodeWriter
2015-09-24 12:54:18,083 - INFO - Loaded plugin LayerView
2015-09-24 12:54:18,114 - INFO - Loaded plugin LocalFileOutputDevice
2015-09-24 12:54:18,148 - INFO - Loaded plugin PostProcessingPlugin
2015-09-24 12:54:18,197 - INFO - Loaded plugin RemovableDriveOutputDevice
2015-09-24 12:54:18,308 - INFO - Loaded plugin SliceInfoPlugin
2015-09-24 12:54:18,347 - INFO - Loaded plugin CameraTool
2015-09-24 12:54:18,398 - INFO - Loaded plugin MirrorTool
2015-09-24 12:54:18,442 - INFO - Loaded plugin PerObjectSettingsTool
2015-09-24 12:54:18,514 - INFO - Loaded plugin RotateTool
2015-09-24 12:54:18,568 - INFO - Loaded plugin ScaleTool
2015-09-24 12:54:18,624 - INFO - Loaded plugin SelectionTool
2015-09-24 12:54:18,677 - INFO - Loaded plugin TranslateTool
2015-09-24 12:54:18,732 - INFO - Checking for new version of cura
2015-09-24 12:54:18,732 - INFO - Loaded plugin UpdateChecker
2015-09-24 12:54:18,819 - INFO - Loaded plugin USBPrinting
2015-09-24 12:54:18,881 - INFO - Loaded plugin MeshView
2015-09-24 12:54:18,942 - INFO - Loaded plugin WireframeView
2015-09-24 12:54:18,956 - INFO - Started engine process: C:\Program Files (x86)\Cura_15.09.83\CuraEngine.exe
2015-09-24 12:54:19,184 - ERROR - An exception occurred loading Machine Instance: C:\Users\user/AppData/Local/cura\machine_instances\Ultimaker+2.cfg: File C:\Users\user/AppData/Local/cura\machine_instances\Ultimaker+2.cfg is an invalid settings file
2015-09-24 12:54:19,186 - ERROR - An exception occurred loading Profile C:\Users\user/AppData/Local/cura\profiles\Normal+Quality+%28Customised%29.cfg: File C:\Users\user/AppData/Local/cura\profiles\Normal+Quality+%28Customised%29.cfg is an invalid settings file
2015-09-24 12:54:19,189 - DEBUG - Setting value of setting support_enable to False
2015-09-24 12:54:19,189 - WARNING - Tried to set value of non-user setting support_enable
2015-09-24 12:54:19,191 - DEBUG - Setting value of setting support_enable to False
2015-09-24 12:54:19,191 - WARNING - Tried to set value of non-user setting support_enable
2015-09-24 12:54:19,195 - DEBUG - Setting value of setting layer_height to 0.06
2015-09-24 12:54:19,195 - WARNING - Tried to set value of non-user setting layer_height
2015-09-24 12:54:19,196 - DEBUG - Setting value of setting layer_height to 0.1
2015-09-24 12:54:19,196 - WARNING - Tried to set value of non-user setting layer_height
2015-09-24 12:54:19,205 - ERROR - An exception occured while trying to read preferences file: 'general'
2015-09-24 12:54:19,214 - DEBUG - Setting active view to MeshView
2015-09-24 12:54:20,323 - DEBUG - Loaded theme C:\Program Files (x86)\Cura_15.09.83\resources\themes\cura
2015-09-24 12:54:21,596 - DEBUG - Preparing to send slice data to engine.
2015-09-24 12:54:21,942 - DEBUG - Backend connected on port 49674
2015-09-24 12:54:32,069 - ERROR - Failed to write Instance to C:\Users\user/AppData/Local/cura\machine_instances\Ultimaker+2.cfg: [WinError 5] Отказано в доступе: 'C:\\Users\\user\\AppData\\Local\\cura\\machine_instances\\tmps9z66dun' -> 'C:\\Users\\user/AppData/Local/cura\\machine_instances\\Ultimaker+2.cfg'
2015-09-24 12:54:32,072 - ERROR - Failed to write profile to C:\Users\user/AppData/Local/cura\profiles\Normal+Quality+%28Customised%29.cfg: [WinError 5] Отказано в доступе: 'C:\\Users\\user\\AppData\\Local\\cura\\profiles\\tmpsx18npdn' -> 'C:\\Users\\user/AppData/Local/cura\\profiles\\Normal+Quality+%28Customised%29.cfg'
2015-09-24 12:54:32,077 - ERROR - Failed to write preferences to C:\Users\user/AppData/Local/cura\cura.cfg: [WinError 5] Отказано в доступе: 'C:\\Users\\user\\AppData\\Local\\cura\\tmpt9qkfx2y' -> 'C:\\Users\\user/AppData/Local/cura\\cura.cfg'

And link to small video: https://www.dropbox.com/s/2qqe477vo9anls6/cura%202.exe?dl=0

**Comment by awhiemstra** [comment] 2015-09-25 08:53
The printer not being selected is due to Ultimaker/Uranium#71 and should be fixed in the next build. I expect the not slicing issue to be also caused by that.

**Closed by awhiemstra** 2015-09-25 08:53 UTC
Labels: bug
