### ISSUE TITLE
Do not get rotation hoops

### ISSUE THREAD

**Issue by zammsieq** [Ultimaker/Cura#12029] opened 2022-04-30 06:42 UTC
### Application Version

5.0.0-beta+1

### Platform

Windows 11

### Printer

Ender 3

### Reproduction steps

Clicked on Rotate 

### Actual results

Do not get the rotation hoops

### Expected results

I expected to see the rotation hoops

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[Plug for bath breather.zip](https://github.com/Ultimaker/Cura/files/8596281/Plug.for.bath.breather.zip)

**Comment by jellespijker** [comment] 2022-05-01 17:14
Duplicate of #11882 and already fixed for the stable release.
@fvrmr I will close this ticket

**Closed by jellespijker** 2022-05-01 17:14 UTC
Labels: Type: Bug
