### ISSUE TITLE
error while slicing

### ISSUE THREAD

**Issue by pmarkiewicz** [Ultimaker/Cura#10729] opened 2021-11-03 08:16 UTC
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Unrelated

### Reproduction steps

1. Loaded 20x20 flat square (I used this many times in the past)
2. Got slice error

### Actual results

Slice error

### Expected results

Sliced

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.zip](https://github.com/Ultimaker/Cura/files/7466140/cura.zip
[20x20 flat.zip](https://github.com/Ultimaker/Cura/files/7466142/20x20.flat.zip)
)

**Comment by fvrmr** [comment] 2021-11-04 10:01
Hi @pmarkiewicz thank you for your bug report. 
This is a duplicate of #10394 and is probably happening because your model is lower than the initial layer height. This is fixed in 4.12 Beta. You can download the beta here: https://github.com/Ultimaker/Cura/releases/tag/4.12-beta

I will close this issue because it is a duplicate.

**Closed by fvrmr** 2021-11-04 10:01 UTC
Labels: Type: Bug
