### ISSUE TITLE
[BUG] Save To Removable Drive (2.6.2)

### ISSUE THREAD

**Issue by daver18qc** [Ultimaker/Cura#2125] opened 2017-07-16 21:31 UTC
This bug was not present in 2.5.x version, at least for me.

Windows 7 x64
Cura 2.6.2

Steps to reproduce : 
-Open Cura
-Load model, slice
-Insert MicroSD card in USB adapter and plug in computer
-Cura detects it and button changes to "Save To Removable Drive"
-Save your Gcode on it, or not.
-Eject the drive, either through Windows or Cura
-Remove the drive physically from the computer
-Save button stays the same, as if USB drive was still connected
-Even if you re-insert the USB drive with the same drive letter, you can't save on it anymore

Have to close and re-start Cura to save on USB drive again.
Even if you manually select "Save to File" then go back to "Save to Removable Drive", you can't save any more Gcode on it until you re-start Cura.

**Comment by nallath** [comment] 2017-07-17 07:25
Duplicate of https://github.com/Ultimaker/Cura/issues/2024

**Closed by nallath** 2017-07-17 07:25 UTC
