### ISSUE TITLE
Small gear icon next to category name to change visibility in settings is gone

### ISSUE THREAD

**Issue by mpsdskd** [Ultimaker/Cura#3178] opened 2018-01-24 19:10 UTC
I'm missing the small gear icon next to the category name to change settings visibility.
Is that gone intentionally or is that a bug?

![screenshot_20180124_195820](https://user-images.githubusercontent.com/12713677/35351895-9fdc90a2-0142-11e8-8103-3f84bbd6e607.png)

I know that I can right-click to change settings visibility, but I liked that gear icon feature.

3.2.0 BETA, Kubuntu 17.10

OT:
Big shout-out to all developers, 3.2 got a lot faster on my weak device.

I had problems with my profiles again, but since #2912 I know how to work around this.

**Comment by fieldOfView** [comment] 2018-01-24 20:50
Does not reproduce for me (ie: the gear icon shows up just fine running the beta on Windows).

Something else that caught my eye in your small screenshot is that it does not show a blue underline under the category. So the real issue seems to be that somehow mouse hover is not being detected.

**Comment by mpsdskd** [comment] 2018-01-25 12:58
I can confirm that no blue line appears under the category name on mouseover.

However tooltips for each item in these categorys are shown on mouseover and input fields light up blue on mouseover.

**Comment by Ghostkeeper** [comment] 2018-02-13 08:42
Also doesn't reproduce for me, using the 3.2 stable release on Ubuntu 17.10.
![screenshot from 2018-02-13 09-41-51](https://user-images.githubusercontent.com/2448634/36140640-32285a68-10a2-11e8-8480-98bd39b7ba0d.png)

**Comment by ianpaschal** [comment] 2018-03-09 14:01
Also doesn't reproduce for me. We're going to need some logs to look for QML bugs or something. @mpsdskd could you share your log file please?

**Comment by mpsdskd** [comment] 2018-03-12 07:51
Of course I can:
[cura.log](https://github.com/Ultimaker/Cura/files/1801802/cura.log)
I guess this is the one, you are looking for?

**Comment by Ghostkeeper** [comment] 2018-04-05 10:46
That's the log file, yeah. But the log file doesn't seem to contain any indication of anything out of the ordinary. Maybe only "Object destroyed upon incubation" is something but that's not something we can trace down from the log :crying_cat_face:

**Comment by ChrisTerBeke** [comment] 2018-05-23 19:15
No new info and can't reproduce. Closing.

**Closed by ChrisTerBeke** 2018-05-23 19:15 UTC
Labels: Category: Uranium, Status: Needs Info
