### ISSUE TITLE
Alignment of the seams

### ISSUE THREAD

**Issue by NicoArg2022** [Ultimaker/Cura#12550] opened 2022-06-17 23:41 UTC
### Application Version

5.0.0

### Platform

Windows 11

### Printer

Generic printer

### Reproduction steps

1.I choose fuzzy skin
2.I choose seam alignment mode

### Actual results

The alignment of the seams does not change in the preview or in the printed part even if I choose different alignment modes (user specified, random, shortest or sharpest corner), this did not happen in version 4.13.1

### Expected results

The seam alignment should change in the different alignment modes (user specified, random, shortest or sharpest corner) as it was in version 4.13.1

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Cura](https://user-images.githubusercontent.com/107729914/174412754-10204f7a-b1f3-4405-9ed5-1e788ca986fb.jpg)

**Comment by nallath** [comment] 2022-06-20 07:10
Duplicate of #12525

**Closed by nallath** 2022-06-20 07:10 UTC
Labels: Type: Bug, Status: Duplicate
