### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by CamoJackson** [Ultimaker/Cura#1594] opened 2017-03-28 01:55 UTC
This error occurs whenever i click on a object
Version: 2.5.0-BETA
Platform: Windows-10-10.0.15063
Qt: 5.7.1
PyQt: 5.7.1

Exception:
TypeError: unable to convert a C++ 'QVector3D' instance to a Python object

[cura log.txt](https://github.com/Ultimaker/Cura/files/874268/cura.log.txt)
[DxDiag.txt](https://github.com/Ultimaker/Cura/files/874270/DxDiag.txt)

**Comment by aevyrie** [comment] 2017-03-28 04:12
Same error. Been using without issue until now, tried enabling and disabling auto-slice. Cura is fine until I click on an object on the build plate (tried multiple .STL's), then I get this error, every time:

> Version: 2.5.0-BETA
> Platform: Windows-10-10.0.14393
> Qt: 5.7.1
> PyQt: 5.7.1
> 
> Exception:
> TypeError: unable to convert a C++ 'QVector3D' instance to a Python object

Strangely, I had just been working with the part and restarted because I changed the currency and a material price/weight.

**Comment by nallath** [comment] 2017-03-28 07:02
This has to do with the "center camera on select" issue. If you disable this it should be gone.

**Comment by Bobb1** [comment] 2017-03-28 19:02
I can confirm nallath's comment.  This only occurs when "center camera..." is checked.

**Comment by Ghostkeeper** [comment] 2017-03-29 09:15
Duplicate of https://github.com/Ultimaker/Cura/issues/1566 .

**Closed** 2017-03-29 09:15 UTC
Labels: duplicate
