### ISSUE TITLE
NativeCAD Plugin incompatible with Solidworks 2023

### ISSUE THREAD

**Issue by RSchnabel78** [Ultimaker/Cura#17288] opened 2023-11-11 08:24 UTC
### Cura Version

5.5.0

### Operating System

Windows 11

### Printer

Ultimaker S5 latest Firmware

### Reproduction steps

Open native Solidworks 2023 CAD files creates failure message. Also reported in #15163

### Actual results

Not able to load file ; workaround by saving files to STL required.

### Expected results

Using sucessfully SOLIDWORKS2023 files without converting it

### Add your .zip and screenshots here ⬇️

![230505341-8fe133a2-884b-4053-a3a3-094a9df96b34](https://github.com/Ultimaker/Cura/assets/150512014/697ceabe-fd8d-4a4f-a28e-861fcaacff02)

**Comment by fieldOfView** [comment] 2023-11-11 13:13
Since this is indeed a duplicate of https://github.com/Ultimaker/Cura/issues/15163, I am closing this issue in favor of that previous report.

**Closed by fieldOfView** 2023-11-11 13:13 UTC
Labels: Type: Bug, Status: Triage

**Comment by RSchnabel78** [comment] 2023-11-11 13:25
But is there a short term solution available?Am 11.11.2023 um 14:13 schrieb Aldo Hoeben ***@***.***>:﻿
Since this is indeed a duplicate of #15163, I am closing this issue in favor of that previous report.
