### ISSUE TITLE
scania r1000

### ISSUE THREAD

**Issue by alex17510** [Ultimaker/Cura#17292] opened 2023-11-12 08:38 UTC
### Cura Version

5.5.0

### Operating System

windows 10

### Printer

creality cr10

### Name abnormal settings

non

### Describe model location

non

### Describe your model

non

### Add your .zip here ⬇️

[untitled-R1000__11_.zip](https://github.com/Ultimaker/Cura/files/13327537/untitled-R1000__11_.zip)

**Comment by GregValiant** [comment] 2023-11-13 16:22
Thanks for the report.
I didn't have any trouble slicing it with a CR10 and the "Standard Quality" settings so I'm unable to duplicate the probem.
Have you tried moving the model around or rotating it in Cura?  You might also try changing the Initial Layer Height by a lttle bit.
This might be a duplicate of the slicing error that is in 5.5.0 but because it doesn't do it for me I can't tell.  Nonetheless, I'll mark this as a duplicate report and go ahead and close it.  I hope you understand.

It's a 42 hour print.
![image](https://github.com/Ultimaker/Cura/assets/64202104/ed976167-585d-4120-8d7a-eb6fabc6104b)

**Closed by GregValiant** 2023-11-13 16:22 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error :collision:
