### ISSUE TITLE
Arachne kicks out when saving to sd card

### ISSUE THREAD

**Issue by canadainvette** [Ultimaker/Cura#9415] opened 2021-03-18 10:31 UTC
### Application Version

Arachne Engine Beta

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

1) imported STL file,
2) Ran the slicer
3) saving to sdcard 

### Actual results

1) import works fine
2) slicer works ok
3) program crashes and kicks out and i have to restart program.
tried with multiple files and get the same issues.
tried 4.8 version with same files and have no issues.

### Expected results

should not crash

i find that this version is faster when importing the stl files which is nice

**Comment by fvrmr** [comment] 2021-03-18 14:38
Hi @canadainvette thank you for your bug report. This is a duplicate of #9057
We have already a ticket in our backlog for this issue. So we hope to fix this soon. 

I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-03-18 14:38 UTC
Labels: Type: Bug
