### ISSUE TITLE
Cura 5.x not responding.

### ISSUE THREAD

**Issue by saruichiban** [Ultimaker/Cura#13562] opened 2022-10-15 20:36 UTC
### Application Version

5.2

### Platform

Windows 10

### Printer

none

### Reproduction steps

Opened Cura 5.1 or 5.1.1 or 5.2 beta

### Actual results

It sits on white screen with not responding 

### Expected results

Cura should load in to working enviroment.
4.13.1 works just fine. 
![Desktop Screenshot 2022 10 15 - 14 32 16 17](https://user-images.githubusercontent.com/39427101/196006472-7fcf7f11-f2e0-4be6-8880-32f75c7edcc9.png)
![Desktop Screenshot 2022 10 15 - 14 33 54 89](https://user-images.githubusercontent.com/39427101/196006553-1a7823a2-0f3c-4d11-a432-6bcc5c8feee6.png)
![Desktop Screenshot 2022 10 15 - 14 34 33 60](https://user-images.githubusercontent.com/39427101/196006555-8478fa03-29ef-4dd2-9920-787ab1590481.png)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I have no log files or project files as it doesn't load.

**Comment by MariMakes** [comment] 2022-10-31 14:25
Hey @saruichiban,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Could this be a duplicate of https://github.com/Ultimaker/Cura/issues/8892 ?

One of the users posted the following workaround
`FIXED IT BY STOPPING ASUS GPU TWEAK SOFTWARE THAT CAME WITH MY TUF 3060TI!
Even though Cura ran perfectly on the same machine with the same software a few days ago...`

Is this something that would work for you?

**Closed** 2022-11-15 00:21 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage
