### ISSUE TITLE
Random Crash when printing

### ISSUE THREAD

**Issue by FlyingMasterChef** [Ultimaker/Cura#11974] opened 2022-04-26 06:52 UTC
### Application Version

5.0 beta

### Platform

Windows 11

### Printer

Anycubic Chiron

### Reproduction steps

I started Cura 5.0 beta. I loaded a file (Wingtest_Pla_Planeprint.stl), loaded the settings they require (https://www.planeprint.com/print), sliced the model and clicked to Print via USB.  

### Actual results

The printer printed maybe 10 or so layers then stopped. When I looked Cura had simply shut down. This happens every time at the same place on the print. 

### Expected results

The part would have been printed successfully.  

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8560502/cura.log)
[cura.log](https://github.com/Ultimaker/Cura/files/8560575/cura.log)

Currently, I have 3 Chrome windows open. 1 PDF file. in Adobe Reader. Thunderbird email client. And logi capture for video capture. Various apps/services in the background are always running.

**Comment by fieldOfView** [comment] 2022-04-26 07:08
Duplicate of #11896

**Closed** 2022-04-26 07:55 UTC
Labels: Type: Bug
