### ISSUE TITLE
Dual extrusion Skips layers per print core

### ISSUE THREAD

**Issue by GoguyT3D** [Ultimaker/Cura#14945] opened 2023-03-18 12:06 UTC
### Application Version

5.3

### Platform

Windows 11

### Printer

Ultimaker S3

### Reproduction steps

Start a dual extrusion print with my custom profile of .1mm layer height and 2 print cores AA & BB

### Actual results

Slicing engine prints both AA & BB skirt and starts the print core AA prime tower though skips support core BB for prime tower and every other layer subsequent to the slicer generated supports within the model.

### Expected results

Both nozzles print their entire .1mm layer on each layer in order AA-BB

### Checklist of files to include

- [x] Log file
- [X] Project file

### Additional information & file uploads

[Dual Carling Switch Mount.zip](https://github.com/Ultimaker/Cura/files/11008474/Dual.Carling.Switch.Mount.zip)

**Comment by GoguyT3D** [comment] 2023-03-18 12:35
[quality_changes.zip](https://github.com/Ultimaker/Cura/files/11008527/quality_changes.zip)
heres the log files

**Comment by GoguyT3D** [comment] 2023-03-18 12:56
The "eraser" next to the model was supposed to "induce" the support nozzle to start the prime tower at the beginning of the print though the support extruder skips every layer. Remove the "eraser" and you will see that the support core does not start until 5.1mm when the cura generated supports start.

**Comment by GoguyT3D** [comment] 2023-03-18 13:17
Don't know if this will help for those of you pythons out there trying to code this fix but removing the prime tower and all unnecessary "erasers" induced the print cores to both print for each required layer

**Comment by MariMakes** [comment] 2023-04-03 14:23
Hey @GoguyT3D,

Good to see you again. 😊 
Sorry, it took us a while to get back to you 😞 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/15078
We have resolved the issue, and you can even download a nightly to see for yourself. 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/15078

**Closed by MariMakes** 2023-04-03 14:23 UTC
Labels: Type: Bug, Status: Triage
