### ISSUE TITLE
Sprial Lines are in Segments

### ISSUE THREAD

**Issue by zwu513** [Ultimaker/Cura#11332] opened 2022-01-25 04:42 UTC
### Application Version

1.12.0

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

1. Slice File
2. Preview
3. Print

### Actual results

![Cura_C57RstAPRe](https://user-images.githubusercontent.com/32444398/150909245-b0a98067-f211-4da1-81f9-084697837039.png)

### Expected results

![Inventor_2JYt2mew2D](https://user-images.githubusercontent.com/32444398/150909253-ef12b1e3-c45d-4f43-afbc-922e26a0c393.png)

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Additional information & file uploads

[CE3_TestSweepPattern_0.28mm_15%_215C_60C_0H_2M.zip](https://github.com/Ultimaker/Cura/files/7930654/CE3_TestSweepPattern_0.28mm_15._215C_60C_0H_2M.zip)

**Comment by fvrmr** [comment] 2022-01-25 11:06
Hi @zwu513 thank you for your report.
If you slice your model in our Arachne engine it will slices, like you expected. This is because Arachne has a variable line width. And your model is probably to thin to print, that's why you will get these gaps. 
https://github.com/Ultimaker/Cura/releases/tag/Arachne_engine_beta_2

![Capture(246)](https://user-images.githubusercontent.com/77000924/150964126-1f7b476f-ca30-44ec-8749-fd423fdda8ba.PNG)

**Comment by zwu513** [comment] 2022-01-25 11:09
The confusing part is that I've gotten it to slice as a single line with no issues. It's seems it had something to do with the exact width and height. I'll try the beta, thank you.

**Comment by Ghostkeeper** [comment] 2022-02-01 12:46
Duplicate of https://github.com/Ultimaker/Cura/issues/4685. This is fixed by #1210 .

**Closed by Ghostkeeper** 2022-02-01 12:46 UTC
Labels: Type: Bug
