### ISSUE TITLE
Avoid starting perimeters on overhangs

### ISSUE THREAD

**Issue by martinsykes1** [Ultimaker/Cura#8422] opened 2020-09-21 16:36 UTC
**Is your feature request related to a problem? Please describe.**
When printing walls including tree supports, the perimeter often starts on an overhang whereas starting at a non-overhanging point would give better results. This *may* be linked to aligning the z-seam on the sharpest corner which will tend to be on the tip of a tree support.

**Describe the solution you'd like**
When deciding where to start a perimeter, I'd like to provide a maximum overhang angle parameter and it wouldn't start the perimeter at any point overhanging more than this unless it had no other option available. Within the remaining available options, it would respect the shortest, sharpest corner etc. options as now

**Comment by Ghostkeeper** [comment] 2020-09-23 15:29
Duplicate of https://github.com/Ultimaker/Cura/issues/5892

**Closed by Ghostkeeper** 2020-09-23 15:29 UTC
Labels: Type: New Feature
