### ISSUE TITLE
Will not complete slicing

### ISSUE THREAD

**Issue by Captain-Benjamin** [Ultimaker/Cura#10406] opened 2021-09-07 17:02 UTC
### Application Version

4.11.0

### Platform

Windows 10 pro

### Printer

Anycubic 4Max

### Reproduction steps

Worked in previous version...Did not change

### Actual results

Slicing failed

### Expected results

Complete slicing

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[A4_A4 spiralboxcover2 Generic PETG.zip](https://github.com/Ultimaker/Cura/files/7123201/A4_A4.spiralboxcover2.Generic.PETG.zip)

**Comment by fvrmr** [comment] 2021-09-09 07:54
Hi @Captain-Benjamin thank you for your bug report. I can reproduce your issue. 
I will bring this up with the team. Keep you posted!

**Comment by smartavionics** [comment] 2021-09-09 08:09
See https://github.com/Ultimaker/Cura/issues/10418.

Same fix, either turn off monotonic skins or use lines rather than zigzag skin pattern.

**Comment by fvrmr** [comment] 2021-09-10 09:24
I have discussed it with the team. And I made a ticket on our backlog for this. It is linked to the other issue since @smartavionics explains what is causing the crash. So I will close this ticket as a duplicate. Follow the other thread for updates.

**Closed by fvrmr** 2021-09-10 09:24 UTC
Labels: Type: Bug
