### ISSUE TITLE
3D connexion Mouse

### ISSUE THREAD

**Issue by ddrossie** [Ultimaker/Cura#8799] opened 2020-11-19 13:40 UTC
**Describe the solution you'd like**

For working in Cura it would be nice to use my 3D mouse (3D connexion) for orbiting around the print area.

**Comment by nallath** [comment] 2020-11-19 13:42
Duplicate of #1152

**Closed by nallath** 2020-11-19 13:42 UTC
Labels: Type: New Feature

**Comment by fieldOfView** [comment] 2020-11-19 13:43
See https://github.com/smartavionics/RawMouse
