### ISSUE TITLE
Will not slice; slicing failed

### ISSUE THREAD

**Issue by mdwilson85** [Ultimaker/Cura#13418] opened 2022-09-30 17:35 UTC
### Application Version

5.1.0 and 5.1.1

### Platform

Windows 11

### Printer

Ender 3 Pro

### Reproduction steps

Uploaded a chalice I wanted to print, set the settings and temps and hit slice. I just sliced another file for my ender 5 + and it worked but my ender 3 pro profile is returning an error. 

### Actual results

![cura slicing issue](https://user-images.githubusercontent.com/69731952/193325260-91e2258f-5ee6-4555-9e07-76e0cc490bb3.jpg)
![image](https://user-images.githubusercontent.com/69731952/193325152-7f206fd3-d55e-4d85-9334-dcddf15ec44f.png)

### Expected results

It should have sliced the file in order for me to save the file and print it! I have attached the project file
[CE3PRO_Hex3D_SkullChalice.zip](https://github.com/Ultimaker/Cura/files/9686587/CE3PRO_Hex3D_SkullChalice.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE3PRO_Hex3D_SkullChalice.zip](https://github.com/Ultimaker/Cura/files/9686591/CE3PRO_Hex3D_SkullChalice.zip)

**Comment by GregValiant** [comment] 2022-10-02 02:35
Thanks for the report.
There is an oft reported bug in 5.0 and 5.1.x that can keep error-free models from slicing.  You can try moving it on the build plate or rotating the model.  That will often fool the bug and allow the model to slice.
I've just installed 5.2beta and your model sliced with no problems.
This is a duplicate of numerous other reports regarding 5.0 and 5.1 and I'll mark it as such and close this.  If the bug persists in 5.2beta then this can be reopened.

**Closed by GregValiant** 2022-10-02 02:35 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error💥
