### ISSUE TITLE
No Custom support with Cura 4.4

### ISSUE THREAD

**Issue by lwbsbde** [Ultimaker/Cura#6693] opened 2019-11-21 15:04 UTC
I can not find the function  " Custom support" 
Cura 4.4

**Comment by fieldOfView** [comment] 2019-11-21 15:24
Duplicate of https://github.com/Ultimaker/Cura/issues/6681

**Comment by nallath** [comment] 2019-11-21 15:41
I've already approved the plugin, but the author still needs to publish it. So expect it to be there soonish.

**Closed by nallath** 2019-11-21 15:41 UTC
Labels: Type: Bug
