### ISSUE TITLE
Right clicking model doesnt bring up full intended menu

### ISSUE THREAD

**Issue by mastory** [Ultimaker/Cura#83] opened 2015-07-02 02:45 UTC
First 3 items in object right click menu don't display as described here:

https://ultimaker.com/en/support/view/16518-mouse-control

Win7, Logitech g700

**Comment by BagelOrb** [comment] 2015-07-02 10:29
The website should probably be updated.

**Comment by mastory** [comment] 2015-07-03 17:17
This may be related to #84

**Comment by awhiemstra** [comment] 2015-07-06 16:05
The same code is used to check what is underneath the cursor, so if it fails for selection it will also fail for this, so that sounds likely.

**Comment by awhiemstra** [comment] 2015-07-07 10:31
Closing this as a duplicate of #84

**Closed by awhiemstra** 2015-07-07 10:31 UTC
Labels: duplicate
