### ISSUE TITLE
4.4.1: Support Interface Floor Partial Coverage

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#7097] opened 2020-02-13 20:07 UTC
Running 4.4.1 on Windows 10 and noticed this small issue:

![image](https://user-images.githubusercontent.com/12439543/74473506-569ec600-4e69-11ea-8879-18ea5c36cd70.png)

I have verified that the model's bottom face is parallel to this face, and even at a multiple of layer height. Subsequent face above this doesn't exhibit the same issue:

![image](https://user-images.githubusercontent.com/12439543/74473912-0d9b4180-4e6a-11ea-80ee-e4483ee6101d.png)

[gcode.txt](https://github.com/Ultimaker/Cura/files/4200749/gcode.txt)

[model.zip](https://github.com/Ultimaker/Cura/files/4200757/model.zip)

**Comment by Ghostkeeper** [comment] 2020-02-17 16:08
Hrm, I'm not getting that issue.
![image](https://user-images.githubusercontent.com/2448634/74669675-fb8e0b80-51a7-11ea-9d8d-b52702853af6.png)
Could you try changing the Support Stair Step Height to 0? That has given us this sort of issues in the past.

Otherwise, can you send us a project file completely? Perhaps some of my settings are still different from yours.

**Comment by CCS86** [comment] 2020-02-17 16:58
Looks like you are looking at the second support interface floor, which I had no problems with either.

I can confirm that setting the support stair step height to 0, resolves the issue. Thanks for the workaround!

**Comment by rburema** [comment] 2020-02-19 09:55
If that workaround is the answer, then it's very likely a duplicate of a long list of issues.

Closing this because it's a duplicate, please continue any discussion here: #6379

**Closed by rburema** 2020-02-19 09:55 UTC
Labels: Type: Bug

**Comment by rburema** [comment] 2020-06-25 13:25
We might finally have squashed this bug! When we eventually release 4.7 (which might take a bit longer than usual) you can check it out.

**Comment by CCS86** [comment] 2020-06-25 13:27
> We might finally have squashed this bug! When we eventually release 4.7 (which might take a bit longer than usual) you can check it out.

Sweet, thanks!
