### ISSUE TITLE
Slicing failed with an unexpected error

### ISSUE THREAD

**Issue by renkam** [Ultimaker/Cura#17905] opened 2024-01-05 09:39 UTC
### Cura Version

5.6.0

### Operating System

Linux Debian 11

### Printer

Creality Ender-3 S1 Pro

### Name abnormal settings

It slices with vertical orientation, fails horizontaly

### Describe model location

center

### Describe your model

https://www.thingiverse.com/thing:2830825/files

### Add your .zip here ⬇️

[02PLAG_center_finder_tool_CE3S1PRO.3mf.zip](https://github.com/Ultimaker/Cura/files/13840354/02PLAG_center_finder_tool_CE3S1PRO.3mf.zip)

**Comment by renkam** [comment] 2024-01-05 12:30
Good to know, I've got only small error window, that tells me nothing.
![2024-01-05-133107_408x156_scrot](https://github.com/Ultimaker/Cura/assets/3105796/1bfdf422-dd1a-4b58-9ec0-89d0b128a92a)
It could print a message that support generation failed, so I could turn it off.

Thanks for tip!

**Comment by Vandresc** [comment] 2024-01-19 13:04
👋 Quick update on our side.
Your issue seems to have been resolved with this fix from our wonderful community member ThomasRahm here CuraEngine: Fix crashes caused by tree support.
CLOSED
 

I'll close this issue since it's resolved, a fix should be available with the upcoming release. 

Thanks again, and please let us know if you run into any other issues 💪

**Closed by Vandresc** 2024-01-19 13:04 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:

**Comment by HellAholic** [comment] 2024-04-03 13:23
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
