### ISSUE TITLE
Running cura from source PyQt6.QtNetwork module not found

### ISSUE THREAD

**Issue by phedg1** [Ultimaker/Cura#12745] opened 2022-07-12 07:10 UTC
### Application Version

CURA-9365 branch

### Platform

Windows 10

### Printer

Ultimaker Doesnt Matter

### Reproduction steps

`pip install conan --upgrade
conan config install https://github.com/ultimaker/conan-config.git
conan profile new default --detect --force
conan remote remove cura
powershell
PS cd C:\Users\Me\Documents\3D_Print\_Software\Workspace\CuraEngine
PS conan editable add . curaengine/latest@ultimaker/testing
PS cd C:\Users\Me\Documents\3D_Print\_Software\Workspace\Cura
PS conan install . cura/5.1.0-beta@ultimaker/stable --build=missing --update -o cura:devtools=True -g VirtualPythonEnv

PS C:\Users\Me\Documents\3D_Print\_Software\Workspace\Cura> .\venv\Scripts\activate.ps1
PS C:\Users\Me\Documents\3D_Print\_Software\Workspace\Cura> python cura_app.py`

### Actual results

`PS C:\Users\Me\Documents\3D_Print\_Software\Workspace\Cura> .\venv\Scripts\activate.ps1
Capturing current environment in C:\Users\Me\Documents\3D_Print\_Software\Workspace\Cura\venv\Scripts\deactivate_Activate.ps1
Configuring environment variables
PS C:\Users\Me\Documents\3D_Print\_Software\Workspace\Cura> python cura_app.py
Traceback (most recent call last):
  File "C:\Users\Me\Documents\3D_Print\_Software\Workspace\Cura\cura_app.py", line 23, in <module>
    from PyQt6.QtNetwork import QSslConfiguration, QSslSocket
ImportError: DLL load failed while importing QtNetwork: The specified module could not be found.`

### Expected results

I expected this to run cura from source.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I'm trying to run Cura and CuraEngine from source. I am on the latest commit in the Cura-9365 branch for Cura and the latest commit in the 5.1 branch in CuraEngine. I ran the commands as listed in the wiki page for running from source. I have tried restarting the powershell and rebooting my pc. No dice. What should I be doing for this?

**Comment by yess1987** [comment] 2022-07-14 04:13
I have this problem too, how to fix it

**Comment by SWDontheway** [comment] 2022-08-16 09:35
> 
i also have this issue and i'm now trying your intermittment solution.
what all ".dll" in which folder do you  mean?
i've copied all ".dll" file from the `C:\Cura\venv\Lib\site-packages` to `C:\Cura\venv\Lib\` or 'C:\Cura\venv\Scripts'...
but both didnt work.

**Comment by ZacharyHowell-Essentium** [comment] 2022-08-23 01:21
@jellespijker 
I'm also still having this issue. Has there been any solid solution formed yet?
Thanks!

**Comment by jellespijker** [comment] 2022-08-23 08:49
Working on this as we speak, I believe the problem is that PyQt6 and Qt6 link to the system python3.dll and not our own python310.dll.

I'm currently setting things up to compile Qt6 and PyQt6 from source in our build process, which is not a trivial thing, but I'm making progress.

I will reopen this issue since it is still an ongoing issue

**Comment by ZacharyHowell-Essentium** [comment] 2022-08-23 20:37
@jellespijker 
Great, thanks for the update!
Was the bot supposed to auto-close this issue?

**Comment by jellespijker** [comment] 2022-08-23 20:41
No the bot wasn't suppose to close this issue....
**Bad bot**

**Comment by jellespijker** [comment] 2022-08-23 20:53
#12773 and #13047 are both duplicates of this btw

**Closed** 2022-08-23 20:54 UTC
Labels: Type: Bug

**Comment by SWDontheway** [comment] 2022-08-29 11:45
@jellespijker thanks for updating!

How do I use this commit to solve the issue? Could you pls provide more infos. 

I retried the build commands again from https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source. But still the same error. 

the python venv was activated, showing python 3.10.4.

**Comment by jellespijker** [comment] 2022-08-29 13:11
See the discussion on #12773 still work in progress atm
