### ISSUE TITLE
cura 4.6.0 - Creality ender 3 pro - nozzle diameter missing

### ISSUE THREAD

**Issue by fsaitta999** [Ultimaker/Cura#7571] opened 2020-04-22 21:33 UTC
**Application version**
cura 4.6.0

**Platform**
windows 7

**Printer**
Creality Ender 3 pro

**Reproduction steps**

1. I install the program
2. I add printer profile
3. I can't find the choice of the diameter of the nozzle

**Screenshot(s)**
![Cattura](https://user-images.githubusercontent.com/64170241/80036257-aba62a80-84f1-11ea-8c75-92d9706c13ed.PNG)

**Actual results**
no print profile exists

**Expected results**
correct error and insert profiles as for Creality ender 3

**Comment by fieldOfView** [comment] 2020-04-23 08:16
Duplicate of duplicate of https://github.com/Ultimaker/Cura/issues/7550

**Closed** 2020-04-23 08:29 UTC
Labels: Type: Bug
