### ISSUE TITLE
Adaptative layers: Problematic Tuning

### ISSUE THREAD

**Issue by joaquinabian** [Ultimaker/Cura#13088] opened 2022-08-22 10:01 UTC
### Is your feature request related to a problem?

Small changes in Adaptative Layers' Max Variation produces extreme changes in quality and print times

![image](https://user-images.githubusercontent.com/619491/185893817-e5098dfc-8f02-4887-8e5c-7a9826201576.png)
Cura-calculated number of layers and print time vs Adaptative Layers Maximum Variation.
Object: https://www.thingiverse.com/thing:2569573

![image](https://user-images.githubusercontent.com/619491/186031258-bfb46f55-5a7a-42de-af8b-10e3774dfa4e.png)
Differences between Adaptative Layers Maximum Variation: 0.100 and 0.101, the two extreme values in plot above. Other parameters constant.

### Describe the solution you'd like

The algorithm should be capable of smoothing these variations or a tool provided to determine the optimum parameter values in a given range.

### Describe alternatives you've considered

I calculated layer number and times manually in Cura. This takes a long time as changes can be very fast like in the example given where 0.001 mm makes a great difference.

### Affected users and/or printers

Everybody using Adaptative Layers

**Comment by MariMakes** [comment] 2022-09-28 13:27
Hey @joaquinabian,

Thanks for your elaborate report 😍 
I showed it to the team and they were super impressed by your detective work 🔍 

We've been scratching our heads about what you are observing. 
It seems to be [a Tolerance Stack-up. ](https://www.wasyresearch.com/2d-tolerance-stack-up-analysis-with-examples/) 

Your model is showing the behavior extremely clearly.
A domed shape like this should be immune to a tolerance stack-up.
If I try the same analysis method as you, I'm seeing the expected behavior.
![image](https://user-images.githubusercontent.com/40423138/192785133-a61280a3-08ce-476f-aae7-42669cd682ed.png)

This leads me to conclude that what you are seeing is expected behavior, but just unfortunate with the model that you've chosen. 

I will therefore be closing this issue. I hope you understand.

Thank you again for the report! We are constantly working on making Ultimaker Cura better. Our community is a big part of that by requesting new features and reporting bugs.

**Closed by MariMakes** 2022-09-28 13:27 UTC
Labels: Type: New Feature, Status: Under Investigation
