### ISSUE TITLE
[3.6.0] a random layer has been assigned to the wrong z height.

### ISSUE THREAD

**Issue by megablue** [Ultimaker/Cura#5043] opened 2018-12-22 20:46 UTC
**Application Version**
3.6.0

**Platform**
windows 10 pro 64bit

**Printer**
my custom delta

**Steps to Reproduce**
slice https://www.thingiverse.com/thing:2493386 small moai at 0.01mm layer height
should be triggered by maximum resolution, i was running 0.02mm, it seems fine at 0.1mm

**Actual Results**
crash into a print and try to destroy my printer. 

**Expected results**
properly assign the layer height 

**Additional Information**
![cura_2018-12-23_04-30-56](https://user-images.githubusercontent.com/164641/50378426-21d01e00-066d-11e9-9034-9cdfd561776e.png)

[CFFFP_moai-Small-NO_OVERHANG.3mf.zip](https://github.com/Ultimaker/Cura/files/2705523/CFFFP_moai-Small-NO_OVERHANG.3mf.zip)

**Comment by smartavionics** [comment] 2018-12-22 21:30
Just sliced your project and cannot see that weird line. Could you please zip up your gcode and attach to this issue. Thanks.

![screenshot_2018-12-22_21-30-09](https://user-images.githubusercontent.com/585618/50378738-c849fe00-0630-11e9-9dec-428a47e89f9e.png)

**Comment by megablue** [comment] 2018-12-22 21:44
I've lost the gcode. I just tried again, for some reasons, I couldn't reproduce it either... i swear i did re-sliced a few times and it was broken.

**Comment by Ghostkeeper** [comment] 2019-05-28 15:35
Indeed this looks like a duplicate of #3815. Since that issue was closed though, please continue discussion here: #5788.

**Closed by Ghostkeeper** 2019-05-28 15:35 UTC
