### ISSUE TITLE
[3.6.0] Overextrude before bridge

### ISSUE THREAD

**Issue by fjriosp** [Ultimaker/Cura#5021] opened 2018-12-19 16:25 UTC
**Application Version**
3.6.0

**Platform**
Windows 10

**Printer**
Prusa i3

**Steps to Reproduce**
Enable bridge settings with a Bridge speed different to Print Speed.

**Actual Results**
After the bridge there is an overextrussion proportional to the difference between bridge and print speed.

**Expected results**
The extrusion before the bridge must be the same without Enable bridge settings.

**Additional Information**
Problem detail:
![detail](https://user-images.githubusercontent.com/6414473/50232905-83b12f00-03b2-11e9-89a5-0942a2d66b81.PNG)
GCode generated:
![bad](https://user-images.githubusercontent.com/6414473/50232908-8744b600-03b2-11e9-9cc6-0ac09f8c379b.PNG)
Expected GCode:
![good](https://user-images.githubusercontent.com/6414473/50232919-8d3a9700-03b2-11e9-9fa6-9b1dc25e70e4.PNG)

Projects:
[bridge.zip](https://github.com/Ultimaker/Cura/files/2695693/bridge.zip)

**Comment by smartavionics** [comment] 2018-12-19 21:56
The increased extrusion rate following the bridge is intentional. It is attempting to get the nozzle pressure back up to what is required for the wall segments following the bridge.

Have you actually printed this? If so, did you get big fat walls immediately following the bridge wall? If so, please post pictures and the gcode. Thanks.

**Comment by fjriosp** [comment] 2018-12-20 16:36
I tried to print it, but my firmware interrupts the print because a volumetric limit on that segment.

I'll try disabling the volumetric constraints in the firmware...

**Comment by Superchicken** [comment] 2019-12-02 16:01
I am also experiencing this issue, the difference between my print speed and bridging speed creates a preview with a comically large extrusion. 

My firmware (klipper) also interrupts the print because of a too large single extrude.

**Very slow bridge setting (5mm/s)**
First bridge looks good:
![image](https://user-images.githubusercontent.com/874822/69972024-74a18f00-14e6-11ea-9344-a3cead895048.png)
Extremely large extrude before next bridge:
![image](https://user-images.githubusercontent.com/874822/69972048-7ff4ba80-14e6-11ea-826e-7cb7646d2413.png)
Second bridge looks good:
![image](https://user-images.githubusercontent.com/874822/69973021-56d52980-14e8-11ea-9cf9-fa7400a357bc.png)

Entire layer view:
![image](https://user-images.githubusercontent.com/874822/69971989-65224600-14e6-11ea-94bd-4a7532883ce5.png)

**Default bridge settings**
Automatically calculated 60mm/s bridging wall+skin speed by cura. This printed upside down arches instead of horizontal bridges:
![image](https://user-images.githubusercontent.com/874822/69972149-aa467800-14e6-11ea-97ac-d0cfcc5b906b.png)

**Application Version**
4.4.0

**Platform**
Windows 10

**Printer**
Ender 3

**Files** (changed extension)
[jaw .2mm inset.stl.zip](https://github.com/Ultimaker/Cura/files/3912019/jaw.2mm.inset.stl.zip)
[my profile.curaprofile.zip](https://github.com/Ultimaker/Cura/files/3912025/my.profile.curaprofile.zip)
[CE3_jaw .2mm inset.gcode.zip](https://github.com/Ultimaker/Cura/files/3912037/CE3_jaw.2mm.inset.gcode.zip)

**Comment by smartavionics** [comment] 2019-12-02 16:41
I am to blame for this and a fix (https://github.com/Ultimaker/CuraEngine/pull/1056) has already been merged for the next release (4.5?) In the meantime, if you wish to try one of my Cura builds, you can see if the fix is sufficient. You can find my builds at https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0. Please read the README.md in there.

BTW, why are you using 5mm/S for the bridge wall speed? Does that really give you better results than, say, 25mm/S?

**Comment by Superchicken** [comment] 2019-12-02 18:21
> ...fix (Ultimaker/CuraEngine#1056) has already been merged for the next release...

Oops, I was only looking for existing issues in this repo.

I appreciate your builds, saves me lots of time  :slightly_smiling_face:

It looks like the issue is fixed, judging by the preview. 

> BTW, why are you using 5mm/S for the bridge wall speed? Does that really give you better results than, say, 25mm/S?

I don't know :stuck_out_tongue_winking_eye:
5mm/s is the first/lowest speed I'm trying to test to find the right settings for me.

**Comment by nallath** [comment] 2019-12-03 10:35
This can be closed, since the fix has been merged.

**Closed by nallath** 2019-12-03 10:35 UTC
