### ISSUE TITLE
[3.5] Messy infill lines

### ISSUE THREAD

**Issue by Pajacyk0v** [Ultimaker/Cura#4483] opened 2018-10-05 07:57 UTC
**Application Version**
3.5

**Platform**
Windows 10 x64

**Printer**
Custom - Reprap

**Steps to Reproduce**
1. select infill lines multiplier > 1
2. select connect infill lines

**Actual Results**
There is complete mess in preview mode. Infill lines are conected thru model.

**Expected results**
Connected multiple infill lines :]

**Additional Information**
![9tu349gth58g](https://user-images.githubusercontent.com/43875157/46523091-f6ffd600-c884-11e8-8810-aac9df599bea.jpg)

**Comment by rburema** [comment] 2018-10-05 09:56
Hi @Pajacyk0v,
Could you attach the model please? I also see you're using a custom printer. Have you written a custom definition? It may help if you attach that as well. 
(Also, this is just a hunch, but what nozzle-diameter do you use?)
cheers, Remco.

**Comment by Pajacyk0v** [comment] 2018-10-12 19:16
> 
> 
> Hi @Pajacyk0v,
> Could you attach the model please? I also see you're using a custom printer. Have you written a custom definition? It may help if you attach that as well.
> (Also, this is just a hunch, but what nozzle-diameter do you use?)
> cheers, Remco.

Sorry for a delay. I had holidays :]
I use 0.4 nozzle. Files in attachement
[cura_3.5_infill_issue.zip](https://github.com/Ultimaker/Cura/files/2474319/cura_3.5_infill_issue.zip)

**Comment by smartavionics** [comment] 2018-10-12 20:14
Hi @Pajacyk0v , is it possible you could save the project (.3mf) file, zip that and attach to this issue? Thanks.

**Comment by Pajacyk0v** [comment] 2018-10-13 15:42
> 
> 
> Hi @Pajacyk0v , is it possible you could save the project (.3mf) file, zip that and attach to this issue? Thanks.

In attachment. Regards
[dobijak_simmeringu.zip](https://github.com/Ultimaker/Cura/files/2475602/dobijak_simmeringu.zip)

**Comment by smartavionics** [comment] 2018-10-13 15:49
Thanks for the project. I can confirm that the problem is fixed using my Cura which is based on the master branch so I would think that it will be fixed in a future release.

**Closed** 2018-10-16 08:28 UTC
Labels: Status: Needs Info

**Comment by Pajacyk0v** [comment] 2018-10-16 17:37
With which release? 3.5.1 doesn't fix this problem.
![2018-10-16 19_35_14-ultimaker cura](https://user-images.githubusercontent.com/43875157/47035597-b7859380-d17a-11e8-8a3f-31a6b986dc01.jpg)

**Comment by Pajacyk0v** [comment] 2018-10-16 17:53
With which release? 3.5.1 doesn't fix this problem.
![2018-10-16 19_35_14-ultimaker cura](https://user-images.githubusercontent.com/43875157/47035597-b7859380-d17a-11e8-8a3f-31a6b986dc01.jpg)

**Comment by smartavionics** [comment] 2018-10-16 18:01
The next major release, I would expect.

**Comment by rburema** [comment] 2018-10-17 08:00
@smartavionics is right. Some background info: Point-releases like 3.5.1 are only supposed to fix major sources of crashes and other complete showstoppers like that (anything else is a bonus), and more importantly, are on the same branch as the 3.5.0 release that was split off from master a while ago (one or more weeks before that release). The master-branch will be used for the next release.

**Comment by diegopradogesto** [comment] 2018-10-31 20:11
@Pajacyk0v the version 3.6 BETA is live from today and this issue should be fixed there. You can try the version and test you projects. If you still see something wrong, please let us know.
