### ISSUE TITLE
Opening new Input Window freezes Cura

### ISSUE THREAD

**Issue by TheRealTripleM** [Ultimaker/Cura#12494] opened 2022-06-10 20:13 UTC
### Application Version

5.0.0

### Platform

Windows 11

### Printer

Ender 3

### Reproduction steps

1. Load STL File 
2. Select loaded body
3. right click
4. select "multiply selected"
![grafik](https://user-images.githubusercontent.com/49285652/173143258-d1a6ee3b-bcd7-4d4a-8bb1-e25a4e36721d.png)

### Actual results

cura freezes -> "No Response"

### Expected results

new Window should be opend to input number of copies

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

it happens also when i try to open other windows like Extensions etc.

**Comment by fieldOfView** [comment] 2022-06-10 20:25
This is a duplicate of https://github.com/Ultimaker/Cura/issues/12264. Cura 5.0 has an issue on some multi-monitor setups.
In order to keep the discussion centralized, I am closing this issue.

**Closed by fieldOfView** 2022-06-10 20:25 UTC
Labels: Type: Bug, Status: Duplicate, Status: Triage
