### ISSUE TITLE
Eror slice as connect Top/Bottom Polygons

### ISSUE THREAD

**Issue by ArhaNNN** [Ultimaker/Cura#15797] opened 2023-06-18 18:50 UTC
### Cura Version

5.4

### Operating System

Windows 11

### Printer

Ender 3 pro

### Name abnormal settings

Yes - connect Top/Bottom Polygons

### Describe your model

No

### Add your .zip here ⬇️

[CE3PRO_Fabulous Amur (3).zip](https://github.com/Ultimaker/Cura/files/11782361/CE3PRO_Fabulous.Amur.3.zip)

**Comment by MariMakes** [comment] 2023-06-18 20:13
Hey @ArhaNNN,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

I can reproduce it, it seemed to work in Cura 5.3.1 but not anymore. Thanks for pointing us in the right direction. 

I'll bring it up to the team to see what they can do to improve it before the Stable Release.
Fingers crossed 🤞

**Comment by MariMakes** [comment] 2023-07-05 14:25
Thanks again for the report. 💪 
We were able to resolve this issue in the 5.4 Stable release. 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.4.0

I'll close the issue since it's resolved.

**Closed by MariMakes** 2023-07-05 14:25 UTC
Labels: Type: Bug, Status:  On Backlog, Slicing Error :collision:, PreRelease :bug:
