### ISSUE TITLE
Show time and weight for different settings

### ISSUE THREAD

**Issue by Mcklp** [Ultimaker/Cura#11417] opened 2022-02-04 17:09 UTC
### Is your feature request related to a problem?

It's tedious to change and compare print time of many settings, most of us stick to what they like the most, but for example infill like gyroid and lightning are better or worse depending of model that we are printing, and its not obvious without checking which will be faster.

### Describe the solution you'd like

I'd like a option to slice model with two presets, where we can chose one or many options that will be changed for one of them. It could be like that:

![image](https://user-images.githubusercontent.com/47704974/152569276-61e80c1a-8bb0-4bc1-a824-2b7e5f5233bf.png)

The default one will be in preview, and after clicking "Switch" it will change to settings from the second one.

There might be a need to add some place for short name for the presset. 

### Describe alternatives you've considered

Im not sure if its already possible, if it is it should be more visible to do. Custom print setings in this windows will be also preety handy:

![image](https://user-images.githubusercontent.com/47704974/152570647-9d52f00c-af4d-442e-b677-7a2f57f70f7b.png)

Custom names, so we can shorten them to fit, two rows for more options in less space.

### Affected users and/or printers

I think everyone? There is no perfect infill or wall count, so i think everyone should be beneficial from this. Only problem i can see from this is longer slicing time, but if it will be showing first model in preview, while the second one is still slicing it will be a good compromise for me.

**Comment by fvrmr** [comment] 2022-02-07 15:39
Hi @Mcklp thank you for your feature request.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/10481 and this issue is linked to a ticket on our backlog.
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2022-02-07 15:39 UTC
Labels: Type: New Feature
