### ISSUE TITLE
item failed to slice after adding anti warping tabs

### ISSUE THREAD

**Issue by wluckie1** [Ultimaker/Cura#15790] opened 2023-06-18 10:14 UTC
### Cura Version

5.4.0

### Operating System

windows 11

### Printer

creality cr-10

### Name abnormal settings

i added anti warping tabs

### Describe model location

i have rotated model 90 degrees to print upside down. model sliced fine before adding the tabs

### Describe your model

basic model which is part of laser pistol

### Add your .zip here ⬇️

[AEP7_laser_pistol_Frame_front_brace.zip](https://github.com/Ultimaker/Cura/files/11781178/AEP7_laser_pistol_Frame_front_brace.zip)

**Comment by 5axes** [comment] 2023-06-20 16:56
Same issue as : https://github.com/Ultimaker/Cura/issues/15807  

Looks like an issue with the Mesh type Support : 
![image](https://github.com/Ultimaker/Cura/assets/11015345/a3addf3b-36c9-4241-9f8e-761768f72725)

**Comment by MariMakes** [comment] 2023-06-21 10:38
Hey @wluckie1,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for using the beta and reporting your issues👍 

You are not the first person to report this, I'll mark this issue as a duplicate of https://github.com/Ultimaker/Cura/issues/15836
I'm bringing it up to the team to see what they can do to improve it before the Stable release,

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/15836

**Closed by MariMakes** 2023-06-21 10:38 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:, PreRelease :bug:
