### ISSUE TITLE
Z Seam Alignment setting not being adhered to in Cura 5.3.X

### ISSUE THREAD

**Issue by brayne** [Ultimaker/Cura#15802] opened 2023-06-19 02:16 UTC
### Application Version

5.3.1

### Operating System

MacOS Ventura

### Printer

Ender 5 S1

### Reproduction steps

1. Open any model (I have used Benchy for my tests)
2. Slice the model with "Z Seam Alignment" set to "Sharpest Corner"

### Actual results

The seams are all over the place, not on the sharpest corner.
![cura531](https://github.com/Ultimaker/Cura/assets/1421504/ae2ba7a4-fca6-4869-b134-f9d4f8bcaa46)

### Expected results

Expected the seams to be on the sharpest corner. This is an example of the exact same settings using Cura 5.2.2, suggesting that the issue has occurred in the 5.3 updates.
![cura522](https://github.com/Ultimaker/Cura/assets/1421504/ed1563c0-5e41-4f19-9a07-54ac9bc119d8)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[3DBenchy.3mf.zip](https://github.com/Ultimaker/Cura/files/11783391/3DBenchy.3mf.zip)

**Comment by MariMakes** [comment] 2023-06-19 09:36
Hey @brayne,

Welcome to the UltiMaker Cura Github 🚀 

We made some improvements in Cura 5.3 for the Zseam.
Could you check if you get the same result if you change the Seam Corner Preference to None?
I expect that it shows a better result, we are aware that the sharpest corner is not working as expected yet. 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/15290
We have a ticket on our backlog with the intent to improve this behavior.

I'll be closing this issue as a duplicate but you can follow the progress here:https://github.com/Ultimaker/Cura/issues/15290

**Closed by MariMakes** 2023-06-19 09:36 UTC
Labels: Type: Bug, Status: Triage
