### ISSUE TITLE
supports wider than part

### ISSUE THREAD

**Issue by jxer** [Ultimaker/Cura#16880] opened 2023-10-04 01:46 UTC
### Cura Version

5.4

### Operating System

10

### Printer

ender

### Reproduction steps

normal supports are wider than actual part, this does not occur in 5.1

photo below
https://i.imgur.com/uNlMZk8.jpeg
5.1.1 on left 5.4 on right

### Actual results

5.4 is wider

### Expected results

should be same width as part

### Add your .zip and screenshots here ⬇️

https://i.imgur.com/uNlMZk8.jpeg
5.1.1 on left 5.4 on right

**Comment by Asterchades** [comment] 2023-10-04 02:08
Without a log or project all anyone can do is guess, but this looks like exactly the expected behaviour you'd find if the `Support Horizontal Expansion` values were different between the two slices - specifically 5.4 having a higher value.

Should this not be the case, more information is going to be required in order to do any meaningful diagnostics.

**Comment by jxer** [comment] 2023-10-04 02:11
You nailed it but this a calculated value, 5.4 puts it at .8 vs 0 for 5.1 any idea why?

**Comment by GregValiant** [comment] 2023-10-04 03:18
0.8 is the default value in 5.4.0.  I don't know why they did that.  You could put an override into your printer definition file or update a custom profile with your favorite value.  The setting's internal name is "support_offset".

I'll go ahead and remove the bug label and close this.  As @Asterchades says, this is expected behavior.

**Closed as completed by GregValiant** 2023-10-04 03:18 UTC
Labels: Type: Discussion, Status: Under Investigation

**Comment by Asterchades** [comment] 2023-10-04 04:12
> any idea why?

It was changed eight months ago (pull request #14627) to have a value equal to the Support Line Width plus 0.4mm when using regular supports, or 0mm for trees. The notation for the pull indicates that smoothing being applied to support generation was effectively applying a negative horizontal expansion value, so they've applied a positive value by default to compensate.

It was also noted in the [5.3 release notes](https://github.com/Ultimaker/Cura/releases/tag/5.3.0) under `Printer definitions, profiles and materials`, albeit no specific value was given.

> - Updated Support Horizontal Expansion, Support Join Distance, and Minimum Support Area Settings to improve support reliability.

**Comment by GregValiant** [comment] 2023-10-04 12:30
There are instances when the "Support Horizontal Expansion" at 0.8 can hang off the edge of the model when the supports are "Everywhere".  The first ring around this platform will fail as will the tiny Support Interface being generated.
![image](https://github.com/Ultimaker/Cura/assets/64202104/62ed41d3-126b-42cd-b81a-19196c691b1e)

**Comment by jxer** [comment] 2023-10-04 15:59
not sure why we are closing as expected behavior, its clearly too large for at least 3 of the models I ran against it.

**Comment by GregValiant** [comment] 2023-10-04 19:59
It's a setting that you can change to suit the situation.  Change it from 0.8 to whatever is required by your current project.  You can save it to a custom profile and it will be the default in that profile.  You can add an override to the printer definition file and make the default whatever you want.  When "Setting Visibility" is set to "All" you will find "Support Horizontal Expansion" in the Support section.
It isn't a bug and the setting is working as it is supposed to.  Your issue seems to be that you don't like the default value of 0.8 which someone else had asked for.
You can put in a feature request to have the default rolled back to "0.0".  I went with the override in the printer definition file as I do for all things in Cura that I don't like the default setting ("Skirt Height" is another one.)
