### ISSUE TITLE
Customize print order for “One at a Time”

### ISSUE THREAD

**Issue by agermanltk** [Ultimaker/Cura#7167] opened 2020-02-27 04:37 UTC
Title pretty much says it all. When arranging numerous prints and opting for the one at a time feature there is no method (that I could find) to easily set the order which objects are printed. 

Also maybe considering grouping? So if you have an entire square bed filled with models you can print one row simultaneously, then move on to the next row, and so on. This way if you have a failure mid print (Jam, loss of power, etc.) you will have a method to mitigate your loses

**Comment by Ghostkeeper** [comment] 2020-02-28 14:52
Grouping already exists. You can select multiple models (using the shift key) then right click and select "Group Models" (or Ctrl+G). Models within the same group get printed together all at once.

The other feature request is a duplicate of https://github.com/Ultimaker/Cura/issues/4835. Please continue discussion there.

**Closed by Ghostkeeper** 2020-02-28 14:52 UTC
Labels: Type: New Feature
