### ISSUE TITLE
[REQUEST] Rename items in Object List

### ISSUE THREAD

**Issue by KenLucke** [Ultimaker/Cura#7933] opened 2020-06-14 22:59 UTC
Please add the ability to rename the names of the items in the Object List.  This would help to keep track of duplicated objects better, and also allow the support blockers and other "attached" items to be named so that they could be identified.

Also, it would be helpful if things such as the support blockers would be hierarchical (preferably collapsible) with their parent object, rather than separate in the list.

**Comment by smartavionics** [comment] 2020-06-15 05:17
If you install the Mesh Tools plugin from the Cura marketplace, it has the ability to rename items in the object list along with its other useful features.

**Comment by KenLucke** [comment] 2020-06-15 09:04
> If you install the Mesh Tools plugin from the Cura marketplace, it has the ability to rename items in the object list along with its other useful features.

Ah, OK, have that installed, did  not realize it did that.  That helps... it would be easier to just control-click on the name to change it, but I can't have everythinig :)

The hierarchical stuff would still be cool.

**Comment by mahtDFR** [comment] 2020-06-16 08:52
Nice idea. We discussed it this morning and decided that as the functionality is already available as a plugin we can't prioritise this right now, so it is deferred and open to pull requests.

**Comment by fieldOfView** [comment] 2020-06-16 09:16
The next release will already have some improvements to the objects list (see https://github.com/Ultimaker/Cura/pull/7483). I was planning a PR to add "the hierarchical stuff" for a later release.

**Comment by konskarm** [comment] 2020-10-22 08:47
There is already a ticket in our backlog for this exact issue (CURA-6798). I am closing this issue as a duplicate of https://github.com/Ultimaker/Cura/issues/7116.

**Closed by konskarm** 2020-10-22 08:47 UTC
Labels: Category: Cura, Status: Deferred, Type: New Feature
