### ISSUE TITLE
Crashes opening file

### ISSUE THREAD

**Issue by swd2000** [Ultimaker/Cura#15918] opened 2023-06-26 08:23 UTC
### Application Version

5.4.0-beta.1

### Operating System

Linux

### Printer

Ender 3

### Reproduction steps

I started Cura.
I clicked File->Open File(s).

### Actual results

It crashed and dumped core.

(UltiMaker-Cura:606318): Gtk-WARNING **: 04:10:03.370: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
/tmp/.mount_UltiMambUi95/AppRun: line 25: 606318 Aborted                 (core dumped) $scriptdir/UltiMaker-Cura "$@"

### Expected results

It shouldn't crash, but instead let me open a file to work on.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/11865969/cura.log)

**Comment by MariMakes** [comment] 2023-10-19 13:59
Hi @swd2000,

Sorry, it took us a while to get back to you 😞 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/16932
We have a ticket on our backlog with the intent to improve this behavior.

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/16932

**Closed by MariMakes** 2023-10-19 13:59 UTC
Labels: Type: Bug, Status: Triage
