### ISSUE TITLE
MacOS Catalina v 10.15.7

### ISSUE THREAD

**Issue by Jesseril** [Ultimaker/Cura#13910] opened 2022-11-27 00:44 UTC
### Application Version

5.2.1

### Platform

MacOS Catalina v 10.15.7

### Printer

Ender 3V2

### Reproduction steps

I upgrade to vV5.2.1 from V5.0.

### Actual results

The Cura program will not start up.

### Expected results

Went back to V5.0 everything work fine.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none

**Comment by MariMakes** [comment] 2022-12-01 12:56
Hey @Jesseril,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

The last version of Ultimaker Cura that supports your MacOS 10.15 is Cura 5.1.0.
We now have this support page explaining which operating systems we do and do not support.
https://support.ultimaker.com/hc/en-us/articles/360011889579

We plan to implement a fix soon where users will get a warning if their OSx is too outdated: https://github.com/Ultimaker/Cura/issues/13611

Apologies for any inconvenience caused by our delayed response.
With improvements in place, I'll be closing this issue.

**Closed by MariMakes** 2022-12-01 12:56 UTC
Labels: Type: Bug, Status: Triage
