### ISSUE TITLE
Occurence of small, sharp steps on wall paths

### ISSUE THREAD

**Issue by Pepe-Pepperoni** [Ultimaker/Cura#15482] opened 2023-05-09 00:05 UTC
### Application Version

5.3.1 AppImage

### Platform

Linux (Manjaro)

### Printer

Ender 5 Plus

### Reproduction steps

Download this model: https://files.printables.com/media/prints/388834/stls/3253117_d071ab34-d9af-491e-916d-d7f80e989fbb/body.stl

Slice it with default standard quality profile

Observe fine steps in surface

### Actual results

There are 90° steps generated on wall paths where there are no edges in the input STL file that make the printer slow down and create blobs. There is no connection with the triangulation of the input file because even if I remesh it in blender so that only well shaped triangles (no elongated ones anywhere) are present the artifacts happen at approximately the same locations of the model.
Translating or rotating the model didn't change the artifacts in a significant way.
The ridge in image "artifacts_walls.png" is almost continuous with some small gaps here and there.
These edges appear on multiple smooth surfaces seemingly random.
Changing slicing settings (like random seam placement and others) has no influence on the artifacts afaict unless "spiralize outer contour" is selected. Then I didn't see any.

### Expected results

Smooth wall paths without 90° steps on smooth surfaces.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![artifacts_walls_angle](https://user-images.githubusercontent.com/35401801/236960613-c182460e-4899-4985-9311-440ceba599cf.png)
![artifacts_walls_2](https://user-images.githubusercontent.com/35401801/236960616-2162ea3e-6dc7-40ac-9866-1547002037a1.png)
![artifacts_walls](https://user-images.githubusercontent.com/35401801/236960619-11751211-5555-4f8c-b559-6d405f123712.png)
[project.zip](https://github.com/Ultimaker/Cura/files/11425974/project.zip)

**Comment by MariMakes** [comment] 2023-05-09 14:52
Hey @Pepe-Pepperoni,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

I recognize your issue 😊 
This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/14811
Our developers are looking at a solution for these strange line segments as we speak. 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/14811

**Closed by MariMakes** 2023-05-09 14:52 UTC
Labels: Type: Bug, Status: Triage
