### ISSUE TITLE
When I get a popup window( market place or when trying to multiply selected)  the window is white and then stope responding.

### ISSUE THREAD

**Issue by rwfracing** [Ultimaker/Cura#13001] opened 2022-08-11 04:56 UTC
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Creality CR-10 and Sidewinder x1

### Reproduction steps

When I get a popup window( market place or when trying to multiply selected)  the window is white and then stope responding.

### Actual results

When I click to multiply selected I get the popup window and it has a white background and stops responding. also happens when I try to go to the market place.  
![curanotresponding](https://user-images.githubusercontent.com/8878741/184066433-0cd746eb-2edb-48c7-8d87-2222d5bab55d.png)
 

### Expected results

Should get the option to put the numbers of objects.
[cura.log](https://github.com/Ultimaker/Cura/files/9306157/cura.log)
 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9306160/cura.log)

**Comment by Vandresc** [comment] 2022-08-11 13:40
Hi @rwfracing , thank you for your report, we have a ticket on our backlog still. I will close this ticket as a duplicate of https://github.com/Ultimaker/Cura/issues/12197. Please follow any progress/feedback in there. Thank you!

**Closed by Vandresc** 2022-08-11 13:40 UTC
Labels: Type: Bug, Status: Triage
