### ISSUE TITLE
tagging releases

### ISSUE THREAD

**Issue by greyltc** [Ultimaker/Cura#878] opened 2016-07-20 11:28 UTC
It looks like 2.12 has been out for a while:
https://ultimaker.com/en/products/cura-software/list

Where is the tag corresponding to this release?

**Comment by Ghostkeeper** [comment] 2016-07-21 11:04
Duplicate of #763. We are really intending to do that with 2.1.3 ;)

**Closed** 2016-07-21 11:04 UTC
Labels: duplicate
