### ISSUE TITLE
Won't Slice object.

### ISSUE THREAD

**Issue by TheSpiceOfLife** [Ultimaker/Cura#15741] opened 2023-06-13 21:03 UTC
### Cura Version

5.3.1

### Operating System

Windows 10 Pro

### Printer

Ultimaker S3

### Name abnormal settings

None That I know of

### Describe your model

It is a box lid

### Add your .zip here ⬇️

[UMS3_CardBoxTop v7 - Flat on Build Plate.zip](https://github.com/Ultimaker/Cura/files/11739324/UMS3_CardBoxTop.v7.-.Flat.on.Build.Plate.zip)

I don't understand.  I've never had a issue slicing an object on older versions of Cura.  Why Now?  Its a simple box should not cause a issue, no crazy angles.  It makes no sense.  Any assistance is appreciated.

**Comment by MariMakes** [comment] 2023-07-17 13:35
Hey @TheSpiceOfLife,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 

I took a look at your projectfile in Cura 5.4 because we made a lot of improvements in the tree support and I was able to slice your project successfully!
![image](https://github.com/Ultimaker/Cura/assets/40423138/28302d42-c7d9-4cb4-888b-690bacc12c79)

You can download the Cura version with the fix here: https://github.com/Ultimaker/Cura/releases/tag/5.4.0

To me, it doesn't seem like a bug in Ultimaker Cura, since we have a solution in place. 
Apologies for any inconvenience caused by our delayed response. 
I'll be closing this issue. I hope you understand.

**Closed by MariMakes** 2023-07-17 13:35 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:
