### ISSUE TITLE
Not detected OpenGL when load from Microsoft Remote Desktop

### ISSUE THREAD

**Issue by humbertosales** [Ultimaker/Cura#8160] opened 2020-08-07 19:14 UTC
**Application version**
4.6.2

**Platform**
Windows 10

**Printer**
Ender 3

**Reproduction steps**
1. Connect in remote computer using Remote Desktop (RDP)
2. Start Cura
3. Message show.

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/9614088/89679999-84b90c00-d8c8-11ea-913d-52220301bcc5.png)

**Actual results**
Computer with OpenGL, but Cura not start because not detect OpenGL via RDP.

**Expected results**
Start Cura.

**Project file**
N/A

**Log file**
N/A

**Additional information**
N/A

**Comment by Mosher23** [comment] 2020-08-08 08:04
its not cura its your pc, any program which uses OpenGL will not start over RDP

**Comment by fieldOfView** [comment] 2020-08-08 09:57
If you happen to be using an NVidia GPU, there's a patch to fix the problem:
https://www.khronos.org/news/permalink/nvidia-provides-opengl-accelerated-remote-desktop-for-geforce-5e88fc2035e342.98417181
If not, you are out of luck. It is your OS telling Cura (or other applications that need OpenGL) that there is no GPU in the system.

**Comment by Ghostkeeper** [comment] 2020-08-10 12:01
Duplicate of https://github.com/Ultimaker/Cura/issues/5474.

**Closed by Ghostkeeper** 2020-08-10 12:01 UTC
Labels: Type: Bug
