### ISSUE TITLE
Multiple Machines VIA USB

### ISSUE THREAD

**Issue by reedpat1** [Ultimaker/Cura#8800] opened 2020-11-19 14:17 UTC
PROBLEM: I have 2 Ender 3 Pros, both are connect to the same computer via USB.  Unfortunately, it is impossible to open 2 Cura applications and print to these 2 machines via USB at the same time. 

SOLUTION:  When open, the Cura Application can set which printer it is hosting via USB.  Hence, if another Cura Application is open I can chose a different printer.  Each time the application is open it connects to a specific printer.

ALETERNATIVE: I have to connect one of my Ender 3 Pro to Cura and the other to MatterControl - which I hate.

BENEFITS: You have unlimited NON-networking printer all going to one computer. 

OTHER: As a reference, I have been doing this for years with my MakerBot printers. I have 3 Makerbots all connected to one computer.  I open 3 Makerbot Desktops Applications. Choose which printer will go to which application and then I can print to each printer simultaneously  

![Cura Usb Problem](https://user-images.githubusercontent.com/74720633/99677626-ea7c6e80-2a47-11eb-9738-87110d152fd8.jpg)

[Cura Usb Problem.pdf](https://github.com/Ultimaker/Cura/files/5567261/Cura.Usb.Problem.pdf)

**Comment by Ghostkeeper** [comment] 2020-11-23 09:57
Duplicate of https://github.com/Ultimaker/Cura/issues/5207 .

This can currently be done from command line with the `CURA_DEVICENAMES` environment variable, which is not a viable solution for 99% of the users but it's something you might want to look at as a workaround.

**Closed by Ghostkeeper** 2020-11-23 09:57 UTC
Labels: Type: New Feature
