### ISSUE TITLE
Show the real scale with big models

### ISSUE THREAD

**Issue by MiguelAngelLV** [Ultimaker/Cura#259] opened 2015-08-16 07:14 UTC
When you load a big model, Cura autorescale to max size for the bed. This is good, but show scale 100% when it is less.

I think it would show the scale real used.

**Comment by Ghostkeeper** [comment] 2015-08-17 00:19
This is a duplicate of #142. We should continue conversation there.

**Closed** 2015-08-17 00:19 UTC
