### ISSUE TITLE
[4.0.0] Dock / Expand Settings Pane

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#5624] opened 2019-04-13 04:29 UTC
Maybe I am just missing it, but how can the full height settings pane be restored?

I am really not a fan of moving the settings pane off the right side of the screen, and isolating the layers slider in a corridor of wasted space.

**Comment by fieldOfView** [comment] 2019-04-13 05:20
There’s a plugin for that: Sidebar GUI, available in the Marketplace.

**Comment by CCS86** [comment] 2019-04-13 17:48
Thank you, much better!

**Comment by Ghostkeeper** [comment] 2019-04-15 10:02
Duplicate of https://github.com/Ultimaker/Cura/issues/5097

**Closed by Ghostkeeper** 2019-04-15 10:02 UTC
