### ISSUE TITLE
Octoprint webcam not showing in monitor in rev. 4.1

### ISSUE THREAD

**Issue by paubley** [Ultimaker/Cura#5869] opened 2019-06-06 21:32 UTC
**Application Version**

**Platform**

**Printer**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by Ghostkeeper** [comment] 2019-06-07 08:42
Please report issues with third-party plug-ins in their respective repositories. In your case this is a duplicate of https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues/116.

**Closed by Ghostkeeper** 2019-06-07 08:42 UTC
Labels: Type: Bug
