### ISSUE TITLE
Single layer prints not working

### ISSUE THREAD

**Issue by Haydos76** [Ultimaker/Cura#10477] opened 2021-09-19 00:12 UTC
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Anycubic Chiron

### Reproduction steps

Load up the 25 bed leveling circles that I have always used since owning the machine. 
select 0.3 draft
select slic
![1](https://user-images.githubusercontent.com/90991921/133911495-a246bddc-1929-450c-a7fb-3469219167ad.jpg)
![2](https://user-images.githubusercontent.com/90991921/133911498-2a664817-0a76-42b1-8765-3af11f3d9468.jpg)

e

### Actual results

The sliced file will not work, it won't generate the gcode and comes up with 0 time and 0g used

### Expected results

It should generate a working print that will assisst me in leveling the bed

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Nothing to add.

**Comment by jellespijker** [comment] 2021-09-19 06:16
Duplicate of #10394 closing this in favor of the discussion there

**Closed by jellespijker** 2021-09-19 06:16 UTC
Labels: Type: Bug
