### ISSUE TITLE
[4.4.1] Support dots appearing in air not connected to model

### ISSUE THREAD

**Issue by SlightlyLeprousHamster** [Ultimaker/Cura#7132] opened 2020-02-19 00:58 UTC
**Application version**
4.4.1

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)
Windows 10 64bit

**Printer**
Creality CR-10

**Reproduction steps**
1. Model loaded (https://www.thingiverse.com/thing:4051669)
2. Model sliced with tree supports (support settings in screenshot)
3. Dots appear (screenshot)
4. During print, extrusion does occur at these locations.

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
![image](https://user-images.githubusercontent.com/61214783/74791479-88a89180-5288-11ea-9893-ab6ff4dedda3.png)

![image](https://user-images.githubusercontent.com/61214783/74791510-952cea00-5288-11ea-8e5a-add30e372824.png)

![image](https://user-images.githubusercontent.com/61214783/74791524-9f4ee880-5288-11ea-98c0-b2fe23e5c68c.png)

![image](https://user-images.githubusercontent.com/61214783/74791538-abd34100-5288-11ea-9bf4-5f59e0c3eb29.png)

**Actual results**
Model prints mostly ok, but with extrusions at the phantom dots.

**Expected results**
These dots should not appear.

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

[CCR10_Frost_elemental.zip](https://github.com/Ultimaker/Cura/files/4222560/CCR10_Frost_elemental.zip)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by rburema** [comment] 2020-02-25 08:16
I don't have a ready solution right now, but as a workaround, you can try to set 'Minimum Support Area' to a small value (instead of `0`).

**Comment by Ghostkeeper** [comment] 2020-02-25 16:41
I've seen this bug myself as well. It can even occur if you've disabled support interface completely, for some reason.

**Comment by rburema** [comment] 2020-03-17 13:35
I think this is a duplicate of #7050 since creality has support x/y distance set to > 0 could be a workaround as well to set x/y distance to 0?

Closing this as duplicate, please see the open original ticket for further discussion.

**Closed by rburema** 2020-03-17 13:35 UTC
Labels: Status: Duplicate, Type: Bug

**Comment by nallath** [comment] 2020-07-13 09:25
Fixed for 4.7
