### ISSUE TITLE
ERREUR INCONNUE SLICE

### ISSUE THREAD

**Issue by JOLLIVON** [Ultimaker/Cura#13773] opened 2022-11-09 08:14 UTC
### Application Version

5.2.1

### Platform

WINDOWS 11

### Printer

ENDER 3 V2

### Reproduction steps

SLICE

### Actual results

ECHEC DE LA DECOUPE AVEC UNE ERREUR INCONNUE

### Expected results

DECOUPE
![Capture d’écran 2022-11-09 091100](https://user-images.githubusercontent.com/114077029/200774698-8d476dd3-13f6-4db1-bdd7-7139a962fcf2.png)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

FILE
[CE3E3V2_Corps1.zip](https://github.com/Ultimaker/Cura/files/9968852/CE3E3V2_Corps1.zip)

**Comment by JOLLIVON** [comment] 2022-11-09 10:08
Thanks .
i think it's not a problem of the part because i had this kind of error
many times with the 5.1 and i succes to slice sometimes. maybe it's a
problem of the installation of the software.
I tried differents part and i have the same issue.
When i have this issue i can't slice anything. so i use ideamaker to slice
but i prefer Cura.
I don't understand this issue if i can help to solve it.
Best regards.
Jérôme Ollivon

*Mail*: ***@***.***
*Téléphone:* +33 6 81 55 04 10
*Adresse: *4 allée des boulards
                   78430  Louveciennes

**Comment by MariMakes** [comment] 2022-11-09 10:11
Thanks for the update!

Ah, than it might be related to something on your device. 
Than it would be more helpful for us to see your logs the next time you encounter this. 

You can find your log file here:
Windows: %APPDATA%\cura\<Cura version>\cura.log or usually C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Comment by JOLLIVON** [comment] 2022-11-09 13:26
i had the issue . I use Fusion 360 and when i send the part to cura i have
the issue
*Jérôme Ollivon*

*Mail*: ***@***.***
*Téléphone:* +33 6 81 55 04 10
*Adresse: *4 allée des boulards
                   78430  Louveciennes


Le mer. 9 nov. 2022 à 11:18, OLLIVON JEROME ***@***.***> a
écrit :

**Comment by MariMakes** [comment] 2022-11-10 12:42
Hey @JOLLIVON,

Thanks for getting back to us 👍
How are you sending your model from Fusion 360 to Cura? 

Are you exporting your model to an STL?
[Are you Sending to Cura? ](https://knowledge.autodesk.com/support/fusion-360/learn-explore/caas/sfdcarticles/sfdcarticles/How-to-3D-print-a-stl-model-in-Fusion-360-to-a-Ultimaker-Cura-printer.html) 
Or are you using the [Fusion 360 integration](https://marketplace.ultimaker.com/app/cura/integrations/Autodesk/Fusion360)?

**Comment by JOLLIVON** [comment] 2022-11-10 15:02
Hello, I use the fusion360 integration with a specific application because
I use Creality slicer and Ultimate Cura.
*Jérôme Ollivon*

*Mail*: ***@***.***
*Téléphone:* +33 6 81 55 04 10
*Adresse: *4 allée des boulards
                   78430  Louveciennes

**Comment by MariMakes** [comment] 2022-11-30 10:12
Apologies for any inconvenience caused by our delayed response. 
To me, it doesn't seem like a bug in Ultimaker Cura, since it only seems to happen with a Fusion360 integration. 

Would you still like to keep this issue open or do you agree that we can close it?

**Closed** 2022-12-14 12:19 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage, Slicing Error💥
