### ISSUE TITLE
Print settings menu - Scrollbar of on-hover text not reachable

### ISSUE THREAD

**Issue by volker-rode** [Ultimaker/Cura#11908] opened 2022-04-23 12:03 UTC
### Application Version

5.0.0-beta+1

### Platform

Windows 10

### Printer

Anycubic Vyper

### Reproduction steps

Use the advanced Print Settings.
Move the mouse cursor to a setting description and wait until the explanation comes hovering up.
If the text is a bit longer then the area is limited in height and there is a scrollbar. (e.g. Combing Mode)

### Actual results

The text disappears before you can reach the scrollbar. I'm not able to read the lower area of the text.
Comparison to V 4.13.1 : No scrollbars there!

### Expected results

Either display the complete text or make the help text scrollbar reachable.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no uploads needed.

**Comment by fvrmr** [comment] 2022-04-25 11:48
Hi @volker-rode thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11834
I will close this since this is a duplicate.

**Closed by fvrmr** 2022-04-25 11:48 UTC
Labels: Type: Bug
