### ISSUE TITLE
skin overlap missing

### ISSUE THREAD

**Issue by pi4head** [Ultimaker/Cura#9745] opened 2021-05-01 16:46 UTC
### Application Version

arachne

### Platform

windows 10

### Printer

creality ender 3

### Reproduction steps

I activate skin overlap in the setting menu

![image](https://user-images.githubusercontent.com/83510188/116789073-61b13680-aaad-11eb-9f43-f29482dc1fb7.png)

### Actual results

it doesn't show up

![image](https://user-images.githubusercontent.com/83510188/116789091-71c91600-aaad-11eb-84e7-17ac9b342d4c.png)

### Expected results

it should show up.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

mandatory text here

**Comment by fvrmr** [comment] 2021-05-03 13:06
Hi @pi4head thank you for your report.
I am not able to reproduce this. Could you share a project file (file - save project)?

**Comment by pi4head** [comment] 2021-05-03 14:25
Here you go.
on a side note, on some preloaded profile that is imported from 4.8
version, the skin overlap is already there.

**Comment by fvrmr** [comment] 2021-05-04 09:07
Could you attach the file as a .zip in a comment on Github? I can't see the file since you replied via email.

**Comment by pi4head** [comment] 2021-05-04 09:09
[bugReport_arachne.zip](https://github.com/Ultimaker/Cura/files/6420062/bugReport_arachne.zip)
gladly.

**Comment by fvrmr** [comment] 2021-05-04 15:38
Thank you, if you change your top/bottom pattern to lines or zigzag the skin overlap is visible. The reason is that concentric is not supported with skin overlap. 
I will close this issue, since changing the top/bottom pattern will solve this issue.

But feel free to reach out if you have more questions.

**Comment by pi4head** [comment] 2021-05-04 15:48
thank you for your clarification. I think that an additional line in the tooltip would be helpful. Have a nice day!

**Closed** 2021-05-04 15:57 UTC
Labels: Type: Bug
