### ISSUE TITLE
[5.0 beta] Popup descriptions do not show the entire text and can't be scrolled

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#11880] opened 2022-04-22 10:08 UTC
### Application Version

5.0 beta

### Platform

win10

### Printer

custom fff

### Reproduction steps

Hover cursor over a setting.
A popup description appears with scrollbars.

### Actual results

There is no way to scroll it as it disappears as soon as I move the cursor from the setting.
If I use the mouse wheel or arrow buttons it scrolls the settings instead.

### Expected results

Show the entire description or make it possible to scroll it somehow.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![popups](https://user-images.githubusercontent.com/32172100/164686077-aec653a3-1ade-47d6-8efe-473686045cf1.jpg)

**Comment by Vandresc** [comment] 2022-04-22 10:23
Yes, on our radar. Working on it for the stable. Keep bringing them in :)

**Comment by printingotb** [comment] 2022-04-24 10:30
> Keep bringing them in :

You asked for it 😁

**Comment by fvrmr** [comment] 2022-04-25 09:55
Closing this issue since it is a duplicate of https://github.com/Ultimaker/Cura/issues/11834

**Closed by fvrmr** 2022-04-25 09:55 UTC
Labels: Type: Bug
