### ISSUE TITLE
Not slicing

### ISSUE THREAD

**Issue by ThomasNiemann** [Ultimaker/Cura#14408] opened 2023-01-28 19:35 UTC
### Application Version

5.1.0

### Platform

Windows 11

### Printer

Twotree Saphire Plus

### Reproduction steps

1. added a model
2. rotated to it fit flat
3. increased scale to 250%
4. tried to slice

### Actual results

Error: Slicing failed do to unexpected error.

### Expected results

Model is sliced

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

None

**Comment by MariMakes** [comment] 2023-02-03 15:29
Hey @ThomasNiemann,

Welcome to the Ultimaker Cura Github 🚀
Thanks for your report 👍

Is it possible that your printjob is located at 0, 0, 0, and it slices if you move it a little away from the center of the buildplate? 
Then it might be a duplicate of https://github.com/Ultimaker/Cura/issues/13643

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Closed** 2023-02-18 00:18 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage
