### ISSUE TITLE
Z seam failure

### ISSUE THREAD

**Issue by BaininMW** [Ultimaker/Cura#15882] opened 2023-06-23 16:42 UTC
### Application Version

5.4.0 beta1

### Operating System

Windows 10 Intel

### Printer

Kingroon KP3S

### Reproduction steps

Slice model with flat vertical face with 0.2mm nozzle: Z seam align: Shortest, smart hiding. Good result.
Identical model; only settings changed 0.4mm nozzle and line width: Z seam on flat vertical face although sharp corners are available.
Similar issues with all z seam alignment settings using 0.4 nozzle.

### Actual results

Correct with 0.2 nozzle, z seam on flat vertical face with 0.4mm nozzle.
Similar issues with all z seam alignment settings using 0.4mm nozzle.
3mf fproject files:
[MW-z-seam-files.zip](https://github.com/Ultimaker/Cura/files/11850261/MW-z-seam-files.zip)
Screenshots:
[CuraScreen001.zip](https://github.com/Ultimaker/Cura/files/11850338/CuraScreen001.zip)

### Expected results

0.4 nozzle slice should have had similiar sean placement as 0.2mm nozzle

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Fully reproducible: attached files are remakes of those on which I first saw the issue.

**Comment by RedeyesXBL** [comment] 2023-06-25 00:11
I posted a similar bug which turns out to be the same bug. It works properly at .2mm nozzle as you say, gets progressively worse the bigger the nozzle size. ,8 makes no attempt to hide the seam at all.

**Comment by BaininMW** [comment] 2023-06-25 10:41
Thanks Bill. I will keep an eye on the progress of these bug reports. There
does seem to have been an issue with the seams for a while, and I hope it
can be fixed soon.
Mike

**Comment by MariMakes** [comment] 2023-07-05 14:49
Hey @BaininMW,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I recognize this issue. 🕵️ 
We have a known issue where the Hide seam is actually not hidden and can give random results, for now changing the Seam Corner Preference to None will give better results. 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/15290.
We have a ticket on our backlog with the intent to improve this behavior.
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/15290.

**Closed by MariMakes** 2023-07-05 14:49 UTC
Labels: Type: Bug, Status: Triage

**Comment by BaininMW** [comment] 2023-07-05 17:57
Many thanks for your email.
I posted the report because of the variations in results with different
nozzle sizes.
As a moderator on the Cura Ultimaker slicer group I have been made aware of
various z seam issues, and I was following the advice I give to most of the
complainers: report problems to the developers!
Keep up the good work.
Regards,
Mike
