### ISSUE TITLE
A Fatal Exception has occurred.

### ISSUE THREAD

**Issue by misalo1** [Ultimaker/Cura#3036] opened 2017-12-23 02:34 UTC
Just stopped working, reloaded and got this, re-installed and got the same error.

Version: 2.3.1
Platform: Windows-Vista-6.0.6002-SP2
Qt: 5.5.1
PyQt: 5.5.1

Exception:
Traceback (most recent call last):
  File "cura_app.py", line 61, in <module>
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Application.py", line 310, in getInstance
  File "D:\2.3\build\inst\lib\python3.4\site-packages\cura\CuraApplication.py", line 173, in __init__
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Qt\QtApplication.py", line 94, in __init__
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\VersionUpgradeManager.py", line 107, in upgrade
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\VersionUpgradeManager.py", line 281, in _upgradeFile
MemoryError

**Comment by fieldOfView** [comment] 2017-12-23 09:34
Duplicate of #2993

Go to C:\Users[you]\AppData\local\cura, and delete cura.log

**Closed** 2017-12-29 15:10 UTC
