### ISSUE TITLE
Supports extending to bed, but un-needed

### ISSUE THREAD

**Issue by yet-another-average-joe** [Ultimaker/Cura#5538] opened 2019-03-30 18:36 UTC
Sorry, I had some problems while formatting this post, it is havoc !

**Application Version**

Cura 4.0, but the issue was there with 3.6 

steps to reproduce

- "walls" with "holes" (the technical terminology could be different, but I miss some vocabulary !
fillets around the bottom face
- supports everywhere

- Large holes not touching buildplate are sliced normally
- Small holes not touching buildplate have supports extending to buildplate

but the supports exist onlky between the part bottom and the plate, not in the part itself (hopefully !)

What should happen after the above steps have been followed

no supports between the part and the plate ; they are useless, and need some unwanted post processing

**Additional Information**

In this model, I trick Cura in order to have no infill in the sides but 100% infill (playing with nozzle diameter and part walls width), so the part walls are filled with straight lines (much more faster, and less stress for the printer). (later, I will have a feature suggestion about this)

It seems to be hole size dependant. I will model a part with different hole sizes and see what happens

![Cura supports 01](https://user-images.githubusercontent.com/43514870/55280163-d55a4580-5321-11e9-8785-0c8eae9bc929.PNG)

[E3D Workbench Enclosure v1.2.3mf.zip](https://github.com/Ultimaker/Cura/files/3025813

![Cura supports 02](https://user-images.githubusercontent.com/43514870/55280306-22d7b200-5324-11e9-9d54-6cb5325aac95.PNG)

/E3D.Workbench.Enclosure.v1.2.3mf.zip)

**Comment by yet-another-average-joe** [comment] 2019-03-30 21:45
[update]

[supports01.zip](https://github.com/Ultimaker/Cura/files/3025990/supports01.zip)

![Cura supports 03](https://user-images.githubusercontent.com/43514870/55281985-bf597e80-533b-11e9-99a7-347eba654f2f.PNG)

![Cura supports 05](https://user-images.githubusercontent.com/43514870/55282008-0a739180-533c-11e9-9164-59695286d2bd.PNG)

![Cura supports 04](https://user-images.githubusercontent.com/43514870/55281988-c54f5f80-533b-11e9-9c5f-c5971336a5d1.PNG)

And now, without fillet : 

![Cura supports 06](https://user-images.githubusercontent.com/43514870/55282090-5b37ba00-533d-11e9-9ede-9d2e2c65beda.PNG)

**Comment by PKav89** [comment] 2019-04-01 05:39
It seems, like you have tree supports active with normal supports. Try disabling tree supports.

**Comment by yet-another-average-joe** [comment] 2019-04-01 10:27
Tree support is not activated (until now, I never used this function): 

![Cura supports 07](https://user-images.githubusercontent.com/43514870/55319588-7dccee80-5475-11e9-84b1-d1c4d47960cf.PNG)

Un-needed supports also appear when 'Touching buildplate" is selected :

![Cura supports 08](https://user-images.githubusercontent.com/43514870/55319860-23805d80-5476-11e9-9d83-7a20f2a137cb.PNG)

Replacing filet with a 45° chamfer, therefore, it seems it is not related to the filet :

![Cura supports 09](https://user-images.githubusercontent.com/43514870/55320345-1e6fde00-5477-11e9-813d-803c30b23186.PNG)

![Cura supports 10](https://user-images.githubusercontent.com/43514870/55320351-2596ec00-5477-11e9-9478-b3eb08b0c9b0.PNG)

I am pretty sure taht this problem appeared with 3.6, and wasn't there before : I use filets and chamfers a lot, and did'nt see this before. Could some config file be corrupted ? Can you reproduce this on you setup ? (I uploaded a 3mf file in my previous post)

**Comment by PKav89** [comment] 2019-04-01 10:31
Sorry, my mistake. Try to disable "Use towers" and then, if it won't help, try to set Support horizontal expansion to 0.

**Comment by yet-another-average-joe** [comment] 2019-04-01 11:00
Bingo, it is towers related !

The glitches appear only when "Use Towers" is DISABLED and supports ENABLED (touching buildplate or not).

**Comment by Ghostkeeper** [comment] 2019-04-01 12:54
I consider this a bug. It's a duplicate of https://github.com/Ultimaker/Cura/issues/4219

The problem is that there is still support next to the model all the way down from the hole in your wall, due to the 0.2mm offset. This support is 0.2mm thick and thus too small to print. However down near the bottom of the model, the model gives way and then it is thick enough to print.

Closing this as a duplicate of #4219.

**Closed by Ghostkeeper** 2019-04-01 12:54 UTC
