### ISSUE TITLE
Cura will save a file named ".gcode" to external media

### ISSUE THREAD

**Issue by bbum** [Ultimaker/Cura#1760] opened 2017-04-29 22:47 UTC
- model something in Fusion 360
- have it spit STL at Cura
- Do the Cura thing and insert an SD card in reader
- Click "Save to External Media"

Cura will do so and offer to eject the media.  However, since the file seemingly comes in from Fusion with no name, it will be saved simply as ".gcode", which the Ultimaker will not recognize or open.

**Comment by fieldOfView** [comment] 2017-04-30 06:55
Duplicate of/caused by #1703

**Closed** 2017-05-01 07:42 UTC
