### ISSUE TITLE
4.6 and 4.7 Very slow response from GUI

### ISSUE THREAD

**Issue by clementatt** [Ultimaker/Cura#8497] opened 2020-10-05 11:23 UTC
I have not been able to do much with Cura.The GUI is very unresponsive which makes it horrible to use.
**Application version**
I experienced this in both version 4.6 and 4.7.

**Platform**
Windows 10 pro 2004

**Printer**
Ender 3

**Reproduction steps**
After setting anything in the profile, trying to rotate the model, clicking between views, etc. Pretty much any time I tried to do something with the GUI.

Screenshot(s)
![image](https://user-images.githubusercontent.com/44233232/95073148-ea960880-073e-11eb-80ee-a71c35e1691d.png)
![image](https://user-images.githubusercontent.com/44233232/95073160-ee298f80-073e-11eb-80f0-ccdccf8ad271.png)

Actual results
Takes 10 - 60 seconds to respond.

Expected results
It should respond much quicker.

Project file
N/A

**Log file**
[https://uploader.shimo.im/f/na7P2eQoyPODdC0S.log](url)

**Additional information**
I have used MKS Wifi Plugun, and cura has a freeze. When I uninstall it, the freeze still exists。
![image](https://user-images.githubusercontent.com/44233232/95073881-2a112480-0740-11eb-99fb-126c55c02d04.png)

I tried all of the things they that were suggested like turning off many of the plugins, running in compatibility mode, changing firewall settings, and changing preferences.

**Comment by konskarm** [comment] 2020-10-05 15:31
Try to see if the instructions in https://github.com/Ultimaker/Cura/issues/7476#issuecomment-703309810 fix your issue. 
I am closing this, since it is a duplicate of the aforementioned issue.

**Closed by konskarm** 2020-10-05 15:31 UTC
Labels: Type: Bug
