### ISSUE TITLE
Tree support supports inside hole

### ISSUE THREAD

**Issue by mbartlett21** [Ultimaker/Cura#5808] opened 2019-05-29 13:54 UTC
**Application Version**
4.0.0

**Platform**
Windows 10

**Steps to Reproduce**
Slice the attached model with tree supports enabled and standard supports disabled.

**Actual Results**
There is support in the middle hole.

**Expected results**
There should not be support in the middle hole

**Additional Information**
![image](https://user-images.githubusercontent.com/29034492/58562501-ba964580-826c-11e9-9a72-337d8022ea0a.png)
[STL File](https://cad.onshape.com/documents/70a82f53ae25d265335d33bc/w/85f5eb9e6264fd7739b1fec9/e/38e13bb5dd80e09dbb6a2bda)

**Comment by Ghostkeeper** [comment] 2019-05-29 14:24
Duplicate of https://github.com/Ultimaker/Cura/issues/4025

**Closed by Ghostkeeper** 2019-05-29 14:24 UTC
