### ISSUE TITLE
Generating support causes random shaped support "bone spurs" to print adjacent to model.

### ISSUE THREAD

**Issue by mbmast** [Ultimaker/Cura#6547] opened 2019-10-16 22:15 UTC
Even with very simple models, Cura 4.3.0 adds strange looking, spiky support adjacent to the model.  The photos included here have brim generated, but the problem occurs even with no brim.
![2019-10-16 (4)](https://user-images.githubusercontent.com/15057985/66963061-9377bf00-f027-11e9-81f2-7dc3bfa83f5a.png)
![2019-10-16 (3)](https://user-images.githubusercontent.com/15057985/66963062-9377bf00-f027-11e9-90bb-4d7634cfd738.png)
![2019-10-16 (2)](https://user-images.githubusercontent.com/15057985/66963063-9377bf00-f027-11e9-8c41-2c598ff91283.png)
![2019-10-16 (6)](https://user-images.githubusercontent.com/15057985/66963064-9377bf00-f027-11e9-8716-160fac976ebe.png)
![2019-10-16 (5)](https://user-images.githubusercontent.com/15057985/66963065-94105580-f027-11e9-963c-fcd00ab18e09.png)

Here's the model file:

[Support Test.zip](https://github.com/Ultimaker/Cura/files/3736590/Support.Test.zip)

**Comment by nallath** [comment] 2019-10-17 07:19
I think this might be caused by a rounding error. At the very least I can already provide a workaround for this. If you set the `support horizontal expansion` to -0.1, they weird areas will no longer be generated.

**Comment by Ghostkeeper** [comment] 2019-10-17 15:28
Duplicate of https://github.com/Ultimaker/Cura/issues/4219

**Closed by Ghostkeeper** 2019-10-17 15:28 UTC

**Comment by mbmast** [comment] 2019-10-17 18:22
@nallath's suggestion to set `support horizontal expansion` to -0.1 works.  If this suggestion does NOT provide a workaround to issue #4219 (and I suspect it won't) then I would say this issue is NOT a duplicate of #4219.

**Comment by Ghostkeeper** [comment] 2019-10-18 09:20
Setting horizontal expansion to -0.1 also improves it for the model in #4219. It's not completely gone then though. Seems that it needs -0.2 there. But the issue is very similar.
