### ISSUE TITLE
Octoprint camera picture in Monitor window not showing.

### ISSUE THREAD

**Issue by Kmarkopl** [Ultimaker/Cura#3725] opened 2018-04-25 17:40 UTC
**Application Version**
 3.3.0 3.3.1

**Platform**
 Windows 8.1 

**Qt**

**PyQt**

**Display Driver**

**Printer**

**Steps to Reproduce**
 All I did is install new Cura, first 3.3.0 then 3.3.1 

**Actual Results**
 Camera picture from octoprint not showing 

**Expected results**
 Camera picture from octoprint should be displayed 

**Additional Information**
 https://imgur.com/a/0q0M8ph

**Comment by fieldOfView** [comment] 2018-04-25 18:04
Can you upload the cura.log file from your configuration folder somewhere?

**Comment by Kmarkopl** [comment] 2018-04-25 18:16
Here please https://ufile.io/k5451

**Comment by fieldOfView** [comment] 2018-04-25 18:52
Thanks. Is ```http://192.168.1.100:8080/video``` the correct url for the camera image in your network?

I think the problem is the same as https://github.com/Ultimaker/Cura/issues/3457 and an issue of Cura as opposed to the OctoPrintPlugin, but I'll try to investigate. 

For the record, the camera image works fine for me, at least until I switch to a second OctoPrint instance.

**Comment by Kmarkopl** [comment] 2018-04-26 13:04
The IP of the camera is correct.
All works on older Cura 3.2.1 . After installing latest version of Cura 3.3.0 or 3.3.1,  no camera picture.

**Comment by adzule** [comment] 2018-04-26 16:02
`2018-04-24 11:11:36,094 - DEBUG - [MainThread] UM.Controller.setActiveStage [159]: Setting active stage to MonitorStage
2018-04-24 11:11:36,160 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [277]: file:///C:/Program Files/Ultimaker Cura 3.3/resources/qml/PrintMonitor.qml:27:5: QML OutputDeviceHeader: Binding loop detected for property "implicitHeight"
2018-04-24 11:11:40,094 - DEBUG - [MainThread] AutoSave.AutoSave._onTimeout [71]: Autosaving preferences, instances and profiles
2018-04-24 11:11:45,116 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [277]: file:///%USERPROFILE%/AppData/Roaming/cura/3.3/plugins/OctoPrintPlugin/OctoPrintPlugin/DiscoverOctoPrintAction.qml:236: TypeError: Cannot read property 'baseURL' of undefined
2018-04-24 11:11:51,815 - DEBUG - [MainThread] AutoSave.AutoSave._onTimeout [71]: Autosaving preferences, instances and profiles
2018-04-24 11:12:08,295 - DEBUG - [MainThread] OctoPrintPlugin.DiscoverOctoPrintAction.testApiKey [141]: Trying to access OctoPrint instance at http://192.168.1.167:80/ with the provided API key.
2018-04-24 11:12:09,601 - DEBUG - [MainThread] OctoPrintPlugin.DiscoverOctoPrintAction._onRequestFinished [291]: API key accepted by OctoPrint.
2018-04-24 11:12:19,989 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [277]: file:///C:/Program Files/Ultimaker Cura 3.3/resources/qml/PrinterOutput/OutputDeviceHeader.qml:31: TypeError: Cannot read property 'name' of null
2018-04-24 11:12:19,992 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [277]: file:///C:/Program Files/Ultimaker Cura 3.3/resources/qml/SidebarHeader.qml:20: TypeError: Cannot read property 'length' of undefined
2018-04-24 11:12:19,994 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [277]: file:///C:/Program Files/Ultimaker Cura 3.3/resources/qml/Preferences/MachinesPage.qml:162: TypeError: Cannot read property 'connectionText' of null
2018-04-24 11:12:20,009 - DEBUG - [MainThread] OctoPrintPlugin.OctoPrintOutputDevice.connect [316]: Connection with instance octopi._octoprint._tcp.local with url http://192.168.1.167:80/ started
2018-04-24 11:12:20,037 - DEBUG - [MainThread] OctoPrintPlugin.OctoPrintOutputDevice.connect [316]: Connection with instance octopi._octoprint._tcp.local with url http://192.168.1.167:80/ started
2018-04-24 11:12:20,072 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [277]: file:///%USERPROFILE%/AppData/Roaming/cura/3.3/plugins/OctoPrintPlugin/OctoPrintPlugin/MonitorItem.qml:7:9: QML Image: Failed to get image from provider: image://camera/2
2018-04-24 11:12:20,090 - INFO - [MainThread] UM.OutputDevice.OutputDeviceManager.addOutputDevice [103]: Output Device octopi._octoprint._tcp.local already added
2018-04-24 11:12:20,092 - INFO - [MainThread] UM.OutputDevice.OutputDeviceManager.addOutputDevice [103]: Output Device octopi._octoprint._tcp.local already added
2018-04-24 11:12:20,265 - DEBUG - [MainThread] OctoPrintPlugin.OctoPrintOutputDevice._onRequestFinished [681]: Set OctoPrint camera url to http://192.168.1.167:80/webcam/?action=stream`

**Comment by AirmakZ** [comment] 2018-04-28 10:46
Exactly same issue here upgrading from 3.2.1  to 3.3.1.
Stream url is OK but error "Failed to get image from provider" appears in the log.

**Comment by fieldOfView** [comment] 2018-04-28 11:41
I still have not been able to reproduce this exact issue, but do get a similar issue when there are two printers each with a different OctoPrint instance; in that case I can only get one camera to show (the one that Cura was started with as the active printer). I'll look in to fixing that, hoping that it also fixes your issue. Note that this seems to be a Cura issue, so it may not be possible to fix it before Cura 3.4.

Something you might try is switching to/from another printer while in the monitor.

**Comment by peacefulhill** [comment] 2018-04-28 11:43
I have the same issue after upgrading from 3.2.1 to 3.3.1. I only have one printer so I can't switch between different printers.

**Comment by fieldOfView** [comment] 2018-05-02 09:38
For my reference, here's a similar issue with the UM3 camera feed:
https://community.ultimaker.com/topic/22750-camera-on-ultimaker-3-not-working-in-cura-331/

**Comment by Gasman2014** [comment] 2018-05-02 13:07
Same here - macOS. Camera was working with Cura 3.2.1, now no longer works with Cura 3.3.1. Camera feed is viewable correctly at usual address and also viewable in Octoprint.

**Comment by ur7x** [comment] 2018-05-03 22:45
Same problem for me.  The camera is fine in browser and worked on Cura 3.2.1. now it's not there.

**Comment by VMaxx** [comment] 2018-05-08 01:01
Something I've noticed with this issue is that when you click in and out of monitor the error about image changes.  First pass its complaining about image://camera/2 and  image://camera/4, next click out and back to monitor it is image://camera/6 and image://camera/8 the number increases as you click in and out.

**Comment by Ghostkeeper** [comment] 2018-05-11 12:07
ShinerG on Ultimaker's forums says he found a cause and a solution/workaround: https://community.ultimaker.com/topic/22750-camera-on-ultimaker-3-not-working-in-cura-331/?tab=comments#comment-209181

Maybe that helps some people with this when it occurs in Octoprint. We have seen reports that this also happens with connections to the Ultimaker 3 camera feed but haven't been able to reproduce that ourselves yet.

**Comment by ur7x** [comment] 2018-05-15 23:11
So I have uninstalled 3.3.1 and went back to 3.2.1 and the Camera feed came back but the profiles are not backward compatible

**Comment by HappyDino** [comment] 2018-05-16 07:27
I have the same issue.
The stream url is also ok.

**Comment by rneurink** [comment] 2018-06-04 09:42
Also having this problem the url is correct but the camera wont show up.
I've had the camera show up once

`2018-06-04 11:38:54,634 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [277]: file:///C:/Users/user/AppData/Roaming/cura/3.3/plugins/OctoPrintPlugin/OctoPrintPlugin/MonitorItem.qml:7:9: QML Image: Failed to get image from provider: image://camera/26`

`2018-06-04 11:38:54,659 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [277]: file:///C:/Program Files/Ultimaker Cura 3.3/resources/qml/PrintMonitor.qml:27:5: QML OutputDeviceHeader: Binding loop detected for property "implicitHeight"`

`2018-06-04 11:38:54,703 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [277]: file:///C:/Users/user/AppData/Roaming/cura/3.3/plugins/OctoPrintPlugin/OctoPrintPlugin/MonitorItem.qml:7:9: QML Image: Failed to get image from provider: image://camera/28`

**Comment by nean-and-i** [comment] 2018-06-04 16:00
same here on macos.
+ 3.3.1 also have issues with fonts in some dialogs like plugins.
+ 3.3.1 also generates jobname prefix (CFDMP) out of type and not from printer name as previous version did 
had to downgrade to 3.2.2 which was much more stable on my end.
need to ask if you guys require some more additional help for testing before releasing?

**Comment by fieldOfView** [comment] 2018-06-04 16:21
@nean-and-i adding more problems to this issue will not get them fixed, and will only confuse things.

All, I am just a single 3rd party contributor. As I have indicated, I cannot reproduce this issue, so I cannot even begin to fix it. Thanks for the log snippets, but unfortunately they don't help me. I see the same messages on my working installation.

**Comment by AirmakZ** [comment] 2018-06-04 20:33
@fieldOfView, is there a way to release a test version including extra debug traces or similar?

**Comment by nean-and-i** [comment] 2018-06-05 11:51
@fieldOfView , sorry, that was not suppose to go into your direction, I appreciate your work!

**Comment by rneurink** [comment] 2018-06-06 10:03
@fieldOfView is there any information you need from us? it is obviously a problem with the QImageprovider so maybe the problem lies in the source code. Is there a way to get more debug information from the provider or check if the image is available. I can set up a dev enviroment if needed.

**Comment by fieldOfView** [comment] 2018-06-06 10:32
I have finally managed to reliably make it *not* work for me, looking to see if I can see why.

**Comment by RudiKlein** [comment] 2018-06-10 12:32
Same issue here. Went from 2.7 (camera works fine) to 3.3.1 (camera fail).
Would a Wireshark trace help to see what the actual string is that is sent over the network?
As a workaround for not being able to debug Cura?

**Comment by fieldOfView** [comment] 2018-06-11 09:32
I think I may have fixed the issue. It looks like the camera image did or did not show depending on how quickly Cura and the OctoPrintPlugin started (hence my trouble reproducing it). 

Please try this fix and see if it also fixes things for you:
* Go to Help -> Show configuration folder
* Navigate to plugins/OctoPrintPlugin/OctoPrintPlugin
* Replace the file named OctoPrintOutputDevice.py with this file:
https://raw.githubusercontent.com/fieldOfView/OctoPrintPlugin/3.4/OctoPrintOutputDevice.py
* Restart Cura
* Let me know if it is fixed

**Comment by msticninja** [comment] 2018-06-11 09:55
Works for me! TY!

**Comment by rneurink** [comment] 2018-06-11 10:19
That fixed it. Great work

**Comment by adzule** [comment] 2018-06-11 14:52
Also worked for me, thank you so much!

**Comment by fieldOfView** [comment] 2018-06-11 15:04
Ok, 3 confirmed fixes, I am submitting a fixed version to the plugins repository and am calling this fixed. The issue can be closed.

**Comment by RudiKlein** [comment] 2018-06-12 07:04
You nailed it! Works like a charm now.

Thanks!

**Comment by HappyDino** [comment] 2018-06-28 21:21
Works for me.

Thanks.

**Comment by ur7x** [comment] 2018-06-29 20:43
Broken again in 3.4 LOL...

**Comment by fieldOfView** [comment] 2018-06-30 08:10
@Ur7x, glad you find it funny. Technically it is not broken *again*, but it is broken *still*; the toolbox is still serving up a non-fixed version, instead of one including the fix above.

**Comment by LilBub** [comment] 2018-06-30 16:03
I agree with FoV.  It’s very frustrating that this has made it into the current release.  And when I pointed it out to Cura they quickly closed the ticket without a fix.   I’m not impressed.

**Comment by ur7x** [comment] 2018-06-30 17:11
Sorry my sarcasm was lost in my post... of course it is not funny... it is crazy... and sloppy.

**Comment by voglster** [comment] 2018-07-01 02:15
I will also confirm the fixed version of OctoprintOutputDevice.py indeed works.  I got here after searching the issue as well.

**Comment by diegopradogesto** [comment] 2018-07-10 09:00
Hey @fieldofview , this is the fix that you made in the version 3.4.1 of your plugin, right? If I'm correct, this version is now in the Toolbox, so... should we close this issue?

**Comment by fieldOfView** [comment] 2018-07-10 09:06
Yes, this can be closed

**Comment by diegopradogesto** [comment] 2018-07-10 09:12
Ok

**Closed by diegopradogesto** 2018-07-10 09:12 UTC
Labels: Category: 3rd-Party, Status: Needs Info

**Comment by cereyanli** [comment] 2018-09-05 09:54
This is also working on Mac OS

**Comment by paubley** [comment] 2019-06-06 21:38
Same behaviour after upgrade from 4.0 to 4.1...

**Comment by fieldOfView** [comment] 2019-06-07 07:01
@paubley, please see https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues/116 for a more up to date issue. This one has been closed long ago, because at the time the problem was fixed. Apparently some people have a similar issue with the current version.
