### ISSUE TITLE
Cura 2.7 beta - filament costs and weight not saved

### ISSUE THREAD

**Issue by nicolinux** [Ultimaker/Cura#2191] opened 2017-08-02 09:54 UTC
When I add the cost to a standard material it is reset to 0 when I restart Cura.
macOS Sierra 10.12.6

![screen shot 2017-08-02 at 11 50 00](https://user-images.githubusercontent.com/1069286/28868277-3fcfe8e2-7779-11e7-892a-0500644a8e47.png)

**Comment by nickthetait** [comment] 2017-08-02 21:15
This problem also exists on Ubuntu 17.04
Both fields are reset after closing Cura.

**Comment by Ghostkeeper** [comment] 2017-08-18 07:28
It doesn't happen for me. I also tried on Ubuntu 17.04. These were my reproduction steps:

* Start a fresh install of Cura.
* Add Ultimaker 3 printer.
* Go into the material manager.
* Set Filament Cost to 1 euro and weight to 200g.
* Close the dialogue.
* Restart Cura.
* Open the material manager again.

The information tab still shows 1 euro and 200g then, for me.

**Comment by nickthetait** [comment] 2017-08-18 18:18
I suggest trying with a installed version of the application @Ghostkeeper

**Comment by Ghostkeeper** [comment] 2017-08-29 23:17
Okay, I'm trying with a fresh install (or rather, deleted `AppData/Local/cura` and `AppData/Roaming/cura`) of the Cura 2.7 beta on Windows 8 now:

* Start a fresh install of Cura.
* Add Ultimaker 3 printer.
* Go into the material manager.
* Set Filament Cost to 1 euro and weight to 200g.
* Close the dialogue.
* Restart Cura.
* Open the material manager again.

The information tab still shows 1 euro and 200g then, for me :confused:

**Comment by nickthetait** [comment] 2017-09-01 19:29
Tested on Windows 10 and cannot reproduce the issue. Seems specific to Linux/OS X?

**Comment by ianpaschal** [comment] 2018-02-27 16:19
This is fixed in the most recent version (3.2.1).

**Closed by ianpaschal** 2018-02-27 16:19 UTC
