### ISSUE TITLE
Fatal Exception when setting filament diameter

### ISSUE THREAD

**Issue by Fixx** [Ultimaker/Cura#1614] opened 2017-03-30 19:14 UTC
1.75Version: 2.5.0-BETA
Platform: Windows-10-10.0.14393
Qt: 5.7.1
PyQt: 5.7.1

Exception:
Traceback (most recent call last):
  File "C:\Program Files\Cura 2.5\plugins\CuraEngineBackend\CuraEngineBackend.py", line 190, in slice
    self.printDurationMessage.emit(0, [0])
  File "D:/2.5/build/inst/lib/python3.5/site-packages/UM\Signal.py", line 201, in emit
  File "D:/2.5/build/inst/lib/python3.5/site-packages/UM\Signal.py", line 305, in __performEmit
  File "D:/2.5/build/inst/lib/python3.5/site-packages/cura\PrintInformation.py", line 122, in _onPrintDurationMessage
  File "D:/2.5/build/inst/lib/python3.5/site-packages/cura\PrintInformation.py", line 162, in _calculateInformation
ZeroDivisionError: float division by zero

**Comment by fieldOfView** [comment] 2017-03-30 19:17
Duplicate of #1582, fixed with #1586

**Closed** 2017-03-30 19:39 UTC
