### ISSUE TITLE
Slicing failed with unexpected error

### ISSUE THREAD

**Issue by harleyriderne1969** [Ultimaker/Cura#14251] opened 2023-01-09 13:11 UTC
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Ender 3

### Reproduction steps

Attempted to slice this print using my normal settings.  It fails each time.

### Actual results

I get the following error message.  Slicing failed with unexpected error.

### Expected results

Successful slicing

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10373371/cura.log)
[CE3E3V2_zebra.zip](https://github.com/Ultimaker/Cura/files/10373373/CE3E3V2_zebra.zip)

**Comment by MariMakes** [comment] 2023-01-09 14:26
Hey @harleyriderne1969,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

I was able to reproduce your slicing crash. 
But when I moved the model away from the center of the buildplate I was able to slice it succesfully!
![image](https://user-images.githubusercontent.com/40423138/211330649-08e17e25-7bd4-40ee-90fe-c53a45b64744.png)

I hope at least that helps you get unstuck. 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13643
We have a ticket on our backlog with the intent to improve this behavior.
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/13643

Thanks again!

**Closed by MariMakes** 2023-01-09 14:26 UTC
Labels: Type: Bug, Status: Triage
