### ISSUE TITLE
Cura crashes during preview

### ISSUE THREAD

**Issue by ecwhitney42** [Ultimaker/Cura#9543] opened 2021-04-09 11:04 UTC
### Application Version

4.8.0

### Platform

macOS 11.2.3, MacBook Pro 13" M1, 2020, 16GB RAM

### Printer

Creality Ender 3 Pro

### Reproduction steps

1. Loaded a large STL file
2. Sliced it
3. Clicked Preview

[Cura480BugReportFiles.zip](https://github.com/Ultimaker/Cura/files/6285161/Cura480BugReportFiles.zip)

### Actual results

I've attached two project and STL files that have caused a Cura crash during Preview. I have been able to preview other files that happen to be smaller prints although I don't have specific data to say that it's the size of the file that's the issue.

The program crashes before rendering the preview. Also, the Cura window gets filled with vertical strips of random color pixels.

The Cura log is attached.

### Expected results

I expected the preview to show the sliced model.

**Comment by nallath** [comment] 2021-04-09 15:08
Duplicate of #9542

**Closed** 2021-04-09 15:08 UTC
Labels: Status: Duplicate, Type: Bug
