### ISSUE TITLE
Unable to select and manipulate models with mouse

### ISSUE THREAD

**Issue by sdickson** [Ultimaker/Cura#11309] opened 2022-01-21 16:22 UTC
### Application Version

4.13.0

### Platform

MacOs 11.6.1 Big Sur

### Printer

Creality CR-10S

### Reproduction steps

1. Add a .stl model by either dragging the file to the app or clicking the directory icon and opening the model file.
2. Click it with the mouse in many places all around the model.

Also 
1. Right click the screen and select "select all models"
2. Click and drag to try and move or resize the model

### Actual results

The model is not selected or moved or resize.  The model is deselected. 

### Expected results

The model selects and is manipulated with the mouse without issue. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I have no file to upload, it's not crashing or having a slice issue.

**Comment by fvrmr** [comment] 2022-01-24 13:28
Closing this issue since it is probably a duplicate of https://github.com/Ultimaker/Cura/issues/9912

**Closed by fvrmr** 2022-01-24 13:28 UTC
Labels: Type: Bug
