### ISSUE TITLE
Missing layers

### ISSUE THREAD

**Issue by RobertDarmond** [Ultimaker/Cura#13467] opened 2022-10-04 04:33 UTC
### Application Version

5.1.0

### Platform

Windows 11

### Printer

Sidewinder X1

### Reproduction steps

Slice an object. STL file from Fusion 360

### Actual results

Layers was missing.
On the preview and when printing.

I try many times. I quit and reload Cura.
This append at random layers, in the base of the object.

gCode show no layer 3 (can't find "LAYER:3" in file) and Z jump from 0.36 to 0.60 (layer height is 0.12) :

G0 F300 X156.752 Y149.285 Z0.24
...
;LAYER:1
...
G0 F300 X156.66 Y150.733 Z0.36
...
;LAYER:2
...
G0 F300 X156.892 Y148.803 Z0.6
...
;LAYER:4

![Cura - Missing layers 1](https://user-images.githubusercontent.com/39325940/193734481-c41c4bc0-2cc1-4d43-a33c-63b6aa1dd3d2.jpg)

When showing preview, sometimes all the layers are shown plus lines going to the origin. On the picture below, the slider is on layer 18. Layers 17 and 19 show correctly.
![Cura - Missing layers 2](https://user-images.githubusercontent.com/39325940/193734497-7476350c-48c7-439f-b9f1-3230a0c2591b.jpg)

### Expected results

All layers printed.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Pique-Mais v4.zip](https://github.com/Ultimaker/Cura/files/9702791/Pique-Mais.v4.zip)

**Comment by MariMakes** [comment] 2022-10-04 10:08
Hey @RobertDarmond,

Welcome to the Ultimaker Cura Github 🚀 

I took a look at the file that you shared, and I can reproduce your empty layers.
But it does not seem to be an error in Cura. 

It seems that your mesh is broken.
The Mesh Tools Plug-in is indicating that your model is not watertight. 
You can get the plug-in here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

Do you still have the model in Fusion 360? 
Can you inspect the model in the part that shows the empty layers?
Can you check your export settings?

**Comment by RobertDarmond** [comment] 2022-10-05 05:21
Hello!
Thank you for your prompt response.

I have drop (and rebuild) the original model in Fusion. I only have the .stl file I sent to you.

If there is a problem in the model, I think it is not in the part that shows the empty layers in the base (witch is very simple) but in the other side of the object, near the pointed end. See layers 474 and 493.

You said "it does not seem to be an error in Cura".
But Cura generated a .gcode file with no warning and the print failed.
Fortunately, this print was not a very big one.
Cura should warn user. That is why I opened this issue.

What do you mean when you ask to "check the export settings" ?

**Comment by GregValiant** [comment] 2022-10-07 12:45
This is the view in Mesh Mixer.  The magenta colored areas show errors.  In this case there are only 2 errors but they include the whole model.
![image](https://user-images.githubusercontent.com/64202104/194554739-3004faf5-23c3-4e2b-9d5a-bd31cdac6e01.png)

Here is the model sliced.  The model on the right has been repaired in 3D Builder.  You can see that the layer is correct where the unrepaired model shows a floor there because a surface normal in inside out.
![image](https://user-images.githubusercontent.com/64202104/194555912-a1bbbe7b-62a4-43dd-a02b-057a07b1fdc6.png)

I don't see a bug here as the model is in error.  Once repaired the model slices as it should.  I'll leave the bug label on for now and you can respond here.

**Comment by madhephaestus** [comment] 2023-10-03 15:51
For reference, i just tested this model in Cura 5.4.0, and it slices correctly.

**Comment by GregValiant** [comment] 2023-10-03 21:15
@RobertDarmond if you load the Mesh Fixes Plugin from the MarketPlace a warning should come up.
Can we close this??

**Closed** 2023-10-18 00:16 UTC
Labels: Type: Bug, Status: Needs Info, Status: Under Investigation
