### ISSUE TITLE
cura displays text on the right side of the text box, cusing it to colied with the measurements units and be unreadable

### ISSUE THREAD

**Issue by ITSIK1231995** [Ultimaker/Cura#9750] opened 2021-05-02 10:08 UTC
### Application Version

4.9.0

### Platform

win 10

### Printer

anet A8

### Reproduction steps

on a windows machine running hebrew language, go to the print settings
https://ibb.co/XYB7CPy

### Actual results

the text is displayed on top of the units

### Expected results

text should be to the left of the units

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![33](https://user-images.githubusercontent.com/16593113/116809608-7a6e2a80-ab47-11eb-81dd-c56f574456fd.PNG)

**Comment by fvrmr** [comment] 2021-05-03 07:46
Hi @ITSIK1231995 thank you for your bug report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9667 that's why I will close this issue.

**Closed by fvrmr** 2021-05-03 07:46 UTC
Labels: Type: Bug
