### ISSUE TITLE
failure to slice

### ISSUE THREAD

**Issue by LordNobady** [Ultimaker/Cura#14040] opened 2022-12-13 17:58 UTC
### Application Version

5.2.1

### Platform

windows 10

### Printer

Neptune 3

### Reproduction steps

drop model in slicer, slice and than crash. 
[cura.txt](https://github.com/Ultimaker/Cura/files/10220731/cura.txt)
[N2_AEPCEF9 - 4x4 Thicket Road Corner.zip](https://github.com/Ultimaker/Cura/files/10220753/N2_AEPCEF9.-.4x4.Thicket.Road.Corner.zip)

Slicing it as my snapmaker 2 is working as it should. 
[S2A_AEPCEF9 - 4x4 Thicket Road Corner.zip](https://github.com/Ultimaker/Cura/files/10220773/S2A_AEPCEF9.-.4x4.Thicket.Road.Corner.zip)
[curasnapmaker.txt](https://github.com/Ultimaker/Cura/files/10220782/curasnapmaker.txt)

### Actual results

a notice that the slicing failed.

### Expected results

a sliced model

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

other models slice correctly for this printer.

**Comment by MariMakes** [comment] 2022-12-14 13:02
Hey @LordNobady,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

I encountered the same crash as you.
At first I thought it was related to the adaptive layers, but when I rotated the model by 45 degrees I was able to slice it successfully. I hope that helps you get unstuck
![image](https://user-images.githubusercontent.com/40423138/207601739-d1c43f5d-4b34-4356-8599-25d90388b171.png)

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13643
We have a ticket on our backlog with the intent to improve this behavior.
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/13643

**Closed by MariMakes** 2022-12-14 13:02 UTC
Labels: Type: Bug, Status: Triage, Slicing Error💥
