### ISSUE TITLE
Cura now very slow, update of my findings

### ISSUE THREAD

**Issue by j-snijder** [Ultimaker/Cura#13872] opened 2022-11-21 10:55 UTC
### Application Version

5.1.0 and 5.2.0 beta and 5.2.1

### Platform

Windows 11

### Printer

Ender 3pro

### Reproduction steps

changing settings in cura

### Actual results

cura slowing down drastically

### Expected results

Working smooth as in v5.0.0 ?

I used the Arachne beta and now remember that there the poblems did not occur as far as slowing down drastically.
I even had v5.0.0 installed and as far as I can remember that version did not have the bug also.

Hopefully it helps you too find the cause of the problem because I do not want to miss this wonderfull and very capable slicer.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

no files neede to upload

**Comment by MariMakes** [comment] 2022-12-01 14:01
Hey @j-snijder 

Thanks for your report 👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13820
We are investigating what is going on and how we can resolve it. 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/13820

**Closed by MariMakes** 2022-12-01 14:01 UTC
Labels: Type: Bug, Status: Triage
