### ISSUE TITLE
Export and slicing failing

### ISSUE THREAD

**Issue by WalletUpLLC** [Ultimaker/Cura#15801] opened 2023-06-19 00:54 UTC
### Cura Version

5.4.0 beta 1

### Operating System

Macbook pro, OS 13.4  Radeon Pro 560X 4 GB Intel UHD Graphics 630 1536 MB

### Printer

Creality K1, using Cura 5.4 

### Describe your model

car. it's the first time trying to slice.

### Add your .zip here ⬇️

[CCR6SE_untitled.3mf.zip](https://github.com/Ultimaker/Cura/files/11783007/CCR6SE_untitled.3mf.zip)

impossible to export. it keeps failing. Thanks

**Comment by WalletUpLLC** [comment] 2023-06-20 22:00
any updates?

**Comment by MariMakes** [comment] 2023-07-17 14:48
Hey @WalletUpLLC,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

This mesh seems faulty, I'm getting an error upon loading it.
We see this often with car models like this when they are exported from videogames. 

Have you tried doing a quick mesh fix with the Meshtools Plugin? 
You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that doesn't fix it you can try a more elaborate mesh fixer like https://myminifactory.github.io/Fast-Quadric-Mesh-Simplification/, or https://www.nanodlp.com/repair-3d-stl-file/.
Or you can use the "Make Solid" feature in AutoDesk MeshMixer. https://meshmixer.com/download.html

To me, it doesn't seem like a bug in Ultimaker Cura, since the mesh is faulty and Cura is not built to alter meshes in this way, that's what CAD software is for.

Apologies for any inconvenience caused by our delayed response. 
I'll be closing this issue. I hope you understand.

**Closed by MariMakes** 2023-07-17 14:48 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:, PreRelease :bug:
