### ISSUE TITLE
Embed Update info into Appimage

### ISSUE THREAD

**Issue by raycekar** [Ultimaker/Cura#8345] opened 2020-09-08 13:01 UTC
For when I used the binaries for 64 bit install, I get stuck at the start screen not able to pass the welcome screen.  Using the Appimage and I don't have any issues.  One request I have is if we embed the update information within the Appimage, we could leverage this tool to update the Appimage without having to download and replace.

https://github.com/AppImage/AppImageUpdate

**Comment by Ghostkeeper** [comment] 2020-09-10 09:31
I'm not sure what binaries you are speaking of there. We only release the AppImage to support Linux.

This is a duplicate of https://github.com/Ultimaker/Cura/issues/7834. Please continue the discussion there.

**Closed by Ghostkeeper** 2020-09-10 09:31 UTC
Labels: Type: New Feature
