### ISSUE TITLE
[4.5.0]Cura crashes when using multiple displays (screens)

### ISSUE THREAD

**Issue by Sahrio** [Ultimaker/Cura#7340] opened 2020-03-24 10:48 UTC
**Application version**
Ultimaker Cura 4.5.0

**Platform**
Win10
GPU: GeforceGTX970m
intel i7 6700HQ
16gbRAM
Two displays

**Printer**
Anet A8
Selected Custom FFF printer with the settings of an ANET A8

**Reproduction steps**
1. With the secondary display disconnected launch the Cura application.
2. Now connect the secondary display.
3.Drag the Cura window from main display to secondary display.
4.Close the Cura window on the secondary display.
5.Relaunch Cura

**Screenshot(s)**
![Captura de pantalla (16)](https://user-images.githubusercontent.com/61823525/77416477-2c271d80-6dc4-11ea-94c0-88e0f5ce07e5.png)
Cura launches correctly on the main display

![Captura de pantalla (17)](https://user-images.githubusercontent.com/61823525/77416481-2d584a80-6dc4-11ea-8836-69108005b1c9.png)
Dragging cura to the secondary display

![Captura de pantalla (18)](https://user-images.githubusercontent.com/61823525/77416483-2df0e100-6dc4-11ea-801a-e5d0292a9a8a.png)
Closing Cura in the secondary display

![Captura de pantalla (19)](https://user-images.githubusercontent.com/61823525/77416485-2e897780-6dc4-11ea-892f-d013f8bc7d26.png)
Launching Cura again

![Captura de pantalla (20)](https://user-images.githubusercontent.com/61823525/77416489-2f220e00-6dc4-11ea-925f-baeb2d59184d.png)
Cura crashes and never loads. Indeed, its somehow hard to get the "end process question" from windows to terminate the crashed app without going to the Task Manager.

**Actual results**
Cura crashes and stays blank

**Expected results**
Cura launches correctly on the secondary display.

**Project file**
Doesn´t matter. This happens even with no files being loaded.

**Log file**
(https://github.com/Ultimaker/Cura/files/4374692/cura.log)

**Additional information**
My main display and my secondary display dont have the same resolution nor ratio. I suppose the problem could be the different ratios, one is 16:9 and the other is 4:3.

**Comment by fieldOfView** [comment] 2020-03-24 10:57
As a workaround, in the General preferences there's an option "Restore window position on start". If you uncheck that, Cura will always start on the primary screen.

**Comment by Ghostkeeper** [comment] 2020-03-25 12:14
Duplicate of https://github.com/Ultimaker/Cura/issues/5651

**Closed by Ghostkeeper** 2020-03-25 12:14 UTC
Labels: Type: Bug
