### ISSUE TITLE
Profiles Issue

### ISSUE THREAD

**Issue by Jcoulter24** [Ultimaker/Cura#14955] opened 2023-03-19 05:26 UTC
### Application Version

5.3.0

### Platform

Windows 11

### Printer

FLsun Super Racer

### Reproduction steps

Load up application 

### Actual results

I get a failure to load profile backups but all profiles are there. Does not save from last settings used, it reverts to some random settings. I have to re-click the profile in order to get the correct settings to show. Profiles also do not update when trying to save current settings to current profile

### Expected results

When opening application, previously used settings should still be current. When saving settings to current profile, settings should be changed upon next application open

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This is screenshot of first load in with random settings I do not use, I have to click on the profile to reload the correct settings

<img width="1920" alt="Screenshot 2023-03-19 012320" src="https://user-images.githubusercontent.com/119092880/226155504-b159aa6e-ad24-4090-87c6-0abc573579ad.png">

**Comment by MariMakes** [comment] 2023-04-03 12:13
Hey @Jcoulter24,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 

I apologize, I'm having some trouble understanding your issue. 

Maybe these questions can help 
- Are settings changed from the default that you did not change?
- Do you often open old project files or project files from others? 
- Do you prefer to work on a new project or alter existing projects? 
- Do you often switch printers?
- What do you expect to happen when you load your back-up?

If your problem is that settings are not saved. 
Could it be a duplicate of https://github.com/Ultimaker/Cura/issues/13158?

If that doesn't clear it up could you share a video/screenshare of your problem?

**Closed** 2023-04-21 00:37 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage
