### ISSUE TITLE
Slicing fails after resizing "Parts for Calibration" extension

### ISSUE THREAD

**Issue by jdbeyers** [Ultimaker/Cura#10540] opened 2021-09-29 10:18 UTC
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Creality CR-10S

### Reproduction steps

I have "Calibration Shapes" version 1.3.3 by 5axes installed.
1. Select "Add a bed level calibration"
2. Scale it to 90%, with only "uniform scaling" selected
3. Click on "slice"
4. Slicing will then fail with an unexpected error
![image](https://user-images.githubusercontent.com/70121045/135249477-42d46da5-349c-4bd1-9658-81f1aea56ec2.png)

### Actual results

I can go no further with slicing

### Expected results

I should be able to slice the image and print it out

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.zip](https://github.com/Ultimaker/Cura/files/7251020/cura.zip)
[CCR10S_ill2.zip](https://github.com/Ultimaker/Cura/files/7251022/CCR10S_ill2.zip)

**Comment by nallath** [comment] 2021-09-29 10:53
Duplicate of #10394

**Closed by nallath** 2021-09-29 10:53 UTC
Labels: Type: Bug
