### ISSUE TITLE
Weight estimation not showing with UM2

### ISSUE THREAD

**Issue by zippy1978** [Ultimaker/Cura#1089] opened 2016-10-28 12:12 UTC
Hi,

I noticed that Cura 2.3 weight estimation does not work when using an Ultimaker 2.
Is there anything to fix that ?

Regards,
Gilles

**Comment by Ghostkeeper** [comment] 2016-10-29 01:10
I could reproduce this. It looks like a new bug!

**Comment by fieldOfView** [comment] 2016-10-29 07:37
There is some logic to the bug though. For the UM2, the material is set on the printer instead of in Cura. So Cura does not know the material, or the density of the material, and consequently it can not calculate the weight of the determined length of material.

I *think* 15.04 just assumed PLA for the UM2 weight calculation.

**Comment by nallath** [comment] 2016-10-31 08:22
Yea it did. It used PLA as defaults.

**Comment by Ghostkeeper** [comment] 2016-11-04 00:08
This was just classified by Ultimaker as a Won't Fix. So it's going to still say 0g, but please ignore it.

**Closed by Ghostkeeper** 2016-11-04 00:08 UTC
Labels: bug

**Comment by Dilbert1** [comment] 2017-04-30 15:04
Classified by Ultimaker as a Won't Fix?
...?
Is it sooo difficult to multiply the filament length with the weight per length?
Plugins like "Print Cost Calculator" dont work any longer since new api.
Or ist there an other alternative to get the weight without to calculate it myself?

**Comment by fieldOfView** [comment] 2017-04-30 17:53
> Is it sooo difficult to multiply the filament length with the weight per length?

Yes, it is. Because you select the material on the printer, Cura does not know the density of the material used. Without the density it cannot calculate the weight of the used material.

**Comment by Ghostkeeper** [comment] 2017-05-05 08:55
We could assume PLA again, but that is somewhat misleading.
