### ISSUE TITLE
Scaling Z axis changes Y axis percentage & more

### ISSUE THREAD

**Issue by GIJ0E** [Ultimaker/Cura#8122] opened 2020-07-29 16:32 UTC
**Application version**
4.6.2

**Platform**
Windows 10 Version 1903 Build 18362.959
Intel HD Graphics 520

**Printer**
Custom - MeCreator2

**Reproduction steps**
Selected the model, switched to the scaling tool, unchecked the Uniform Scaling checkbox, used the Z axis scaling coordinate on the model, changed scaling.
Noticed the Y axis percentage changes instead of the Z axis. Z axis mm changes appropriately and model scales appropriately.
Also...
Found that changing the Z axis mm changes the Y axis percentage.
Changing the Y axis percentage does not always correctly change the Y axis scaling. It also changes the Z axis percentage but does not scale the model's Z axis, looks like it multiplies it?
Reset also does not change the Y axis percentage back to 100%.

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
![image](https://user-images.githubusercontent.com/41352326/88826795-c80bd000-d18e-11ea-8d59-9953e00804e1.png)
![image](https://user-images.githubusercontent.com/41352326/88826859-d823af80-d18e-11ea-985b-2512ba044ac8.png)

**Comment by rburema** [comment] 2020-07-30 07:49
Have you rotated the model?

If so, probably yet another duplicate of #4136 , a longstanding issue that proved surprisingly tenacious.

**Closed** 2020-07-30 11:09 UTC
Labels: Type: Bug

**Comment by GIJ0E** [comment] 2020-07-30 13:09
I searched for an existing issue but failed to find #4136 
You're correct, it was rotated. My apologies for missing that detail.
Thanks!
