### ISSUE TITLE
Cura 4.13.0 Thin wall issue

### ISSUE THREAD

**Issue by DVSVIDEO** [Ultimaker/Cura#11320] opened 2022-01-23 15:05 UTC
### Application Version

4.13.0

### Platform

Windows 10 64bit

### Printer

Micromake C1 modified core xz printer

### Reproduction steps

Download this: https://www.thingiverse.com/thing:3845689
Load stl file: silica_Gel_Body on Cura
settings: PLA 0.4 Draft 0.2mm, 4 top, 4 bottom layer, 2 walls
press slice button

### Actual results

It uses a bottom or top infill instead of a thin wall.
The cura misrecognises the thin wall and uses bottom/top fill, which gives a strange result.
![Cura Thinwall on](https://user-images.githubusercontent.com/96373457/150684288-7a8806f8-eb9a-4ed9-a15b-2f052a362d79.jpg)

If I turn off the thin wall option, this part disappears from the model.
![Cura Thinwall off](https://user-images.githubusercontent.com/96373457/150684312-bc98bbd2-8989-4f6f-b28d-2401cddaeb25.jpg)

Here it is up close, without the layers above:
![Cura Thinwall closeup](https://user-images.githubusercontent.com/96373457/150684352-fb5e8154-2314-453f-9249-32b03447b965.jpg)

### Expected results

Correctly interpreted thin wall in SuperSlicer:
![SS thin wall](https://user-images.githubusercontent.com/96373457/150684815-1b8e8cc2-1b52-44d8-8ad3-bd5abd54fbf8.jpg)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[Silica_Gel_Body.zip](https://github.com/Ultimaker/Cura/files/7920707/Silica_Gel_Body.zip)

**Comment by fieldOfView** [comment] 2022-01-23 15:16
Try the Cura Arachne beta, which will do a better job at slicing thin walls:
https://ultimaker.com/learn/3d-printing-revolution-continues-second-beta-for-ultimaker-cura-arachne
This is a preview of the slicing improvements that will be part of Cura 5.0

**Comment by DVSVIDEO** [comment] 2022-01-24 14:22
> Try the Cura Arachne beta, which will do a better job at slicing thin walls:

I tried it, but I didn't like it.
The outer walls of the 20x20 test cube were not pretty. 4.13.0 gave a much nicer print.

**Comment by GregValiant** [comment] 2022-01-26 21:00
Can you post a 3mf file of your project (File | Save Project)?  I can't duplicate this in 4.12 or 4.13.
This is with my plain old regular settings.  Print thin walls is turned off.
![image](https://user-images.githubusercontent.com/64202104/151245972-3dc21767-4be1-4167-9212-535f5f322fc9.png)

**Comment by fvrmr** [comment] 2022-01-31 13:52
Hi @DVSVIDEO thank you for your report. Like @GregValiant I could also not reproduce your issue with the stl and reproduction steps.
Also @fieldOfView is right that thin walls are sliced better in Arachne since it uses variable line width.

**Comment by Ghostkeeper** [comment] 2022-02-01 09:48
The entire feature has been removed in favour of variable line width in Ultimaker/CuraEngine#1210 . We consider this fixed for the next release. If you are having trouble with the Arachne beta, we'd love to hear about those instead. That change is not going to get reverted.

This is effectively a duplicate of https://github.com/Ultimaker/Cura/issues/5110.

**Closed by Ghostkeeper** 2022-02-01 09:48 UTC
Labels: Type: Bug, Status: Needs Info
