### ISSUE TITLE
Cura 2.7 font issue on Print Setup panel

### ISSUE THREAD

**Issue by dinowchang** [Ultimaker/Cura#2462] opened 2017-09-20 14:42 UTC
The first 3 rows (lines) of Print Setup panel, "Quality", "Layer Height", and "Initial Layer Height" shown is abnormal (kind of squeezed).
After scroll down a little bit, the font will become normal.
My system is Win10, and the resolution of display is 1920x1200.

![screenclip](https://user-images.githubusercontent.com/15682038/30648296-598d19dc-9e50-11e7-902d-d724acacf478.png)

![screenclip 1](https://user-images.githubusercontent.com/15682038/30648713-47ca5e8e-9e51-11e7-8bff-6b3a65c2dd66.png)

**Comment by Ghostkeeper** [comment] 2017-09-25 08:32
It seems the text is not aligned to pixels.

I'm not able to reproduce this bug here though. Maybe it's all different because I'm on Linux and have a different screen size or DPI.

**Comment by waspinator** [comment] 2017-09-25 13:36
same issue on macOS Sierra. 

![](https://i.imgur.com/p0etqvml.png)

**Comment by ianpaschal** [comment] 2018-02-27 12:19
This will be fixed in the next release of Cura (3.3).

**Closed by ianpaschal** 2018-02-27 12:19 UTC
Labels: Platform: macOS, Type: Bug

**Comment by Ghostkeeper** [comment] 2018-03-20 14:21
The original issue should already be fixed for 3.0 for most places where it occurred.

**Comment by dinowchang** [comment] 2018-03-31 02:21
It is fixed in cura 3.3beta
