### ISSUE TITLE
2.6.2 ungrouping collections/milti-part STL's

### ISSUE THREAD

**Issue by PJParish** [Ultimaker/Cura#2145] opened 2017-07-22 23:16 UTC
I can see the option to do this but it is greyed out and the short cut keys do not work.  I used to be able to break an object apart or separate a collection of parts that had been exported out as a group.  This was a really useful option especially in conjunction with the Per Object Settings.  Can this be brought back?

**Comment by BagelOrb** [comment] 2017-07-23 11:27
Duplicate of https://github.com/Ultimaker/Cura/issues/2052

**Closed by BagelOrb** 2017-07-23 11:27 UTC
Labels: enhancement
