### ISSUE TITLE
Cura manages optical output and switches it to bluetooth mode

### ISSUE THREAD

**Issue by Lorthiz** [Ultimaker/Cura#10183] opened 2021-07-25 14:49 UTC
### Application Version

4.10

### Platform

Windows 10

### Printer

irrelevant

### Reproduction steps

1) Connetcted optical cable to soundbar with optical/bluetooth modes
2) Start Cura

### Actual results

Cura somehow switches soundbar mode to bluetooth for some unknown reason and by that turns off all PC sounds.

### Expected results

Cura does not change optical output on it's own

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

After switching it back manually using remote it still switches to bluetooth. Problem is gone the moment I turn off Cura and switch it back manualy.

Cura is printing/slicing software why does it mess with optical output?

**Comment by fieldOfView** [comment] 2021-07-25 15:40
If you don't use USB Printing from Cura, you can turn off the USB Printing plugin via the "Installed" tab of the "Marketplace". This will likely stop Cura from accessing hardware it has no business with.

**Comment by Lorthiz** [comment] 2021-07-25 15:45
@fieldOfView Just checked it and you were right it's fixed now. Thank you!
Since this is a plugin problem I am closing this issue.

**Comment by fieldOfView** [comment] 2021-07-25 16:02
This will likely be closed as a duplicate of #6836, which was marked as a duplicate of #5207

**Comment by fvrmr** [comment] 2021-07-26 08:26
I will close this indeed as a duplicate of #5207

**Closed by fvrmr** 2021-07-26 08:26 UTC
Labels: Type: Bug
