### ISSUE TITLE
Dragging cura to another monitor makes the UI look strange

### ISSUE THREAD

**Issue by rembii** [Ultimaker/Cura#10455] opened 2021-09-14 21:44 UTC
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Creality Ender-3

### Reproduction steps

1. I open Cura on my Labtob (screen is smaller, but higher resolution, than second Monitor)
2. I Drag the Window Over to my second mointor
3. Cura gets squished and just looks very weird

### Actual results

Cura gets squished and just looks very weird and is very zoomed on
![Screenshot 2021-09-14 233304](https://user-images.githubusercontent.com/84150447/133337179-e7fcc5e3-ae04-4b15-8903-54324f980f45.jpg)

### Expected results

The Program should scale like any normal Program

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I have a Surface pro 7 with a 12.3 Inch display and i have a 27 Inch Monitor
Attached is a video of my monitor

https://user-images.githubusercontent.com/84150447/133338078-70f3c187-83a8-4c3e-8cd4-1ef7fbabd2eb.mp4

**Comment by nallath** [comment] 2021-09-15 08:20
Duplicate of #8966

**Closed by nallath** 2021-09-15 08:20 UTC
Labels: Type: Bug, Status: Duplicate
