### ISSUE TITLE
[4.0] Support brim printing before skirt

### ISSUE THREAD

**Issue by xelprep** [Ultimaker/Cura#5760] opened 2019-05-19 23:49 UTC
**Application Version**
4.0

**Platform**
macOS 10.14.5

**Printer**
Creality Ender 5

**Steps to Reproduce**
Configure a print to start with a skirt and enable support brims

**Actual Results**
Support brim prints first, then the skirt is printed

**Expected results**
Skirt should print first to ensure the nozzle is primed and clean

**Additional Information**
When the support brim prints first, the nozzle might not be fully primed which leads to an incomplete support brim and failed supports

**Comment by Vandrasc** [comment] 2019-05-20 06:25
Hi @xelprep , this should be already fixed for 4.1. 

If you wish, for confirmation, you could give 4.1 Beta a try, save your current Cura user directory first. 

Let us know, thanks!

**Comment by Ghostkeeper** [comment] 2019-05-20 14:16
Duplicate of https://github.com/Ultimaker/Cura/issues/4829.

**Closed by Ghostkeeper** 2019-05-20 14:16 UTC
