### ISSUE TITLE
Layer 687 of print shows printed at Z=0 in preview

### ISSUE THREAD

**Issue by DuncanMcCain** [Ultimaker/Cura#10374] opened 2021-09-01 11:03 UTC
### Application Version

4.10.0

### Platform

Windows 10

### Printer

Creality CR-10 Mini

### Reproduction steps

1. Loaded model into Cura
2. changed orientation to be as shown in Cura
3. Sliced model
4. Previewed the model and saw the visual bug

### Actual results

1 layer (layer 687) seems to be displayed as printed a Z height of 0

### Expected results

The layer should not be displayed at a Z height of 0

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Cura_visual_layer_bug.zip](https://github.com/Ultimaker/Cura/files/7090482/Cura_visual_layer_bug.zip)

I have confirmed through OctoPrint that the bug is not persistent in the G-code, so it should not effect the print.

**Comment by fvrmr** [comment] 2021-09-02 08:36
Hi @DuncanMcCain thank you for your report. This is a duplicate of https://github.com/Ultimaker/Cura/issues/7412
We have a ticket on our backlog for this and it is indeed a visual bug. 
I will close this issue, since it is a duplicate.

**Closed by fvrmr** 2021-09-02 08:36 UTC
Labels: Type: Bug
