### ISSUE TITLE
Insta-crash whenever the "Scale" button is pressed in Preview Mode

### ISSUE THREAD

**Issue by Enrico-Fanelli-97** [Ultimaker/Cura#9743] opened 2021-05-01 14:15 UTC
### Application Version

4.9.0

### Platform

Zorin OS 15.3

### Printer

Creality Ender-3 Pro

### Reproduction steps

I'm running Cura directly from the AppImage downloaded on the official site on my Linux machine. 

1. Pressed the "Scale" button while in Preview mode

This happens with every STL file.

### Actual results

Cura crashes.

### Expected results

Not crashing.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

Cannot seem to find any log generated by Cura, instead here's the terminal output. After pressing the "Scale button" the last line is "Illegal instruction". [Log.txt](https://github.com/Ultimaker/Cura/files/6409696/Log.txt)

**Comment by fieldOfView** [comment] 2021-05-01 16:13
Duplicate of #9709, which incidentally also reports using Zorin OS

**Comment by fvrmr** [comment] 2021-05-03 12:12
Since it is a duplicate I will close this issue.

**Closed by fvrmr** 2021-05-03 12:12 UTC
Labels: Type: Bug
