### ISSUE TITLE
Crash during slicing

### ISSUE THREAD

**Issue by flashy63** [Ultimaker/Cura#13709] opened 2022-11-02 06:25 UTC
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Creality CR-10S Pro

### Reproduction steps

1. Opening the joined stl file (see screenshot for initial position)
2. Turning -90° around X-axis
3. Turning -90° around Z-Axis (see screenshot for final position)
4. Setting arborescent supports
5. Launch slicing

### Actual results

Cura start the slicing but, after a little moment (around 40% according to the progressbar), Cura crashed

### Expected results

Have a gcode file !

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9916816/cura.log)
[coude 160mm.zip](https://github.com/Ultimaker/Cura/files/9916826/coude.160mm.zip)
![Initial position](https://user-images.githubusercontent.com/39700112/199412928-cc59583d-e364-4500-be57-9f686a119f62.jpg)
![Final position](https://user-images.githubusercontent.com/39700112/199412929-1559754d-18c9-463d-af5c-47aedaa7b335.jpg)
[coude 160mm-stl.zip](https://github.com/Ultimaker/Cura/files/9916833/coude.160mm-stl.zip)

**Comment by GregValiant** [comment] 2022-11-03 12:47
Thanks for the report.
It sliced fine for me.  Your Cura log file shows "Backend exited abnormally with return code 3221225477!" which has been coming up on some installations.
This may be a duplicate of some other reports and I'll mark it as such.  The Cura team will take a look.

**Comment by MariMakes** [comment] 2023-02-23 14:38
Hey @flashy63,

Thanks for your report 👍

Return code 3221225477, is actually a super generic error, even though it doesn't sound generic 😅
In the Cura 5.3 Beta, we made a fix that should solve a number of these errors.
Can you download the Beta and retry your slice?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0-beta.1

If that's it still doesn't work, please let us know.

**Closed** 2023-03-10 00:40 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage, Slicing Error :collision:
