### ISSUE TITLE
Cura 4.9 & 4.10 : Unable to select the printer when printing over network to a host group

### ISSUE THREAD

**Issue by V3DPrinting** [Ultimaker/Cura#10162] opened 2021-07-21 10:07 UTC
### Application Version

4.9 & 4.10

### Platform

macOS 11.4

### Printer

Ultimaker S5

### Reproduction steps

I am using the "print over network" feature with a group of 3 printers were the host is an S5 and two UM3E printers connected to it.

After slicing the project, when you try to "Print over Network", the drop down list of the printer's selection is grayed.

![318309957_Capturedecran2021-07-12a15_50_06 thumb png 9f38c2428a8006e9d3c80522eefe5c16](https://user-images.githubusercontent.com/57400894/126471743-94e74496-5124-4f51-b254-49e4ed1a3f22.png)

The issue is present with a fresh install of Cura and latest FW for the S5

### Actual results

No printer selection available

### Expected results

The drop down list should allow the printer selection

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Refer to the topic in Ultimaker Forum
https://community.ultimaker.com/topic/37495-cura-49-410-unable-to-select-the-printer-when-printing-over-network-to-a-host-group/?tab=comments#comment-292533

**Comment by fvrmr** [comment] 2021-07-22 08:45
Hi @V3DPrinting thank you for your bug report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9734 and we have a ticket on our backlog for this.
I will close this one as a duplicate. Hope you understand.

**Closed by fvrmr** 2021-07-22 08:45 UTC
Labels: Type: Bug
