### ISSUE TITLE
[2.7] Profiles window shows incorrect information 

### ISSUE THREAD

**Issue by ChrisRiddell** [Ultimaker/Cura#2237] opened 2017-08-10 09:14 UTC
The profiles window shows all profiles with data from the last saved or created profile and not of its own

An image tells a better story see the speed 
![profile](https://user-images.githubusercontent.com/2055566/29163512-e30b97a8-7dfb-11e7-87c0-d4cd82dcf249.PNG)

**Comment by Ghostkeeper** [comment] 2017-08-23 22:36
Duplicate of https://github.com/Ultimaker/Cura/issues/2151

**Closed by Ghostkeeper** 2017-08-23 22:36 UTC
