### ISSUE TITLE
Files do not open in Cura

### ISSUE THREAD

**Issue by suryanisaac** [Ultimaker/Cura#12576] opened 2022-06-21 14:35 UTC
### Application Version

5.0.0

### Platform

Arch Linux x86_64, Kernel 5.18.5

### Printer

Creality Ender 3

### Reproduction steps

1. Open Cura
2. Go to File -> Open File

### Actual results

Nothing happens when the button is clicked

### Expected results

A file explorer should open to select a file

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

Interestingly, the same happens when trying to save an already sliced file.

However, dragging and dropping the file from a file explorer works, and selecting a file from the recently opened menu also works.
Saving to an external drive works as well.

[cura.log](https://github.com/Ultimaker/Cura/files/8949856/cura.log)

**Comment by nallath** [comment] 2022-06-21 15:16
Duplicate of #12266

**Closed by nallath** 2022-06-21 15:16 UTC
Labels: Type: Bug, Status: Triage
