### ISSUE TITLE
Update of the Ultimaker printer firmware

### ISSUE THREAD

**Issue by GabyChab** [Ultimaker/Cura#15737] opened 2023-06-13 12:20 UTC
### Application Version

5.3.1 / 5.3.0 / 5.0.0

### Operating System

W11 

### Printer

ultimaker S5

### Reproduction steps

I got several problem with my printer so I thought it was because of the old version of the printer firmware.
1. Parameter of the printer ( s5)
2. Update firmware
3. I've got a black screen

### Actual results

I previously updated the firmawre and in step 3. I had : chose a file from USB.
After that I take the file ( found in the Ultimaker website)  from my USB key and I transfert it to the printer. 
Now It's impossible. 

### Expected results

How I can update my firmware ? I don't have acess to digital factory or wifi config.
Thanks by advance ! 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I can provide the log file

**Comment by MariMakes** [comment] 2023-07-17 13:28
Hey @GabyChab,

Thank you for making separate tickets for separate problems. 
I'm sorry to hear you are stuck updating your firmware 😖 

As mentioned in https://github.com/Ultimaker/Cura/issues/15735, this is the Cura issue tracker. 
This seems like an issue with UltiMaker Hardware and Firmware.

You will get better (and faster) feedback if you contact our support channel.
If you have not done so, you can submit a ticket here: https://support.makerbot.com/s/contactsupport

To me, it doesn't seem like a bug in Ultimaker Cura.
Apologies for any inconvenience caused by our delayed response. 
I'll be closing this issue. I hope you understand.

**Closed** 2023-07-17 13:28 UTC
Labels: Type: Bug, Status: Triage
