### ISSUE TITLE
Slicing issue

### ISSUE THREAD

**Issue by noctas99** [Ultimaker/Cura#12570] opened 2022-06-21 03:13 UTC
### Application Version

5.0.0

### Platform

MacOS 12.4

### Printer

Hellbot Magna 2 Dual

### Reproduction steps

Loaded dual-colour .stl files
Selected each part for each extruder
Merged corresponding parts
Resized 200%
Pressed Slice

### Actual results

No slicing

### Expected results

Yes slicing

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[twoColor2_2_7_10_53_0hs00min.3mf.zip](https://github.com/Ultimaker/Cura/files/8945467/twoColor2_2_7_10_53_0hs00min.3mf.zip)
[cura.log.zip](https://github.com/Ultimaker/Cura/files/8945495/cura.log.zip)

**Comment by rburema** [comment] 2022-07-08 10:49
Whatever we did, it seems that we fixed it in the 5.1-beta already:
- I confirmed a crash in 5.0.0 with this model
- 5.1-beta will slice properly (takes a while though... expected since not a simple model)

Thanks for the report! It seems we don't have to do any action though and as such I'll be closing this.

**Closed by rburema** 2022-07-08 10:49 UTC
Labels: Type: Bug, Status: Under Investigation
