### ISSUE TITLE
Open Files dialog does not open.

### ISSUE THREAD

**Issue by changedsoul** [Ultimaker/Cura#12846] opened 2022-07-24 00:29 UTC
### Application Version

5.1.0-Linux-Modern  Appimage

### Platform

Arch Linux - 5.18.13

### Printer

Prusa MKS+

### Reproduction steps

Download Appimage,
Executed appimage,
tried to load a file from the folder icon, and thru the menu.

Drag and drop works to load files.

### Actual results

nothing happens when you try and load a file. No file dialog opens.

### Expected results

File dialog should open to allow you to select a file to load for slicing.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

Attached is my cura.log
[cura.log](https://github.com/Ultimaker/Cura/files/9174881/cura.log)
g

**Comment by Vandresc** [comment] 2022-07-25 09:39
Hi @changedsoul , I will close this as a duplicate of https://github.com/Ultimaker/Cura/issues/12266#issuecomment-1193803774.
Please check for more information on the linked ticket. Thank you!

**Closed by Vandresc** 2022-07-25 09:39 UTC
Labels: Type: Bug, Status: Triage
