### ISSUE TITLE
System Requirements for OS X.

### ISSUE THREAD

**Issue by thanarious** [Ultimaker/Cura#7414] opened 2020-04-05 08:14 UTC
I was pleasantly surprised when I read that even the latest (4.5) version of Cura only needs OS X 10.7 on Mac, since I have a MacBook 4,1 running 10.7.5 at home. However, installing that version on this computer doesn't seem to lead anywhere, Cura just crashes as soon as it launches. Is this a known issue? Anyone knows of the latest version that supports such an old OS?

I found version 2.3 to be working, but it still crashes randomly.

**Comment by MariMakes** [comment] 2022-11-01 12:48
Hey @thanarious,

Sorry, it took us a while to get back to you 😞 

We now have this support page explaining which operating systems we do and do not support.
https://support.ultimaker.com/hc/en-us/articles/360011889579

We plan to implement a fix soon where users will get a warning if their OSx is too outdated: https://github.com/Ultimaker/Cura/issues/13611

Apologies for any inconvenience caused by our delayed response. 
With improvements in place, I'll be closing this issue.

**Closed by MariMakes** 2022-11-01 12:48 UTC
Labels: Type: New Feature
