### ISSUE TITLE
Crash when loading any file (STL/GCode) - OpenGL issue?

### ISSUE THREAD

**Issue by spanzetta** [Ultimaker/Cura#8295] opened 2020-09-01 12:20 UTC
see attached screenshot and log file

[stderr.log](https://github.com/Ultimaker/Cura/files/5156122/stderr.log)

![crash](https://user-images.githubusercontent.com/49818743/91850613-1c0e4680-ec5e-11ea-9678-02982e61802a.jpg)

**Comment by fieldOfView** [comment] 2020-09-01 12:44
Duplicate of #8235 and #8230

**Closed** 2020-09-01 12:50 UTC
Labels: Type: Bug
