### ISSUE TITLE
Cura 3.1 can't import Cura 3.0 printers and profiles (MacOS High Sierra)

### ISSUE THREAD

**Issue by boksbox** [Ultimaker/Cura#2934] opened 2017-12-08 00:17 UTC
I just got the new Cura 3.1.

It has not carried over the old 3.0 printers and profiles. 
Import profiles can't find previous profiles as well

**Comment by ChrisTerBeke** [comment] 2017-12-08 08:56
High. Did you use the 3.1 beta before this?

**Comment by boksbox** [comment] 2017-12-08 12:08
No.  I just downloaded it when I got the email from Cura that the new 3.1 is out.

**Comment by ChrisTerBeke** [comment] 2017-12-08 12:36
@LipuFei

**Comment by LipuFei** [comment] 2017-12-08 12:46
@boksbox Which printer are you using? and could you send the profiles you want to import to us?

**Comment by boksbox** [comment] 2017-12-08 12:52
@LipuFei I'm using a RepRap Kossel Mini with repetier firmware.  The 3.1 managed to get the previous Materials profile but not the old print profiles and printer settings.  
Where can I find the old profiles?

**Comment by LipuFei** [comment] 2017-12-08 12:57
If you are on Windows, you can find them in `C:\Users\<your-username>\AppData\Roaming\cura`.

**Comment by LipuFei** [comment] 2017-12-08 12:59
Ah sorry... Forgot you are on Mac. I got lost between issues...
You can find it in `/Users/<your-username>/Library/Application Support/cura`

**Comment by boksbox** [comment] 2017-12-08 13:23
Ok, I'm already in /Users/<your-username>/Library/Application Support/cura folder.  Where do I find it? Can't find any file with .curaprofile extension.

![screen shot 2017-12-08 at 9 16 49 pm](https://user-images.githubusercontent.com/10462276/33767664-93055904-dc5d-11e7-86b1-d38e1a2b1474.jpg)

**Comment by LipuFei** [comment] 2017-12-08 13:25
They are not saved as `.curaprofile`. Could you upload your `3.0` and `3.1` folders? We can check what failed during the upgrade.

**Comment by boksbox** [comment] 2017-12-08 13:30
I tried uploading the .zipped folders, but they exceeded the 10mb limit here (72mb for the 2 folders)

**Comment by PianoMan2112** [comment] 2017-12-08 16:59
I have the same issue - if I import one of my saved exported custom material profiles, it says it imported, but does not show. (my 3.0 & 3.1 folders compress to 29 MB).

**Comment by LipuFei** [comment] 2017-12-11 10:12
@boksbox @PianoMan2112 This can be a bit confusing, but the material list only shows the materials that are compatible with the machine you have activated. Could this be the case?

**Comment by boksbox** [comment] 2017-12-11 10:25
As I mentioned, my previous machine's settings were not carried over but previously, I only had 1 material and this was carried over from 3.0 to 3.1.  I don't know about the other preset materials because I don't use them.

**Comment by LipuFei** [comment] 2017-12-11 12:36
@boksbox It must be the oversized log file. Could you try removing `cura.log` and `cache` and upload again? Thanks.

**Comment by boksbox** [comment] 2017-12-11 12:48
If I remove just the cache and cura.log they are still over 12mb when zipped. So...

Inside the 3.0 folder there are 2 folders named 2.0 and 15.04.6.  I also removed them together with the cache and cura.log

And in the 3.1 folder I did the same.  I left the 3.0 folder within but took out the cache and cura log inside this 3.0 folder as well.

Is that ok?

[3.0.zip](https://github.com/Ultimaker/Cura/files/1547794/3.0.zip)
[3.1.zip](https://github.com/Ultimaker/Cura/files/1547795/3.1.zip)

**Comment by LipuFei** [comment] 2017-12-11 13:09
@boksbox That's good! Thanks!

**Comment by LipuFei** [comment] 2017-12-11 13:49
@boksbox I made a fix for this c6cdc1d1dbb649b73e66d93fe8584cf57dfcb2cf. The problem is that, if you have a profile with special characters such as "%" in its name, the version upgrade will fail.

To fix this for you, some manual steps are required. You can follow the instructions below:
1. Download this ZIP file [fix_3.1_boksbox.zip](https://github.com/Ultimaker/Cura/files/1547989/fix_3.1_boksbox.zip)
2. You can find two files in this ZIP, those are the upgraded quality files of yours.
3. Copy and paste those two files into your `~/Library/Application Support/cura/3.1/qualities`, one of your "old" files will be overwritten and the other is new.
4. Try start Cura 3.1 again.

Hope this works for you.

**Comment by LipuFei** [comment] 2017-12-11 13:52
Hi @PianoMan2112 Could you provide more information on your issue?
1. Which machine are you using?
2. If possible, could you provide the profile you were trying to import?

Thanks

**Comment by boksbox** [comment] 2017-12-11 14:32
@LipuFei Thanks a lot. I did as you instructed.  
I managed to get the Slow 0% to appear on the Custom profiles but the rest from the previous 3.0 didn't make it.
![screen shot 2017-12-11 at 10 21 06 pm](https://user-images.githubusercontent.com/10462276/33835696-3e83cab6-dec2-11e7-9e87-f698f80c4910.jpg)

**Comment by DanalEstes** [comment] 2017-12-11 15:22
I converted from 3.0.4 to 3.1.0, via the "Ultimaker Cura-3.1.0-win64.exe" installer downloaded 12/10/2017.

All printers came forward.  All materials came forward. All customized print profiles did not. 

Several "Custom" printers (3rd party).   Windows 10 Home, V1703, Build 15063.726.

[cura.zip](https://github.com/Ultimaker/Cura/files/1548266/cura.zip)

**Comment by LipuFei** [comment] 2017-12-12 11:13
Hi @DanalEstes, I have manually recovered the custom qualities for you. You can download this ZIP [fix-DanalEstes-cura3.1-qualities.zip](https://github.com/Ultimaker/Cura/files/1551309/fix-DanalEstes-cura3.1-qualities.zip) and copy it to your `AppData/Roaming/cura/3.1/quality/` directory. Could you try that? Thanks.

**Comment by LipuFei** [comment] 2017-12-12 11:29
Hi @boksbox , somehow I can see your custom profiles after the Cura 3.1 upgrade. Here is a package of all the upgraded quality files [fix_boksbox_cura3.1_quality.zip](https://github.com/Ultimaker/Cura/files/1551373/fix_boksbox_cura3.1_quality.zip). You can try it out by copying and pasting to your `~/Library/Application Support/cura/3.1/qualities` directory.

**Comment by DanalEstes** [comment] 2017-12-12 13:34
Fantastic!  Thank you!

I was not anticipating such great service; I had mostly provided the zip of
the directory so that you folks could avoid this in the future.

Thank you once again,

Danal

**Comment by boksbox** [comment] 2017-12-13 00:29
@LipuFei, That did it!  Thank you very much!

**Comment by DanalEstes** [comment] 2017-12-13 01:25
And, Lipu Fei, that did the trick.  Worked perfectly.

I know I said "thank you" several times above... but... Thank You!

**Comment by LipuFei** [comment] 2017-12-13 09:22
@boksbox @DanalEstes 😄

**Comment by LipuFei** [comment] 2017-12-13 09:24
@PianoMan2112 I will close this issue for now. If you still have that issue, feel free to reopen it.

**Closed by LipuFei** 2017-12-13 09:24 UTC

**Comment by mzhu1113** [comment] 2017-12-13 17:43
Hello LipuFei,

I still have this issue and I've tried taking your changes and compiling it and shoehorning it into my App directory (Windows 10) and only 2 of my profiles make it into 3.1. All printers and materials upgrade properly.

Any help would be appreciated as I love the sound of the new features but I can't use them :(

Thanks!

I've attached both 3.0 which works fine and 3.1 which only migrated two profiles.
[3.0.zip](https://github.com/Ultimaker/Cura/files/1556426/3.0.zip)
[3.1.zip](https://github.com/Ultimaker/Cura/files/1556430/3.1.zip)

**Comment by LipuFei** [comment] 2017-12-15 07:31
Hi @mzhu1113 Sorry that I kept you waiting. Your recovered profiles are in 
[fix_3.1_quality_mzhu1113.zip](https://github.com/Ultimaker/Cura/files/1561918/fix_3.1_quality_mzhu1113.zip). Unpack the ZIP and copy-and-paste them to your `C:\Users\<your-username>\AppData\Roaming\cura\3.1\quality` directory. Your profiles should be back. :)

**Comment by LipuFei** [comment] 2017-12-15 07:33
@mzhu1113 Oh, and also remove those files named as "msu%2B-%2Bduplicator", which have those `%xx` escape characters.

**Comment by mzhu1113** [comment] 2017-12-16 14:37
Hey @LipuFei,

No worries. :) I appreciate the help. Not really strong in python programming but it was interesting when trying.

Much appreciated, the profiles are all back. Looking forward to the new features!

Thanks!

**Comment by PianoMan2112** [comment] 2018-01-02 01:54
@LipuFei I'm so sorry; I didn't see any replies and just happened to see these now.  My printer is a Monoprice Mini (relabeled Malyan M200), which isn't in the printer list, so I pick Custom.  The profiles I were trying to import should show in my old version as brand Hatchbox, a sample is:
      <brand>Hatchbox</brand>
      <material>PLA</material>
      <color>White</color>
      <label>White PLA</label>
Note: I had previously exported this as a material file; importing that file appears to do nothing in 3.1.

**Comment by laegion420** [comment] 2018-03-14 19:11
I'm having the same problem now with importing profiles from 3.0.4 into 3.2! Only one made it successfully into the new version.

How did you fix those files? Can someone fix mine for me or tell me how it's done?

**Comment by DanalEstes** [comment] 2018-03-14 20:40
Just for the record:  3.1 to 3.2 dropped all my profiles.  I chose to
rebuild them.

**Comment by laegion420** [comment] 2018-03-14 20:43
The nice part is that you can go to the profile storage location for the previous version and open the profiles in notepad and read all the settings out of them.

**Comment by ianpaschal** [comment] 2018-03-15 06:32
@laegion420 do you get an error popup when trying to import the profile?

**Comment by laegion420** [comment] 2018-03-15 06:36
Yes, I do.

**Comment by ianpaschal** [comment] 2018-03-15 08:08
@laegion420 ...and what does it say?
