### ISSUE TITLE
Fail at slicing for heads

### ISSUE THREAD

**Issue by JP060202** [Ultimaker/Cura#17457] opened 2023-11-28 01:16 UTC
### Cura Version

5.5.0

### Operating System

Windows 11

### Printer

Kingroon Kp3s

### Describe model location

Completely in the center of buildplate

### Describe your model

Two replacement heads for transformers, I printed them before, just don't know why its failing

### Add your .zip here ⬇️

[KK_Scourge revealed head.zip](https://github.com/Ultimaker/Cura/files/13482269/KK_Scourge.revealed.head.zip)

**Comment by 5axes** [comment] 2023-12-05 21:26
Duplicate : **Print Thin Wall** 
![image](https://github.com/Ultimaker/Cura/assets/11015345/fabb9bd2-713b-4f6c-a3c4-efa1eb23e4f2)

**Comment by JP060202** [comment] 2023-12-06 00:14
Thanks! 
I need to have the thin walls activated or deactivated?

**Comment by 5axes** [comment] 2023-12-06 07:12
Don't activate **Print Thin Walls**

**Comment by JP060202** [comment] 2023-12-06 16:41
Interesting, I've printed some models using thin walls yesterday, why does sometimes fails and sometimes doesnt?

**Comment by 5axes** [comment] 2023-12-06 17:30
Because some models have Thin Walls and Some don't and in some case slicing fails on this area if you activate Thin Walls. It's a Cura Issue and We hope that one day someone will take care of these issues.

**Comment by MariMakes** [comment] 2024-01-18 15:23
hI @JP060202,

Quick update from our side 👋
We are introducing a new tool to analyze slicing crashes like the one you reported. 💪

Even with the changes we made in the latest versions of Cura we still see that your model crashes. 🫤 But we have added your project file to our analyzing tool and found there were at least 8 crashes that were similar to yours, which helps us to narrow down what the cause is of your crash so we can resolve this for you and others.
Hopefully, we can find a solution soon 🤞

I'll be closing this issue as a duplicate but you can follow the progress here https://github.com/Ultimaker/Cura/issues/16417

**Closed by MariMakes** 2024-01-18 15:23 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:

**Comment by HellAholic** [comment] 2024-02-16 09:24
Small update,
Issue is resolved in CURA-11570 and will be part of the next Cura release.

**Comment by HellAholic** [comment] 2024-04-03 12:39
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
