### ISSUE TITLE
Cura 4.8 beta / 4.8 - strange wall slicing results

### ISSUE THREAD

**Issue by jarekdudzinski** [Ultimaker/Cura#8786] opened 2020-11-17 17:10 UTC
I'm having weird slicing results. All lines in this model are exactly 1.5mm width - modelled in Fusion. Tried my custom and default slicer settings with 0.5 line width.

Some of the lines are sliced as 2 external wall + 1 internal (as it should be), but some are having two very thin lines inside. This also generates weird fill on the corners, where the lines join.

![Screenshot 2020-11-17 at 17 59 44](https://user-images.githubusercontent.com/4148652/99422170-8d75a100-28ff-11eb-88bb-6b12f92c015b.png)

**Comment by jarekdudzinski** [comment] 2020-11-17 17:41
PS: in Prusa slicer it looks like this (correct, I think):
![Screenshot 2020-11-17 at 18 41 07](https://user-images.githubusercontent.com/4148652/99426550-8735f380-2904-11eb-8a54-fd4547349ea0.png)

**Comment by konskarm** [comment] 2020-11-18 15:48
Could you share the project file that reproduces this issue?

**Comment by jarekdudzinski** [comment] 2020-11-18 15:59
It's very simple - just 1.5mm lines intersecting. Attached below.
[Body7.stl.zip](https://github.com/Ultimaker/Cura/files/5561203/Body7.stl.zip)

**Comment by Ghostkeeper** [comment] 2020-11-19 09:35
Duplicate of https://github.com/Ultimaker/Cura/issues/6401.

Cura currently generates only even number of walls that loop around the border. Anything of exactly 1 line width or below is omitted and filled with gap filling instead (if enabled). A workaround is to reduce the line width by 0.001mm.
We also have a real fix in progress here: Ultimaker/CuraEngine#1210

**Closed by Ghostkeeper** 2020-11-19 09:35 UTC
Labels: Type: Bug

**Comment by jarekdudzinski** [comment] 2020-11-19 14:12
Ok, there IS some improvement using 0.499mm line width - but intersections still looks strange, and because of it printing time is ~30-50% higher. Plus, you have many more additional retractions.
It generates those double-triangles (with small dots for filling them). 
![Screenshot 2020-11-19 at 15 11 04](https://user-images.githubusercontent.com/4148652/99677065-97231400-2a79-11eb-8fe2-c427ebfd89b7.png)

**Comment by Ghostkeeper** [comment] 2020-11-20 10:36
Yeah, it will still print all walls as loops. So since they overlap by almost all of their width, you'd get overextrusion if Wall Overlap Compensation is not enabled. I'd also suggest to set Minimum Wall Flow to ~50% to prevent going over the same line twice with practically no flow. That would save a lot of time here.
