### ISSUE TITLE
Save to disk gcode does not put any file extention on for linux

### ISSUE THREAD

**Issue by protocolkey** [Ultimaker/Cura#14174] opened 2022-12-30 19:04 UTC
### Application Version

5.2.1

### Platform

Mint Linux cat 20.3

### Printer

Longer LK5 PRO

### Reproduction steps

Drag and drop STL onto platform, slice in generic PLA Standard Quality. save to linux disk with EXT4 partition.  older versions automatically added file extension.
screen shot of saving
![cura save bug linux ext4 partition](https://user-images.githubusercontent.com/20066261/210103594-79f08202-29ae-4eab-a1e3-0f823468d812.png)

Screenshot of file saved and a manual copy of the file and naming showing proper file extention
![cura save bug showing missing extention](https://user-images.githubusercontent.com/20066261/210103616-f093029f-538c-4cb5-8bdc-036aecfbd7b3.png)

### Actual results

Gcode file saved without extention, Gcode file seems fine and works as expected if extension is added.

### Expected results

Expect selected file type in dialog drop down to check and append proper extension if it does not already have it in the manual text box entry.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![cura save bug showing missing extention](https://user-images.githubusercontent.com/20066261/210104194-4560e806-8cd9-4a8e-9fec-1828c1dae24b.png)

![cura save bug linux ext4 partition](https://user-images.githubusercontent.com/20066261/210104198-4a52cee9-0c9b-4257-a46e-40e2fa026dde.png)

**Comment by MariMakes** [comment] 2023-01-05 12:18
Hey @protocolkey,

Welcome to the Ultimaker Cura Github 🚀 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12659
We've had multiple reports on this issue, we have a ticket on our backlog with the intent to improve this behavior.
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12659

Fingers crossed that we found a solution soon. 🤞

**Closed by MariMakes** 2023-01-05 12:18 UTC
Labels: Type: Bug, Status: Triage

**Comment by MariMakes** [comment] 2023-03-31 09:21
Quick update on our side. 

We might have a fix for this issue. 🎉 
It's a bit hard for us to test, but we have a nightly build available. 
Can you please try it out and let us know if it resolves your issue? 

[You can find the download links and the discussion here. ](https://github.com/Ultimaker/Cura/discussions/15098)
