### ISSUE TITLE
Possibly too complex? 

### ISSUE THREAD

**Issue by ultrasuperman1001** [Ultimaker/Cura#16914] opened 2023-10-09 03:05 UTC
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Ender 3 Pro

### Describe your model

I can slice with 3 of the models but it fails on 4

### Add your .zip here ⬇️

[complete_skeleton0h00m.zip](https://github.com/Ultimaker/Cura/files/12842426/complete_skeleton0h00m.zip)
My guess is there is too much movement but I've sliced more complicated things than this before

Also this isn't a high priority or anything, just trying to make Cura better

**Comment by GregValiant** [comment] 2023-10-09 10:28
Thanks for the report.
Each grouping has a few errors.
-> Analyzed your file:
--> 0 Naked edges (?)
--> 0 Planar holes (?)
--> 0 Non-planar holes (?)
--> 1 Non-manifold edges (?)
**--> 1 Inverted faces (?)
--> 40 Degenerate faces (?)
--> 2 Duplicate faces (?)**
--> 0 Disjoint shells (?)
-> Repairing: 100.00%
----- Repair completed in 12397ms ------
-> Vertex count changed from 46182 to 46205 (+23)
-> Triangle count changed from 92786 to 92852 (+66)

That really isn't too bad.  There is a bug in 5.4.0 that can keep models from slicing.
After repairing, moving, and rotating the models I got the 4 to slice.  The group wouldn't slice after simply repairing them.

I'll mark this as a duplicate of numerous previous reports regarding this behavior.  I'm going to close this one as the Cura team has a lot of examples of this happening.  I hope you understand.
![image](https://github.com/Ultimaker/Cura/assets/64202104/c00db03b-af7f-47f9-b847-b94421c62f8b)

**Closed by GregValiant** 2023-10-09 10:28 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error :collision:
