### ISSUE TITLE
Beta 5 — File Chooser does not open

### ISSUE THREAD

**Issue by bjornpijnacker** [Ultimaker/Cura#12196] opened 2022-05-14 08:47 UTC
### Application Version

5.0.0-beta+1

### Platform

Arch Linux 5.17.5-arch1-1

### Printer

Ender 3 Max

### Reproduction steps

1. Opened Cura 5.0.0-beta+1 using the AppImage from the release
2. Try to load a file from the "prepare" pane

### Actual results

File chooser does not open. Terminal logging where the app image is launched does not show any logging

### Expected results

The file chooser opens as it does in Cura 4.13.1

### Checklist of files to include

- [X] Log file
- [x] Project file

### Additional information & file uploads

The cura log is not different before and after pressing the file chooser button. It is as if the button simply does not do anything. The log file is included here: [cura.log](https://github.com/Ultimaker/Cura/files/8692584/cura.log)

**Comment by fvrmr** [comment] 2022-05-19 11:25
Hi @bjornpijnacker thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11874, so I will close this issue.

**Closed by fvrmr** 2022-05-19 11:25 UTC
Labels: Type: Bug
