### ISSUE TITLE
Cura 2.4.0: Error occurs While Temperature Setting at 0

### ISSUE THREAD

**Issue by plaplapla** [Ultimaker/Cura#1492] opened 2017-03-05 15:58 UTC
I prefer to preheat bed and nozzle manually. So I set both bed and nozzle temperature to 0. Now, error occurred. The printer would wait the nozzle to be "heated" to 0 degree. And the bed would be set at 0 degree soon. 

I checked the gcode file: "M109 S0","M140 S0" were at the very beginning of th file.
![image 001](https://cloud.githubusercontent.com/assets/4974333/23588919/7db8d99c-01ff-11e7-8642-9187d510fb7d.png)

![image 002](https://cloud.githubusercontent.com/assets/4974333/23588917/7db61d1a-01ff-11e7-87b7-9c30d1f2afe1.png)

![image 003](https://cloud.githubusercontent.com/assets/4974333/23588918/7db87236-01ff-11e7-855c-380fea39b658.png)

**Comment by Ghostkeeper** [comment] 2017-03-06 09:58
Duplicate of https://github.com/Ultimaker/Cura/issues/1209

**Closed** 2017-03-06 09:59 UTC
Labels: duplicate
