### ISSUE TITLE
Cannot import profile for Creality Ender 3 PRO

### ISSUE THREAD

**Issue by linuxjunkie999** [Ultimaker/Cura#6459] opened 2019-10-01 17:25 UTC
**Application version**
4.3.0

**Platform**
10.13.6 (17G8037)
iMac (21.5-inch, Late 2009)
14 GB 1067 MHz DDR3

**Printer**
Creality Ender 3 PRO

**Reproduction steps**
1. Add a printer: Ender 3
2. Add a custom profile provided by Creality for the Ender 3 PRO

**Actual results**
1. Be informed  "Failed to import profile from /Volumes/DataDUMP/3dprinterstuff/Ender-3  Pro/2.Software and USB Driver/CURA/Reference data/Ender-3 Pro.ini: Could not find a quality type normal for the current configuration."

**Expected results**
1. the profile would install ensuring the proper configuration for the printer.

**Additional information**
Im guessing that "standard" is the same as "normal" and if so then "standard" needs to be renamed to "normal".

[Ender-3 Pro Reference data.pdf](https://github.com/Ultimaker/Cura/files/3677701/Ender-3.Pro.Reference.data.pdf)

_".ini" not supported; file extension changed to ".txt" please pretend its .ini_
[Ender-3 Pro.txt](https://github.com/Ultimaker/Cura/files/3677708/Ender-3.Pro.txt)

![Screen Shot 2019-10-01 at 12 23 33](https://user-images.githubusercontent.com/19335109/65984902-59fb5d00-e446-11e9-8988-5cc25778cf22.png)

**Comment by Ghostkeeper** [comment] 2019-10-02 09:14
Duplicate of https://github.com/Ultimaker/Cura/issues/6453

**Closed by Ghostkeeper** 2019-10-02 09:14 UTC
Labels: Type: Bug
