### ISSUE TITLE
Solidworks "Export to Cura" plugin

### ISSUE THREAD

**Issue by FynDestiny** [Ultimaker/Cura#4480] opened 2018-10-04 20:21 UTC
**Application Version**

3.5.0

**Platform**

Win 10

**Printer**

Creality CR10S

**Steps to Reproduce**

clicked on "export" button in Solidworks….
![screenshot 62](https://user-images.githubusercontent.com/18093484/46500687-59bc8780-c81b-11e8-9ec6-40b880da153e.png)

**Actual Results**

![screenshot 61](https://user-images.githubusercontent.com/18093484/46500541-ff232b80-c81a-11e8-895c-48faa3c9a555.png)

**Expected results**

Expected my part to be loaded in to Cura

**Additional Information**

worked fine in 3.4.1

**Comment by ChrisTerBeke** [comment] 2018-10-04 20:34
Duplicate of https://github.com/Ultimaker/Cura/issues/4475.

**Closed by ChrisTerBeke** 2018-10-04 20:34 UTC
