### ISSUE TITLE
Cura 4.12.1 can type value with "."

### ISSUE THREAD

**Issue by pierremilcent** [Ultimaker/Cura#11162] opened 2021-12-30 10:05 UTC
### Application Version

4.12.1

### Platform

MacOS M1

### Printer

Artillery Sidewinder X2

### Reproduction steps

When i want to move or scale any object to a value with a ".", or a comma un french language for numbers, i cannot get it.

### Actual results

150.98 does not work i cannot type the "."

### Expected results

i would be able to type 150.98

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

nothing

**Comment by fvrmr** [comment] 2022-01-07 13:59
Hi @pierremilcent thank you for your report. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/10943 and this is because of your system locale. 
I will close this since it is a duplicate.

**Closed by fvrmr** 2022-01-07 13:59 UTC
Labels: Type: Bug
