### ISSUE TITLE
Missing overhangs on FLSUN Super Racer

### ISSUE THREAD

**Issue by drackp2m** [Ultimaker/Cura#11741] opened 2022-03-30 21:13 UTC
### Application Version

4.13.1

### Platform

macOS Monterey 12.3 (21E230)

### Printer

FLSUN Super Racer

### Reproduction steps

1. Install application
2. Slice a piece with overhangs

I tried installing previous versions and deleting the application configuration completely (in /Users/<user>/Library/Application Support/cura/<version>) and it still fails...

### Actual results

Bad result with FLSUN Super Racer
<img width="736" alt="imagen" src="https://user-images.githubusercontent.com/12443324/160929581-5da8c312-f544-4402-9ef0-c7b1de65f707.png">

<img width="757" alt="imagen" src="https://user-images.githubusercontent.com/12443324/160929639-dd243ccf-93f0-4c54-9dda-6d63fffa2dd1.png">

### Expected results

Works fine with FLSUN Q5 (for example)
<img width="661" alt="imagen" src="https://user-images.githubusercontent.com/12443324/160929817-54d27dd8-a56b-40c1-9239-de065a53e8cf.png">

<img width="722" alt="imagen" src="https://user-images.githubusercontent.com/12443324/160929850-752beaec-8210-4586-b566-fc11f9635b04.png">

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

The last test I did was deleting the application, then the configuration folder, reinstalling the program and configuring the printer, only changing the outer walls to 1 before cutting (so that the effect is more noticeable, but it happens with any number of walls and values in the rest of the settings).

And the problem occurs also on Linux (Ubuntu 21.10) and Windows 10

**Comment by fvrmr** [comment] 2022-03-31 09:08
Hi @drackp2m thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11553. For now you can change the `Maximum Skin Angle for Expansion` to 90. This is fixed for the next release.
I will close this issue since this is a duplicate.

**Closed by fvrmr** 2022-03-31 09:08 UTC
Labels: Type: Bug
