### ISSUE TITLE
Manual Entry Boxes for Rotation Values

### ISSUE THREAD

**Issue by BMarik** [Ultimaker/Cura#19011] opened 2024-05-03 12:26 UTC
### Is your feature request related to a problem?

Earlier versions of Cura allowed the manual entry of rotation values. These newer versions do not. This is particularly frustrating when a user is trying to minimize the seam line. 

### Describe the solution you'd like

Please reinstate the manual entry boxes for rotation values.

### Describe alternatives you've considered

There are no alternative solutions available. A user must spend hours rotating parts around their axis on the plate to place the part's seam in the best location.  I suppose I could uninstall the version of Cura and go back to the version from 2 or 3 years ago.

### Affected users and/or printers

All users will benefit from this reinstatement of the manual entry boxes.

**Comment by fieldOfView** [comment] 2024-05-03 12:41
Thanks for the request, but this is a duplicate of #17049. Please continue the discussion there.

**Closed by fieldOfView** 2024-05-03 12:41 UTC
Labels: Type: New Feature, Status: Triage
