### ISSUE TITLE
Speed overrides in materials

### ISSUE THREAD

**Issue by MarcusWolschon** [Ultimaker/Cura#1141] opened 2016-11-13 10:58 UTC
Some materials have maximum recommed printing speeds (bonus points for doing the same with travel speeds because a too large gap between printing and travel speeds will obviously cause quality issues).
This should be a part of the material profile to override the values from the printing profile
just like a maximum machine speed overrides the speeds in a printing profile that the machine is not capable of reaching.

**Comment by filipgoc** [comment] 2016-11-13 16:15
+1. I'm curious about this holistically. 
(Whether everything in material should override anything in quality https://github.com/Ultimaker/Cura/issues/1135)

**Comment by Ghostkeeper** [comment] 2016-11-14 02:47
The XML materials are not as powerful in what they can express as the rest of the profiles in Cura. Currently it defines only 7 settings (seen here: https://github.com/Ultimaker/Cura/blob/master/plugins/XmlMaterialProfile/XmlMaterialProfile.py#L532).This is because it was designed as an industry-wide standard.

We have plans to extend the profiles with a Cura namespace so that we can define our own settings in there.

**Comment by filipgoc** [comment] 2016-11-14 03:30
happy to hear the list is to be expanded a bit. 
(At least to add cool_fan_speed_max and cool_fan_speed_min (instead of just speed) etc. basically add categories of settings, instead of specific settings.)
(And I do agree with @MarcusWolschon that for many flexibles limiting max speeds make sense...)

**Comment by ChrisTerBeke** [comment] 2017-11-23 13:41
Do we want this? It might mean that something lower in the stack suddenly gets priority over something that's higher up in the stack?

**Comment by nallath** [comment] 2017-11-27 10:31
Preferably not. The data model is already complicated enough as it is.

**Comment by ChrisTerBeke** [comment] 2017-11-27 14:24
Agreed.

**Comment by fieldOfView** [comment] 2017-11-27 14:52
> It might mean that something lower in the stack suddenly gets priority over something that's higher up in the stack?

How would it do that? Please see (and preferably test) #2333, which implements the namespaced arbitrary cura setting concept mentioned by @Ghostkeeper. That enables setting speeds from the material profile. Any setting made there is neatly overridden by settings in higher containers (quality, quality changes and user). All fairly well behaved.

**Comment by ChrisTerBeke** [comment] 2017-11-27 15:13
@fieldOfView this behaviour is in the request of @MarcusWolschon ("This should be a part of the material profile to override the values from the printing profile"), which indeed goes against the whole stack setup so we probably won't do this. Loading Cura settings from an XML namespace is fine, but having them overrule the quality settings is not.

**Comment by fieldOfView** [comment] 2017-11-27 15:18
Right. It was getting confusing who was reacting to what.

**Comment by ChrisTerBeke** [comment] 2017-11-27 16:12
To be clear @MarcusWolschon: the request is to be able to set a maximum allowed printing speed in the material profile so that Cura gives a warning when a quality profile exceeds that value?

**Comment by Ghostkeeper** [comment] 2017-12-11 12:23
If we can set Cura's settings in material profiles we can override the maximum feedrate machine settings there.

**Comment by ianpaschal** [comment] 2018-02-27 15:53
Based on @nallath and @ChrisTerBeke's comments, I'm closing this.

**Closed by ianpaschal** 2018-02-27 15:53 UTC
Labels: Type: New Feature
