### ISSUE TITLE
Cant Drag and Drop

### ISSUE THREAD

**Issue by lartem12** [Ultimaker/Cura#12034] opened 2022-04-30 14:38 UTC
### Application Version

5.0.0 beta

### Platform

Windows 10

### Printer

Ender 3v2

### Reproduction steps

Can't drag and drop files to the plate neither from Windows explorer, Winrar or Total Commander

### Actual results

I tried to drop files, but it only shows the crossed circle mouse icon

### Expected results

Let me do the drag and drop stl-s.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

-

**Comment by Asterchades** [comment] 2022-05-01 03:12
Make sure you're not launching Cura as Admin - such as it will be launched from the installer. You can't drag-and-drop from a User task to an Admin one.

The alternative would be to launch your Explorer, WinRAR, or Total Commander as Admin, but it's generally not a good idea to run tasks as Admin unless absolutely necessary.

**Comment by fvrmr** [comment] 2022-05-02 08:45
Hi @lartem12 thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11937, so I will close this issue.

**Closed by fvrmr** 2022-05-02 08:45 UTC
Labels: Type: Bug
