### ISSUE TITLE
want extruder control function in monitor 

### ISSUE THREAD

**Issue by lyfbuaa** [Ultimaker/Cura#6320] opened 2019-09-07 14:49 UTC
There are no buttons to extrude/retract material.

request again,because  no reply in time and closed 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Affected users and/or printers**
 
**Additional context**

**Comment by Ghostkeeper** [comment] 2019-09-09 14:27
Well sorry, I'll close this as duplicate of https://github.com/Ultimaker/Cura/issues/6316 now. That ticket was re-opened. Don't be afraid to ask for tickets to be re-opened if necessary. We'll honour valid reasons.

**Closed by Ghostkeeper** 2019-09-09 14:27 UTC
Labels: Type: New Feature
