### ISSUE TITLE
[Feature Request] Rename object groups

### ISSUE THREAD

**Issue by goscicki** [Ultimaker/Cura#8590] opened 2020-10-22 00:34 UTC
**Is your feature request related to a problem? Please describe.**
The problem is that when you group multiple objects they get named "Group #1". This is ok, unless you have many groups, it is hard to find the correct group.

**Describe the solution you'd like**
Add a context menu item to rename the group.

**Affected users and/or printers**
Anyone who uses multiple objects in a print.

**Additional context**
![image](https://user-images.githubusercontent.com/49505154/96804237-71eca880-13dc-11eb-8667-aa8cfcb4a16d.png)

**Comment by konskarm** [comment] 2020-10-22 08:45
Hi @goscicki. This feature has been requested before. We already have a ticket in our backlog (devs see CURA-6798) to rename any objects in the object list (including groups), although it is not prioritized at the moment. I am closing issue as a duplicate of https://github.com/Ultimaker/Cura/issues/7116.

**Closed by konskarm** 2020-10-22 08:45 UTC
Labels: Type: New Feature
