### ISSUE TITLE
Multiply selected fails to create 1 extra copy

### ISSUE THREAD

**Issue by harjoat** [Ultimaker/Cura#12062] opened 2022-05-02 15:06 UTC
### Application Version

Beta 5.0

### Platform

Windows 10

### Printer

Creality Ender 5

### Reproduction steps

Right click model
Multiply Selected
Number of Copies : 1
Click Ok

### Actual results

No new copies are made, nothing happens.

### Expected results

One copy should be made so that there are 2 in total, the original and the copy.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No additional information should be required

**Comment by fvrmr** [comment] 2022-05-02 15:13
Hi @harjoat thank you for your report. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11894, so I will close this issue.

**Closed by fvrmr** 2022-05-02 15:13 UTC
Labels: Type: Bug
