### ISSUE TITLE
Support missing at the bottom due to stair stepping

### ISSUE THREAD

**Issue by abrooks-Accutime** [Ultimaker/Cura#6379] opened 2019-09-19 12:09 UTC
Cura does not add support where it needs support. This problem was also found in Cura 4.2.0 and Cura 4.2.1
![No Support](https://user-images.githubusercontent.com/55541098/65242656-9200b880-dab4-11e9-92e9-37c0a0db90d4.JPG)
![No Support 2](https://user-images.githubusercontent.com/55541098/65242662-95943f80-dab4-11e9-9166-6beecee5464e.JPG)

**Comment by nallath** [comment] 2019-09-19 12:40
Could you also share the model and the settings that you used to get this?

**Comment by abrooks-Accutime** [comment] 2019-09-19 12:51
Is there an email I can send this to since I don't want this model in the public?

**Comment by nallath** [comment] 2019-09-19 13:01
Sure, you can send it to j.vankessel@ultimaker.com

**Comment by nallath** [comment] 2019-09-20 07:43
I don't know what the problem is, but I've tried to slice it with 4.2 and 4.3 (although I am running it from source) with the profile that you provided. In both cases I got correct support:

4.2:
![Cura42Support](https://user-images.githubusercontent.com/3922611/65308649-d1013d80-db8a-11e9-99fc-f24f8993ef8d.png)

4.3
![SupportCura43](https://user-images.githubusercontent.com/3922611/65308754-060d9000-db8b-11e9-8dac-f69364ce9fd0.png)

I'm guessing you must have other changes than the ones you sent me. Could you share a project file of the setup where the issue occurs?

**Comment by abrooks-Accutime** [comment] 2019-09-20 12:06
Let me know if you can see the problem know. I don’t understand what going on here and how you can see the normal support.

Best Regards,

Andrew Brooks
Electrical Engineer

Accu-Time Systems, Inc.
175 West Road, Suite #4
Meadowview Plaza
Ellington, CT 06029
T. (860) 870-5000
D. (860)375-2028
Web: www.accu-time.com<http://www.accu-time.com/>
[ATS_logo_signature]

**Comment by Ghostkeeper** [comment] 2019-09-23 14:59
We were able to reproduce this issue last Friday. It turns out to be a bug related to stair stepping. We'll raise this and see if a fix can be made, but it won't make it for 4.3.

As a workaround, you can set the Support Stair Step Height setting to 0.

**Comment by cnfengjie** [comment] 2020-02-28 14:17
> We were able to reproduce this issue last Friday. It turns out to be a bug related to stair stepping. We'll raise this and see if a fix can be made, but it won't make it for 4.3.
> 
> As a workaround, you can set the Support Stair Step Height setting to 0.

Sorry anybody can help to explain if change “Support Stair Step Height‘’  to ‘0’, What will be impact? Can I rest assured change it?

**Comment by abrooks-Accutime** [comment] 2020-02-28 17:11
This issue has been fixed on Cura 4.5 Beta

**Comment by cnfengjie** [comment] 2020-02-29 12:28
> This issue has been fixed on Cura 4.5 Beta

Wow, good news, could you give me a download link？ I always don't know where I can get version update news or find new version~

**Comment by mahtDFR** [comment] 2020-03-02 11:52
Internal discussion on this here: CURA-6989

**Comment by abrooks-Accutime** [comment] 2020-03-02 13:02
cnfengjie,

I think I'm getting you confused to what my issue was at hand here. I had an issue where there will be no support from the build plate to the 90 degree overhang. All I know is if I have any issues with the new software, I would just go back to Cura version 4.1

**Comment by Ghostkeeper** [comment] 2020-03-03 12:27
I don't think this is fixed in Cura 4.5 yet. Our ticket on this is still open at least.

**Comment by nallath** [comment] 2020-06-22 07:42
Our internal ticket for this has finally been resolved. This should be fixed for 4.7

**Closed by nallath** 2020-06-22 07:42 UTC
