### ISSUE TITLE
Any open file function always not work.

### ISSUE THREAD

**Issue by ernestliou** [Ultimaker/Cura#12275] opened 2022-05-20 13:17 UTC
### Application Version

5.0.0

### Platform

Ubuntu 20.04

### Printer

CR-10s pro

### Reproduction steps

1.Click open file icon -> not work
2.Click top menu - open file -> not work
3.Press Ctrl-O -> not work.

### Actual results

Any open file function always not work to load file that I want to printing.

### Expected results

1.Click open file icon -> Work
2.Click top menu - open file -> Work
3.Press Ctrl-O -> Work.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

None.

**Comment by nallath** [comment] 2022-05-20 14:01
Duplicate of #12266

**Closed by nallath** 2022-05-20 14:01 UTC
Labels: Type: Bug
