### ISSUE TITLE
Slicing fails when using custom supports with large models

### ISSUE THREAD

**Issue by JarydBaker** [Ultimaker/Cura#15962] opened 2023-06-30 16:21 UTC
### Cura Version

5.4.0-beta.1

### Operating System

Windows 11

### Printer

Ender 3 V2

### Name abnormal settings

Print 1 at a time, gantry height

### Describe model location

No rotation allows it to print

### Describe your model

3 largish parts with custom supports. Without custom supports, the mesh is successful.

### Add your .zip here ⬇️

[CE3E3V2_Jabberwock body_wings.zip](https://github.com/Ultimaker/Cura/files/11918547/CE3E3V2_Jabberwock.body_wings.zip)

The model will mesh without custom supports, but fails when using custom supports.

**Comment by GregValiant** [comment] 2023-07-01 12:05
Thanks for the report and the file.
This won't slice for me either.  If I change the support cylinders to "Print as Normal Model" then it slices.
The Cura team will take a look.

**Comment by MariMakes** [comment] 2023-07-05 15:44
Hey @JarydBaker,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

I recognize this issue. 🕵️‍♀️
This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/15836, where using custom supports would result in a slicing crash. 

It's resolved in the 5.4 stable release, you can download the Cura version with the fix here: https://github.com/Ultimaker/Cura/releases/tag/5.4.0
I'll close this issue since it's a duplicate and resolved.

**Closed by MariMakes** 2023-07-05 15:44 UTC
Labels: Type: Bug, Status: Under Investigation, Slicing Error :collision:, PreRelease :bug:

**Comment by JarydBaker** [comment] 2023-07-05 15:50
Hi @MariMakes, thanks for the update, that is great to hear :).
