### ISSUE TITLE
Cura 5.0 could not reach Marketplace

### ISSUE THREAD

**Issue by BoBdBmstr** [Ultimaker/Cura#11852] opened 2022-04-21 19:36 UTC
### Application Version

5.0

### Platform

Windows 10

### Printer

Creality Ender 3 S1 Pro

### Reproduction steps

Try to open Marketplace for Plugins.

### Actual results

It says "failed to load Packages: could not reach Marketplace"

### Expected results

Plugins should be listet.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8534529/cura.log)

**Comment by nallath** [comment] 2022-04-22 07:41
Duplicate of https://github.com/Ultimaker/Cura/issues/11858

**Closed by nallath** 2022-04-22 07:41 UTC
Labels: Type: Bug
