### ISSUE TITLE
better handling of printers connections / usb ports / disconnections

### ISSUE THREAD

**Issue by pabloandresm** [Ultimaker/Cura#7266] opened 2020-03-11 19:29 UTC
Cura automatically connects to a printer on the USB port.

problems:
 - It is not possible to see which printer it is connected to.
 - It is not possible to disconnect from that printer except unplugging the usb cable.
 - And sometimes it is even needed to restart Cura in case we plug the printer after Cura started, because it did not detected it at the beginning.
 - it makes impossible to deal with more than one printer plugged to the computer
 - it makes impossible to handle multiple printers connected to the computer to different programs at the same time (like Cura for one printer to one USB port, and repetier to another printer on another USB port)

It would be nice to have a nice button next to the printer selection that allows to do "connect" and "disconnect" to a printer, like repetier has.

This would allow:
 - disconnect the printer port temporarily, freeing the printer to be connected from another program (like repetier, or even arduino serial monitor)
 - being able to connect different printers at the same time, and knowing which one we are using

and some other advantages

greetings

**Comment by Ghostkeeper** [comment] 2020-03-17 12:56
Duplicate of https://github.com/Ultimaker/Cura/issues/5207.

**Closed by Ghostkeeper** 2020-03-17 12:56 UTC
Labels: Type: New Feature
