### ISSUE TITLE
Weird Fonts in Settings

### ISSUE THREAD

**Issue by michaelgrossklos** [Ultimaker/Cura#10716] opened 2021-11-01 15:57 UTC
### Application Version

4.11

### Platform

Big Sur (M1)

### Printer

Elegoo Neptune 2

### Reproduction steps

1. Open Settings ([https://imgur.com/a/2dgSSz8](https://imgur.com/a/2dgSSz8))

### Actual results

Weird looking fonts in dropdown fields

### Expected results

Correct fonts

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Bildschirmfoto 2021-11-01 um 16 54 14](https://user-images.githubusercontent.com/6610580/139701490-52ca7cf4-4142-4cb3-a295-ab01b75d270d.png)
![Bildschirmfoto 2021-11-01 um 16 51 54](https://user-images.githubusercontent.com/6610580/139701497-32995b3d-25a5-40c8-a562-eff53469449a.png)

**Comment by fvrmr** [comment] 2021-11-01 16:11
Hi @michaelgrossklos thank you for your report. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/8993
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-11-01 16:11 UTC
Labels: Type: Bug

**Comment by julianCast** [comment] 2022-08-09 10:24
This is happening to me, but **without M1** chip model, only happening on Big Sur:

Application Version
4.11

Platform
Big Sur (Intel)
