### ISSUE TITLE
IMPORT materiaux

### ISSUE THREAD

**Issue by ghost** [Ultimaker/Cura#1818] opened 2017-05-11 21:41 UTC
Bonjour,
J'ai fais plusieurs fois importer le fichier PETG , ce dernier s'importe avec succès mais n’apparaît pas dans la liste des matériaux !
Pouvez vous m'aidez à résoudre le problème ? 
Cordialement MR ERIC.

**Comment by fieldOfView** [comment] 2017-05-12 08:04
The language spoken in the Cura github project is english. Also note that the issue-queue is not a support forum. Perhaps you can use the Ultimaker forums, they have a section for "other languages" too:
https://ultimaker.com/en/community/languages/other-languages

The people at that forum will need more information to help you: What version of Cura are you using, what printer, what OS?

**Comment by Ghostkeeper** [comment] 2017-05-12 09:39
The problem is probably that the PETG material that's being imported has a different diameter than the printer requires, or specifically says it doesn't support the printer.

**Comment by fieldOfView** [comment] 2017-05-12 09:42
>  that's being imported has a different diameter than the printer requires

That would only be the case if he's running master, since Cura 2.5 does no such filtering.

**Comment by BagelOrb** [comment] 2017-07-23 11:37
I understand it's fixed now.

**Closed by BagelOrb** 2017-07-23 11:37 UTC
Labels: bug
