### ISSUE TITLE
Z Hop Settings Error on Cura 4.2 with Ender 3 on Default Settings

### ISSUE THREAD

**Issue by MACRI20** [Ultimaker/Cura#6098] opened 2019-07-31 09:01 UTC
**Application version**

Cura 4.2
**Platform**

MacOS Mojave 10.14.6 (18G84)
**Printer**

Ender 3
**Reproduction steps**

Loading STL file and choosing the default slicing settings.
**Actual results**

An error message in regards to "Z Hop" settings. I then went into "Custom" and disabled Z Hop all together to see if this would help, but I get an error again, but this time it doesn't actually display what the issue is.
**Expected results**

I'm not sure as I am not really good at Cura, and just use the default slicing settings. I had to re-install 4.1 with the same STL file and got no issues this time around.
**Additional information**

**Comment by Ghostkeeper** [comment] 2019-07-31 09:49
Duplicate of https://github.com/Ultimaker/Cura/issues/6085.

**Closed by Ghostkeeper** 2019-07-31 09:49 UTC
Labels: Type: Bug
