### ISSUE TITLE
GUI Glitches

### ISSUE THREAD

**Issue by SConaway** [Ultimaker/Cura#3419] opened 2018-03-01 19:43 UTC
**Application Version**

3.2.1

**Platform**

Mac OS High Sierra Dev Beta 

**Display Driver**

**Steps to Reproduce**

Open Cura

**Actual Results**

Weird Glitches/ letters missing

**Expected results**

No letters missing

**Additional Information**

![screen shot 2018-03-01 at 11 39 59 am](https://user-images.githubusercontent.com/20807660/36865895-abce15ba-1d45-11e8-97a8-456cba82e19a.png)

**Comment by fieldOfView** [comment] 2018-03-01 20:19
Duplicate of #3277. That issue contains a link to an unofficial fixed version

**Closed** 2018-03-01 20:22 UTC
Labels: Status: Duplicate
