### ISSUE TITLE
Blobs and Micro jerks

### ISSUE THREAD

**Issue by Marcma1964** [Ultimaker/Cura#15259] opened 2023-04-16 12:41 UTC
### Application Version

5.3.0

### Platform

windows 11 / Klipper

### Printer

Ender 3

### Reproduction steps

tryed a project which was from Cura 5.2.1 and sliced it with 5.3.0.
The Gcode from 5.3.0 produces blobs and Jerks on the print.
Round parts of the print have some micro jerks which cause the blobs on the print.
Thougt at first  the filament was wet. But also with another filament same problem.

Same model sliced in Cura 5.2.1 do have no issues

Regards

Marcus

### Actual results

with 5.2.1 everything works fine

### Expected results

smooth print without blobs and no jerks

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE3PRO_FatDino_esun.zip](https://github.com/Ultimaker/Cura/files/11242273/CE3PRO_FatDino_esun.zip)
![1681648640145](https://user-images.githubusercontent.com/82822210/232311771-a7a3aade-cdcc-42ac-b531-519a25c3ab54.jpg)

**Comment by MariMakes** [comment] 2023-05-05 12:53
Hey @Marcma1964,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

@northcoastam, is correct! It's related to the ticket they mentioned. 

It seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/14811
We have one of our developers working on reducing the number of microsegments that are introducing this behavior. 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/14811
Thanks again, reports like this really help us to troubleshoot the issue.

**Closed by MariMakes** 2023-05-05 12:53 UTC
Labels: Type: Bug, Status: Triage
