### ISSUE TITLE
Layer view not showing

### ISSUE THREAD

**Issue by dadavis6011** [Ultimaker/Cura#2373] opened 2017-09-03 04:31 UTC
I just installed the new cura 2.7, and now when I want to look at my prints in layer view it wont re-slice it and only shows the grey outline of the object. Even as I adjust which layer height it's on, all it shows is that its on the 1st layer and nothing changed.
Thanks for the help!

**Comment by smartavionics** [comment] 2017-09-03 06:19
Hi, do you see a Prepare button in bottom right corner? If so, press that!

**Comment by dadavis6011** [comment] 2017-09-03 06:50
Thanks for the fast response, but no there is no Prepare button on my screen. I attached a picture of what my screen looks like on my end.
![capture](https://user-images.githubusercontent.com/31582069/30001142-2f95699c-9020-11e7-86e5-0a9d0612557c.PNG)

**Comment by smartavionics** [comment] 2017-09-03 06:53
OK, but if you now change one of the settings, does it show the prepare button instead of the save to removable drive button? BTW, I see that lots of people are having a problem with the save to removable drive feature on Windoze. Perhaps your problem is related to that?

**Comment by smartavionics** [comment] 2017-09-03 06:59
Or maybe there's a problem with the model? Can you post a link to it, please?

**Comment by dadavis6011** [comment] 2017-09-03 06:59
I change the infill density and it sliced it and know the layer view in showing up.
Thanks for you help!
![capture1](https://user-images.githubusercontent.com/31582069/30001166-7ac71aea-9021-11e7-9243-a1486b95a34c.PNG)

**Comment by smartavionics** [comment] 2017-09-03 07:00
OK, that's good. If you're happy, please close this issue. Bye.

**Comment by fieldOfView** [comment] 2017-09-03 12:02
I would still think this constitutes as a bug

**Comment by dadavis6011** [comment] 2017-09-03 19:16
It seams to only happen when I put a put a print in layer view after opening it and I haven't changed any print settings. It does eventually work when I change one of the print settings and it goes to re-slice it and then shows it in layer view. If this does constitute as a bug, how should I report this.

**Comment by smartavionics** [comment] 2017-09-03 19:22
Hello again. Well, just creating this issue is good enough, why don't you reopen it again and the devs will take notice.

**Comment by LipuFei** [comment] 2017-09-04 06:59
Hi @dadavis6011 , I cannot reproduce the problem... Could you send us your log file when it happens? And could you also create a project file out of it and send it to us?

**Comment by Ghostkeeper** [comment] 2017-09-10 14:48
This bug has existed for quite a long while now, but it only occurs very rarely and not at all when stress-testing. I've seen it in 2.5, 2.6, 2.7 and master (and perhaps earlier, but I don't remember). The problem is that we can't reproduce it when we need to, as it only happens like twice a week on a full work-week of working with Cura.

**Comment by Ghostkeeper** [comment] 2017-09-10 14:49
As a workaround, I typically drag the model up a bit above the build plate, then let it drop down automatically again. This triggers a reslice, and that will (99%) be working fine.

**Comment by ianpaschal** [comment] 2018-02-27 16:26
As an edge case bug in an old version, I'm labelling this `Won't Fix` and closing.

**Comment by Ghostkeeper** [comment] 2018-03-21 10:01
It's not an edge case and still happens today. It has been getting worse recently too!

**Comment by ScottyDoesKnow** [comment] 2018-04-29 05:05
I'm getting it constantly at the moment, even after reslicing. Are there any files I can share to help track this down?

**Comment by ianpaschal** [comment] 2018-05-23 08:43
As part of our new ticket handling strategy, we voted as a team on the likelihood of fixing this issue. Unfortunately, we’ve decided that we will not take time to fix it, and are marking it as `Status: Won’t Fix/Do` and closing the issue.

@ScottyDoesKnow We're really sorry you're experiencing it a lot but due to the rarity and randomness with respect to recreating it, it's basically impossible to code a fix without just getting blind dumb luck.

**Closed** 2018-05-23 17:52 UTC
Labels: Category: Cura, Category: CuraEngine, Type: Bug
