### ISSUE TITLE
slicing stl files generates as 0 minutes and no filament to be used.

### ISSUE THREAD

**Issue by shift838** [Ultimaker/Cura#10410] opened 2021-09-08 03:00 UTC
### Application Version

4.11.0

### Platform

Windows 10, 32gb ram, 1TB HD, Nvidia 1070Ti

### Printer

Ender 5+

### Reproduction steps

1. Executed install of 4.11.0
2. 4.11.0 install detected 4.9 and asked to remove.  Selected yes and ensured I did not delete my profiles for cura.
3. Opened up STL file in Cura 4.11.0 to print
4. Ensured all settings were still correct and 3D printer was still shown
5. sliced

### Actual results

Cura now shows the print will take 0 minutes and 0 amount of filament to be used.

### Expected results

Cura should calculate the time and filament appropriately and allow me to print.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[CE5P_Bed_Levelling.zip](https://github.com/Ultimaker/Cura/files/7125462/CE5P_Bed_Levelling.zip)

**Comment by nallath** [comment] 2021-09-08 15:42
You're printing an object that is 0.1 mm high with an initial layer height of 0.2. 

Change the height of the object to something above 0.2mm and it should work. Other than that, this is a duplicate of https://github.com/Ultimaker/Cura/issues/10394

**Closed by nallath** 2021-09-08 15:42 UTC
Labels: Type: Bug
