### ISSUE TITLE
2.7.0 BETA not start- Error message

### ISSUE THREAD

**Issue by Hoverhead** [Ultimaker/Cura#2245] opened 2017-08-11 04:58 UTC
Version: 2.7.0-BETA
Platform: Linux-4.12.4-041204-lowlatency-x86_64-with-debian-stretch-sid
Qt: 5.8.0
PyQt: 5.8.2

Exception:
Traceback (most recent call last):
  File "/build/2.7/build/inst/lib/python3/dist-packages/cura/CuraApplication.py", line 707, in event
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/Qt/QtApplication.py", line 261, in event
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/Event.py", line 189, in call
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/Signal.py", line 315, in __performEmit
  File "/build/2.7/build/inst/lib/python3/dist-packages/cura/Settings/ExtruderStack.py", line 94, in _onPropertiesChanged
AttributeError: 'NoneType' object has no attribute 'definition'

-------------------------
Thread 0x00007f1743fff700 (most recent call first):
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/Backend/Backend.py", line 155 in _storeStderrToLogThread
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 862 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f1760ff9700 (most recent call first):
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/Backend/Backend.py", line 147 in _storeOutputToLogThread
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 862 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f1761ffb700 (most recent call first):
  File "/tmp/.mount_b2YJ2l/usr/bin/plugins/plugins/USBPrinting/USBPrinterOutputDeviceManager.py", line 88 in _updateThread
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 862 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f17627fc700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 116 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f1762ffd700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 116 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f17637fe700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 116 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f1763fff700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 116 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f1780ff9700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 116 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f17817fa700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 116 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f1781ffb700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 297 in wait
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 1569 in wait
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 1153 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f17827fc700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 297 in wait
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 1569 in wait
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 1017 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f1782ffd700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 946 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f17837fe700 (most recent call first):
  File "/tmp/.mount_b2YJ2l/usr/bin/plugins/plugins/RemovableDriveOutputDevice/RemovableDrivePlugin.py", line 58 in _updateThread
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 862 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f1783fff700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 297 in wait
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 1569 in wait
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 1153 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f1798dd1700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 297 in wait
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 1569 in wait
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 1017 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f17995d2700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 946 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f179a619700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 297 in wait
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 1569 in wait
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 1017 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f179ae1a700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 946 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Current thread 0x00007f17c42df700 (most recent call first):
  File "/build/2.7/build/inst/lib/python3/dist-packages/cura/CrashHandler.py", line 100 in show
  File "/build/2.7/build/inst/bin/cura", line 45 in exceptHook
  File "/build/2.7/build/inst/lib/python3/dist-packages/cura/CuraApplication.py", line 676 in run
  File "/build/2.7/build/inst/bin/cura", line 73 in <module>
  File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load
  File "/build/env/2.7/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 21 in <module>
  File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load
  File "/build/env/2.7/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/__startup__.py", line 12 in <module>
  File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load

**Comment by Ghostkeeper** [comment] 2017-08-23 21:14
Duplicate of #2230. This has been fixed by now.

**Closed by Ghostkeeper** 2017-08-23 21:14 UTC
