### ISSUE TITLE
[3.3.1] Locked model still moved by other model

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#3628] opened 2018-04-06 13:02 UTC
**Application Version**
3.2.1

**Platform**
Linux Mint

**Printer**
UM3, UM2

**Steps to Reproduce**
* load model
* lock model
* load second model
* **load third model** (Edit!)
* move model over first model

**Actual Results**
first model is pushed free

**Expected results**
first model doesn't move

**Additional Information**
I have drop on build plate and keep apart enabled

**Comment by Ghostkeeper** [comment] 2018-04-30 10:45
Can't reproduce this bug. Whenever you move the second model over the first model, it only moves the second model outside of the first. The first stays in place (also when not locked).

**Comment by BagelOrb** [comment] 2018-04-30 11:34
![lock_model_bug](https://user-images.githubusercontent.com/8895761/39425311-0feca3c2-4c7b-11e8-8465-da1105746c96.gif)

**Comment by BagelOrb** [comment] 2018-04-30 11:36
3.3.0 AppImage:
![lock_model_bug_3 3 0](https://user-images.githubusercontent.com/8895761/39425375-70c54906-4c7b-11e8-9377-7a3e7257a1f6.gif)

**Comment by BagelOrb** [comment] 2018-04-30 11:38
3.3.0 project file:
*remove* extension
[lock_model_bug.curaproject.3mf.zip](https://github.com/Ultimaker/Cura/files/1960376/lock_model_bug.curaproject.3mf.zip)

**Comment by BagelOrb** [comment] 2018-04-30 11:39
The reproduction scenario needs a third model.

**Comment by diegopradogesto** [comment] 2018-05-09 11:30
That is still happening, even with just 2 models in the build plate. CURA-5347

**Comment by diegopradogesto** [comment] 2018-06-12 14:56
This issue is fixed in master now.

**Closed by diegopradogesto** 2018-06-12 14:56 UTC
Labels: Category: Cura, Status: In Progress, Type: Bug
