### ISSUE TITLE
Dark Mode Readable Text

### ISSUE THREAD

**Issue by ttyler3** [Ultimaker/Cura#13419] opened 2022-09-30 18:20 UTC
### Is your feature request related to a problem?

After updating from 4.X to 5.1, the dark mode makes reading certain text almost impossible. Dark gray against lightish gray has almost no contrast. Specifically, this is referring to the file name and dimensions of the model in the bottom left of the screen. When importing a .3mf file, the text is impossible to read/invisible.

### Describe the solution you'd like

Like the ETA, either put a black background on the bottom left text like it is on the right or change the left color/print bed colors so they have higher contrast. Also have the name of the imported .3mf displaying correctly.

### Describe alternatives you've considered

Light mode, which blinds my eyes.

### Affected users and/or printers

Everyone that uses dark mode (unless there is different colors for the printer beds, then just Ender printer users)

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/97608784/193332658-96211f05-d0ad-4d23-9451-0c623ab6ca65.png)
Can you easily read this??

Upon opening an existing .3mf file, you get this not readable text.
![image](https://user-images.githubusercontent.com/97608784/193334555-f8fbd845-a4d4-4335-a427-bb7fe6ce8aaf.png)

**Comment by MariMakes** [comment] 2022-11-01 13:32
Hey @ttyler3,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13615
We improved the behavior for mac users in Cura 5.2, but by accident not for windows users. 
We are discussing with the team how to improve this behavior.

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/13615

**Closed by MariMakes** 2022-11-01 13:32 UTC
Labels: Type: New Feature
