### ISSUE TITLE
[3.5] Random useless supports

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#4658] opened 2018-10-26 01:46 UTC
**Application Version**
3.5

**Platform**
Windows 10 x64

**Printer**
Cr-10s

**Steps to Reproduce**
Use supports

**Actual Results**
There are random supports which are not required

**Expected results**
There shouldn't be any wasted support

**Additional Information**
![useless support 2](https://user-images.githubusercontent.com/20385116/47539645-aa327c80-d8d1-11e8-8f9f-600033f8efc8.png)
![useless support](https://user-images.githubusercontent.com/20385116/47539646-aa327c80-d8d1-11e8-8397-03d1679478af.png)

[CCR10S wasted support3mf.zip](https://github.com/Ultimaker/Cura/files/2517310/CCR10S.wasted.support3mf.zip)

**Comment by rburema** [comment] 2018-10-26 14:48
Hi @Liger, Very likely a duplicate of #4606 and #4653 , please continue any discussion over there (the first one that is). cheers, Remco.

**Comment by Ghostkeeper** [comment] 2018-10-29 09:35
I can't reproduce the issue in this picture with your model. It's probably dependent on the exact positioning of the model.

Reinforcing that argument is that your model has a lot of extra geometry on the inside, which can confuse Cura as to which parts of your volume are inside and which side are outside.

![screenshot from 2018-10-29 10-33-09](https://user-images.githubusercontent.com/2448634/47641417-407ed080-db66-11e8-9873-988d882fa20f.png)

**Closed by Ghostkeeper** 2018-10-29 09:35 UTC
Labels: Status: Duplicate
