### ISSUE TITLE
Scale 

### ISSUE THREAD

**Issue by Sadesign823** [Ultimaker/Cura#6829] opened 2019-12-19 21:49 UTC
In the scaling window the windows of numerical input and input in percent are mixed up.
Version 4.3.0 for Mac.

**Comment by Ghostkeeper** [comment] 2019-12-20 10:01
I can't reproduce this problem. This is a screenshot of the scale tool panel showing the absolute size and the scale percentages.

![Screenshot from 2019-12-20 10-53-13](https://user-images.githubusercontent.com/2448634/71246498-11ea2900-2317-11ea-845a-8c8826db6f6f.png)

It doesn't look like there is anything mixed up. The scale is in the scale textboxes and the percentage is in the percentage textboxes.

Can you provide us with:
* Reproduction steps
* Expected behaviour
* Observed behaviour (and how it's different from expected behaviour)

We have an issue template that asks for these things but you've neglected that. It would help to solve this problem!

**Comment by GooodFr** [comment] 2019-12-30 20:12
Hello,

I have the same problem with 4.4.0 & 4.4.1 (never tried before) on PC

To reproduce the problem : 
 _ Import a file (I like so much the drag and drop 👍 )
 _ Rotate your object to 90°
 _ Unselect Uniform Scaling
 _ Change axis values
1) Some percent are not in front of the correct axis
2) If you correct the percent auto-modified, the other axis is modified ! ))

Regards ;)

**Comment by Ghostkeeper** [comment] 2019-12-31 13:59
Ah, yeah I understand then. This is a duplicate of https://github.com/Ultimaker/Cura/issues/4136. The 20th duplicate in fact :tada: We understand it's a big problem, but it's a very hairy problem to tackle. We've concluded now that the interface needs to be changed to make the scaling by percentage apply only to the current state and then reset to 100% after the scaling is completed.

**Closed by Ghostkeeper** 2019-12-31 13:59 UTC
Labels: Status: Needs Info
