### ISSUE TITLE
Cura 4.6.1 wont start on my computer

### ISSUE THREAD

**Issue by jsnake1489** [Ultimaker/Cura#7895] opened 2020-06-08 15:58 UTC
**Application version**
4.6.1

**Platform**
attaching DxDiag file

[DxDiag.txt](https://github.com/Ultimaker/Cura/files/4747105/DxDiag.txt)

**Printer**
(Which printer was selected in Cura?)
Creality ender 3 
**Reproduction steps**
opened the program
ran compatibilty mode in Win 8 which didnt work 

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
Application Continues to crash on opening

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**
application wont even open

**Log file**

[cura.log](https://github.com/Ultimaker/Cura/files/4747099/cura.log)

**Additional information**
(Extra information relevant to the issue.)

**Comment by jsnake1489** [comment] 2020-06-11 03:51
Awesome that fixed it right up and i'm back to work!

Thank you so much!

**Comment by Ghostkeeper** [comment] 2020-06-15 09:41
Okay, closing as a duplicate of #4427 then.

**Closed by Ghostkeeper** 2020-06-15 09:41 UTC
Labels: Status: Needs Info, Type: Bug
