### ISSUE TITLE
Instant shutdown

### ISSUE THREAD

**Issue by DKNicholson** [Ultimaker/Cura#9817] opened 2021-05-12 17:24 UTC
### Application Version

4.9.1

### Platform

Linux Mint Cinnamon

### Printer

Anycubic Mega S

### Reproduction steps

1. Imported a project as an .STL file
2. Able to print it without any alteration
3. Needed to re-scale object

### Actual results

As soon as I selected the object and clicked on the 'Scaling' icon on the left side, Ultimaker Cura instantly shuts down.

### Expected results

I should have been able to scale the object

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/6467989/cura.log)

This is the latest logfile - hopefully it will highlight the issue, but I have since used 4.8.0 in order the get the job done.

**Comment by smartavionics** [comment] 2021-05-13 06:50
For an alternative Cura release that has this problem fixed, see https://github.com/smartavionics/Cura/releases/tag/20210511

**Comment by fieldOfView** [comment] 2021-05-13 14:30
Duplicate of #9709

**Comment by fvrmr** [comment] 2021-05-14 07:26
Closing since it is a duplicate of #9709

**Closed by fvrmr** 2021-05-14 07:26 UTC
Labels: Type: Bug
