### ISSUE TITLE
Cura 4.8.0 not displaying tooltips when mouse hovering toolbar item on left side?

### ISSUE THREAD

**Issue by peta** [Ultimaker/Cura#8925] opened 2020-12-10 15:19 UTC
**Application version**
4.8.0

**Platform**
Win10 Enterprise 64bit; GPU = Intel HD Graphics 620 1GB (integrated; not very potent)

**Printer**
Ender 3 v2/pro

**Reproduction steps**
1. (Something you did.)
2. (Something you did next.)

**Screenshot(s)**
N/A

**Actual results**
When i move the cursor over a command icon in the left main toolbar (move, scale, translate asf.) no tooltip with the tool name is appearing.

**Expected results**
When i move the cursor over a command icon in the left main toolbar (move, scale, translate asf.) a tooltip with the tool name should be displayed

**Project file**
N/A; Indepedent of project file

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
N/A

**Comment by fieldOfView** [comment] 2020-12-10 15:26
Duplicate of #8914, #8324. Fixed in #8731.

**Closed** 2020-12-10 15:27 UTC
Labels: Type: Bug
