### ISSUE TITLE
Arrange without rotate

### ISSUE THREAD

**Issue by rophiroth** [Ultimaker/Cura#9382] opened 2021-03-08 16:41 UTC
### Is your feature request related to a problem?

Yes, since 4.8 arrange rotate objects, and for some proyects thats not optimal

### Describe the solution you'd like

option to disable auto rotation

### Describe alternatives you've considered

no necessary 

### Affected users and/or printers

cura v4.8

**Comment by fvrmr** [comment] 2021-03-09 10:50
Hi @rophiroth this is a duplicate of #8860 
We have a ticket on our backlog for this. 
Developers see CURA-7951

**Closed by fvrmr** 2021-03-09 10:50 UTC
Labels: Type: New Feature

**Comment by rophiroth** [comment] 2021-03-09 13:25
This issue dont have anything to do with #8860 ! please help.
