### ISSUE TITLE
Problem with options visibility

### ISSUE THREAD

**Issue by igordegteryov** [Ultimaker/Cura#6441] opened 2019-09-28 15:20 UTC
![Screenshot 2019-09-28 18-11-45](https://user-images.githubusercontent.com/45534952/65818651-16bda600-e21c-11e9-8936-7c26948719a3.png)
Version 4.3
OS Linux Mint 19.2
I've tried to change color scemes - without sucsess.

**Comment by Ghostkeeper** [comment] 2019-09-30 11:26
Duplicate of https://github.com/Ultimaker/Cura/issues/5296

Workaround for now seems to be to delete the folder `~/.cache/qtshadercache`. It seems that sometimes Qt creates a corrupt file there that causes this problem.

**Closed by Ghostkeeper** 2019-09-30 11:26 UTC
Labels: Type: Bug
