### ISSUE TITLE
Cura Ultimaker not opening after downloading. "Could not probe OpenGL"

### ISSUE THREAD

**Issue by gg1507** [Ultimaker/Cura#12526] opened 2022-06-15 02:01 UTC
### Application Version

5.0

### Platform

Windows 11

### Printer

Never got into Cura

### Reproduction steps

1. Download Cura from Ultimaker.com
2. Open Cura for the first time

### Actual results

A message comes up saying- Could not probe OpenGL. This program requires OpenGL 2.0 or higher. Please check your video card drivers.

![cura stuff](https://user-images.githubusercontent.com/107522119/173719529-2cc9ec82-88c8-4d0b-a6fd-693fc98fc6cd.jpg)

### Expected results

Cura should open. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![cura stuff](https://user-images.githubusercontent.com/107522119/173720377-f19b6275-034d-49b2-8972-e54fb98425af.jpg)

**Comment by nallath** [comment] 2022-06-15 07:38
Duplicate of #12359

**Closed by nallath** 2022-06-15 07:38 UTC
Labels: Type: Bug, Status: Triage
