### ISSUE TITLE
Cura misbehaves with an uncommon dual screen arrangement

### ISSUE THREAD

**Issue by fast2611** [Ultimaker/Cura#12306] opened 2022-05-22 13:31 UTC
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

I've got two different size screens using different element size settings in windows, in this arrangement.
![grafik](https://user-images.githubusercontent.com/104209844/169697461-10d79007-da94-4d78-af1d-853f48716d12.png)
Cura 4.13 did not have this issue.

### Actual results

Popups windows spawn in the "void" of no screens in the bottom right, thus being completly inacessible for all but the full screen size wide ones.
Cura also randomly switched from the correct UI element scale for the screen it was on to a significantly smaller one as has not reverted with system restarts

### Expected results

Cura needs to check if popups are inbounds and fully visible when creating them, or needs an option to be able to be locked to a single screen.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none needed

**Comment by usernametakenaaaa** [comment] 2022-05-29 20:56
At least it does not crash.
Try move the second screen down so the dialog can be rendered visibly, then it will crash.

**Comment by Vandresc** [comment] 2022-05-31 12:11
Thank you, @usernametakenaaaa, this is now on our radar. Duplicate of https://github.com/Ultimaker/Cura/issues/12102

**Closed by Vandresc** 2022-05-31 12:11 UTC
Labels: Type: Bug

**Comment by rburema** [comment] 2022-07-21 08:11
We're still investigating this. (So it we couldn't fix this in 5.1 yet unfortunately.) At present moment, we have two (other) leads, bot largely outside of our sphere of direct influence:

- A surprising connection was found to some particular audio drivers: https://github.com/Ultimaker/Cura/issues/12197#issuecomment-1157988232
- Found (and reported to) a possible bug in Qt, that might affect certain multi-monitor setups: https://bugreports.qt.io/browse/QTBUG-105070

**Comment by MariMakes** [comment] 2023-03-31 12:28
Quick update on our side,

We might have a fix for some of the issues reported here. 🎉
It's a bit hard for us to test, but we have a nightly build available.
Can you please try it out and let us know if it resolves your issue?

[You can find the download link and discussion here. ](https://github.com/Ultimaker/Cura/discussions/15098)
