### ISSUE TITLE
Cura 3.3.1 - Monitoring page temperature is not updating during heating phase

### ISSUE THREAD

**Issue by maikbooehme** [Ultimaker/Cura#3741] opened 2018-04-27 11:35 UTC
Application Version

3.3.1

Platform

Windows 10

Printer

I3 pro B 

Issue: 
During the pre-heating phase of each print, the temperatur for the extruder and the bed is not update , like it was in 3.2.1

**Comment by Razolayer** [comment] 2018-05-03 23:55
Same here!

**Comment by VanessaE** [comment] 2018-05-19 18:31
Happens for me also.  Makes it look like the program or printer communication is hung up.

**Comment by Ghostkeeper** [comment] 2018-06-27 14:59
Can confirm. Also reproduced for me.

**Comment by diegopradogesto** [comment] 2018-06-29 13:13
I was wondering if this PR https://github.com/Ultimaker/Cura/pull/3855 may fix this...

**Comment by PeskyWabbit** [comment] 2018-07-04 23:32
Can confirm, happens to me as well. It does start printing when it's up to temp, but theres not telling how close it is to being up to temp or if it's even heating or not.

**Comment by ianpaschal** [comment] 2018-08-16 08:31
We think this is fixed but unfortunately we can't test it since we only have Ultimaker 3s/S5s in the office. I'm going to close this but if anyone can confirm that the bug exists in 3.4.1, I'll reopen it and mark it as deferred.

**Comment by fieldOfView** [comment] 2018-08-16 08:34
UMO+ and UM2(+) are no longer supported then?

**Comment by ianpaschal** [comment] 2018-08-16 09:45
They are but we're unable to recreate them on those printers, therefore, we think it's fixed, but are unable to check if that's also the case on an i3...

**Comment by ianpaschal** [comment] 2018-08-16 09:47
But to be perfectly honest, we have one working UM2 and one half-working UMO in Cura team, so no, they're not really a priority for us.

**Comment by pentar25** [comment] 2018-09-12 07:15
Temperature still isn’t updating on 3.4.1. Seems like it’s hung with no way to tell. Particularly frustrating with two extruders

**Comment by pentar25** [comment] 2018-09-14 05:58
Update, this appears to only happen when connected via USB. when connected via octoprint everything seems to be perfectly in sync.

**Comment by alekseisasin** [comment] 2018-09-28 13:58
Thank @fieldOfView, he fixed this issue. I want to ask somebody to test this fix. For this purpose, I made **not stable** Cura build. It is only for testing purposes.
The download link is available for 7 days.
https://wetransfer.com/downloads/6ecbe5af589a4d32736a156001df5e2a20180928134317/2c53ab5ce1c1ea32d694a7320c87add920180928134317/aedf1a

**Closed** 2018-10-03 08:35 UTC
Labels: Category: 3rd-Party, Category: Cura, Type: Bug
