### ISSUE TITLE
Include update information in AppImage build

### ISSUE THREAD

**Issue by marcsekz** [Ultimaker/Cura#13669] opened 2022-10-27 07:38 UTC
### Is your feature request related to a problem?

I really don't like downloading new AppImages whenever Cura has a new update

### Describe the solution you'd like

It would be very nice if the AppImage build included update information metadata, so that the AppImage update tool (https://github.com/AppImageCommunity/AppImageUpdate) could be used to update Cura. I think this would be the easiest to implement out of all possible auto-update solutions.

### Describe alternatives you've considered

I have been downloading new versions manually, very inconvenient. Another solution could be that Cura itself does automatic update.

### Affected users and/or printers

All linux users

**Comment by MariMakes** [comment] 2022-11-01 14:00
Hey @marcsekz 

Welcome to the Ultimaker Cura Github 🚀 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13182
We have a ticket on our backlog with the intent to improve this behavior.
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/13182

**Closed by MariMakes** 2022-11-01 14:00 UTC
Labels: Type: New Feature
