### ISSUE TITLE
To keep lateral adhesion continuity between "infill-skin-wall"

### ISSUE THREAD

**Issue by physicsimulation** [Ultimaker/Cura#10947] opened 2021-11-28 15:44 UTC
### Is your feature request related to a problem?

Some users target precision and print outer wall before any other "section" with optionally followed (or not) by Inner wall.
Some others, like me, prefer structural stiffness and target optimal Infill (w/wo wall), then Walls (inner then outer (with inset).

Both of us have concerns about lateral adhesion continuity between Infill (w/wo extra wall), "top-underlying" Skin (w/wo extra wall) and Outer wall (w/wo inner wall(s), independently of Wall Ordering, in Arachne).

That continuity is broke by the "top-underlying" skin that is always printed after Infill and Wall.

Note: Top-Underlying Skin or Skin in Top/Bottom section, I know juxtaposing top and underlying is "special" but ...

### Describe the solution you'd like

Having an option that enable the user to sequence printed parts with lateral adhesion continuity. For example :
 - For precision :
1) Outer wall, 2) Inner walls, 3) Expanded skin walls, 4) Expanded skin, 5) Infill walls, 6) Infill
 - For structural stiffness :
1) Infill, 2) Infill walls, 3) Expanded skin, 4) Expanded skin walls, 5) Inner walls, 6) Outer wall
With variable width center (or inner) last wall that glue wall cordon and fill any gaps in one pass.

Also, adding this option, would give secondary (automatic?) option to adapt layer printing sequence for each adjacent layer when vertical surface is concave or convex to improve overhang, in conjonction with adaptative layer height. Kind of Adaptive printing sequence ?!

### Describe alternatives you've considered

My printer is very well hard and soft calibrated.
I give a try and test to Prusa but I rapidly return to Cura convenience.
I am used to print between 20% to 80% with adaptive layer height and between 102.5% to 125% cordon width (upon line type) to ensure optimal lateral adhesion.
BTW, I return from Prusa to Cura mainly because to your adaptive layer height algorithm.
Now, you target adaptive cordon width to optimize lateral adhesion and optimizing both extrusion-time.

It's time to prepare the next feature, "Adaptive Layer Printing Sequence", ALPS

### Affected users and/or printers

Those who adhere to lateral adhesion 8)

**Comment by fvrmr** [comment] 2021-12-03 12:52
Hi @physicsimulation thank you for your feature request.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/6734 and we have a ticket on our backlog related to this.
Please add your ideas to this issue, so we keep everything in one place!

I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-12-03 12:52 UTC
Labels: Type: New Feature
