### ISSUE TITLE
Support parameters not settable per mesh

### ISSUE THREAD

**Issue by KOUBeMT** [Ultimaker/Cura#6767] opened 2019-12-06 13:36 UTC
**Application version** 
Cura 4.4.0

**Platform**
Windows 10 pro

**Printer**
eMotionTech Strateo3D

**Reproduction steps**
In Strateo3D.def.json I modified the "settable_per_mesh" value from false to true of several parameters, mainly support parameters. I did this for test reasons, only in our workshop (not pushed)
"support_interface_material_flow": { "settable_per_mesh": true },
"support_roof_material_flow": { "settable_per_mesh": true },
"support_bottom_material_flow": { "settable_per_mesh": true },
I also did this for Support interface density (roof and bottom) and support distances (top & bottom).
The idea was to print many test parts with different support parameters to find out the best ones.

**Something you did next.**
In Cura4.4.0 I was able now to modify for each part/mesh the parameters listed above. I noticed that it takes lot of processing power and many times Cura crashed!
I finnaly managed to set them all and sliced (turned off many processes running on my PC).

**Actual results**
Surprisingly cura didn't take the overrides into account when slicing.
Meanwhile other parameters like support top & bottom distances were taken into account and overriden in the slice process, but not the rest of those listed before...

**Comment by Ghostkeeper** [comment] 2019-12-09 10:51
So the `settable_per_mesh` and such are only indicating what the front-end should display. CuraEngine will still [get the setting value from the support extruder](https://github.com/Ultimaker/CuraEngine/blob/e40ac1c6c322a464805d49c3ddd450bcec54e740/src/settings/PathConfigStorage.cpp#L186) (or the support interface extruder, support roof extruder or support floor extruder). So if you make it settable per model and then change this value for one model, CuraEngine will ignore that override in the per-model settings.

The reason for this is that the support algorithm doesn't run separately for each model. It'll generate overhang areas for each model separately (and as such the overhang angle can be different for each model) but the support areas are merged for all models together. This is necessary for functionality like Support Join Distance. And then each of the support zones get their appropriate flow rate. We can't have part of a polygon being printed with different settings than another at the moment. By that time we've long forgotten which part of which polygon belongs to which model(s).

We've always tried to allow changing settings as specifically as possible. The only real exceptions are some of the settings that only make sense per model, such as whether the model is printed as infill mesh or not which cannot be set per extruder in the sidebar.

So this is expected behaviour. Sorry! These settings can't be changed per mesh.

**Closed by Ghostkeeper** 2019-12-09 10:51 UTC
Labels: Type: Bug
