### ISSUE TITLE
Unsupported small features

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#6585] opened 2019-10-25 17:39 UTC
This is a general problem of how we handle support and infill.
Cura designates areas to fill with support and filling it with some density of support structure, but that approach fails for small overhang protrusions.

There is no easy fix for this. This issue can only be solved by rethinking our infill and support systems. I don't expect this issue to be closed any time soon.

Example for infill:
The skin generated for these dice dot cutouts is wholly unsupported and creates stringing:
![image](https://user-images.githubusercontent.com/8895761/67591421-b4de5680-f75d-11e9-8cf0-fd60d64700e6.png)
[dice_models.zip](https://github.com/Ultimaker/Cura/files/3773116/dice_models.zip)

Example for support:
Because of the Z distance an outline will get generated, but still those outlines are unsupported.
![image](https://user-images.githubusercontent.com/8895761/67591897-c3793d80-f75e-11e9-8912-a6d0765efcbf.png) 
![image](https://user-images.githubusercontent.com/8895761/67592412-f243e380-f75f-11e9-84f7-c47cae46cf61.png)
[axes_models.zip](https://github.com/Ultimaker/Cura/files/3773128/axes_models.zip)

related: https://github.com/Ultimaker/Cura/issues/5440
credits: https://www.reddit.com/r/3Dprinting/comments/dmzib2/prevent_filter_or_warn_about_extrusions_into_thin/

**Comment by BagelOrb** [comment] 2019-10-25 17:43
**Physical problem:**
Such unsupported regions causes spaghetti which will get wiped off on some unknown location. It's undefined printer behavior. Who knows what mischief the spaghetti might cause.

Moreover, the missing print feature will cause defects on further layers above.

**Comment by BagelOrb** [comment] 2019-10-25 17:44
**Impact**
I believe that small holes and small protrusions in horizontal faces are quite common in engineering applications.

**Comment by Ghostkeeper** [comment] 2019-10-30 10:52
Duplicate of https://github.com/Ultimaker/Cura/issues/6001

**Closed by Ghostkeeper** 2019-10-30 10:52 UTC
Labels: Category: Engine, Type: Bug
