### ISSUE TITLE
Slicing fails in 5.2.1, but slices fine in 4.4.1

### ISSUE THREAD

**Issue by jasonrohrer** [Ultimaker/Cura#14079] opened 2022-12-18 17:19 UTC
### Application Version

5.2.1

### Platform

Ubuntu 20.04.5 LTS

### Printer

Ultimaker S3

### Reproduction steps

1. Open Cura 5.2.1
2. Load the project.
3. Slice

### Actual results

Slice fails with Unexpected Slicing Error

### Expected results

This slice works fine in 4.4.1 (which is the repository version of Cura in Ubuntu 20.04.5 LTS).

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[UMS3_pretty3DTree_slicer_bug.zip](https://github.com/Ultimaker/Cura/files/10254327/UMS3_pretty3DTree_slicer_bug.zip)
![Screenshot from 2022-12-18 12-18-09](https://user-images.githubusercontent.com/12563681/208310846-066b4edd-9252-4926-aa4b-1ce9fdc608f5.png)
[cura.log](https://github.com/Ultimaker/Cura/files/10254334/cura.log)

**Comment by jasonrohrer** [comment] 2022-12-18 17:24
Other notes:

If you scale it to 200% (instead of 300%), the slice completes successfully and quickly.

If you scale it to 400%, it takes FOREVER (like... 20+ minutes before I give up and kill it?)  It's too slow to be usable, especially for such a simple model.  I never waited for it to finish, so I'm not sure if it eventually reaches a slicing error or not.

In 4.4.1, all scales (200%, 300%, and 400%) complete successfully and quickly with PVA supports.

This model also slices fine in FlashForge's FlashPrint slicer.

**Comment by MariMakes** [comment] 2022-12-20 13:35
Hey @jasonrohrer,

Thanks for your report and the extra investigation👍
This looks like a super complicated model 👀 
I'm super curious what it's used for. 

![image](https://user-images.githubusercontent.com/40423138/208678251-25af41b4-1eca-436c-ae8f-214ff381a77d.png)

This mesh seems faulty
Have you tried doing a quick mesh fix with the Meshtools Plugin? 
You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

I also noticed that I am able to slice the model if I rotate it by 180 degrees and move it away from the center.
In your case it might also speed up the printing time if you move it close to the switching bay 😉 
![image](https://user-images.githubusercontent.com/40423138/208679342-9d226eb4-9003-4cd5-875a-197e607f0867.png)

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13643
We have a ticket on our backlog with the intent to improve this behavior.
It has to do with rounding errors, and that is probably why you are seeing different behavior with different sizes. 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/13643

**Comment by jasonrohrer** [comment] 2022-12-21 01:33
Thanks!

I knew that this might be a dupe... just wanted to report another example, just in case.

It's a sculpture that serves no purpose other than looking interesting.

And yes, there are "errors" in the mesh.... it's output from Structure Synth, and is composed of overlapping cubes.

However, slicers generally seem to be okay with errors like this.  Cura usually handles it just fine.

**Comment by jellespijker** [comment] 2023-01-17 16:50
@MariMakes this is unreleated to #13643 it crashes in an other area of the code.

[support.cpp#L1297](https://github.com/Ultimaker/CuraEngine/blob/701e72c0012544d60d35c653f35a9a623a289cc1/src/support.cpp#L1297)

I will reopen this ticket

**Comment by Vandresc** [comment] 2023-01-30 14:57
Slices perfectly for me in the latest main build. Will close for now, please re-open if the issue still persists for you.

**Closed by Vandresc** 2023-01-30 14:57 UTC
Labels: Type: Bug, Slicing Error :collision:
