### ISSUE TITLE
Cura 5.0-beta1 - Spiralize outer contour (vase mode) not working

### ISSUE THREAD

**Issue by MikeGlue** [Ultimaker/Cura#11926] opened 2022-04-24 03:12 UTC
### Application Version

5.0.0-beta1

### Platform

Windows 11

### Printer

Ender 3 v2

### Reproduction steps

1. Import attached "pineapple-vase" STL
2. Enable 'Spiralize Outer Contour' and slice

[pineapple-vase.zip](https://github.com/Ultimaker/Cura/files/8548970/pineapple-vase.zip)

### Actual results

The model is sliced with a lot of inner elements that should not be there.  

See pic below:

![Screenshot 2022-04-23 230956](https://user-images.githubusercontent.com/5204734/164954612-930f946b-4cc6-4d8b-9f32-ab02c86f6f00.png)

### Expected results

Only the outer wall should be printed, as shown below when the same STL is sliced in Cura 4.13.1:

![Screenshot 2022-04-23 231150](https://user-images.githubusercontent.com/5204734/164954676-5f396875-d0ac-4653-a3b4-74a1528d43e4.png)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

..

**Comment by smartavionics** [comment] 2022-04-24 06:43
Try enabling "remove all holes".

**Comment by fieldOfView** [comment] 2022-04-24 06:47
... but don't forget to turn it off again when you are done.

**Comment by fvrmr** [comment] 2022-04-25 12:44
Hi @MikeGlue thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11843 and we have a ticket on our backlog for this. 
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2022-04-25 12:44 UTC
Labels: Type: Bug
