### ISSUE TITLE
Adaptive layers responding to angle changes too late

### ISSUE THREAD

**Issue by lwbsbde** [Ultimaker/Cura#4470] opened 2018-10-03 19:52 UTC
the adaptive layers are changed too late

the adjustment of the layer thickness would have to start 2-3 layers sooner

![screenshot 2](https://user-images.githubusercontent.com/43827576/46437184-084cc380-c75b-11e8-8ddc-b46cebf11259.png)

**Comment by ChrisTerBeke** [comment] 2018-10-03 20:01
Please post your question/issue in English so all the developers can read it.

**Comment by ChrisTerBeke** [comment] 2018-10-04 15:01
This is caused by the engine not looking very far ahead when calculating the layer heights (which is done before almost all other calculations). Changing this behavior would be quite a challenge.

**Comment by Ghostkeeper** [comment] 2021-11-30 10:32
This is being tracked through https://github.com/Ultimaker/Cura/issues/6641. Even though this feature request was earlier, I'll close it in favour of the other which has more information now. We're also tracking this in Ultimaker's internal Jira tracker as CURA-7026 (but only Ultimaker employees can see that).

**Closed by Ghostkeeper** 2021-11-30 10:32 UTC
Labels: Type: Improvement, Category: Engine, Status: Deferred
