### ISSUE TITLE
Cura 4.13.1 Top surface when monotonic enabled.

### ISSUE THREAD

**Issue by frankygoop** [Ultimaker/Cura#11537] opened 2022-02-23 22:03 UTC
### Application Version

4.13.1

### Platform

Windows 11

### Printer

Tevo Tarantula

### Reproduction steps

With monotonic enabled, not sure if can be reproduced. only happened on layer 148. The last layer is 150. 

Attached Gcode. go to layer 148.

I also recorded a video https://we.tl/t-7EK7KwkhVe

### Actual results

I believe previous versions did it ok. I just realized after updating to 4.13.1, when monotonic top is enabled, the head move back and forth jumping from one end to another and not printing. 
It is difficult to explain. I recorded a video. The first portion is with the monotonic enabled. the second half is disabled and printing fine. 
I noticed only happened on layer 148. the last layer is 150.

### Expected results

Print continuously along the wall path as normal, not jumping back and forth.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[TT_Africa v7.zip](https://github.com/Ultimaker/Cura/files/8128035/TT_Africa.v7.zip)

**Comment by fvrmr** [comment] 2022-02-24 09:40
Hi @frankygoop thank you for your report.
I think this is a duplicate of https://github.com/Ultimaker/Cura/issues/11401 
Are you using zigzag as top/bottom pattern?

**Comment by frankygoop** [comment] 2022-02-24 18:44
yes, ZigZag.

**Comment by fvrmr** [comment] 2022-02-25 08:10
Then I will close this as a duplicate.
You can change the pattern in Lines and it shouldn't happen.

**Comment by frankygoop** [comment] 2022-02-25 20:31
Dear Fvrmr, Sorry for my confusion with the infill pattern. 
I confirm the mentioned issue is happening with Top/Bottom Pattern in Lines.

**Comment by Ghostkeeper** [comment] 2022-03-12 18:42
Perhaps you could share a project file of that happening, then? You can save a project file with File -> Save Project. It allows us to reproduce the model and the settings you're using.

**Comment by frankygoop** [comment] 2022-03-14 16:28
I attached the project in the first post, go to layer 148. thanks

**Comment by fvrmr** [comment] 2022-03-16 15:21
The attached file is a gcode, to save a project file: file - save project and share it here as a .zip.

**Comment by Vandresc** [comment] 2022-10-14 07:29
Fixed in 5.2.

**Closed** 2022-10-14 07:29 UTC
Labels: Type: Bug
