### ISSUE TITLE
Cura mouse control is offset

### ISSUE THREAD

**Issue by dannystaple** [Ultimaker/Cura#2470] opened 2017-09-22 20:40 UTC
Environment: Windows 10
Cura Version 2.7.0
Display Resolution: 1920x1080

There is something off when interacting with Cura on Windows 10. The controls that are highlighted/clicked do not line up with where the mouse pointer actually is. 

What is odd here - is near the vertical centre of the screen, the control under the mouse hotspot highlights, and can be selected, as you move further from this, up or down, the alignment gets further off away from the centre. 

Possibly related - the "Create Profile" dialog has the name control mostly above the visible area - you cannot see anything but the bottom few pixels of that text control.

**Comment by fieldOfView** [comment] 2017-09-23 07:35
Duplicate of #2068. See https://github.com/Ultimaker/Cura/issues/2068#issuecomment-324917547

**Closed** 2017-09-26 08:51 UTC
