### ISSUE TITLE
Still getting blobs/zits on curved surfaces

### ISSUE THREAD

**Issue by harishrajan96** [Ultimaker/Cura#15813] opened 2023-06-19 17:40 UTC
### Application Version

5.4.0-beta.1

### Operating System

Windows 11

### Printer

Ender 3 V2 Neo (Sprite Direct Drive) + Klipper

### Reproduction steps

Ran two benchy prints with Cura 5.4.0 beta and Prusa 2.5.2, Sliced a standard benchy. Settings were kept same between two slicers. Speed was standard 50mm/s, retraction was 1mm at 45mm/s, material used was PLA+ at 200 degC and 60degC bed temperature. The one with Cura is gettings zits and blobs like it was sliced in 5.3.x and prusa one is clean. I have attached pictures below. 

### Actual results

![20230619_221042](https://github.com/Ultimaker/Cura/assets/45509751/7b811410-66c8-4e24-86b7-2691fe8480f4)

### Expected results

![20230619_221346](https://github.com/Ultimaker/Cura/assets/45509751/386d0dd3-c2b9-4056-a967-8bf888e8178c)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

N/A

**Comment by GregValiant** [comment] 2023-06-19 22:50
Thanks for the report.
This is a duplicate of #14811 where you will find much discussion regarding this problem.
I'll go ahead and close this as a duplicate as the team is aware of this problem when dealing with Klipper.

**Closed by GregValiant** 2023-06-19 22:50 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation
