### ISSUE TITLE
Error: configparser.DuplicateSectionError: While reading from 'C:\\Users\\x/AppData/Local/cura\\cura.cfg' [line 20]: section 'view' already exists

### ISSUE THREAD

**Issue by FuzzySadist** [Ultimaker/Cura#454] opened 2015-10-03 06:48 UTC
So this has been working since I downloaded it... then suddenly today, for no reason that I can find, it is dropping this error everytime I run it.  Help!

Error dialog:
Version: 15.06.03
Platform: Windows-8-6.2.9200
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "cura_app.py", line 9, in <module>
  File "c:\dev\uranium\UM\Application.py", line 329, in getInstance
  File "c:\dev\cura\cura\CuraApplication.py", line 56, in __init__
  File "c:\dev\uranium\UM\Qt\QtApplication.py", line 48, in __init__
  File "c:\dev\uranium\UM\Application.py", line 67, in __init__
  File "c:\dev\uranium\UM\Preferences.py", line 56, in readFromFile
  File "c:\dev\uranium\UM\Preferences.py", line 122, in _loadFile
  File "c:\dev\python34\lib\configparser.py", line 672, in read
  File "c:\dev\python34\lib\configparser.py", line 1044, in _read
configparser.DuplicateSectionError: While reading from 'C:\\Users\\x/AppData/Local/cura\\cura.cfg' [line 20]: section 'view' already exists

**Comment by Ghostkeeper** [comment] 2015-10-03 19:40
This is a duplicate of #346, #389 and #428. Version 15.06 created corrupt configuration files when the Python environment is interrupted while it is writing that file, or when multiple instances of Cura are writing to it at the same time. This issue is fixed in version 15.10.

To fix your Cura version, delete the file mentioned in your traceback: C:\Users\x\AppData\Local\cura\cura.cfg. Cura will then create it anew, but you will lose your configuration. You could also try and open that file with a text editor such as Notepad to try to mend it, if you're feeling adventurous and really don't want to lose your settings.

**Closed** 2015-10-03 19:40 UTC
Labels: duplicate
