### ISSUE TITLE
[5.3.1] Make overhang printable affects cutting meshes

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#9583] opened 2021-04-15 09:38 UTC
### Application Version

4.9 beta

### Platform

win 7

### Printer

custom fff

### Reproduction steps

Enable "make overhangs printable", I used 33°.
Place a cutting mesh with for example reduced speed.

### Actual results

Cutting mesh is affected by make overhangs printable.

### Expected results

It shouldn't be affected?
![overhang printable](https://user-images.githubusercontent.com/32172100/114848295-d8c4aa80-9dde-11eb-80d0-0cdb7d49752a.PNG)
[overhang printable.zip](https://github.com/Ultimaker/Cura/files/6316827/overhang.printable.zip)

**Comment by fvrmr** [comment] 2021-04-15 12:51
Hi @printingotb thank you for your bug report!
I will discuss this with the team. Keep you posted!

**Comment by Ghostkeeper** [comment] 2021-04-15 16:53
It might sound a bit weird going by the opposing titles, but I think this has the same root cause as this bug: https://github.com/Ultimaker/Cura/issues/9350

The bug is that instead of "Make Overhang Printable" being applied to some part of the main mesh, it's being applied to the cutting mesh, causing a different piece to be cut off. Your bug report reports that a different piece is being cut off. The other one reports that (part of) the main mesh is not being edited.

**Comment by printingotb** [comment] 2021-04-15 19:50
Sounds like the same bug.

If I don't disable "make overhangs printable" with the modifier, the modifier is affected by the settings profile.
![Skärmklipp](https://user-images.githubusercontent.com/32172100/114928323-c07e7b00-9e32-11eb-9c4b-c421102fe5e2.PNG)
If I do disable it, its affected to a certain amount, the model is still affected:
![Skärmklipp](https://user-images.githubusercontent.com/32172100/114929685-68e10f00-9e34-11eb-923e-3bae63ab2963.PNG)
With the setting turned off in the profile and then enabled in the modifier, neither is affected.
![Skärmklipp](https://user-images.githubusercontent.com/32172100/114928696-2f5bd400-9e33-11eb-8b2a-23291ba1b0a3.PNG)
[Body1.zip](https://github.com/Ultimaker/Cura/files/6320745/Body1.zip)
(sliced in arachne beta this time)

**Comment by fvrmr** [comment] 2021-04-16 09:23
Hi @printingotb I have discussed it with the team. And we decided to defer this issue. Because we think that not many people will use this combination of settings. Hope you understand.

**Comment by printingotb** [comment] 2023-05-27 08:26
Confirming that the issue is still present in 5.3.1

**Comment by MariMakes** [comment] 2023-05-30 14:51
Hey @printingotb,

Fresh eyes reporting for duty 🐣 

Thanks for doublechecking if it's still present. It's odd indeed. 
I did notice that you can disable the setting in your mesh, but I wouldn't have thought of that when I saw it. 
![image](https://github.com/Ultimaker/Cura/assets/40423138/d9317246-ef6f-45e9-99c6-ca32b22e1a3b)

I'll bring it up to the team to see what they think. 
But I expect that if it's not a quick fix that it will not get a high priority to implement.

**Comment by printingotb** [comment] 2023-05-30 16:11
Thanks, keep up the good work!

**Comment by MariMakes** [comment] 2023-06-01 09:19
I brought your issue up with the team. 💪 
They recognized the issue but since there is an easy workaround in place, and the setting is experimental we decided to close the issue. Since Cura is open source, you or anyone else is more than welcome to work on this issue and create a pull request yourself.

I'll close this issue, I hope you understand. 🙏

**Closed by MariMakes** 2023-06-01 09:19 UTC
Labels: Type: Bug, Status: Deferred, Status: Under Investigation
