### ISSUE TITLE
impossible de decouper avec elegoo cura 5.6.0

### ISSUE THREAD

**Issue by nphilou68** [Ultimaker/Cura#18957] opened 2024-04-25 19:31 UTC
### Cura Version

elegoo cura 5.6.0

### Operating System

Windows 11 

### Printer

elegoo neptune 4 plus

### Name abnormal settings

non

### Describe model location

non

### Describe your model

decoupage avec cura ok pas avec elegoo cura 5.6.0

### Add your .zip here ⬇️

avec cura normal découpage ok 
impossible avec elegoo cura 5.6.0 
imprimante elegoo neptune 4 plus
[EN4P_Goldorak Damaged V2 02.zip](https://github.com/Ultimaker/Cura/files/15119715/EN4P_Goldorak.Damaged.V2.02.zip)

**Comment by GregValiant** [comment] 2024-04-26 01:14
Thanks for the report.
A lot of the random slicing errors that occurred in 5.4-5.6 were fixed for 5.7.0.  5.7.1 was released last week.  I would suggest you install 5.7.1 and see if the problem has been fixed.

I'll mark this as a duplicate report and close it.  Let us know if the problem is present in 5.7.1.

This is an 80 hour print and your support settings need a lot of help.
![image](https://github.com/Ultimaker/Cura/assets/64202104/f041c146-b29a-42c3-bd58-1df91ee9af5a)

**Closed by GregValiant** 2024-04-26 01:14 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error :collision:
