### ISSUE TITLE
5.1.1 View manipulation not working: zoom/rotate/panning

### ISSUE THREAD

**Issue by Distillah2** [Ultimaker/Cura#13590] opened 2022-10-18 10:06 UTC
### Application Version

Cura 5.0.0 and .1.1

### Platform

Win 10

### Printer

Creality Ender 6

### Reproduction steps

When Cura opens and when a model is inserted and after slicing, none of the mouse buttons for zooming, panning and rotating are working. None of the view buttons are working either (lower left corner).
This started in Cura 5.0.0 and is still happening in the update to 5.1.1.

### Actual results

None of the view buttons on mouse or lower left corner are working.
The screen as shown stays in that position, what ever viewing command is given
![Picture1](https://user-images.githubusercontent.com/116072735/196400152-be6f53dd-4151-4794-a06b-ca7ac86be91f.png)

### Expected results

The view should follow viewing instructions

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No further additional information

**Comment by timmackey0851** [comment] 2022-10-27 14:21
Ive also reported the same issue

**Comment by MariMakes** [comment] 2022-11-08 13:12
Hey @Distillah2,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13590
We have quite a number of reports about this, so I'll be bringing it up with the team. 
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/13590

**Closed by MariMakes** 2022-11-08 13:12 UTC
Labels: Type: Bug, Status: Triage
