### ISSUE TITLE
HINT APPEAR OVER TEXTBOX, COULD NOT WRITE THE VALUE

### ISSUE THREAD

**Issue by tamarit77** [Ultimaker/Cura#15165] opened 2023-04-07 00:24 UTC
### Application Version

4.13.1

### Platform

Windows 10

### Printer

Hellbot Magna Dua

### Reproduction steps

1. When wish to write the Extruder temperature to preheat using the mouse cursor, the HINT dialog come ONTOP and don't let me to write the value on the textbox.
2. I need to be quicker than software and click on the textbox and then mover out the mouse cursor, thus be able to write on the textbox

### Actual results

Finally I can write the value, but is quite unconfortable

### Expected results

The hint must NOT APPEAR OVER THE TEXTBOX

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

-

**Comment by MariMakes** [comment] 2023-05-04 14:34
Hey @tamarit77,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 

A screenshot would be helpful in this case, but I think I know what you mean 😅 
Do you have the Settings Guide Plug-in installed?
Is what you are seeing this?
![image](https://user-images.githubusercontent.com/40423138/236239231-9cb29d01-b95d-48ee-9bc5-19d3d36743e6.png)

That's an issue for the plug-in and not for Cura. 
An easy workaround is to temporarily disable the plug-in until you are finished with editing the start gcode.

If you go to the marketplace, click on the gear icon, find the settings guide plug-in and click Disable, it will temporarily disable. If you want it back you can enable it again. 

![image](https://user-images.githubusercontent.com/40423138/236239924-e11b11d6-b3c6-4bfc-815f-9c3ce2152efa.png)

I hope this helps 😇

To me, it doesn't seem like a bug in Ultimaker Cura, but with the plug-in instead. 
Apologies for any inconvenience caused by our delayed response. 
I'll be closing this issue. I hope you understand.

**Closed by MariMakes** 2023-05-04 14:34 UTC
Labels: Type: Bug, Status: Triage
