### ISSUE TITLE
unable to slice group (screenshot included)

### ISSUE THREAD

**Issue by reverendfuzzy** [Ultimaker/Cura#16452] opened 2023-08-10 13:58 UTC
### Cura Version

5.4.0

### Operating System

Ubuntu Linux 22.04.3 LTS

### Printer

Creality Ender 3

### Name abnormal settings

no abnormal settings

### Describe model location

distributed evenly away from center

### Describe your model

.stl of a tire  and screenshot of error

### Add your .zip here ⬇️

[wheel.zip](https://github.com/Ultimaker/Cura/files/12313503/wheel.zip)
![Screenshot from 2023-08-10 08-55-37](https://github.com/Ultimaker/Cura/assets/35825055/f69b49bb-71e7-4360-a6fb-65e7f2fbac1f)

**Comment by GregValiant** [comment] 2023-08-12 01:35
Thanks for the report.
A project file is always better.  set Cura up and use the "File | Save Project" command and zip the file and post the zip folder here.
This slices fine for me.  I set the models equally about the center line and there were no issues.
You might try changing the Initial Layer Height by just a little bit.  That can sometimes fool the bug.

This sounds like a duplicate of some other reports.  I'll leave it open for a while so you can respond but a project file would be  helpful.

**Closed** 2023-08-26 12:05 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage, Slicing Error :collision:
