### ISSUE TITLE
Anycubic Vyper Start and Endcode

### ISSUE THREAD

**Issue by Toddi3D** [Ultimaker/Cura#12292] opened 2022-05-21 13:12 UTC
### Application Version

5.0

### Platform

Windows 10 64

### Printer

Anycubic Vyper

### Reproduction steps

The Start and Endcode for the Vyper .. something is wrong ... 

Start:

G21 ;metric values
G90 ;absolute positioning
M82 ;set extruder to absolute mode
M107 ;start with the fan off
G28 X0 Y0 ;move X/Y to min endstops
M300 S1318 P266
G28 Z0 ;move Z to min endstops
G0 Z0.2
G92 E0 ;zero the extruded length
G1 X40 E25 F400 ; Extrude 25mm of filament in a 4cm line. Reduce speed (F) if you have a nozzle smaller than 0.4mm!
G92 E0 ;zero the extruded length again
G1 E-1 F500 ; Retract a little
G1 X80 F4000 ; Quickly wipe away from the filament line
M117 ; Printing…
G5

Endcode:

M104 S0 ; turn off extruder
M140 S0 ; turn off bed
M84 ; disable motors
M107
G91 ;relative positioning
G1 E-1 F300 ;retract the filament a bit before lifting the nozzle, to release some of the pressure
G1 Z+0.5 E-5 ;X-20 Y-20 F{speed_travel} ;move Z up a bit and retract filament even more
G28 X0 ;Y0 ;move X/Y to min endstops, so the head is out of the way
G1 Y180 F2000
M84 ;steppers off
G90
M300 S1318 P266

at end of printing i hear no beep

### Actual results

i put this M300 S1318 P266 after G28 and it works, but somebody tell me the endcode is not ok... so maybe the Startcode has also errors ?

### Expected results

nothing

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8747659/cura.log)

**Comment by Vandresc** [comment] 2022-05-31 11:17
Duplicate of https://github.com/Ultimaker/Cura/issues/12255

**Closed by Vandresc** 2022-05-31 11:17 UTC
Labels: Type: Bug
