### ISSUE TITLE
Tree support do not generate a layer between support and model

### ISSUE THREAD

**Issue by fastline0** [Ultimaker/Cura#7131] opened 2020-02-18 23:35 UTC
Can anyone explain why cura tree support not generate a layer between support structure and my model, it's because I print with ABS and use PVA as the support material between my support structure and my model. My Z distance is 0, so it should have a close contact with my support structure. 
<img width="1352" alt="tree support 1" src="https://user-images.githubusercontent.com/61213188/74787499-a50bf480-52af-11ea-9e00-cbe7030ec07b.png">

**Comment by Ghostkeeper** [comment] 2020-02-25 16:15
This is a duplicate of https://github.com/Ultimaker/Cura/issues/5759 .

It seems that there is one layer at which the circles for each branch are too small to print.

**Closed by Ghostkeeper** 2020-02-25 16:15 UTC
Labels: Type: Bug
