### ISSUE TITLE
[4.8 BETA] Does not open on macOS Big Sur 11.0.1 Beta (20B5012d)

### ISSUE THREAD

**Issue by dkalinai** [Ultimaker/Cura#8668] opened 2020-10-31 07:29 UTC
**Application version**
4.8 BETA

**Platform**
macOS Big Sur 11.0.1 Beta (20B5012d)

**Printer**
Ender 5

I w3as using 4.8 perfectly on same machine on Catalina, then decided it was time to try Big Sur. Now version 4.7 still works in Big Sur and I can work with it, but 4.8 just bounces for 1-2 seconds and closes. No way for me to open it. I believe this is the relevant log files, does complain about python package however 4.7 works and same machine 4.8 worked on older os.
[stderr.log](https://github.com/Ultimaker/Cura/files/5468646/stderr.log)

**Comment by jellespijker** [comment] 2020-10-31 10:39
duplicate of #8617

**Closed** 2020-10-31 10:39 UTC
Labels: Type: Bug
