### ISSUE TITLE
setting the USB port in 2.3.1/2.4 under linux

### ISSUE THREAD

**Issue by simpsonar77** [Ultimaker/Cura#1280] opened 2016-12-29 19:14 UTC
I cannot find any place to select/enter the USB device in cura.  Using 15.X, it would either show the list of possible USB devices, or allow you to enter one.

Using Fedora 23 and fedora 25.  Unable to print via USB.  It looks like it connected initially, but after creating a custom printer, it would now allow a connection to the printer.

**Comment by Ghostkeeper** [comment] 2017-01-02 08:41
Manual selecting wasn't put in (yet) after the rewrite of Cura 2.

Duplicate of #736, #799 and #912.

**Comment by Ghostkeeper** [comment] 2017-01-02 08:42
For the record, in our internal tracker this is CURA-1726 and currently scheduled for Cura 2.6.

**Closed by Ghostkeeper** 2017-01-02 08:41 UTC
