### ISSUE TITLE
Display scaling and graphic corruption on secondary monitor

### ISSUE THREAD

**Issue by microdesigns2000** [Ultimaker/Cura#2849] opened 2017-11-26 04:11 UTC
1) On Windows 10 on a laptop with a high resolution screen (3200x1800), Cura 3.0.4 displays most text too small to be viewed.  Cura does not react to changes on the Windows 10 > Display > Scale and layout setting.

3) When the Cura window is dragged to a secondary monitor (1920x1080), the text size looks ok, but the Cura user interface is completely corrupt, and does not display any changes, or appear to react to any user input.  When the window is dragged back to the primary monitor, normal function returns.

I did not experience any of these problems using Cura 2.7.

![cura3 0 4](https://user-images.githubusercontent.com/24869416/33237031-07a94c24-d22d-11e7-9f46-a7d5e5160e42.PNG)

**Comment by ChrisTerBeke** [comment] 2017-11-26 18:43
Duplicate of https://github.com/Ultimaker/Cura/issues/2493.

**Closed by ChrisTerBeke** 2017-11-26 18:43 UTC
