### ISSUE TITLE
Fine edges/details are breaking up - Prusa Slicer has no probelms in classic mode.  

### ISSUE THREAD

**Issue by Davethegithub** [Ultimaker/Cura#13241] opened 2022-09-08 04:10 UTC
### Application Version

5.1

### Platform

Window 10

### Printer

Ender S1 Pro

### Reproduction steps

Slicing a small part with fine edges.  0.08 or 0.12 layer height gets the same result.  

Reducing minimum line width settings to 0.1 does nothing to change the sliced appearance.

It happens in Prusa Slicer as well ONLY if I have Arachne generator on.  Classic mode is fine.

An Arachne generator issue??  Can it be turned off in Cura.

Part pre slice
![1](https://user-images.githubusercontent.com/33383595/189031140-623fb4d9-9e76-4f86-aebe-c5f4fd75b4d5.JPG)

Post slice with jagged edges
![2](https://user-images.githubusercontent.com/33383595/189031144-daffa138-f9b1-45bc-98b0-a93786ddf0f4.JPG)

In Prusa Classic mode.

![image](https://user-images.githubusercontent.com/33383595/189031507-0826437c-f433-4347-b25e-f7ee331e0932.png)

### Actual results

Jagged edges on sliced preview & print.

### Expected results

Smooooothness.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[CE3PRO_AIRY 5.zip](https://github.com/Ultimaker/Cura/files/9523483/CE3PRO_AIRY.5.zip)

**Comment by MariMakes** [comment] 2022-09-13 12:10
Hey @Davethegithub 

Welcome to the Ultimaker Cura Github 🚀 
Thanks for the report, this is a super interesting test case. 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12817
We have a ticket on our backlog with the intent to improve this behavior.

Also @Piezoid great tip! Thanks for helping out ❤️ 
Hopefully, that makes troubleshooting a little easier. 😄 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12817

**Closed by MariMakes** 2022-09-13 12:10 UTC
Labels: Type: Bug, Status: Triage
