### ISSUE TITLE
Cura sets Top Layers to 0 and Bottom Layers to 999999 when choosing 100% Infill Density

### ISSUE THREAD

**Issue by krikru** [Ultimaker/Cura#10111] opened 2021-07-09 11:13 UTC
### Application Version

4.10.0

### Platform

Windows 10

### Printer

Creality Ender-3

### Reproduction steps

1. Set Infill Density to 100.0

### Actual results

Top Layers is set to 0 and Bottom Layers is set to 999999.

### Expected results

Top Layers and Bottom Layers remain unchanged.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Even though setting Bottom Layers to 999999 will make sure the model is completely filed, this may not be desirable as the user may want another infill pattern than the pattern on the top and bottom layers.

**Comment by fvrmr** [comment] 2021-07-09 14:33
Hi @krikru this is a duplicate of https://github.com/Ultimaker/Cura/issues/9004 and this behaviour is expected. If you want an other infill pattern you could change the bottom layers manually. 
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-07-09 14:33 UTC
Labels: Type: Bug
