### ISSUE TITLE
Christmas Village slicing failed

### ISSUE THREAD

**Issue by myhalfcent** [Ultimaker/Cura#17073] opened 2023-10-22 16:29 UTC
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Ender 3 V3 SE

### Name abnormal settings

Usual, standard printer settings

### Describe model location

Center of platform; rotating 90 and moving away both produced a crash

### Describe your model

Never used this model before; is watertight, Mesh tools couldn't help

### Add your .zip here ⬇️

[CE3V3SE_Christmas_Village.zip](https://github.com/Ultimaker/Cura/files/13063912/CE3V3SE_Christmas_Village.zip)

**Comment by GregValiant** [comment] 2023-10-23 01:38
Thanks for the report
This model has shown up here a couple of times previously and this report is a duplicate of #16951.  I'll go ahead and close this.  If you have further comments you can make them on the other report.

**Closed by GregValiant** 2023-10-23 01:38 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error :collision:
