### ISSUE TITLE
A cura setting for preventing the head from approaching from the wrong side.

### ISSUE THREAD

**Issue by mthayne** [Ultimaker/Cura#10529] opened 2021-09-28 01:20 UTC
### Is your feature request related to a problem?

When printing overhangs the head many times approaches the part from the side of the overhang, this increasing the risk of having the nozzle hook on the edge that may be warped upwards.

### Describe the solution you'd like

Have a setting that specifies that overhangs are not to be approached from the overhanging side.

### Describe alternatives you've considered

There really aren't any other ways to address this problem in other ways on many parts.

### Affected users and/or printers

Everyone could be affected at one time or another.

**Comment by Ghostkeeper** [comment] 2021-10-04 13:14
Duplicate of https://github.com/Ultimaker/Cura/issues/9369.

**Closed by Ghostkeeper** 2021-10-04 13:14 UTC
Labels: Type: New Feature
