### ISSUE TITLE
Scaling in Cura 4.2.1

### ISSUE THREAD

**Issue by 2-k** [Ultimaker/Cura#6150] opened 2019-08-04 17:10 UTC
So it has to do with rotation of the part, once it's 90° then Cura gets confused.

Would be nice if Cura made tickets, like I don't know when you click report a bug maybe make a ticket to the computer information. Y effects Z so it's extremely annoying only fix I have found is to delete the part with the issue otherwise it makes a unusable code.
![IMG_20190804_095948](https://user-images.githubusercontent.com/53622621/62426868-6b6ef580-b69f-11e9-8d4a-7be83568b391.jpg)
![IMG_20190804_095933](https://user-images.githubusercontent.com/53622621/62426869-6c078c00-b69f-11e9-852d-cac09687a78c.jpg)
![IMG_20190804_100019](https://user-images.githubusercontent.com/53622621/62426870-6c078c00-b69f-11e9-8a69-2fbce7307787.jpg)
![IMG_20190804_100010](https://user-images.githubusercontent.com/53622621/62426871-6c078c00-b69f-11e9-869a-400d0e4f4da8.jpg)
Why does it direct me to this? Seems like a waste of time.

**Comment by Ghostkeeper** [comment] 2019-08-11 17:28
Duplicate of https://github.com/Ultimaker/Cura/issues/4136.

**Closed by Ghostkeeper** 2019-08-11 17:28 UTC
Labels: Type: Bug
