### ISSUE TITLE
Uninstalling errors at startup

### ISSUE THREAD

**Issue by CHBPro** [Ultimaker/Cura#11992] opened 2022-04-27 06:47 UTC
### Application Version

5.0.0-beta+1

### Platform

Windows 10 Pro 21H2

### Printer

Home made

### Reproduction steps

I started the program

### Actual results

The program starts with a failure notice, The notice disappears, and the program works normally.

### Expected results

No failures

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

screenshot of the failure
![errorCura5](https://user-images.githubusercontent.com/68540787/165458014-1eb88a8d-38cf-4970-9dcb-bf3a2473cd4e.jpg)

**Comment by fvrmr** [comment] 2022-04-28 08:04
Hi @CHBPro thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11865, so I will close this issue.

**Closed by fvrmr** 2022-04-28 08:04 UTC
Labels: Type: Bug
