### ISSUE TITLE
Can't read description of setting

### ISSUE THREAD

**Issue by juanchacon98** [Ultimaker/Cura#12047] opened 2022-05-01 17:32 UTC
### Application Version

5.0.0

### Platform

Windows 11

### Printer

SV02

### Reproduction steps

1. I was setting up the functions
2. When I put the pointer over the function, it displays a descrption of the function

### Actual results

![image](https://user-images.githubusercontent.com/95106627/166157322-56c79e18-7b26-48e4-906d-e04292aecb8c.png)

when the description is too long, it requires to scroll down, when I move the pointer to  the dialog box, it disappears.

### Expected results

Let the pointer inside the dialog box to scroll down without disappearing.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

nothing

**Comment by fvrmr** [comment] 2022-05-02 09:06
Hi @juanchacon98 thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11834, so I will close this issue.

**Closed by fvrmr** 2022-05-02 09:06 UTC
Labels: Type: Bug
