### ISSUE TITLE
Z-Seam Alignement "Random" Causes Travel-Moves For Every Single Wall (Even Inner Walls)

### ISSUE THREAD

**Issue by FPrefect20** [Ultimaker/Cura#15142] opened 2023-04-04 23:03 UTC
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Any Printer

### Reproduction steps

1. Slice a simple object (e.g. cylinder - see screenshot)
2. Settings:    [Wall Line Count]:   "8" / [Z-Seam Alignement]: "random"
3. Switch to "preview"
--> have a look of the number of travel moves

### Actual results

Travel move for every single wall (inner and outer walls) to random starting position.

### Expected results

One random travel move. Only for the outer wall (one random position move per layer)
The rest of the walls (inner walls) should use "shortest".

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![random](https://user-images.githubusercontent.com/65475741/229940978-f51f5d63-7e95-4139-a326-ecf703944802.jpg)

**Comment by rburema** [comment] 2023-04-13 21:31
Seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/15131, please continue any discussion there.

**Closed by rburema** 2023-04-13 21:31 UTC
Labels: Type: Bug, Status: Duplicate, Status: Triage
