### ISSUE TITLE
cx python error

### ISSUE THREAD

**Issue by brendanssound** [Ultimaker/Cura#9669] opened 2021-04-23 15:21 UTC
### Application Version

4.9.0

### Platform

Windows 10

### Printer

Creality Ender 3

### Reproduction steps

Had version 4.8.0 
Ran installer for version 4.9.0 which asked if i wanted to remove old version.. I did.. So it did.. 
Attempted to run 4.9.0 

### Actual results

Get an error 

Error in sys.excepthook
Exception (WinError 53) The network path was not found.
x:\\4.9.exe\build\inst\bin\cura_app.py
Original Exception (WinError 53) The Network path was not found
x:\\4.9.exe\build\inst\bin\cura_app.py

No idea why its looking on a network drive for a file.. ?? 

Installed from my local drive.. never run anything off my network drives.. Don't use onedrive/any other cloud storage
Have removed the cura directories in Local & Roaming
Uninstalled/Reinstalled
Even restarted after uninstall and tried reinstall

### Expected results

Program runs, I get to slice prints and live happily ever after

**Comment by brendanssound** [comment] 2021-04-23 17:01
![Screenshot 2021-04-24 011637](https://user-images.githubusercontent.com/83081762/115905412-6a03e300-a4a9-11eb-9192-15d5625aeace.png)

**Comment by jellespijker** [comment] 2021-04-23 17:07
Duplicate of #9647 will close this issue in favor of the discussion there.

**Closed by jellespijker** 2021-04-23 17:07 UTC
Labels: Type: Bug
