### ISSUE TITLE
BUG: Virtual Display disappears when a file is loaded in.

### ISSUE THREAD

**Issue by jambalyle** [Ultimaker/Cura#312] opened 2015-09-02 00:10 UTC
As soon as I load a file into the build environment the whole view goes grey. Can't see the platform, can't see the model, nothing. Tried changing the views but it doesn't help.

**Comment by nallath** [comment] 2015-09-02 07:19
Please have a look at https://github.com/Ultimaker/Cura#logging-issues

**Comment by awhiemstra** [comment] 2015-09-02 08:49
Ths sounds like a duplicate of #110

**Closed by awhiemstra** 2015-09-02 08:49 UTC
