### ISSUE TITLE
Brim on multiple layers

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#7038] opened 2020-01-28 18:06 UTC
**Is your feature request related to a problem? Please describe.**
One brim isn't enough for things that barely have a touching point on the first layer, especially on materials like ABS

**Describe the solution you'd like**
Put a brim on multiple selected layer

**Describe alternatives you've considered**
Work along with #6996 and also put a skirt around the brim so the brimm will be clean. 

**Affected users and/or printers**
Any

**Additional context**
S3d makes it and it works nice, making the best out of both brim and raft. Also the skirt working with distance like a brim that was being worked on would be perfect along with this, in which case even a multiple layers skirt would be useful for minimal distances like 0.1mm.

**Comment by Ghostkeeper** [comment] 2020-01-30 14:14
Duplicate of https://github.com/Ultimaker/Cura/issues/6939. Please continue the discussion there.

**Closed by Ghostkeeper** 2020-01-30 14:14 UTC
Labels: Type: New Feature
