### ISSUE TITLE
Auto generated comment in G-Code has no version info on Cura 5.1.0 for Windows

### ISSUE THREAD

**Issue by Tiryoh** [Ultimaker/Cura#12833] opened 2022-07-22 19:18 UTC
### Application Version

5.1.0

### Platform

Windows 11

### Printer

Kingroon KP3S

### Reproduction steps

1. Install Cura 5.1.0 on Windows from https://github.com/Ultimaker/Cura/releases/tag/5.1.0
2. Slice a STL (any STL and any config is OK)
3. Save G-Code
4. Open G-Code with text editor and check the auto generated comment

### Actual results

```
;Generated with Cura_SteamEngine main
```

<img width="369" alt="image" src="https://user-images.githubusercontent.com/3256629/180506457-71e57679-bf78-46f5-8aac-1bc39135df2c.png">

### Expected results

```
;Generated with Cura_SteamEngine 5.1.0
```

For the reference, Cura 5.0.0 shows the version correctly.

<img width="343" alt="image" src="https://user-images.githubusercontent.com/3256629/180506702-dcbc02ca-8826-4a38-875c-94ca38989f61.png">

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Once this issue is fixed, an application like Klipper can get the G-Code info correctly.

<img width="497" alt="image" src="https://user-images.githubusercontent.com/3256629/180508339-b646a19b-8df6-4238-bd6d-0d78b23adc27.png">

**Comment by GregValiant** [comment] 2022-07-22 23:03
Thanks for the reporrt.
This is a duplicate of #12825 and I'll mark it as such and close this in favor of the previous report.  If you want to leave more comments you can put them in that other report.
(BTW...Nice eye.  I looked at _a lot_ of gcode files sliced with 5.1 and missed this completely.)

**Closed by GregValiant** 2022-07-22 23:03 UTC
Labels: Type: Bug, Status: Duplicate

**Comment by Tiryoh** [comment] 2022-07-22 23:23
Oops, sorry for creating the duplicate issue and thanks for checking this issue.
I'll continue checking the update on https://github.com/Ultimaker/Cura/issues/12825.
