### ISSUE TITLE
No nozzle size in cura with artillery genius profile

### ISSUE THREAD

**Issue by nflyer** [Ultimaker/Cura#8183] opened 2020-08-12 22:11 UTC
When i import a profile for artillery genius i can't see nozzle size ( in the nozzle  screen i see "empty")
-->

**Application version**
Cura 4.6.1

**Platform**
Windows 10 intel I7

**Printer**
Import profile for artillery genius

![cxcvcxcxccx](https://user-images.githubusercontent.com/22818903/90073465-88e68e80-dcf9-11ea-954b-2cae506cf791.JPG)

**Comment by rburema** [comment] 2020-08-13 05:52
Can you post the profile here?

(Anything in the logs when you imported it?)

**Comment by theodore0310** [comment] 2020-08-13 10:03
I have the same problem, with a pro

[petg myself.zip](https://github.com/Ultimaker/Cura/files/5068384/petg.myself.zip)

file for the artillery sidewinder x1, exported from Cura slicer of my old PC. This is it. ###

**Comment by nallath** [comment] 2020-08-13 13:42
It's not really something we can test, because we don't _have_ the artillery sidewinder machine definition. Where did you get that from?

**Comment by nflyer** [comment] 2020-08-13 14:16
from 3d nexus site

Il giorno gio 13 ago 2020 alle ore 15:43 Jaime van Kessel <
notifications@github.com> ha scritto:

**Comment by Ghostkeeper** [comment] 2020-08-14 09:18
Duplicate of https://github.com/Ultimaker/Cura/issues/8104

The profile on 3DNexus is simply outdated. Use Cura 4.6.1 or manually update the profile from 3DNexus.

**Closed by Ghostkeeper** 2020-08-14 09:18 UTC
Labels: Type: Bug

**Comment by PocoComunicativo** [comment] 2020-10-01 20:37
I had the same problem. I have Ultimate Cura version 4.7.1 and I just download this profile, and works just fine:

https://www.thingiverse.com/thing:4581098
