### ISSUE TITLE
[4.7.0] Scaling shows changes in different axis when using mm or %

### ISSUE THREAD

**Issue by diogorolo** [Ultimaker/Cura#8392] opened 2020-09-16 08:59 UTC
**Application version**
Cura 4.7.0

**Platform**
Windows 10

**Printer**
Ender 3 pro

**Reproduction steps**
1. Select a model that is vertical
2. Click on "Lay flat" until it's on the bed
3. Go to scale, do not select uniform scaling, and change the size (in mm) of an axis.

**Screenshot(s)**
Before changing the scale:
![before](https://user-images.githubusercontent.com/3449660/93315195-a9c36780-f802-11ea-857e-83a077a99e3e.PNG)
After changing the scale in mm:
![after](https://user-images.githubusercontent.com/3449660/93315279-c2338200-f802-11ea-9e66-1a9e155b9641.PNG)

**Actual results**
After 3. the percentage that changes is not the axis that has had the value in mm changed.

**Expected results**
The percentage that changes should be the changed axis

**Project file**
[WesternEurope.zip](https://github.com/Ultimaker/Cura/files/5230994/WesternEurope.zip)

**Log file**
2020-09-16 09:57:40,120 - DEBUG - [MainThread] UM.Operations.OperationStack.push [72]: ScaleOp.(node=<CuraSceneNode object: 'SouthAmerica.stl'>,scale=<1.0,1.54,1.0>,mode=relative), took 7ms
2020-09-16 09:57:40,239 - DEBUG - [MainThread] UM.Operations.OperationStack.push [72]: PlatformPhysicsOp.(trans.=<0.0,0.35,0.0>), took 1ms

We can see in the log file that the scale operations are being done on the Y axis but the GUI shows the Z axis when in mm and Y axis when in %

**Comment by nallath** [comment] 2020-09-16 09:28
Duplicate of https://github.com/Ultimaker/Cura/issues/4136

**Closed by nallath** 2020-09-16 09:28 UTC
Labels: Type: Bug
