### ISSUE TITLE
I'm not able to slice a specific model

### ISSUE THREAD

**Issue by Coulsonharris** [Ultimaker/Cura#14066] opened 2022-12-17 00:22 UTC
### Application Version

5.2.1

### Platform

Mac OS ventura

### Printer

ender 3

### Reproduction steps

1. opened a model
2. tried to slice it

### Actual results

unable to slice 

### Expected results

slice

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[LAS_VEGAS_TEMPLE.3mf.zip](https://github.com/Ultimaker/Cura/files/10250243/LAS_VEGAS_TEMPLE.3mf.zip)

**Comment by GregValiant** [comment] 2022-12-17 19:58
Thanks for the report and the file.
It wouldn't slice when I opened it.  After rotating the model and moving it on the build plate it sliced fine.
This is a duplicate of many other reports of good models that won't slice when centered on the build plate in Cura.  Previously it was only a problem on Windows but it seems to be creeping into the Mac world.

I'll mark this as a duplicate and leave it open for the Cura team.  in the mean time see if moving the model in Cura and'or rotating it allows it to slice.  Let us know how you make out.

You can see below that I rotated it 90° CCW and moved it near the left front corner.
![image](https://user-images.githubusercontent.com/64202104/208263948-7351a4ce-9cbe-458b-99cb-0648e95ab123.png)

**Closed** 2023-01-01 00:19 UTC
Labels: Type: Bug, Status: Duplicate, Status: Needs Info, Status: Under Investigation, Slicing Error💥
