### ISSUE TITLE
[4.7] Custom Machine Start G-Code fails to parse and fails to appear in sliced G-Code

### ISSUE THREAD

**Issue by lps-rocks** [Ultimaker/Cura#8238] opened 2020-08-26 01:09 UTC
**Application version**
4.7 (4.6 was not affected)

**Platform**
MacOSX

**Printer**
Lulzbot Mini 

**Reproduction steps**
1. Use start G-Code with more than 4 or 5 comment strings and multiple empty lines
2. Edit Machine start g-code in GUI (Not all g-code is shown
3. Slice
4. Inspect G-code produced from slice. It will be missing the start code.

**Screenshot(s)**
Cura 4.7 GUI
https://i.hexhost.net/xfLPza.png
This is what's in the saved file for the printer
https://i.hexhost.net/8u0Ws9.png
This is what ends up in the G-Code
https://i.hexhost.net/ezlAPy.png

**Actual results**
Not all machine start g-code is included in sliced g-code

**Expected results**
All machine start g-code should be included in sliced g-code

**Comment by nallath** [comment] 2020-08-26 07:43
Duplicate of https://github.com/Ultimaker/Cura/issues/8230

**Closed by nallath** 2020-08-26 07:43 UTC
Labels: Status: Duplicate, Type: Bug
