### ISSUE TITLE
Monotonic enabled, excessive travel

### ISSUE THREAD

**Issue by frankygoop** [Ultimaker/Cura#13565] opened 2022-10-15 23:38 UTC
### Application Version

5.2.0

### Platform

Windows 11

### Printer

Tevo Tarantula

### Reproduction steps

Enable monotonic, go to layer 33 

### Actual results

observe the excessive travel over the wall skin. It made a mess on the outer wall. I recorded a video but could not uploaded due to the size.

### Expected results

to behave like with previous versions.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![Screenshot 2022-10-15 173243](https://user-images.githubusercontent.com/18506409/196011275-dd7af827-be14-4775-9a9b-523939a72810.png)
[TT_Celholder.zip](https://github.com/Ultimaker/Cura/files/9793297/TT_Celholder.zip)

**Comment by GregValiant** [comment] 2022-10-15 23:59
Thanks for the report.
You're being nice about it.  It's a ridiculous amount of travel.
I believe that the 5.2 stable release will have Monotonic back the way it was.  Besides the travel there is a lot of stringing caused by this motion.
I'll remove the bug label as this is Expected Behavior in 5.2beta.  Hopefully what I heard about reverting back to the previous motion will turn out to be true.  @MariMakes may have an update on that.

**Comment by MariMakes** [comment] 2022-10-17 09:46
Hey @frankygoop,

Thanks for the report 👍 
@GregValiant is right, it's a known error in monotonic on our side that has been resolved in https://github.com/Ultimaker/Cura/issues/13456

I checked our latest internal version and you can see the fix, and the immensive time save, on the right. 
![image](https://user-images.githubusercontent.com/40423138/196145691-3cd2a4df-5814-43c5-bfd4-a44fb8ddb5b8.png)

Your issue should be fixed in 5.2 Stable once it is released. 
Thanks again for the report 😄 
I'll be closing this issue.

**Closed by MariMakes** 2022-10-17 09:46 UTC
Labels: Type: Discussion, Status: Under Investigation
