### ISSUE TITLE
Cura generate tree supports in the air

### ISSUE THREAD

**Issue by Mascantosh** [Ultimaker/Cura#12835] opened 2022-07-23 00:02 UTC
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Creality Ender 5 

### Reproduction steps

All information in attachment project

### Actual results

![image](https://user-images.githubusercontent.com/38609392/180581654-28e54c5d-0acc-4e4d-a423-bebb3d7b4e18.png)

### Expected results

Airflow parts connected with bottom plate

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Airflow_bug.zip](https://github.com/Ultimaker/Cura/files/9172727/Airflow_bug.zip)
In attached project
Go to -> **Preview** and select 165 layer

**Comment by DerGenaue** [comment] 2022-07-23 15:47
Duplicate of #12326

**Comment by Vandresc** [comment] 2022-07-25 09:18
Indeed a duplicate, we will close this ticket. @Mascantosh pls check the duplicate for progress. Thank you!

**Closed by Vandresc** 2022-07-25 09:18 UTC
Labels: Type: Bug, Status: Triage
