### ISSUE TITLE
[3.2.1] Not able to open any STL file

### ISSUE THREAD

**Issue by rivalion** [Ultimaker/Cura#3649] opened 2018-04-11 00:12 UTC
Cura 3.21 Win 10 64bit

I've installed Cura 3.21, it is opening just normal, but when I try to open STL file the app is crushing. It does not matter if I try to open it from the app File menu, or by double clicking. I've tried couple of times reinstalling, but nothing helps.

[cura.log](https://github.com/Ultimaker/Cura/files/1896808/cura.log)

**Comment by Vandrasc** [comment] 2018-04-11 08:59
Hi @rivalion, the crash occurs each time you open ANY stl file? Or reproducible only with one file? If so, could you please share your model with us? Thank you!

**Comment by rivalion** [comment] 2018-04-11 10:15
Hi @Vandrasc I was not able to open any file, so I would say it's not related to a certain model. 
I.e. I've tried to open calibration cube from : www.thingiverse.com/thing:1278865

**Comment by LipuFei** [comment] 2018-04-11 11:26
Hi @rivalion , from the log, it seems to be a problem with file character encoding. Could you tell us which system language do you use on your Windows 10?

**Comment by fieldOfView** [comment] 2018-04-11 11:40
From the log, it looks like qhull is having an issue with the model, before the encoding issue.

**Comment by rivalion** [comment] 2018-04-11 12:25
@LipuFei I have an English version, but with keyboard set to polish layout - "Polski(progarmisty)"

**Comment by diegopradogesto** [comment] 2018-04-25 11:42
I have checked on windows and at least these characters can fail the code above:
`ę` or `ż` (probably some other characters too)

**Comment by LipuFei** [comment] 2018-04-25 11:44
Hi @rivalion , as @diegopradogesto described, I guess you have polish characters in your Windows username? Could you try using a username that only has ASCII characters? At the meantime, we will try to figure out a fix for this.

**Comment by LipuFei** [comment] 2018-04-25 12:36
For dev, JIRA ticket: CURA-5288

**Comment by LipuFei** [comment] 2018-05-02 09:55
Hi @rivalion, I think this problem is now fixed and the fix will be included in the next release. We have created a new testing build with this fix, could you try it out see if it works for you?
https://send.firefox.com/download/48a55ecc2b/#NG5fmL9AuhBzuR_KEsiy4Q

**Comment by LipuFei** [comment] 2018-05-22 08:38
@rivalion I am closing this issue now. If you still encounter the problem, feel free to reopen it.

**Closed by LipuFei** 2018-05-22 08:38 UTC
Labels: Category: Cura, Platform: Windows, Status: In Progress, Status: Needs Info, Type: Bug
