### ISSUE TITLE
With Cura 2.7 beta on MacOS, changing Views using the menubar does not always change

### ISSUE THREAD

**Issue by rtideas** [Ultimaker/Cura#2294] opened 2017-08-18 12:23 UTC
Switching Views back and front between X-ray and Solid using the menubar does not always update the view. Switching to Layers seems to help when switching back.

**Comment by Ghostkeeper** [comment] 2017-08-29 23:10
Not able to reproduce this using the 2.7 beta on Windows 8. It might be a MacOS-only issue here.

**Comment by ChrisTerBeke** [comment] 2017-09-28 08:35
Confirmed issue on my Mac.

**Comment by nallath** [comment] 2017-09-28 15:34
@ChrisTerBeke Did you also logged this on Jira?

**Comment by ianpaschal** [comment] 2018-07-30 14:20
Can no longer reproduce this; it appears to be fixed in Cura 3.4.1.

**Closed by ianpaschal** 2018-07-30 14:20 UTC
Labels: Platform: MacOS, Type: Bug

**Comment by rtideas** [comment] 2018-07-30 15:08
Thanks!
