### ISSUE TITLE
cann't load gcode file to print 

### ISSUE THREAD

**Issue by lyfbuaa** [Ultimaker/Cura#6314] opened 2019-09-06 09:31 UTC
now only view gcode file

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Affected users and/or printers**
 
**Additional context**

**Comment by Ghostkeeper** [comment] 2019-09-06 14:20
I've not been able to reproduce this. These were my reproduction steps:

1. Add Ultimaker 3 printer.
2. Load a model file (1cm cube in my case).
3. Save to g-code.
4. Restart Cura.
5. Connect printer via wifi to my physical printer.
6. Load previously saved g-code file.
7. Click on Print via Network.

The printer starts printing that cube then.

I have a couple of questions for you. What are your...

**Application version**


**Platform**


**Printer**


**Reproduction steps**


**Actual results**


**Expected results**


**Additional information**

**Comment by lyfbuaa** [comment] 2019-09-07 14:53
1.open cura 4.2.1 in pc
2.load .gcode file
3.no button to print

**Comment by Ghostkeeper** [comment] 2019-09-09 14:30
I'm still not able to reproduce that!

I opened Cura 4.2.1, added an Ultimaker S5 printer (because otherwise it won't let me open any .gcode file) and then dragged the .gcode file onto the build plate. I see a button to print:

![Screenshot from 2019-09-09 16-29-13](https://user-images.githubusercontent.com/2448634/64539663-68a29880-d30e-11e9-944f-3dc2eabf2981.png)

**Comment by lyfbuaa** [comment] 2019-09-10 01:03
sorry,I misreport it.
just I try again,the print button is there.

**Comment by Ghostkeeper** [comment] 2019-09-10 09:31
All right, so if the bug can't be found again I'll close it.

**Closed by Ghostkeeper** 2019-09-10 09:31 UTC
Labels: Status: Needs Info, Type: Bug
