### ISSUE TITLE
[4.0.0] Freeze/Hangs on splash screen

### ISSUE THREAD

**Issue by Deneteus** [Ultimaker/Cura#5348] opened 2019-02-22 21:18 UTC
**Application Version**
4.0.0

**Platform**
Windows 10 x64

![image](https://user-images.githubusercontent.com/6380390/53270331-158a3080-36b1-11e9-81f7-e68f9743f429.png)

![image](https://user-images.githubusercontent.com/6380390/53271748-f8576100-36b4-11e9-853a-50bb0fe7644e.png)

**Printer**
No printer is connected to the PC but it is set to Prusa Mk3.
I use Octoprint normally but this is a fresh install of 4.0
 
**Steps to Reproduce**
Opening the application causes it to load and freeze on splash screen.

![image](https://user-images.githubusercontent.com/6380390/53273337-643bc880-36b9-11e9-854e-732e88946f32.png)
****

**Expected results**
The application should not freeze on loading.

**Additional Information**
Version 3.6 was working fine prior to upgrading. 
Video of issue located here:  https://youtu.be/aA4oXi092uM

**Log Files:** 

I checked under roaming and found stderr and cura.log: 

Cura 4.0: [stderr.log](https://github.com/Ultimaker/Cura/files/2895902/stderr.log)
Cura 4.0: [cura.log](https://github.com/Ultimaker/Cura/files/2895903/cura.log)

![image](https://user-images.githubusercontent.com/6380390/53272899-212d2580-36b8-11e9-9510-013b04135759.png)

**Cura 3.6 LOG:** [cura.log](https://github.com/Ultimaker/Cura/files/2895948/cura.log)

**Event Viewer log:** 

The program Cura.exe version 0.0.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 53b0
 Start Time: 01d4caebb9acc38c
 Termination Time: 5
 Application Path: C:\Program Files\Ultimaker Cura 4.0\Cura.exe
 Report Id: 3a015046-2b29-4869-a034-bcc1619c0584
 Faulting package full name: 
 Faulting package-relative application ID: 

Log Name:      Application
Source:        Application Hang
Date:          2/22/2019 2:21:33 PM
Event ID:      1002
Task Category: (101)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:   
Description:
The program Cura.exe version 0.0.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 53b0
 Start Time: 01d4caebb9acc38c
 Termination Time: 5
 Application Path: C:\Program Files\Ultimaker Cura 4.0\Cura.exe
 Report Id: 3a015046-2b29-4869-a034-bcc1619c0584
 Faulting package full name: 
 Faulting package-relative application ID:

**Comment by Deneteus** [comment] 2019-02-23 04:20
After an extremely long time (hour and a half) I came back to the application open on the desktop even though the window had disappeared on the task bar. Clicking on Preferences and Materials and it Freezes up.

**Comment by Ghostkeeper** [comment] 2019-02-28 08:43
Nothing in the logs that is relevant to this :disappointed: 

![The logs, they tell me nothing](https://memegenerator.net/img/instances/69420300/the-logs-they-tell-me-nothing.jpg)

We've been getting similar reports via Reddit.

**Comment by Ghostkeeper** [comment] 2019-02-28 09:33
Could you try going to that same folder where you found the log, and editing the `cura.cfg` file with a text editor (while Cura is closed). Remove the preferences there that start with `window_` under the `[general]` category. Then start Cura, to see if the problem is fixed?

I'm wondering if this bug occurs when the preferences say to create a window which is smaller than the minimum size of the new GUI.

**Comment by Deneteus** [comment] 2019-03-02 22:15
@Ghostkeeper 

I used Sublime Text and searched for all the occurrences of 'window_' and found only a couple lines to delete. The only thing left was Window_State = 2. When I opened Cura 4 it still froze at 'Loading Interface...'

**Comment by Ghostkeeper** [comment] 2019-03-04 15:49
We're still unable to reproduce this freeze so far, at HQ :disappointed: Even with that .cfg file.

**Comment by AlanWhereAreYou** [comment] 2019-03-19 12:40
I am getting a similar problem: Typically Cura launches on my laptop in less than 30 seconds.

Recently though, sometimes the launch does not go smoothly:
- Sometimes it hangs in the background, no splash screen.
- Sometimes it gets a splash screen and correctly shows progress. In this case, you can see that it's progressing through the load steps but they are taking extremely long - over 10 minutes to launch.

Other notes of questionable accuracy:

- There appears to be a pattern where on first launch after reboot (even if the reboot was hours ago) Cura will launch properly. Then, at some point, it stops being happy and launches after that are slow.
- Usually killing the app and restarting doesn't help. Last time, though, I killed the app and shutdown my NIC, then relaunched at it seemed to be faster. 

I uninstalled and reinstalled. That didn't fix anything.
I'm Cura 3.6.0 up to date as of today on Win10.
I am going to try to grab log files etc.. next time it happens.

**Comment by AlanWhereAreYou** [comment] 2019-03-31 21:04
FYI, my problem turned out to be the "Frozen Path" issue described here: https://github.com/Ultimaker/Cura/issues/5534#issuecomment-478353058

**Comment by McNeight** [comment] 2019-05-29 13:48
This issue was the first hit in a search for 'cura 4.0 hangs' and for me, it was resolved by installing Cura 4.1 with the fix from #5534 in it.

**Comment by Ghostkeeper** [comment] 2019-05-29 14:22
That makes sense. Thank you for confirming.

**Closed by Ghostkeeper** 2019-05-29 14:22 UTC
