### ISSUE TITLE
Cura 5.0 unable to open or save files

### ISSUE THREAD

**Issue by Ismas** [Ultimaker/Cura#12317] opened 2022-05-22 20:16 UTC
### Application Version

5.0.0

### Platform

Ubuntu 20.04

### Printer

Creaty Ender 3

### Reproduction steps

Using last Appimage for linux x64.
On pressing the folder icon or File -> Open menu options nothing happens. File chooser will not open.
The same for file save on menu or "Save to disk" big button.

You can drag and drop stl files and they load OK, app is fully workable, but cannot export gcode so becomes unusable.
Previous 4.x versions worked like a charm.

There is not error or message on file open tries, just some warnings on run.

### Actual results

File open or save is not possible

### Expected results

Them working

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

 ./Ultimaker-Cura-5.0.0-linux.AppImage 
PyInstaller/loader/pyimod03_importers.py:495: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
Cyclic dependency detected between "file:///tmp/.mount_Ultima4ADbqM/share/cura/resources/qml/Actions.qml" and "file:///tmp/.mount_Ultima4ADbqM/share/cura/resources/qml/Actions.qml"
QQmlEngine::setContextForObject(): Object already has a QQmlContext

**Comment by chipmunk1977** [comment] 2022-05-23 07:20
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11874
The devs are working on it.

**Closed** 2022-05-23 09:08 UTC
Labels: Type: Bug
