### ISSUE TITLE
Ubuntu 15.04 - Cura crashes with a segfault

### ISSUE THREAD

**Issue by danilius** [Ultimaker/Cura#503] opened 2015-10-22 19:58 UTC
I have Ubuntu 15.04 installed, and Cura crashes with a segfault, although the splashscreen does show up for a moment, as well as the changelog window, and then everything disappears

I have python3-opengl installed, but that does not seem to be the problem.

I do have Nvidia drivers installed, version 346.96.

Output from the command line can be found here: http://daniepstein.com/daniepstein/wp-content/uploads/2015/10/cura-crash-report.txt

**Comment by daid** [comment] 2015-10-23 07:14
This should be fixed in the latest beta:
http://software.ultimaker.com/Cura_closed_beta/15.10/?C=M;O=D
(odd conflict between Mesa development packages and the driver on Ubuntu)

**Comment by danilius** [comment] 2015-10-23 07:16
Sadly no.

**Comment by awhiemstra** [comment] 2015-10-23 08:26
"QOpenGLShader: could not create shader" that does suggest your 3D support fails to load properly or is broken. Can you provide the output of glxinfo ?

**Comment by danilius** [comment] 2015-10-23 09:32
You can find it here: http://daniepstein.com/daniepstein/wp-content/uploads/2015/10/glxinfo_output.txt

**Comment by danilius** [comment] 2015-11-01 11:04
Has there been any progress on this issue? I have researched this myself but go nowhere. It's not really my field.

**Comment by Ghostkeeper** [comment] 2015-11-02 09:09
We haven't reproduced this yet. Not on Ubuntu with Intel drivers at least. We have a testing computer with NVidia and Ubuntu, it could be tried there.

**Comment by TMHogenhout** [comment] 2015-11-02 09:16
@danilius  Which version of Cura are your using?

**Comment by danilius** [comment] 2015-11-02 11:18
15.09.91

**Comment by danilius** [comment] 2015-12-11 10:21
Solved it. I modified the beginning of cura_app.py to read as follows:

#!/usr/bin/env python3

# Copyright (c) 2015 Ultimaker B.V.
# Cura is released under the terms of the AGPLv3 or higher.

import sys
from OpenGL import GL

**Comment by Ghostkeeper** [comment] 2015-12-14 08:36
Oh, good job! I wonder though why cura_app.py would need OpenGL though, since there is no direct reference to it there. Perhaps the problem is better solved when importing OpenGL in different files.

**Comment by daid** [comment] 2015-12-14 08:49
https://github.com/Ultimaker/Cura/blob/master/cura/CuraApplication.py#L57

**Comment by danilius** [comment] 2015-12-14 11:25
I will give that a whirl when I have a moment and see if that works.

**Comment by thopiekar** [comment] 2016-01-14 17:08
@Ghostkeeper: I also think it should be moved into Uranium.
I remember I also reported about this segfault already, but closed it as I thought it is KDE related, so as I was working with my notebook with Intel graphics I was sure it is fixed now.

However, as far as I understand PyQt5 as a Qt5 binding, it shouldn't depend on Python-OpenGL. So what I believe is that Python-OpenGL has something in __init__ that prepares the hardware to work, what Qt5 doesn't seem to do. So the only true solution to this problem is to remove this dirty fix and fix it the PyQt5 way.

**Closed** 2016-09-19 21:48 UTC
Labels: bug, duplicate, OS: Linux, release: old
