### ISSUE TITLE
Multiplying Bug

### ISSUE THREAD

**Issue by jjjjjjj687** [Ultimaker/Cura#10995] opened 2021-12-03 00:50 UTC
### Application Version

4.12.0

### Platform

Mac, MacOS Monterey.

### Printer

Ender 3

### Reproduction steps

First, I put a whatever I wanted to print down, then I try to multiply it.

### Actual results

It just says "Placing objects, Multiplying and placing objects" and the progress bar does not move at all, I sometimes even wait 5 minutes but still it does not work.
<img width="451" alt="Screen Shot 2021-12-02 at 7 47 22 PM" src="https://user-images.githubusercontent.com/84553051/144525838-c178747c-8408-4409-a0a8-e40840ffdb9d.png">

### Expected results

It should just take a moment on a slow computer, and it multiplies.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I used to work on the same computer, but I don't remember when, it just stopped working, I think because of an update.

**Comment by fvrmr** [comment] 2021-12-03 08:02
Hi @jjjjjjj687 thank you for your report.
This is a duplicate of: #10249. And this is fixed in 4.12.1: https://ultimaker.com/software/ultimaker-cura
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-12-03 08:02 UTC
Labels: Type: Bug

**Comment by jjjjjjj687** [comment] 2021-12-03 22:47
Thanks
