### ISSUE TITLE
Horizontal extension / first layer

### ISSUE THREAD

**Issue by Bersaker** [Ultimaker/Cura#12677] opened 2022-07-06 09:53 UTC
### Application Version

5.1.0

### Platform

Win 10

### Printer

Ender 3V2

### Reproduction steps

Hello,
horizontal extension and horizontal extension first layer are swapped.

### Actual results

-

### Expected results

-

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![2](https://user-images.githubusercontent.com/62776321/177523547-bda89bd2-0d33-4ec7-a632-18a4a19e4cd7.jpg)
![1](https://user-images.githubusercontent.com/62776321/177523551-19937700-e1f1-4ea3-be60-65f5f6ec7a39.jpg)

**Comment by GregValiant** [comment] 2022-07-07 00:43
Nice eye.  It took me a few minutes of playing around to notice that's what it was doing.
#12685 is a duplicate of this one.  Someone from the Cura team will take a look (@Joeydelarago ?)

**Comment by Ergonomicmike** [comment] 2022-07-09 23:49
I thought it was not picking up the negative sign. That is, if I set a positive number for horizontal expansion, then I get the result that I expected. (The bottom layer is smaller than the others.) But I didn't measure to see which layer changed.  (Because the Measure Tool doesn't work for me in Beta 5.1.0 304.)

**Comment by MIOsystems** [comment] 2022-07-14 17:47
100% confirmed. How in the name of science have this could happened!? Took 2 hours of my life to discover such an ridiculous mistake.

**Comment by GregValiant** [comment] 2022-07-14 18:07
From what I've read - two variables got swapped.  Kind of a glorified typo.  It will be fixed in 5.1 stable.
This is the sort of thing that points out why it's important for users to spend some time with the beta releases.  The more eyeballs involved the more thorough the de-bugging is.  In this case everything in the software worked correctly but the results were wrong.  For the most part people had to print something and really look at it before getting a "Hey, wait a minute..." moment.

**Comment by MIOsystems** [comment] 2022-07-15 10:07
Got it. Sorry for the frustration. Mainly caused by new GUI features i hate. As an engineer i like it technical but simple. Not fancy and shinny. The smooth scrolling is a good example. Or fading unfold actions on menus and lists. Only implemented for fancyness and to annoy powerusers. Looking forward to have a forked CURA for engineers

**Closed** 2022-07-15 12:30 UTC
Labels: Type: Bug, Status: Under Investigation

**Comment by MIOsystems** [comment] 2022-07-17 07:25
You totally right for the BETA. Sorry for the incrustation. But my time is to expensive too deal with others software issues.

#12272 is good example of GUI implementations annoys me. Why is this implemented?
