### ISSUE TITLE
Unable to slice

### ISSUE THREAD

**Issue by JonyPlay5561** [Ultimaker/Cura#11365] opened 2022-01-28 18:21 UTC
### Application Version

4.13.1

### Platform

Windows 10

### Printer

Tevo Tarantula Pro

### Reproduction steps

1. I downloaded the Model and put it in the Ultimaker cura.
2. I changed to 0.2 mm and gave a slice
It wrote me:
Unable to slice witch the current settings. The following settings have errors: Z hop speed
3. I went to hop speed settings from
and when I changed it from 10 to 15, it certainly wrote to me:
Unable to slice witch the current settings. The following settings have errors: Z hop speed
 
Please fix it otherwise I will not be able to use your buggy program.

Well thank you.

### Actual results

it certainly wrote to me:
Unable to slice witch the current settings. The following settings have errors: Z hop speed
 
Please fix it otherwise I will not be able to use your buggy program.

Well thank you.

### Expected results

give me the option to save it in G-code and instead wrote:
Unable to slice witch the current settings. The following settings have errors: Z hop speed

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7960929/cura.log)
![TTPRO_wrist_connector - Ultimaker Cura 28  1  2022 18_52_00](https://user-images.githubusercontent.com/98610577/151600809-dd36e07a-89f8-4bfa-98e4-3da958ed1f47.png)
![TTPRO_wrist_connector - Ultimaker Cura 28  1  2022 18_51_50](https://user-images.githubusercontent.com/98610577/151600816-0a887e8f-a442-4451-b639-9061872a362c.png)

**Comment by fvrmr** [comment] 2022-01-31 11:04
Hi @JonyPlay5561 thank you for your report.
Changing the value to 1.5 should help you to slice.
This is also a duplicate of https://github.com/Ultimaker/Cura/issues/10083 but this was fixed before, so I will bring it up for discussion with the team. Keep you posted.

**Closed** 2022-02-01 10:36 UTC
Labels: Type: Bug
