### ISSUE TITLE
Duplicate parts does not work

### ISSUE THREAD

**Issue by neofuture** [Ultimaker/Cura#10758] opened 2021-11-07 13:34 UTC
### Application Version

4.11

### Platform

macOS m1

### Printer

CR10/Ender3

### Reproduction steps

Select object, select "Multiply Selected" change the number in the dialog, press ok, and the progress bar shows but does nothing more

### Actual results

Stuck progress bar and no multiplication

### Expected results

Multiplication of items

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

does not need files

**Comment by fieldOfView** [comment] 2021-11-07 13:38
Duplicate of #10249

**Closed** 2021-11-07 13:51 UTC
Labels: Type: Bug, Status: Duplicate
