### ISSUE TITLE
Acceleration Tower Problem

### ISSUE THREAD

**Issue by fabiobarros79** [Ultimaker/Cura#15328] opened 2023-04-22 20:55 UTC
### Application Version

5.2.2

### Platform

Windows 10 Pro

### Printer

Ender 3 S1 Pro

### Reproduction steps

Open Cura
Extensions
Part for Calibration
Add an Acceleration Tower
Select the piece by clicking on it.
Press R to rotate
Press blue arrow to change orientation (to match X of piece with X ok printer)

At this point, if I click on slice

This error appears

![image](https://user-images.githubusercontent.com/39351670/233805877-232e8b5f-9260-4b10-9389-3916f08be884.png)

If I don't change the orientation, there's no problem.

### Actual results

Slicing error

### Expected results

Normal slicing

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/11302264/cura.log)
[Error project.zip](https://github.com/Ultimaker/Cura/files/11302265/Error.project.zip)

**Comment by GregValiant** [comment] 2023-04-22 23:41
Thanks for the report and the files.
I can't get the model to "not slice" so I'm unable to duplicate the problem.
The plugin was written by @5axes so you might want to give him a heads-up on his GitHub page.
There have been several other reports of Cura having trouble slicing models and this may be a duplicate of that bug rather than something wrong with the plugin.  I'll mark this as a slicing error and I'm sure both the Cura team and 5Axes will take a look.

**Comment by 5axes** [comment] 2023-04-23 17:58
https://github.com/5axes/Calibration-Shapes/issues/106

**Comment by fabiobarros79** [comment] 2023-04-23 18:16
Hi there,

I Just updated to Cura 5.3 and the problem was solved.

Thank you very much.

**Comment by GregValiant** [comment] 2023-04-23 18:51
@fabiobarros79 I'll go ahead and close this as the new version seems to be the fix.  Let me know if you think that is premature.

**Closed by GregValiant** 2023-04-23 18:51 UTC
Labels: Status: Under Investigation
