### ISSUE TITLE
Cura Poor Performance with Material Station

### ISSUE THREAD

**Issue by StephWoodhouse** [Ultimaker/Cura#12617] opened 2022-06-27 11:33 UTC
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

Setup
Ultimaker S5 + Material Station as host, connected to second Ultimaker S5 + Material Station & UM3E

Open Cura and leave open for short period

### Actual results

Software lags with every input, unusable until application is closed and reopened. Issue repeats after short period.

### Expected results

The software actually being usable

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

The PC used has ran Cura without issue before, error has only occurred since getting material stations.

**Comment by fieldOfView** [comment] 2022-06-27 21:01
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11608. That does not mean that this is not a problem that needs to be fixed, but we need to keep discussions centralized.

**Closed by fieldOfView** 2022-06-27 21:01 UTC
Labels: Type: Bug, Status: Triage
