### ISSUE TITLE
3.5.1 - Overlapping issue 

### ISSUE THREAD

**Issue by amagr0** [Ultimaker/Cura#4632] opened 2018-10-22 16:37 UTC
**Application Version** - CURA 3.5.1
**Platform** - Win 10 Pro, 64 bit
**Display Driver** - NVIDIA GeForce 840M

**Steps to Reproduce** - Open Cura Project; analyse the toolpath - 1st layer.

**Actual Results** - There's a strange overlap situation in the initial layer.
![screenshot_1](https://user-images.githubusercontent.com/12901952/47304872-c4453400-d61f-11e8-884c-8016a7856d26.jpg)

![screenshot_3](https://user-images.githubusercontent.com/12901952/47304902-d626d700-d61f-11e8-9ba3-0985cb4e91f3.jpg)

And is also strange the way toolpath is generated. 
From the left to center, it prints on this way.
![screenshot_2](https://user-images.githubusercontent.com/12901952/47304883-cb6c4200-d61f-11e8-8831-83917cb0e003.jpg)

And then, from the center to the right it prints on a completely different way.
![screenshot_4](https://user-images.githubusercontent.com/12901952/47304896-d2935000-d61f-11e8-8873-f7a58b51dbc8.jpg)

Since this section of the print is symmetrical, the expected result should be the same.

There's also other sittuations on the same gcode:
![screenshot_7](https://user-images.githubusercontent.com/12901952/47305272-da9fbf80-d620-11e8-8675-fd3677559d34.jpg)
![screenshot_6](https://user-images.githubusercontent.com/12901952/47305279-dd9ab000-d620-11e8-8174-d64e34a5482b.jpg)

**Comment by smartavionics** [comment] 2018-10-22 17:38
Yes, I think they know about this breakage.

**Comment by Ghostkeeper** [comment] 2018-12-31 09:31
The case of it behaving not symmetrically is because the lines aren't aligned symmetrically. It's sort of expected behaviour. Your piece may be symmetrical over the Y axis, but the lines aren't; they are shifted.

The blob in the corner has since been fixed.

The overlapping situation still exists even after our recent refactors in this case. It happens because it finds two short lines very close to each other that can be merged together. It doesn't do any form of detection of whether there is a line in between (as that would be very expensive).

I don't think we are able to fix this elegantly. It happens in few enough cases and with small enough consequences that I think we should accept the overlaps as-is.

**Closed by Ghostkeeper** 2018-12-31 09:31 UTC
