### ISSUE TITLE
Temps done before Start Gcode

### ISSUE THREAD

**Issue by kr15uk** [Ultimaker/Cura#1675] opened 2017-04-11 13:54 UTC
Ladies and gents,

I need M80 (power on) command to be initiated **before** it kicks in heaters.
If I add M80 to my start-gcode, final gcode has M190,M104, M109 and only then goes M80...
Obviously no M80 = no 12v and no 12v = no power to the heaters...

Is there a chance to add M80 aka PS_ON tickbox in machine settings for the future releases?
Is there a workaround for the time being like editinh json file or so?!
Thanks.

I've attached 2x screenshots. 1st start-gcode in Cura, 2nd final gcode.

Thanks.

<img width="316" alt="screen shot 2017-04-11 at 14 53 09" src="https://cloud.githubusercontent.com/assets/5671041/24912669/b72ed594-1ec6-11e7-984f-d360c2f34970.png">

![screen shot 2017-04-11 at 14 53 27](https://cloud.githubusercontent.com/assets/5671041/24912676/be52580a-1ec6-11e7-8e51-a36d09b64399.png)

**Comment by fieldOfView** [comment] 2017-04-11 14:26
CuraEngine detects if your start gcode sets the temperatures. If it doesn't (like in your case), it adds them before the start gcode in the final gcode file.

Make sure you include M190 S{material_bed_temperature} and M104 S{material_print_temperature} in your start gcode (after the M80 line) and CuraEngine will not put them in the gcode before the start gcode.

**Comment by BagelOrb** [comment] 2017-07-23 11:59
Duplicate of https://github.com/Ultimaker/Cura/issues/1657

**Closed by BagelOrb** 2017-07-23 11:59 UTC
Labels: bug, component: CuraEngine
