### ISSUE TITLE
Extended Desktop

### ISSUE THREAD

**Issue by eric-the-eye** [Ultimaker/Cura#12119] opened 2022-05-06 14:12 UTC
### Application Version

5.0 Beta + 1

### Platform

Windows 10 64 bit

### Printer

Ender 5

### Reproduction steps

Start Cura 5.0 beta

### Actual results

Cura splash screen starts on 2nd monitor of extended desktop before application opens on 1st monitor
Action and confirmation messages also display on 2nd monitor

### Expected results

Should start and display messages on monitor 1 unless application moved to monitor 2

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

None

**Comment by MariskaMaas** [comment] 2022-05-24 15:43
Hi @eric-the-eye, thanks for reporting this issue. 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12102
But you will read in there that the issue has been deferred. 

We are constantly working on making Ultimaker Cura better. Our community is a big part of that by requesting new features and reporting bugs. To be able to focus on the most requested and needed features and bug fixes from our community and from Ultimaker, we have decided that it has no priority for us to fix or implement this, therefore we decided to defer this.

I hope you understand.

**Closed by MariskaMaas** 2022-05-24 15:43 UTC
Labels: Type: Bug
