### ISSUE TITLE
Cura cannot produce circles nor smooth curves rather it produces segmented straight lines poorly mimicking a curve.

### ISSUE THREAD

**Issue by DDG127** [Ultimaker/Cura#15577] opened 2023-05-21 21:26 UTC
### Application Version

5.3.1

### Platform

windows 10

### Printer

Tronxy x5sa/x5st/Pro400

### Reproduction steps

Saved a 3d file with the extension .3mf [obj files are even worse], inspected the file and noted RIBS in the curvature areas.  I have attached a png snapshot pointing out the flaws.

### Actual results

When printed these ribs are very pronounced.  How can I get a smooth curve?

### Expected results

Smooth curves, no ribs.  I know that the printer is capable of printing smooth curves.  I cannot get this to work.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Vent cover.zip](https://github.com/Ultimaker/Cura/files/11525589/Vent.cover.zip)
![Vent](https://github.com/Ultimaker/Cura/assets/109562336/f187e0c9-a43e-4074-99eb-b37f6d33791c)

**Comment by GregValiant** [comment] 2023-05-21 23:52
Thanks for the report.
There are no circles if a computer is involved.  PI has been calculated to 30 trillion decimal places so there are always chords.  
The facets you see on a model are from the translation into STL or 3mf, OBJ, etc. from the software the model was developed in.  You can increase the resolution within the CAD-to-STL translation software but only up to a point.  Cura just gets the model as it exists.  If the model is low resolution there are large facets.  If it is high resolution there are smaller facets.  The G2 and G3 commands turn circles over to the firmware.  Marlin has a setting for "Minimum Arc Segment Size" that sets the limit for each line segment that makes up (what looks like) a circle or radius.

So there is no bug here and I'll remove the label and close this.

**Closed by GregValiant** 2023-05-21 23:52 UTC
Labels: Type: Discussion

**Comment by DDG127** [comment] 2023-05-22 00:40
Minimum Arc Segment Size - Is there a setting to adjust in Fusion 360?  I looked again in Fusion 360, I don't see it. 
I have seen 3D printers create perfect circles.

**Comment by GregValiant** [comment] 2023-05-22 01:19
They only look like perfect circles, they are still a bunch of line segments.  The shorter the line segments the more precise the circle.
When you export the model from Fusion there should be options.  In AutoCad it's "FacetRes" but I don't know Fusion.
The screenshot below shows the same model but the left was exported at hi-res and the right was exported at low res.  You can see that the facets are much larger on the low res model.  The Mesh that each model consists of is made up of triangles.  Triangles don't have curved sides.
![image](https://github.com/Ultimaker/Cura/assets/64202104/620fa31e-29d4-4a03-a8f2-9a37b9e423cf)

**Comment by DDG127** [comment] 2023-05-22 01:48
Thank you for your help.  I will look into this. and hopefully get better at printing.

**Comment by DDG127** [comment] 2023-06-03 15:19
I'm sorry to bother you again, but I have used my 3D CAD files with another slicer and the curves are smooth and seamless.  I use the same file with CURA and there are obvious segments.  This appears to be a CURA problem and nothing to do with the CAD software as described above.  Please look at this again.

**Comment by GregValiant** [comment] 2023-06-03 20:30
No slicers have the capability to change a models resolution.  It is what it is and is built into the model file.
Below are several pieces of software showing  your Vent model.  The facets are the same in all of them.  No slicer can change that as it can only slice the geometry that it is given.
There is no "AI" built into any slicer that can say "Well this looks like it should be an arc so I'll make it an arc".  All curves are a collection of straight lines.  Circles only exist as polygons with a lot of sides.  How would a slicer be able to decide that your 12 sided dodecahedron should really have 200 sides so it looks more like a circle?  What if you actually wanted the 12 sided print?

This is your vent in Prusaslicer.  
![image](https://github.com/Ultimaker/Cura/assets/64202104/583f64eb-c0e0-4d94-b2a9-04d2fed89f09)

This is a screenshot from Cura
![image](https://github.com/Ultimaker/Cura/assets/64202104/e4534df2-b696-467e-8b45-64f8663b0607)

This shot is from IdeaMaker
![image](https://github.com/Ultimaker/Cura/assets/64202104/10f9c773-d552-4941-9919-d12e1e5786df)

This one is from MS 3D Builder.  I was able to paint the facets so they are more obvious.
![image](https://github.com/Ultimaker/Cura/assets/64202104/14023b7c-7c0e-4fd3-a5b1-774a82ad8815)

And this one is from Bambu Studio
![image](https://github.com/Ultimaker/Cura/assets/64202104/6d515fc9-e068-46a3-80d0-ce4f42f4e5e0)

Here is a comparison of two STL's in Cura.  They are of the same model.  The model on the left was exported from AutoCad at the highest resolution I can get and the right model is at low resolution.  The right model is highly faceted because that's the way the model is represented within the STL file.
![image](https://github.com/Ultimaker/Cura/assets/64202104/0c77faf5-1e04-4214-95f3-55531e9b9bf1)

Here are the same two models in PrusaSlicer.  The problem is identical.
![image](https://github.com/Ultimaker/Cura/assets/64202104/4734006a-204b-482a-912d-0ab6b5de2ad6)

I can re-open this if you want, but I really don't see anything that can be done from a slicer point of view.  You can call it a bug if you like, but if fixing the problem is the crux of the matter then I think you need to look at how your models are exporting and what the settings are.

I've been working with CAD software since the late 1970's.  There are tricks you can do in CAD to change the resolution of an export.  There is nothing that can be done to increase a models resolution once the export file is created because the actual model is required to do so and that actual model only resides in the CAD software.
