### ISSUE TITLE
STL Files can not open

### ISSUE THREAD

**Issue by Vito540** [Ultimaker/Cura#9877] opened 2021-05-20 07:05 UTC
### Application Version

4.9.1

### Platform

Window 10

### Printer

Deltacomb DC-30

### Reproduction steps

1. Unstall software V4.7
2. Install V4.9.1
3. Restart computer
4. Open  Ultimaker Cura 4.9.1 
5. Ctrl + O，open old files

### Actual results

Computer log 3sec , then show up " No Response" and shut down directly.

### Expected results

Load STL files correctly.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![error1](https://user-images.githubusercontent.com/33221600/118934249-bcd39c00-b97c-11eb-9e53-6251692de3b9.png)
![error2](https://user-images.githubusercontent.com/33221600/118934258-bf35f600-b97c-11eb-905d-c73023baec67.png)

**Comment by fvrmr** [comment] 2021-05-20 09:05
Hi @Vito540 thank you for your report.
This is a duplicate of #9668 there you can find a workaround to solve this issue.
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-05-20 09:05 UTC
Labels: Type: Bug
