### ISSUE TITLE
Delete key on mac not working on selected model

### ISSUE THREAD

**Issue by meeroczz** [Ultimaker/Cura#5544] opened 2019-04-01 07:22 UTC
**Application Version**
4.0.0

**Platform**
mac mojave

**Printer**
tevo tarantula

**Steps to Reproduce**
when slicing model, and then trying to delete it when selected,
the delete key does not delete model. I have to right click and select delete

**Actual Results**
after pressing delete key the model does not get deleted

**Expected results**
deletion of model after pressing the delete button on keyboard

**Additional Information**
... not needed.

**Comment by Ghostkeeper** [comment] 2019-04-01 13:39
Duplicate of #5198.

**Closed by Ghostkeeper** 2019-04-01 13:39 UTC
