### ISSUE TITLE
Slicing issue (?) printer moves to corner and extrudes filament

### ISSUE THREAD

**Issue by osterac** [Ultimaker/Cura#4707] opened 2018-11-01 16:41 UTC
Sometimes when I try to print with my Creality Ender 4 my printer will, after heating and homing, move to the opposite corner (while slightly adjusting the z axis) and extrude massive amounts of filament until I cancel the print (SD card) or unplug it (printing from USB - abort print doesn't work). if I'm printing from USB, Cura will then crash.
[v beam x2.zip](https://github.com/Ultimaker/Cura/files/2539261/v.beam.x2.zip)

**Application Version**

3.5.1
**Platform**

Windows 10 x64
**Printer**

Creality Ender 4
**Steps to Reproduce**

Seemingly random occurrence upon printing a project
**Actual Results**

 my printer will, after heating and homing, move to the opposite corner (while slightly adjusting the z axis) and extrude massive amounts of filament until I cancel the print (SD card) or unplug it (printing from USB - abort print doesn't work). if I'm printing from USB, Cura will then crash.
**Expected results**

Normal print of my project
**Additional Information**

**Comment by smartavionics** [comment] 2018-11-01 17:11
I sliced your project and looked at the gcode (using craftware) and I can't see any obvious reasons for the behaviour you describe. Here's the first layer:

![screenshot_2018-11-01_17-07-37](https://user-images.githubusercontent.com/585618/47867304-0bd67780-ddf9-11e8-9a6a-9d752f1eaa90.png)

**Comment by osterac** [comment] 2018-11-02 14:30
Well I hope it's not my printer... If it is, it's something that's only started recently.

**Comment by osterac** [comment] 2018-11-02 14:31
It's happened with other projects too

**Comment by Ghostkeeper** [comment] 2019-02-05 10:54
I'm also unable to reproduce this, even with your project file. Maybe this was fixed in a more recent version?

**Comment by osterac** [comment] 2019-02-06 23:45
It may have been something with the firmware. I've since stopped using the stock firmware and switched to straight Marlin with my printer's parameters added. I've had no problems like this since.

**Closed** 2019-02-06 23:45 UTC
Labels: Status: Needs Info
