### ISSUE TITLE
Rather than "Drop (All) objects to build plate", could it be "Default [Drop object to build plate] Y/N" ?

### ISSUE THREAD

**Issue by dwendooley** [Ultimaker/Cura#11586] opened 2022-03-02 19:50 UTC
### Is your feature request related to a problem?

I'm always frustrated when I have to turn off "drop object to build plate" if I'm using "modify object for overlap" with objects to strengthen parts (for instance, arms, heads, etc, 

### Describe the solution you'd like

I would like to see the edit setting allow us to choose a "Default" for object dropped to build plate, and have "drop to build plate" be a check/uncheck feature of each individual object. Presumably on the right-click menu for the object.

### Describe alternatives you've considered

When moving numerous objects around the build plate it'd be nice for certain objects to automatically drop to build plate always, and others to not be forced to. I like to use overlap objects to get custom supports, change infill density or number of walls to strengthen sections, etc,.  Definitely can be an issue to move stuff around and be careful not to move the original above the build plate while rearranging. 

### Affected users and/or printers

All object placement.

### Additional information & file uploads

Nah, you get me.

**Comment by fvrmr** [comment] 2022-03-07 15:40
Hi @dwendooley thank you for your request.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/8117 and we have a ticket on our backlog for this, since it is indeed a bit confusing and not working optimal. 
I will close this issue, since it is a duplicate.

**Closed by fvrmr** 2022-03-07 15:40 UTC
Labels: Type: New Feature
