### ISSUE TITLE
file size

### ISSUE THREAD

**Issue by nodrognosduh** [Ultimaker/Cura#1956] opened 2017-06-09 17:37 UTC
i can't open a file bigger than 500 megs.....

**Comment by Ghostkeeper** [comment] 2017-06-10 23:53
What happens when you try to open such files? Do you get an error message? Blue screen of death? Does your mouse arm get cramps? 

I just tried loading an 1.8GB file: A sphere generated in OpenSCAD using `sphere(r=40, $fn=3000);` It loaded eventually, but it took some time to get there (492s according to the log) and after loading it the frame rate dropped considerably. It then proceeded to slice in 11s. Because the slicer just collapses vertices that are too close for the resolution of the engine to handle.

**Comment by nallath** [comment] 2017-06-12 09:47
Also note that if a file is that big, it will probably contain details that get ignored by the engine in the first place.

**Comment by nodrognosduh** [comment] 2017-06-12 14:54
I just get an error message saying “can’t open file”
 
Gordon Hudson
Mech. Engineer
 

Handi Quilter, Inc.
501 North 400 West
North Salt Lake, UT 84054
Phone: 801 335-0848
Fax: 801.335.0843
www.handiquilter.com

**Comment by Ghostkeeper** [comment] 2017-06-23 07:17
Perhaps there is something in the log then. We provide more detailed error messages there.

**Comment by ianpaschal** [comment] 2018-05-22 14:51
Needs info; never got it; not reproducible, closing.

**Closed by ianpaschal** 2018-05-22 14:51 UTC
Labels: Type: Bug
