### ISSUE TITLE
Setting Panel

### ISSUE THREAD

**Issue by Vaibhavkhakkar** [Ultimaker/Cura#11103] opened 2021-12-21 16:27 UTC
### Application Version

4.12.1

### Platform

Windows 10

### Printer

Creality Ender 5

### Reproduction steps

Setting box not expanding. 

### Actual results

Setting box not expanding. 

### Expected results

Setting box not expanding. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Setting box not expanding.

**Comment by fvrmr** [comment] 2021-12-22 13:29
Hi @Vaibhavkhakkar thank you for your report.
Could you maybe share a screenshot/video of what is happening? 
And could you also share your log file? You can find your log file here: `C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`

**Comment by Ghostkeeper** [comment] 2021-12-30 15:21
Duplicate of https://github.com/Ultimaker/Cura/issues/5527.

**Closed by Ghostkeeper** 2021-12-30 15:21 UTC
Labels: Type: Bug, Status: Needs Info
