### ISSUE TITLE
[OS X] hidpi difficult to rotate

### ISSUE THREAD

**Issue by ErikDeBruijn** [Ultimaker/Cura#28] opened 2015-06-05 07:09 UTC
As a user, when trying to rotate the object, I'd like it to be clear and easy to do this. It's pretty hard to see the highlight on hidpi (e.g. Retina) screens, because the circles are very thin (single pixel). Also, grabbing the line is equally hard.

If the lines would be thicker that would really make things easier.

![image](https://cloud.githubusercontent.com/assets/191236/8001044/1856a812-0b62-11e5-8952-f0be43a14292.png)
Tested with OS X 10.10.3 

How to test:
 1. Find a retina Macbook
 1. Load .63 version of Cura
 1. Load a model
 1. Click on rotate
 1. Get the mouse exactly where in should be (this is the hard part)

**Comment by nallath** [comment] 2015-06-05 09:57
Could you use the template as found on https://github.com/Ultimaker/Uranium/wiki/Bug-Reporting-Template next time? This makes it a lot easier for us to quickly scan through issues.

**Comment by ErikDeBruijn** [comment] 2015-06-06 07:07
Will try whenever I have more time. This was in between being meetings.

**Comment by awhiemstra** [comment] 2015-06-24 11:04
So in the upcoming build I have improved the rendering of lines to account for screen DPI. On my hi-dpi testing machine that fixes this issue, but please do test once the new build (.96) is available.

**Comment by BagelOrb** [comment] 2015-07-03 15:10
I suppose the issue is fixed now.

**Closed by BagelOrb** 2015-07-03 15:10 UTC
