### ISSUE TITLE
Need a Setting for 'Overhanging Wall Fan Speed'

### ISSUE THREAD

**Issue by rachael7** [Ultimaker/Cura#11529] opened 2022-02-23 01:58 UTC
### Is your feature request related to a problem?

When printing high temp materials like Nylon and Polycarbonate, it is recommended not to use the part cooling fan(s), since it negatively impacts layer adhesion. However, not using the part cooling fan(s) negatively impacts print quality on overhangs, even when the overhang is relatively minor, like 20 degrees off vertical. Using support on such gentle overhangs is expensive, time-consuming, and just not that practical. Allowing the Cura profile to specify a different fan speed for overhangs would improve the appearance of overhangs, while minimizing the impact on layer adhesion in the rest of the part.

### Describe the solution you'd like

There is currently an experimental setting for Overhanging Wall Speed that reduces speed based on the setting of Overhanging Wall Angle. I would like to see a setting for Overhanging Wall Fan Speed that is also based on a wall angle setting.

### Describe alternatives you've considered

I have attempted using speed reductions on the overhangs, as well as optimizing layer thickness, nozzle size, and line widths. Reducing speed helped somewhat, but not enough to produce prints of the quality the machine is capable of.

### Affected users and/or printers

Anyone using materials which prefer to print without a fan, including ABS, Nylon, Polycarbonate, etc is affected by this problem.

**Comment by fvrmr** [comment] 2022-02-24 12:09
Hi @rachael7 thank you for your request.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/5140 and we have a ticket on our backlog for this.
I will close this issue since this is a duplicate.

**Closed by fvrmr** 2022-02-24 12:09 UTC
Labels: Type: New Feature
