### ISSUE TITLE
macOS Big Sur and Cura 4.8 - unable to add modifiers

### ISSUE THREAD

**Issue by davidewen** [Ultimaker/Cura#9403] opened 2021-03-14 18:03 UTC
### Application Version

4.8.0

### Platform

macOS Big Sur

### Printer

Prusa MK3s

### Reproduction steps

I am unable to add any type of modifier or custom support

### Actual results

I am unable to add any type of modifier or custom support

### Expected results

I expect to be able to add modifiers and/or custom supports

**Comment by fvrmr** [comment] 2021-03-15 13:31
Hi @davidewen thank you for your report.
This a duplicate of #8745.
We are working on a solution and we already have done a test build that will fix this problem. Progress with the upgrade of the Qt version is still ongoing. There are other crashes still to solve now.

Because this is a duplicate I will close this issue.

**Closed by fvrmr** 2021-03-15 13:31 UTC
Labels: Type: Bug
