### ISSUE TITLE
Weird slice error

### ISSUE THREAD

**Issue by Shakansis** [Ultimaker/Cura#14217] opened 2023-01-06 00:29 UTC
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Creality Ender 3 V2

### Reproduction steps

1. import the .stl file
2. click on the slice button

### Actual results

The slice begins and with approximately 30% it returns with an error message.

### Expected results

Slice complete and I am able to print the GCODE

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10356466/cura.log)

**Comment by ThomasRahm** [comment] 2023-01-06 04:43
This part of the log suggests to me that this crash could maybe come from the tree-support code for some reason:
`2023-01-05 21:17:34,270 - DEBUG - [EngineOutputThread] UM.Backend.Backend._backendLog [115]: [Backend] [2023-01-05 21:17:34.270] [info] Processing support tree mesh group 1 of 1 containing 1 meshes.`
`2023-01-05 21:17:37,395 - ERROR - [MainThread] CuraEngineBackend.CuraEngineBackend._onBackendQuit [964]: Backend exited abnormally with return code 3221226505!`
Does it also crash if you disable support?
If no: Does it crash again if you try again? If yes: Is there any chance that you can include the project file, and if you can, tell me how many cores/logical processors (seen in the task manager in the performance tab) your cpu has?

If your issue was the slice attempt 3 minutes later at `2023-01-05 21:20:18,507`, disregard the above.
You can try moving the model around a bit to hope that the bug does not occur.

**Comment by ThomasRahm** [comment] 2023-01-06 04:53
I think this could be a duplicate of #14113 where there is an project file with a reproducible crash

**Comment by Shakansis** [comment] 2023-01-09 00:17
Hello Thomas, 

Thank you for your response :)

Yes, it looks like it is related to the new tree support and, yes, I think it is a duplicate of https://github.com/Ultimaker/Cura/issues/14113, sorry...

But, the answers to your questions:

Cores
![image](https://user-images.githubusercontent.com/86420702/211225640-7e5055bf-80e9-4fe4-a050-66b9304402f6.png)

The project file is 49MB
![image](https://user-images.githubusercontent.com/86420702/211225844-52f8d209-5dc7-44fb-b7c7-b43e0c4208c6.png)

But you can find the .stl here:
https://www.printables.com/model/343261-balrog-figure-lord-of-the-rings

It had the tree support turned on, 0.16mm quality, brim turned on, retraction (7mm), and coasting turned on.  
Material: PLA
Temps:
200C - hot end
60C - Table


Regards,
R.

**Comment by MariMakes** [comment] 2023-01-09 12:53
Hey @Shakansis,

Thanks for your report 👍

We would love to add your file as a testcase. 

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
For big files, you may need to use WeTransfer or similar file-sharing sites.

**Closed** 2023-01-23 13:05 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage, Slicing Error :collision:, PreRelease :bug:
