### ISSUE TITLE
slicing error

### ISSUE THREAD

**Issue by dadshideout** [Ultimaker/Cura#14313] opened 2023-01-17 20:03 UTC
### Application Version

5.2.1

### Platform

windows 10 pro

### Printer

aquila 

### Reproduction steps

opened cura
loaded file
got the error

### Actual results

opened cura
loaded file (takes a while to load)
before its finished loading i get a slicing error
then slices the stl file 

### Expected results

it to open the file.. it works on 50% size  just not 100% for some reason

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

https://i.imgur.com/nTPWSFM.png

for compresed and uploaded folder
https://we.tl/t-TzkD2v3QoP

**Comment by MariMakes** [comment] 2023-01-20 11:12
Hey @dadshideout,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13643
If you move the model slightly away from the center of the buildplate and rotate it, it slices without crashing
![image](https://user-images.githubusercontent.com/40423138/213681962-e497684c-b299-451f-99c2-852c5eb5b439.png)
I hope this helps you get unstuck. 


We have someone working on resolving this issue for our next release. 
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/13643

**Closed by MariMakes** 2023-01-20 11:12 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:
