### ISSUE TITLE
There is a Text Color mistake in Cura 5.3.1

### ISSUE THREAD

**Issue by CBrocken** [Ultimaker/Cura#15379] opened 2023-04-28 15:17 UTC
### Application Version

5.0.0-5.3.1

### Platform

Windows 11

### Printer

Artillery Sidewinder X2

### Reproduction steps

In Cura 5 (to 5.3.1) if you zoom into the Build Plate you can`t read the Text in the Object list !

### Actual results

The Color of the Build Plate and the Text are the same !

### Expected results

In Cura 4 you can read the Text in the Objekt List ervery time even you zoom in or out !

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Object list-Cura4](https://user-images.githubusercontent.com/132077310/235186719-c46f6711-fe4c-4f4f-aa84-185a7bd7bf3b.jpg)
![Object list-Cura5](https://user-images.githubusercontent.com/132077310/235186736-d6a31846-635c-4044-95a0-50373799d488.jpg)

**Comment by MariMakes** [comment] 2023-05-08 13:24
Hey @CBrocken,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13615
We have a ticket on our backlog with the intent to improve this behavior.

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/13615

**Closed by MariMakes** 2023-05-08 13:24 UTC
Labels: Type: Bug, Status: Triage
