### ISSUE TITLE
Beta 5.0.0-beta+1 Bugs

### ISSUE THREAD

**Issue by Kraig777** [Ultimaker/Cura#12107] opened 2022-05-05 23:59 UTC
### Application Version

5.0.0-beta+1

### Platform

Windows 8.1

### Printer

Monoprice MP-10

### Reproduction steps

1. Did nothing.
2. attempted to copy/paste to manage printer Start G-Code and End G-Code areas.

### Actual results

1. The executable gets quarantined by my McAffee anti-virus software.  I just noticed this when the executable mysteriously disappeared.  I restored it; but, it keeps getting quarantined again later.
2. Unable to copy/paste from/to the manage printer Start G-Code and End G-Code areas.

### Expected results

1. Did not expect McAffee software to quarantine the Cura executable.
2. Expected to be able to copy/cut/paste normally.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none

**Comment by MariskaMaas** [comment] 2022-05-23 09:05
Hi Kraig, thanks for reporting your issues.

I see that this is your first issue. In the future could you open a separate bug report if you have separate bugs? That makes it easier for us, and you, to keep track of them. 

We are aware that our executable is getting flagged by McAfee. 
You can find more about the status at https://support.ultimaker.com/hc/en-us/articles/4901253538076

I checked your second issue with Cura 5.0 stable, and I cannot reproduce it. 
I'm closing this issue since it seems to be resolved.

**Closed by MariskaMaas** 2022-05-23 09:05 UTC
Labels: Type: Bug
