### ISSUE TITLE
print sequence user-defined

### ISSUE THREAD

**Issue by cnfengjie** [Ultimaker/Cura#7566] opened 2020-04-22 16:10 UTC
**Is your feature request related to a problem? Please describe.**
(A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])
seems 'special modes'->'print sequence'->options ‘one at a time’ the print sequence is decide by A
automatic.

**Describe the solution you'd like**
(A clear and concise description of what you want to happen. If possible, describe why you think this is a good solution.)
add a print sequence user-defined function, user can define which is the first print, and if user choose automatic print sequence after last print fish the heat head shold be rised up higher then the highest mould 

**Describe alternatives you've considered**
(A clear and concise description of any alternative solutions or features you've considered. Again, if possible, think about why these alternatives are not working out.)
If this an automatic print sequence, after last print finish the nozzle shold be move higher then the printed highest model to avid crash.

**Affected users and/or printers**
(Who do you think will benefit from this? Is everyone going to benefit from these changes? Or specific kinds of users?)
Solve problems that are sometimes after finish the last model nozzle move back to X0,Y0 it's crash on a highest printed model.

**Additional context**
(Add any other context or screenshots about the feature request here.)
![999](https://user-images.githubusercontent.com/61469151/80005889-c75fff80-84f6-11ea-89db-8af60e4407b4.png)

**Comment by Ghostkeeper** [comment] 2020-04-28 09:11
Duplicate of https://github.com/Ultimaker/Cura/issues/4835.

Maybe we need to consider putting a travel move to move to the height of the highest model at the end of the print though. This is not a problem for any Ultimaker printer since those will always lower the bed before homing X/Y precisely in order to prevent this issue. The problem with that though is that some printers have a "wipe off" movement in their end g-code to prevent a little tail from appearing at the end of the print, which wouldn't be possible any more then. I think the most robust solution would be to just move to the printer's height in the printer end g-code.

**Closed by Ghostkeeper** 2020-04-28 09:11 UTC
Labels: Type: New Feature

**Comment by josephted** [comment] 2020-05-03 15:19
I also understand that there must be a way for the user to change the order of objects. The program arbitrates the sequence in the order that the objects are inserted on the table. From the last to the first.
There could be a window that allows you to change that order.
