### ISSUE TITLE
Wipe distance travels backwards onto the path, pulling up layed line.

### ISSUE THREAD

**Issue by elmo40** [Ultimaker/Cura#13860] opened 2022-11-20 15:30 UTC
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Anycubic Chiron

### Reproduction steps

Using Arc Welder with parts that have full circles to print, such as towers.
Slice normally, otherwise.

### Actual results

At the end of a G2 or G3 print line, the wipe retraces backward onto the line.
This tends to pull and ball up the just layed plastic. Worse when printing softer plastic such as TPU.

### Expected results

Using Arc Welding this should continue wiping 'forward' into the circle. Continue an arc for set distance.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Slice a cylindrical part (such as a tube with smooth walls) and use Arc Welding.

**Comment by MariMakes** [comment] 2022-12-02 08:55
Hey @elmo40,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 

The ArcWelder Plug-in is created by one of our wonderfull community members @fieldOfView 
To me, it doesn't seem like a bug in Ultimaker Cura, because you are describing behavior in the Arcwelder Plug-in. 

But you can create a new issue in his repository here: https://github.com/fieldOfView/Cura-ArcWelderPlugin

Apologies for any inconvenience caused by our delayed response. 
I'll be closing this issue. I hope you understand.

**Closed by MariMakes** 2022-12-02 08:55 UTC
Labels: Type: Bug, Status: Triage
