### ISSUE TITLE
Allow half layer Support Z distance

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#9019] opened 2020-12-26 09:10 UTC
**Is your feature request related to a problem? Please describe.**
Supports are difficult to tune for optimal results. We often get either _easy to remove_  or _smooth surfaces._ This setting would allow more room for optimization.

**Describe the solution you'd like**
Ideally we should be able to use any Z-distance but I think half of a layer would be enough (and easier to implement?).
This would only affect the top support layer.

**Affected users and/or printers**
Everyone

**Additional context**
As long as the halved support layer is printed before everything else, there would be no collisions.
![support halved](https://user-images.githubusercontent.com/32172100/103148651-5eeeaf80-4762-11eb-8d26-f63348cee267.jpg)

**Comment by hunt3dprints** [comment] 2020-12-26 12:28
This would he a great help! The supports hate working with large layer heights having an option to change that would be awesome.

**Comment by samtaylor3d** [comment] 2020-12-26 22:11
Yeah I agree, this would be soooo handy with printing at larger layer heights with bigger nozzles.

When using layer height of 0.2 the z gap of 0.2 is perfect. When printing at 0.1 layer height 0.2mm z gap is also perfect 

But when printing at 0.4mm layer height the 0.4mm z gap is way too large and the features needing support either droop down or curl up. 0.2mm z gap would really help with this.  I know we can adjust the xy distance which helps but it isn't enough to get perfect supports with these larger layer heights. 

As said above ideally choosing any z gap at any layer height would be amazing but halving would be sufficient.

**Comment by Ghostkeeper** [comment] 2020-12-28 20:29
Duplicate of https://github.com/Ultimaker/Cura/issues/6105.

**Closed by Ghostkeeper** 2020-12-28 20:29 UTC
Labels: Type: New Feature

**Comment by MariMakes** [comment] 2023-11-16 12:02
Quick update on our side, you can now enter values that deviate from your layer height for the Support Z Distance. 
Can you please try it out and let us know if it resolves your issue?
You can download it here. https://github.com/Ultimaker/Cura/releases/tag/5.6.0-beta.1
