### ISSUE TITLE
Cura 4.9 windows 10 crashes shortly after opening

### ISSUE THREAD

**Issue by AllenF88** [Ultimaker/Cura#9660] opened 2021-04-22 19:10 UTC
### Application Version

4.9

### Platform

Windows 10

### Printer

Ender 5

### Reproduction steps

1. I installed cura 4.9 without uninstalling 4.8. Cura 4.8 and 4.9 both crashed as it opens. I uninstalled both and just installed 4.9, it opens but as soon as I click on Get started, it closes immediately, no errors. Error log attached 
[stderr.log](https://github.com/Ultimaker/Cura/files/6360691/stderr.log)

### Actual results

Cura 4.9 closes without an error dialog.

### Expected results

It should work

**Comment by fvrmr** [comment] 2021-04-23 09:59
Hi @AllenF88 thank you for your report.
I will discuss this with the team. Keep you posted!

**Comment by coolgua888** [comment] 2021-04-24 00:46
I also have the same problem. After opening it, click anywhere and the program will not respond and crash

**Comment by haithamkob** [comment] 2021-04-24 08:48
am also having this problem, when starting 4.9 crashes and gives this msg ( see pic), 4.8 working well.
am using Windows 10 pro.
![Screenshot 2021-04-24 114641](https://user-images.githubusercontent.com/16082040/115953214-ce976000-a4f2-11eb-9ba9-80e472575649.jpg)

**Comment by lucafedechen** [comment] 2021-04-25 02:56
hi
same error here! attached log
launch the program and crashes
thanks
[stderr.log.txt](https://github.com/Ultimaker/Cura/files/6371154/stderr.log.txt)

**Comment by AllenF88** [comment] 2021-04-25 08:39
> Hi @AllenF88 thank you for your report.
> I will discuss this with the team. Keep you posted!

Thanks @fvrmr. I saw window events saying my OpenGL was corrupted or couldnt be found. Not sure if it was caused by installing the 4.9 update.

**Comment by LAP87** [comment] 2021-04-25 23:10
Why is cura looking for X: drive at all?
I'm using X: for a mounted cloudstorage, and cura 4.9 crashes at boot with this message.
![bild](https://user-images.githubusercontent.com/7335216/116012666-31d8dd80-a62c-11eb-8d72-18b642251dcd.png)

**Comment by alexdelli** [comment] 2021-04-29 17:09
the same here

**Comment by Ghostkeeper** [comment] 2021-05-11 09:35
Duplicate of https://github.com/Ultimaker/Cura/issues/9600 . This is fixed in version 4.9.1, which is to be released shortly.

**Closed by Ghostkeeper** 2021-05-11 09:35 UTC
Labels: Type: Bug
