### ISSUE TITLE
Active job terminated by Cura

### ISSUE THREAD

**Issue by WorldShader** [Ultimaker/Cura#5202] opened 2019-01-20 23:22 UTC
**Application Version**
3.6.0

**Platform**
Windows

**Printer**
Anycubic i3

**Steps to Reproduce**
1. Turn off your computer.
2. Do an offline job using SD card.
3. Turn on your computer
4. Open Cura.
5. Watch your printer gets connected by Cura and the job be unreasonably stopped.

**Actual Results**
The active offline printing job was stopped

**Expected results**
The printer should continue to print because there's an ACTIVE fucking job.

**Comment by fieldOfView** [comment] 2019-01-21 08:20
duplicate of #70, #1478 

Don't have your printer connected via USB when you print from SD. Or disable the USB Printing plugin.

Also: Mind your fucking language!

**Comment by nallath** [comment] 2019-01-22 09:42
Closing because it's a duplicate.

**Closed by nallath** 2019-01-22 09:42 UTC
Labels: Status: Duplicate

**Comment by WorldShader** [comment] 2019-01-22 09:57
your fu

> duplicate of #70, #1478
> 
> Don't have your printer connected via USB when you print from SD. Or disable the USB Printing plugin.
> 
> Also: Mind your fucking language!

Ok, try stay calm when your 20-hour long 90% completed printing job is ruined just because you double clicked a fucking software contributed by you piece of shit.

**Comment by fieldOfView** [comment] 2019-01-22 10:35
>what a great piece of code you wrote, congratulations.

Thank you, you are welcome.

**Comment by WorldShader** [comment] 2019-01-22 11:37
> > what a great piece of code you wrote, congratulations.
> 
> Thank you, you are welcome.

no problem, just paid 150 bucks for Simplify3D. Keep up your good free work, you are worth it.
