### ISSUE TITLE
Cannot open/save files on Cura 5.2.0-beta

### ISSUE THREAD

**Issue by uski** [Ultimaker/Cura#13427] opened 2022-10-02 05:43 UTC
### Application Version

5.2.0-beta

### Platform

Linux

### Printer

Doesn't matter

### Reproduction steps

Click the "Open" button or try to save the project

PLEASE NOTE, I had that issue before and it appeared before 5.2.0-beta.

### Actual results

Nothing happens

### Expected results

System shows a dialog to open/save a file

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

Attached log
[cura.log](https://github.com/Ultimaker/Cura/files/9691846/cura.log)

**Comment by MariMakes** [comment] 2022-10-25 09:42
Hey @uski,

Sorry, it took us a while to get back to you 😞 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12266
We have a ticket on our backlog with the intent to improve this behavior.
If you read through the ticket you'll find a great number of tips and workarounds. 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12266

**Closed by MariMakes** 2022-10-25 09:42 UTC
Labels: Type: Bug, Status: Triage
