### ISSUE TITLE
[3.2.1] GUI incorrectly scales on Fedora on HDPI displays

### ISSUE THREAD

**Issue by JonHeron** [Ultimaker/Cura#3679] opened 2018-04-16 19:39 UTC
**Application Version**

3.2.1
**Platform**

5
**PyQt**

?
**Display Driver**
Intel® HD Graphics 620 (Kaby Lake GT2) 

**Printer**

Pursa MK2 (actual printer is an MK3)
**Steps to Reproduce**
Open Cura
**Actual Results**

The bottom of the application is off the screen, cant select buttons because of it. Using ALT to move the window does not work.
**Expected results**

Application is full screen 

**Additional Information**

**Comment by N0YHR** [comment] 2018-04-16 23:50
If you don't know to hit Control-E to get the Print interface, there are no clues on the interface.

It's overly complicated, and worse yet, the bed heats, and then just sits there.

I have a highly modified Rigidbot Regular with all the Peter Stoneham mods and prox sensor for bed leveling.

**Comment by fieldOfView** [comment] 2018-04-17 08:49
@JonHeron: we need more information. What resolution are you running Cura on? A screenshot could be helpful.

@N0YHR: Cura only loads with the sidebar hidden if you have hidden it yourself before closing Cura.
If you have more problems, please open other issues, but don't hijack an existing issue.

**Comment by N0YHR** [comment] 2018-04-17 11:28
Jon Heron: Very true regarding hiding the interface.  Once hidden though there is no clue to its existence without finding it in Help.  My screen resolution is 1280x1024.

 

My apologies for hijacking the issue…

**Comment by diegopradogesto** [comment] 2018-04-17 11:33
As @fieldOfView says, please send a screenshot to know what is going on with the GUI

**Comment by ianpaschal** [comment] 2018-04-17 11:42
@N0YHR: This is a separate issue, I believe. We could maybe make a menu item or some other affordance to unhide it, but having the sidebar be hidden is intended behavior.

As for the original issue, it sounds like @JonHeron's screen/window is too small and it's clipping off the bottom of the UI.

**Comment by JonHeron** [comment] 2018-04-17 12:54
Resolution is 1920 x 1080 (16x9)
The machine is an Asus UX430U ultrabook running F27_64
<img>http://theherons.ca/album/var/albums/3D_Printing/Screenshot%20from%202018-04-17%2008-49-06.png?m=1523969508</img>
Cheers,
Jon

**Comment by JonHeron** [comment] 2018-04-17 20:19
Is there a way to set the size of the gui at runtime by chance, from the terminal for example? 
Is Qt used for the GUI?
The font is quite large as well, If I reduce the font size it will likely all fit on the screen too but I cant find  a way to change the fonts size either...
Cheers,
Jon

**Comment by ianpaschal** [comment] 2018-04-17 21:45
I'm just eyeballing this but it looks like Cura is failing to recognize your screen DPI correctly and interpreting the screen as 520 px tall, clipping off 80 or so px of the min window size. Will look into it more tomorrow.

**Comment by JonHeron** [comment] 2018-04-17 21:51
Thank you!
Jon

**Comment by fieldOfView** [comment] 2018-04-18 07:09
Qt seems to think you have a "high dpi" screen. Try setting the env variable QT_SCALE_FACTOR to 1 (or other values) before launching Cura.

**Comment by JonHeron** [comment] 2018-04-18 20:07
Ithink this is a "high DPI" screen but I am not sure I know what I am talking about! :)
I tried this from the terminal with no effect:
`set env QT_SCALE_FACTOR=1
`
Not sure if that's what I am supposed to do or not?
Cheers,
Jon

**Comment by fieldOfView** [comment] 2018-04-19 10:16
@thopiekar, any ideas? I don't know the first thing about fedora.

**Comment by thopiekar** [comment] 2018-04-19 10:27
Hey @fieldOfView :)

What do you mean by "first thing"?

Afaik, scailing should work. I did that already in the past and only a hand full of widgets were not scaled. But at least Cura ist then usable again.
To be honest I never use "set env". Don't know what this specifically does, but try to use "export" instead.

Cheers! :wink:

**Comment by fieldOfView** [comment] 2018-04-19 11:29
(@thopiekar: "I don't know the first thing about X" means "I don't know anything about X")

@JonHeron: how do you normally start Cura? From a commandline or with an icon? If you just set an environment variable from a terminal, it could be that that environment variable is only set in that terminal session, so if you then use some icon in your desktop manager to launch Cura that environment variable will not be set for that session.

**Comment by thopiekar** [comment] 2018-04-19 11:43
@fieldOfView : Haha, alright. I'm a Ubuntu user and sometimes using Debian. Personally I would say there are many differences between the distros. The only thing I see is the choice of how software is maintained.

Some things are still unclear to me:
* Which desktop environment is being used?
* Are you using Xorg or Wayland ( some settings are still not synched between both systems)
* Are you using the official aka supported aka holly Ultimaker AppImage? Or the software packages, which come with your distro?

Thanks :grinning:

**Comment by JonHeron** [comment] 2018-04-19 12:06
Sorry for leaving out the important details:
Using Wayland
Gnome 3.26.2
Using Cura from the official fedora software repo
I tried running it from the command line after setting the env too, with the same results.
There is some debug info I see in the log from terminal:
`[jonnyslaptop@jonnyslaptop-localdomain ~] $ cura
[(140257942676800)-MainThread] UM.Resources.__initializeStoragePaths [351]: Initializing storage paths
[(140257942676800)-MainThread] UM.Resources.__initializeStoragePaths [362]: Config storage path is /home/jonnyslaptop/.config/cura/3.2
[(140257942676800)-MainThread] UM.Resources.__initializeStoragePaths [370]: Data storage path is /home/jonnyslaptop/.local/share/cura/3.2
[(140257942676800)-MainThread] UM.Resources.__initializeStoragePaths [382]: Cache storage path is /home/jonnyslaptop/.cache/cura/3.2
[(140257942676800)-MainThread] UM.View.GL.OpenGLContext.detectBestOpenGLVersion [103]: Trying OpenGL context 4.1...
[(140257942676800)-MainThread] UM.View.GL.OpenGLContext.detectBestOpenGLVersion [113]: Yay, we got at least OpenGL 4.1 core: 4.5 Core profile
[(140257942676800)-MainThread] UM.Qt.QtApplication.__init__ [88]: Detected most suitable OpenGL context version: 4.1 Core profile
[(140257942676800)-MainThread] UM.Qt.QtApplication.__init__ [104]: Command line arguments: {'debug': False, 'trigger_early_crash': False, 'external-backend': False, 'headless': False, 'disable-textures': False, 'qmljsdebugger': None, 'file': [], 'single_instance': False}
2018-04-19 07:44:53,429 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin ConsoleLogger
2018-04-19 07:44:53,478 - INFO - [(140257942676800)-MainThread] CuraEngineBackend.CuraEngineBackend.__init__ [65]: Found CuraEngine at: /usr/bin/CuraEngine
2018-04-19 07:44:53,479 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin CuraEngineBackend
2018-04-19 07:44:53,482 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin FileLogger
2018-04-19 07:44:53,486 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin LocalFileOutputDevice
2018-04-19 07:44:53,486 - WARNING - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [200]: Plugin ConsoleLogger was already loaded
2018-04-19 07:44:53,494 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin STLReader
2018-04-19 07:44:53,496 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin OBJReader
2018-04-19 07:44:53,498 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin STLWriter
2018-04-19 07:44:53,500 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin OBJWriter
2018-04-19 07:44:53,549 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin UpdateChecker
2018-04-19 07:44:53,555 - INFO - [(140256764745472)-Thread-1] UpdateChecker.UpdateCheckerJob.run [34]: Checking for new version of cura
2018-04-19 07:44:53,558 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin CameraTool
2018-04-19 07:44:53,562 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin TranslateTool
2018-04-19 07:44:53,567 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin ScaleTool
2018-04-19 07:44:53,570 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin MirrorTool
2018-04-19 07:44:53,574 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin RotateTool
2018-04-19 07:44:53,577 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin SelectionTool
2018-04-19 07:44:53,579 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin LocalContainerProvider
2018-04-19 07:44:53,581 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin SimpleView
2018-04-19 07:44:53,584 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin GCodeProfileReader
2018-04-19 07:44:53,678 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin UM3NetworkPrinting
2018-04-19 07:44:53,682 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin PostProcessingPlugin
2018-04-19 07:44:53,685 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin MachineSettingsAction
2018-04-19 07:44:53,700 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin 3MFWriter
2018-04-19 07:44:53,704 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin GCodeReader
2018-04-19 07:44:53,713 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin SimulationView
2018-04-19 07:44:53,716 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin LegacyProfileReader
2018-04-19 07:44:53,719 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin UserAgreementPlugin
2018-04-19 07:44:53,721 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin GCodeWriter
2018-04-19 07:44:53,729 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin PluginBrowser
2018-04-19 07:44:53,733 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin ChangeLogPlugin
2018-04-19 07:44:53,736 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin FirmwareUpdateChecker
2018-04-19 07:44:53,741 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin XmlMaterialProfile
2018-04-19 07:44:53,744 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin AutoSave
2018-04-19 07:44:53,747 - WARNING - [(140257942676800)-MainThread] UM.Preferences.getValue [81]: Tried to get the value of non-existing setting cura/active_mode.
2018-04-19 07:44:53,748 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin PerObjectSettingsTool
2018-04-19 07:44:53,750 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin VersionUpgrade26to27
2018-04-19 07:44:53,753 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin VersionUpgrade25to26
2018-04-19 07:44:53,755 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin VersionUpgrade30to31
2018-04-19 07:44:53,758 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin VersionUpgrade27to30
2018-04-19 07:44:53,761 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin VersionUpgrade21to22
2018-04-19 07:44:53,764 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin VersionUpgrade22to24
2018-04-19 07:44:53,767 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin CuraProfileWriter
2018-04-19 07:44:53,771 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin MonitorStage
2018-04-19 07:44:53,778 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin 3MFReader
2018-04-19 07:44:53,781 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin SolidView
2018-04-19 07:44:53,785 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin SliceInfoPlugin
2018-04-19 07:44:53,796 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin USBPrinting
2018-04-19 07:44:53,804 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin RemovableDriveOutputDevice
2018-04-19 07:44:53,805 - WARNING - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [200]: Plugin CuraEngineBackend was already loaded
2018-04-19 07:44:53,816 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin X3DReader
2018-04-19 07:44:53,821 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin UltimakerMachineActions
2018-04-19 07:44:53,825 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin CuraProfileReader
2018-04-19 07:44:53,829 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin ImageReader
2018-04-19 07:44:53,832 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin XRayView
2018-04-19 07:44:53,835 - INFO - [(140257942676800)-MainThread] UM.PluginRegistry.loadPlugin [238]: Loaded plugin PrepareStage
2018-04-19 07:44:53,894 - DEBUG - [(140257942676800)-MainThread] UM.Backend.Backend._logSocketState [173]: Socket state changed to Listening
2018-04-19 07:44:53,901 - INFO - [(140257942676800)-MainThread] UM.Backend.Backend.startEngine [74]: Started engine process: /usr/bin/CuraEngine
2018-04-19 07:44:53,902 - DEBUG - [(140257942676800)-MainThread] UM.Backend.Backend._backendLog [90]: [Backend] Calling engine with: ['/usr/bin/CuraEngine', 'connect', '127.0.0.1:49674', '-j', '/usr/share/cura/resources/definitions/fdmprinter.def.json', '']
2018-04-19 07:44:53,904 - INFO - [(140257942676800)-MainThread] UM.VersionUpgradeManager.upgrade [113]: Looking for old configuration files to upgrade.
2018-04-19 07:44:53,911 - DEBUG - [(140255948683008)-Thread-10] UM.Backend.Backend._backendLog [90]: [Backend] 
2018-04-19 07:44:53,912 - DEBUG - [(140255948683008)-Thread-10] UM.Backend.Backend._backendLog [90]: [Backend] Cura_SteamEngine version 3.2.1
2018-04-19 07:44:53,912 - DEBUG - [(140255948683008)-Thread-10] UM.Backend.Backend._backendLog [90]: [Backend] Copyright (C) 2017 Ultimaker
2018-04-19 07:44:53,912 - DEBUG - [(140255948683008)-Thread-10] UM.Backend.Backend._backendLog [90]: [Backend] 
2018-04-19 07:44:53,912 - DEBUG - [(140255948683008)-Thread-10] UM.Backend.Backend._backendLog [90]: [Backend] This program is free software: you can redistribute it and/or modify
2018-04-19 07:44:53,913 - DEBUG - [(140255948683008)-Thread-10] UM.Backend.Backend._backendLog [90]: [Backend] it under the terms of the GNU Affero General Public License as published by
2018-04-19 07:44:53,913 - DEBUG - [(140255948683008)-Thread-10] UM.Backend.Backend._backendLog [90]: [Backend] the Free Software Foundation, either version 3 of the License, or
2018-04-19 07:44:53,914 - DEBUG - [(140255948683008)-Thread-10] UM.Backend.Backend._backendLog [90]: [Backend] (at your option) any later version.
2018-04-19 07:44:53,914 - DEBUG - [(140255948683008)-Thread-10] UM.Backend.Backend._backendLog [90]: [Backend] 
2018-04-19 07:44:53,914 - DEBUG - [(140255948683008)-Thread-10] UM.Backend.Backend._backendLog [90]: [Backend] This program is distributed in the hope that it will be useful,
2018-04-19 07:44:53,914 - DEBUG - [(140255948683008)-Thread-10] UM.Backend.Backend._backendLog [90]: [Backend] but WITHOUT ANY WARRANTY; without even the implied warranty of
2018-04-19 07:44:53,915 - DEBUG - [(140255948683008)-Thread-10] UM.Backend.Backend._backendLog [90]: [Backend] MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
2018-04-19 07:44:53,915 - DEBUG - [(140255948683008)-Thread-10] UM.Backend.Backend._backendLog [90]: [Backend] GNU Affero General Public License for more details.
2018-04-19 07:44:53,915 - DEBUG - [(140255948683008)-Thread-10] UM.Backend.Backend._backendLog [90]: [Backend] 
2018-04-19 07:44:53,915 - DEBUG - [(140255948683008)-Thread-10] UM.Backend.Backend._backendLog [90]: [Backend] You should have received a copy of the GNU Affero General Public License
2018-04-19 07:44:53,915 - DEBUG - [(140255948683008)-Thread-10] UM.Backend.Backend._backendLog [90]: [Backend] along with this program.  If not, see <http://www.gnu.org/licenses/>.
2018-04-19 07:44:54,037 - DEBUG - [(140257942676800)-MainThread] UM.Backend.Backend._logSocketState [177]: Socket state changed to Connected
2018-04-19 07:44:54,037 - DEBUG - [(140257942676800)-MainThread] UM.Backend.Backend._onSocketStateChanged [167]: Backend connected on port 49674
2018-04-19 07:44:54,720 - WARNING - [(140257942676800)-MainThread] UM.Preferences.getValue [81]: Tried to get the value of non-existing setting view/filter_current_build_plate.
2018-04-19 07:44:54,721 - DEBUG - [(140257942676800)-MainThread] cura.Scene.CuraSceneController.setActiveBuildPlate [101]: Select build plate: 0
2018-04-19 07:44:54,723 - DEBUG - [(140257942676800)-MainThread] UM.Controller.setActiveStage [155]: Setting active stage to PrepareStage
2018-04-19 07:44:54,723 - DEBUG - [(140257942676800)-MainThread] UM.Controller.setActiveView [92]: Setting active view to SolidView
2018-04-19 07:44:54,736 - DEBUG - [(140257942676800)-MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [50]: Loading container Prusa i3 Mk2
2018-04-19 07:44:54,738 - DEBUG - [(140257942676800)-MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [50]: Loading container Prusa i3 Mk2_user
2018-04-19 07:44:54,741 - DEBUG - [(140257942676800)-MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [50]: Loading container normal
2018-04-19 07:44:54,743 - DEBUG - [(140257942676800)-MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [50]: Loading container Prusa i3 Mk2_settings
2018-04-19 07:44:54,744 - DEBUG - [(140257942676800)-MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [50]: Loading container prusa_i3_mk2
2018-04-19 07:44:54,789 - DEBUG - [(140257942676800)-MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [50]: Loading container Prusa i3 Mk2 fdmextruder
2018-04-19 07:44:54,791 - DEBUG - [(140257942676800)-MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [50]: Loading container Prusa i3 Mk2 fdmextruder_user
2018-04-19 07:44:54,792 - DEBUG - [(140257942676800)-MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [50]: Loading container fabtotum_pla
2018-04-19 07:44:54,793 - DEBUG - [(140257942676800)-MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [50]: Loading container Prusa i3 Mk2 fdmextruder_settings
2018-04-19 07:44:54,795 - DEBUG - [(140257942676800)-MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [50]: Loading container fdmextruder
2018-04-19 07:44:54,796 - INFO - [(140257942676800)-MainThread] cura.Settings.GlobalStack.addExtruder [73]: Extruder[Prusa i3 Mk2 fdmextruder] added to [Prusa i3 Mk2] at position [0]
2018-04-19 07:44:54,797 - WARNING - [(140257942676800)-MainThread] UM.Settings.ContainerStack.addMetaDataEntry [166]: Meta data with key machine was already added.
2018-04-19 07:44:54,799 - WARNING - [(140257942676800)-MainThread] cura.Settings.GlobalStack.addExtruder [69]: Extruder [Prusa i3 Mk2 fdmextruder] has already been added to this stack [Prusa i3 Mk2]
2018-04-19 07:44:54,799 - WARNING - [(140257942676800)-MainThread] UM.Settings.ContainerStack.addMetaDataEntry [166]: Meta data with key machine was already added.
2018-04-19 07:44:54,800 - WARNING - [(140257942676800)-MainThread] cura.Settings.ExtruderManager.registerExtruder [223]: Extruder [Prusa i3 Mk2 fdmextruder] has already been registered on machine [Prusa i3 Mk2], not doing anything
2018-04-19 07:44:54,803 - DEBUG - [(140257942676800)-MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [50]: Loading container fdmprinter
2018-04-19 07:44:54,906 - DEBUG - [(140256747960064)-Thread-3] UM.Mesh.MeshData.calculateNormalsFromVertices [421]: Calculating normals took 0.032140493392944336 seconds
2018-04-19 07:44:54,989 - DEBUG - [(140256747960064)-Thread-3] STLReader.STLReader.read [79]: Loaded a mesh with 8052 vertices
2018-04-19 07:44:55,180 - DEBUG - [(140257942676800)-MainThread] cura.Settings.MachineManager._checkStacksHaveErrors [423]: Checking 2 stacks for errors took 0.34 s
2018-04-19 07:44:55,193 - DEBUG - [(140257942676800)-MainThread] UM.Mesh.MeshData.approximateConvexHull [388]: approximateConvexHull(target_count=1024) Calculating 3D convex hull took 0.00550532341003418 seconds. 36 input vertices. 36 output vertices.
2018-04-19 07:44:55,527 - DEBUG - [(140257942676800)-MainThread] cura.Settings.MachineManager._checkStacksHaveErrors [423]: Checking 2 stacks for errors took 0.33 s
2018-04-19 07:44:55,771 - DEBUG - [(140257942676800)-MainThread] UM.Qt.Bindings.Theme.load [172]: Loading theme file: /usr/share/cura/resources/themes/cura-dark/theme.json
2018-04-19 07:44:55,771 - DEBUG - [(140257942676800)-MainThread] UM.Qt.Bindings.Theme.load [172]: Loading theme file: /usr/share/cura/resources/themes/cura-light/theme.json
2018-04-19 07:44:55,822 - DEBUG - [(140257942676800)-MainThread] UM.Qt.Bindings.Theme.load [240]: Loaded theme /usr/share/cura/resources/themes/cura-light
2018-04-19 07:44:55,823 - DEBUG - [(140257942676800)-MainThread] UM.Qt.Bindings.Theme.load [240]: Loaded theme /usr/share/cura/resources/themes/cura-dark
2018-04-19 07:44:55,868 - WARNING - [(140257942676800)-MainThread] UM.Qt.QtApplication.__onQmlWarning [267]: file:///usr/lib64/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:210:25: QML ListView: Binding loop detected for property "model"
2018-04-19 07:44:55,936 - DEBUG - [(140257942676800)-MainThread] UM.Controller.setActiveView [92]: Setting active view to SolidView
2018-04-19 07:44:56,025 - WARNING - [(140257942676800)-MainThread] UM.Qt.Bindings.Theme.getColor [101]: No color black defined in Theme
qml: TableViewSelection: index out of range
qml: TableViewSelection: index out of range
2018-04-19 07:44:56,117 - DEBUG - [(140257942676800)-MainThread] UM3NetworkPrinting.DiscoverUM3Action._createAdditionalComponentsView [136]: Creating additional ui components for UM3.
2018-04-19 07:44:56,136 - DEBUG - [(140257942676800)-MainThread] UM3NetworkPrinting.DiscoverUM3Action.startDiscovery [36]: Starting printer discovery.
2018-04-19 07:44:56,146 - DEBUG - [(140257942676800)-MainThread] UM.Controller.setActiveStage [155]: Setting active stage to PrepareStage
2018-04-19 07:44:56,596 - DEBUG - [(140257942676800)-MainThread] cura.Settings.MachineManager._checkStacksHaveErrors [423]: Checking 2 stacks for errors took 0.34 s
2018-04-19 07:44:56,611 - DEBUG - [(140257942676800)-MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [50]: Loading container draft
2018-04-19 07:44:56,613 - DEBUG - [(140257942676800)-MainThread] cura.Settings.MachineManager._onInstanceContainersChanged [365]: Connecting profiles model...
2018-04-19 07:44:56,613 - DEBUG - [(140257942676800)-MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [50]: Loading container coarse
2018-04-19 07:44:56,615 - DEBUG - [(140257942676800)-MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [50]: Loading container extra_coarse
2018-04-19 07:44:56,619 - DEBUG - [(140257942676800)-MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [50]: Loading container high
2018-04-19 07:44:56,620 - DEBUG - [(140257942676800)-MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [50]: Loading container low
2018-04-19 07:44:56,796 - DEBUG - [(140257942676800)-MainThread] UM.Qt.QtRenderer._initialize [184]: Support for Vertex Array Objects: True
2018-04-19 07:44:56,802 - DEBUG - [(140257942676800)-MainThread] UM.View.GL.OpenGL.__init__ [92]: Initialized OpenGL subsystems.
2018-04-19 07:44:56,802 - DEBUG - [(140257942676800)-MainThread] UM.View.GL.OpenGL.__init__ [93]: OpenGL Version:  4.5 (Core Profile) Mesa 17.3.6
2018-04-19 07:44:56,802 - DEBUG - [(140257942676800)-MainThread] UM.View.GL.OpenGL.__init__ [94]: OpenGL Vendor:   Intel Open Source Technology Center
2018-04-19 07:44:56,802 - DEBUG - [(140257942676800)-MainThread] UM.View.GL.OpenGL.__init__ [95]: OpenGL Renderer: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
2018-04-19 07:44:56,803 - DEBUG - [(140257942676800)-MainThread] UM.View.GL.ShaderProgram.load [55]: Loading shader file [/usr/share/uranium/resources/shaders/default.shader]...
2018-04-19 07:44:56,810 - DEBUG - [(140257942676800)-MainThread] UM.View.GL.ShaderProgram.load [55]: Loading shader file [/usr/share/uranium/resources/shaders/selection.shader]...
2018-04-19 07:44:56,813 - DEBUG - [(140257942676800)-MainThread] UM.View.GL.ShaderProgram.load [55]: Loading shader file [/usr/share/uranium/resources/shaders/default.shader]...
2018-04-19 07:44:56,818 - DEBUG - [(140257942676800)-MainThread] UM.View.GL.ShaderProgram.load [55]: Loading shader file [/usr/share/uranium/resources/shaders/composite.shader]...
2018-04-19 07:44:56,832 - DEBUG - [(140257942676800)-MainThread] UM.View.GL.ShaderProgram.load [55]: Loading shader file [/usr/share/cura/resources/shaders/overhang.shader]...
2018-04-19 07:44:56,847 - DEBUG - [(140257942676800)-MainThread] UM.View.GL.ShaderProgram.load [55]: Loading shader file [/usr/share/cura/resources/shaders/striped.shader]...
2018-04-19 07:44:56,865 - DEBUG - [(140257942676800)-MainThread] UM.View.GL.ShaderProgram.load [55]: Loading shader file [/usr/share/cura/resources/shaders/transparent_object.shader]...
2018-04-19 07:44:56,876 - DEBUG - [(140257942676800)-MainThread] UM.View.GL.ShaderProgram.load [55]: Loading shader file [/usr/share/cura/resources/shaders/striped.shader]...
2018-04-19 07:44:56,896 - DEBUG - [(140257942676800)-MainThread] UM.View.GL.ShaderProgram.load [55]: Loading shader file [/usr/share/uranium/resources/shaders/default.shader]...
2018-04-19 07:44:56,901 - DEBUG - [(140257942676800)-MainThread] UM.View.GL.ShaderProgram.load [55]: Loading shader file [/usr/share/cura/resources/shaders/grid.shader]...
2018-04-19 07:44:56,910 - DEBUG - [(140257942676800)-MainThread] UM.View.GL.ShaderProgram.load [55]: Loading shader file [/usr/share/uranium/resources/shaders/platform.shader]...
2018-04-19 07:44:57,550 - DEBUG - [(140257942676800)-MainThread] cura.Settings.MachineManager._checkStacksHaveErrors [423]: Checking 2 stacks for errors took 0.32 s
2018-04-19 07:44:57,911 - DEBUG - [(140257942676800)-MainThread] cura.Settings.MachineManager._checkStacksHaveErrors [423]: Checking 2 stacks for errors took 0.33 s
2018-04-19 07:44:58,619 - DEBUG - [(140257942676800)-MainThread] cura.Settings.MachineManager._checkStacksHaveErrors [423]: Checking 2 stacks for errors took 0.35 s
2018-04-19 07:44:59,146 - DEBUG - [(140257942676800)-MainThread] CuraEngineBackend.CuraEngineBackend.slice [197]: starting to slice!
2018-04-19 07:44:59,147 - DEBUG - [(140257942676800)-MainThread] CuraEngineBackend.CuraEngineBackend.slice [214]: Going to slice build plate [0]!
2018-04-19 07:44:59,148 - DEBUG - [(140257942676800)-MainThread] CuraEngineBackend.CuraEngineBackend.slice [218]: Build plate 0 has no objects to be sliced, skipping
2018-04-19 07:45:02,301 - DEBUG - [(140257942676800)-MainThread] UM.Qt.QtApplication.windowClosed [345]: Shutting down cura
2018-04-19 07:45:02,332 - DEBUG - [(140257942676800)-MainThread] CuraEngineBackend.CuraEngineBackend._terminate [262]: Attempting to kill the engine process
2018-04-19 07:45:02,333 - DEBUG - [(140257942676800)-MainThread] CuraEngineBackend.CuraEngineBackend._terminate [268]: Killing engine process
2018-04-19 07:45:02,334 - DEBUG - [(140257942676800)-MainThread] CuraEngineBackend.CuraEngineBackend._terminate [271]: Engine process is killed. Received return code -15
`
`[jonnyslaptop@jonnyslaptop-localdomain ~] $ cura --version
cura 3.2.1
`
Cheers,
Jon

**Comment by fieldOfView** [comment] 2018-04-19 12:10
Try starting Cura with ```QT_SCALE_FACTOR=1 cura```, but also try other values (eg ```QT_SCALE_FACTOR=0.5 cura```)

**Comment by thopiekar** [comment] 2018-04-19 12:16
And please try to reproduce while using Xorg. 🙂

**Comment by JonHeron** [comment] 2018-04-19 12:27
@fieldOfView Using a scale factor less then 1 breaks the UI. Using 1 or above does not fix the issue.
@thopiekar  same issue confirmed with wayland and xorg.
Cheers,
Jon

**Comment by fieldOfView** [comment] 2018-04-19 12:51
What do you mean by "breaks the UI"? Please be more specific (another screenshot perhaps?). Also when using a value > 1, does that change anything (ie: do the fonts get even bigger)?

**Comment by JonHeron** [comment] 2018-04-19 13:03
Here it is @ .5
http://theherons.ca/album/var/albums/3D_Printing/Screenshot%20from%202018-04-19%2008-59-34.png?m=1524142862
http://theherons.ca/album/var/albums/3D_Printing/Screenshot%20from%202018-04-19%2008-59-46.png?m=1524142863
This is the same for anything <1.
Jon

**Comment by ianpaschal** [comment] 2018-04-26 07:54
I'm not a linux user so I can't do much testing on my own, that's why I'm slightly deferring to @thopiekar's comments.

Tagging our Cura devs who use linux: @jackha @Ghostkeeper, although I'm sure this doesn't recreate for them or they wouldn't get any dev work done! @nallath works on CuraConnect but he uses Fedora so maybe he can help.

I'm going to label this as a bug but since it's highly unlikely any of us will be able to recreate the bug, I would not hold your breath. Sorry. ☹️

**Comment by JonHeron** [comment] 2018-04-26 11:49
Thanks for your efforts!
Cheers,
Jon

**Comment by jackha** [comment] 2018-04-26 12:04
Can't check or reproduce it on my Ubuntu with Unity...

**Comment by ianpaschal** [comment] 2018-04-26 21:57
Bad luck Jon, we use PyQt so the only C++ code is the CuraEngine (slicing backend).

**Comment by JonHeron** [comment] 2018-05-23 02:54
Using the latest appImage 3.3.1 and the latest F28..... the bug is dead!
Looking forward to trying it out (when I get home from this business trip :) )
   
Cheers!
Jon

**Comment by diegopradogesto** [comment] 2018-05-23 06:12
Hey, glad to hear! Thanks for the info.

**Closed by diegopradogesto** 2018-05-23 06:12 UTC
Labels: Category: Cura, Platform: Linux, Type: Bug
