### ISSUE TITLE
[3.3.0-beta] Speed settings need enter key hit for setting to take effect

### ISSUE THREAD

**Issue by scrat82** [Ultimaker/Cura#3575] opened 2018-03-27 15:54 UTC
**Application Version**
 beta 3.3.0 beta

**Platform**
 windows 10 64 bit, linux, probably all

**Qt**

**PyQt**

**Display Driver**

**Printer**
ultimaker 2+, Ultimaker 3

**Steps to Reproduce**
 enter speed setting and click on another box the the old setting reappears (but not always)

**Actual Results**

**Expected results**

**Additional Information**

**Comment by smartavionics** [comment] 2018-03-27 16:04
Hi, please try entering the speed digits slowly (around 1 per second) followed by enter or tab. If you do that and the old setting does not reappear, then it's the same issue as I am seeing (#3564).

**Comment by scrat82** [comment] 2018-03-27 17:20
I have waiting for it to slice and watch other settings go back to a different value. If I highlight the value to change instead of clicking on the box and using the delete key I get different results too.

**Comment by smartavionics** [comment] 2018-03-27 17:21
Hmm, it appears to have a problem... LOL, I expect someone will wake up and fix it before too long!

**Comment by scrat82** [comment] 2018-03-27 17:29
I agree. I was looking at the layer view, and when I highlighted the infill and changed that, the layer view changed instead. Almost if I read the mouse to far to the left when I'm highlighting the number, it jumped over to the layer height box in the view window

**Comment by darkdvd** [comment] 2018-03-27 19:37
Same problem for me (CURA 3.2.1 / 3.3)
Windows 10 x64
CURA in "compatibility mode"

**Comment by jackha** [comment] 2018-03-29 09:36
Really weird, I see it too on my UM3 in linux.
Devs: CURA-5176

**Comment by macaron16** [comment] 2018-04-01 19:05
same issue on osX.
If we click 'tab key' no effect (the value don't change) 
Not only for speed setting, but for all settings.

**Comment by smartavionics** [comment] 2018-04-01 20:47
Yes, the UI appears to be well broken in 3.3 beta. There's this problem with entering values into settings and also the problem with editing start/end gcode. I am mildly shocked that it was released in such a broken state.

**Comment by lolorc** [comment] 2018-04-11 07:15
confirmed, it's very annoying

**Comment by lolorc** [comment] 2018-04-12 08:43
@smartavionics oh that's good news, i'll build master this evening then.
what's the commit ? looks like I missed it.

**Comment by smartavionics** [comment] 2018-04-12 08:46
Sorry, I forget now, I think it was in Uranium (maybe 7b53e35fcb7f28ca4cda43a79102f5bfee44106d).

**Comment by lolorc** [comment] 2018-04-12 09:03
looks like it, a revert, thanks

**Comment by diegopradogesto** [comment] 2018-04-13 07:56
This was fixed on April 6th and it will be in 3.3.

**Closed by diegopradogesto** 2018-04-13 07:56 UTC
Labels: Category: Cura, Category: Settings, Status: In Progress, Type: Bug
