### ISSUE TITLE
Cura 4.9.1 display bug.

### ISSUE THREAD

**Issue by kangoam** [Ultimaker/Cura#9965] opened 2021-06-10 16:54 UTC
### Application Version

4.9.1

### Platform

Windows 10

### Printer

Creality Ender 3

### Reproduction steps

hello,
1. I open the print settings and click on the small wheel for the "Fill" settings.

![Bug_cura_a](https://user-images.githubusercontent.com/85697249/121564649-fb102880-ca1b-11eb-92d0-22449806b45d.jpg)

### Actual results

1. The settings window is systematically placed at the top of the list, displaying the "Quality" section.

![Bug_cura_b](https://user-images.githubusercontent.com/85697249/121565082-6c4fdb80-ca1c-11eb-8491-c3b6f2dd9f8d.jpg)

### Expected results

1. Cura should display the "Filling" section directly.

![Bug_cura_c](https://user-images.githubusercontent.com/85697249/121565367-ae791d00-ca1c-11eb-809f-3ce89565251d.jpg)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Can the problem be caused by a third-party Windows software?

Thanks for your help, and sorry for my very poor English!

**Comment by fvrmr** [comment] 2021-06-11 08:14
Hi @kangoam thank you for your bug report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9621 and this is fixed for the next release. 
I will close this because it is a duplicate.

**Closed by fvrmr** 2021-06-11 08:14 UTC
Labels: Type: Bug

**Comment by kangoam** [comment] 2021-06-11 17:20
@fvrmr  Thank you so much for giving me the link to the post solving my problem!!!
