### ISSUE TITLE
Traceback exception running 2.7.0 on Mint KDE Linux release during load of stl.

### ISSUE THREAD

**Issue by stampedeboss** [Ultimaker/Cura#2557] opened 2017-10-05 04:52 UTC
aj@0laf:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:          16026        2702        3471         587        9853       12599
Swap:         15999          28       15971
As you can see there is more than enough memory available.  Additionally, 2.6.2 works without issue even when 2.7.0 is running.  The following occurs when ANY stl is loaded regardless of size or complexity.

Version: 2.7.0
Platform: Linux-4.4.0-21-generic-x86_64-with-debian-stretch-sid
Qt: 5.8.0
PyQt: 5.8.2

Exception:
Traceback (most recent call last):
  File "/build/2.7/build/inst/lib/python3/dist-packages/cura/CuraApplication.py", line 713, in event
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/Qt/QtApplication.py", line 261, in event
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/Event.py", line 189, in call
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/Signal.py", line 315, in __performEmit
  File "/build/2.7/build/inst/lib/python3/dist-packages/cura/CuraApplication.py", line 1319, in _readMeshFinished
  File "/build/2.7/build/inst/lib/python3/dist-packages/cura/Arrange.py", line 64, in create
  File "/build/2.7/build/inst/lib/python3/dist-packages/cura/ShapeArray.py", line 33, in fromPolygon
  File "/build/2.7/build/inst/lib/python3/dist-packages/cura/ShapeArray.py", line 70, in arrayFromPolygon
MemoryError

-------------------------
Thread 0x00007faa5bfff700 (most recent call first):
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/Backend/Backend.py", line 156 in _storeStderrToLogThread
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 862 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007faa78ff9700 (most recent call first):
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/Backend/Backend.py", line 148 in _storeOutputToLogThread
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 862 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007faa79ffb700 (most recent call first):
  File "/tmp/.mount_I93zuu/usr/bin/plugins/plugins/USBPrinting/USBPrinterOutputDeviceManager.py", line 88 in _updateThread
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 862 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007faa7a7fc700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 116 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007faa7affd700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 116 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007faa7b7fe700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 116 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007faa7bfff700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 116 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007faa98ff9700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 116 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007faa997fa700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 116 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007faa99ffb700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 116 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007faa9a7fc700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 293 in wait
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 424 in acquire
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 86 in _nextJob
  File "/build/2.7/build/inst/lib/python3/dist-packages/UM/JobQueue.py", line 116 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007faa9affd700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 297 in wait
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 1569 in wait
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 1153 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007faa9b7fe700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 297 in wait
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 1569 in wait
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 1017 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007faa9bfff700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 946 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007faabcfb7700 (most recent call first):
  File "/tmp/.mount_I93zuu/usr/bin/plugins/plugins/RemovableDriveOutputDevice/RemovableDrivePlugin.py", line 58 in _updateThread
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 862 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007faabd7b8700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 297 in wait
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 1569 in wait
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 1153 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007faabdfb9700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 297 in wait
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 1569 in wait
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 1017 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007faabe7ba700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 946 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007faabf7fe700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 297 in wait
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 1569 in wait
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 1017 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007faabffff700 (most recent call first):
  File "/build/env/2.7/inst/lib/python3.5/site-packages/zeroconf.py", line 946 in run
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/build/env/2.7/inst/lib/python3.5/threading.py", line 882 in _bootstrap

Current thread 0x00007faae2b49700 (most recent call first):
  File "/build/2.7/build/inst/lib/python3/dist-packages/cura/CrashHandler.py", line 100 in show
  File "/build/2.7/build/inst/bin/cura", line 45 in exceptHook
  File "/build/2.7/build/inst/lib/python3/dist-packages/cura/CuraApplication.py", line 682 in run
  File "/build/2.7/build/inst/bin/cura", line 73 in <module>
  File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load
  File "/build/env/2.7/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 21 in <module>
  File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load
  File "/build/env/2.7/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/__startup__.py", line 12 in <module>
  File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load

**Comment by Ghostkeeper** [comment] 2017-10-15 15:16
Duplicate of https://github.com/Ultimaker/Cura/issues/2474.

**Closed by Ghostkeeper** 2017-10-15 15:16 UTC
