### ISSUE TITLE
Cura Displays all Icons as Gray Boxes 

### ISSUE THREAD

**Issue by TURTLEHARDBODY** [Ultimaker/Cura#2075] opened 2017-07-05 21:34 UTC
Application Version: >2.4 (Currently on 2.6.1, occurred previously on 2.5. Rolling back to 2.4 was the only way I could get icons / sprites to work. 
Platform: Windows 10 64 bit Home, 
Specs:

    i5 4670 @ 3.4 ghz
    Asus - H87-PLUS ATX LGA1150 Motherboard
    4x4 GB ram (16 GB) 
    Samsung 840 Evo SSD
    MSI Geforce GTX 1070 

Qt: How do I find this on Windows? All searches came up with Linux specific instructions.
PyQt: How do I find this on Windows? All searches came up with Linux specific instructions.
Display Driver: GeForce Game Ready Driver 382.05

Steps to Reproduce:
Launch Cura under normal conditions on system. 

Actual Results:
Gray boxes appear instead of icons.

Expected results:
Icons / sprites should be present. 

Additional Information:
Dxdiag and screenshot attached.
![cura gray boxes](https://user-images.githubusercontent.com/29931440/27885882-9e326f6e-61a7-11e7-9c62-08bc4d8bd880.png)

[DxDiag.txt](https://github.com/Ultimaker/Cura/files/1126094/DxDiag.txt)
[
Troubleshooting performed. ](https://www.reddit.com/r/3Dprinting/comments/6aj09m/cura_25_doesnt_have_icons_just_various_grey_boxes/)

**Comment by fieldOfView** [comment] 2017-07-06 07:12
Duplicate of https://github.com/Ultimaker/Cura/issues/1722

**Closed** 2017-07-06 07:47 UTC
