### ISSUE TITLE
Multiplying and Placing Objects

### ISSUE THREAD

**Issue by schaferaccess** [Ultimaker/Cura#11071] opened 2021-12-14 01:01 UTC
### Application Version

4.12.0

### Platform

macOS Monterey

### Printer

Reality Ender 3

### Reproduction steps

- Add file
- _Multiply Selected_
- _Number of Copies_

### Actual results

- Prompt says placing objects
- Never actually loads

### Expected results

For the program to Multiply and place the objects

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7707842/cura.log)
[CE3_squareFlat.3mf.zip](https://github.com/Ultimaker/Cura/files/7707843/CE3_squareFlat.3mf.zip)

**Comment by fvrmr** [comment] 2021-12-14 07:57
Hi @schaferaccess thank you for your report.
This is a duplicate of: #10249. And this is fixed in 4.12.1: https://ultimaker.com/software/ultimaker-cura
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-12-14 07:57 UTC
Labels: Type: Bug
