### ISSUE TITLE
3.4.1/3.5.1 - issue with "Skin Overlap" feature 

### ISSUE THREAD

**Issue by amagr0** [Ultimaker/Cura#4628] opened 2018-10-22 13:38 UTC
**Application Version** - CURA 3.4.1 / 3.5.1
**Platform** - Win 10 Pro, 64 bit
**Display Driver** - NVIDIA GeForce 840M

**Steps to Reproduce** - Open Cura Project; analyse the toolpath.

**Actual Results** - Some lines are trespassing from the wall, this seems to be related with "Skin Overlap". Is also strange that is happening in the middle of the part, and not only on the skins parts.  

![bug_1](https://user-images.githubusercontent.com/12901952/47294972-622c0500-d606-11e8-88c7-3ea3f76f253a.jpg)

 

[BUG_1.zip](https://github.com/Ultimaker/Cura/files/2501524/BUG_1.zip)

**Comment by rburema** [comment] 2018-10-26 11:10
Hi @amagr0, From the description of the Skin Overlap setting: 

> The amount of overlap between the skin and the walls. A slight overlap allows the walls to connect firmly to the skin.

To me, it seems like it does what it's supposed to do.

Now you could of course argue that

 - there should be a warning when the overlap is bigger than the wall-size
 - and/or there shouldn't be a difference between layers here.  

... but neither of these, given the definition, seem like large improvements, so I'll still close this issue for now. But if you think those two are important, please reply so we can discuss potentially reopening them, or creating a new issue.

cheers,
Remco.

**Comment by amagr0** [comment] 2018-10-26 15:06
Hello @rburema 
The "Skin Overlap" value is 0.35 mm, and the "Wall Line Width" is 0,4 mm, so how can the lines from the skin overlap trespass the wall perimeter?

Tks

**Comment by rburema** [comment] 2018-10-26 15:08
Hi @amagr0, That is a good point. I'll reopen this issue.

**Comment by Ghostkeeper** [comment] 2019-01-18 11:42
Still reproduces in 4.0.

**Comment by LipuFei** [comment] 2019-01-22 09:33
For dev, JIRA ticket: CURA-6140

**Comment by rburema** [comment] 2019-02-15 10:04
Hi @amagr0,
I took another good look and I found out what the issue is:

The nozzle, while printing the arching lines, stops at 0.35 mm relative to the start of the wall. (Correctly, I think.) You can see that if you have 'travels' enabled in layer-view. However, since the line thickness is indeed 0.4 mm, the material can still 'stick out' of the wall by -(0.4 / 2 - 0.35) = 0.15 mm. In order to guarantee not to have it stick out, you should select a skin overlap of (less than) half the wall-tichkness.

In the process we found that the description of Skin Overlap (and especially '.. Percentage') is confusing at best and probably misleading, so we'll change that at least.
cheers,
Remco.

**Closed by rburema** 2019-02-15 10:04 UTC
Labels: Category: Cura
