### ISSUE TITLE
Version 4.8 Mouse Selection not possible Mac OS Big Sur

### ISSUE THREAD

**Issue by cfisher273** [Ultimaker/Cura#8930] opened 2020-12-11 17:06 UTC
**Application version**
4.8.0

**Platform**
Mac OSX Big Sur MacBook Pro 15-inch 2.6GHz Intel Core i7

**Printer**
Ender 5 Pro

**Reproduction steps**
1. Adding an stl does not affect this. It is when you do something else. 
2. Add a second stl, now you cannot select the model with the mouse, you must select the object in the object list. Clicking anywhere on the screen will unselect the object. This prohibits the ability to resize, move, or do any other action. Right clicking on the object will still work.
3. Instead of adding a second stl I have tried to add a mesh for blocking supports, or modifying fill percent for a part of the print. As soon as you click in the model to add the mesh, the same problem occurs. No mesh is added. I can no longer select the model, except in object list. Clicking anywhere on the screen will unselect the model. 
4. If I have this problem I can start a new document view and the problem usually goes away. Until I repeat one of these scenarios. 
5. During the problems occurrence I can still use the middle mouse and right mouse button to rotate and move the view of the model. It is only the selection with the mouse that is effected. 

**Screenshot(s)**
None

**Actual results**
See above - Mouse selection is no longer possible

**Expected results**
I should always be able to select the model by clicking on it. I should always be able to move the object using the green, blue, and red arrows. These options no longer function when this problem occurs. 

**Project file**
No file, it happens with all files.

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by nallath** [comment] 2020-12-14 09:07
Duplicate of #8831

**Closed by nallath** 2020-12-14 09:07 UTC
Labels: Type: Bug
