### ISSUE TITLE
Tree support does not correctly apply Z distance and overlaps model

### ISSUE THREAD

**Issue by bagelsesame** [Ultimaker/Cura#11349] opened 2022-01-27 02:34 UTC
### Application Version

4.13.0

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

1. Generate Support: Yes
2. Support structure: Tree
3. Support placement: Everywhere

### Actual results

A) Tree support does not correctly apply Support Z Distance. The first layer of the support overlaps the top layer of the model, effectively merging with it. Enabling support interface results in the same issue with the first layer of the interface merging with the model.

B) The generated tree support intersects the models at several points, thus not respecting the Minimum Support X/Y Distance.

### Expected results

A) The generated tree support's first layer should be above the top layer of the model, respecting the Support Z Distance setting

B) The tree support branches should not be intersecting the model, they should be avoiding it or not be generated at all.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE3_Giant Spider.zip](https://github.com/Ultimaker/Cura/files/7947077/CE3_Giant.Spider.zip)
![Cura_bug_3](https://user-images.githubusercontent.com/7464826/151281735-45b09384-a1d5-42c9-a307-ff2ac0e7c5bc.png)
![Cura_bug_4](https://user-images.githubusercontent.com/7464826/151281742-3b445ebf-45f3-4cb7-8605-0f88c74fe3bf.png)
![Cura_bug_1](https://user-images.githubusercontent.com/7464826/151281724-c173da85-9045-451d-aaa9-fa837684946b.png)
![Cura_bug_2](https://user-images.githubusercontent.com/7464826/151281733-f3db0753-78d4-4c01-8a3f-f5327d7f346f.png)

**Comment by fvrmr** [comment] 2022-01-27 08:59
Hi @bagelsesame thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11258. That's why I will close this issue.

**Closed by fvrmr** 2022-01-27 08:59 UTC
Labels: Type: Bug

**Comment by Ghostkeeper** [comment] 2022-02-03 16:27
This looks more like https://github.com/Ultimaker/Cura/issues/11136, which isn't fixed yet in 4.13.1 (see CURA-8874).
