### ISSUE TITLE
Brim inside text (even with "brim only on outside" option checked)

### ISSUE THREAD

**Issue by giobbino** [Ultimaker/Cura#8648] opened 2020-10-29 04:23 UTC
**Application version**
4.7.1

**Platform**
Windows 7

**Printer**
Creality Ender 3 Pro

**Reproduction steps**
1. I made some text carved in the middle of my item. The text is on the first layer.
2. I sliced the item with the option "Brim only on outside".
3. There's some brim where it should be nothing (empty part that represents the text)

**Screenshot(s)**
(Image showing the problem,
![without brim](https://user-images.githubusercontent.com/63927489/97524817-46d9fa00-1984-11eb-998d-1b6b9601cfc5.jpg)
![with brim](https://user-images.githubusercontent.com/63927489/97524819-48a3bd80-1984-11eb-8af4-56803eadb9f3.jpg)

 perhaps before/after images.) 

**Actual results**
Please look at the images. Should be self-explaining

**Expected results**
Please look at the images. Should be self-explaining

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save Project. For big files you may need to use WeTransfer or similar file sharing sites. G-code files are not project files!)
[Sample STL.zip](https://github.com/Ultimaker/Cura/files/5456128/Sample.STL.zip)

**Comment by Ghostkeeper** [comment] 2020-10-30 12:22
Duplicate of https://github.com/Ultimaker/Cura/issues/4222. This is currently expected behaviour. That is a feature request to allow changing that.

**Closed by Ghostkeeper** 2020-10-30 12:22 UTC
Labels: Type: Bug
