### ISSUE TITLE
Manually set the height and independent support height

### ISSUE THREAD

**Issue by 651851996** [Ultimaker/Cura#6620] opened 2019-11-03 15:25 UTC
1，I hope to set the layer height manually by support blocker.
2，Make the contact contact gap unaffected by the layer height.This has a great impact on the support effect.

Everyone gets the desired print and a flatter support surface.

**Comment by Ghostkeeper** [comment] 2019-11-04 14:18
Please report only one issue/feature per ticket. Otherwise it becomes confusing which issues are fixed or implemented and which are not.

The second suggestion is a duplicate of https://github.com/Ultimaker/Cura/issues/6105. Please continue the discussion about the second suggestion there.

I'm not sure what you mean with "set the layer height manually by support blocker". I'll ignore that now and close this one as duplicate of https://github.com/Ultimaker/Cura/issues/6105. But maybe you'll want to create a new issue about it with a properly filled-in issue template. That would help a lot!

**Closed by Ghostkeeper** 2019-11-04 14:18 UTC
Labels: Type: New Feature
