### ISSUE TITLE
Crashes on start up.

### ISSUE THREAD

**Issue by TelliMantelli** [Ultimaker/Cura#10292] opened 2021-08-16 14:09 UTC
### Application Version

4.10

### Platform

Windows 10 64bit

### Printer

Cant even get there

### Reproduction steps

Start program.

### Actual results

When Cura Loads GUI crashes

### Expected results

Program should start

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

Log file - I have uninstalled all version, have reinstalled gfx driver..issue still remains.
2021-08-16 09:48:31,475 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin FileLogger
2021-08-16 09:48:31,486 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin FirmwareUpdateChecker
2021-08-16 09:48:31,488 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] 
2021-08-16 09:48:31,489 - DEBUG - [MainThread] UM.Backend.Backend._logSocketState [192]: Socket state changed to Connected
2021-08-16 09:48:31,491 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] Cura_SteamEngine version 4.10.0
2021-08-16 09:48:31,491 - DEBUG - [MainThread] UM.Backend.Backend._onSocketStateChanged [181]: Backend connected on port 49676
2021-08-16 09:48:31,493 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] Copyright (C) 2021 Ultimaker
2021-08-16 09:48:31,494 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] 
2021-08-16 09:48:31,496 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] This program is free software: you can redistribute it and/or modify
2021-08-16 09:48:31,497 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] it under the terms of the GNU Affero General Public License as published by
2021-08-16 09:48:31,499 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] the Free Software Foundation, either version 3 of the License, or
2021-08-16 09:48:31,501 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] (at your option) any later version.
2021-08-16 09:48:31,502 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] 
2021-08-16 09:48:31,504 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] This program is distributed in the hope that it will be useful,
2021-08-16 09:48:31,506 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] but WITHOUT ANY WARRANTY; without even the implied warranty of
2021-08-16 09:48:31,509 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
2021-08-16 09:48:31,510 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] GNU Affero General Public License for more details.
2021-08-16 09:48:31,512 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] 
2021-08-16 09:48:31,513 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] You should have received a copy of the GNU Affero General Public License
2021-08-16 09:48:31,516 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] along with this program.  If not, see <http://www.gnu.org/licenses/>.
2021-08-16 09:48:31,516 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin FirmwareUpdater
2021-08-16 09:48:31,522 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin GCodeGzReader
2021-08-16 09:48:31,528 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin GCodeGzWriter
2021-08-16 09:48:31,534 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin GCodeProfileReader
2021-08-16 09:48:31,544 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin GCodeReader
2021-08-16 09:48:31,550 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin GCodeWriter
2021-08-16 09:48:31,557 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin ImageReader
2021-08-16 09:48:31,563 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin LegacyProfileReader
2021-08-16 09:48:31,568 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin LocalContainerProvider
2021-08-16 09:48:31,575 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin LocalFileOutputDevice
2021-08-16 09:48:31,581 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin MachineSettingsAction
2021-08-16 09:48:31,587 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin ModelChecker
2021-08-16 09:48:31,594 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin MonitorStage
2021-08-16 09:48:31,601 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin PerObjectSettingsTool
2021-08-16 09:48:31,607 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin PostProcessingPlugin
2021-08-16 09:48:31,613 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin PrepareStage
2021-08-16 09:48:31,619 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin PreviewStage
2021-08-16 09:48:31,627 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin RemovableDriveOutputDevice
2021-08-16 09:48:31,632 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin SentryLogger
2021-08-16 09:48:31,642 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin SimulationView
2021-08-16 09:48:31,648 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin SliceInfoPlugin
2021-08-16 09:48:31,655 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin SolidView
2021-08-16 09:48:31,662 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin SupportEraser
2021-08-16 09:48:31,676 - WARNING - [MainThread] UM.Logger.logException [112]: Exception: Failed to load packages for Marketplace
2021-08-16 09:48:31,678 - WARNING - [MainThread] UM.Logger.logException [116]: NoneType: None
2021-08-16 09:48:31,679 - WARNING - [MainThread] UM.Logger.logException [112]: Exception: Failed to load packages for Marketplace
2021-08-16 09:48:31,681 - WARNING - [MainThread] UM.Logger.logException [116]: NoneType: None
2021-08-16 09:48:31,682 - WARNING - [MainThread] UM.Logger.logException [112]: Exception: Failed to load packages for Marketplace
2021-08-16 09:48:31,683 - WARNING - [MainThread] UM.Logger.logException [116]: NoneType: None
2021-08-16 09:48:31,685 - WARNING - [MainThread] UM.Logger.logException [112]: Exception: Failed to load packages for Marketplace
2021-08-16 09:48:31,686 - WARNING - [MainThread] UM.Logger.logException [116]: NoneType: None
2021-08-16 09:48:31,690 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin Toolbox
2021-08-16 09:48:31,695 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin CameraTool
2021-08-16 09:48:31,703 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin MirrorTool
2021-08-16 09:48:31,712 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin RotateTool
2021-08-16 09:48:31,721 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin ScaleTool
2021-08-16 09:48:31,728 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin SelectionTool
2021-08-16 09:48:31,738 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin TranslateTool
2021-08-16 09:48:31,744 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin TrimeshReader
2021-08-16 09:48:31,756 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin UFPReader
2021-08-16 09:48:31,762 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin UFPWriter
2021-08-16 09:48:31,769 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin UltimakerMachineActions
2021-08-16 09:48:31,819 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin UM3NetworkPrinting
2021-08-16 09:48:31,827 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin UpdateChecker
2021-08-16 09:48:31,828 - INFO - [JobQueueWorker [0]] UpdateChecker.UpdateCheckerJob.run [40]: Checking for new version of cura
2021-08-16 09:48:31,849 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin USBPrinting
2021-08-16 09:48:31,858 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade21to22
2021-08-16 09:48:31,864 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade22to24
2021-08-16 09:48:31,871 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade25to26
2021-08-16 09:48:31,877 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade26to27
2021-08-16 09:48:31,883 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade27to30
2021-08-16 09:48:31,888 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade30to31
2021-08-16 09:48:31,894 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade32to33
2021-08-16 09:48:31,899 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade33to34
2021-08-16 09:48:31,905 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade34to35
2021-08-16 09:48:31,910 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade35to40
2021-08-16 09:48:31,917 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade40to41
2021-08-16 09:48:31,923 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade41to42
2021-08-16 09:48:31,929 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade42to43
2021-08-16 09:48:31,934 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade43to44
2021-08-16 09:48:31,941 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade44to45
2021-08-16 09:48:31,946 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade45to46
2021-08-16 09:48:31,951 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade460to462
2021-08-16 09:48:31,957 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade462to47
2021-08-16 09:48:31,962 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade47to48
2021-08-16 09:48:31,969 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade48to49
2021-08-16 09:48:31,975 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade49to410
2021-08-16 09:48:31,980 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin SimpleView
2021-08-16 09:48:31,987 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin X3DReader
2021-08-16 09:48:31,994 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin XmlMaterialProfile
2021-08-16 09:48:32,000 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin XRayView
2021-08-16 09:48:32,003 - DEBUG - [MainThread] UM.PluginRegistry.loadPlugins [404]: Loading all plugins took 1.3701467514038086 seconds
2021-08-16 09:48:32,010 - INFO - [MainThread] UM.VersionUpgradeManager.upgrade [163]: Looking for old configuration files to upgrade.
2021-08-16 09:48:32,023 - INFO - [MainThread] UM.VersionUpgradeManager.upgrade [175]: Checking and performing updates took 0.012964963912963867
2021-08-16 09:48:32,025 - INFO - [MainThread] UM.Qt.QtApplication.startSplashWindowPhase [235]: The preferences file cannot be opened or it is corrupted, so we will use default values
2021-08-16 09:48:32,027 - INFO - [MainThread] UM.Qt.QtApplication.startSplashWindowPhase [242]: The preferences file 'None' cannot be found, will use default values
2021-08-16 09:48:32,028 - INFO - [MainThread] UM.Logger.info [128]: Completed loading preferences.
2021-08-16 09:48:32,043 - INFO - [MainThread] UM.Logger.info [128]: Created system tray icon.
2021-08-16 09:48:33,172 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.loadAllMetadata [361]: Loading metadata into container registry took 1.1241674423217773 seconds
2021-08-16 09:48:33,180 - DEBUG - [MainThread] cura.Scene.CuraSceneController.setActiveBuildPlate [142]: Select build plate: 0
2021-08-16 09:48:33,182 - INFO - [MainThread] cura.CuraApplication.run [797]: Initializing machine error checker
2021-08-16 09:48:33,184 - INFO - [MainThread] cura.CuraApplication.run [802]: Initializing machine manager
2021-08-16 09:48:33,186 - INFO - [MainThread] cura.CuraApplication.run [807]: Initializing container manager
2021-08-16 09:48:33,336 - WARNING - [MainThread] LocalContainerProvider.LocalContainerProvider._saveCachedDefinition [295]: The definition cache for definition fdmprinter failed to pickle.
2021-08-16 09:48:33,345 - WARNING - [MainThread] UM.OutputDevice.OutputDeviceManager.removeOutputDevice [235]: Could not find output device with id digital_factory to remove
2021-08-16 09:48:33,365 - DEBUG - [MainThread] UM.Scene.Camera._preferencesChanged [255]: Changing perspective mode to perspective.
2021-08-16 09:48:33,384 - DEBUG - [MainThread] UM.Qt.Bindings.Theme.load [182]: Loading theme file: C:\Program Files\Ultimaker Cura 4.10.0\resources\themes\cura-light\theme.json
2021-08-16 09:48:33,500 - DEBUG - [MainThread] UM.Qt.Bindings.Theme.load [287]: Loaded theme C:\Program Files\Ultimaker Cura 4.10.0\resources\themes\cura-light
2021-08-16 09:48:33,742 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin._createView [342]: Creating post processing plugin view.
2021-08-16 09:48:33,744 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: ChangeAtZ
2021-08-16 09:48:33,745 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: ColorMix
2021-08-16 09:48:33,745 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: CreateThumbnail
2021-08-16 09:48:33,746 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: DisplayFilenameAndLayerOnLCD
2021-08-16 09:48:33,746 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: DisplayProgressOnLCD
2021-08-16 09:48:33,746 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: FilamentChange
2021-08-16 09:48:33,747 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: InsertAtLayerChange
2021-08-16 09:48:33,747 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: PauseAtHeight
2021-08-16 09:48:33,748 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: RetractContinue
2021-08-16 09:48:33,748 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: SearchAndReplace
2021-08-16 09:48:33,749 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: Stretch
2021-08-16 09:48:33,749 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: TimeLapse
2021-08-16 09:48:33,750 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: UsePreviousProbeMeasurements
2021-08-16 09:48:33,866 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin._createView [352]: Post processing view created.
2021-08-16 09:48:33,935 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [421]: file:///C:/Program Files/Ultimaker Cura 4.10.0/resources/qml/PrintSetupSelector/Custom/MenuButton.qml:42:18: QML Label: Cannot anchor to an item that isn't a parent or sibling.
2021-08-16 09:48:33,950 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService._parseJWT [100]: There was no auth data or access token
2021-08-16 09:48:33,985 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [421]: file:///C:/Program Files/Ultimaker Cura 4.10.0/resources/qml/Settings/SettingView.qml:157:5: QML SettingVisibilityPresetsMenu: Binding loop detected for property "width"
2021-08-16 09:48:34,038 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService._parseJWT [100]: There was no auth data or access token
2021-08-16 09:48:34,040 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService._parseJWT [100]: There was no auth data or access token
2021-08-16 09:48:34,082 - DEBUG - [MainThread] UM.Controller.setActiveStage [180]: Setting active stage to PrepareStage
2021-08-16 09:48:34,111 - DEBUG - [MainThread] cura.Machines.Models.NozzleModel._update [28]: Updating NozzleModel.
2021-08-16 09:48:34,113 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [421]: file:///C:/Program Files/Ultimaker Cura 4.10.0/resources/qml/Menus/ConfigurationMenu/ConfigurationMenu.qml:143: TypeError: Cannot read property 'hasRemoteConnection' of null
2021-08-16 09:48:34,155 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [421]: file:///C:/Program Files/Ultimaker Cura 4.10.0/resources/qml/Menus/ConfigurationMenu/CustomConfiguration.qml:233: TypeError: Cannot read property 'isEnabled' of null
2021-08-16 09:48:34,177 - DEBUG - [MainThread] UM.Controller.setActiveView [108]: Setting active view to SolidView
2021-08-16 09:48:34,196 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [421]: file:///C:/Program Files/Ultimaker Cura 4.10.0/resources/qml/WelcomePages/WelcomeContent.qml:33:9: QML Image: Binding loop detected for property "sourceSize.height"
2021-08-16 09:48:34,197 - DEBUG - [MainThread] ModelChecker.ModelChecker._createView [117]: Creating model checker view.
2021-08-16 09:48:34,202 - DEBUG - [MainThread] ModelChecker.ModelChecker._createView [126]: Model checker view created.
2021-08-16 09:48:34,202 - DEBUG - [MainThread] SliceInfoPlugin.SliceInfo._createDialog [76]: Creating dialog [MoreInfoWindow.qml]
2021-08-16 09:48:34,236 - DEBUG - [MainThread] Toolbox.src.Toolbox._makeRequestByType [542]: Requesting [updates] metadata from server.
2021-08-16 09:48:34,239 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService.getAccessToken [126]: No auth data to retrieve the access_token from
2021-08-16 09:48:34,240 - DEBUG - [MainThread] UM.Logger.debug [122]: User is not logged in for Cloud API request to https://api.ultimaker.com/cura-packages/v1/cura/v7.6.0/packages/package-updates?installed_packages=AMFReader:1.0.0&installed_packages=GenericABS:1.4.0&installed_packages=OctofiberPLA:1.0.1&installed_packages=VertexDeltaTPU:1.4.0&installed_packages=MirrorTool:1.0.1&installed_packages=UltimakerNylon:1.4.0&installed_packages=PostProcessingPlugin:2.2.1&installed_packages=VersionUpgrade25to26:1.0.1&installed_packages=TranslateTool:1.0.1&installed_packages=UltimakerPP:1.4.0&installed_packages=ImageReader:1.0.1&installed_packages=GenericPVA:1.4.0&installed_packages=VersionUpgrade44to45:1.0.0&installed_packages=VersionUpgrade41to42:1.0.0&installed_packages=CuraProfileReader:1.0.1&installed_packages=VersionUpgrade35to40:1.0.0&installed_packages=OBJWriter:1.0.1&installed_packages=X3DReader:1.0.1&installed_packages=UltimakerCPE:1.4.0&installed_packages=FABtotumPLA:1.4.0&installed_packages=VersionUpgrade48to49:1.0.0&installed_packages=VersionUpgrade49to410:1.0.0&installed_packages=Toolbox:1.0.1&installed_packages=PrepareStage:1.0.1&installed_packages=VersionUpgrade43to44:1.0.0&installed_packages=GenericNylon:1.4.0&installed_packages=GenericPETG:1.4.0&installed_packages=UM3NetworkPrinting:1.0.1&installed_packages=RemovableDriveOutputDevice:1.0.1&installed_packages=GenericCFFPA:1.4.0&installed_packages=PolyMaxPLA:1.0.1&installed_packages=SupportEraser:1.0.1&installed_packages=UltimakerTPLA:1.4.0&installed_packages=FABtotumABS:1.4.0&installed_packages=GCodeGzWriter:1.0.1&installed_packages=UltimakerMachineActions:1.0.1&installed_packages=FirmwareUpdateChecker:1.0.1&installed_packages=CuraEngineBackend:1.0.1&installed_packages=UltimakerPC:1.4.0&installed_packages=UltimakerPLA:1.4.0&installed_packages=VersionUpgrade45to46:1.0.0&installed_packages=CuraDrive:1.2.0&installed_packages=SimulationView:1.0.1&installed_packages=PolyWoodPLA:1.0.1&installed_packages=LocalContainerProvider:1.0.1&installed_packages=IMADE3DJellyBOXPETG:1.0.1&installed_packages=UFPReader:1.0.0&installed_packages=VersionUpgrade32to33:1.0.1&installed_packages=ConsoleLogger:1.0.1&installed_packages=TrimeshReader:1.0.0&installed_packages=VertexDeltaABS:1.4.0&installed_packages=GenericPP:1.4.0&installed_packages=GenericTPU:1.4.0&installed_packages=VersionUpgrade30to31:1.0.1&installed_packages=MonitorStage:1.0.1&installed_packages=GenericPLA:1.4.0&installed_packages=STLReader:1.0.1&installed_packages=GenericCPEPlus:1.4.0&installed_packages=LocalFileOutputDevice:1.0.1&installed_packages=VersionUpgrade462to47:1.0.0&installed_packages=GenericGFFPA:1.4.0&installed_packages=IMADE3DJellyBOXPLA:1.0.1&installed_packages=SentryLogger:1.0.0&installed_packages=PerObjectSettingsTool:1.0.1&installed_packages=VersionUpgrade34to35:1.0.1&installed_packages=SliceInfoPlugin:1.0.1&installed_packages=CuraProfileWriter:1.0.1&installed_packages=VersionUpgrade33to34:1.0.1&installed_packages=LegacyProfileReader:1.0.1&installed_packages=FirmwareUpdater:1.0.1&installed_packages=GenericCFFCPE:1.4.0&installed_packages=Filo3DPLA:1.0.1&installed_packages=GCodeReader:1.0.1&installed_packages=3MFReader:1.0.1&installed_packages=VersionUpgrade21to22:1.0.1&installed_packages=MachineSettingsAction:1.0.1&installed_packages=PreviewStage:1.0.1&installed_packages=GCodeProfileReader:1.0.1&installed_packages=GenericGFFCPE:1.4.0&installed_packages=FABtotumNylon:1.4.0&installed_packages=DigitalLibrary:1.0.0&installed_packages=GCodeWriter:1.0.1&installed_packages=VersionUpgrade22to24:1.0.1&installed_packages=GenericBAM:1.4.0&installed_packages=UltimakerABS:1.4.0&installed_packages=VersionUpgrade40to41:1.0.1&installed_packages=FABtotumTPU:1.4.0&installed_packages=OBJReader:1.0.1&installed_packages=ModelChecker:1.0.1&installed_packages=UltimakerBAM:1.4.0&installed_packages=VertexDeltaPET:1.4.0&installed_packages=VersionUpgrade47to48:1.0.0&installed_packages=GenericCPE:1.4.0&installed_packages=UltimakerPVA:1.4.0&installed_packages=SelectionTool:1.0.1&installed_packages=RotateTool:1.0.1&installed_packages=FileLogger:1.0.1&installed_packages=VersionUpgrade26to27:1.0.1&installed_packages=PolyFlexPLA:1.0.1&installed_packages=UpdateChecker:1.0.1&installed_packages=GenericPC:1.4.0&installed_packages=SolidView:1.0.1&installed_packages=PolyPlusPLA:1.0.1&installed_packages=CameraTool:1.0.1&installed_packages=ScaleTool:1.0.1&installed_packages=USBPrinting:1.0.2&installed_packages=XRayView:1.0.1&installed_packages=3MFWriter:1.0.1&installed_packages=GenericHIPS:1.4.0&installed_packages=VersionUpgrade42to43:1.0.0&installed_packages=UltimakerCPEP:1.4.0&installed_packages=VertexDeltaPLA:1.4.0&installed_packages=GCodeGzReader:1.0.1&installed_packages=FiberlogyHDPLA:1.0.1&installed_packages=VersionUpgrade460to462:1.0.0&installed_packages=XmlMaterialProfile:1.0.1&installed_packages=SimpleView:1.0.1&installed_packages=VersionUpgrade27to30:1.0.1&installed_packages=UltimakerTPU:1.4.0&installed_packages=DagomaChromatikPLA:1.0.1&installed_packages=UFPWriter:1.0.1&installed_packages=STLWriter:1.0.1&installed_packages=GenericToughPLA:1.4.0
2021-08-16 09:48:34,248 - DEBUG - [JobQueueWorker [1]] cura.Machines.ContainerTree.run [174]: Started background loading of MachineNodes
2021-08-16 09:48:34,248 - DEBUG - [MainThread] cura.CuraApplication.run [851]: Booting Cura took 4.467816591262817 seconds
2021-08-16 09:48:34,249 - DEBUG - [JobQueueWorker [1]] cura.Machines.ContainerTree.run [185]: All MachineNode loading completed
2021-08-16 09:48:34,366 - DEBUG - [MainThread] cura.Machines.Models.QualityProfilesDropDownMenuModel._update [62]: Updating QualityProfilesDropDownMenuModel.
2021-08-16 09:48:34,368 - DEBUG - [MainThread] cura.Machines.Models.QualityProfilesDropDownMenuModel._update [74]: No active GlobalStack, set quality profile model as empty.
2021-08-16 09:48:34,369 - DEBUG - [MainThread] cura.Machines.Models.CustomQualityProfilesDropDownMenuModel._update [33]: Updating CustomQualityProfilesDropDownMenuModel.
2021-08-16 09:48:34,371 - DEBUG - [MainThread] cura.Machines.Models.CustomQualityProfilesDropDownMenuModel._update [38]: No active GlobalStack, set CustomQualityProfilesDropDownMenuModel as empty.
2021-08-16 09:48:34,521 - DEBUG - [MainThread] UM.Qt.QtRenderer._initialize [210]: Support for Vertex Array Objects: True
2021-08-16 09:48:34,528 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [112]: Initialized OpenGL subsystems.
2021-08-16 09:48:34,530 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [113]: OpenGL Version:  4.1.0 NVIDIA 471.68
2021-08-16 09:48:34,533 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [114]: OpenGL Vendor:   NVIDIA Corporation
2021-08-16 09:48:34,534 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [115]: OpenGL Renderer: NVIDIA GeForce GTX 1650 Ti/PCIe/SSE2
2021-08-16 09:48:34,536 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [116]: GLSL Version:    4.0.0
2021-08-16 09:48:34,538 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [59]: Loading shader file [C:\Program Files\Ultimaker Cura 4.10.0\resources\shaders\default.shader]...
2021-08-16 09:48:34,542 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [59]: Loading shader file [C:\Program Files\Ultimaker Cura 4.10.0\resources\shaders\selection.shader]...
2021-08-16 09:48:34,547 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [59]: Loading shader file [C:\Program Files\Ultimaker Cura 4.10.0\resources\shaders\select_face.shader]...
2021-08-16 09:48:34,550 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [59]: Loading shader file [C:\Program Files\Ultimaker Cura 4.10.0\resources\shaders\default.shader]...
2021-08-16 09:48:34,554 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [59]: Loading shader file [C:\Program Files\Ultimaker Cura 4.10.0\resources\shaders\composite.shader]...
2021-08-16 09:48:34,559 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [59]: Loading shader file [C:\Program Files\Ultimaker Cura 4.10.0\resources\shaders\overhang.shader]...
2021-08-16 09:48:34,564 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [59]: Loading shader file [C:\Program Files\Ultimaker Cura 4.10.0\resources\shaders\striped.shader]...
2021-08-16 09:48:34,566 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [59]: Loading shader file [C:\Program Files\Ultimaker Cura 4.10.0\resources\shaders\transparent_object.shader]...
2021-08-16 09:48:34,570 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [59]: Loading shader file [C:\Program Files\Ultimaker Cura 4.10.0\resources\shaders\striped.shader]...
2021-08-16 09:48:34,574 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [59]: Loading shader file [C:\Program Files\Ultimaker Cura 4.10.0\resources\shaders\xray.shader]...
2021-08-16 09:48:34,577 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [59]: Loading shader file [C:\Program Files\Ultimaker Cura 4.10.0\resources\shaders\xray_composite.shader]...
2021-08-16 09:48:34,581 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [59]: Loading shader file [C:\Program Files\Ultimaker Cura 4.10.0\resources\shaders\platform.shader]...
2021-08-16 09:48:34,590 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [59]: Loading shader file [C:\Program Files\Ultimaker Cura 4.10.0\resources\shaders\xray.shader]...

**Comment by fvrmr** [comment] 2021-08-17 07:49
Hi @TelliMantelli thank you for your bug report. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/7744

As a workaround you can edit `%appdata%/cura/4.10/cura.cfg` and add the line `opengl_version_detect = force_legacy` under the `[view]` header.

I will close this issue, but let me know if this works for you!

**Closed by fvrmr** 2021-08-17 07:49 UTC
Labels: Type: Bug

**Comment by TelliMantelli** [comment] 2021-09-08 14:27
This did work thank you!
