### ISSUE TITLE
[3.2.1] Adaptive layers bug with two or more items

### ISSUE THREAD

**Issue by mtmello2003** [Ultimaker/Cura#3429] opened 2018-03-03 03:51 UTC
Using this experimental function the top is cutted:
![2018-03-03_0031](https://user-images.githubusercontent.com/15361590/36930294-87647b00-1e7c-11e8-9d3b-ecfe96e9e6df.png)

if I remove the function, top layers are okay:
![2018-03-03_0049](https://user-images.githubusercontent.com/15361590/36930322-e21f26a8-1e7c-11e8-9981-1a13450dfdf1.png)

**Comment by Vandrasc** [comment] 2018-03-03 08:10
Devs CURA-4967

**Comment by Ghostkeeper** [comment] 2018-03-03 14:45
This is a duplicate of #3318.

As a workaround, if you load the tallest object into Cura first it'll slice everything but the layer heights will still only be based on the first object.

We've fixed this for the 3.3 version.

**Closed by Ghostkeeper** 2018-03-03 14:45 UTC
Labels: Category: CuraEngine, Status: In Progress, Type: Bug
