### ISSUE TITLE
{material_print_temperature} not work for dual extruders 

### ISSUE THREAD

**Issue by pablogventura** [Ultimaker/Cura#2091] opened 2017-07-09 14:19 UTC
I'm using Cura 2.6.1 with a dual extruder prusa printer.
My start gcode uses "{material_print_temperature}", but it is replaced by "210" although I selected 230. If you add another machine profile with only one extruder, and use the same star gcode, it works.

**Comment by Ghostkeeper** [comment] 2017-07-10 01:21
Duplicate of https://github.com/Ultimaker/Cura/issues/1296

**Closed by Ghostkeeper** 2017-07-10 01:21 UTC
Labels: duplicate
