### ISSUE TITLE
Multiply Item Not working

### ISSUE THREAD

**Issue by coghillcort** [Ultimaker/Cura#10958] opened 2021-11-29 16:57 UTC
### Application Version

4.12.0

### Platform

MAC OS  Montery V12.0.1 (MAC Silicon)

### Printer

Creality CR6 SE and FLSUN SR

### Reproduction steps

1. Selected item to be multiplied. 
2. Right Click
3. Select Multiply Selected
4. Enter value (doesn't matter what number is used)
5. Hit Okay
6. Dialog box "placing objects Multiplying and placing objects" appears but no status and dialog cannot be cleared (see attached image.
![Cura V4 Multiply Bug](https://user-images.githubusercontent.com/14495406/143910236-5d18ea69-5c0f-4a81-95c0-39e5e1a9057a.png)
 

### Actual results

Same thing as what is listed in Step 6. Nothing.  The item is not duplicated and the dialog box just stays there. However, Cura is still functional and does not crash and does allow other operations to include slicing. 

### Expected results

Should duplicate the selected item. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Cura V4 Multiply Bug](https://user-images.githubusercontent.com/14495406/143910288-c1c91b18-db3b-4bf8-8dd2-9bcafed47363.png)

**Comment by fvrmr** [comment] 2021-11-30 08:37
Hi @coghillcort thank you for your report.
This is a duplicate of: #10249
And this is fixed in 4.12.1: https://ultimaker.com/software/ultimaker-cura
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-11-30 08:37 UTC
Labels: Type: Bug

**Comment by coghillcort** [comment] 2021-11-30 11:48
Thank you.  Much appreciated.
