### ISSUE TITLE
[3.4.1] Tree supports touch the model but start in the air

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#4399] opened 2018-09-21 14:14 UTC
**Application Version**
3.4.1

**Platform**
Windows 10 x64

**Printer**
Creality cr-10s

**Steps to Reproduce**
Use tree supports. 

**Actual Results**
They will start in the air without touching anything, even tough they normally  support the model.. using the air as support. They only touch the model but not the ground.

**Expected results**
They touch both the ground and the model.

**Additional Information**
![supporti iniziano in aria 1](https://user-images.githubusercontent.com/20385116/45886432-6bcd0d80-bdb9-11e8-8494-0da8d2b94695.png)
![supporti iniziano in aria 2](https://user-images.githubusercontent.com/20385116/45886433-6bcd0d80-bdb9-11e8-81ee-e88c934d2229.png)
[CCR10_Blade_Middle_X3.zip](https://github.com/Ultimaker/Cura/files/2405681/CCR10_Blade_Middle_X3.zip)

**Comment by rburema** [comment] 2018-09-21 14:43
Hi @Liger0,

This is a duplicate of #3249, and will be fixed in the next release. You could try out the 3.5-beta, the fix should be in there as well.

Be advised that the solution at the time is somewhat crude in some cases: if the tree-support becomes wide enough to intersect the model, we remove that specific branch. (One of the reasons Tree-Support still in experimental.)

Tested your attached model in the current master & it does as expected. Please let us know if there still is a problem, if so, we'll reopen this ticket.

cheers, Remco.

**Closed by rburema** 2018-09-21 14:43 UTC
Labels: Status: Duplicate
