### ISSUE TITLE
Cannot rotate, mirror or scale in 15.06

### ISSUE THREAD

**Issue by BESPOKE3DPRINTING** [Ultimaker/Cura#230] opened 2015-08-07 15:59 UTC
The latest version isn't allowing me to rotate, scale or mirror any of my .stl files
any ideas?
Kind regards

**Comment by nallath** [comment] 2015-08-10 07:51
Please have a look at https://github.com/Ultimaker/Cura#logging-issues. We need more information before we can help.

**Comment by BagelOrb** [comment] 2015-08-10 09:17
Besides the information @nallath is asking for:
do you get the rotate, scale etc. buttons on the bottom left?
Do you get the on-model arrows in red, green and blue?

**Comment by BESPOKE3DPRINTING** [comment] 2015-08-10 10:06
I can see the buttons on the left but I am not seeing the on model co
ordinate system. It's like cura isn't recognising any of the stl files.

**Comment by awhiemstra** [comment] 2015-08-10 10:20
Can you select objects by clicking on them?

**Comment by BESPOKE3DPRINTING** [comment] 2015-08-10 11:05
No

**Comment by awhiemstra** [comment] 2015-08-10 11:08
Then it is a duplicate of #84

**Closed by awhiemstra** 2015-08-10 11:08 UTC
Labels: duplicate

**Comment by BESPOKE3DPRINTING** [comment] 2015-08-10 11:25
Ok I'll try that.
Thanks for your support.
