### ISSUE TITLE
my projects won't save or splice. 

### ISSUE THREAD

**Issue by jalynb** [Ultimaker/Cura#14367] opened 2023-01-24 00:14 UTC
### Application Version

5.1.0

### Platform

Windows 11

### Printer

ender-3 pro 

### Reproduction steps

1 i tried saving and splicing multiple times 

### Actual results

nothing 

### Expected results

to save and splice

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

na

**Comment by MariMakes** [comment] 2023-02-03 12:39
Hey @jalynb,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Is it possible that your printjob is located at 0, 0, 0, and it slices if you move it a little away from the center of the buildplate? 
Then it might be a duplicate of https://github.com/Ultimaker/Cura/issues/13643

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Closed** 2023-02-17 13:06 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage, Slicing Error :collision:
