### ISSUE TITLE
4.5 beta - "No layers to show" popup

### ISSUE THREAD

**Issue by tlhintoq** [Ultimaker/Cura#7103] opened 2020-02-15 19:53 UTC
Please either get rid of this popup or give us a checkbox in the preferences to turn it off.

Its annoying as all get out to be in the preview and have it pop up every time you make a change.

There is already so little screen left to view the bed with all the pallets, and overlays adding this really makes it worse.

Or at the very least have it appear and AUTOMATICALLY dismiss itself after 3 seconds.

**Comment by fieldOfView** [comment] 2020-02-15 21:36
Just so we know what you are talking about, is it the message that appears in the Preview tab after slicing if there are no models that are totally inside the buildvolume? It actually says `Nothing to *slice* because none of the models fit the build volume or are assigned to a disabled extruder. Please scale or rotate models to fit, or enable an extruder.`

**Comment by tlhintoq** [comment] 2020-02-16 12:51
@fieldOfView 
That is correct
![image](https://user-images.githubusercontent.com/11351506/74604942-0efa8300-5091-11ea-9d10-cb1c132255e1.png)

**Comment by Liger0** [comment] 2020-02-16 20:20
That is extremely annoying as it appears everything you do indeed.

**Comment by Ghostkeeper** [comment] 2020-02-18 12:02
We've decided to put a checkbox there to not show it again.

**Comment by tlhintoq** [comment] 2020-02-19 18:25
Outstanding.  Thank you !

**Comment by BagelOrb** [comment] 2020-02-21 13:04
If you click the pop-up away it will stay away even when making changes, *except* when you have Slice Automatically enabled.

However, when Slice Automatically is enabled the layers will automatically get loaded.

I therefore propose to never show the message when Slice Automatically is enabled.

**Comment by BagelOrb** [comment] 2020-02-21 14:16
Just implemented both my and @Ghostkeeper s idea.

**Comment by Ghostkeeper** [comment] 2020-02-25 11:54
Fixed for 4.5 stable.

**Closed by Ghostkeeper** 2020-02-25 11:54 UTC
Labels: Type: Bug

**Comment by alfrankgit** [comment] 2022-02-05 09:52
Still there in 4.13.1 with automatic slicing disabled.
If you close it, "Processing layers" gets stuck at 72% (3DBenchy loaded).
No preview appears.

**Comment by Ghostkeeper** [comment] 2022-02-19 19:17
A log file could help to see what the issue is there then. I'm not able to reproduce that issue. Processing the layers completes as normal. Do you have any reproduction steps, perhaps a specific model that it occurs for, if it doesn't happen always?
