### ISSUE TITLE
Hi everyone，What happened, how to solve the problem？cura2.3 do not work！！！

### ISSUE THREAD

**Issue by robin1015** [Ultimaker/Cura#1153] opened 2016-11-17 15:59 UTC
![123](https://cloud.githubusercontent.com/assets/23254213/20396636/c96dd604-ad21-11e6-9b67-bfe622720ed9.PNG)

**Comment by Ghostkeeper** [comment] 2016-11-18 00:13
Duplicate of https://github.com/Ultimaker/Cura/issues/1107.

**Closed by Ghostkeeper** 2016-11-18 00:13 UTC
