### ISSUE TITLE
Raft Base Print Speed and Initial Layer Speed, which one should be used for very first layer?

### ISSUE THREAD

**Issue by ukkuroda** [Ultimaker/Cura#15224] opened 2023-04-13 08:22 UTC
### Application Version

5.3.0

### Platform

Windows10

### Printer

Ender-3 S1

### Reproduction steps

I set 'Print Speed' to 500mm/s so I can test how fast my printer can print.

### Actual results

'Raft Print Speed' was set to '250.0mm/s' and 'Raft Middle Print Speed', 'Raft Base Print Speed' was set to '187.5mm/s'.
And Initial Layer of the raft was printed with '187.5mm/s'.

### Expected results

I think the printing speed of the initial layer should follow 'Initial Layer' value instead of 'Raft Base Print Speed'.
Or, maybe 'Raft Base Print Speed' should be derived from 'Initial Layer Speed' instead of 'Print Speed'.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[CE3S1_washer.zip](https://github.com/Ultimaker/Cura/files/11219882/CE3S1_washer.zip)

**Comment by GregValiant** [comment] 2023-04-13 19:26
Thanks for the report.
I sliced your project and it looked good to me.
The Raft is the Raft so it has it's own speed section.  The speeds I see in the gcode exactly match what you have the raft set to.
The "Initial Layer" speed refers to the model so if you happen to print on a raft the first layer of the actual print (LAYER:0 in the gcode) will be at "Initial Layer Speed".  Layers with negative numbers will be at raft speeds.  That is expected behavior and it looks like it's working correctly.

That's a very small part and you might be bumping up against the "Minimum Layer Time".
There are 104 extrusions at 500mm/sec extrusions in the gcode.  There are also 104 extrusions at 258mm/sec.  That might be because of the Minimum Layer Time.

Try bringing in a flat sided calibration cube.  Scale it to 200 x 200 x 2mm thick and change the Skin line directions to [0, 90].  Set the Bed Adhesion to "None" and "Number of Slower Layers" to 0.  I see you have the Initial Layer Print speed less than 500 so in your case it would be the 2nd layer and up that go down at 500. 

My older Ender 3 Pro will print well at 175 but above that the extruder doesn't keep up.  I suppose I could tweak the E Acceleration but I lost interest at that point.  I like the way the materials look when printed at slower speeds.

At any rate I don't see a bug here but rather "expected behavior".  I'll remove the bug label and close this.  I hope you understand.

**Closed by GregValiant** 2023-04-13 19:26 UTC
Labels: Type: Discussion
