### ISSUE TITLE
Closes out

### ISSUE THREAD

**Issue by SithLordAgony** [Ultimaker/Cura#11969] opened 2022-04-25 21:40 UTC
### Application Version

5

### Platform

Windows 10

### Printer

Ender3 Pro

### Reproduction steps

Started the program. Added stl file spliced, then printed via USB cord. after about 20 mins program just closes out this has happened twice.

### Actual results

redownloading older version

### Expected results

you should fix it so this doesnt happen. there was nothing reported for as crash

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no

**Comment by fvrmr** [comment] 2022-04-26 12:49
Hi @SithLordAgony thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11896, because it is a duplicate I will close this issue.

**Closed by fvrmr** 2022-04-26 12:49 UTC
Labels: Type: Bug
