### ISSUE TITLE
Wacom tablet problems - continued

### ISSUE THREAD

**Issue by 3dHawwy** [Ultimaker/Cura#12353] opened 2022-05-25 20:50 UTC
### Application Version

5.0

### Platform

Mac Monterey 12.4

### Printer

Creality Ender 3 V2

### Reproduction steps

I am have problems using the Wacom tablet with Cura 5.0.  This is a new issue, never had problems with earlier Cura versions.  Sometimes it works for a minute or so, then Cura doesn't respond anymore to any Wacom control.  

### Actual results

I have to re-start Cura and using trackpad control or mouse ( which I don't like ).

### Expected results

Full Wacom support

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

n/a

**Comment by Ghostkeeper** [comment] 2022-06-01 12:06
Duplicate of https://github.com/Ultimaker/Cura/issues/2515.

**Closed by Ghostkeeper** 2022-06-01 12:06 UTC
Labels: Type: Bug

**Comment by MariMakes** [comment] 2022-08-23 12:51
Whoops.
This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12554 instead.
