### ISSUE TITLE
Cura 3.5.1 - Under Extruding - Wrong Filament Diameter - "unknown material" applied by default when 1.75mm filament set

### ISSUE THREAD

**Issue by pinchies** [Ultimaker/Cura#4660] opened 2018-10-26 04:53 UTC
In 3.5.1 the machine filament diameter is not respected, unless a material is selected. In 3.5.1 there is a bug where no material is selected by default. This results in custom printers with 1.75mm filament diameters experiencing severe under extrusion. Verified this issue is not present in 3.5. Verified this issue does occur after resetting Cura.

**Application Version**
Cura 3.5.1 or higher

**Platform**
Mac OS - High Sierra 10.13.6 (17G65)

**Printer**
Any

**Steps to Reproduce**

1. Add a new custom printer
2. Under machine settings, set filament diameter to 1.75
3. Add stl file, and export gcode - save as "test_unknown_material.gcode".
4. Under materials, you will see the material currently selected is "unknown material". Even though in the slicer interface PLA is shown. (see image at bottom of issue)
5. Select generic PLA from the matieral manager, and activate that.
6. Slice again, and save as "test_generic_PLA.gcode".
7. Open both files - observe that the filament length for the unknown material is half as long - it is slicing as 2.85mm filament even though we specifically set 1.75mm in the machine settings.

**Actual Results**
1. Setting the machine filament diameter to 1.75 causes the current material to be set to "unknown material".
2. When "unknown material" is selected, when a file is sliced, the machine filament diameter is ignored, and the material is sliced as 2.85mm.

**Expected results**
1. Setting the machine filament to 1.75 should not change the material selected. 
2. The filament diameter set in machine settings should be used to slice the material.

**Additional Information**
Verified bug after removing and reconfiguring all Cura files.
<img width="892" alt="screen shot 2018-10-26 at 3 45 35 pm" src="https://user-images.githubusercontent.com/13392985/47545239-e2b87180-d936-11e8-9089-136ac00fa31c.png">

**Comment by rburema** [comment] 2018-10-26 14:16
Hi @pinchies, This seems like a duplicate of https://github.com/Ultimaker/Cura/issues/4582 , and was fixed in master very recently. cheers, Remco.

**Comment by pinchies** [comment] 2018-10-26 14:19
I'm satisfied that it looks like it has been fixed. I hope the 3.6 release comes out pretty soon... I lost many hours to troubleshooting this one, first thinking that my printer was on the fritz... this bug will affect every single user who has 1.75 who sets up a custom printer.

**Comment by pinchies** [comment] 2018-10-29 17:19
Hi team, any ETA for 3.6? I've been helping people all day on our facebook group and forum - many people are running into this bug and suffering underextrusion. It's causing people to waste a whole bunch of time diagnosing hardware, when the problem is software.

**Comment by smartavionics** [comment] 2018-10-29 17:42
Hello @pinchies, you could try one of my master branch builds. The most recent is likely to contain the fix although I can't be 100% sure. You can find them at:

https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0

**Comment by pinchies** [comment] 2018-10-29 17:48
Great, thank you, I'll try that out.

**Comment by diegopradogesto** [comment] 2018-10-31 20:00
3.6 BETA is live from today. You can try if this is fixed for you.

**Comment by diegopradogesto** [comment] 2018-10-31 20:03
I'm closing this issue since it's considered as a duplicate and because it is fixed in our 3.6 branch and master.

**Closed by diegopradogesto** 2018-10-31 20:03 UTC
Labels: Status: Duplicate

**Comment by Picklwarrior** [comment] 2020-11-14 07:08
I am literally having this issue in 4.8. I didn't upgrade from 2.7 for years because ages ago I **finally** figured out this was my problem and I refused to upgrade until I was sure it would never be an issue again. I finally upgraded because I really needed the support remover function and now I'm having the exact same problem.

**Comment by Ghostkeeper** [comment] 2020-11-17 22:06
You should not be able to get any 2.85mm materials to load in a printer that uses 1.75mm. Do you have reproduction steps for us?
