### ISSUE TITLE
Skirt is printed after the Tree Support during first layer

### ISSUE THREAD

**Issue by jairov4** [Ultimaker/Cura#5384] opened 2019-03-03 14:03 UTC
**Application Version**
3.6.0

**Platform**
Windows

**Printer**
TEVO Tarantula

**Steps to Reproduce**
Disable Support
Enable Tree Support (In experimental section)
Enable Skirt
Enable Support brim*
Print!

**Actual Results**
The Skirt is printed after the tree support during first layer

**Expected results**
The first thing to print should be the Skirt

**Additional Information**
Please fix this, Im very happy with the tree support results, its just a simple quirk sometimes preventing the perfect printing

**Comment by rburema** [comment] 2019-03-05 10:02
Hi @jairov4,
I've tried to reproduce this in 4.0-BETA-2, and found it printed skirt first, even when I switched around the adhesion and/or skirt/brim extruder a couple of times. Could you try that version? The 'final' 4.0.0 will follow within a few weeks.
cheers, Remco.

**Comment by jairov4** [comment] 2019-03-05 14:47
sure I will try it :)

**Comment by MightyCreak** [comment] 2019-03-24 17:04
I do have the same issue (on an Anycubic model), but not only with tree support. I'll share you some screenshots.

Screenshot of the issue w/ tree support:
![Capture d’écran de 2019-03-24 12-54-49](https://user-images.githubusercontent.com/6382548/54882827-68801080-4e34-11e9-8665-6a8e813d1378.png)
As you can see, it's starting the skirt after the tree supports, which is highly problematic (at least with my printer) since it takes a good 50 mm until it starts extruding, so basically the first one or two supports are missing their base, and never adhere to the build plate with the next layers.

Screenshot of the issue w/o tree support:
![image](https://user-images.githubusercontent.com/6382548/54882892-358a4c80-4e35-11e9-9953-93a87aa86363.png)

Here are the 3MF files: [AKLP_support_tests.zip](https://github.com/Ultimaker/Cura/files/3000606/AKLP_support_tests.zip)

**Comment by MightyCreak** [comment] 2019-03-24 17:12
Here is the result of the print with tree support:
![IMG_20190324_130702](https://user-images.githubusercontent.com/6382548/54882985-7767c280-4e36-11e9-8786-1bf23e294e87.jpg)

**Comment by rburema** [comment] 2019-03-26 07:28
@MightyCreak I don't have the printer definition you have 'anycubic_kossel_plus', as such, I couldn't reproduce it (that is, I can only get skin befir the rest is printed). But the missing definition only allows me to import the model; could you maybe send the definition as well?

**Comment by rburema** [comment] 2019-03-26 07:35
... scratch that, I can see it now: it needs 'enable support brim' set to true. Which makes it a duplicate of  ticket #4829. We're working on that! We know what cuases it, and both internal tickets will very probably end up in 4.1

**Closed** 2019-03-26 07:36 UTC
Labels: Status: Duplicate

**Comment by MightyCreak** [comment] 2019-03-26 10:20
Actually, "Enable Support Brim" is already set to true.
![image](https://user-images.githubusercontent.com/6382548/54989570-32a36f00-4f8f-11e9-9935-36e74b04e5cc.png)

**Comment by rburema** [comment] 2019-03-26 10:30
@MightyCreak Yes, I needed that option on 'true' to reproduce the bug.

**Comment by MightyCreak** [comment] 2019-03-26 10:46
I'll wait for the next update then ;)
Thank you!
