### ISSUE TITLE
[3.3.0 beta] Pause/Resume doesn't work.

### ISSUE THREAD

**Issue by kirilledelman** [Ultimaker/Cura#3683] opened 2018-04-18 17:30 UTC
Paused print around 70% to fix stuck filament. Clicked Resume, nothing happens.

Additionally, move axis buttons don't work in paused state. Ideally, I'd like to pause, move Z up, do stuff to extruder, move Z down, resume.

**Comment by Appesteijn** [comment] 2018-04-20 20:40
What printer do you have? We could use some more info.

**Comment by ianpaschal** [comment] 2018-04-20 21:38
Yes, @Appesteijn is correct. Please use the issue template provided when opening an issue. It takes a minute tops to explain what you were doing and what results you got, and without it the possibility that we can diagnose the problem and fix it is basically zero. Please fill it out or we'll have to close the issue.

**Comment by kirilledelman** [comment] 2018-04-21 11:58
Fair enough:
3.3.0 Cura beta 
Mac OS - High SIerra
Custom FDM printer - Marlin 1.8, dual extruder
[Left_box.3mf.zip](https://github.com/Ultimaker/Cura/files/1934458/Left_box.3mf.zip)

**Comment by adrianmihalko** [comment] 2018-04-27 12:59
Same problem with latest cura and Creality Ender 3.

**Comment by Ghostkeeper** [comment] 2018-05-25 09:58
I can't reproduce the bug. It properly resumes when I click Resume. I tested this using an Ultimaker 2 as I don't have the Creality Ender 3 available here.

The way that resuming works is a bit weird. While printing, it normally sends the next command after the printer responds to the previous command with "ok". When you pause, it sees the "ok" but then sends nothing any more. When you resume, it will no longer ignore the next "ok" message so then it continues with sending the next g-code command. But the printer only responds to "ok" after getting g-code. The reason that this works is because every 2 seconds we poll the temperature, which should also give a "ok" message.

So my question is: Does the nozzle temperature indicate correctly in the Cura monitor page? Because if not, then the problem is really that your printer doesn't respond with "ok" to our regular temperature polling.

In the meanwhile I'll see what I can do to make the code a bit more logical and stable there.

**Closed** 2019-01-07 13:57 UTC
Labels: Status: Needs Info

**Comment by krikru** [comment] 2021-06-28 15:49
I had the same issue with the dog test model gcode that came on the microSD card and an Ender-3 I bought new a few weeks ago, so this seems to be purely a Creality issue. When I paused the print, the printer head wouldn't return to home, and when I pressed resume, the nozzle and bed wouldn't reheat again. As a workaround, if I turn off and turn on the machine and then choose resume, the bed and nozzle reheats, the printer head returns to home, and then printing is resumes.
