### ISSUE TITLE
Make overhangs printable in conjuction with support block modified settings

### ISSUE THREAD

**Issue by misslittlem** [Ultimaker/Cura#11670] opened 2022-03-15 19:35 UTC
### Application Version

4.13.1

### Platform

Windows 10

### Printer

All, ender 5 pro, UM2 olsson , UM2+ UM2+E

### Reproduction steps

add a model, enable make overhangs printable. create a support block over an area you do not want make overhangs printable. Modify overlap settings to disable the make overhangs printable setting.

slice

it still has the make overhangs printable in use in that area

### Actual results

it still has the make overhangs printable in use in that area

### Expected results

should be able to control which areas do and do not have make overhangs printable when using support block modifiers

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

its a constant issue

**Comment by gsdaemon** [comment] 2022-03-15 23:15
Looks like a duplicate of this: https://github.com/Ultimaker/Cura/issues/9350
Would be great to have an update on the issue though

**Closed as completed** 2022-03-17 14:36 UTC
Labels: Type: Bug
