### ISSUE TITLE
Ultimaker 3 using both extruders when only 1 material is required

### ISSUE THREAD

**Issue by fish0and0chips** [Ultimaker/Cura#1775] opened 2017-05-02 08:28 UTC
When setting up a print to use just extruder 1 or extruder 2 (we have PLA in 1 and PC in 2), Cura automatically sets up the print to print the first layer with one material and then continue with the other. This is fixed by turning on support material, selecting the correct material and then switching off support again (as we are not using support in this print). This is frustrating to go through every time we switch between the two materials.

You can see in the attached picture that the path of the extruder shows it priming each head in the corner.

![dual extruder](https://cloud.githubusercontent.com/assets/28291942/25609803/b255401e-2f18-11e7-928c-af2916563aa9.PNG)

**Comment by Ghostkeeper** [comment] 2017-05-05 10:55
Ah, huh. We recently had this bug. It seems it was only fixed in the front-end, not in the back-end.

**Comment by Ghostkeeper** [comment] 2017-05-05 10:57
Hmm, I can't reproduce this bug. Perhaps you could export your set-up as a project and upload it here, to see if we can reproduce it?

**Comment by BagelOrb** [comment] 2017-07-21 13:16
Which version of Cura are you using?

**Comment by fish0and0chips** [comment] 2017-07-21 15:32
Hi, sorry, this was in an old build of Cura and doesn't seem to be a problem any more.

**Closed** 2017-07-21 15:32 UTC
Labels: bug, component: CuraEngine, needsinfo
