### ISSUE TITLE
slicing fails when print thin walls turned on on this model 

### ISSUE THREAD

**Issue by greencheetah100** [Ultimaker/Cura#16515] opened 2023-08-19 13:45 UTC
### Cura Version

5.4.0

### Operating System

win 10

### Printer

ender 3 pro

### Name abnormal settings

print thin walls

### Describe model location

slices on left side but not right or right-side up, moving did nothing

### Describe your model

semi truck badly converted from a mesh full of holes. first time trying to slice

### Add your .zip here ⬇️

problem was inconsistently solved using 'lay flat' feature, oriented right side up with print thin walls turned on, or most times with print thin walls off
[semi (1).zip](https://github.com/Ultimaker/Cura/files/12385971/semi.1.zip)

**Comment by MariMakes** [comment] 2024-01-18 15:24
hI @greencheetah100,

Quick update from our side 👋
We are introducing a new tool to analyze slicing crashes like the one you reported. 💪

Even with the changes we made in the latest versions of Cura we still see that your model crashes. 🫤 But we have added your project file to our analyzing tool and found there were at least 8 crashes that were similar to yours, which helps us to narrow down what the cause is of your crash so we can resolve this for you and others.
Hopefully, we can find a solution soon 🤞

I'll be closing this issue as a duplicate but you can follow the progress here https://github.com/Ultimaker/Cura/issues/16417

**Closed by MariMakes** 2024-01-18 15:24 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:

**Comment by HellAholic** [comment] 2024-02-16 09:24
Small update,
Issue is resolved in CURA-11570 and will be part of the next Cura release.
