### ISSUE TITLE
Enable "Layer Height" of Quality tab when adding blocks to override print setting

### ISSUE THREAD

**Issue by delnegri** [Ultimaker/Cura#9181] opened 2021-01-24 23:25 UTC
**Is your feature request related to a problem? Please describe.**
We often need to increase the Z resolution of only parts of the print and Cura does not have this feature. Cura has "Adaptive Layers" in the Experimental tab, but we have no control over it or where to start, finish and set the layer height when printing a piece.

**Describe the solution you'd like**
The best place for this feature is to enable the "Layer Height" of Quality tab when adding a block to override print setting. In this way we can determine at which height the piece will be applied

**Affected users and/or printers**
This is an extremely important feature, it will save printing time, material and increase print quality. 
All users with their 3D printer will benefit from this feature.

Thanks

![LayerHeight](https://user-images.githubusercontent.com/62126565/105647024-fdfde880-5e81-11eb-9924-5ac748ca3a37.JPG)

**Comment by fvrmr** [comment] 2021-01-25 15:31
Thank you for your feature request. 
This is an duplicate of https://github.com/Ultimaker/Cura/issues/7488 that's why I will close this issue. 
You can continue the thread there.

**Closed by fvrmr** 2021-01-25 15:31 UTC
Labels: Type: New Feature
