### ISSUE TITLE
Decimal point vs. decimal comma

### ISSUE THREAD

**Issue by juraj-ondruska** [Ultimaker/Cura#7451] opened 2020-04-09 07:40 UTC
**Application version**
4.5.0

**Platform**
OS: macOS Catalina 10.15.3
GPU1: Intel UHD Graphics 630
GPU2: Radeon Pro 560X

**Printer**
Anet A8

**Reproduction steps**
1. Open "Manage Printers"
2. Select a printer, click "Machine Settings"
3. Open other "Extruder 1" tab
4. Try to change the Nozzle size (currently there is "0.4", rewrite it to "0.8")
5. Close the window
6. Repeat the steps 1-3
7. Check the Nozzle size (the previously set "0.8" was erased and replaced by the dafault "0.4")

**Screenshot(s)**
<img width="639" alt="Screenshot 2020-04-09 at 09 35 45" src="https://user-images.githubusercontent.com/28895178/78869892-90ddab80-7a45-11ea-9143-5fc8053854ba.png">

**Actual results**
Nozzle size was not updated

**Expected results**
Nozzle size is updated to 0.8

**Project file**
n/a

**Log file**
n/a

**Additional information**
The root cause of this issue is a problem in the decimal separator. When I enter "0,8" instead of "0.8", the value is accepted and properly updated and converted to "0.8". The main problem is, that the application displays the current value using decimal point, but when I try to edit it, it accepts decimal comma only.

**Comment by fieldOfView** [comment] 2020-04-09 08:13
Duplicate of https://github.com/Ultimaker/Cura/issues/6546

**Closed** 2020-04-14 12:58 UTC
Labels: Type: Bug
