### ISSUE TITLE
Skin section is repeated ruining surface.

### ISSUE THREAD

**Issue by PhilBaz** [Ultimaker/Cura#13120] opened 2022-08-25 20:38 UTC
### Application Version

5.0

### Platform

win 10

### Printer

Voron - klipper - raspberry pi 3b

### Reproduction steps

Slice..........

### Actual results

Skin section is gone over twice...looks like it has something to do with monotonic. Layer 44. Ruins the print.

### Expected results

Gone once as expected. 

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[skin doubled on layer 44.zip](https://github.com/Ultimaker/Cura/files/9428066/skin.doubled.on.layer.44.zip)

**Comment by MariMakes** [comment] 2022-08-26 14:45
Hey @PhilBaz 

Thanks for your report 👍 
I recognize this issue. It seems to a duplicate of https://github.com/Ultimaker/Cura/issues/12807
It's indeed related to Monotonic and we have an issue on our backlog with the intent to fix it soon. 

I'm closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12807

**Closed by MariMakes** 2022-08-26 14:45 UTC
Labels: Type: Bug, Status: Triage
