### ISSUE TITLE
layer issue

### ISSUE THREAD

**Issue by lbe001** [Ultimaker/Cura#9295] opened 2021-02-19 09:28 UTC
**Application version**
4.8

**Platform**
Win10

**Printer**
Artillery X1

**Reproduction steps**
Always

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
![cura_issue](https://user-images.githubusercontent.com/54121917/108484861-967a6380-729c-11eb-95c5-687248ccb829.PNG)

**Actual results**
Pb offset the layers

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by fvrmr** [comment] 2021-02-19 14:08
Hi @lbe001 could you share your project file? So I try to reproduce this issue.

**Comment by lbe001** [comment] 2021-02-21 20:42
Hi here it is, with CURA 4.7.1 I don't have this issue
Thanks
[anneau2.zip](https://github.com/Ultimaker/Cura/files/6018439/anneau2.zip)

**Comment by fvrmr** [comment] 2021-02-23 08:30
Hi @lbe001 thank you for your file. You attached a stl and not a project file. 
But this is the result I get in 4.8. So no missing layer. 

![Screenshot (66)](https://user-images.githubusercontent.com/77000924/108818354-870b5b00-75b9-11eb-94cf-440ebfe62433.png)

Could you add your project file (file - save project) a project file contains all your settings. So probably also the missing layer.

**Comment by lbe001** [comment] 2021-02-24 22:06
Hi, here is the project file

[anneau2.zip](https://github.com/Ultimaker/Cura/files/6039129/anneau2.zip)

**Comment by fvrmr** [comment] 2021-02-26 10:48
Hi @lbe001 thank you for your project file.

This is happening because of the `hole horizontal expansion`. If you look with the top view at your model you can see that this is happening at layer 28 and layer 49 and between these layers there's is no horizontal hole, because of a 'gap'.  

Layer 48:
![Screenshot (85)](https://user-images.githubusercontent.com/77000924/109290269-aefff600-7827-11eb-97fc-fff487b095b8.png)

As you can see in the screenshot above is there is no 'hole' , because of the hole in the wall. And at the next layer there is a hole, so the hole horizontal expansion applies.

Layer 49:
![Screenshot (84)](https://user-images.githubusercontent.com/77000924/109290292-b6bf9a80-7827-11eb-8c4e-d9ecc98f8d47.png)

When I change the hole horizontal expansion to 0 you will see that it won't happen.

Unfortunately the only solution for this is changing your model in a CAD program and add the expansion on your model there.

I will close this issue, because it is expected behaviour and not a bug. 
But please reach out if this makes sense to you or you have questions about this.

**Closed by fvrmr** 2021-02-26 10:48 UTC
Labels: Type: Bug
