### ISSUE TITLE
Slicing failed with unexpected error

### ISSUE THREAD

**Issue by RRSmith1947** [Ultimaker/Cura#10539] opened 2021-09-29 05:57 UTC
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Creality Ender 3

### Reproduction steps

Dropped an STL file onto Cura build plate and pressed "slice", note this is a single layer (.2mm) thick item

[150mmSquare.zip](https://github.com/Ultimaker/Cura/files/7249183/150mmSquare.zip)

### Actual results

no sliced file was produced

### Expected results

A gcode file

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[150mmSquare.zip](https://github.com/Ultimaker/Cura/files/7249195/150mmSquare.zip)

**Comment by nallath** [comment] 2021-09-29 07:38
Thanks for reporting this. We've had it reported to us a few times now, so I'm closing this in favor of the original one. 

Duplicate of #10394

**Closed by nallath** 2021-09-29 07:38 UTC
Labels: Type: Bug
