### ISSUE TITLE
Cura creates directories in ~

### ISSUE THREAD

**Issue by dsancheznet** [Ultimaker/Cura#9017] opened 2020-12-25 09:56 UTC
First of all, let me thank you for this great slicer. I absolutely love it!

I'm running the Appimage of version 4.8 on Elementary Linux 5.1 and every time I start Cura it creates a subdirectory in my home directory named `~/fontconfig`. If I delete this directory (which seems to be a font cache) it appears again after launching Cura. 
I am very picky on the cleanliness of my home directory (did I say obsessed ? 🤣). And no applications should create visible subdirectories in home. So I see a few solutions here:

1. Make it invisible by preceding it with a period (.)
2. Save all data in the relevant `.config` subdirectory adhering to the standard 
3. Let the user configure where he or she wants the cache to be located.

I think the line between feature request and bug report is pretty blurred, so please forgive me if you consider this to be a feature request.

Best regards and Merry Xmas

**Comment by Ghostkeeper** [comment] 2020-12-27 03:13
Duplicate of https://github.com/Ultimaker/cura-build/issues/239. Some analysis has been going on there.

**Closed by Ghostkeeper** 2020-12-27 03:13 UTC
Labels: Type: Bug
