### ISSUE TITLE
Scale X Y Z UI value/ boxes seem to be incorrectly wired or placed with respect to each other.

### ISSUE THREAD

**Issue by twobob** [Ultimaker/Cura#7799] opened 2020-05-21 17:25 UTC
**Application version**
4.6.1

**Platform**
Windows 10

**Printer**
Creality CR10 

**Reproduction steps**

1. I selected an object and chose SCALE
2. I dragged to tool handle in the Z axis to increase the value and observed the %age value being updated in another column.

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/915232/82586773-0766e080-9b90-11ea-8988-cd595bd73e63.png)

**Actual results**
The Y axis %age increased rather than the Z axis %age value

**Expected results**
The relevant axis %age changing relative to the manipulated intended measurement

**Additional information**
It results in wacky resizes when clicking around in the zoom boxes after resizing something absolutely.

**Comment by ssavickiy** [comment] 2020-05-21 23:17
I also encountered this error 
![Безымянный](https://user-images.githubusercontent.com/23532871/82615137-59c8f100-9bd2-11ea-9bb1-6222a0568078.png)

**Comment by 64Florian** [comment] 2020-05-21 23:47
look like it's the old bug #4136

**Comment by twobob** [comment] 2020-05-22 07:02
Ah thanks. I did search trying to find it.

**Comment by fieldOfView** [comment] 2020-05-22 07:50
As long as the model is not rotated in Cura, the boxes will be "correctly wired".

**Comment by twobob** [comment] 2020-05-22 08:35
I see, so it's some kind of projection issue. Fine. Thus my hack should work for all cases. Good to know

**Comment by Ghostkeeper** [comment] 2020-05-25 13:07
Yeah, it's a well known but decently difficult bug.

Closing this as duplicate of https://github.com/Ultimaker/Cura/issues/4136, https://github.com/Ultimaker/Cura/issues/3625, https://github.com/Ultimaker/Cura/issues/4309, https://github.com/Ultimaker/Cura/issues/4386, https://github.com/Ultimaker/Cura/issues/5221, https://github.com/Ultimaker/Cura/issues/5189, https://github.com/Ultimaker/Cura/issues/5310, https://github.com/Ultimaker/Cura/issues/5462, https://github.com/Ultimaker/Cura/issues/5599, https://github.com/Ultimaker/Cura/issues/5602, https://github.com/Ultimaker/Cura/issues/5603, https://github.com/Ultimaker/Cura/issues/5872, https://github.com/Ultimaker/Cura/issues/5916, https://github.com/Ultimaker/Cura/issues/5965, https://github.com/Ultimaker/Cura/issues/6148, https://github.com/Ultimaker/Cura/issues/6150, https://github.com/Ultimaker/Cura/issues/6238, https://github.com/Ultimaker/Cura/issues/6370, https://github.com/Ultimaker/Cura/issues/6619, https://github.com/Ultimaker/Cura/issues/6770, https://github.com/Ultimaker/Cura/issues/6829, https://github.com/Ultimaker/Cura/issues/6890, https://github.com/Ultimaker/Cura/issues/6971, https://github.com/Ultimaker/Cura/issues/7102, https://github.com/Ultimaker/Cura/issues/7142, https://github.com/Ultimaker/Cura/issues/7237, https://github.com/Ultimaker/Cura/issues/7388, https://github.com/Ultimaker/Cura/issues/7446, https://github.com/Ultimaker/Cura/issues/7448, https://github.com/Ultimaker/Cura/issues/7582, https://github.com/Ultimaker/Cura/issues/7638, https://github.com/Ultimaker/Cura/issues/7703, https://github.com/Ultimaker/Cura/issues/7768 and https://github.com/Ultimaker/Cura/issues/7778. Yup, it's bad.

**Closed** 2020-05-25 13:07 UTC
Labels: Type: Bug
