### ISSUE TITLE
While USB printing: printing time and estimated time left not shown/calculated correctly

### ISSUE THREAD

**Issue by RogerWeihrauch** [Ultimaker/Cura#2727] opened 2017-11-04 13:35 UTC
Hints:
MacOS 10.13.1; Cura:3.0.4; Printer Profile: RF100; User: NOOB level (new to 3D Printing)

In attached PNG you may see that the estimated time left and the printing time (in summay, I think) are both shown as zero/not calculated values. Those, I know, are not essentially for using Cura Software, but will be helpful if shown correctly.
Thank you for correcting this feature.

Kind regards,
Roger
![cura_printing_time](https://user-images.githubusercontent.com/15932486/32405840-442fe5de-c16d-11e7-9821-690e588cfb18.png)

**Comment by Ghostkeeper** [comment] 2017-11-10 00:50
This is a duplicate of https://github.com/Ultimaker/Cura/issues/1448

**Closed by Ghostkeeper** 2017-11-10 00:50 UTC
