### ISSUE TITLE
laggy print setting menu in cura 5.xx

### ISSUE THREAD

**Issue by xanovich** [Ultimaker/Cura#13737] opened 2022-11-05 11:24 UTC
### Is your feature request related to a problem?

If u move print settings list with mouse roller, it moves very slowly, and it visibly deccelerate, so maybe it is hard codded feature. But for me feature like that is more like a bug, it feels like CPU is throttling. Generally makes GUI unresponsive. 
There is no visible lag when u move slider up and down with coursor. 

Maybe it is small thing, but it hated it so much, that I was still using Cura v4. I just downloaded  newest v5 and problem is still the same as in the beta. Also list of visible option in  preferences opens so slow, maybe it is related.

All other things are working properly.

### Describe the solution you'd like

Smooth without lagging

### Describe alternatives you've considered

Using Cura v4 or comiting suicide

### Affected users and/or printers

mental health

**Comment by MariMakes** [comment] 2022-11-08 13:38
Hey @xanovich,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12110
We have a ticket on our backlog with the intent to improve this behavior.
Some first efforts were made here: https://github.com/Ultimaker/Cura/commit/56ad7c4273c47dd9fe439668ab169ba7c305c113

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12110

**Closed by MariMakes** 2022-11-08 13:38 UTC
Labels: Type: New Feature, Status: Triage
