### ISSUE TITLE
[4.6.1] Can't login to Cura

### ISSUE THREAD

**Issue by darloe** [Ultimaker/Cura#8126] opened 2020-07-30 15:59 UTC
**Cura 4.6.1**
(The version of the application this issue occurs with.)

**Win10 Home 1909**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)

**N/A**
(Which printer was selected in Cura?)

**Reproduction steps**
1. Open Cura application
2. Click 'Sign in' in top right corner

**
![Screenshot 2020-07-30 09 46 47](https://user-images.githubusercontent.com/69006475/88945400-2eeebf00-d24b-11ea-8090-4427f1f24a81.png)
**
(Image showing the problem, perhaps before/after images.) 

**Get error page as shown in attached screenshot, sometimes even after entering username/password**
(What happens after the above steps have been followed.)

**Successfully login to Cura account to access Cura backups**
(What should happen after the above steps have been followed.)

**N/A**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**
[cura.log](https://github.com/Ultimaker/Cura/files/5002381/cura.log)
**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Sometimes after clicking 'Sign in' in Cura, I get to a login page and then it directs me to the error page. Other times it goes directly to the error page.**
(Extra information relevant to the issue.)

**Comment by Ghostkeeper** [comment] 2020-08-03 13:55
I get this as well. For me the issue is that I've configured my browser to delete cookies from a domain if I there are no more tabs on that domain. Since the Ultimaker website's log-in process takes you through several domains that are not configured to share cookies, the cookies are deleted and I get this message. It basically means that I need to log-in 3 times before I get a successful log-in.
When I reported the issue to them, it was rejected. I'd just have to retain cookies for longer or suck it up and click on the login button three times.

Does the problem still occur if you remove all Cookie Autodelete add-ons in your browser and (temporarily) set the cookie policy to keep cookies indefinitely?

**Comment by darloe** [comment] 2020-08-13 03:20
Sorry for the delayed response, I've been too busy working to get to this issue. So I've set Chrome to allow all cookies and the "Clear cookies and site data when you quit Chrome" setting is off. This still doesn't make a difference.
I tried the suggestion to login 3 times, and on the second attempt it indicates it's trying to reach 'localhost' but can't connect. I don't know what this means or if this has significance here.

**Comment by Ghostkeeper** [comment] 2020-08-17 09:20
Your issue is different then from what we're seeing. Maybe a firewall is preventing Cura from listening to connections on localhost? Would be weird though, since that is also used for slicing.

Maybe if someone else also gets this problem we can learn more about the similarities in your situations, to indicate what could be causing the problem.

**Comment by darloe** [comment] 2020-08-27 23:38
Turning off the firewall did not resolve the issue.

**Comment by darloe** [comment] 2020-09-21 03:33
I recently updated Cura to version 4.7.1 and was immediately able to login to my Ultimaker account through Cura, so I thought the update resolved this issue. But I just now tried logging in again, and have the same problems as before. Evidently this issue is not yet permanently fixed.

**Comment by Ghostkeeper** [comment] 2020-09-23 14:45
@allardhoeve is this something you guys have been able to reproduce?

**Comment by darloe** [comment] 2021-08-11 04:51
This issue persists in version 4.10. Can't this be fixed?

**Comment by nallath** [comment] 2021-08-11 07:48
We've added extra logging in the meantime and also some extra for 4.11 (which will be out for beta soon).

Could you try it with a clean install again and provide us the log files?

**Comment by darloe** [comment] 2021-08-14 22:23
I reinstalled Cura 4.10 but this issue persists. The log file is attached.

**Comment by nallath** [comment] 2021-08-16 07:08
If you reply via email and add attachments, they won't end up with us, sorry. You will need to upload them via the web interface. 

I would also ask you to try again with 4.11 (the beta will be out in a few days). We've drastically increased the verbosity of logging of the login sequence, so that would provide us with a lot more information.

**Comment by darloe** [comment] 2021-09-30 02:06
I've installed Cura 4.11, but this issue still persists. The log file is attached.
[cura.log](https://github.com/Ultimaker/Cura/files/7256065/cura.log)

**Comment by allardhoeve** [comment] 2021-10-01 10:18
@rvdh

**Comment by debonthj** [comment] 2021-11-11 19:28
I am getting the same error with the Cura to Ultimaker account link on my work laptop (issue not present on my personal laptop).

Log below. Does anyone have a workaround? Note I have been able to resolve similar or same issue with Arduino IDE not connecting to online files via a workaround I believe I found on github, but I have no idea what I am doing, just copy and pasting code. Hopefully someone can figure out something similar for Cura.


2021-11-11 20:11:29,783 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService.startAuthorizationFlow [170]: Starting new OAuth2 flow...
2021-11-11 20:11:29,787 - DEBUG - [MainThread] cura.OAuth2.LocalAuthorizationServer.start [64]: Starting local web server to handle authorization callback on port 32118
2021-11-11 20:11:29,794 - DEBUG - [Thread-8] cura.OAuth2.LocalAuthorizationServer._serve_forever [101]: Local web server for authorization has started
2021-11-11 20:11:31,244 - DEBUG - [Thread-9] cura.OAuth2.AuthorizationService._onAuthStateChanged [233]: Got callback from Authorization state. Something went wrong: [Unable to connect to remote server: HTTPSConnectionPool(host='account.ultimaker.com', port=443): Max retries exceeded with url: /token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')))]
2021-11-11 20:11:31,253 - DEBUG - [Thread-9] cura.OAuth2.LocalAuthorizationServer.stop [81]: Stopping local oauth2 web server...
2021-11-11 20:11:31,253 - WARNING - [MainThread] cura.API.Account._onLoginStateChanged [184]: Failed to login: Unable to connect to remote server: HTTPSConnectionPool(host='account.ultimaker.com', port=443): Max retries exceeded with url: /token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')))
2021-11-11 20:11:31,261 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService._parseJWT [100]: There was no auth data or access token
2021-11-11 20:11:31,266 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService._parseJWT [100]: There was no auth data or access token
2021-11-11 20:11:31,273 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService._parseJWT [100]: There was no auth data or access token
2021-11-11 20:11:31,281 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService.getAccessToken [133]: No auth data to retrieve the access_token from
2021-11-11 20:11:31,288 - DEBUG - [MainThread] UM.Logger.debug [122]: User is not logged in for Cloud API request to https://api.ultimaker.com/cura/v1/feature_budgets
2021-11-11 20:11:31,299 - DEBUG - [MainThread] UM.Logger.debug [122]: Requesting packages metadata from server.
2021-11-11 20:11:31,303 - DEBUG - [Thread-9] cura.OAuth2.LocalAuthorizationServer.stop [89]: Local oauth2 web server was shut down
2021-11-11 20:11:31,309 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService.getAccessToken [133]: No auth data to retrieve the access_token from
2021-11-11 20:11:31,317 - DEBUG - [MainThread] UM.Logger.debug [122]: User is not logged in for Cloud API request to https://api.ultimaker.com/cura-packages/v1/cura/v7.8.0/packages
2021-11-11 20:11:31,325 - DEBUG - [MainThread] UM.Logger.debug [122]: Requesting authors metadata from server.
2021-11-11 20:11:31,334 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService.getAccessToken [133]: No auth data to retrieve the access_token from
2021-11-11 20:11:31,343 - DEBUG - [MainThread] UM.Logger.debug [122]: User is not logged in for Cloud API request to https://api.ultimaker.com/cura-packages/v1/cura/v7.8.0/authors
2021-11-11 20:11:31,688 - DEBUG - [MainThread] UM.TaskManagement.HttpRequestManager._onRequestError [376]: request[9e6ae1b8][get][PyQt5.QtCore.QUrl('https://api.ultimaker.com/cura/v1/feature_budgets')][timeout=10][no-data] got an QNetworkReplyError Host requires authentication. The server returned: b'{"errors": [{"id": "7d31106c-c713-4f5e-8c24-ea616cf4fd9e", "code": "noBearerToken", "http_status": "401", "title": "No bearer token has been given to authenticate the request.", "meta": {"error_type": "AuthError", "url": "https://api.ultimaker.com/feature_budgets"}}]}'
2021-11-11 20:11:31,705 - WARNING - [MainThread] UM.Logger.warning [134]: Digital Factory: Response is not a feature budget, likely an error: <PyQt5.QtNetwork.QNetworkReply object at 0x00000243C5C4DA60>

**Comment by debonthj** [comment] 2021-11-11 19:32
Not sure why this is closed, there are plenty of people using ultimaker printers for work on work laptops, Ultimaker need to fix this, and issue should be reopened until done.

**Comment by Ghostkeeper** [comment] 2021-11-18 10:52
Yeah, not to worry. We did have this on our backlog for quite a while. And we are working on a fix here: https://github.com/Ultimaker/Cura/pull/10854

Most likely this error will keep occurring for plug-ins that also use Requests. We can't remove the Python module until we do a major SDK version increment (which is allowed to have backwards incompatibilities).

I think it is better to communicate the work-in-progress by re-opening the issue indeed.

**Comment by Ghostkeeper** [comment] 2021-11-26 10:28
Fixed in Cura 4.13, by this pull request: https://github.com/Ultimaker/Cura/pull/10901

**Closed by Ghostkeeper** 2021-11-26 10:28 UTC
Labels: Type: Bug, Category: Cloud
