### ISSUE TITLE
Use parts of the infill as transition for filament changes within one structure

### ISSUE THREAD

**Issue by AlexHuebi** [Ultimaker/Cura#9191] opened 2021-01-26 20:42 UTC
This feature request is "relatively" simple. I want to use a different filament for the wall than the infill is as a cost saving measure. But if use different filaments, a prime tower is needed since I don't want (eg black) filament as a part of the wall (that would be wooden filament in my case).

If a bit of the infill can be used as a transition, then the walls could be clean and the prime tower could be turned off.

Using the prime tower is wasteful and cant be used in some cases if the printed part is almost as large as the build area itself. Using only one filament is too expensive for this usecase where a bit of structural integrity is needed. 

One example where a prime tower doesn't even fit:
![grafik](https://user-images.githubusercontent.com/39099705/105902494-03dd0080-601f-11eb-8462-32ffb10d50d4.png)

**Comment by fvrmr** [comment] 2021-01-28 10:18
Hi @AlexHuebi thank you for your feature request. I will discuss this with the team. Keep you posted!

**Comment by Ghostkeeper** [comment] 2021-01-29 09:15
Duplicate of https://github.com/Ultimaker/Cura/issues/3657.

**Closed** 2021-01-29 09:18 UTC
Labels: Type: New Feature
