### ISSUE TITLE
Sort Parts by a number

### ISSUE THREAD

**Issue by tenner21** [Ultimaker/Cura#9183] opened 2021-01-25 15:35 UTC
**Is your feature request related to a problem? Please describe.**
(A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])

Hello, 
I have the problem, that for printing multiple pieces, every piece will sorted arbitrarily. So if i want to print part by part, f.e. 20 parts with 4 in a line, cura placed the sequence arbitrarily. 

**Describe the solution you'd like**
(A clear and concise description of what you want to happen. If possible, describe why you think this is a good solution.)

There was a "Sort by number"-function neaded. So every can manual place a sequence-number to every placed part and everything was fine. 

This problem was discussed in many forums. 

**Describe alternatives you've considered**
(A clear and concise description of any alternative solutions or features you've considered. Again, if possible, think about why these alternatives are not working out.)

**Affected users and/or printers**
(Who do you think will benefit from this? Is everyone going to benefit from these changes? Or specific kinds of users?)

**Additional context**
(Add any other context or screenshots about the feature request here.)

**Comment by fvrmr** [comment] 2021-01-26 11:58
Thank you for your feature request. 
This feature request is a duplicate of #4835 
I will close this issue because it is a duplicate, but please feel free to continue the thread there.

**Closed by fvrmr** 2021-01-26 11:58 UTC
Labels: Type: New Feature
