### ISSUE TITLE
Cura 4.9 Locks up Mac

### ISSUE THREAD

**Issue by Bflat703** [Ultimaker/Cura#9673] opened 2021-04-23 22:08 UTC
### Application Version

4.9.0

### Platform

Mac OS 10.13.6

### Printer

CR-10

### Reproduction steps

Slice Project
Switch to "Preview" mode

First attempt locked up the entire computer.
Second attempt locked up Cura.
[Reflecting Unit Problem.3mf.zip](https://github.com/Ultimaker/Cura/files/6368269/Reflecting.Unit.Problem.3mf.zip)

### Actual results

System locked up.
Force restart.

### Expected results

Sort of expected it to work.

### Additional information

Mac Pro (Mid 2010) 3.2 GHz Quad-Core Xeon 32GB
ATI Radeon HD 5770 1024 MB

[cura.log](https://github.com/Ultimaker/Cura/files/6368283/cura.log)

**Comment by talondnb** [comment] 2021-04-24 08:49
Same here. iMac 2011, complete hangup but if I click another tab quick enough (e.g. Monitor or Prepare) I can avoid the full lockup.

**Comment by Vasiy** [comment] 2021-04-24 16:18
same issue

**Comment by jellespijker** [comment] 2021-04-24 17:46
Duplicate of #9631 I will therefore close this issue in favor of that one.

**Closed by jellespijker** 2021-04-24 17:46 UTC
Labels: Type: Bug
