### ISSUE TITLE
Suggestion: Dynamic File Name

### ISSUE THREAD

**Issue by Raiden38** [Ultimaker/Cura#4490] opened 2018-10-05 12:52 UTC
Not an issue but a suggestion:

Can you build a way to generate dynamically the file name of the gcode file?

Example, I would like the file name to be:

PartName-Color-PrintTime.gcode

or 
MachineName-PartName-PrintTime.gcode

Thanks!

**Comment by fieldOfView** [comment] 2018-10-05 19:56
Duplicate of https://github.com/Ultimaker/Cura/issues/4076 (among others)

**Closed** 2018-10-06 16:42 UTC
