### ISSUE TITLE
Acceleration Settings for Bridging

### ISSUE THREAD

**Issue by dlinders10** [Ultimaker/Cura#8941] opened 2020-12-13 21:17 UTC
I would like for there to be acceleration settings for bridging. I like to use lower custom acceleration settings for my prints so I can get detailed outer walls but the low acceleration messes up bridging. If I use higher acceleration values, bridging is improved but the rest of print isn't as good. This feature is in Prusa slicer and works very well enabling low accelerations where needed and high acceleration which is necessary for good bridges.

**Comment by smartavionics** [comment] 2020-12-13 22:09
See https://github.com/smartavionics/Cura/releases/tag/20201121 for a Cura variant that provides accel/jerk settings for bridge walls and skins.

**Comment by Ghostkeeper** [comment] 2020-12-18 15:47
Duplicate of https://github.com/Ultimaker/Cura/issues/4955.

**Closed by Ghostkeeper** 2020-12-18 15:47 UTC
Labels: Type: New Feature
