### ISSUE TITLE
Face aligning does not work

### ISSUE THREAD

**Issue by NoteToSelfFindGoodNickname** [Ultimaker/Cura#13729] opened 2022-11-04 05:08 UTC
### Application Version

5.2.0

### Platform

Windows 10

### Printer

Kobra Max

### Reproduction steps

I clicked the face that I want to align.
It does not work.

### Actual results

It does not do what it should.

### Expected results

It should align the clicked face to the build plate.
[AKMAX_rock1.zip](https://github.com/Ultimaker/Cura/files/9935173/AKMAX_rock1.zip)

Here is a video:
https://www.youtube.com/watch?v=5EvQoe4HPLc

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Video here:

https://www.youtube.com/watch?v=5EvQoe4HPLc

[AKMAX_rock1.zip](https://github.com/Ultimaker/Cura/files/9935178/AKMAX_rock1.zip)

**Comment by GregValiant** [comment] 2022-11-04 13:15
Thanks for the report.
This is a duplicate of #13697 and I'll mark it as such.
If you check out that post you will see that @MariMakes has provided a workaround and that the issue has been deferred.
I'm going to close this ticket as the subject is well covered in the 13697.  You can respond in that thread.

**Closed by GregValiant** 2022-11-04 13:15 UTC
Labels: Type: Bug, Status: Duplicate, Status: Deferred
