### ISSUE TITLE
The print parameter description (pop-up display) is interrupted.

### ISSUE THREAD

**Issue by viper0078** [Ultimaker/Cura#8493] opened 2020-10-04 14:43 UTC
**Application version**
4.6.2
**Platform**
Win10
**Printer**
Custom

The print parameter pop-up message is interrupted. I would like the message to be displayed without interruption.
![無題](https://user-images.githubusercontent.com/69872727/95018564-9423be00-069b-11eb-8cce-5473fef60d05.png)
Also, is it possible to reference these descriptions as a text file? I would like to convert this using a translation software.
Best regards.

**Comment by nallath** [comment] 2020-10-05 07:39
This is caused by the print setting guide and not by Cura itself. That being said, this was semi recently changed. If it's not in the 4.7.1 release, it will be in the 4.8 release.

**Closed by nallath** 2020-10-05 07:39 UTC
Labels: Type: Bug

**Comment by Ghostkeeper** [comment] 2020-10-06 13:13
Yeah that was merged into 4.8 (while 4.7 was in beta). I purposefully waited until 4.7 was branched off and feature frozen to allow more time to test the scrolling of tooltips.

**Comment by viper0078** [comment] 2020-10-07 00:56
Thanks for the answer.

By the way, is it possible to refer to these detailed instructions in a text file or something like that, I wish I could do it on the web site.
I want to convert them in my translation software.

I'm taking the following steps
1) Pop up the detail view.
2) Capture the screen and display it in paint software.
3) Convert it into a text file with OCR software.
4) Use a translation software to convert the file.

It's very complicated.

**Comment by Ghostkeeper** [comment] 2020-10-09 11:10
The Settings Guide is available online here: https://github.com/Ghostkeeper/SettingsGuide

You can view the articles there online too (under "resources/articles"). Or you can download the text files by clicking on the green "Code" button on the top right corner and then "Download zip".

**Comment by viper0078** [comment] 2020-10-09 14:37
Thank you for the information.
