### ISSUE TITLE
Layered fan speed

### ISSUE THREAD

**Issue by Snaiper1945** [Ultimaker/Cura#6960] opened 2020-01-13 07:10 UTC
I would like to see the layered fan speed, by analogy with the material flow.

**Comment by Ghostkeeper** [comment] 2020-01-14 13:41
What do you mean?

**Comment by lbibass** [comment] 2020-02-02 20:13
Perhaps they mean they would like to have the fan speed change depending on the volume of material coming out? a .07mm layer would need less cooling than a 1mm layer.

Though that matters more with adaptive layers.

**Comment by Snaiper1945** [comment] 2020-02-06 06:21
No, your know layer mode with defferent colors in cura? It would be nice to have a fan speed display mode.

**Comment by fvrmr** [comment] 2021-10-05 14:26
Duplicate of https://github.com/Ultimaker/Cura/issues/7495

**Closed by fvrmr** 2021-10-05 14:26 UTC
Labels: Category: Cura, Type: New Feature
