### ISSUE TITLE
[4.8.0] Bad skirt outline calculation

### ISSUE THREAD

**Issue by FFY00** [Ultimaker/Cura#9267] opened 2021-02-11 18:59 UTC
**Application version**
4.8.0

**Platform**
Arch Linux

**Printer**
Ender 3 V2

**Reproduction steps**
1. Load https://www.thingiverse.com/thing:2515926
2. Enable skirt
3. Slice

**Screenshot(s)**
![cura-skirt-broken](https://user-images.githubusercontent.com/11718923/107684456-ba391a80-6c9a-11eb-9d85-94b5bd13df89.png)

**Actual results**
The big cylinder piece does not get included in the skirt outline.

**Expected results**
The skirt outline should not conflict with any piece.

**Project file**
[CE3_Solder_holder_56mm_spool.zip](https://github.com/Ultimaker/Cura/files/5967811/CE3_Solder_holder_56mm_spool.zip)

**Comment by fvrmr** [comment] 2021-02-12 07:48
Hi @FFY00 thank you.
It looks like this is a problem with the model. Because if you look at the first layer, you can see the big cylinder is not aligned at the same height as the spool holder and the ring. 
![Screenshot (52)](https://user-images.githubusercontent.com/77000924/107741643-da55f180-6d0d-11eb-8c44-cc776b26f3ff.png)

A simple solution for this is to move your model -0.02 on the z axis. 
![Screenshot (54)](https://user-images.githubusercontent.com/77000924/107742187-dd051680-6d0e-11eb-8d1f-954f9e88a180.png)

Hope this works for you. 
I will close this issue because it is not a bug with Cura.

Please let me know if you have more questions!

**Closed by fvrmr** 2021-02-12 07:48 UTC
Labels: Type: Bug

**Comment by FFY00** [comment] 2021-02-16 00:24
Hi, thank you for the quick response! I ended up just printing as-is, it worked fine as the gap seems to be pretty small. Would it make sense to have cura warn about objects which are completely in the air?

**Comment by fvrmr** [comment] 2021-02-16 13:02
Great to hear that it did work, it is only one layer so that is mostly not a problem indeed.
Well, that's difficult to tell, because sometimes it is mean to be not to touch the build plate. Also Cura already takes a few mm of the bottom of the object to place it.
