### ISSUE TITLE
Support within object perimeter lifts the object off the buildplate by one layer

### ISSUE THREAD

**Issue by iFreilicht** [Ultimaker/Cura#3238] opened 2018-02-05 21:15 UTC
**Application Version**
3.1.0
2.7.0

**Platform**
Windows 10

**Steps to Reproduce**
Load [this .curaproject.3mf](https://1drv.ms/u/s!AmgnMR2IYHpNk5QAPyJXL8HgiHw0vw) file with cura 3.1.0 and take a look at the first and second layer in layer view. I also tested this in Cura 2.7.0, and the same problems occur there.

**Actual Results**
You will notice that the first layer only contains the support structure and the skirt. The model itself starts in the second layer, which leads to the print failing spectacularly.

**Expected results**
The skirt should be around the model and the model should be on the buildplate.

**Additional Information**

Screenshots for Cura 2:
![cura2_1st](https://user-images.githubusercontent.com/9742635/35829005-c5dde322-0ac1-11e8-9aa4-ddd7a2f55db1.PNG)
![cura2_2nd](https://user-images.githubusercontent.com/9742635/35829006-c6d745a2-0ac1-11e8-867c-966664b2305c.PNG)

Screenshots for Cura 3:
![cura3_1st](https://user-images.githubusercontent.com/9742635/35829009-c7cfaf26-0ac1-11e8-9582-aa96760ecd3e.PNG)
![cura3_2nd](https://user-images.githubusercontent.com/9742635/35829014-c8d1d5f2-0ac1-11e8-90d5-6567b5d8a88d.PNG)

**Comment by iFreilicht** [comment] 2018-02-09 10:23
I also tested this without any adhesion helper and with brim, but it doesn't change the behaviour. The manual workaround would be to remove the first layer in Gcode and modify all other ones accordingly, but that's quite tedious.

**Comment by Ghostkeeper** [comment] 2018-03-05 09:39
An easier workaround would be to move the object down in Cura by 0.051mm.

This reproduces for me. We've seen this sort of thing often when the bottom of a model isn't 100% flat. But at least I'd expect there to be support along the entirety of the first layer then.

**Comment by Ghostkeeper** [comment] 2018-03-05 09:49
Turns out this is more of a matter of Cura's front-end not being entirely accurate in its 3D convex hull calculation which results in not putting the model entirely flat on the build plate.

**Comment by iFreilicht** [comment] 2018-03-05 14:00
Just lowering the model by 0.051mm is a great workaround, thank you so much! It seems this problem also disappears for lower layer heights. If I set the layer height to 0.298 or lower, the model is placed on the buildplate properly. If it's 0.299 or more, it's raised by one layer.

**Comment by diegopradogesto** [comment] 2018-07-04 07:59
I will close this ticket since there is a workaround and maybe is provoked by a non perfectly flat surface in the model.

**Closed by diegopradogesto** 2018-07-04 07:59 UTC
Labels: Category: Cura, Status: In Progress, Type: Bug
