### ISSUE TITLE
programm is closing it self

### ISSUE THREAD

**Issue by tigerfacexxl** [Ultimaker/Cura#9824] opened 2021-05-13 17:22 UTC
### Application Version

4.9.0

### Platform

windows 10

### Printer

Anycubic Mega Zero 2.0

### Reproduction steps

I was working with 4.8 everything was fine to use. Cura has asked me to install 4.9.0, which I did. (unistalled the old version but keept the config files). I opened the version 4.9.0 (or 4.9.1 is the same fault). All the time when I click on the icon to open a STL file, the programm closes imedialtly again and I can not use the programm anymore since this version upgrade
![Screenshot 2021-05-13 191354](https://user-images.githubusercontent.com/84146809/118161193-99aa6900-b41f-11eb-9ca8-24d84c2ebab3.jpg)
![Screenshot 2021-05-13 1913542](https://user-images.githubusercontent.com/84146809/118161194-9a42ff80-b41f-11eb-9aeb-b724e30f35f6.jpg)
![Screenshot 2021-05-13 1914453](https://user-images.githubusercontent.com/84146809/118161195-9a42ff80-b41f-11eb-8c5d-5b5390b42795.jpg)

### Actual results

I have reinstalled the version 4.8.xx and all was fine again

### Expected results

programm should not close itself...

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

nothing more to say

**Comment by fvrmr** [comment] 2021-05-14 12:00
Hi @tigerfacexxl thank you for your bug report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9668
There you can find a work around to solve this issue. 
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-05-14 12:00 UTC
Labels: Type: Bug
