### ISSUE TITLE
Cura Version 304 can not Output the  Slicing G Code  

### ISSUE THREAD

**Issue by Hardwarekiller** [Ultimaker/Cura#2714] opened 2017-11-03 00:27 UTC
Cura Version 304 can not Output the Gode !

When you go to the  "Save to File"
give NOT the GCode Output !

Cura Version 303 is OK 
Cura Version 304 can NOT Save a GCode 
This ist a big BUG !

Here the Picture of the BUG from Cura 304!
I can NOT Save an GCODE, 
he is missing

![cura304fehler](https://user-images.githubusercontent.com/1480700/32356428-43f56280-c035-11e7-97e5-1b5000ab10ae.jpg)

An here the Cura Version 303 it works

![cura303richtig](https://user-images.githubusercontent.com/1480700/32356429-4432e43e-c035-11e7-8ac7-7c84a1f88e64.jpg)

By 

Hardwarekille

**Comment by Ghostkeeper** [comment] 2017-11-03 08:35
Could you go into the application menu: "Plugins" -> "Installierte Plugins...", and look there if the plug-in "G-Code-Writer" is enabled?

**Comment by Hardwarekiller** [comment] 2017-11-04 04:09
Hi, now it work,s 
thanks for you Tip !

The Problem from Version 304 is, this Version Change Plugin  "G-Code-Writer" automatic  to "off"   after an new installing.
or when i switch between Output to "print via usb" or "save to File" go to  
"G-Code-Writer"  to "off" and not return to "on"

I Thing the Version 303 with name  "Cura 3.0.3" sets the   "G-Code-Writer"  to standart   "on"
the last Version 304 Name with name   Ultimaker Cura 3.0.4 sets the  "G-Code-Writer" to standart   "off"

Thanks 

Hardwarekiller

**Comment by Ghostkeeper** [comment] 2017-11-10 00:37
Weird. I haven't seen that happen.

Some other people have been reporting random plug-ins disabling sometimes. Myself I've been seeing the "Do you want to share anonymous data" box come back and the window position reset. But it's all pretty hard to reproduce :(

**Comment by EldarPolitkin** [comment] 2018-02-16 22:31
Have the same issue

but I cant enable the G-Code-Writer plugin =\

![capture](https://user-images.githubusercontent.com/32969822/36332180-d5b84218-1379-11e8-8b60-66cf480ccbb4.PNG)

thenk you,
Eldar/

**Comment by Ghostkeeper** [comment] 2018-03-09 08:37
A workaround is to go to Help -> Show Configuration Folder. There open the `cura.cfg` file with a text editor and under the `[general]` category remove the `GCodeWriter` plug-in from the `disabled-plugins` list. Or just remove the `disabled-plugins` line altogether (which will reset the disabled/enabled state of all your plug-ins).

**Comment by Ghostkeeper** [comment] 2018-03-09 08:39
We don't know how this happens. I haven't seen it occur. As long as we don't know how to reproduce the issue, there is little we can really do to help...

**Comment by ianpaschal** [comment] 2018-05-28 07:56
Being unable to reproduce or fix this, and also the fact that the plugin browser has replaced this UI anyway, I'm going to close this.

**Closed by ianpaschal** 2018-05-28 07:56 UTC
Labels: Category: Cura, Status: Needs Info, Type: Bug
