### ISSUE TITLE
Slicing model generates broken preview

### ISSUE THREAD

**Issue by SebastianKumor** [Ultimaker/Cura#11493] opened 2022-02-16 12:44 UTC
### Application Version

4.13.1

### Platform

MacOS monterey 12.2

### Printer

Anycubic mega

### Reproduction steps

1. Download Rocktopus from thingiverse or use attached project file
2. Slice it

### Actual results

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/8973431/154266432-09adde72-c776-4bc7-8dc9-5e319b3105a0.png">

### Expected results

I have sliced this before on 4.12.1 and it worked normaly. Same stl and same printing settings

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[AI3M_rocktopus_v2.3mf.zip](https://github.com/Ultimaker/Cura/files/8079930/AI3M_rocktopus_v2.3mf.zip)

**Comment by fvrmr** [comment] 2022-02-17 08:38
Hi @SebastianKumor thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/10387
Because this is a duplicate I will close your issue, you can read there that a reboot fixed it for some people.
Please continue the thread there, so we keep everything in one place.

**Closed by fvrmr** 2022-02-17 08:38 UTC
Labels: Type: Bug
