### ISSUE TITLE
Descriptor Scrollbar inop

### ISSUE THREAD

**Issue by russemi** [Ultimaker/Cura#12027] opened 2022-04-30 04:41 UTC
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ender 5+

### Reproduction steps

On longer descriptions that have a scrollbar, I can't move over to the arrow & keep the description visible.

### Actual results

So as a result, I can't read the entire description.

### Expected results

I should be able to keep the description visible while moving over to the scrollbar.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![ScreenShot](https://user-images.githubusercontent.com/104666050/166091304-fed560cd-b75e-4b5c-abb5-700ef838790e.jpg)

**Comment by fvrmr** [comment] 2022-05-02 09:15
Hi @russemi thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11834, so I will close this issue.

**Closed by fvrmr** 2022-05-02 09:15 UTC
Labels: Type: Bug
