### ISSUE TITLE
cura keeps closing while printing 

### ISSUE THREAD

**Issue by kaine518** [Ultimaker/Cura#12213] opened 2022-05-15 23:59 UTC
### Application Version

5

### Platform

windows 11

### Printer

xyz davinci jr 3 in 1 1.0

### Reproduction steps

loaded my project selected my settings and began to print as usual 

### Actual results

the print application closed mid print 

### Expected results

the printer should continue to print 

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

none of my files will print all the way through
[CFFFP_Magneto_Helmet Left rear lower.zip](https://github.com/Ultimaker/Cura/files/8696320/CFFFP_Magneto_Helmet.Left.rear.lower.zip)

**Comment by fieldOfView** [comment] 2022-05-16 08:54
Duplicate of #11896

**Closed** 2022-05-16 09:47 UTC
Labels: Type: Bug, Status: Duplicate

**Comment by fieldOfView** [comment] 2022-05-16 10:24
You read the issue that this is a duplicate of, and find the test-build that includes the fix, all while realizing that you are using beta software.
