### ISSUE TITLE
the cura without chitubox crashed when opening a STL file

### ISSUE THREAD

**Issue by w0z0h** [Ultimaker/Cura#10888] opened 2021-11-20 08:49 UTC
### Application Version

4.12.1

### Platform

windows 10

### Printer

Anycubic i3 mega X

### Reproduction steps

I open a STL ,and I don't have chitubox on my computer

### Actual results

the software crashed,and nothing appeared.

### Expected results

the stl should be opened

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7574229/cura.log)

**Comment by nallath** [comment] 2021-11-20 13:28
Duplicate of #9644

**Closed by nallath** 2021-11-20 13:28 UTC
Labels: Type: Bug
