### ISSUE TITLE
[4.3.0] Problem resizing without uniform scaling

### ISSUE THREAD

**Issue by winijanc** [Ultimaker/Cura#6619] opened 2019-11-03 13:18 UTC
When scaling without uniform scaling, the percentages and values ​​of the X, Y, and Z axes become messy, depending on which information changes, another value also changes incorrectly. It looks like an interface problem.

![image](https://user-images.githubusercontent.com/22943859/68085679-47e45400-fe22-11e9-823a-ee81db14a728.png)
![image](https://user-images.githubusercontent.com/22943859/68085720-b6291680-fe22-11e9-8a04-a68eeffdd6a9.png)

**Comment by Kingmiwok** [comment] 2019-11-03 23:26
I'm having a similar problem, but it seems to be tied to rotating the model.  Non-uniform scaling works fine unit I rotate the model, then afterward scaling gets weird, and the axis's get jumbled.  It seems like if you rotate an object on an axis, then scaling association should move with the axis, but it does not.  In my case, if I scale first, then rotate, it's fine (except the scale percentage is associated with the wrong axis).  But if I rotate first, and then try to scale, I have the problems like described above.
This works.
![Screenshot 2019-11-03 13 15 56](https://user-images.githubusercontent.com/57332836/68093761-23e23c00-fe3d-11e9-8d2c-d0d440935c38.png)
![Screenshot 2019-11-03 13 18 35](https://user-images.githubusercontent.com/57332836/68093769-2f356780-fe3d-11e9-9aa2-7ff061b7d2a9.png)
![Screenshot 2019-11-03 13 18 14](https://user-images.githubusercontent.com/57332836/68093776-365c7580-fe3d-11e9-9498-0d1c97be80f0.png)

Changing the order (rotating first, and then scaling) does not.
![Screenshot 2019-11-03 13 15 56](https://user-images.githubusercontent.com/57332836/68093786-57bd6180-fe3d-11e9-8b0f-f760bb4dbe0b.png)
![Screenshot 2019-11-03 13 16 25](https://user-images.githubusercontent.com/57332836/68093787-5b50e880-fe3d-11e9-8d1f-a10904b56a4b.png)
![Screenshot 2019-11-03 13 17 13](https://user-images.githubusercontent.com/57332836/68093789-60ae3300-fe3d-11e9-9080-7053d2082c83.png)

**Comment by Ghostkeeper** [comment] 2019-11-04 14:13
Indeed, rotating the model + non-uniform scaling causes this issue. It's a very difficult one.

This is a duplicate of https://github.com/Ultimaker/Cura/issues/4136. Please continue the discussion there.

**Closed by Ghostkeeper** 2019-11-04 14:13 UTC
