### ISSUE TITLE
Certain stls arent correctly laying flat in 3.04

### ISSUE THREAD

**Issue by kentishbull** [Ultimaker/Cura#2847] opened 2017-11-25 23:45 UTC
Work fine in 2.7. The file Im wanting to print in 3.04 ends up sitting on supports when it isnt necessary. Its about 3mm too high from the bedplate and have to lower the Z in Cura. 2.7 adequately places objects correctly and prints without the effective raft underneath

**Comment by ChrisTerBeke** [comment] 2017-11-26 18:47
Duplicate of https://github.com/Ultimaker/Cura/issues/2792.

**Closed by ChrisTerBeke** 2017-11-26 18:47 UTC
