### ISSUE TITLE
Cura 3.2.1 Font Issue on macOS High Sierra Version 10.13.3

### ISSUE THREAD

**Issue by popzct0214** [Ultimaker/Cura#3427] opened 2018-03-02 22:19 UTC
**Application Version**
3.2.1

**Platform**
macOS High Sierra Version 10.13.3

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**
Load Cura 3.2.1.

**Actual Results**
Fonts are fragmented.

**Expected results**
Should not be fragmented, update stated problem was repaired.

**Additional Information**
<img width="433" alt="screen shot 2018-03-02 at 4 15 40 pm" src="https://user-images.githubusercontent.com/1562780/36924650-0aef4006-1e35-11e8-801e-029ae1b94133.png">

**Comment by ChrisTerBeke** [comment] 2018-03-02 22:41
Duplicate of https://github.com/Ultimaker/Cura/issues/3277.

**Closed by ChrisTerBeke** 2018-03-02 22:41 UTC
