### ISSUE TITLE
Custom supports

### ISSUE THREAD

**Issue by fnhhnxfn** [Ultimaker/Cura#8223] opened 2020-08-23 10:21 UTC
**Is your feature request related to a problem? Please describe.**
(Hi i am simplify3D user and just started using cura because it works better with ultimaker machines. but always frustrated when i have to design a support structure [...])

**Describe the solution you'd like**
(I know that there is custom support option in cura plugins but that is very basic , if its possible i would like to see a custom support menu in cura just like in any other slicer like simplify3D or craftware etc.)

**Describe alternatives you've considered**
(i tried  making soluble supports but parts take double time to complete and i need functional parts on daily basis.)

**Affected users and/or printers**
(I think it would be a great add on for ultimaker machines so mainly ultimaker community will benefit from it or otherwise everyone will see for alternatives including myself)

**Additional context**
(Add any other context or screenshots about the feature request here.)

**Comment by Ghostkeeper** [comment] 2020-08-24 16:34
Duplicate of https://github.com/Ultimaker/Cura/issues/7291.

**Closed by Ghostkeeper** 2020-08-24 16:34 UTC
Labels: Type: New Feature
