### ISSUE TITLE
Visual glitch: Random layer appears in the first layer instead of its proper layer

### ISSUE THREAD

**Issue by Deses** [Ultimaker/Cura#8591] opened 2020-10-22 00:47 UTC
**Application version**
4.7.1

**Platform**
Windows 10 x64, Ryzen 3700X & Radeon R9 390x

**Printer**
Ender 3

**Reproduction steps**
1. Place STL
2. Inspect layers

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/1654959/96804880-89458900-1410-11eb-8dc6-de9d2176bf59.png)
![image](https://user-images.githubusercontent.com/1654959/96805535-27861e80-1412-11eb-8d6d-6c4ff61c312e.png)

**Actual results**
The layer 327 is displayed in the wrong place, but the exported gcode *SEEMS* fine. After inspecting the Gcode, a proper change of Z height is called with the correct data. Looks like purely a visual glitch, but I'll let you judge that.

**Expected results**
The layer should be in its place.

**Project file**
[Issue #8591.zip](https://github.com/Ultimaker/Cura/files/5419362/Issue.8591.zip)

**Log file**
[cura_2.log](https://github.com/Ultimaker/Cura/files/5419382/cura_2.log)

**Additional information**
After clearing the build plate and reloading the model, I can't reproduce the issue anymore... and other similar models with the same height also didn't present the issue. 🤷‍♂️

**Comment by Ghostkeeper** [comment] 2020-10-22 14:27
Duplicate of https://github.com/Ultimaker/Cura/issues/7412.

**Closed by Ghostkeeper** 2020-10-22 14:27 UTC
Labels: Type: Bug

**Comment by Deses** [comment] 2020-10-22 14:36
> Duplicate of #7412.

I see! I didn't saw that one when I searched for a similar issue. Well, I'm glad you already have this one tracked. :D

**Comment by Ghostkeeper** [comment] 2020-10-23 09:16
It's a difficult issue that has been happening for years. So all we're really doing with it is tracking it. As far as we know it's random and pretty rare, so that makes it extremely hard to debug.
