### ISSUE TITLE
No random "Z Seam Alignment" when "Fuzzy Skin" is activated

### ISSUE THREAD

**Issue by AndyS1957** [Ultimaker/Cura#13129] opened 2022-08-26 09:42 UTC
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Artillery Genius / Artillery Genius Pro

### Reproduction steps

1. Activation "Z Seam Alignment" -> "Random"
2. Activation "Fuzzy Skin"
3. Printing a cylinder

### Actual results

The "Z-Seam Alignment" is not "Random", but in a vertical line on one side of the cylinder. This happens only, when "Fuzzy Skin" is activated. When not, "Z Seam Alignment" works correct

### Expected results

I expect a random "Z Seam Alignment"

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[PRO_Topf_130x130_3farb_GPETG.zip](https://github.com/Ultimaker/Cura/files/9432059/PRO_Topf_130x130_3farb_GPETG.zip)

**Comment by Asterchades** [comment] 2022-08-27 02:53
Duplicate of #12190.

**Closed by Asterchades** 2022-08-27 02:53 UTC
Labels: Type: Bug, Status: Duplicate, Status: Triage, dependencies

**Comment by nallath** [comment] 2022-09-08 13:41
This has been fixed for 5.2
