### ISSUE TITLE
Support Blocker Modify settings for overlaps (cutting mesh) makes wall width thin

### ISSUE THREAD

**Issue by Screlias** [Ultimaker/Cura#9961] opened 2021-06-10 06:49 UTC
### Application Version

4.9.1

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

1. Insert support blocker
2. Size it and move it where I wanted it
3. Per Model Settings - Modify settings for overlaps - cutting mesh and nothing else (I wanted to use fuzzy skin)
4. Slice

### Actual results

![image](https://user-images.githubusercontent.com/85665365/121473600-975e0f00-c9cb-11eb-835a-4f9822676106.png)
![image](https://user-images.githubusercontent.com/85665365/121473639-a8a71b80-c9cb-11eb-9c19-a0dc85e62302.png)
![image](https://user-images.githubusercontent.com/85665365/121473680-b3fa4700-c9cb-11eb-9bd9-6107e390a168.png)
and I tried it on another model:
![image](https://user-images.githubusercontent.com/85665365/121473972-15221a80-c9cc-11eb-8a90-0490f2f0c248.png)

### Expected results

The walls should have stayed at the same width as well the bottom layers 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Same steps and profile and blocker placement in cura 4.4.1 no problems there...
![image](https://user-images.githubusercontent.com/85665365/121477806-f7a37f80-c9d0-11eb-829f-63edf04e0431.png)
![image](https://user-images.githubusercontent.com/85665365/121477837-ff632400-c9d0-11eb-994a-04979a8a19b2.png)
There is definitely a bug or I am doing something very wrong

**Comment by fvrmr** [comment] 2021-06-10 11:54
Hi @Screlias thank you for your report.
Could you share your project file (file - save project) than I can take a look at it.

**Comment by Screlias** [comment] 2021-06-11 06:10
Without changing anything (except downloading cura 4.4.1) it doesn't do it any more! And I spent hours searching for a solution and all it needed was a computer restart -_- ! Although it bugged for sure, I didn't notice it until the print broke on the 67th layer where the infill line was so thin the didn't stick together. I am sorry I can't reproduce the bug because it is a major issue, which turned the print to rubbish. 
![20210611_090603](https://user-images.githubusercontent.com/85665365/121638953-7b727000-ca94-11eb-83df-f5d2ff2bee94.jpg)
![20210611_090619](https://user-images.githubusercontent.com/85665365/121638956-7ca39d00-ca94-11eb-867e-2f832641e568.jpg)
The project file has the same settings...
[CE3_fem_pic_rail_diam_gripv2.zip](https://github.com/Ultimaker/Cura/files/6636197/CE3_fem_pic_rail_diam_gripv2.zip)

**Comment by fvrmr** [comment] 2021-06-11 09:36
Thank you for your project file. I think this was caused by enabling the bridging setting. Because when I enabled it shows exactly the same as you screenshots.

![Screenshot (192)](https://user-images.githubusercontent.com/77000924/121666043-255bf780-caa9-11eb-96ce-c12cabb59c79.png)

But you did make it work now in 4.9.1 right?

**Comment by Screlias** [comment] 2021-06-11 16:22
Yes you are right I forgot that I had enabled bridging but is it normal?

**Comment by fvrmr** [comment] 2021-06-15 14:29
I would say no, because there is no need for bridging. It could be that fuzzy skin and bridging doesn't work nice together. 
I will bring it up with the team. Keep you posted!

**Comment by Ghostkeeper** [comment] 2021-06-16 11:45
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9083. Please continue the conversation there.

**Closed by Ghostkeeper** 2021-06-16 11:45 UTC
Labels: Type: Bug

**Comment by Screlias** [comment] 2021-06-16 15:16
It has nothing to do with fuzzy skin. The bug occurs when you have bridging enabled and you insert a support blocker in cutting mesh mode.

**Comment by Ghostkeeper** [comment] 2021-06-17 09:41
Yeah I think the "fuzzy skin" was just a mix-up. fvrmr meant to say Cutting Mesh. And indeed, they don't work nice together. We consider that to be a bug.
