### ISSUE TITLE
Generated & variable multi-layer brim.

### ISSUE THREAD

**Issue by mporter88** [Ultimaker/Cura#9426] opened 2021-03-21 20:42 UTC
### Is your feature request related to a problem?

I print functional and structural components of ABS and other materials prone to warping.
To increase adhesion to build surface I often design printed components with a brim that is
an outward extension of MULTIPLE bottom solid layers and so is more rigid and effective than a standard brim.
Sometimes I design this brim such that it tapers/steps down to a single layer at the outermost path.

I trim the brim off with a laminate trimming bit on a router table as it is not typically removable by hand.

I believe this a useful practice... and as such might be worth incorporating in the bed adhesion options of CURA.

### Describe the solution you'd like

A "STRUCTURAL BRIM" option toggle.

IF toggled on THEN display:
"Warning - generates a brim that is not easily removable by hand and may require mechanical means to remove."

Variables.
1 - How many layers thick? (or match to bottom solid layers?)
2 - How many lines/walls out from model should the structural brim extend? (width)
3 - Taper? Y/N (decreases in layer thickness down to 1).
4 - How many lines/walls of width to taper? 

Variables could be set to create a brim that is attached to the model at multiple layers...
but that tapers down to a single layer at some specified distal line.
A single layer brim may still extend outward beyond the last line/wall of the taper.

### Describe alternatives you've considered

I have often used standard CURA generate brims.

Sometimes a particularly difficult part will lift a generated single layer thick brim no matter how wide.

This can be caused by use of materials that are more prone to warping.
This can be caused by environmental variables.

My solution has been to design a brim that is more substantial (and as such more rigid).
Sometimes I design a brim that becomes less substantial the further it extends from the model.

### Affected users and/or printers

Will benefit users who require more rigid built plate adhesion....and are willing to use 
mechanical means to cut away a generated brim that is thicker and less flexible and more permanently attached.

Typical removal tool is a flush or bevel cutting laminate trimmer in a router table.

Note:  I have also used a hand held "dremel" (milling bit)... equipped with a small printed "flush fence" attachment.

**Comment by fvrmr** [comment] 2021-03-22 10:54
Hi @mporter88 thank you for your very detailed feature request.
We already got a duplicate of this request: #6939 that's why I will close this issue. Here you can read why we deferred this request. Hope you understand. 
Feel free to continue the thread there and reach out for more questions.

**Closed by fvrmr** 2021-03-22 10:54 UTC
Labels: Type: New Feature
