### ISSUE TITLE
garbled fonts MacOS 11.3 high resolution screen

### ISSUE THREAD

**Issue by jtbnz** [Ultimaker/Cura#9755] opened 2021-05-03 10:48 UTC
### Application Version

4.9.0

### Platform

Mac Os 11.3

### Printer

Ender 5

### Reproduction steps

various places fonts are garbled.
1) Add a printer the maker name is unreadable.
2) Extenstions add a script script names are unreadable
![Screenshot 2021-05-03 at 12 40 40](https://user-images.githubusercontent.com/57672422/116867195-f7170c80-ac0c-11eb-94a6-b1d9064e6429.png)
![Screenshot 2021-05-03 at 12 40 57](https://user-images.githubusercontent.com/57672422/116867201-f9796680-ac0c-11eb-86d0-8ef5923a06e5.png)

### Actual results

options are still available if you click on them

### Expected results

fonts are readable

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/6414358/cura.log)

[CE5_Heat_tower_190-240_Bridge.3mf.zip](https://github.com/Ultimaker/Cura/files/6414371/CE5_Heat_tower_190-240_Bridge.3mf.zip)

**Comment by fvrmr** [comment] 2021-05-03 14:51
Hi @jtbnz thank you for your bug report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/8993 and this is related to the M1 chip that doesn't support the Qt library Cura is using.  
I will close this because it is a duplicate. I hope you understand.

**Closed by fvrmr** 2021-05-03 14:51 UTC
Labels: Type: Bug
