### ISSUE TITLE
Cura 3.4.1 Infill Density Bug

### ISSUE THREAD

**Issue by kornshadow097** [Ultimaker/Cura#4091] opened 2018-07-17 01:10 UTC
**Application Version**
 3.4.1

**Platform**
Windows 10

**Printer**
 Tevo Tarantula

**Steps to Reproduce**
 Setting infill to zero makes the slicer unable to slice with current project and asked for a "infill line distance" which i have checked as OFF in the settings tab..  It forces me to input the same value i have as line width even though i have no infill and its supposed to calculate this on its own...  After I do that it says i need "infill line thickness" but there is no such option that i can find... I believe it stated something about this being a per model setting. Which i saw is a new feature but i don't see it there either..

**Actual Results**
"Unable to slice"

**Expected results**
 Being able to slice...

**Additional Information**

I have infill set to zero and this shows up.

**Comment by LipuFei** [comment] 2018-07-17 06:41
Hi @kornshadow097 , I tried to slice a model with infill density set to 0 and it worked. Could you save your print as a project file and send it to us so we can check what went wrong? Thanks!

You can save as a project file via menu "File -> Save project".

**Comment by kornshadow097** [comment] 2018-07-17 22:04
here you go.

**Comment by kornshadow097** [comment] 2018-07-18 05:01
So does anyone know about this weird issue?

**Comment by LipuFei** [comment] 2018-07-18 07:53
Hi @kornshadow097 , also took us a while to figure it out... The problem is with the "Infill Layer Thickness" but you can ONLY see it if your infill density is larger than 0. So, you can change your infill density to 1 for example, and then you can see this:

![image](https://user-images.githubusercontent.com/2630468/42867419-dcb1c73e-8a6f-11e8-904e-6fd3e0c31f1d.png)

I see that you have "Infill Layer Thickness" set to 0.5 in your custom quality profile. That's why it's using 0.5. The maximum value for it is 0.48 in your case: `layer_height * 8 = 0.06 * 8 = 0.48`.

Although the error message is more or less pointing to the right direction, but it's not straightforward how to correct the values when an error happens. We will discuss see how we can improve that.

Thanks for reporting this!

**Comment by kornshadow097** [comment] 2018-07-18 08:14
I see. Well I don't see why that option should make the slicer fail, especially when the input shouldn't be included in the slice anyway. That's like getting an error for having too thin of a bottom layers when you have bottom layers set to 0.

I see, so layer height *8 is my max infill layer thickness. So then layer thickness isn't the same thing as layer height? I know with a 0.4mm nozzle we arents supposed to go beyond 75-80% or 0.32mm. 

No problem, I enjoy troubleshooting and finding bugs and making suggestion for improvements. Thanks for the help.

I also posted a few suggestions for the app in another post.

Thanks

Jonathan

**Comment by LipuFei** [comment] 2018-07-18 09:59
For infill and support infill, CuraEngine will try to combine multiple layers into one and print that once with a thicker layer height. For example, if you have layer height 0.1mm and infill layer thickness 0.3mm, then 3 layers of 0.1mm infill will be printed on the 3rd layer as a 0.3mm infill layer to save time. This is why the explanation of the setting says that it should be a multiple of the layer height.

The maximum limit for infill layer thickness is there due to a limitation of CuraEngine at the moment: it cannot process too many layers for combining. If you give a higher number, the engine will fail.

**Comment by kornshadow097** [comment] 2018-07-18 10:11
I see. so it actually leaves a infill gap that it will fill up with the combined value later? interesting. 

Where can i find more basics about how cura works? ive been using both cura and s3d and so far s3d i only like due to its ease of use and simplicity but its skin quality and engine is sometimes lacking. while cura has so many options and settings i get overwhelmed with them and sometimes forget the subtle differences in layer types and sizes and max and mins i can and cant use etc...

thanks

Jonathan

**Comment by LipuFei** [comment] 2018-07-18 10:19
I believe @Ghostkeeper knows more than I do. :) You are welcome. I'll close this ticket.

**Closed by LipuFei** 2018-07-18 10:19 UTC
Labels: Status: Needs Info

**Comment by LipuFei** [comment] 2018-07-18 10:21
You can also find a lot of discussion in the CuraEngine repository: https://github.com/Ultimaker/CuraEngine

**Comment by Ghostkeeper** [comment] 2018-08-29 10:04
> Where can i find more basics about how cura works?

We've been improving the documentation of CuraEngine recently here: https://github.com/Ultimaker/CuraEngine/blob/master/docs/pipeline.md

There has also been an effort to document each setting better, here: https://github.com/alekseisasin/CuraSettingsGuidePlugin

I've fixed the error value for when you've disabled the infill here: 1d8f19f1d1c501f5d7525ca695967a7813f30c16
