### ISSUE TITLE
[Cura 4.4.1] macOS Version command for delete object from keyboard don't work

### ISSUE THREAD

**Issue by Gipielle** [Ultimaker/Cura#7002] opened 2020-01-20 08:28 UTC
**Application version**
4.4.1

**Platform**
macOS Mojave 10.14.6

**Printer**
CR10S but is not a printer related problem

**Reproduction steps**
1. Select an object ed hit delete button on keyboard 
2. Nothing heppens, you have to use the mouse with right click for delete or the cura menu.

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by mahtDFR** [comment] 2020-01-20 09:36
Thanks for the report. This issue is a duplicate of #6475 . I will close this as the issue is fixed in an upcoming release.

**Closed by mahtDFR** 2020-01-20 09:36 UTC
Labels: Type: Bug
