### ISSUE TITLE
Unable to slice

### ISSUE THREAD

**Issue by DeCaff24** [Ultimaker/Cura#10278] opened 2021-08-13 08:02 UTC
### Application Version

4.10.0

### Platform

Windows 10

### Printer

Malyan M200

### Reproduction steps

installed this version
open STL file
Lay flat
Hit Slice

### Actual results

Error message:

Unable to slice
Unable to slice with the current settings. The following settings have errors: Z Hop Speed

### Expected results

it should have sliced the part. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Good to mention that I did change to fine and finer first... then back to normal. on all profiles I get the same error and I cannot slice

**Comment by nallath** [comment] 2021-08-13 08:06
Duplicate of #10119

**Closed by nallath** 2021-08-13 08:06 UTC
Labels: Type: Bug
