### ISSUE TITLE
CuraEngine stopped working, Cura 2.7

### ISSUE THREAD

**Issue by modem7** [Ultimaker/Cura#2281] opened 2017-08-15 20:24 UTC
**Edit: After a bit more searching, I see that this is related to #2211. - Sorry!**

Hey guys, 

Repeatable error here:

Enabling "Extra wall skin count" (I set it to 1, but it doesn't seem to matter on the value) seems to crash curaengine when slicing a model. 

Windows 7

CuraEngine.exe 
   0.0.0.0 
   59804cef 
   CuraEngine.exe 
   0.0.0.0 
   59804cef 
   c0000005 
   00000000000c920c 
   cf2c 
   01d316045f12802a 
   C:\Program Files\Cura 2.7\CuraEngine.exe 
   C:\Program Files\Cura 2.7\CuraEngine.exe 
   9f2d64b0-81f7-11e7-bcf7-00acc7375d92 

Faulting application name: CuraEngine.exe, version: 0.0.0.0, time stamp: 0x59804cef
Faulting module name: CuraEngine.exe, version: 0.0.0.0, time stamp: 0x59804cef
Exception code: 0xc0000005
Fault offset: 0x00000000000c920c
Faulting process id: 0xcf2c
Faulting application start time: 0x01d316045f12802a
Faulting application path: C:\Program Files\Cura 2.7\CuraEngine.exe
Faulting module path: C:\Program Files\Cura 2.7\CuraEngine.exe
Report Id: 9f2d64b0-81f7-11e7-bcf7-00acc7375d92

**Comment by LipuFei** [comment] 2017-08-16 07:35
As mentioned in #2211, it is fixed for 2.7: Ultimaker/CuraEngine@ee5f62c

@modem7 Would you mind if I close this issue since it is a duplicate of #2211?

**Comment by modem7** [comment] 2017-08-16 07:44
Please do!

**Closed** 2017-08-16 08:20 UTC
