### ISSUE TITLE
Touch screen support in Windows 10

### ISSUE THREAD

**Issue by firefighter331** [Ultimaker/Cura#9299] opened 2021-02-20 04:12 UTC
It would be nice to have the ability to navigate the main screen (viewing the model) using a touch screen, rather than trying to right click and hope it works with the touch pad. Some lower end touch pads don't allow dragging while simultaneously right-clicking.

This would be necessary for some devices that don't have a built-in touch pad, like the Microsoft Surface line of tablets, and would be convenient on my Razer Blade Stealth laptop, since it does have a touch screen and it would be nice if I could make use of it when I'm using Cura. I'm sure many others are in the same situation.

**Comment by fvrmr** [comment] 2021-02-22 13:00
Hi @firefighter331 thank you for your feature request.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/2515
We have a ticket on our back log for this. 
That's why I will close this issue. Feel free to continue the tread there.

**Closed by fvrmr** 2021-02-22 13:00 UTC
Labels: Type: New Feature
