### ISSUE TITLE
Not loading or slicing in Portugese

### ISSUE THREAD

**Issue by Guisao5** [Ultimaker/Cura#2010] opened 2017-06-21 17:08 UTC
Na linguagem em portugues nao aparece a mesa da maquina e nao e possivel carregar arquivos.

**Comment by Ghostkeeper** [comment] 2017-07-02 23:56
I've tested the Portuguese language in Cura myself. Just retesting to confirm:

* The printer list is properly filled in when you click "Adicionar Impressora". Adding a printer works fine.
* Loading a file works fine, and it starts to "Fatiando" right away.

In other words, I can't reproduce your problem.

**Comment by Ghostkeeper** [comment] 2017-07-02 23:56
Perhaps you can share a log file with us? I'd expect these problems to show up there.

**Comment by ChrisTerBeke** [comment] 2017-09-28 08:43
Closing since we cannot reproduce and no futher information has been provided. Please comment if this is still an issue for you.

**Closed by ChrisTerBeke** 2017-09-28 08:43 UTC
Labels: bug, needsinfo
