### ISSUE TITLE
Multiply object not working

### ISSUE THREAD

**Issue by ylandot** [Ultimaker/Cura#10285] opened 2021-08-15 10:44 UTC
### Application Version

4.10

### Platform

MacOS

### Printer

Ultimaker 3

### Reproduction steps

1. put an object (any object)
2. select the object
3. try to multiply the object (1,2 ...)

### Actual results

Object doesn't multiply (only one remaining)

### Expected results

Object doesn't multiply (only one remaining)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![screen](https://user-images.githubusercontent.com/9982035/129475823-8c2b9916-44b2-4383-9a9e-9bd2d0d62bc0.jpg)

**Comment by ylandot** [comment] 2021-08-15 10:45
In this example i had to put manually 10 version of the object myself, the multiply function doesn't work and leave a message like it can finish the process ...

**Comment by jellespijker** [comment] 2021-08-15 18:28
Possible duplicate of #10284 
@ylandot which version of MacOS are you running?

**Comment by nallath** [comment] 2021-08-16 08:48
Could you also include the log files? They should give is more information as to what is going on.

**Comment by ylandot** [comment] 2021-08-18 08:31
Hi

I’m using a beta of MacOS (Monterey, beta 4 will update this week end to beta5) but have no problem with the same OS & functionnality with cura 4.8
it's stuck only with cura 4.10

Here is a log with 2 attemps at 10h25 and 10h29 today (2021-8-18 ) 

Sincerely

Yann

**Comment by nallath** [comment] 2021-08-18 08:46
Unfortunately, attachments are stripped by GitHub if you send them in by email. Could you attach them via the web interface?

**Comment by jellespijker** [comment] 2021-08-18 08:50
Also definitely a duplicate of #10249 so I'm closing this bug report. Please continue the discussion there.

**Comment by ylandot** [comment] 2021-08-18 09:09
OK, thanks

**Closed** 2021-08-18 09:40 UTC
Labels: Type: Bug, Status: Duplicate
