### ISSUE TITLE
Blender Exported Files Appear Out of Build Area when Imported After Cura Update

### ISSUE THREAD

**Issue by YarkspiriFantasyArt** [Ultimaker/Cura#9037] opened 2020-12-29 16:55 UTC
**Application version**
(The version of the application this issue occurs with.)
4.8.0

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)
Computer#1
OS Name	Microsoft Windows 10 Pro
Intel Core I7-5820k
BaseBoard Product	X99-A/USB 3.1
Installed Physical Memory (RAM)	32.0 GB
System Type	x64-based PC
Nvidia GeForce CTX 970

computer#2
Processor	AMD Ryzen 7 1700 Eight-Core Processor
BaseBoard Product	PRIME X370-PRO
Installed Physical Memory (RAM)	32.0 GB
OS Name	Microsoft Windows 10 Home
System Type	x64-based PC
Nvida GeForce GTX 1070

**Printer**
(Which printer was selected in Cura?)
Anycubic I3 Mega

**Reproduction steps**
1. From file explorer, I clicked and dragged the file into Cura.  When the file appeared it was extremely high up in the build plate.
2. I tried importing the file instead with the same results.
3. Files which were realigned in Cura and re-exported out appeared correctly.

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
![Image is Issue](https://user-images.githubusercontent.com/76743251/103299700-1e459f00-49cb-11eb-8623-0c87979896ca.png)

**Actual results**
(What happens after the above steps have been followed.)
![Image is Issue](https://user-images.githubusercontent.com/76743251/103300283-86e14b80-49cc-11eb-86c8-6ef4f98b6971.png)

**Expected results**
(What should happen after the above steps have been followed.)
![Expected Result](https://user-images.githubusercontent.com/76743251/103299792-58af3c00-49cb-11eb-90d3-1eff7f28ee98.png)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save Project. For big files you may need to use WeTransfer or similar file sharing sites. G-code files are not project files!)
[AI3M_Cub_FromBlender.zip](https://github.com/Ultimaker/Cura/files/5751434/AI3M_Cub_FromBlender.zip)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)
[DxDiag.txt](https://github.com/Ultimaker/Cura/files/5751453/DxDiag.txt)

**Additional information**
(Extra information relevant to the issue.)

**Comment by Ghostkeeper** [comment] 2021-01-06 12:57
Duplicate of https://github.com/Ultimaker/Cura/issues/8752.

**Closed by Ghostkeeper** 2021-01-06 12:57 UTC
Labels: Type: Bug
