### ISSUE TITLE
crashes during slice

### ISSUE THREAD

**Issue by xTheCanadianx** [Ultimaker/Cura#16708] opened 2023-09-10 18:57 UTC
### Cura Version

5.4.0

### Operating System

Windows 11 

### Printer

Ender 3 Pro

### Describe model location

no difference

### Describe your model

model is watertight per meshfix

### Add your .zip here ⬇️

[CE3E3V2_blastmesh.zip](https://github.com/Ultimaker/Cura/files/12569961/CE3E3V2_blastmesh.zip)

**Comment by GregValiant** [comment] 2023-09-12 15:25
Thanks for the report and the file.
This is a duplicate of numerous other reports regarding good models that won't slice.
There are three main workarounds and one or a combination of them often works to fool the bug.

- Rotate the model in Cura
- Move the model away from the midpoint of the Cura build plate
- Change the Initial Layer Height by a little bit

For this project I rotated the group 90° CCW and moved the group.  That allowed it to slice.
I'll add the Duplicate label to this.  I'm going to close it as the Cura team is aware of this bug and has a lot of examples to work with.  I hope you understand.
![image](https://github.com/Ultimaker/Cura/assets/64202104/6d3b6200-2825-4e79-a81e-1fbeee323264)

**Closed by GregValiant** 2023-09-12 15:25 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error :collision:
