### ISSUE TITLE
slicing error

### ISSUE THREAD

**Issue by Jeffphoenixgold** [Ultimaker/Cura#14425] opened 2023-01-30 21:35 UTC
### Application Version

5.2.2

### Platform

Windows 10

### Printer

Anet ETX5

### Reproduction steps

resized file, then went to slice

### Actual results

Says "slicing Failed"

slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker

### Expected results

should have sliced file

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

![error](https://user-images.githubusercontent.com/123992471/215600030-534c90ef-deac-4639-af6b-b058fa420caa.jpg)

![error](https://user-images.githubusercontent.com/123992471/215600156-6fc44069-d2ee-42f8-bed9-bdf468de7e9e.jpg)

**Comment by Jeffphoenixgold** [comment] 2023-01-30 21:36
![noslice](https://user-images.githubusercontent.com/123992471/215600676-913292d5-0e71-4353-b0bf-057deadb54b1.jpg)

**Comment by MariMakes** [comment] 2023-02-03 15:49
Hey @Jeffphoenixgold ,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍


This mesh seems faulty
Have you tried doing a quick mesh fix with the Meshtools Plugin? 
You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools
If that doesn't fix it you can try a more elaborate mesh fixer like https://myminifactory.github.io/Fast-Quadric-Mesh-Simplification/.

Is it possible that your printjob is located at 0, 0, 0, and it slices if you move it a little away from the center of the buildplate? 
Then it might be a duplicate of https://github.com/Ultimaker/Cura/issues/13643

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Comment by Jeffphoenixgold** [comment] 2023-02-04 00:56
Thank you for replying back. I will definitely try these ideas.

Thanks

Jeff

Sent from my iPhone

On Feb 3, 2023, at 10:50 AM, MariMakes ***@***.***> wrote:

﻿

Hey @Jeffphoenixgold<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJeffphoenixgold&data=05%7C01%7C%7Cb5f362da13574f55990b08db05fe4d96%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638110362008509002%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tsPIct742%2BDCYlewIge272qRtaCjxWXAgw25XETgl0k%3D&reserved=0> ,

Welcome to the Ultimaker Cura Github 🚀
Thanks for your report 👍

This mesh seems faulty
Have you tried doing a quick mesh fix with the Meshtools Plugin?
You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmarketplace.ultimaker.com%2Fapp%2Fcura%2Fplugins%2Ffieldofview%2FMeshTools&data=05%7C01%7C%7Cb5f362da13574f55990b08db05fe4d96%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638110362008509002%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zP4aodBQKNiGdpTh2dzODQQKzJmKGy2LkoqQEBWLZ1o%3D&reserved=0>
If that doesn't fix it you can try a more elaborate mesh fixer like https://myminifactory.github.io/Fast-Quadric-Mesh-Simplification/<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmyminifactory.github.io%2FFast-Quadric-Mesh-Simplification%2F&data=05%7C01%7C%7Cb5f362da13574f55990b08db05fe4d96%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638110362008509002%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BLIRxvlc69sHaQomSiKLVzXxgJBQf8nLdRC3bARCNOg%3D&reserved=0>.

Is it possible that your printjob is located at 0, 0, 0, and it slices if you move it a little away from the center of the buildplate?
Then it might be a duplicate of #13643<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUltimaker%2FCura%2Fissues%2F13643&data=05%7C01%7C%7Cb5f362da13574f55990b08db05fe4d96%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638110362008509002%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ah3PzBE8WX02f87z3AuzyQFZYc2CuA8sLz%2BEqvTmHE4%3D&reserved=0>

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting.
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the view it on GitHub link at the bottom of your email to open GitHub in the browser.

**Comment by MariMakes** [comment] 2023-02-13 10:49
Hey @Jeffphoenixgold,

Can you give us an update? 
Is it still an issue or can we close the ticket?

**Comment by Jeffphoenixgold** [comment] 2023-02-13 12:41
Thank you for your help. Yes you can close the ticket.

Sent from my iPhone

On Feb 13, 2023, at 5:49 AM, MariMakes ***@***.***> wrote:

﻿

Hey @Jeffphoenixgold<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJeffphoenixgold&data=05%7C01%7C%7Ce96446ce290c4d7c473508db0db007bc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638118821919752958%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=u4rIcicMuDwP2EJhSHOtuGI%2FK9QdBvF7CA6aCle1EP0%3D&reserved=0>,

Can you give us an update?
Is it still an issue or can we close the ticket?

**Comment by MariMakes** [comment] 2023-02-13 14:20
Thank you! Happy printing!

**Closed by MariMakes** 2023-02-13 14:20 UTC
Labels: Type: Bug, Status: Triage
