### ISSUE TITLE
2.5 (Beta) Crash after clicking on imported STL

### ISSUE THREAD

**Issue by MechanicalMe** [Ultimaker/Cura#1662] opened 2017-04-06 16:07 UTC
Version: 2.5.0-BETA
Platform: Windows-10-10.0.14393
Qt: 5.7.1
PyQt: 5.7.1

Exception:
TypeError: unable to convert a C++ 'QVector3D' instance to a Python object

I imported an STL file, and as soon as I click on it, it crashes. The file is not corrupted, because it slices fine as long as I don't try to move it. 

![image](https://cloud.githubusercontent.com/assets/13726552/24764339/3f2d28ac-1ab1-11e7-9b19-ceac8fc46de2.png)

**Comment by nallath** [comment] 2017-04-07 07:17
Duplicate of #1627

**Closed by nallath** 2017-04-07 07:17 UTC
