### ISSUE TITLE
SD eject closes program

### ISSUE THREAD

**Issue by weaponx7777** [Ultimaker/Cura#9137] opened 2021-01-16 18:57 UTC
**Application version**
Cura Arachne engine Alpha

**Platform**
Windows 10. AMD 4700U with Radeon graphics laptop

**Printer**
CR-10S pro V2

**Reproduction steps**
1. Slice file 
2. save to removable
3. eject removable through Cura
4. Cura closes 

**Screenshot(s)**
N/A

**Actual results**
Cura continues to close when I eject the SD card through the program. 

**Expected results**
Cura should remain open after ejecting the SD card

**Project file**
N/A

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by nallath** [comment] 2021-01-16 19:05
Duplicate of #9057

**Closed by nallath** 2021-01-16 19:05 UTC
Labels: Type: Bug
