### ISSUE TITLE
Multiply Function Does Not Work V4.11.0 on Mac OS 12.0.1 on Apple Silicon

### ISSUE THREAD

**Issue by ASpaceViking** [Ultimaker/Cura#10952] opened 2021-11-28 22:48 UTC
### Application Version

4.11.0

### Platform

Mac OS 12.0.1

### Printer

Ender 3

### Reproduction steps

1. Try to multiply any model by using Edit -> Multiply
2. The pop up for 'multiplying and placing objects' appears but just hangs.
3. Cura never multiplies or places any objects and the pop up stays on the screen. The application does't go unresponsive, but the pop up will not leave until you quit the application. The model is never multipli
![Uploading Screen Shot 2021-11-28 at 3.47.14 PM.png…]()
ed

### Actual results

Nothing - the multiply function does not work.

### Expected results

Cura should duplicate or 'multiply' the model

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This occurs with any file I attempt to multiply in Cura V4.11.0 on Mac OS 12.0.1 on Apple Silicon

**Comment by fvrmr** [comment] 2021-11-29 10:04
Hi @ASpaceViking thank you for your report.
This is a duplicate of: https://github.com/Ultimaker/Cura/issues/10249
And this is fixed in 4.12.1: https://ultimaker.com/software/ultimaker-cura
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-11-29 10:04 UTC
Labels: Type: Bug
