### ISSUE TITLE
Variable Height Support

### ISSUE THREAD

**Issue by viper0078** [Ultimaker/Cura#8848] opened 2020-11-28 07:03 UTC
Variable Height Support

**Is your feature request related to a problem? Please describe.**

The vertical distance of the support of a structure can be set in the "Support top distance".
However, as a result of slicing, the size of the gap will be more than a multiple of LayerHeight.

I print with a LayerHeight of 0.24mm. 
Since the gap between the support and the printed material is large, the underside of the printed material will be rough.
In other cases, the print and the support may be strongly welded together.
The optimal gap between the print and support also depends on the value of LayerHeight.

I want a function that makes it easy to separate the object and the support, and to obtain a clean printing surface.

**Describe the solution you'd like**
I want a function that automatically adjusts the height of the support in contact with the underside of the printed work.

For example
　LayerHeight=0.24mm
　SupportTopDistance=0.10mm
In this case, the height of the topmost support surface is automatically adjusted from 0 to 0.14 mm to ensure a 0.1 mm gap.

This makes it easier for the printout and the support to come off, while still producing a clean printout.

A minimum thickness setting of support would be necessary.

**Comment by Ghostkeeper** [comment] 2020-12-01 11:07
Duplicate of https://github.com/Ultimaker/Cura/issues/6105.

**Closed by Ghostkeeper** 2020-12-01 11:07 UTC
Labels: Type: New Feature
