### ISSUE TITLE
Camera connection

### ISSUE THREAD

**Issue by ThomasSlowhand** [Ultimaker/Cura#13187] opened 2022-09-01 09:52 UTC
### Application Version

5.1.0

### Platform

Windows 11

### Printer

Ultimaker S2+

### Reproduction steps

I am using Cura with Octoprint and Repetier-Server. The camera view in the Monitor tab is disabled when Cura was started before the printer is started, and Cura does not re-econnect to the camera when the printer comes online. You must quit Cura and re-start to enable the camera connection and view in the Monitor tab.

### Actual results

--

### Expected results

--

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

--

**Comment by MariMakes** [comment] 2022-09-02 13:52
Hey @ThomasSlowhand ,

Welcome to the Ultimaker Cura Github 🚀 !

I'm not familiar with the Ultimaker S2+, did you mean an Ultimaker 2+?  🤔 

The Octoprint Plugin is not created by Ultimaker but by one of our lovely community members in his spare time. 
I don't have a printer that supports Octoprint so I can't tell if this behavior is a bug or by design. 
You can leave your bug or feature request on his repository at https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues

I'll be closing this issue since it's not an Ultimaker Cura issue. 
Good luck! 👍

**Closed by MariMakes** 2022-09-02 13:52 UTC
Labels: Type: Bug, Status: Triage
