### ISSUE TITLE
Cura 3.5.0 - Nozzle temperature always at 210 °C

### ISSUE THREAD

**Issue by sched75** [Ultimaker/Cura#4510] opened 2018-10-07 13:06 UTC
**Application Version**

Cura 3.5.0

**Platform**

Windows 10

**Printer**

CTC PRUSA I3 PRO B (clone)

**Steps to Reproduce**

Just try to export G-Code after setting up a temp of 230°C

**Actual Results**

In G-Code you always get 210 °C (any material or setup)

**Expected results**

Should use the requested temp.

**Additional Information**

**Comment by fieldOfView** [comment] 2018-10-07 14:11
Duplicate of #4469. Read about the workaround there.

**Comment by LipuFei** [comment] 2018-10-08 14:04
Since this is a duplicate, I'm closing it now. Made a fix for this for 3.5: https://github.com/Ultimaker/Cura/pull/4520

**Closed** 2018-10-08 14:04 UTC
Labels: Category: Cura, Category: Settings, Status: Duplicate
