### ISSUE TITLE
Connecting Infill Polygons

### ISSUE THREAD

**Issue by BackwardEcho** [Ultimaker/Cura#12334] opened 2022-05-24 08:47 UTC
### Application Version

5.0

### Platform

Windows 10

### Printer

Monoprice Mini Delta (MPMD)

### Reproduction steps

1. Have a 0.25mm nozzle .
2. Test various infill patterns with small nozzle for strength.
3. Find that a Cubic pattern, checking "Connect Infill Polygons", and having "Infill Line Multiplier" greater than 1 gets really strong infill.
4. Upgrade to 5.0
5. Slice a model with a fairly large space where a lot of infill will be printed together.
6. From there the slicing fails until I uncheck "Connect Infill Polygons". It however seems to work for models with small spaces for infill, but I am no longer sure on that.

### Actual results

Slicing failed with an unexpected error.

### Expected results

Slicing doesn't fail.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[fail to slice.zip](https://github.com/Ultimaker/Cura/files/8761005/fail.to.slice.zip)
[can slice.zip](https://github.com/Ultimaker/Cura/files/8761014/can.slice.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/8764962/cura.log)

"Fail to slice" will not slice until "Connect Infill Polygons" is unchecked, however "Can slice" works just fine.

**Comment by Vandresc** [comment] 2022-06-07 15:09
Hi @BackwardEcho , thank you for your feedback, I could indeed reproduce your issue. I will bring this up with the rest of the team.

**Comment by Ghostkeeper** [comment] 2022-06-16 13:41
We analysed this and found it to be a duplicate of https://github.com/Ultimaker/Cura/issues/12312.

As a workaround, you can disable the Randomize Infill Start setting.

**Closed as completed by Ghostkeeper** 2022-06-16 13:41 UTC
Labels: Type: Bug, Status: Duplicate
