### ISSUE TITLE
cura stops as soon as you click open file

### ISSUE THREAD

**Issue by casper76** [Ultimaker/Cura#6312] opened 2019-09-05 23:21 UTC
I just downloaded cura 4.2.1 and every time I click open file it say cura exe has stopped working 
**Application version**

**Platform**

**Printer**

**Reproduction steps**

**Actual results**

**Expected results**

**Additional information**

**Comment by nallath** [comment] 2019-09-06 07:46
Could you please fill in the entire template?

**Comment by Ghostkeeper** [comment] 2019-09-06 13:41
Duplicate of https://github.com/Ultimaker/Cura/issues/5937. Try without any Windows shell extensions. This is an open Qt bug.

**Closed by Ghostkeeper** 2019-09-06 13:41 UTC
Labels: Status: Needs Info, Type: Bug
