### ISSUE TITLE
Start of the print problem, with two nozzles.

### ISSUE THREAD

**Issue by Naamakana** [Ultimaker/Cura#9780] opened 2021-05-06 13:34 UTC
### Application Version

4.9.0

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

1. I started print normally with using PLA and PVA. First layer required both materials.
2. I enabled prime plob on both materials.
3. When print started, PVA squirted prime plob normally and begun to print normally.
4. After PVA printing, the machine skipped PLA prime plob and over all forgot that PLA was pulled backwards with the motor when previous print ended. So obviously it didn't print anything for a while.

### Actual results

So all in all PLA motor did not compensate the fact that PLA was pulled back when previous print ended. And also it for some reason skipped the prime plob command all together. I also tried to start the pring with PLA first and the same problem happened for PVA that time, so either way one of the printheads are bugging.

### Expected results

I expected that both nozzles would make prime plob normally and begun printing with filament in the extruders.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

The error does not occure in version 4.6.1 of Ultimaker Cura. Im not sure about other versions.

**Comment by fvrmr** [comment] 2021-05-06 14:31
Hi @Naamakana thank you for your bug report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9672 that's why I will close this issue. 
And we have fixed this for 4.9.1 that will be released soon.

**Closed by fvrmr** 2021-05-06 14:31 UTC
Labels: Type: Bug
