### ISSUE TITLE
[master] Unconnected support structures

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#8468] opened 2020-09-29 18:31 UTC
I'm designing something new here and noticed the following in the preview tab.
I don't see any sense of the unconnected support structure, so I guess it is a bug in the engine?

**Application version**
Build from master

**Platform**
Linux / Ubuntu / PPA

**Reproduction steps**
1. Open my model and slice it.
2. Select the preview tab and take a look at the path.

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/1847437/94600555-53d6d100-0292-11eb-9a3c-31c218a6f367.png)

**Actual results**
Unconnected support structure.

**Expected results**
Remove the useless structure or connect it to give it some sense.

**Project file**
[UM3_CUAV_X7_5series_mount.3mf_renamed.zip](https://github.com/Ultimaker/Cura/files/5301099/UM3_CUAV_X7_5series_mount.3mf_renamed.zip)

**Log file**
Request it if you need it.

**Additional information**
If you need the part, let me know.

**Comment by Ghostkeeper** [comment] 2020-10-02 13:52
Duplicate of https://github.com/Ultimaker/Cura/issues/7487 . As a workaround, you could try disabling Use Towers or reducing the Support Horizontal Offset.

**Closed by Ghostkeeper** 2020-10-02 13:52 UTC
Labels: Type: Bug
