### ISSUE TITLE
Cancel profile saving with ESC key still override the profile.

### ISSUE THREAD

**Issue by distante** [Ultimaker/Cura#17000] opened 2023-10-16 09:48 UTC
### Cura Version

5.4.0

### Operating System

MacOS 4.0

### Printer

Anycubic Vyper

### Reproduction steps

1. Create a Profile
2. Change something on print setting side menu.
3. Click the save button
4. In the confirmation popup, press the key ESC

### Actual results

The profile gets overridden with the current values

### Expected results

The save process should be cancelled and no saving should happen

### Add your .zip and screenshots here ⬇️

Here I changed the skirt value to 3, clicked save, and then pressed ESC. I had the same problem before, which led me to lose my initial profile with more than 15 changes.

https://github.com/Ultimaker/Cura/assets/5490201/690a79b3-ccd5-4b94-8899-dfe81e310729

**Comment by MariMakes** [comment] 2023-10-16 14:21
Hi @distante,

Welcome to the UltiMaker Cura Github 🚀 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/15601
We have a ticket on our backlog with the intent to improve this behavior.
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/15601

Thanks for your report. Together we can make Cura better 😊

**Closed by MariMakes** 2023-10-16 14:21 UTC
Labels: Type: Bug, Status: Triage
