### ISSUE TITLE
Object of type settingfunction is not json

### ISSUE THREAD

**Issue by shawnp30** [Ultimaker/Cura#13756] opened 2022-11-07 15:07 UTC
### Application Version

5.2.1

### Platform

win11

### Printer

custom corexy

### Reproduction steps

I opened cura. Tried to upload file to my rpi like always and got the error in title. If I cut ufp image upload off it seems to work. Why would it change out of nowhere
![image](https://user-images.githubusercontent.com/20215592/200341472-f8e4c387-1666-4d7f-ad1b-5b5ba64e44e7.png)

### Actual results

Error

### Expected results

Its supposed to upload to my printer
[lstfileissue.zip](https://github.com/Ultimaker/Cura/files/9952826/lstfileissue.zip)
[cura.zip](https://github.com/Ultimaker/Cura/files/9952882/cura.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.zip](https://github.com/Ultimaker/Cura/files/9952887/cura.zip)
[lstfileissue.zip](https://github.com/Ultimaker/Cura/files/9952889/lstfileissue.zip)

**Comment by fieldOfView** [comment] 2022-11-07 15:17
Thanks for reporting. This is a duplicate of #13675.

**Closed by fieldOfView** 2022-11-07 15:17 UTC
Labels: Type: Bug, Status: Triage
