### ISSUE TITLE
Problem with select model

### ISSUE THREAD

**Issue by userosos** [Ultimaker/Cura#6268] opened 2019-08-27 20:16 UTC
Cura 4.2.1 have problem with select model. Sometimes i can not select a model into bed. And can't rotate selected model.

**Comment by rburema** [comment] 2019-08-28 07:59
Hello @userosos, Does this happen for specific models, or all of them?

**Comment by userosos** [comment] 2019-08-28 14:12
@rburema all of them

**Comment by rburema** [comment] 2019-08-28 15:22
> Sometimes i can not select a model into bed.

Do you mean that the model is below the build-plate when you try to select it?

**Comment by userosos** [comment] 2019-08-28 16:56
@rburema 
> Do you mean that the model is below the build-plate when you try to select it?
Yes. I has the problem regularly but not all of them models which are located on the build-plate.

**Comment by rburema** [comment] 2019-08-29 06:42
So if I understand correctly, the following .gif illustrates the problem?

![model_below](https://user-images.githubusercontent.com/41987080/63916380-9814f380-ca38-11e9-942c-29ad2cba8685.gif)

The gray area is the 'shadow' of the model, not the actual model, so it can't be used to select it. Which is more difficult, since the object is not visible below the build-plate?

**Comment by userosos** [comment] 2019-08-29 18:47
> 
> 
> So if I understand correctly, the following .gif illustrates the problem?
> 
> ![model_below](https://user-images.githubusercontent.com/41987080/63916380-9814f380-ca38-11e9-942c-29ad2cba8685.gif)
> 
> The gray area is the 'shadow' of the model, not the actual model, so it can't be used to select it. Which is more difficult, since the object is not visible below the build-plate?

No. I can not select model sometimes. But i can not replay the bug now.

**Comment by fieldOfView** [comment] 2019-08-29 21:19
Are you using the Sidebar GUI plugin?

**Comment by userosos** [comment] 2019-08-30 07:18
> Are you using the Sidebar GUI plugin?

Yes. I use the plugin.

**Comment by fieldOfView** [comment] 2019-08-30 09:56
I can sometimes reproduce it.
I'm looking into it.

**Comment by Ghostkeeper** [comment] 2019-09-03 09:13
I've had this problem for the past 2 years. There seem to be some invisible zones in the 3D scene where the selection area wasn't properly rendered or something.

**Comment by fieldOfView** [comment] 2019-09-03 09:38
I have sofar been unable to reproduce it with https://github.com/Ultimaker/Uranium/pull/518 in place. 

I am not sure if the selectionpass is to blame; I inspected the selectionpass with RenderDoc (an OpenGL debugger) and the selectionpass rendered fine. It might be that something that is not currently visible is interfering with the mouse coordinates.

**Comment by Ghostkeeper** [comment] 2019-09-03 14:21
@rburema has had a similar issue on a branch that he was working on and that was fixed by Ultimaker/Uranium#518 as well. That gives me sufficient confidence that this issue is also fixed by it. Thanks fieldOfView!

**Closed by Ghostkeeper** 2019-09-03 14:21 UTC
Labels: Status: Needs Info, Type: Bug
