### ISSUE TITLE
Profile export

### ISSUE THREAD

**Issue by GaMa87** [Ultimaker/Cura#12209] opened 2022-05-15 18:21 UTC
### Application Version

5.0.0. BETA

### Platform

MAC OSX 12.3.1.

### Printer

CR6 SE

### Reproduction steps

I tried to export my profile from Preferences\Configure Cura\Profiles. 

### Actual results

It looks like everything ok, but when I export a profile, I can not find the file and I tried a different location for saving.

### Expected results

The file should be saved (exported) in the chosen folder.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I think I wrote everything above

**Comment by nallath** [comment] 2022-05-17 12:37
Closing this as a duplicate of https://github.com/Ultimaker/Cura/issues/12204

**Closed by nallath** 2022-05-17 12:37 UTC
Labels: Type: Bug, Status: Duplicate
