### ISSUE TITLE
Change the custom supports system pls

### ISSUE THREAD

**Issue by userosos** [Ultimaker/Cura#8151] opened 2020-08-05 17:17 UTC
Now i can't use the system for manual support. It is very crazy. I think that it need change.  It is very bed and slowly.
Ok. I think that you can do:
1. Press the button "manual supports"
2. Then you need touch surface an model with left click mouse - at the touch point of the model the color to indicate the choice of the surface of the supports.
3. Left click mouse and touch surface an model will be clear the surface for an support and change the color for indicate.
4. Add settings for set the radius touching.
What do you think about it?

**Comment by Ghostkeeper** [comment] 2020-08-06 15:16
I think that's a very good idea. In fact, that's precisely what I implemented for my [Custom Support](https://github.com/Ultimaker/Cura/tree/feature_custom_support/plugins/CustomSupport) plug-in back in 2018. However that project was never finished because Ultimaker doesn't think research is important enough. I don't have the time to finish it.

I'll close this as a duplicate of https://github.com/Ultimaker/Cura/issues/7291.

**Closed by Ghostkeeper** 2020-08-06 15:16 UTC
Labels: Type: New Feature
