### ISSUE TITLE
Cura 5.4.0 - Still facing no Support Brim when Bed Adhesion is set to 'None'

### ISSUE THREAD

**Issue by gmoua663** [Ultimaker/Cura#16702] opened 2023-09-09 04:42 UTC
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Creality Ender 3 with Klipper

### Reproduction steps

Set Bed Adhesion to 'None'

Slice

### Actual results

Cura will not print Support Brim. 

### Expected results

Cura should print the Support Brim.

The issue is that even with Skirt Line Count set to '0' it still wants to print a line around the entire print. It's an issue because if I want to use the entire bed I need to disable any kind of skirt or brim. Bed adhesion isn't an issue with my printers so I don't regularly use any type of additional bed adhesion from Cura. 

### Add your .zip and screenshots here ⬇️

![Screenshot 2023-09-09 004218](https://github.com/Ultimaker/Cura/assets/100174303/06586759-5423-48e5-8b2e-85b6d34be8b0)

**Comment by Asterchades** [comment] 2023-09-10 05:07
Yes. It has been fixed internally but that was well after the release of 5.4. It should be part of the next release, which at this point should be 5.5. Unfortunately I have no estimated release window for that build.

Duplicate of #14983.

**Closed by Asterchades** 2023-09-10 05:07 UTC
Labels: Type: Bug, Status: Triage
