### ISSUE TITLE
PLA Diameter

### ISSUE THREAD

**Issue by Teclkltd** [Ultimaker/Cura#4488] opened 2018-10-05 11:16 UTC
The latest version of Cura 3.5 has the PLA Diameter for the Crteality Ender 3 set at 2.85mm when it should be 1.75mm.
This really screws up prints.

Thanks and Regards   Keith

**Comment by fieldOfView** [comment] 2018-10-05 11:59
Duplicate of https://github.com/Ultimaker/Cura/issues/4468

**Closed** 2018-10-08 11:07 UTC
