### ISSUE TITLE
Unable to paste in new Start Code

### ISSUE THREAD

**Issue by grumpytwo** [Ultimaker/Cura#6885] opened 2019-12-30 15:52 UTC
**Application version**
Cura 4.4.1

**Platform**
Windows 10

**Printer**
Ender 3

**Reproduction steps**
1. Right clicked mouse 
2. (Something you did next.)

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
nothing happens

**Expected results**
 I was expecting the usual cut paste copy menue

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by grumpytwo** [comment] 2019-12-30 15:54
I have fitted a bed leveller to my Ender 3 and I am trying to paste the new code into the Cura start code only Cura won't let me.

I have copied the code from Notepad but there seems no way to paste it into Cure, right clicking the mouse and nothing happens.
I realise it is probably something I am doing wrong but I can't find an answer anywhere.

**Comment by yet-another-average-joe** [comment] 2019-12-30 16:09
just do Ctrl V...

**Comment by Ghostkeeper** [comment] 2019-12-31 13:49
Duplicate of https://github.com/Ultimaker/Cura/issues/6159.

**Closed by Ghostkeeper** 2019-12-31 13:49 UTC
