### ISSUE TITLE
Slicing fail

### ISSUE THREAD

**Issue by GavSeil** [Ultimaker/Cura#14920] opened 2023-03-16 22:26 UTC
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Creality Ender 3 Pro

### Reproduction steps

Loaded model, repositioned and commenced slicing

### Actual results

Slicing failed approx 50% complete :(
[CE3PRO_half shell.zip](https://github.com/Ultimaker/Cura/files/10996351/CE3PRO_half.shell.zip)

### Expected results

slicing failed!

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

slicing failed!

**Comment by MariMakes** [comment] 2023-04-03 10:21
Hey @GavSeil,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I can reproduce your crash. So I'll bring it up to the team.
Thanks for your report 👍

I also noticed that if I rotate the model 90 degrees, I can slice it successfully. 
I hope that helps you to get unstuck. 
![image](https://user-images.githubusercontent.com/40423138/229482690-860caa1d-5c6f-46ce-abeb-5c40b7e62909.png)

**Comment by jellespijker** [comment] 2024-01-14 16:25
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.
I'm closing this issue as fixed for the 5.7.0 release
![image](https://github.com/Ultimaker/Cura/assets/8535734/f2fbc8fb-b44c-48d7-af0c-8c740541ce85)

**Closed by jellespijker** 2024-01-14 16:25 UTC
Labels: Type: Bug, Status: Under Investigation, Slicing Error :collision:
