### ISSUE TITLE
Removing Profiles doesn't delete Profiles

### ISSUE THREAD

**Issue by Ergonomicmike** [Ultimaker/Cura#12739] opened 2022-07-11 14:34 UTC
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ender 3 v2

### Reproduction steps

I have been using Cura 5.0.1 Beta. While using it, I cleaned up a bunch of my Profiles by "removing" them. I expected that that was the same as deleting them. 

### Actual results

But no. When I reinstalled Cure 5.0.0 - in a different directory than the Beta - all my old Profiles populated the list in 5.0.0.

### Expected results

I expected that "removing" a profile was the same as deleting a profile.

If this is the intended behavior, then does the file that holds Profiles (a .json, if I have it correct) grow without bound?

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

(Is there a "compact" function or add-on, that users can use to clean up the Profile's file?)

**Comment by Ghostkeeper** [comment] 2022-07-13 14:27
I think you meant 5.1.0, not 5.0.1?

Indeed, you're right that changes made in 5.1 are not reflected in Cura 5.0.

When you first start a new, higher minor version, Cura will copy your entire configuration and upgrade it for the new version. Changes made in the new version are not downgraded back to the 5.0 configuration folder.

We used to have an option in the uninstaller to clean up the previous release when the uninstaller uninstalls it. However this gave problems because the uninstaller runs before the user starts the new version, giving Cura no opportunity to copy that configuration and then the configuration is lost. I'm not really sure what the plans are now for that.

But in any case, this is expected behaviour. Downgrading changes to previous Cura releases is generally hard to do because those Cura versions sometimes have vastly different structures, don't know of certain settings (Enable Travel Accelerations, etc.) or even entire concepts (like intent profiles). We won't fix this.

**Closed by Ghostkeeper** 2022-07-13 14:27 UTC
Labels: Type: Bug, Status: Triage
