### ISSUE TITLE
Spiralize outer contour problems with accuracy

### ISSUE THREAD

**Issue by thetechy2** [Ultimaker/Cura#12504] opened 2022-06-12 04:40 UTC
### Application Version

4.11.10

### Platform

WIN10

### Printer

custom i3

### Reproduction steps

put in model and set to vase mode print profile spiralize outer contour, smooth outer. the slicer just add random spots in the wall that arent present anywhere on my model.

### Actual results

These errors are barely visible from here
![vase_mode_smoll](https://user-images.githubusercontent.com/55606257/173214587-22061635-a0ed-4c3e-9360-d7a83a1b7dce.JPG)
starting to see
![vase_mode_smoll_1](https://user-images.githubusercontent.com/55606257/173214590-b9033145-0be1-4c90-92c2-3e290a54d39e.JPG)
there! it just moves a part of the wall there for no reason
![vase_mode_smoll_2](https://user-images.githubusercontent.com/55606257/173214592-5f227e10-6a4d-4c96-8dd1-615462a4d32e.JPG)

### Expected results

this is what the model is supposed to look like
![aactual model](https://user-images.githubusercontent.com/55606257/173214637-686c965c-ef56-409d-a6bf-8f5b71fa3ced.JPG)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Project-[foldy_lampshade.zip](https://github.com/Ultimaker/Cura/files/8885210/foldy_lampshade.zip)
Log-[cura.log](https://github.com/Ultimaker/Cura/files/8885211/cura.log)

**Comment by GregValiant** [comment] 2022-06-12 11:23
This is really a duplicate of #12503.  The model has errors, and is not suitable to use spiralize as it isn't solid all the way through and consists of two meshes.
The preview you are getting is not of a spiralized model but a conventionally sliced model with a single wall.  Your 1.0 line width may be hiding how the slicing really turned out.
I'll leave this one open if you would care to add further comments but I don't see a bug here.

**Comment by nallath** [comment] 2022-06-13 08:25
Furthermore, this is also done in cura 4.11, which will no longer get any updates.

**Closed by nallath** 2022-06-13 08:25 UTC
Labels: Status: Needs Info, Status: Under Investigation
