### ISSUE TITLE
Conical support missing

### ISSUE THREAD

**Issue by Chad541121** [Ultimaker/Cura#14789] opened 2023-03-06 14:49 UTC
### Application Version

5.3.0 beta 2

### Platform

Window 10

### Printer

Ender 5 Plus

### Reproduction steps

1. When conical support is enabled, sliced.  There is no support shown in the preview.
2. If I use one of my custom profiles from Cura 5.0.0 then the conical support is shown, however there is no brim.
3. With conical support disabled and brim enabled, supports are generated but brim is missing

### Actual results

1. There is no support shown in the preview.
2. There is no brim.
3. There is no brim.

### Expected results

1. Should see conical support with brim
2. Should have brim
3. Should have brim

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Problem_No conical support.zip](https://github.com/Ultimaker/Cura/files/10899427/Problem_No.conical.support.zip)

**Comment by GregValiant** [comment] 2023-03-06 20:11
Thanks for the report and the file.
I can confirm that Conical Supports is broken for certain printers.  When my Ender 3 Pro is active it simply isn't available and for some Creality and Anycubic printers it might be available but it just doesn't work.
#14666 , #14752, and a couple of others appear to be duplicates of this.
I'll mark it as a duplicate and the Cura team will take a look.

**Comment by MariMakes** [comment] 2023-03-20 16:57
Hey @Chad541121,

Thanks for your report 👍
We were able to resolve the problem with Conical Support in 5.3.0 Stable. 

I can successfully slice your model. You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0
![image](https://user-images.githubusercontent.com/40423138/226412952-bb752a08-7c45-44d9-b31d-765d5471285d.png)

I'll close this issue since there is a solution in place. 
Please let us know if you run into any new issues. 💪

**Closed by MariMakes** 2023-03-20 16:57 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation

**Comment by Chad541121** [comment] 2023-03-21 11:37
The problem is not fixed!!!

 

Add support brim and you can see that it does not generate support, and first layer doesn’t touch the build plate!  Change support brim to zero and you will see the support touches the build plate.

**Comment by Chad541121** [comment] 2023-03-21 11:42
Apologies.  I figured out that my saved profiles don’t update.  Is there a way to update my existing profiles, or do I have to rebuild all my profiles?

**Comment by Chad541121** [comment] 2023-03-21 11:58
There is a setting somewhere that breaks the support brim feature.  I just changed all my settings to match my old profile and now the support brim disappears again.

**Comment by Chad541121** [comment] 2023-03-21 17:03
I do not have a dual extender. How would I define it. How is build plate adhesion for the model relevant to support brim? I would think they should be separate entities. Chad's iPhone 14 ProOn Mar 21, 2023, at 10:13 AM, MariMakes ***@***.***> wrote:﻿
Hey @Chad541121,
Could it be related to #14666 (comment)?
In some dual extrusion printjobs we see small brims if the Buildplate Adhesion Extruder is not defined.
If you define it to be one of your extruders instead of overridden it should work as intended.

**Comment by Chad541121** [comment] 2023-03-22 11:43
I only have 1 extruder and those options aren’t available in the 5.3.0 that I downloaded.  Even if I search for extruder, the options don’t show up.

**Comment by MariMakes** [comment] 2023-03-28 12:08
Hey @Chad541121,

Apologies, I must have confused your report for a different one. 
I took another look at your original project file. 
I see that a support brim is generated, but only the inside, this is expected. 
That's also what is described in the tooltip: 
![image](https://user-images.githubusercontent.com/40423138/228231299-a4fd5ff6-01cc-4d25-8c94-ee05338ed37e.png)

![image](https://user-images.githubusercontent.com/40423138/228230342-c73e9502-c899-415d-852b-bc0cf01f0d67.png)

If you want a bigger brim on the support, you'll have to turn on the brim for the model and make sure to uncheck the Brim Only on Outside. Than it will look like this: 
![image](https://user-images.githubusercontent.com/40423138/228230595-ee91a6b4-a332-4bd1-b01f-69973c0f5df7.png)

Is that what you are looking for?

**Comment by Chad541121** [comment] 2023-03-28 20:05
When I enable support brim it does nothing. No support brim is generated unless model support is also enabled. I want 3-4 layers of support brim and zero model support brim. If model support is not enabled. I’m then support brim leaves a gap between print bed and support instead of adding support brim it actually disappearsChad's iPhone 14 ProOn Mar 28, 2023, at 8:09 AM, MariMakes ***@***.***> wrote:﻿
Hey @Chad541121,
Apologies, I must have confused your report for a different one.
I took another look at your original project file.
I see that a support brim is generated, but only the inside, this is expected.
That's also what is described in the tooltip:


If you want a bigger brim on the support, you'll have to turn on the brim for the model and make sure to uncheck the Brim Only on Outside. Than it will look like this:

Is that what you are looking for?

**Comment by MariMakes** [comment] 2023-04-03 12:56
This discussion seems to have resulted in the following ticket: 
https://github.com/Ultimaker/Cura/issues/14983
