### ISSUE TITLE
Reload function only reloads the last changed object

### ISSUE THREAD

**Issue by Harryhar** [Ultimaker/Cura#10137] opened 2021-07-14 15:24 UTC
### Application Version

4.10.0

### Platform

Windows 10

### Printer

Ultimaker 2+

### Reproduction steps

Load 2 or more objects
Change 2 of the objects loaded in Cura
Cura asks to reload the object that has changed.

### Actual results

Cura only loads the last changed object, ignoring the first changed object.

### Expected results

Cura should load all changed objects

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No additional info

**Comment by fvrmr** [comment] 2021-07-15 10:35
Hi @Harryhar I can't reproduce your issue. Do you have any model files that can does reproduce this.

**Comment by Harryhar** [comment] 2021-07-15 11:59
Hi @fvrmr 

Copy the 2 objects from the directory "initial" to a place on your harddrive.
Import the 2 objects from your harddrive into Cura.
Copy the 2 files from the directroy "replace" to the same place on your harddrive where you copied the files from "initial"

After replacing Cura responds with :

File has been modified
Would you like to reload Object 1.stl?

Only the 1st object is reloaded, the changes to the second object are not reloaded.

[cura_replace_problem.zip](https://github.com/Ultimaker/Cura/files/6822864/cura_replace_problem.zip)

**Comment by fvrmr** [comment] 2021-07-16 13:29
Thank you, I can reproduce your issue. But if you press F5 or right click and press `reload all models` the other model will be reloaded. I will bring this up for discussion with the team. Keep you posted!

**Comment by fvrmr** [comment] 2021-07-21 15:44
We have created a ticket on our backlog for this. Developers see CURA-8419

**Comment by MariMakes** [comment] 2024-11-19 15:51
👋 Quick update on our side.
This is resolved in the 5.9 release 🎉 , you can download the Cura version with the fix here: [https://github.com/Ultimaker/Cura/releases/tag/5.9.0](https://github.com/Ultimaker/Cura/releases/tag/5.9.0)

I'll close this issue since it's resolved.
Thanks again, and please let us know if you run into any other issues 💪

**Closed by MariMakes** 2024-11-19 15:51 UTC
Labels: Type: Bug
