### ISSUE TITLE
[4.2.1] Unable to remove custom material from list

### ISSUE THREAD

**Issue by jake-meister** [Ultimaker/Cura#6115] opened 2019-08-01 15:29 UTC
I was able to create a new material on the Materials list, but I cannot seem to delete it now. The "Remove" button remins inactive and the new material cannot be selected on the list.

**Comment by fieldOfView** [comment] 2019-08-01 15:31
That is probably because it is the currently selected material for a printer in Cura. Please select/activate a different material, and the Remove button should become active.

**Comment by jake-meister** [comment] 2019-08-01 17:06
Fixed it. The culprit is the "Material Settings" Plugin - it seems to "freeze" the Material Preference Pane.

**Comment by fieldOfView** [comment] 2019-08-01 17:52
I am the creator of the Material Settings plugin. Could you elaborate what you mean by "freeze"?

**Comment by jake-meister** [comment] 2019-08-01 19:28
Sure. If you install the Material Settings Plug-in in cura 4.2.1 the materials cannot be selected or edited from within the "manage Materials" menu. I will upload a video to youtube (private access) to illustrate it better... I am running Cura 4.2.1 on a mac (Mojave 10.14.6)

**Comment by jake-meister** [comment] 2019-08-01 19:51
https://youtu.be/6G4alIyKDHI

**Comment by Liger0** [comment] 2019-08-02 17:03
#6137 is explained then.

**Comment by Ghostkeeper** [comment] 2019-08-08 12:01
Closing this as duplicate of https://github.com/fieldOfView/Cura-MaterialSettingsPlugin/issues/3 . It looks like fieldOfView has made a fix for it in his plug-in :tada:

**Closed by Ghostkeeper** 2019-08-08 12:01 UTC
Labels: Type: Bug
