### ISSUE TITLE
"Pause at Height" returns 1mm high

### ISSUE THREAD

**Issue by tlhintoq** [Ultimaker/Cura#6035] opened 2019-07-20 21:58 UTC
Application Version: 4.2 beta
Platform: Windows
Printer: All for this bug - not printer specific
Steps:
Slice a job with using "Pause at height"
Pick a layer. Doesn't matter.  22 for example
At the pause there is a raise of 1mm
Then a second raise 
Upon returning out of the pause, it returns to the height 1mm to high
On the _next_ layer it will DROP to the next expected layer

Please see attached gCode screen shot of significant portions with Z height highlighted.

This has happened on my CR10s5, Ender3pro and Tronxy x5-st-400
Its not machine specific.  It has ruined several prints before I thought to check the gCode.

![image](https://user-images.githubusercontent.com/11351506/61584574-fd132a80-ab17-11e9-88ab-8f9efe1636c1.png)

**Comment by Ghostkeeper** [comment] 2019-07-22 10:56
Duplicate of https://github.com/Ultimaker/Cura/issues/5924.

**Closed by Ghostkeeper** 2019-07-22 10:56 UTC
Labels: Type: Bug
