### ISSUE TITLE
Slicing failed at files which have been previously successful

### ISSUE THREAD

**Issue by tx3m** [Ultimaker/Cura#15593] opened 2023-05-23 19:26 UTC
### Application Version

5.3.0-beta

### Platform

Windows 11

### Printer

Longer LK4 Pro

### Reproduction steps

Trying to slice a model

### Actual results

Slicing failed

### Expected results

Slicing success

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

After restarting cura the slicing of the same files in the same location was normal

[LLK4PRO SpoolDrawer_extra_low_5_box Custom PLA lw 0.8mm lh 0.3mm if 15% ext1 203C bed 60C.zip](https://github.com/Ultimaker/Cura/files/11547709/LLK4PRO.SpoolDrawer_extra_low_5_box.Custom.PLA.lw.0.8mm.lh.0.3mm.if.15.ext1.203C.bed.60C.zip)

[cura.log](https://github.com/Ultimaker/Cura/files/11547715/cura.log)

**Comment by GregValiant** [comment] 2023-05-24 10:23
Thanks for the report and the files.
From the log file:  _"Backend exited abnormally with return code 3221225477!"_.  My understanding is that code is a memory error from the Cura Engine.  I've never been able to duplicate the error on my Win10 system and your project sliced fine for me.

This is a duplicate of numerous other reports about 5.3.1.  The Cura team is aware of this bug and hopefully it will be addressed by version 5.4.  I'll mark this as a dupe and a slicing error and go ahead and close this.  I hope you understand.

You might try a couple of things to get them to slice.  Move and/or rotate the model in the Cura workspace.  You can also try changing the Initial Layer height or the Layer Height by a little bit.

**Closed by GregValiant** 2023-05-24 10:23 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error :collision:
