### ISSUE TITLE
Cura 2.6 unable to upgrade firmware for UMO+

### ISSUE THREAD

**Issue by Pascal1573** [Ultimaker/Cura#2028] opened 2017-06-25 20:59 UTC
I'm Using a Ultimaker Original plus and i'm unable to upgrade the firmware.
"due to a communiaction error".
This works fine using earlier versions V2.5 and before.
(I also reported this using the 2.6 Beta)

I removed everything and reinstalled, without a result.
Returning to Cura 2.5.
![cura26error](https://user-images.githubusercontent.com/29694510/27519722-f92d8472-59f9-11e7-8c65-ac9929e4bbfd.jpg)

**Comment by nallath** [comment] 2017-06-26 07:41
Could you post the logs?

**Comment by ChrisRiddell** [comment] 2017-06-26 14:05
I had this same issue on windows 10, worked fine on OSX though.

**Comment by Pascal1573** [comment] 2017-06-27 06:39
Sorry for the late responce I will upload the log asap. not able to at the moment. sorry!
as soon as i'm able to, i'm going te reinstall 2.6 and send the log!

By the way I use windows 10 pro (64bit) (ann. ed.)

**Comment by Pascal1573** [comment] 2017-06-28 21:00
Hi I installed cura2.6 and tried to update firmware.
the cura log is 2 days old, but the stderr and stdout logs are "from now".
It looks like the printer is detected at com4, but  then the update procedure tries to use com1.
I did see cersion 2.6.1 going to install that one now.


[stdout.zip](https://github.com/Ultimaker/Cura/files/1110189/stdout.zip)

**Comment by nallath** [comment] 2017-06-29 08:24
I don't see anything specific that could explain this in the logs. Weird. I'll ask testing if they also encountered the issue.

**Comment by Pascal1573** [comment] 2017-06-29 10:28
ok (?)
If I must test something just tell me and I'll do it.
With Cura 2.5 and before it works just fine even now.
It's the same USB cable the same PC the same UMO+.
When using cura 2.6, do I have to upgrade firmware? Or could I use cura 2.6(.1) and the firmware that I loaded with 2.5?

**Comment by nallath** [comment] 2017-06-29 10:55
We didn't change any code regarding the USB upgrading (or any USB related stuff) as far as I know. Could you try if uploading the firmware with the install custom firmware button works (and then upload the firmware from version 2.5)?

**Comment by fieldOfView** [comment] 2017-06-29 11:08
> When using cura 2.6, do I have to upgrade firmware? Or could I use cura 2.6(.1) and the firmware that I loaded with 2.5?

You should be able to run Cura 2.6 with the firmware that came with Cura 2.5 just fine.

**Comment by Pascal1573** [comment] 2017-06-29 20:55
nallath i did what you asked.
I used cura 2.6.1 to upload the firmware provided with cura 2.5
![20170629 cura261 - firmware from 250 update](https://user-images.githubusercontent.com/29694510/27709819-d1ca0762-5d1d-11e7-93a0-a90bc4872e62.png)
as you can see again unsuccessfull.
and here are the logs again.
[cura.zip](https://github.com/Ultimaker/Cura/files/1113499/cura.zip)

**Comment by Equinox1st** [comment] 2017-06-30 11:51
Hi there, i have the same Problem. Using Win10 64 Bit and the latest Cura 2.6.1. I'm not able to do the upgrade, it always stops with the communication Error mentioned above. But when i check the Version on my Ultimaker 2+ it tells me Firmware Version 2.6 14. Jun. With Cura 2.5 everything worked fine (It installed the 2.4 Firmware propperly)  I also deleted the Cura Folders in AppData Roaming // Local. No effect. If you want some logs... Where can i find them? :D

**Comment by Pascal1573** [comment] 2017-06-30 22:13
Hi!
The logs are in:
c:\users\<username>\appdata\cura

**Comment by Equinox1st** [comment] 2017-06-30 22:32
Thank you :) I'll post them on Monday

**Comment by fieldOfView** [comment] 2017-07-01 12:04
Note that for 2.6, the logs are in /roaming/cura/2.6, not in /local/cura

**Comment by Equinox1st** [comment] 2017-07-01 15:50
Ok Thanks :)

**Comment by Pascal1573** [comment] 2017-07-02 16:46
oke.. then I did post the wrong ones. thanks!

**Comment by Ghostkeeper** [comment] 2017-07-03 01:26
Worth noting that while Cura 2.6 has a "new" version for the UMO firmware and all its variants, there should be no change from the 2.5 other than the compilation date and the version number.

This is because of the script that I'm using to recompile: https://github.com/Ultimaker/cura-build/blob/master/marlin-build.sh
It basically just builds all of the firmwares that Cura supports except that odd Witbox one. Perhaps it should do something with the commit hashes to only recompile the ones that are updated.

**Comment by Equinox1st** [comment] 2017-07-03 08:24
Ok, so now here are the logs. 

I'm using Win 10 64 Bit and an Ultimaker 2+

First I deleted Cura 2.6.1 (the files in AppData\local an Roaming too) and installed 2.5 and did the firmware upgrade, everything was fine. 

@Pascal1573 The Logs (cura/stderr/stdout) are in the directory appdata\local 

![img_6449](https://user-images.githubusercontent.com/29797145/27783953-8fec3e38-5fd8-11e7-928f-dff296a6adaf.JPG)
![img_6450](https://user-images.githubusercontent.com/29797145/27783954-8ff00144-5fd8-11e7-9168-a1a188574739.JPG)
[Log Cura 25.zip](https://github.com/Ultimaker/Cura/files/1118874/Log.Cura.25.zip)


Now i deleted Cura 2.5 (the appdata folders too) an installed 2.6.1
It abortet with the known Error Msg but whe i checked the Version on the Printer it is a new Version
@Pascal1573 The logs are here: cura.log at Roaming and the other two at local

![img_6452](https://user-images.githubusercontent.com/29797145/27784195-99f1ffac-5fd9-11e7-8261-2743c7cc3b46.JPG)
![img_6453](https://user-images.githubusercontent.com/29797145/27784194-99edc1ee-5fd9-11e7-96fe-664382ee05f9.JPG)
[Log Cura 2.6.1.zip](https://github.com/Ultimaker/Cura/files/1118888/Log.Cura.2.6.1.zip)

**Comment by Ghostkeeper** [comment] 2017-07-03 10:56
I just tested this on an Ultimaker Original and an Ultimaker Original+. They seemed to upgrade fine. No error messages in Cura, just "completed".

**Comment by Pascal1573** [comment] 2017-07-03 11:04
Okay, but I still get the message. As a did mention same PC same cable same printer..
With 2.5 no error , with 2.6(.1) the commnunication error.
The firmware is loaded in the printer though!
Did you test with a apple? (Someone did mention that they did get the message on an apple)
I use the windows version.

**Comment by Ghostkeeper** [comment] 2017-07-03 11:05
It's a hackintosh: Apple hardware but the OS is Ubuntu.

**Comment by fieldOfView** [comment] 2017-07-03 11:10
(that's not a hackintosh; hackintosh is OSX on non-apple hardware)

**Comment by Ghostkeeper** [comment] 2017-07-03 11:27
Ah. Well it's a Macinhack then?

**Comment by Ghostkeeper** [comment] 2017-07-07 07:37
@teriperi tried this on Windows 10 at my behest and says it updated fine for her as well.

**Comment by Pascal1573** [comment] 2017-07-09 14:02
@Ghostkeeper:  I just updated to cura 2.6.2 and tried it again.
I still get the "error message" "Firmware update failed due to an comminication error.".
Unlike the message sugested the firmware is loaded though... firmware date 4 jul 2017.

It looks like you don't believe the other persons in this topic, only because your update is going okay? Peronaly I think you are just testing with your ubuntu box, or your running windows 10 (pro or are you using home) in a virtual machine.
(And if I'm mistaken than sorry for my comment.)

I'm going to update my windows 10 pro from annivesary edition to creators update. So I have to test eveything again, if my PC is up and running again..

**Comment by Ghostkeeper** [comment] 2017-07-10 01:17
I'm believing you! It's just that when we can't reproduce the issue on our end it's going to be very hard to do anything about it.

I was indeed testing with my Ubuntu box, but the Windows 10 was an actual Windows 10 laptop. I believe it's Enterprise edition (not entirely sure).

My prime suspect right now is the Arduino firmware. That has given us trouble in the past as well. You could try re-installing the Arduino firmware, maybe. You can install it through the Cura installer, or from the Arduino website. Don't use the default firmware that comes with Windows 10.

**Comment by Pascal1573** [comment] 2017-07-19 16:17
Sorry for the late responce.
Isn't the arduino formware/driver installed by the cura installer?
I have cura 2.5 also installed on my windows box.
Can I use or run someting from that install to install the arduino stuff?
Firmware update is going okay with the 2.5.

**Comment by Ghostkeeper** [comment] 2017-07-24 15:28
Yes the Arduino firmware should get installed by the Cura installer (unless you disable that). However if you ever tried fixing the firmware via Windows, Windows will put its own, older version of the firmware back.

The Arduino versions we delivered with 2.5 and with 2.6 are the same. It shouldn't matter. In fact, they haven't been updated in [2 years](https://github.com/Ultimaker/cura-binary-data/tree/master/windows/arduino), but still the version in Windows is older...

So if 2.5 worked and 2.6 didn't then it would be something on Cura's side that broke it. But only broke it for you.

**Comment by fieldOfView** [comment] 2017-07-24 15:43
@Ghostkeeper Firmware or driver?

**Comment by Equinox1st** [comment] 2017-07-24 18:22
@Ghostkeeper For me too 😄
can we somehow give you more Informations, so you can reproduce this? 
When 2.6.1 got out, i also tried upgrading with my win10 Laptop, this failed the same way. Sorry i forgot about it...

**Comment by Equinox1st** [comment] 2017-07-25 17:03
Ok i tried it with Cura 2.6.2. 
Laptop success - Desktop failed.... I added the Logs
[Laptop.zip](https://github.com/Ultimaker/Cura/files/1174194/Laptop.zip)
[Desktop.zip](https://github.com/Ultimaker/Cura/files/1174193/Desktop.zip)

**Comment by Pascal1573** [comment] 2017-07-25 21:00
okay....I didn't cancel the driver installation that came with the cura installer.. 
But like I mentiond my windows had an update, so I will install everything cura related once again.
(But everything I wrote was before this update (v1703 "creators update"))

The arduino driver must be the "not MS" one, so this could also mean that the usb (chipset) driver could be giving the same problem.(?) (at the moment this is a MS driver (for intel 5 series) on my machine i noticed).
Going to correct that one.

**Comment by Pascal1573** [comment] 2017-07-30 04:23
Hi. I installed the arduino driver using the newst ide (1.8.3) installer from www.arduino.cc
Sorry that I have to say that the same thing happens while updating the software.
It results in a communication error message, but it seems the firmware is loaded to the UMO  plus board.
And like before printing via USB is okay.

**Comment by delinend** [comment] 2017-08-02 17:32
I see same problem, with "Firmware update failed due to an comminication error." on my Win10 1703. 
My only solution was to use Cura 2.5.0, and then select "Upload custom Firmware", and then select the new firmware "MarlinUltimaker2plus.hex" from the "..Cura 2.6/resources/firmware" directory. This updates with no errors.
It's not the best solution, but it works until now.

**Comment by Pascal1573** [comment] 2017-08-02 22:23
Yeh that was suggested by Nallath in the past. That worked for me too , for my UMO+.
Thanks for confirming ;)

**Comment by Pascal1573** [comment] 2017-08-07 20:59
I just downloaded and installed Cura 2.7 beta from the ultimaker site.
Upgrading firmware does work in this version (2.7 beta) just like with cura 2.5 for my ultimaker Original plus.

**Comment by ETitus** [comment] 2017-08-12 11:42
Last time I printed I was using legacy Cura, time to upgrade.

Can confirm Windows 10 1703 with Cura 2.6.2 doesn't like the firmware update and it is indeed fixed in 2.7 beta, I used 2.7 to load both the firmware included in 2.7 and 2.6.2(downgraded successfully).

**Comment by Ghostkeeper** [comment] 2017-08-14 23:22
I don't remember anything being changed for 2.7 related to this.

I mean, I'm glad that it apparently works again, but I'm a bit suspicious!

**Comment by TAGood827** [comment] 2017-09-05 18:54
I will also report a failure to update using Cura 2.6.2 with Win7Pro 64bit. 

Downgrade to Cura 2.5 and it works.

Have not tried Cura 2.7 yet, will attempt after this run of parts are finished.

**Comment by Equinox1st** [comment] 2017-09-05 22:37
2.7 works fine

**Comment by TAGood827** [comment] 2017-09-11 12:56
Just tried update with Cura 2.7 and it did work.

**Closed** 2017-09-12 11:44 UTC
Labels: bug
