### ISSUE TITLE
gcode

### ISSUE THREAD

**Issue by ve3sqb** [Ultimaker/Cura#2951] opened 2017-12-10 10:56 UTC
can not open edit gcode in 3.1 stable

**Comment by ChrisTerBeke** [comment] 2017-12-10 19:01
Can you be more specific? Which menu are you trying to open?

**Comment by ve3sqb** [comment] 2017-12-11 07:37
In the extensions tab,
post processing, Modify g-code.

**Comment by fieldOfView** [comment] 2017-12-11 08:08
As a workaround, can you try using the cursor keys and enter to navigate the menu?

**Comment by ve3sqb** [comment] 2017-12-11 13:04
cursor keys work

**Comment by Ghostkeeper** [comment] 2017-12-30 16:51
It looks like this is a duplicate of https://github.com/Ultimaker/Cura/issues/1940

**Closed by Ghostkeeper** 2017-12-30 16:51 UTC
Labels: needsinfo
