### ISSUE TITLE
Slicing failed (again)

### ISSUE THREAD

**Issue by iandavys** [Ultimaker/Cura#12495] opened 2022-06-10 21:07 UTC
### Application Version

5.0.0

### Platform

windows 11

### Printer

Flsun Q5

### Reproduction steps

Just a lot of hocks.
when i did the slicing it just failed.
if i removed all my settings it was fine.
went back to a previeverious vertion of cura with the new settings and again it was fine.
version 5 seams to have this glitch in it each time.
Hope you can help, or put it right.
Thank you,

from Ian

### Actual results

it just does not what to slice!

### Expected results

[Hooks.zip](https://github.com/Ultimaker/Cura/files/8882259/Hooks.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

This is the second time i have sent in a slicing error.
I have done loads, this like this before, with no issues, in the oldered Curas!
What has happed?
Hope you can help.

From Ian

**Comment by Asterchades** [comment] 2022-06-11 07:13
Duplicate of #12489.

PS Please don't check the "Log file" checkbox if you haven't actually included a log. The checkbox doesn't automatically upload anything - it simply to indicate whether you've done so yourself or not.

**Closed by Asterchades** 2022-06-11 07:13 UTC
Labels: Type: Bug
