### ISSUE TITLE
failed to splice

### ISSUE THREAD

**Issue by lucario7007** [Ultimaker/Cura#14645] opened 2023-02-23 04:50 UTC
### Application Version

5.2.2

### Platform

Windows 11

### Printer

custom

### Reproduction steps

1. added file
2. increased infill line multiplier from 1 to 2
3. tried to splice failed to splice 15 times

### Actual results

splice continued to fail

### Expected results

no fail to splice i have done this on it for a while just needed to make it a bit tougher so it wouldn't break as easily and now it won't work

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CFFFP_Barrel_Cup_wHandle.zip](https://github.com/Ultimaker/Cura/files/10810332/CFFFP_Barrel_Cup_wHandle.zip)

**Comment by MariMakes** [comment] 2023-02-23 13:32
Hey @lucario7007,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

It seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13643
I can slice your file in the new Cura 5.3 Beta that contains the fix for this. 
![image](https://user-images.githubusercontent.com/40423138/220921141-ec47f4af-c72d-4a80-a250-bc3ab7178451.png)


You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0-beta.1
Good luck! I'll close the issue.

**Closed by MariMakes** 2023-02-23 13:32 UTC
Labels: Type: Bug, Status: Triage
