### ISSUE TITLE
Speed settings ignored extruder one 

### ISSUE THREAD

**Issue by woofoo33** [Ultimaker/Cura#2876] opened 2017-11-29 11:06 UTC
Cura 3.0.4 
Ultimaker 3 on the latest UK version,

The issue or setting problem is I set the speed to say 50mms after the 1st layer the head moves so fast it under extrudes, Yes I know the 1st layer is always slower as I see this in the settings, 

put the exact same settings into extruder 2 it work correct every time ....

I have had this problem for a while its as if EX 1 has a built in default speed after the 1st layer

**Comment by Ghostkeeper** [comment] 2017-12-13 01:26
I can't reproduce this bug. If I reduce the speed on the first extruder it prints slower (or at least the `F` parameter of the moves is lower).

Perhaps you could upload a project file where you changed the speed settings and expect it to appear in the g-code? Those project files contain all your settings so we can more easily reproduce it.

**Comment by woofoo33** [comment] 2017-12-13 08:55
just to add the the filament used was 
Nylon or flex I was having the issues with but on in Extuder 1 , 

Ill try to re create

**Comment by ianpaschal** [comment] 2018-03-26 11:23
Needs more info; never got it; closing.

**Closed by ianpaschal** 2018-03-26 11:23 UTC
Labels: Status: Needs Info
