### ISSUE TITLE
profile error

### ISSUE THREAD

**Issue by rponte-BR** [Ultimaker/Cura#15935] opened 2023-06-27 22:21 UTC
### Application Version

5.4.0

### Operating System

windows 11 pro

### Printer

ender 3 S1 plus

### Reproduction steps

import profile

### Actual results

profiles are not loading even installed. Error seen in generic profile.

### Expected results

see all generic profiles

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

error

**Comment by zcohenld** [comment] 2023-06-28 11:55
By the way, this is the same for the Ender 3 S1 regular printer as well as the Plus.

**Comment by MariMakes** [comment] 2023-07-05 15:28
Hey @zcohenld,

Thanks for your report 👍

Could this be a duplicate of https://github.com/Ultimaker/Cura/issues/15771?
This should be resolved in the 5.4 stable release, you can download the Cura version with the fix here: https://github.com/Ultimaker/Cura/releases/tag/5.4.0

Could you let us know if this is a duplicate?
If that's not it, I'll need a little bit more information from you.
Could you perhaps share some screenshots of what you are seeing?

**Closed** 2023-07-20 00:20 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage, PreRelease :bug:
