### ISSUE TITLE
issue infill mesh - save

### ISSUE THREAD

**Issue by pektrus** [Ultimaker/Cura#5236] opened 2019-01-28 15:31 UTC
Hi guys
i have another issue … when i finish to do multiple infill mesh in other parts on the model , i go saving but when I open the file again, the model is completely diferente …its complete diferente because when i open again, i dont know what happen but the model that i used to divide the diferentes parts to do infill mesh, its now part of the model … so when i open the file  and this model joint to the another model and i dont want that. I just use the model to separate parts for diferentes infill meshs but when i save and open again the file … that model joint to the other model
i dont know what to do …
Thanks ( i use the 3.6 upadte)

**Comment by Ghostkeeper** [comment] 2019-01-29 15:32
Duplicate of #5228.

**Closed by Ghostkeeper** 2019-01-29 15:32 UTC
Labels: Status: Needs Info
