### ISSUE TITLE
slice preview 

### ISSUE THREAD

**Issue by Solotov1muhammad** [Ultimaker/Cura#19505] opened 2024-08-08 00:24 UTC
### Cura Version

5.8.0

### Operating System

windows 11

### Printer

ender3 v2 neo

### Reproduction steps

1. when i do slice i can't se preview video .

### Actual results

1. when i do slice i can't se preview video .

### Expected results

the preview play button disappeared 

### Add your .zip and screenshots here ⬇️

![צילום מסך 2024-08-08 032404](https://github.com/user-attachments/assets/7b666ed8-80a3-4d4b-975f-c5ab6e65b4d4)

**Comment by GregValiant** [comment] 2024-08-08 10:40
Thanks for the report.
The "Preview Video" is not available when Cura is in "Compatibility Mode".  If you have an OpenGL version lower than 4.1 Cura will automatically put itself into "Compatibility Mode".

You can try going to "Preferences | Configure Cura" and on the "General" tab uncheck "Force Layer View Compatibility Mode" and in some cases that would work.  If Cura cannot access the graphics system OpenGL or the system doesn't support OpenGL 4.1 then Cura will stay in Compatibility Mode regardless of the value of that setting.
Cura will not work at all if the OpenGL version is less than 2.2(?).
![image](https://github.com/user-attachments/assets/a3a31785-ae6c-482a-a826-168d4abb3cf6)

If you cannot get Cura out of Compatibility Mode you will have to take a look at your graphics drivers.  Some systems have both a "Standard" graphic system (often an onboard Intel system) and an optional (more advanced) graphic system.  You may have to go into the graphics controller and set it up so Cura can use the more advanced graphics card.

Right now I can't tell if this is a bug, or expected behavior due to your hardware.

**Comment by Solotov1muhammad** [comment] 2024-08-08 17:50
Thank you its work

**Comment by GregValiant** [comment] 2024-08-08 18:17
Good.  I'll go ahead and close this then.

**Closed by GregValiant** 2024-08-08 18:17 UTC
Labels: Type: Discussion, Status: Under Investigation
