### ISSUE TITLE
z_movement while printig

### ISSUE THREAD

**Issue by robschii** [Ultimaker/Cura#5798] opened 2019-05-28 14:53 UTC
with the new version the z-movement while printig is so slow....

in 4.0 it was fast enough to prevent stringing

**Application Version**
4,1

**Platform**
win10
**Printer**
mkv4.1

**Comment by Ghostkeeper** [comment] 2019-05-28 16:51
Duplicate of https://github.com/Ultimaker/Cura/issues/5753

**Closed by Ghostkeeper** 2019-05-28 16:51 UTC
