### ISSUE TITLE
The multiply feature does not work.  Hangs in the "Placing Objects" dialog.  

### ISSUE THREAD

**Issue by liaviator** [Ultimaker/Cura#10809] opened 2021-11-12 04:11 UTC
### Application Version

4.12.0

### Platform

MacOS

### Printer

Ultimaker 3

### Reproduction steps

1. Place object on build plate in Cura
2. Right click and select Multiply
3. Change the number of items
4. Press enter.
![image](https://user-images.githubusercontent.com/50585683/141408043-b0351a37-dc9a-447d-b7d5-62d5b15086c8.png)

### Actual results

![image](https://user-images.githubusercontent.com/50585683/141408062-a5d7f499-82d4-48d0-a8d1-6e58b7caed37.png)

### Expected results

The object should be multiplied on the build plate.  This used to work fine.  

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No additional files.

**Comment by fvrmr** [comment] 2021-11-12 08:14
Hi @liaviator thank you for your report. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/10249 
I will close this and mark it as a duplicate.

**Closed by fvrmr** 2021-11-12 08:14 UTC
Labels: Type: Bug
