### ISSUE TITLE
Blank layer of Prime tower

### ISSUE THREAD

**Issue by jamteang-cubicon** [Ultimaker/Cura#11347] opened 2022-01-27 00:55 UTC
### Application Version

4.13.0

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

When extruder1 is set as the main material and extruder2 is set as support to use the prime tower, in the layer where only Extruder1 is used, only the Prime Tower and Extruder1 are used.

### Actual results

In the Prime Tower, which was continuously connected to Extruder2, Extruder2 is not output from the corresponding layer, so an empty layer is created.

### Expected results

In the layer where Extruder2 is used again, the Prime Tower prints Extruder2 in an empty space, which causes final printing failure.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[UMS5_checker_cone_B.zip](https://github.com/Ultimaker/Cura/files/7946653/UMS5_checker_cone_B.zip)
Extruder2 was not created up to layer 61 of the Prime Tower, and from layer 62 it was suddenly created on the empty space.

**Comment by fvrmr** [comment] 2022-01-27 13:44
Hi @jamteang-cubicon thank you for your report. 
This is intended behaviour of the prime tower. And this is a duplicate of https://github.com/Ultimaker/Cura/issues/6909
You can read here why this is the intended behaviour: https://github.com/Ultimaker/Cura/issues/6909#issuecomment-573544929

I will close this issue since it is a duplicate.

**Closed by fvrmr** 2022-01-27 13:44 UTC
Labels: Type: Bug
