### ISSUE TITLE
Wall Thickness Miss-Calculates passes for 0.8 nozzle

### ISSUE THREAD

**Issue by BloodBlight** [Ultimaker/Cura#3231] opened 2018-02-04 23:06 UTC
**Application Version**
3.1.0 (3.0.4 is NOT affected)

**Platform**
Debian 9.2

**Steps to Reproduce**
I changed my nozzle to a 0.8MM, changes my printer settings, but is it still pathing and extruding for a 0.4MM.

Wall count calculations also impacted (so if it is set for 1.6MM, it calculated for four walls rather than two).  It seems like the setting is not being completely honored when set manually on an original UM.  The change does show in the amount of filament used, so the setting is being processed to some extent.

**Comment by Thorinair** [comment] 2018-02-05 08:24
Could this possibly be related to #3197 ?

**Comment by Ghostkeeper** [comment] 2018-02-27 12:54
I'm getting the inverse of this.

Reproduce steps:
1. Add Ultimaker Original.
2. Load a model.
3. Go into Machine Settings.
4. Under the extruder, change Nozzle Size to 0.8mm. Close dialogue and let it slice.

Now this is what happens for me:
* The model's lines become much thicker.
* The line width setting remains the same.

**Comment by Ghostkeeper** [comment] 2018-02-27 12:56
Ah but it seems that my bug is only an update bug.

**Comment by ianpaschal** [comment] 2018-07-31 07:41
Duplicate of #3338 but fixed.

**Closed by ianpaschal** 2018-07-31 07:41 UTC
Labels: Category: Engine, Category: Settings, Status: In Progress, Type: Bug
