### ISSUE TITLE
[4.2.1] Scale input fields for amount and percentage are switched for Y and Z axis

### ISSUE THREAD

**Issue by spirritus** [Ultimaker/Cura#6238] opened 2019-08-21 22:39 UTC
When you scale an object and activate non uniform scaling:
Putting an amount in the X value changes the percentage at X. Yes, that is was is expected.

However, when you change the amount for Y the percentage for Z changes, and when you put an amount into Z the percentage for Y changes.

I guess this is a confusion of the fields.

**Comment by Ghostkeeper** [comment] 2019-08-22 07:55
Duplicate of https://github.com/Ultimaker/Cura/issues/4136.

It only occurs when combining rotation and scaling non-uniformly and only concerns the percentage fields.

**Closed by Ghostkeeper** 2019-08-22 07:55 UTC
Labels: Type: Bug
