### ISSUE TITLE
Unused support material

### ISSUE THREAD

**Issue by fabus1989** [Ultimaker/Cura#2941] opened 2017-12-08 19:18 UTC
Hello, 

I've testing cura 3.1.0 and it generates not needed support (screenshot attached).

Please let me know if any further information is needed.

Best regards
Fabian
![2017-12-08_20h12_26](https://user-images.githubusercontent.com/32595854/33781378-ab59d0d8-dc54-11e7-9e8b-360d4260bc5c.png)

**Comment by ChrisTerBeke** [comment] 2017-12-08 19:19
Might be a bug in the engine. Can you upload a project file with this model and the settings so we can reproduce it?

**Comment by fabus1989** [comment] 2017-12-08 19:28
It's not possible here. Maybe you will share your email?

**Comment by fabus1989** [comment] 2017-12-08 19:30
Sorry I forgot about cloud services.

Here is the link to model: [https://1drv.ms/u/s!AnrstGN8arUcj89d4GjluhtoyJzVMA](url)

**Comment by ChrisRiddell** [comment] 2017-12-08 20:16
Go to custom settings and turn off Support Towers, I had the same thing.

**Comment by fabus1989** [comment] 2017-12-08 20:19
Thanks for workaround :)

**Comment by nallath** [comment] 2017-12-15 12:38
Is your horizontal expansion of the support set to non zero?

**Comment by Ghostkeeper** [comment] 2017-12-20 10:19
This is a duplicate of https://github.com/Ultimaker/CuraEngine/issues/544.

**Closed by Ghostkeeper** 2017-12-20 10:19 UTC

**Comment by alekseisasin** [comment] 2018-01-25 16:03
Hello @fabus1989, Sorry for long time waiting reply, for now this issue can be solved if you will set setting
¨Support Horizontal Expansion¨ value to 0.
