### ISSUE TITLE
Cura hogs serial peripherals

### ISSUE THREAD

**Issue by mranvick** [Ultimaker/Cura#8242] opened 2020-08-26 09:03 UTC
**Application version**
4.7.0 and 4.6.0 (no other version tested)

**Platform**
MacOS Catalina 10.15.6

**Printer**
Not Relevant (Ender 3 Pro)

**Reproduction steps**
This issue concerns the fact that Cura is hogging any serial peripherial that I plug into my computer. More explicitely, I am using for different purposes an [Adafruit Trinket M0](https://learn.adafruit.com/adafruit-trinket-m0-circuitpython-arduino/overview) and an [USB to UART Module](https://www.amazon.fr/WINGONEER-CP2104-convertisseur-Module-compatible/dp/B01CYBHM26/). Both appears under ```/dev/tty.XXX```(where ```XXX``` is their respective name).

When plugged in, I can interact with either of these peripherals through means such as ```screen``` (built-in terminal tool), or **Python Serial** (Python library). However, when I launch Cura, I always get the ```resource busy``` error message and I cannot use my serial peripherals any more. Unplugging and re-plugging of the peripheral does not solve the problem. The resource is free anew only when I close Cura.

1. Plug in a serial peripheral (registered under ```/dev/tty.Peripheral_Name```)
2. Launch Cura
3. Try to open a serial link with e.g. ```screen /dev/tty/Peripheral_Name BAUD_RATE```

**Screenshot(s)**
Not Relevant.

**Actual results**
The ```screen```command returns a ```resource busy``` error message followed by a ```could not find PTY``` message.

**Expected results**
The serial peripheral should have been usable as when Cura is not launched.

**Project file**
None.

**Log file**
Included in **Additional information** (below), there seems to be an issue with ```USBPrinting.AutoDetectBaudJob```.

**Additional information**
[cura.log](https://github.com/Ultimaker/Cura/files/5128716/cura.log)

**Comment by Ghostkeeper** [comment] 2020-08-28 13:21
Duplicate of https://github.com/Ultimaker/Cura/issues/5207.

**Closed by Ghostkeeper** 2020-08-28 13:21 UTC
