### ISSUE TITLE
(4.9.1 + 5.0.0) OBJ file import bug: Unable to Open File

### ISSUE THREAD

**Issue by denis-fisseler** [Ultimaker/Cura#12130] opened 2022-05-07 10:37 UTC
### Application Version

4.9.1 + 5.0.0

### Platform

Windows 10

### Printer

Ultimaker 3

### Reproduction steps

Try to open any obj model file which contains special characters like german umlauts and which is not encoded in utf-8 but in ANSI, e.g. codepage Windows-1252.

### Actual results

Cura displays the message:
Unable to Open File
Failed to load [Filename]. The file could be corrupt, inaccessible or it did not contain any models.

### Expected results

Cura opens the file and loads the model.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Example obj file: [box.zip](https://github.com/Ultimaker/Cura/files/8644918/box.zip)

**Comment by MariskaMaas** [comment] 2022-05-24 16:33
Hey @denis-fisseler,

Thanks for reporting this, I can reproduce it. 

This indeed seems to be related to the Umlaut.
This issue seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12239.
I'm closing this issue in favor of that one, you can follow the progress on resolving this issue over there.

**Closed by MariskaMaas** 2022-05-24 16:33 UTC
Labels: Type: Bug
