### ISSUE TITLE
UMO platform image turned black after loading .stl

### ISSUE THREAD

**Issue by Xisle** [Ultimaker/Cura#497] opened 2015-10-20 15:51 UTC
Cura 15.09.91
OS X 10.9.5

I loaded an .stl and got this..

![screen shot 2015-10-20 at 7 49 03 am](https://cloud.githubusercontent.com/assets/12257213/10612905/5e6a37de-76ff-11e5-8612-a27cae6164e0.png)

**Comment by Ghostkeeper** [comment] 2015-10-21 07:50
Looks like the normals got erased / corrupt.

**Comment by Ghostkeeper** [comment] 2015-10-21 07:53
I can't find the results of @TMHogenhout's OSX test cases, but in the others this error hasn't occurred. It will be difficult to reproduce this.

**Comment by TMHogenhout** [comment] 2015-10-21 08:39
Well actually I have seen this many times, in another form though. I didn't put it in the test report because it wasn't within the scope of the test (which was only targeted at the stability of Cura). It doesn't happen on my computer (testing from source), but I think I can reproduce it on one of the test-computers (to be continued..)

**Comment by fieldOfView** [comment] 2016-11-09 16:07
Issue can be closed. Was fixed by making sure there is always a texture, even if the machine definition does not specify one.

**Closed** 2016-11-09 16:36 UTC
Labels: bug
