### ISSUE TITLE
Print settings can't scroll to reach create, update, discard profile options

### ISSUE THREAD

**Issue by furman3000** [Ultimaker/Cura#13550] opened 2022-10-13 01:58 UTC
### Application Version

5.1.1

### Platform

Windows 10

### Printer

Ender-3 

### Reproduction steps

1. Add many 10? custom profiles
2. Click Printer settings, Profile drop down, shows Default and Custom profiles, then sub-box with Create, Update, Discard options.

However with many Custom profiles we can't navigate to see the sub-box because the sub-box extends past the displayable window.
A fix would be to have the existing vertical scroll bar be extended to also scroll the sub-box.

### Actual results

1. Can't get to sub-box which has Create, Update, Discard profile options because it is past the displayable window
 

### Expected results

1. To be able to see and click on Create, Update, Discard profile options

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

NA

**Comment by MariMakes** [comment] 2022-10-13 07:45
Hey @furman3000,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for this interesting report. 

I have three questions for you. 
1. Do you have a picture for us how your window looks like? 
2. Can you share why you have so many profiles? 
3. What is the reason for you to create a new profile?

**Comment by furman3000** [comment] 2022-10-27 15:21
1) I don’t have a picture.

2) Why I have lots of profiles: Trying CHEP’s set of custom fast printing profiles. He has fast ones for 0.12, 0.2, 0.28, and TPU. He also has hyper-fast and Beta. 

My laptop landscape height is limited, so I need to change rotation to portrait. Using portrait allows increasing the Cura window height to ‘reach’ the profile options to Create, Update, Discard. 

3) Why I want to create new profiles: I am tweaking CHEP’s profiles to print TPU. 

Thank you, Jeff

**Comment by furman3000** [comment] 2022-10-29 01:13
Yes, That is exactly the same issue!  As I mentioned the only way to drill down to ‘reach’ those options is to expand my window width. But since landscape laptop screen is size limited, I need to switch to portrait mode to able to expand the window. Thanks in advance for bringing this up with the team.  Jeff

**Comment by furman3000** [comment] 2022-10-29 01:14
Sorry, I meant expand window height to reach those options

**Comment by MariMakes** [comment] 2022-10-31 13:38
This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13668
Since we have multiple reports on the issue, I'll discuss it with the team. 
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/13668

**Closed by MariMakes** 2022-10-31 13:38 UTC
Labels: Type: Bug, Status: Triage
