### ISSUE TITLE
Anti warping tabs

### ISSUE THREAD

**Issue by ChrisLMink** [Ultimaker/Cura#15888] opened 2023-06-24 00:31 UTC
### Cura Version

5.4.0

### Operating System

win 10

### Printer

creality ender 5 plus

### Name abnormal settings

anti warping tabs

### Describe your model

Full scale R2D2 body part

### Add your .zip here ⬇️

[Mainbody_2_a.zip](https://github.com/Ultimaker/Cura/files/11853967/Mainbody_2_a.zip)

**Comment by MariMakes** [comment] 2023-07-17 14:58
Hey @ChrisLMink,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I recognize this issue. 🔎
This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/15836, where using custom supports would result in a slicing crash. 

It's resolved in the 5.4 stable release, you can download the Cura version with the fix here: https://github.com/Ultimaker/Cura/releases/tag/5.4.0
I'll close this issue since it's a duplicate and resolved. 

Thanks again, and please let us know if you run into any other issues 💪

**Closed by MariMakes** 2023-07-17 14:58 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:
