### ISSUE TITLE
Tree Support trying to build in midair

### ISSUE THREAD

**Issue by pfjason** [Ultimaker/Cura#3374] opened 2018-02-21 15:02 UTC
I've noticed that when using tree support and support placement "Touching Buildplate" that occasionally I will see tree supports built out in midair, for instance on the below benchy.

![image](https://user-images.githubusercontent.com/16055757/36486942-bd4bc43a-16ed-11e8-9bbb-dccea8e32e15.png)

![image](https://user-images.githubusercontent.com/16055757/36486894-a8584f30-16ed-11e8-9b0d-9e6fdd343e25.png)

**Application Version**
3.2.1

**Platform**
Windows 10

**Qt**
Version from ultimaker's site

**PyQt**
Version from Ultimaker''s site

**Display Driver**
AMD Radeon drivers 23.20.15002.11

**Steps to Reproduce**
Try to slice a model requiring supports, and use Tree supports. uncheck "Generate Support" but leave "Tree supports" checked. set Support Placement to "Touching Buildplate".  My example above is a 125% scale benchy.

**Actual Results**
Cura may generate tree supports that start in midair, which would be impossible to print. 

**Expected results**
Cura should always place supports touching the buildplate or the model, depending on the settings, and never place supports in midair.

**Additional Information**
NA

**Comment by ChrisRiddell** [comment] 2018-02-21 23:27
Duplicate of #3249

**Closed** 2018-03-02 21:57 UTC
Labels: Status: Duplicate
