### ISSUE TITLE
Non uniform scaling controls not connected to proper axis after rotation

### ISSUE THREAD

**Issue by MarekPikula** [Ultimaker/Cura#7778] opened 2020-05-17 12:41 UTC
**Application version**
Noticed on 4.5.0 and higher, but probably goes back to earlier versions as well.

**Platform**
Fedora 32 Workstation, official AppImage.

**Printer**
Doesn't matter.

**Reproduction steps**
1. Load a model.
3. Rotate a model 90° in any direction (for example Z).
2. Go to _Scale_.
3. Uncheck _Uniform scaling_.
4. Set X scale to 110%.

**Screenshot(s)**

Before:
![Zrzut ekranu z 2020-05-17 14-36-26](https://user-images.githubusercontent.com/1504981/82146640-02cac100-984c-11ea-88fc-c06eadb4e504.png)

After:
![Zrzut ekranu z 2020-05-17 14-37-27](https://user-images.githubusercontent.com/1504981/82146644-0a8a6580-984c-11ea-86d7-3010c95c0ce2.png)

**Actual results**
Y scale control changes to 110% as well.

**Expected results**
Object rescales in X axis and only X axis scale control is at 110%.

**Project file**
Not applicable.

**Log file**
Not applicable.

**Additional information**
When you apply scale by hand in _mm_ control it scales ok, but percentage controls are mixed up.

Similar bug #7768 has been already reported, but didn't use correct reporting scheme.

**Comment by nallath** [comment] 2020-05-18 08:39
Duplicate of https://github.com/Ultimaker/Cura/issues/4136

**Closed by nallath** 2020-05-18 08:39 UTC
Labels: Type: Bug
