### ISSUE TITLE
[4.5] Machine settings window is not high enough & not resizable (mac)

### ISSUE THREAD

**Issue by jlsjonas** [Ultimaker/Cura#7376] opened 2020-03-31 13:46 UTC
**Application version**
(The version of the application this issue occurs with.)
4.5 (downloaded 15min before issue time)

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)
Mac os X 10.14.6

**Printer**
(Which printer was selected in Cura?)
Vertex Delta K8800

**Reproduction steps**
1. open machine settings

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
![image](https://user-images.githubusercontent.com/932193/78033180-53eb2800-7366-11ea-870b-868d72ec03bf.png)
Extruder tab is fine:  
![image](https://user-images.githubusercontent.com/932193/78033277-7b41f500-7366-11ea-8e23-85ab19cd89a0.png)

**Actual results**
(What happens after the above steps have been followed.)
Window doesn't have enough space left to properly display the start & end G-code textareas, they are fine on the Extruder 1 tab (since there's enough extra space there)

**Expected results**
(What should happen after the above steps have been followed.)
Readable textareas, more than a single line

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)
N/A

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)
N/A

**Additional information**
(Extra information relevant to the issue.)
Closely related to comments added in #7300, decided to make it a separate issue as the core issue reported there is the text offsetting of the input boxes, not the Start/End G-code not being displayed big enough.

**Comment by rburema** [comment] 2020-03-31 17:03
Duplicate of #7306 

_Should_ be fixed in the upcoming version 4.6, if not, please open a new issue.

**Closed by rburema** 2020-03-31 17:03 UTC
Labels: Status: Duplicate, Type: Bug
