### ISSUE TITLE
Touchpad-friendly movement/rotation

### ISSUE THREAD

**Issue by leoheck** [Ultimaker/Cura#8916] opened 2020-12-09 14:42 UTC
Currently is pretty hard to work with a trackpad especially when rotating the area.
Maybe it is pretty much hard to do it with a keyboard as well due to the lack of shortcuts.

Do you think it is possible to add something to improve this?
An example of that is [Freecad touchpad mode](https://wiki.freecadweb.org/Template:Touchpad_Navigation)

**Comment by Ghostkeeper** [comment] 2020-12-18 11:56
Duplicate of https://github.com/Ultimaker/Cura/issues/2515.

**Closed by Ghostkeeper** 2020-12-18 11:56 UTC
Labels: Type: New Feature
