### ISSUE TITLE
Control angle rotation by typing (Cura 4.1)

### ISSUE THREAD

**Issue by leoheck** [Ultimaker/Cura#6013] opened 2019-07-15 19:28 UTC
This is kinda bug report (but you might consider it as a feature as well)

> I am using Cura 4.1

So, the issue is that the `Move (T)` and `Scale (S)` have text input fields to set values manually. However, the `Rotate (R)` does not have such a thing. The test input field is missing for setting angles. It is always preferable to have precise control to test and repeat processes.

**Comment by fieldOfView** [comment] 2019-07-15 20:14
Duplicate of https://github.com/Ultimaker/Cura/issues/2779

**Closed** 2019-07-16 07:16 UTC
Labels: Type: Bug
