### ISSUE TITLE
echaec decoupage

### ISSUE THREAD

**Issue by laeti3d** [Ultimaker/Cura#17478] opened 2023-11-29 16:34 UTC
### Cura Version

5.6.0

### Operating System

windows

### Printer

dagoma magis

### Name abnormal settings

je ne sais pas

### Describe your model

personnage 

### Add your .zip here ⬇️

[DM_dragon.zip](https://github.com/Ultimaker/Cura/files/13503165/DM_dragon.zip)

**Comment by MariMakes** [comment] 2024-01-18 15:35
Hi @laeti3d,

Quick update from our side 👋
We are introducing a new tool to analyze slicing crashes like the one you reported. 💪

Even with the changes we made in the latest versions of Cura we still see that your model crashes. 🫤 But we have added your project file to our analyzing tool and found there were at least 5 crashes that were similar to yours, which helps us to narrow down what the cause is of your crash so we can resolve this for you and others.
Hopefully, we can find a solution soon 🤞

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/17679

**Closed by MariMakes** 2024-01-18 15:35 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:
