### ISSUE TITLE
Some input fields (like Infill Density) react "funny" to input

### ISSUE THREAD

**Issue by Linkenelis** [Ultimaker/Cura#14997] opened 2023-03-22 13:08 UTC
### Application Version

5.3.0

### Platform

Windows 11

### Printer

Saphire Plus

### Reproduction steps

Infill Density = 30.0
cursor before the 3 and del, deletes the 3 and exits field
cursor between 3 and 0 then Backspace, deletes 3 and exits field
Select all and try to type 20, exits field after the 2

Deleting and editing the other characters is fine, it's just the first one

### Actual results

it exits field, making typing an input difficult

### Expected results

normal behaviour would be to stay in the field after typing a key (exept tab and Enter keys)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/58143885/226913324-0583a452-7588-450b-829c-21f11b209267.png)
![image](https://user-images.githubusercontent.com/58143885/226913435-ea7f68b5-d533-40ab-8702-096de65e4195.png)
Backspace
![image](https://user-images.githubusercontent.com/58143885/226913534-527c378c-4e5d-4061-839d-c7259375d9b8.png)
cannot type a 2 into the field

**Comment by MariMakes** [comment] 2023-04-03 14:48
Hey @Linkenelis,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12949
We have a ticket on our backlog with the intent to improve this behavior.
I'll raise it again with the team. 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12949
Thanks again for the report 💪

**Closed by MariMakes** 2023-04-03 14:48 UTC
Labels: Type: Bug, Status: Triage
