### ISSUE TITLE
(5.2.2) Slice fails for tall object at the origin

### ISSUE THREAD

**Issue by bikin-brett** [Ultimaker/Cura#15559] opened 2023-05-18 21:51 UTC
### Application Version

5.2.2

### Platform

Windows 11

### Printer

Creality Ender-3 / Ender-3 v2

### Reproduction steps

1. I cleared the build plate
2. I loaded in a rather tall STL
3. I clicked "Slice"

### Actual results

The slicing process failed with "an unexpected error." :/

### Expected results

I should have gotten a G-code preview, right?

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Data files:

[transition-seg1.3mf.zip](https://github.com/Ultimaker/Cura/files/11511762/transition-seg1.3mf.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/11511784/cura.log)
[cura.log](https://github.com/Ultimaker/Cura/files/11511784/cura.log)

This happens when the model is at the origin:

![problemm](https://github.com/Ultimaker/Cura/assets/73145297/709992c4-e368-4414-8479-232cd0ef4f17)

Interestingly, the bug doesn't occur if I simply scoot the model away from the origin, specifically in the negative y direction. However, the bug still does occur if the y-value is too close to zero (I think):

![not-a-problemm](https://github.com/Ultimaker/Cura/assets/73145297/7a71d2a9-3c22-4573-bd3c-ad144860df6e)

**Comment by GregValiant** [comment] 2023-05-19 00:37
Thanks for the report and the file.
This is a duplicate of several other bug reports.  Yes, the main workaround is to move and/or rotate the model.  I suspect that works because Cura always slices from the same start point and maybe the slightly different "attack angle" makes a difference.

I'm going to mark this as a duplicate and go ahead and close it as the Cura team has a lot of examples of this behavior.  I hope you understand.

**Closed by GregValiant** 2023-05-19 00:37 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error :collision:
