### ISSUE TITLE
Seam alignment does not work

### ISSUE THREAD

**Issue by PunCala** [Ultimaker/Cura#15716] opened 2023-06-11 09:54 UTC
### Application Version

5.3.1

### Operating System

Windows 10

### Printer

FLSun V400

### Reproduction steps

1. Put any settings on seam alignment, and check that it seems fine in preview
2. When printed, the seams are all over the part. The part in question is a roughly  half moon shaped, so curved on one side and corners on the other. The goal is to get the seams aligned in the corners.

### Actual results

The seams are printed all over the part, especially on the curved side that was supposed to be completely without seams

### Expected results

Expected seams to be in the exact places (corners) where the preview showed them to be.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Try printing this, preferably on a delta printer, and you will see that the seams go all over the part.
![seams](https://github.com/Ultimaker/Cura/assets/135166060/f428d0ce-8ea8-469a-be7d-2d501cc44121)
Here is the stl file: https://www.dropbox.com/s/q1iu3wn9u10cchx/Oikea%20lesti%201b.stl?dl=0

Example seam settings: 
Z seam alignment: User specified
Z seam position: Back right
Seam corner preference: Smart Hiding
Z seam relative: Yes

Just try to hide the seams in the corners and see what happens.

**Comment by MariMakes** [comment] 2023-07-17 12:49
Hey @PunCala,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I recognize this issue. 🔎
This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/14811 where zits would appear on curved surfaces for Klipper Printers, like FLSUN 400.

It's resolved in the 5.4 stable release, you can download the Cura version with the fix here: https://github.com/Ultimaker/Cura/releases/tag/5.4.0
I'll close this issue since it's a duplicate and resolved. 

Thanks again, and please let us know if you run into any other issues 💪

**Closed by MariMakes** 2023-07-17 12:49 UTC
Labels: Type: Bug, Status: Triage
