### ISSUE TITLE
cura2.6.0 beta!!!    print head size, print one at a time 

### ISSUE THREAD

**Issue by mitchy2233** [Ultimaker/Cura#1874] opened 2017-05-24 08:17 UTC
no matter how many times i try and change the print head size it will not save my changes!! it did it one time but will not do it again!! ive restarted my computer many times!!  also i sure don't like how you can only fit one object on the bed with the print at one time on!! i use cura 15.06 or what ever and was able to fit 4 of the exact same item on the bed with the print at one time!! why did you change this?? or what is going on???  even when i had the correct "head size" i was still unable to print the exact same items!!  ps ive never had a crash before (extruder crash) why did you change such a good thing? lol

**Comment by Ghostkeeper** [comment] 2017-05-24 13:49
I tried this, using the following steps:
* Add a Custom FDM Printer.
* Change Y Min to 15 (up from 10).
* Restart Cura.
* Open up the Machine Settings again.

Now the Y Min still says 15. Seems to work fine? What steps did you take to modify the print head size and when did it go wrong?

**Comment by Deepfriedchril** [comment] 2017-05-24 17:25
I've also had problems with 2.6.0 losing my machine settings after closing Cura and not allowing me to change them after reopening Cura. Dual extruders get removed and forces single.
I've resorted to creating a new profile every time I want to slice something. This gets fairly annoying with dual extruders that also need configuring.

**Comment by fieldOfView** [comment] 2017-05-24 20:08
When this happens, please zip up your entire configuration folder and post it somewhere so we can have a look. Note: the location has changed for Cura 2.6

**Comment by fieldOfView** [comment] 2017-05-25 21:33
Could you check if this also happens if you add a new printer, and change the settings of that printer? I think the issue is with upgraded printers

**Comment by Deepfriedchril** [comment] 2017-05-25 22:24
I took a look in the config folder and deleted everything in there.
Haven't experienced any issues since my last post. I've been able to change the printer and extruder profiles freely.

**Comment by BagelOrb** [comment] 2017-07-21 12:38
So you mean the bug issolved..? :)

**Closed by BagelOrb** 2017-07-21 12:38 UTC
