### ISSUE TITLE
Horizontal expansion and initial layer horizontal expansion fields swapped

### ISSUE THREAD

**Issue by dsdanielko** [Ultimaker/Cura#12772] opened 2022-07-15 21:35 UTC
### Application Version

5.0.1 beta

### Platform

Windows 10

### Printer

Creality Ender 3 Pro

### Reproduction steps

Changed horizontal expansion value -> Slice -> Preview
Changed initial horizontal expansion value -> Slice -> Preview

### Actual results

Changed horizontal expansion value -> Slice -> Preview and saved gcode behaves as if initial horizontal expansion value was changed
Changed initial horizontal expansion value -> Slice -> Preview and saved gcode behaves as if horizontal expansion value was changed

### Expected results

Changed horizontal expansion value -> Slice -> Preview and saved gcode behaves as if horizontal expansion value was changed
Changed initial horizontal expansion value -> Slice -> Preview and saved gcode behaves as if initial horizontal expansion value was changed

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE3PRO_ceiling_door_hook.zip](https://github.com/Ultimaker/Cura/files/9124171/CE3PRO_ceiling_door_hook.zip)
![image](https://user-images.githubusercontent.com/1181559/179314066-4ee6bac0-e2f1-4725-bcca-846299c4efc7.png)
![image](https://user-images.githubusercontent.com/1181559/179314110-0a67bd22-e8e1-4c16-bf0a-866854645a2f.png)
![image](https://user-images.githubusercontent.com/1181559/179314169-515f5e33-70a1-4084-adb8-a5445325ec35.png)
![image](https://user-images.githubusercontent.com/1181559/179314256-d63076c2-e264-49aa-a3a1-8907ab4bf354.png)

**Comment by GregValiant** [comment] 2022-07-16 11:16
Than you for the report.
This is a duplicate of about "a lot" of bug reports.  I'll mark it as a duplicate and close it.  If you think that is premature let me know here.

**Closed by GregValiant** 2022-07-16 11:16 UTC
Labels: Type: Bug, Status: Duplicate

**Comment by fieldOfView** [comment] 2022-07-16 14:35
The good news is that it has been fixed, and the fix will be in Cura 5.1:
https://github.com/Ultimaker/CuraEngine/pull/1695
