### ISSUE TITLE
Improve Cura start position choice on layers

### ISSUE THREAD

**Issue by GreyArea1966** [Ultimaker/Cura#4063] opened 2018-07-12 00:18 UTC
**Application Version**

All versions

**Platform**

All platforms
**Printer**

All printers

**Steps to Reproduce**

Slice a file with Infill layers at overhangs. “Spring no support” on thingiverse is a good example

**Actual Results**

Cura will occasionally start a layer where there is no material beneath it, when there are other options where there WOULD be material beneath.

**Expected results**

Cura should never start a layer in empty space if there is an alternative that is on material laid in the previous layer.

**Additional Information**

A good test piece is “spring, no support” on thingiverse, as it is very small and the layers are almost identical, but rotate...I believe it is this rotation that “confuses” Cura somehow

**Comment by smartavionics** [comment] 2018-07-12 09:31
Related to / duplicate of https://github.com/Ultimaker/Cura/issues/3875.

**Comment by diegopradogesto** [comment] 2018-07-12 10:31
Yes, it looks like it's duplicated. I'll close this to continue the discussing there.

**Closed by diegopradogesto** 2018-07-12 10:31 UTC
