### ISSUE TITLE
render the z-seam on a 3d model

### ISSUE THREAD

**Issue by nesergen** [Ultimaker/Cura#8153] opened 2020-08-06 13:21 UTC
Dealing with the Z-seam settings. And I want to see how changes in the settings affect the printed model (seams position). Therefore, I go to the preview mode, but I do not see where the seam is located.

It would be nice to render the seam on a 3d model. And highlight it with color.

**Comment by Ghostkeeper** [comment] 2020-08-07 14:30
Duplicate of https://github.com/Ultimaker/Cura/issues/6072.

**Closed by Ghostkeeper** 2020-08-07 14:30 UTC
Labels: Type: New Feature
