### ISSUE TITLE
Fatal Exception 2.5.0 BETA

### ISSUE THREAD

**Issue by SwiftyJ** [Ultimaker/Cura#1575] opened 2017-03-24 16:23 UTC
This occurred when I was changing material diameter and it was set to 0.

Version: 2.5.0-BETA
Platform: Windows-10-10.0.14393
Qt: 5.7.1
PyQt: 5.7.1

Exception:
Traceback (most recent call last):
  File "C:\Program Files\Cura 2.5\plugins\CuraEngineBackend\CuraEngineBackend.py", line 190, in slice
    self.printDurationMessage.emit(0, [0])
  File "D:/2.5/build/inst/lib/python3.5/site-packages/UM\Signal.py", line 201, in emit
  File "D:/2.5/build/inst/lib/python3.5/site-packages/UM\Signal.py", line 305, in __performEmit
  File "D:/2.5/build/inst/lib/python3.5/site-packages/cura\PrintInformation.py", line 122, in _onPrintDurationMessage
  File "D:/2.5/build/inst/lib/python3.5/site-packages/cura\PrintInformation.py", line 162, in _calculateInformation
ZeroDivisionError: float division by zero

**Comment by nallath** [comment] 2017-03-27 07:35
For our reference; CURA-3594

**Comment by jackha** [comment] 2017-03-29 08:48
I couldn't reproduce, but the cause has been taken away (https://github.com/Ultimaker/Cura/pull/1586). Thanks for reporting.

**Comment by fieldOfView** [comment] 2017-03-29 08:59
Can confirm this is a duplicate of #1582, which was fixed. This issue can be closed.

**Closed** 2017-03-29 09:11 UTC
