### ISSUE TITLE
Cura.exe has stopped working

### ISSUE THREAD

**Issue by GlancyNicholls** [Ultimaker/Cura#2195] opened 2017-08-02 10:10 UTC
Hi,

Please find attached report in relation to Cura (2.6.2) constantly crashing when trying to open a file. We have updated drivers but the issue is still occurring.

[DxDiag.txt](https://github.com/Ultimaker/Cura/files/1193431/DxDiag.txt)

[cura.txt](https://github.com/Ultimaker/Cura/files/1193451/cura.txt)

Can you please contact me on the details below

raghbir.sehmar@nexusgs.co.uk
02476223865

Kind Regards

Rags

**Comment by Ghostkeeper** [comment] 2017-08-04 07:19
Duplicate of #1537.

**Closed by Ghostkeeper** 2017-08-04 07:19 UTC
