### ISSUE TITLE
will not slice at .28

### ISSUE THREAD

**Issue by digital0785** [Ultimaker/Cura#10649] opened 2021-10-20 20:46 UTC
### Application Version

4.11

### Platform

windows 10

### Printer

ender 3

### Reproduction steps

imported file .. tried to slice it stops at about half way on .28 layer height .. it works fine on .24 or .2

### Actual results

does not slice

### Expected results

[es-n end tank.zip](https://github.com/Ultimaker/Cura/files/7382896/es-n.end.tank.zip)
slice haha

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![28 tank slice](https://user-images.githubusercontent.com/74274738/138133929-337f4afe-e6ed-43a1-bf49-c6353588bd86.JPG)
![24 slice](https://user-images.githubusercontent.com/74274738/138133978-008bbcda-6b33-4cf6-9948-ec9efc3ba7d2.JPG)

**Comment by fvrmr** [comment] 2021-10-21 09:27
Hi @digital0785 thank you for your bug report. 
This is a duplicate of #10418 and is happening because the top/bottom pattern is set to zigzag. If you change this to lines, the engine won't crash.
We have fixed this for our next release.

I will close this issue since it is a duplicate.

**Closed as completed by fvrmr** 2021-10-21 09:27 UTC
Labels: Type: Bug, Status: Duplicate
