### ISSUE TITLE
print "two color world"  model mistake

### ISSUE THREAD

**Issue by lyfbuaa** [Ultimaker/Cura#6502] opened 2019-10-08 01:27 UTC
Application version
Ultimaker_Cura-4.3.0.AppImage

Platform
fedora 30 x86_64

Printer
diy printer like ultimaker with marlin 1.0.2-2

**Reproduction steps**
1.download stl  :https://www.thingiverse.com/thing:11660
2.cura load stl(land and water)
3.cura edit menu->select all models ->merge models
4.slice to print
5.after print layer 1,extruder move toward (0,0）

**Actual results**
after print layer 1,extruder move toward (0,0）

**Expected results**
after print layer 1,continue layer 2,3.....
and normal with Ultimaker_Cura-4.2.1.AppImage

**Comment by rburema** [comment] 2019-10-08 07:23
I can confirm this, also that it doesn't happen in 4.2.1
(Devs: I got a project saved and will attach it to the ticket if we decide to make one.)

**Comment by Ghostkeeper** [comment] 2019-10-08 09:33
This is a duplicate of https://github.com/Ultimaker/Cura/issues/5383.

We still have the intention to fix this though. It's a semi-serious issue that doesn't occur often but has undefined behaviour when it does.

**Closed by Ghostkeeper** 2019-10-08 09:33 UTC
Labels: Type: Bug

**Comment by rburema** [comment] 2019-10-08 11:33
Relevant internal ticket: CURA-6279
