### ISSUE TITLE
unreadable menu in parameters window

### ISSUE THREAD

**Issue by grandey-HA** [Ultimaker/Cura#10047] opened 2021-06-28 20:29 UTC
### Application Version

4.9.1

### Platform

Mac OS Big Sur (M1)

### Printer

Artillery Sidewinder X1

### Reproduction steps

when accessing the parameter menu, and trying to unfold choices, the choices are unereadble !

### Actual results

![image](https://user-images.githubusercontent.com/73668739/123699535-b0860d00-d85f-11eb-807e-04cf86d3234b.png)

![image](https://user-images.githubusercontent.com/73668739/123699650-ce537200-d85f-11eb-9121-661d8d08964c.png)

### Expected results

readable !

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

tried everything in the system settings...quite lost as it seems i'm the only one having the issue.

**Comment by fvrmr** [comment] 2021-06-29 12:01
Hi @grandey-HA thank you for your bug report. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/8993 and the reason why this is happening is because we don't support M1 since it is not supporting the QT library we are using. 
I am closing this issue as a duplicate, hope you understand.

**Closed by fvrmr** 2021-06-29 12:01 UTC
Labels: Type: Bug
