### ISSUE TITLE
Memory error on start-up

### ISSUE THREAD

**Issue by robin1015** [Ultimaker/Cura#1107] opened 2016-11-04 07:45 UTC
Version: 2.1.99-master.20160930
Platform: Windows-7-6.1.7601-SP1
Qt: 5.5.1
PyQt: 5.5.1

Exception:
Traceback (most recent call last):
  File "cura_app.py", line 61, in <module>
  File "D:\master\build\inst\lib\python3.4\site-packages\UM\Application.py", line 308, in getInstance
  File "D:\master\build\inst\lib\python3.4\site-packages\cura\CuraApplication.py", line 140, in __init__
  File "D:\master\build\inst\lib\python3.4\site-packages\UM\Qt\QtApplication.py", line 94, in __init__
  File "D:\master\build\inst\lib\python3.4\site-packages\UM\VersionUpgradeManager.py", line 107, in upgrade
  File "D:\master\build\inst\lib\python3.4\site-packages\UM\VersionUpgradeManager.py", line 281, in _upgradeFile
  File "C:\Python34\lib\codecs.py", line 319, in decode
MemoryError

-------------------------------------------
PS：My computer does not have a D disk.

**Comment by Ghostkeeper** [comment] 2016-11-04 12:39
Your computer does not have enough memory to run Cura, apparently. It's crashing in one of the first stages of the start-up process.

The "D" path is actually on our build server that created the executable you're running. In the final executable, there are no paths to the actual .py files any more since everything is packed inside the binaries. So it uses the original paths of the .py files on the build server.

**Comment by robin1015** [comment] 2016-11-04 17:56
![003](https://cloud.githubusercontent.com/assets/23254213/20016520/c32e08bc-a2fa-11e6-8477-0cd22de8b156.PNG)
how about it( not have enough memory)?please see pics upload by me.would you help me to solve the problem

**Comment by fieldOfView** [comment] 2016-11-04 21:01
Because none of us read chinese (?), here's the translation looking at my english Windows 7 task monitor:

Physical Memory (MB)
Total    3497
Cached  1534
Available 1854
Free       831

Kernel Memory (MB)
Paged  187
Nonpaed  92

**Comment by robin1015** [comment] 2016-11-05 09:51
yes,you are right.thank very much fieldOfView

**Comment by robin1015** [comment] 2016-11-05 09:54
I completely uninstall and then reinstall the Cura, but still not success

**Comment by thopiekar** [comment] 2016-11-05 10:01
@robin1015 To make a complete uninstallation, you'll need to remove the settings in AppData ($User/AppData/Local/cura) manually. The uninstaller only removes the application not the settings.

**Comment by robin1015** [comment] 2016-11-05 10:44
![001](https://cloud.githubusercontent.com/assets/23254213/20029461/620f5134-a387-11e6-9581-d0cd83f8969b.PNG)
![0001](https://cloud.githubusercontent.com/assets/23254213/20029462/631a973c-a387-11e6-967e-b7ef780be9b2.PNG)

**Comment by robin1015** [comment] 2016-11-05 10:55
![0003](https://cloud.githubusercontent.com/assets/23254213/20029530/38641b60-a389-11e6-93bf-17a2b17b7ac2.PNG)

**Comment by thopiekar** [comment] 2016-11-05 11:05
Are you sure that your user account is called "CURRENT_USER"?
There really should be an "Local" directory in there. A lot of applications are using it to store their settings.

**Comment by robin1015** [comment] 2016-11-10 15:48
I'm not sure。
Why uninstall this software is so complex.
And are you sure that's the reason。

**Comment by Ghostkeeper** [comment] 2016-11-11 01:08
It's not *very* complex. The normal installer usually does the job good enough. But to completely remove all traces when uninstalling, we should probably find a way to modify the uninstaller a bit to optionally remove the preferences as well. Lots of uninstallers leave traces in the registry.

We're not sure that is the reason. We're just trying to debug via you, since we can't reproduce the problem on our end.

**Comment by robin1015** [comment] 2016-11-17 16:18
not found
“the settings in AppData ($User/AppData/Local/cura) manually”.try many times。

**Comment by robin1015** [comment] 2016-11-18 04:15
how about python34？would you tell me What is the meaning of the error message? What other possibilities?thank you

**Comment by robin1015** [comment] 2016-11-18 08:40
thopiekar，you are right

**Comment by bananaslug123** [comment] 2016-12-04 17:02
Hi.  I have encountered the same error.  No issues for the last few months, and suddenly a memory error:

Version: 2.3.1
Platform: Windows-7-6.1.7601-SP1
Qt: 5.5.1
PyQt: 5.5.1

Exception:
Traceback (most recent call last):
  File "cura_app.py", line 61, in <module>
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Application.py", line 310, in getInstance
  File "D:\2.3\build\inst\lib\python3.4\site-packages\cura\CuraApplication.py", line 173, in __init__
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\Qt\QtApplication.py", line 94, in __init__
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\VersionUpgradeManager.py", line 107, in upgrade
  File "D:\2.3\build\inst\lib\python3.4\site-packages\UM\VersionUpgradeManager.py", line 281, in _upgradeFile
MemoryError

**Comment by fieldOfView** [comment] 2016-12-04 17:29
Please see if deleting cura.log from C:\Users\<your username>\AppData\Local\cura helps

**Comment by bananaslug123** [comment] 2016-12-04 22:34
Thanks for the suggestion.  I just tried and I'm experiencing the same error.

For what it's worth, the error first occurred on 2.1.99.  I installed 2.3.1, and the error is the same.

**Comment by Ghostkeeper** [comment] 2016-12-05 08:48
I recently added a guard around this particular line. It would try and open each file to see if it is a file that should be upgraded to the latest version, but some files, such as the log, can become too big to read. Let's hope the guard helps.

**Comment by bananaslug123** [comment] 2016-12-05 16:32
Hi.  Is the guard you added in v2.3.1?  Also could other files trigger this memory error?  My files are small, and this error occurred after 2-3 months of Cura use.

Thanks.

**Comment by fieldOfView** [comment] 2016-12-05 16:54
No, the safeguard will be in 2.4. Are there no large(ish) files in the AppData\Local\cura folder?

**Comment by bananaslug123** [comment] 2016-12-06 01:24
The largest file in that folder is cura.log which is 21KB.

**Comment by fieldOfView** [comment] 2016-12-06 08:51
@bananaslug123, are you also using a 32 bit version of Cura with 4Gb of memory?

**Comment by bananaslug123** [comment] 2016-12-06 20:51
Correct.

**Comment by Ghostkeeper** [comment] 2016-12-07 01:54
It's plausible that the rest of your applications you have open are using like 3.9Gb of that available memory, leaving Cura with an insufficient amount of memory within the first 4Gb of address space. If you have a 64-bit computer, it is always advisable to use the 64-bit version. If not, I suggest you close a few other applications and try again.

**Comment by nallath** [comment] 2017-07-27 13:54
Closing this, as this doesn't seem to be a Cura issue.

**Closed by nallath** 2017-07-27 13:54 UTC
Labels: bug
