### ISSUE TITLE
Changed scale measurement, auto changes wrong percentage

### ISSUE THREAD

**Issue by Dignan17** [Ultimaker/Cura#8725] opened 2020-11-10 20:11 UTC
I tried to search for this but wasn't sure how...

**Application version**
4.7.1

**Platform**
Windows 10

**Printer**
FLSUN QQ-S Pro but also happens on Anycubic i3 Mega S

**Reproduction steps**
1. imported STL
2. clicked on it
3. chose scaling
4. unchecked "uniform scaling" (I wanted to make something shorter)
5. I had a specific height in mind, so I entered 30mm in the Z box
6. pressed tab, which generally makes the software implement what I've just entered
7. the software scaled correctly, but now in the percentage next to Z it said 100%, and the percentage next to Y says 46.67 percent.

**Screenshot(s)**

**Actual results**
**Expected results**
Sorry, I included that above

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)
![curascale](https://user-images.githubusercontent.com/28424669/98728125-0bb5ce80-2367-11eb-8d3e-1dc1bcd9ea86.png)

**Comment by konskarm** [comment] 2020-11-11 08:32
This is a duplicate of https://github.com/Ultimaker/Cura/issues/4136. It has been fixed for the newly released 4.8.

**Closed by konskarm** 2020-11-11 08:32 UTC
