### ISSUE TITLE
PauseAtHeight.py returns to wrong height

### ISSUE THREAD

**Issue by brodgartech** [Ultimaker/Cura#6272] opened 2019-08-28 11:19 UTC
**Application version**
4.2.1

**Platform**
macOS 10.14.6

**Printer**
Anet A6

**Reproduction steps**
Insert PauseAtHeight plugin, after resuming print it resumes well above the model.

**Actual results**
Return 1mm above the model

**Expected results**
Return at correct z-height

**Additional information**
'move head back' code actually returns to z+1 where it should return to z (line 312)

**Comment by DirtyRat91** [comment] 2019-09-02 15:40
I want to comment I've experienced the same bug on W10 version of Cura 4.2.1. Checking the GCODE the Z height typically is set to 15 during the pause, and then returned to the previous Z height +1. If the last layer was 3.32, then it will return to 4.32.

**Comment by Ghostkeeper** [comment] 2019-09-03 11:25
Duplicate of https://github.com/Ultimaker/Cura/issues/5924

**Closed by Ghostkeeper** 2019-09-03 11:25 UTC
Labels: Type: Bug
