### ISSUE TITLE
drag and drop doesnt work

### ISSUE THREAD

**Issue by Dr-Archadus** [Ultimaker/Cura#13152] opened 2022-08-29 08:28 UTC
### Application Version

4.11.0

### Platform

windows 10

### Printer

Artillery sidewinder x2

### Reproduction steps

i had the sidewinder selected and everything was working fine untill i switched to my ender 3 profile and the drag and drop feature would work after swithcing back to the sidewinder it would register me wanting to drop a file for slicing but wouldnt load the file

### Actual results

the drag and drop feature wont load the droped file

### Expected results

the file would load

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

everything was explaned above

**Comment by MariMakes** [comment] 2022-08-31 15:38
Hey @Dr-Archadus,

Thanks for your report 🎉 
Could this be a duplicate of https://github.com/Ultimaker/Cura/issues/11937 ?

This was resolved in Cura 5.1, and I've been dragging and dropping all day today. 
Can you please try the latest version of Cura? 
[You can download it here. ](https://github.com/Ultimaker/Cura/releases/tag/5.1.0) 

Thank you 😇

**Closed** 2022-09-15 00:22 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage
