### ISSUE TITLE
solidworks 2017 plugin

### ISSUE THREAD

**Issue by jnBremen** [Ultimaker/Cura#10816] opened 2021-11-12 17:41 UTC
### Application Version

4.12.0

### Platform

windows 10

### Printer

Ultimaker S5

### Reproduction steps

#update from cura4.10 to cura4.12
# start solidworks
# load a part
# start export to to cura 2.x
# cura start

### Actual results

#"Datei kann nicht geöffnet werden"
![image](https://user-images.githubusercontent.com/94191539/141509315-f3ff67be-177e-49f8-8101-e5bae4645133.png)

### Expected results

part loaded in cura for printing

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[G19-008.zip](https://github.com/Ultimaker/Cura/files/7529408/G19-008.zip
[UMS5_W019-103.zip](https://github.com/Ultimaker/Cura/files/7529428/UMS5_W019-103.zip)
)

**Comment by fvrmr** [comment] 2021-11-15 16:35
Hi @jnBremen thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/10806
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-11-15 16:35 UTC
Labels: Type: Bug
