### ISSUE TITLE
Bug Mold Firsts layers not correct

### ISSUE THREAD

**Issue by userosos** [Ultimaker/Cura#6621] opened 2019-11-03 15:47 UTC
Cura 4.3
I want make an form for silicone bit if i use the form the first layers are hanging in the air.
I want that the first layers aren't hanging in the air.
3mf file:
https://we.tl/t-s8TcXOwXvC

**Comment by nallath** [comment] 2019-11-04 08:36
I don't understand what you mean. What is it exactly that you're trying to do (and failing to do?)

**Comment by userosos** [comment] 2019-11-04 08:44
@nallath 
I user Mold and it work not ok.
![first_layer](https://user-images.githubusercontent.com/22872748/68108292-77659000-fef8-11e9-908e-f18a5b937c9b.PNG)
![2_3_layer](https://user-images.githubusercontent.com/22872748/68108293-77659000-fef8-11e9-9161-c5ce7321b3db.PNG)
![4 layer](https://user-images.githubusercontent.com/22872748/68108294-77659000-fef8-11e9-994f-c714ef7f2939.PNG)

**Comment by nallath** [comment] 2019-11-04 12:20
Did you check if your model is watertight? I've just tried it and it works for the models I used.

**Comment by Ghostkeeper** [comment] 2019-11-04 14:29
The model seems to be watertight. The problem, I think, is an expectation problem. The user's model actually contains a base plate (like the bottom of a box). You can see it in X-ray view as the dark underside of the model, where the X-rays go through only 2 faces.

![Screenshot from 2019-11-04 15-25-32](https://user-images.githubusercontent.com/2448634/68128103-01205800-ff0f-11e9-90ed-27d5d1d2ca8c.png)

If you were to slice normally (without mould enabled), this produces a base plate of 5 layers thick. With mould enabled, it produces a hollow area of 5 layers thick (using your 3MF file's settings, which are apparently different from the 3 layers you reported). This is intended because Cura thinks you want to cast the base plate as well. It doesn't know that you only want to cast those 3 protruding parts of your model.

**Comment by Ghostkeeper** [comment] 2019-11-04 14:31
If you move the model 1mm down it'll behave as you'd expect because Cura won't create a mould for the piece that is below the build plate (i.e. the base plate of your model).

We'll close this because it's expected behaviour.

**Closed by Ghostkeeper** 2019-11-04 14:31 UTC
Labels: Type: Bug
