### ISSUE TITLE
Object list lists multiplied objects in wrong order.

### ISSUE THREAD

**Issue by oliof** [Ultimaker/Cura#18919] opened 2024-04-20 12:30 UTC
### Cura Version

5.7.0

### Operating System

POP!_OS Linux 20.04

### Printer

Betaminion (custom cartesian printer)

### Reproduction steps

1. loaded a model
2. Asked Cura to make 71 copies

### Actual results

The copies are listed in string comparison oder, not in numerical order
![image](https://github.com/Ultimaker/Cura/assets/1230627/485fafb4-34e3-47ff-bd1d-e088f336d948)

### Expected results

In the image above, M6Washer-Body.stl(7) should not be between M6Washer-Body.stl(69) and M6Washer-Body.stl(70), but between copies 5 and 7; likewise 8 and 9 end up at the end of the list.

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/1230627/46e46556-c130-406e-83cd-d4d164b0cd1d)

**Comment by GregValiant** [comment] 2024-04-20 17:46
Thanks for the report.
The list is in "Alphabetic" order and not "Numeric" order.  That is expected behavior.  If there was an 81 it would be between 8 and 9.  Some models have numbers in their filenames so this can't be done any other way.
If you are printing in "One at a Time" mode you can elect to manually re-order the list because a ssof 5.7.0 the Object List is now the printing order.

I'll go ahead and remove the bug label and close this.  I hope you understand.

**Closed by GregValiant** 2024-04-20 17:46 UTC
Labels: Type: Discussion, Status: Under Investigation
