### ISSUE TITLE
z-seam is not smooth

### ISSUE THREAD

**Issue by passkal** [Ultimaker/Cura#13441] opened 2022-10-02 20:24 UTC
### Application Version

5.2.0

### Platform

windows 10

### Printer

Ender 5

### Reproduction steps

In all versions of CURA 5.x, the Z-seam on the round surface turns out to be torn, only for this reason I use only the CURA 4.13.1 version

![z-seam](https://user-images.githubusercontent.com/51381842/193474024-e80e466e-b87f-4521-a8b8-578806f132a5.jpg)

### Actual results

In all versions of CURA 5.x, the Z-seam on the round surface (of my model) turns out to be torn,

### Expected results

Please pay attention to this problem

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![z-seam-2](https://user-images.githubusercontent.com/51381842/193474733-3bf4e1e1-029f-4c07-9cea-2653b388e020.jpg)

**Comment by passkal** [comment] 2022-10-02 20:28
Another angle of the model
![z-seam-3](https://user-images.githubusercontent.com/51381842/193474880-381ffebd-71e0-46a0-ae91-30146016191d.jpg)

**Comment by GregValiant** [comment] 2022-10-03 03:02
Thanks for the report.
This is a duplicate of #11877 (another report is #12100).  I'll mark it as a duplicate and close your report.  You can follow progress on #11877.

**Closed by GregValiant** 2022-10-03 03:02 UTC
Labels: Type: Bug, Status: Duplicate
