### ISSUE TITLE
Preview bug when moving up on the z-axis

### ISSUE THREAD

**Issue by Ak1K0rt** [Ultimaker/Cura#15338] opened 2023-04-24 07:06 UTC
### Application Version

5.3.0

### Platform

Windows 10 and Windows 11

### Printer

Anycubic Kobra

### Reproduction steps

1. Open STL-file in Cura
2. Check "Generate Support" and "Touching Buildplate" settings.
3. Uncheck "Drop Down Model" from the Move ("T") settings
4. Move object in Z-axis 10mm upwards
5. Press Slice
6. Press Preview

### Actual results

Printable model remains attached to the buildplate.

![Cura_5 3 0_z-up](https://user-images.githubusercontent.com/128142686/233921935-a89bb57f-b9ad-499f-8a50-14e53b7cc45b.png)

### Expected results

Printable model should move upwards 10mm and there should be support between buildplate and model. This screenshot is taken from Cura 5.2.1.
![2023-04-24 10_00_48-AK_PiratesCoin - Ultimaker Cura](https://user-images.githubusercontent.com/128142686/233922309-80cfd731-aec0-4232-a799-136a18925c22.png)

### Checklist of files to include

- [x] Log file
- [ ] Project file

### Additional information & file uploads

Cura 5.3.0 logfile

[cura.log](https://github.com/Ultimaker/Cura/files/11307581/cura.log)

**Comment by GregValiant** [comment] 2023-04-24 10:42
Thanks for the report.
I think you have stumbled on to "one of those things".
When "Generate Support" is checked - it hides the "Mesh Fixes" setting "Remove Empty First Layers" BUT "Remove Empty First Layers" is being used (even when hidden) and if it happens to be enabled then yes, the model is printed on the build plate instead of on top of a bed of support.
So the workaround is to:

- Turn off "Generate Support"
- Turn off "Remove Empty First Layers" in Mesh Fixes
- Re-enable "Generate Support"

I feel that a setting that is being used shouldn't be hidden and there is confusion between "Remove Empty..." and the General Setting "Automatically drop models to the build plate".  The Cura Team is looking into this.

This is a duplicate of #14989 and #15179 and I'll mark it as such and I'll go ahead and close this ticket given that the team has indicated it will be addressed.  I hope you understand.

**Closed by GregValiant** 2023-04-24 10:42 UTC
Labels: Type: Bug, Status: Under Investigation

**Comment by Ak1K0rt** [comment] 2023-04-24 10:50
Thanks for the tip!
