### ISSUE TITLE
Filament diameter settings dont work

### ISSUE THREAD

**Issue by hagan66** [Ultimaker/Cura#4619] opened 2018-10-19 18:09 UTC
Entering different filament diameters in materials settings makes no difference in extrusion. I also tried changing diameter in the Machine settings. No effect. I have made a complete re-install of Cura resetting everything. I also wonder where the right place is to enter the measured filament diameter now since you removed it from the material settings in the sidebar.

**Application Version**
3.5.1

**Platform**
Mac

**Printer**
Prusa i3 mk2s

**Steps to Reproduce**
Print single wall cube, measure wall thickness. Change diameter settings, print again and measure.

**Comment by TheNitek** [comment] 2018-10-20 19:33
Probably a duplicate of #4582

**Comment by diegopradogesto** [comment] 2018-10-24 16:57
Yes, I think it's the same. Fixed in the upcoming Cura 3.6.

**Closed by diegopradogesto** 2018-10-24 16:57 UTC
