### ISSUE TITLE
Print tempreture

### ISSUE THREAD

**Issue by AndrewJarvis** [Ultimaker/Cura#4514] opened 2018-10-07 19:04 UTC
When I set the temp to 270 in cura and create gcode it actually prints at 210?? and I have to manually up the temp.  Cura 3.5

**Comment by alexodus** [comment] 2018-10-07 19:44
https://community.ultimaker.com/topic/24702-cura-35-gcode-always-works-at-210%C2%BA-nozzle/

**Comment by alexodus** [comment] 2018-10-07 19:45
Duplicate of #4469

**Closed** 2018-10-07 22:33 UTC
