### ISSUE TITLE
Cura 4.5.0 ignores Skin Overlap Percentage values causing gaps on skin surfaces when Top Surface Skin Layers set to > 0

### ISSUE THREAD

**Issue by sekbowee** [Ultimaker/Cura#7263] opened 2020-03-11 07:39 UTC
**Application version**
Latest Cura 4.5.0

**Platform**
Windows 10 Pro 64-bit
GTX 980 Ti

**Printer**
Creality Ender-3 (Selected printer in cura)

**Reproduction steps**
1. Calibrate Flow Rate / E-steps
2. Changing values of Skin Overlap Percentage to 5 - 50 %

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/4946108/76393005-9e076c00-63ad-11ea-9dac-02a8c4620a3e.png)

**Expected results**
1. Skin overflow onto perimeter/walls
2. No more gaps between skin and wall.

**Actual results**
Gaps present on the top surface of the cube.
![Cura Issue](https://user-images.githubusercontent.com/4946108/76392927-7f08da00-63ad-11ea-8cd6-63a0707fe45b.jpg)

**Profile**
[Creality Ender-3 PLA.zip](https://github.com/Ultimaker/Cura/files/4316633/Creality.Ender-3.PLA.zip)
Profile built up from scratch, not imported from 4.4.1 or earlier.

**Comment by Ghostkeeper** [comment] 2020-03-13 15:46
I'm not able to reproduce your bug. With the overlap set to 20 micrometres the overlap is pretty much invisible so I upped it to 0.8mm, and you can clearly see that the skin lines are overlapping with the walls:
![image](https://user-images.githubusercontent.com/2448634/76636904-19058980-654a-11ea-8f7a-e84d4bbc3564.png)

Perhaps the gaps are caused by other things. Tried upping the print temperature a little bit?

So far I don't see any bug here in how Cura behaves.

**Comment by sekbowee** [comment] 2020-03-14 05:52
I just found out that if u had Top Surface Skin Layers set to > 0 , the top skin will ignore the skin overlap setting

![image](https://user-images.githubusercontent.com/4946108/76676069-d64fba00-65fa-11ea-9d93-55346541e0ea.png)

If Top Surface Skin Layers set to 0, top skin will follow the skin overlap setting

![image](https://user-images.githubusercontent.com/4946108/76676080-f7b0a600-65fa-11ea-90a8-34003a2d09c9.png)

**Comment by Ghostkeeper** [comment] 2020-03-18 15:07
Ah, yes. That's a known issue, sorry. I'll close this as a duplicate of https://github.com/Ultimaker/Cura/issues/5758.

**Closed by Ghostkeeper** 2020-03-18 15:07 UTC
Labels: Category: Settings, Status: Needs Info, Type: Bug
