### ISSUE TITLE
[4.1 beta] Window can't be enlarged adding a custom printer + bug on the machine edit layout

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#5742] opened 2019-05-15 13:15 UTC
**Application Version**
4.1 beta

**Platform**
Win10 x64

**Printer**
Custom

**Steps to Reproduce**
Add a custom printer.

**Actual Results**
The window is very small, and you can't enlarge it or make it smaller. The drag doesn't work, though there is the icon.
The fields also cross each other.
If you then try to modify the setting after so that the drag bug isn't there, there is another visual glitch.

**Expected results**
Guess it.

**Additional Information**
![Add custom printer](https://user-images.githubusercontent.com/20385116/57778403-44e69180-7724-11e9-8744-c2681898dcc2.png)
![Machine edit](https://user-images.githubusercontent.com/20385116/57857336-2ac5b580-77ef-11e9-8786-dcbeba02bfe8.png)

**Comment by wizhippo** [comment] 2019-05-15 19:56
I just tried on fresh install and have no issue resizing.

**Comment by Liger0** [comment] 2019-05-15 20:05
Mine was a fresh install too.

**Comment by wizhippo** [comment] 2019-05-15 20:14
My mistake.  I added then went back in to edit it.   I can confirm this does happen on the initial add print page.  You can resize when you go back in to edit.

**Comment by Liger0** [comment] 2019-05-16 13:28
Updated with another bug related to this.
If you want to modify the machine later, as the first gui when creating the machine is bugged, you'll still encounter another bug related to the gcode tabs.

**Comment by Ghostkeeper** [comment] 2019-05-17 07:50
I agree that it's inconsistent and it would be useful to allow the Add Printer window to be resized.

Can't reproduce that bug with the g-code going out of the text area though.

**Comment by LipuFei** [comment] 2019-05-17 12:30
The resizing issue is fixed in 361636af2

**Comment by Liger0** [comment] 2019-05-17 17:10
I didn't try the fix as I always wait for the releases to be published, but even if the resize is fixed, would it be possible to fix the distance between the printer and extruder tab, so that even at that minimum size, the printer settings fields don't cross the printhead settings ones?

**Comment by Ghostkeeper** [comment] 2019-05-20 09:53
Well, I can't get them to cross here. The minimum size is preventing me. I think we might have some other issues with the screen scale factor in this place.

**Comment by Ghostkeeper** [comment] 2019-05-28 13:52
Could you try this again in the 4.1 stable release that we've released today?

**Comment by Liger0** [comment] 2019-05-28 19:49
This (still) happens when resizing.
![machine edit](https://user-images.githubusercontent.com/20385116/58507447-18099400-8192-11e9-8f70-e79507bc88e3.png)

Also, the vertical and horizontal scrolling bars in the gcode don't appear, not even pointing on them. They only appear if I use the mouse wheel (is it called so? I'm not a native speaker)

**Closed** 2019-06-06 07:45 UTC
Labels: Category: Cura, Type: Improvement

**Comment by Ghostkeeper** [comment] 2019-06-06 08:08
Fixed the widths of the labels and reorganised the positioning of the two columns a bit. I hope it works on your computer as well.

**Comment by Liger0** [comment] 2019-07-26 15:17
Start and ending gcode is still out of the tab when resizing.
