### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Mejituu** [Ultimaker/Cura#10134] opened 2021-07-14 03:45 UTC
### Application Version

4.10.0

### Platform

Windows 10

### Printer

CoreXY 兔兔

### Reproduction steps

Open Cura and load 123.STL Cura crashes and crashes during the loading process.

### Actual results

Open Cura and load 123.STL Cura crashes and crashes during the loading process.

### Expected results

Open Cura and load 123.STL Cura crashes and crashes during the loading process.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[stderr.log](https://github.com/Ultimaker/Cura/files/6813355/stderr.log)

**Comment by fvrmr** [comment] 2021-07-15 14:11
Hi @Mejituu it seems like it can't access a temporary folder. This issue: https://github.com/Ultimaker/Cura/issues/10113 is also having the same error but with loading printers. 
I will bring this up for discussion with the team. Keep you posted.

**Comment by Ghostkeeper** [comment] 2021-07-21 13:43
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9644. Please continue the conversation there.

**Closed by Ghostkeeper** 2021-07-21 13:43 UTC
Labels: Type: Bug
