### ISSUE TITLE
Auto Infill of settings

### ISSUE THREAD

**Issue by StockyJ** [Ultimaker/Cura#13691] opened 2022-10-29 09:54 UTC
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Tevo BW

### Reproduction steps

Using 5.2.1 (and with previous updates, but not before 4) I have noticed that when entering some settings for Example Infill Percentage when I what 20% as soon as I type 2 it auto sets 2%. Even backspacing the percentage figures it defaults to 0.0 and enters it. 
 Small issue but annoying.

### Actual results

Details above

### Expected results

Should allow digits to be entered with no auto input.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

As above

**Comment by MariMakes** [comment] 2022-11-01 11:51
Hey @StockyJ 

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

I recognize your issue, this seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12949
We have a ticket on our backlog with the intent to improve this behavior.
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12949

**Closed by MariMakes** 2022-11-01 11:51 UTC
Labels: Type: Bug, Status: Triage
