### ISSUE TITLE
Menu text is garbage

### ISSUE THREAD

**Issue by OmiPops** [Ultimaker/Cura#3595] opened 2018-03-29 13:24 UTC
**Application Version**

3.2.1
**Platform**

iMac (27-inch, Late 2013)  OS 10.13.3
**Qt**

**PyQt**

**Display Driver**

NVIDIA GeForce GTX 775M 2 GB
**Printer**

any printer (e.g. BQ Hephestos 2, Prusa MK2)
**Steps to Reproduce**

load Cura, observe right-hand panel of user interface
**Actual Results**

Menu text is garbage
**Expected results**

Menu text is readable
**Additional Information**

![garbage text](https://user-images.githubusercontent.com/25321971/38091201-1d3d0f3c-3365-11e8-9436-83f92b8b49d6.jpeg)

**Comment by fieldOfView** [comment] 2018-03-29 13:38
Duplicate of #3277, fixed in Cura 3.3

**Closed** 2018-03-29 14:13 UTC
