### ISSUE TITLE
Incorrect Scaling after rotation of an object

### ISSUE THREAD

**Issue by PacketPaul** [Ultimaker/Cura#5189] opened 2019-01-17 16:51 UTC
**Application Version**
3.6.0

**Platform**
Windows

**Printer**
N/A

**Steps to Reproduce**
1) Place an object in Cura. 

2) Rotate the Object 90 Degrees from the horizontal so the front face of the object is laying flat on the bed (i.e. rotate the red circle 90 degrees).  But in reality any rotation will work.  

3) Select scaling and make sure Snap Scaling and Uniform Scaling are not selected.

4) Try to independently adjust the X, Y, and Z scale.  If rotated 90 degrees from the horizonal, you will find the Y and Z scales are linked.  When adjusting Z it also adjusts Y.  And, even worse, every time you click on the Z value (i.e. bringing Z in focus), even if the values are not changed, it changes the Y value lower.

**Actual Results**
1) Set X to 102%.  Works
2) Set Y to 102% … it also set's Z to 102%
3) Set Z to 100% and it adjusts Y lower (usually around 98.04%)
4) Select the X value again.  Then select Z value.  Then Select X value without changing Z.  They Y value will again decrease.  To see it in action, simply tab between the different values.  Every time the Z value loses focus, the Y value is decreased.

**Expected results**
After rotation, the X, Y, and Z faces should represent the after rotated value.  You should be able to independently adjust the X, Y, Z values.

**Additional Information**

**Comment by Ghostkeeper** [comment] 2019-01-29 15:25
Duplicate of #4136.

**Closed by Ghostkeeper** 2019-01-29 15:25 UTC
