### ISSUE TITLE
Support infill ignores inner boundaries when using tree support

### ISSUE THREAD

**Issue by Jmlannan** [Ultimaker/Cura#7105] opened 2020-02-15 21:03 UTC
When you have support going all the way around a print and have support density not zero cura will try to fill in the support infill all the way through the print. 

**Application version**
4.4.1

**Platform**
Windows 10

**Printer**
Tevo tarantula

**Reproduction steps**
1. Starting with a part with an overhang that goes around the part or will have support going around the part
2. Turn on tree support with nonzero support density
3. Check preview to see that support infill is now going through the part.

**Screenshot(s)**
![Capture](https://user-images.githubusercontent.com/3395054/74595072-648c4c80-500b-11ea-86de-fba97ecf4dee.PNG)

**Actual results**
Support infill joined to print

**Expected results**
Support infill should only be within the supports not in the print.

**Project file**
[TT_Vive_Katana_Handle_Adapter.3mf.txt](https://github.com/Ultimaker/Cura/files/4208991/TT_Vive_Katana_Handle_Adapter.3mf.txt)

**Comment by Ghostkeeper** [comment] 2020-02-18 12:58
You spent a lot of time optimising this print, I can tell.

That bug indeed reproduces. I feel like I've seen this before but I thought we fixed that.

**Comment by mahtDFR** [comment] 2020-02-19 14:21
This is on our backlog as CURA-7236

**Comment by Ghostkeeper** [comment] 2020-03-10 12:30
Duplicate of https://github.com/Ultimaker/Cura/issues/5223.

**Closed by Ghostkeeper** 2020-03-10 12:30 UTC
Labels: Category: Engine, Type: Bug

**Comment by nallath** [comment] 2020-07-01 13:20
Fixed for 4.7
