### ISSUE TITLE
Options cancel too quickly

### ISSUE THREAD

**Issue by benclewett** [Ultimaker/Cura#18641] opened 2024-03-17 15:06 UTC
### Cura Version

5.7.0-beta1

### Operating System

MacOS 14.2.1

### Printer

Creality v2 Neo

### Reproduction steps

Select an option, like Infill density.  Delete the current option.  Wait about a 0.1 of a second.  The value will be replace with 0 and the option committed.  It gives almost no chance in typing in the option I want.

### Actual results

As above

### Expected results

As above

### Add your .zip and screenshots here ⬇️

None

**Comment by GregValiant** [comment] 2024-03-17 15:27
Thanks for the report.
I know I can reproduce this one.  As soon as you get one character typed into a box you get bopped out and the rest of your typing ends up on the floor.

The Cura team will take a look.

**Comment by MariMakes** [comment] 2024-03-18 16:19
Hi @benclewett 

Thanks for your report 👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12949
We have a ticket on our backlog with the intent to improve this behavior.

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12949

**Closed by MariMakes** 2024-03-18 16:19 UTC
Labels: Type: Bug, Status: Under Investigation, PreRelease :bug:

**Comment by benclewett** [comment] 2024-03-19 08:31
Thanks.  It seems a shame that such a high-impact bug is left unfixed for
nearly 20 months.
