### ISSUE TITLE
Tabs in Cura

### ISSUE THREAD

**Issue by omega-regulus** [Ultimaker/Cura#8692] opened 2020-11-04 13:56 UTC
Hello, I was on windows and I become a Mac user recently and I have "recommandation" for you, your software is so cool but can you put different tabs like a web browser to switch between printers and stl files without make a new project and keep a sliced stl while slicing another for example.

**Comment by Glodigit** [comment] 2020-11-04 19:54
+1 on this. Really like Mattercontrol's use on this, especially since the multi build plate feature of 3.2 seems to have been removed.

**Comment by Ghostkeeper** [comment] 2020-11-05 13:45
Duplicate of https://github.com/Ultimaker/Cura/issues/7009.

Sorry, this was considered out of scope for the time being. It's an enormous task and regression hazard to implement something like this. For now, the workaround is to just open multiple instances of Cura.

**Closed by Ghostkeeper** 2020-11-05 13:45 UTC
Labels: Type: New Feature
