### ISSUE TITLE
Lack of save feature on the printer settings, including Machine Settings

### ISSUE THREAD

**Issue by MrBill57** [Ultimaker/Cura#12068] opened 2022-05-03 02:09 UTC
### Application Version

5.0.0-beta

### Platform

Win 10

### Printer

Ender3v2

### Reproduction steps

Difficult to verify if changes in machine settings has been done. No way to cancel changes. No way to acknowledge that you want to save. 

### Actual results

Appears to change when examining the g-code.

### Expected results

Save/Cancel or just a Save and close to exit without saving.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

New version with many changes. Some things will break. I love the new engine!

File attached is not important - nothing to show.
[Extruder_Rate_Spreadsheet.xlsx](https://github.com/Ultimaker/Cura/files/8607923/Extruder_Rate_Spreadsheet.xlsx)

**Comment by fvrmr** [comment] 2022-05-03 12:21
Hi @MrBill57 thank you for your report. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/12021, so I will close this issue.

**Closed by fvrmr** 2022-05-03 12:21 UTC
Labels: Type: Bug
