### ISSUE TITLE
Cura crash when file is opened

### ISSUE THREAD

**Issue by Slotcarprinter** [Ultimaker/Cura#11643] opened 2022-03-10 17:08 UTC
### Application Version

4.13.1

### Platform

Windows 10

### Printer

Creality CR10

### Reproduction steps

I have been using Cure for about a year with no issues. Today Cura immediately closes when I open a file. I did do a windows 10 update, not sure if this caused the issue with Cura. I have re-installed Cura but to no avail. I also downloaded Chitubox, also not sure if this may cause some kind of clash. I would realy like to keep on using Cura as I find it brilliant to use. Please help!

### Actual results

Cura just closes

### Expected results

Cura should open the file 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

The file I try to open is irrelevant, Cura has the same issue irrelevant which file I try to open

**Comment by fvrmr** [comment] 2022-03-11 08:23
Hi @Slotcarprinter thank you for your report.
This is happening because of Chitubox. You can read here the work around: https://support.ultimaker.com/hc/en-us/articles/4402996140946-Ultimaker-Cura-crashes-when-opening-any-file 
I will close this issue since it is a duplicate of https://github.com/Ultimaker/Cura/issues/9668

**Closed by fvrmr** 2022-03-11 08:23 UTC
Labels: Type: Bug
