### ISSUE TITLE
Bad Circular Top Layer

### ISSUE THREAD

**Issue by Zogar89** [Ultimaker/Cura#10098] opened 2021-07-07 06:36 UTC
### Application Version

4.10

### Platform

Windows 10

### Printer

Artillery X1

### Reproduction steps

Top layer are broken

![imagen](https://user-images.githubusercontent.com/11767960/124711317-4fe87700-ded4-11eb-97a1-04598b6f57dc.png)
![imagen](https://user-images.githubusercontent.com/11767960/124711899-02b8d500-ded5-11eb-8990-f2e26a1b8fdd.png)

[1h10m35g-A.zip](https://github.com/Ultimaker/Cura/files/6774907/1h10m35g-A.zip)

### Actual results

Broken lines

### Expected results

Continuous line

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Proyect File uploaded

**Comment by fvrmr** [comment] 2021-07-08 09:05
Hi @Zogar89 I can't reproduce your issue, my lines are not broken. 

![Screenshot (213)](https://user-images.githubusercontent.com/77000924/124894801-421e1900-dfdc-11eb-9682-b372ed3c2417.png)

On what layer height did your problem occur?

**Comment by nallath** [comment] 2021-07-09 12:00
Problems like this are also solved with Arachne. We have essentially re-written the algorithms that handle that behavior for that version. It's still in BETA though, but it's stable enough to use.

**Comment by Ghostkeeper** [comment] 2021-07-14 12:09
Duplicate of https://github.com/Ultimaker/Cura/issues/7687.

**Closed by Ghostkeeper** 2021-07-14 12:09 UTC
Labels: Status: Needs Info, Type: Bug
