### ISSUE TITLE
One-time failure to slice

### ISSUE THREAD

**Issue by GodOfCheese** [Ultimaker/Cura#14613] opened 2023-02-19 18:23 UTC
### Application Version

5.1.0

### Platform

Windows 11

### Printer

Anycubic Vyper

### Reproduction steps

Slicing this model: https://www.thingiverse.com/thing:4790987

Saved the project here:

[AV_Echo_Dot_V3_Octostand.zip](https://github.com/Ultimaker/Cura/files/10777597/AV_Echo_Dot_V3_Octostand.zip)

[cura.log](https://github.com/Ultimaker/Cura/files/10777619/cura.log)

### Actual results

Slice takes a really long time and eventually errors out.
Re-slicing a second time (no changes!) does not repro.  

### Expected results

Slice succeeds :-D

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

I'm guessing this error in the log has something to do with it:
2023-02-19 10:08:02,179 - ERROR - [MainThread] CuraEngineBackend.CuraEngineBackend._onBackendQuit [959]: Backend exited abnormally with return code 3221225477!
2023-02-19 10:08:02,185 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._terminate [359]: Attempting to kill the engine process
2023-02-19 10:08:02,186 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._terminate [365]: Killing engine process
2023-02-19 10:08:02,187 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._terminate [368]: Engine process is killed. Received return code 3221225477

**Comment by MariMakes** [comment] 2023-02-21 10:51
Hey @GodOfCheese 🧀,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13643
It has been resolved for the upcoming Cura 5.3 Beta.
So keep your eyes peeled for that update. 

![image](https://user-images.githubusercontent.com/40423138/220325134-f7d0bc51-52c8-40c9-8fee-7bab96aaec1f.png)

**Closed by MariMakes** 2023-02-21 10:51 UTC
Labels: Type: Bug, Status: Triage
