### ISSUE TITLE
4.9 creates supports in the wild 

### ISSUE THREAD

**Issue by rakoenig** [Ultimaker/Cura#9681] opened 2021-04-24 15:07 UTC
### Application Version

4.9.0

### Platform

openSUSE 15.2

### Printer

Sovol SV01

### Reproduction steps

1. Downloaded STL from https://cdn.thingiverse.com/assets/e9/b9/b2/da/a5/adapter_pour_telescope_v3-slider.stl

Slicing it with 0.2 and 40% infill and supports enabled. 

### Actual results

Cura 4.9.0 creates a small support "in the wild" on the right side in the front.

### Expected results

No Supports in the wild as Cura 4.7.1 did.

### Additional information

**Screenshot from 4.7.1:**

![Screenshot-4 7 1](https://user-images.githubusercontent.com/7784123/115963408-6dd24c80-a51f-11eb-9647-73f28ae48c3e.png)

**Screenshot from 4.9.0:**

![Screenshot-4 9 0](https://user-images.githubusercontent.com/7784123/115963409-6f037980-a51f-11eb-86d5-25423b22e4ee.png)

**Comment by fvrmr** [comment] 2021-04-26 07:08
Hi @rakoenig thank you for your report.
Disable `use towers` under custom and your problem should be solved.
I will close this issue, but please reach out if you have more questions!

**Closed by fvrmr** 2021-04-26 07:08 UTC
Labels: Type: Bug

**Comment by Ghostkeeper** [comment] 2021-05-11 12:48
For posterity, this is an actual bug, but a duplicate of https://github.com/Ultimaker/Cura/issues/7487.
