### ISSUE TITLE
Bug Report - Layer 686 printed at z=0

### ISSUE THREAD

**Issue by marc-CR-10** [Ultimaker/Cura#8880] opened 2020-12-03 21:36 UTC
**Application version**
4.8.0
**Platform**
Windows 10

**Printer**
Creality CR-10

**Reproduction steps**
1. Reviewinging slices in layers
2. Noticed an artifact on the bed (z=0), identified it as layer 686

**Screenshot(s)**
Layer No.685 
![image](https://user-images.githubusercontent.com/75452745/101090727-17bb3780-3585-11eb-8398-b1ccf051bf1d.png)
Layer 686 (bottom right corner of pic)
![image](https://user-images.githubusercontent.com/75452745/101090804-38838d00-3585-11eb-9138-49b96ffd341d.png)

**Actual results**
Can not remove artifact

**Expected results**
slice model without dumping layers to the bed

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save Project. For big files you may need to use WeTransfer or similar file sharing sites. G-code files are not project files!)

[Cord Chamber-Bug.zip](https://github.com/Ultimaker/Cura/files/5639053/Cord.Chamber-Bug.zip)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by Ghostkeeper** [comment] 2020-12-07 11:11
Duplicate of https://github.com/Ultimaker/Cura/issues/5788.

It's just a visualisation issue. It's not in the output g-code. And it seems to happen very rarely.

**Closed by Ghostkeeper** 2020-12-07 11:11 UTC
Labels: Type: Bug

**Comment by marc-CR-10** [comment] 2020-12-08 00:33
Thank you!
