### ISSUE TITLE
Beginning of layer on straigth line instead of corner

### ISSUE THREAD

**Issue by matthieut59** [Ultimaker/Cura#9834] opened 2021-05-15 06:33 UTC
### Is your feature request related to a problem?

Corners are often the weak spot on my prints (warping etc.), and on some simple prints (mostly rectangle) I would find it very usefull to start my first layer for instead on the inner wall of a straigth line, instead of the corner.

Not matter what I m trying to define in the slice, it always starts on a corner :( Random is clearly not random and always pick a corner :( )

Thks in advance, interested by your view on this!

Matt

### Describe the solution you'd like

anything not limiting the seam position to a corner would be usefull

### Describe alternatives you've considered

none so far :(

### Affected users and/or printers

All users

**Comment by smartavionics** [comment] 2021-05-15 07:01
My Cura will start walls not on a corner when the z-seam alignment is user specified and the seam corner preference is set to none. Like this...

![Screenshot_2021-05-15_07-59-52](https://user-images.githubusercontent.com/585618/118351383-9dd7a300-b553-11eb-94a6-d4850e9bab38.png)

My latest release can be found at https://github.com/smartavionics/Cura/releases

Please read the README.md there for more information.

**Comment by matthieut59** [comment] 2021-05-15 07:14
I tried pretty much all possible Z seam X/Y couple, and it s always on a corner with this setting :  
![image](https://user-images.githubusercontent.com/32267255/118351747-fdd34700-b55d-11eb-9657-bf5382586564.png)

**Comment by smartavionics** [comment] 2021-05-15 07:25
Which Cura are you using? This only works with my releases, not the UM releases.

**Comment by matthieut59** [comment] 2021-05-15 07:27
oh! I m using master 4.9, so I need to move on your version ? Have you proposer this enhancement to Master ?

**Comment by smartavionics** [comment] 2021-05-15 07:33
No, sorry, I don't contribute new features to Cura any more, just bug fixes.

**Comment by Ghostkeeper** [comment] 2021-05-17 09:50
Duplicate of https://github.com/Ultimaker/Cura/issues/8010.

**Closed by Ghostkeeper** 2021-05-17 09:50 UTC
Labels: Type: New Feature
