### ISSUE TITLE
"Moonraker plugin could not be loaded". 

### ISSUE THREAD

**Issue by ptwats** [Ultimaker/Cura#12230] opened 2022-05-17 16:01 UTC
### Application Version

5.0.0

### Platform

Windows 11

### Printer

Network

### Reproduction steps

Installed Cura 5.0.0 and opened when finished. 

### Actual results

Cura 5.0.0 opens a window with The plugin MoonrakerPlugin could not be loaded. Re-installing the plugin might solve the issue.

I select "Remove plugin" then restart.
Cura errors with the same message.

Then opened Marketplace and remove Moonraker Plugin from Marketplace window.
Closed and restarted Cura.  Same error on Cura restart.

### Expected results

I expected the error to clear after plugin was remove and a restart of the Cura app
[cura.log](https://github.com/Ultimaker/Cura/files/8709775/cura.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

I also ran CCleaner after several attempts to open Cura. Cura seemed operational even with the error on opening the app

**Comment by fvrmr** [comment] 2022-05-18 09:13
Hi @ptwats thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11865, so I will close this issue.

**Closed by fvrmr** 2022-05-18 09:13 UTC
Labels: Type: Bug
