### ISSUE TITLE
Cura does not remember the path it opened a file from

### ISSUE THREAD

**Issue by ErwinBaeyens** [Ultimaker/Cura#14187] opened 2023-01-02 12:01 UTC
### Application Version

5.2.1

### Platform

Fedora Linux 37

### Printer

Anycubic Vypoer/ Does not matter

### Reproduction steps

1. Open a file, either via selecting File-> open files, The folder icon or ctrl-o
2. The fileselector opens in  the users home drive. 
3. Navigate to the correct folder  
4. click the file to open 
5. Open a second file 
6. the fileselector opens again in the root of the users home folder. 

### Actual results

With every new file access that is made the file selector opens again in the root of the users home folder, not in the last place it was. 

### Expected results

The file selector should retain the previously used path, at least in the current session. 
This does not happen in 4.13 where the file selector opens in the previously used path
Initial opening:
![image](https://user-images.githubusercontent.com/15808295/210228180-492537c8-e649-4352-9ced-470bed1a034b.png)

![image](https://user-images.githubusercontent.com/15808295/210226838-814c8b24-3086-4f7e-ac16-c3b10845ebb1.png)

![image](https://user-images.githubusercontent.com/15808295/210226938-489ccd2f-6c77-44e7-ac45-c1dff10a0d4e.png)

Open for a 2nd file: 
![image](https://user-images.githubusercontent.com/15808295/210226791-df801a7e-69ca-4f1f-8235-455936aa3acb.png)

![image](https://user-images.githubusercontent.com/15808295/210227338-692ba445-e15b-4d65-a2cb-7cf2ae1ad02e.png)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

See the attached images to show that the fileselector opens in he hom folder of the user 
same sequence in 4.13.1: 
initial opening 
![image](https://user-images.githubusercontent.com/15808295/210228471-ed1dc6b1-c6a2-46b0-834f-8033c14bdf16.png)

![image](https://user-images.githubusercontent.com/15808295/210228486-e05cdcdf-ba8d-4dc6-adbd-a8e1f643b6ca.png)

load  project:
![image](https://user-images.githubusercontent.com/15808295/210228502-81613a6e-ff92-4333-b5f7-a3fdffdcc6e7.png)

![image](https://user-images.githubusercontent.com/15808295/210228583-4fb1de1b-6eda-4e19-8653-c87714802c82.png)

**Comment by MariMakes** [comment] 2023-01-05 13:25
Hey @ErwinBaeyens,

Thanks for your report 👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12295
We have a ticket on our backlog with the intent to improve this behavior.
We've had quite a number of reports on it so I hope we can pick it up soon 🤞 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12295

**Closed by MariMakes** 2023-01-05 13:25 UTC
Labels: Type: Bug, Status: Triage
