### ISSUE TITLE
FLsun QQ-s Model Not Correct on screen 

### ISSUE THREAD

**Issue by JohanPluister** [Ultimaker/Cura#9738] opened 2021-05-01 05:39 UTC
### Application Version

4.9.0

### Platform

Windows 10

### Printer

FLsun QQ-s

### Reproduction steps

If you choose the FLsun qq-s for printer, the printer is turned 90 degrees. This is shedding on the screen.

### Actual results

![IMG_8859 1](https://user-images.githubusercontent.com/83095557/116772519-eec5a280-aa4f-11eb-88ec-89cf75cced86.JPG)

### Expected results

Can it be changed again at 4.9.1 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I would like to see that change

**Comment by GregValiant** [comment] 2021-05-01 21:15
This is from your printer definition file in "...\Ultimaker Cura 4.x.x\resources\definitions"
"author": "Cataldo URSO & Eddy Emck ",
        "manufacturer": "FLSUN",
        "platform": "flsun_qq_s.3mf"
The platform "flsun_qq_s.3mf" is in "...\Ultimaker Cura 4.x.x\resources\meshes".  I suppose you could alter that file by rotating the platform in MS Builder or something similar.  In the definition file, if you leave the platform as an empty string **"platform: ""** then you would see just the build plate in Cura.

**Comment by fvrmr** [comment] 2021-05-03 07:30
Hi @JohanPluister thank you for your report. This is a duplicate of #9687 
You could try the work around @GregValiant is suggesting or mine here: https://github.com/Ultimaker/Cura/issues/9687#issuecomment-826850461
I will close this issue since it is a duplicate. But please reach out if you have more questions.

**Closed by fvrmr** 2021-05-03 07:30 UTC
Labels: Type: Bug
