### ISSUE TITLE
M104 S{material_print_temperature} order of precedence not correct - fdmprinter.def.json

### ISSUE THREAD

**Issue by zyphermonkey** [Ultimaker/Cura#3032] opened 2017-12-22 12:28 UTC
**Application Version**
3.1

**Platform**
Windows 10 64-bit

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**
I have M104 S{material_print_temperature} set in my start Gcode under machine settings. No matter what temperature I set  "Default Printing Temperature" or "Printing Temperature" to in cura the value always gets set in the outputted Gcode to the value found in fdmprinter.def.json. 

### fdmprinter.def.json
"default_material_print_temperature":
                {
                    "label": "Default Printing Temperature",
                    "description": "The default temperature used for printing. This should be the \"base\" temperature of a material. All other print temperatures should use offsets based on this value",
                    "unit": "°C",
                    "type": "float",
                    "default_value": 210,
                    "minimum_value_warning": "0",
                    "maximum_value_warning": "285",
                    "enabled": "machine_nozzle_temp_enabled",
                    "settable_per_extruder": true,
                    "settable_per_mesh": false,
                    "minimum_value": "-273.15"
                },
                "material_print_temperature":
                {
                    "label": "Printing Temperature",
                    "description": "The temperature used for printing.",
                    "unit": "°C",
                    "type": "float",
                    "default_value": 210,
                    "value": "default_material_print_temperature",
                    "minimum_value": "-273.15",
                    "minimum_value_warning": "0",
                    "maximum_value_warning": "285",
                    "enabled": "machine_nozzle_temp_enabled and not (material_flow_dependent_temperature)",
                    "settable_per_mesh": false,
                    "settable_per_extruder": true
                }

### Cura
Default Printing Temperature: 200
Printing Temperature: 200

### Machine Settings>Start Gcode
M104 S{material_print_temperature} ;Start heating extruder
M140 S{material_bed_temperature}   ;Start heating bed
M109 S{material_print_temperature} ;Wait for extruder to reach temp before proceeding
M190 S{material_bed_temperature} ;Wait for bed to reach temp before proceeding

**Actual Results**
M104 S210 ;Start heating extruder
M140 S60   ;Start heating bed
M109 S210 ;Wait for extruder to reach temp before proceeding
M190 S60 ;Wait for bed to reach temp before proceeding

**Expected results**
M104 S200 ;Start heating extruder
M140 S60   ;Start heating bed
M109 S200 ;Wait for extruder to reach temp before proceeding
M190 S60 ;Wait for bed to reach temp before proceeding

**Additional Information**
Interesting enough changing the bed temperature in cura produces the correct results in the exported Gcode.
LogFile [https://pastebin.com/kEQsrav9](url)

**Comment by ChrisTerBeke** [comment] 2017-12-22 12:36
Duplicate of https://github.com/Ultimaker/Cura/issues/1296.

**Closed by ChrisTerBeke** 2017-12-22 12:36 UTC
