### ISSUE TITLE
Settings for Anycubic 4Max wrong

### ISSUE THREAD

**Issue by Mike1960** [Ultimaker/Cura#6158] opened 2019-08-05 22:08 UTC
**Application version**
Cura 4.2.1

**Platform**
Win10 64bit

**Printer**
Anycubic 4Max

**Reproduction steps**
setting temperature for PETG (230°C) in the filament setup gives 265°C in the printing menue

**Additional information**
opened the basic settings (eg. printer profile) with editor and found for temperature + 35°C

**Comment by Vandrasc** [comment] 2019-08-06 08:28
Hi @Mike1960 , correct, you adjusted the Default printing Temperature which is the base temperature and all other printing temperatures are based on this value. The Default printing temperature value will affect the Printing Temperature, in this case, +35 as given in the profile, that is also the case in previous versions. 

You can adjust the Printing Temperature setting in the Material category in Custom and it will not be affected by the default value. 

Hope this helps! 

I will close this ticket, as it is the intended behavior, but please feel free to reopen if I misunderstood the issue. Thank you for your feedback!

**Closed** 2019-08-06 08:28 UTC
Labels: Type: Bug
