### ISSUE TITLE
[3.4.1] Brim on inside goes outside the buildplate to infinity

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#4165] opened 2018-07-31 20:33 UTC
**Application Version**
3.4.1 (also 3.4.0)

**Platform**
win7 64bit

**Printer**
Custom FDM printer
(Wanhao Di3)

**Steps to Reproduce**
Load my project file and slice with the "brim only on outside" checkbox unchecked.
Each time I slice this I get different magnitudes of the issue. Rechecking and unchecking the box gives a new pattern and print-time when sliced again. 
Slicing with it checked works as intended.

**Actual Results**
The brim goes out of the build area and adds a lot to the print time an material used, See attached pictures

**Additional Information**
I have checked the stl with Meshmixer for errors.
I attached pictures and my project-file
![skarmklipp](https://user-images.githubusercontent.com/32172100/43484682-52219bda-950f-11e8-90c2-7155e9dff303.PNG)
![skarmklipp2](https://user-images.githubusercontent.com/32172100/43485219-e00b2eba-9510-11e8-99fb-e03a9dc62325.PNG)

[Brim_inside_issue.curaproject.zip](https://github.com/Ultimaker/Cura/files/2246936/Brim_inside_issue.curaproject.zip)

Let me know if I need to add more info.

**Comment by BagelOrb** [comment] 2018-08-02 11:35
I cannot reproduce this on current master, but I cannot load the project file in 3.4.1.

That being said, such a bug could be specific to your computer hardware setup.

Can you attach the gcode?
It could be the problem is in the visualization only.
Here's a nice online gcode viewer you don't need any installation for: http://www.chilipeppr.com/tinyg

**Comment by printingotb** [comment] 2018-08-02 13:14
Thanks for the reply! 
I started the print and it did actually try to travel outside the buildplate. It was travelling and not extruding. Probably on it's way to start extruding at the other end of the line.
It was also printing a "cross" on top of the already printed brim (at same layer).
Here is the G-code I just ran:
[Buggy.zip](https://github.com/Ultimaker/Cura/files/2253574/Buggy.zip)
And here is the stl (I made a new similar to the original since customer project, both have the issue):
[BrimIssue.zip](https://github.com/Ultimaker/Cura/files/2253607/BrimIssue.zip)
![img_20180802_150542](https://user-images.githubusercontent.com/32172100/43585618-db03d344-9665-11e8-875f-4d605ad9b0bd.jpg)

**Comment by BagelOrb** [comment] 2018-08-02 13:25
There's definitely something wrong in master:
![image](https://user-images.githubusercontent.com/8895761/43586544-323e3364-9668-11e8-93da-0475b3ae5bae.png)

**Comment by BagelOrb** [comment] 2018-08-02 13:29
The problem was most probably introduced in f06302c359ff3706c5ec3dd7d63061c42fb9e8a3 by @alekseisasin

**Comment by BagelOrb** [comment] 2018-08-02 13:39
Scrap those comments, I was looking at the wrong layer ^^

**Comment by BagelOrb** [comment] 2018-08-02 14:28
Oh this was already fixed. See https://github.com/Ultimaker/Cura/issues/4009. Fixed in https://github.com/Ultimaker/CuraEngine/commit/af07b7cee963953b64fc3eb7cddbd06b6222130a

**Closed** 2018-08-02 14:29 UTC
Labels: Category: Engine, Type: Bug

**Comment by printingotb** [comment] 2018-08-02 15:42
Perfect, thanks! Didn't see that one.
