### ISSUE TITLE
UI addition

### ISSUE THREAD

**Issue by mikeoverbay** [Ultimaker/Cura#9564] opened 2021-04-11 16:21 UTC
### Is your feature request related to a problem?

no

### Describe the solution you'd like

It would be really handy to have the current Z displayed for the current slice you are previewing. Beside the slice number would be good. It is just (slice thickness * layer number) correct?

### Describe alternatives you've considered

Doing the math by hand

### Affected users and/or printers

any and all

**Comment by jellespijker** [comment] 2021-04-11 18:45
Duplicate of #7576 closing this thread in favor of that one.

**Closed by jellespijker** 2021-04-11 18:45 UTC
Labels: Type: New Feature
