### ISSUE TITLE
[4.6.1] "Brim" et. al. reduces the maximum model size, even when the bottom layer is well within limits 

### ISSUE THREAD

**Issue by bugpwr** [Ultimaker/Cura#7728] opened 2020-05-10 01:45 UTC
**Application version**
4.6.1 and before

**Platform**
Windows

**Printer**
UM3

**Reproduction steps**
1. Take a large model with relatively small bottom layer but large projection, that really scratches the limits of the printer.
2. Make sure the bottom that touches the build plate is well within limits
3. Switch build adhesion from "none" to "brim". You can no longer print it, even though brim would do just fine.

**Screenshot(s)**
Uploaded.

**Actual results**
The situation limits the build model size when it did not have to. 

**Expected results**
The grayed "impossible areas" would only affect the bottom layer, not the rest of the model. For the rest of the model areas should be a subset, not affected by adhesion settings.

**Project file**
Try enabling brim in this project file
[UM3_ultimaker_RSspool_holder - Part 1 (6).zip](https://github.com/Ultimaker/Cura/files/4604998/UM3_ultimaker_RSspool_holder.-.Part.1.6.zip)

**Log file**
Irrelevant. Easy to reproduce

**Additional information**
Just a tiny (peaceful) rant - with small printers such as UM3, every millimeter counts. I would rather add an option "temporary disregard all limits" to let user take the responsibility, with a warning about a potential damage to the machine, to prevent this and other issues.

**Comment by Ghostkeeper** [comment] 2020-05-12 13:02
Duplicate of https://github.com/Ultimaker/Cura/issues/6946 . 

You can sort of "temporarily ignore all limits" by making the printer bigger in the Printer Settings dialogue, but you can't easily make the printer bigger in the negative coordinate space. The only way to do that is to make the printer more than twice as big and set the coordinate origin to be in the centre.

**Closed by Ghostkeeper** 2020-05-12 13:02 UTC
Labels: Type: Bug
