### ISSUE TITLE
printer setting bug

### ISSUE THREAD

**Issue by xia01eng** [Ultimaker/Cura#3549] opened 2018-03-24 13:40 UTC
![image](https://user-images.githubusercontent.com/31816340/37864539-95c0a238-2fab-11e8-8eb7-93465816d5eb.png)
As shown in this picture, every time you close the cura application the nozzle size configuration just cannot be stored. Thus every time I restart cura, I have to change that setting. It's really ... . Hope to fix that bug.

**Comment by fieldOfView** [comment] 2018-03-24 18:04
A screenshot shows us nothing in this case. Please locate and share your logs (cura.log in the configuration folder)

**Comment by xia01eng** [comment] 2018-03-25 14:09
Sorry, where to find configuration folder. OSX

**Comment by xia01eng** [comment] 2018-03-25 14:10
@fieldOfView

**Comment by xia01eng** [comment] 2018-03-25 14:40
Unfortunately, it did not display any information about this issue in the log. But just like I described before, this problem did exist.

**Comment by Thisismydigitalself** [comment] 2018-03-25 15:38
> this problem did exist. 

> 
Still exists in 3.2.1.
You mean fixed in 3.3? any ETA for 3.3?

**Comment by ianpaschal** [comment] 2018-03-26 09:13
Duplicate of #3511.

This is fixed and will be in the 3.3 beta released this week.

**Closed by ianpaschal** 2018-03-26 09:13 UTC
Labels: Category: Cura, Status: Duplicate, Type: Bug
