### ISSUE TITLE
Support structure is generated in the part

### ISSUE THREAD

**Issue by brandlc** [Ultimaker/Cura#11382] opened 2022-01-30 12:11 UTC
### Application Version

4.13.0

### Platform

Windows 10

### Printer

Formbot T-rex 3

### Reproduction steps

For components that need to generate hollow and support structures inside, support structure is also generated inside the component. The error only occurs with tree supports.

### Actual results

![7afb5ed9-0c7c-4039-81f7-b7b758f4040c](https://user-images.githubusercontent.com/98691499/151698568-ff83f456-37a0-4cde-89be-c7567ea426f1.jpg)
![937f8ca3-f39f-4f0f-aa14-3341463c8fcf](https://user-images.githubusercontent.com/98691499/151698574-c0336afe-9914-47d0-9289-e46d270b111c.jpg)
![2aa4e2a5-afa0-4a98-821b-32fdb40a1a42](https://user-images.githubusercontent.com/98691499/151698579-6410d09b-625d-4163-84a8-86d592b3e5f0.jpg)

### Expected results

Support structures should not be printed in the component, but on top of it if necessary.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

![2aa4e2a5-afa0-4a98-821b-32fdb40a1a42](https://user-images.githubusercontent.com/98691499/151698882-b030446f-e228-495d-bb2f-27fe78ab41c2.jpg)
![7afb5ed9-0c7c-4039-81f7-b7b758f4040c](https://user-images.githubusercontent.com/98691499/151698885-c48cf4c8-8912-4e57-bf40-f7d16530ceb7.jpg)
![937f8ca3-f39f-4f0f-aa14-3341463c8fcf](https://user-images.githubusercontent.com/98691499/151698888-47d90353-aafb-4ff9-a1a2-14c07af3e7be.jpg)

**Comment by GregValiant** [comment] 2022-01-30 13:51
There is an emergency Cura release to fix this.  @fvrmr's post on the [ULTIMAKER FORUM](https://community.ultimaker.com/topic/39459-ultimaker-cura-4131/#comment-302241) has the download link to 4.13.1.

**Comment by fvrmr** [comment] 2022-01-31 10:00
Hi @brandlc thank you for your report.
This is indeed fixed in 4.13.1 and this issue is a duplicate of https://github.com/Ultimaker/Cura/issues/11258
You can download 4.13.1 here: https://ultimaker.com/software/ultimaker-cura
I will close this issue.

**Closed by fvrmr** 2022-01-31 10:00 UTC
Labels: Type: Bug
