### ISSUE TITLE
Minicooper

### ISSUE THREAD

**Issue by Matyasgo** [Ultimaker/Cura#16820] opened 2023-09-25 21:54 UTC
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Hellbot Hidra 220

### Name abnormal settings

No

### Describe model location

No

### Describe your model

Modelo dual color

### Add your .zip here ⬇️

[Proyecto Mini_2.zip](https://github.com/Ultimaker/Cura/files/12719685/Proyecto.Mini_2.zip)

**Comment by GregValiant** [comment] 2023-09-26 11:02
Thanks for the report and the file.
This looks to be a duplicate of the often reported slicing bug in 5.4.0.  I'll mark it as a duplicate and close it as the Cura team hs lots of examples of this behavior.  I hope you understand.

There are three workarounds to fool the bug.  I had to use all three and setting the Initial Layer Height to .20 finally allowed it to slice.

- Rotate the model
- Move the model
- Change the Initial Layer Height by a little bit.

Here I've done all three.
![image](https://github.com/Ultimaker/Cura/assets/64202104/2405ec73-fe5f-4ac6-bb7a-ecd29eca8c3a)

**Closed by GregValiant** 2023-09-26 11:02 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error :collision:
