### ISSUE TITLE
Cura should begin printing on the outer side of the object

### ISSUE THREAD

**Issue by dr4Ke** [Ultimaker/Cura#2440] opened 2017-09-16 10:39 UTC
I've got a model that have an open outside, so that the brim is printed on the outside and near the center of the model. The issue is that it starts to print the brim at the most inner point, not the most outer. So it prints over the filament extruded during the travel from oozing point to the print start point.
I think the start point should always be at the outer of the model. The closer to the oozing point, the better. What do you think?

I use a third party printer:
![cura_fabtotum](https://user-images.githubusercontent.com/128122/30511548-d063ea04-9adb-11e7-9eae-1fb1f984ba22.png)

I tried with a Ultimaker 3:
![cura_ultimaker](https://user-images.githubusercontent.com/128122/30511551-d2165440-9adb-11e7-93b2-71290a48329b.png)

Notice the first travel trace through the model to the inner side of the brim.

**Comment by MikeTough** [comment] 2017-09-18 14:06
Had the same issue. Brim creation inside to outside caused a 20mm gap at the begining of the travel leaving brim unattached to the part, resulting in failed print. This is worthy of fixing/further investigation.

**Comment by Ghostkeeper** [comment] 2017-09-24 14:24
Even if you print from outside to the inside, there will still be a travel move because it's moving to the Z seam location.

**Comment by dr4Ke** [comment] 2017-09-24 18:48
It's not all travel moves that bothers me. It's the initial one, because it carries unused filament, not attached to the bed. And when it tries to print over this filament, there's a good chance that this filament will be hurt by the nozzle, preventing the brim to attach on the bed.
On the subsequent travel moves, there is only a thin remaining of filament and it's OK.

**Comment by Ghostkeeper** [comment] 2017-10-01 12:24
I'm a bit worried that this will change all of the tensions in the brim. It might be for the better, or might be for the worse. Only some testing will give an answer, I guess.

**Comment by ChrisTerBeke** [comment] 2018-03-02 21:11
There's a setting for this. By default we don't do it because it gives poor printing results.

**Comment by Ghostkeeper** [comment] 2018-03-26 12:40
Which setting is that then? As far as I know there is no setting for where to start with the brim.

**Comment by hamster65** [comment] 2019-01-19 12:36
I'd like to know which setting it is, too. My brim starts at the walls when the nozzle has not been primed. So the brim is not connected to the object, which then warps or comes loose (Cura 3.6.0)

**Comment by tioteath** [comment] 2019-03-26 23:58
This is the real issue on Endre-3. After this initial travel, the head hits this single line of filament each time it goes around printing Brim. This causes visible defect on the print and wears down printer parts.

**Comment by Ghostkeeper** [comment] 2019-03-28 15:17
There is no setting for where to start with the brim. It should take the brim line that is closest to the initial nozzle position first. Usually that would be the outermost brim.

As far as I could reproduce, it's always starting with the outermost brim using default settings.

**Closed** 2020-06-20 01:49 UTC
Labels: Category: Engine, Status: Needs Info
