### ISSUE TITLE
I can't remove screensaver

### ISSUE THREAD

**Issue by TriKriSta** [Ultimaker/Cura#6058] opened 2019-07-25 14:40 UTC
I installed the program (v 4.0.0)

The program showed me screensaver
`Welcome to Ultimaker Cura
Please follow these steps to set up Ultimaker Cura. This will only take a few moments`

But it doesn't disappear and I cannot remove it

**Comment by Vandrasc** [comment] 2019-07-25 14:57
Hi @TriKriSta , do you mean the installation window?  Could you please share a screenshot with us, so we can get a better understanding of what your issue is? I guess you are using Windows? And are you using the 4.0 version or Cura 4.1?

**Comment by TriKriSta** [comment] 2019-07-25 15:07
I tryed to install both versions 4.0 and 4.1.
I'm using Arch Linux.
![Screenshot_20190725_180351](https://user-images.githubusercontent.com/2956022/61885657-dd5c7780-af06-11e9-9f29-af22dc1e80fd.png)

**Comment by fieldOfView** [comment] 2019-07-25 15:53
Try the AppImage. That is currently the only supported version on Linux. There are some issues between Cura and Qt 5.13 which is installed on your system. The AppImage doesn’t have those issues.

**Comment by elbowz** [comment] 2020-02-17 17:25
I found here: https://bugs.archlinux.org/task/62133?project=5&string=cura
a possible workaround to start cura without issue:

`env -u DESKTOP_SESSION -u KDE_FULL_SESSION -u XDG_CURRENT_DESKTOP cura`

**Comment by mahtDFR** [comment] 2020-02-18 10:59
Closing this for reasons above

**Closed by mahtDFR** 2020-02-18 10:59 UTC
Labels: Status: Needs Info, Type: Bug

**Comment by JohannCahier** [comment] 2020-08-01 18:39
Hey DAWGS..

**Comment by JohannCahier** [comment] 2020-08-01 18:40
That's a fucking showstopper....

**Comment by fieldOfView** [comment] 2020-08-01 18:57
Yo DAWG, try the AppImage. That is currently the only supported version on Linux. There are some issues between Cura and Qt 5.13 which is installed on your system. The AppImage doesn’t have those issues.

**Comment by JohannCahier** [comment] 2020-08-04 11:23
Thanks for the answer. I was meaning : using AppImages IS the showstopper to me. More for political / system maintenance policy reason than technical ones.

I was I bit tired I think, I didn't saw @elbowz answer, that works for me (at least I have the "Get Started" button back, I can browse a few screens... Seems way better).

I keep in mind I may meet instabilities... 

BTW : I'll rather try to built it from sources, before going with an AppImage ! 
I'm surprized there is no recipe for that in the AUR already...

**Comment by nallath** [comment] 2020-08-04 11:52
Dependency issues were the main reason we moved away from .deb images. Conceptually it's a great idea to share dependencies, but in practice, it just doesn't work in all cases (especially if you have a hard dependency on a specific version of a lib).

So it's a bit more data that you're pumping around if you use an appimage, but at least you control what exact configuration is being used (which also decreases the difficulty in finding issues caused by dependency version interplay). 

I'm not aware of any political reasons not to do something with AppImages. Did I miss something?

**Comment by JohannCahier** [comment] 2020-08-04 16:46
Hey @nallath.

Indeed "political" was a bit overkill, take it as irony...
The "system maintenance policy" stated is my previous reply (which lacks a bit of editing), is more accurate.

If you want a "political" aspect of this : I like "green computing", and clearly loading multiple versions of the same lib is a given machine RAM is not "green". 

I don't have any problem with the distribution solution you choose. It's open source, so I can recompile it. 

I'am a bit puzzled I had to land to land here, after the only PKGBUILD if found on the AUR downloaded a binary package...

Maybe it's a call to contribute to the AUR with a "clean" cura-git package.

And maybe i'll change my mind for some reason in the next few days : i'm very new to 3D printing, so i'll learn a lot the next days/weeks.

Don't worry for me,

Many greets to your community and see you soon :)

**Comment by JohannCahier** [comment] 2020-08-04 16:52
@nallath : a .deb distro package wouldn't have solved my problem anyway :)

Thanks for the comment !

**Comment by Ghostkeeper** [comment] 2020-08-05 15:27
We'd welcome fixes necessary to make it work with Qt 5.15, as long as they don't break compatibility with the Qt 5.10 that we ship with the Windows builds, MacOS builds and the AppImage.

**Comment by KiralyCraft** [comment] 2020-12-19 13:01
elbowz's workaround is just fine for me. Running Manjaro KDE with Qt 5.15. Many thanks!

**Comment by electronoob** [comment] 2021-01-05 02:01
worked for me also, edited the shortcut for cura, nice nice. thank you.

**Comment by 983** [comment] 2021-05-12 09:09
This issue also occurs on Kubuntu 20.04. The blue `Get started` button simply does not show up. I think this issue should be reopened until `sudo apt install cura` actually installs a working version of cura.

**Comment by Ghostkeeper** [comment] 2021-05-20 07:44
We did fix this issue. Since Cura 4.9 we are using Qt 5.15, so Cura is expected to work with Qt 5.15 now.

Only [the package maintainer didn't update it yet](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=cura&searchon=names). Again, we don't maintain those packages. It's not under our control. We just provide the AppImage.

**Comment by 983** [comment] 2021-05-20 08:10
Great, then we know where to continue. Thanks!
