### ISSUE TITLE
Defacing with 4K NON-HiDPI display

### ISSUE THREAD

**Issue by sl1pkn07** [Ultimaker/Cura#6000] opened 2019-07-11 15:59 UTC
**Application version**
GIT 6941af002

**Platform**

Archlinux
Nvidia RTX2060 with latest vulkan drivers
Asus PB287Q

display info:

~~~
quoted from https://www.asus.com/us/Commercial-Monitors/PB287Q/:

with resolution up to 3840 by 2160. With a pixel density of 157 pixels-per-inch (PPI),
https://www.asus.com/us/Commercial-Monitors/PB287Q/specifications/

Display Viewing Area(HxV) : 620.93 x 341.28 mm


└───╼  xdpyinfo | grep -B1 dots
  dimensions:    3840x2160 pixels (621x341 millimeters)
  resolution:    157x161 dots per inch
└───╼  xrandr | grep ' connected'
DP-1 connected primary 3840x2160+0+0 (normal left inverted right x axis y axis) 621mm x 341mm
~~~

**Printer**

**Reproduction steps**
build from GIT and run it

**Actual results**
![Screenshot_20190711_174643](https://user-images.githubusercontent.com/462213/61065404-db24f400-a403-11e9-9574-e0542dcf5678.png)
![Screenshot_20190711_180654](https://user-images.githubusercontent.com/462213/61066905-b5e5b500-a406-11e9-9b24-0978b2134772.png)

**Expected results**
IDK ,because i can't disable the HiDPI support with the QT environment variables
https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt or cura settings

**Additional information**

Qt 5.13 from repos (archlinux)
uranium and curaneguine from GIT
dark or light theme doesn't matter

**Comment by fieldOfView** [comment] 2019-07-11 16:15
Please try the AppImage from software.ultimaker.com

**Comment by sl1pkn07** [comment] 2019-07-11 16:33
seems look good

![Screenshot_20190711_183228](https://user-images.githubusercontent.com/462213/61068412-3fe34d00-a40a-11e9-8bfb-8560dfb73d38.png)

upscaled, but without defacing

**Comment by fieldOfView** [comment] 2019-07-11 18:24
In that case, this is a duplicate of https://github.com/Ultimaker/Cura/issues/5487

Cura is tested with Qt 5.10, you are using a newer version. Ultimaker only supports the AppImage version for Linux.

**Comment by Ghostkeeper** [comment] 2019-07-12 07:12
Yes, those are bugs that seem to arise from Qt 5.12+. We require 5.10 right now.

**Closed by Ghostkeeper** 2019-07-12 07:12 UTC
Labels: Type: Bug
