### ISSUE TITLE
Z Seam Alignment(Sharpest Corner) must not consider fuzzy skin

### ISSUE THREAD

**Issue by wolfgangmauer** [Ultimaker/Cura#11548] opened 2022-02-25 23:11 UTC
### Application Version

4.12.1

### Platform

Windows 10

### Printer

Any

### Reproduction steps

Set Z-seam alignment to sharpest corner(fuzzy skin off)  and slice
Set fuzzy skin on, now the startpoint from walls are changed

### Actual results

Z-seam alignment(sharpest corner) changes when activating fuzzy skin

### Expected results

Z-seam alignment(sharpest corner) remains the same with or without fuzzy skin

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads
Set Z Seam Alignment(Sharpest Corner) and Fuzzy Skin on
![grafik](https://user-images.githubusercontent.com/27953724/155838965-67d84ad0-42ff-48e0-855b-6ae5e63b7aff.png)

Set Z Seam Alignment(Sharpest Corner) and Fuzzy Skin off
![grafik](https://user-images.githubusercontent.com/27953724/155839022-e0a49dd4-236f-458f-8091-2325fd5dd076.png)

For all printers, for all models

**Comment by wolfgangmauer** [comment] 2022-03-03 15:11
Hi @fvrmr,
but that means Z Seam Alignment dont work, alignment will be always random on Fuzzy Skin ?!

**Comment by fvrmr** [comment] 2022-03-04 12:03
I have discussed it with the team and this is indeed expected behaviour, the fuzzy skin places the seam in the sharpest corner of that layer and since the fuzzy skin creates random jitters it will align random. 
We also decided that this is something we do not want to change. So I will close this issue, but let me know if you have questions.

**Closed by fvrmr** 2022-03-04 12:03 UTC
Labels: Type: Bug

**Comment by wolfgangmauer** [comment] 2022-03-04 21:25
No problem, with prusaslicer i can use the seam painting even with fuzzy skin
