### ISSUE TITLE
[3.2.1]  Loading shorter model first followed by taller model cuts the taller model to shorter model height

### ISSUE THREAD

**Issue by vernieg** [Ultimaker/Cura#3468] opened 2018-03-10 13:15 UTC
[3.2.1]  Loading shorter model first followed by taller model cuts the taller model to shorter model height

**Application Version**
3.2.1

**Platform**
Linuxmint 8.3

**Printer**
Anycubic i3 Mega

**Steps to Reproduce**
Load a shorter height model file on the build plate. Load another taller model file. Go to Layer view.

**Actual Results**
Maximum printable layers is only that of the shorter model.  Loading a taller model first then shorter second will makes all printable.
This has been replicated many times with .stl or .obj files.

**Expected results**
All models should be printable at their full height.

**Additional Information**
![screenshot from 2018-03-10 21-11-29](https://user-images.githubusercontent.com/37242799/37242626-cc04515a-24a7-11e8-8bb4-4648e5f20b44.png)

**Comment by smartavionics** [comment] 2018-03-10 13:18
Hi, could you please make those models available so I can try and recreate the problem? Thanks.

**Comment by ianpaschal** [comment] 2018-03-10 13:32
Are you using adaptive layers? If so, this is a known bug we're working on.

**Comment by vernieg** [comment] 2018-03-10 13:36
Yes, just noticed it now, this only trigger on using adaptive layers. Thank you.

**Comment by ianpaschal** [comment] 2018-03-10 13:39
Duplicate of #3318.

**Comment by ianpaschal** [comment] 2018-03-10 13:40
This will be fixed in 3.3.

**Closed by ianpaschal** 2018-03-10 13:39 UTC
