### ISSUE TITLE
Cura 2.7.0 Beta - Inability to select COM: Port for Custom FDM Printer

### ISSUE THREAD

**Issue by TheOriginalFreddoFrog** [Ultimaker/Cura#2267] opened 2017-08-13 00:09 UTC
Hi,

If you have multiple COM: ports connected to your PC, and say have another COM: powered device (i.e say a radio transceiver or multi-port COM: module for connecting to routers) the software does NOT necessarily pick up the Marlin-powered device and tries to communicate with other devices instead...

There is a necessity for manual COM: port selection for communication to the device to be made more obvious (or provided full stop !!!)

Regards

Freddo

**Comment by Ghostkeeper** [comment] 2018-01-15 09:30
Let's close this as duplicate of #1049.

**Closed by Ghostkeeper** 2018-01-15 09:30 UTC
Labels: enhancement
