### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Formware** [Ultimaker/Cura#489] opened 2015-10-17 09:37 UTC
Version: 15.06.03
Platform: Windows-8-6.2.9200
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "cura_app.py", line 9, in <module>
  File "c:\dev\uranium\UM\Application.py", line 329, in getInstance
  File "c:\dev\cura\cura\CuraApplication.py", line 56, in __init__
  File "c:\dev\uranium\UM\Qt\QtApplication.py", line 76, in __init__
  File "c:\dev\uranium\UM\Application.py", line 355, in loadMachines
  File "c:\dev\uranium\UM\Settings\MachineSettings.py", line 87, in loadValuesFromFile
  File "c:\dev\python34\lib\configparser.py", line 672, in read
  File "c:\dev\python34\lib\configparser.py", line 1044, in _read
configparser.DuplicateSectionError: While reading from 'C:\\Users\\Formware/AppData/Local/cura\\settings\\Ultimaker+2.cfg' [line 39]: section 'blackmagic' already exists

**Comment by Ghostkeeper** [comment] 2015-10-18 14:38
This is a duplicate of #346, #389, #428, #454, #458 and #476. Version 15.06 created corrupt configuration files when the Python environment is interrupted while it is writing that file, or when multiple instances of Cura are writing to it at the same time. This issue is fixed in version 15.10.

To fix your Cura version, delete the file mentioned in your traceback: C:\Users\Formware\AppData\Local\cura\settings\Ultimaker+2.cfg. Cura will then create it anew, but you will lose your machine settings for Ultimaker 2. You could also try and open that file with a text editor such as Notepad to try to mend it, if you're feeling adventurous and really don't want to lose your settings.

**Closed** 2015-10-18 14:38 UTC
Labels: duplicate
