### ISSUE TITLE
[XUbuntu 22.04.1 LTS] - Cura not adding file extensions when saving/exporting anything

### ISSUE THREAD

**Issue by InstantMuffin** [Ultimaker/Cura#14235] opened 2023-01-07 18:58 UTC
### Application Version

5.2.1

### Platform

XUbuntu 22.04.1 LTS

### Printer

Any

### Reproduction steps

You save a project, export, or save a gcode file.

### Actual results

The file will be saved without any extension.

### Expected results

For the file to be saved with the appropriate file extension

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I assume this is a Linux, or probably XUbuntu-only issue due to no one else reporting it.

This wouldn't be too much of an issue in itself, but Cura uses the file's extension at least as a first barrier for opening it. The current behavior therefore makes it impossible to open the file/project with Cura unless you rename it yourself and add the appropriate extension.

**Comment by MariMakes** [comment] 2023-01-09 13:21
Hey @InstantMuffin,

Thanks for your report 👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12659
We have a ticket on our backlog with the intent to improve this behavior.
I'll ask the team to take a look again since we've been getting quite a number of reports on this issue. 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12659

**Closed by MariMakes** 2023-01-09 13:21 UTC
Labels: Type: Bug, Status: Triage
