### ISSUE TITLE
Slicing tree supports error: Failing to discretize parabola! Must add an apex or one of the endpoints.

### ISSUE THREAD

**Issue by p-wysocki** [Ultimaker/Cura#15229] opened 2023-04-13 15:43 UTC
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Custom profile for Qidi X-Max II

### Reproduction steps

I added tree supports with `Support placement: Touching Buildplate`. Once I changed that option to `Everythere` slicing fails with:

`[warning] Failing to discretize parabola! Must add an apex or one of the endpoints.`

If that's something that could be a good fit for a first issue please let me know, I can try to contribute in my spare time.

### Actual results

An uncaught error is raised.

### Expected results

Succesful slice.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

GitHub didn't let me attach the files separately due to their extensions, I hope a .zip is alright.
[Cura_issue.zip](https://github.com/Ultimaker/Cura/files/11223956/Cura_issue.zip)

**Comment by Vandresc** [comment] 2023-04-28 10:05
Hi @p-wysocki, thank you for your feedback! The issue is not reproducible for me in the main build, meaning the issue is already fixed for future 5.4. I will close this ticket for now but if the issue still reproduces for you in the next release please re-open.

**Closed by Vandresc** 2023-04-28 10:05 UTC
Labels: Type: Bug, Status: Triage
