### ISSUE TITLE
Entering rotation degrees manually instead of only snapping to predefined values!

### ISSUE THREAD

**Issue by RalfZgeib** [Ultimaker/Cura#12521] opened 2022-06-14 18:42 UTC
### Is your feature request related to a problem?

One can't rotate a part by certain values needed. Only predefined values exist with snap rotations. That's very limiting!

### Describe the solution you'd like

Add an input box for each axis of rotation that allows the user to input custom values for rotation.

### Describe alternatives you've considered

Can open an input box when clicking on the rotation rings around the object if needed.

### Affected users and/or printers

All users and printers.

**Comment by nallath** [comment] 2022-06-15 08:42
Duplicate of #2779

**Closed by nallath** 2022-06-15 08:42 UTC
Labels: Type: New Feature
