### ISSUE TITLE
3D view becomes grey when opening STL file

### ISSUE THREAD

**Issue by MarijnHeeren** [Ultimaker/Cura#403] opened 2015-09-19 13:13 UTC
Application Version: 15.06.03
Platform: OS X 10.10.5

Steps to Reproduce:
Load an STL. Right after it loads the 3D view becomes grey.

Actual Results:
3D view is grey. You can click it and see the controls to move an object. See below:
<img width="983" alt="schermafbeelding 2015-09-19 om 15 12 02" src="https://cloud.githubusercontent.com/assets/14360569/9976321/ded17a4a-5ee0-11e5-9a2c-47422789721f.png">

Expected results:
See the object, see the build platform.

**Comment by nallath** [comment] 2015-09-19 13:20
Could you try if it works with 15.09.82? You can find it at software.ultimaker.com/Cura_closed_beta/15.10/

**Comment by nallath** [comment] 2015-09-23 09:56
And the next version is also up. Could you check if it works there?

**Comment by awhiemstra** [comment] 2015-09-23 10:10
This is a duplicate of #110 that was already fixed.

**Closed by awhiemstra** 2015-09-23 10:10 UTC
Labels: bug
