### ISSUE TITLE
dont want to slice

### ISSUE THREAD

**Issue by crusty777** [Ultimaker/Cura#12957] opened 2022-08-05 05:55 UTC
### Application Version

5.1.0

### Platform

windows 10 nvidia rtx 2060 super

### Printer

ender3 pro

### Reproduction steps

cura wont slice my stl file, a windows appear instantly for bug report
![bug](https://user-images.githubusercontent.com/25441768/183009682-8df0ee01-91d8-489f-8085-64f6d93a979a.PNG)
 

### Actual results

dont want to slice

### Expected results

slice my file

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

dont know what to say

**Comment by GregValiant** [comment] 2022-08-05 10:35
Thanks for the report.
The "Crystal Dragon" model has a lot of errors in it.  You can use MS 3D Builder or an on-line STL repair service to fix it.  That will be required before it will slice.  Without having your model I can't tell if it's the exact same dragon.
Load the model and get Cura set up to slice and then use the "File | Save Project" command.  A 3mf file will be created.  Zip the 3mf file and post it here.
I'm going to mark this as a duplicate of #12546.  I'll leave this open for now so you can respond but it's likely that this is a model issue.

**Closed** 2022-08-19 12:06 UTC
Labels: Type: Bug, Status: Duplicate, Status: Needs Info, Status: Under Investigation
