### ISSUE TITLE
[4.8] Superfluous unsupported infill

### ISSUE THREAD

**Issue by Epicurusismyhomeboy** [Ultimaker/Cura#8750] opened 2020-11-12 22:33 UTC
**Application version**
4.8

**Platform**
Win10

**Printer**
Ender 3

**Reproduction steps**
When slicing a specific model in 4.8, 21 layers in I get two layers of unsupported infill across the entire model despite there being no geometry that requires it. If I increase my wall count from 2 to 3, those two layers of unsupported infill disappear. This cannot be reproduced in 4.7.1 or 4.6.

**Screenshot(s)**
Cura 4.8
![cura4 8](https://user-images.githubusercontent.com/74383726/99003108-63cd0c00-24f2-11eb-8e40-8c84f3cdc721.JPG)
Cura 4.7.1
![Cura4 7](https://user-images.githubusercontent.com/74383726/99003165-7c3d2680-24f2-11eb-8810-5d0f745dad4c.JPG)

**Actual results**
Terrible terrible things happen.

**Expected results**
There should be no unsupported infill.

**Project file**
[CE3_Ulvheim_Building_roof.zip](https://github.com/Ultimaker/Cura/files/5533614/CE3_Ulvheim_Building_roof.zip)

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/5533621/cura.log)

**Additional information**
(Extra information relevant to the issue.)

**Comment by konskarm** [comment] 2020-11-13 08:28
Indeed, it reproduces with your model, but I am closing this as a duplicate of https://github.com/Ultimaker/Cura/issues/6728.

**Closed by konskarm** 2020-11-13 08:28 UTC
Labels: Type: Bug

**Comment by konskarm** [comment] 2020-11-13 10:19
This is now in our backlog. Devs see internal ticket CURA-7845.
