### ISSUE TITLE
Scaling parameters bug

### ISSUE THREAD

**Issue by kevinjones4642** [Ultimaker/Cura#3830] opened 2018-05-17 22:37 UTC
Cura 3.3.1

Win7 64

Ultimaker 3

1). Load a part in Cura.
2). Rotate the part. For example, around the x-axis by 90 degrees.
3). Scale the part in Z with the Uniform Scaling box un-checked.

This seems to scale the part correctly, but it reports in the scaling widget that both y and z have been scaled by 102%, but the actual length of the part in y appears to be unchanged.

Cura should report that x was scaled by 100%, y was scaled by 100% and z was scaled by 102%

It appears as if the scaling percentages reflect the un-rotated part, but the dimensions reflect the rotated part

**Comment by ianpaschal** [comment] 2018-05-18 07:31
This is in progress. Devs, see: CURA-5307

**Comment by Ghostkeeper** [comment] 2018-06-21 07:54
Yeah this is a duplicate of https://github.com/Ultimaker/Cura/issues/3625.

**Closed** 2018-06-21 08:15 UTC
Labels: Category: Cura, Status: In Progress, Type: Bug
