### ISSUE TITLE
Possible bug in vase mode - strange even layers

### ISSUE THREAD

**Issue by bartwaw** [Ultimaker/Cura#18277] opened 2024-02-09 07:39 UTC
### Cura Version

every

### Operating System

Windows

### Printer

every

### Reproduction steps

Vase mode generates additional lines in bottom layers - at every second layer.

If we setup vase mode to more bottom layers than one we get every odd layer with uncontrolable look behavior

### Actual results

So first layer is like we set in slicer:
![image](https://github.com/Ultimaker/Cura/assets/7601033/7424165d-8242-4df2-a6cd-bdcac2f6df89)

second one looks like this:
![image](https://github.com/Ultimaker/Cura/assets/7601033/10183b4d-70aa-4963-8615-aaba61343f34)

third again normal:
![image](https://github.com/Ultimaker/Cura/assets/7601033/84e201c7-95ba-4533-b762-9e102acd8520)

4th same as 3th:
![image](https://github.com/Ultimaker/Cura/assets/7601033/4b80ecc8-5972-4484-acd9-e31d5e192435)

### Expected results

even layers should be same as odd layers

### Add your .zip and screenshots here ⬇️

[CFFFP_Part5.zip](https://github.com/Ultimaker/Cura/files/14218565/CFFFP_Part5.zip)

**Comment by smartavionics** [comment] 2024-02-09 08:20
That's how it has always behaved when spiralizing. It's a feature, not a bug. I forget the reasoning behind the extra walls.

**Comment by bartwaw** [comment] 2024-02-09 08:27
Hi, i know but that,  tested your fork also. 
but personally think that this feature should be turned off. It's does nothing to improve anything. If you want to print with 4 bottom layers and specially with bigger nozzle, then bottom layer looks reallt strange. There should be option to use standard infills.

**Comment by smartavionics** [comment] 2024-02-09 08:59
I'll add an option to my Cura to disable the extra walls. It will be available in the next release.

**Comment by bartwaw** [comment] 2024-02-09 09:41
Great, thanks.

**Comment by GregValiant** [comment] 2024-02-09 12:18
This is expected behavior so I'll remove the bug label.
@bartwaw  You could put in a feature request here for UM Cura to incorporate the same sort of "switch" that SmartAvionics is going to put into his fork.
I'm going to close this report.  Let me know if you feel that is premature.

**Closed by GregValiant** 2024-02-09 12:18 UTC
Labels: Type: Discussion
