### ISSUE TITLE
[4.5.0] Brim in holes with islands

### ISSUE THREAD

**Issue by AndreKR** [Ultimaker/Cura#7760] opened 2020-05-14 20:39 UTC
**Application version**
4.5.0

**Platform**
Windows 7

**Printer**
Anycubic i3 mega

**Reproduction steps/Screenshots**

The model:

![image](https://user-images.githubusercontent.com/1188538/81983113-24049500-9633-11ea-9d26-f26f663e422b.png)

Brim settings:

![image](https://user-images.githubusercontent.com/1188538/81983149-2e269380-9633-11ea-8690-81cddc27c042.png)

First layer:

![image](https://user-images.githubusercontent.com/1188538/81983229-53b39d00-9633-11ea-984d-81f2a9c0db1a.png)

**Actual results**
The left (on the screenshot) hole (the one with the island inside) has a brim, the right hole does not.

**Expected results**
This might be a misunderstanding on my part, but is it supposed to print a brim in the left hole with "Brim Only on Outside" selected?

**Comment by AndreKR** [comment] 2020-05-14 20:43
By the way, a Skirt with Skirt Distance = 0mm seems to give the expected result, despite the Skirt Distance input box being orange.

**Comment by Ghostkeeper** [comment] 2020-05-18 11:39
This is currently the expected behaviour, not a bug. The problem arises from how the brim lines are expected to join together like this:
![image](https://user-images.githubusercontent.com/2448634/82209069-f2c6e600-990c-11ea-894b-1a0de48db072.png)

We currently can't make the brim be interrupted by anything. It's always full contours. That would need to change.

**Comment by fvrmr** [comment] 2021-07-01 12:18
Closing this issue since it is a duplicate of https://github.com/Ultimaker/Cura/issues/4222 and we have a ticket on our backlog for this and is related to that issue, so we keep everything in one issue.

**Closed by fvrmr** 2021-07-01 12:18 UTC
Labels: Category: Engine, Type: Improvement
