### ISSUE TITLE
[4.7.0] Crash to bug reporter when trying to load STL.

### ISSUE THREAD

**Issue by fmjensen** [Ultimaker/Cura#8328] opened 2020-09-06 07:52 UTC
4.7.0
Windows 10
Creality Ender 5 plus

**Reproduction steps**
1. Install Cura in default configuration e.g. just clicking next next next
2. Start Cura 4.7.0
3. Attempt to load a STL file.

**Image showing the problem.**
![Capture](https://user-images.githubusercontent.com/3484684/92320775-45472200-f024-11ea-9041-4009f4726c42.PNG)

**What happens after the above steps have been followed.**
Cura immediately crashes and shows the Crash Reporter.
_I used the "Send report" button after every attempt to figure out if I did something wrong_

**What should happen after the above steps have been followed.**
Cura loads STL and allows slicing to be done.

**File that case the problem.**
Any and all STL files.

**Cura Log.**
[cura.log](https://github.com/Ultimaker/Cura/files/5179232/cura.log)

**Extra information relevant to the issue.**
No other version is installed. But older versions have been installed and working fine.

**Comment by nallath** [comment] 2020-09-07 08:24
Duplicate of https://github.com/Ultimaker/Cura/issues/8230

**Closed by nallath** 2020-09-07 08:24 UTC
Labels: Type: Bug
