### ISSUE TITLE
Scaling % bug

### ISSUE THREAD

**Issue by uwe999** [Ultimaker/Cura#1629] opened 2017-04-01 16:51 UTC
When changing the scaling from 100% to say 125% I enter the cursor, remove both 0 with backspace to replace them with 25. 
Sometimes when pressing the backspace twice the model disappears completely.
Haven't been able to duplicate it consistently but it happens frequently for me.
Cura 2.4

**Comment by Ghostkeeper** [comment] 2017-04-03 11:58
Reproduced in Cura 2.5.

**Comment by Ghostkeeper** [comment] 2017-07-03 08:33
I haven't seen this in a while. Have you?

**Comment by Ghostkeeper** [comment] 2017-08-08 08:45
Our project manager rejected this issue because it had been inactive for too long.

**Comment by ianpaschal** [comment] 2018-02-27 11:55
This is fixed in version 3.2.1.

**Closed by ianpaschal** 2018-02-27 11:55 UTC
Labels: Type: Bug
