### ISSUE TITLE
Can't escape Layer View!

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#364] opened 2015-09-10 10:03 UTC
When in layer view, selecting solid view again reloads the layer view instead of going back to the solid view.

**Comment by BagelOrb** [comment] 2015-09-10 10:05
perhaps related:
double layer view (after rescaling)
![cura_double_layer_view](https://cloud.githubusercontent.com/assets/8895761/9785649/34665a9a-57b4-11e5-8c46-a56aa3298008.png)

**Comment by BagelOrb** [comment] 2015-09-10 10:13
Possibly related: https://github.com/Ultimaker/Cura/issues/302

**Comment by nallath** [comment] 2015-09-10 10:24
Confirmed the issue.

**Comment by awhiemstra** [comment] 2015-09-10 13:22
The layer change bug is fixed now. The dupe bug is unrelated.

**Closed** 2015-09-16 13:44 UTC
Labels: bug
