### ISSUE TITLE
Cura 5.2.2 Mac DMG app name and CFBundleIdentifier not consistent 

### ISSUE THREAD

**Issue by Lotusshaney** [Ultimaker/Cura#14518] opened 2023-02-08 18:31 UTC
### Application Version

5.2.2

### Platform

Mac

### Printer

ANy

### Reproduction steps

5.2.2 app for Mac has 

```
<key>CFBundleIdentifier</key>
<string>nl.ultimaker.cura_UltiMaker_Cura_5.2.2</string> 
```
and a name of UltiMaker Cura.app

Older versions have 

```
<key>CFBundleIdentifier</key>
<string>nl.ultimaker.cura</string> 
```
and a name of Ultimaker-Cura.app

Meaning software management systems don't see 5.2.2 as a newer version of Cura

### Actual results

Getting info from the info.plist gives

```
<key>CFBundleIdentifier</key>
<string>nl.ultimaker.cura_UltiMaker_Cura_5.2.2</string> 
```

and a name of UltiMaker Cura.app

### Expected results

```
<key>CFBundleIdentifier</key>
<string>nl.ultimaker.cura</string>
```

and a name of Ultimaker-Cura.app

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This is a problem for software management systems

**Comment by MariMakes** [comment] 2023-02-10 15:37
Hey @Lotusshaney,

Thanks for your report 👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/14375
We have a ticket on our backlog with the intent to improve this behavior.

After digging into this it seems to effect permissions, and window locations and might require you to enter your password more often. They seem to be minor conveniences. Do you have other examples of why we should increase the priority? 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/14375

**Closed by MariMakes** 2023-02-10 15:37 UTC
Labels: Type: Bug, Status: Triage
