### ISSUE TITLE
Only One Head Allowed in Cura 3.2.0 for Dual-head Ultimaker 3

### ISSUE THREAD

**Issue by cjp0008** [Ultimaker/Cura#3253] opened 2018-02-07 17:52 UTC
**Application Version**
3.2.0 BETA.  Doesn't occur with 3.1.0

**Platform**
Win10x64

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**
Choose a custom material

**Actual Results**
Cura is setup with my ultimaker 3, but it takes away control over the right extruder and only shows one material option. 
![image](https://user-images.githubusercontent.com/32529488/35932406-29ba24a0-0bfd-11e8-9347-6a9c192ceb9b.png)

**Expected results**
Should look like Cura 3.1.0:
![image](https://user-images.githubusercontent.com/32529488/35932485-56b951ba-0bfd-11e8-9618-79b99e49c30b.png)

**Additional Information**

**Comment by fieldOfView** [comment] 2018-02-07 18:39
Haven't seen that happen before.... Before you do anything, could you go to Help->Show Configuration Folder, and zip up all the contents of the folder so this situation can be debugged?

On the Printers page of the preferences, go to Machine Settings and check if the number of extruders is set to 2. If that does not help, you can probably fix the problem by adding a new Ultimaker 3 printer.

**Comment by cjp0008** [comment] 2018-02-07 23:27
Sure, it’s attached!

The number of extruders already is set to 2:
[cid:image002.jpg@01D3A038.E56CC580]

However, adding a new Ultimaker fixed the issue.  Thank you!!

**Comment by nallath** [comment] 2018-02-08 16:23
Attachments don't work if you reply by email.

**Comment by ChrisTerBeke** [comment] 2018-05-23 19:17
Was beta, no new info, cannot reproduce. Closing.

**Closed by ChrisTerBeke** 2018-05-23 19:17 UTC
Labels: Category: Cura, Status: Needs Info, Type: Bug
