### ISSUE TITLE
Slicing just failed

### ISSUE THREAD

**Issue by DragonDon** [Ultimaker/Cura#19041] opened 2024-05-07 23:24 UTC
### Cura Version

5.4.0

### Operating System

Windows 11 Pro

### Printer

Ender 5 Plus

### Name abnormal settings

I had the model raised above teh bed

### Describe model location

It was away from the build place 

### Describe your model

"watertight with 2 sub-meshes"

### Add your .zip here ⬇️

[CE5PLUS_taillight-maybe.zip](https://github.com/Ultimaker/Cura/files/15242091/CE5PLUS_taillight-maybe.zip)

**Comment by GregValiant** [comment] 2024-05-10 02:09
Thanks for the report.
It sliced for me on Win10 and Cura 5.7.1 so I'm unable to duplicate the problem.  The model is fine.
Cura 5.4 - 5.6 had problems slicing certain models.  Try upgrading to 5.7.1 and see if the problem is fixed.

I'll mark this as a duplicate and go ahead and close it as the problem seems to be fixed.

**Closed by GregValiant** 2024-05-10 02:09 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error :collision:
