### ISSUE TITLE
Vertical/horisontal filp.

### ISSUE THREAD

**Issue by krsshtx** [Ultimaker/Cura#7424] opened 2020-04-06 01:13 UTC
Hi!

Would suggest these 2 buttons in "rotate" row.

(tired rotating with mouse)

**Comment by nallath** [comment] 2020-04-06 07:47
You mean like the mirror tool?

**Comment by krsshtx** [comment] 2020-04-06 09:15
gimp-like rotate 180 degree 
- change top with bottom (Z flip)
- change front with back (X flip)

rotate 90 deg is also useful
- rotate 90 deg by X
- rotate 90 deg by Y

> You mean like the mirror tool?

**Comment by Ghostkeeper** [comment] 2020-04-08 13:32
Duplicate of https://github.com/Ultimaker/Cura/issues/6404.

**Closed by Ghostkeeper** 2020-04-08 13:32 UTC
Labels: Type: New Feature
