### ISSUE TITLE
"Skin Overlap Percentage" not used for skin if "Extra Skin Wall Count" is > 0

### ISSUE THREAD

**Issue by Triangulix** [Ultimaker/Cura#13019] opened 2022-08-13 00:05 UTC
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Custom

### Reproduction steps

Set "Extra Skin Wall Count" to a value > 0 and set "Skin Overlap Percentage" to a value you can easily see in the preview, like 60%.

### Actual results

The overlap which should help to attach the ends of the skin lines to the walls is not applied to the skin lines but to the additional wall line. 

### Expected results

I know that someone will claim that the behavior is correct since the additional wall line is technically part of the infill.
But this doesn't change the fact that the overlap only helps if it is applied where ends of lines need to stick to walls.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![b](https://user-images.githubusercontent.com/43012099/184458445-34e9c362-1f2c-4ead-88d2-85e4ec2f7099.PNG)
![a](https://user-images.githubusercontent.com/43012099/184458446-d1e3f6d7-f9e6-4e42-982d-f8202ecea8c8.PNG)

**Comment by GregValiant** [comment] 2022-08-13 01:17
Thanks for the report.
I am showing the same behavior in Cura and reading the gcode files into AutoCad confirms the problem.
The developers will take a look at this.

**Comment by Piezoid** [comment] 2022-08-13 01:30
also, bridge settings are not applied to skin extra walls either.

**Comment by Vandresc** [comment] 2022-08-16 08:29
We have a ticket on our backlog, CURA-9381. I will link the git ticket to ours. I will close this as a duplicate of https://github.com/Ultimaker/Cura/issues/12294, please feel free to follow any progress in the linked ticket. 
Thank you for your report!

**Closed by Vandresc** 2022-08-16 08:29 UTC
Labels: Type: Bug, Status: Under Investigation

**Comment by PhilBaz** [comment] 2022-10-01 01:03
@Vandresc 

This has not been fixed in 5.2 beta....

Also, please, bridge and surface-skin each need their own skin overlap % settings.
