### ISSUE TITLE
Kettenhemd

### ISSUE THREAD

**Issue by qugu57** [Ultimaker/Cura#16885] opened 2023-10-04 13:44 UTC
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Any Cubic i3 Mega

### Describe model location

No

### Describe your model

I created some interlocking rings with tinkerCAD

### Add your .zip here ⬇️

[Downloads.zip](https://github.com/Ultimaker/Cura/files/12804120/Downloads.zip)

**Comment by GregValiant** [comment] 2023-10-08 11:31
Thanks for the report.
This appears to be a duplicate of hte standard slicing bug in 5.4.0.  After rotating and moving the model in Cura it sliced.  Sometimes altering the Initial Layer Height by a little bit will fool the bug as well.
I'll mark this as a duplicate and go ahead and close this report.  I hope you understand.
![image](https://github.com/Ultimaker/Cura/assets/64202104/5b26df85-5934-43f6-964e-d2dbdf900d74)

**Closed by GregValiant** 2023-10-08 11:31 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error :collision:
