### ISSUE TITLE
Scaling Issues

### ISSUE THREAD

**Issue by StarsnStripes** [Ultimaker/Cura#4610] opened 2018-10-18 14:51 UTC
Hey there,

I got some issues while scaling my .stl file. The assignment of x,y,z to their percentage doesn't seems right.
You will find some screenshots and the project in my attechment.

Kind regards!

**Application Version**
Cura 3.5.1

**Platform**
Windows 7

**Printer**
Other: ANET A8

**Additional Information**
original:
![original](https://user-images.githubusercontent.com/44267606/47163076-89788e80-d2f5-11e8-9cc2-51d4e2121328.PNG)

scaled:
![changed](https://user-images.githubusercontent.com/44267606/47163087-90070600-d2f5-11e8-84e8-1ea2966cc97c.PNG)

[scaling_issues.zip](https://github.com/Ultimaker/Cura/files/2492363/scaling_issues.zip)

**Comment by rburema** [comment] 2018-10-18 15:09
Hi @StarsnStripes, While not quite the same behaviour, there's something strange going on in the current master as well with your model when I tried those steps. Will discuss it with the team. cheers, Remco.

**Comment by diegopradogesto** [comment] 2018-10-19 07:05
This is a duplicate of #3625.

**Closed by diegopradogesto** 2018-10-19 07:05 UTC
Labels: Type: Bug
