### ISSUE TITLE
Cura 5.0-beta1 - Can't see scrollbar in dark mode

### ISSUE THREAD

**Issue by MikeGlue** [Ultimaker/Cura#11924] opened 2022-04-24 02:12 UTC
### Application Version

5.0.0-beta1

### Platform

Windows 11

### Printer

Ender 3

### Reproduction steps

Set Cura to run in "Ultimaker Dark" mode. 

### Actual results

The vertical scrollbar for the settings is barely visible.

![image](https://user-images.githubusercontent.com/5204734/164953023-43916f91-f4a1-460f-b981-94402a43ef17.png)

### Expected results

scroll bar needs more contrast so it can more easily be seen

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

--

**Comment by fvrmr** [comment] 2022-04-25 12:23
Hi @MikeGlue thank you for your report.
This is the duplicate of https://github.com/Ultimaker/Cura/issues/11872
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2022-04-25 12:23 UTC
Labels: Type: Bug
