### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by KalixtShawxo** [Ultimaker/Cura#10522] opened 2021-09-27 14:00 UTC
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Creality Ender 3 Pro

### Reproduction steps

loaded the file "200mm_bed_center_calibration_crosshair into Cura.
File was gotten from here : https://www.thingiverse.com/thing:2280529

### Actual results

Cura gave an error and suggested filing a report

### Expected results

should have loaded and sliced the file for printing

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7236786/cura.log
[CE3PRO 200mm_bed_center_calibration_crosshair INLAND PLA lw 0.4mm lh 0.2mm if 20.0% ext1 215.0C bed 60.0C.zip](https://github.com/Ultimaker/Cura/files/7236792/CE3PRO.200mm_bed_center_calibration_crosshair.INLAND.PLA.lw.0.4mm.lh.0.2mm.if.20.0.ext1.215.0C.bed.60.0C.zip)
)

**Comment by nallath** [comment] 2021-09-27 15:09
Duplicate of #10394

**Closed by nallath** 2021-09-27 15:09 UTC
Labels: Type: Bug
