### ISSUE TITLE
Absturz beim Slicen eines "First Layer" STL

### ISSUE THREAD

**Issue by derrapf** [Ultimaker/Cura#11185] opened 2022-01-02 16:10 UTC
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Ender3 Pro

### Reproduction steps

Slice attached stl.

### Actual results

"Slicing failed withg an unexpected error"
When I resize the model in Z to 0.4mm then it slices without error

### Expected results

Slicing finishes without error

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.zip](https://github.com/Ultimaker/Cura/files/7799392/cura.zip)
[first_layer_0_1.zip](https://github.com/Ultimaker/Cura/files/7799393/first_layer_0_1.zip)

**Comment by fvrmr** [comment] 2022-01-04 15:50
Hi @derrapf thank you for your report. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/10394 and is fixed in 4.12 and above. 
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2022-01-04 15:50 UTC
Labels: Type: Bug
