### ISSUE TITLE
Objects Multiplying doesn't work

### ISSUE THREAD

**Issue by Hellbilly91** [Ultimaker/Cura#11456] opened 2022-02-10 16:32 UTC
### Application Version

4.12.0

### Platform

MacOS Monterey

### Printer

Anycubic i3 Mega Pro

### Reproduction steps

I Put an Object in the Program and want to multiply this object 4 times. I press the right klick on the mouse and press Multiply add the number 4 in the Program.

### Actual results

[](url
<img width="478" alt="Bildschirmfoto 2022-02-10 um 17 28 07" src="https://user-images.githubusercontent.com/99419840/153451793-ef36400f-ab10-46bd-8eb0-8701b23cf6e2.png">
)

### Expected results

It should multiply the object

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

https://www.thingiverse.com/thing:1282549/files

**Comment by fvrmr** [comment] 2022-02-10 16:48
Hi @Hellbilly91 thank you for your report. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/10249 and this is fixed in 4.12.1 and above. You can download the newest version 4.13.1 here: https://ultimaker.com/software/ultimaker-cura
I will close this since it is a duplicate.

**Closed as completed by fvrmr** 2022-02-10 16:48 UTC
Labels: Type: Bug, Status: Duplicate
