### ISSUE TITLE
Print settings menus shown incorrectly (symbols < and ∨ in menus)

### ISSUE THREAD

**Issue by hummel65** [Ultimaker/Cura#8737] opened 2020-11-11 23:06 UTC
**Application version**
4.8.0

**Platform**
macOS 10.15.7 and Windows 10 OS Build 19041.630

**Printer**
Ultimaker 3 and Ultimaker 2+

**Reproduction steps**
1. Start Cura
2. Open Print settings
3. Click any of the settings like "Quality", "Speed"
4. < is not changing to V

"Quality" and all others except "Dual Extrusion" is always <
"Dual Extrusion" is always V

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

![Skärmavbild 2020-11-11 kl  23 47 47](https://user-images.githubusercontent.com/62713893/98873736-3132fd00-2479-11eb-91c8-7e37c60d50e4.jpg)
![Skärmavbild 2020-11-11 kl  23 47 37](https://user-images.githubusercontent.com/62713893/98873750-35f7b100-2479-11eb-9f8a-c607c69319d1.jpg)
![Skärmavbild 2020-11-11 kl  23 47 06](https://user-images.githubusercontent.com/62713893/98873752-36904780-2479-11eb-8a38-96a0b37298f5.jpg)

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
When content of "Quality" is shown < is expected to change to V and so on for all items

**Log file**
2020-11-11 23:57:20,587 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin FileLogger
2020-11-11 23:57:20,591 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin LegacyProfileReader
2020-11-11 23:57:20,596 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin AMFReader
2020-11-11 23:57:20,600 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin SimpleView
2020-11-11 23:57:20,605 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin SolidView
2020-11-11 23:57:20,611 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin FirmwareUpdateChecker
2020-11-11 23:57:20,615 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin SentryLogger
2020-11-11 23:57:20,623 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin SupportEraser
2020-11-11 23:57:20,628 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin PrepareStage
2020-11-11 23:57:20,648 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin MaterialCostTools
2020-11-11 23:57:20,666 - DEBUG - [MainThread] RawMouse.RawMouse._cacheProfileValues [110]: Device 3Dconnexion / Space Explorer, profile spacemouse
2020-11-11 23:57:20,667 - DEBUG - [MainThread] RawMouse.RawMouse._cacheProfileValues [127]: axis 0, scale = 0.100000, threshold = 0.010000, offset = 0.000000, target = movx
2020-11-11 23:57:20,667 - DEBUG - [MainThread] RawMouse.RawMouse._cacheProfileValues [127]: axis 1, scale = 100.000000, threshold = 1.000000, offset = 0.000000, target = zoom
2020-11-11 23:57:20,667 - DEBUG - [MainThread] RawMouse.RawMouse._cacheProfileValues [127]: axis 2, scale = 0.100000, threshold = 0.010000, offset = 0.000000, target = movy
2020-11-11 23:57:20,667 - DEBUG - [MainThread] RawMouse.RawMouse._cacheProfileValues [127]: axis 3, scale = 0.050000, threshold = 0.010000, offset = 0.000000, target = rotpitch
2020-11-11 23:57:20,667 - DEBUG - [MainThread] RawMouse.RawMouse._cacheProfileValues [127]: axis 4, scale = 0.050000, threshold = 0.010000, offset = 0.000000, target = rotroll
2020-11-11 23:57:20,667 - DEBUG - [MainThread] RawMouse.RawMouse._cacheProfileValues [127]: axis 5, scale = -0.100000, threshold = 0.010000, offset = 0.000000, target = rotyaw
2020-11-11 23:57:20,668 - DEBUG - [RawMouse] RawMouse.RawMouse._run [167]: Trying to open IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS10@14800000/4-Port USB 2.0 Hub@14800000/AppleUSB20Hub@14800000/AppleUSB20HubPort@14820000/4-Port USB 2.0 Hub@14820000/AppleUSB20Hub@14820000/AppleUSB20HubPort@14821000/4-Port USB 2.0 Hub@14821000/AppleUSB20Hub@14821000/AppleUSB20HubPort@14821300/Space Explorer@14821300/IOUSBHostInterface@0/ConnexionUSB@14821300,0
2020-11-11 23:57:20,670 - INFO - [RawMouse] RawMouse.RawMouse._run [173]: Manufacturer: 3Dconnexion
2020-11-11 23:57:20,673 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin RawMouse
2020-11-11 23:57:20,673 - INFO - [RawMouse] RawMouse.RawMouse._run [174]: Product: Space Explorer
2020-11-11 23:57:20,680 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin PauseBackendPlugin
2020-11-11 23:57:20,686 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin CustomJobPrefix
2020-11-11 23:57:20,692 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin OrientationPlugin
2020-11-11 23:57:20,696 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin GcodeFilenameFormat
2020-11-11 23:57:20,700 - INFO - [MainThread] StartOptimiser.StartOptimiser.__init__ [40]: 1919 containers are blacklisted by StartOptimiser
2020-11-11 23:57:20,705 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin StartOptimiser
2020-11-11 23:57:20,953 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin SettingsGuide2
2020-11-11 23:57:20,960 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin ZOffsetPlugin
2020-11-11 23:57:20,965 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin CustomSupports
2020-11-11 23:57:20,967 - DEBUG - [MainThread] UM.PluginRegistry.loadPlugins [432]: Loading all plugins took 1.0972840785980225 seconds
2020-11-11 23:57:20,975 - INFO - [MainThread] UM.VersionUpgradeManager.upgrade [163]: Looking for old configuration files to upgrade.
2020-11-11 23:57:20,994 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ./.DS_Store, skip it
2020-11-11 23:57:20,998 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ./.DS_Store, skip it
2020-11-11 23:57:21,001 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ./.DS_Store, skip it
2020-11-11 23:57:21,004 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ./.DS_Store, skip it
2020-11-11 23:57:21,007 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ./.DS_Store, skip it
2020-11-11 23:57:21,010 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ./.DS_Store, skip it
2020-11-11 23:57:21,013 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ./.DS_Store, skip it
2020-11-11 23:57:21,016 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ./.DS_Store, skip it
2020-11-11 23:57:21,019 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ./.DS_Store, skip it
2020-11-11 23:57:21,021 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ./.DS_Store, skip it
2020-11-11 23:57:21,025 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ./.DS_Store, skip it
2020-11-11 23:57:21,028 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ./.DS_Store, skip it
2020-11-11 23:57:21,030 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ./.DS_Store, skip it
2020-11-11 23:57:21,033 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ./.DS_Store, skip it
2020-11-11 23:57:21,036 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ./.DS_Store, skip it
2020-11-11 23:57:21,039 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ./.DS_Store, skip it
2020-11-11 23:57:21,042 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ./.DS_Store, skip it
2020-11-11 23:57:21,064 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ../generic_tpu+%232.xml.fdm_material, skip it
2020-11-11 23:57:21,067 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ../generic_pla+%232.xml.fdm_material, skip it
2020-11-11 23:57:21,069 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ../generic_tpu+%233.xml.fdm_material, skip it
2020-11-11 23:57:21,072 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ../generic_pla+%233.xml.fdm_material, skip it
2020-11-11 23:57:21,074 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ../Textura/AddNorthTexturaFlare/AddNorth_TexturaFlare.xml.fdm_material, skip it
2020-11-11 23:57:21,077 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ../colorfabb_colorondemand/colorFabb_COD.xml.fdm_material, skip it
2020-11-11 23:57:21,080 - WARNING - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [332]: Failed to get file version: ../NinjaTekArmadillo/ninjatek_armadillo.xml.fdm_material, skip it
2020-11-11 23:57:21,087 - INFO - [MainThread] UM.VersionUpgradeManager.upgrade [175]: Checking and performing updates took 0.11182999610900879
2020-11-11 23:57:22,091 - INFO - [MainThread] CuraEngineBackend.CuraEngineBackend.slice [246]: Starting to slice...
2020-11-11 23:57:22,091 - WARNING - [MainThread] CuraEngineBackend.CuraEngineBackend.slice [250]: Slice unnecessary, nothing has changed that needs reslicing.
2020-11-11 23:57:23,132 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.loadAllMetadata [361]: Loading metadata into container registry took 1.4987719058990479 seconds
2020-11-11 23:57:23,150 - DEBUG - [MainThread] cura.Scene.CuraSceneController.setActiveBuildPlate [142]: Select build plate: 0
2020-11-11 23:57:23,153 - INFO - [MainThread] cura.CuraApplication.run [782]: Initializing machine error checker
2020-11-11 23:57:23,328 - INFO - [MainThread] cura.UI.MachineActionManager.addDefaultMachineActions [74]: Default machine actions added for machine definition [ultimaker3]
2020-11-11 23:57:23,431 - INFO - [MainThread] cura.Settings.GlobalStack.addExtruder [194]: Extruder[ultimaker3_extruder_left #2] added to [Mats-UM3] at position [0]
2020-11-11 23:57:23,434 - INFO - [MainThread] cura.Settings.GlobalStack.addExtruder [194]: Extruder[ultimaker3_extruder_right #2] added to [Mats-UM3] at position [1]
2020-11-11 23:57:23,468 - INFO - [Thread-2] FirmwareUpdateChecker.FirmwareUpdateCheckerJob.run [93]: You have a(n) Ultimaker 3 in the printer list. Do firmware-check.
2020-11-11 23:57:23,740 - INFO - [Thread-2] FirmwareUpdateChecker.FirmwareUpdateCheckerJob.run [110]: Reading firmware version of Ultimaker 3: checked = 5.2.16-20200331.0 - latest = 5.2.16-20200331.0
2020-11-11 23:57:25,495 - DEBUG - [MainThread] cura.Machines.ContainerTree.__getitem__ [120]: Adding container tree for ultimaker3 took 1.9882559776306152 seconds.
2020-11-11 23:57:25,519 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: ChangeAtZ
2020-11-11 23:57:25,519 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: ColorMix
2020-11-11 23:57:25,520 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: DisplayFilenameAndLayerOnLCD
2020-11-11 23:57:25,521 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: DisplayProgressOnLCD
2020-11-11 23:57:25,522 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: FilamentChange
2020-11-11 23:57:25,522 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: InsertAtLayerChange
2020-11-11 23:57:25,523 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: PauseAtHeight
2020-11-11 23:57:25,523 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: RetractContinue
2020-11-11 23:57:25,524 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: SearchAndReplace
2020-11-11 23:57:25,525 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: Stretch
2020-11-11 23:57:25,525 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: TimeLapse
2020-11-11 23:57:25,526 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [202]: Begin loading of script: UsePreviousProbeMeasurements
2020-11-11 23:57:25,572 - INFO - [MainThread] cura.CuraApplication.run [787]: Initializing machine manager
2020-11-11 23:57:25,588 - INFO - [MainThread] cura.CuraApplication.run [792]: Initializing container manager
2020-11-11 23:57:26,172 - DEBUG - [Thread-3] UM.Mesh.MeshData.calculateNormalsFromVertices [556]: Calculating normals took 0.006021976470947266 seconds
2020-11-11 23:57:26,174 - WARNING - [MainThread] UM.Logger.warning [128]: Starting a new sync while previous sync was not completed
{'CloudOutputDeviceManager': 0}
2020-11-11 23:57:26,483 - DEBUG - [MainThread] cura.Machines.MachineErrorChecker._rescheduleCheck [155]: New error check scheduled.
2020-11-11 23:57:26,514 - DEBUG - [MainThread] UM.Scene.Camera._preferencesChanged [255]: Changing perspective mode to perspective.
2020-11-11 23:57:26,689 - DEBUG - [MainThread] UM.Qt.Bindings.Theme.load [158]: Loading theme file: /Applications/Ultimaker Cura 4.8.0.app/Contents/MacOS/resources/themes/cura-light/theme.json
2020-11-11 23:57:26,794 - DEBUG - [MainThread] UM.Qt.Bindings.Theme.load [246]: Loaded theme /Applications/Ultimaker Cura 4.8.0.app/Contents/MacOS/resources/themes/cura-light
2020-11-11 23:57:27,139 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin._createView [340]: Creating post processing plugin view.
2020-11-11 23:57:27,224 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin._createView [350]: Post processing view created.
2020-11-11 23:57:27,473 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [406]: file:///Applications/Ultimaker Cura 4.8.0.app/Contents/MacOS/resources/qml/Account/UserOperations.qml:17:5: QML QQuickItem: Binding loop detected for property "height"
2020-11-11 23:57:27,476 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [406]: file:///Applications/Ultimaker Cura 4.8.0.app/Contents/MacOS/resources/qml/Account/UserOperations.qml:17:5: QML QQuickItem: Binding loop detected for property "height"
2020-11-11 23:57:27,495 - DEBUG - [MainThread] cura.Machines.Models.NozzleModel._update [28]: Updating NozzleModel.
2020-11-11 23:57:27,519 - DEBUG - [MainThread] cura.Machines.Models.NozzleModel._update [28]: Updating NozzleModel.
2020-11-11 23:57:27,604 - DEBUG - [MainThread] PauseBackendPlugin.PauseBackend._createAdditionalComponentsView [27]: Creating additional ui components for Pause Backend plugin.
2020-11-11 23:57:27,612 - DEBUG - [MainThread] CustomJobPrefix.CustomJobPrefix._createAdditionalComponentsView [40]: Creating additional ui components for CustomJobPrefix
2020-11-11 23:57:27,628 - DEBUG - [MainThread] UM.Controller.setActiveStage [180]: Setting active stage to PrepareStage
2020-11-11 23:57:27,686 - DEBUG - [MainThread] cura.Machines.Models.NozzleModel._update [28]: Updating NozzleModel.
2020-11-11 23:57:27,721 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [406]: file:///Applications/Ultimaker Cura 4.8.0.app/Contents/MacOS/resources/qml/Menus/ConfigurationMenu/CustomConfiguration.qml:234: TypeError: Cannot read property 'activeStack' of undefined
2020-11-11 23:57:27,750 - DEBUG - [MainThread] UM.Controller.setActiveView [108]: Setting active view to SolidView
2020-11-11 23:57:27,761 - DEBUG - [MainThread] SliceInfoPlugin.SliceInfo._createDialog [76]: Creating dialog [MoreInfoWindow.qml]
2020-11-11 23:57:27,779 - DEBUG - [MainThread] ModelChecker.ModelChecker._createView [117]: Creating model checker view.
2020-11-11 23:57:27,783 - DEBUG - [MainThread] ModelChecker.ModelChecker._createView [126]: Model checker view created.
2020-11-11 23:57:27,785 - DEBUG - [MainThread] Toolbox.src.Toolbox._makeRequestByType [544]: Requesting [updates] metadata from server.
2020-11-11 23:57:27,891 - DEBUG - [MainThread] cura.CuraApplication.run [833]: Booting Cura took 8.35668396949768 seconds
2020-11-11 23:57:27,892 - DEBUG - [Thread-5] cura.Machines.ContainerTree.run [174]: Started background loading of MachineNodes
2020-11-11 23:57:27,972 - INFO - [MainThread] FirmwareUpdateChecker.FirmwareUpdateChecker.checkFirmwareVersion [79]: No machine with name Ultimaker 2+ in list of firmware to check.
2020-11-11 23:57:28,010 - DEBUG - [MainThread] cura.Machines.Models.CustomQualityProfilesDropDownMenuModel._update [33]: Updating CustomQualityProfilesDropDownMenuModel.
2020-11-11 23:57:28,027 - DEBUG - [MainThread] cura.Machines.Models.QualityProfilesDropDownMenuModel._update [62]: Updating QualityProfilesDropDownMenuModel.
2020-11-11 23:57:28,323 - DEBUG - [MainThread] UM.Qt.QtRenderer._initialize [210]: Support for Vertex Array Objects: True
2020-11-11 23:57:28,329 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [112]: Initialized OpenGL subsystems.
2020-11-11 23:57:28,332 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [113]: OpenGL Version:  4.1 ATI-3.10.18
2020-11-11 23:57:28,335 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [114]: OpenGL Vendor:   ATI Technologies Inc.
2020-11-11 23:57:28,338 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [115]: OpenGL Renderer: AMD Radeon Pro Vega 64 OpenGL Engine
2020-11-11 23:57:28,341 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [116]: GLSL Version:    4.10.0
2020-11-11 23:57:28,344 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [/Applications/Ultimaker Cura 4.8.0.app/Contents/MacOS/resources/shaders/default.shader]...
2020-11-11 23:57:28,352 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [/Applications/Ultimaker Cura 4.8.0.app/Contents/MacOS/resources/shaders/selection.shader]...
2020-11-11 23:57:28,360 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [/Applications/Ultimaker Cura 4.8.0.app/Contents/MacOS/resources/shaders/select_face.shader]...
2020-11-11 23:57:28,367 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [/Applications/Ultimaker Cura 4.8.0.app/Contents/MacOS/resources/shaders/default.shader]...
2020-11-11 23:57:28,374 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [/Applications/Ultimaker Cura 4.8.0.app/Contents/MacOS/resources/shaders/composite.shader]...
2020-11-11 23:57:28,382 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [/Applications/Ultimaker Cura 4.8.0.app/Contents/MacOS/resources/shaders/overhang.shader]...
2020-11-11 23:57:28,389 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [/Applications/Ultimaker Cura 4.8.0.app/Contents/MacOS/resources/shaders/striped.shader]...
2020-11-11 23:57:28,397 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [/Applications/Ultimaker Cura 4.8.0.app/Contents/MacOS/resources/shaders/transparent_object.shader]...
2020-11-11 23:57:28,404 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [/Applications/Ultimaker Cura 4.8.0.app/Contents/MacOS/resources/shaders/striped.shader]...
2020-11-11 23:57:28,411 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [/Applications/Ultimaker Cura 4.8.0.app/Contents/MacOS/resources/shaders/xray.shader]...
2020-11-11 23:57:28,417 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [/Applications/Ultimaker Cura 4.8.0.app/Contents/MacOS/resources/shaders/xray_composite.shader]...
2020-11-11 23:57:28,424 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [/Applications/Ultimaker Cura 4.8.0.app/Contents/MacOS/resources/shaders/default.shader]...
2020-11-11 23:57:28,430 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [/Applications/Ultimaker Cura 4.8.0.app/Contents/MacOS/resources/shaders/grid.shader]...
2020-11-11 23:57:28,437 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [/Applications/Ultimaker Cura 4.8.0.app/Contents/MacOS/resources/shaders/platform.shader]...
2020-11-11 23:57:28,486 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [/Applications/Ultimaker Cura 4.8.0.app/Contents/MacOS/resources/shaders/xray.shader]...
2020-11-11 23:57:28,695 - INFO - [MainThread] UM3NetworkPrinting.src.Cloud.CloudOutputDevice.connect [114]: Attempting to connect to cluster 4QNMc9v-xHiOGMg-P_3CuMe6CYIorv0C7yD83CF3nrlB
2020-11-11 23:57:28,737 - DEBUG - [MainThread] cura.Machines.Models.CustomQualityProfilesDropDownMenuModel._update [33]: Updating CustomQualityProfilesDropDownMenuModel.
2020-11-11 23:57:28,747 - DEBUG - [MainThread] cura.Machines.Models.QualityProfilesDropDownMenuModel._update [62]: Updating QualityProfilesDropDownMenuModel.
2020-11-11 23:57:30,541 - DEBUG - [Thread-5] cura.Machines.ContainerTree.__getitem__ [120]: Adding container tree for ultimaker2_plus took 1.6376550197601318 seconds.
2020-11-11 23:57:30,545 - DEBUG - [Thread-5] cura.Machines.ContainerTree.run [185]: All MachineNode loading completed
2020-11-11 23:57:31,450 - INFO - [MainThread] cura.Machines.MachineErrorChecker._setResult [214]: Error check finished, result = False, time = 5.0s
2020-11-11 23:57:32,402 - INFO - [Thread-4] SettingsGuide2.CuraSettingsGuide.load_all [161]: Finished loading Settings Guide articles.
2020-11-11 23:57:48,519 - DEBUG - [MainThread] cura.AutoSave._onTimeout [59]: Autosaving preferences, instances and profiles
2020-11-11 23:57:55,369 - DEBUG - [MainThread] cura.TaskManagement.OnExitCallbackManager.triggerNextCallback [51]: No more on-app-exit callbacks to process. Tell the app to exit.
2020-11-11 23:57:55,372 - INFO - [MainThread] cura.CuraApplication.closeApplication [603]: Close application
2020-11-11 23:57:55,378 - DEBUG - [MainThread] UM.Qt.QtApplication.windowClosed [470]: Shutting down cura
2020-11-11 23:57:55,631 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._terminate [315]: Attempting to kill the engine process
2020-11-11 23:57:55,631 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._terminate [321]: Killing engine process
2020-11-11 23:57:55,632 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._terminate [324]: Engine process is killed. Received return code -15

**Additional information**
This is n minor but annoying UI bug.

**Comment by konskarm** [comment] 2020-11-12 08:27
I am closing this as a duplicate of https://github.com/Ultimaker/Cura/issues/8283. Please add any extra comments there.

**Closed by konskarm** 2020-11-12 08:27 UTC
Labels: Type: Bug

**Comment by hummel65** [comment] 2020-11-12 08:43
Hi,

I searched for it and couldn’t find it, sorry for my duplicate report. Thank you for the speedy reply!

Mats
