### ISSUE TITLE
[5.0 Beta] Errors Uninstalling Packages

### ISSUE THREAD

**Issue by LoneWolfe007** [Ultimaker/Cura#12181] opened 2022-05-12 00:38 UTC
### Application Version

5.0 Beta

### Platform

Windows 11 Pro

### Printer

Creality Ender-3 V2

### Reproduction steps

When I first installed Cura 5.0 Beta I chose to uninstall the plugins which were giving errors for being incompatible. 
 

### Actual results

After removing the plugins anytime I start Cura I receive errors stating that there was an issue uninstalling the packages, but they are not there. I have attached a picture to show the screen I am referring to
![Screenshot 2022-05-11 203054](https://user-images.githubusercontent.com/22029613/167968845-bfda0633-700b-4b10-9fed-e079b60d638a.jpg)
.

### Expected results

I should be able to start Cura with no error warnings. 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8674145/cura.log)

**Comment by fvrmr** [comment] 2022-05-12 08:24
Hi @LoneWolfe007 thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11865, so I will close this issue.

**Closed by fvrmr** 2022-05-12 08:24 UTC
Labels: Type: Bug
