### ISSUE TITLE
Bug Cura Master scaling a rotated model

### ISSUE THREAD

**Issue by Gonzo3so** [Ultimaker/Cura#8594] opened 2020-10-22 10:01 UTC
**Application version**
Cura Master

**Platform**
Windows 10

**Printer**
Custom, Artillery Genius

**Reproduction steps**
1 insert model
2 rotate model
3 scale model uniform to 135 % 
4 untick uniform scaling
5 scale x axis to 150 % 

**Screenshot(s)**

**Actual results**
cura bugs and changes more than 1 axis, I believe due to "memory" of first position before rotating the object

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**

**Log file**

**Additional information**

**Comment by konskarm** [comment] 2020-10-22 10:08
I followed the reproduction steps and I am unable to reproduce this. Could you share a project file where the issue is observed? 

We recently saw a similar thing where in strange rotations the scaling _may_ influence not just the axis you are changing, but also other axes (e.g. if you are scaling X, it would change the scale percentage of Y _but only by a tiny bit, <1% or so_) which we attribute to rounding errors, since the mm field wasn't changing. That issue we decided to defer for now, since it isn't really affecting the model. Could it be the same issue?

**Comment by nallath** [comment] 2020-10-22 11:46
Did you also update Uranium? We quite recently made some changes to the scaling tool and that is in the Uranium repo.

**Comment by Gonzo3so** [comment] 2020-10-22 13:11
Hello, thanks for the quick reply.

It is my first bug report so if I didn't file it correctly I'm sorry.

I have included screenshots from the actions I took, hope this helps.

Friso

Op do 22 okt. 2020 om 13:47 schreef Jaime van Kessel <
notifications@github.com>:

**Comment by nallath** [comment] 2020-10-22 13:16
Attaching things via email doesn't work; We can't see them. If you want to share pictures, you will have to do so via the github webpage.

**Comment by Gonzo3so** [comment] 2020-10-22 13:53
![Screenshot 2020-10-22 144642](https://user-images.githubusercontent.com/73283490/96881353-779aca80-147e-11eb-9395-398c0b1abec7.png)
![Screenshot 2020-10-22 144708](https://user-images.githubusercontent.com/73283490/96881355-78cbf780-147e-11eb-8d14-6620c496c709.png)
![Screenshot 2020-10-22 144746](https://user-images.githubusercontent.com/73283490/96881357-78cbf780-147e-11eb-99b9-aca67db66731.png)
![Screenshot 2020-10-22 144820](https://user-images.githubusercontent.com/73283490/96881359-79648e00-147e-11eb-9849-7bc0fb719d77.png)
![Screenshot 2020-10-22 144845](https://user-images.githubusercontent.com/73283490/96881361-79fd2480-147e-11eb-9255-36be20dc9369.png)



Included you find the screenshots, sorry complete noob here for filing a report. No I havent updated Uranium, I just downloaded the zip file but not sure what to do with it or how to use it.

**Comment by konskarm** [comment] 2020-10-22 13:57
Wait, you are saying you are using Cura master. Are you running Cura from source, or just running the latest cura version (4.7.1)?

**Comment by Gonzo3so** [comment] 2020-10-22 15:51
This is the cura I run 
![Screenshot 2020-10-22 175025](https://user-images.githubusercontent.com/73283490/96897647-1a5b4500-148f-11eb-9241-9dab67b5f98d.png)


I double checked and the version 4.6.1 I have also has the same bug.

**Comment by Ghostkeeper** [comment] 2020-10-23 13:09
That doesn't really tell which version it really is :(
If it's one of our nightly master builds (which we published recently for the bug in polygon simplification in another thread) then it should also include a date there. I wonder where you got that build from.

In any case, even in that nightly we published then, that bug wasn't fixed yet, but it is fixed for the 4.8 beta. We've just published that here: https://github.com/Ultimaker/Cura/releases/tag/4.8-beta Could you try with that version?

**Comment by Gonzo3so** [comment] 2020-10-23 13:11
I'll give it a go, thank you

**Comment by Gonzo3so** [comment] 2020-10-23 14:08
I just installed 4.8 beta and the bug is gone, perfect. 

As to why I have Cura master? I honestly don't know how or why I installed it.

**Comment by fieldOfView** [comment] 2020-10-23 14:18
Might have been an @smartavionics build. AFAIK, they are always based on the master branch.

**Comment by konskarm** [comment] 2020-10-23 14:23
> I just installed 4.8 beta and the bug is gone, perfect.
> 
> As to why I have Cura master? I honestly don't know how or why I installed it.
Excellent! We can close this issue.

**Closed by konskarm** 2020-10-23 14:23 UTC
Labels: Type: Bug

**Comment by Tampa** [comment] 2021-08-23 09:40
There is still an issue with this to some degree. When rotating an object like a long stick say 35 degrees on the buildplate and then scaling with uniform scaling unchecked the result is the object actually changing shape. Image below should be a rectangle, but the corners changed angles and that seems to depend on the selected scale vectors. I think instead of scaling the object according to the original rotation, instead the new "bounding box" orientated to the buildplate itself is scaled, causing the object to actually shift along the XY axis of the buildplate and not the object. Given this is not rotated in the stl itself, but in CURA, it should probably not mess with proportions like this.

![image](https://user-images.githubusercontent.com/1579370/130425730-1c4f39e9-616a-4648-bf34-a8f832fdd142.png)

**Comment by nallath** [comment] 2021-08-23 10:47
> There is still an issue with this to some degree. When rotating an object like a long stick say 35 degrees on the buildplate and then scaling with uniform scaling unchecked the result is the object actually changing shape. Image below should be a rectangle, but the corners changed angles and that seems to depend on the selected scale vectors. I think instead of scaling the object according to the original rotation, instead the new "bounding box" orientated to the buildplate itself is scaled, causing the object to actually shift along the XY axis of the buildplate and not the object. Given this is not rotated in the stl itself, but in CURA, it should probably not mess with proportions like this.
> 
> ![image](https://user-images.githubusercontent.com/1579370/130425730-1c4f39e9-616a-4648-bf34-a8f832fdd142.png)

No, that is correct. The scaling is done on a world level. That's also what the tool handles indicate; They aren't rotated.

**Comment by Tampa** [comment] 2021-08-23 11:23
That creates a disconnection between the model and its rotation however as once the model is distorted from scaling at a different angle the transform sticks through further rotation or reset. Reversing the transformation means rotating the opposite direction and scaling once more, making it rather difficult and unintuitive to prepare a model for printing as to avoid problems with distortion scaling can only happen without rotation applied.

A switch to change the scaling based on the models axis rather than that of the buildplate would make this more intuitive and the original behavior can be kept as well. It's not what one expects when most cad programs and the like scale based on object origin when it comes to self contained parts.

And no just showing the handles as not rotated is not a good indication when the rotation handles don't change their indicator positions on rotation either, even if a rotation is applied their arrows still stick in the same place, which gives the impression the indicators are not meant to move to show a change in rotation or scale either, else the rotation indicators would orient according to model orientation and the scale vectors would change their position according to the applied scale factor.

**Comment by Ghostkeeper** [comment] 2021-09-01 13:08
The logic is that, from the moment you release the rotation handle after rotating your cube 45 degrees, the model behaves as if you loaded in the rotated model. There's no state. I'd say it's illogical that saving the model and re-loading it would change the way it scales afterwards.

Further confusion would be that after rotating your model 90 degrees, scaling the X dimension would result in the model scaling in the Y direction.

There is no consensus on which one to use in the industry. Some (e.g. Blender) apply transformations locally. Some (e.g. CloudCompare) apply transformations globally.
