### ISSUE TITLE
strange step over in middle of a print 

### ISSUE THREAD

**Issue by exiledmachinist** [Ultimaker/Cura#12545] opened 2022-06-16 18:46 UTC
### Application Version

5.0

### Platform

win10

### Printer

custom 

### Reproduction steps

sliced a part with bosses attached to the main body of part and noticed a step over in the slicing layer view.
next I tried another slicer other then cura... yes I'm sorry I strayed.  the step wasn't there
![cura](https://user-images.githubusercontent.com/77942532/174140009-da7bbf78-5d2e-4990-9a42-f2d0f222e0cb.jpg)
![superslicer](https://user-images.githubusercontent.com/77942532/174140018-c810c3f0-b7e0-4444-a8ed-0159bbea0c4c.jpg)

I then tried another part different set up that I had the same issue on and proceeded to test every setting in my print profile until I found the issue.
![cura2](https://user-images.githubusercontent.com/77942532/174140602-fcaad410-13c8-4bbe-8b6e-b76ec0175189.jpg)
![cura3](https://user-images.githubusercontent.com/77942532/174140618-a401955d-6065-4bf5-af3a-c003ec8d6059.jpg)
 if you'll notice the step in the internal square of the part there's a step over in the first pic titled cura 2  and my hole horizonal expansion is set at .8 ( yes this exaggerated to make it more visible for photos)  the step is cause by the expansion feature because of the hole in the end of the part. the hole breaks the loop or closed feature AKA hole so it turns the hole horizontal expansion off for the layers where the hole is and then turns it back on after the whole so you end up with a nice ridge in the middle of the square hole. the next picture titled cura 3 is with hole horizontal expansion 0.0 out or turned off  no step no ridge in the part.  

### Actual results

now that i know what the issue is i can work around it for now. i just have to not use hole horizontal expansion and just add the hole expansion correction factor to the dimensions in my drawings for now until there a fix for it if theres a way to fix it.  not sure im just a dumb machnist not a software genius like yall. the stuff you guys make software do is amazing. 

### Expected results

im hoping in the future that cura can fix this issue and make the cura slicer software even better then it is  as of right now its pretty amazing and fixxing this issue will only make it better.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[New Compressed (zipped) Folder.zip](https://github.com/Ultimaker/Cura/files/8921587/New.Compressed.zipped.Folder.zip)
log file and 2 project files one with and one without hole horizontal expansion to show the issue   

thank you

**Comment by GregValiant** [comment] 2022-06-16 20:20
Congratulations on figuring it out.  Most people don't.
@smartavionics might have something  add here or you can check #11217 for a fix.  I don't know where UM Cura is with this so maybe one of the team members can explain.
This looks to be a duplicate of #11217 so I will mark it that way.  If you feel it's different you can add another post here.

**Comment by exiledmachinist** [comment] 2022-06-16 20:57
well @smartavionics solution is great. if the setting he made was actually
in cura 4.13.1 or 5.0  unless it's some custom thing he added on a big
brain level that i do not possess. the version in the post you linked me to
was 4.12.1 so not sure if his fix will even work for cura 5.0 which is the
current version i'm using.

**Comment by smartavionics** [comment] 2022-06-16 21:24
Hi, I'm afraid the above mentioned setting is currently only in my releases (https://github.com/smartavionics/Cura/releases). Perhaps one day UM will put something similar into their releases (it's a trivial thing to implement). In the meantime you could always try my release and enjoy all the extra bells and whistles that it provides. You can install it without stomping on your existing Cura installation.

**Comment by exiledmachinist** [comment] 2022-06-16 22:18
> Hi, I'm afraid the above mentioned setting is currently only in my releases (https://github.com/smartavionics/Cura/releases). Perhaps one day UM will put something similar into their releases (it's a trivial thing to implement). In the meantime you could always try my release and enjoy all the extra bells and whistles that it provides. You can install it without stomping on your existing Cura installation.

you sir are a scholar and a gentlemen.  i was wondering if the cura builds on your github where a custom one. im sorry for the trouble and so many questions im computer stupid. im a machinist/welder/fabricator my solutions for fixing things are bore it out weld it shut or in place or hit it with a bigger hammer if it dont fit.  ill give your version a try

**Comment by nallath** [comment] 2022-06-17 08:11
Duplicate of #11217

**Closed by nallath** 2022-06-17 08:11 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation
