### ISSUE TITLE
Cura 4.5. Cube infill issues. 

### ISSUE THREAD

**Issue by ranbros** [Ultimaker/Cura#7493] opened 2020-04-13 15:53 UTC
On cura 4.5 is supported anet a8. 
The standard infill is set to cubic but this produce artifact on surface due to infill that push the shell. 
With previous cura the default infill was lines. Lines works better. 
I have change the infill pattern from cubic to lines in Cura 4.5 this solves the problem. 

**Application version**
Cura 4.5.

**Platform**
Windows 10

**Printer**
Anet a8

**Reproduction steps**
Default settings 0.1 0.2

**Screenshot(s)**

**Actual results**
Infill overlaps shell 

**Expected results**
Set infill patter from cubic to lines

**Project file**

**Log file**

**Additional information**

**Comment by mahtDFR** [comment] 2020-04-14 15:06
Thanks for the report. Please save a project file (File -> Save...), zip up the .3mf file and attach to this issue so we can try to reproduce it.

If you haven't already, please can you attach a [log file](https://github.com/Ultimaker/Cura#logging-issues).

**Comment by ranbros** [comment] 2020-04-14 15:12
[AA8_bird_whistle.zip](https://github.com/Ultimaker/Cura/files/4476112/AA8_bird_whistle.zip)

**Comment by Ghostkeeper** [comment] 2020-04-21 16:07
So I think you just need to reduce the [Infill Overlap](https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/infill/infill_overlap.md) setting. It'll probably result in slightly weaker parts, but it'll look better.

I'm closing this since it's really working as expected. There is no difference between cubic and lines with the overlap. There is a difference due to the new Infill Overlap setting.

**Closed by Ghostkeeper** 2020-04-21 16:07 UTC
Labels: Type: Bug

**Comment by Ghostkeeper** [comment] 2020-04-21 16:17
So I think you just need to reduce the [Infill Overlap](https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/infill/infill_overlap.md) setting. It'll probably result in slightly weaker parts, but it'll look better.

I'm closing this since it's really working as expected. There is no difference between cubic and lines with the overlap. There is a difference due to the new Infill Overlap setting.
