### ISSUE TITLE
Rotate + Scale = Bug

### ISSUE THREAD

**Issue by chris6w** [Ultimaker/Cura#7388] opened 2020-04-01 17:28 UTC
**Application version**
Mac 4.5.0

**Platform**
Mac

**Printer**
Ender 3

**Reproduction steps**
GIF:
https://imgur.com/HafoxzO

1.  Import a model
2. Select the model and click Rotate Tool
3. Click "Select face to align model", click on a face (i used a plane on Y-Axis which rotates 90%, but normal rotate also has this error)
4. Click on Scale tool
5. Uncheck Uniform Scaling
6. Change the Z scale to 118, press Enter (BUG 1: Y% will automatically go from 100 to 118%, visually it did not scale up)
7. Click outside of the object and then select the object again to view the scale (BUG 2: Y% will automatically get updated to 1.18 * 1.18  = 1.3924, this time visually it updated to 139%)

**Actual results**
see above
https://imgur.com/a/fOi9xVR

**Expected results**
Only Z axis should get scaled according to my input of 118%, others stay the same

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
The bug happens when the UI gets updated, the wrong axis (original Y axis of the object > Y axis of the UI) got the update.
I also notice this happen to the custom support blocks.  If something had been rotated before, the block will scale like a trapezoid. 
Looks like similar to #4309 but it is definitely not fixed on 4.5.0

**Comment by nallath** [comment] 2020-04-02 15:10
You're correct that it's a duplicate of #4309 (which in turn, is a duplicate of #4136)

**Closed by nallath** 2020-04-02 15:10 UTC
Labels: Type: Bug
