### ISSUE TITLE
Cura 5.2.1 crashes when trying to save a sliced file in .ufp format

### ISSUE THREAD

**Issue by konior21** [Ultimaker/Cura#14180] opened 2023-01-01 16:49 UTC
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Creality CR-10

### Reproduction steps

1. Slice a file
2. Click the 'Save to Disk' button
3. Change file type to .ufp
4. Click 'Save'

### Actual results

Cura starts to write the file but crashes and a Crash Report window pops up.

### Expected results

The sliced file should have saved successfully in the .ufp format.

### Checklist of files to include

- [X] Log file
- [x] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10329104/cura.log)

This only happens in 5.2.1. Previous versions all still work for saving .ufp files for me. It seems to happen with any model I tried as well.

**Comment by fieldOfView** [comment] 2023-01-02 14:29
Looking at the logs, this is a duplicate of #13675. It has (likely) been fixed for the next version of Cura.

**Closed by fieldOfView** 2023-01-02 14:29 UTC
Labels: Type: Bug, Status: Triage
