### ISSUE TITLE
Slicing engine for Cura has stopped working

### ISSUE THREAD

**Issue by KF5YDG** [Ultimaker/Cura#15560] opened 2023-05-19 02:51 UTC
### Application Version

5.3.1

### Platform

Windows 11

### Printer

Anycubic Kobra Max

### Reproduction steps

Ran slicer 

### Actual results

Slicing stops and popup says "Slicing engine for Cura has stopped working"

### Expected results

For item to be sliced
[back 3mk 85 by do3d.zip](https://github.com/Ultimaker/Cura/files/11513079/back.3mk.85.by.do3d.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

thanks

**Comment by GregValiant** [comment] 2023-05-19 10:57
Thanks for the report and the file.
I rotated the model -90° and it sliced.
This is a duplicate of numerous other reports of this behavior.  I'll mark it and close it as the Cura team has a lot of examples to look at.
![image](https://github.com/Ultimaker/Cura/assets/64202104/e3f3b664-44e9-4935-ae9b-f06ac372b825)

**Closed by GregValiant** 2023-05-19 10:57 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error :collision:
