### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by justinreed270** [Ultimaker/Cura#11384] opened 2022-01-30 21:31 UTC
### Application Version

4.12.1

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

I imported a STL file. 

I clicked slice.

The slice error message appeared. 

### Actual results

message failure

### Expected results

The file should be slices and I should be able to send it to my Ender 3 via OctoPi server.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

N/a

**Comment by fvrmr** [comment] 2022-01-31 15:46
Hi @justinreed270 thank you for your report.
Could you share your project file (file - save project) as a .zip and your log file: `C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`
Without these files it is difficult to know what could cause this.

**Comment by justinreed270** [comment] 2022-01-31 16:02
I wish I would have known that you needed this information...

I ended up uninstalling and reinstalling Cura... This fixed the issue. Next
time, I will save the logs and project in a .zip file and send it to your
company.

Thanks,

Justin Reed

731.592.0565

**Comment by fvrmr** [comment] 2022-02-01 09:31
Hi @justinreed270 thank you for your reply.
Good to know that the issue is fixed for you.
I will close this issue, but reach out if it happens again!

**Closed by fvrmr** 2022-02-01 09:31 UTC
Labels: Type: Bug
