### ISSUE TITLE
[5.5.0 b1] Skirt is not continuous and contains multiple large travel moves

### ISSUE THREAD

**Issue by massis87** [Ultimaker/Cura#17076] opened 2023-10-23 06:37 UTC
### Cura Version

5.5.0 beta 1

### Operating System

Windows 11

### Printer

Voron Trident

### Reproduction steps

I have a model with a square 90x90mm base, I've added 9 of them to the baseplate with minimal spacing. 
Print settings include a 3 line count skirt, with 1.5mm distance to model and a minimum length of 750mm.
I also have "avoid printed parts when Traveling" active, which comes into play.

I've seen it happen on multiple objects/prints but cannot consistently reproduce it.

### Actual results

The skirt starts in front left, goes straight back and then right (as expected) but then stops, after which a travel move is done which moves in between the (yet to be ) printed objects back to the front left, where it starts a second loop. That loop is then completely made, followed by a 2nd and 3rd complete loop. Finally it stops again, travels to the front right where it adds a tiny section of the corner before moving back to the front left to start the actual print.

### Expected results

I would expect slicing to pick a point somewhere around the objects and loop around it a minimum of 3 times in a single continous line.

### Add your .zip and screenshots here ⬇️
added the skirt section of the gcode in question:
[skirt_issue.zip](https://github.com/Ultimaker/Cura/files/13066865/skirt_issue.zip)

**Comment by GregValiant** [comment] 2023-10-23 20:29
Thanks for the report.
There are a couple of new features in Cura and I think you are seeing two come into play here.
The first is that when you have a model right near the edge of the build plate Cura will allow it to slice by ignoring the skirt/brim along the edges where it simply won't fit.  You can see that happening in this screenshot where the skirt ends because it no longer fits between the model and the front edge of the bed.  In previous versions of Cura the model simply didn't slice if was too close to the edge.  Now it will, but you get that partial skirt/brim.
This is LAYER:0
![image](https://github.com/Ultimaker/Cura/assets/64202104/d882bd58-c0c1-48a7-ba80-0d4374f3f289)

The second thing is "Skirt Height" so during the two followup layers some material is added to the skirt to (allegedly) make it easier to remove.  Whether it is layer 0, 1, or 2 the skirt is not continuous and so Cura starts and stops while printing it.
If you were to group those models and move the group to the midpoint of the Cura build plate you would see the skirt go down all at once.  Setting the "Skirt Height" to 1 will eliminate the nozzle revisiting the skirt on the second and third layers.

So this is not a bug but rather "expected behavior".  I'll remove the bug label and go ahead and close this.  Let me know if you feel that is premature.

**Closed by GregValiant** 2023-10-23 20:29 UTC
Labels: Type: Discussion, Status: Under Investigation
