### ISSUE TITLE
[3.6.0] Non-exclusive use of tty device

### ISSUE THREAD

**Issue by sk8nfool** [Ultimaker/Cura#5398] opened 2019-03-06 14:39 UTC
**Application Version**
Cura 3.6.0

**Platform**
Ubuntu 18.04

**Printer**
Ender-2

**Steps to Reproduce**
Run an instance of Cura, Start a print, Once printing starts start a second instance of Cura.

**Actual Results**
The first print stops and both instances have connected to the same printer

**Expected results**
The second instance should auto connect to a different printer or no printer

**Additional Information**
I checked if the tty (/dev/ttyUSB0) was still available using "date < /dev/ttyUSB0" and it was (I expected the date command to fail with an open error it the tty was in use)

**Comment by Ghostkeeper** [comment] 2019-03-07 08:51
Duplicate of https://github.com/Ultimaker/Cura/issues/5207

**Closed by Ghostkeeper** 2019-03-07 08:51 UTC
