### ISSUE TITLE
bizarre lines visualised in preview mode

### ISSUE THREAD

**Issue by hugo-gu** [Ultimaker/Cura#11143] opened 2021-12-28 12:22 UTC
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Modified Ender 3 PRO profile

### Reproduction steps

I was slicing some models in "print sequence: one at a time" mode. When I went into the visualise tab and scrolled in the layer view to layer 137 and noticed some strange lines. originally I assumed these were just travel lines but after further inspection, I realised they were not. they do not appear on any other layer and I have do not have "travels" selected in my view settings (line type). strangely when I deselect infill some of the strange lines disappear
![Screenshot 2021-12-28 121514](https://user-images.githubusercontent.com/62945847/147565339-c157b276-3aa7-45b2-ab38-3d485ad9736f.jpg)
.

### Actual results

I have not seen this while slicing any other models but it seems to happen every time I slice these models, I have tried changing a few settings but I still get this strange bug

### Expected results

I believe these lines should not be showing
[cura.log](https://github.com/Ultimaker/Cura/files/7784581/cura.log)
g

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[CE3PRO_Body2.zip](https://github.com/Ultimaker/Cura/files/7784589/CE3PRO_Body2.zip)

**Comment by fvrmr** [comment] 2022-01-03 11:02
Hi @hugo-gu thank you for your bug report. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11057
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2022-01-03 11:02 UTC
Labels: Type: Bug
