### ISSUE TITLE
Layers pop up doesn't fit in the window

### ISSUE THREAD

**Issue by sedwards2009** [Ultimaker/Cura#2110] opened 2017-07-13 06:53 UTC
See the layers pop up in the bottom left corner. It is mostly off screen and usable.

![cura_layer_dont_fit](https://user-images.githubusercontent.com/6926644/28153935-567650bc-67a8-11e7-870a-0d28e5625c7c.png)

This is Cura 2.6.1, AppImage on Linux/KDE, with 1920x1080 on a 14" laptop (thus a somewhat higher DPI than most older desktop monitors.) I'm guessing this is Qt's HiDPI scaling in effect.

**Comment by fieldOfView** [comment] 2017-07-13 07:13
Hi Simon, this was fixed for Cura 2.7 here: https://github.com/Ultimaker/Cura/pull/2016

Duplicate of https://github.com/Ultimaker/Cura/issues/2013 and https://github.com/Ultimaker/Cura/issues/2080

It is not so much the HiDPI scaling effect, but more not taking into account smaller screens while adding buttons to the toolbar (extruder buttons).

**Closed** 2017-07-13 07:43 UTC
