### ISSUE TITLE
Feature Request: Show Settings Different From Profile

### ISSUE THREAD

**Issue by sleemanj** [Ultimaker/Cura#4540] opened 2018-10-10 23:49 UTC
In simple terms, a manner in which we can select to see thew settings which are different from the profile (the ones with the circular arrow), and ONLY those.  Rather than having to show all setting and then scroll through the list looking for circular arrows.

![a12](https://user-images.githubusercontent.com/207209/46772358-21093a80-cd54-11e8-8f7b-01c05f05155e.jpg)

**Comment by fieldOfView** [comment] 2018-10-11 08:36
At one point in the history of the SettingVisibilityPresets menu, I was planning to add this (https://github.com/Ultimaker/Cura/commit/503c612509346d5a215953255d9230c1e2dc9288#diff-47c5e3ec9d6202c11682ef44841784ac), but I did not get around to implementing it.

**Comment by ChrisTerBeke** [comment] 2018-10-11 09:44
Note that you can see a diff already when you switch to another profile and you have unsaved changes.

**Comment by Ghostkeeper** [comment] 2018-12-14 08:43
A couple of UX things to think about:
* If you don't have any changes, what will it display?
* If the value for a profile setting is currently at 0.4mm and you want to type "0.45mm", should the setting briefly disappear after displaying "0." and before displaying "0.45"?
* If you click on one of the reset buttons, should the setting disappear too?

**Comment by Ghostkeeper** [comment] 2018-12-14 08:45
Ah, hold on. This is a duplicate of #3713. I'll post those concerns there.

**Closed by Ghostkeeper** 2018-12-14 08:45 UTC
