### ISSUE TITLE
Unable to select models on the table with the mouse pointer after entering the change model type menu

### ISSUE THREAD

**Issue by glazkovigor** [Ultimaker/Cura#9138] opened 2021-01-17 13:31 UTC
**Application version**
4.8.0

**Platform**
MAC OS Big Sur 11.1 (20C69)

**Printer**
Ender 3, Coustom printer.

**Reproduction steps**
The interface works well until you click on the button to change the model type (shown in the screenshot). If you click on the button, then it is not possible to select the model on the table with the mouse. It just is not marked. In this case, you can rotate the camera, the menu items are pressed and work correctly.

![Снимок экрана 2021-01-17 в 16 16 08](https://user-images.githubusercontent.com/46419472/104844148-7e9b7280-58df-11eb-9418-e1e4a7dbc24c.png)

The problem is seen on any loaded models.

The problem does not depend on the program settings.
Reinstallation with clearing the program cache does not help. The problem manifests itself on version 4.7.0 and higher. It was not possible to check the younger versions, they do not start on this version of the operating system.

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/5826159/cura.log)

**Comment by fvrmr** [comment] 2021-01-18 12:20
Can you share your project file? I can't reproduce this right now.

**Comment by glazkovigor** [comment] 2021-01-18 18:59
> Can you share your project file? I can't reproduce this right now.
Yes, I added a file.

I found a very similar problem described by issues (#8745)
Suggested solutions in the post [https://github.com/Ultimaker/Cura/issues/8745#issuecomment-756965115] also help me, but this issues of course needs to be solved somehow ...

**Comment by ehusar** [comment] 2021-01-19 00:11
One thing to add. If I leave Cura open for an extended time period, say 3-4. hours untouched, then load a new model I have this same issue.  The model cannot be selected.  If I exit Cura and restart it, load the model, then I can select it.

**Comment by fvrmr** [comment] 2021-01-19 10:22
I'm gonna close this, because it is a duplicate of https://github.com/Ultimaker/Cura/issues/8745

**Closed by fvrmr** 2021-01-19 10:22 UTC
Labels: Type: Bug
