### ISSUE TITLE
The material diameter isn't updated when changing materials

### ISSUE THREAD

**Issue by Seeyainthex** [Ultimaker/Cura#1825] opened 2017-05-13 17:01 UTC
I set up two different materials with different temps & diameters.  Only the temps are updated.

**Comment by fieldOfView** [comment] 2017-05-13 17:06
@Seeyainthex what version of Cura are you using?
Duplicate of https://github.com/Ultimaker/Cura/issues/1687

**Comment by Seeyainthex** [comment] 2017-05-13 17:21
Just installed 2.5. Problem still there.  Also used 2.3.  on Windows.

**Comment by Seeyainthex** [comment] 2017-05-13 17:34
OK I'll wait for 2.6.

**Comment by Seeyainthex** [comment] 2017-05-14 22:28
Fixed in upcoming rlse

**Closed** 2017-05-14 22:28 UTC
