### ISSUE TITLE
Extrusion Cool Down Speed Modifier crashes Cura 3.2.1

### ISSUE THREAD

**Issue by amagr0** [Ultimaker/Cura#3442] opened 2018-03-06 10:28 UTC
**Application Version** - CURA 3.2.1
**Platform** - Win 10 Pro, 64 bit
**Display Driver** - NVIDIA GeForce 840M

**Steps to Reproduce** - Select a dual extrusion printer, and modify the "Extrusion Cool Down Speed Modifier" to 2 ºC/s.

**Actual Results** - "CuraEngine.exe. has stopped working"

**Expected results** - Successfully slicing

![screenshot_1](https://user-images.githubusercontent.com/12901952/37027368-09a826d0-2129-11e8-877a-38039c230752.jpg)

**Comment by BagelOrb** [comment] 2018-03-06 11:02
Please attach your project file.

For an Ultimaker 3 the Extrusion cooldown speed modifier can't be above 1.6, because that is the value of the machine_nozzle_heat_up_speed, which is a machine setting which is not configurable by the user.

I cannot reproduce it.

**Comment by amagr0** [comment] 2018-03-06 11:52
[BEEVC.curaproject.curaproject.3mf.zip](https://github.com/Ultimaker/Cura/files/1784840/BEEVC.curaproject.curaproject.3mf.zip)

**Comment by BagelOrb** [comment] 2018-03-06 13:39
My Cura doesn't crash.

Note that an extrusion cool down speed modifier of 2 is highly unlikely, because the heatup speed is 2.
That means that the extruder is unable to heat up during printing ( 2 - 2 = 0 ).

Perhaps that setting should be limited to just under 2, rather than 2.

Note to other testers: you still need to manually set the Extrusion Cool Down Speed Modifier to 2.

**Comment by alekseisasin** [comment] 2018-03-06 15:17
I confirm it crashes in Cura 3.2.1. I checked your project in "development/latest" Cura version and it already works fine. I want to ask you to wait next Cura version.

**Comment by alekseisasin** [comment] 2018-03-07 08:25
@amagr0 I will close this issue, the fix already added.

**Comment by diegopradogesto** [comment] 2019-09-10 14:58
This was indeed fixed a while ago but this ticket was never closed.

**Closed by diegopradogesto** 2019-09-10 14:58 UTC
Labels: Category: Engine, Status: Fixed/Solved, Type: Bug
