### ISSUE TITLE
[4.1.0 Beta] Machine settings Start G-code input display corrupt

### ISSUE THREAD

**Issue by bobstro** [Ultimaker/Cura#5779] opened 2019-05-24 23:12 UTC
**Application Version**
4.1.0 Beta

**Platform**
MacOS Mojave 10.14.5 on 27" iMac 5K

**Printer**
Prusa i3 Mk3

**Steps to Reproduce**
Attempt to modify printer Start G-code

**Actual Results**
Display of gcode is corrupted. Scroll bars are erratic and appear in middle of dialog box. Pasted text is accepted and works, but it is very difficult to review.

**Expected results**
Entry and editing of text using normal platform editing commands, proper display of text.

[XYZ Cube.3mf.zip](https://github.com/Ultimaker/Cura/files/3218829/XYZ.Cube.3mf.zip)
<img width="780" alt="Screenshot 2019-05-24 19 06 40" src="https://user-images.githubusercontent.com/32421635/58360610-c098ba80-7e57-11e9-98fb-dcdee6a3f510.png">

**Additional Information**

**Comment by Liger0** [comment] 2019-05-25 15:44
Maybe related: #5742

**Comment by Ghostkeeper** [comment] 2019-05-28 13:51
Yeah I think it's a duplicate of #5742. Please continue discussion there.

**Closed by Ghostkeeper** 2019-05-28 13:51 UTC
