### ISSUE TITLE
Cura 2.3.0 100% Infill not showing and not printing.

### ISSUE THREAD

**Issue by Underp4ntz** [Ultimaker/Cura#1105] opened 2016-11-03 15:35 UTC
It seems Cura 2.3.0 doesn't want to show the 100% infill and it wont print it either way.
And Cura 2.1.3 does well with showing the infill and printing it.

Cura 2.3.0
![cura230](https://cloud.githubusercontent.com/assets/23241521/19972763/62eadba0-a1e3-11e6-97f7-ee31e4a17461.jpg)

Cura 2.1.3
![cura213](https://cloud.githubusercontent.com/assets/23241521/19972764/62f0324e-a1e3-11e6-8809-e42438efc862.jpg)

Also the Dimensions of the model seems off. 

Dimensions in Cura 2.3.0: 33.5mm x 33.5mm x 9.0mm
Dimensions in Cura 2.1.3: 33.4mm x 33.4mm x 9.0mm

So whats up with that?

**Comment by nickthetait** [comment] 2016-11-03 16:26
Could you upload the model or point to where it was downloaded?

**Comment by Ghostkeeper** [comment] 2016-11-04 12:31
The infill can be explained. It is the Fill Small Gaps feature that has perished in version 2.3. We're planning to bring it back for version 2.4.

The dimensions are indeed different. It might be some change to the scene transformation engine we made for 2.3. I wonder which are the correct dimensions though?

**Comment by Ghostkeeper** [comment] 2016-11-04 12:31
The infill is a duplicate of https://github.com/Ultimaker/Cura/issues/1099

**Closed** 2017-02-24 10:56 UTC
Labels: duplicate, enhancement, release: master
