### ISSUE TITLE
Scaling doesn't follow rotation

### ISSUE THREAD

**Issue by ToyMaker62** [Ultimaker/Cura#8369] opened 2020-09-11 12:10 UTC
**Application version**
4.7.1

**Platform**
Mac

**Printer**
Ender 3 Pro

**Reproduction steps**
1. Uncheck Uniform Scaling
2. Change part scaling
3. Rotate the part, the mm correctly rotate, the % does not change positions

**Actual results**
Any further attempt to change values by changing the % field adjusts the size based on the original position and not the current view.

**Expected results**
When a rotation occurs and the Y and Z axis exchange, the dimensions as well as the % change should follow the rotation.

**Comment by konskarm** [comment] 2020-09-14 08:57
Hi @ToyMaker62. This has been an issue for a long time now. Duplicate of https://github.com/Ultimaker/Cura/issues/4136 so I am closing this one. If needed, please continue the discussion there.

**Closed by konskarm** 2020-09-14 08:57 UTC
Labels: Type: Bug
