### ISSUE TITLE
Reload objects in .3mf projects is not working

### ISSUE THREAD

**Issue by Bbop-3D** [Ultimaker/Cura#7791] opened 2020-05-19 14:41 UTC
**Application version**
<= 4.6.1 (all)

**Platform**
Win10x64

**Printer**
not relevant (custom i3 clone)

**Reproduction steps**
1) in Cura slice example.stl and save as example.3mf project (same directory stl & 3mf), close Cura
2) in new started Cura open example.3mf project 
3) modify test.stl with cad software and save at same place and same name
4) in Cura press F5 (reload objects) does not reload .stl from same directory, it seems to reload object from .3mf file (if any) - this seems to be senseless for me, because it will never change...

If you open a .stl directly in cura (or drag and drop) then F5 is working.

It is a bit of frustrating if you have a complex 3mf with many support blockers and there is a need to change the original stl. If the initial instance of Cura (wich knows the path of the stl) is closed, you can't reload the objects any more without deleting and open the stl again. Then you have to generate all support blockers again!
My workaround: Keep (many instances of) Cura and PC running all the time...

**Expected results**
When opening a 3mf project, F5 should reload the .stl from same path as .3mf (or at least reload .stl from origin path)

I'm not sure if it is a bug or a feature request, maybe it's a limitation of the 3mf format.

Edit: just seen this is already addressed at [#7680](https://github.com/Ultimaker/Cura/issues/7680)

**Comment by mahtDFR** [comment] 2020-05-19 14:57
As this is a duplicate of #7680 I will close it

**Closed by mahtDFR** 2020-05-19 14:57 UTC
Labels: Status: Duplicate, Type: Bug
