### ISSUE TITLE
Good evening. I'm trying to create a 3D model calculator for my website. I was told that you can use the Cure/Cura Engine slicer. How do I understand how to work with curaengine —stl MYSTL.stl —config CONF.json Example of the calculator on the website: A person loads the model and sees the weight of the model, the approximate time of printing. ( Sorry for my English)

### ISSUE THREAD

**Issue by Creativ671** [Ultimaker/Cura#3614] opened 2018-04-02 19:07 UTC
Good evening. I'm trying to create a 3D model calculator for my website. I was told that you can use the Cure/Cura Engine slicer. How do I understand how to work with curaengine —stl MYSTL.stl —config CONF.json
Example of the calculator on the website: A person loads the model and sees the weight of the model, the approximate time of printing.
( Sorry for my English)

**Comment by ianpaschal** [comment] 2018-04-03 07:05
Duplicate of #3556.

Please do not write your question in the title.

**Closed by ianpaschal** 2018-04-03 07:05 UTC
