### ISSUE TITLE
Ability to Add print information to G-Code file name when Saving.

### ISSUE THREAD

**Issue by mcolojr** [Ultimaker/Cura#6804] opened 2019-12-13 13:11 UTC
It's hard remembering things like what nozzle size or what material was used for an older G-Code file. So I usually manually add that information in the file name. It's a pain.

It would be nice there were some options to add print settings information to the .gcode file name when saving so we don't have to do it manually every time. Things like _Nozzle Size_, _Layer Height_, _Profile Name_, _Time Estimation_, _Material Used_, etc.

Example File Name:
_CE3_iPhoneXCase_.48LayerHeight_6mmNozzle_1h48m_PLA.gcode_

In **Preferences** > **General** 
We see there is an option to Add machine prefix to job name.
<img width="775" alt="Screen Shot 2019-12-13 at 1 36 25 PM" src="https://user-images.githubusercontent.com/57288342/70802193-13fd3680-1db1-11ea-8a51-1e99e9c17871.png">
It would be nice if somehow there were more checkbox options for adding information to the .gcode file name. I feel these extra options would be appropriate under this section.

This would be a great feature for amateurs or professionals that like to stay more organized.

**Comment by smartavionics** [comment] 2019-12-13 14:08
Take a look at this plugin...

![Screenshot_2019-12-13_14-07-25](https://user-images.githubusercontent.com/585618/70805890-f086bb80-1db1-11ea-8697-7f4a7cd46488.png)

**Comment by mcolojr** [comment] 2019-12-13 16:37
@smartavionics Thanks for sharing! This plugin seems like a good solution although I'm having trouble figuring out if there is a way to add the objects name first. It automatically places it at the end.

**Comment by smartavionics** [comment] 2019-12-13 16:51
You need @fieldOfView to answer that. Cheers!

**Comment by Ghostkeeper** [comment] 2019-12-16 10:34
Duplicate of https://github.com/Ultimaker/Cura/issues/3753 (and solved by that plug-in that fieldOfView wrote too).

**Closed by Ghostkeeper** 2019-12-16 10:34 UTC
Labels: Type: New Feature

**Comment by fieldOfView** [comment] 2019-12-16 10:49
@mcolojr for the plugin only changes the _pre_fix that Cura already supports. Theoretically, the plugin could try replacing (more) parts of Cura to support a postfix, but this would increase the chance of the plugin breaking when Cura is updated.
