### ISSUE TITLE
Adaptive Layers Issue With Model Off Build Plate

### ISSUE THREAD

**Issue by jorlain83** [Ultimaker/Cura#11541] opened 2022-02-24 15:26 UTC
### Application Version

4.13.1

### Platform

Windows 11

### Printer

Creality CR6 SE

### Reproduction steps

1. Raise model from build plate
2. Enable "Use Adaptive Layers"
3. Slice

### Actual results

Application indicates a build time and material usage of 0 and does not slice the model.

### Expected results

Model is sliced and has an estimated build time and material usage.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[AdaptiveLayerIssue.zip](https://github.com/Ultimaker/Cura/files/8133662/AdaptiveLayerIssue.zip)
![OnBuildPlateWithAL](https://user-images.githubusercontent.com/100365699/155554156-3b5f67a3-7e00-45dd-b934-c6ac043d7e03.jpg)
![OffBuildPlateWithAL](https://user-images.githubusercontent.com/100365699/155554161-2b600763-bb4c-4391-9c06-dec5211f2e45.jpg)
![OffBuildPlateWithoutAL](https://user-images.githubusercontent.com/100365699/155554164-220779f9-6cb1-4c16-8e58-b2c8a81f3683.jpg)

**Comment by fvrmr** [comment] 2022-02-28 10:50
Hi @jorlain83 thank you for your report.
I will bring it up with the team. Keep you posted.

**Comment by Ghostkeeper** [comment] 2022-03-12 18:36
What was the result of that discussion?

Seems like the same as this issue: https://github.com/Ultimaker/Cura/issues/3183

**Comment by fvrmr** [comment] 2022-03-21 16:29
I forgot to update the status, but we decided to defer this, it has not a high priority to fix this. 
I will close this issue since it is indeed a duplicate of #3183

**Closed by fvrmr** 2022-03-21 16:29 UTC
Labels: Type: Bug
