### ISSUE TITLE
Open GL crash

### ISSUE THREAD

**Issue by ml878us** [Ultimaker/Cura#11953] opened 2022-04-25 05:31 UTC
### Application Version

5

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

Installed and tried to open

### Actual results

On my desktop (W10 64/i5/Lenevo) it wont open and gives an error about Open GL. On my laptop (W1065/i5/Dell) it opens fine. Both machines show drivers up-to-date.

### Expected results

Should open and run

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Screen](https://user-images.githubusercontent.com/94803735/165026276-6dd85a8a-b508-4e2a-8f89-a2831de30d51.jpg)

**Comment by groomit** [comment] 2022-06-10 07:36
Same issue here on linux. Used to work on appImage 4.11.

OS:
Pop!_OS 22.04

Cura Version:
5.0

**Comment by nallath** [comment] 2022-06-10 14:41
Duplicate of #12359

**Closed by nallath** 2022-06-10 14:41 UTC
Labels: Type: Bug
