### ISSUE TITLE
Selection Bug

### ISSUE THREAD

**Issue by jflund** [Ultimaker/Cura#9396] opened 2021-03-13 15:06 UTC
### Application Version

4.8.0

### Platform

Mac OS

### Printer

Ultimaker 3

### Reproduction steps

Add a model to Cura
Switch to either the Preview or Monitor tabs
Try to select a model by clicking on it

### Actual results

After the above steps, the model cannot be selected by clicking, and any tools (rotate tool, move tool, etc.) also cannot be clicked or used.

### Expected results

Should be able to select, move, scale models.

I know you have known about this for months now, how is it not fixed? This is a MAJOR usability bug, making Cura almost unusable. The only way a model can be moved, scaled, or rotated is close Cura and reopen it. Please fix it! No company that truly cares about its customers lets a bug like this persist for months!

**Comment by fvrmr** [comment] 2021-03-15 13:01
Hi @jflund thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/8745
We are working on a solution and we have  made a testing build with Qt 5.15 and it shows that this indeed fixes the Big Sur issue. Progress with the upgrade of the Qt version is still ongoing. There are other crashes still to solve now.

I will close this issue because of the duplicate. Hope you understand.

**Closed by fvrmr** 2021-03-15 13:01 UTC
Labels: Type: Bug
