### ISSUE TITLE
Fenetre en dehors de l'écran.

### ISSUE THREAD

**Issue by didierma34** [Ultimaker/Cura#14871] opened 2023-03-13 17:45 UTC
### Application Version

5.2.2

### Platform

Windows 11

### Printer

TL D3Pro

### Reproduction steps

Ouverture de l'application

### Actual results

La fenêtre est en dehors de l'écran.
Il faut la lancer en plein écran pour la retrouver.
Je précise que j'ai deux écrans.

### Expected results

La fenêtre est en dehors de l'écran.
Il faut la lancer en plein écran pour la retrouver.
Je précise que j'ai deux écrans.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Pas de fichier

**Comment by MariMakes** [comment] 2023-03-14 16:35
Hey @didierma34,

Je m'excuse, je ne parle pas français mais je pense que je peux vous aider.

Apologies for the inconvenience. 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/11907
We have a ticket on our backlog with the intent to improve this behavior.
But we are mainly dependent on QT to resolve their bug. 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/11907

This is a list of workarounds that might help:
1. Do you have multiple monitors? Does Cura start if you disable one of the monitors?
2. Do you have two monitors placed above each other? Can you try this workaround from the community? ttps://community.ultimaker.com/topic/42633-cura-522-stopped-working/#comment-318105
3. Do you have GPU Tweak OSD overlay enabled? Does Cura start if you disable that software?
4. Do you have a Ryzen Graphics card? Can you try this workaround? https://support.makerbot.com/s/article/1667412437627
5. Do you have the Nahimic audio enhancement service enabled? Can you try this workaround? https://github.com/Ultimaker/Cura/issues/12102#issuecomment-1157907665

**Closed by MariMakes** 2023-03-14 16:35 UTC
Labels: Type: Bug, Status: Triage
