### ISSUE TITLE
[4.6.1] support does not touch buildplate

### ISSUE THREAD

**Issue by berberic2** [Ultimaker/Cura#7810] opened 2020-05-23 13:17 UTC
**Application version**
4.6.1

**Platform**
Linux

**Printer**
Monoprice Delta Mini

**Problem**
If _Support Placement_ is set to _Everywhere_ Cura make a gap below support that is based on the buildplate and does not startr al first layer. This makes support free floating and (small) support structures fail.
The gap is necessary if the support sits on top a build part, but not on support that sits on the buildplate.

**Resolution**
Support that is based on the buildplate should **always** start at first layer without a gap, regardless of settings.

**Comment by berberic2** [comment] 2020-05-23 13:38
Screenshots of layer 1, 2, 3 and 4, showing that support in the holes start at layer **4**.

![Screenshot_20200523_153515](https://user-images.githubusercontent.com/13178920/82732060-38b7eb80-9d0b-11ea-9678-a487e37ea9df.png)
![Screenshot_20200523_153520](https://user-images.githubusercontent.com/13178920/82732062-3c4b7280-9d0b-11ea-98cd-742a70434647.png)
![Screenshot_20200523_153526](https://user-images.githubusercontent.com/13178920/82732067-3f466300-9d0b-11ea-9bf8-c06ac15c2e6d.png)
![Screenshot_20200523_153533](https://user-images.githubusercontent.com/13178920/82732069-42d9ea00-9d0b-11ea-848b-abc98c455970.png)

**Comment by 64Florian** [comment] 2020-05-23 13:40
Hello,
Could you add an example with your CURA with your settings and click on "File" -> "Save" ->"Save" -> "Save" (after providing a filename)
The output file is an "3mf" file. Please Zip the file and drop it in a post in your ticket.
=> This file is really useful to see / understand / reproduce the same behavior as you describe
(_As I know / see I'm not able to reproduce on my version_)

Thank you

**Comment by 64Florian** [comment] 2020-05-24 00:39
For dev team / as memo: could it be the same issue as #7808

**Comment by berberic2** [comment] 2020-05-24 12:32
sure.
Project file of example above.
[MMD_Part_1.3mf.zip](https://github.com/Ultimaker/Cura/files/4673477/MMD_Part_1.3mf.zip)

**Comment by 64Florian** [comment] 2020-05-24 13:39
Thank you @berberic2 
unfortunately, It seems something missing in the file to make the same workspace as yours 
![Capture d’écran 2020-05-24 à 15 31 33](https://user-images.githubusercontent.com/34726380/82755483-14741180-9dd4-11ea-9368-e4d5e84e4ce9.png)
I'll try to use normal default but with my settings I'm not able to reproduce 
![Capture d’écran 2020-05-24 à 15 34 55](https://user-images.githubusercontent.com/34726380/82755500-2c4b9580-9dd4-11ea-999c-d925ec95b9be.png)

Could you go in Cura, -> "Help" -> "Show configuration folder" -> a file explorer should be opened with a 4.6 folder selected 
Pleas zip this folder and add it in this ticket (_this folder contain all your printer profile_)

**Comment by 64Florian** [comment] 2020-05-24 13:49
Just for you,
For this product, you should use "Grid" @ 0% infill... your product should be better printed (_In my point of view_)
but it's another thing

**Comment by berberic2** [comment] 2020-05-24 19:08
The .3mf contains the machine definition and the filament definition. 
```
.
├── 3D
│   └── 3dmodel.model
├── [Content_Types].xml
├── Cura
│   ├── 3djake_pla_silber.xml.fdm_material
│   ├── monoprice_mini_delta.def.json
│   ├── monoprice_mini_delta_extruder_0 #2.extruder.cfg
│   ├── monoprice_mini_delta_extruder_0 #2_settings.inst.cfg
│   ├── monoprice_mini_delta_extruder_0 #2_user.inst.cfg
│   ├── monoprice_mini_delta_extruder_0.def.json
│   ├── Monoprice Mini Delta.global.cfg
│   ├── monoprice_mini_delta_Global_Fast_Quality.inst.cfg
│   ├── Monoprice Mini Delta_settings.inst.cfg
│   ├── Monoprice Mini Delta_user.inst.cfg
│   ├── preferences.cfg
│   └── version.ini
├── _rels
└── X.zip
```

So this seems to be another bug in cura, in the project load or save routine.
_Grid_ for _**support-**_ or _**infill-**_pattern and 0 % _**infill**_ ?!

**Comment by rburema** [comment] 2020-05-24 20:15
@berberic2 Could you try to setting either (or both) 'Support Stair Step Width' or 'Support Stair Step aximum Height' to 0? Just trying to confirm if this is a known issue (that we maybe finally getting to soon).

**Comment by berberic2** [comment] 2020-05-25 07:44
> Could you try to setting either (or both) 'Support Stair Step Width' or 'Support Stair Step aximum Height' to 0?

Setting either of these values to 0 solves the problem.

**Comment by Ghostkeeper** [comment] 2020-05-26 09:00
This is a duplicate of https://github.com/Ultimaker/Cura/issues/6379.

**Closed by Ghostkeeper** 2020-05-26 09:00 UTC
Labels: Type: Bug
