### ISSUE TITLE
Crashing when trying to open files

### ISSUE THREAD

**Issue by imLokiGod** [Ultimaker/Cura#10744] opened 2021-11-04 22:18 UTC
### Application Version

4.12.0

### Platform

Windows 11

### Printer

Anycubic Chiron

### Reproduction steps

When I try to open files, if I click directly on a file in explorer, the whole thing crashes. If I select a folder on the left hand menu, and then a sub folder, file, it will not crash. But directly on right hand window, hitting an icon will crash Cura

### Actual results

Cura shuts down completely 

### Expected results

Files should be able to open

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

....

**Comment by fvrmr** [comment] 2021-11-05 10:05
Hi @imLokiGod thank you for your bug report.
Could you share your log file? You can find your log file here: `C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`

I am also wondering if you have Chitubox installed? If so it is a duplicate of #9668

**Closed** 2021-11-19 10:41 UTC
Labels: Type: Bug, Status: Needs Info
