### ISSUE TITLE
Brim only on outside still partially puts a brim on the inside

### ISSUE THREAD

**Issue by KoenVanduffel** [Ultimaker/Cura#11547] opened 2022-02-25 22:09 UTC
### Application Version

4.13.1 4.12.1 and Arachne engine beta 2

### Platform

Windows 10

### Printer

Creality CR-6

### Reproduction steps

Slice the model https://www.prusaprinters.org/prints/126838-cr-6-direct-drive-dragon-hf-sf-and-orbiter-v15-mou the main mount block of this complete hotend assembly. Slice with a default 0.4 mm profile (several people have reported the exact same behavior)  and with the brim only on outside off the expected behavior is seen: all 3 the letters and the spaces between the vanes get filled with brim material. When Brim only on outside is ticked the R and the 6 still get a brim.

The model is made in Fusion 360 and the text is a simple emboss about 8 mm high text.

### Actual results

![image](https://user-images.githubusercontent.com/13643644/155809457-b3d94efa-5348-4e6f-819a-14933e1fd31c.png)
There is a partial brim in the R and 6.

### Expected results

no brim in the R and 

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CR-6 LGX Lite & Dragon mount.zip](https://github.com/Ultimaker/Cura/files/8145127/CR-6.LGX.Lite.Dragon.mount.zip)

**Comment by fvrmr** [comment] 2022-03-03 10:04
Hi @KoenVanduffel thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/4222 and we have a ticket on our backlog for this.
I will close this issue, since it is a duplicate.

**Closed by fvrmr** 2022-03-03 10:04 UTC
Labels: Type: Bug
