### ISSUE TITLE
Adjustable Wall Line Count on Top Skin Layer

### ISSUE THREAD

**Issue by Lecso11** [Ultimaker/Cura#11207] opened 2022-01-06 18:18 UTC
### Is your feature request related to a problem?

A setting where we can set the number of walls on the top skin layer individually would be useful for small top surfaces. It makes them virtually bigger and results in better top layer quality and a more unified surface. 

### Describe the solution you'd like

A setting in the Top/Bottom category, where I can determine the numbers of walls on the top layer. 

### Describe alternatives you've considered

No alternative solution in Cura

### Affected users and/or printers

Everybody, the problem is mostly visible on small top areas.

### Additional information & file uploads

Photos attached of single top perimeter prints sliced in SuperSlicer.

https://ultimaker.sendsafely.com/receive/?thread=13YL-YDAR&packageCode=tqG0rIv7WY8y1O7PuEE1PM93J4yCHuXCpl0C0j0oWrc#keyCode=DczhMxRlINndCxIfWvtgYJWOX3OXMKN4CvmP1Cb1Dsg

**Comment by fvrmr** [comment] 2022-01-07 11:10
Hi @Lecso11 thank you for your request.
From the pictures it looks like the following issue: https://github.com/Ultimaker/Cura/issues/10834 and that one was closed because it is a duplicate of https://github.com/Ultimaker/Cura/issues/7324 which is more about the first layer but has the same effect for the top layer. So I will close this issue because it is a duplicate.

**Closed by fvrmr** 2022-01-07 11:10 UTC
Labels: Type: New Feature
