### ISSUE TITLE
FLSUN QQS printer ghost rotated out-of-phase

### ISSUE THREAD

**Issue by matthewbaggett** [Ultimaker/Cura#11544] opened 2022-02-25 08:44 UTC
### Application Version

4.10 -> 4.13.1 atleast

### Platform

Linux

### Printer

FLSUN QQ-S

### Reproduction steps

Load a part in cura, ghost of printer can be seen rotated incorrectly relative to reality.

### Actual results

Printer is seen to be about 120 degrees rotated from reality

### Expected results

Printer ghost lines up with reality

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![photo_2022-02-25_09-42-16](https://user-images.githubusercontent.com/943948/155683495-f674c45e-cc84-4869-bfe3-b270619fb4e5.jpg)

In this illustration, the green axis arrow is pointing towards the true front of the machine, but the touch panel cutout can be seen facing approximately 120 degrees out of rotation with the bed.

**Comment by fvrmr** [comment] 2022-02-25 10:47
Hi @matthewbaggett thank you for your report.
This is a duplicate of: https://github.com/Ultimaker/Cura/issues/9687 
I will close this as a duplicate.

**Closed by fvrmr** 2022-02-25 10:47 UTC
Labels: Type: Bug
