### ISSUE TITLE
Cura 4.10 crash on first launch after computer startup.

### ISSUE THREAD

**Issue by cmayou** [Ultimaker/Cura#10325] opened 2021-08-22 20:45 UTC
### Application Version

4.10

### Platform

Windows 10

### Printer

Creality Ender3

### Reproduction steps

1. start computer as normal. 
2. launch Cura for the first time
3. Cura Crashes
4. relaunch Cura and it works fine. 

### Actual results

Cura works as expected. 

### Expected results

Cura should open and run just fine any time I want to use it. 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[Cura crash on first launch after reboot.zip](https://github.com/Ultimaker/Cura/files/7028116/Cura.crash.on.first.launch.after.reboot.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/7028120/cura.log)

**Comment by fvrmr** [comment] 2021-08-24 08:57
Hi @cmayou this is a duplicate of https://github.com/Ultimaker/Cura/issues/7744

As a workaround you can edit `%appdata%/cura/4.10/cura.cfg` and add the line `opengl_version_detect = force_legacy` under the `[view]` header.

I will close this issue as a duplicate.

**Closed by fvrmr** 2021-08-24 08:57 UTC
Labels: Type: Bug
