### ISSUE TITLE
Rotation Face Align issue

### ISSUE THREAD

**Issue by Penano** [Ultimaker/Cura#13614] opened 2022-10-20 20:18 UTC
### Application Version

4.10.0

### Platform

Windows 10 Enterprise

### Printer

Ultimaker S5

### Reproduction steps

1. Open stl file in Cura Enterprise 4.10.0 (Has happened to me also in standard Cura 5.1.0)
2. Select model
3. Select face-align in rotation options
4. Click on a flat surface of the model

https://user-images.githubusercontent.com/11069622/197048489-d56bd281-5890-4309-a94b-3c710784f01a.mp4

### Actual results

Model is rotated to a seemingly random orientation

### Expected results

Model is rotated so that selected surface gets aligned with the buildplate

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[UMS5_fxt_23364094_001b.zip](https://github.com/Ultimaker/Cura/files/9833629/UMS5_fxt_23364094_001b.zip)
https://user-images.githubusercontent.com/11069622/197048489-d56bd281-5890-4309-a94b-3c710784f01a.mp4

**Comment by MariMakes** [comment] 2022-10-31 14:50
Hey @Penano,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I checked in Cura 5.2.1 and I can't reproduce the behavior you are describing. 
https://user-images.githubusercontent.com/40423138/199036344-284ce36e-fc2b-441a-b5c7-04edd95a74d4.mp4

I also understood that this performance might be related to your GPU.
https://community.ultimaker.com/topic/41874-select-face-to-align-to-build-plate-item-in-the-rotate-menu-is-missing

Could you check if you still see the behavior in the latest version of Cura?
Thank you 🙏

**Closed** 2022-11-15 17:08 UTC
Labels: Type: Bug, Status: Triage
