### ISSUE TITLE
Cura 4.12 -- not multiplying objects

### ISSUE THREAD

**Issue by ealmeidaus** [Ultimaker/Cura#10865] opened 2021-11-18 00:07 UTC
### Application Version

4.12

### Platform

Mac

### Printer

Creality CR-6 SE

### Reproduction steps

After upgrading to the Cura 4.12 (I had the 4.11 before) it is not possible to multiply the objects. When you select how many you want to duplicate the app just freeze.

### Actual results

Nothing happens. The progress bar remains frozen.

### Expected results

Multiply the selected object based on the qty informed.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

<img width="2560" alt="Screen Shot 2021-11-17 at 6 06 16 PM" src="https://user-images.githubusercontent.com/94577552/142302061-3d9a7eed-7f09-4afb-8a5b-8de885ecfb87.png">

**Comment by fieldOfView** [comment] 2021-11-18 07:27
See #10249

**Comment by fvrmr** [comment] 2021-11-18 10:02
Closing this issue since it is a duplicate of https://github.com/Ultimaker/Cura/issues/10249

**Closed by fvrmr** 2021-11-18 10:02 UTC
Labels: Type: Bug
