### ISSUE TITLE
Problem with slicing object.

### ISSUE THREAD

**Issue by vtozato** [Ultimaker/Cura#10221] opened 2021-08-02 12:48 UTC
### Application Version

arachne engine beta

### Platform

Windows 10

### Printer

Creality Ender 3

### Reproduction steps

I imported my object for the curate and had it sliced.

### Actual results

Slicing starts, but when it would finish, it gets the message "slicing".

### Expected results

I wait for the end of the slicing to be able to save the file, but it doesn't finish.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

There is no log file.

![Error_Cura](https://user-images.githubusercontent.com/11969330/127864115-fd5ff180-7bcb-4e6e-80f9-012c668b43b0.jpg)

[CE3_Suporte_Controle_Portao.zip](https://github.com/Ultimaker/Cura/files/6916967/CE3_Suporte_Controle_Portao.zip)

**Comment by fvrmr** [comment] 2021-08-02 14:31
Hi @vtozato this is a duplicate of https://github.com/Ultimaker/Cura/discussions/9388#discussioncomment-474565 and we have a ticket on our backlog for this bug. 
The `top surface skin layers` and bridging settings are causing this. You could disable the `enable bridge settings` or set `top skin surface` to 0. 
I will close this issue as a duplicate.

**Closed by fvrmr** 2021-08-02 14:31 UTC
Labels: Type: Bug
