### ISSUE TITLE
[4.6.2] Scale XY mm and percent box is mixed

### ISSUE THREAD

**Issue by skjolddesign** [Ultimaker/Cura#8100] opened 2020-07-23 16:27 UTC
**Application version**
4.6.2 (same problem in 3.51)

**Platform**
Windows 10 x64

**Printer**
Ender 3

**Reproduction steps**
1. Rotate blue axis 90degr with the clock.
2. Unselect Snap Scaling and Uniform Scaling.
3. Reduce X mm by half.

**Screenshot(s)**
[https://prnt.sc/tndko3](https://prnt.sc/tndko3)

**Actual results**
Y percentage box is 50%.

**Expected results**
X percentage box should be 50%.

**Comment by konskarm** [comment] 2020-07-27 07:48
Hi @skjolddesign, I tried reproducing the issue in 4.6.1, 4.6.2, and latest master with no success. Halving the X mm corresponds to the X % being halved.

**Comment by Ghostkeeper** [comment] 2020-07-27 07:59
Did you rotate your object before trying this?

**Comment by skjolddesign** [comment] 2020-07-28 12:19
> 
> 
> Did you rotate your object before trying this?

Yes, I must haved done that. Only when model is rotated, is the scaling mixed.
I rotated the blue axis 90degr. with the clock.

**Comment by nallath** [comment] 2020-07-29 07:54
Duplicate of https://github.com/Ultimaker/Cura/issues/4136

**Closed by nallath** 2020-07-29 07:54 UTC
Labels: Type: Bug
