### ISSUE TITLE
copy+reflect

### ISSUE THREAD

**Issue by marqch** [Ultimaker/Cura#16213] opened 2023-07-18 23:13 UTC
### Cura Version

5.4.0

### Operating System

windows 10

### Printer

anet et4

### Reproduction steps

1. open any model in cura
2. copy it
3. use mirror tool and reflect a copy
4. slice

### Actual results

the original model (not a copy) becomes solid (slices with 100% infill)

### Expected results

expected 2 objects with the same settings

### Add your .zip and screenshots here ⬇️

![bug](https://github.com/Ultimaker/Cura/assets/23721633/90a37d4f-db79-4d58-b69e-49b3d4866c36)

**Comment by GregValiant** [comment] 2023-07-19 00:18
Thanks for the report.
I can't reproduce this.  When I mirror a model it's the same as the original.
![image](https://github.com/Ultimaker/Cura/assets/64202104/f6cb3de3-db3d-45b8-97ce-3f9ba76f4078)

It is possible to force the problem by using the Per Model settings and changing the infill density of one of the models.
Here the left model has 90% density and the right is 20%.
![image](https://github.com/Ultimaker/Cura/assets/64202104/2c54f21e-52e1-4ff4-b7be-275cd9a480db)

If you attach a project file it would be helpful.

**Comment by marqch** [comment] 2023-07-19 06:53
Hello. I found what was the problem. It is the "make overhang printable" (experimental) option that gives this result.
[AET4PRO_BoredFrog.zip](https://github.com/Ultimaker/Cura/files/12091957/AET4PRO_BoredFrog.zip)

**Comment by GregValiant** [comment] 2023-07-19 10:28
That one and "Remove all Holes" have their uses, but they are just for specialty situations.

I'll go ahead and remove the bug label and close this then.

**Closed by GregValiant** 2023-07-19 10:28 UTC
Labels: Type: Discussion, Status: Under Investigation
