### ISSUE TITLE
Cura 4.9 crashes when opening files

### ISSUE THREAD

**Issue by MarvinWalther** [Ultimaker/Cura#9668] opened 2021-04-23 12:02 UTC
### Application Version

4.9.0

### Platform

Windows 10

### Printer

Ultimaker 2+

### Reproduction steps

1. Had 4.8.0 installed
2. Installed 4.9.0 (uninstalled old version but kept user setting)
3. Open Cura
4. Click on "open file" button
5. Type something (that exists / can be found) in the search bar
6. Hit enter

### Actual results

Cura crashes after showing search results for about 2 seconds.
But only if there are results to show. If I search for something, I know doesn't exists, it shows "no results" and everything is fine.

### Expected results

Show me search results and be able to open files.

### Additional information

In Windows file explorer, searching for files does work without problems. Tested with the same search in the same folder.
Also just open a file in Cura without searching for it does work.

### Log:
```
2021-04-23 13:56:38,399 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin FileLogger
2021-04-23 13:56:38,409 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin FirmwareUpdateChecker
2021-04-23 13:56:38,416 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin FirmwareUpdater
2021-04-23 13:56:38,421 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin GCodeGzReader
2021-04-23 13:56:38,426 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin GCodeGzWriter
2021-04-23 13:56:38,432 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin GCodeProfileReader
2021-04-23 13:56:38,445 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin GCodeReader
2021-04-23 13:56:38,452 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin GCodeWriter
2021-04-23 13:56:38,461 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin ImageReader
2021-04-23 13:56:38,466 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin LegacyProfileReader
2021-04-23 13:56:38,473 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin LocalContainerProvider
2021-04-23 13:56:38,480 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin LocalFileOutputDevice
2021-04-23 13:56:38,486 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin MachineSettingsAction
2021-04-23 13:56:38,491 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin ModelChecker
2021-04-23 13:56:38,498 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin MonitorStage
2021-04-23 13:56:38,505 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin PerObjectSettingsTool
2021-04-23 13:56:38,513 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin PostProcessingPlugin
2021-04-23 13:56:38,518 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin PrepareStage
2021-04-23 13:56:38,523 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin PreviewStage
2021-04-23 13:56:38,531 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin RemovableDriveOutputDevice
2021-04-23 13:56:38,536 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin SentryLogger
2021-04-23 13:56:38,552 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin SimulationView
2021-04-23 13:56:38,559 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin SliceInfoPlugin
2021-04-23 13:56:38,567 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin SolidView
2021-04-23 13:56:38,575 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin SupportEraser
2021-04-23 13:56:38,601 - WARNING - [MainThread] UM.Logger.logException [112]: Exception: Failed to load packages for Marketplace
2021-04-23 13:56:38,603 - WARNING - [MainThread] UM.Logger.logException [116]: NoneType: None
2021-04-23 13:56:38,604 - WARNING - [MainThread] UM.Logger.logException [112]: Exception: Failed to load packages for Marketplace
2021-04-23 13:56:38,606 - WARNING - [MainThread] UM.Logger.logException [116]: NoneType: None
2021-04-23 13:56:38,607 - WARNING - [MainThread] UM.Logger.logException [112]: Exception: Failed to load packages for Marketplace
2021-04-23 13:56:38,609 - WARNING - [MainThread] UM.Logger.logException [116]: NoneType: None
2021-04-23 13:56:38,610 - WARNING - [MainThread] UM.Logger.logException [112]: Exception: Failed to load packages for Marketplace
2021-04-23 13:56:38,612 - WARNING - [MainThread] UM.Logger.logException [116]: NoneType: None
2021-04-23 13:56:38,616 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin Toolbox
2021-04-23 13:56:38,623 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin CameraTool
2021-04-23 13:56:38,630 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin MirrorTool
2021-04-23 13:56:38,641 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin RotateTool
2021-04-23 13:56:38,652 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin ScaleTool
2021-04-23 13:56:38,658 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin SelectionTool
2021-04-23 13:56:38,667 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin TranslateTool
2021-04-23 13:56:38,673 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin TrimeshReader
2021-04-23 13:56:38,686 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin UFPReader
2021-04-23 13:56:38,693 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin UFPWriter
2021-04-23 13:56:38,701 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin UltimakerMachineActions
2021-04-23 13:56:38,782 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin UM3NetworkPrinting
2021-04-23 13:56:38,791 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin UpdateChecker
2021-04-23 13:56:38,791 - INFO - [JobQueWorker [0]] UpdateChecker.UpdateCheckerJob.run [40]: Checking for new version of cura
2021-04-23 13:56:38,817 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin USBPrinting
2021-04-23 13:56:38,828 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade21to22
2021-04-23 13:56:38,834 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade22to24
2021-04-23 13:56:38,840 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade25to26
2021-04-23 13:56:38,846 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade26to27
2021-04-23 13:56:38,852 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade27to30
2021-04-23 13:56:38,857 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade30to31
2021-04-23 13:56:38,863 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade32to33
2021-04-23 13:56:38,868 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade33to34
2021-04-23 13:56:38,873 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade34to35
2021-04-23 13:56:38,878 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade35to40
2021-04-23 13:56:38,883 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade40to41
2021-04-23 13:56:38,890 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade41to42
2021-04-23 13:56:38,895 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade42to43
2021-04-23 13:56:38,901 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade43to44
2021-04-23 13:56:38,907 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade44to45
2021-04-23 13:56:38,912 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade45to46
2021-04-23 13:56:38,918 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade460to462
2021-04-23 13:56:38,924 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade462to47
2021-04-23 13:56:38,929 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade47to48
2021-04-23 13:56:38,934 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade48to49
2021-04-23 13:56:38,940 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin SimpleView
2021-04-23 13:56:38,951 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin X3DReader
2021-04-23 13:56:38,965 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin XmlMaterialProfile
2021-04-23 13:56:38,970 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin XRayView
2021-04-23 13:56:38,975 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin CustomSupports
2021-04-23 13:56:38,977 - DEBUG - [MainThread] UM.PluginRegistry.loadPlugins [395]: Loading all plugins took 1.2587502002716064 seconds
2021-04-23 13:56:38,986 - INFO - [MainThread] UM.VersionUpgradeManager.upgrade [163]: Looking for old configuration files to upgrade.
2021-04-23 13:56:39,022 - INFO - [MainThread] UM.VersionUpgradeManager.upgrade [175]: Checking and performing updates took 0.036032676696777344
2021-04-23 13:56:39,035 - INFO - [MainThread] UM.Logger.info [128]: Completed loading preferences.
2021-04-23 13:56:39,046 - INFO - [MainThread] UM.Logger.info [128]: Created system tray icon.
2021-04-23 13:56:40,109 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.loadAllMetadata [361]: Loading metadata into container registry took 1.0567359924316406 seconds
2021-04-23 13:56:40,119 - DEBUG - [MainThread] cura.Scene.CuraSceneController.setActiveBuildPlate [142]: Select build plate: 0
2021-04-23 13:56:40,121 - INFO - [MainThread] cura.CuraApplication.run [794]: Initializing machine error checker
2021-04-23 13:56:40,205 - INFO - [MainThread] cura.UI.MachineActionManager.addDefaultMachineActions [74]: Default machine actions added for machine definition [ultimaker2_plus]
2021-04-23 13:56:40,295 - INFO - [MainThread] cura.Settings.GlobalStack.addExtruder [194]: Extruder[ultimaker2_plus_extruder_0 #2] added to [Ultimaker 2+] at position [0]
2021-04-23 13:56:40,295 - INFO - [MainThread] FirmwareUpdateChecker.FirmwareUpdateChecker.checkFirmwareVersion [79]: No machine with name Ultimaker 2+ in list of firmware to check.
2021-04-23 13:56:40,677 - DEBUG - [MainThread] cura.Machines.ContainerTree.__getitem__ [120]: Adding container tree for ultimaker2_plus took 0.37578749656677246 seconds.
2021-04-23 13:56:40,684 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: ChangeAtZ
2021-04-23 13:56:40,686 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: ColorMix
2021-04-23 13:56:40,687 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: CreateThumbnail
2021-04-23 13:56:40,688 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: DisplayFilenameAndLayerOnLCD
2021-04-23 13:56:40,689 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: DisplayProgressOnLCD
2021-04-23 13:56:40,690 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: FilamentChange
2021-04-23 13:56:40,691 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: InsertAtLayerChange
2021-04-23 13:56:40,694 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: PauseAtHeight
2021-04-23 13:56:40,695 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: RetractContinue
2021-04-23 13:56:40,696 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: SearchAndReplace
2021-04-23 13:56:40,699 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: Stretch
2021-04-23 13:56:40,700 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: TimeLapse
2021-04-23 13:56:40,701 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [204]: Begin loading of script: UsePreviousProbeMeasurements
2021-04-23 13:56:40,702 - WARNING - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadAllScripts [155]: Unable to create a folder for scripts: C:\Program Files\Ultimaker Cura 4.9.0\resources\scripts
2021-04-23 13:56:40,752 - INFO - [MainThread] cura.CuraApplication.run [799]: Initializing machine manager
2021-04-23 13:56:40,754 - INFO - [MainThread] cura.CuraApplication.run [804]: Initializing container manager
2021-04-23 13:56:40,988 - DEBUG - [JobQueWorker [1]] UM.Mesh.MeshData.calculateNormalsFromVertices [556]: Calculating normals took 0.0010013580322265625 seconds
2021-04-23 13:56:41,000 - DEBUG - [MainThread] cura.OAuth2.AuthorizationHelpers.parseJWT [114]: Checking the access token for [https://account.ultimaker.com/check-token]
2021-04-23 13:56:41,154 - WARNING - [MainThread] UM.Logger.warning [134]: Starting a new sync while previous sync was not completed
{'CloudOutputDeviceManager': 0}
2021-04-23 13:56:41,176 - DEBUG - [MainThread] cura.Machines.MachineErrorChecker._rescheduleCheck [155]: New error check scheduled.
2021-04-23 13:56:41,179 - WARNING - [MainThread] UM.OutputDevice.OutputDeviceManager.removeOutputDevice [235]: Could not find output device with id digital_factory to remove
2021-04-23 13:56:41,195 - DEBUG - [MainThread] UM.Scene.Camera._preferencesChanged [255]: Changing perspective mode to perspective.
2021-04-23 13:56:41,275 - DEBUG - [MainThread] UM.Qt.Bindings.Theme.load [158]: Loading theme file: C:\Program Files\Ultimaker Cura 4.9.0\resources\themes\cura-light\theme.json
2021-04-23 13:56:41,402 - DEBUG - [MainThread] UM.Qt.Bindings.Theme.load [246]: Loaded theme C:\Program Files\Ultimaker Cura 4.9.0\resources\themes\cura-light
2021-04-23 13:56:41,404 - DEBUG - [MainThread] cura.TaskManagement.OnExitCallbackManager.addCallback [28]: on-app-exit callback [<bound method USBPrinterOutputDevice._checkActivePrintingUponAppExit of <USBPrinting.USBPrinterOutputDevice.USBPrinterOutputDevice object at 0x0000022402D15CA0>>] added.
2021-04-23 13:56:41,409 - DEBUG - [JobQueWorker [2]] USBPrinting.AutoDetectBaudJob.run [24]: Auto detect baud rate started.
2021-04-23 13:56:41,672 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin._createView [342]: Creating post processing plugin view.
2021-04-23 13:56:41,752 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin._createView [352]: Post processing view created.
2021-04-23 13:56:41,842 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [411]: file:///C:/Program Files/Ultimaker Cura 4.9.0/resources/qml/PrintSetupSelector/Custom/MenuButton.qml:42:18: QML Label: Cannot anchor to an item that isn't a parent or sibling.
2021-04-23 13:56:41,968 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [411]: file:///C:/Program Files/Ultimaker Cura 4.9.0/resources/qml/Account/UserOperations.qml:17:5: QML QQuickItem: Binding loop detected for property "height"
2021-04-23 13:56:41,969 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [411]: file:///C:/Program Files/Ultimaker Cura 4.9.0/resources/qml/Account/UserOperations.qml:17:5: QML QQuickItem: Binding loop detected for property "height"
2021-04-23 13:56:41,987 - DEBUG - [MainThread] cura.Machines.Models.NozzleModel._update [28]: Updating NozzleModel.
2021-04-23 13:56:42,033 - DEBUG - [MainThread] UM.Controller.setActiveStage [180]: Setting active stage to PrepareStage
2021-04-23 13:56:42,072 - DEBUG - [MainThread] cura.Machines.Models.NozzleModel._update [28]: Updating NozzleModel.
2021-04-23 13:56:42,140 - DEBUG - [MainThread] UM.Controller.setActiveView [108]: Setting active view to SolidView
2021-04-23 13:56:42,147 - DEBUG - [MainThread] ModelChecker.ModelChecker._createView [117]: Creating model checker view.
2021-04-23 13:56:42,153 - DEBUG - [MainThread] ModelChecker.ModelChecker._createView [126]: Model checker view created.
2021-04-23 13:56:42,153 - DEBUG - [MainThread] SliceInfoPlugin.SliceInfo._createDialog [76]: Creating dialog [MoreInfoWindow.qml]
2021-04-23 13:56:42,187 - DEBUG - [MainThread] Toolbox.src.Toolbox._makeRequestByType [542]: Requesting [updates] metadata from server.
2021-04-23 13:56:42,197 - DEBUG - [MainThread] cura.CuraApplication.run [848]: Booting Cura took 4.958669424057007 seconds
2021-04-23 13:56:42,197 - DEBUG - [JobQueWorker [3]] cura.Machines.ContainerTree.run [174]: Started background loading of MachineNodes
2021-04-23 13:56:42,218 - DEBUG - [MainThread] cura.Machines.Models.CustomQualityProfilesDropDownMenuModel._update [33]: Updating CustomQualityProfilesDropDownMenuModel.
2021-04-23 13:56:42,225 - DEBUG - [MainThread] cura.Machines.Models.QualityProfilesDropDownMenuModel._update [62]: Updating QualityProfilesDropDownMenuModel.
2021-04-23 13:56:42,379 - DEBUG - [MainThread] cura.Machines.Models.QualityProfilesDropDownMenuModel._update [62]: Updating QualityProfilesDropDownMenuModel.
2021-04-23 13:56:42,383 - DEBUG - [MainThread] cura.Machines.Models.CustomQualityProfilesDropDownMenuModel._update [33]: Updating CustomQualityProfilesDropDownMenuModel.
2021-04-23 13:56:42,704 - DEBUG - [JobQueWorker [3]] cura.Machines.ContainerTree.run [185]: All MachineNode loading completed
2021-04-23 13:56:42,938 - DEBUG - [MainThread] UM.Qt.QtRenderer._initialize [210]: Support for Vertex Array Objects: True
2021-04-23 13:56:42,946 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [112]: Initialized OpenGL subsystems.
2021-04-23 13:56:42,948 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [113]: OpenGL Version:  4.1.0 NVIDIA 465.89
2021-04-23 13:56:42,949 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [114]: OpenGL Vendor:   NVIDIA Corporation
2021-04-23 13:56:42,951 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [115]: OpenGL Renderer: NVIDIA GeForce GTX 1080/PCIe/SSE2
2021-04-23 13:56:42,953 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [116]: GLSL Version:    4.0.0
2021-04-23 13:56:42,954 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [C:\Program Files\Ultimaker Cura 4.9.0\resources\shaders\default.shader]...
2021-04-23 13:56:42,957 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [C:\Program Files\Ultimaker Cura 4.9.0\resources\shaders\selection.shader]...
2021-04-23 13:56:42,960 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [C:\Program Files\Ultimaker Cura 4.9.0\resources\shaders\select_face.shader]...
2021-04-23 13:56:42,962 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [C:\Program Files\Ultimaker Cura 4.9.0\resources\shaders\default.shader]...
2021-04-23 13:56:42,965 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [C:\Program Files\Ultimaker Cura 4.9.0\resources\shaders\composite.shader]...
2021-04-23 13:56:42,968 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [C:\Program Files\Ultimaker Cura 4.9.0\resources\shaders\overhang.shader]...
2021-04-23 13:56:42,971 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [C:\Program Files\Ultimaker Cura 4.9.0\resources\shaders\striped.shader]...
2021-04-23 13:56:42,974 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [C:\Program Files\Ultimaker Cura 4.9.0\resources\shaders\transparent_object.shader]...
2021-04-23 13:56:42,977 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [C:\Program Files\Ultimaker Cura 4.9.0\resources\shaders\striped.shader]...
2021-04-23 13:56:42,980 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [C:\Program Files\Ultimaker Cura 4.9.0\resources\shaders\xray.shader]...
2021-04-23 13:56:42,982 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [C:\Program Files\Ultimaker Cura 4.9.0\resources\shaders\xray_composite.shader]...
2021-04-23 13:56:42,985 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [C:\Program Files\Ultimaker Cura 4.9.0\resources\shaders\default.shader]...
2021-04-23 13:56:42,988 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [C:\Program Files\Ultimaker Cura 4.9.0\resources\shaders\grid.shader]...
2021-04-23 13:56:42,991 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [C:\Program Files\Ultimaker Cura 4.9.0\resources\shaders\platform.shader]...
2021-04-23 13:56:43,008 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [58]: Loading shader file [C:\Program Files\Ultimaker Cura 4.9.0\resources\shaders\xray.shader]...
2021-04-23 13:56:43,083 - DEBUG - [JobQueWorker [2]] USBPrinting.AutoDetectBaudJob.run [49]: Checking COM6 if baud rate 115200 works. Retry nr: 0. Wait timeout: 3
2021-04-23 13:56:45,133 - INFO - [MainThread] cura.Machines.MachineErrorChecker._setResult [214]: Error check finished, result = False, time = 4.0s
2021-04-23 13:56:47,608 - DEBUG - [JobQueWorker [2]] USBPrinting.AutoDetectBaudJob.run [49]: Checking COM6 if baud rate 250000 works. Retry nr: 0. Wait timeout: 3
2021-04-23 13:56:52,127 - DEBUG - [JobQueWorker [2]] USBPrinting.AutoDetectBaudJob.run [49]: Checking COM6 if baud rate 500000 works. Retry nr: 0. Wait timeout: 3
2021-04-23 13:56:53,739 - DEBUG - [MainThread] cura.AutoSave._onTimeout [59]: Autosaving preferences, instances and profiles
```

**Comment by fvrmr** [comment] 2021-04-26 12:16
Hi @MarvinWalther thank you for your bug report. 
I can't reproduce this issue. But it seems like this might be related to some other issues.
I will discuss this with the team keep you posted.

**Comment by evtrados** [comment] 2021-04-29 07:08
I can only reproduce this issue if:

- I have Chitubox installed. Doesn't matter if it's currently running or not or whether you enable the thumbnail preview during the installation
- **AND** I use the Preview Pane on Windows Explorer. If I disable the latter then Cura no longer crashes. It will crash again though if you try and select a different View option (e.g., large icons, etc). 

The only reason I can think of that this happens on Cura 4.9 and not on 4.8 is because we now use Qt 5.15.2 and Chitubox 1.8.1 uses Qt 5.15.1. I've had similar issues on macOS where two different applications that were using the same Qt version were crashing because the OS would find the same library in different locations in the system.

**Comment by nallath** [comment] 2021-04-29 08:33
So it's actually chitubox "poisoning" the operating system by inserting their version of QT into the preview dialog.

**Comment by CBDesignS** [comment] 2021-05-03 16:06
This has bugged me for a few days since updating, I had to move files into the last opened folder because of this untill it pi$$ed me off enough to dig into it and evtrados is correct. Chitucrap is screwing things over. I never used chitubox64 1.6.4.3.beta for a long time but removing the dll sorted the crash instantly.  regsvr32 /u "C:\Program Files\ChiTuBox64 1.6.4.3 Beta\CHITUBOX_Thumbnail.dll". Thnks for the heads up

**Comment by inlsadler** [comment] 2021-05-15 20:58
This is helpful also have Chitubox installed which I like for my resin printer.  If I disable the DLL will Chitubox still work?

**Comment by CBDesignS** [comment] 2021-05-15 21:06
@inlsadler it should work ok. I have never used my resin printer for over a year and I am dreading looking inside as I left resin in the tray. I could have a fubar machine but on the original question. Shitubox still opend and slices so I see no reason why it would not work.. I think this dll problem has been round for years now so disable it and get back to printing again.

**Comment by inlsadler** [comment] 2021-05-15 22:29
All sorted and both working now.  Thanks for the help.

**Comment by chepo92** [comment] 2021-05-16 07:12
Same here, with 4.9 and 4.9.1, but I don't have shitubox installed

**Comment by Ghostkeeper** [comment] 2021-05-17 10:05
Perhaps you could share a log file then, @chepo92?

**Comment by chepo92** [comment] 2021-05-17 16:27
Attached log file, I just opened Cura and drag n' drop a file from desktop

[cura.log](https://github.com/Ultimaker/Cura/files/6495352/cura.log)

**Comment by fieldOfView** [comment] 2021-05-17 19:22
@chepo92, please update the Printjob Naming plugin in the Marketplace.

**Comment by chepo92** [comment] 2021-05-17 20:13
> 
> 
> @chepo92, please update the Printjob Naming plugin in the Marketplace.

That worked for me! thks

**Comment by fieldOfView** [comment] 2021-05-17 20:26
For future reference: try to keep your plugins up to date for issues such as this. The update to this plugin was released more than a month before Cura 4.9, to prevent this exact issue.

**Comment by nallath** [comment] 2021-05-27 08:12
I'm going to close this issue as it's chitubox doing this (or a user needing to update plugins).

**Closed by nallath** 2021-05-27 08:12 UTC
Labels: Type: Bug

**Comment by robhp81** [comment] 2021-07-02 14:04
The instructions you provided do not work!!!

**Comment by Ghostkeeper** [comment] 2021-07-07 12:38
In one of the duplicates, @3Duke3 asked if it's possible for Cura to create its own thumbnailer:

> Excuse my lack of deeper software understanding, but seeing as Cura is such a major STL application, would there be an option to develop your own STL thumbnail tool that took priority over shitubox?

We could probably develop a thumbnailer (if given time), but I don't think it's possible to ensure that it takes priority over Chitubox' extension. You can't just tell Windows that your program is more important than another one. I'd expect that it just depends on whichever extension you installed last. And if it is possible, having both extensions installed would still cause it to crash anyway, since Chitubox' Qt 5.15.1 DLL is still loaded by the operating system when the file dialogue is opened.

You can try it for yourself by installing an alternative thumbnailer. I've been using this one myself: https://github.com/unlimitedbacon/stl-thumb

**Comment by Ghostkeeper** [comment] 2021-11-19 11:00
We are working on the upgrade to Qt 6.2. It's currently in a bit of a preparation state still, not so far yet. The aim is to complete the upgrade for Cura 5.0 but when 5.0 will be released is uncertain.

This upgrade is expected to hide the issue. It's currently crashing because of a collision between two 5.15 versions of Qt, which link to the same libraries. Once Cura updates to 6.2, they should no longer collide. At least not until Chitubox also updates to 6.2.
