### ISSUE TITLE
Preview visualisation broken

### ISSUE THREAD

**Issue by ysoldak** [Ultimaker/Cura#12158] opened 2022-05-10 13:27 UTC
### Application Version

5.0.0-beta+1

### Platform

macOS 12.3.1

### Printer

Prusa MK3s

### Reproduction steps

Tried to slice a little object.

### Actual results

Preview looks weird (see attached screenshot), prints OK though.
Same result for both 3mf and STL files.

### Expected results

Preview shows actual expected print moves w/o weird artifacts.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

<img width="667" alt="Screenshot 2022-05-10 at 15 19 55" src="https://user-images.githubusercontent.com/1061565/167638764-7576ef5e-f01b-4d14-be78-fa716963c1b8.png">
[Body4.zip](https://github.com/Ultimaker/Cura/files/8661906/Body4.zip)

**Comment by fvrmr** [comment] 2022-05-19 12:20
Hi @ysoldak thank you for your report.
I checked this with a colleague with macOS 12.3.1 but we couldn't reproduce this. See also: https://github.com/Ultimaker/Cura/issues/10387

I will close this issue, since it is a duplicate.

**Closed by fvrmr** 2022-05-19 12:20 UTC
Labels: Type: Bug
