### ISSUE TITLE
When I try to "Save to Removable Disk" the file name is always ".gcode"

### ISSUE THREAD

**Issue by tylerecouture** [Ultimaker/Cura#1835] opened 2017-05-16 16:32 UTC
Running Cura 2.5.0 on Ubuntu, install from the PPA.  Tried removing/purging/reinstalling but no luck.

When I try to Save the slice to an SD card, it always ends up as  ".gcode" and I don't see how to set it?

**Comment by fieldOfView** [comment] 2017-05-16 16:53
This is a known issue, that has been fixed for Cura 2.6.
As a workaround, press the small pencil icon in the lower right of the viewport and type in a name before saving.

Duplicate of #1703, #1749, #1760 and #1776.

**Closed** 2017-05-17 07:21 UTC
