### ISSUE TITLE
missing file menu in GUI

### ISSUE THREAD

**Issue by Unouzhukrnet** [Ultimaker/Cura#3823] opened 2018-05-17 12:48 UTC
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by fieldOfView** [comment] 2018-05-17 12:52
Probably a duplicate of https://github.com/ultimaker/cura/issues/2068 (in short: you have to update your intel GPU driver), but I can't be sure because you ignored the issue template and the issue title is not a good place to explain what you mean.

**Comment by Unouzhukrnet** [comment] 2018-05-17 12:56
On one machine missing file menu in GUI. Because of that there is a difference between button's picture area and button's active area(to click at button i have to move cursor for some pixels lower the button)
![printscr](https://user-images.githubusercontent.com/39374757/40178631-99067bca-59d1-11e8-9e70-d5470119098a.png)
I tried to reinstall and also to clear appdata folder but result is the same.

**Closed** 2018-05-17 13:03 UTC
