### ISSUE TITLE
Can't multiply object in Mac OS 12.0.1

### ISSUE THREAD

**Issue by izzycura** [Ultimaker/Cura#10725] opened 2021-11-02 16:42 UTC
### Application Version

4.10, 4.11, 4.12 beta

### Platform

MAC OS Monterey 12.0.1

### Printer

JGAurora

### Reproduction steps

1. Right Click on object
2. Multiply Selected
3. Notification window with time bar comes out.

### Actual results

Nothing happens window bar stays open and it just hangs.

Repeat and another window bar opens and continues to hang

### Expected results

It should multiply my object. I also tried different objects.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

<img width="974" alt="Screen Shot 2021-11-02 at 09 38 03" src="https://user-images.githubusercontent.com/93607397/139908133-c6461c41-66e7-433d-8655-d52a8312aab3.png">

**Comment by nallath** [comment] 2021-11-03 10:04
Duplicate of #10249

**Comment by nallath** [comment] 2021-11-03 10:05
For the next time; Please fill in the entire template (eg; include log files). We need that information to help diagnose the issue and provide a fix.

**Closed by nallath** 2021-11-03 10:04 UTC
Labels: Type: Bug

**Comment by tommyhlc** [comment] 2021-11-04 03:00
I have the same issue, thought the BETA ver. can help, but still not working...
