### ISSUE TITLE
Drop-down menus missing in 4.4.1 and 4.5

### ISSUE THREAD

**Issue by juren53** [Ultimaker/Cura#7336] opened 2020-03-23 21:27 UTC
**Application version**
Cura 4.4.1 and 4.5

**Platform**
Linux Ubuntu 18.10

**Printer**
Anycubic S

**Reproduction steps**
1. Pulled up an STL file in both versions and the model displayed in 3D but the drop-down menus were missing
2. Same when I ran Cura without an STL file

**Screenshot(s)**
Sorry, I didn't get a screen shot

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)

**Work Around/Fix**

On the Cura forum, curatester posted the following fix that worked for me:

Posted October 23, 2019 · cura not showing menu items
I had this too, I use Ubuntu 18.04 LTS. I deleted the QT shader cache by emtying the folder ~/.cache/qtshadercache and it showed all menus again.
Seems like QT having hiccups from time to time... :-)
Have fun!
Mike

**Comment by rburema** [comment] 2020-03-24 16:47
If it's really the shader cache, then there's a more permanent workaround implemented in 4.5

If you edit `cura.cfg`, put `force_empty_shader_cache = True` under the `[view]` header (if there isn't a `[view]` header, you can create one).

**Comment by Ghostkeeper** [comment] 2020-03-25 10:07
Duplicate of https://github.com/Ultimaker/Cura/issues/5296.

**Closed by Ghostkeeper** 2020-03-25 10:07 UTC
Labels: Type: Bug
