### ISSUE TITLE
[REQUEST] Allow combing over thin sections.

### ISSUE THREAD

**Issue by Douggie-J** [Ultimaker/Cura#3615] opened 2018-04-03 03:51 UTC
A lot of my prints are mechanical parts that have (or are almost entirely made of) thin walls that need to be fairly clean and free of blobbing. Combing would solve the issue, but combing does not work if the layer doesn't have at least 1.5-ish inner walls to travel over. An option to allow combing over outer walls would be extremely useful for parts like this, as the only other "good" option is to use a very fine nozzle; an issue in itself.

**Comment by Douggie-J** [comment] 2018-04-03 04:15
UPDATE: Actually, after some more fiddling, apparently this is already supported, but the behavior is a bit...strange.

Image one shows what I was initially working with. Mess of travels outside the part to fill in the odd cavities formed by the threads of the cap. Image two shows the exact same cap with the wall thickness set to the width of the nozzle, such that there will be no inner wall at all. It now slices exactly as expected.

Solves my problem, at least for this particular component...
![wot1](https://user-images.githubusercontent.com/36877457/38228932-e2c299ea-36ba-11e8-94c1-b07cd5d1eb57.png)
![wot2](https://user-images.githubusercontent.com/36877457/38228935-e6dd0ce0-36ba-11e8-803d-058722d3294c.png)

**Comment by Ghostkeeper** [comment] 2018-04-26 11:44
Yeah we've also seen this bug and we're investigating it now.

**Comment by Ghostkeeper** [comment] 2018-04-26 11:46
In fact, this is a duplicate of https://github.com/Ultimaker/Cura/issues/3458.

**Closed** 2018-04-26 11:46 UTC
Labels: Category: CuraEngine, Status: Duplicate, Type: Bug
