### ISSUE TITLE
[4.3] Words after dot removed when saving directly on the removable drive

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#6557] opened 2019-10-19 20:12 UTC
**Application version**
4.3

**Platform**
Win10 x64

**Printer**
Cr10S

**Reproduction steps**
Name a file something like "test v1.1" and save directly on a removable drive

**Actual results**
The file, even shown with the name "test v1.1" in the files dropdown, is shown as exported in the popup, and then saved, as "test v1"

**Expected results**
Save the file and show the name on the popup as ""test v1.1"

**Additional information**
It doesn't happen when saving a file on a specified directory
![after dot](https://user-images.githubusercontent.com/20385116/67150867-883dc100-f2bd-11e9-84d4-07b11dd79ace.png)

**Comment by Ghostkeeper** [comment] 2019-10-21 12:53
Duplicate of https://github.com/Ultimaker/Cura/issues/5626.

**Closed by Ghostkeeper** 2019-10-21 12:53 UTC
Labels: Type: Bug
