### ISSUE TITLE
Filling in holes on its  own. 

### ISSUE THREAD

**Issue by jamesjfc123** [Ultimaker/Cura#1667] opened 2017-04-09 16:15 UTC
I designed a 3d model in sketchup. When I brought it in it looked like it should. When I went to check the layers it filled in all the holes I had in the object. This is an issue and I can not figure out how to fix it.

**Comment by fieldOfView** [comment] 2017-04-09 16:32
duplicate of #1666

**Closed** 2017-04-10 07:31 UTC
