### ISSUE TITLE
Part of the layer was skipped on the raft

### ISSUE THREAD

**Issue by homerender** [Ultimaker/Cura#14879] opened 2023-03-13 23:55 UTC
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Anycubic i3 Mega Pro

### Reproduction steps

Open STL file
Click Slice
Preview 3rd layer

### Actual results

big part of 3rd layer is missed

### Expected results

You will see a problem... A missed layer part. The same happens on the printed models and it's not useful.
![Screenshot_2](https://user-images.githubusercontent.com/28815435/224857323-aca53b7f-d56e-49e2-a901-d0c1870df087.png)
[Card_Game_Keeper.zip](https://github.com/Ultimaker/Cura/files/10962863/Card_Game_Keeper.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

--
![Screenshot_1](https://user-images.githubusercontent.com/28815435/224857823-7d9e77d7-8b8e-4609-8f37-69f92256c876.png)

**Comment by MariMakes** [comment] 2023-03-14 13:53
Hey @homerender,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12276
We have a ticket on our backlog with the intent to improve this behavior.
There is a workaround with moving the printjob away from the center of the buildplate. 
This location seemed to work for your printjob
![image](https://user-images.githubusercontent.com/40423138/225023051-9396d639-3051-4796-884a-108928a69785.png)


Apologies for the inconvenience. 
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12276

**Closed by MariMakes** 2023-03-14 13:53 UTC
Labels: Type: Bug, Status: Triage

**Comment by homerender** [comment] 2023-03-14 13:55
Ohk, good to know, thank you!

вт, 14 мар. 2023 г. в 17:53, MariMakes ***@***.***>:
