### ISSUE TITLE
"Brim only on the outside" doesn't work

### ISSUE THREAD

**Issue by kdomkus** [Ultimaker/Cura#6655] opened 2019-11-13 19:54 UTC
I was helping a friend debug a problem he ran into - he had two numbers that he was trying to include on his print. A 5 and a 4. The 5 was OK but the 4 was filled in. Turned out it was the brim setting that was adding brim material inside the 4 and ending up closing it. So we found the 'brim only on the outside' setting. But turning it on or off did not avoid putting brim inside the 4. 
![Capture 1](https://user-images.githubusercontent.com/20526147/68799003-4da11d00-060c-11ea-8581-13e1b46f41e3.jPG)
![Capture 2](https://user-images.githubusercontent.com/20526147/68799004-4da11d00-060c-11ea-81ad-858a3d9afba2.JPG)

**Comment by rburema** [comment] 2019-11-14 08:09
This is a known issue, and a limitation of the current implementation. It occurs because the middle part of the 4 is an 'island', and this the whole hole is seen as 'outside'.

We've got an internal ticket ( CURA-5960 ) to resolve this, but it may be a while untill we get to that.

I'm closing this ticket, since it's a duplicate of #4222 (and a whole slew of others) please continue any discussion there.

**Closed by rburema** 2019-11-14 08:09 UTC
Labels: Category: Engine, Status: Duplicate
