### ISSUE TITLE
Ultimaker Cura Crash when I hit Scale

### ISSUE THREAD

**Issue by mcristian15** [Ultimaker/Cura#9944] opened 2021-06-06 03:14 UTC
### Application Version

4.9.1

### Platform

Kubuntu 20.04

### Printer

Hellbot Magna 2 dual 230

### Reproduction steps

1. Open Ultimaker Cura.
2. Open a Model
3. Hit Scale Button

### Actual results

Application closes unexpected.

### Expected results

It should resize the object.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/6603573/cura.log)
[stderr.log](https://github.com/Ultimaker/Cura/files/6603574/stderr.log)

**Comment by smartavionics** [comment] 2021-06-06 06:03
See #9709

**Comment by fvrmr** [comment] 2021-06-07 07:08
Closing because it is a duplicate of #9709

**Closed by fvrmr** 2021-06-07 07:08 UTC
Labels: Type: Bug
