### ISSUE TITLE
Extruder change over model

### ISSUE THREAD

**Issue by lokanaft** [Ultimaker/Cura#4901] opened 2018-11-28 17:28 UTC
**Application Version**
3.6

**Platform**
**Printer**
Any

**Steps to Reproduce**
Use 2 extruder and prime tower

**Actual Results**
Extruder change over model, wait temperature and only then go to prime tower

**Expected results**
Extruder should go to prime tower and change and heat over prime tower, otherwise it flow filament over model in this time

**Comment by rburema** [comment] 2018-11-29 14:10
Hi @lokanaft,
Does this happen for any model? If not, could you Save it to a 3mf file and attach it to this ticket?
cheers, Remco.

**Comment by lokanaft** [comment] 2018-11-29 14:40
For any model.
In #4855 it's realy Cura not understand, where to go for change extruder, but with prime tower it's obviously

**Comment by amagr0** [comment] 2018-12-06 16:54
https://github.com/Ultimaker/Cura/issues/3451

**Comment by Ghostkeeper** [comment] 2018-12-27 11:07
> Printer
Any

This part of your description is wrong. It doesn't happen with any printer. UM3 is fine in this regard.

To move to a location where it's safe to change extruders, Cura needs to know where to move to. This is in your printer's definition. It would need to mention something like this:

    "machine_extruder_start_pos_abs": {"default_value": true},
    "machine_extruder_start_pos_x": {"default_value": 0},
    "machine_extruder_start_pos_y": {"default_value": 0},
    "machine_extruder_end_pos_x": {"default_value": 0},
    "machine_extruder_end_pos_y": {"default_value": 0},

I'm closing this as a duplicate of #3451 then.

**Closed by Ghostkeeper** 2018-12-27 11:07 UTC
Labels: Status: Needs Info
