### ISSUE TITLE
Brim inside when Brim Outside only

### ISSUE THREAD

**Issue by Abelma1500** [Ultimaker/Cura#4954] opened 2018-12-07 20:48 UTC
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by Abelma1500** [comment] 2018-12-07 20:49
Brim inside model when Only Brim Outside activated

**Comment by smartavionics** [comment] 2018-12-07 21:07
This maybe a duplicate of https://github.com/Ultimaker/Cura/issues/4222 but as you don't provide any useful information it's hard to know for sure.

**Comment by Ghostkeeper** [comment] 2019-02-19 08:29
Yeah I'm closing this as a duplicate of #4222.

**Closed by Ghostkeeper** 2019-02-19 08:29 UTC
Labels: Status: Needs Info
