### ISSUE TITLE
[Ironing] Option to choose or filter layers to be ironed. (not only top layer)

### ISSUE THREAD

**Issue by Tinkot** [Ultimaker/Cura#9297] opened 2021-02-19 18:27 UTC
When printing more complex models (benchy for example) it starts to iron every possible area. Even the tiniest spots at the slope of benchy. There already exists an option to select only top layer, but to select a specific layer (or filter it out using some kind of option) would be a huge improvement.

**Comment by fvrmr** [comment] 2021-02-22 11:01
Hi @Tinkot thank you again for your feature request. 
Also for this feature request I need more information. So if you could fill in the form that would help us a lot. 
Thank you in advance!

**Comment by Ghostkeeper** [comment] 2021-03-03 11:51
It's pretty clear I guess. This is a duplicate of https://github.com/Ultimaker/Cura/issues/7975.

**Closed by Ghostkeeper** 2021-03-03 11:51 UTC
Labels: Status: Needs Info, Type: New Feature
