### ISSUE TITLE
Cura, 3.04 and 3.1.0, wrong extruder temperature for PETG

### ISSUE THREAD

**Issue by joselauro** [Ultimaker/Cura#3044] opened 2017-12-24 19:36 UTC
It is not 215ºC! The correct value is about 240ºC. I lost many printings until realised this.

**Comment by linuxglobal** [comment] 2017-12-24 21:36
mine will stay at 210C for output gcode no matter what material is used..

**Comment by joselauro** [comment] 2017-12-24 21:51
But do you print in PETG? 210, 215ºC is for PLA.

**Comment by linuxglobal** [comment] 2017-12-24 22:17
no matter what material is selected, cura will display the correct 255C i request, yet when the PRUSA mk2 loads the gcode it will still warm up nozzle to 210. If i alter the bed temperature within cura, the value will correspond in the gcode bed temp.

**Comment by ChrisTerBeke** [comment] 2017-12-29 15:03
Probably a duplicate of #1296. Fixed in next release.

**Closed by ChrisTerBeke** 2017-12-29 15:03 UTC
