### ISSUE TITLE
cura 4.9.1 crash at startup

### ISSUE THREAD

**Issue by Manikem** [Ultimaker/Cura#9956] opened 2021-06-09 14:30 UTC
### Application Version

4.9.1

### Platform

Windows 10

### Printer

None : first run

### Reproduction steps

Delete all previous cura instance
Delete all existing folders in program files and %appdata%
Install cura 4.9.1

### Actual results

After the launching popup indicating Launching UI a blank window appears for 2 seconds and disappears

### Expected results

App launch

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

log file
[cura.log](https://github.com/Ultimaker/Cura/files/6624542/cura.log)

**Comment by fvrmr** [comment] 2021-06-10 09:27
Hi @Manikem thank you for your bug report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9847 
Because it is a duplicate I will close this issue. For the next Cura release this will be fixed.

**Comment by Manikem** [comment] 2021-06-10 09:51
@fvrmr : I don't think this is caused by authentication there is no "cura.OAuth2.AuthorizationHelpers" in my cura.log

**Comment by fvrmr** [comment] 2021-06-11 13:24
You are right. But I can't see anything else that would cause this. 
I will bring this up for discussion with the team. Keep you posted!

**Comment by fvrmr** [comment] 2021-06-15 08:40
Hi @Manikem we can't reproduce your issue. Do you have maybe an external monitor?

**Comment by Manikem** [comment] 2021-06-15 08:52
Hello yes I have an external monitor but cura appears on my main screen at startup. 
How can I help you ?
Reinstall last version of cura, try to launch with my external monitor disconnected ?

**Comment by fvrmr** [comment] 2021-06-15 11:24
Yes, try to launch Cura without your external monitor.

**Comment by Ghostkeeper** [comment] 2021-06-15 12:07
If the crash happens due to the extra monitor, we might have a fix for that in Cura 4.10.

**Comment by Manikem** [comment] 2021-06-16 07:51
Hello due to multiple test 1 don't know exactly what was the lastest version I was able to run so I download all version from 4.6.1 to 4.9.1 ans with my external screen unplugged.
The best version which run is 4.7.1,  the greater one with "win64" in filename.
All version with amd64 in the filname doesn't work.

![image](https://user-images.githubusercontent.com/85630479/122179422-ccfd6f00-ce87-11eb-9efd-75d6047818f1.png)

**Comment by Ghostkeeper** [comment] 2021-06-17 09:28
Duplicate of https://github.com/Ultimaker/Cura/issues/7183 then.

**Closed by Ghostkeeper** 2021-06-17 09:28 UTC
Labels: Type: Bug

**Comment by Manikem** [comment] 2021-06-17 09:43
Reinstalled 4.9.1 to try to correct cura.cfg as specified in #7183, but always crashing at startup, the config file allready has the option set to false. joined my cfg file (not edited).
[cura.cfg.txt](https://github.com/Ultimaker/Cura/files/6669128/cura.cfg.txt)

**Comment by fvrmr** [comment] 2021-06-21 12:40
Hi @Manikem Cura 4.10 beta is released last Friday. Could you try to this version and see if Cura doesn't crash anymore on start up.
https://github.com/Ultimaker/Cura/releases/tag/4.10-beta
