### ISSUE TITLE
Combing mode all routes along outer wall when it doesn't need to

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#3890] opened 2018-06-05 11:08 UTC
**Application Version**

3.4.99

**Platform**

Linux

**Printer**

S5

**Steps to Reproduce**

Load project slice, print, be disappointed with resulting print quality, investigate issue...

**Actual Results**

What's happening is that Cura has routed travel along the outer wall of the part and the resulting dribble has caused a lot of visual problems.

**Expected results**

Cura should route on the inner walls/infill and not the outer wall when it can.

**Additional Information**

![screenshot_2018-06-05_12-01-47](https://user-images.githubusercontent.com/585618/40972465-b5623a7a-68b8-11e8-9f1d-1f8da20c4ce9.png)

![img_20180605_110148370](https://user-images.githubusercontent.com/585618/40972483-c1674176-68b8-11e8-81b3-938b8e0d4b4f.jpg)
[UMS5_combo_mount_ela.curaproject.3mf.renamed.zip](https://github.com/Ultimaker/Cura/files/2072097/UMS5_combo_mount_ela.curaproject.3mf.renamed.zip)

**Comment by smartavionics** [comment] 2018-06-05 20:20
The reason it's doing this is because on that layer the model narrows down in a couple of places (near the ends of the "arms") and there's only enough room for the outermost wall line and so the combing boundary has been set to the outermost wall for the whole layer when it only needs to be set to the outermost wall for the narrow region. For the rest of the model, the combing boundary could be an inner wall. Interestingly, for the combed travel moves that are used  while printing the skin regions, it does use an inner wall and not the outer.?

**Comment by smartavionics** [comment] 2018-06-05 20:31
@jackha, you have worked on the combing boundary code recently, any ideas?

**Comment by AbeFM** [comment] 2018-06-05 20:36
I had some issues where I was blaming extruder cooling... But I could get a LOT of that missing/defective outer wall. If you guys are short on examples I could try to work some up, but otherwise will just watch and learn.

**Comment by jackha** [comment] 2018-06-06 07:06
This is how it works and it may or may not have caused this:
- Try to comb using inner walls only. Success -> finished, else...
- Try to comb using all walls. If a single part is very thin, it combs everything using all walls, and not only the thin parts. Success -> finished, else..
- Travel outside, then in again.

**Comment by smartavionics** [comment] 2018-06-06 08:20
One thing you could do is to not use the centre line of the outer wall as the combing boundary but use the inner edge, that would move the nozzle slightly away from the edge of the part.

**Comment by jackha** [comment] 2018-06-06 09:23
I was worried about the computational time. Now it does 1 extra try before going to travel. But yes, that would be better. Still don't know if it's actually the cause though... Have you tried different combing modes?

**Comment by smartavionics** [comment] 2018-06-06 09:27
No, because my "no skins" combing is quite different to master (see https://github.com/Ultimaker/CuraEngine/pull/781 for details).

**Comment by smartavionics** [comment] 2018-06-06 09:28
What I mean is that it's not useful to compare no skins combing mode to all mode.

**Comment by smartavionics** [comment] 2018-06-06 10:40
Hi Jack, I think I have a possible solution, working on it, will let you know what happens!

**Comment by smartavionics** [comment] 2018-06-06 10:57
I have a working solution, will continue to test and clean up and if all well, will submit PR.

![screenshot_2018-06-06_11-57-17](https://user-images.githubusercontent.com/585618/41034206-d75b149e-6980-11e8-93d1-2cae650e0ada.png)

**Comment by diegopradogesto** [comment] 2018-06-13 11:15
Hey, @smartavionics, do you have a picture of the printed part after your fix? It will help to get an extent of the improvement.

**Comment by smartavionics** [comment] 2018-06-13 12:08
The above photo shows a part printed on the S5 and the slicer I am using for that doesn't have the fix. I will recreate the issue on a different printer and get before/after images.

**Comment by smartavionics** [comment] 2018-06-13 13:41
Hi @diegopradogesto, here you go. I have printed a section of the model that showed the problem. This is using another printer and another filament compared to above but the end result is the same.

Layer view without PR, travel goes along middle of outer wall:

![screenshot_2018-06-13_13-19-55](https://user-images.githubusercontent.com/585618/41354430-e4360c14-6f16-11e8-8c34-80c2ffc3b8d4.png)

Layer view with PR, travel goes along middle of second wall:

![screenshot_2018-06-13_13-54-18](https://user-images.githubusercontent.com/585618/41354429-e40eeef4-6f16-11e8-98d8-510d43f0a522.png)

With PR on left, without PR on right, you can see the dribble on the outer wall has made a lot of roughness not only on the layers immediately above/below the holes but also on the inside corners:

![img_20180613_143224454](https://user-images.githubusercontent.com/585618/41354458-f1deb14a-6f16-11e8-9010-130039760f4e.jpg)

**Comment by diegopradogesto** [comment] 2018-06-13 14:32
Oh, nice! I will add the PR to be reviewed and tested following the normal process and I will do some test prints.
Thanks!

**Comment by jackha** [comment] 2018-06-14 07:22
Very nice work @smartavionics !

**Comment by smartavionics** [comment] 2018-06-15 20:23
> Can I trivially transfer my printer (and slicing) settings from windows to Ubuntu to test PR's there?

The PR has not been incorporated in any release yet so the only way you can test it is to build CuraEngine from source.

If you have a sample project that has the problem, please share it if you can and I will see if the problem is still there with this PR in place.

**Comment by ctzsnooze** [comment] 2018-06-19 03:06
@smartavionics thanks for your work on improving combing - I just got 3.4 beta (OK slow) and your retraction with combing made a huge improvement on my thin wall TPU prints.

There were some instances of dribbling type effects like in your photos above, but overall the results were massively better.  No need to use Z-retraction with its associated stringing problems, lovely smooth interior and exterior.  Fantastic!

In relation to the above, I'd have hoped that combing moves could be, in order of priority:
- over the middle of the infill, if present, or
- over the centre of innermost wall, as per this PR.

Thank you!

**Comment by diegopradogesto** [comment] 2018-06-19 07:06
@ctzsnooze this fix is not yet in 3.4 beta, it is still in review process and it will be incorporated probably in the next release (not 3.4). However during the 3.4 development stage we (also together with @smartavionics) were working in some improvements in the combing, so maybe is related with what you see in 3.4 beta. 
I appreciate that you share your thoughts.

**Comment by ctzsnooze** [comment] 2018-06-19 09:39
Actually in 3.4 the retraction during combing is in place, and works great!  That's what's making the difference right now with my TPU prints.  This change would make it even better  :-)

Thanks!

**Closed** 2018-07-31 23:14 UTC
Labels: Category: Engine, Status: Fixed/Solved, Type: Improvement
