### ISSUE TITLE
슬라이싱 실패

### ISSUE THREAD

**Issue by LDONGYEOP** [Ultimaker/Cura#16362] opened 2023-08-02 07:24 UTC
### Cura Version

5.4.0

### Operating System

윈도우11

### Printer

creality ender-3

### Describe your model

아니요

### Add your .zip here ⬇️
[새 압축(ZIP) 폴더.zip](https://github.com/Ultimaker/Cura/files/12237264/ZIP.zip)

**Comment by MariMakes** [comment] 2023-08-02 09:08
Hey @LDONGYEOP,

저는 한국어를 거의 하지 못하지만 당신을 도울 수 있을 것 같습니다

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/16002
This should be resolved in the next 5.5 release.
The linked ticket contains a workaround to slice this object 😉 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/16002

**Closed** 2023-08-02 09:09 UTC
Labels: Type: Bug, Status: Duplicate, Slicing Error :collision:
