### ISSUE TITLE
Space to write notes

### ISSUE THREAD

**Issue by Zogar89** [Ultimaker/Cura#9977] opened 2021-06-14 16:16 UTC
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Sometimes it is necessary to write notes on how to handle some projects.

For example, record slicer options tested, which worked and which did not.

This already exists in Prusaslicer, it would be nice in Cura.

I'm just talking about a plain text field that is saved with the project.
Let it be consulted in several months in the future when I no longer remember the particularities of the project in question.

### Describe alternatives you've considered

None

### Affected users and/or printers

All

**Comment by fvrmr** [comment] 2021-06-15 08:00
Hi @Zogar89 thank you for your feature request. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/7468 
We had a ticket on our backlog for this, but it got removed because we don't think we will work on it anytime soon. 

I will close this ticket as a duplicate.
Hope you understand!

**Closed by fvrmr** 2021-06-15 08:00 UTC
Labels: Type: New Feature
