### ISSUE TITLE
Cura 4.4.1 Won't Launch

### ISSUE THREAD

**Issue by bxlaster0611** [Ultimaker/Cura#7035] opened 2020-01-28 13:13 UTC
**Application version**

Cura 4.4.1

**Platform**

Windows 10

**Printer**

Ender 3

**Reproduction steps**

Launch Cura from anywhere on PC

**Screenshot(s)**

![Cura Crash Report](https://user-images.githubusercontent.com/60391174/73266804-a2811800-41a5-11ea-9612-4f4c342f0ea0.png)

**Actual results**

I get the blue hourglass wheel for about five seconds then it disappears and no actions are taken after. I have updated my computer with the latest updates so that is not an issue. I have attempted to run Cura through all the options in compatibility troubleshooter. I have even deleted and reinstalled Cura now probably 10 times. I have tried to run "as administrator" multiple times. I have given Cura permission in windows defender and have even attempted to restore windows defender settings to default. I have gone as far as following some youtube videos to look into launching actions but all other programs/apps on my laptop are fine. When I install older Cura versions they still have the exact same issue upon launch. It shouldn't be a RAM issue as I have 16GB and Cura used to run smoothly I have tried everything a basic computer guy would know of. I have attached a crash/diagnostic report. Any help/suggestions would be awesome and highly appreciated!!

**Expected results**

Cura should properly launch and not crash

**Project file**

**Log file**

%APPDATA%\cura\<Cura version>\cura.log

**Additional information**

**Comment by mahtDFR** [comment] 2020-01-28 13:48
Duplicate of #6197 
Thanks for the report. This should be fixed in the upcoming release.

**Closed by mahtDFR** 2020-01-28 13:48 UTC
Labels: Type: Bug
