### ISSUE TITLE
Travels when changing extruder/colors

### ISSUE THREAD

**Issue by maaspt** [Ultimaker/Cura#2433] opened 2017-09-14 20:35 UTC
I am having  strange travels when using two extruder changing colors with the same hotend.

If the project has two colors but the first layer only has one, the hotend always travel to (x0,y0) no changes on z, on every extruder/color change, no matter if it has prime tower or not. 
If the project has 100+ extruder changes, it goes 100+ times (x0,y0). It afects outer shell finish, and color oozing.

If the objet has two color but they start from first layer, first layer has two colors, I don`t get these travels from X and y to 0, on every extruder/color change.

Are these thavels a default feature, if they are, why ? How to disable them ?

It happens on all objects that do not have two colors in first layer, no matter what extruder or printer configuration I have. 

Best regards

**Comment by Ghostkeeper** [comment] 2017-09-20 10:29
I suspect it's the extruder switch start/end position.

The author of the printer definition you're using should set the setting `machine_extruder_start_pos_abs` to `false`. This way the start/end position gets interpreted as a relative coordinate and moves to relative coordinate 0,0 are left out.

**Comment by Ghostkeeper** [comment] 2017-09-20 10:29
What printer are you using?

**Comment by maaspt** [comment] 2017-09-21 21:46
I have my own build cartasian printers with marlin 1.1.5 , working with  two extruders one nozzle.

I don´t think it is printer definition on marlin, because without any extruder start/end gcode in cura, travels to x0,y0 are visible in Cura, any version.

If you dowload a project from thingiverse with two or more colors, open it in cura merge them, and you can see travels I am talking about.
The project you select, second color can not start in first layer.

**Comment by Ghostkeeper** [comment] 2017-09-26 09:12
I didn't mean a printer definition on Marlin, but a printer definition in Cura.

This is what I get with a proper printer definition in Cura: It moves to the switching bay in the top-right.
![image](https://user-images.githubusercontent.com/2448634/30852083-ee3ee890-a2aa-11e7-9487-d2b3773e517e.png)

And this is what I get with Custom FDM Printer: In this case, the extruder's start and end positions are 0 and the `machine_extruder_start_pos_abs` is also False, so there are no strange movements to 0 (only the one from the starting location on the first layer):
![image](https://user-images.githubusercontent.com/2448634/30852297-9cd5f812-a2ab-11e7-94c7-235dcc2a2848.png)

**Comment by maaspt** [comment] 2017-10-01 17:22
Select a project that does not start with two color in first layer.

second color starts after first layer.
![cura2](https://user-images.githubusercontent.com/29154277/31057130-64ef19f0-a6d5-11e7-9ebe-21456208073e.jpg)
![cura](https://user-images.githubusercontent.com/29154277/31057136-6e98069c-a6d5-11e7-8ad5-ae6e3e397288.png)

**Comment by maaspt** [comment] 2017-10-01 17:38
please get these project
https://www.thingiverse.com/thing:2524765

Select objects and extruders to start two colors in first layer, I get no travels to (0,0)

If you select objects and colors that you get object with same color in first layer I get travels to (0,0) 

![2](https://user-images.githubusercontent.com/29154277/31057251-a1af5dc6-a6d7-11e7-8464-64f3df84e78c.jpg)
![1](https://user-images.githubusercontent.com/29154277/31057252-b07517ce-a6d7-11e7-950c-e5dca0f0052e.jpg)
![4](https://user-images.githubusercontent.com/29154277/31057256-b3bd0a36-a6d7-11e7-9784-6520b68d0645.jpg)
![3](https://user-images.githubusercontent.com/29154277/31057258-b5d17708-a6d7-11e7-904d-e55529521724.jpg)

**Comment by maaspt** [comment] 2017-10-01 17:56
I am on Custom FDM Printer

Already changed machine_extruder_start_pos_abs to false, in fdmextruder.json but getting same travels, maybe I am not changing in the right file.

"machine_extruder_start_pos_abs":
                {
                    "label": "Extruder Start Position Absolute",
                    "description": "Make the extruder starting position absolute rather than relative to the last-known location of the head.",
                    "type": "bool",
                    "default_value": false,
                    "settable_per_mesh": false,
                    "settable_per_extruder": false,
                    "settable_per_meshgroup": false,
                    "settable_globally": false
                },

**Comment by Ghostkeeper** [comment] 2017-10-11 13:57
I'm getting the same result using a similar model that I made:

![image](https://user-images.githubusercontent.com/2448634/31444515-b488e198-ae9c-11e7-857c-2d3ab476b325.png)

I tried modifying the prime position (hence the giant disallowed area that you see there) but it still happened. I suspect it might be a bug in the engine because I get some supposedly empty layers which aren't in the model.

**Comment by Ghostkeeper** [comment] 2017-10-11 14:03
I was able to move half of them by modifying Layer Start X and Layer Start Y. This is because the initial position of a layer is unknown when the travel moves are planned, because the travel moves are planned for all layers at the same time.

**Comment by Ghostkeeper** [comment] 2018-02-21 09:26
Our project manager removed this from our planning because it was not deemed important enough.

**Comment by epsalmond** [comment] 2018-06-30 04:35
@maaspt and others, you can solve this with Extenions > Post Processing script.

Add a find and replace for the negative position moves.  See below.

![screenshot 2018-06-29 21 33 49](https://user-images.githubusercontent.com/424145/42121452-48aac9bc-7be4-11e8-9536-2fb666d78912.png)

**Comment by TimoErdmann** [comment] 2018-09-24 14:11
so any news on this Bug?

**Comment by Ghostkeeper** [comment] 2018-11-21 13:19
Yes, I believe we fixed this in version 3.6 (or was it 3.5?). Could you try again?

**Comment by xile6** [comment] 2018-12-24 22:52
This problem has not been fix in 3.6
I just ran into it today. Really sucks because it rams the hotend into a bed clip.
Any thing to fix this? besides the replace code?

**Comment by com9** [comment] 2019-02-04 21:57
Still unfixed and really dangerous Bug, please, please fix!

**Comment by paukstelis** [comment] 2019-03-09 16:54
Agreed that this is dangerous. This is still in CuraEngine 4.0 (current master).

**Comment by Ghostkeeper** [comment] 2019-03-11 12:56
This is a duplicate of https://github.com/Ultimaker/Cura/issues/5383. This issue is older but that issue has some good reproduction steps that will help debug this. Let's move the discussion over there.

**Closed by Ghostkeeper** 2019-03-11 12:56 UTC
Labels: Category: Engine, Status: Deferred, Type: Bug
