### ISSUE TITLE
Slicing model fails every time regardless of checking for items suggested

### ISSUE THREAD

**Issue by EgrStallion** [Ultimaker/Cura#11225] opened 2022-01-09 04:39 UTC
### Application Version

4.12.1

### Platform

Windows 10 64-Bit

### Printer

Creality Ender 3 Pro

### Reproduction steps

Set setting to 100% infill, low quality
Tried to slice part

### Actual results

received error message "unable to slice"

"Please review settings and check if your models:
-Fit within the build volume
-Are assigned to an enabled extruder
-Are not all set as modifier meshes"

### Expected results

Slicing should have occurred.  I did not play with extruder settings at all, and my build volume was well under 220 x 220mm.  (Not sure what a modifier mesh is, though.)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE3PRO_Rectangular Pot.zip](https://github.com/Ultimaker/Cura/files/7834462/CE3PRO_Rectangular.Pot.zip)
![2022-01-08_12-25-16](https://user-images.githubusercontent.com/97374357/148669618-b27944b8-166c-4320-8b77-7adf09093269.png)

**Comment by GregValiant** [comment] 2022-01-09 16:15
The gray border is reserved for the skirt/brim and you can see your model intrudes into that area.  You have a skirt Line Count of 3 and a Skirt Distance distance of 10mm and that adds to the footprint size of the model on the build plate.  So the 215 model + (1.2 + 10) on each end = 237.4.
Change the Skirt Line Count to 1 and the Skirt Distance to 2mm and the footprint becomes 219.4 and you should be good.

**Comment by EgrStallion** [comment] 2022-01-10 05:41
Thank you, Greg!  I obviously am still becoming familiar with the
software.  I was finally able to get it to slice due to your advice.  I
noted how to go through all the other advanced settings now as well
(albeit, will need to come up to speed on a few of them).

**Comment by fvrmr** [comment] 2022-01-10 10:56
Closing this issue since this is not a bug but related to settings. 
Feel free to reach out if you have more questions!

**Closed by fvrmr** 2022-01-10 10:56 UTC
Labels: Type: Bug
