### ISSUE TITLE
Random Cura Crash

### ISSUE THREAD

**Issue by RalloTa** [Ultimaker/Cura#1520] opened 2017-03-10 19:37 UTC
when using cura it will randomly crash with no explanation

im using windows 10 
the problem occurs about have way throught slicing large objects(longer that 1 hour)
i am using the latest version of cura(2.4.0)

**Comment by fieldOfView** [comment] 2017-03-10 19:51
Thanks for your report. Unfortunately it is less than useless without additional details. At the very least we need to know your OS, and the version of Cura you are using. Logs are also critical in determining the cause of crashes.

**Comment by ianpaschal** [comment] 2018-02-21 09:49
Since this is a year old and never got more info, I am closing it.

**Closed by ianpaschal** 2018-02-21 09:49 UTC
Labels: needsinfo
