### ISSUE TITLE
Separate Top/Bottom Flow into Top Flow and Bottom Flow

### ISSUE THREAD

**Issue by weaseljohnson** [Ultimaker/Cura#11427] opened 2022-02-06 21:08 UTC
### Is your feature request related to a problem?

I am working to solve my Elephants Foot problem. I have found that decreasing the flow for the initial layer and bottom layers has helped to fix it, significantly. However, currently decreasing my bottom flow also decreases my top flow, which has created gaps in some of the top surfaces of my prints. That is not great.

I've also found that I get some over extrusion, just in the first layers, which causes nozzle dragging. This has also been mitigated by decreasing initial and bottom flow. But, the result with the top layers is still the same. 

### Describe the solution you'd like

I believe that if Top/Bottom Flow could be separated into two settings "Top Flow" and "Bottom Flow", that would allow for much better control and allow for better starts to prints without compromising the top surface quality. 

### Describe alternatives you've considered

I've already calibrated E-steps and general flow rate, and calibrated ideal temperatures for my filament. Those things have helped, but changing initial and bottom flow rates still have been the best solution to my issues. 

### Affected users and/or printers

I think everyone would benefit from this change.

**Comment by fvrmr** [comment] 2022-02-07 15:38
Hi @weaseljohnson thank you for your feature request.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/10970 I will close this issue, since it is a duplicate.

**Closed by fvrmr** 2022-02-07 15:38 UTC
Labels: Type: New Feature
