### ISSUE TITLE
Ugly font with Russian locale

### ISSUE THREAD

**Issue by sadr0b0t** [Ultimaker/Cura#2518] opened 2017-09-29 12:00 UTC
Hello,

I am using Cura2.7 Linux on Ubuntu 16.04. Interface font with Russian locale is ugly in menu and dialogs. On the Print setup panel in the main window is ok.

See screenshot:
![ugly cura russian font](https://user-images.githubusercontent.com/1653222/31015083-f028d372-a526-11e7-9e47-4851ec10cc90.png)

**Comment by Ghostkeeper** [comment] 2017-10-04 13:12
Doesn't reproduce for me on Ubuntu 17.04.

![image](https://user-images.githubusercontent.com/2448634/31177463-6738e57c-a916-11e7-8a4c-c7df4d06ee3c.png)

Let's see if other users of 16.04 find this, too.

**Comment by sadr0b0t** [comment] 2017-12-21 17:05
I have installed Cura 3.1 and have exactly same problem. It is pleasant to know, that Ubuntu 17.04 does not show this problem with Cura, but Ubuntu 16.04 LTS is going to be with us at least until 2021, so I hope this problem could be somehow fixed inside Cura build.

**Comment by ChrisTerBeke** [comment] 2018-03-02 21:12
3.3 will have updated fonts, should be fixed then. Please re-open if that's not the case.

**Closed by ChrisTerBeke** 2018-03-02 21:12 UTC

**Comment by sadr0b0t** [comment] 2018-04-26 12:33
Same story with Cura 3.3.1

![2018-04-26 15-32-23](https://user-images.githubusercontent.com/1653222/39305841-1be9327e-4967-11e8-8621-0518c349c4e6.png)

**Comment by sadr0b0t** [comment] 2018-04-26 12:42
And now not only dialogs, but also print task settings are disturbed (in 3.1 they were ok)

![2018-04-26 15-35-58](https://user-images.githubusercontent.com/1653222/39306150-fe1fd378-4967-11e8-8427-f4cd21b9fbf6.png)

**Comment by sadr0b0t** [comment] 2018-04-26 12:43
can't reopen

**Comment by ianpaschal** [comment] 2018-04-26 14:18
That was a message for us to re-open it.

I have just discussed this internally though, and our Estonian (but Russian speaking) colleague did some research in Russian to try and find a solution. He could not find any possible solution and since Russian Ubuntu users are a very, very small demographic of our total users we won't be able to spend any time on this issue.

Sorry about that.
