### ISSUE TITLE
Does not print when the STL is equal to or less than the first layer height

### ISSUE THREAD

**Issue by joseaguardia** [Ultimaker/Cura#10473] opened 2021-09-18 13:23 UTC
### Application Version

4.11

### Platform

Ubuntu 21.04 with KDE 5.21.4

### Printer

Anycubic i3 Mega S

### Reproduction steps

Import a STL file with a height of 0.24mm, and slice it with a 0.24mm first layer

### Actual results

Cura leaves the piece grayed out as unprintable. If I lower the layer height to 0.2 or even 0.23 it does print it

![image](https://user-images.githubusercontent.com/16305835/133890162-253ba856-68dd-4b7b-9273-f3a24a3b0c27.png)

### Expected results

The part is printed at 0.24mm 

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[curaIssue.3mf.zip](https://github.com/Ultimaker/Cura/files/7189948/curaIssue.3mf.zip)

**Comment by jellespijker** [comment] 2021-09-18 14:03
Duplicate of #10394 closing this report in favor of the discussion on that thread

**Closed by jellespijker** 2021-09-18 14:03 UTC
Labels: Type: Bug
