### ISSUE TITLE
Cura slicing add strange things

### ISSUE THREAD

**Issue by pierreblavy2** [Ultimaker/Cura#11766] opened 2022-04-04 13:32 UTC
### Application Version

4.13.1

### Platform

fedora 35

### Printer

CR10 s pro V2

### Reproduction steps

Open project
Slice
Show preview

See screeshot to see the part that are added during slicing

### Actual results

There is a strange planed, added by the slicing procedure, that's not supposed to be here. This plane is marked WTF on the screenshot

### Expected results

Slicing a tube, should produce a tube

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CCR10SPRO_drawer-tube.3mf.zip](https://github.com/Ultimaker/Cura/files/8410113/CCR10SPRO_drawer-tube.3mf.zip)
![screen](https://user-images.githubusercontent.com/5548408/161555088-811dcf7d-e7b4-48de-81a3-8060f90d5284.png)

**Comment by pierreblavy2** [comment] 2022-04-04 15:00
**- Exclusive works for me. Thanks :)**
- Inclusive makes things worse

**Comment by fvrmr** [comment] 2022-04-05 09:01
Hi @pierreblavy2 thank you for your report. 
This looks like a duplicate of https://github.com/Ultimaker/Cura/issues/9979
We have a ticket on our backlog for this! I will close this issue, since it is a duplicate.

**Closed by fvrmr** 2022-04-05 09:01 UTC
Labels: Type: Bug
