### ISSUE TITLE
Multi-file object placement territory battle

### ISSUE THREAD

**Issue by cusz721** [Ultimaker/Cura#15456] opened 2023-05-06 19:45 UTC
### Application Version

5.3.1

### Platform

Linux Mint 

### Printer

Ender 3

### Reproduction steps

1. start with blank build plate
2. open file selector
3. select multiple files at once
4. select open

### Actual results

files are loaded and parts are placed on build sheet intersecting each other. AKA, parts are not auto-arranged when multiple parts are selected and opened at the same instance. 
![cura](https://user-images.githubusercontent.com/82480291/236643655-11d82f51-24c4-40b8-8b9c-a2cf92721d92.jpg)

### Expected results

when multiple part files are selected and opened at the same instance, parts should be loaded into cura and auto-arranged. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none

**Comment by MariMakes** [comment] 2023-05-08 15:16
Hey @cusz721,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/14838
We actually have a developer working on a solution right now. 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/14838

**Closed by MariMakes** 2023-05-08 15:16 UTC
Labels: Type: Bug, Status: Triage
