### ISSUE TITLE
Skirt not flowing in continuous line.

### ISSUE THREAD

**Issue by lococnc** [Ultimaker/Cura#7577] opened 2020-04-23 13:47 UTC
The purpose of the skirt is to purge nozzle and get flowing, but in 4.6.0 the skirt now changes start point for each row instead of printing entire thing in one continuous line. This causes issues and should be put back the way it was before.

**Comment by smartavionics** [comment] 2020-04-23 14:48
https://github.com/Ultimaker/CuraEngine/pull/1231 probably fixes this issue as well.

**Comment by ashleysommer** [comment] 2020-04-24 09:16
I noticed this too, was about to come to make an issue about it. It used to be one continuous line, now on 4.6.0 it stops the line, and moves over one layer and starts a new line. Not a big deal, but less correct than it was before.

**Comment by rburema** [comment] 2020-04-28 13:42
I've only reviewed the code, but I agree with @smartavionics that the PR will probably fix this issue.

**Comment by jacekkopecky** [comment] 2022-07-31 09:53
I have just installed Cura 5.1 and noticed that the skirt is no longer continuous like it used to be. It doesn't even start near the same point. To illustrate: 

<img width="259" alt="Screen Shot 2022-07-31 at 10 49 03" src="https://user-images.githubusercontent.com/807315/182020756-054de148-0e9b-4655-ba6e-0c15cc372315.png">

<img width="260" alt="Screen Shot 2022-07-31 at 10 49 16" src="https://user-images.githubusercontent.com/807315/182020755-31c45c2c-6dea-408d-a6ff-23438649e2b8.png">

<img width="256" alt="Screen Shot 2022-07-31 at 10 49 33" src="https://user-images.githubusercontent.com/807315/182020752-46dd6c57-f264-416e-b9ce-aed0da205999.png">

It starts higher every time... That's unnecessary travel moves.

**Comment by rburema** [comment] 2022-07-31 20:05
@jacekkopecky Thanks for the notify, but could you please make a new bug report? This was closed a while ago, and it's likely that the cause is completely different.

**Comment by jacekkopecky** [comment] 2022-07-31 20:10
Will do - I'll look into it some more. This issue isn't closed though @rburema , that's why I posted here.

**Comment by GregValiant** [comment] 2023-09-15 15:37
I'll go ahead and close this as it appears there is another issue open on this same topic.

**Closed by GregValiant** 2023-09-15 15:37 UTC
Labels: Type: Bug
