### ISSUE TITLE
Add new layer chart: cooling fan speed

### ISSUE THREAD

**Issue by DefektSan** [Ultimaker/Cura#10568] opened 2021-10-05 06:09 UTC
### Is your feature request related to a problem?

Cura does not have layer chart of cooling fan speed.
This is very inconvenient, i cant view fan speed on layers before printing.
Cooling fan speed often very high speed.
Without fine adjustment cooling speed before printing, i can only adjust fan speed between done printing models.
Different plastics, need different settings of fan speed, if cooling not enough - printing model diffuses when printing, if cooling too much - printed model quickly cracks between layers because plastic bad sintering of layers.

### Describe the solution you'd like

Add to layer charts new chart "cooling fan speed" similar to existing layer charts as "speed" "flow" or "line type".
Like existing layer chart "speed" have color diagram match with line color, add similar diagram and line color to chart "cooling fan speed".

### Describe alternatives you've considered

Without "cooling fan speed" layer chart i can only try guess in mind, what will be the fan speed on current line or layer height based on line color in layer chart "speed". However this method inaccurate and does not allow adjust fan speed before printing, just guess in mind.

### Affected users and/or printers

This feature can helpful for all slicer user to fine adjust fan speed by cooling settings, and will help to prevent layer delamination with  instantly speed up fan speed before printing.

**Comment by fvrmr** [comment] 2021-10-05 12:39
Hi @DefektSan thank you for your feature request.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/7495

I will close this issue, since it is a duplicate.

**Closed by fvrmr** 2021-10-05 12:39 UTC
Labels: Type: New Feature
