### ISSUE TITLE
Christmas Village 2019 slicing error

### ISSUE THREAD

**Issue by Pants536** [Ultimaker/Cura#17442] opened 2023-11-27 03:20 UTC
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Creality Ender-3 Pro

### Name abnormal settings

Doesn't slice with standard settings along with mine.

### Describe model location

(0,0), doesn't print at any rotation (90 degree increments)

### Describe your model

Haven't sliced before, Says watertight.

### Add your .zip here ⬇️

[Christmas Village 2019.zip](https://github.com/Ultimaker/Cura/files/13469388/Christmas.Village.2019.zip)
![image](https://github.com/Ultimaker/Cura/assets/87623852/d8c630bf-5006-4f96-aad5-ffe8d98ddd57)
![image](https://github.com/Ultimaker/Cura/assets/87623852/a071a35e-72d4-4e78-95b8-4c2638833b1f)
![image](https://github.com/Ultimaker/Cura/assets/87623852/4fc754f6-7c93-4a9c-b036-5b554e4bfa69)

**Comment by GregValiant** [comment] 2023-11-27 03:47
Thanks for the report.
This is a duplicate of numerous other reports on this model not slicing.  It will slice in 5.2.2 or 4.13.1 but not in later versions.  
I'll mark this as a duplicate and go ahead and close this.  I hope you understand.

**Closed by GregValiant** 2023-11-27 03:47 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error :collision:
