### ISSUE TITLE
There are no supports when the model is not lying on the table.

### ISSUE THREAD

**Issue by arturius78** [Ultimaker/Cura#15663] opened 2023-06-02 18:18 UTC
### Application Version

5.3.1

### Operating System

Windows 11

### Printer

Creality Ender 2 Pro

### Reproduction steps

Tried different settings

### Actual results

No result

### Expected results

There are no supports when the model is not lying on the table, but hanging in the air. It is necessary for printing with nylon so that the entire model lies on the supports. This helps to avoid deformation. When slicing, the model is forcibly lowered onto the table. In other slicers, this setting works.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

There are no supports when the model is not lying on the table, but hanging in the air. It is necessary for printing with nylon so that the entire model lies on the supports. This helps to avoid deformation. When slicing, the model is forcibly lowered onto the table. In other slicers, this setting works.

**Comment by GregValiant** [comment] 2023-06-02 21:38
Thanks for the report.

- Turn off "Generate Supports"
- Go to Mesh Fixes and turn off "Remove Empty First Layers"
- Turn on "Generate Supports"

This appears to be a duplicate of #14989 and I'll mark it.  This bug has been addressed and should be fixed in 5.4.  I'll go ahead and close this report.  Let me know if you feel that this is different and I can re-open it.  A project file would be helpful in that case.  There is more information in the 14989 page.

**Closed by GregValiant** 2023-06-02 21:38 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation
