### ISSUE TITLE
Tree support starts from emptiness

### ISSUE THREAD

**Issue by Chrispizz** [Ultimaker/Cura#3249] opened 2018-02-07 10:16 UTC
**Application Version**
CURA V 3.2
**Platform**
Windows 

**Qt**
N/a

**PyQt**
N/a

**Display Driver**
NVIDIA 

**Steps to Reproduce**
1 - Download the STL of YODA BUST on thingiverse 
2 - Drop it in CURA V3.2 with Z scale 100.0 ( 10 centimeters ) 
3 - Apply the "Tree supports" 

**Actual Results**
1 - You will see a lot of support for low points of the chin
2 - You will see under the right ear a support not connected , begining from an empty space , starting from emptiness , with nothing below

**Expected results**
The support should begin from an other support or from the bed

**Additional Information**
![yoda - support arborescent](https://user-images.githubusercontent.com/6710050/35916293-36cb1142-0c0a-11e8-87cb-aab6657fc940.JPG)

**Comment by ChrisRiddell** [comment] 2018-02-07 10:43
My tree supports look way different to what is generated for you.

But I can get tree supports to generate mid air.
![tree2](https://user-images.githubusercontent.com/2055566/35912035-65d22dd6-0c4b-11e8-9259-a92d1d6d8e87.gif)


While checking this I noticed it also does not always support unsupported areas.
![tree](https://user-images.githubusercontent.com/2055566/35912099-8661fb3a-0c4b-11e8-8ce6-66f1bfb1cacc.gif)

**Comment by Chrispizz** [comment] 2018-02-07 10:47
That you show to us is not "tree support"

**Comment by ChrisRiddell** [comment] 2018-02-07 10:57
That is what the "Tree Support" option generates for me.

@Ghostkeeper is my Cura not generating tree supports as per the implementation?

**Comment by Chrispizz** [comment] 2018-02-07 11:05
I don't see your "branches" as a support growing

**Comment by ChrisRiddell** [comment] 2018-02-07 11:13
Yes it is very confusing, I have tagged the dev that done the CuraEngine PR to get some clarification.

**Comment by Chrispizz** [comment] 2018-02-07 11:25
I think that you had not "unchecked" the classical support 
Enable only "Tree support" in "Experimental" section

**Comment by ChrisRiddell** [comment] 2018-02-07 11:30
Above is with "Support" unchecked, If I enable "Support" as well as "Tree support" I get the same result as above but with normal support within the empty space.

**Comment by ChrisRiddell** [comment] 2018-02-10 10:23
So seem to be getting the same type as @Chrispizz now I seem to get the other style depending on model loaded 😕 

https://www.thingiverse.com/thing:1074129

![floating](https://user-images.githubusercontent.com/2055566/36061022-18b3f60a-0ea4-11e8-818f-4cd26f06f22e.PNG)

**Comment by slikk66** [comment] 2018-02-17 00:14
Came here looking for same thing.. I was using 3.2 beta before and got trees, but on 3.2.1 I'm getting non-trees when should be trees.

**Comment by Ghostkeeper** [comment] 2018-03-09 08:47
All of your screenshots look like Cura's tree support. Don't worry about it not being tree support, I guess. ChrisRiddell's last screenshot has support infill though (which defaults to 0% when tree support is enabled and normal support is not). Cura's tree support does look like it envelops the model sometimes.

The tree support generating in mid-air for ChrisRiddell [here](https://github.com/Ultimaker/Cura/issues/3249#issuecomment-363729630) is sort of a limitation of how the support is generated. I don't really consider it a big problem since it just results in some minor blips on the support and quickly corrects itself in most cases.

The original problem that Chrispizz had though is more serious. I've seen it happen before at colleagues but don't know what causes it. We'll have to investigate that.

The second animation that [ChrisRiddell](https://github.com/Ultimaker/Cura/issues/3249#issuecomment-363729630) posted about it not supporting some areas is new to me. But it could happen if you set support to be touching the build plate only, when there is no possible path towards the build plate. That's just like normal support.

**Comment by Ghostkeeper** [comment] 2018-03-09 10:15
I can't reproduce this with the Yoda model though. What settings are you using? Maybe share a project file?

**Comment by DiddiZ** [comment] 2018-04-07 09:59
I get this with a different model `Radial_Fan_Fang_5015.stl` from https://www.thingiverse.com/thing:2175956/ and `Support Placement: Touching Buildplate`.

![grafik](https://user-images.githubusercontent.com/645819/38453710-66b6a384-3a5a-11e8-850f-70e5576a2e7d.png)

The towers inside the fan duct start in thin air. Granted, there is no way these branches could ever reach the buildplate from inside the ducts, but I think Cura should either complain, or remove these supports entirely instead of letting them start mid-air.


Using Cura 3.3.0-BETA

**Comment by tsumeone** [comment] 2018-04-20 20:25
I am also still experiencing this on 3.3.0 Beta (coincidentally, also trying to print a fan duct).  https://www.thingiverse.com/thing:2861755  It's a shame since tree supports generate a much better finish for me while being way easier to remove.  I loathe the normal supports.

![image](https://user-images.githubusercontent.com/5659068/39072075-518068d0-44b7-11e8-9bfc-16eae10a0155.png)

**Comment by DiddiZ** [comment] 2018-04-20 21:00
Recently, I ran into this problem so often, I basically had to abandon tree support, which is a shame.

I think the following happens (I have by no means looked into the code, so I could be way off): Cura selects the points on the model which shall be supported. Then, working from the top of the model down, Cura tries to plan the trees layer for layer. If for some reason, the tree can't be continued, the tree ends in mid-air. Reasons can be `Tree Support Branch Angle` (as in there is no way to avoid the model and not violate the angle constraint) or `Tree Support Branch Diameter Angle` (i.e.: the increased diameter would hit the model).

This is based on how `Support Placement: Touching Buildplate` and `Tree Support Branch Angle` affect the chance for partial trees. When increasing `Tree Support Branch Angle` a previuosly unconnected tree can span around and obstacle and reach the buildplate. Also, when decreasing `Tree Support Branch Diameter Angle` a collision with the model could be avoided.

If my assumption is correct, Cura should be able to detect if it can not continue a branch (it already does, as it does not continue) , then remove the partial branch (it could not be printed anyway and would just create a mess, but I guess this is the tricky part as branches can effect each other) and possibly display a warning message.

**Comment by Ghostkeeper** [comment] 2018-05-08 13:01
It reproduces 100% with tsumeone's model when I set Support Placement: Touching Buildplate on a blank Custom FDM Printer. This way we can debug the issue.

**Comment by diegopradogesto** [comment] 2018-07-13 12:06
For Devs.: CURA-5341

**Comment by Ghostkeeper** [comment] 2018-08-27 08:28
This is fixed in the next release.

**Closed by Ghostkeeper** 2018-08-27 08:28 UTC
Labels: Category: Engine, Status: In Progress, Type: Bug

**Comment by mr-moon** [comment] 2022-09-03 21:53
Still issue at 5.1.0
<img width="710" alt="image" src="https://user-images.githubusercontent.com/933164/188288744-822914cb-5a47-4f9d-8619-5904c99a38ae.png">

**Comment by jellespijker** [comment] 2022-09-04 16:15
@mr-moon please open up a new ticket for this and make sure you that you provide the project 3mf file as well.
