### ISSUE TITLE
Slicing failed with an unexpected error

### ISSUE THREAD

**Issue by YMY2005** [Ultimaker/Cura#17312] opened 2023-11-14 12:11 UTC
### Cura Version

5.5.0

### Operating System

Windows 10

### Printer

FLSUN 400

### Describe model location

Center

### Describe your model

Cura 5,4,0 Slicing

### Add your .zip here ⬇️

[FV_GENERIC MALE - Camlock Male Connection v0.zip](https://github.com/Ultimaker/Cura/files/13348526/FV_GENERIC.MALE.-.Camlock.Male.Connection.v0.zip)

**Comment by GregValiant** [comment] 2023-11-14 13:22
Thanks for the report.
I had trouble opening the project file (this has been happening lately).  I installed a V400 and imported just the model.  Using the standard "Normal" profile with no changes the model sliced for me in 5.5.0.
![image](https://github.com/Ultimaker/Cura/assets/64202104/8d489329-a5bb-4717-baff-7ece730cf9bc)

Update - after some repairs to my installation using files from your project, I was able to open the project file and (of course) it sliced for me with no problem.

I'll mark this as a duplicate of numerous other reports and close this as the Cura team has lots of examples of this behavior.  I hope you understand.

**Closed by GregValiant** 2023-11-14 13:22 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error :collision:
