### ISSUE TITLE
PyQt6.QtNetwork not found

### ISSUE THREAD

**Issue by SWDontheway** [Ultimaker/Cura#13047] opened 2022-08-16 08:54 UTC
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Ultimaker

### Reproduction steps

1. I have set up the  venv folder, and PyQt6 already exists in the  `C:\Cura\venv\Lib\site-packages`

![image](https://user-images.githubusercontent.com/109791718/184840022-c2718183-362f-4f15-8d10-76e67bb3955e.png)

2. I successfully ran `.\venv\Scripts\activate.ps1`
![image](https://user-images.githubusercontent.com/109791718/184839806-3a51f114-1dcb-486c-a84b-7e4966429284.png)

3. ran `python cura_app.py`

### Actual results

![image](https://user-images.githubusercontent.com/109791718/184838482-0805eb1a-50f4-454a-b05e-4e22957cc517.png)

Traceback (most recent call last):
  File "C:\Cura\cura_app.py", line 23, in <module>
    from PyQt6.QtNetwork import QSslConfiguration, QSslSocket
ImportError: DLL load failed while importing QtNetwork: The specified module could not be found.

### Expected results

no module importing error should happen...

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

what's more, module UM seeems not available as well 

![image](https://user-images.githubusercontent.com/109791718/184839261-63eef093-5c83-4dab-82a8-80ee61240f50.png)

**Comment by jellespijker** [comment] 2022-08-19 15:09
Duplicate of #12773 closing this ticket in favor of that on.

**Closed** 2022-08-19 15:10 UTC
Labels: Type: Bug, Status: Duplicate
