### ISSUE TITLE
Multiplie Parts on Printbed

### ISSUE THREAD

**Issue by tdierks28** [Ultimaker/Cura#10863] opened 2021-11-17 16:53 UTC
### Application Version

4.12

### Platform

macOS Monterey, M1Max

### Printer

Anycubic Vyper

### Reproduction steps

Place a Print Part on Heatbed and right click to multiply. I Use the Vyper Printer Profile

### Actual results

no additional Part created and an the bottom ther is a small Window with no Results

### Expected results

dipplicated objects

### Checklist of files to include

- [x] Log file
- [X] Project file

### Additional information & file uploads

[cube with error.3mf.zip](https://github.com/Ultimaker/Cura/files/7556471/cube.with.error.3mf.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/7556477/cura.log)

**Comment by nallath** [comment] 2021-11-17 18:19
Duplicate of #10249

**Closed by nallath** 2021-11-17 18:19 UTC
Labels: Type: Bug
