### ISSUE TITLE
Skirt distance / size effects active bed size.

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ultimaker/Cura#2528] opened 2017-09-30 23:18 UTC
When increasing skirt distance, the effective bed size shrinks down. this seems unnecessary.
if the model was bigger, Cura wont slice it. 

Skirt @ 70mm
![70](https://user-images.githubusercontent.com/30949968/31050266-04bdc1f8-a64e-11e7-9e74-3192a1709ebd.png)

Skirt @ 20mm
![20](https://user-images.githubusercontent.com/30949968/31050267-088eb7f6-a64e-11e7-8142-68ae0253f875.png)

**Comment by fieldOfView** [comment] 2017-10-01 09:07
> this seems unnecessary.

It is not. Cura "reserves" space to print the brim. Say you have a model 5 mm from the edge of your buildplate, and then you try to print a 10 mm brim. That would not fit on the buildplate.

**Comment by Thisismydigitalself** [comment] 2017-10-01 11:18
But this is clearly not the case. 
as you can see the model is few cm big. skirt is so far away from both the object and the edge of bed. 
Most of the time i print skirts close to the model (5mm or so), but sometimes i chose to print it further away to check that the bed is leveled. 

I believe something is not right here.

**Comment by fieldOfView** [comment] 2017-10-01 11:31
Take your top image. Now drag the model closer to the edge of the available space (ie: the not shaded part of the buildplate). You will see that when the model just about hits the edge of the available space, the skirt will just about hit the edge of the buildplate. It can't go further.

**Comment by Thisismydigitalself** [comment] 2017-10-01 11:57
Thanks for sticking in with me.
Please check both snapshots made for the sake of the argument.
if this is by design then i stand correct. it just seems there can be more room for the skirt to print is such cases.

45mm skirt (Sliced)
![45](https://user-images.githubusercontent.com/30949968/31054297-79c3a62e-a6b8-11e7-8572-46353a189a3e.png)


50mm skirt (Slicing failed)
![50](https://user-images.githubusercontent.com/30949968/31054298-7e338b48-a6b8-11e7-9d34-e9bfefe9fccb.png)

**Comment by fieldOfView** [comment] 2017-10-01 12:11
Determining the outline of the first layer is surprisingly much harder than finding the "shadow" that Cura draws. That shadow is used with the above logic.

Cura uses a simplification (that shadow as opposed to the outline of the first layer), by design.

**Comment by Thisismydigitalself** [comment] 2017-10-01 12:15
Understood.

**Comment by Ghostkeeper** [comment] 2017-10-11 13:11
To find the size of the first layer we'd have to slice first (otherwise we won't know what the first layer is). That just takes too much time because you typically want to see where you can place the model before slicing.

**Comment by ianpaschal** [comment] 2018-03-09 15:19
Relates to: #3371 and #3365.

Question has been answered though so closing.

**Closed by ianpaschal** 2018-03-09 15:19 UTC
