### ISSUE TITLE
Cura 3.5.1 slicing bug, extrusion outside of the model

### ISSUE THREAD

**Issue by Roblue** [Ultimaker/Cura#4661] opened 2018-10-26 07:33 UTC
**Application Version**

3.5.1

**Platform**

Windows 10

**Printer**

Geeetech Clone, Prusa i3 Mk 2

**Steps to Reproduce**

Select Cross 3D as infill pattern, 20% infill density, connect infill lines on, connect polygons on

**Actual Results**

Cura wants to print random lines marked as "Infill" in the layer view outside of the actual print. It happened with several models.
![cura_infill_out_5](https://user-images.githubusercontent.com/44492201/47551162-bafae680-d901-11e8-87a1-99b9dd9793e4.PNG) (Color scheme: Feedrate)

![cura_infill_out_1](https://user-images.githubusercontent.com/44492201/47551221-e382e080-d901-11e8-804c-6b60129c335a.PNG) (Color scheme: Line Type)

**Additional Information**

I wasn't able to reproduce the problem with any other infill density than 20%. The problem is not affected by any settings other then the ones named (as far as I tested).

Additional pictures and the poject file:
[SlicingBug.zip](https://github.com/Ultimaker/Cura/files/2518201/SlicingBug.zip)

**Comment by smartavionics** [comment] 2018-10-26 07:36
Hi, I'm pretty sure this has been fixed for the next release.

See https://github.com/Ultimaker/Cura/issues/4483.

**Comment by rburema** [comment] 2018-10-26 14:28
Hi @Roblue,
I've tested this in 3.5.1 (bug does occur for your model) and a recent master-build (fixed, for this model as well). So I agree with @smartavionics, this is a duplicate of that issue, and will be fixed in the next release.

P.S, As an aside; 'save' instead of 'export' causes settings to be saved as well, this allows for quicker set-up on our end.
cheers, Remco.

**Comment by Roblue** [comment] 2018-10-26 16:43
Thank you for your quick answers.

I may have overlooked the other thread while searching for the issue.
Thanks for the hint @rburema!

Best regards, Rob

**Comment by diegopradogesto** [comment] 2018-10-31 20:13
I'll close this issue since it is a duplicate. Also you can check out Cura 3.6 BETA that is live from today.

**Closed by diegopradogesto** 2018-10-31 20:13 UTC
Labels: Status: Duplicate
