### ISSUE TITLE
How to build and makefile for Cura?(ubuntu 15.10)

### ISSUE THREAD

**Issue by maoshenglinTw** [Ultimaker/Cura#567] opened 2015-12-15 02:44 UTC
Hi, everyone i am Rookie engineer.
I want to build Cura 15.06 and makefile in unbuntu 15.10.
I was follow ubuntu-15.04-build-script.sh to build Cura.,but it is seem fail.
Could someone give me some instructions?

**Comment by nallath** [comment] 2015-12-15 08:24
The build scripts for 15.04 will not work for any version of 15.06

**Comment by Ghostkeeper** [comment] 2015-12-15 08:37
He's talking about Ubuntu 15.04, not Cura 15.04. This is a duplicate of https://github.com/Ultimaker/cura-build/issues/23 so I'll close it here.

**Closed** 2015-12-15 08:37 UTC
Labels: duplicate

**Comment by nallath** [comment] 2015-12-15 08:58
Derp, that should teach me to answer questions before coffee.
