### ISSUE TITLE
Slicing failed with unexpected error

### ISSUE THREAD

**Issue by RAEROVIA** [Ultimaker/Cura#13257] opened 2022-09-10 00:04 UTC
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Creality Ender-3

### Reproduction steps

Imported Object
Clicked Slice

### Actual results

Slicing Failed
Slicing failed with unexpected error

### Expected results

Slice Successful

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE3_Bow 1.zip](https://github.com/Ultimaker/Cura/files/9539251/CE3_Bow.1.zip)

**Comment by GregValiant** [comment] 2022-09-10 15:05
Thanks for the report.
You can see in the image below that the model has a lot of errors as indicated by the red and purple areas.  It won't slice until it is repaired or redesigned.  Unless you shut it off - that warning dialog should have come up when you opened this model in Cura.
![image](https://user-images.githubusercontent.com/64202104/189489020-7dec94c8-97c1-4ea7-a2c7-1b188e6db897.png)

I'll remove the bug label as this doesn't appear to be a Cura issue.  I'll leave it open so you can respond.

Here you can see that it slices after being repaired.
![image](https://user-images.githubusercontent.com/64202104/189489311-a5d46b06-f8c6-4104-ae81-33712c2f5304.png)

**Comment by MariMakes** [comment] 2022-11-10 13:28
Hey @RAEROVIA,

To me, it doesn't seem like a bug in Ultimaker Cura, since the mesh is faulty and Cura is not built to alter meshes in this way, that's what CAD software is for. 

Apologies for any inconvenience caused by our delayed response. 
I'll be closing this issue. I hope you understand.

**Closed by MariMakes** 2022-11-10 13:28 UTC
Labels: Type: Discussion
