### ISSUE TITLE
Cura 3.1 extruder temp problem

### ISSUE THREAD

**Issue by bhamlin52** [Ultimaker/Cura#2942] opened 2017-12-08 19:48 UTC
Cura 3.1 Printing Temperature will change in the gcode. After 4 stringing test slices Cura 3.1 with temp set at 195 or 200 the gcode was at 210. 

![cura 3 1 bug](https://user-images.githubusercontent.com/30397006/33782437-b99a8652-dc26-11e7-90db-34f14cdc882e.JPG)

;FLAVOR:Marlin
;TIME:13575
;Filament used: 8.69164m
;Layer height: 0.2
;Generated with Cura_SteamEngine 3.1.0
M82 ; absolute extrusion mode
G21 ; set units to millimeters
G90 ; use absolute positioning
M82 ; absolute extrusion mode
M104 S210 ; set extruder temp
M140 S50.0 ; set bed temp
M190 S50.0 ; wait for bed temp
M109 S210 ; wait for extruder temp

**Comment by Liukkjan** [comment] 2017-12-08 22:55
I am having this issue as well. Changing printing temperature does not affect saved Gcode. Has the {variables} used in start up code changed?

**Comment by fiveseven808** [comment] 2017-12-09 00:58
I have this issue. So freaking annoying. I can no longer set my first layer temperature. It defaults to 210, I need to edit the gcode manually or change it via Octoprint while it's going.

**Comment by bhamlin52** [comment] 2017-12-09 03:24
I finally uninstalled 3.1 and went back to the prior version. When I did that I got all my profiles back also. 3.1 so far is totally useless.

**Comment by notnyt** [comment] 2017-12-09 09:23
I have this same issue,   Both of these below always output to 210, no matter what I set it to.
````
M104 S{material_print_temperature_layer_0}
M104 S{material_print_temperature}
````

**Comment by fieldOfView** [comment] 2017-12-09 09:52
I would wager a bet that this is a regression caused by the single extrusion rework. Devs: I think the replacement pattern variables are taken from the global stack, but they should be taken from an extruder stack now. Perhaps the easiest way to fix this is to add a resolvement function on the global stack that resolves to taking the value from the first active extruder.

**Comment by joker3d** [comment] 2017-12-09 15:36
i have same problem with a new update

**Comment by ChrisTerBeke** [comment] 2017-12-10 19:05
Did any of you use the beta 3.1 version? If so, remove the 3.1 data folder and then start the 3.1 stable (there were some issues in the beta with project files and version upgrade data storage).

**Comment by notnyt** [comment] 2017-12-10 19:07
I completely uninstalled and removed all of the data folders and the issue persisted. any of the temperature variables in my start script get replaced with 210

**Comment by bhamlin52** [comment] 2017-12-10 19:50
I never installed the 3.1 beta version.

**Comment by ChrisTerBeke** [comment] 2017-12-10 21:22
Okay, clear. I think @fieldOfView's comment is very relevant, I'll mention it to the team tomorrow and create an internal ticket after that.

**Comment by bhamlin52** [comment] 2017-12-10 23:49
Thanks for taking a look at this. You should be able to duplicate. Just slice something and check the gcode.

**Comment by Ghostkeeper** [comment] 2017-12-10 23:50
Duplicate of https://github.com/Ultimaker/Cura/issues/1296, https://github.com/Ultimaker/Cura/issues/2091, https://github.com/Ultimaker/Cura/issues/2546 and https://github.com/Ultimaker/Cura/issues/2812. Only now it also manifests on single extrusion printers because those printers now also have an extruder stack.

**Closed by Ghostkeeper** 2017-12-10 23:50 UTC
Labels: bug

**Comment by ChrisTerBeke** [comment] 2017-12-15 12:22
@fieldOfView I'm working on fixing this issue now, will probably be similar to your suggestion, thanks!

**Comment by tlhintoq** [comment] 2018-01-14 16:55
So this ticket is marked 'closed' - Any idea of when a new release will be available?  Including fix on single-extruders?  I have all previous versions installed side-by-side so right now I just use 3.04 instead of 3.10. The bug isn't killing me for that reason; but its nice to have all the little updates.

**Comment by ChrisTerBeke** [comment] 2018-01-14 16:59
The beta for 3.2 is due in ~1.5 weeks. Keep in mind that it's a beta, so other things might not be working 100% as intended. The stable release will follow about 2 weeks after that.

**Comment by kelemenlajos** [comment] 2018-02-07 14:24
I think i found something. If you install the app, and don't change the material, only switching to custom setup, the extruder temp works as expected. But after changing Material the "Printing Temperature" value isn't used anymore.

Could someone also test this?
(I reproduced the problem on my home and work computer.)
