### ISSUE TITLE
input problems

### ISSUE THREAD

**Issue by 33bill** [Ultimaker/Cura#13701] opened 2022-10-31 12:47 UTC
### Application Version

5.2

### Platform

linux mint 64 bit

### Printer

ender 5 pro

### Reproduction steps

the  accept or click to accept or do an action is not recognized when my huion graphic tablet nib is touched to the tablet,
to achieve a accept click a left click of the(also attached) trackball is necessary.
the tablet moves the curser as normal but having to click the trackball to do an action makes this software unusable..
note the above behavior has only started with versions after 4.12,
i use a guarded keyboard ,the graphic tablet ,and a trackball(mainly for scrolling)
this setup is to allow me to accurately use the computer which i would find very difficult with the normal keyboard and mouse set up due to my poor coordination.
i have not found  a input setting configuration in the app , this would appear to be the issue.
i have not found this issue with gimp blender mypaint audacity cura4.12 etc only with the new version of cura

### Actual results

  aa

### Expected results

aa

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

aa

**Comment by MariMakes** [comment] 2022-10-31 16:41
Hey @33bill,

Welcome to the Ultimaker Cura Github 🚀 

I think I recognize your report. 
Do you think it's a duplicate of https://github.com/Ultimaker/Cura/issues/13299?

Do you mind taking a picture of your set-up and sharing it here?

**Closed** 2022-11-15 00:21 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage
