### ISSUE TITLE
Latest version pauses for 5 secs between retractions.

### ISSUE THREAD

**Issue by rickyelqasem** [Ultimaker/Cura#5865] opened 2019-06-06 10:06 UTC
**Application Version**
<4.1.0>

**Platform**
<Windows 10 Dell Laptop>

**Printer**
<Ender 3>

**Actual Results**
<I have a profile that retracts between parts of the print. Now since 4.1.0 update it pauses 5 secs between parts which i never told it to do.>

**Expected results**
<Continue without pausing>

**Additional Information**
<Project: https://www.dropbox.com/s/0okt8vubzr1u39h/CE3_Sharp%20MZ700.3mf?dl=0   .BTW I have 4.0.0 install on another machine using the same profile I dont have the issue.>

**Comment by rickyelqasem** [comment] 2019-06-06 10:33
Also build time for project using the same profile on 4.0.0 and 4.1.0 differ. 4.0.0 is 12:45 and 4.1.0 is 16:45

**Comment by rickyelqasem** [comment] 2019-06-06 14:20
I found others on Facebook facing same issue.

**Comment by Block137** [comment] 2019-06-06 16:25
More info here>>> https://github.com/Ultimaker/Cura/issues/5753
*Fixed for 4.2

Workaround: Set Maximum Z Speed to non-zero (15 is default for Ender 3)
Found under "Speed" tab
![Screenshot (63)](https://user-images.githubusercontent.com/23495338/59049368-0622a200-88b2-11e9-8cb8-ca47fe39a43f.png)

**Comment by Ghostkeeper** [comment] 2019-06-07 07:49
Duplicate of https://github.com/Ultimaker/Cura/issues/5753.

**Closed by Ghostkeeper** 2019-06-07 07:49 UTC
Labels: Type: Bug
