### ISSUE TITLE
Cura ties up all USBSer devices

### ISSUE THREAD

**Issue by foxabilo** [Ultimaker/Cura#6012] opened 2019-07-15 19:21 UTC
**Application version**

4.1.0

**Platform**

Windows 10

**Printer**

Ender 3

**Reproduction steps**

While printing to my Ender 3 I connected an FTDI RS232 serial interface to a spare USB port in the form of an Arduino.

**Actual results**

Cura takes the newly created USBSer device and holds it in an open state.

**Expected results**

If Cura is already printing and a new USBSer device is detected it should be ignored, if Cura is not already printing it should prompt the user if they would like to connect to the newly discovered device or not.

**Additional information**

None

**Comment by Ghostkeeper** [comment] 2019-07-16 08:24
Duplicate of https://github.com/Ultimaker/Cura/issues/5207

**Closed by Ghostkeeper** 2019-07-16 08:24 UTC
Labels: Type: Bug
