### ISSUE TITLE
[4.7.1] Support Blocker Not Blocking

### ISSUE THREAD

**Issue by Snargola** [Ultimaker/Cura#8349] opened 2020-09-08 18:38 UTC
**Application version**
4.7.1

**Platform**
Windows 10 Home, Intel Core i5-7200U

**Printer**
CR-10s

**Reproduction steps**
1) Loaded model.
2) Orientated model.
3) Placed support blocker.
4) Clicked, 'slice'.
5) Looked at preview.
6) Frowned.
7) Repeated steps 1-6 multiple times, varying step 2, many, many times.
8) Came here to post this.

**Screenshot(s)**
![support02](https://user-images.githubusercontent.com/70974193/92514657-1cab5d80-f1c7-11ea-89bd-76240cc2b0f5.jpg)
![support03](https://user-images.githubusercontent.com/70974193/92514659-1ddc8a80-f1c7-11ea-9382-1a21e2a682a9.jpg)
![support04](https://user-images.githubusercontent.com/70974193/92514660-1ddc8a80-f1c7-11ea-91e3-5d6b314ac213.jpg)
![support05](https://user-images.githubusercontent.com/70974193/92514666-1fa64e00-f1c7-11ea-8233-74c07e119c5b.jpg)
![support06](https://user-images.githubusercontent.com/70974193/92514670-21701180-f1c7-11ea-9fe5-f43eac3dac5e.jpg)
![support07](https://user-images.githubusercontent.com/70974193/92514672-2208a800-f1c7-11ea-87e7-49329f810ddb.jpg)

**Actual results**
An unexpected result. Supports are not blocked, as requested.

**Expected results**
I had hopped that supports in the area selected would be blocked. They are not.

**Project file**
https://www.dropbox.com/s/f9m45ed7chs6bso/ttyt_copper_robbie_sitting_body.3mf?dl=0

**Log file**
No crash but, I can still add the log file later, if you would like.

**Additional information**
Nothing further to add.

**Comment by EeleDahc** [comment] 2020-09-09 04:08
Not working in 4.7.0 on my machine either. Same results.   AMD Ryzen 5 3600.  16gb ram.  Just upgraded from 4.6. Uninstalled 4.6 but kept data.

**Comment by nallath** [comment] 2020-09-09 07:20
The project file that you provided doesn't have any support blockers in it. When I add one myself, it blocks the support as intended. 

Could you re-check the project file and see if it's the right one?

**Comment by Snargola** [comment] 2020-09-09 19:52
> 
> 
> The project file that you provided doesn't have any support blockers in it. When I add one myself, it blocks the support as intended.
> 
> Could you re-check the project file and see if it's the right one?

I have downgraded to Cura 4.6.2 since I posted this however, the problem still persists. I'll post a DropBox link to the project file, gcode and profile I am using.
![support08](https://user-images.githubusercontent.com/70974193/92646251-01118700-f29b-11ea-9ca3-0c0f66455a16.jpg)
Project file
-----------
https://www.dropbox.com/s/lqkj3ezqch7d2h2/robbie_sitting_body.3mf?dl=0

gcode
------
https://www.dropbox.com/s/jp79gois5a9zbed/ttyt_copper_robbie_sitting_body.gcode?dl=0

profile
------
https://www.dropbox.com/s/w1v8srx0f29vz8x/ttyt_copper_robbie_sitting_body.curaprofile?dl=0

Thank you for your help so far.

**Comment by nallath** [comment] 2020-09-10 08:38
You have the `support join distance` set to 2mm and the support blocker itself is also 2 mm. This, combined with the `support horizontal expansion` of 0.5mm, means that the supports are initially removed but then merged back together again.

**Closed by nallath** 2020-09-10 08:38 UTC
Labels: Type: Bug
