### ISSUE TITLE
Arranging models to platform and manual Z hight setting

### ISSUE THREAD

**Issue by GuidoAllegaert** [Ultimaker/Cura#8885] opened 2020-12-04 16:59 UTC
**Application version**
Cura 4.8

**Platform**
Windows 10 Home edition
**Printer**
Creality Ender 3 Pro
**Reproduction steps**
Dear, I just installed Cura 4.8. It is no longer possible to use the right mouse button to 'arrange all models'. You then have to manually go to the Z height of the model. When you enter 'Z = 0' you will not get a red indication that the model is hitting the platform. If you enter Z = -0.01 ', for example, you will get this image.

Hoping to have been of service to you with this report.

Greetings Guido
![01](https://user-images.githubusercontent.com/75493961/101191653-3b03e680-365a-11eb-917d-ad83aa9cb70e.JPG)
![02](https://user-images.githubusercontent.com/75493961/101191659-3b9c7d00-365a-11eb-91f1-802b7b67fe9e.JPG)

2. (Something you did next.)

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save Project. For big files you may need to use WeTransfer or similar file sharing sites. G-code files are not project files!)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by rburema** [comment] 2020-12-08 08:03
Could you attach the model please? I suspect the bottom may not be entirely flat. (You might have to rename or zip it, as github only accepts a few file-formats.)

**Comment by Ghostkeeper** [comment] 2020-12-08 12:21
Duplicate of https://github.com/Ultimaker/Cura/issues/8735. Fixed by https://github.com/Ultimaker/Cura/pull/8802.

**Closed by Ghostkeeper** 2020-12-08 12:21 UTC
Labels: Type: Bug
