### ISSUE TITLE
SLICING ERROR

### ISSUE THREAD

**Issue by brenozicarelli** [Ultimaker/Cura#12922] opened 2022-08-01 06:40 UTC
### Application Version

5.1.0

### Platform

win 10

### Printer

Kingroon KP3s

### Reproduction steps

1. load model
2. start slicing
3. error

### Actual results

error return code 3221226505

### Expected results

successful slice

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

22-08-01 03:03:51,620 - INFO - [MainThread] UM.Qt.QtApplication.__init__ [88]: Adding QT6 plugin path: C:\Program Files\Ultimaker Cura 5.1.0\PyQt6\plugins
2022-08-01 03:03:51,620 - INFO - [MainThread] UM.Qt.QtApplication.__init__ [98]: Adding QT5 plugin path: C:\Program Files\Ultimaker Cura 5.1.0\PyQt6\plugins
2022-08-01 03:03:51,620 - DEBUG - [MainThread] UM.Application.initialize [161]: Initializing Ultimaker Cura
2022-08-01 03:03:51,620 - DEBUG - [MainThread] UM.Application.initialize [162]: App Version 5.1.0
2022-08-01 03:03:51,620 - DEBUG - [MainThread] UM.Application.initialize [163]: Api Version 8.1.0
2022-08-01 03:03:51,621 - DEBUG - [MainThread] UM.Application.initialize [164]: Build type None
2022-08-01 03:03:51,621 - WARNING - [MainThread] UM.PluginRegistry.addPluginLocation [202]: Plugin location C:\Program Files\lib\uranium must be a folder.
2022-08-01 03:03:51,621 - WARNING - [MainThread] UM.PluginRegistry.addPluginLocation [202]: Plugin location C:\Program Files\lib64\uranium must be a folder.
2022-08-01 03:03:51,621 - WARNING - [MainThread] UM.PluginRegistry.addPluginLocation [202]: Plugin location C:\Program Files\lib32\uranium must be a folder.
2022-08-01 03:03:51,621 - WARNING - [MainThread] UM.PluginRegistry.addPluginLocation [202]: Plugin location C:\Program Files\Ultimaker Cura 5.1.0\plugins must be a folder.
2022-08-01 03:03:51,621 - WARNING - [MainThread] UM.PluginRegistry.addPluginLocation [202]: Plugin location C:\Program Files\Resources\uranium\plugins must be a folder.
2022-08-01 03:03:51,621 - WARNING - [MainThread] UM.PluginRegistry.addPluginLocation [202]: Plugin location C:\Program Files\Resources\cura\plugins must be a folder.
2022-08-01 03:03:51,622 - DEBUG - [MainThread] UM.Resources.__initializeStoragePaths [481]: Initializing storage paths
2022-08-01 03:03:51,622 - DEBUG - [MainThread] UM.Resources.__initializeStoragePaths [491]: Config storage path is C:\Users\breno\AppData\Roaming\cura\5.1
2022-08-01 03:03:51,622 - DEBUG - [MainThread] UM.Resources.__initializeStoragePaths [499]: Data storage path is C:\Users\breno\AppData\Roaming\cura\5.1
2022-08-01 03:03:51,622 - DEBUG - [MainThread] UM.Resources.__initializeStoragePaths [511]: Cache storage path is C:\Users\breno\AppData\Local\cura\5.1\cache
2022-08-01 03:03:51,622 - INFO - [MainThread] UM.PackageManager.__init__ [56]: Found bundled packages JSON file: C:\Program Files\Ultimaker Cura 5.1.0\share\uranium\resources\bundled_packages\uranium.json
2022-08-01 03:03:51,622 - INFO - [MainThread] UM.PackageManager.__init__ [56]: Found bundled packages JSON file: C:\Program Files\Ultimaker Cura 5.1.0\share\cura\resources\bundled_packages\cura.json
2022-08-01 03:03:51,622 - DEBUG - [MainThread] UM.View.GL.OpenGLContext.detectBestOpenGLVersion [124]: Trying OpenGL context 4.1...
2022-08-01 03:03:51,622 - DEBUG - [MainThread] UM.View.GL.OpenGLContext.detectBestOpenGLVersion [132]: Yay, we got at least OpenGL 4.1 core: 4.1 Core profile
2022-08-01 03:03:51,623 - DEBUG - [MainThread] UM.Qt.QtApplication.initialize [191]: Detected most suitable OpenGL context version: 4.1 Core profile
2022-08-01 03:03:51,623 - INFO - [MainThread] UM.Qt.QtApplication.initialize [198]: Initializing job queue ...
2022-08-01 03:03:51,623 - INFO - [MainThread] UM.Qt.QtApplication.initialize [202]: Initializing version upgrade manager ...
2022-08-01 03:03:51,623 - INFO - [MainThread] UM.PackageManager._loadManagementData [174]: Loaded bundled packages data from C:\Program Files\Ultimaker Cura 5.1.0\share\uranium\resources\bundled_packages\uranium.json
2022-08-01 03:03:51,623 - INFO - [MainThread] UM.PackageManager._loadManagementData [174]: Loaded bundled packages data from C:\Program Files\Ultimaker Cura 5.1.0\share\cura\resources\bundled_packages\cura.json
2022-08-01 03:03:51,623 - INFO - [MainThread] UM.PackageManager._loadManagementData [201]: Loaded user packages management file from C:\Users\breno\AppData\Roaming\cura\5.1\packages.json
2022-08-01 03:03:51,623 - INFO - [MainThread] UM.PackageManager._removeAllScheduledPackages [280]: Attempting to remove the following scheduled packages: - 
2022-08-01 03:03:51,623 - INFO - [MainThread] UM.PluginRegistry.initializeBeforePluginsAreLoaded [121]: Loading plugin configuration file 'C:\Users\breno\AppData\Roaming\cura\5.1\plugins.json'
2022-08-01 03:03:51,624 - WARNING - [MainThread] UM.PluginRegistry.addPluginLocation [202]: Plugin location C:\Program Files\lib\cura must be a folder.
2022-08-01 03:03:51,624 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin FileLogger 1.0.1
2022-08-01 03:03:51,640 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin LocalContainerProvider 1.0.1
2022-08-01 03:03:51,659 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin LocalFileOutputDevice 1.0.1
2022-08-01 03:03:51,674 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin CameraTool 1.0.1
2022-08-01 03:03:51,691 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin MirrorTool 1.0.1
2022-08-01 03:03:51,712 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin RotateTool 1.0.1
2022-08-01 03:03:51,731 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin ScaleTool 1.0.1
2022-08-01 03:03:51,744 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin SelectionTool 1.0.1
2022-08-01 03:03:51,762 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin TranslateTool 1.0.1
2022-08-01 03:03:51,798 - INFO - [MainThread] UpdateChecker.UpdateChecker.checkNewVersion [68]: Checking for new version
2022-08-01 03:03:51,800 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin UpdateChecker 1.0.1
2022-08-01 03:03:51,930 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin SimpleView 1.0.1
2022-08-01 03:03:52,012 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin 3MFReader 1.0.1
2022-08-01 03:03:52,035 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin 3MFWriter 1.0.1
2022-08-01 03:03:52,462 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin AMFReader 1.0.0
2022-08-01 03:03:52,497 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin CuraDrive 1.2.0
2022-08-01 03:03:52,582 - INFO - [MainThread] CuraEngineBackend.CuraEngineBackend.__init__ [96]: Found CuraEngine at: C:\Program Files\Ultimaker Cura 5.1.0\CuraEngine.exe
2022-08-01 03:03:52,583 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin CuraEngineBackend 1.0.1
2022-08-01 03:03:52,595 - DEBUG - [MainThread] UM.Backend.Backend._logSocketState [188]: Socket state changed to Listening
2022-08-01 03:03:52,612 - INFO - [MainThread] UM.Backend.Backend.startEngine [91]: Started engine process: C:\Program Files\Ultimaker Cura 5.1.0\CuraEngine.exe
2022-08-01 03:03:52,612 - DEBUG - [MainThread] UM.Backend.Backend._backendLog [111]: [Backend] Calling engine with: ['C:\\Program Files\\Ultimaker Cura 5.1.0\\CuraEngine.exe', 'connect', '127.0.0.1:49674', '']
2022-08-01 03:03:52,626 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin CuraProfileReader 1.0.1
2022-08-01 03:03:52,639 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin CuraProfileWriter 1.0.1
2022-08-01 03:03:52,741 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin DigitalLibrary 1.1.0
2022-08-01 03:03:52,767 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin FirmwareUpdateChecker 1.0.1
2022-08-01 03:03:52,781 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin FirmwareUpdater 1.0.1
2022-08-01 03:03:52,793 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin GCodeGzReader 1.0.1
2022-08-01 03:03:52,806 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin GCodeGzWriter 1.0.1
2022-08-01 03:03:52,820 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin GCodeProfileReader 1.0.1
2022-08-01 03:03:52,850 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin GCodeReader 1.0.1
2022-08-01 03:03:52,866 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin GCodeWriter 1.0.1
2022-08-01 03:03:52,874 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [111]: [Backend] 
2022-08-01 03:03:52,874 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [111]: [Backend] Cura_SteamEngine version main
2022-08-01 03:03:52,874 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [111]: [Backend] Copyright (C) 2022 Ultimaker
2022-08-01 03:03:52,875 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [111]: [Backend] 
2022-08-01 03:03:52,875 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [111]: [Backend] This program is free software: you can redistribute it and/or modify
2022-08-01 03:03:52,875 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [111]: [Backend] it under the terms of the GNU Affero General Public License as published by
2022-08-01 03:03:52,877 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [111]: [Backend] the Free Software Foundation, either version 3 of the License, or
2022-08-01 03:03:52,877 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [111]: [Backend] (at your option) any later version.
2022-08-01 03:03:52,877 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [111]: [Backend] 
2022-08-01 03:03:52,878 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [111]: [Backend] This program is distributed in the hope that it will be useful,
2022-08-01 03:03:52,878 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [111]: [Backend] but WITHOUT ANY WARRANTY; without even the implied warranty of
2022-08-01 03:03:52,878 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [111]: [Backend] MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
2022-08-01 03:03:52,879 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [111]: [Backend] GNU Affero General Public License for more details.
2022-08-01 03:03:52,879 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [111]: [Backend] 
2022-08-01 03:03:52,879 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [111]: [Backend] You should have received a copy of the GNU Affero General Public License
2022-08-01 03:03:52,879 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [111]: [Backend] along with this program.  If not, see <http://www.gnu.org/licenses/>.
2022-08-01 03:03:52,879 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [111]: [Backend] [ERROR] Could not connect to the given address
2022-08-01 03:03:52,886 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin ImageReader 1.0.1
2022-08-01 03:03:52,899 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin LegacyProfileReader 1.0.1
2022-08-01 03:03:52,913 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin MachineSettingsAction 1.0.1
2022-08-01 03:03:53,020 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService.getAccessToken [145]: No auth data to retrieve the access_token from
2022-08-01 03:03:53,023 - DEBUG - [MainThread] cura.UltimakerCloud.UltimakerCloudScope.requestHook [30]: User is not logged in for Cloud API request to https://api.ultimaker.com/cura-packages/v1/cura/v8.1.0/packages/package-updates?installed_packages=UltimakerNylon:1.4.0&installed_packages=GenericToughPLA:1.4.0&installed_packages=FABtotumNylon:1.4.0&installed_packages=PolyPlusPLA:1.0.1&installed_packages=IMADE3DJellyBOXPETG:1.0.1&installed_packages=GenericPVA:1.4.0&installed_packages=GenericCPE:1.4.0&installed_packages=PolyFlexPLA:1.0.1&installed_packages=IMADE3DJellyBOXPLA:1.0.1&installed_packages=UltimakerTPU:1.4.0&installed_packages=GenericGFFPA:1.4.0&installed_packages=FABtotumABS:1.4.0&installed_packages=GenericPP:1.4.0&installed_packages=GenericPC:1.4.0&installed_packages=GenericCFFCPE:1.4.0&installed_packages=DagomaChromatikPLA:1.0.1&installed_packages=GenericCFFPA:1.4.0&installed_packages=GenericABS:1.4.0&installed_packages=Filo3DPLA:1.0.1&installed_packages=FiberlogyHDPLA:1.0.1&installed_packages=GenericCPEPlus:1.4.0&installed_packages=UltimakerPVA:1.4.0&installed_packages=VertexDeltaTPU:1.4.0&installed_packages=GenericHIPS:1.4.0&installed_packages=UltimakerABS:1.4.0&installed_packages=GenericTPU:1.4.0&installed_packages=GenericBAM:1.4.0&installed_packages=PolyMaxPLA:1.0.1&installed_packages=UltimakerBAM:1.4.0&installed_packages=VertexDeltaPET:1.4.0&installed_packages=UltimakerTPLA:1.4.0&installed_packages=UltimakerPC:1.4.0&installed_packages=GenericNylon:1.4.0&installed_packages=VertexDeltaPLA:1.4.0&installed_packages=UltimakerCPEP:1.4.0&installed_packages=VertexDeltaABS:1.4.0&installed_packages=FABtotumPLA:1.4.0&installed_packages=PolyWoodPLA:1.0.1&installed_packages=GenericPETG:1.4.0&installed_packages=UltimakerCPE:1.4.0&installed_packages=UltimakerPLA:1.4.0&installed_packages=FABtotumTPU:1.4.0&installed_packages=GenericGFFCPE:1.4.0&installed_packages=OctofiberPLA:1.0.1&installed_packages=UltimakerPP:1.4.0&installed_packages=GenericPLA:1.4.0&installed_packages=VersionUpgrade460to462:1.0.0&installed_packages=TranslateTool:1.0.1&installed_packages=SelectionTool:1.0.1&installed_packages=CuraProfileReader:1.0.1&installed_packages=ImageReader:1.0.1&installed_packages=3MFWriter:1.0.1&installed_packages=VersionUpgrade41to42:1.0.0&installed_packages=CuraEngineBackend:1.0.1&installed_packages=VersionUpgrade411to412:1.0.0&installed_packages=LegacyProfileReader:1.0.1&installed_packages=UFPWriter:1.0.1&installed_packages=VersionUpgrade43to44:1.0.0&installed_packages=GCodeGzWriter:1.0.1&installed_packages=VersionUpgrade40to41:1.0.1&installed_packages=VersionUpgrade30to31:1.0.1&installed_packages=CustomSupportCylinder:2.6.4&installed_packages=SimulationView:1.0.1&installed_packages=RotateTool:1.0.1&installed_packages=VersionUpgrade462to47:1.0.0&installed_packages=LocalContainerProvider:1.0.1&installed_packages=MirrorTool:1.0.1&installed_packages=VersionUpgrade25to26:1.0.1&installed_packages=OBJReader:1.0.1&installed_packages=X3DReader:1.0.1&installed_packages=OBJWriter:1.0.1&installed_packages=UltimakerMachineActions:1.0.1&installed_packages=FileLogger:1.0.1&installed_packages=VersionUpgrade22to24:1.0.1&installed_packages=MachineSettingsAction:1.0.1&installed_packages=VersionUpgrade21to22:1.0.1&installed_packages=VersionUpgrade48to49:1.0.0&installed_packages=GCodeWriter:1.0.1&installed_packages=XRayView:1.0.1&installed_packages=GCodeReader:1.0.1&installed_packages=GCodeGzReader:1.0.1&installed_packages=SentryLogger:1.0.0&installed_packages=XMLMaterialProfile:1.0.1&installed_packages=OctoPrintPlugin:3.7.2&installed_packages=DigitalLibrary:1.1.0&installed_packages=PreviewStage:1.0.1&installed_packages=UpdateChecker:1.0.1&installed_packages=ConsoleLogger:1.0.1&installed_packages=CuraProfileWriter:1.0.1&installed_packages=SupportEraser:1.0.1&installed_packages=VersionUpgrade49to410:1.0.0&installed_packages=3MFReader:1.0.1&installed_packages=VersionUpgrade45to46:1.0.0&installed_packages=UM3NetworkPrinting:1.0.1&installed_packages=ModelChecker:1.0.1&installed_packages=SolidView:1.0.1&installed_packages=VersionUpgrade33to34:1.0.1&installed_packages=VersionUpgrade26to27:1.0.1&installed_packages=CameraTool:1.0.1&installed_packages=SliceInfoPlugin:1.0.1&installed_packages=VersionUpgrade27to30:1.0.1&installed_packages=UFPReader:1.0.0&installed_packages=GCodeProfileReader:1.0.1&installed_packages=OrientationPlugin:3.7.1&installed_packages=STLWriter:1.0.1&installed_packages=Marketplace:1.0.0&installed_packages=TrimeshReader:1.0.0&installed_packages=VersionUpgrade35to40:1.0.0&installed_packages=FirmwareUpdateChecker:1.0.1&installed_packages=STLReader:1.0.1&installed_packages=PerObjectSettingsTool:1.0.1&installed_packages=ScaleTool:1.0.1&installed_packages=PrepareStage:1.0.1&installed_packages=VersionUpgrade34to35:1.0.1&installed_packages=MeshTools:3.7.0&installed_packages=SimpleView:1.0.1&installed_packages=LocalFileOutputDevice:1.0.1&installed_packages=FirmwareUpdater:1.0.1&installed_packages=PostProcessingPlugin:2.2.1&installed_packages=VersionUpgrade32to33:1.0.1&installed_packages=AMFReader:1.0.0&installed_packages=RemovableDriveOutputDevice:1.0.1&installed_packages=VersionUpgrade42to43:1.0.0&installed_packages=USBPrinting:1.0.2&installed_packages=MonitorStage:1.0.1&installed_packages=VersionUpgrade44to45:1.0.0&installed_packages=VersionUpgrade47to48:1.0.0&installed_packages=CuraDrive:1.2.0
2022-08-01 03:03:53,024 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin Marketplace 1.0.0
2022-08-01 03:03:53,038 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin ModelChecker 1.0.1
2022-08-01 03:03:53,052 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin MonitorStage 1.0.1
2022-08-01 03:03:53,073 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin PerObjectSettingsTool 1.0.1
2022-08-01 03:03:53,087 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin PostProcessingPlugin 2.2.1
2022-08-01 03:03:53,100 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin PrepareStage 1.0.1
2022-08-01 03:03:53,112 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin PreviewStage 1.0.1
2022-08-01 03:03:53,137 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin RemovableDriveOutputDevice 1.0.1
2022-08-01 03:03:53,175 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin SimulationView 1.0.1
2022-08-01 03:03:53,192 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin SliceInfoPlugin 1.0.1
2022-08-01 03:03:53,207 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin SolidView 1.0.1
2022-08-01 03:03:53,221 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin SupportEraser 1.0.1
2022-08-01 03:03:53,234 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin TrimeshReader 1.0.0
2022-08-01 03:03:53,250 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin UFPReader 1.0.0
2022-08-01 03:03:53,265 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin UFPWriter 1.0.1
2022-08-01 03:03:53,282 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin UltimakerMachineActions 1.0.1
2022-08-01 03:03:53,497 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin UM3NetworkPrinting 2.0.0
2022-08-01 03:03:53,549 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin USBPrinting 1.0.2
2022-08-01 03:03:53,578 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade21to22 1.0.1
2022-08-01 03:03:53,592 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade22to24 1.0.1
2022-08-01 03:03:53,607 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade25to26 1.0.1
2022-08-01 03:03:53,621 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade26to27 1.0.1
2022-08-01 03:03:53,635 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade27to30 1.0.1
2022-08-01 03:03:53,648 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade30to31 1.0.1
2022-08-01 03:03:53,662 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade32to33 1.0.1
2022-08-01 03:03:53,674 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade33to34 1.0.1
2022-08-01 03:03:53,687 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade34to35 1.0.1
2022-08-01 03:03:53,700 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade35to40 1.0.0
2022-08-01 03:03:53,714 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade40to41 1.0.1
2022-08-01 03:03:53,728 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade411to412 1.0.0
2022-08-01 03:03:53,741 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade413to50 1.0.0
2022-08-01 03:03:53,755 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade41to42 1.0.0
2022-08-01 03:03:53,767 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade42to43 1.0.0
2022-08-01 03:03:53,781 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade43to44 1.0.0
2022-08-01 03:03:53,795 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade44to45 1.0.0
2022-08-01 03:03:53,808 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade45to46 1.0.0
2022-08-01 03:03:53,822 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade460to462 1.0.0
2022-08-01 03:03:53,836 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade462to47 1.0.0
2022-08-01 03:03:53,850 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade47to48 1.0.0
2022-08-01 03:03:53,865 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade48to49 1.0.0
2022-08-01 03:03:53,879 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin VersionUpgrade49to410 1.0.0
2022-08-01 03:03:53,899 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin X3DReader 1.0.1
2022-08-01 03:03:53,926 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin XmlMaterialProfile 1.0.1
2022-08-01 03:03:53,939 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin XRayView 1.0.1
2022-08-01 03:03:53,960 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin CustomSupportCylinder 2.6.4
2022-08-01 03:03:53,988 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin MeshTools 3.7.0
2022-08-01 03:03:54,075 - DEBUG - [MainThread] OctoPrintPlugin.OctoPrintOutputDevicePlugin.<module> [59]: Using included Zeroconf module version 0.31.0
2022-08-01 03:03:54,096 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin OctoPrintPlugin 3.7.2
2022-08-01 03:03:54,122 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [493]: Loaded plugin OrientationPlugin 3.7.1
2022-08-01 03:03:54,123 - DEBUG - [MainThread] UM.PluginRegistry.loadPlugins [416]: Loading all plugins took 2.63189959526062 seconds
2022-08-01 03:03:54,135 - INFO - [MainThread] UM.VersionUpgradeManager.upgrade [163]: Looking for old configuration files to upgrade.
2022-08-01 03:03:54,185 - INFO - [MainThread] UM.VersionUpgradeManager.upgrade [177]: Checking and performing updates took 0.054049015045166016
2022-08-01 03:03:54,194 - INFO - [MainThread] UM.Qt.QtApplication.startSplashWindowPhase [265]: Completed loading preferences.
2022-08-01 03:03:54,231 - INFO - [MainThread] UM.Qt.QtApplication.startSplashWindowPhase [300]: Created system tray icon.
2022-08-01 03:03:58,082 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.loadAllMetadata [548]: Loading metadata into container registry took 3.8335092067718506 seconds
2022-08-01 03:03:58,094 - DEBUG - [MainThread] cura.Scene.CuraSceneController.setActiveBuildPlate [142]: Select build plate: 0
2022-08-01 03:03:58,101 - INFO - [MainThread] cura.CuraApplication.run [823]: Initializing machine error checker
2022-08-01 03:03:58,307 - WARNING - [MainThread] LocalContainerProvider.LocalContainerProvider._saveCachedDefinition [308]: The definition cache for definition kingroon_kp3s failed to pickle.
2022-08-01 03:03:58,314 - INFO - [MainThread] cura.UI.MachineActionManager.addDefaultMachineActions [74]: Default machine actions added for machine definition [kingroon_kp3s]
2022-08-01 03:03:58,463 - WARNING - [MainThread] LocalContainerProvider.LocalContainerProvider._saveCachedDefinition [308]: The definition cache for definition kingroon_base failed to pickle.
2022-08-01 03:03:58,512 - INFO - [MainThread] cura.Settings.GlobalStack.addExtruder [192]: Extruder[kingroon_base_extruder_0 #2] added to [KP3S] at position [0]
2022-08-01 03:03:58,513 - INFO - [MainThread] FirmwareUpdateChecker.FirmwareUpdateChecker.checkFirmwareVersion [79]: No machine with name Kingroon KP3S in list of firmware to check.
2022-08-01 03:03:58,726 - DEBUG - [MainThread] cura.Machines.ContainerTree.__getitem__ [120]: Adding container tree for kingroon_kp3s took 0.20747637748718262 seconds.
2022-08-01 03:03:58,742 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [206]: Begin loading of script: ChangeAtZ
2022-08-01 03:03:58,747 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [206]: Begin loading of script: ColorMix
2022-08-01 03:03:58,751 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [206]: Begin loading of script: CreateThumbnail
2022-08-01 03:03:58,755 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [206]: Begin loading of script: DisplayFilenameAndLayerOnLCD
2022-08-01 03:03:58,760 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [206]: Begin loading of script: DisplayProgressOnLCD
2022-08-01 03:03:58,764 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [206]: Begin loading of script: FilamentChange
2022-08-01 03:03:58,768 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [206]: Begin loading of script: InsertAtLayerChange
2022-08-01 03:03:58,774 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [206]: Begin loading of script: PauseAtHeight
2022-08-01 03:03:58,778 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [206]: Begin loading of script: RetractContinue
2022-08-01 03:03:58,782 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [206]: Begin loading of script: SearchAndReplace

**Comment by Vandresc** [comment] 2022-08-01 14:49
Hi @brenozicarelli , could you please share a project file so we can reproduce the issue described by you? Thank you! 

You can save it as a project with the configuration that reproduces the issue from the File menu, zip the file and attach it to this ticket, please.

**Comment by brenozicarelli** [comment] 2022-08-01 16:25
[files.zip](https://github.com/Ultimaker/Cura/files/9235622/files.zip)

**Comment by Vandresc** [comment] 2022-08-02 06:28
For me, it successfully slices when loading the project you attached. Also, the log doesn't provide any information regarding the slicing error, this makes it hard to address if we cannot reproduce it.

**Comment by brenozicarelli** [comment] 2022-08-02 16:18
sorry for getting in the way, the last windows update somehow caused several programs to stop working, I reversed the upgrade and CURA is working normally.

**Comment by jellespijker** [comment] 2022-08-02 18:25
Great to hear that it works again. I will close this ticket

**Closed by jellespijker** 2022-08-02 18:25 UTC
Labels: Type: Bug
