### ISSUE TITLE
Cura / CuraEngine heats non-existent bed

### ISSUE THREAD

**Issue by Ocarthon** [Ultimaker/Cura#1275] opened 2016-12-28 14:20 UTC
I wrote a custom configuration for my Vellemann K8400. It worked fine until yesterday when i updated Cura to the current 2.4 Beta. The configuration sets `machine_heated_bed` and `material_bed_temp_prepend` to false, but in the generated GCode, a M140 command is inserted, resulting in my printer to stop due to a heater error.

**Comment by Ghostkeeper** [comment] 2016-12-29 08:34
Duplicate of #1209.

**Comment by fieldOfView** [comment] 2016-12-29 09:20
@Ghostkeeper, either you linked to the wrong issue, or you misread this issue.

@Ocarthon. could you paste your custom configuration into pastebin or into a github gist?

**Comment by Ocarthon** [comment] 2016-12-29 11:45
[k8400.def.json](https://gist.github.com/Ocarthon/a6f26b1b33cbdb27580145aabbd01a7c)
[k8400_extruder_1.def.json](https://gist.github.com/Ocarthon/29ddd6f665a8703610356f9214627434)
[k8400_extruder_2.def.json](https://gist.github.com/Ocarthon/9bc0cece4834c0f2ccd6105d9cdff93b)

At least at some point Cura does read the configuration correct, because i cannot change the bed temperature even if i make that setting visible.

**Comment by Ghostkeeper** [comment] 2016-12-29 19:29
I think I misread it. It's not about disabling M140 via setting the temperature to 0 but about disabling M140 via setting the enabled-setting to false.

**Comment by Ocarthon** [comment] 2016-12-29 19:35
In the meantime i looked a bit in the code and probably found the solution. I create a seperate [issue](https://github.com/Ultimaker/CuraEngine/issues/428) in the CuraEngine repo.

**Comment by BagelOrb** [comment] 2017-07-23 12:16
fixed

**Closed by BagelOrb** 2017-07-23 12:16 UTC
