### ISSUE TITLE
Cura 2.5 beta crashes when i select an object on the platform

### ISSUE THREAD

**Issue by moxrobin** [Ultimaker/Cura#1706] opened 2017-04-20 14:26 UTC
Version: 2.5.0-BETA
Platform: Windows-10-10.0.14393
Qt: 5.7.1
PyQt: 5.7.1

Exception:
TypeError: unable to convert a C++ 'QVector3D' instance to a Python object

**Comment by fieldOfView** [comment] 2017-04-20 15:07
Duplicate of #1591, #1589, #1594, #1607, #1627, and most importantly: fixed in the final release of 2.5.0 which was released yesterday. Please update.

**Closed** 2017-04-24 09:33 UTC
