### ISSUE TITLE
Cannot Click - MacOS M1 Chip

### ISSUE THREAD

**Issue by 3Deee** [Ultimaker/Cura#9226] opened 2021-02-02 18:55 UTC
Mac OS, M1 Processor. 

**Application version**
4.8.0

**Platform**
MacOS, M1 Chip. MacBook Air

**Printer**
N/A --- but its a Reality Ender 3

**Reproduction steps**
I created a new file and added a new model. I multiplied the model and resized them. I sliced and previewed. Then waned to change layout. I got out of preview mode but cannot select on the model. I can see the models, can "select all models" from drop down, but cannot click on the models.  I had to scrap the project and start new. Replicated the issue. Scrapped and started new again. 

**Screenshot(s)**
<img width="1168" alt="Screen Shot 2021-02-02 at 1 54 14 PM" src="https://user-images.githubusercontent.com/70620495/106648339-28286800-655e-11eb-8808-862cfeb7cc63.png">

**Actual results**
Cannot proceed.

**Expected results**
clickable models after getting out of preview mode.

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save Project. For big files you may need to use WeTransfer or similar file sharing sites. G-code files are not project files!)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by fvrmr** [comment] 2021-02-04 11:01
Hi @3Deee thank  you for your bug report. It is a known issue. 
You can read about it more [on our website.](https://support.ultimaker.com/hc/en-us/articles/360018141480-Ultimaker-Cura-won-t-run-on-my-new-Macbook)
I will close this issue because it is a duplicate of #8745

We hope that we have a solution soon.

**Closed by fvrmr** 2021-02-04 11:01 UTC
Labels: Type: Bug
