### ISSUE TITLE
Cura fail to start when enabling "Use a single instance of Cura" under 5.0.0-b1

### ISSUE THREAD

**Issue by mattdw1** [Ultimaker/Cura#12124] opened 2022-05-06 20:08 UTC
### Application Version

5.0.0-b1

### Platform

Windows 10

### Printer

Anycubic Mega X

### Reproduction steps

1. Open any file with Cura default settings.
2. Enable "Use a single instance of Cura" under opening and savings files - general.
3. Attempt to open a second file

### Actual results

Cura doesn't start, and prompts user to reset configuration settings.

### Expected results

Cura starts and adds the second STL file to the same window.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I've also attempted to have "Use single instance" enabled, then completely restart cura (as some settings require). It still prompted the same error.

Traceback (most recent call last):
  File "cura_app.py", line 238, in <module>
  File "cura\CuraApplication.py", line 813, in run
    super().run()
  File "UM\Qt\QtApplication.py", line 366, in run
    super().run()
  File "UM\Application.py", line 256, in run
    self.initialize()
  File "cura\CuraApplication.py", line 323, in initialize
    self.__sendCommandToSingleInstance()
  File "cura\CuraApplication.py", line 339, in __sendCommandToSingleInstance
    if self._single_instance.startClient():
  File "cura\SingleInstance.py", line 32, in startClient
    if single_instance_socket.state() != QLocalSocket.ConnectedState:
AttributeError: type object 'QLocalSocket' has no attribute 'ConnectedState'

**Comment by fvrmr** [comment] 2022-05-11 11:10
Hi @mattdw1 thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11850, so I will close this issue! This is fixed for the 5.0 stable release.

**Closed by fvrmr** 2022-05-11 11:10 UTC
Labels: Type: Bug
