### ISSUE TITLE
Slicing error with negative horizontal expansion: Cura V4.8.0

### ISSUE THREAD

**Issue by swdenman** [Ultimaker/Cura#9225] opened 2021-02-02 16:14 UTC
**Application version**
4.8.0

**Platform**
Windows 10

**Printer**
Creality CR-10S

**Reproduction steps**
1. Open attached object file
2. Set horizontal expansion to -2mm
3. Slice

**Screenshot(s)**
see screenshots below

**Actual results**
The slicing with -2mm horizontal expansion has created strands bridging the valley at the top of the model.

**Expected results**
The slicing with 0mm horizontal expansion shows the result as expected with a clean valley at the top of the model.

**Project file**
[CCR10S_slice-error.zip](https://github.com/Ultimaker/Cura/files/5912701/CCR10S_slice-error.zip)

**Log file**
[slice-error.log](https://github.com/Ultimaker/Cura/files/5912724/slice-error.log)

**Additional information**

**Comment by fvrmr** [comment] 2021-02-02 16:27
Hi @swdenman I can't see your attached files and screenshots. Could you add them?

**Comment by swdenman** [comment] 2021-02-02 16:30
Prepare view:
![image](https://user-images.githubusercontent.com/65888845/106628632-eacdd580-6571-11eb-8f2d-9d110d7aeb07.png)

Preview (Horizontal expansion 0mm)
![image](https://user-images.githubusercontent.com/65888845/106628919-31bbcb00-6572-11eb-9d4a-ef5bd1de8624.png)

Preview (Horizontal expansion -2mm)
![image](https://user-images.githubusercontent.com/65888845/106629065-5adc5b80-6572-11eb-94b2-5dfce77d2ece.png)

**Comment by fvrmr** [comment] 2021-02-04 16:06
Thank you @swdenman, this is expected behaviour. Because it applies only on the horizontal axis. And not on the z axis. You can see that in the shadow of your model, the top is not affected by the horizontal expansion. So that's why you get that on your model.
![image (3)](https://user-images.githubusercontent.com/77000924/106917944-0e775400-6709-11eb-9e45-fe8669668606.png)

Hopes that this makes sense to you. Please let me know if you need more 
But I will close this issue now, because it is not a bug.

**Closed by fvrmr** 2021-02-04 16:06 UTC
Labels: Type: Bug

**Comment by Ghostkeeper** [comment] 2021-02-09 10:52
I've made a small modification based on this bug, since the miter limit was also making lines hang in mid-air. It should be a bit better by default in the next version.

**Comment by swdenman** [comment] 2021-02-09 15:09
Thanks for the update.
