### ISSUE TITLE
1st Layer Line Width Slicing Wrong

### ISSUE THREAD

**Issue by Hacksolot** [Ultimaker/Cura#10351] opened 2021-08-28 23:22 UTC
### Application Version

4.10.0

### Platform

Windows 10

### Printer

Ender 3 (modified for E3 V2)

### Reproduction steps

With a 0.4 nozzle and line width of 0.8, the first layer gcode looks wrong, and prints badly

'Actual results' has the gcode file imported by itself not sliced (Incorrect)
'Expected results' has what the preview after slicing the model it (Correct)

### Actual results

![Incorrect](https://user-images.githubusercontent.com/29818978/131233333-0c717b0b-7ce0-4d48-9a04-ecd895168d3c.JPG)
Actual Gcode output

### Expected results

![Correct](https://user-images.githubusercontent.com/29818978/131233337-bc6b7248-e05d-47e3-88be-d8e6d85d5692.JPG)
Preview after slicing

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Still Printing, 1st layer looks bad, everything else looks good, will upload photos when done.

**Comment by fvrmr** [comment] 2021-08-30 08:52
Hi @Hacksolot thank you for your report. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/10300
The reason why this is happening is explained here: https://github.com/Ultimaker/Cura/issues/10300#issuecomment-905448798

I will close this issue and mark it as a duplicate.

**Closed by fvrmr** 2021-08-30 08:52 UTC
Labels: Type: Bug
