### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by MadRickMaker** [Ultimaker/Cura#13557] opened 2022-10-15 05:15 UTC
### Application Version

5.1.1

### Platform

Windows 11

### Printer

Mingda Magician Pro

### Reproduction steps

Set up STL for slicing
Added Tabs
Clicked Slice
Waited

### Actual results

Slicing Failed notification

### Expected results

A sliced file ready for printing

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Crystal Dragon

**Comment by GregValiant** [comment] 2022-10-15 11:43
Thanks for the report.
The Crystal Dragon model has so many errors in it that it is impossible to slice.  There are numerous reports here about it and I've tried to repair it using several different softwares and it just isn't possible.  It needs a rework.
This is a duplicate of #12546.  I'll close this as it isn't a Cura problem.  You can still respond here or on the other thread.
It's possible that you have a different model than was supplied earlier and if you would post it I'll look, but the one previously submitted gets my award as the worst model ever.

**Closed by GregValiant** 2022-10-15 11:43 UTC
Labels: Status: Duplicate, Status: Under Investigation
