### ISSUE TITLE
Can't login/sign in to Cura

### ISSUE THREAD

**Issue by cartooned** [Ultimaker/Cura#9022] opened 2020-12-26 18:12 UTC
**Application version**
Cura 4.8.0

**Platform**
MacOS 10.15.7

**Printer**
Creality CR-6 SE

**Reproduction steps**
1. Clicked "Sign in" in application

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
Got an error screen
This site can’t be reachedThe connection was reset.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_RESET

**Expected results**
Expected to receive a login screen
I have no parental controls, firewalls, VPN or proxies. I have tried on 3 different networks including a mobile hotspot.

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save Project. For big files you may need to use WeTransfer or similar file sharing sites. G-code files are not project files!)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
Thanks!

**Comment by Ghostkeeper** [comment] 2020-12-27 03:04
The website is up and running and hasn't seen any downtime that I know of recently (since the Google outage a few weeks ago).

ERR_CONNECTION_RESET is most likely a problem local on your computer. You get this if it attempts to make internet connections but something is interrupting the connection.
Here are a few things you can try: https://www.thewindowsclub.com/err_connection_reset-chrome

I'll close this issue since it is not a bug in Cura but a reachability problem of Ultimaker's website. You'll need to contact Ultimaker's support if it persists.

**Closed by Ghostkeeper** 2020-12-27 03:04 UTC
Labels: Type: Bug
