### ISSUE TITLE
Brim only on outside checkbox does not work inn 4.11

### ISSUE THREAD

**Issue by Valiance** [Ultimaker/Cura#10734] opened 2021-11-03 20:47 UTC
### Application Version

4.11

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

I Found error only happens in the Brim setting so far.
I have a model where the bottom face has brim selected, and is putting brim line inside the model where gaps are.
I tried both checking and unchecking Brim only on outside.  Nothing changes.

### Actual results

the preview after slice still has the offending lines inside the gaps on bottom of the print, regardless of Brim only on outside check box being used or not.

### Expected results

I expected the lines inside the gaps to no longer preview/print when I check the box Brim only on outside is checked.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[Desktop.zip](https://github.com/Ultimaker/Cura/files/7470570/Desktop.zip)
[cura.log.1.zip](https://github.com/Ultimaker/Cura/files/7470579/cura.log.1.zip)

**Comment by Ghostkeeper** [comment] 2021-11-03 23:06
This is a duplicate of https://github.com/Ultimaker/Cura/issues/4222 . Sorta.

The brim is expected to remain present on the inside if there are islands on the inside in the hole, which is the case in your print. This is because the inside island should still have a brim towards its outside, otherwise the island will fail just as much as any normal print would without any other part surrounding it.

That means though that what you're asking also wouldn't solve your issue. It would still fill that gap entirely with brim, but just with the outside brim of the part that's on the inside.

What you really seem to need is for some parts to not get a brim, but other parts to get a brim. That would be this issue: https://github.com/Ultimaker/Cura/issues/6882

**Closed by Ghostkeeper** 2021-11-03 23:06 UTC
Labels: Type: Bug
