### ISSUE TITLE
Control part sequence for "one at a time" print

### ISSUE THREAD

**Issue by DeJe63** [Ultimaker/Cura#6321] opened 2019-09-08 08:33 UTC
When printing multiple parts with "one at a time" printing I want to choose in which sequence the parts gets printed. That way I could optimize the count how many parts I can print at once.
As of now Cura chooses a pretty weird sequence how the parts gets printed. Unfortunately exactly the badest for my printer. There is no way to change it by hand.

best regards,
DeJe

**Comment by Ghostkeeper** [comment] 2019-09-09 15:02
Duplicate of https://github.com/Ultimaker/Cura/issues/3070.

Cura already thinks of the most optimal order, *if it knows the shape of your print head*. This is why the order cannot be customised. If the order causes the print head to collide with previously printed objects or allows too much space between prints, most likely the print head has the wrong shape.

**Closed by Ghostkeeper** 2019-09-09 15:02 UTC
Labels: Type: New Feature
