### ISSUE TITLE
When I use 4.10, I can't get the fill shown in Figure 2

### ISSUE THREAD

**Issue by coolgua888** [Ultimaker/Cura#10373] opened 2021-09-01 04:44 UTC
### Application Version

4.10.0

### Platform

win10

### Printer

tronxy xy-2 pro

### Reproduction steps

Model wall thickness is 1mm
When I use 4.8, I get the fill shown in Figure 1,
When I use 4.10, I can't get the fill shown in Figure 2,
4.8 print thin wall filling mode is more stable, 4.10 will be divided into two layers.
When using padding, is it possible to change 4.10 to the same as 4.8?
4.10 also has a bug, sometimes I click on some menus, still stuck, the computer will become very slow.
My computer has a 16G flash memory i5CPU

### Actual results

In 4.10, the walls of the model will be divided into two vertical layers.
4.10 will get stuck

### Expected results

4.9, I can get strong outer walls, but 4.10 removed the horizontal connections, how can I get them back

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![21213](https://user-images.githubusercontent.com/82374291/131613121-b2cc8c16-d7c2-4404-abb6-d65786460d9b.png)
![21421434](https://user-images.githubusercontent.com/82374291/131613153-5592994e-845e-49af-9f25-14bead45ab1e.png)
[_model3apple新.zip](https://github.com/Ultimaker/Cura/files/7088301/_model3apple.zip)

**Comment by fvrmr** [comment] 2021-09-02 14:08
Hi @coolgua888 thank you for your report. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/10199 which you've reported as well. 
@Ghostkeeper explained there that these lines are over extruding, you will also see that in printing so it is not expected behaviour. 

To get stronger walls you can use the setting alternate extra wall https://support.ultimaker.com/hc/en-us/articles/360012512340-Wall-settings

I will close this issue since it is a duplicate. You can continue the thread there if you want.

**Closed by fvrmr** 2021-09-02 14:08 UTC
Labels: Type: Bug
