### ISSUE TITLE
(4.11.0) Multiply selected not working

### ISSUE THREAD

**Issue by damenleeturks** [Ultimaker/Cura#10903] opened 2021-11-22 22:42 UTC
### Application Version

4.11.0

### Platform

MacOS Monterey

### Printer

Creality Ender 3v2

### Reproduction steps

1. Right click on model
2. Select "Multiply selected"
3. A window appears asking for the number of copies. 
4. Select "Okay"

### Actual results

1. A notification dialog box appears at the bottom of the main window stating "Placing objects. Multiplying and placing objects". There is a progress bar in the dialog box.
2. The progress bar in dialog box never completes (nor even starts).
![image](https://user-images.githubusercontent.com/259759/142945379-3ef818ff-6d44-4351-972a-9a42c72988b0.png)

### Expected results

1. The copies of the model are added to the plate. 
2. Models are rearranged to accommodate the new copies. 

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[PLA_0h00m_Expo_Marker_magnetic_holder_(1)_028lh_150pct.3mf.zip](https://github.com/Ultimaker/Cura/files/7584788/PLA_0h00m_Expo_Marker_magnetic_holder_.1._028lh_150pct.3mf.zip
[cura.log](https://github.com/Ultimaker/Cura/files/7584794/cura.log)
)

**Comment by fvrmr** [comment] 2021-11-23 08:15
Hi @damenleeturks thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/10249
And this is fixed in 4.12.1 which you can download from here: https://ultimaker.com/software/ultimaker-cura
I will close this issue since it is a duplicate!

**Closed by fvrmr** 2021-11-23 08:15 UTC
Labels: Type: Bug
