### ISSUE TITLE
Single 0.2mm layer prints fail to slice

### ISSUE THREAD

**Issue by OliverJEvans** [Ultimaker/Cura#10541] opened 2021-09-29 14:46 UTC
### Application Version

4.11.0

### Platform

Mac OSX 11.6 

### Printer

Ender 5 Pro

### Reproduction steps

1. Download bed level test - https://www.thingiverse.com/thing:3404473 - This is a 0.2mm tall print
2. Flatten, scale, and arrange on print bed (if scaling, ensure uniform scaling is disabled to maintain 0.2mm layer height)
3. Click Slice

### Actual results

Slicing failed popup appears when using custom profile - Slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker

When slicing with default 'Standard Quality' profile - 0 minutes print time and no preview

### Expected results

Model is sliced

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

- Works in 4.10
- I don't think this is an issue with the bed level test file as I've git 4 different level test files and they all fail
- Nozzle is 0.4mm
- Layer height on my custom profile is 0.2mm
- Print is 0.2mm tall
- Slicing with standard quality shows a 0 minutes print time (0g, 0.00m)
- Slicing with dynamic quality shows a 0 minutes print time as above.
- Slicing with super quality shows 21 minute print time)
- Its almost as if sits slightly below the build plate meaning any profile with > 0.12mm layer height (the default super quality layer height) will not slice
- I have tried reinstalling

[CE5_400x400_0.2_Bed_Test.3mf.zip](https://github.com/Ultimaker/Cura/files/7252855/CE5_400x400_0.2_Bed_Test.3mf.zip)

**Comment by rburema** [comment] 2021-09-29 18:19
This seems to be another duplicate of #10394 -- Per our policy, we'll keep the original issue open (for further discussion, investigation, reporting, etc,), but will close this (as a) duplicate.

**Closed by rburema** 2021-09-29 18:19 UTC
Labels: Type: Bug, Status: Duplicate
