### ISSUE TITLE
"Mulitply Selected" window opens on another monitor

### ISSUE THREAD

**Issue by DokuKaefer** [Ultimaker/Cura#12998] opened 2022-08-10 12:32 UTC
### Application Version

5.1.0

### Platform

Windows 11 (22H2)

### Printer

Ender 3 S1

### Reproduction steps

1. Select model
2. Rightclick
3. Hit "Mulitply Selected"

### Actual results

I have 4 monitors and the windows do not open then on the same screen as Cura itself.

### Expected results

The window should open on the same screen as Cura if there are multiple screens.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no

**Comment by Vandresc** [comment] 2022-08-11 13:32
Hi @DokuKaefer , thank you for your feedback. We have a ticket on the backlog related to this issue. I will close this ticket as a duplicate of https://github.com/Ultimaker/Cura/issues/12102, where you can follow future progress. Thank you!

**Closed by Vandresc** 2022-08-11 13:32 UTC
Labels: Type: Bug, Status: Triage
