### ISSUE TITLE
Wont Slice

### ISSUE THREAD

**Issue by sfischer1979** [Ultimaker/Cura#14299] opened 2023-01-15 05:23 UTC
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Ender 3 S1

### Reproduction steps

1. Clicked on Slice
2. Slice failed

### Actual results

1. Clicked on Slice
2. Slice failed

### Expected results

1. Clicked on Slice
2. Slice completed
3. gcode saved

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

1. Clicked on Slice
2. Slice failed

**Comment by MariMakes** [comment] 2023-01-20 10:36
Hey @sfischer1979,

Thanks for your report 👍

Is it possible that your printjob is located at 0, 0, 0, and it slices if you move it a little away from the center of the buildplate? 
Then it might be a duplicate of https://github.com/Ultimaker/Cura/issues/13643

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Closed** 2023-02-03 12:06 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage, Slicing Error :collision:
