### ISSUE TITLE
no reset after abort

### ISSUE THREAD

**Issue by teknomancer2008** [Ultimaker/Cura#4333] opened 2018-09-06 17:38 UTC
**Application Version**
ultimaker cura 3.4.1

**Platform**
windows 10 build 1803

**Printer**
prusa i3 (ctc clone)

**Steps to Reproduce**
load a project, attempt to print, press cancel print button on screen.

**Actual Results**
the program stops the print, but all the screen stays greyed out, and nothing is accessible as it is locked out.

**Expected results**
i expect to be able to actually continue as if i had nbot attempted to print in the fiorst place

**Additional Information**
this has caused me to constantly keep re loading the program just because of a single error
![untitled-1](https://user-images.githubusercontent.com/14828929/45174971-195def80-b204-11e8-8bba-5d54d224bf76.jpg)

**Comment by nallath** [comment] 2018-09-06 18:11
I'm a bit confused. What cancel print button do you mean? Your screenshot doesn't seem to show what you are referring to.

**Comment by teknomancer2008** [comment] 2018-09-06 22:05
I was referring to abort print. In this shot, I have actually already pressed it. The screen remains greyed out like this, stopping further access. Not sure why...

**Comment by fieldOfView** [comment] 2018-09-07 06:18
You can switch back to the Prepare screen using the button in the top left corner.

**Comment by alekseisasin** [comment] 2018-09-12 08:53
So far as it is intended behavior I close the issue.

**Closed by alekseisasin** 2018-09-12 08:53 UTC
