### ISSUE TITLE
Cura Slicing Material Viewer

### ISSUE THREAD

**Issue by scott132526** [Ultimaker/Cura#10832] opened 2021-11-15 08:12 UTC
### Is your feature request related to a problem?

Is there, or will there be a future setting in Cura whereby after a Slice has been carried out and you are in the [Preview] screen, when scrolling down the Layers both the time & material parameters change accordingly? If Cura can work out the total time/material, then surely it can work out what layer above will happen. 

Why? Well, if you do not have enough material or printing an item over 750g/1kg and want to change or are having a long print and you wanted to use a 'Post Process' script, you can fine tune at a better point......(unless there already is 😱)

Just curious....have a good day all😄😉

### Describe the solution you'd like

When in [Preview] tab and you scroll up and dien through the layer, tge material and time change accordingly. 

### Describe alternatives you've considered

None

### Affected users and/or printers

Everyone

**Comment by fvrmr** [comment] 2021-11-16 12:13
Hi @scott132526 thank you for your feature request.
I would consider this as a duplicate of https://github.com/Ultimaker/Cura/issues/7683
Only that is more about time is but this would also be the case for material. 
I will close this issue since it is a duplicate. But please continue the thread in the other issue if you want!

**Closed by fvrmr** 2021-11-16 12:13 UTC
Labels: Type: New Feature
