### ISSUE TITLE
Triple Click to Select Complete Value Fails in Move and Scale modes

### ISSUE THREAD

**Issue by gedascher** [Ultimaker/Cura#12131] opened 2022-05-07 12:11 UTC
### Application Version

5.0.0-beta+1

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

1. Open any .stl file
2. Click  on any of the objects that appear
3. Type "T" to go into Move mode
4. Triple click the input area of one of the fields
5. Try and change the value with the keyboard OR Hit the Backspace key to completely remove the value

### Actual results

The value does not change if you try and type a new value in
If you hit the backspace key, the selected object is deleted

### Expected results

I expect the value to be replaced by whatever I am typing
OR I expect the value to be completely deleted and have an empty value ready to fill in

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

IF I select the value to be replaced by clicking in the input area and selecting the value by dragging the mouse, the program works as expected. It is ONLY when I triple click in the input area that the problem occurs.  This happens for both the Move mode and the Scale mode.

**Comment by MariskaMaas** [comment] 2022-05-24 16:41
Hi @gedascher 

Thanks for reporting this. 😄 
I've encountered this as well, and we have created a ticket with the intention to resolve it. 
I'm closing this issue since it seems to be a duplicate of https://github.com/Ultimaker/Cura/discussions/11842#discussioncomment-2653797 
You can track the progress of the issue over in that thread.

**Closed by MariskaMaas** 2022-05-24 16:41 UTC
Labels: Type: Bug
