### ISSUE TITLE
Cannot import multiple stl files at the same time

### ISSUE THREAD

**Issue by Dawn-Of-Justice** [Ultimaker/Cura#16043] opened 2023-07-07 07:36 UTC
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Ender 3 Pro 

### Reproduction steps

We just have to try selecting multiple models to import from the import menu.

### Actual results

only 1 model is begin selected even though tho shift key is pressed

### Expected results

Older version had multiple stl import at the same time.

### Add your .zip and screenshots here ⬇️

![Screenshot 2023-07-07 130532](https://github.com/Ultimaker/Cura/assets/80523850/b75ecf97-884c-46aa-8def-002c63539707)

**Comment by GregValiant** [comment] 2023-07-07 11:53
Thanks for the report.
This report is a duplicate of #16003 .  A workaround is to used File Explorer and select multiple files and drag them to the Cura workspace.
I'll go ahead and close this as the Cura team is aware of the problem.

**Closed by GregValiant** 2023-07-07 11:53 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation
