### ISSUE TITLE
Creating custom material of type ASA shows warning

### ISSUE THREAD

**Issue by damiandudycz** [Ultimaker/Cura#14629] opened 2023-02-21 15:09 UTC
### Application Version

5.2.2

### Platform

macOS

### Printer

Voron 2.4

### Reproduction steps

I created custom material and in Material type entered ASA. Then I selected this material. It shows warning. Doesn't happened if in Material type I enter ABS or PLA.

### Actual results

Cura shows warning sign that says "There are no profiles matching the configuration of this extruder.

### Expected results

This should not display this warning, as ASA is a standard material name.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

<img width="1440" alt="Zrzut ekranu 2023-02-21 o 16 04 59" src="https://user-images.githubusercontent.com/11561511/220382754-a4289a52-c54a-49b3-86d6-1dc7d487fd49.png">

**Comment by MariMakes** [comment] 2023-02-23 12:21
Hey @damiandudycz,

Welcome to the Ultimaker Cura Github 🚀 

I recognize your issue, it's quite common. 
When making a new material it's important that Material Type matches one of the Generic Materials. 
You won't see it anywhere, but Cura needs this material to determine what to base the different layerheight/profiles on.

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/8229
We have a ticket on our backlog with the intent to improve this so it's easier to pick a material and the chance that something goes wrong is smaller. 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/8229
I hope you understand

**Closed by MariMakes** 2023-02-23 12:21 UTC
Labels: Type: Bug, Status: Triage
