### ISSUE TITLE
Won't slide bed calibration pattern

### ISSUE THREAD

**Issue by Jonny5isaliv3** [Ultimaker/Cura#14206] opened 2023-01-04 21:02 UTC
### Application Version

5.2.1

### Platform

Windows 11 Home

### Printer

Ender 3

### Reproduction steps

Load calibration file from Thingiverse

Click Slice

Error cannot slide...

### Actual results

slicing error and asks me to report bug

### Expected results

outputs sliced file

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![bug1](https://user-images.githubusercontent.com/121979546/210649162-8583be9e-795d-47d2-8555-286c224eb578.jpg)
![bug2](https://user-images.githubusercontent.com/121979546/210649175-b0c99552-5228-4dfd-975c-0de485d862f0.jpg)

**Comment by MariMakes** [comment] 2023-01-05 14:57
Hey @Jonny5isaliv3,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

Does it slice if your model is not in the center of the build plate? 
Could it be a duplicate of https://github.com/Ultimaker/Cura/issues/13643 ?

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Closed** 2023-01-20 00:19 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage, Slicing Error :collision:
