### ISSUE TITLE
[4.6.1] Some UI problems with Archlinux KDE

### ISSUE THREAD

**Issue by Titome** [Ultimaker/Cura#8014] opened 2020-07-01 18:54 UTC
**Application version**
4.6.1 AppImage downloaded in the Cura website

**Platform**
ArchLinux, KDE, i7-8700k, GTX1080

**Printer**
Longer3D LK4 Pro

**Reproduction steps**
Open setting

**Screenshot(s)**
![Screenshot_20200701_203734](https://user-images.githubusercontent.com/748679/86279877-0c7d6d80-bbdb-11ea-9bb0-bdf74d7d10fd.png)
![Screenshot_20200701_203937](https://user-images.githubusercontent.com/748679/86279894-156e3f00-bbdb-11ea-8791-d00fad64e048.png)

**Actual results**
Some texts are not visible or croped.

**Expected results**
See texts.

**Project file**
Don't need

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
I see similar issues but not exactly same #7300 #5490 #4826

I try to run from source but it's very painful :(

**Comment by Ghostkeeper** [comment] 2020-07-06 12:31
Duplicate of https://github.com/Ultimaker/Cura/issues/5490.

**Closed by Ghostkeeper** 2020-07-06 12:31 UTC
Labels: Type: Bug

**Comment by Titome** [comment] 2020-07-06 12:47
I belive in #5490 the reporter use black theme in Cura but I'm wrong & MaxVerevkin's solution work for me for white label in white background : `env -u DESKTOP_SESSION -u KDE_FULL_SESSION -u XDG_CURRENT_DESKTOP ~/Downloads/Ultimaker_Cura-4.6.1.AppImage`

![Screenshot_20200706_144538](https://user-images.githubusercontent.com/748679/86594561-888b0300-bf97-11ea-932f-e0617485ebd7.png)

But the text still croped...

![Screenshot_20200706_144604](https://user-images.githubusercontent.com/748679/86594573-8d4fb700-bf97-11ea-84ae-c3fbc83804d1.png)

**Comment by Ghostkeeper** [comment] 2020-07-07 12:29
I also see the wonky text rendering, been there for a long time. It's still in the back of my head to look at one day. It seems to be specific to Linux.
