### ISSUE TITLE
Selected working directory not being maintained.

### ISSUE THREAD

**Issue by shilo91** [Ultimaker/Cura#13984] opened 2022-12-07 02:02 UTC
### Application Version

5.2.1

### Platform

Ubuntu

### Printer

Any

### Reproduction steps

1. Open Cura and load an stl file.
2. No matter what you do - clear the print bed, attempt to add a model or close and re-open Cura the next attempt to open a file starts you off in the default directory. Older versions of Cura kept track of the last working directory for all OSs. Only the latest Windows version of Cura 5.2 has fixed this issue.

### Actual results

User gets annoyed with sloppy work by developers.

### Expected results

Basic operations should work consistently across all platforms.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

None required.

**Comment by MariMakes** [comment] 2022-12-07 13:38
Hey @shilo91,

Thanks for your report 👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12295
We have a ticket on our backlog with the intent to improve this behavior soon. 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12295

**Closed by MariMakes** 2022-12-07 13:38 UTC
Labels: Type: Bug, Status: Triage
