### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by moxrobin** [Ultimaker/Cura#1591] opened 2017-03-27 03:25 UTC
Version: 2.5.0-BETA
Platform: Windows-10-10.0.14393
Qt: 5.7.1
PyQt: 5.7.1

Exception:
TypeError: unable to convert a C++ 'QVector3D' instance to a Python object

**Comment by fieldOfView** [comment] 2017-03-27 07:00
Seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/1566

**Comment by nallath** [comment] 2017-03-27 07:38
It is. Closing this issue

**Closed by nallath** 2017-03-27 07:38 UTC
