### ISSUE TITLE
UI Scaling incorrectly between different resolution monitors

### ISSUE THREAD

**Issue by erstultz1** [Ultimaker/Cura#10309] opened 2021-08-19 16:50 UTC
### Application Version

4.10.0

### Platform

Windows 10

### Printer

Ender 3v2

### Reproduction steps

1. Open Cura
2. Move the application to different display that has a different resolution

### Actual results

All of the application UI is scaled incorrectly. Cura takes on the scale of whatever monitor it starts on and then does not change. 

When moving from lower resolution (1080p) display to 4k display, the UI within the app is super small and hard to read.

When going the other way around, the UI is super big and blocks most of the screen. 

Windows scaling for the displays are normal. All other applications scale their UIs appropriately. 

### Expected results

App should scale appropriately similar to other applications

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Thank you!

**Comment by nallath** [comment] 2021-08-19 17:49
Duplicate of #8966

**Closed by nallath** 2021-08-19 17:49 UTC
Labels: Type: Bug
