### ISSUE TITLE
Pain On Supports

### ISSUE THREAD

**Issue by RetArsonFD** [Ultimaker/Cura#17563] opened 2023-12-08 20:42 UTC
### Is your feature request related to a problem?

I can't stand the "Custom Supports".  Most of the time, in order to get supports where I need them, I need to enable all supports, then individually block out areas I do not need supported.  Way too much work, when other slicers already have paint on supports where you need them.

### Describe the solution you'd like

I'd like to see paint on supports added as a feature.

### Describe alternatives you've considered

Not sure.

### Affected users and/or printers

I hope everyone will benefit in some way.

**Comment by Asterchades** [comment] 2023-12-09 04:45
This has been asked for more than once since PrusaSlicer incorporated them. Honestly I'm not sure what the current state of the request is as there's been no mention on a forum I can access.

Duplicate of #14648.

**Closed by Asterchades** 2023-12-09 04:45 UTC
Labels: Type: New Feature, Status: Triage

**Comment by RetArsonFD** [comment] 2023-12-09 19:32
I figured it probably had already been requested, but hoping that another request MIGHT persuade the programmers a little more to incorporate the feature.  THANKS !!!!!!!
