### ISSUE TITLE
Cura Mirror and make overhangs printable

### ISSUE THREAD

**Issue by dienerbilt** [Ultimaker/Cura#6553] opened 2019-10-19 02:12 UTC
If you mirror and object and make overhangs printable cura ignores infill and sets it to 100 percent as far as i can tell. Basically doubing the print time at best.

**Comment by Ghostkeeper** [comment] 2019-10-21 09:55
Yes, I can reproduce that problem. Very weird!

The problem seems to be that the normal vectors are inside-out then. We should fix that in general (not particular to making overhang printable).

**Comment by dienerbilt** [comment] 2019-10-21 10:11
Yeah it was a wierd part that im making for a customer and through me off
guard also. Great program other wise, its my goto. Thanks for the reply.

**Comment by LipuFei** [comment] 2019-10-24 07:07
Fixed in https://github.com/Ultimaker/Uranium/pull/535

**Closed by LipuFei** 2019-10-24 07:07 UTC
Labels: Category: Engine, Type: Bug
