### ISSUE TITLE
Monotonic top order

### ISSUE THREAD

**Issue by Kamilpl1235** [Ultimaker/Cura#13571] opened 2022-10-16 20:35 UTC
### Application Version

5.2

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

1. Enabled monotonic top/bottom order
2. Slice

### Actual results

 It was making strange travel moves. On previous version it was ok but here its making one line and travel to other side and so on for whole print. It increase print time for over 50% for my prints

### Expected results

It should make one part of top, then next and connect them later, not go line by line like laser engravers

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

None

**Comment by GregValiant** [comment] 2022-10-16 23:44
Thanks for the report.
This is a duplicate of #13565.  I believe that the 5.2 stable release will have the motion the way it was previously.  This new motion wastes a lot of time and causes stringing.
I'll close this as a duplicate and remove the bug label as this is the current "Expected Behavior".  You can follow the progress on the other thread.

**Closed by GregValiant** 2022-10-16 23:44 UTC
Labels: Status: Duplicate, Type: Discussion, Status: Under Investigation
