### ISSUE TITLE
[4.7.1] Layer missing on its height and displayed at 0

### ISSUE THREAD

**Issue by SergioHerreroSanz** [Ultimaker/Cura#8595] opened 2020-10-22 18:04 UTC
**Application version**
4.7.1

**Platform**
Windows 10 version 2004 freshly installed

**Printer**
Ender 3 (non pro)

**Reproduction steps**
1. Create custom supports using cube primitives
2. Slice model normally (1mm nozzle draft profile)

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/59641749/96910235-74640680-149f-11eb-8c8a-677198be619d.png)

**Actual results**
Layer 138 seems missing and appears to have merged with the first layer. Its just a viewport bug, file prints nicely.

**Expected results**
Normal slicing

**Project file**
Fresh Cura 4.7.1 install
.NET framework installing on background
File: v0.62.stl form https://www.thingiverse.com/thing:2875361
![image](https://user-images.githubusercontent.com/59641749/96910985-88f4ce80-14a0-11eb-9934-eefcfa501d4a.png)

**Log file**
Log not found on C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log

**Additional information**
Issue disappeared after re-slicing.

**Comment by Ghostkeeper** [comment] 2020-10-23 15:06
This has nothing to do with custom support. It seems to be a random communication mishap between CuraEngine and the slicer. I've seen it with other prints as well that have no support at all, custom or not.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/7412.

**Closed** 2021-01-11 10:49 UTC
Labels: Status: Duplicate, Type: Bug
