### ISSUE TITLE
[3.4.1] Not necessary long moviment when changing tool

### ISSUE THREAD

**Issue by mtmello2003** [Ultimaker/Cura#4101] opened 2018-07-20 00:03 UTC
Win10 x64

Why even with prime tower disabled, when the tool change, cura make a long hotend moviment to the 0,0, wait a little bit and back to the last position to start to print with the another changed tool?

This is not in toos start/end gcode....

![2018-07-19_2058](https://user-images.githubusercontent.com/15361590/42976269-0fba8238-8b97-11e8-9369-e752955b46cc.png)

**Comment by smartavionics** [comment] 2018-07-20 07:30
This may be the same bug that is fixed in https://github.com/Ultimaker/CuraEngine/pull/776.

**Comment by ChrisTerBeke** [comment] 2018-07-20 10:56
Nth duplicate of this issue, which indeed already has a PR to fix it.

**Closed by ChrisTerBeke** 2018-07-20 10:56 UTC
