### ISSUE TITLE
CURA 4.0 beta - Generated surface finish of Model

### ISSUE THREAD

**Issue by STEVESALF** [Ultimaker/Cura#5295] opened 2019-02-12 13:49 UTC
**Application Version**

**Platform**
W7

**Printer**
UM2

**Steps to Reproduce**
IMPORT STL

**Actual Results**
SCREEN RESOLUTION IS NOT REPRESENTATIVE OF SURFACE OF MODEL - 

**Expected results**
CORRECT GENERATED SURFACE

**Additional Information**
(https://user-images.githubusercontent.com/47564623/52639810-00511d00-2ecd-11e9-9e10-86e42121a322.JPG)
 -->

**Comment by Ghostkeeper** [comment] 2019-02-12 15:14
This is a duplicate of https://github.com/Ultimaker/Cura/issues/3313

**Closed by Ghostkeeper** 2019-02-12 15:14 UTC
