### ISSUE TITLE
 Cura 4.11.0 generates unsupported tree supports in thin air

### ISSUE THREAD

**Issue by MrAnachronist** [Ultimaker/Cura#10466] opened 2021-09-17 02:54 UTC
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Creality Ender 5

### Reproduction steps

Generate tree supports

### Actual results

bad tree supports generated

### Expected results

The supports have elements which are printed in thin air.  Put another way, the tree supports contain elements shaped like stalactites, so that they cannot be printed.

In the attached file, a floating section of support starts at layer 69 and isn't tied in to the main tree support until layer 82.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Here is a screenshot and my project file:

[Tree Support Error.zip](https://github.com/Ultimaker/Cura/files/7182245/Tree.Support.Error.zip)

![Screenshot](https://user-images.githubusercontent.com/47403495/133716716-66406a71-00aa-41e8-ba2e-11973b05963e.png)

**Comment by Ghostkeeper** [comment] 2021-09-22 21:30
Duplicate of https://github.com/Ultimaker/Cura/issues/4342.

**Closed by Ghostkeeper** 2021-09-22 21:30 UTC
Labels: Type: Bug
