### ISSUE TITLE
Horizontal expansion bug

### ISSUE THREAD

**Issue by ruredi87** [Ultimaker/Cura#9778] opened 2021-05-05 22:35 UTC
### Application Version

4.9.0

### Platform

Windows 10

### Printer

Ender 3 v2

### Reproduction steps

I calibrated my horizontal expansion value.then I saw surface was not smooth then checked slicer preview and see this line issues. Also cura 4.8 has this problem

### Actual results

Surface not smooth and has artifacts.

### Expected results

Smooth surface quality.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

https://drive.google.com/drive/folders/1HXm_AmNzeZkQgfWJJrD9bYTrpEBBe9PE?usp=sharing

**Comment by fvrmr** [comment] 2021-05-06 12:46
Hi @ruredi87 thank you for your report. 
This is not a bug but I understand that it is confusing. It is happening on layer 9 and 23.
The reason why the `horizontal hole expansion` is causing this because Cura only sees the closed parts as a hole. So between layer 10 and 22 there are two separate parts and Cura doesn't see them as a hole. So the horizontal hole expansion will only apply on a closed hole, with no gaps. 

Layer 9:
![Screenshot (159)](https://user-images.githubusercontent.com/77000924/117300106-832d6c00-ae79-11eb-9db3-c4c1422d6e2c.png)

Layer 10:
![Screenshot (160)](https://user-images.githubusercontent.com/77000924/117300121-888ab680-ae79-11eb-8c5a-71693fe17f1f.png)

I will close this issue since it is a duplicate of #9185
But please reach out if you have more questions.

**Closed by fvrmr** 2021-05-06 12:46 UTC
Labels: Type: Bug
