### ISSUE TITLE
Loading of files limited to single file rather than a group

### ISSUE THREAD

**Issue by leotilson** [Ultimaker/Cura#15944] opened 2023-06-28 12:58 UTC
### Application Version

5.4.0-beta.1

### Operating System

Windows 10

### Printer

Creality CR-10 Max

### Reproduction steps

Tried to load stl files into Cura

### Actual results

Only able to select one file at a time. The single file selected loads successfully.

### Expected results

Previously, was able to select multiple files at once using a combination of shift/control and mouse click.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

N/A

**Comment by GregValiant** [comment] 2023-06-28 20:30
Thanks for the report.
I had noticed this.  It worked as you described in 5.3.1 but not in the 5.4 beta.  I'll leave the bug label on this but it might be a new "expected behavior".

**Comment by leotilson** [comment] 2023-06-28 23:07
Thank you for the individual response Greg

All of Cura is very much appreciated - a magnificent program.

Regards

Leo

**Comment by MariMakes** [comment] 2023-07-05 15:10
Hey @leotilson,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report and the magnificent compliment 😊👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/15879
We have a ticket on our backlog with the intent to improve this behavior.
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/15879

**Closed by MariMakes** 2023-07-05 15:10 UTC
Labels: Type: Bug, Status: Triage
