### ISSUE TITLE
[4.3B] Support Blocker Scaling Issue

### ISSUE THREAD

**Issue by roseg0ld** [Ultimaker/Cura#6370] opened 2019-09-17 17:52 UTC
**Application version**
At least 4.2 and 4.3 beta

**Platform**
OSX Mojave

**Reproduction steps**
Insert support blocker and scale it non-uniformly along Y or Z

**Actual results**
The blue Z axis scaling handle scales along Y and vice versa 

This is not a major issue but is always inconvenient when trying to arrange support blockers on my Mac.

**Comment by rburema** [comment] 2019-09-18 07:41
Did you rotate the support blocker in relation to the main object? (Or apply any rotation/mirror beforehand?)

**Comment by roseg0ld** [comment] 2019-09-18 15:14
I did not, I rotated the main object 90 deg before adding the support blocker.

**Comment by Ghostkeeper** [comment] 2019-09-19 12:35
Yeah, I see the bug. It happens because the support blocker is set to be transforming along with the object you're placing it on (so that if you rotate that object, the support blocker rotates along). And then it is rotated back such that the initial location is always axis-aligned. If you then scale non-uniformly, the bug of #4136 shows up in the support blocker cube.

As a workaround, you can type the desired size in the text boxes in millimetres.

I'll close this as duplicate of #4136.

**Closed** 2019-12-31 14:13 UTC
Labels: Status: Needs Info, Type: Bug
