### ISSUE TITLE
4.3-PPA Support Blocker doesn't scale correctly along X or Y direction

### ISSUE THREAD

**Issue by kepbrown** [Ultimaker/Cura#6487] opened 2019-10-06 02:49 UTC
**Application version**
4.3-PPA

**Platform**
Ubuntu 19.04

**Printer**
Creality Ender 3

**Reproduction steps**
Open a model with overhangs
Click on support blockers 
Click an overhang 
Click the new support blocker
Click scaling
Unselect Uniform Scaling
Grab the Green (Y) scaling block and pull it.

**Actual results**
 The support blocker expands in the y direction but but also at a downward angle.
Also seems to do the same thing in the X direction just not as noticeable.

**Expected results**
Just expands in the X or Y direction.

**Additional information**
If you manually enter in scaling values it scales correctly. This started happening to me with 4.2.0 PPA

![image](https://user-images.githubusercontent.com/12927417/66263528-06bc3e00-e7a9-11e9-8187-a76518502e6f.png)

**Comment by Ghostkeeper** [comment] 2019-10-07 13:39
Duplicate of https://github.com/Ultimaker/Cura/issues/6370.

**Closed by Ghostkeeper** 2019-10-07 13:39 UTC
Labels: Type: Bug
