### ISSUE TITLE
CURA starts printing supports in mid air

### ISSUE THREAD

**Issue by AkiDuino** [Ultimaker/Cura#7193] opened 2020-02-29 18:48 UTC
hi .. 
as in title

figurine: kim .. change z=200mm, supports: both / no tree

![1-Vollbildaufzeichnung 29 02 2020 193958](https://user-images.githubusercontent.com/61632661/75613312-69352280-5b2c-11ea-8fab-ccbbd7d810ff.jpg)
![1-Vollbildaufzeichnung 29 02 2020 194726](https://user-images.githubusercontent.com/61632661/75613315-6a664f80-5b2c-11ea-8ec7-b0851293761c.jpg)
![2-Vollbildaufzeichnung 29 02 2020 194712](https://user-images.githubusercontent.com/61632661/75613316-6afee600-5b2c-11ea-9f30-90a00c2976a9.jpg)
![3-1-Vollbildaufzeichnung 29 02 2020 193958](https://user-images.githubusercontent.com/61632661/75613318-6b977c80-5b2c-11ea-8ca8-6cf513ef7719.jpg)

**Comment by mahtDFR** [comment] 2020-03-03 13:04
Duplicate of #7191

**Closed by mahtDFR** 2020-03-03 13:04 UTC
Labels: Type: Bug
