### ISSUE TITLE
Cura 15.06.03: Scale all wrong by large objects

### ISSUE THREAD

**Issue by foreachthing** [Ultimaker/Cura#617] opened 2016-01-28 05:06 UTC
If I import a very large model (bigger than the printer's able to print) my model gets scaled. So far so good. But what's not good is, that this scaled version of my model is now 100% to scale (in reality, it should be ~18% to scale)?!
Cura 15.04.4 does it correctly - if scaled, the scale in Cura is adjusted. That way I can still print my model at 2% of the original scale.
And, no, I don't want to scale my model in CAD.

**Comment by Ghostkeeper** [comment] 2016-01-28 09:28
Duplicate of #142. This was fixed in August.

**Closed by Ghostkeeper** 2016-01-28 09:28 UTC
