### ISSUE TITLE
3.4.0 support first layer issue when using brim as plate adhesion

### ISSUE THREAD

**Issue by maxipalay** [Ultimaker/Cura#4046] opened 2018-07-09 19:12 UTC
**Application Version**
3.4.0

**Platform**
macOS

**Printer**
Deltabot

**Steps to Reproduce**
Use brim as plate adhesion and supports touching build plate. Try to slice a hollow cylinder (vertical position) with one end covered (see pictures attached), in such position that support is needed inside the cylinder to hold the covered end of the cylinder (which will print on top).

**Actual Results**
The first layer won't print support inside the cylinder, but the second will. This doesn't let the filament of the support stick correctly to the plate.

**Expected results**
First layer prints support.

**Additional Information**
Please see captures attached.

See how on second layer the support will be printed inside the cylinder but not on the first.

On the outside of the cylinder the support is printed since first layer.

When I say printed I mean what would happen if you were to print this, although it is a slicer issue.

<img width="411" alt="screen shot 2018-07-09 at 4 07 52 pm" src="https://user-images.githubusercontent.com/41023326/42470929-6379ff28-8392-11e8-9b79-92919f1f7197.png">
<img width="814" alt="screen shot 2018-07-09 at 4 08 13 pm" src="https://user-images.githubusercontent.com/41023326/42470930-639da48c-8392-11e8-95d7-c47b08c7a210.png">
<img width="819" alt="screen shot 2018-07-09 at 4 08 26 pm" src="https://user-images.githubusercontent.com/41023326/42470931-63c452b2-8392-11e8-85a5-0a314d4a5f3f.png">

**Comment by ianpaschal** [comment] 2018-07-10 07:20
hmm indeed so it doesn't generate "inside" shapes...

**Comment by diegopradogesto** [comment] 2018-07-10 08:36
This is a duplicate of #3254. This issue is indeed fixed in our current board.

**Closed by diegopradogesto** 2018-07-10 08:36 UTC
