### ISSUE TITLE
Crash when slice.

### ISSUE THREAD

**Issue by rpotalara** [Ultimaker/Cura#13907] opened 2022-11-26 17:27 UTC
### Application Version

5.2.1

### Platform

Windows 8.1

### Printer

Creality Ender 3 S1 Custom.

### Reproduction steps

Download fillenium malcon by aaskedall on Thingiverse: https://www.thingiverse.com/thing:919475 and try to Slice,

### Actual results

Crash

### Expected results

Slice correct.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Any archive has problem to slice.

**Comment by GregValiant** [comment] 2022-11-28 03:15
Thanks for the report.
Bug report #13908 is the same model and it sliced for me on the first try so I'm unable to duplicate the problem.
There have been numerous reports of a bug that causes slicing to fail on certain hi-resolution models. If you move and/or rotate the model on the build plate in Cura you can often fool the bug and the model will slice.
For now I'll mark this as a duplicate of the other slicing errors. Try the workaround and let me know if it works for you.

I'll close this report as there have been a lot of reports of this same problem and it is being worked on and should be fixed in 5.3.  I hope you understand.

**Closed by GregValiant** 2022-11-28 03:15 UTC
Labels: Type: Bug, Status: Duplicate, Slicing Error💥
