### ISSUE TITLE
Tree support generating unsupported material

### ISSUE THREAD

**Issue by Omee84** [Ultimaker/Cura#7249] opened 2020-03-09 10:14 UTC
Tree support generate supports that isnt attached to build plate- it appears first on layer 14. See attached screenshot and project.

**Application version**
Cura 4.5

**Platform**
Windows

**Printer**
Anycubic i3 Mega

**Reproduction steps**
1. See attached project file- preview the layers generated.

**Screenshot(s)**
![Capture](https://user-images.githubusercontent.com/55780086/76203203-5caa7b80-624a-11ea-9a0c-36d4a479362b.PNG)

**Actual results**
Support work first appears on layer 14 in the middle of the area between the mech's feet.

**Expected results**
Supported area should start on layer 1.

**Project file**
[AI3M_Legs.zip](https://github.com/Ultimaker/Cura/files/4305969/AI3M_Legs.zip)

**Comment by Ghostkeeper** [comment] 2020-03-12 15:22
You're reporting a duplicate of https://github.com/Ultimaker/Cura/issues/4342.

This issue is inherent in the way that tree support works: Tree support creates circles ("branches") starting from the overhang that gradually move closer together. If multiple branches, approaching from different sides, come together at the same height, then there was a gap in the middle that gets eradicated by the approach of different branches from different directions. What you're seeing here is one of those gaps that just doesn't go all the way down to the build plate.

In most cases this prints fine because the gaps between the branches are short-lived. It'll repair it in the end. In your case, maybe not.

You can solve this by adding some infill density, particularly with Gradual Support Infill Density. That will make your support connect better to itself.

Your project file doesn't reproduce the problem for me by the way, but I know what you're talking about.

**Closed by Ghostkeeper** 2020-03-12 15:22 UTC
