### ISSUE TITLE
After printing the brim or raft centered, the extruder then displaced and prints the model far from the centered raft. I have  Ultimakers 2+, version _3.3.0. How do I fix it?

### ISSUE THREAD

**Issue by SandraEMyers** [Ultimaker/Cura#7355] opened 2020-03-26 17:08 UTC
**Application version**
version 3.3.0

**Platform**
iMac, Mojave 10.14.5

**Printer**
Ultimaker 2+

**Reproduction steps**
1. open Cura, upload the model I want to print, saved it to the SD card.
2. place the SD card, click print, add glue to the glass.

**Screenshot(s)**
(attached below, please look at next comment) 

**Actual results**
the model is printed outside the centered brim or raft

**Expected results**
I need the print to be accurate as I make use of the entire plate to print

**Project file**

[dommachsamp.gcode.zip](https://github.com/Ultimaker/Cura/files/4388761/dommachsamp.gcode.zip)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.) I looked, can't find the log file...please advice

**Additional information**
I have tried Factory reset. it works, then after a while it happens again.

**Comment by SandraEMyers** [comment] 2020-03-26 17:18
![IMG_5523](https://user-images.githubusercontent.com/62452567/77676063-05472380-6f4b-11ea-8e30-aae6806be3f3.jpg)
![IMG_5524](https://user-images.githubusercontent.com/62452567/77676069-07a97d80-6f4b-11ea-92ef-78c547bd82c2.jpg)
![IMG_5525](https://user-images.githubusercontent.com/62452567/77676078-0aa46e00-6f4b-11ea-852f-276f17fb9f77.jpg)
I have attached pictures of the Cura setting and the final 3D prints

**Comment by SandraEMyers** [comment] 2020-03-28 01:30
I had to stop the printer, suddenly started printing out of bounds towards the edge of the workplate!

**Comment by Ghostkeeper** [comment] 2020-03-30 14:36
The g-code you shared looks correct to me. It's not going outside of the bounds of the printer.
![image](https://user-images.githubusercontent.com/2448634/77924828-79176200-72a4-11ea-83e9-50d413d4bb42.png)

Have you considered that this could be a problem in your printer rather than in Cura's g-code output?

**Comment by Ghostkeeper** [comment] 2020-03-30 14:38
Reading over the bug report template you filled in, I think you intended to report a firmware bug, as you filled in the firmware version _3.3.0.

Perhaps you should look into layer shifts and the ways to prevent them: https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/troubleshooting/layer_shift.md

**Comment by nallath** [comment] 2020-03-30 15:05
I'm fairly sure that this isn't a slicer (or any software) issue. I think you should check if your pulleys (both on the rods and on the motor) are still tight. They are the most likely candidates for causing this.

**Comment by SandraEMyers** [comment] 2020-04-07 18:13
yes I checked every pulley, it seems ok. I'm still watching it just in case.


Best Regards,


SANDRA MYERS

Innovation Lab & Technology Educator

[cid:031609b4-6efe-4c01-95ef-1711c8b6ed85]

________________________________

**Comment by SandraEMyers** [comment] 2020-04-07 18:13
Thanks for your support, stay safe and healthy!


Best Regards,


SANDRA MYERS

Innovation Lab & Technology Educator

[cid:3c06cab7-64f1-4493-8258-b04800b6bee4]

________________________________

**Comment by SandraEMyers** [comment] 2020-04-07 18:16
I have read the article on layer shift, so far stop doing it since the last reset. I truly appreciated your support, I think it helped, Thanks!


Best Regards,


SANDRA MYERS

Innovation Lab & Technology Educator

[cid:336eb2c8-9673-462d-a641-7a11c7020e5f]

________________________________

**Comment by SandraEMyers** [comment] 2020-04-07 18:18
Ghostkeeper also concurred. I did check the pulleys, they seemed ok. It hasn't done it since the last reset. Thanks so very much for the support!


Best Regards,


SANDRA MYERS

Innovation Lab & Technology Educator

[cid:05f53c50-11f9-4767-b5e1-5e2bee5d25f1]

________________________________

**Comment by Ghostkeeper** [comment] 2020-04-09 14:45
Glad to hear you found the issue. We'll close this then since it's not a bug in the slicer but more a problem in the hardware and the settings.

**Closed by Ghostkeeper** 2020-04-09 14:45 UTC
Labels: Status: Needs Info
