### ISSUE TITLE
cura 2.3.1 inputs M109 S0 when setting temp to 0

### ISSUE THREAD

**Issue by Harakan** [Ultimaker/Cura#1348] opened 2017-01-13 23:30 UTC
in old cura, if you set your temps to 0 then the gcode generated would not have any gcode in it relating to setting temps, so you could set it yourself in another fashion.

in cura 2.3.1 if you set the nozzle temp to 0 it actually imputs M109 S0 turning off the heater after your print starts.

yet if you set your bed to 0 it does not input any gcode setting your bed to 0 and leaves it open like it should.

**Comment by Ghostkeeper** [comment] 2017-01-22 20:02
Duplicate of #1209.

**Closed by Ghostkeeper** 2017-01-22 20:02 UTC
