### ISSUE TITLE
Can not disconnect the printer?

### ISSUE THREAD

**Issue by sim31r** [Ultimaker/Cura#2639] opened 2017-10-19 22:22 UTC
Maybe I do not see the button (close printer). I can not disable the active printer. Only by closing the program the printer becomes free (rather the port like as COM10 ...). This is necessary to run another program that will work with the printer.

**Comment by Ghostkeeper** [comment] 2017-10-30 22:35
Bonus points for having an auto-generated avatar in the shape of an ethernet port.

But still, this is a duplicate of https://github.com/Ultimaker/Cura/issues/2135.

**Closed by Ghostkeeper** 2017-10-30 22:35 UTC
