### ISSUE TITLE
Cura [4.0.0] Mac Printer settings disappear

### ISSUE THREAD

**Issue by masc2279** [Ultimaker/Cura#5249] opened 2019-01-30 18:15 UTC
Printer Settings keep disappearing after a few uses. To change nozzle size you must delete printer and re install to get the dialog where you can change your settings.

Working Screen Image ....
<img width="187" alt="screen shot 2019-01-30 at 11 08 44 am" src="https://user-images.githubusercontent.com/1273722/52002639-c79e5600-247f-11e9-95f3-ccbe0b6ff9a5.png">

When it fails to work screen image .....
<img width="187" alt="screen shot 2019-01-30 at 11 09 00 am" src="https://user-images.githubusercontent.com/1273722/52002659-cf5dfa80-247f-11e9-86a5-5d3566eceb71.png">

This is not project specific 

Thank you for using Cura!
-->

**Application Version**
[4.0.0]

**Platform**
MAC

**Printer**
Ender 3

**Steps to Reproduce**
Install printer ... use cura as you  normally would quit  and start slice a few project and at some  point the settings are no longer accessible

**Actual Results**
Cannot change any printer settings like nozzle ...

**Expected results**
I should  be able to  change nozzle sizes without having to un install printer and re install.

**Comment by nallath** [comment] 2019-01-31 16:40
I think this issue has already been fixed by us, but in the meantime (as a work around) you can just change the line width instead of changing the nozzle size.

**Comment by masc2279** [comment] 2019-01-31 17:37
its still in the current public beta so not sure what you mean you all fixed it ... unless its on a non  released version

**Comment by nallath** [comment] 2019-01-31 19:03
The current publicly released beta is from a while ago, so there are quite a few changes & fixes that have not been released yet. 
I've been unable to reproduce it running that version, but it could always be that there is something system specific that's causing the issue.

**Closed** 2020-11-26 13:07 UTC
