### ISSUE TITLE
Fill gaps between walls uneven on curved surfaces

### ISSUE THREAD

**Issue by alexeyzel** [Ultimaker/Cura#8856] opened 2020-11-29 22:42 UTC
**Application version**
4.8.0, 4.6.2 

**Platform**
Windows 10 x64, GeForce 1050Ti

**Printer**
Flsun Q5

**Reproduction steps**
1. Create model with 0.98 mm rounded walls, open it in Cura
2. Enable "Fill gaps between walls" settings, set it to "everywhere"
3. Slice it with 0.4mm layer width
4. Check "preview" section

**Screenshot(s)**
Some layers have faulty infill like this:
![image](https://user-images.githubusercontent.com/50808386/100555431-1c8d9c00-32a4-11eb-9eb4-969a735d0a9b.png)
And some are normal:
![image](https://user-images.githubusercontent.com/50808386/100555425-0f70ad00-32a4-11eb-9870-a994b59b4bc8.png)

**Actual results**
Some layers have uneven fill between the walls on curved surfaces and some are normal. This affects print quality.

**Expected results**
Consistent curved infill between walls on all layers.

**Project file**
[project.zip](https://github.com/Ultimaker/Cura/files/5612967/project.zip)

**Log file**
Will attach if needed.

**Additional information**
I had this issue in older 4.6.2 version.

**Comment by Ghostkeeper** [comment] 2020-12-01 15:02
Duplicate of https://github.com/Ultimaker/Cura/issues/4685 .

This issue has improved significantly since that issue was reported, but it still exists in certain orientations of thin walls. Since your curve has all orientations in one, it'll have this problem regularly.

It is expected to be fixed by Ultimaker/CuraEngine#1210.

**Closed by Ghostkeeper** 2020-12-01 15:03 UTC
Labels: Type: Bug
