### ISSUE TITLE
Cura 4.5 Can't change nozzle size...

### ISSUE THREAD

**Issue by DangerD256** [Ultimaker/Cura#7377] opened 2020-03-31 14:51 UTC
Can't change nozzle size, i can change everything except it...
https://youtu.be/WnUBKiiRJLI

Log:
[cura.zip](https://github.com/Ultimaker/Cura/files/4409887/cura.zip)

**Comment by fieldOfView** [comment] 2020-03-31 15:20
Try entering the number with a comma instead of a dot.

Duplicate of https://github.com/Ultimaker/Cura/issues/6546

**Comment by rburema** [comment] 2020-03-31 17:05
Closing this duplicate in favour of #6546 -- please continue any discussion under that issue.

**Closed by rburema** 2020-03-31 17:05 UTC
Labels: Status: Duplicate, Type: Bug
