### ISSUE TITLE
does not open a file browser window, also popup  windows have no close button

### ISSUE THREAD

**Issue by dubiouser** [Ultimaker/Cura#12371] opened 2022-05-27 14:54 UTC
### Application Version

5.0.0

### Platform

Ubuntu 20.04.4 LTS / CYGWIN_NT-10.0-19044

### Printer

Anet A8

### Reproduction steps

I am running cura 5.0.0 on my ubuntu system and the display back to my windows workstation, this works fine with previous releases.

when I   select File -> OpenFile(s)...  I get no file browser popup 

when a popup window does open eg preferences->Configure Cura , Help->About...  etc. there is no close button, and i have to kill the window from the task bar 

### Actual results

nothing 

### Expected results

file browser opens   

ssh ssh 

or popup opens with window control buttons 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8787495/cura.log)
[stderr.log](https://github.com/Ultimaker/Cura/files/8787499/stderr.log)

**Comment by nallath** [comment] 2022-06-10 11:13
Duplicate of #12266

**Closed by nallath** 2022-06-10 11:13 UTC
Labels: Type: Bug
