### ISSUE TITLE
[4.1] UI Totaly broken

### ISSUE THREAD

**Issue by asyade** [Ultimaker/Cura#6050] opened 2019-07-23 12:03 UTC
**Application version**
4.1.0

**Platform**
![System prop](https://i.ibb.co/9w7CmQW/Capture.png)
-  GPU: *RTX2060* with NVIDIA driver version *25.21.14.1971*

**Printer**
A custom PRUSA i3 is used but only the GUI is affected, the printer control work fine.

**Reproduction steps**
- Install *Cura 4.1*
- Run *Cura*
- Its working fine
  -  At this point you can close/launch cura it's working as expected
- Restart the computer
- Open cura
- The GUI dosent appear propely
  - Try using "Run with integrated graphic [...]" and "Run with high performance graphic [...]", same result
  - Try as administrator, compatibilites mode [...], same result
  - Uninstall Cura and restart reproduction steps will fix the probleme until next reboot

**Actual results**
Cura is working fine (printer can be controlled, i can perform print but preview is not working) but the gui look like totaly broken
![GUI with a bench model loaded and printing](https://i.ibb.co/qywbg7D/Capture.png)

**Expected results**
The GUI should appear normaly

**Additional information**
The windows setup is clean (only cura and autodesk inentor are installed) but windows isn't activated.

**Comment by Ghostkeeper** [comment] 2019-07-24 07:04
Duplicate of https://github.com/Ultimaker/Cura/issues/6006.

It seems that a recent Windows update broke stuff here, and you'd need to reinstall your graphics drivers.

**Closed** 2019-07-24 07:04 UTC
Labels: Type: Bug
