### ISSUE TITLE
Tree supports hanging in mid-air

### ISSUE THREAD

**Issue by KamodaP** [Ultimaker/Cura#12481] opened 2022-06-09 07:44 UTC
### Application Version

5.0.0

### Platform

Windows 11

### Printer

Anycubic Vyper

### Reproduction steps

1. Import model
2. Set support to tree, 50% overhang, buildplate only

### Actual results

![image](https://user-images.githubusercontent.com/5961927/172791582-b73286b1-9c3c-489e-a3af-140a4c35b9d9.png)
![image](https://user-images.githubusercontent.com/5961927/172791719-4cfb49ba-7de8-4c5f-87bf-38c34b1628c1.png)
support hangs in mid-ai

### Expected results

Supports should be supported

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[bugshow_save.zip](https://github.com/Ultimaker/Cura/files/8868046/bugshow_save.zip)

**Comment by DerGenaue** [comment] 2022-06-10 02:06
Probably a duplicate of #8218.
If this is a critical issue to you, you can use [this Cura fork with improved Tree Supports](https://github.com/ThomasRahm/CuraEngine) in the meantime

**Comment by Vandresc** [comment] 2022-10-14 11:25
Though tree support still has some issues, this specific case has been fixed for the 5.2 stable release. 
![tree s](https://user-images.githubusercontent.com/77665581/195835712-95086506-78f5-48eb-a706-790a79948291.PNG)

**Closed by Vandresc** 2022-10-14 11:25 UTC
Labels: Type: Bug, Status:  On Backlog
