### ISSUE TITLE
Allow user to customize the Abort Print command

### ISSUE THREAD

**Issue by conyg** [Ultimaker/Cura#9370] opened 2021-03-05 06:17 UTC
### Is your feature request related to a problem?

Sometimes, while using the "Print via USB" option I need to Cancel the print.
I'm always frustrated when I want to drag the bed toward me and the bed is stuck.
This is happening after I press Abort Print in Cura but is not happening when I abort printing from the printer directly.

### Describe the solution you'd like

The solution I see is to add in the settings, a script section for Abort Print G-code.

### Describe alternatives you've considered

The printer setting sections has a End G-code sections that contains a list of commands to be executed at the end of the print. In case of my printer (Artillery SW-X1) that script contains also a M84 (disable motors) command.
A good alternative is to execute the End G-code script after the Abort Print command.

Another solution would to include the M84 (disable motors) command to the existing Abort Printing command (that is not editable by user). It is possible though, that some users (with other printers) might not like that.

### Affected users and/or printers

I think this would benefit everyone trying to print via USB from Cura.

**Comment by fvrmr** [comment] 2021-03-05 11:06
Hi @conyg thank you for your feature request. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/7562
You can read about this more in that thread. Feel free to ask your questions or comments there. 
And that's why I will close this issue, hope you understand.

**Closed by fvrmr** 2021-03-05 11:06 UTC
Labels: Type: New Feature
