### ISSUE TITLE
Raft for certain parts and not all build plate

### ISSUE THREAD

**Issue by neofuture** [Ultimaker/Cura#10839] opened 2021-11-16 00:36 UTC
### Is your feature request related to a problem?

No problem but it would be nice to be able to raft some tiny parts on a build plate and leave the raft off for others

User Story

I have some small (2") drink number key rings im printing in a rainbow PLA, one of the parts is very small (the straw) and it would be ideal to print these on a raft while printing the rest of the items on the build plate. 

### Describe the solution you'd like

User Story

I have some small (2") drink number key rings im printing in a rainbow PLA, one of the parts is very small (the straw) and it would be ideal to print these on a raft while printing the rest of the items on the build plate. 

### Describe alternatives you've considered

printing twice but the two models then have different colours as using rainbow filament

### Affected users and/or printers

unsure

**Comment by fvrmr** [comment] 2021-11-16 15:02
Hi @neofuture thank you for your feature request.
I would consider this as a duplicate of https://github.com/Ultimaker/Cura/issues/6882 this is mostly focused on the brim. But this is also the same as the raft, since it is both adhesion. 
I will close this issue and mark it as a duplicate.

**Closed by fvrmr** 2021-11-16 15:02 UTC
Labels: Type: New Feature
