### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by feesta** [Ultimaker/Cura#13962] opened 2022-12-03 22:57 UTC
### Application Version

5.2.1

### Platform

MacOS

### Printer

Ender 3

### Reproduction steps

1. Load model
2. Click "Slice"

### Actual results

Error pops up that slicing failed and recommended to file a bug.

### Expected results

Expected to slice or to describe the problem so it can be addressed.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

cura.log
[cura.log](https://github.com/Ultimaker/Cura/files/10147501/cura.log)
[CE3PRO_otis7-2-Otis.3mf.zip](https://github.com/Ultimaker/Cura/files/10147503/CE3PRO_otis7-2-Otis.3mf.zip)

**Comment by feesta** [comment] 2022-12-03 23:05
Running "Fix Model Normals" from Mesh Tools made the model slicable. Maybe the issue should be caught and prompt to fix the model. Even better would be to give a shortcut to the fix the normals or at least state that that's a recommended step to troubleshoot.

**Comment by MariMakes** [comment] 2022-12-06 12:45
Hey @feesta,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

Your mesh indeed seems faulty. I'm getting this notification from the Meshtools Plugin.
![image](https://user-images.githubusercontent.com/40423138/205915697-dc23894a-804e-442d-a57b-6eb58546f8ef.png)

I've also noticed that the model slices without making model fixes if you move the model slightly away from the center of the buildplate. 
![image](https://user-images.githubusercontent.com/40423138/205916089-66dbf96f-f468-49a0-8a85-4c72e8915498.png)

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13643
We have a ticket on our backlog with the intent to improve this behavior.
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/13643

Thanks again for your report 😊

**Closed by MariMakes** 2022-12-06 12:45 UTC
Labels: Type: Bug, Status: Triage
