### ISSUE TITLE
Add flow to material-specific print settings

### ISSUE THREAD

**Issue by MarkusvonStaden** [Ultimaker/Cura#11587] opened 2022-03-02 20:03 UTC
### Is your feature request related to a problem?

I'm currently setting up my materials in cura. 
But I can't set the flow for each material.

### Describe the solution you'd like

"Just" add the option, to set the flow from the material setting

### Describe alternatives you've considered

-

### Affected users and/or printers

Those, who use the materials function in cura

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/41544048/156440573-d543f2a9-f3fe-46cf-9557-930686b01c56.png)

**Comment by nallath** [comment] 2022-03-03 09:21
You can do that with the following plugin: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MaterialSettingsPlugin

This is also a duplicate of #11575

**Closed by nallath** 2022-03-03 09:21 UTC
Labels: Type: New Feature
