### ISSUE TITLE
Cura 5.0.0 on chromebook in a debian container

### ISSUE THREAD

**Issue by arararar** [Ultimaker/Cura#12308] opened 2022-05-22 14:05 UTC
### Application Version

5.0.0

### Platform

Chrome OS

### Printer

Ender 3

### Reproduction steps

Open Cura. Very Slow.
Open .stl - even slower.

### Actual results

After that, i cant select or do anything further, cura is changing with every input click/keypress between two submenues and presenting them in gui.
unusable.

### Expected results

should work ;)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8749585/cura.log)

**Comment by MariskaMaas** [comment] 2022-06-03 08:21
Hi @arararar 

We don't support Chrome OS and unfortunately we are not planning developing Cura for Chromebooks any time soon.
However some people have made it work: https://community.ultimaker.com/topic/27382-cura-on-chromebook-how/#comment-289389

But we don't officially support this since we don't test this ourselves.
I will close this issue since it's a duplicate of https://github.com/Ultimaker/Cura/issues/11038, I hope you understand.

**Closed by MariskaMaas** 2022-06-03 08:21 UTC
Labels: Type: Bug
