### ISSUE TITLE
Save to Removable Drive truncates filename at last period in project name

### ISSUE THREAD

**Issue by GIJ0E** [Ultimaker/Cura#8123] opened 2020-07-29 17:02 UTC
**Application version**
4.6.2

**Platform**
Windows 10 Version 1903 Build 18362.959
Intel HD Graphics 520

**Printer**
Custom - MeCreator2

**Problem**
When saving to removable disk, the filename is truncated if a period exists in the project name. If multiple periods exist, it truncates at the last period. 
For example, a project name of TestPartV1.2.3.4.5.6 would be truncated to TestPartV1.2.3.4.5.gcode and TestPartV2.1 would be truncated to TestPartV2.gcode 

It does not do this using Save to File button, only the Save to Removable Drive button.

I also believe it doesn't ask to overwrite an existing file when saving to Removable Drive.

**Comment by rburema** [comment] 2020-07-30 07:44
I can confirm this, I'll put it up for discussion. _Probably_ an easy fix.

> I also believe it doesn't ask to overwrite an existing file when saving to Removable Drive.

This last one is intended, as the 'save to removable drive' is supposed to be a quick option. If you desire to be guarded against overwrites, then use the normal save to file function, but then put it on your removable drive.

**Comment by rburema** [comment] 2020-07-30 11:24
Pushed a fix, will probably be in 4.7

**Closed** 2020-07-30 11:24 UTC
Labels: Category: Cura, Type: Bug

**Comment by GIJ0E** [comment] 2020-07-30 13:05
Thank you very much!
