### ISSUE TITLE
Start Gcode / End Gcode text not readable. [4.6.1]

### ISSUE THREAD

**Issue by bteamfox** [Ultimaker/Cura#8078] opened 2020-07-17 14:12 UTC
**Application version**
4.6.1

**Platform**
Acer Extensa 5235 Laptop
CPU: Pentium T4500 (2) @ 2.300GHz
GPU: Intel Mobile 4 Series Chipset
Resolution: 1366x768
Linux Mint 20 XFce

**Printer**
Ender-3

**Reproduction steps**
View Start/End Gcode screen

**Screenshot(s)**
![Screenshot_2020-07-17_14-38-41](https://user-images.githubusercontent.com/47488365/87794103-0d023f00-c83e-11ea-8842-40b721310aa6.png)

**Actual results**
Prints Correctly.

**Expected results**
Prints Correctly.

**Project file**
N/A

**Log file**
Sorry I don't understand GitHub

**Additional information**
Cut and past text from the Start or End Gcode windows, past into a text editor, the text then displays fine.
Linux Mint was a clean install from the Linux Mint XFce .ISO 
I selected UK for Region and keyboard as normal.
I selected Dark Mode.
I also closed Cura 4.6.1 then selected Light Mode. Launched Cura 4.6.1 with same fault.

**Comment by Ghostkeeper** [comment] 2020-07-21 11:32
Duplicate of https://github.com/Ultimaker/Cura/issues/7836. There is some discussion about a workaround there.

**Closed by Ghostkeeper** 2020-07-21 11:32 UTC
Labels: Type: Bug
