### ISSUE TITLE
Cura 2.5 on Ultimaker 3 "Print Finished" but no print 

### ISSUE THREAD

**Issue by eghterafi** [Ultimaker/Cura#1654] opened 2017-04-05 21:04 UTC
I installed Cura 2.5 and started working with it, but after a day anything i want to print it says "Print Finished. Carefully remove the print..... on my ulimaker 3. 
not i am printing on the wireless network. 
I tried to add new printer and try and had the same problem, the only way is to uninstall Cura and install it again.

**Comment by nallath** [comment] 2017-04-06 07:28
Check your printer. It should display the same message. As long as it's there, the machine reports that it' s still printing.

**Comment by Ghostkeeper** [comment] 2017-04-06 11:55
Hold up. I think Nallath read this issue wrongly.

Eghterafi reports that whenever he starts printing, the printer says that it's done printing without printing anything.

**Comment by Ghostkeeper** [comment] 2017-04-06 11:59
It could be related to the wifi bug we found in the last few days. Or perhaps the user set some setting weirdly, like layer height to 20m, which causes the g-code to be empty.

Could you save a print that has this problem as a project so that we can reproduce this issue? It's under File -> Save Project.

**Comment by eghterafi** [comment] 2017-04-06 16:48
I checked all the settings, Ghostkeeper is correct, the message is on the printer, so i press print on network, and then immediately it says print finished. 
it does not happen on cure 2.4

**Comment by Ghostkeeper** [comment] 2017-04-07 08:27
It doesn't happen for me. I'm not reproducing it here :confused:

**Comment by Icemixx** [comment] 2017-04-21 14:49
Same here. Using LAN. But I found a workaround. It only does the error, if I load a file with double clicking. I clear the build plate, load file using open file menu, and then it works

**Comment by fieldOfView** [comment] 2017-04-21 16:12
Then the problem is probably the an empty Jobname (in the lower right of the viewport). Fill in a name there before printing and it should work.

For the devs: See https://github.com/Ultimaker/Cura/issues/1703

**Comment by Icemixx** [comment] 2017-04-21 16:23
you are perfectly right! I can't start a print now because i already have an active one, but if I load the file, there is no jobname

**Comment by Ghostkeeper** [comment] 2017-04-25 08:22
I'll close this one as a duplicate of #1703 then.

**Closed by Ghostkeeper** 2017-04-25 08:22 UTC
