### ISSUE TITLE
Cura 5 beta Auto Closure

### ISSUE THREAD

**Issue by Babarakus** [Ultimaker/Cura#11928] opened 2022-04-24 05:53 UTC
### Application Version

5

### Platform

Windows 11

### Printer

Ender 3

### Reproduction steps

Clicked on page and just closed mid print via USB

### Actual results

above

### Expected results

expect it not to close app mid print

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Fix bug pls.

**Comment by fieldOfView** [comment] 2022-04-24 06:45
Provide logs pls.

We can't really know what happened without further information. And if we don't know what happened, we can't fix it so it won't happen again.

**Comment by Babarakus** [comment] 2022-04-24 07:31
Hey

Where aboits can I find the logs. I've uninstalled 5 and usint 4.13 again cos it's stabke and problem free. Will the 5 logs still be under the Cura install folder. 

Regards

**Comment by MLocke13** [comment] 2022-04-24 17:02
Hey, I am having the exact same issue.
I attached my .Log
[cura.log](https://github.com/Ultimaker/Cura/files/8550128/cura.log)

**Comment by fvrmr** [comment] 2022-04-25 16:30
Hi @Babarakus thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11896, so I will close this issue.

**Closed by fvrmr** 2022-04-25 16:30 UTC
Labels: Type: Bug
