### ISSUE TITLE
Weird shape being generated by Cura 5

### ISSUE THREAD

**Issue by luizbgomide** [Ultimaker/Cura#12780] opened 2022-07-17 13:08 UTC
### Application Version

5.0.0 (also happens on beta 5.1.0)

### Platform

Windows 10

### Printer

Two Trees Bluer

### Reproduction steps

Just slice the attached project.

### Actual results

There is a weird loop instead of a flat top. The loop position and format changes depending on orientation and position on the table.
![image](https://user-images.githubusercontent.com/18707781/179399720-c47316cf-592e-4033-a4a8-091b298379a7.png)

### Expected results

Smooth top (that gcode was sliced in Cura 4.x).
![image](https://user-images.githubusercontent.com/18707781/179399790-62383e3f-36c5-4eb3-9a44-e9fc447147f6.png)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[FilamentClipV2.zip](https://github.com/Ultimaker/Cura/files/9127687/FilamentClipV2.zip)

**Comment by GregValiant** [comment] 2022-07-17 14:12
I think this is a duplicate report but I'm unable to find the previous one.  @Ghostkeeper may have information on this behavior.

**Comment by Ghostkeeper** [comment] 2022-07-18 12:44
Yes, it's a duplicate of https://github.com/Ultimaker/Cura/issues/12425.

**Closed by Ghostkeeper** 2022-07-18 12:44 UTC
Labels: Type: Bug, Status: Under Investigation
