### ISSUE TITLE
[4.1] Adaptive Layer Varation step size resets to 0 disabling second extruder and it prevents slicing

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#5890] opened 2019-06-12 20:28 UTC
**Application Version**
4.1

**Platform**
Win10 x64

**Printer**
Dual extruder custom printer

**Actual Results**
When disabling the second extruder and trying to slice, it gives an error because the Variation step size defaults to 0, and I have to set it manually to 0.04mm each time.

**Expected results**
Why the heck does it change that value? It shouldn't.

**Comment by Ghostkeeper** [comment] 2019-06-13 08:45
For me it defaults to 0.01mm and slices fine then. My reproduction steps were:

1. Add Custom FFF printer.
2. Set number of extruders to 2.
3. Disable the second extruder.
4. Load a cube. Let it slice.

When I enable the Adaptive Layer Height checkbox it says that the setting is 0.01mm (and still slices fine). Here is a project file: [CFFFP_cube.zip](https://github.com/Ultimaker/Cura/files/3284991/CFFFP_cube.zip)

**Comment by Liger0** [comment] 2019-06-13 11:57
I don't have the adaptive layer height and automatic layer height enabled. 
If I create a 2 extruders machine and set the adaptive layer height to 0.04, disable the adaptive layer setting, and disable the second extruder, the first extruder defaults to 0.00 adaptive layer height and slicing gives an error even tho the feature is disabled.

**Comment by Liger0** [comment] 2019-06-13 20:27
https://youtu.be/aShAdV3nAd8

**Comment by Ghostkeeper** [comment] 2019-06-14 09:05
Could you try the same reproduce steps, but with Custom FFF printer? The steps I'm trying according to your instructions are now:

1. Add Custom FFF printer.
2. Set number of extruders to 2.
3. Enable Use Adaptive Layers.
4. Set Adaptive Layers Variation Step Size to 0.04mm.
5. Disable Use Adaptive Layers.
6. Disable the second extruder.
7. Load a cube. Let it slice.

It slices fine for me. I believe you, but I'm not able to reproduce the problem on my computer yet :cry:

**Comment by Liger0** [comment] 2019-06-14 12:16
The printer I use is already a custom FFF one. :(

**Comment by Ghostkeeper** [comment] 2019-06-17 08:40
With your profile it's complaining about the prime tower position since the profile overrides that position but my custom FFF printer was not big enough to include your new position. Making the printer bigger in my machine settings fixed that and allows it to slice fine again. :confused:

**Comment by Liger0** [comment] 2019-06-17 13:51
Did you act exactly like in my video? Disabling same extruder and the options in that order etc.. :\

**Comment by Ghostkeeper** [comment] 2019-06-18 07:41
Yeah. Well, almost. I don't have the sidebar plug-in installed so I'm disabling the extruder via the panel for the printer configuration.

Perhaps you can share a project file? That could shed some light in where this value of "0" comes from.

**Comment by Liger0** [comment] 2019-06-18 08:41
> 
> 
> Yeah. Well, almost. I don't have the sidebar plug-in installed so I'm disabling the extruder via the panel for the printer configuration.
> 
> Perhaps you can share a project file? That could shed some light in where this value of "0" comes from.

Well.. as you see that happens without any model loaded.

**Comment by Ghostkeeper** [comment] 2019-06-18 12:18
Not happening here. Maybe it's been fixed in 4.2?

**Comment by Ghostkeeper** [comment] 2019-06-18 12:21
Ah, yeah, that was it. In 4.1 it does reproduce using that project file.

**Comment by Ghostkeeper** [comment] 2019-06-18 12:24
It seems that this commit fixed it: https://github.com/Ultimaker/Cura/commit/63cd3a52ce3f04a3c69a038ae158eba2ee406461#diff-10b03606c8df532a49117b75a8a32be3

**Closed by Ghostkeeper** 2019-06-18 12:24 UTC
Labels: Category: Cura, Status: Needs Info, Type: Bug
