### ISSUE TITLE
Slicer is creating tiny floating unprintable spikes

### ISSUE THREAD

**Issue by d-schmidt** [Ultimaker/Cura#13406] opened 2022-09-29 22:14 UTC
### Application Version

5.1.1

### Platform

Windows 10

### Printer

Ender 3 V2

### Reproduction steps

[hpcounter_half.zip](https://github.com/Ultimaker/Cura/files/9679359/hpcounter_half.zip)

### Actual results

It slices tiny towers some of which are floating
![grafik](https://user-images.githubusercontent.com/3226483/193151706-f720df4e-cbe6-4085-91a9-aad2c3bde74a.png)

### Expected results

If the wall are too thin, it should skip the spikes.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[hpcounter_half.zip](https://github.com/Ultimaker/Cura/files/9679359/hpcounter_half.zip)

**Comment by MariMakes** [comment] 2022-10-25 12:22
Hey @d-schmidt.

Sorry, it took us a while to get back to you 😞 
What an interesting model 🤩 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12817
We have a ticket on our backlog with the intent to improve this behavior.
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12817

**Closed by MariMakes** 2022-10-25 12:22 UTC
Labels: Type: Bug, Status: Triage
