### ISSUE TITLE
Auto Slicing function - 3.0.4

### ISSUE THREAD

**Issue by jorgan202** [Ultimaker/Cura#2742] opened 2017-11-06 12:50 UTC
Version 3.0.4
When a model is loaded you need to go into setting and toggle the auto slicing function, to get it to do it first time, there after any changes you make, it does it as expected

**Comment by nallath** [comment] 2017-11-08 13:58
I don't understand what your issue is. You mean that it won't auto slice the first time? Does it auto slice if you move the object after loading it?

**Comment by nickthetait** [comment] 2017-11-08 17:56
possible duplicate of https://github.com/Ultimaker/Cura/issues/2693

**Comment by Ghostkeeper** [comment] 2017-11-11 17:07
As I understand it, he's in manual slicing mode and it won't slice the first time until he enables and disables auto-slicing to trigger the first slice?

**Closed** 2018-03-02 21:51 UTC
Labels: Status: Duplicate, Status: Won't Fix
