### ISSUE TITLE
Add shortcut for "Automatically drop models to build plate" function.

### ISSUE THREAD

**Issue by AlexAnYuEn** [Ultimaker/Cura#8754] opened 2020-11-13 02:37 UTC
**Is your feature request related to a problem? Please describe.**
We often need to rearrange ours parts above the build surface, but to prevent the part from auto dropping to the build plate, we need to go in Preferences>General every time.

**Describe the solution you'd like**
A shortcut button to this function on the main Prepare page. Also, it would be interesting if this function could also work per part instead of the whole built plate, because if we raise some parts (auto drop turned off), and then turn on auto drop, all parts drop to the surface and we need to rearrange them again.

**Describe alternatives you've considered**
None. We need to manually go into settings every time.

**Affected users and/or printers**
All Cura users?

**Comment by Ghostkeeper** [comment] 2020-11-17 19:45
Duplicate of https://github.com/Ultimaker/Cura/issues/8117.

**Closed by Ghostkeeper** 2020-11-17 19:45 UTC
Labels: Type: New Feature
