### ISSUE TITLE
Problem with setting of nozzle size (Anet A8)

### ISSUE THREAD

**Issue by cendakrejce** [Ultimaker/Cura#7555] opened 2020-04-21 18:28 UTC
**Application version**
4.6

**Platform**
Windows 10 

**Printer**
Anet A8

**Reproduction steps**
1. Try change nozzle size
2. Try make new FFD printer with different nozzle size

**Screenshot(s)**

![image](https://user-images.githubusercontent.com/64098956/79900312-5513f000-840e-11ea-88c2-13c9bf8df20a.png)

**Actual results**
If I try change nozzle size it will have no effect  - start size nozzle 0.4 - change 0.6 - close window - open setting window again nozzle is 0.4

**Expected results**
Different size of nozzle

**Comment by fsaitta999** [comment] 2020-04-22 21:26
I have the same problem using the profile for Creality ender 3 pro. there is no profile for the nozzle diameter

**Comment by Ghostkeeper** [comment] 2020-04-22 22:56
Duplicate of https://github.com/Ultimaker/Cura/issues/6546.

The missing profiles for the Ender 3 Pro have been added for the next release.

**Comment by fsaitta999** [comment] 2020-04-23 07:52
> Duplicate of #6546. Try using a comma instead of a period.
> 
> The missing profiles for the Ender 3 Pro have been added for the next release.

![image](https://user-images.githubusercontent.com/64170241/80073502-2863f380-8548-11ea-8a2a-fce35b536be2.png)

**Comment by fsaitta999** [comment] 2020-04-23 07:52
not work

**Comment by fieldOfView** [comment] 2020-04-23 08:15
@fsaitta999 you have a different problem than @cendakrejce 
Yours is a duplicate of https://github.com/Ultimaker/Cura/issues/7550

**Closed** 2020-04-28 12:29 UTC
Labels: Status: Duplicate
