### ISSUE TITLE
Can't slice

### ISSUE THREAD

**Issue by yoavzil10** [Ultimaker/Cura#14289] opened 2023-01-13 21:54 UTC
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Ender 3 S1

### Reproduction steps

1. When i turned on support, it couldn't slice.
2 . When the support is turnd off, its working

### Actual results

54965176

### Expected results

Just slice it

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/122648374/212426259-a7bde3ae-48d4-4913-a771-c9d87bad2617.png)

**Comment by MariMakes** [comment] 2023-01-16 16:39
Hey @yoavzil10,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

Is it possible that your printjob is located at 0, 0, 0, and it slices if you move it a little away from the center of the buildplate? 
Then it might be a duplicate of https://github.com/Ultimaker/Cura/issues/13643

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Closed** 2023-01-31 00:19 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage, Slicing Error :collision:
