### ISSUE TITLE
(5.3.0-alpha+xmas)the generated gcode includes random parts of files i printed in the past

### ISSUE THREAD

**Issue by Laura-1207** [Ultimaker/Cura#14910] opened 2023-03-16 18:39 UTC
### Application Version

5.3.0-alpha+xmas

### Platform

windows 10

### Printer

Mingda Magician X

### Reproduction steps

I sliced the file normally, as i sliced similar stls in the past days (i'm printing a set of stackable cubes, the stls are all very similar). i didn't even change the settings (they were the same of the previous successful slicing i did)

### Actual results

the resulting gcode file prints the model i sliced for the first layers, then it starts trying to print random parts of my previous prints
![Screenshot (60)](https://user-images.githubusercontent.com/128086056/225716878-70213165-0dec-48c4-9e6a-eb8f87603e8e.png)
![Screenshot (61)](https://user-images.githubusercontent.com/128086056/225716886-4e43ffac-9afa-49d1-bcb7-d96c9fd6e06b.png)

### Expected results

it should have generated a gcode file to print the model i sliced
![Screenshot (62)](https://user-images.githubusercontent.com/128086056/225717652-7702c121-bb8a-462e-89d9-062d86b39017.png)
![Screenshot (63)](https://user-images.githubusercontent.com/128086056/225717660-03d9865d-2a3c-4c25-9cd6-0610ea9017ab.png)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

i don't have a project file of the time the bug occurred but this is the project file of the model with the same settings:
[MMX_diamond box.zip](https://github.com/Ultimaker/Cura/files/10994674/MMX_diamond.box.zip)

this is the bugged gcode file:
[bug cura.zip](https://github.com/Ultimaker/Cura/files/10994650/bug.cura.zip)

this is the stl of the model:
[diamond box.zip](https://github.com/Ultimaker/Cura/files/10994679/diamond.box.zip)

the problem presented a couple of times in the past weeks, with different models and with the standard (non alpha) 5.3 version

**Comment by MariMakes** [comment] 2023-04-03 09:56
Hey @Laura-1207,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

It looks like you loaded a Gcode file before starting on your next project.
Did you clear your buildplate in between projects?

In 5.3.0-alpha+xmas we still had a bug with the Gcode Reader. 
That has been resolved in Cura 5.3. https://github.com/Ultimaker/Cura/pull/14636

I was not able to reproduce your error in Cura 5.3.
Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

Thank you 😊

**Closed** 2023-04-21 01:05 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage, PreRelease :bug:
