### ISSUE TITLE
Can not start Cura 4.4 on Mac

### ISSUE THREAD

**Issue by EL250a** [Ultimaker/Cura#6700] opened 2019-11-22 11:59 UTC
**Application version**
Cura 4.4
Mac

**Printer**
Cr10spro

**Reproduction steps**
Open Cura 4.4

**Actual results**
"Ultimaker Cura" cannot be opened because Apple cannot check for malicious software.

**Expected results**
Open the program

**Additional information**

<img width="422" alt="Skærmbillede 2019-11-22 kl  12 58 12" src="https://user-images.githubusercontent.com/58074691/69424016-d5cba480-0d27-11ea-91b2-c6185b631ec4.png">

**Comment by sparky14** [comment] 2019-11-23 01:44
I am having the same issue on Mac Catalina 10.15.1

**Comment by smartavionics** [comment] 2019-11-23 10:20
You could try one of my builds that can be found at https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0. They have been built using a more recent version of QT compared to the UM releases. Please read the README.md file there. They can be installed alongside the UM builds without conflict.

**Comment by Ghostkeeper** [comment] 2019-12-04 14:27
Though the symptom is different, we're merging this as a duplicate of #6643. The problem is the same. We're currently using an old version of Qt in order to support MacOS 10.11. Upgrading the Qt version would drop support for MacOS 10.11 but apparently gain support for 10.15. There is no option to support both. So I think we'll choose 10.15 over 10.11 then.

**Closed by Ghostkeeper** 2019-12-04 14:27 UTC
Labels: Type: Bug
