### ISSUE TITLE
[4.3.0] Initial Layer Flow is not applied as an absolute value

### ISSUE THREAD

**Issue by alexchiolo** [Ultimaker/Cura#6521] opened 2019-10-10 23:51 UTC
**Application version**
4.3.0

**Platform**
Windows

**Printer**
Creality Ender-3

**Reproduction steps**
Starting from the default standard quality profile I changed the first layer flow to 105 (to optimize first layer on PETG), and a test square printed perfectly, then in a subsequent print I changed the main flow value to 90 to tune vertical wall thickness and it unexpectedly affected the first layer as well.

**Actual results**
The inside surface of the bottom layer is underextruded, the 90 value is applied as well as 105, resulting in a 94.5% flow.

**Expected results**
Initial layer flow set according to the configured value for it.

**Additional information**
Upon further investigation the issue can be reproduced easily in the slicer preview by exacerbating the values, the attached screenshots should be self-explanatory, including a workaround that allows to obtain the expected flow in the first layer (input value=100*{"first layer flow"/"flow")

If the observed behaviour of the initial layer flow being a multiplier for the other flow values is expected, it should be documented properly (both in the tooltip for flow, which doesn't mention initial layer flow as affected parameter, and in the one for initial layer flow mentioning that the extruded material for layer 0 is multiplied by this value AND the relevant wall/bottom values), if otherwise the initial layer flow is meant to be an independent value the calculations need to be fixed.

![1  bottom flow 100% initial layer 105%](https://user-images.githubusercontent.com/7735622/66614479-1a104480-ebc1-11e9-8765-314126c16666.png)
![2  bottom flow 20% initial layer 105%](https://user-images.githubusercontent.com/7735622/66614477-1977ae00-ebc1-11e9-9a2f-5c76f8fbddff.png)
![3  bottom flow 20% initial layer 525%](https://user-images.githubusercontent.com/7735622/66614478-1977ae00-ebc1-11e9-996c-f61fd23228a7.png)

**Comment by nallath** [comment] 2019-10-11 08:28
Nice find (and thanks for the detailed write up!). I've created an internal ticket for this; CURA-6885

**Comment by soxhi8** [comment] 2020-12-28 02:34
Issue is still present in Cura 4.8.0.

**Comment by Ghostkeeper** [comment] 2020-12-28 20:56
Indeed, looking at that internal ticket mentioned above it seems that our PO has deferred the issue since he thinks we won't have time for it any time soon. It's not fixed because there were other issues that were deemed more important.

**Comment by soxhi8** [comment] 2023-05-30 09:17
Still an issue in Cura 4.13.1.

**Comment by MariMakes** [comment] 2023-05-30 14:27
A fresh set of eyes reporting for duty 🐣 

We updated the initial flow settings in Cura 5.2. 
You can now define the following settings to fit your needs. 
- Initial Layer Outer Wall Flow
- Initial Layer Inner Wall Flow
- Initial Layer Bottom Flow

But I would expect that in this case, the Initial Layer Flow would override the Top/Bottom flow. 
![image](https://github.com/Ultimaker/Cura/assets/40423138/d163b76f-31af-429d-82fe-510013591e6a)

I'll bring it up to the team to see what they can do to improve it. 
But I expect that if it's not a quick fix that it will not get a high priority to implement. 
Fingers crossed 🤞

**Comment by MariMakes** [comment] 2023-08-29 14:22
Quick update from our side 👋

I've discussed this with the team and they find it confusing as well. 😅 
I will mark this as a duplicate of https://github.com/Ultimaker/Cura/issues/14874
We have a ticket on our backlog with the intent to improve this behavior, but this behavior has existed for quite a while, so we'll have to analyze if the risk is worth the impact. 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/14874

Apologies for the wait, hopefully, we can resolve this to make it easier for everyone.

**Closed by MariMakes** 2023-08-29 14:22 UTC
Labels: Type: Bug, Status: Deferred, Status: Under Investigation
