### ISSUE TITLE
Will not open on MacOS

### ISSUE THREAD

**Issue by lcanino** [Ultimaker/Cura#7884] opened 2020-06-05 15:44 UTC
**Application version**
6.1

**Platform**
MacOS

**Printer**
no problems with my printer 
**Reproduction steps**
1. (Something you did.)
I updated my Macs software
2. (Something you did next.)
retried downloading  Cura
<img width="419" alt="Screen Shot 2020-06-05 at 11 36 53 AM" src="https://user-images.githubusercontent.com/65800031/83895577-e1f5dd00-a720-11ea-9a41-ad985ad89c31.png">

**Screenshot(s)**

![image](https://user-images.githubusercontent.com/65800031/83895922-5cbef800-a721-11ea-92e6-58c06820f183.png)

**Actual results**
it bounces a few time and does not load even when I try to override and force it open

**Expected results**
it should open to the work bentch 

**Project file**
none

**Log file**
none that I know of

**Additional information**
No other issues that I am aware of

**Comment by mahtDFR** [comment] 2020-06-09 15:03
I guess you mean 4.6.1 here? Can you share a log please? This will help us work out why it's happening.

**Comment by mahtDFR** [comment] 2020-06-09 15:04
**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Comment by fieldOfView** [comment] 2020-06-09 15:07
The above dialog is shown before Cura has a chance to start logging.

**Comment by mahtDFR** [comment] 2020-06-09 15:15
Oh yeah. Actually this issue already exists on our backlog as CURA-7391
I suspect it's also a duplicate...

**Comment by Ghostkeeper** [comment] 2020-06-10 08:51
Duplicate of https://github.com/Ultimaker/Cura/issues/7389.

**Closed by Ghostkeeper** 2020-06-10 08:51 UTC
Labels: Status: Needs Info, Type: Bug
