### ISSUE TITLE
Cura 4.8 relative extrusion incomplete layers

### ISSUE THREAD

**Issue by dtwolfen** [Ultimaker/Cura#8742] opened 2020-11-12 14:21 UTC
**Application version**
Cura 4.8

**Platform**
Mac Catalina and Windows 10

**Printer**
Custom FFF

**Reproduction steps**
1. I slice model with absolute extrusion save gcode and print all good
2. I slice model with relative extrusion and certain layers are missing sections of the layers even though preview shows them. 
3. Print model and miss sections of layers.
4. Look at gcode in cura and see missing sections only have travel no extrusion. 

**Screenshot(s)**
![Screen Shot 2020-11-12 at 9 14 11 AM](https://user-images.githubusercontent.com/63448250/98950948-a2010600-24c7-11eb-80ba-3eed5de1fdb9.png)
![Screen Shot 2020-11-12 at 9 14 50 AM](https://user-images.githubusercontent.com/63448250/98950949-a2010600-24c7-11eb-818c-956a80d9059f.png)

**Actual results**
Incomplete layers when using relative extrusion

**Expected results**
Complete Layers when using relative extrusion

**Project file**

**Log file**

**Additional information**

[corner test.txt](https://github.com/Ultimaker/Cura/files/5531153/corner.test.txt)

**Comment by dtwolfen** [comment] 2020-11-12 21:09
Note this also happens with any other stl. Seems as though the top, bottom, and infill lines get traveled but no extrusion.

**Comment by dtwolfen** [comment] 2020-11-13 14:46
Find if I downgraded to 4.6 same thing, then downgraded to 4.4 and it worked. Something broke between 4.4 and 4.6. Sorry never used 4.5 so didn't have it available

**Comment by rburema** [comment] 2020-11-17 12:40
Hi @dtwolfen Since this probably depends on the (printer-)settings, could you still save (not export!) a project and attach it here? (As a zip, as gtihub is picky with file-formats, it basically only seems to accept zip, txt and images.)

This makes the debugging process easier as we don't have to second-guess ourselves.

**Comment by Ghostkeeper** [comment] 2020-11-17 17:46
Duplicate of https://github.com/Ultimaker/Cura/issues/6174.

**Closed by Ghostkeeper** 2020-11-17 17:46 UTC
Labels: Status: Needs Info, Type: Bug
