### ISSUE TITLE
RepRap (Volumetric)

### ISSUE THREAD

**Issue by landodragon141** [Ultimaker/Cura#1184] opened 2016-11-27 04:25 UTC
This gcode option cannot be selected in Cura 2.3

**Comment by fieldOfView** [comment] 2016-11-27 10:31
This will be fixed when this PR is merged:
https://github.com/Ultimaker/Cura/pull/1118

**Comment by Ghostkeeper** [comment] 2016-11-28 11:47
Confirmed that it is now fixed, since the PR is merged.

**Closed by Ghostkeeper** 2016-11-28 11:47 UTC

**Comment by landodragon141** [comment] 2016-11-28 14:39
Thank you!
