### ISSUE TITLE
Small bits of infill left after applying gradual infill steps

### ISSUE THREAD

**Issue by soswow** [Ultimaker/Cura#3992] opened 2018-06-28 10:03 UTC
**Application Version**
3.4.0

**Platform**
Mac OS 10.13.5

**Printer**
wanhao duplicator i3

**Steps to Reproduce**
Take my model and slice it.

**Actual Results**

**Expected results**
There are no small bumps of support at the places where support would start if not for gradual infill

**Additional Information**
I have what's basically a cylinder model. I've specified Gradual Infill Steps. It generated very small percentage infill throughout the almost whole model, and the only most top has gradual build up. The problem is - it has these random bits of infill right next to the inside shell. I think they are in the places where infill would start without gradual.

<img width="689" alt="screen shot 2018-06-28 at 7 25 52 pm" src="https://user-images.githubusercontent.com/108065/42027762-cce7acfe-7b0d-11e8-92ba-3e40b215089c.png">

[PI3_Booster Aft Section 3.3mf.zip](https://github.com/Ultimaker/Cura/files/2144784/PI3_Booster.Aft.Section.3.3mf.zip)

**Comment by ianpaschal** [comment] 2018-07-10 07:49
Labelled as bug because it's not really what we want, but if there's not a negative impact on the print's quality its probably not going to be a priority for us. Most infill looks kind of gross compared to the outer shell where aesthetics and surface finish are key.

**Comment by soswow** [comment] 2018-07-10 08:08
Thanks.
It actually has an impact. I can't use this feature atm for these reasons:
1. It increases print time. With all those multiple places it needs to visit along the way makes each layer much longer to finish.
2. With this - I am forced to disable retraction. With retraction for each of those points it will pull in and out all the time making it very noisy print + with my non-ideal printing head quite often I Am end up with either blocked nozzle or with not enough material when it actually start printing a well.

I haven't cross-validated it, but I have a feeling it wasn't a thing before. Now I see this on all models. It was a great feature, but with this bug it's unusable at least by me.

**Comment by ianpaschal** [comment] 2018-07-10 08:47
Hmm. Your problem does not appear to be very severe. But, in an effort to figure out which parts of your project file were causing his bad behavior I compared it to the default settings and daaaaaaaaaaaaaamn. Gradual infill is very messed up at least on the default quality profiles for Prusa i3.

<img width="808" alt="screen shot 2018-07-10 at 10 46 06" src="https://user-images.githubusercontent.com/1137232/42499258-9d2181c8-842e-11e8-9b5b-4831fdbed762.png">
<img width="805" alt="screen shot 2018-07-10 at 10 45 45" src="https://user-images.githubusercontent.com/1137232/42499259-9d3b7efc-842e-11e8-987f-ff46306738b5.png">

These are just normal 0.1 profile with gradual infill turned on. Very strange behavior indeed.

**Comment by ianpaschal** [comment] 2018-07-18 12:05
I've done some research on this. It seems to be caused by the infill overlap (how much the infill lines overlap with the wall).

If you set that to 0, you'll remove the issue on your print, however then you won't get all the strength boost as if there is some overlap.

I also cross checked this with other printers and profiles and the issue seems to be limited to Prusa I3 profiles/printers. I'm making a sticky note for our "what to do about it" board and we'll figure out our plan of action.

**Comment by ianpaschal** [comment] 2018-07-18 12:16
My thinking (aloud, because I'm on vacation the rest of the week so the other Cura team members can read this), is that since this is not occurring everywhere, it's not a bug in Cura Engine but in the quality profiles for Prusa I3. This hopefully means that it's a relatively small fix that doesn't require lots of test prints and introduce possible regression for other printers.

**Comment by soswow** [comment] 2018-07-18 13:52
Frankly, I don't know exactly what differentiates one "profile" from another 🤷‍♂️ . 
I mean, it's an engine that generates infill, right? And I imagine an engine as a black box function with inputs and one of the inputs is "support infill". Then if there is a chance the output of this function has the artifact we see - it's an engine problem. So, that's where I am unknowledgeable of how and where profile sits in this picture. It could be that there are some meta-parameters that are hardcoded into profile that also come as an argument to this engine function. And it could be only one of the profiles makes this engine generate these artifacts. But never the less - it's the engine that generates them.

**Comment by alekseisasin** [comment] 2018-07-19 08:53
Devs: CURA-5583

**Comment by soswow** [comment] 2019-04-18 13:45
@ianpaschal , Was this actually fixed? I still have it. 4.0.0.
<img width="1613" alt="Screen Shot 2019-04-18 at 11 44 21 PM" src="https://user-images.githubusercontent.com/108065/56365364-0b5d5c00-6234-11e9-94e4-cd43b06d7e22.png">

**Comment by soswow** [comment] 2019-04-18 13:47
[PI3_Star_Lords_Gun_Part_1_200mm.3mf.zip](https://github.com/Ultimaker/Cura/files/3094655/PI3_Star_Lords_Gun_Part_1_200mm.3mf.zip)

**Comment by Ghostkeeper** [comment] 2019-04-19 09:58
Could you upload a project file rather than just a 3MF file? Your file doesn't contain any settings or the profile that you were using, so it doesn't reproduce.

**Comment by Ghostkeeper** [comment] 2019-04-19 10:02
Incidentally, when slicing that 3MF file in the configuration that I happened to have active at the time, I'm getting a segfault: [segfault_outerpolygon.zip](https://github.com/Ultimaker/Cura/files/3097769/segfault_outerpolygon.zip)

**Comment by soswow** [comment] 2019-04-19 10:55
@Ghostkeeper Sure thing. I am still confused what am I "Saving" vs "exporting" :shrug:

[example.3mf.zip](https://github.com/Ultimaker/Cura/files/3097871/example.3mf.zip)
Will this do?
It's a different model. Just happens to be loaded right now.:
<img width="1541" alt="Screen Shot 2019-04-19 at 8 55 04 PM" src="https://user-images.githubusercontent.com/108065/56421365-787cfa00-62e5-11e9-91b8-eaa261d0f2f6.png">

**Comment by LipuFei** [comment] 2019-04-23 10:06
@Ghostkeeper The segfault seems to be fix on the latest master. I think it's fixed by https://github.com/Ultimaker/CuraEngine/pull/1042

**Comment by Ghostkeeper** [comment] 2019-04-24 05:11
> [example.3mf.zip](https://github.com/Ultimaker/Cura/files/3097871/example.3mf.zip)
> Will this do?

Yup, that does it. I see the same bits on this end now as well.

**Comment by Ghostkeeper** [comment] 2019-04-24 05:21
It's a bit hard to trace now since our issue tracker isn't able to link to Github any more, but originally the PR that fixed this issue was https://github.com/Ultimaker/CuraEngine/pull/820.

**Comment by Ghostkeeper** [comment] 2019-04-24 09:46
Made a slightly better fix here: https://github.com/Ultimaker/CuraEngine/commit/ff00a47977c024e7f1e4499fb6fe4b251ba86a52

**Closed** 2019-04-24 09:47 UTC
Labels: Category: Engine, Status: Fixed/Solved, Type: Bug
