### ISSUE TITLE
Honeycomb infill ?

### ISSUE THREAD

**Issue by azalanono** [Ultimaker/Cura#7181] opened 2020-02-28 12:26 UTC
I know, this is a long lasting wish of many users, I am one of them.

Why isn't Honeycomb infill available? it is a very strong structure, rotating the parallel lines by 60 deg. every layer.
I love it, and when I need very string parts, I usually use slic3r in such case, it supports this infill.

**Comment by mahtDFR** [comment] 2020-02-28 12:36
Duplicate of #2069

**Closed by mahtDFR** 2020-02-28 12:36 UTC
Labels: Type: New Feature
