### ISSUE TITLE
CURA UI Slow. Not my computer

### ISSUE THREAD

**Issue by Wdfitzpat007** [Ultimaker/Cura#5668] opened 2019-04-26 02:40 UTC
What ever info you need I will provide. Sorry if repost, I am too busy to look for an existing post.

I have a 2013 macbook pro 15" retina version, 4th gen intel hyper-threaded quadcore with 16 GB of ram and a SSD with 51gb of free space. Running out of memory/CPU time is not an issue. Bootcamp keeps my drivers up-to-date.

Fusion360, solidworks and other programs with intensive UI / graphics work fine. Inside cura everything works except the UI, for example I click on settings and it just hands for a few seconds at 18% CPU usage with an outline of the dropdown that should pop up. I have not tried re-installing, though will if you like. I can post any screenshots or video if you need. I expect this will take some effort on my end and hope that the users of my programs put in the same effort I will put into helping you.

Also, movement is funky. IE when I hover over the rotate circles or move arrows sometimes it fails to trigger a color change and thus nothing happens with click+drag.

**Application Version** 4.0.0

**Platform** Windows 10 pro 64x Bootcamp

**Printer** Invalid, ( Custom profile Qiditech Xone2 ( school ) Tevo Tornado ( home ) if you insist )

**Steps to Reproduce** Worked fine until one day I added a ton of models to the same print, though that day ( 4/11/19 ) was the day I updated. So it may have been on update, yes there was a previous version, yes it successfully uninstalled. No I did not clear settings, and yes I did copy the cura appdata files from another computer to avoid formatting the custom profile on 8 computers when deploying custom windows images, but non of the other computers have this problem, and they have been updated too. Yes, the only laptop with problems is the bootcamped macbook but please dont be lazy and chalk it up to that, lets do the do diligence of testing before coming to likely the same conclusion.

**Actual Results** UI is painfully slow and pegs the CPU to 20% with no on screen response for 5-15 seconds. This sucks as it happens on everything.

**Expected results** When you click on a UI element, it opens, not give you a phantom box and peg CPU.

**Additional Information** Included above

**Comment by fieldOfView** [comment] 2019-04-26 06:24
Duplicate of https://github.com/Ultimaker/Cura/issues/4505
Should be fixed in the upcoming Cura 4.1. A patched version of Cura 4.0 can be found here:
https://github.com/Ultimaker/Cura/issues/4505#issuecomment-482270203

**Closed** 2019-05-10 08:53 UTC
Labels: Status: Needs Info

**Comment by ilium007** [comment] 2019-05-30 00:00
Cura 4.1 lagging for me. Fresh install. Unuseable.

**Comment by nallath** [comment] 2019-05-31 08:33
Look, only posting a "Me too" comment isn't helpful at all. If you don't post information about what your setup is, what the logs say and what it is that you're doing **exactly**, there is nothing we can do to fix it.

**Comment by ilium007** [comment] 2019-06-04 08:03
> Look, only posting a "Me too" comment isn't helpful at all. If you don't post information about what your setup is, what the logs say and what it is that you're doing **exactly**, there is nothing we can do to fix it.

What else do you want me to add ? Its a slow UI problem.

OSX 10.14.1
16GB RAM
i5 Mac Mini

What I'm doing exactly? Anything in the menus / UI.

What logs *exactly* do you want?

**Comment by Ghostkeeper** [comment] 2019-06-04 12:55
> What logs *exactly* do you want?

The Cura log could be helpful. Here's instructions on where to find it: https://github.com/Ultimaker/Cura#logging-issues
