### ISSUE TITLE
2.4.0 Vase/Spiralize mode Z seam + Z hop

### ISSUE THREAD

**Issue by kr15uk** [Ultimaker/Cura#1534] opened 2017-03-14 10:35 UTC
Vase mode prints gradually increasing Z as expected but does weird Z hop when perimiter is completed leaving Z seam.
I have predefined Z seam location (200, 200) and Z seam goes there but if I chose Shortest or Random it still does Z seam but in different location obviously.

**Comment by Ghostkeeper** [comment] 2017-03-14 12:30
This was initially fixed in https://github.com/Ultimaker/CuraEngine/pull/465, but then this was abandoned and eventually fixed again in https://github.com/Ultimaker/CuraEngine/pull/468. It'll be released with Cura 2.5.

**Comment by Ghostkeeper** [comment] 2017-03-14 12:31
This is a duplicate of https://github.com/Ultimaker/Cura/issues/1396.

**Closed by Ghostkeeper** 2017-03-14 12:31 UTC
