### ISSUE TITLE
Cura default profile change

### ISSUE THREAD

**Issue by Hun73rdk** [Ultimaker/Cura#12004] opened 2022-04-28 02:12 UTC
### Is your feature request related to a problem?

When changing filament type stop cura from reverting to default profile 

### Describe the solution you'd like

Want a way that if i change filament type that it does not change away from the current print profile selected 

### Describe alternatives you've considered

either make so we can set a default profile we use or a button to stop the profile from changing when changing filament profile 

### Affected users and/or printers

Everyone that has custom profiles and never use the defaults

**Comment by nallath** [comment] 2022-06-15 13:26
Duplicate of #8229

**Closed by nallath** 2022-06-15 13:26 UTC
Labels: Type: New Feature
