### ISSUE TITLE
Raft Error

### ISSUE THREAD

**Issue by rafaelldavid** [Ultimaker/Cura#15930] opened 2023-06-27 07:06 UTC
### Application Version

5.4.0-beta.1

### Operating System

Windows 11

### Printer

Ender 3

### Reproduction steps

I changed the Build Plate Adhesion type from skirt to raft and g-code started counting the first few layers as negative.
Because of this, printing does not start.

![image](https://github.com/Ultimaker/Cura/assets/22876281/d806cb84-a7c9-420a-9da2-04ed7a239102)

### Actual results

;LAYER:-6
SET_PRINT_STATS_INFO CURRENT_LAYER=-5
This appears in g-code

Error on 'SET_PRINT_STATS_INFO_BASE CURRENT_LAYER=-4': CURRENT_LAYER must have minimum of 0
This appears in Klipper Console

### Expected results

Start Print... xD

### Checklist of files to include

- [x] Project file
- [ ] Log file

### Additional information & file uploads

[CE3S1_Townsfolke_Woman.zip](https://github.com/Ultimaker/Cura/files/11878647/CE3S1_Townsfolke_Woman.zip)

**Comment by GregValiant** [comment] 2023-06-27 19:11
Thanks for the report.
That is expected behavior in Cura.  The model starts positive layer numbers with LAYER:0 and raft layers are negative.
You can turn off the macro in Klipper, you can re-write it to account for negative layer numbers, you can use Search and Replace to search for ";LAYER:-" and replace it with ";LAYER:".
This isn't a Cura bug as it has been this way since it's inception.  Ideamaker also uses negative numbers for rafts.  Prusaslicer doesn't use layer numbering at all.
I'll remove the bug label and go ahead and close this.  I hope you understand.

**Closed by GregValiant** 2023-06-27 19:11 UTC
