### ISSUE TITLE
Issues Slicing .8 mm walls when using .8 mm nozzle

### ISSUE THREAD

**Issue by benderprod** [Ultimaker/Cura#7697] opened 2020-05-06 22:29 UTC
**Application version**
4.6.0

**Platform**
Windows 10

**Printer**
Ender 5

**Reproduction steps**
1. Generated a model in Fusion 360 with walls that are .8mm thick.  Rectangular or Circular
2. Slice in Cura with .8mm nozzle selected.

**Screenshot(s)**
Slicing .8mm walls with .8mm nozzle
![image](https://user-images.githubusercontent.com/64932036/81234160-385ae900-8fc6-11ea-8335-b159ebcf2da5.png)

Slicing 1.6mm walls with .8mm nozzle
![image](https://user-images.githubusercontent.com/64932036/81234317-88d24680-8fc6-11ea-93a2-7e718afd4dc5.png)

**Actual results**
Wall are incomplete, leaving opened gaps.

**Expected results**
Each layer should simply be a single wall circle.

**Project file**
[Outside Speaker Light - Outside Spiral (0.8 walls).3mf.zip](https://github.com/Ultimaker/Cura/files/4589774/Outside.Speaker.Light.-.Outside.Spiral.0.8.walls.3mf.zip)

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/4589780/cura.log)

**Comment by 64Florian** [comment] 2020-05-07 18:53
I saw this "issue" too ... (for 0.4 mm nozzle)
I use "spiralize outer contour as workaround 
<img width="753" alt="Capture d’écran 2020-05-07 à 20 16 25" src="https://user-images.githubusercontent.com/34726380/81330048-cbb41d00-909f-11ea-8dd8-c3cc8bbce33b.png">
"
but in your case, you may have to use another object with "modify object for overlaps" for your 4 handles (they look like thicker than the body)

**Comment by Ghostkeeper** [comment] 2020-05-11 12:46
That's because your model has staggered vertices for the inside and outside of the model:

![image](https://user-images.githubusercontent.com/2448634/81562980-f5b65980-9395-11ea-9360-a9ba2485b700.png)

This means that in some places the wall is thinner than 0.8mm and in some places the wall is wider than 0.8mm. The wall only gets drawn if it's wider than one line width.

Duplicate of https://github.com/Ultimaker/Cura/issues/7687.

**Closed by Ghostkeeper** 2020-05-11 12:46 UTC
Labels: Type: Bug
