### ISSUE TITLE
[4.2.1] Supports for empty space generated

### ISSUE THREAD

**Issue by iglitchy** [Ultimaker/Cura#6282] opened 2019-08-30 10:29 UTC
**Application version**

4.2.1
**Platform**

Win 10
**Printer**

[D_spool.3mf.zip](https://github.com/Ultimaker/Cura/files/3559497/D_spool.3mf.zip)
**Reproduction steps**

Slice with supports enabled and support horizontal expansion set to 0
**Actual results**

Supports generated inside the model, along the vertical wall, that do not support anything
![Horizontal_expansion_0](https://user-images.githubusercontent.com/17552521/64014041-d4744c80-cb29-11e9-99db-08e6c645d095.PNG)
**Expected results**

Supports are only generated for the parts that have overhang and actually touch something
![Horizontal_expansion_01](https://user-images.githubusercontent.com/17552521/64014043-d4744c80-cb29-11e9-9533-0930ea633062.PNG)
**Additional information**

For this model i need supports for inner groove overhang
![Horizontal_expansion_support](https://user-images.githubusercontent.com/17552521/64014044-d50ce300-cb29-11e9-958b-f1cc3b5d5460.PNG)

**Comment by StefanoV1989** [comment] 2019-09-02 05:52
Yes, i have the same problem with supports in 4.2.1 version.
Yesterday it tried to put supports to a wall, without creating a base ... directly in the air linked only to the wall.

**Comment by Ghostkeeper** [comment] 2019-09-03 15:04
Duplicate of https://github.com/Ultimaker/Cura/issues/4219

**Closed by Ghostkeeper** 2019-09-03 15:04 UTC
Labels: Type: Bug
