### ISSUE TITLE
Custom Prime tower or using per model objects to wipe 

### ISSUE THREAD

**Issue by eskeyaar** [Ultimaker/Cura#8473] opened 2020-10-01 18:19 UTC
**Is your feature request related to a problem? Please describe.**
Yes, Since prime tower is needed for purging the next color, can we able to purge into an existing object so that we don't throw away square prime tower.

**Describe the solution you'd like**
Instead of purging material into a block, we can purge into an object, ( yes, the color will be different but still we can keep it and save material too )

Just heads up: Prusa Slicer has this feature and it really is a good feature I like to see in cura. 

Thanks

**Comment by Ghostkeeper** [comment] 2020-10-02 15:12
Duplicate of https://github.com/Ultimaker/Cura/issues/3657.

**Closed by Ghostkeeper** 2020-10-02 15:12 UTC
Labels: Type: New Feature
