### ISSUE TITLE
the direction arrows 3 colors  are huge and cant make them smaller or scale it 

### ISSUE THREAD

**Issue by sankafola** [Ultimaker/Cura#13004] opened 2022-08-11 15:31 UTC
### Application Version

5.10

### Platform

mac 

### Printer

anyquibic predator

### Reproduction steps

it happen in any slicing parts

### Actual results

i cant change direction 

### Expected results

when i zoom out the direction arrows the 3 colors should get smaller and able to use them

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

let me know if you need screen shots

**Comment by Vandresc** [comment] 2022-08-15 06:50
Hi @sankafola, for me they do scale when zooming in or out, could you indeed provide a screenshot or a recording?

**Comment by sankafola** [comment] 2022-08-16 13:55
hi,
 please see below , i zoomed out and the arrow dont reduce at all 


amir ibrahim
***@***.***

**Comment by Vandresc** [comment] 2022-08-18 07:46
Hi, sorry but I do not see any attachment. Can be attached only via github and not via an e-mail reply, unfortunately.

**Comment by MariMakes** [comment] 2022-08-26 11:27
Hey @sankafola,

It's hard for us to troubleshoot this without a screenshot or a video.
Can you please visit Github in your browser to share your screenshot? 
Thank you! 👼

**Comment by sankafola** [comment] 2022-08-26 11:55
![Image 2022-08-26 at 7 54 AM](https://user-images.githubusercontent.com/64208964/186897884-4c2f1ab1-46db-4498-a7c1-35366306b04b.jpg)
here we go

**Comment by sankafola** [comment] 2022-08-26 11:55
you see its zoomed out and the arrow are still very big

**Comment by MariMakes** [comment] 2022-08-26 12:11
Oh wow! 
Yea that looks like a bug, I'll bring it up to the team.

In the means time. You seem to have quite some plug-ins installed, and some of them might influence your rendering.
Can you share your configuration folder? You can find it under Help, Show Configuration Folder. 
Could you zip the contents and share them with me?

**Comment by sankafola** [comment] 2022-08-26 12:17
its 31 meg too big to upload how can i reduce ? what you dont need so i can delete from it ?

**Comment by MariMakes** [comment] 2022-08-26 12:18
You can use https://wetransfer.com/ to share bigger files on Github. 👍

**Comment by sankafola** [comment] 2022-08-26 12:21
https://we.tl/t-46MtNTnjYg 

let me know if you got it

**Comment by MariMakes** [comment] 2022-08-26 12:32
I did it, but my arrows look relatively normal
![image](https://user-images.githubusercontent.com/40423138/186903925-d9ae37bf-4a82-404a-a897-fa6b15352013.png)

I'll bring it up to the team anyways.

**Comment by stargazer529** [comment] 2022-10-22 19:41
i have the same problem with the gigantic arrows since version 5.1.0
 in 5.2.1 it still remains

**Comment by revantjhalani** [comment] 2023-01-14 19:58
I have the same Issue 
![image](https://user-images.githubusercontent.com/39228530/212493906-4c6796df-3314-4ad0-94fb-068d5febeb53.png)
![image](https://user-images.githubusercontent.com/39228530/212493957-16063895-e625-418e-8218-4480c9770c97.png)

**Comment by MariMakes** [comment] 2023-01-16 09:33
Hey @revantjhalani,

Thanks for the extra report. 
I've noticed that you and sankafola both seem to have a plug-in that facilitates printing to your printer. I think it's the Octoprint plugin. 

Can you share what operating system you are on? 
Maybe we have the device here so we can reproduce your issue.

**Comment by revantjhalani** [comment] 2023-05-12 21:48
Hey @MariMakes, sorry for the delayed response.
The issue is fixed for me now and everything seems to be normal. 
If it's of any value now, the plugin I use is https://marketplace.ultimaker.com/app/cura/plugins/thomas_kriechbaumer/DuetRRFPlugin

**Comment by MariMakes** [comment] 2023-05-15 08:58
Hey all,

We've been receiving similar bug reports via our support channel and they all seem to be resolved by disabling the Cura-DuetRRFPlugin and was processed here: https://github.com/Kriechi/Cura-DuetRRFPlugin/issues/47

To me, it doesn't seem like a bug in Ultimaker Cura anymore since it's related to the plug-in. 
I'll be closing this issue. I hope you understand.

**Closed by MariMakes** 2023-05-15 08:58 UTC
Labels: Type: Bug, Status: Under Investigation
