### ISSUE TITLE
Stop on slicing process cura 2.3.1 mac (Ultimaker 2 Go)

### ISSUE THREAD

**Issue by Loleyouss** [Ultimaker/Cura#1222] opened 2016-12-07 07:39 UTC
Configuration MacBook pro i7 : OSX 10.8.5 
Ultimaker 2 Go

After loading a 3D model (a normal .stl), we have the message "Preparing to slice...) an that'all.
 Then impossible to save to file and if i try to save le selected file, we have the following message : "Could not save to /.....filename.gcode:None
If I change the 3D model printer for an Ultimaker 2 (just this one, I add the ultimaker 2 and remove Ultimaker 2go then reboot the soft)
and then the bug is the same : preparing slice...... and nothing else.

**Comment by Ghostkeeper** [comment] 2016-12-07 08:22
Duplicate of #1203.

**Closed by Ghostkeeper** 2016-12-07 08:22 UTC
