### ISSUE TITLE
Many walls vase mode

### ISSUE THREAD

**Issue by karabas2011** [Ultimaker/Cura#11408] opened 2022-02-03 12:16 UTC
### Is your feature request related to a problem?

I print on pellet extruder with big nozzle (3mm currently ) with no retract. 
Most my models are vase mode capable and it is preferable printing method. No travel movements at all, no nozzle leaking. No seams.
But it limited to one wall thickness.

### Describe the solution you'd like

 I need a  mode when all walls  in layer become one closed loop. Then  it can be printed in vase mode.
Suboption is rounding semiloop "ends" to more smooth movement

### Describe alternatives you've considered

common way is currently used.

### Affected users and/or printers

Any user can use vase mode on any nozzle diameter and no wall thickness limitation

**Comment by karabas2011** [comment] 2022-02-04 06:38
![image](https://user-images.githubusercontent.com/2634978/152483750-cff45adc-0687-4926-80b8-128783468de9.png)

**Comment by fvrmr** [comment] 2022-02-07 15:44
Hi @karabas2011 thank you for your feature request.
I will bring this up with the team. Keep you posted!

**Comment by karabas2011** [comment] 2022-02-08 09:51
Preliminary tests show problem with "seam". We need some options for overlapping "seam" ends. Currently no noticeble advantages.

**Comment by casperlamboo** [comment] 2022-02-11 10:24
Hi @karabas2011, This ticket has already been deferred but I thought it was really interesting. Your example of 3 walls can be extended to a general solution that work for a vase mode that work on vase mode with a wall count of any number. In this solution there is a slight difference between even and odd number walls. The image below can be trivially extended to any number walls.
![Untitled Diagram](https://user-images.githubusercontent.com/6638028/153574504-c40baab4-042c-41b1-8f6e-6a9e1f0621ec.png)

There is still one problem though: the 2nd 3rd etc walls must be offsetted from the original polygon shape. A offset of a continuous polygon doesn't always end up as a continuous polygon (see attached image below). For vase mode this is a problem as it requires all polygons to be continious, otherwise funky stuff will happen. 
![Untitled Diagram-Page-2 drawio](https://user-images.githubusercontent.com/6638028/153574510-83da3905-3b28-45d4-a75e-126c71330913.png)

**Comment by karabas2011** [comment] 2022-02-17 06:59
Yes this is limitation. You need to model part with such slicing in mind. But I faced with more important seam problem. There are no any possibility to overlap seam walls even with no-vase mode. Big nozzle tends to drag extruded plastic line when starts to travel and  creates seam holes.

**Comment by Ghostkeeper** [comment] 2022-02-17 13:44
This is a duplicate of https://github.com/Ultimaker/Cura/issues/4323 . There has been some analysis in the other ticket as well about how this could be approached, and the limitations with what shapes can be printed, water tightness, etc.

**Closed by Ghostkeeper** 2022-02-17 13:44 UTC
Labels: Status: Deferred, Type: New Feature
