### ISSUE TITLE
Material Colour always yellow

### ISSUE THREAD

**Issue by kr15uk** [Ultimaker/Cura#2873] opened 2017-11-28 23:46 UTC
Cura 3.0.4
macOS 10.13.1 High Sierra
Custom machine
Custom material with set colour

In Layer View, Material Colour model is always yellow, doesn't change to set colour.

**Comment by ChrisTerBeke** [comment] 2017-11-28 23:51
I cannot reproduce this issue. Did you activate (select) the custom material after creating it?

**Comment by kr15uk** [comment] 2017-11-29 00:03
Yes I did.
It works in Solid View but not in Layer View (Material Colour)

**Comment by ChrisTerBeke** [comment] 2017-11-29 00:08
Ok. And I assume it re-sliced after selecting the custom material?

**Comment by kr15uk** [comment] 2017-11-29 00:11
Yep, every time when I change material it re-slices.

**Comment by ChrisTerBeke** [comment] 2017-11-29 00:26
Okay, I can reproduce this in 3.0.4. In the 3.1 beta it seems fixed for the layer view (we overhauled the layer view and extruder settings management), but the color indicator circles don't seem to update yet, so I'll create an internal ticket for those.

**Comment by ChrisTerBeke** [comment] 2017-11-29 08:27
Devs: see CURA-4641

**Comment by ChrisTerBeke** [comment] 2017-11-29 09:53
It was fixed in https://github.com/Ultimaker/Cura/commit/16e07fc461ad186038c6f8aa2cf55847593bd1ec. Please keep in mind that the layer view color won't update until after a re-slice. This is expected behaviour.

**Closed by ChrisTerBeke** 2017-11-29 09:53 UTC
