### ISSUE TITLE
Machine settings do not save.

### ISSUE THREAD

**Issue by Stormwing01** [Ultimaker/Cura#7369] opened 2020-03-29 19:50 UTC
**Application version**
4.5

**Platform**
windows 10 pro 64 bit

**Printer**
wanhao i3 mini

**Reproduction steps**
1. go to settings -> printer -> manage printer ->machine settings -> extruder 1

If I change the nozzle diameter from 0.4 to 0.3 and the filament diameter from 1.75 to 1.73, they both reset as soon as I click close and exit to use cura. when I go back to that setting, they are back to 0.4 and 1.75 respectively.

**Screenshot(s)**
![Untitled](https://user-images.githubusercontent.com/36460787/77859156-0ce72080-7208-11ea-91d5-309b721c552f.png)

![untitled 2](https://user-images.githubusercontent.com/36460787/77859162-0eb0e400-7208-11ea-97f8-321f4a8405ed.png)

**Actual results**
nozzle and filament diamter settings in "machine settings" are not saved.

**Expected results**
the software should have saved those settings and made adjustments accordingly, because I do not use a 0.4mm nozzle, and my filament diameter is at this moment an average of 1.73mm. it impacts print quality negatively.

**Project file**
there is no project.

**Log file**
I have no cura.log file.

**Additional information**
(Extra information relevant to the issue.)

**Comment by fieldOfView** [comment] 2020-03-29 20:03
Could you try entering the numbers with a comma instead of a dot?

**Comment by Stormwing01** [comment] 2020-03-29 20:40
edit: when I save te settings as with a "," and not a "." in the value, they do save, but if I simply edit and exit with a "." in the value, it resets itself....

**Comment by fieldOfView** [comment] 2020-03-29 20:45
Duplicate of https://github.com/Ultimaker/Cura/issues/6546

**Closed** 2020-03-30 09:03 UTC
Labels: Type: Bug
