### ISSUE TITLE
support brim not working and layer buildup incorrect

### ISSUE THREAD

**Issue by GeenIdee91** [Ultimaker/Cura#15925] opened 2023-06-26 17:46 UTC
### Application Version

latest beta and previous

### Operating System

windows 11

### Printer

ender 5 plus

### Reproduction steps

Hello,

When supports are created, for some reason it makes a small shape at the first layer and not the full shape. The full shape comes in at 2nd layer. Therefor it does not get max adhesion with risk of failure (happened to me twice). Now with a new print I run into the same issue. Please compare layer one to layer two.

Also, als you can see, there is no support brim. Why? Bug or am I doing something wrong?

![Schermafbeelding 2023-06-26 192927](https://github.com/Ultimaker/Cura/assets/137820424/c5b21115-416f-4c26-a793-e11551b8e767)

![Schermafbeelding 2023-06-26 192949](https://github.com/Ultimaker/Cura/assets/137820424/94746f57-9854-4084-b0d0-acd124e7067f)

![Schermafbeelding 2023-06-26 193033](https://github.com/Ultimaker/Cura/assets/137820424/c017f51e-7923-4eb5-8390-4601a4ce6b4a)

Thanks
kevin

### Actual results

no brim, full support footprint starts at 2nd layer

### Expected results

actual support brim and full support footprint at first layer

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE5P_calipertool.zip](https://github.com/Ultimaker/Cura/files/11872175/CE5P_calipertool.zip)

**Comment by GregValiant** [comment] 2023-06-27 21:52
Thanks for the report and the file.
It's a bug.  If the Bed Adhesion is set to "None" then the support brim doesn't form on layer:0 and the support itself starts on layer:1.
Use a skirt and the problem should go away.
I'll mark this as a duplicate of #14725 and #14822 and go ahead and close this one.  I hope you understand.
This is the initial layer with the skirt enabled.
![image](https://github.com/Ultimaker/Cura/assets/64202104/5f65fdae-13a2-49fa-a692-2e257e311d04)

**Closed by GregValiant** 2023-06-27 21:52 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation
