### ISSUE TITLE
Slicer crash when using monotronic mode

### ISSUE THREAD

**Issue by MeSoLost** [Ultimaker/Cura#10626] opened 2021-10-15 23:23 UTC
### Application Version

4.11

### Platform

windows 10

### Printer

Custom- Ender 3

### Reproduction steps

https://www.thingiverse.com/thing:3631413

Attempting to slice rear hole variant with monotronic top/bottom order, zig-zag, custom angle array[45,90,135,180].  no gap fill between walls, leave gaps, 0.05/0.03 horizontal expansion, 4 top 3 bottom layers, 2 skin layers

### Actual results

called module cura slicer engine either directly returns a crash to the program or remains resident with 0.00% cpu usage and never returns.  Cancel button within program does successfully stop the hung slicer.

### Expected results

um... click slice, watch the bar complete, view returned layer slice within program before saving. You know, the usual thing that happens when you click "slice"

[CE3_Ender_3_External_Electronics_Case_-_Rear_Wiring_Hole.zip](https://github.com/Ultimaker/Cura/files/7356325/CE3_Ender_3_External_Electronics_Case_-_Rear_Wiring_Hole.zip)

### Checklist of files to include

- [x] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7356365/cura.log)

**Comment by fvrmr** [comment] 2021-10-18 09:16
Hi @MeSoLost thank you for your report. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/10418 and is happening because the top/bottom pattern is set to zigzag. If you change this to lines. The engine won't crash. 
We have fixed this for our next release.

I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-10-18 09:16 UTC
Labels: Type: Bug
