### ISSUE TITLE
LAYER VIEW Issue in a CAR DESIGN.

### ISSUE THREAD

**Issue by soniashish1009** [Ultimaker/Cura#3260] opened 2018-02-08 05:37 UTC
APPLICATION VERSION is **CURA 3.2.0** stable.
 
CURA Platform **(LAYER VIEW)**

I have been using CURA for about 10 months. As a regular work when I have used **_CURA_** to open a file of the CAR designed in the **_SKETCHUP_**. I saw an error. I have seen the SOLID VIEW & LAYER VIEW does not match. 

Actually, I want to hollow the back portion of the CAR which is L- shaped. So in the SOLID VIEW as I am seeing the Design it is same as I want. But in the LAYER VIEW, it is not hollow as I want.

So I want that L- shaped pipe to be hollow in the LAYER VIEW.

I have attached some screenshots, which will give you better knowledge.

![screenshot 110](https://user-images.githubusercontent.com/36254936/35956901-68cec06c-0cbe-11e8-8aa9-a43de50678e5.png)

![screenshot 111](https://user-images.githubusercontent.com/36254936/35956902-6ccdb77c-0cbe-11e8-9d24-d7ccf33568de.png)

![screenshot 112](https://user-images.githubusercontent.com/36254936/35956908-70c41bf0-0cbe-11e8-89d3-3ad6ee71b831.png)

![screenshot 113 _li](https://user-images.githubusercontent.com/36254936/35956980-f5629404-0cbe-11e8-8517-5d1017ef141d.jpg)
![screenshot 114 _li](https://user-images.githubusercontent.com/36254936/35957044-5c066d52-0cbf-11e8-855d-e30a23fd988c.jpg)

 Please help ASAP. It's very important to solve this issue.

**Comment by ChrisTerBeke** [comment] 2018-02-08 08:05
It seems your model is not a single solid volume, which makes it hard for Cura (or any other slicer for that matter) to get the intended results

**Comment by fieldOfView** [comment] 2018-02-08 08:41
I agree that there’s an issue with your model, even if it is not directly obvious in solid view. The xray view probably shows some red areas. Sketchup is notorious for producing models that are broken for 3d printing.

You can try un-setting the “Union overlapping volumes” setting. Use the search in the custom sidebar to find this setting.

**Comment by Ghostkeeper** [comment] 2018-03-02 12:53
If you are at liberty to share a model that reproduces this issue, we could tell you more.

**Comment by ChrisTerBeke** [comment] 2018-05-23 19:18
Issue with model, not Cura. Closing.

**Closed by ChrisTerBeke** 2018-05-23 19:18 UTC
Labels: Category: CuraEngine, Status: Needs Info
