### ISSUE TITLE
Missing toolbar and blurry text on Windows 10

### ISSUE THREAD

**Issue by leonardoherrmann** [Ultimaker/Cura#2327] opened 2017-08-27 13:46 UTC
Hello!

I am having trouble with Cura 2.6.2 with Windows 10. When I open the software, it loads just fine but when the program opens it is all blurry and missing the toolbar on the top.

I already tried deleting all Cura files and reinstaling the program, it did'nt work.

![image](https://user-images.githubusercontent.com/31195425/29750365-e02dbc66-8b14-11e7-8926-9ebb3d17778d.png)

Any suggestions?

**Comment by fieldOfView** [comment] 2017-08-27 17:52
You have to either upgrade or downgrade your Intel HD Graphics driver. See https://github.com/Ultimaker/Cura/issues/2068#issuecomment-324917547

**Comment by Ghostkeeper** [comment] 2017-09-02 17:16
Duplicate of #2068.

**Closed by Ghostkeeper** 2017-09-02 17:16 UTC
