### ISSUE TITLE
error support_z_distance = 0.0. (cura 4.3)

### ISSUE THREAD

**Issue by Goodfeat** [Ultimaker/Cura#6548] opened 2019-10-17 00:35 UTC
Hello, I found a bug in CURA 4.3
CURA does not generate support if the parameter support_z_distance = 0.0.
not generated if nozzle 0.4 is installed

![1](https://user-images.githubusercontent.com/44455128/66968620-67ad1580-f0c9-11e9-9e1d-2f42b64c5769.PNG)

if the support_z_distance > 0, then everything becomes normal

![2](https://user-images.githubusercontent.com/44455128/66968709-c96d7f80-f0c9-11e9-8bed-4c7dacd4efd0.PNG)

- Windows 10
- Cura 4.3
- Delta printer
- nozzle 0.4
- dual extruder (extr 1 + extr.support)

**Comment by rburema** [comment] 2019-10-18 07:30
Hi @Goodfeat,

If I just follow the reproduction steps it doesn't reproduce for me. Could you attach the project (saved, not exported, you may have to zip it to get github to accept it), please?

cheers,
Remco.

**Comment by Goodfeat** [comment] 2019-10-18 07:50
[альтернатива 0.zip](https://github.com/Ultimaker/Cura/files/3742822/0.zip)
This is an archive with the stl file. I use two nozzles. the second nozzle prints only the bonding layer

**Comment by rburema** [comment] 2019-10-18 09:04
I see.

A workaround is to put either the stair step width or height to a low value.

Maybe related to #6185 which was originally closed as a duplicate, but the fix for the underlying issue was reverted at one point (see #6163 ). Stair-stepping is a piece of code we've had/realised some problems with over the past year or so.

**Comment by Ghostkeeper** [comment] 2019-10-18 09:06
Could you save a project file instead of exporting the STL file? To save a project file you'd need to go to File -> Save. The resulting file not only contains the 3D model but also all of the settings that were used. This way we can reproduce the problem and see what is going wrong with it.

I've also tried to do this with a basic overhanging model but it just generates support as well as support interface fine as expected.

**Comment by rburema** [comment] 2019-10-18 09:36
(Also, while there's probably a reason you do it this way, I thought I'd mention that it may be better to print that model upside down.)

**Comment by Goodfeat** [comment] 2019-10-18 09:51
> (Also, while there's probably a reason you do it this way, I thought I'd mention that it may be better to print that model upside down. so no support is needed.)

Not in this case. I just provided a model by which to reproduce the error.
I am testing printing with two nozzles with plastic PLA

**Comment by rburema** [comment] 2019-10-25 11:06
Seems to happen only on deltabot type printers. If I have a CustomFFF printer with elliptical buildplate and origin at center it doesn't happen. I'm not sure _why_ because there don't seem to be much other parameters different between those situations that could influence this. Perhaps I've overlooked something though.

**Comment by rburema** [comment] 2019-10-25 11:37
Please open a new issue, so we can, for example, open & close them separately.

**Comment by Goodfeat** [comment] 2019-10-25 11:38
Ok

**Comment by rburema** [comment] 2019-11-12 13:36
I've some time to further investigate now, sorry for the wait.

It seems I _can_ reproduce it (on a non-deltabot printer) if I set the layer-height to 0.2 (like in the original). This also happens to the stair-stepping height. Putting the 'support stair step height' to anything below 0.2 will work as a workaround.

**Comment by rburema** [comment] 2019-11-12 14:02
I now think this is a duplicate of #6379 for which we have an internal ticket already (CURA-6808).

**Comment by Goodfeat** [comment] 2019-11-15 06:56
I looked at the problem # 6379,
There you mentioned that the problem is "Support stair step height". 
This topic is about a problem with the parameter "Support Z Distance"
interesting that the problem is very similar

**Comment by rburema** [comment] 2019-11-15 07:10
Yes, but your problem will also go away if you put 'support z distance' to a smaller problem, regardless of what 'support top distance' is. These values interact with each other.

**Comment by Goodfeat** [comment] 2019-11-15 07:19
Really. the problem disappears
This is a "bug" or "particularity" when building supports ?

**Comment by rburema** [comment] 2019-11-15 07:21
This is a bug within the stair-stepping. This is a bit of code we've had trouble with in the past. It seems each time we fix a bug there, another one appears. Fortunately this last one has an easy work-around.

**Closed** 2019-12-03 13:33 UTC
Labels: Status: Duplicate, Type: Bug

**Comment by rburema** [comment] 2020-06-25 13:20
When the time comes (it might be a while) could you check again in 4.7? It seems we finally might've fixed this issue in the master branch.
