### ISSUE TITLE
Cura pause at layer height pauses at wrong layer

### ISSUE THREAD

**Issue by martijnschouten** [Ultimaker/Cura#8305] opened 2020-09-02 20:45 UTC
**Application version**
Cura 4.7.0

**Platform**
Windows 

**Printer**
Diabase H-series

**Reproduction steps**
1. Slice my model with a pause at a height of 0.4 mm. The model has a 0.1mm layer height, a 0.1mm initial layer heigt and a T{initial_extruder_nr} line in the start gcode (but removing that doesn't fix the problem).
2. Save the gcode.

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/6079002/92034304-5286b700-ed6d-11ea-809f-23cd7ec28683.png)

**Actual results**
The gcode includes a pause at the start of the 0.3mm layer and moves back to a height of 0,4mm

**Expected results**
The gcode includes a pause at the start of the 0.4mm layer and moves back to a height of 0,4mm

**Project file**
[model.zip](https://github.com/Ultimaker/Cura/files/5164734/model.zip)

**Log file**
[cura.zip](https://github.com/Ultimaker/Cura/files/5164749/cura.zip)

**Comment by rburema** [comment] 2020-09-04 09:21
Confirmed. It seems the 'current z/height' is set incorrectly during in the pause at height script at this point for some reason.

**Comment by Ghostkeeper** [comment] 2020-09-04 12:32
Duplicate of https://github.com/Ultimaker/Cura/issues/5085. It's a bit of a weird issue, this one. Happens only with certain numbers apparently.

**Closed by Ghostkeeper** 2020-09-04 12:32 UTC
Labels: Type: Bug
