### ISSUE TITLE
[3.5.0] Crashes when trying to load gcode files.

### ISSUE THREAD

**Issue by erispe** [Ultimaker/Cura#4523] opened 2018-10-08 18:24 UTC
**Application Version**

3.5.0

**Platform**

Windows

**Printer**

Original Prusa i3 MK3

**Steps to Reproduce**

Either drag-n-drop a .gcode file into the main window or using File > Open File(s)

**Actual Results**

Program exits to desktop.

**Expected results**

Model should load into the scene. I can load the same gcode files without issue in 3.4.1 and it does not matter if the gcode was generated in 3.50 or 3.4.1, they all work in the previous version and all crash in the newer.

**Additional Information**

[cura.log](https://github.com/Ultimaker/Cura/files/2457207/cura.log)

**Comment by LipuFei** [comment] 2018-10-08 19:02
Hi @erispe , I don't see anything interesting in the log file. If possible, could you send that gcode file you were trying to load? Thanks

**Comment by Drayson80** [comment] 2018-10-09 07:42
Hi! I experience the same issue. 
Cura 3.5
Win10
UMO
same issue description as from erispe...
Gave it a try with very old gcode files and newly sliced gcode. Log-file looks good, no indication also on my side.

**Comment by nallath** [comment] 2018-10-09 07:54
If you don't drag them in but load them via file-> load, does then the same happens? Also, could you share the g-code where this happens?

**Comment by Lundsgaard2** [comment] 2018-10-09 10:53
Same problem here, with a twist.
When I open files i created from scratch using sketchup there is no problem.
Printing items from 3dwarehouse makes Cura 3.5 crash.
It works in earlier versions.

**Comment by LipuFei** [comment] 2018-10-09 10:57
Hi @Lundsgaard2 , if possible, could you share the file(s) that don't work for you? Thanks.

**Comment by Lundsgaard2** [comment] 2018-10-09 11:17
Here You are.

[DoNotWork.zip](https://github.com/Ultimaker/Cura/files/2460133/DoNotWork.zip)

**Comment by LipuFei** [comment] 2018-10-09 12:53
Hi @erispe @Lundsgaard2 , I see that you are using Prusa i3 MK3. Please check https://github.com/Ultimaker/Cura/issues/4497 that we have found the printer profiles provided by prusa3d for MK2S and MK3 don't work in Cura 3.5. Could you check if that's the case for you? If you switch to use a different printer (one that's available in the "Add Machine" list), does this problem still occur?

**Comment by Drayson80** [comment] 2018-10-09 21:42
ok, sorry for late reply  @nallath 
I playd a bit around and it seems that my issue is linked to the SD-card reader....
If I open an old gcode from my SD archive, Cura crashes. 
If I copy the same file to my local disk, it opens correctly...
Attached a file sliced 14/07/2017 with Cura_SteamEngine 2.6.1 for my UMO where I experienced the issue. (just rename it to .
![einkaufswagenchip gcode](https://user-images.githubusercontent.com/10231889/46700374-f36da580-cc1c-11e8-9495-d9b830e830bb.jpg)
gcode)

**Comment by LipuFei** [comment] 2018-10-10 06:08
@szepeu From the log file you uploaded, it crashes on OpenGL. It may have something to do with your graphics card driver. Looks similar to https://github.com/Ultimaker/Cura/issues/4302 but crashes in different ways. Could you update your graphics card driver? If you opened more than one Cura window at the same time, could you try just one? Thanks

**Comment by Lundsgaard2** [comment] 2018-10-10 06:12
Hi LipuFei. I am using AnyCubic I3 Mega and not  Prusa i3 MK3.
![printer](https://user-images.githubusercontent.com/43989513/46716427-40c13580-cc64-11e8-94b3-6660355c3a52.JPG)

**Comment by LipuFei** [comment] 2018-10-10 06:18
Hi @Drayson80 , it sounds like the same problem as https://github.com/Ultimaker/Cura/issues/4502 and https://github.com/Ultimaker/Cura/issues/4495 (fail to open files on Windows on a remote/portable drive), which has been fixed. It will be in the next 3.5 patch release.

**Comment by LipuFei** [comment] 2018-10-10 06:20
@erispe @Lundsgaard2 Could you try opening files that's on your local hard drive, for example `C:\`, and then from some other drive? Does it make a difference?

**Comment by LipuFei** [comment] 2018-10-10 06:33
Hi @szepeu , sorry that ignore my previous comments... I have too many log files and I think I looked at the wrong one...

**Comment by Lundsgaard2** [comment] 2018-10-10 07:01
Ok

Venlig hilsen

Lars Lundsgaard Andersen
Faglærer
la@eucnord.dk<mailto:la@eucnord.dk>

EUC Nord, M. P. Koefoeds Vej 10, 9800 Hjørring
Tlf. 7224 6000  -  www.eucnord.dk<http://www.eucnord.dk/>

Fra: Lipu Fei <notifications@github.com>
Sendt: 10. oktober 2018 08:34
Til: Ultimaker/Cura <Cura@noreply.github.com>
Cc: Lars Lundsgaard Andersen <la@eucnord.dk>; Mention <mention@noreply.github.com>
Emne: Re: [Ultimaker/Cura] [3.5.0] Crashes when trying to load gcode files. (#4523)


Hi @szepeu<https://github.com/szepeu> , sorry that ignore my previous comments... I have too many log files and I think I looked at the wrong one...

**Comment by LipuFei** [comment] 2018-10-10 09:14
Hi @erispe  @Lundsgaard2 @szepeu @Drayson80  , could you try a Cura 3.5.1 candidate build for us? We have a fix for #4495 and wonder if it works for you. Thanks!
Link: https://we.tl/t-0gqXweB9KG

**Comment by Lundsgaard2** [comment] 2018-10-10 11:13
I can`t install.

Venlig hilsen

Lars Lundsgaard Andersen
Faglærer
la@eucnord.dk<mailto:la@eucnord.dk>

EUC Nord, M. P. Koefoeds Vej 10, 9800 Hjørring
Tlf. 7224 6000  -  www.eucnord.dk<http://www.eucnord.dk/>

Fra: Lipu Fei <notifications@github.com>
Sendt: 10. oktober 2018 11:14
Til: Ultimaker/Cura <Cura@noreply.github.com>
Cc: Lars Lundsgaard Andersen <la@eucnord.dk>; Mention <mention@noreply.github.com>
Emne: Re: [Ultimaker/Cura] [3.5.0] Crashes when trying to load gcode files. (#4523)


Hi @erispe<https://github.com/erispe> @Lundsgaard2<https://github.com/Lundsgaard2> @szepeu<https://github.com/szepeu> @Drayson80<https://github.com/Drayson80> , could you try a Cura 3.5.1 candidate build for us? We have a fix for #4495<https://github.com/Ultimaker/Cura/issues/4495> and wonder if it works for you. Thanks!
Link: https://we.tl/t-0gqXweB9KG

**Comment by Lundsgaard2** [comment] 2018-10-10 12:30
Now it works. I can load my “donotwork” and save as gcode.
The printer is busy at the moment but I will test it later.

Venlig hilsen

Lars Lundsgaard Andersen
Faglærer
la@eucnord.dk<mailto:la@eucnord.dk>

EUC Nord, M. P. Koefoeds Vej 10, 9800 Hjørring
Tlf. 7224 6000  -  www.eucnord.dk<http://www.eucnord.dk/>

Fra: Lipu Fei <notifications@github.com>
Sendt: 10. oktober 2018 13:47
Til: Ultimaker/Cura <Cura@noreply.github.com>
Cc: Lars Lundsgaard Andersen <la@eucnord.dk>; Mention <mention@noreply.github.com>
Emne: Re: [Ultimaker/Cura] [3.5.0] Crashes when trying to load gcode files. (#4523)


Hi @Lundsgaard2<https://github.com/Lundsgaard2> , could you provide more specific information on why you can't install? Is it that nothing happens when you double click the installer, or the installation fails at some point, etc.?

**Comment by LipuFei** [comment] 2018-10-10 13:38
@Lundsgaard2 Great to hear. I guess the problem is fixed for you. You can try 3.5.1 once it's released.

**Comment by szepeu** [comment] 2018-10-10 16:53
@LipuFei it does work. However, after regular Cura upgrades since 3.0, minor and major bugs and issues, I'm gonna stay with 15.06 - waaaaaay better performance and actually better gcode quality.

**Comment by LipuFei** [comment] 2018-10-11 06:11
I'll close this issue then.

**Closed by LipuFei** 2018-10-11 06:11 UTC
Labels: Category: Cura, Platform: Windows, Status: Needs Info

**Comment by Lundsgaard2** [comment] 2018-10-11 06:49
Thanks for Your rapid solution ☺

Venlig hilsen

Lars Lundsgaard Andersen
Faglærer
la@eucnord.dk<mailto:la@eucnord.dk>

EUC Nord, M. P. Koefoeds Vej 10, 9800 Hjørring
Tlf. 7224 6000  -  www.eucnord.dk<http://www.eucnord.dk/>

Fra: Lipu Fei <notifications@github.com>
Sendt: 11. oktober 2018 08:12
Til: Ultimaker/Cura <Cura@noreply.github.com>
Cc: Lars Lundsgaard Andersen <la@eucnord.dk>; Mention <mention@noreply.github.com>
Emne: Re: [Ultimaker/Cura] [3.5.0] Crashes when trying to load gcode files. (#4523)


I'll close this issue then.

**Comment by erispe** [comment] 2018-10-12 09:03
@LipuFei, Wow! I forgot to come back this thread for a few days. Was just about to upload a gcode file for you to test and instead you already supplied a new build that fixes the issue. I am truly amazed!
