### ISSUE TITLE
Error while duplicating objects

### ISSUE THREAD

**Issue by HenrikLagercrantz** [Ultimaker/Cura#11280] opened 2022-01-17 10:07 UTC
### Application Version

4.12.0

### Platform

Mac OS Monterey 12.1

### Printer

Ender 3 Max

### Reproduction steps

Multiply object, chose 1. The software pauses at "Placing objects" " Multiplying and placing objects" without completing the task
<img width="485" alt="Screenshot 2022-01-17 at 11 04 02" src="https://user-images.githubusercontent.com/16309031/149749165-c20c6ebc-fcb5-456c-919e-50d136e711be.png">
.

### Actual results

The action is never finished but slicing is still possible so the main thread is not frozen.

### Expected results

Completion and copying of the attached str file.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This is Cura 4.12 that reports crashes if left on when Mac tries to go into sleep mode. These issues might have been addressed in new version.

**Comment by fvrmr** [comment] 2022-01-17 10:32
Hi @HenrikLagercrantz thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/10249 and this is fixed in 4.12.1 and newer. 
Also good to know is that we don't fully support Mac M1 since it is not compatible with a library we are using. Hopefully when we updated these libraries this will solve a lot of issues in the next release. 
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2022-01-17 10:32 UTC
Labels: Type: Bug
