### ISSUE TITLE
Serial port automatically opened by Cura!! Could cause $$$ damage!

### ISSUE THREAD

**Issue by tomb18** [Ultimaker/Cura#6897] opened 2020-01-01 23:40 UTC
When Cura is opened, and just after the opening credits, it is opening a serial port and sends gcode.  It is also toggling DTR on that port.
I see no way to disable this behavior.  There is no configuration for this.  Now in my case, I have many serial ports on my system and some are connected to amateur radio transmitters.  When Cura starts up, it sends a bunch of gcode and toggles DTR on the serial port.  The result is that the transmitter goes into transmit.  In stays in transmit until cura is closed.
I just happen to always set my power out to 0W, but the antenna is not connected.  If the power is at full, it is into a dead short and my $4000 radio will need repair.  Are you going to foot the bill?
I see that there are numerous serial port issues here.  One should not indiscriminately poll serial ports looking for an open connection. The consequences are beyond  a 3D printer bug.
You should fix the serial port problem.

**Comment by Ghostkeeper** [comment] 2020-01-02 00:24
Duplicate of https://github.com/Ultimaker/Cura/issues/5207.

**Closed by Ghostkeeper** 2020-01-02 00:24 UTC
Labels: Type: Bug
