### ISSUE TITLE
Unable to connect to cloud message

### ISSUE THREAD

**Issue by askgdb** [Ultimaker/Cura#5773] opened 2019-05-22 17:07 UTC
**Application Version**
4.0.0
**Platform**
Windows 10
**Printer**
CR10s Pro
**Steps to Reproduce**
trying to open the Marketplaces it sais "Could not connect to the Cura Package Database. Please check your connection"
**Actual Results**
Marketplaces can't connect and I cannot figure out why
![Screenshot 2019-05-22 19 58 17](https://user-images.githubusercontent.com/17203298/58194036-1856ea80-7ccd-11e9-85cd-fe5b7348913e.png)
![Screenshot 2019-05-22 19 58 21](https://user-images.githubusercontent.com/17203298/58194037-18ef8100-7ccd-11e9-8f69-b217c85a3bca.png)
**Expected results**
It's a bug and there is a fix, or something with the server?

**Additional Information**
also, it pop ups a message saying "There was an error connecting to the cloud"

**Comment by egore24** [comment] 2019-05-22 20:18
Receiving same error message of "There was an error connecting to the cloud"

**Comment by Ghostkeeper** [comment] 2019-05-23 07:37
Even though this ticket was slightly earlier, I'm going to close it as a duplicate of https://github.com/Ultimaker/Cura/issues/5774 since that ticket contains somewhat more useful information as to connection debugging. Please continue the conversation there!

**Closed by Ghostkeeper** 2019-05-23 07:37 UTC
Labels: Category: Cloud, Status: In Progress, Type: Bug
