### ISSUE TITLE
[3.4.1] Rotated Model and Scaling Bug

### ISSUE THREAD

**Issue by Inq720** [Ultimaker/Cura#4309] opened 2018-08-30 18:58 UTC
I did a search and an item came up with Rotation and Scaling in the title, but no verbiage in the content seemed applicable.

**Application Version**
3.4.1

**Platform**
Windows 8.1

**Printer**
Original Prusa i3 Mk3

**Steps to Reproduce**
1) Drop/open any model on the workspace
2 ) Rotate it about the X axis by 90 degrees
3) Switch to the Scaling window and uncheck the "Uniform Scaling"
4) Enter 103 into the X% box and the Y and Z stay at 100 as expected.
5) Enter 103 into the Y% box and press enter.  The Z box gets updated to 103 also.
6) If I then mouse click on the Z box (with the intent of changing it back to 100) it changes again on its own to 106.09.
7) If I then brute force it to 100, the Y box drops to 94.26.  Clicking on the Y box, it changes to 88.85 on its own.

**Actual Results**
It's a round robin that never can achieve X = 103, Y = 103, Z = 100.

**Expected results**
Let me type in three separate scaling percentages:  X = 103%, Y = 103%, Z = 100%.

**Additional Information**
If it matters, my simple test model is a 20mm cube with a feature ﻿on one ﻿face﻿.

**Comment by diegopradogesto** [comment] 2018-08-31 07:28
Duplicate of https://github.com/Ultimaker/Cura/issues/4136

**Closed** 2018-08-31 07:28 UTC
Labels: Status: Duplicate
