### ISSUE TITLE
Retraction extra prime amount still has to be positive

### ISSUE THREAD

**Issue by HClO4** [Ultimaker/Cura#3276] opened 2018-02-10 01:14 UTC
Sadly the retraction extra prime amount still can't be negative. I need an negative amount to avoid getting blops.

In #2392 it was mentioned that this issue will be fixed in the following version. In Cura 3.2 the issue is still there :(

**Comment by HClO4** [comment] 2018-02-17 15:35
No one who has the same problem?

**Comment by devils27** [comment] 2018-02-26 04:23
i do, they said it was going to be fixed 3 releases ago and still the same thing.  i dont get it.  smartavonics posted a simple fix to literally just allow cura to allow a negative value the the "extra prime amount" spot in the code and still nothing

**Comment by ianpaschal** [comment] 2018-02-26 07:37
Duplicate of #2392 and #2667. We'll continue the conversation in those threads.

**Closed by ianpaschal** 2018-02-26 07:37 UTC

**Comment by Ghostkeeper** [comment] 2018-03-14 14:52
Seems to work fine for me:
![screenshot from 2018-03-14 15-50-48](https://user-images.githubusercontent.com/2448634/37409867-a209469e-279f-11e8-8bd8-2654cee1f138.png)
