### ISSUE TITLE
Travel-distance dependent retraction distance setting

### ISSUE THREAD

**Issue by alexeyzel** [Ultimaker/Cura#8825] opened 2020-11-24 20:16 UTC
**Is your feature request related to a problem? Please describe.**
I have printer with Bowden tube and I have to set about 6 mm retraction. When printing with PETG when traveling distance is not small - the filament has time to ooze and on unretracting everything is OK. But on short travel distances I get under extrusion after retraction

**Describe the solution you'd like**
Add feature of travel-distance dependent retraction distance setting.

**Describe alternatives you've considered**
I can lower retraction distance but in this case on big travel distances filament will ooze from the extruder and I get overextrusion.

**Affected users and/or printers**
Users with printers with Bowden tubes often using PETG filament.

**Comment by Ghostkeeper** [comment] 2020-11-27 10:24
Duplicate of https://github.com/Ultimaker/Cura/issues/3452.

There is a post-processing script in Cura now called Retract Continue that implements this as a stop-gap measure. It's a bit clunky to use but it works.

**Closed by Ghostkeeper** 2020-11-27 10:24 UTC
Labels: Type: New Feature
