### ISSUE TITLE
Custom supports not slicing

### ISSUE THREAD

**Issue by skywalkerx86** [Ultimaker/Cura#15864] opened 2023-06-22 14:53 UTC
### Cura Version

5.4 beta

### Operating System

Windows 11

### Printer

FLSun V400

### Name abnormal settings

using custom supports

### Describe your model

A helmet dome, it slices fine except when trying to use custom supports

### Add your .zip here ⬇️

[FV_dome.zip](https://github.com/Ultimaker/Cura/files/11835358/FV_dome.zip)

**Comment by MariMakes** [comment] 2023-06-22 15:06
Hey @skywalkerx86,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for trying our Beta and reporting your issues with us.

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/15836
Good news, we think we found a fix that we hope to include in the stable release. 🎉 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/15836

Thanks again for your report, feel free to let us know if you find anything new! 😊

**Closed by MariMakes** 2023-06-22 15:06 UTC
Labels: Type: Bug, Status: Duplicate, Slicing Error :collision:
