### ISSUE TITLE
Rotating Model Making the Scale Changes !!!

### ISSUE THREAD

**Issue by Ruweshed** [Ultimaker/Cura#8507] opened 2020-10-07 03:42 UTC
When i try to Rotate my Model to Fit Within the Printing Area Which Should have Computed by some Button and you Guys missing That Feature,,,, Anyway when i Rotate it on X or Y access its Changing the SCALE of the WHOLE MODEL!!!! WHYYYYYYYYYYYYYY 

Guys you dont have an Automatic  Fitting Button and even Wont let US Rotate with our Same %100 Model Size !!!!!!???

This have to GET FIXED !!

**Comment by konskarm** [comment] 2020-10-07 07:41
This sounds like a duplicate of https://github.com/Ultimaker/Cura/issues/4136. Nevertheless, please fill in the entire [bug template](https://github.com/Ultimaker/Cura/issues/new?assignees=&labels=Type%3A+Bug&template=bug-report.md&title=) so that we can identify the problem clearly.

**Comment by Ruweshed** [comment] 2020-10-07 22:09
Well anyway this could be fixed by Adding some Feature to Fit the Model "AS IT IS" within Printing AREA... i mean Within the PRINTABLE ALLOWED AREA ... is there any Project for such Feature soon??

**Comment by konskarm** [comment] 2020-10-08 07:31
We are currently working on changing our arrange algorithm to a new version, which should deal with this exact problem. I'll close this issue, since the original bug (rotation causes scale to behave weirdly) has been reported again and we want the discussions of similar issues to exist in a single thread (#4136).

**Closed by konskarm** 2020-10-08 07:31 UTC
Labels: Type: Bug
