### ISSUE TITLE
[3.4.1] Cura tree supports start "in the air"

### ISSUE THREAD

**Issue by biz2000** [Ultimaker/Cura#4420] opened 2018-09-24 07:09 UTC
**Application Version**
3.4.1

**Platform**
Windows 7

**Printer**
CR10

**Steps to Reproduce**
Load the trip-ribs1.stl file of this project (too big to attach). BTW trying to save a 3mf file crashes the computer.
https://www.thingiverse.com/thing:2071610

**Actual Results**
Some support start in the air, not linked to the main base standing on the bed.

**Expected results**
Cannot print this way for obvious reasons

**Additional Information**
Screenshot attached.
![treesupportbug](https://user-images.githubusercontent.com/43532919/45940495-b927c580-bfd9-11e8-8514-b9c5366bd7e8.jpg)

**Comment by rburema** [comment] 2018-09-26 07:31
Hi @biz2000, Could you check if the 3.5-BETA works for you? If so, this might be a duplicate of another (fixed) issue. cheers, Remco.

**Comment by diegopradogesto** [comment] 2018-10-02 18:49
Probably duplicate of #3249. That is fixed in the 3.5 version.

**Closed by diegopradogesto** 2018-10-02 18:49 UTC

**Comment by biz2000** [comment] 2018-10-03 06:12
Thanks !

Le mar. 2 oct. 2018 à 20:49, Diego Prado Gesto <notifications@github.com> a
écrit :
