### ISSUE TITLE
Adding materials

### ISSUE THREAD

**Issue by JFougner** [Ultimaker/Cura#10173] opened 2021-07-23 08:22 UTC
### Application Version

4.10.0

### Platform

Windows 10

### Printer

Creality Ender 5 Plus

### Reproduction steps

I need to supplement with the material profile eSUN ePA-CF so I did the following

1. Marketplace
2. Materials
3. eSUN, ePA-CF
4. Install

### Actual results

The marketplace says that the profile is installed but it is not visible in my options under eSUN

Found the downloaded files in C: \ Users \ johan.FOUGNERKONTOR \ AppData \ Roaming \ cura \ 4.10 \ materials. I went to Manage Materials and Import, selected the file I found and got the answer "Successful import"

Still nothing new under material in Manage Materials / eSUN so I tried to create my own profile according to your instructions. As soon as I select that profile, I get the message that the profile does not support and all my set choices of printer profile, material and size of nozzel are planked and must be selected again.

### Expected results

The newly installed material profile should be automatically added to the list of materials available in the Manage Materials database under the correct manufacturer. If the material is not considered by you to be able to be printed on the selected printer, the material text should be gray or red and the choice to activate should remove any barriers from you.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I, like so many others, have a rebuilt printer and have nowhere to choose, for example all metal hotend, direct extruder etc. to be able to decide whether you can print the material or not.

**Comment by fvrmr** [comment] 2021-07-26 12:01
Hi @JFougner thank you for your report. 
This is because the materials in the marketplace are compatible with Ultimaker printers. The problem is indeed that the marketplace doesn't show if it is compatible with your printer. We have a ticket on our backlog to update this. 
Your issue is a duplicate of https://github.com/Ultimaker/Cura/issues/6236 

I will close your issue, since it is a duplicate. Hope you understand.

**Closed by fvrmr** 2021-07-26 12:01 UTC
Labels: Type: Bug
