### ISSUE TITLE
Profile, extruder table is empty

### ISSUE THREAD

**Issue by Inglebard** [Ultimaker/Cura#8888] opened 2020-12-06 13:45 UTC
**Application version**
Cura 4.8

**Platform**
Appimage Linux

**Printer**
Prusa Mk2

**Reproduction steps**
1. Create a profile modify some settings
2. Update the current profile
3. Restart Cura
4. Go to profile manager
5. Extruder table is empty

**Screenshot(s)**
![globalsettings](https://user-images.githubusercontent.com/8203903/101281654-83ddab80-37d0-11eb-95c7-a3cf3eda75f7.png)

![extruder1](https://user-images.githubusercontent.com/8203903/101281652-83451500-37d0-11eb-822e-5f57d8bfdf6b.png)

**Files present in profile :**

[prusa_i3_mk2_extruder_0_prusaplacalcaire.txt](https://github.com/Ultimaker/Cura/files/5648818/prusa_i3_mk2_extruder_0_prusaplacalcaire.txt)
[prusa_i3_mk2_prusaplacalcaire.txt](https://github.com/Ultimaker/Cura/files/5648819/prusa_i3_mk2_prusaplacalcaire.txt)

**Actual results**
In profile manager the extruder table is empty.

**Expected results**
In profile manager the extruder table show the values manually set. The "Setting", "Profile", "Unit" columns should at least be set.
prusa_i3_mk2_extruder_0_prusaplacalcaire.txt contain the value I modify and should be present in the extruder table.
I expect the behavior to be the same as "Global Settings".

**Comment by Ghostkeeper** [comment] 2020-12-08 12:58
Duplicate of https://github.com/Ultimaker/Cura/issues/7626.

**Closed by Ghostkeeper** 2020-12-08 12:58 UTC
Labels: Type: Bug
