### ISSUE TITLE
bug in creating g-code, wall lines

### ISSUE THREAD

**Issue by JediRAMA** [Ultimaker/Cura#9380] opened 2021-03-08 08:41 UTC
### Application Version

4.8.0

### Platform

Win 10

### Printer

Climber 7

### Reproduction steps

i sliced the wall. 1.2mm 0.4 nozzle. 

### Actual results

wall must to be with 3 extruder lines. But cura making mid line twice. Its the same problem for any 3d printer

### Expected results

So one mid line  extruding twice insted once. 
Same action for walls with 1.2mm-3lines, 2mm 5 lines

Even count lines in wall - everything ok. 
Odd count lines in wall - cura extruding mid line twice. 
Few ppl in our community tested this bug on few different printers. Bug exist
[Layer bug.zip](https://github.com/Ultimaker/Cura/files/6099981/Layer.bug.zip)

**Comment by fvrmr** [comment] 2021-03-08 10:30
Hi @JediRAMA thank you for your bug report. 
This is a duplicate of #9356 that's why I will close this issue. In that thread you can read that our Arachne release solves this problem. So please check our Arachne release [here](https://github.com/Ultimaker/Cura/releases/tag/Arachne_engine_alpha). 
Hope you understand, please feel free to continue the thread there.

**Closed by fvrmr** 2021-03-08 10:30 UTC
Labels: Type: Bug
