### ISSUE TITLE
Solidworks Plugin klappt nicht

### ISSUE THREAD

**Issue by Kaicura** [Ultimaker/Cura#10946] opened 2021-11-28 15:38 UTC
### Application Version

Cura Arachne  beta2

### Platform

Win 7

### Printer

SidewinderX1

### Reproduction steps

Start Cura.Cant load Solidworks Plugin message.

### Actual results

cant open SWX Files

### Expected results

no

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7613815/cura.log)

**Comment by fvrmr** [comment] 2021-11-29 10:06
Hi @Kaicura thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/10806
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-11-29 10:06 UTC
Labels: Type: Bug
