### ISSUE TITLE
app shut down pre print 

### ISSUE THREAD

**Issue by srvader95** [Ultimaker/Cura#11861] opened 2022-04-22 04:50 UTC
### Application Version

5.0.0

### Platform

windows 11

### Printer

anyvubic

### Reproduction steps

nothing

### Actual results

nothing

### Expected results

it to work

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

cura keeps crashing during print its the only app on my pc besides mesh mixer

**Comment by nallath** [comment] 2022-04-22 07:43
Please provide us with the log files, we really need this in order to help you.

**Comment by fvrmr** [comment] 2022-04-26 09:57
Hi @srvader95 are you printing via USB?
If so this is a duplicate of https://github.com/Ultimaker/Cura/issues/11896

**Closed** 2022-05-23 20:17 UTC
Labels: Type: Bug, Status: Needs Info
