### ISSUE TITLE
Not working correctly on scaled display since v. 2.6.1

### ISSUE THREAD

**Issue by hyteoo** [Ultimaker/Cura#2218] opened 2017-08-06 19:43 UTC
OS: Windows 10
Display scaling: 200%

Since 2.6.1 it seems like the interface is "shifted" slightly higher. Moving the mouse over the interface is very tricky, mouse pointer has to be lower than elements to actually interact with them.

The menu is also not visible anymore, the interface seems to be shifted by the height of the menu.

Tried again with 2.6, all works fine.

**Comment by fieldOfView** [comment] 2017-08-07 17:05
This has been reported once or twice before and was solved by updating the graphics driver

**Comment by hyteoo** [comment] 2017-08-16 19:22
It doesn't seem to be drivers, I keep up to date with drivers (Dell XPS 15 9550)
Reverting back to older versions (2.6 for ex) works fine
It's something in the 2.6.2 version
Alos checked with 2.7beta, same problem

**Comment by Ghostkeeper** [comment] 2017-08-23 08:42
Duplicate of #2068.

**Closed by Ghostkeeper** 2017-08-23 08:42 UTC
