### ISSUE TITLE
ULTIMAKER CURA FECHA AO TENTAR ADICIONAR OUTRO ARQUIVO

### ISSUE THREAD

**Issue by Cars118** [Ultimaker/Cura#11699] opened 2022-03-22 16:40 UTC
### Application Version

4.12

### Platform

WINDOWS 10

### Printer

CR-10S

### Reproduction steps

ULTIMAKER CURA FECHA AO TENTAR ADICIONAR OUTRO ARQUIVO

### Actual results

ULTIMAKER CURA FECHA AO TENTAR ADICIONAR OUTRO ARQUIVO

### Expected results

ULTIMAKER CURA FECHA AO TENTAR ADICIONAR OUTRO ARQUIVO

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

ULTIMAKER CURA FECHA AO TENTAR ADICIONAR OUTRO ARQUIVO

**Comment by Cars118** [comment] 2022-03-22 17:09
Good afternoon,
I'm sorry, I didn't mean to shout, but I didn't know how to fill out
the form in the best way.
The problem that is happening to me is when I want to open several
files in Cura, it automatically closes the program, there will be a
solution for that.
thanks
Carlos Silva


A terça, 22/03/2022, 16:55, Aldo Hoeben ***@***.***> escreveu:

**Comment by Cars118** [comment] 2022-03-23 11:07
Good morning,
I appreciate the availability to help me,
 I uninstalled chitubox and it solved the problem and I can now open
several files at the same time.
 I just can't see the preview of the files in the files to know what object
it is.
 Is there any feature or update to get the preview to work?
Thanks,
Carlos Silva

Em ter., 22 de mar. de 2022 às 18:26, Aldo Hoeben ***@***.***>
escreveu:

**Comment by fvrmr** [comment] 2022-03-24 12:49
Duplicate of https://github.com/Ultimaker/Cura/issues/9668 then.

About the preview you can install a stl thumnail viewer like this one: https://github.com/unlimitedbacon/stl-thumb

I will close this because it is a duplicate.

**Closed by fvrmr** 2022-03-24 12:49 UTC
Labels: Type: Bug
