### ISSUE TITLE
Error that models do not fit, but they do.

### ISSUE THREAD

**Issue by Hajto** [Ultimaker/Cura#10164] opened 2021-07-21 13:56 UTC
### Application Version

4.10.0

### Platform

Mac OS

### Printer

Ender 3 V2 modded (not applicable though)

### Reproduction steps

Put Models on the build plate
Try arranging them

### Actual results

Program say don't fit

### Expected results

They actually do and there is abundance of space

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

<img width="1792" alt="Zrzut ekranu 2021-07-21 o 15 45 40" src="https://user-images.githubusercontent.com/8336429/126499969-4b41c394-4cd7-4e70-a077-ec1f7c490ae3.png">
<img width="1792" alt="Zrzut ekranu 2021-07-21 o 15 45 27" src="https://user-images.githubusercontent.com/8336429/126499989-8fa3841b-253a-45e7-86c5-9311fc29128e.png">
[Archiwum.zip](https://github.com/Ultimaker/Cura/files/6856238/Archiwum.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/6856262/cura.log)

**Comment by fvrmr** [comment] 2021-07-22 08:55
Hi @Hajto thank you for your bug report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9793 there you can read that this is happening because we are depended of the library we use for arranging models.

I will close this ticket as a duplicate, hope you understand.

**Closed by fvrmr** 2021-07-22 08:55 UTC
Labels: Type: Bug
