### ISSUE TITLE
Windows 10 cross dependency development CuraEngine alias

### ISSUE THREAD

**Issue by phedg1** [Ultimaker/Cura#12758] opened 2022-07-13 22:05 UTC
### Application Version

5.1 branch

### Platform

Windows 10

### Printer

Ultimaker Doesnt Matter

### Reproduction steps

Create a new folder to be your workspace. Create a Cura folder in this directory as well as a CuraEngine folder. Clone both repos into their respective directories. Select the 5.1 branch on both directories. Open the powershell on Windows 10. Follow the steps in the "Running Cura from source" wiki page in the section "Configuring Conan (All OSes)". Also remove the cura remote because I'm not an official dev. Then run the editable command from the "Cross dependency development (All OSes)" section. Lastly, run the install command from the "Initializing a Virtual Python Development Environment (All OSes)" section.

### Actual results

After only a handful of seconds you will see:
ERROR: Alias definition error in curaengine/latest@ultimaker/stable: 'CuraEngineConan' object has no attribute 'alias'

### Expected results

I expected that the cura conan install would proceed successfully.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I am unsure which branches are required for this to function on Windows 10. I am also unsure how to go about manually adding a CuraEngineConan object alias manually as a work around.. I have read, re read and checked again the steps on the wiki pages and I'm pretty sure I'm following them right. If anybody can point me in the right direction, that would be really helpful.

I am wanting to make just a few small changes to the cura engine to use in the cura application, but when I tried to do it the old way I found I could not get troubleshooting support because this project is closer to doing things the new way now. So hence I'm trying to do it the new way, even though that isn't fully implement yet it would seem.

**Comment by jellespijker** [comment] 2022-07-15 14:05
@phedg1 is this still an issue?
Even after you remove your Conan data cache and reinstalled the Conan config?
```
conan remove "*" -f
conan config install https://github.com/ultimaker/conan-config.git
```
I know the current state of the development environment is suboptimal at best. But as you correctly state we are full on working on this atm. So things might change on an hourly basis. Our first priority at this time is to ensure that we can build the Cura-5.1.0 release version. Which should be released next week. After that we will focus on fixing these kind of problems in a sustainable way. Which will in likelihood take up two sprints (4 weeks) in total.

So rest assure we are working on it.

**Comment by phedg1** [comment] 2022-07-16 01:48
@jellespijker 

I am now getting a different issue. The error message is no longer about the alias of CuraEngine, but that curaengine could not be found in the remotes.

My steps were:
Move onto the main branch of Cura (commit 298181ab...)
Move onto the main branch of CuraEngine (commit d1946e6f...)
Open the powershell.
Run: pip uninstall conan
Delete the .conan directory from C:\Users\Me\
Run: pip install conan --upgrade
Run: conan config install https://github.com/ultimaker/conan-config.git
Run: conan profile new default --detect --force
Run: conan remote remove cura
Enter my CuraEngine root directory in the terminal.
Run: conan editable add . curaengine/latest@ultimaker/stable
Go up one directory and enter my Cura root directory in the terminal.
Run: conan install . cura/5.1.0-beta@ultimaker/stable --build=missing --update -o cura:devtools=True -g VirtualPythonEnv

The last output lines were:
curaengine/5.1.0: Not found in local cache, looking in remotes...
curaengine/5.1.0: Trying with 'cura-ce'...
curaengine/5.1.0: Trying with 'conan-center'...
ERROR: Failed requirement 'curaengine/5.1.0' from 'conanfile.py (cura/5.1.0-beta@ultimaker/stable)'
ERROR: Unable to find 'curaengine/5.1.0' in remotes

Based on that I have a suspicion that this has to do with this two commands:
conan editable add . curaengine/latest@ultimaker/stable
conan install . cura/5.1.0-beta@ultimaker/stable --build=missing --update -o cura:devtools=True -g VirtualPythonEnv

And more specifically to do with the package listings. Should that be using the beta and or stable bits? Should either of those be testing or empty or I have no idea? Just a thought.

**Comment by jellespijker** [comment] 2022-07-16 09:01
Did you also pull in the latest changes on the `5.1` or `main` branch from the Curb repo?

**Comment by jellespijker** [comment] 2022-07-16 09:10
Try your previous command on the `5.1` branch.

The problem is that it will try to get the requirements for `5.1.0` from the `conandata.yml`, but that version isn't released yet. A quick solution would be to copy the entry `None` in that file and rename the copy to `5.2.0` 
Then change your version in the `conan install` command to `5.2.0`

**Comment by jellespijker** [comment] 2022-07-16 09:16
Alternatively you can add a `--require-override=curaengine/latest@ultimaker/testing` at the `conan install` but you would have to do that for each requirement as well

**Comment by phedg1** [comment] 2022-07-17 02:45
So, after doing what you said, I'm back to the original alias issue.

ERROR: Alias definition error in curaengine/latest@ultimaker/stable: 'CuraEngineConan' object has no attribute 'alias'

Does this command need to be changed somewhat to give it an alias?
conan editable add . curaengine/latest@ultimaker/stable

I tried replacing the stable part with testing but it was the same deal, only saying testing in the error instead.

**Comment by phedg1** [comment] 2022-07-25 21:39
@jellespijker I'm still getting this alias issue. I've seen that 5.1 has got an official release now, do you have an incredibly rough eta for when this might be fixed?

**Comment by jellespijker** [comment] 2022-07-26 13:48
The cura-ce authorization issue should be fixed now.

With these kind of errors be sure to empty the Conan cache before you try again:
```
conan remove "*" -f
```
 And then try again

**Comment by phedg1** [comment] 2022-07-28 22:12
Ok, it is no longer asking for login details. After setting an alias this way, I now get the following error:
ERROR: C:\Users\Peter\Documents\3D_Print\_Software\Workspace\CuraEngine\conanfile.py: maximum recursion depth exceeded in comparison

What should I do now?

**Comment by MariMakes** [comment] 2022-08-24 15:38
Hey @phedg1, 

I'm not very knowledgeable in building from source.... yet... 👼 

But I know we updated our documentation a few days ago. 
So it might have some helpful input, you can check it here.
https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source

If it does not have the information you are looking for, can you let us know and tag @jellespijker ? 
He knows a lot about running development CuraEngine! 💪

**Comment by jellespijker** [comment] 2022-08-24 18:43
@phedg1 if this still not works for you it might be an idea to do a video call. Because I know you're trying to set this up for a while now.

**Closed as completed** 2022-09-09 12:41 UTC
Labels: Type: Bug, Status: Needs Info, Status: Under Investigation
