### ISSUE TITLE
[3.1] Python Error after upgrade

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ultimaker/Cura#2837] opened 2017-11-24 12:27 UTC
Win10/64, DX 12, Nvidia TI750, drv: 388.13.

![ice_screenshot_20171124-142536](https://user-images.githubusercontent.com/30949968/33210611-9f875604-d123-11e7-8c00-b9c109a6d236.png)

**Comment by Thisismydigitalself** [comment] 2017-11-24 13:00
[3.1B CrashLog.txt](https://github.com/Ultimaker/Cura/files/1501709/3.1B.CrashLog.txt)

**Comment by alekseisasin** [comment] 2017-11-24 14:13
Probably the problem is not related to your OpenGLVersion, from the log file I see the error occurs while initializing containter (it other word printer settings). 
I assume you have used custom printers in your previous cura version, if yes then can you provide additional information about them. To do this you can run old Cura load any model and save as project. (and share in github) The saved project will contain information of the used printer. This information might help us to understand better the issue.

**Comment by Appesteijn** [comment] 2017-11-24 15:49
Also reported at the forum: https://ultimaker.com/en/community/52135-ultimaker-cura-31-beta?page=1#reply-193559

**Comment by Thisismydigitalself** [comment] 2017-11-24 17:16
What should I be practicing to get this fixed?
Any file i should replace to get going?

**Comment by fieldOfView** [comment] 2017-11-24 18:20
Zip up your configuration folder (%APPDATA%\cura) and post it somewhere where it can be downloaded. Something is going wrong while loading your configuration, and we don't know what (yet).

The way to get it going would be to clear out the configuration folder (but leave the folder itself in place), but that will remove all your profiles so it should not be considered a solution.

**Comment by Thisismydigitalself** [comment] 2017-11-24 18:58
Unbelievable. 
Went into user folder, deleted my printer's *.inst.cfg file and Cura 3.1 is now up and running but without my printer which i will try to set again from scratch.

**Comment by Thisismydigitalself** [comment] 2017-11-24 19:02
Ok. this file is defiantly the culprit. 
[BW_current_settings.inst.zip](https://github.com/Ultimaker/Cura/files/1502396/BW_current_settings.inst.zip)

**Comment by Thisismydigitalself** [comment] 2017-11-24 19:17
I hope my findings will help fixing this bug.

![ice_screenshot_20171124-211558](https://user-images.githubusercontent.com/30949968/33222026-c34f9144-d15c-11e7-806a-fe9b914fe22c.png)

**Comment by Drayson80** [comment] 2017-11-25 09:16
Same error happens on my side - have also a custom printer/derivate of UMO printer profile...

**Comment by alekseisasin** [comment] 2017-11-27 09:35
@Thisismydigitalself Can you upload your file again? The file which you uploaded is corrupted and cannot be opened.

**Comment by fieldOfView** [comment] 2017-11-27 10:08
@alekseisasin, the file @Thisismydigitalself is not actually a zip, but he renamed it to be a zip so he could attach it here.

@Thisismydigitalself, the file does not give is much information to go on, without the context of the rest of your configuration folder. Could you upload a zipped copy of your whole (not working) configuration?

**Comment by ChrisTerBeke** [comment] 2017-11-27 14:27
Actually the folder that represents the 3.0.x state would be quite useful as well so we can check the upgrading procedure between the versions for your specific configuration. The 3.1 folder might already have corrupted files which would be harder to check.

**Comment by ChrisTerBeke** [comment] 2017-11-27 14:28
(also we did a lot of fixes already, so bluntly loading your 3.1 config into our latest 3.1 local builds might cause a lot of other issues that we'll never encounter in real life).

**Comment by LipuFei** [comment] 2017-12-13 09:48
This is the same issue as https://github.com/Ultimaker/Cura/issues/2837

**Comment by ChrisTerBeke** [comment] 2017-12-13 18:35
#2837 is this issue indeed :P

**Comment by Ghostkeeper** [comment] 2018-01-01 16:42
So I believe the currently accepted answer to this one is: The upgrade from 3.0 to 3.1 left the folder in an invalid state. It's fixed in 3.2 but users of 3.1 will have to do a factory reset.

Or am I mixing up things now?

**Closed** 2018-03-02 21:30 UTC
Labels: Category: Cura, Status: Fixed, Type: Bug
