### ISSUE TITLE
multiple models are sliced wrong (same models)

### ISSUE THREAD

**Issue by jeroensomers** [Ultimaker/Cura#1223] opened 2016-12-07 13:42 UTC
When duplicating a model multiple times (or just opening the same model multiple times), some models aren't sliced correctly.
In this particularly case its the hook at the side of the model.
![2016-12-07_13-30-44](https://cloud.githubusercontent.com/assets/7030107/20969439/3e1b4ae2-bc89-11e6-8044-9c4676cdb393.jpg)
When deleting the model that is good it turn's the other models in 1 good and 1 wrongly sliced.
![2016-12-07_13-31-06](https://cloud.githubusercontent.com/assets/7030107/20969466/639cf522-bc89-11e6-9521-d1f061c3f656.jpg)

I attached the .stl file and my profile settings so you can try it yourself.

[stl and profile.zip](https://github.com/Ultimaker/Cura/files/636687/stl.and.profile.zip)
I'm using Cura 2.3.0

I tried reloading the model through different ways (dragging and dropping it in and through the menu).
I tried turning the model and mirroring the model, nothing seems to help.

**Comment by peteruithoven** [comment] 2016-12-07 14:22
This also happens with the default Normal Quality profile (using Ultimaker 2). 
It's probably causes by overlapping shapes:
![overlap](https://cloud.githubusercontent.com/assets/523210/20971072/6dda4498-bc90-11e6-845c-6264ac098473.png)
For some reason it doesn't happen when I set the `Print sequence` setting to `One at a time`. 
For some reason it seems to be influenced by the `Print sequence` setting, changing that sometimes "fixes it", even in `All at Once` mode, but this is very unpredictable.

**Comment by fieldOfView** [comment] 2016-12-07 14:35
Switching to One at a Time and back probably pushed the objects further from eachother.

**Comment by Ghostkeeper** [comment] 2016-12-08 08:37
Also, One At A Time mode basically runs most of the process in the engine separately for every object and then appends the g-code in sequence.

**Comment by Ghostkeeper** [comment] 2016-12-08 09:19
I can't reproduce this :( Not with the provided models and settings. It prints the little hook properly on all three copies.

I had scaled the mesh to 50%.

**Comment by peteruithoven** [comment] 2016-12-08 09:50
So unfair ;) 
We scaled them to 30% but that can't hardly matter. 
You tried Normal Quality / Jeroen's profile? Print sequence All at once? 

When I separate them in 3 stl's (ear, outer ring and inner gears) and merge those in Cura it seems to work without issues.

**Comment by Ghostkeeper** [comment] 2016-12-08 10:40
Yup, using the profile in the .zip.

**Comment by peteruithoven** [comment] 2016-12-12 14:39
Ultimaker 2, Normal Quality, model 30% scaled, then duplicated 3 times. Moving the third shape 2mm to the right:
![screenshot from 2016-12-12 15 36 51](https://cloud.githubusercontent.com/assets/523210/21103053/10779e3c-c081-11e6-8db6-9fc7dbbfa491.png)
![screenshot from 2016-12-12 15 38 28](https://cloud.githubusercontent.com/assets/523210/21103052/1076eb2c-c081-11e6-8f66-1b3b6ef50b39.png)

Looks like something is wrong with the `Union Overlapping Volumes` feature when models are positioned to close to each other? 

File: [Gear BearingV1 (7).stl.zip](https://github.com/Ultimaker/Cura/files/646159/Gear.BearingV1.7.stl.zip)

**Comment by Ghostkeeper** [comment] 2016-12-12 22:04
I did get this reproduced at home on 2.3.0 (I tried it at home previously as well). Though it didn't position the models in the exact same places for me, it still occurred.
Perhaps I should try a bit harder when I'm at work with 2.4.

This is the build plate I used using Ultimaker 2, Normal Quality defaults:
[UM2_Gear BearingV1 (7).zip](https://github.com/Ultimaker/Cura/files/647343/UM2_Gear.BearingV1.7.zip)
I would've exported a workspace, but of course that feature is not available yet in this ancient version ;)

**Comment by Ghostkeeper** [comment] 2016-12-14 08:26
I still can't get this to reproduce in 2.4. We did change a few things around with how the outlines are generated though. Perhaps this fixed it.

**Comment by peteruithoven** [comment] 2016-12-19 17:22
Awesome work guys! It seems to be fixed in 2.4 (from the ppa):
![screenshot from 2016-12-19 18 18 39](https://cloud.githubusercontent.com/assets/523210/21322020/98b5a3ca-c617-11e6-8c6f-5a67a3072fee.png)

(Also really digging the settings filter and multiply features)

**Comment by fieldOfView** [comment] 2016-12-19 17:35
> (Also really digging the settings filter and multiply features)

(thanks)

**Closed** 2016-12-20 01:10 UTC
