### ISSUE TITLE
The middle of the object is filled with skin?

### ISSUE THREAD

**Issue by bishop-5** [Ultimaker/Cura#8781] opened 2020-11-16 12:02 UTC
The middle of the object is also filled with skins and infills.
Is this a bug? Or does it depend on settings?
![err](https://user-images.githubusercontent.com/74541597/99250232-ae31ee00-284e-11eb-98e8-3f1aadcb9267.jpg)

[CFFFP_test.zip](https://github.com/Ultimaker/Cura/files/5546045/CFFFP_test.zip)

**Comment by eskeyaar** [comment] 2020-11-16 12:17
You have 3 walls, reduce to 2 see your infill.
![image](https://user-images.githubusercontent.com/6142521/99251697-b285e900-2805-11eb-9ad2-071a1ec7b0f6.png)

**Comment by bishop-5** [comment] 2020-11-16 12:27
I found this in a printout I was working on.
So I created a test object to upload to the board.
I can't reduce the walls to keep the printout strong.
Is there another solution?

**Comment by eskeyaar** [comment] 2020-11-16 14:38
You have small model part, so when printing with 3 walls, it automatically takes as single line. Change ur skin overlap percentage to low value, then you can get single line inside the wall.  or   reduce wall to 2, and make infill to 100%, to make strong parts.

**Comment by konskarm** [comment] 2020-11-16 15:26
This is caused by the "Fill Gaps Between Walls", which if it is set to "Everywhere" may result in overlapping infill and skin. Duplicate of https://github.com/Ultimaker/Cura/issues/8724.

**Closed by konskarm** 2020-11-16 15:26 UTC
Labels: Type: Bug
