### ISSUE TITLE
Cura 5 beta 1 incorrect slicing

### ISSUE THREAD

**Issue by rondlh** [Ultimaker/Cura#12112] opened 2022-05-06 08:48 UTC
### Application Version

5 beta 1

### Platform

Windows 10

### Printer

Custom

### Reproduction steps

1. Import the model
2. Slice it
3. Check the preview
![Circle_Test_model_view](https://user-images.githubusercontent.com/77279634/167098260-4a087cb0-84be-45c6-9e42-ff2f016e3139.png)

### Actual results

Incorrect slicing
![Circle_Test_Sliced_view](https://user-images.githubusercontent.com/77279634/167098270-8d548c35-cc6d-4f20-b994-2e1ea065e1a9.png)

### Expected results

Proper slicing

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

I attached the STL, project and created Gcode. 
The model STL parts have 0.6mm width. The used printer nozzle is also 0.6mm. I noticed that the slicing is fine for another printer with a 0.5mm nozzle.

[Circle_test STL 3MF GCODE.zip](https://github.com/Ultimaker/Cura/files/8638723/Circle_test.STL.3MF.GCODE.zip)

**Comment by rondlh** [comment] 2022-05-06 15:45
> That is not an acceptable model for "Spiralize Outer Contour".

Good catch! I didn't mean to use this mode, but still a bit odd.

**Comment by GregValiant** [comment] 2022-05-06 21:00
It needs to be solid all the way through.  A glass full of water to the brim would work.  An empty glass or a half full glass would not.  In the case of the empty glass a slice would pass through the outer wall into solid, then out the inner wall into air, then back into solid and finally back into air.  There would be an inner ring and an outer ring and that would require travel moves to get from one to the other.
I think that's what you are seeing there.  Cura tried to spiralize but there were too many walls and that resulted in a lot of travel moves all over the place and then back to the layer start point.

**Comment by fvrmr** [comment] 2022-05-19 12:08
Hi @rondlh thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11843, as a workaround you can enable `remove holes`.
I will close this issue, since it is a duplicate.

**Closed by fvrmr** 2022-05-19 12:08 UTC
Labels: Type: Bug
