### ISSUE TITLE
can't save to sd card

### ISSUE THREAD

**Issue by rawdilz** [Ultimaker/Cura#2057] opened 2017-07-03 01:06 UTC
it works the first time i save to card but if i clear the plate and try to save another project it doesn't save it. i have to close cure and reopen.

**Comment by kr15uk** [comment] 2017-07-05 11:17
Same here.
I'm still able to save by manually browsing through the "Save File"
I'm on macOS 10.12.5, Cura 2.6.1

**Comment by Ghostkeeper** [comment] 2017-07-06 09:26
Duplicate of https://github.com/Ultimaker/Cura/issues/2024 and https://github.com/Ultimaker/Cura/issues/2038.

**Closed** 2017-07-06 09:26 UTC
Labels: duplicate
