### ISSUE TITLE
Scaling to main monitor instead of where it opens

### ISSUE THREAD

**Issue by tlhintoq** [Ultimaker/Cura#11481] opened 2022-02-15 02:19 UTC
### Application Version

4.13.1

### Platform

Win10x65

### Printer

Ender3pro

### Reproduction steps

Multiple monitors on laptop.
Main (built-in) is a 4k
Cura opens to monitor 2 at 2560x1080 ultrawide monitor.
Cura seems to be scaling to the 4k resolution so magnifying a huge amount .
Should be scaling to the monitor it is on.
Does not rescale to match the monitor it is moved to.

![2022-02-14_21-11-28](https://user-images.githubusercontent.com/11351506/153979796-6d09d501-0d0a-4c48-92e5-a8a3be9b4830.jpg)
![StealthDeck_Screens](https://user-images.githubusercontent.com/11351506/153979920-a7cabd0c-98f0-4143-b6ca-be690690c5e0.jpg)

### Actual results

Cura seems to be scaling to the 4k resolution so magnifying a huge amount .

### Expected results

Should be scaling to the monitor it is on.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Nothing additional

**Comment by fvrmr** [comment] 2022-02-15 16:12
Hi @tlhintoq thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/8966 and we have a ticket on our backlog related to this.
I will close this issue, since it is a duplicate.

**Closed by fvrmr** 2022-02-15 16:12 UTC
Labels: Type: Bug
