### ISSUE TITLE
Cura 4.9 crashes after opening any stl

### ISSUE THREAD

**Issue by electricJP** [Ultimaker/Cura#9688] opened 2021-04-25 13:18 UTC
### Application Version

4.9

### Platform

Win 10

### Printer

Custom Core XY

### Reproduction steps

1- launch Cura 4.9
2- open a stl file (same files load no problem in Cura 4.6 to 4.8)

### Actual results

Crash

### Expected results

no crash

**Comment by electricJP** [comment] 2021-04-25 13:20
[cura.zip](https://github.com/Ultimaker/Cura/files/6371999/cura.zip)

**Comment by nallath** [comment] 2021-04-28 08:25
Looks to be a duplicate of #9648

**Closed by nallath** 2021-04-28 08:25 UTC
Labels: Type: Bug

**Comment by electricJP** [comment] 2021-04-28 12:03
Well, not really the same. I can browse folders without any issue. Cura will crash only when I try to open a file. Anyway, I will wait for the next release.
