### ISSUE TITLE
Preview does not always show in Cura 4.8 on Mac OS 11.2

### ISSUE THREAD

**Issue by klmullen** [Ultimaker/Cura#9407] opened 2021-03-16 02:22 UTC
### Application Version

4.8.0

### Platform

Mac OS 11.2.3

### Printer

CR6SE or Ender3 

### Reproduction steps

Loaded  an STL file to slice. After verifying the slicer settings I chose "Slice" then clicked on "Preview"

### Actual results

The display area was blank in Preview mode. I tried resetting the view but still saw nothing. 

### Expected results

I should see a preview of the sliced model. This doesn't always happen but it's enough that I find It annoying. 

Here's a simple before and after and the Cura log file.

[cura.log](https://github.com/Ultimaker/Cura/files/6145624/cura.log)

<img width="2136" alt="Screen Shot 2021-03-15 at 9 05 37 PM" src="https://user-images.githubusercontent.com/6502440/111245495-b880b080-85d2-11eb-9710-4b97d6c1a8d7.png">
<img width="2135" alt="Screen Shot 2021-03-15 at 9 06 11 PM" src="https://user-images.githubusercontent.com/6502440/111245506-bc143780-85d2-11eb-8e25-a19f99a4e40f.png">

**Comment by fvrmr** [comment] 2021-03-16 08:24
Hi @klmullen thank you for your report.
This is a duplicate of #8745 
We are working on a solution and we already have done a test build that will fix this problem. Progress with the upgrade of the Qt version is still ongoing. There are other crashes still to solve now.

Because this is a duplicate I will close this issue.

**Closed by fvrmr** 2021-03-16 08:24 UTC
Labels: Type: Bug

**Comment by klmullen** [comment] 2021-03-17 23:31
Thanks
