### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by TatosBR** [Ultimaker/Cura#10883] opened 2021-11-19 21:38 UTC
### Application Version

4.12

### Platform

windows 10

### Printer

Ender 5 plus

### Reproduction steps

When I want to open a file from cure, the program closes.

### Actual results

The program closes

### Expected results

no closing

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none

**Comment by nallath** [comment] 2021-11-20 13:30
Please check https://support.ultimaker.com/hc/en-us/articles/4402996140946-Ultimaker-Cura-crashes-when-opening-any-file

Alternatively, it could be that this is a duplicate of https://github.com/Ultimaker/Cura/issues/9644, but without log files it's impossible to tell.

**Closed** 2021-12-04 13:47 UTC
Labels: Type: Bug, Status: Needs Info
