### ISSUE TITLE
Cura 3.2 always crashing while slicing : CURAengine.exe stop working

### ISSUE THREAD

**Issue by nurayha** [Ultimaker/Cura#3309] opened 2018-02-14 09:25 UTC
Cura 3.2 keep on crashing while slicing stl file.

Update:
Thanks @smartavionics for the advice.

I was using normal/default setting. Right after installing Cura 3.2, I just drag in a simple cube to test it and while in the middle of slicing the cube, the pop up window says CuraEngine.exe has stop working came out. I've tried a few times reloading stl model, change to another stl file, and even uninstall & install Cura 3.2 back with a newly downloaded installer, the same problem still occurs.
![cura crash](https://user-images.githubusercontent.com/36472427/36199074-6ee32002-11b3-11e8-88f8-b917d6e6404d.jpg)
Need help on this.
Thanks.

**Comment by smartavionics** [comment] 2018-02-14 09:27
With all due respect, that's a completely useless report. You need to provide more info such as what profile you were using, what model, etc. Without that info, there's no chance that your issue will be investigated. Thanks.

**Comment by nurayha** [comment] 2018-02-14 10:26
Same problem with another stl file.
![cura crash 2](https://user-images.githubusercontent.com/36472427/36199449-997da4c6-11b4-11e8-9d4c-d1e0ddaae313.jpg)

**Comment by smartavionics** [comment] 2018-02-14 10:30
OK, thanks for providing some info. Now, what version OS are you using? How much memory is in the machine? Can you locate the cura.log file and post it here?

Actually, I am not a good person to talk to about this because I don't use Windows. Hopefully, someone else can pick this up.

**Comment by nurayha** [comment] 2018-02-14 10:35
This is my computer spec
![image](https://user-images.githubusercontent.com/36472427/36199767-81ae4ec6-11b5-11e8-9141-54e7093ec258.png)

I'm sorry, but may I know what is the cura.log file?

**Comment by Vandrasc** [comment] 2018-02-14 11:44
Hi @nurayha, you can find your log files in Cura itself, Launch Cura -> Help menu->Show configuration folder or in C:\Users\<username>\Appdata\Roaming\cura\3.2

I doubt the log will show something about the crash though, I do hope so. 

This happens after the upgrade from a previous version? Could you check your **Roaming and Local** folder and see if there is another version mentioned, except the 3.2? If so, then you can remove the older directory and restart Cura, be sure to backup your Cura folder if you don't want to lose any important files. 

Please let us know if this fixed your problem, thank you!

**Comment by nurayha** [comment] 2018-02-14 12:17
Hi @Vandrasc ,
Thanks for the advice. I will try it and update you guys soon during office hour in my country, since I installed the Cura at the office.
Cheers.

**Comment by nurayha** [comment] 2018-02-15 02:09
Good day everybody,
So I guess this is where the log data is located.
So what should I do next?
Now even with the Cura 3.2.1 version,  I'm still having the same problem. I think it could be my computer problem since it works ok in my other PC.
![image](https://user-images.githubusercontent.com/36472427/36237634-0532f4a4-1238-11e8-9f3a-25df3c86f9b2.png)

**Comment by EvilGreenOne** [comment] 2018-02-16 20:48
I am having this same issue today after updating to 3.2.1 from 3.1.

Reinstalled 3.1 in parallel with 3.2.1; 3.1 slices the same file with the same profile fine.

All previous profile directories have been removed from /AppData/Roaming/cura

System Info:
Edition: Windows 10 Pro
Version: 1709
OS Build: 16299.248
System Type: 64-bit
Installed RAM: 32 GB

```
Windows Error Event 1000 for the process:
Faulting application name: CuraEngine.exe, version: 0.0.0.0, time stamp: 0x5a840e96
Faulting module name: CuraEngine.exe, version: 0.0.0.0, time stamp: 0x5a840e96
Exception code: 0x40000015
Fault offset: 0x000000000020e212
Faulting process id: 0x3a20
Faulting application start time: 0x01d3a76391e6b56c
Faulting application path: C:\Program Files\Ultimaker Cura 3.2\CuraEngine.exe
Faulting module path: C:\Program Files\Ultimaker Cura 3.2\CuraEngine.exe
Report Id: 20c9f2d0-7701-4061-8529-27ec11681f95
Faulting package full name: 
Faulting package-relative application ID: 
```
Cura Log file with this event only - Startup to Crash.
[cura.log](https://github.com/Ultimaker/Cura/files/1732737/cura.log)

File sliced does not matter, but for this test I was using a TPU profile and this model:
https://www.thingiverse.com/thing:2510970

**Comment by Vandrasc** [comment] 2018-02-17 11:23
Thank you both for sharing, unfortunately we are not able to reproduce, could you please zip your 3.2 user configuration and share the folder with us? 
And you both removed your older configuration (3.0, 3.1) and it still occurs with a clean install?

**Comment by EvilGreenOne** [comment] 2018-02-17 14:49
This was an upgrade install.  However, prior to adding to this report I followed the trouble shooting tips given previously and had removed all of the previous user directories for prior versions.

If it will help, I can remove both 3.1 (Which I reinstalled to get some slicing done), and 3.2 and try with a completely blank config.  That is not really a solution for me though as I have a customer printer configured and my own library of materials and profiles.

Attached is the entire 3.2 user directory from the affected install.
[3.2.zip](https://github.com/Ultimaker/Cura/files/1733748/3.2.zip)

I did that totally clean install with no previous profiles to be auto-imported and the cura engine does not crash.  I forgot just how many of the useful features are hidden by default.  It's like using a completely different application!  I guess it is back to 3.1 for now just because I do not have the patience to re-setup my printer and profiles.

**Comment by fieldOfView** [comment] 2018-02-17 14:51
I have not looked at your files, but check the layer height and the initial layer height. I have seen someone reporting that the crash happens when the layerheight is higher than the initial layer height.

**Comment by EvilGreenOne** [comment] 2018-02-17 15:00
With the user profile restored that makes it crash.  I tried the following:
Layer Height: .2
Initial Layer Height: .3
- Crash

Layer Height: .2
Initial Layer Height: .2
-Crash

Layer Height: .4
Initial Layer Height: .3
-Crash

None of the combinations I tried, Lower/Higher, Even, Higher/Lower remediated the issue.

**Comment by fieldOfView** [comment] 2018-02-17 19:54
Thanks for trying

**Comment by Ceteak** [comment] 2018-02-18 08:36
See if adaptive layer is on , mine kept crashing when slicing as well, but would only crash the slicing part of the program i could still move the STL and change settings when i turned adaptive layer off it sliced fine

**Comment by Vandrasc** [comment] 2018-02-18 09:45
@EvilGreenOne, I could indeed reproduce your issue with your configuration, I think it has to do with the Enable retraction children settings, Retraction speed, Retract speed and Prime speed. I noticed that the retraction was disabled and after enabling it those children settings show an error value. I customized the children settings (from 0.0 change to 0.1mm/s) of the retraction and I was able to successfully trigger a slice. So, I would say that the fault is in the profile? As workaround try to change the retraction speed, retract speed and prime speed to an acceptable value and then disable the retraction. We will have a further look but for now, I hope this workaround works for you.

**Comment by EvilGreenOne** [comment] 2018-02-18 15:40
@Vandrasc That indeed did the trick.  Thank you for the support.

I think that the way this came about is that the default values when you "create" a new material fills those two values with 0's.  If I am working with TPU or TPEE, I pretty much run with no retraction so I didn't even think to change those to some other value as Retraction was disabled in my Flexible profile I usually start from.  In previous versions if Retraction was off, I guess it just properly ignored those settings?

I am glad we found a resolution to the issue.  Now I can go take the new features for a spin.

**Comment by nurayha** [comment] 2018-02-19 06:16
Hi everyone,
Thanks for all the advice. I'm glad some of you already solved the issue, but the issue with mine haven't resolved yet. My Cura 3.2.1 still keep on crashing while it is halfway slicing an item. I have checked and tried all method suggested by you guys, but it still happens again.
This is my cura log for your reference.
[cura.log](https://github.com/Ultimaker/Cura/files/1735701/cura.log)

Thank you.

**Comment by Vandrasc** [comment] 2018-02-19 07:51
Hi @nurayha, if it works ok on your other pc it may be that there are some configurations which are causing the crash, could you upload your user configuration as well (the folder where the log is located)? 

@EvilGreenOne anytime, glad it did the trick as well. Yes, it may be, we will try to investigate it and make a fix for it. 
And, thank you for working with us :)

**Comment by nurayha** [comment] 2018-02-19 07:57
Hi @Vandrasc 
Here's the cura configuration as requested.
[cura.zip](https://github.com/Ultimaker/Cura/files/1735879/cura.zip)
Hopefully you can find something that causes the issue in here.
Thank you.

**Comment by Vandrasc** [comment] 2018-02-19 08:11
Is it possible to attach the entire 3.2 folder? The one containing the quality, machine definitions, extruders? 
Thank you for your quick reply

**Comment by nurayha** [comment] 2018-02-19 08:31
Hi @Vandrasc,
Here you go.
[3.2.zip](https://github.com/Ultimaker/Cura/files/1735951/3.2.zip)
Thank you.

**Comment by Vandrasc** [comment] 2018-02-19 09:16
Oke, @nurayha easily reproduced. The slicing engine stops working when the default temperature is set to 0, though it displays warning values it should keep slicing. Any possibility to print with a higher temperature than 0 degrees? I set the default temperature to 0.1 and it successfully triggered a slice. 
I will make a bug report and will be fixed in the next release. 
Good catch, both of you!

**Comment by nurayha** [comment] 2018-02-19 09:24
Hi @Vandrasc,
Thank you for your prompt response.
Yup, it turns out that the value 0 in Default Printing Temperature causes the crashing. It wasn't an issue when I did the same with Cura 3.1.
Thank you so much for helping us solve the problem. Appreciate it.
Cheers! :)

**Comment by Vandrasc** [comment] 2018-02-19 13:18
Devs CURA-4982/4983

**Comment by Vandrasc** [comment] 2018-03-09 12:17
Both issues fixed. Thank you all for reporting it!

**Closed by Vandrasc** 2018-03-09 12:17 UTC
Labels: Type: Bug
