### ISSUE TITLE
Error g-code viewer?

### ISSUE THREAD

**Issue by userosos** [Ultimaker/Cura#9551] opened 2021-04-10 08:08 UTC
### Application Version

4.9.0 beta

### Platform

Windows 10 pro 64 bit

### Printer

Ulti

### Reproduction steps

1. Add the model.
2. Multiply the model.
3. Slice

### Actual results

I cansee from ~130 layer that it will printing on first layer. See pic.

### Expected results

I dont want that the hotend goto 1 layer from 130 layer and print.

UPD. Attachment files were not added from the form
![изображение](https://user-images.githubusercontent.com/22872748/114263275-37f47a80-99ed-11eb-9aa8-356f8484d9e8.png)
[ULTI_02mm_30%_car_bubishka_v2_Ulti_Nylon_HTP.zip](https://github.com/Ultimaker/Cura/files/6289480/ULTI_02mm_30._car_bubishka_v2_Ulti_Nylon_HTP.zip)

**Comment by fieldOfView** [comment] 2021-04-11 11:18
Duplicate of https://github.com/Ultimaker/Cura/issues/7412

**Comment by fvrmr** [comment] 2021-04-13 13:39
Hi @userosos thank you for your bug report. 
I can not reproduce this on 4.9 beta with your file, but with another file I can reproduce this issue on 4.9 beta. 
We have a ticket on our backlog for this issue.
Developers see CURA-7960

I will close this issue since it is a duplicate. Thank you @fieldOfView for referring

**Closed by fvrmr** 2021-04-13 13:39 UTC
Labels: Type: Bug
