### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by satan666666666666** [Ultimaker/Cura#14886] opened 2023-03-14 19:37 UTC
### Application Version

4.6.1

### Platform

chrome os

### Printer

Ender 3

### Reproduction steps

![Screenshot 2023-03-14 3 35 04 PM](https://user-images.githubusercontent.com/127892693/225117357-18566fdc-c92f-4239-8d53-48b9f19ef76c.png)

### Actual results

the file won't download

### Expected results

the file should download

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

![Screenshot 2023-03-14 3 35 04 PM](https://user-images.githubusercontent.com/127892693/225117738-af0f0bfb-381a-430c-961b-fb8e7e5b0e34.png)

**Comment by MariMakes** [comment] 2023-03-17 15:17
Hey @satan666666666666 😈 ,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

Are you sure you are on Cura 4.6.1? It looks like Cura 5.3.0

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/11991
It might also be related to https://github.com/Ultimaker/Cura/issues/12659 where you do not get the suggested .gcode when exporting your project. 

Can you confirm if this is the case and if it's related to a field not being filled or to the file simply not saving?

**Comment by MariMakes** [comment] 2023-03-31 09:19
Quick update on our side. 

We might have a fix for this issue. 🎉 
It's a bit hard for us to test, but we have a nightly build available. 
Can you please try it out and let us know if it resolves your issue? 

[You can find the download links and the discussion here. ](https://github.com/Ultimaker/Cura/discussions/15098)

**Closed** 2023-04-01 00:18 UTC
Labels: Type: Bug, Status: Duplicate, Status: Needs Info, Status: Triage
