### ISSUE TITLE
15.09.81: Uncaught exception has occured!

### ISSUE THREAD

**Issue by robomaniac** [Ultimaker/Cura#395] opened 2015-09-14 02:11 UTC
![crash](https://cloud.githubusercontent.com/assets/5814871/9840700/2d5ee318-5a64-11e5-85b6-50575a1742b6.png)

Sorry I can't copy paste since it crash bad and can't do nothing!

**Comment by Ghostkeeper** [comment] 2015-09-14 07:28
Thank you for all that debugging work, man :fist:

**Comment by nallath** [comment] 2015-09-14 11:40
Could you have a look at your logging files? You can find more information about those on https://github.com/Ultimaker/Cura#logging-issues

**Comment by awhiemstra** [comment] 2015-09-25 09:30
Looking at the screenshot, this seems to be caused by eject disk. This should be fixed with the next build.

**Closed by awhiemstra** 2015-09-25 09:30 UTC
Labels: bug
