### ISSUE TITLE
Mouse hover hint not fully readable

### ISSUE THREAD

**Issue by toto-w** [Ultimaker/Cura#12031] opened 2022-04-30 10:40 UTC
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Reprap

### Reproduction steps

Open the printing option on the right side.
Move the mouse over several options and watch the hints that will be shown for each option.
If you find a hint with longer text that exceeds the text box, try to scroll the text so you can read it fully.

### Actual results

It is not possible to read the full text because you can't scroll the text because to scroll means to move the mouse away from the option that brought up the hint and therefore the text disappears.
![2022-04-30 12_14_48-Window](https://user-images.githubusercontent.com/68814488/166102039-13412446-93fc-4230-bfb2-894e31173484.png)

### Expected results

To be able to read the full hint text like in Cura 4.13.1 as attached.
![Cura4 13 1 - Correct](https://user-images.githubusercontent.com/68814488/166102135-b86b9319-c62d-4eb4-ac95-e0ae4117fff6.png)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Nothing.

**Comment by fvrmr** [comment] 2022-05-02 09:14
Hi @toto-w thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11834, so I will close this issue.

**Closed by fvrmr** 2022-05-02 09:14 UTC
Labels: Type: Bug
