### ISSUE TITLE
Dirty Install? 

### ISSUE THREAD

**Issue by BuschyX** [Ultimaker/Cura#13593] opened 2022-10-18 18:38 UTC
### Application Version

2.2.0

### Platform

Windows 11 Pro

### Printer

Custom

### Reproduction steps

1> I installed the new 5.2.0 Update
2> I click on File to Open in NEW Cura (5.2.0)

### Actual results

Old version of Cura Opens instead

### Expected results

When I click on a file to open in Cura I expect it to open the latest version that I just installed. But this version and the last one too did not do that. I have to go in and uninstall the old version before simply clicking on a file will open in the new version. The last time I had to go in a change the file associations by hand as well.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I am new to this program, just a couple days really. I don't know if this is standard practice and exists for some reason. But to me, when I install a new version of some software, I expect it to replace the old version by default. Is there a way to change all the File associations to the new program that I am not aware of?

Thanks

**Comment by MariMakes** [comment] 2022-10-19 13:29
Hey @BuschyX,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report. 

You are not the first one to report this. It's actually quite common for Cura users to have multiple versions of Cura installed at the same time to compare results. We removed the uninstalling flow in Cura 5.0 , because it confused users, but not having it all is also confusing. So we have to find a new solution for this. 

This seems to be a duplicate of  https://github.com/Ultimaker/Cura/issues/13446
We have a ticket on our backlog with the intent to improve this behavior.
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/13446

**Closed by MariMakes** 2022-10-19 13:29 UTC
Labels: Type: Bug, Status: Triage
