### ISSUE TITLE
O sinal de "-" do expansão da camada horizontal não esta aparecendo 

### ISSUE THREAD

**Issue by DanielWachoLobao** [Ultimaker/Cura#6427] opened 2019-09-26 19:54 UTC
![image](https://user-images.githubusercontent.com/55855515/65720407-45057f00-e07e-11e9-83da-a05cd8a839f2.png)

**Comment by Ghostkeeper** [comment] 2019-09-27 09:47
Duplicate of https://github.com/Ultimaker/Cura/issues/6277.

**Closed by Ghostkeeper** 2019-09-27 09:47 UTC
Labels: Type: Bug
