### ISSUE TITLE
when using support the first layer does not contain all of the structure needed

### ISSUE THREAD

**Issue by Johnep101** [Ultimaker/Cura#16769] opened 2023-09-19 21:23 UTC
### Cura Version

5.4.0

### Operating System

Mac  os monterey 12.6.9

### Printer

Ender 5 pro

### Reproduction steps

1) design in open scad exported .stl file
2) added support structures in cura

### Actual results

this is the first printed layer

![image](https://github.com/Ultimaker/Cura/assets/54002141/4ce05e38-c0d7-47d8-8ccf-5bef32c41d69)

this is the second printed layer, note the support layer being printed in thin air.

![image](https://github.com/Ultimaker/Cura/assets/54002141/dd45b1de-cfc0-4881-8a79-48b9bc854233)

### Expected results

the first layer should contain the second layer support structure.

### Add your .zip and screenshots here ⬇️

project.3mf.zip
[top_wall.stl.zip](https://github.com/Ultimaker/Cura/files/12666511/top_wall.stl.zip)

**Comment by GregValiant** [comment] 2023-09-20 00:21
Thanks for the report.  We like to get a project file instead of the STL as a project file has your settings and printer in it.  Use the "File | Save Project" comand to create one.
I have to guess at your setup but this looks like a previously reported bug.  If the "Bed Adhesion" is set to "None" the Support Brim doesn't form and yes, the support is left hanging in the air on the second layer.
![image](https://github.com/Ultimaker/Cura/assets/64202104/cb5a63a3-85ba-41d2-8649-7044fbf9987b)

When the "Bed Adhesion" is set to anything other than "None" the support brim forms.  Here I've set it to Skirt with the Skirt Line Count set to "0".
![image](https://github.com/Ultimaker/Cura/assets/64202104/62763338-e0ab-4883-b2a9-3045e45f5592)

This appears to be a duplicate of #14810 and a few others.  Let me know if the above fix works for you.
I'm going to go ahead and mark this as a duplicate and close it but if your problem is different it can be reopened.

**Comment by GregValiant** [comment] 2023-09-20 13:17
This should be fixed in the next release.  Good that you got it squared away.

**Closed by GregValiant** 2023-09-20 13:17 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation
