### ISSUE TITLE
Brim for support directly linking to Buildplate adhesion brim

### ISSUE THREAD

**Issue by DestinEngineer** [Ultimaker/Cura#16785] opened 2023-09-21 15:28 UTC
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Any

### Reproduction steps

Brim for support(tree) is being directly linked with the buildplate adhesion for the actual part. Even if brim for support(tree) is enabled, the buildplate adhesion will override that setting  if skirt or none are selected and the support base gets printed without a brim.

### Actual results

If skirt, none, or raft are enabled in Build Plate Adhesion tab, support will NOT print with a brim, even if brim is enabled in the Support tab.

### Expected results

Brim support should work independent of the part. I don't want a brim on my part but need the brim for adhesion for the supports(tree)

### Add your .zip and screenshots here ⬇️

None necessary

**Comment by GregValiant** [comment] 2023-09-22 00:16
Thanks for the report.
This is a duplicate of many reports describing this behavior and it is easy to duplicate.
The Cura team is aware of this so I'll mark this as a duplicate and go ahead and close it.  I hope you understand.

I haven't run 5.5beta yet but hopefully this will be fixed in the next release.

**Closed by GregValiant** 2023-09-22 00:16 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation
