### ISSUE TITLE
UI lock-ups caused by slow drives

### ISSUE THREAD

**Issue by slundell** [Ultimaker/Cura#9399] opened 2021-03-14 09:05 UTC
### Application Version

4.8.0

### Platform

Windows 10

### Printer

Various (ArtistD, Cetus and Ender5)

### Reproduction steps

1. Open a model
2. Change a setting like layer height
3. UI locks up, Window's spinner is showing. 
4. After at least 30s the UI comes back and you are able to continue.
5. Check what drives you have mounted. I have 7 network shares. One on SSH to an off-site server, two to are mapped to servers that are currently offline, and the rest to various servers in house. 
6. Unmount these. 
7. Change a slicing setting again and notice the speed improvement.

### Actual results

UI locks up. 

### Expected results

UI should not lock up on checking drives. If it is necessary to check the drives that often, it should be done in a non-blocking fashion.

**Comment by fvrmr** [comment] 2021-03-15 13:27
Hi @slundell thank you for your report. 
I am wondering if you have an X drive on your computer. If so this is a duplicate of #1602.

Please let me know if that could be the problem.

**Closed** 2021-03-29 13:57 UTC
Labels: Status: Needs Info, Type: Bug
