### ISSUE TITLE
Preview of Infill Layer Thickness increase seems incorrect

### ISSUE THREAD

**Issue by rondlh** [Ultimaker/Cura#16034] opened 2023-07-06 14:59 UTC
### Cura Version

5.4.0

### Operating System

Windows 10 x64

### Printer

Custom

### Reproduction steps

Compare the result of 1x the layer height and 5x the layer height in the preview

### Actual results

Infill layers seems to get much wider, wall surfaces are visually affected too. I believe this is only an visual issue (didn't test it), I assume the actual print is not affected like shown.

Infill layer thickness 0.05mm ( = layer height), everything looks normal.
![Infill Layer Thickness 0 05](https://github.com/Ultimaker/Cura/assets/77279634/1634600b-0619-4879-92ed-77b86b2a7bb5)

Infill layer thickness 0.4mm (8x the layer height), infill seems far too wide. Some artifacts in the walls are visible.
![Infill Layer Thickness 0 4](https://github.com/Ultimaker/Cura/assets/77279634/f41a34d3-2c13-4f88-8b01-fec49204deb1)

Note: The used material is about the same.

### Expected results

Visually there should not be much difference.

### Add your .zip and screenshots here ⬇️

![Infill Layer Thickness 0 4](https://github.com/Ultimaker/Cura/assets/77279634/0fb4d424-fcc6-4903-97f9-2a757128fa68)

**Comment by Asterchades** [comment] 2023-07-07 08:01
Duplicate of #16022.

Much as I explain there, I believe this behaviour is unintentional but largely unavoidable due to the nature of the preview system.

**Closed by Asterchades** 2023-07-07 08:01 UTC
Labels: Type: Bug, Status: Triage

**Comment by ymh1003** [comment] 2023-12-05 01:12
Can you share the zip file? Much appreciated!
