### ISSUE TITLE
Cura 5.3.1

### ISSUE THREAD

**Issue by Justolik** [Ultimaker/Cura#15783] opened 2023-06-17 19:11 UTC
### Application Version

5.3.1

### Operating System

Linux

### Printer

FBG6

### Reproduction steps

In the current version of Ultimaker Cure 5.3.1, when cutting some models with radius surfaces, such as a cylinder, sphere and similar, it makes some bug. When printing such models on a printer, the printer's head, describing an arc, makes micro stops in some places. These places of micro-stops are repeated from layer to layer. There was no such problem on version 5.2.1. I had to go back to this version...

### Actual results

In the current version of Ultimaker Cure 5.3.1, when cutting some models with radius surfaces, such as a cylinder, sphere and similar, it makes some bug. When printing such models on a printer, the printer's head, describing an arc, makes micro stops in some places. These places of micro-stops are repeated from layer to layer. There was no such problem on version 5.2.1. I had to go back to this version...

### Expected results

In the current version of Ultimaker Cure 5.3.1, when cutting some models with radius surfaces, such as a cylinder, sphere and similar, it makes some bug. When printing such models on a printer, the printer's head, describing an arc, makes micro stops in some places. These places of micro-stops are repeated from layer to layer. There was no such problem on version 5.2.1. I had to go back to this version...

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

In the current version of Ultimaker Cure 5.3.1, when cutting some models with radius surfaces, such as a cylinder, sphere and similar, it makes some bug. When printing such models on a printer, the printer's head, describing an arc, makes micro stops in some places. These places of micro-stops are repeated from layer to layer. There was no such problem on version 5.2.1. I had to go back to this version...

**Comment by MariMakes** [comment] 2023-07-17 14:16
Hey @Justolik,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I recognize this issue. 🔎
This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/14811
The new Cura 5.4 contains the fix for this stuttering behavior on Klipper printers. Could you test if that's the case for you as well?  You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.4.0

I'll close this issue since it's a duplicate and resolved. 

Thanks again, and please let us know if you run into any other issues 💪
It would help if you fill in the template correctly next time, that can help us get you to a solution quicker.

**Closed by MariMakes** 2023-07-17 14:16 UTC
Labels: Type: Bug, Status: Triage
