### ISSUE TITLE
Support blocker has no effect

### ISSUE THREAD

**Issue by anno0** [Ultimaker/Cura#14841] opened 2023-03-10 19:00 UTC
### Application Version

5.2.2

### Platform

Ubuntu 20.04

### Printer

Anycubic Mega X

### Reproduction steps

1. Insert a part into the project from thingiverse https://www.thingiverse.com/thing:5036812
2. Add some support blocker because only inside a support should be printed

I don't know if it is a setting issue or bug.

### Actual results

Outer supports from the build plate are printed although I have added some support blocker to avoid these.

### Expected results

Only support inside the part should be printed.

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Additional information & file uploads

![view](https://user-images.githubusercontent.com/2607705/224403088-69dfa01e-381f-4d49-9681-c1fe712c7864.png)
[support blocker.zip](https://github.com/Ultimaker/Cura/files/10945118/support.blocker.zip)

**Comment by MariMakes** [comment] 2023-03-17 14:28
Hey @anno0,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 

We made a number of improvements to printing supports in Cura 5.3, 
I believe this is one of them.  You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

Can you let us know if it works for you?

**Comment by anno0** [comment] 2023-03-17 18:37
Hey @MariMakes ,
I installed Cura 5.3.0. The blocked support looks better but is not ignored at all. I had seen that I added the support not tight enough at the corners to prevent to outer support. After I have fixed this (as seen in the project file) the support is still created. 

![display](https://user-images.githubusercontent.com/2607705/225989866-e2180c6e-dbb4-4c8f-bb8d-50277dfc3c97.png)
![moved support](https://user-images.githubusercontent.com/2607705/225989874-f291224e-f0e9-48b3-ac74-6e1d2d11d4fa.png)
[support blocker5.3.0.zip](https://github.com/Ultimaker/Cura/files/11004604/support.blocker5.3.0.zip)

**Comment by MariMakes** [comment] 2023-03-20 14:04
Hey @anno0,

Thanks for checking in 5.3 and getting back to us. 
I think I figured out what is going wrong! 

Your Support Horizontal Expansion is too high and "spills" through the side cracks of your model. 
If you reduce the _Support Horizontal Expansion_ to 0, Cura slices faster and there is no unnecessary support. 
You don't need the expansion for this model anyways. Seems like a win-win to me. 😄 
![image](https://user-images.githubusercontent.com/40423138/226363175-7bdec388-7df4-4b06-8b1b-0eaab0c3665e.png)

Also, did you know you can make any type of mesh a support blocker?
In this case, I made a duplicate of your model, increased the size slightly, and used it as a support blocker. 
It saves a lot of hassle in your case. 

This is the file I ended up creating: [Mari_AI3MX_support.blocker.zip](https://github.com/Ultimaker/Cura/files/11019037/Mari_AI3MX_support.blocker.zip)

To me, it doesn't seem like a bug in Ultimaker Cura anymore. 
Would you still like to keep this issue open or do you agree that we can close it?

**Comment by anno0** [comment] 2023-03-20 19:02
How have you created this arbitrary support blocker? I haven't found any function to set a model as support blocker.
I think this bug can be closed.

**Closed as completed** 2023-03-21 13:55 UTC
Labels: Type: Bug, Status: Triage
