### ISSUE TITLE
Variable layer height

### ISSUE THREAD

**Issue by 68AndersK** [Ultimaker/Cura#6759] opened 2019-12-04 10:13 UTC
On high curvature parts it's often desired to use a very small layer height. If a large portion of such part doesnt have that curvature the print time gets extremely long.
Adaptive layers are useful but can be quite difficult to specify settings to get wanted result.

I would like to be able to specify layer thickness at a given height of the print.
(similar to how you can set different te,perature at different heights)

Have been working with adaptive layers but sometimes difficult to find the settings.
Variable layer thickness can also have bad visiual impact so it would help if you could set that from height xx you would always get layer height yy

Showing a typical example of that in screen shot below where adaptive layers give variations in the area  would like to have only the 0,05 height. 
![image](https://user-images.githubusercontent.com/54984462/70133522-946fb900-1686-11ea-892f-59ce404fe207.png)

Coarse layer settings give fast print but aweful appearance
![image](https://user-images.githubusercontent.com/54984462/70133657-d698fa80-1686-11ea-87ef-915f50f598bd.png)

Fine layers giving a nice surface but very long print time
![image](https://user-images.githubusercontent.com/54984462/70133780-12cc5b00-1687-11ea-853f-1221ac716d31.png)

**Comment by Ghostkeeper** [comment] 2019-12-06 10:38
Duplicate of https://github.com/Ultimaker/Cura/issues/4295. Nice illustrative pictures here though.

**Closed by Ghostkeeper** 2019-12-06 10:38 UTC
Labels: Type: New Feature
