### ISSUE TITLE
Can not choose material (eSun ePA-CF)

### ISSUE THREAD

**Issue by mentor2k1** [Ultimaker/Cura#10128] opened 2021-07-13 09:45 UTC
### Application Version

4.10.0

### Platform

MacOSX

### Printer

Anycubic Mega S

### Reproduction steps

1. i removed the cura folder like described in https://support.ultimaker.com/hc/en-us/articles/360013007080-How-can-I-completely-reset-my-Ultimaker-Cura-installation-
2. restart of Cura
3. After setup the printer again i switched into the material section. eSun ePA-CF wasn't installed so i did it in marketplace
4. Cura wants to shut down
5. restart of Cura

### Actual results

I see the material flagged as installed the marketplace, but i cant choose it

![Bildschirmfoto 2021-07-13 um 10 54 42](https://user-images.githubusercontent.com/1419917/125429699-15bd9f57-69f5-4783-865f-5e1dc565c472.png)

![Bildschirmfoto 2021-07-13 um 10 55 08](https://user-images.githubusercontent.com/1419917/125429686-88cf4eee-0596-4d81-a675-672c4b0f23e7.png)

### Expected results

Possibility to select the material

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

The Ultimaker Material project here on github also doesn't have the fdm_material file, so i need help to get it working.

**Comment by fvrmr** [comment] 2021-07-13 10:13
Hi @mentor2k1 all the materials from the marketplace are only for Ultimaker printers, so that's why it isn't showing up. Your printer has a 1.75 mm material diameter and Ultimaker 2.85mm. 
See also this issue: https://github.com/Ultimaker/Cura/issues/6236

The problem is that the marketplace doesn't show if the material is compatible with your printer. 
I will close this issue as a duplicate. I hope you understand.

**Closed by fvrmr** 2021-07-13 10:13 UTC
Labels: Type: Bug
