### ISSUE TITLE
Ultimaker Digital Factory Code not being generated by my US3

### ISSUE THREAD

**Issue by GoguyT3D** [Ultimaker/Cura#13625] opened 2022-10-22 16:04 UTC
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Ultimaker S3

### Reproduction steps

On my printer i did a Digital Factory Reset, then Reset All Printer Settings, after I set up my network and named the printer as it was named before. Also I removed my printer from Ultimaker Cura and re-added it after the printer was set up. I am trying to connect to Ultimaker Digital Factory as I was in the past, although my printer says its connected to Ultimaker Digital Factory without compiling a 6 digit code for me to type into the website.

### Actual results

Printer shows it is connected to ultimaker digital factory, PC needs a 6 digit code to connect to the printer and the printer will not make one, immediately connects, though doesnt show on the PC

### Expected results

My U3S should create a Ultimaker Digital Factory 6 digit code and allow me to simply connect my printer to the cloud.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

Every time I try to squash one bug another one is right there waiting for me

**Comment by MariMakes** [comment] 2022-10-25 08:23
Hey @GoguyT3D,

Thanks for your report 👍 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13624
We have a ticket on our backlog with the intent to improve this behavior.
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/13624

**Closed by MariMakes** 2022-10-25 08:23 UTC
Labels: Type: Bug, Status: Triage
