### ISSUE TITLE
Prime Tower Not Printing, Appearing as Shadow

### ISSUE THREAD

**Issue by Jcraig619** [Ultimaker/Cura#16681] opened 2023-09-06 20:25 UTC
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Sovol SV02

### Reproduction steps

1. Added STL that does not require supports.
2. Adjusted settings for dual extrusion printing.
3. Noticed that prime tower appears as a shadow.
4. Attempted print 8 times with adjustments in prime tower settings. (extruders feed for 3 seconds regardless of settings rather than printing prime tower)
5. Referenced, "Prime Tower Only Showing as a Shadow and Therefore it Doesn't Print #14707" for insight
6. Attempted to edit SV02.def.json to remove the error and received a pop-up saying that I am not authorized to edit.

I have printed multiple objects using one extruder. However the inability of the prime tower to be printed is preventing me from printing dual extrusion objects.

### Actual results

Prime tower does not print, and instead extruders feed filament for 3 seconds. This creates prints streaked with both colors that fail frequently due to the filament fed getting stuck to the nozzle.

### Expected results

Prime tower should print allowing for models printed with distinct colors in separate parts.

### Add your .zip and screenshots here ⬇️

[SSL_zou_ghost_Keychain.zip](https://github.com/Ultimaker/Cura/files/12542180/SSL_zou_ghost_Keychain.zip)

**Comment by GregValiant** [comment] 2023-09-07 01:46
Thanks for the report.
Yes, this is a definition file issue and so the problem is with Sovol rather than with Cura.

Windows may want you to grant yourself permission to access the files in the definitions folder.  You can try right clicking on the main Cura 5.4.0 folder and under Properties are the Security and Sharing settings.  I had to adjust both of them to gain access on my own computer.

As you saw in #14707 there is an error in the definition file and that came from Sovol.  UltiMaker cannot asses if a definition for a 3rd party print is correct.  Unfortunately you will have to address the problem with Windows in order to fix the problem.

I'll remove the bug label from this and I'll close it.  I hope you understand.

**Closed by GregValiant** 2023-09-07 01:46 UTC
Labels: Type: Bug, Type: Discussion, Status: Under Investigation
