### ISSUE TITLE
Cura Crashing Machine when left open

### ISSUE THREAD

**Issue by Lite5h4dow** [Ultimaker/Cura#10990] opened 2021-12-02 12:35 UTC
### Application Version

4.12

### Platform

Win 10

### Printer

Ender 3 V2

### Reproduction steps

1. Open Cura
2. Open STL(optional)
3. Leave Cura Open.
4. PC shuts down after undeterminate amount of time.

### Actual results

pc hard crashes. not to desktop, fully shuts down.

### Expected results

lets you slice modify and do other stuff while the application is open in the background

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7641837/cura.log)

Specs: 
AMD Ryzen 3700x
NVidia GTX 1070
16GB Ram
2TB NVme SSD

**Comment by fvrmr** [comment] 2021-12-03 10:07
Hi @Lite5h4dow thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/5265
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-12-03 10:07 UTC
Labels: Type: Bug
