### ISSUE TITLE
Moving with the mouse doesn't do anything

### ISSUE THREAD

**Issue by Silfred** [Ultimaker/Cura#14719] opened 2023-02-28 16:31 UTC
### Application Version

5.3.0-beta2.0

### Platform

macOS Ventura 13.2.1

### Printer

Ultimaker 2+

### Reproduction steps

1. Started the application
2. Want to change the view of the printer, but the view will not change.
3. I can change the view of the printer only with the buttons below. 

### Actual results

The view will still be the same

### Expected results

The view will change if I'm moving my mouse

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

If you want, I can make a video of my screen.

**Comment by MariMakes** [comment] 2023-03-21 15:18
Hey @Silfred,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Did it use to work before? Or has it just never worked? 
What kind of mouse are you using? 
If it's a tablet it might be a duplicate of this issue https://github.com/Ultimaker/Cura/issues/12554

If it's not, it would be helpful if you included a recording of your screen. 
Or at least some more details about your hardware.

**Closed** 2023-04-21 12:19 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage
