### ISSUE TITLE
[3.6.0] Troubles of Zig-zag infill

### ISSUE THREAD

**Issue by Generator73** [Ultimaker/Cura#4947] opened 2018-12-06 19:33 UTC
Ultimaker Cura 3.6.0 win7-64
Zig-zag infill does not work correctly.

![zig-zag-1](https://user-images.githubusercontent.com/45670429/49607396-dba96800-f9a6-11e8-992b-759814847244.jpg)
![zig-zag-2](https://user-images.githubusercontent.com/45670429/49607398-dba96800-f9a6-11e8-8c52-f91c48e50f38.jpg)

**Comment by smartavionics** [comment] 2018-12-06 19:49
Yes, unfortunately there's a regression that breaks various infills and skin. I expect they will fix it sometime. In the meantime, you could try using one of my builds that doesn't suffer from this problem and gives your some other goodies, too. They can be found at https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0

**Comment by Thisismydigitalself** [comment] 2018-12-06 23:07
@Generator73 
Just checking, - Did you mirror this part in Cura?
https://github.com/Ultimaker/Cura/issues/4858

**Comment by Generator73** [comment] 2018-12-07 06:00
@Thisismydigitalself 
No. I mirrored it in Solidworks.

**Comment by smartavionics** [comment] 2018-12-07 07:19
Switching the infill pattern to lines rather than zig-zag will probably fix the problem.

**Comment by Generator73** [comment] 2018-12-07 07:33
@smartavionics 
Of course. But I need zig-zag.

**Comment by smartavionics** [comment] 2018-12-07 07:38
In that case you must use a different version of Cura to get around this problem.

**Comment by Generator73** [comment] 2018-12-07 08:38
Or I can use other slicer ;)

**Comment by smartavionics** [comment] 2018-12-07 09:04
> Or I can use other slicer ;)

Of course, you always have that option.

**Comment by Thisismydigitalself** [comment] 2018-12-07 10:13
@Generator73 
Before making a mistake and swithing to a differnet slicer :), care to share your stl?  
I am using 3.6 and i don't have this issue, at least i t seem so.

**Comment by smartavionics** [comment] 2018-12-07 10:17
Hello @Thisismydigitalself , whether the problem occurs or not is model and settings dependent. So changing a line width or infill density or similar can make the bug come and go.

**Comment by Generator73** [comment] 2018-12-07 11:11
@Thisismydigitalself 
The same parameters but added another STL model.
![zz](https://user-images.githubusercontent.com/45670429/49644604-f1ac3c80-fa29-11e8-867c-9840e6a0355b.jpg)

**Comment by smartavionics** [comment] 2018-12-07 11:16
Yes, but the bottom rh part's infill is still screwy.

**Comment by smartavionics** [comment] 2018-12-07 11:30
> Yes. Programmers should fix it.

Indeed so.

**Comment by Thisismydigitalself** [comment] 2018-12-07 12:58
ZigZag InFill is overrated and for the weak, pun intended.
I vote for Gyroid.

**Comment by ctmakro** [comment] 2019-01-10 14:42
same problem as #4559. ran into multiple times. although this problem is going to be fixed in 4.0, I'd still like to post one more example, just for the record.

![image](https://user-images.githubusercontent.com/9973364/50975604-f2545900-1528-11e9-8f5c-0068a411145c.png)

v 3.6

**Comment by BagelOrb** [comment] 2020-11-24 11:04
Linked issue is closed because it's fixed, so I'm closing this one as well.

**Closed by BagelOrb** 2020-11-24 11:04 UTC
