### ISSUE TITLE
5.3.0 Stalling when printing circles with Klipper

### ISSUE THREAD

**Issue by NNMale** [Ultimaker/Cura#15001] opened 2023-03-22 18:27 UTC
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Flying Bear 5 (Klipper)

### Reproduction steps

1. Create any cylinder. The optimal diameter is 40 mm.
2. Make a Cura 5.3.0 slice with normal mode (Not vase mode).
3. Send to the Klipper for printing.

### Actual results

Left Cura 5.3.0 (stripes due to printing head stoppage can be seen)
Right Cura 5.2.2 (normal print quality)

![20230321_104915](https://user-images.githubusercontent.com/96396187/227000412-1c1024e1-38df-4ded-ba8a-af91c5fb7a1d.jpg)

### Expected results

It was not possible to print on the Klipper without problems. No problems detected on the Marlin.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No further information

**Comment by tianer2820** [comment] 2023-03-23 15:28
I got a similar issue. Gcodes generated by cura 5.3.0 produce random blobs on the surface when printed with klipper. I checked that the cause is not over-extrusion nor seams. This issue does not exist in 5.2.1.

![PXL_20230323_152049950~2](https://user-images.githubusercontent.com/43716345/227251683-85ac1ad6-2279-4ac7-91e9-d30135677b9c.jpg)

[project files.zip](https://github.com/Ultimaker/Cura/files/11052686/project.files.zip)

**Comment by darrellenns** [comment] 2023-03-26 23:33
Possible duplicate of #14811

**Comment by IamAles** [comment] 2023-03-27 19:49
Hello, I can see the same issue in Cura 5.3 on my modified Anet A8+ with Klipper on it. 
![IMG_20230325_234144](https://user-images.githubusercontent.com/129112009/228049781-6604663e-4d41-43c8-b09e-14e17061a529.jpg)

![IMG_20230325_234400](https://user-images.githubusercontent.com/129112009/228049821-bbae6830-b505-4fcc-ba16-98840f436ce8.jpg)

It is a top "ring" from this project - https://www.thingiverse.com/thing:45214. I have tried to increase buffer in Klipper (buffer_time_high: 10) with no success.

[AA8P_tealight_top_40mm_3fm.zip](https://github.com/Ultimaker/Cura/files/11082465/AA8P_tealight_top_40mm_3fm.zip)

**Comment by fmonaca** [comment] 2023-03-29 08:40
I have the same issue on my Voron with Klipper and Cura 5.3, heavy stuttering on curves that produces blobs. No issues with Cura 5.2.

**Comment by DPe997** [comment] 2023-03-30 07:49
Same issue Windows 11 Cura 5.3.0 FLSUN V400 with Klipper. Perfect prints everytime with 5.2.2.

**Comment by Madin5** [comment] 2023-03-30 12:52
Can confirm, had this issue for couple of days, didn't realise that i updated cura.
Left 5.3, right 5.2.2
![IMG_20230330_144618](https://user-images.githubusercontent.com/39805927/228841795-9b75e9f9-d830-4a19-81db-9894657c78ce.jpg)

**Comment by Piezoid** [comment] 2023-03-30 13:42
In theory the only thing that could make klipper stutter like this are tiny invisible segments at a sharp angle. This can be verified by checking that lower `square_corner_velocity` values worsen the issue.

**Comment by IamAles** [comment] 2023-04-02 14:52
https://www.gcodeanalyser.com/ shows this for my posted print:
![5 3 0_issue_a](https://user-images.githubusercontent.com/129112009/229360316-293b7b5c-0cc3-4ea1-a6e3-29b2d3720341.png)
https://gcode.ws/ shows this:
![5 3 0_issue_b](https://user-images.githubusercontent.com/129112009/229360355-9f5486c3-ecc5-4f5a-9781-b7d33e9ce228.png)
In the gcode there are tiny moves like this:
![5 3 0_issue_c](https://user-images.githubusercontent.com/129112009/229360392-cd011b2b-3825-40ef-9d6a-ba3abeea8453.png)
Mesh settings in Cura 5.3.0 for this print was:
Maximum Resolution: 0.1
Maximum Travel Resolution: 0.1
Maximum Deviation: 0.05

I have also tried:
Maximum Resolution: 0.5
Maximum Travel Resolution: 0.5
Maximum Deviation: 0.1
which unfortunately did not solve the issue.
It seems to me that Cura 5.3.0 did not respect those settings.

**Comment by MariMakes** [comment] 2023-04-03 14:54
Hey All! Sorry, it took us a while to get back to you 😰 
This looks scary. 😮 

It's outside my field of expertise but a klipper bug we introduced in Cura 5.3 is a typo related to ;MESH:NONMESH
It should be resolved in the upcoming service pack. 

Can you try the workaround mentioned here and let us know if it works for you? ttps://github.com/Ultimaker/Cura/issues/14679

**Comment by IamAles** [comment] 2023-04-03 19:30
Hi MariMakes, thank you for information. I have just tried adding replace script NOMESH -> NONMESH, but the result is unfortunately the same.

**Comment by MariMakes** [comment] 2023-04-04 09:44
Hey @IamAles,

Thanks for testing! ❤️ 
I'll bring it up to the team to see what they can do to improve it. 
But I'm not sure what we can do since we don't have access to Klipper printers. 

@ckvsoft you know more about Klipper printers than I do, do you perhaps see what might be going on?

**Comment by Piezoid** [comment] 2023-04-04 10:20
@MariMakes: @IamAles analysis of the gcode shows small extrusion segments perpendicular to the contour, as I suspected. Klipper constrains the velocity profile in order to follow the extrusion precisely. This cause significant slowdowns on these artifacts. 

> https://gcode.ws/ shows this:
> ![5 3 0_issue_b](https://user-images.githubusercontent.com/129112009/229360355-9f5486c3-ecc5-4f5a-9781-b7d33e9ce228.png)

My guess would be an issue with the path simplification: small segments could be collapsed in longer ones, accumulating the deviation on a short segment whose angle is getting shaper and shaper.
A potential mitigation for this issue is to get less simplification by decreasing maximum resolution and deviation. Most printers running klipper are able to handle high number of segments.

**Comment by ckvsoft** [comment] 2023-04-04 12:46
Hallo @MariMakes 
> Hey @IamAles,
> 
> Thanks for testing! heart I'll bring it up to the team to see what they can do to improve it. But I'm not sure what we can do since we don't have access to Klipper printers.
> 
> @ckvsoft you know more about Klipper printers than I do, do you perhaps see what might be going on?

This NOMESH/NONMESH typo has nothing to do with this faulty print.
This was about excluding objects during printing. I can't say whether that only makes clippers about this information.

I would not have noticed this printed image, but I rarely print such objects. Has anyone tried whether this is also the case with other firmware? I think it's a slicing error

**Comment by IamAles** [comment] 2023-04-04 20:04
Hi @Piezoid
> ...A potential mitigation for this issue is to get less simplification by decreasing maximum resolution and deviation....

The print was sliced with those parameters:
Maximum Resolution: 0.1
Maximum Travel Resolution: 0.1
Maximum Deviation: 0.05

Do you think it should be decreased even more? What values do you suggest?

**Comment by alpytron** [comment] 2023-04-05 12:44
Hi,
I'm having the same issues. Now I switched back to 4.13.1, since 5.3 is creating those artifacts all the time. Below photos show the difference between 5.3 and 4.13.1, both with exactly same settings.

![IMG_20230405_143244](https://user-images.githubusercontent.com/40063267/230083853-b295eccf-c931-4584-a336-92b9e8fd61a8.jpg)

![IMG_20230405_143300](https://user-images.githubusercontent.com/40063267/230083867-f6dedaa7-af56-4cda-97ac-e948e3e65c8d.jpg)

![IMG_20230405_143341](https://user-images.githubusercontent.com/40063267/230083881-2c950300-e93c-4a33-86f3-4763047a7943.jpg)

**Comment by doubletrouble023** [comment] 2023-04-05 14:35
What interface are you using with Klipper? I remember having these exact issues with earlier versions when I used Octoprint (which was the culprit)

I'm using Fluidd on my voron and haven't noticed these stutters for years now. Not even in 5.3.0

**Comment by alpytron** [comment] 2023-04-05 14:38
I use it with Repetier-Server, BTW.

However I believe this issue has nothing to do with Klipper or its interface. The artifact is visible in the GCODE as well, so it's clearly Cura's fault.

**Comment by IamAles** [comment] 2023-04-05 19:24
Hi @doubletrouble023 
> What interface are you using with Klipper? I remember having these exact issues with earlier versions when I used Octoprint (which was the culprit)

I am actually using Octoprint, but as was said the issue is visible in the GCODE. If the Octoprint was the culprit, raising _buffer_time_high_ to 10 should make it "better" or it should be in another place of print at least, which was not the case.

> I'm using Fluidd on my voron and haven't noticed these stutters for years now. Not even in 5.3.0

What is your _square_corner_velocity_? Higher values could probably mitigate the issue as well as higher _pressure_advance_.

**Comment by doubletrouble023** [comment] 2023-04-05 21:36
Yeah I am aware that the issue is with cura. But if that was the entire
story, all marlin users would have the same problems? If I haven't
misunderstood anything cura outputs gcode with a lot of
extremely short moves.
That was the same problem with version 4.x.x  something and it made klipper
stutter a lot. There were some settings you could tweak to make it better
but not by a lot.
I'm just saying that switching to a moonraker client solved that issue for
me.  And I haven't noticed anything like this on either of my V2.4s


Square_corner_velocity is at 5 and pressure advance : 0.035 and smooth_time
: 0.04
So nothing exceptionally high there really.

**Comment by darrellenns** [comment] 2023-04-06 04:08
@doubletrouble023 I don't see why moonraker vs octoprint would matter at all - it's klipper that processes the gcode, not the frontend. Also, I run moonraker and I'm seeing this same issue.

This is very clearly an issue with Cura. You can actually see the problem directly within Cura's own preview if you look closely. It can be seen by viewing the gcode output in other gcode preview software as well. If it's not showing up (or just less visible) on prints from Marlin machines, then I would guess that's probably down to differences in the Marlin's motion planning algorithms or other configuration/feature differences that mask it (linear advance, accelerations, etc).

The fix needs to be done in Cura, and I'm sure it will happen once the devs track down the root cause. Trying to work around it with printer settings/firmware is likely to be an exercise in frustration, if it's even possible. The only workaround I've found is going back to Cura version 5.2.2, which does not have the issue.

**Comment by MariMakes** [comment] 2023-04-06 12:50
Hey All.

Thanks for the reports
I'm going to mark this as a duplicate of https://github.com/Ultimaker/Cura/issues/14811
We have a ticket on our backlog with the intent to improve this behavior. For internal reference CURA-10500

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/14811

**Closed by MariMakes** 2023-04-06 12:50 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage
