### ISSUE TITLE
Scaling isssue with Cura 3.6.0

### ISSUE THREAD

**Issue by botgeek** [Ultimaker/Cura#5221] opened 2019-01-25 20:26 UTC
**Application Version**
3.6.0

**Platform**
Windows 10

**Printer**
Ender 3 Pro

**Steps to Reproduce**

If I...

    Drop the model on the workspace
    Rotate it about the X axis by 90 degrees
    Switch to the Scaling window and uncheck the "Uniform Scaling"
    Enter 80 into the X% box and the Y stays at 100 as expected, Z scales to 80 automatically.
    If I make a change to X or Z then the other one makes an automatic adjustment.
    

**Actual Results**
The part changes to an undesired shape

**Expected results**
 I expected the part to scale to what I entered without automatic incorrect changes.

**Additional Information**
Doesn't seem to matter what Part I try.

**Comment by Eyos** [comment] 2019-01-27 17:13
I also have issue with scaling too. I uncheck the 'Uniform scaling' but when scaling one axis, other axes change as well, in inconsistent way. It is almost impossible to get the model to scale to the dimensions you want it to be.

**Comment by netsab3r** [comment] 2019-01-29 01:03
Same issue when attempting to scale only one axis it automatically changes one other axis scale to match.

**Comment by Ghostkeeper** [comment] 2019-01-29 15:25
Duplicate of #4136.

**Closed by Ghostkeeper** 2019-01-29 15:25 UTC
