### ISSUE TITLE
Building Cura from source: typo in Conan profile?

### ISSUE THREAD

**Issue by mjc-506** [Ultimaker/Cura#14614] opened 2023-02-19 18:35 UTC
### Application Version

5.3.0 (git)

### Platform

Linux

### Printer

NA

### Reproduction steps

Catching up with the latest changes on git, and building from source:

```
[matt@mattop Cura]$ conan config install https://github.com/ultimaker/conan-config.git
Trying to clone repo: https://github.com/ultimaker/conan-config.git
Repo cloned!
Defining remotes from remotes.txt
Copying file global.conf to /home/matt/.conan/.
Processing conan.conf
Copying file .gitignore to /home/matt/.conan/.
Skip README.md
Copying file VirtualPythonEnv.py to /home/matt/.conan/generators
Copying file GitHubActionsRunEnv.py to /home/matt/.conan/generators
Copying file PyCharmRunEnv.py to /home/matt/.conan/generators
Copying file GitHubActionsBuildEnv.py to /home/matt/.conan/generators
Copying file cura.jinja to /home/matt/.conan/profiles
Copying file cura_build.jinja to /home/matt/.conan/profiles
[matt@mattop Cura]$ conan profile new default --detect --force
Found gcc 12.2
Found clang 15.0
gcc>=5, using the major as version

************************* WARNING: GCC OLD ABI COMPATIBILITY ***********************
 
Conan detected a GCC version > 5 but has adjusted the 'compiler.libcxx' setting to
'libstdc++' for backwards compatibility.
Your compiler is likely using the new CXX11 ABI by default (libstdc++11).

If you want Conan to use the new ABI for the default profile, run:

    $ conan profile update settings.compiler.libcxx=libstdc++11 default

Or edit '/home/matt/.conan/profiles/default' and set compiler.libcxx=libstdc++11

************************************************************************************



Profile created with detected settings: /home/matt/.conan/profiles/default
[matt@mattop Cura]$ conan install . --build=missing --update -o cura:devtools=True -g VirtualPythonEnv
ERROR: Error in resulting settings for package 'scripta': 'settings.compiler.cppst' doesn't exist for 'gcc'
'settings.compiler' possible configurations are ['cppstd', 'exception', 'libcxx', 'threads', 'version']
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++
compiler.version=12
os=Linux
os_build=Linux
compiler.cppst=20
[matt@mattop Cura]$ 
```

Opening ~/.conan/profiles/cura.jinja and changing line 9 to `scripta:compiler.cppstd=20`  (cppst -> cppst**d**) results in a successful build.

### Actual results

Without the edit to cura.jinja, the build fails with the error referencing scripta and settings.compiler.cppst

### Expected results

Once the 'd' is added to cura.jinja, the build completes successfully.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

NA

**Comment by MariMakes** [comment] 2023-02-20 14:20
Hey @mjc-506,

Thanks for your report 👍

I brought it up to the team and it seems to have been resolved already: https://github.com/Ultimaker/conan-config/commit/c2e3abb536fede38c918d8eb7d9f11635459fb49

I'll close this issue, thanks for keeping us sharp. ❤️ 
Feel free to open the issue is you are still stuck.

**Closed by MariMakes** 2023-02-20 14:20 UTC
Labels: Type: Bug, Status: Triage, Developer Environment :computer:
