### ISSUE TITLE
"Automatically drop models to the build plate" broken

### ISSUE THREAD

**Issue by garrett-carson** [Ultimaker/Cura#2718] opened 2017-11-03 13:36 UTC
Each of these models will slice fine alone, but try to have them both on the same plate and the Q-window will float up to layer 3.

Files are `A-Gothic-Window-v1.0.stl` and `Q-Gothic-Rosetta-Window-v1.0.stl` from [Printable Scenery's Cathedral Walls](https://www.printablescenery.com/product/cathedral-walls/)

![capture](https://user-images.githubusercontent.com/5941343/32376295-604e43a6-c072-11e7-803a-bff676f56ca6.PNG)
![capture2](https://user-images.githubusercontent.com/5941343/32376300-651865ce-c072-11e7-990c-6716f4a73965.PNG)
![capture3](https://user-images.githubusercontent.com/5941343/32376304-68306ec8-c072-11e7-89c1-c803b97ae107.PNG)

**Comment by Ghostkeeper** [comment] 2017-11-08 01:02
How do those models look in X-ray view? Anything red?

I can't test it for you unless I shell €20,- on it.

**Comment by garrett-carson** [comment] 2017-11-08 02:34
No red. 2 Models in question sent to your email listed in cura's git commits.

![capture](https://user-images.githubusercontent.com/5941343/32528709-198a5dd4-c3fa-11e7-8529-f72910135c14.PNG)

**Comment by Ghostkeeper** [comment] 2017-11-09 23:44
It looks like this issue is a duplicate of https://github.com/Ultimaker/Cura/issues/2050.

The Rosetta Window file doesn't get aligned to the build plate properly. I've tried fixing it up in Meshlab and in CloudCompare but none of the tricks that I pulled could get Cura to align it properly (it did find duplicate faces and a non-manifold edge though, but that didn't seem to matter to Cura).

I suggest that you wait for now until we have a fix for #2050. A workaround is to move the Rosetta to Z=-0.166 using the move tool. I measured that your model was 0.166mm above the build plate.

**Comment by Ghostkeeper** [comment] 2017-11-10 00:15
It seems these are all duplicates of each other. Maybe there could be some more information in the other ones:
* https://github.com/Ultimaker/Cura/issues/545
* https://github.com/Ultimaker/Cura/issues/1101
* https://github.com/Ultimaker/Cura/issues/1487
* https://github.com/Ultimaker/Cura/issues/1527
* https://github.com/Ultimaker/Cura/issues/1979
* https://github.com/Ultimaker/Cura/issues/2050
* https://github.com/Ultimaker/Cura/issues/2296
* https://github.com/Ultimaker/Cura/issues/2718

**Closed by Ghostkeeper** 2017-11-10 00:15 UTC

**Comment by Ghostkeeper** [comment] 2017-12-15 09:30
This is fixed for Cura 3.2.
