### ISSUE TITLE
Issue with importing stl files from network drive

### ISSUE THREAD

**Issue by tonyjosephm** [Ultimaker/Cura#12098] opened 2022-05-05 06:03 UTC
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ultimaker 3 Extended

### Reproduction steps

1. Drag and drop stl files to the application from a network drive.
2. Open network drives through the "Open file from" promt.

### Actual results

1. Can't drag and drop stl files to the application from a network drive.
2. Can't open network drives through the "Open file from" promt.

### Expected results

1. Be able to drag and drop stl files to the application from a network drive.
2. Be able to open network drives through the "Open file from" promt.

**Comment by fieldOfView** [comment] 2022-05-05 08:41
Could you please include the requested logs? Cura.log can be found via Help -> Show configuration folder.

**Comment by tonyjosephm** [comment] 2022-05-05 09:11
[cura.log](https://github.com/Ultimaker/Cura/files/8629922/cura.log)

**Comment by fvrmr** [comment] 2022-05-05 11:17
Hi @tonyjosephm thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/12076, so I will close this issue.

**Closed by fvrmr** 2022-05-05 11:17 UTC
Labels: Type: Bug
