### ISSUE TITLE
Print order - when printing one at a time

### ISSUE THREAD

**Issue by men8ifr** [Ultimaker/Cura#7402] opened 2020-04-03 13:50 UTC
**Is your feature request related to a problem? Please describe.**
If you print objects one at a time it is difficult to work out the print order, would it be possible (like Prusaslicer) to label this on objects and allow the order to be changed? 

**Describe the solution you'd like**
label objects which order they are printed in when print one at a time is selected and allow the user to change the order. 

**Describe alternatives you've considered**
Currently I have to scroll the layer height in preview to see the order, then if the order is not correct (it usually isn't) I have to remember the order, go back to prepare and move them around hoping this time they are printed in the order I want. 

**Affected users and/or printers**
Any-one who uses print one at a time 

**Additional context**
Prusa have already done this and using print one at a time is a great way to improve print quality. It can also reduce filament waste if long prints have problems part way through i.e. you get to save the objects already finished rather than waste the entire build plate.

**Comment by Ghostkeeper** [comment] 2020-04-07 14:35
This is a duplicate of https://github.com/Ultimaker/Cura/issues/4835.

There are a number of issues with this feature, as it collides with the way that Cura is preventing collisions between the print head and the models, and our requirement that Cura can't damage the printer without warning.

**Closed by Ghostkeeper** 2020-04-07 14:35 UTC
Labels: Type: New Feature
