### ISSUE TITLE
Scaled input fields mixed up while scaling model z mm and y%

### ISSUE THREAD

**Issue by MakarofDima** [Ultimaker/Cura#7237] opened 2020-03-06 19:12 UTC
**Application version**
4.5.0

**Platform**
Linux home 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Printer**
Flsun qq-s

**Reproduction steps**
Scaled input fields mixed up while scaling model z mm and y%
I try to change the scale of the Z axis in mm, and the Y axis changes in percentage

This happens after loading the model, turning it 90 degrees. Scaling is not correct.

**Screenshot(s)**
https://ibb.co/LQcXqWy

**Comment by Ghostkeeper** [comment] 2020-03-10 10:42
Duplicate of https://github.com/Ultimaker/Cura/issues/4136

**Closed by Ghostkeeper** 2020-03-10 10:42 UTC
Labels: Type: Bug
