### ISSUE TITLE
Mac Cura 4.13.0 crazy preview :-)

### ISSUE THREAD

**Issue by SzymonPriv** [Ultimaker/Cura#11361] opened 2022-01-28 13:32 UTC
### Application Version

4.13.0

### Platform

macOS Monterey 12.1 (latest updates)

### Printer

FL Sun QQS

### Reproduction steps

When previewing anything, the view shows lines all over the place.  Moving around different perspectives (by doing SHIFT+Click+Drag) shows that the odd lines move too.  Screenshots attached in the "actual results" section as this is hard to describe.  The GCODE produced by the slicing is identical to what is was previously -- this appears to be a preview only problem (and therefore not critical).

### Actual results

<img width="556" alt="image" src="https://user-images.githubusercontent.com/22751629/151554779-7f3a406d-38b5-4729-a074-7919b7ae0017.png">
<img width="965" alt="image" src="https://user-images.githubusercontent.com/22751629/151554812-d1dd6f8f-4597-4f36-8916-7192649e6b08.png">
<img width="534" alt="image" src="https://user-images.githubusercontent.com/22751629/151554840-d3ab5f48-d2bd-4084-9667-354ccb965e4f.png">
<img width="627" alt="image" src="https://user-images.githubusercontent.com/22751629/151555516-393dfdc6-01f5-4122-aa38-b5caf2aefc8d.png">

### Expected results

Normal rendered preview without crazy lines.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Here's a project file in case it's of use -- happy to provide anything else I have.  This worked fine on the previous version I had (I think it was 4.11.0, older but not super old).

[xyzCalibration_cube.3mf.zip](https://github.com/Ultimaker/Cura/files/7958944/xyzCalibration_cube.3mf.zip)

**Comment by fvrmr** [comment] 2022-01-31 10:50
Hi @SzymonPriv thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/10387
Because this is a duplicate I will close your issue, you can read there that a reboot fixed it for some people.
Please continue the thread there, so we keep everything in one place.

**Closed by fvrmr** 2022-01-31 10:50 UTC
Labels: Type: Bug
