### ISSUE TITLE
Arachne Beta - Slicing Hangs

### ISSUE THREAD

**Issue by GregValiant** [Ultimaker/Cura#9394] opened 2021-03-13 12:38 UTC
### Application Version

Arachne Beta

### Platform

Win 10

### Printer

Creality

### Reproduction steps

Opened the model
Tried to slice the model

### Actual results

Slicing did not complete.  Slider went blank.

### Expected results

Should have finished slicing

Load the 3mf and try to slice.  I couldn't tell what setting (or combination) caused the problem.  It has something to do with the profile used.  "Top/Bottom Pattern" and Line Directions were not available.
The project file and Cura.log are in the zip file.
[cura.zip](https://github.com/Ultimaker/Cura/files/6134765/cura.zip)

**Comment by fvrmr** [comment] 2021-03-15 12:52
Hi @GregValiant thank you for your bug report.
I am able to slice your model in Arachne beta. 
![Screenshot (114)](https://user-images.githubusercontent.com/77000924/111155994-8309a200-8595-11eb-8257-e3d8f6061265.png)

But the first time I tried, it didn't worked. Also @Ghostkeeper is able to reproduce this, so will we discuss this with the team. Keep you posted.

**Comment by GregValiant** [comment] 2021-03-15 21:00
Thank you.
It appears that when "Top/Bottom" was split from "Shell" that "Top/Bottom Pattern", "Bottom Pattern Initial Layer", and "Top/Bottom Line Directions" didn't get the memo.  FYI...I think that within the profile I used in that 3mf file, I had altered those settings from the defaults.

**Comment by fvrmr** [comment] 2021-03-16 10:36
I have created a ticket on the backlog.
Developers see CURA-8098

**Comment by Ghostkeeper** [comment] 2021-04-01 11:00
> It appears that when "Top/Bottom" was split from "Shell" that "Top/Bottom Pattern", "Bottom Pattern Initial Layer", and "Top/Bottom Line Directions" didn't get the memo. FYI...I think that within the profile I used in that 3mf file, I had altered those settings from the defaults.

As far as I can see, these are all correctly in the Top/Bottom category :confused:

**Comment by GregValiant** [comment] 2021-04-01 12:03
![top-btm](https://user-images.githubusercontent.com/64202104/113291160-9c625c00-92c0-11eb-907c-ca454d017873.png)
I will re-install Arachne and see how it goes.

**Comment by GregValiant** [comment] 2021-04-01 12:58
After re-installing (same download as before) there was no change in the displayed settings.  I have them checked to be visible but they don't show up and as a result, can't be altered.

**Comment by Ghostkeeper** [comment] 2021-04-01 16:09
@jellespijker This might be something to test in your current ticket.

**Comment by jellespijker** [comment] 2021-04-01 16:26
@Ghostkeeper I thought about that, but that would require a version upgrade from version 4000018 to 4000017 with all the dangers if circular upgrades, once the next version comes out.

**Comment by aft7** [comment] 2021-04-30 01:28
Here is a simple model and 3mf that shows the "slicing hangs" problem.

I first noted that slicing would hang if I set top layers to anything other than 0.
Then noted that it worked at full scale, but failed when scaled to 50%.
Then found : If I set Wall Line Count to "2" it works, but a higher value hangs.  Setting top layers to 0 still slices successfully (but not really useful...)
The model has 2mm thick walls, and I was using 0.5mm wall line width.

It appears to hang once the wall line count would be thicker than the actual walls when interacting with top layers?

Also can confirm - "Top/Bottom Pattern" is missing although it is checked in Setting Visibility - screenshot attached.




[arachne-fail.zip](https://github.com/Ultimaker/Cura/files/6402516/arachne-fail.zip)
![top-bottom-pattern-missing](https://user-images.githubusercontent.com/6821091/116637305-bd9a8480-a920-11eb-9183-4f1742ff4792.jpg)

**Comment by fvrmr** [comment] 2022-01-11 15:03
The ticket on our backlog is closed since we can't reproduce this with Arachne second beta. Can you confirm this @GregValiant?

**Comment by GregValiant** [comment] 2022-01-11 16:06
Yes, slicing went as expected and the settings are visible and available.  It looks good in Beta II so I'll close this.  Thanks Fenne.
![Untitled](https://user-images.githubusercontent.com/64202104/148977740-5e07eaa8-8b5f-4e81-a6b0-74b9aa1fdaa2.png)

**Closed** 2022-01-11 16:06 UTC
Labels: Type: Bug, Category: Engine
