### ISSUE TITLE
Models are not kept apart when opening multiple

### ISSUE THREAD

**Issue by deadlyknapsack** [Ultimaker/Cura#10749] opened 2021-11-05 18:10 UTC
### Application Version

4.11.0

### Platform

Mac OS

### Printer

Ender 3 V2

### Reproduction steps

Opening multiple files while "Ensure models are kept apart" is checked, will let all models overlap in center of the buildplate. Have to manually drag them apart. In previous versions, this worked fine.

### Actual results

Files/models are on top of each other.

### Expected results

Distribute models on build plate, to ensure they are kept apart.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

<img width="852" alt="Screenshot 2021-11-05 at 19 08 44" src="https://user-images.githubusercontent.com/16045814/140558376-1a2a8150-0211-4a20-9620-004a7f1164ab.png">
<img width="1103" alt="Screenshot 2021-11-05 at 19 09 04" src="https://user-images.githubusercontent.com/16045814/140558387-51153252-c836-4731-841d-2cb4d142ae26.png">

**Comment by fieldOfView** [comment] 2021-11-07 13:40
Same underlying issue as #10133 and #10249

**Comment by fvrmr** [comment] 2021-11-08 09:19
Hi @deadlyknapsack thank you for your bug report. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/10717 I will close this issue since this is a duplicate.

**Closed by fvrmr** 2021-11-08 09:19 UTC
Labels: Type: Bug
