### ISSUE TITLE
Auto Arrange - Can't Find Location Error

### ISSUE THREAD

**Issue by weidnerj1** [Ultimaker/Cura#12002] opened 2022-04-28 00:20 UTC
### Application Version

5.0.1 Beta

### Platform

Windows 11

### Printer

Creality CR6 SE

### Reproduction steps

Open up two items that are small enough to fit on the plate but are large enough when the first one is centered so that it doesn't enough free space around it for the 2nd item.  The 2nd item will be out in space, and click auto arrange it will give the error Can't Find Location. 
![Screenshot 2022-04-27 191449](https://user-images.githubusercontent.com/7954230/165651334-6ea6858d-003d-4e60-9ee2-9c47e25b662a.jpg)

Now move the center one to the side and place the 2nd object next to it on the plate, both fit.  If trying to auto arrange even when there is enough room to fit the 2nd object next to the first one still get the same error.  

![Screenshot 2022-04-27 191717](https://user-images.githubusercontent.com/7954230/165651530-8298fc97-a2e4-43d6-8b77-093372f5e0b9.jpg)

 

### Actual results

Get the "Can't Find Location" error

### Expected results

Should be able to fit all objects to the plate as long as there is room for it and not leaving objects in space when there is room on the plate if the first object was able to be moved to the side during the auto arrange process.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No addition information required.

**Comment by fvrmr** [comment] 2022-05-02 14:01
Hi @weidnerj1 thank you for your report. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9793, so I will close this issue.

**Closed by fvrmr** 2022-05-02 14:01 UTC
Labels: Type: Bug
