### ISSUE TITLE
[Cura 5] Tool-tip text clipped on high DPI display

### ISSUE THREAD

**Issue by redstone99** [Ultimaker/Cura#11895] opened 2022-04-22 22:24 UTC
### Application Version

5.0.0-beta+1

### Platform

Ubuntu 21.10

### Printer

XYZprinting da Vinci 1.0 Pro

### Reproduction steps

1. Start Cura using a monitor with a high DPI.
2. Open 'Print Settings'
3. However over a setting until the small window pops up with an explanation of the setting. E.g., hover over the "Outer Wall Speed" setting.

### Actual results

A black box pops up with the explanation of the setting. The text in that box is cut-off. Not all of it fits in the box.
See screenshot:

![Screenshot from 2022-04-22 18-16-23](https://user-images.githubusercontent.com/175450/164803214-3d819b8e-66a2-4bcc-b354-fd71bd3cdb69.png)

### Expected results

I expected the black box to pop up with a size large enough to show the text contents.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

See screenshot attached above.

**Comment by fvrmr** [comment] 2022-04-25 11:34
Hi @redstone99 thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11834
I will close this issue since it is duplicate.

**Closed by fvrmr** 2022-04-25 11:34 UTC
Labels: Type: Bug
