### ISSUE TITLE
Cura 4.5.0 - Material specific nozzle/bed temps not transferred to Monitor screen for Preheat options (worked in all previous versions)

### ISSUE THREAD

**Issue by jimmieclark3** [Ultimaker/Cura#7236] opened 2020-03-06 17:22 UTC
**Application version**
Cura 4.5.0

**Platform**
Win 10

**Printer**
Ender 3 - 2 machines (stock ender 3, ender 3 with skr1.2 and microswiss)

**Reproduction steps**
1. Select material
2. Goto monitor screen
3. Preheat temps are blank (this used to autofill)

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/61883319/76106492-f94bef80-5fa4-11ea-93b9-bafcee92cb30.png)

**Actual results**
Have to manually enter these values every time

**Expected results**
They auto fill as previous

**Comment by mahtDFR** [comment] 2020-03-09 08:56
Duplicate of #7172
Fixed by #7178 

A fix will be available in 4.6. Thanks for the report.

**Closed by mahtDFR** 2020-03-09 08:56 UTC
Labels: Type: Bug

**Comment by DeezLBC** [comment] 2020-03-13 01:28
I'm also having this issue. CR10s and Ender 3 on Win10

**Comment by fieldOfView** [comment] 2020-03-13 07:51
Everyone has this issue in Cura 4.5. It has already been reported and fixed for the next version of Cura.
