### ISSUE TITLE
Brim is printing on interior of model despite Only Outside checked.

### ISSUE THREAD

**Issue by mooklepticon** [Ultimaker/Cura#12346] opened 2022-05-25 02:14 UTC
### Application Version

5.0

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

Sliced model with Brim only on outside checked.

### Actual results

Brim is showing on interior parts
![cura brim on inside](https://user-images.githubusercontent.com/19435974/170164662-7f62bb64-e2f4-4bec-b494-ba1e14771495.png)

### Expected results

There should be brim on the outer circle but not the inner gear stars.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

project file:
[gear_bearing sliced.zip](https://github.com/Ultimaker/Cura/files/8767362/gear_bearing.sliced.zip)

**Comment by GregValiant** [comment] 2022-05-25 16:29
What you have there is 8 models and each has the brim on the outside only.  Notice that the center piece does not have a brim on the inside of the hex hole.
That will print fine with a skirt.
I used mesh tools to split the model into it's component meshes.  "Brim on Outside Only" can't be set per model.  With the models split up it looks like this (but this can't be assembled.)  So is this a bug?  Not my call.  Someone from the Cura team will take a look.  I have seen this before on combined models though.
![image](https://user-images.githubusercontent.com/64202104/170313331-a22635dd-faaa-4604-aa08-0cd2b92f7c3f.png)

**Comment by mooklepticon** [comment] 2022-05-25 23:13
@GregValiant 
Interestingly, your image doesn't have brim on the inside of the outer gear, but mine does. Ignore the star gears.
![cura brim on inside rim only](https://user-images.githubusercontent.com/19435974/170383989-ea9fd008-57be-4767-8e22-82e39d2cb773.png)

Additionally, I thought this might be a 5.0 vs 4.X issue, but 4.13 does it, too.

Either I'm mis-remembering (possible) or the last time I printed this years ago, it only had them on the very outside.

**Comment by GregValiant** [comment] 2022-05-26 03:05
The brim on the inside of the outer gear didn't disappear until I moved all the little gears out of the center.  This might be considered a bug by the Cura Team.  I don't know if it's fixable for that STL file though.  Cura is seeing 8 models and treating them like 8 models.

**Comment by mak0t0san** [comment] 2022-05-30 19:22
I'm also seeing this behavior, even for just one model.
![image](https://user-images.githubusercontent.com/987722/171050142-981af88d-7b6f-4b70-bb03-e1dd1cc7eff7.png)

**Comment by GregValiant** [comment] 2022-05-30 20:26
@mak0t0san: in Cura use the File | Save Project command and zip and post the 3mf file.  The Cura Team will need it to recreate the problem.

**Comment by nallath** [comment] 2022-05-31 07:44
It's a known issue. The areas that do get the brim also have something that gets a brim on the outside. As you can see, the letters with a piece inside it do get a brim.

**Comment by Ghostkeeper** [comment] 2022-06-01 12:19
Duplicate of https://github.com/Ultimaker/Cura/issues/4222.

**Closed by Ghostkeeper** 2022-06-01 12:19 UTC
Labels: Type: Bug
