### ISSUE TITLE
issue with naming files in cura

### ISSUE THREAD

**Issue by antony3775** [Ultimaker/Cura#13095] opened 2022-08-22 23:31 UTC
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Creality ender 3

### Reproduction steps

1: clear build plate to remove the last print of the buildplateà
2: open a new stl and change its name before saving
3: I save the gcode on my driver

### Actual results

it instently changes the name of my cura file(mf) to the previous file i cleared off the buildplate. 

 

### Expected results

name should stay the same

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

nothing aditional to add.

**Comment by MariMakes** [comment] 2022-08-26 14:29
Hey @antony3775,

Thanks for your report.
I recognize this issue, It seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/11276.
We have a ticket on our backlog with the intent to resolve it. 
I'm closing this issue but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/11276

Thank you 😄

**Closed by MariMakes** 2022-08-26 14:29 UTC
Labels: Type: Bug, Status: Triage
