### ISSUE TITLE
Cura verwendet Extruder 2 obwohl dies nicht gewünscht ist

### ISSUE THREAD

**Issue by SebastianWorgt** [Ultimaker/Cura#14867] opened 2023-03-13 08:21 UTC
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

Ich habe ein Objekt in Cura eingefügt.
Das Objekt soll mit Ultrafuse 17-4PH gedruckt werden
Ich habe Support eingestellt mit Extruder 1

### Actual results

Cura macht einfach random mehrere Ebenen mit Extruder 2 rein, warum auch immer

### Expected results

Sollte er nicht, es sollte alles in einem Material (Extruder 1) gedruckt werden.
Wenn ich aber Expliziet den Extruder 2 abschalte geht es einwadfrei

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Extruder Bug](https://user-images.githubusercontent.com/127728315/224645188-3fb843ec-1155-4b8a-98b9-14061d52cada.png)

**Comment by MariMakes** [comment] 2023-03-14 16:51
Hey @SebastianWorgt,

Entschuldigung, dass es nicht auf Deutsch ist, aber das könnte helfen.

Welcome to the Ultimaker Community 🎉

What you are seeing is by design. If you print with material from the Metal Expansion Kit the behavior in Cura changes based on the number of extruders enabled. That there is a special Support Material available that makes the removal of the support and the shrinkage plate easier. And that the settings appear by default is to make the workflow as easy as possible. 

If you don't have access to the BASF Forward AM Ultrafuse® Support Layer then you should disable your second print core to only print the metal-filled filament. 

More information on how to print with this material should be available in this [online course Introduction to Metal FFF](https://academy.ultimaker.com/learn/course/280/introduction-to-metal-fff) or [on this support page. ](https://support.makerbot.com/s/article/1667417416406) 

Hope this helps 😄 

To me, it doesn't seem like a bug in Ultimaker Cura, since we have a solution in place. 
I'll be closing this issue. I hope you understand.

**Closed by MariMakes** 2023-03-14 16:51 UTC
Labels: Type: Bug, Status: Triage
