### ISSUE TITLE
Material Manager causes immediate crash

### ISSUE THREAD

**Issue by LilBub** [Ultimaker/Cura#17857] opened 2024-01-01 23:25 UTC
### Cura Version

5.6

### Operating System

Windows 11

### Printer

Ultimaker S5

### Reproduction steps

1 Open Cura
2 Hit Control K 
3 Wait 4 seconds
4 Scary error message
5 Click Send Report

### Actual results

![image](https://github.com/Ultimaker/Cura/assets/14837299/b70dd403-54fa-48c3-aa8c-a7ebdeed826c)

### Expected results

I wanted to Duplicate the Generic PLA to add a new material

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/14837299/c06e8395-aeb6-4e81-9d6d-ed8acf6e10ea)

**Comment by fieldOfView** [comment] 2024-01-03 08:37
Please post your cura.log file, which contains much more information than the screenshot you included.

**Comment by LilBub** [comment] 2024-01-04 01:22
I'm trying to attach the log file but I get it is telling me it does not support that type of file (txt)

**Comment by fieldOfView** [comment] 2024-01-04 12:45
From the logfile attached [here](https://community.ultimaker.com/topic/44784-56-blows-up-when-entering-material-manager/?do=findComment&comment=329189), and the subsequent testing by another user, it seems that this issue is related to the Material Settings plugin. Can you test if disabling that plugin fixes the issue? If it does, please post an issue here:
https://github.com/fieldOfView/Cura-MaterialSettingsPlugin/issues

**Comment by fieldOfView** [comment] 2024-01-07 10:28
From the discussion on the community forum (https://community.ultimaker.com/topic/44784-56-blows-up-when-entering-material-manager/) it follows that this issue is caused by the Material Settings plugin. Therefore I am closing this issue on the main Cura repository, since this is something that needs to be fixed in the Material Settings plugin instead of in Cura.

**Closed by fieldOfView** 2024-01-07 10:28 UTC
Labels: Type: Bug, Status: Triage
