### ISSUE TITLE
[Feature Request] Orthographic View

### ISSUE THREAD

**Issue by krz4tw** [Ultimaker/Cura#5426] opened 2019-03-13 13:38 UTC
Hey,
I just found [#3159](https://github.com/Ultimaker/Cura/issues/3159) and would appreciate that feature very much. I´d suggest a little mod to the old request to make it more easily implementable

I´d like to have orthographic view to be able to postion supportblockers precisely for example.

The zooming and panning should be quite easy to implement if you only enable orthographic view in Top down, left, right,.... view when you choose them via the little cube icons in the top right corner. Those 3-side projections are by far the most useful way for orthographic projection. I don´t need to orbit around in orthographic view.
Zooming could be done by "scaling" what is on the screen and panning just by doing xy offsets of whats already on screen. Once somebody uses right mouse button to orbit switch back to perspective view.
In fact, I´d make orthographic the default when you click on the cube icons.

Thanks

**Comment by Thisismydigitalself** [comment] 2019-03-14 02:51
https://github.com/Ultimaker/Cura/issues/4806

**Comment by krz4tw** [comment] 2019-03-14 13:03
I wish I would have made a notice of everytime I pushed the blender-ortho-view hotkey just out of pure habit in Cura so that I could give you a long list of situations where it would be usefull, sadly I didn´t.
I feel like this would be one of those changes that you never know you needed but don´t want to live without once you have it.

**Comment by Ghostkeeper** [comment] 2019-03-14 13:08
It's one of those things that comes back once in a while because CAD users are used to it. CAD integration is pretty high up on the vision that Ultimaker has for Cura so I expect that it won't take much longer before we get to implement this properly.

**Comment by Ghostkeeper** [comment] 2019-03-20 08:04
This is a duplicate of #2545.

**Closed by Ghostkeeper** 2019-03-20 08:04 UTC
