### ISSUE TITLE
v5 over extruding by quantity and speed

### ISSUE THREAD

**Issue by anthonyonions-avios** [Ultimaker/Cura#18501] opened 2024-03-03 12:17 UTC
### Cura Version

5.6.0, 5.1.1

### Operating System

macOS Sonoma 14.2.1

### Printer

Creality Ender 3 v2 and Max

### Reproduction steps

1. Open STL file
2. Slice
3. Compare GCode to previous version (4.13.1 in my case)

### Actual results

GCode lines show excessive extrusion values.
I have added 4 gcode files in the attached archive.zip sliced using the various installations/versions of Cura, all using the same profile. v4.13.1 has the same extrusion values regardless of which laptop I'm using. V5 installed on Mac shows excessive extrusion. Also checked for the relative extrusion setting and the values added us to the same as the abolsute values so the issue does not seem to be related to absolute/relative values. 
I am unable to install v5 on my windows laptop.

### Expected results

Extrusion values to be the same, or similar

### Add your .zip and screenshots here ⬇️

[Archive.zip](https://github.com/Ultimaker/Cura/files/14472875/Archive.zip)

**Comment by GregValiant** [comment] 2024-03-03 12:45
Thanks for the report.
You are correct, the volumes of the extrusions can and will vary.

Starting with Cura 5.0 the "Arachne Engine" provides variable line width.  As the line width varies then the volume of extruded material must vary.  So your comment _"Extrusion values to be the same, or similar"_ is incorrect because the volume of a particular extrusion might be different than another extrusion of the exact same length.
The formula is still "LayerHeight x LineWidth x ExtrusionLength" but now the LineWidth is not a set number but rather a guideline.

I'll remove the bug label and close this as it is expected behavior.  Let me know of you feel that is premature.

**Closed as completed by GregValiant** 2024-03-03 12:45 UTC
Labels: Type: Discussion, Status: Under Investigation

**Comment by anthonyonions-avios** [comment] 2024-03-03 13:38
Greg, thanks for the information on the Arachne Engine. 

Would the Arachne engine cause the extruder to behave so differently for the same file that's been sliced on a none Arachne engine version of Cura? Please see the attached video for how the extruder is behaving with a v5 sliced file. 

https://github.com/Ultimaker/Cura/assets/150352309/ca2b52d4-ba06-4dde-bc67-04e5875da868

**Comment by GregValiant** [comment] 2024-03-03 13:58
The gcode files are of a small ring so we might be talking apples and oranges here.
![image](https://github.com/Ultimaker/Cura/assets/64202104/13915e3c-25fa-4de9-b78b-1780244570cb)

The behavior I see in the video makes it look like the G92 E0 was ignored (or not present).  When an extruder spins like that it is moving at it's maximum speed to a location it was told to go to.
I "air printed" the gcode files you included and I don't see that behavior.  In addition, the gcode itself looks to be correct.

If you still have the gcode that is in the video pass that along.
