### ISSUE TITLE
Cura does not create a jobname when loading a model through the commandline

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Cura#1703] opened 2017-04-19 13:15 UTC
When loading a model through the command line (eg ```python cura_app.py model.stl``` or by dropping a model on the Cura icon), the job name remains empty. 

Empty jobnames are a problem when saving gcode (a file named ".gcode" will become invisible on certain platforms) or sending gcode to a printer (not sure how the UM3 responds, but the OctoPrintPlugin did not like POSTing a file named ".gcode").

The command line interface is especially critical for people printing directly from Fusion 360.

**Comment by Ghostkeeper** [comment] 2017-04-24 08:57
Thanks for getting to the bottom of those issues and finding the root cause. I'm sure we can find a fix for this.

**Closed** 2017-05-03 12:19 UTC
Labels: bug

**Comment by Ghostkeeper** [comment] 2017-05-05 10:59
To clarify, this issue has been fixed since then.

**Comment by Wisnaeme** [comment] 2017-05-14 09:28
I still have this problem. What was the fix for this?

**Comment by fieldOfView** [comment] 2017-05-14 09:34
It has been fixed in the source code, but a fixed version has not yet been released. Cura 2.6 beta will be the first version with the fix.

Specifically, if you are running Cura 2.5 from source and want to apply the fix yourself, this is the fix:
https://github.com/Ultimaker/Cura/pull/1781/files
