### ISSUE TITLE
Custom profiles missing

### ISSUE THREAD

**Issue by hyudryu** [Ultimaker/Cura#9901] opened 2021-05-24 10:59 UTC
### Application Version

4.9.1

### Platform

Windows 10

### Printer

CR-10

### Reproduction steps

This issue started happening after upgrading from 4.6.x -> 4.9.0 The issue remained after upgrading from 4.9.0 -> 4.9.1

1. The issue occurs upon opening the app.

### Actual results

When I run Cura, it is missing a lot of my custom profiles. One of my custom profiles was actually loaded by default, but is missing from the drop-down menu. Here's an example of what's missing. I had a profile named "CR10 .6 CF PC" which was selected by default after opening the software, but is nowhere to be found in the drop-down menu, nor in the settings.
![image](https://user-images.githubusercontent.com/22283864/119337611-e540ec00-bc43-11eb-87ae-8ef893e2a0aa.png)
![image](https://user-images.githubusercontent.com/22283864/119337656-f4c03500-bc43-11eb-81ec-d3407e401891.png)

This is one of many custom profiles that are missing

### Expected results

The expected results would be to have all my custom profiles visible.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/6531827/cura.log)

**Comment by hyudryu** [comment] 2021-05-24 11:01
After closing and re-opening the program, sometimes the custom profiles will magically show up again. This was after closing the program 3 times and opening for the 4th time, Heisenbug perhaps?
![image](https://user-images.githubusercontent.com/22283864/119338275-a65f6600-bc44-11eb-9c5b-5d1e3247e587.png)

**Comment by fvrmr** [comment] 2021-05-25 13:37
Hi @hyudryu thank you for your report. 
Did it just solve doing a plain restart? Did you maybe change your material? Because profiles are related to materials.

**Comment by hyudryu** [comment] 2021-05-30 11:14
Hi @fvrmr , thank you for getting back to me regarding this issue. I've been using Cura since day 1, and I have not once touched the "materials" selection. I've always stuck with the default material, and just made new profiles for the different filaments I have.

Restarting it is a hit or miss, sometimes it will take multiple restarts for the profiles to appear, sometimes it takes 1 restart. Aside from the restart, I don't do anything else. I usually keep Cura running in the background 24/7, I never really close it out since I slice and print multiple things every week. Sometimes the issue just randomly pops up when I switch over to Cura after a while. 

Please let me know if there's any more information that I can help provide!

**Comment by fvrmr** [comment] 2021-05-31 14:06
Hi @hyudryu thank you.

I think it is a duplicate of https://github.com/Ultimaker/Cura/issues/8229

There you can read that there was a bug in 4.6 with wrong profiles and since you come from 4.6 to 4.9 I think that is why this is happening to you. 

Here is how profiles should work: https://github.com/Ultimaker/Cura/issues/8229#issuecomment-680042094
And here is a work around to migrate your profiles the correct way: https://github.com/Ultimaker/Cura/issues/8229#issuecomment-684799909

Let me know if that works for you!

**Closed** 2021-06-14 15:00 UTC
Labels: Status: Needs Info, Type: Bug
