### ISSUE TITLE
Wall ordering on thicker layer profiles not optimal 

### ISSUE THREAD

**Issue by glx-seven** [Ultimaker/Cura#12721] opened 2022-07-10 05:21 UTC
### Application Version

5.0.0

### Platform

Windows 10 / MacOS 12.4

### Printer

Ultimaker S5

### Reproduction steps

Slicing any object with overhangs with the 0.3mm experimental profiles.

### Actual results

Due to the thick layers walls with overhangs become very inconsistent, since the outer line has nothing to adhere to and the outermost lines are printed first.

### Expected results

For at least the thicker layer profiles in my opinion the "wall order" "inside to outside" would be beneficial.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Here are the bottom sides of parts with 45° chamfers at the bottom. They are printed with Ultimaker Tough PLA with the "0.3mm Experimental" profile. 
These are with the default outside to inside: 
![98485E9E-41B8-406B-9A58-E4388FCEDB36](https://user-images.githubusercontent.com/19342476/178132298-db409500-b057-4a03-9025-434247a1ed01.jpeg)

These are the same parts with inside to outside:
![FC4B9098-0C40-4398-A619-B447B0ED502D](https://user-images.githubusercontent.com/19342476/178132300-a4bc0e52-5527-48a6-b9b8-e31c87247413.jpeg)

**Comment by GregValiant** [comment] 2022-07-10 11:55
Thanks for the report.
This is a duplicate of #12517.  It is always better to have multiple reports than just one as sometimes the behavior is different.
I will close this one as a duplicate.  If you feel that is incorrect let us know.

**Closed by GregValiant** 2022-07-10 11:55 UTC
Labels: Type: Bug, Status: Duplicate
