### ISSUE TITLE
Material/Filiment Bug went setting up new profiles.

### ISSUE THREAD

**Issue by InjectOH4** [Ultimaker/Cura#1700] opened 2017-04-19 05:26 UTC
https://www.youtube.com/watch?v=kL9LEQ0j5Ug
As you can see in the video sometimes when you duplicate some profiles and change them. It effects both the old and new even when the names are different. 

In the video i change TPU to 50g weight, and ABS to 1000g. 
However when one changes to 50 so does the other, and the reverse.

Also you really need to remove the DUPLICATE button and make a ADD button. It's quite silly the way it's setup. 

Version 2.5 Beta.

**Comment by Ghostkeeper** [comment] 2017-04-19 08:53
Duplicate of https://github.com/Ultimaker/Cura/issues/1597

**Closed** 2017-04-19 08:53 UTC
Labels: duplicate
