### ISSUE TITLE
No retraction distance in Per Model Setting

### ISSUE THREAD

**Issue by JBKAG** [Ultimaker/Cura#19803] opened 2024-10-25 10:21 UTC
### Cura Version

5.9.0 beta

### Operating System

Windows 10

### Printer

Ender 5 Plus

### Reproduction steps

When choosing "Per model settings" the retraction distance is not visible.
Possibly other parameters could be also missing, I haven`t checked that though...

### Actual results

Retraction distance is not present in the parameters to select in "Per model setting".

### Expected results

This would be useful to calibrate retraction during one print, while having several models with different retraction distance setting per each model.

### Add your .zip and screenshots here ⬇️

![retr](https://github.com/user-attachments/assets/b1060eb0-7926-44a3-8563-4dde532b2898)

**Comment by GregValiant** [comment] 2024-10-27 10:56
Thanks for the report.
It is not "settable per mesh" and so is not available to use on blockers or "per model".  That is by design.  I'm not sure why that is so, but it may simply have been too complex to enable, or no use for it was anticipated.
You could change this to a feature request, but it's "expected behavior" rather than a bug and so I'll remove the label and close this.  I hope you understand.

You can use "Change at Z" to make changes to the retraction amount (and/or speed) as a single model builds upward.

**Closed by GregValiant** 2024-10-27 10:56 UTC
Labels: Type: Discussion, Status: Under Investigation
