### ISSUE TITLE
GCODE filename out of loaded STL

### ISSUE THREAD

**Issue by kr15uk** [Ultimaker/Cura#1776] opened 2017-05-02 09:35 UTC
Ladies and gents,

Don't know if this is a glitch or feature but since v2.5.0 when you load STL file it doesn't update file name automatically.
<img width="817" alt="screen shot 2017-05-02 at 10 30 27" src="https://cloud.githubusercontent.com/assets/5671041/25612441/9d356290-2f22-11e7-9e40-aab3db335989.png">
Thanks.

Kris M

**Comment by fieldOfView** [comment] 2017-05-02 09:54
Duplicate of https://github.com/Ultimaker/Cura/issues/1703

**Closed** 2017-05-03 09:53 UTC
