### ISSUE TITLE
Please fix PLA+ material issue

### ISSUE THREAD

**Issue by NiLMoXiE** [Ultimaker/Cura#13498] opened 2022-10-07 20:32 UTC
### Application Version

All

### Platform

Windows 10 Nvidia RTX3090

### Printer

Ender 3

### Reproduction steps

Duplicated eSUN Black PLA+ to change colour and print settings

### Actual results

Just the action of duplicating the material results in the duplicated material being not compatible with any profiles. 

### Expected results

PLA+ should duplicate without being non compatible with profiles

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I understand that changing the material type to PLA fixes the issue but doing so moves it to the PLA drop down, it should remain in the PLA+ material drop down. I have read multiple times that it is because Cura doesnt know what PLA+ is, as there aren't any generic profiles for it - but the default ones work so why can't the duplicates?

Duplicating any material should work just like any of the defaults without resulting in non compatibility. Every other material works except PLA+.

Maybe the default materials should be editable to an extent, for example, display name, colour and print settings?

**Comment by MariMakes** [comment] 2022-10-10 12:09
Hey @NiLMoXiE,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report, I recognize your issue. 

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/8229
We have a ticket on our backlog with the intent to improve this behavior.
We are looking at a solution where you are limited to selecting a material from a dropdown. 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/8229
You will also find a good explanation of the problem and possible workarounds there. 👍

**Closed by MariMakes** 2022-10-10 12:09 UTC
Labels: Type: Bug, Status: Triage
