### ISSUE TITLE
Anycubic i3 Mega S/Pro Cura crashes when printing over usb

### ISSUE THREAD

**Issue by jeremiah-vanofferen** [Ultimaker/Cura#12040] opened 2022-04-30 20:24 UTC
### Application Version

5.0

### Platform

Windows 10

### Printer

Anycubic i3 Mega S/Pro

### Reproduction steps

1. Sliced STL which works on version 4.13 and selected print via usb option

### Actual results

Appears when print buffer hits limit about 3 or 4 layers in Cura crashes, window closes and printing stops
[cura.log](https://github.com/Ultimaker/Cura/files/8597756/cura.log)

### Expected results

Print should finish and Cura window should remain open

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

STL file location
https://www.thingiverse.com/thing:4795401/files

**Comment by fvrmr** [comment] 2022-05-02 09:04
Hi @jeremiah-vanofferen thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11896, so I will close this issue.

**Closed by fvrmr** 2022-05-02 09:04 UTC
Labels: Type: Bug
