### ISSUE TITLE
malformed printer configuration causes cura to crash

### ISSUE THREAD

**Issue by cederom** [Ultimaker/Cura#1187] opened 2016-11-27 22:21 UTC
```
2016-11-27 23:20:12,876 - CRITICAL - /Users/ultimaker/build/2.3/build/inst/lib/python3.5/site-packages/cura/CrashHandler.py (show [24]): RecursionError: maximum recursion depth exceeded in comparison
qmlRegisterSingletonType(): "ProfilesModel" is not available because the callback function returns a null pointer.
Abort trap: 6
```

**Comment by cederom** [comment] 2016-11-27 22:54
Also malformed configuration can be somehow stored in the printer list. Then it is impossible to remove that printer from a list as the application crashes:

```
Version: 2.3.1
Platform: Darwin-16.1.0-x86_64-i386-64bit
Qt: 5.6.1
PyQt: 5.6

Exception:
Traceback (most recent call last):
  File "/Users/ultimaker/build/2.3/build/inst/lib/python3.5/site-packages/cura/Settings/MachineManager.py", line 1046, in getDefinitionByMachineId
AttributeError: 'NoneType' object has no attribute 'getId'
```

**Comment by awhiemstra** [comment] 2016-11-28 09:38
Yeah the problem here is that we set the active printer in the constructor of cura/Settings/MachineManager . If that constructor fails it fails to return a proper instance of that class triggering a loop. I have been meaning to fix that but never got around to it.

**Comment by ChrisTerBeke** [comment] 2017-11-14 20:43
Is this still an issue?

**Comment by ianpaschal** [comment] 2018-03-26 08:55
I can't reproduce it in 3.3 by mangling my printer configs, so I'm marking it as fixed.

**Closed by ianpaschal** 2018-03-26 08:55 UTC
Labels: Type: Bug
