### ISSUE TITLE
Preheat commands as first lines before custom start code

### ISSUE THREAD

**Issue by hawkeyexp** [Ultimaker/Cura#19278] opened 2024-06-23 17:37 UTC
### Cura Version

5.7.2

### Operating System

Windows 11

### Printer

Voron 2.4

### Reproduction steps

Slice an Object seems to happen on all tries

### Actual results

;FLAVOR:Marlin
;TIME:7083
;Filament used: 10.2117m
;Layer height: 0.2
;MINX:93.05
;MINY:119.3
;MINZ:0.2
;MAXX:255
;MAXY:230.7
;MAXZ:40.3
;TARGET_MACHINE.NAME:VORON2 350
;Generated with Cura_SteamEngine 5.7.2
**M104 S220
M105
M109 S220**
M82 ;absolute extrusion mode
PRINT_START BED_TEMP=70 EXTRUDER_TEMP=220.0

### Expected results

;FLAVOR:Marlin
;TIME:7083
;Filament used: 10.2117m
;Layer height: 0.2
;MINX:93.05
;MINY:119.3
;MINZ:0.2
;MAXX:255
;MAXY:230.7
;MAXZ:40.3
;TARGET_MACHINE.NAME:VORON2 350
;Generated with Cura_SteamEngine 5.7.2
M82 ;absolute extrusion mode
PRINT_START BED_TEMP=70 EXTRUDER_TEMP=220.0

### Add your .zip and screenshots here ⬇️

![grafik](https://github.com/Ultimaker/Cura/assets/761728/dda6a879-e01e-47a9-a06d-3fc4a10333bc)

**Comment by GregValiant** [comment] 2024-06-23 17:54
Thanks for the report.
This is duplicate of numerous other reports of this behavior.  #19204 is the main report and there are many comments.

Here is a little script to fix the bug. Unzip and stick "CuraPrependBugFix.py" into the "scripts" folder in your Configuration Folder. It will be available under "Extensions / Post Processing / Modify Gcode" and then "Add Script".
Let me know if there are issues.
[CuraPrependBugFix.zip](https://github.com/user-attachments/files/15945513/CuraPrependBugFix.zip)

I'll mark this as a duplicate and close it as the Cura team is aware of this bug.

**Closed by GregValiant** 2024-06-23 17:54 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation
