### ISSUE TITLE
Improved prime tower

### ISSUE THREAD

**Issue by Juusoz** [Ultimaker/Cura#10885] opened 2021-11-19 23:19 UTC
### Is your feature request related to a problem?

The prime tower in Cura is currently really wasteful. It primes on layers layers that do not have a tool change, for example. This gets expensive fast if you're using more expensive materials like PVA, for example.

In this example picture, more PVA is being used on the prime tower than PLA on the entire actual print, despite PVA only being used in a couple of spots. Interestingly enough, this only happens if the PVA is fed into the number 1 extruder and not into the number 2 extruder. More on that in solution 3.2.

![Screenshot_2](https://user-images.githubusercontent.com/48849652/142696131-7c929af8-85d4-4dd8-a994-2e37b73ae57a.png)

### Describe the solution you'd like

There are a couple of things that can help with this:
1. **Skip priming on layers that do not have a tool switch**. PrusaSlicer and SuperSlicer have this. And Cura does have the "Gantry Height" machine setting that would make keeping track of whether or not it can skip the prime layer really easy. 

![Screenshot_1](https://user-images.githubusercontent.com/48849652/142702321-5098d848-be89-4905-8d9b-1a576bfb172b.png)

Not only would this reduce the amount of priming required, it would also lower the amount of torque applied onto the prime tower, thus reducing the risk of print failure.

![IMG_20211121_145329](https://user-images.githubusercontent.com/48849652/142762732-3f083fd1-2865-4d8a-8714-66fcc09ea1dc.jpg)

2. **Print infill (and supports) with prime material**. Using the prime for the infill of the model would open up the opportunity to not do full, solid layers in the prime tower. You could have a variable infill density in the prime tower to match the amount of material you no longer need to prime.

![Screenshot_3](https://user-images.githubusercontent.com/48849652/142701287-c303f684-08eb-4bcf-9bb4-9f353e08c89e.png)

3. **Some quality of life improvements**.
3.1. **Move the nozzle to the prime tower when changing the extruder**. Currently, the nozzle just stays on top of the print while changing the extruder. This causes a blob to form under the nozzle due to the leftover material in the nozzle, affecting the quality of the print.
3.2. **Prime tower infill**. Currently, if the second extruder is only needed at the top of the print, the prime tower will attempt to prime a circle in mid-air, which can cause the material to get stuck hanging from the extruder, which can lead to print failure. A way to prevent this would be to add a low percent infill under the extrusion.
3.3. **Have the inner priming circle prime from inside-out rather than outside-in**. The prime towers currently have the slight issue of the priming starting with a bit of a delay. This causes the inner circle not adhere to the outer circle at all. And if the cicle is primed mid-air, this will typically cause the primed chunk to come loose and leave the priming area, causing lots of primed chuncks to fall into the print area.
3.4. **Prime tower wipe**. I've tried optimizing my prime tower quite a lot, but I keep getting a lot of stringing between the prime tower and the print. Looking at the .gcode files, you can see that the printer does not do a wipe on the tower, even with "_Wipe Inactive Nozzle on Prime Tower_"  enabled. This could be the cause of the stringing. The wipe should be done towards the other priming circles, as this will help the circles adhere to each other.
3.5. **No override for support material**. Currently, Cura does not have a no override option for support material, but it does for infill material. This would have the potential of ending the need for prime tower earlier than when forcing the material to be one or the other.

### Describe alternatives you've considered

I've completely minimized the amount of priming I need to do using base Cura, but it still is not enough. I'm considering switching to SuperSlicer because their prime tower is better than yours.

### Affected users and/or printers

All printers with 2 to 1 material nozzles will benefit from this.

**Comment by fvrmr** [comment] 2021-11-22 16:33
Hi @Juusoz thank you for your request.
You can disable Wipe Inactive Nozzle on Prime Tower. But I noticed that you are using PVA on extruder one and extruder one will always extrude. If you switch your extruders that should help a bit. 

About the second point, see https://github.com/Ultimaker/Cura/issues/3657

Your third point will be bring up for discussion with the profile and materials team. Keep you posted.

**Comment by Juusoz** [comment] 2021-11-23 00:03
>But I noticed that you are using PVA on extruder one and extruder one will always extrude. If you switch your extruders that should help a bit.

Yeah, I noticed that, but unfortunately it won't be possible in my situation. You see, I have two extruders on my printer, one on the left side of the printer and one on top of it. And my PVA is stored in a fairly large drybox to the left of it, so I literally am not able to put the PVA into the top extruder without modifying the printer.

![IMG_20211123_015150](https://user-images.githubusercontent.com/48849652/142952236-7489c53b-47e8-4a21-9f7c-fa9daf300b80.jpg)

I don't know how hard it would be to implement, but it would be nice to be able to pick which extruder to make the prime tower shell with.

Although, then again, this might just be a me problem.

**Comment by Ghostkeeper** [comment] 2021-11-26 12:45
This is a duplicate of https://github.com/Ultimaker/Cura/issues/5282. Please continue the conversation there.

Any other issues should be made into separate tickets. It's impossible to track the status of them otherwise.

**Closed by Ghostkeeper** 2021-11-26 12:45 UTC
Labels: Type: New Feature

**Comment by Ghostkeeper** [comment] 2021-11-26 12:48
> extruder one will always extrude. If you switch your extruders that should help a bit.

This is not entirely true. It will select the material with the greatest Adhesion Tendency as the one to use for the outer shell of the prime tower. For PLA this setting is greater than for PVA, so I'd expect the PLA extruder to still be used for the outer shell.
