### ISSUE TITLE
Speed is in wrong units (travel in mm/s instead of extruded volume of cubic millimeters per second) - hot-ends can only melt so much - melt capability should determine travel speed instead of hard-coding some guess in mm/s.

### ISSUE THREAD

**Issue by gitcnd** [Ultimaker/Cura#10894] opened 2021-11-21 16:18 UTC
### Is your feature request related to a problem?

All the speed settings need to be laboriously fixed when the nozzle size or filament chemistry is changed... this makes no sense... my hot-end can only melt so much filament, irrespective of the nozzle size, is the same amount.

Cura should know this, and work out it's own speed to suit.

mm/s makes no sense when missing the context of how much plastic is being melted.

### Describe the solution you'd like

Split all speed inputs so we can provide our flow-rate (and perhaps an optional max-speed-not-to-exceed) - ideally, some kind of printer hot-end setting combined with the selected filament would be ideal - so Cura re-computes all the speeds properly and automatically when we change either of those.

### Describe alternatives you've considered

Laboriously re-test everythign every time I change nozzles or fillament

### Affected users and/or printers

Everyone

**Comment by Ghostkeeper** [comment] 2021-11-29 10:30
Duplicate of https://github.com/Ultimaker/Cura/issues/5248.

Aside from a volumetric rate limit, you'd still need a velocity limit (X/Y/Z) because the printer is not just limited by how much it can extrude, but also by the processing speed, motor capability and the stiffness of the frame. Going too fast would cause vibrations resulting in ringing in the print, and cause buffer underruns in the motion planner. It's also what most users are used to; it's easier to visualise for novices and thus easier to adjust for them.

That thread discusses the integration of both of them.

**Closed by Ghostkeeper** 2021-11-29 10:30 UTC
Labels: Type: New Feature
