### ISSUE TITLE
"Cura 3.4.1" Save as

### ISSUE THREAD

**Issue by Kernfusion** [Ultimaker/Cura#4241] opened 2018-08-15 20:17 UTC
When I klick the Bottom "Save as" is always double "gcode.gz" for examble  UM3E**********.gcode.gz.gcode.gz 
WINDOWS10

**Comment by BagelOrb** [comment] 2018-08-16 06:47
We are aware of this issue and we are currently discussing what to do with it. Somehow it is hard to get rid of this thing.

**Comment by ChrisTerBeke** [comment] 2018-08-16 20:13
Duplicate of multiple tickets.

**Closed by ChrisTerBeke** 2018-08-16 20:13 UTC
