### ISSUE TITLE
Feedrate Color Scheme Enhancement

### ISSUE THREAD

**Issue by alsmithson** [Ultimaker/Cura#6807] opened 2019-12-14 04:27 UTC
I would like the feedrate color scheme (or at least the key) to adjust based on what line types are shown rather than every line type in the gcode. That is, the color range would be limited to speeds between the fastest and slowest lines visible on the platform.

![Color Scheme Before](https://user-images.githubusercontent.com/24710412/70843452-569a2f80-1e00-11ea-83fd-7db77ed8d44f.gif)
![Color Scheme After](https://user-images.githubusercontent.com/24710412/70843453-5f8b0100-1e00-11ea-8b56-5882af2ab439.gif)

Many things override the basic print speed setting such as the minimum layer time, bridge speed, ironing, etc.. Unexpected speed changes affect the surface finish (there is even an app that varies speed to show a photo or texture on a 3D a print).  I often use the feedrate color scheme to uncover these unwanted speed changes. Unfortunately, travel moves are often 3 or 4 times faster than extrusion moves and the color range in the key always includes these very high speeds. It is not possible to visually discern between smaller changes such as 40mm/s for outer shells dropping to 20 in a narrow place. 

I temporarily reduce travel and other speeds to very small values so I can see those small differences in the outer shell. That is not a very satisfactory solution

**Comment by Ghostkeeper** [comment] 2019-12-16 12:53
Duplicate of https://github.com/Ultimaker/Cura/issues/3598.

**Closed by Ghostkeeper** 2019-12-16 12:53 UTC
Labels: Type: New Feature
