### ISSUE TITLE
All Files Fail When Slicing w/ Supports!

### ISSUE THREAD

**Issue by Soulfurous** [Ultimaker/Cura#16809] opened 2023-09-24 19:57 UTC
### Cura Version

5.4

### Operating System

Windows 11

### Printer

Elegoo Neptune 2D

### Name abnormal settings

I use a custom profile for all of my prints, but enabling support settings seems to be the culprit.

### Describe model location

No, it fails regardless of orientation

### Describe your model

This is the first time I'm printing this model, but I have received the same error on other models I have printed previously.

### Add your .zip here ⬇️

I recently upgraded my GPU to an RTX 4090, so I doubt it's graphics related (although I won't rule it out).
[Bot_TurtleShellBase.zip](https://github.com/Ultimaker/Cura/files/12709552/Bot_TurtleShellBase.zip)

**Comment by GregValiant** [comment] 2023-09-24 23:00
Thanks for the report. and the file.
There is a bug in 5.4.0 that can keep a model from slicing.  There are three workarounds that can fool the bug.

- Rotate the model.
- Move the model.
- Change the Initial Layer Height by a little bit.

I'll mark this as a duplicate of numerous other reports.  I'll go ahead and close this as the Cura team has a lot of examples of this behavior.  I hope you understand.
![image](https://github.com/Ultimaker/Cura/assets/64202104/4b791349-72be-4444-8b4c-3d4a70e260e5)

**Closed by GregValiant** 2023-09-24 23:00 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation, Slicing Error :collision:
