### ISSUE TITLE
Cannot Slice Files in Cura 5

### ISSUE THREAD

**Issue by RBaxter09** [Ultimaker/Cura#12882] opened 2022-07-27 18:17 UTC
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

Clicked slice and was unable to slice "Due to a Bug"

### Actual results

Clicked slice and was unable to slice "Due to a Bug"

### Expected results

Click Slice
save to be able to removable SD card 

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![Bug](https://user-images.githubusercontent.com/106452067/181343777-5efe93c1-a084-4753-81b1-4a8d5884af70.PNG)

**Comment by GregValiant** [comment] 2022-07-28 03:08
Thanks for the report.
That's about the 4th time I've seen that model here.  It has a LOT of errors in it.  You can use MS 3D Builder to repair it, or there are free on-line tools you can use.
This isn't a Cura problem and it is a duplicate of previous reports on that "Crystal Dragon".  I'm going to close this but you can still respond here if you think that is premature.

After repairing the model you can see that it slices fine.  
![image](https://user-images.githubusercontent.com/64202104/181411349-71b1cac8-c1d5-428a-9625-25a3f6d152ee.png)

**Closed by GregValiant** 2022-07-28 03:08 UTC
Labels: Status: Duplicate, Type: Discussion
