### ISSUE TITLE
Slicing failure

### ISSUE THREAD

**Issue by kdomkus** [Ultimaker/Cura#12629] opened 2022-06-28 17:26 UTC
### Application Version

5.0.0

### Platform

Win 10

### Printer

Ultimaker S3

### Reproduction steps

Downloaded Benchy from Thingiverse 
https://www.thingiverse.com/thing:763622
Chose all default settings for PLA

### Actual results

Error message saying it failed with an unexpected error.

### Expected results

Should have sliced it.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Benchy.zip](https://github.com/Ultimaker/Cura/files/9003383/Benchy.zip)

**Comment by GregValiant** [comment] 2022-06-28 18:15
Thanks for the report.  This is a duplicate of #12611 (and a few others) and so I will close this.
As a workaround, try rotating the model on the build plate.  It would not slice for me the way it came into Cura but rotating it worked to get Cura to slice.

**Closed by GregValiant** 2022-06-28 18:15 UTC
Labels: Type: Bug, Status: Duplicate, Status: Under Investigation
