### ISSUE TITLE
object of type SettingFunction is not JSON serializable

### ISSUE THREAD

**Issue by Linkenelis** [Ultimaker/Cura#13829] opened 2022-11-15 15:23 UTC
### Application Version

5.2.1

### Platform

Windows 10

### Printer

modified Saphire plus

### Reproduction steps

Print with octoprint

### Actual results

error: object of type SettingFunction is not JSON serializable

### Expected results

Should have written the file to Octoprint just like 5.1.0 still does

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Error:   ![image](https://user-images.githubusercontent.com/58143885/201956806-58447345-7708-48ae-a8c5-b1735a4f61e7.png)
I still have the previous version, that keeps working as normal

**Comment by Kedryn** [comment] 2022-11-27 14:45
Me too

**Comment by fieldOfView** [comment] 2022-11-27 14:58
Neither @Kedryn nor @Linkenelis have provided logs. That makes it harder for us to fix this.

Please see https://github.com/Ultimaker/Cura/blob/main/docs/Report.md#cura-gui-log about where to find the logs and post them here.

**Comment by fieldOfView** [comment] 2022-11-27 16:05
This is also a duplicate of #13675, so I am closing this issue in order to keep the discussion centralized.

**Closed by fieldOfView** 2022-11-27 16:05 UTC
Labels: Type: Bug, Status: Triage

**Comment by Linkenelis** [comment] 2022-11-27 20:34
@fieldOfView : sorry for not sending a log...
Update is that it started again, for no reason that I can see. It might be the reboot of my PC that fixed it.
