### ISSUE TITLE
start code area

### ISSUE THREAD

**Issue by tombmatt** [Ultimaker/Cura#14852] opened 2023-03-12 03:08 UTC
### Application Version

5.2.1

### Platform

Windows 10

### Printer

ender 3 pro

### Reproduction steps

tried to edit start code
clicked in area 

### Actual results

instuctions (black info  page) poped up would not close until i moved cursor off area. moved back to area popup returned. can not edit start code

### Expected results

move cursor into start code area no popup or popup opens to side not blocking area. able to enter text in code area

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

unable to use cura if i can't complete start code

![1Untitled](https://user-images.githubusercontent.com/11861713/224522001-88d1a45f-dc76-4474-ab38-9accb524396f.png)
![2Untitled](https://user-images.githubusercontent.com/11861713/224522002-99baf657-9028-4ee5-81d2-0c93f826d02c.png)

**Comment by MariMakes** [comment] 2023-03-17 17:09
Hey @tombmatt,

Thanks for your report 👍

I've seen this before, this seems to be related to the Settings Guide Plug-in. If this pop-up makes using the machine settings unusable, you can consider temporarily disabling the plug-in in the marketplace by clicking the gear next to Plugins Materials and disabling the plug-in there. 

If you want to use it again you can enable it from the same menu. 
Hope this helps. 

To me, it doesn't seem like a bug in Ultimaker Cura anymore, since it is caused by a plug-in.
Would you still like to keep this issue open or do you agree that we can close it?

**Closed** 2023-04-21 12:49 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage
