### ISSUE TITLE
[4.0.0] Shadow not updated after reload of a model

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#5641] opened 2019-04-19 10:20 UTC
**Application Version**
4.0.0

**Platform**
Linux, but sure it doesn't matter

**Printer**
Doesn't matter

**Steps to Reproduce**
 * load an STL model [1]
 * make changes to that file
 * reload the file in Cura

**Actual Results**
Shadow doesn't match the new model [2]

**Expected results**
Shadow should match to the model

**Additional Information**
[1] First iteration
![image](https://user-images.githubusercontent.com/1847437/56420230-755e1b80-629d-11e9-877c-8b42367f6c5d.png)
[2] After reload of second iteration
![image](https://user-images.githubusercontent.com/1847437/56420248-8575fb00-629d-11e9-91e8-d16c7f3582ab.png)

**Comment by Ghostkeeper** [comment] 2019-04-24 05:08
Unable to reproduce this. We recently did some work on the signals related to this though, so perhaps it has been fixed in master.

**Comment by diegopradogesto** [comment] 2019-06-20 10:02
I could reproduce it in 4.0, but not in 4.1. It's been magically fixed, then. @thopiekar could you please confirm?

**Closed by diegopradogesto** 2019-06-20 10:02 UTC
Labels: Category: Cura, Status: Needs Info, Type: Bug
