### ISSUE TITLE
build plate Y axis shortened 

### ISSUE THREAD

**Issue by calconroy** [Ultimaker/Cura#7371] opened 2020-03-30 10:48 UTC
**Application version**
4.5.0

**Platform**
OSX

**Printer**
Ender-3 

**Reproduction steps**

**Screenshot(s)**
![Uploading Screen Shot 2020-03-30 at 12.47.32 PM.png…]()

**Actual results**
cura imposed print restrictions on the y axis. reduced printable area to 235mm(x) x205mm(y)

**Expected results**
no change in size for the printable area

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by mahtDFR** [comment] 2020-03-30 13:53
Your screenshot upload didn't work. Sounds like a duplicate of #7252

**Closed** 2020-03-31 13:36 UTC
Labels: Type: Bug
