### ISSUE TITLE
temp changes not working

### ISSUE THREAD

**Issue by doctortwitchy** [Ultimaker/Cura#19308] opened 2024-06-30 01:55 UTC
### Cura Version

5.7.2

### Operating System

Windows 10

### Printer

Anycubic Chiron with CR10 profile in cura, firmware modified to allow higher temps with marlin 2.1.1.2

### Reproduction steps

I set up a temp tower to start at 300C

### Actual results

after every temp change, the temp resets immediately to the starting temp
![Capture](https://github.com/Ultimaker/Cura/assets/174222390/fb85fbe1-b02d-43e3-a009-da88616184cf)
![Capture](https://github.com/Ultimaker/Cura/assets/174222390/b4b61e3d-8bbd-4be0-b5a9-fd7eee23d94a)

### Expected results

temperature should stay at values assigned in GUI

### Add your .zip and screenshots here ⬇️

![Capture](https://github.com/Ultimaker/Cura/assets/174222390/5ace4725-e4ca-4074-b304-c919b94086e9)
![Capture1](https://github.com/Ultimaker/Cura/assets/174222390/2fd127ee-a7d3-46d8-a37d-f905e3b4b2e1)

**Comment by GregValiant** [comment] 2024-06-30 13:16
Thanks for the report.
You did not supply a project file so I have to make some assumptions.
It appears that you have set up "ChangeAtZ" in a manner that causes each instance to over-write the effect of the previous instance.  That's not a bug but rather "expected behavior" if all your instances are set to trigger at 1.6mm height.
Each instance needs to trigger at a specific height or layer.
With each instance set to change at a specific height I get this at every change:
![image](https://github.com/Ultimaker/Cura/assets/64202104/247c5b08-2c4d-442c-b603-62cdea06a682)
That was the third change and you can see that it is NOT being over-written by the previous instances of "ChangeAtZ".

I'm going to go ahead and remove the bug label and close this as it appears to be a settings issue.  If you continue to have problems post a project file and I'll take another look.

There is a plugin available in the MarketPlace called "AutoTowers Generator".  I have not used it but it does look like you would also need to install "OpenSCAD" to add custom temperatures.

**Closed by GregValiant** 2024-06-30 13:16 UTC
Labels: Type: Discussion, Status: Under Investigation
