### ISSUE TITLE
[2.6.2] Printer idle on top of object when printing one at a time

### ISSUE THREAD

**Issue by MrAmericanMike** [Ultimaker/Cura#2214] opened 2017-08-05 15:20 UTC
When I slice some print with multiple objects and select "Print one at a time" the printer goes idle once it finish the first item.

This is because it waits for the bed to come up to first layer temperature again. The problem is that it idle on top of the object. Wouldn't it be better if the nozzle moves to Home X and Y?

For example on the file provided.
[Tapa.txt](https://github.com/Ultimaker/Cura/files/1202453/Tapa.txt)

**Comment by guiseco** [comment] 2017-08-07 02:26
Same problem here.

**Comment by guiseco** [comment] 2017-08-07 02:27
Cura 2.7 beta not fixes this issue.

**Comment by Ghostkeeper** [comment] 2017-08-23 07:28
Duplicate of #1737.

**Closed by Ghostkeeper** 2017-08-23 07:28 UTC
