### ISSUE TITLE
Automatic Sacrificial layer generation

### ISSUE THREAD

**Issue by perikanttila** [Ultimaker/Cura#7724] opened 2020-05-09 12:16 UTC
When I model a cad file for printing I will add sacrificial layer to the holes that require otherwise support, so the holes with it looks say 0.2 thick layer closing it.

This would be very handy in inset holes eg. for socket cap screws etc.

Could Cura automatically create such bridging layer with the current layer height.

I have added pictures to illustrate how I use sacrificial layers in my parts

![Sacrificial Layer0](https://user-images.githubusercontent.com/53489899/81473561-f6b98080-9207-11ea-8ab9-c7be83110e56.JPG)
![Sacrificial Layer1](https://user-images.githubusercontent.com/53489899/81473562-fa4d0780-9207-11ea-9b07-b86570f3c721.JPG)
![Sacrificial Layer2](https://user-images.githubusercontent.com/53489899/81473564-fd47f800-9207-11ea-926d-4d6cad7d4039.JPG)

**Comment by smartavionics** [comment] 2020-05-09 12:26
Hi, I use that technique myself and agree it would be neat if Cura could add those single layers automatically. I will give the suggestion some thought.

**Comment by smartavionics** [comment] 2020-05-10 13:08
Hello again, I have done some work on this and have an initial implementation. I added a Remove Holes Under Walls setting that enables this behaviour...

![Screenshot_2020-05-10_14-06-05](https://user-images.githubusercontent.com/585618/81500077-8d994200-92c7-11ea-8862-5963f2007435.png)

![Screenshot_2020-05-10_14-06-18](https://user-images.githubusercontent.com/585618/81500071-8a9e5180-92c7-11ea-81b5-36bb5484393e.png)

![Screenshot_2020-05-10_14-06-29](https://user-images.githubusercontent.com/585618/81500068-883bf780-92c7-11ea-85b1-934f0c090fbd.png)

**Comment by perikanttila** [comment] 2020-05-10 13:35
nice!

...
Kari

**Comment by perikanttila** [comment] 2020-09-03 19:18
Is this feature coming to which release, not found in 4.7

**Comment by Ghostkeeper** [comment] 2020-09-07 07:43
It is not planned for a specific release yet. We have this on our backlog at the moment. Actually, it is considered a duplicate of #7324.

**Closed by Ghostkeeper** 2020-09-07 07:43 UTC
Labels: Category: Engine, Type: New Feature

**Comment by perikanttila** [comment] 2020-09-07 13:38
thanks, but #7324 is first layer but this is not the same as sacrificial layer on holes that has support roof before the smaller part of the hole continues. 

...
Kari

**Comment by Ghostkeeper** [comment] 2020-09-08 14:31
Yeah, true. In our backlog we've written it down as being generic for the first layer as well as later layers though.
