### ISSUE TITLE
View all extruders settings

### ISSUE THREAD

**Issue by ALSFelix** [Ultimaker/Cura#8341] opened 2020-09-07 19:07 UTC
I'm having trouble syncronizing my extruders settings.
I have three extruders with the same or  different materials. Usually use two for printing materials and the other for supports (PETG and HIPS). As i'm sure everyone knows even same material spools can have variants in setting depending on brand or even color. It is very dificult to keep track of settings when you have to change (and wait a lot) separator on every extruder.

I would like to have all extruders settings visible side by side.

If there is another solution i would like to know.
Thank you

**Comment by Ghostkeeper** [comment] 2020-09-10 09:17
Duplicate of https://github.com/Ultimaker/Cura/issues/7359.

**Closed by Ghostkeeper** 2020-09-10 09:17 UTC
Labels: Type: New Feature
