### ISSUE TITLE
Printjob name hardly visible on dark mode

### ISSUE THREAD

**Issue by Matszwe02** [Ultimaker/Cura#14555] opened 2023-02-13 21:26 UTC
### Application Version

5.2.2

### Platform

Windows 10

### Printer

Flsun SR

### Reproduction steps

1. Set dark mode
2. Load flsun sr profile (issue may persist on other printers as well)

### Actual results

![image](https://user-images.githubusercontent.com/49353902/218577583-ef7c42e3-7173-4ded-8794-7d14c9bcf49c.png)

### Expected results

I think the best fix is to add more contrast to the text or change its color a bit. Or maybe add some dark half-transparent box with this info

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none

**Comment by MariMakes** [comment] 2023-02-21 09:55
Hey @Matszwe02,

Thanks for your report 👍
This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/14555
We have a ticket on our backlog with the intent to improve this behavior.

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/14555

**Closed by MariMakes** 2023-02-21 09:55 UTC
Labels: Type: Bug, Status: Triage
