### ISSUE TITLE
3.5.1 - Shortcuts left panel not working.

### ISSUE THREAD

**Issue by amagr0** [Ultimaker/Cura#4648] opened 2018-10-25 10:55 UTC
**Application Version** - CURA 3.5.1
**Platform** - Win 10 Pro, 64 bit
**Display Driver** - NVIDIA GeForce 840M

**Steps to Reproduce** - install 3.5.1; open a stl; try the shortcuts from left panel.

**Actual Results** - The shortcuts from the left panel are not working. 

![image](https://user-images.githubusercontent.com/12901952/47495655-8f69f480-d84c-11e8-9bbd-6a05fce0b18b.png)

**Comment by rburema** [comment] 2018-10-26 14:11
Hi @amagr0, Did you select the model first? I haven't been able to reproduce this yet.

**Comment by amagr0** [comment] 2018-10-26 15:18
If you not select the model the panel stay inactive, so yes, the model was selected.
(did you know well Cura software?)

![image](https://user-images.githubusercontent.com/12901952/47575737-a6871000-d93a-11e8-8bde-18351ca1777a.png)

**Comment by rburema** [comment] 2018-10-26 15:40
My apologies, I though you might have selected the model afterwards, to show us which shortcuts you meant. In retrospect, it didn't make that much sense for me to assume that, sorry.

**Comment by alekseisasin** [comment] 2018-10-31 09:50
I close the issue because it is duplicated: https://github.com/Ultimaker/Cura/issues/2556

**Closed by alekseisasin** 2018-10-31 09:50 UTC
Labels: Status: Needs Info
