### ISSUE TITLE
scaling incorrect when model has been rotated

### ISSUE THREAD

**Issue by spattinson** [Ultimaker/Cura#6148] opened 2019-08-04 14:28 UTC
**Application version**
4.2.0

**Platform**
Xubuntu, xserver-xorg-video-nvidia-390
**Printer**
i3 clone
**Reproduction steps**
open an stl, rotate about z axis, then attempt to scale x and y without snap or uniform options.

**Actual results**
x scales correctly and the % and dimension is correct. scaling Y causes Z % to change, but all dimensions are correct. It looks like the original x y z aspects are still used instead of the rotated ones. 

**Expected results**
The visual current x y and z should be changed when scaling not the previous ones before rotation. Confusing for user and difficult to revert

**Additional information**
video [https://imgur.com/zwOOF3a](https://imgur.com/zwOOF3a)

**Comment by Ghostkeeper** [comment] 2019-08-11 17:21
Duplicate of https://github.com/Ultimaker/Cura/issues/4136.

**Closed by Ghostkeeper** 2019-08-11 17:21 UTC
Labels: Type: Bug
