### ISSUE TITLE
Move up incorrect start when object has been dropped

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#271] opened 2015-08-18 13:14 UTC
When object has been drop on the platform because we moved it up too far, the following occurs:
when again starting to drag the object up, the z position of the object suddenly changes to below the build platform.

**Comment by nallath** [comment] 2015-08-20 07:43
This is a duplicate of https://github.com/Ultimaker/Cura/issues/100

**Closed by nallath** 2015-08-20 07:43 UTC
Labels: bug
