### ISSUE TITLE
Ironing moves from plane to plane leaving artifacts.

### ISSUE THREAD

**Issue by J0hanss0n** [Ultimaker/Cura#11095] opened 2021-12-19 18:53 UTC
### Application Version

4.12.1

### Platform

Windows 10

### Printer

Artillery Genius

### Reproduction steps

Enabled Ironing, see attached project file.

### Actual results

The ironing moves from plane to plane on Layer 49.

![grafik](https://user-images.githubusercontent.com/95164456/146687207-e7b85bd5-6859-4d55-ad01-561dfc1aff8a.png)

### Expected results

Ironing should be done in one pass for each continous plane in Layer 49. Each move to an other plane leaves artifacts and ruins the ironing.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[AG_ironing.zip](https://github.com/Ultimaker/Cura/files/7741364/AG_ironing.zip)

**Comment by fvrmr** [comment] 2021-12-22 12:33
Hi @J0hanss0n thank you for your bug report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/10824
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-12-22 12:33 UTC
Labels: Type: Bug
