### ISSUE TITLE
Mac Draggable controls don't work 

### ISSUE THREAD

**Issue by pkneer** [Ultimaker/Cura#11515] opened 2022-02-20 01:00 UTC
### Application Version

4.13.1

### Platform

OSX Monterey 12.2.1

### Printer

Ender 3

### Reproduction steps

open cura in Monterey

Add an object

Attempt to select move, scale etc the object 

Component can only be selected through the object menu
none of the UI controls work

### Actual results

Component can only be selected through the object menu
none of the UI controls work

### Expected results

I expect to be able to click on object to select

I expect to be able to click on the screen controls to scale, move, rotate object

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

n/a

**Comment by fvrmr** [comment] 2022-02-21 09:28
Hi @pkneer thank you for your report.
Are you using an external monitor? If so, it is a duplicate of https://github.com/Ultimaker/Cura/issues/9912
A workaround is to uncheck the option `Restore window position on start` in the general preferences.

**Closed** 2022-03-07 09:37 UTC
Labels: Type: Bug, Status: Needs Info
