### ISSUE TITLE
Spiralize adds extra inner walls on alternating bottom layers

### ISSUE THREAD

**Issue by UnfoldAntwerp** [Ultimaker/Cura#10754] opened 2021-11-06 14:00 UTC
### Application Version

3.1.0, 4.9.1, 4.11

### Platform

MacOS 10.15.7, 11.5

### Printer

Different printers

### Reproduction steps

1. turn on spiralize
2. 5 extra inner walls (green) are added to each alternating even bottom layer.

went through all the settings but could not find anyone causing this behaviour...

### Actual results

5 extra inner walls (green) are added to each alternating even bottom layer.

### Expected results

NO extra inner walls (green) are added to each alternating even bottom layer

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[cupIssue.3mf.zip](https://github.com/Ultimaker/Cura/files/7490587/cupIssue.3mf.zip)
<img width="520" alt="Schermafbeelding 2021-11-06 om 14 59 04" src="https://user-images.githubusercontent.com/11931764/140612281-95feeae9-4b60-4885-adaf-38d1a5eb12c7.png">

**Comment by fvrmr** [comment] 2021-11-08 15:06
Hi @UnfoldAntwerp thank you for your report. 
This is a duplicate of https://github.com/Ultimaker/Cura/issues/8393
There you can read that this is hard-coded to make the model water tight. 

I will close this issue since it is a duplicate.

**Closed by fvrmr** 2021-11-08 15:06 UTC
Labels: Type: Bug

**Comment by UnfoldAntwerp** [comment] 2021-11-08 15:34
Thanks @fvrmr! I did a proper search but did't surface under spiral issues. So thanks for pointing this out. Baffles me that this is on purpose but I'll respond in the older issue.
