### ISSUE TITLE
Slicing the model does not work

### ISSUE THREAD

**Issue by roman777555111** [Ultimaker/Cura#14600] opened 2023-02-18 10:18 UTC
### Application Version

5.2.2

### Platform

Windows 10

### Printer

FlyingBear Ghost 6

### Reproduction steps

after clicking cut model nothing happens. The process just hangs on loading. This happens with different models. On another computer, these same models are cut. I tried to install younger versions of the СURA program, but the result is the same.

### Actual results

after clicking cut model nothing happens. The process just hangs on loading. This happens with different models. On another computer, these same models are cut. I tried to install younger versions of the СURA program, but the result is the same.

### Expected results

I want to get a cut model

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

![1](https://user-images.githubusercontent.com/125734007/219855079-9b0ad5bb-136e-4486-9417-894ddf327ede.jpg)

**Comment by MariMakes** [comment] 2023-02-21 10:06
Hey @roman777555111,

Welcome to the Ultimaker Cura Github 🚀 

Is it possible that your printjob is located at 0, 0, 0, and it slices if you move it a little away from the center of the buildplate? 
Then it might be a duplicate of https://github.com/Ultimaker/Cura/issues/13643

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Closed** 2023-03-07 12:06 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage, Slicing Error :collision:
