### ISSUE TITLE
cura 5.1 keeps crashing

### ISSUE THREAD

**Issue by Scage75** [Ultimaker/Cura#13293] opened 2022-09-14 23:28 UTC
### Application Version

5.1

### Platform

windows 10

### Printer

snapmaker 2

### Reproduction steps

load model
slice model
preview ,odel

### Actual results

loads fine
sometimes slices
sometimes wont go to preview shuts the whole system down

### Expected results

it should slice all models that have no issues and should let me preview it and not crash. i have attached my computer specs to see if they are good for cura aswell

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Screenshot (3)](https://user-images.githubusercontent.com/110274075/190280103-36e3fd6c-5d9c-4e19-a9e7-928c9e323c72.png)

**Comment by MariMakes** [comment] 2022-09-23 15:18
Hey @Scage75,

I'll need some more information to troubleshoot. 

Inititally it sounded like a duplicate of https://github.com/Ultimaker/Cura/issues/9644 where Cura crashes if you have any non-latin characters in your file paths. 

But it could also just be model dependent. If your Cura crahses on a specific model we need a project file. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser. 

Thank you 😄

**Closed** 2022-10-08 00:24 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage
