### ISSUE TITLE
4.4 Failed importing of old profile from 4.3

### ISSUE THREAD

**Issue by MunchHansen** [Ultimaker/Cura#6862] opened 2019-12-27 23:19 UTC
**Application version**
4.4.0

**Platform**
Mac OS X Mojave 10.14.6

Printer
Ender 3

Reproduction steps
Import the following profile:
https://we.tl/t-a1lRX52OnO 

(The link will be deleted in a week, ask me for new upload. :-) )

Screenshot(s)
No screenshot but here is the error text:

Failed to import profile from /Users/Frederik/Desktop/PLA_Ender3.curaprofile: Could not find a quality type normal for the current configuration.
The profile is not imported

Expected results
The profile should be properly imported even though its for an older version of Cura

Project file
N/A

Log file
2019-12-28 00:17:07,627 - DEBUG - [MainThread] cura.Settings.CuraContainerRegistry.importProfile [175]: Attempting to import profile /Users/Frederik/Desktop/PLA_Ender3.curaprofile

Additional information
This profile is for an older version of Cura, I think maybe 4.3.

**Comment by sebachu** [comment] 2019-12-28 09:20
Hi, I have the exact same bug when I tried to update from 4.3 to 4.4.

**Comment by MunchHansen** [comment] 2019-12-28 13:44
> Hi, I have the exact same bug when I tried to update from 4.3 to 4.4.

Did you solved this problem?

**Comment by FlailAway** [comment] 2019-12-29 16:03
Hi, is anyone looking at this issue? 
Can you make it ignore unknown items in an imported profile?
I have just had the same problem with **_"could not find a quality type super for the current configuration."_**

**Comment by rburema** [comment] 2019-12-29 20:46
Does this still happen with 4.4.1? We fixed a few of those in the patch.

**Comment by MunchHansen** [comment] 2019-12-29 20:48
> Does this still happen with 4.4.1? We fixed a few of those in the patch.

Hi there,

Unfortunately it still happen in 4.4.1. I have tried to export one cura profil and import it again to a new printer - getting the error as explained above in the topic. :-(

**Comment by FlailAway** [comment] 2019-12-29 21:07
> Does this still happen with 4.4.1? We fixed a few of those in the patch.

Yup, just grabbed 4.4.1 also in 4.3.0

**Comment by sebachu** [comment] 2019-12-31 04:22
> > Hi, I have the exact same bug when I tried to update from 4.3 to 4.4.
> 
> Did you solved this problem?

No, still an issue. I'm staying with 4.3 for now until it's fixed. I'm happy to post logs etc but the error is exactly the same as you posted originally above - logs show Cura could not find a qualiy type normal.

**Comment by sebachu** [comment] 2019-12-31 04:25
seems to be the same issue as this one:
"Can't import legacy profile: Could not find a quality type "normal" #6682"

**Comment by sebachu** [comment] 2019-12-31 04:27
@Ghostkeeper

**Comment by Ghostkeeper** [comment] 2019-12-31 08:58
Yeah, looks like a duplicate of #6682 then.

**Closed by Ghostkeeper** 2019-12-31 08:58 UTC
Labels: Type: Bug
