### ISSUE TITLE
The letterfonts are broken on my Imac

### ISSUE THREAD

**Issue by Kitcarhans** [Ultimaker/Cura#3402] opened 2018-02-26 13:18 UTC
Apple

It is also helpful to attach a project (.3MF) file and Cura log file so we can debug issues quicker.
Information about how to find the log file can be found at https://github.com/Ultimaker/Cura/wiki/Cura-Preferences-and-Settings-Locations.

Ther latest version in NL
**Platform**

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by ianpaschal** [comment] 2018-02-26 13:51
Can you please share a screen shot to show the problem?

But it sounds like a duplicate of #3277.

**Comment by Kitcarhans** [comment] 2018-02-26 13:56
Ja, het is gezeefd probleem. Wat kan ik er aan doen?

Groet, Hans

**Comment by fieldOfView** [comment] 2018-02-26 14:04
Read that issue. There's a newer test-build to download and test.

**Comment by Kitcarhans** [comment] 2018-02-26 14:07
OK,

3.2.2 works for my. Thank you


Hans de Bruijn
hans@marhans.nl

**Comment by ianpaschal** [comment] 2018-02-26 14:17
Good to hear!

**Closed by ianpaschal** 2018-02-26 14:17 UTC
Labels: Status: Fixed
