### ISSUE TITLE
15.09.81: Printjob Name does not change the name

### ISSUE THREAD

**Issue by robomaniac** [Ultimaker/Cura#393] opened 2015-09-14 02:03 UTC
For me when I change the "Printjob Name" it's suppose to change the .gcode that is save on my SD card. That is how I understand it

Well that does not work.

![printjob_name](https://cloud.githubusercontent.com/assets/5814871/9840600/dd97acb2-5a62-11e5-8106-89e549558023.png)

**Comment by Ghostkeeper** [comment] 2015-09-14 07:22
Yeah, it hasn't been properly implemented yet. Duplicate of #370.

**Closed by Ghostkeeper** 2015-09-14 07:22 UTC
