### ISSUE TITLE
fail in slicing

### ISSUE THREAD

**Issue by alebosio** [Ultimaker/Cura#14646] opened 2023-02-23 05:18 UTC
### Application Version

5.2.1 beta

### Platform

windows 10

### Printer

artillery hornet

### Reproduction steps

slice the model
try again 2 or 3 times

### Actual results

don't slice the stl

### Expected results

show the model, but not sicing

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

nothing more

**Comment by MariMakes** [comment] 2023-02-23 13:33
Hey @alebosio,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

Is it possible that your printjob is located at 0, 0, 0, and it slices if you move it a little away from the center of the buildplate? 
Then it might be a duplicate of https://github.com/Ultimaker/Cura/issues/13643

The new Cura 5.3 Beta contains the fix for this. 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0-beta.1

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Closed** 2023-03-10 12:06 UTC
Labels: Type: Bug, Status: Needs Info, Status: Triage, Slicing Error :collision:
