### ISSUE TITLE
3.4.1 (all versions) Very large build volume of custom printer is not visible in UI

### ISSUE THREAD

**Issue by PierreAuge** [Ultimaker/Cura#4190] opened 2018-08-04 04:02 UTC
Printer volume is 860mm x 860mm x 1600mm

The application window will not zoom out to view the entire build volume.

**Application Version**

All versions of CURA
**Platform**

All Platforms , Windows, MAC, Linux
**Printer**

Custom Built FDM Printer
**Steps to Reproduce**

Setup a custom printer configuration with a very large build volume. Particularly in the Z axis.
**Actual Results**

The view port is limited to a nominal distance to zoom
**Expected results**

You should be able to zoom out to the extremities of whatever build volume you want, regardless of how ridiculous it is.
**Additional Information**

**Comment by ChrisTerBeke** [comment] 2018-08-04 21:49
Duplicate of https://github.com/Ultimaker/Cura/issues/3990.

**Closed by ChrisTerBeke** 2018-08-04 21:49 UTC
