### ISSUE TITLE
Cura fails to start

### ISSUE THREAD

**Issue by dokutan** [Ultimaker/Cura#12280] opened 2022-05-20 20:44 UTC
### Application Version

5.0.0

### Platform

Arch Linux (kernel 5.17.9-arch1-1, Mesa 22.0.4)

### Printer

-

### Reproduction steps

Try to launch the Cura Appimage with ``./Ultimaker-Cura-5.0.0-linux.AppImage``

### Actual results

Cura fails to launch fails with the following error message: Could not probe OpenGL. This program requires OpenGL 2.0 or higher. Please check your video card drivers.

The following is printed to stdout:
```
PyInstaller/loader/pyimod03_importers.py:495: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
libGL error: MESA-LOADER: failed to open radeonsi: /tmp/.mount_Ultima6qnWtq/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/dri/radeonsi_dri.so) (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi: /tmp/.mount_Ultima6qnWtq/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/dri/radeonsi_dri.so) (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /tmp/.mount_Ultima6qnWtq/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/dri/swrast_dri.so) (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
```
OpenGL works in other applications.

### Expected results

Cura starts normally.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

A possible workaround is to remove libstdc++.so.6 from the Appimage by doing the the following:
```
./Ultimaker-Cura-5.0.0-linux.AppImage --appimage-extract
cd squashfs-root 
rm libstdc++.so.6
./Ultimaker-Cura
```

**Comment by nallath** [comment] 2022-05-23 08:22
Duplicate of #11856

**Closed by nallath** 2022-05-23 08:22 UTC
Labels: Type: Bug
