### ISSUE TITLE
anomalous speeds of external walls on the first layer

### ISSUE THREAD

**Issue by beppeGA88** [Ultimaker/Cura#17497] opened 2023-12-02 16:29 UTC
### Cura Version

5.6.0

### Operating System

win 10

### Printer

vyper

### Reproduction steps

pepare the model
slicing

### Actual results

the walls outside the first layer go at the same speed as the outside walls

### Expected results

the external walls on the first layer must go much more slowly

### Add your .zip and screenshots here ⬇️

![photo_2023-12-02_17-16-13](https://github.com/Ultimaker/Cura/assets/152719457/51e4fd2f-f40b-4ba5-a12c-ecc86eeb7136)

**Comment by beppeGA88** [comment] 2023-12-02 16:41
[](url)https://we.tl/t-dhXX58MBPh

**Comment by Asterchades** [comment] 2023-12-03 03:45
This is a known issue. It's under investigation, but there's unfortunately little further information on the subject.

Per previous reports, it can sometimes be addressed by making sure that `Print Thin Walls` is enabled - sometimes in tandem with setting the `Minimum Feature Size` to a lower value, or even zero.

Duplicate of #17210.

**Closed by Asterchades** 2023-12-03 03:45 UTC
Labels: Type: Bug, Status: Triage
