### ISSUE TITLE
Cura 3.3B Open Project.

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ultimaker/Cura#3587] opened 2018-03-29 08:29 UTC
**Application Version**
3.3B
**Platform**
Win10/64

**Display Driver**
NV 391.01

**Steps to Reproduce**
Open saved Project
**Actual Results**
Cura still messes object's placement on Print bed.
**Expected results**
Cura must open saved projects exactly as saved.
**Additional Information**
Same issue reported for 3.2.1: https://github.com/Ultimaker/Cura/issues/3201

**Comment by fieldOfView** [comment] 2018-03-29 09:10
Overloading devs with badly filed duplicate issues will not get this fixed sooner.

**Comment by LipuFei** [comment] 2018-04-11 09:39
Hi @Thisismydigitalself , could you share your project file that has this problem? Thanks.

**Comment by Ghostkeeper** [comment] 2018-09-21 12:37
This is a duplicate of #3201.

**Closed by Ghostkeeper** 2018-09-21 12:37 UTC
Labels: Category: Cura, Status: Needs Info, Type: Bug
