### ISSUE TITLE
Crash on ejecting SD card.

### ISSUE THREAD

**Issue by LCBozo** [Ultimaker/Cura#9598] opened 2021-04-17 16:18 UTC
### Application Version

Arachne engine beta

### Platform

Windows 10

### Printer

Both Fokoos Odin-5 F3 & Tenlog TL-D3 Pro

### Reproduction steps

Simply clicked on the 'Eject' button after saving to SD card.

### Actual results

Program crashed

### Expected results

A dialog box should state Safely Remove Hardware...

**Comment by fvrmr** [comment] 2021-04-19 07:58
Hi @LCBozo thank you for your bug report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9057 that's why I will close this issue. 

This bug is fixed in Cura 4.9 beta. Here you can find the download of the 4.9 beta: https://github.com/Ultimaker/Cura/releases/tag/4.9-beta

**Closed by fvrmr** 2021-04-19 07:58 UTC
Labels: Type: Bug
