### ISSUE TITLE
Inventor files (ipt) will not open in CURA 3.5 anymore

### ISSUE THREAD

**Issue by kerzerl** [Ultimaker/Cura#4484] opened 2018-10-05 08:49 UTC
Inventor files (ipt) will not open in CURA 3.5 anymore.
In version 3.4 that was possible!

**Comment by fieldOfView** [comment] 2018-10-05 09:54
Even though it is a different plugin, this is a duplicate of https://github.com/Ultimaker/Cura/issues/4475

To paraphrase @Appesteijn in that issue:
> To open these files you need the Inventor plugin. When we get an updated Inventor plugin that works (there are breaking plugin changes in Cura 3.5) we will get it in the ToolBox asap.

**Closed** 2018-10-08 11:05 UTC
