### ISSUE TITLE
Concentric top and bottom does not work for extruder 2 on UM3extended

### ISSUE THREAD

**Issue by paulmalot** [Ultimaker/Cura#13694] opened 2022-10-30 13:58 UTC
### Application Version

5.2.0

### Platform

Windows 10 Pro 64 bit

### Printer

Ultimaker 3 extended

### Reproduction steps

I have a model, round hollow cilinder.  when extruder 1 is selected, and top/bottom finish is as concentric, the preview is correct, and top is concetric.  When i select extruder 2, and keep topbottom as concentric,  the preview show the top/bottom as lines.  Not concentric. see pictures in annex for both situations

![concentric_extr2_NOK](https://user-images.githubusercontent.com/117023259/198882405-911326c0-7bbb-48d3-98b3-75d73fadc1e0.jpg)
![concentric_extr1](https://user-images.githubusercontent.com/117023259/198882408-b9417aa6-8622-4dd3-9cf5-b96394a08ab3.jpg)

### Actual results

see added pictures

### Expected results

result in concentric bottom/top on extruder 2

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[UM3E_rol_blanco.zip](https://github.com/Ultimaker/Cura/files/9896004/UM3E_rol_blanco.zip)

**Comment by MariMakes** [comment] 2022-10-31 14:23
Hey @paulmalot,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

I think I know what is happening. 
You are looking at the settings for extruder 1, while the model is sliced for extruder 2.
If you check the settings for extruder 2 you will see that the settings indicate lines pattern. 
![image](https://user-images.githubusercontent.com/40423138/199030439-fd1d13d1-ae9f-4fe0-8103-fdaf31f6fd82.png)

It's a mistake I make myself quite regularly. It's something that we are looking to improve to make more clear in the future. 

I believe what you are seeing is undesired but not a bug 
Do you agree that it's not a bug in Cura and we can close the issue?

**Comment by MariMakes** [comment] 2022-11-01 08:21
Don't worry, it's quite a common mistake. I've made it myself as well.
Our designers are looking into ways to make it more clear in the future. 
Since it's not a bug, I'll be closing this issue.

**Closed by MariMakes** 2022-11-01 08:21 UTC
Labels: Type: Bug, Status: Under Investigation
