### ISSUE TITLE
Custom support

### ISSUE THREAD

**Issue by erickwill** [Ultimaker/Cura#7291] opened 2020-03-17 18:23 UTC
What I'm suggesting is a improvement in a current plugin Custom Supports and Support Blocker, which I do believe that could be integrated into the Cura Core. I'd like to suggest the ability of edit, add and remove manually, the supports beyond the edit the automatic support creation. Idea maker already uses this neat feature besides simplify3d. This cool and useful feature is the only thing I missing while using Cura. Thanks for doing the best slicer ever.

**Comment by Ghostkeeper** [comment] 2020-03-18 12:57
Being able to customise the support placement is a long-time wish of the Cura developers as well. We made some strides for that once, offering a paint brush tool for the red areas on the model that get painted with support. But we never finished the implementation. What was missing is an eraser tool so you can also undo your operations as well as remove support that was previously generated.

This tool also requires some thought in how it interoperates with the current "Overhang Angle" setting. After you customise the support, what should happen if you change the overhang angle?

**Comment by erickwill** [comment] 2020-03-18 14:33
> Being able to customise the support placement is a long-time wish of the Cura developers as well. We made some strides for that once, offering a paint brush tool for the red areas on the model that get painted with support. But we never finished the implementation. What was missing is an eraser tool so you can also undo your operations as well as remove support that was previously generated.
> 
> This tool also requires some thought in how it interoperates with the current "Overhang Angle" setting. After you customise the support, what should happen if you change the overhang angle?
> 
> The customising support plug-in is still on a branch here: https://github.com/Ultimaker/Cura/tree/feature_custom_support/plugins/CustomSupport

Thanks for your prompt reply and explanation.
Yes, now I understand the challenges involved into achieve the correct implementation for this feature,
I just wonder about the "Overhang Angle" settings, if a viable way to work with along with the Custom Support would be to lock the variable overhang angle in a safe value to get custom support working if and when custom support is in use. I wonder if you disable overhang angle while custom support is in use would be, also, a viable way..
Once more, thanks for your hard work and time.

**Comment by Triangulix** [comment] 2020-07-09 10:53
Hi
I found this request because I noticed an unexpected behavior in the custom supports plugin:
My expectation was: I set Cura to create support where it touches the buildplate and then manually add some support in the model.
Unfortunately it seems that Cura in this situation only creates the walls of the manually added support but not the surfaces where the support would touch the supported parts.
This makes it a problem to print an air duct that needs support inside of some long slots but of course cannot be filled up with support inside.

**Comment by Ghostkeeper** [comment] 2020-07-10 12:22
Which custom support plug-in? The one that I linked here in the above reply, or the one in the Marketplace?

The plug-in I linked here was an experiment several years ago. It's not expected to work correctly in the current Cura version. The plug-in in the Marketplace is maintained by Lokster and issues should be reported there: https://github.com/lokster/cura-custom-supports/issues

**Comment by Triangulix** [comment] 2020-07-10 17:10
> Which custom support plug-in? The one that I linked here in the above reply, or the one in the Marketplace?
I meant the PlugIn in the marketplace.

**Comment by Ghostkeeper** [comment] 2020-07-13 12:39
Then please report your bug here: https://github.com/lokster/cura-custom-supports/issues

**Comment by userosos** [comment] 2020-08-06 17:35
No! It is very bad! If i use the plugin i have pain. See the pics. it is crazy. I need scale the box i has notime for it. I need ighlight those surfaces on the model that I want.
![изображение](https://user-images.githubusercontent.com/22872748/89562935-60572400-d823-11ea-825e-01455772638e.png)
![изображение](https://user-images.githubusercontent.com/22872748/89562975-6b11b900-d823-11ea-8642-c7c8785c47fd.png)


I mean that i dont want use box! I mean that i want hold down the mouse button and paint the model. The surfaces that I painted will have supports. See the pics.
![изображение](https://user-images.githubusercontent.com/22872748/89563150-ae6c2780-d823-11ea-837b-32c1b9f07971.png)
![изображение](https://user-images.githubusercontent.com/22872748/89563388-0c007400-d824-11ea-8e89-607ec71f9cc7.png)

I hope you understand me now.

**Comment by Ghostkeeper** [comment] 2020-08-07 15:21
I understand precisely what you mean. And indeed that is exactly what my own [custom support](https://github.com/Ultimaker/Cura/tree/feature_custom_support/plugins/CustomSupport) plug-in did. I still have a demo video of it here: http://dulek.net/work/custom_support_short.mp4

This plug-in is not to be confused with the "Custom Support" plug-in by Lokster which only places a cube in the scene similar to the support blocker tool. As you can see in that video, my plug-in was made for a fairly old version of Cura. Really I'd like nothing more than to finish that plug-in, believe me. But I can't.

**Comment by userosos** [comment] 2020-08-07 16:08
> 
> 
> I understand precisely what you mean. And indeed that is exactly what my own [custom support](https://github.com/Ultimaker/Cura/tree/feature_custom_support/plugins/CustomSupport) plug-in did. I still have a demo video of it here: http://dulek.net/work/custom_support_short.mp4
> 
> This plug-in is not to be confused with the "Custom Support" plug-in by Lokster which only places a cube in the scene similar to the support blocker tool. As you can see in that video, my plug-in was made for a fairly old version of Cura. Really I'd like nothing more than to finish that plug-in, believe me. But I can't.

Very GOOD! Thx! Can i use it rightnow?

**Comment by Ghostkeeper** [comment] 2020-08-07 16:11
I expect that plug-in will not work in modern versions of Cura. And it was limited to begin with, with a number of hacks. It is not fit for release.

You can try copying the source code in, but no promises.

**Comment by userosos** [comment] 2020-08-07 16:43
> 
> 
> I expect that plug-in will not work in modern versions of Cura. And it was limited to begin with, with a number of hacks. It is not fit for release.
> 
> You can try copying the source code in, but no promises.

It is not work. Sorry. Do you have some plan about it?

**Comment by erickwill** [comment] 2020-08-07 17:39
WOW.. such a plugin would be AWESOME! :)

**Comment by Ghostkeeper** [comment] 2020-08-10 11:49
> It is not work. Sorry. Do you have some plan about it?

Indeed, like I said, I expected it to not work. I have no plans to do anything with it unless I can do that during work hours.

**Comment by nallath** [comment] 2020-11-19 13:40
Duplicate of #5955

**Closed by nallath** 2020-11-19 13:40 UTC
Labels: Type: New Feature
