### ISSUE TITLE
[4.5 Beta] Support Blocker Z and Y are inverted

### ISSUE THREAD

**Issue by valeria-gomez** [Ultimaker/Cura#7102] opened 2020-02-15 15:30 UTC
**Application version**
4.5 Beta

**Platform**
Windows 10 

**Printer**
Ultimaker 3

**Reproduction steps**
[supportblocker_45Beta.zip](https://github.com/Ultimaker/Cura/files/4208645/supportblocker_45Beta.zip)
1. Add support blocker
2. While support blocker is selected, uncheck Snap Scaling
3. Scale Y dimension of support blocker by dragging the green handle 

**Actual results**
The Z dimension is adjusted, when I'm scaling Y. 
Same thing happens when scaling Z, Y gets adjusted. 
(X behaves correctly, which is more than what I can say about my Exes IRL.)

**Expected results**
When scaling Z, only Z should change. Same goes for Y. 

**Project file**
This is reproducible without a project file.

**Comment by Ghostkeeper** [comment] 2020-02-18 11:54
This happens when/because the model is rotated before the support blocker was attached. The support blocker rotates itself back when placed so that it appears upright again, but still rotates itself along with whatever it is attached to. Because you're rotating + non-uniform scaling, you're then running into this issue: https://github.com/Ultimaker/Cura/issues/4136

You can see this better when you rotate a model 45 degrees and then place the support blocker. The support blocker scales really weirdly then.

That issue is one of the most serious front-end issues remaining in Cura at the moment. It's also pretty difficult to solve!

I'll close this as a duplicate of #4136.

**Closed by Ghostkeeper** 2020-02-18 11:54 UTC
Labels: Type: Bug
