### ISSUE TITLE
Adaptive Layer Height with raised model results in empty toolpath

### ISSUE THREAD

**Issue by mmahdim** [Ultimaker/Cura#7885] opened 2020-06-05 20:13 UTC
**Application version**
4.3.0

**Platform**
win10 64 bits, running on GPU (1660 ti)

**Printer**
Tevo Tornado

**Reproduction steps**
1. raise the model (move in the z-axis), so that the model is floating in the air
2. enable supports
3. enable Adaptive Layer Height

**Screenshot(s)**
without Adaptive Layer Height
![image](https://user-images.githubusercontent.com/8644346/83918692-7f3b2a80-a78e-11ea-8e13-03b7a518a08a.png)
with Adaptive Layer Height
![image](https://user-images.githubusercontent.com/8644346/83918673-75b1c280-a78e-11ea-8c6b-8e0d8cfd2cd9.png)

**Actual results**
Acts like the model file is empty and reports duration of print as 0 minutes.

**Expected results**
Should have sliced the file.

**Project file**
Any file

**Log file**
-

**Additional information**
-

**Comment by nallath** [comment] 2020-06-08 09:50
I've just tried this with the latest master and I could reproduce the issue.

**Comment by mahtDFR** [comment] 2020-06-09 10:27
This already exists on our backlog as CURA-6513
This ticket is a duplicate of #3183

**Closed by mahtDFR** 2020-06-09 10:27 UTC
Labels: Type: Bug
