### ISSUE TITLE
[3.3.1] Saving Files on Mac mostly impossible due to non-standard file-selection dialog.

### ISSUE THREAD

**Issue by MacLemon** [Ultimaker/Cura#3917] opened 2018-06-11 13:22 UTC
**Application Version**
3.3.1

**Platform**
macOS 10.12.6

**Printer**

**Steps to Reproduce**
Slide any model, klick save file.

**Actual Results**
A non-macOS file selection dialog pops up. Impossible to select external volumes like an SD card, navigation does not support keyboard shortcuts and standard file locations, like the always handy desktop folder. Drag and drop of locations is not supported, recent locations are not supported, keyboard focus doesn't work, views like icons and columns aren't supported. In addition to that it breaks all accessibility features of macOS for saving files.
This file selection dialog makes saving .gcode files mostly impossible.

**Expected results**
The standard macOS file selection dialog must be used, like it used to be in versions before 3.3.

**Additional Information**
Former versions of Cura did use the standard macOS file selection dialog when saving files which is excellent and matches the platform.
The file-selection dialog in 3.3.1 is unusable for the Mac platform.

**Comment by ChrisTerBeke** [comment] 2018-06-11 19:16
Duplicate of https://github.com/Ultimaker/Cura/issues/3770.

**Closed by ChrisTerBeke** 2018-06-11 19:16 UTC
