### ISSUE TITLE
4.8's improved "arrange" algorithm places models colliding with each other and overlapping

### ISSUE THREAD

**Issue by thanhtacles** [Ultimaker/Cura#8822] opened 2020-11-23 08:46 UTC
Both dragging in multiple models, and multiplying models causes them to collide and overlap with each other. Pretty obvious unintended use, as this will cause a ton more time spend rearranging objects.

**Application version**
4.8

**Reproduction steps**
drag or multiply any model at all. They will collide no matter what. 

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/64636310/99942637-d759ef00-2d24-11eb-8686-6f8d6dadb005.png)

**Expected results**
Models used to be spaced part pretty cleanly, even though they were of the same orientation.

**Comment by nallath** [comment] 2020-11-23 10:22
Does this happen for all models with you? I've not been able to reproduce this (eg; All models that I load get nicely spread over the build plate).

If it's just these models, could you share them with us?

**Comment by thanhtacles** [comment] 2020-11-23 11:45
No it's all models

**Comment by Vandrasc** [comment] 2020-11-23 16:21
@nallath is this not a duplicate of https://github.com/Ultimaker/Cura/issues/8779?

**Comment by nallath** [comment] 2020-11-23 16:35
Yeah, I think so. But I am a bit suprised how / why this happens for all models.

**Comment by Ghostkeeper** [comment] 2020-11-26 16:32
It doesn't happen with models where the bounding box is square (as opposed to rectangular).

A workaround is to enable "ensure models are kept apart" in the preferences.

**Comment by linuxdan** [comment] 2021-03-10 23:59
Good workaround, but why isn't that "feature" auto-applied to auto arrangement ?

**Comment by Ghostkeeper** [comment] 2021-03-23 14:53
Closing this as duplicate of https://github.com/Ultimaker/Cura/issues/8779.

**Closed by Ghostkeeper** 2021-03-23 14:53 UTC
Labels: Type: Bug
