### ISSUE TITLE
Save File - Filename does not update when object list changes

### ISSUE THREAD

**Issue by Soynuts** [Ultimaker/Cura#9189] opened 2021-01-26 16:18 UTC
**Application version**
4.8.0

**Platform**
Windows 10
Nvidia GTX 1050 Ti

**Printer**
Doesn't matter (happens on both prusa i3 mk3 and Rostock Max)

**Reproduction steps**
1. Load 2 STL/object files
2. Slice the files
3. Click "Save to File".  It will pre-fill with the first STL/object that was loaded (This is OK)
4. Remove the first Object from the list.
5. Slice and click "Save to File" again.  It will still pre-fill the filename with the object name that has since been removed.

**Actual results**
Wrong filename when saving to file.

**Expected results**
Filename should re-adjust to the first object in the list, rather than what was first loaded.  It does completely reset if you remove ALL files first, the re-add.

**Comment by fvrmr** [comment] 2021-01-28 08:37
Hi @Soynuts

This is expected behaviour of Cura. 

I discussed it with our UX designer, but we won't look into this. Because you can rename the project name yourself and we don't want to modify the project name depending on the models that you have on the build-plate. 

That's why I will close this issue.

**Closed by fvrmr** 2021-01-28 08:37 UTC
Labels: Type: Bug
