### ISSUE TITLE
Cura 5.0.0 inconsistent font sizes

### ISSUE THREAD

**Issue by marcj71** [Ultimaker/Cura#12475] opened 2022-06-08 12:00 UTC
### Application Version

5.0.0

### Platform

Linux (Ubuntu 20.04.4 LTS)

### Printer

Ultimaker 3 Extended

### Reproduction steps

Cura 5 has some interesting choices for font sizes, at least as they appear on my screen. Cura 4 has much more consistency. Attached are images of the same windows for versions 4.13 and 5.0.0:
- Main window
- File menu opened
- Manage printers (preferences -> printers) window
- About window
![cura4 13-1](https://user-images.githubusercontent.com/14938425/172608019-a13a5ff3-704b-4d3e-8521-04c87164a1cc.png)
![cura5-1](https://user-images.githubusercontent.com/14938425/172608288-1099499e-7a6f-4ab0-a1f8-73a39d03fd8c.png)
![cura4 13-2](https://user-images.githubusercontent.com/14938425/172608040-e794f375-7c38-48e2-ab4d-65d301bde933.png)
![cura5-2](https://user-images.githubusercontent.com/14938425/172608304-096497eb-7ef6-4b81-a96e-1c0db5cc3b01.png)
![cura4 13-3](https://user-images.githubusercontent.com/14938425/172608055-df507d7d-fbf7-4056-addb-0466f9ed8167.png)
![cura5-3](https://user-images.githubusercontent.com/14938425/172608321-cec2914e-7bf0-42bd-a18d-955b42a75fcd.png)
![cura4 13-4](https://user-images.githubusercontent.com/14938425/172608073-6544891c-3648-4ed7-ba71-eb5636c7f6d6.png)
![cura5-4](https://user-images.githubusercontent.com/14938425/172608336-52aeb12a-7b73-4a9d-988d-55af5cb0b95a.png)

### Actual results

Both 'on its own', and certainly when compared to Cura 4.13, Cura 5.0.0 has:
- A different font than the system font; I use Helvetica/Nimbus Sans
- A high menu bar (probably caused by increased whitespace everywhere)
- Tiny menu bar font -- or maybe it just looks small because other labes have become so big
- A large logo (top left) where branding takes up too much screen area (this is 'in your face', no subtlety at all)
- A remarkably high button bar (the one with the file button and material selection). The labels 'um3ext' and 'Normal - 0.15mm' are inconsistently large when compared to the material labels
- The menu items are spaced far apart and have tiny labels
- In the Manage printers window, the labels in the three buttons (Add New, Machine Settings, Connect..) are so large to be out of place. In 4.13, these were much more consistent with the other text.
- Also, the close button is gone in 5.0.0
- Surprisingy, the Close button in the About window looks like a link
- Windows with a scroll bar (such as Preferences) do not use the system scroll bar and the mouse wheel does not work in them

### Expected results

- Fonts should be more balanced, as they were in Cura 4
- System font should be respected, as it was in Cura 4
- All buttons should look like buttons, not a button here and a link there
- All windows should have a close button, all in the same corner. Having to use the window bar close button is unexpected, if only because it has the expectation of 'cancel' rather than 'apply and close'. How to I cancel any changes I may have made, other than loading the defaults?
- System scroll bars should be used, mouse wheel should work

I know there's a trend to make everything large with a lot of whitespace, but the overall feel is unbalanced.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no additional information

**Comment by lorenzoromagnoli** [comment] 2022-06-08 15:21
Hi @marcj71, thanks for this very detailed list, I'll look closely at all your suggestions. In the meantime,  could you try setting your screen scaling to 100% and let us know if the UI looks more balanced then?

I'm just asking because, while some of the thing you mentioned are due to totally new components (I.e. the menu bar which was using the the OS native application bar until 4.13 but we had to replace it with a custom made one in 5.0) some of the size differents you are reporting were for sure not intentional... and I actually cannot reproduce them 

This is for instance how I see them - left 4.13 and right 5.0
![Screen Shot 2022-06-08 at 17 17 16](https://user-images.githubusercontent.com/2944758/172654562-874af18f-89d0-49fa-b99e-b11928527520.png)

**Comment by nallath** [comment] 2022-06-09 06:55
> System font should be respected, as it was in Cura 4

This is actually intentional. Previously you would get a mix of fonts throughout the application. Now it always uses the same font everywhere.

**Comment by marcj71** [comment] 2022-06-09 08:18
@lorenzoromagnoli, I did not do any font scaling -- this is a standard Ubuntu Mate installation. These are my font settings:
![image](https://user-images.githubusercontent.com/14938425/172797856-f5a453ee-d9a5-4fba-abe0-c5367b4d2015.png)
Other than web pages, I see the same font in all applications except Cura.

**Comment by lorenzoromagnoli** [comment] 2022-06-09 08:22
Can you please check the "screen" scaling? 
Usually is a setting somewhere close to your display settings. 
![Screen Shot 2022-06-09 at 10 20 53](https://user-images.githubusercontent.com/2944758/172800484-cc632651-e590-444c-b5bf-4dab17918e1f.png)

**Comment by marcj71** [comment] 2022-06-09 08:27
New issue but probably related: Depending on the size of the window/monitor it is hard to select a material. The list just won't fit and it doesn't scroll. I wanted to select Ultimaker PLA Yellow, which is alphabetically challenged:
![cura5-5](https://user-images.githubusercontent.com/14938425/172800639-9880414f-c544-4497-9a4d-13f9055b761b.png)

With a smaller application window, it gets worse:
![cura5-5a](https://user-images.githubusercontent.com/14938425/172800880-b1406f9d-edde-4ac6-b73a-2e1e76cc9529.png)

Fortunately, I could reach it through the Settings menu:
![cura5-5b](https://user-images.githubusercontent.com/14938425/172801095-0e59b54f-8b4a-4623-a53b-335e074d5a43.png)
but only because the menu starts higher. If this hadn't worked, I wouldn't have known how to select the material without Googling...

**Comment by marcj71** [comment] 2022-06-09 10:49
> Can you please check the "screen" scaling? Usually is a setting somewhere close to your display settings. ![Screen Shot 2022-06-09 at 10 20 53](https://user-images.githubusercontent.com/2944758/172800484-cc632651-e590-444c-b5bf-4dab17918e1f.png)

I don't have any font scaling enabled. The Ubuntu Mate setting is 'automatic', which means it uses whatever is detected by the X server.
```
[    18.764] (II) modeset(0): Output eDP-1 connected
[    18.764] (II) modeset(0): Output DP-1 disconnected
[    18.764] (II) modeset(0): Output HDMI-1 disconnected
[    18.764] (II) modeset(0): Output DP-2 disconnected
[    18.764] (II) modeset(0): Output HDMI-2 connected
[    18.764] (II) modeset(0): Using spanning desktop for initial modes
[    18.764] (II) modeset(0): Output eDP-1 using initial mode 1920x1080 +0+0
[    18.764] (II) modeset(0): Output HDMI-2 using initial mode 1920x1200 +1920+0
[    18.764] (==) modeset(0): Using gamma correction (1.0, 1.0, 1.0)
[    18.764] (==) modeset(0): DPI set to (96, 96)
```
Is there a debugging option to see which fonts Cura selects?

**Comment by lorenzoromagnoli** [comment] 2022-06-09 12:14
As you correctly write in your last comment it seems that Ubuntu mate doesn't have a easy way to set a screen scale factor or a font scale factor. https://ubuntu-mate.community/t/scaling-in-mate/19091/14

But I still believe that most of the issues you are reporting are due to some wrong UI scaling. 
Let me try to answer to all your points one by one:

>- Cura Uses a different font than the system font; I use Helvetica/Nimbus Sans_
>- Fonts should be more balanced, as they were in Cura 4
>- System font should be respected, as it was in Cura 4

Cura now uses Noto sans practically everywhere. 
Also in Cura 4.13 and earlier, we used the same font, except for some dialogues and menus. Cura 5.0 brings the same font everywhere which is definitely an improvement when it comes to consistency. 
Most applications use custom fonts afaik (check i.e. vscode, slack, MS teams ). Shipping Cura with the same font on all OS allows us to have more control on how people are going to experience the SW. 

I agree with you that custom fonts should not be used in the main application menu which should actually follow the system theme styling, unfortunately, things broke during the qt upgrade and we couldn't find a way to have OS native application menu... so we replace it the native menu with a new menu with a Custom styling for all users on all OS.

>- A high menu bar (probably caused by increased whitespace everywhere)

Yes, it is indeed different from the menu bar of other applications for the reasons mentioned above

>- Tiny menu bar font -- or maybe it just looks small because other labes have become so big

To make Cura adapt to different people's screen scaling factors we measure the size of your default OS font and we derive a scale factory from that.
From your screenshots, it seems that your screen scale factor is set to something bigger that 100% in fact the stage and the menu look thicker than they should but the same scaling doesn't seem to apply consistently to the fonts. We need to look into that. 

>- A large logo (top left) where branding takes up too much screen area (this is 'in your face', no subtlety at all)

yes, it could be more subtle, but again if you are experiencing it as too big in 5.0 it is because of some weird UI scaling. 

>- A remarkably high button bar (the one with the file button and material selection). The labels 'um3ext' and 'Normal - 0.15mm' are inconsistently large when compared to the material labels

Same here, some weird scaling going on

>- The menu items are spaced far apart and have tiny labels

They could indeed be a bit more packed but it is mostly a matter of taste, I would rather go back into a scenario where the application menu follows the system styling than adjust the spacing.... we will never make everyone happy.  But yes, form your screenshot the font and the menu entry height don't look very proportionate... the same weird scaling.  

>- In the Manage printers window, the labels in the three buttons (Add New, Machine Settings, Connect..) are so large to be out of place. In 4.13, these were much more consistent with the other text.

Yes, we aligned all buttons to look similar and reuse the same components. The size of the button doesn't seem to be the issue here, but indeed the rest of the text in the UI is again not proportioned.

>- Also, the close button is gone in 5.0.0 
>- All windows should have a close button, all in the same corner. Having to use the window bar close button is unexpected, if only because it has the expectation of 'cancel' rather than 'apply and close'. How to I cancel any changes I may have made, other than loading the defaults?

Since we don't have a way to allow you to cancel your edits and go back to the previous state in any preference dialogue, we decided that it would feel more transparent to the user to just remove the close button which actually does exactly the same as closing the window. As I'm receiving multiple reports about this one, we might reconsider and bring the close button back. I'll discuss with the team  

>- Surprisingy, the Close button in the About window looks like a link
>- All buttons should look like buttons, not a button here and a link there

Fair enough... we replicated in Cura all the button styling that Digital factory uses, and there it was decided to have some very light tertiary buttons to compensate for the very heavy primary and secondary buttons. 
The thing is that tertiary should never stay on a page alone, but only be used together with secondary and primary. so yes, that close button shouldn't look like a link

>- Windows with a scroll bar (such as Preferences) do not use the system scroll bar and the mouse wheel does not work in them
>- System scroll bars should be used, mouse wheel should work

Indeed after the qt update, some scrollable areas started showing some issues. we have some tickets open about this, 

>- I know there's a trend to make everything large with a lot of whitespace, but the overall feel is unbalanced. 
Unfortunately, all the white space you are observing doesn't seem intentional, and doesn't show up on other os's, so we need to investigate a bit what is going on.

**Comment by marcj71** [comment] 2022-06-10 10:14
I only notice just now that the text in the Cura 5 About window ('End-to-end solution...') does pick up the system font in the right size! So, knowing it is possible... ;)

**Comment by MariMakes** [comment] 2022-08-23 09:58
Hey @marcj71 and @lorenzoromagnoli 
I'm going through our open issues and noticed this one is still open.

Do you still need me to bring it up to the team?
As you can see there are still a lot of issues open that our attention, I suspect that his one will not be on the top of our list any time soon.

**Closed** 2022-09-06 12:07 UTC
Labels: Type: Bug, Status: Needs Info, Status: Under Investigation
