### ISSUE TITLE
Profile doesn't exports

### ISSUE THREAD

**Issue by HukpoFuJl** [Ultimaker/Cura#12071] opened 2022-05-03 10:51 UTC
### Application Version

5.0.0-beta+1

### Platform

Windows 10 LTSC 1809

### Printer

FlyingBear Ghost 5

### Reproduction steps

Create new profile. Try to export. 

### Actual results

Nothing happend.

### Expected results

File with profile must be created :)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Permissions is ok, trying save to root directory of many disks.

**Comment by PhilBaz** [comment] 2022-05-03 18:49
Me too! Cant export profiles. Can save them but not export.

**Comment by fvrmr** [comment] 2022-05-04 07:23
Hi @HukpoFuJl thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11971, so I will close this issue.

**Closed by fvrmr** 2022-05-04 07:23 UTC
Labels: Type: Bug
