### ISSUE TITLE
Brim Mode: Corners Only

### ISSUE THREAD

**Issue by 360alaska** [Ultimaker/Cura#8173] opened 2020-08-11 00:36 UTC
Where bed adhesion is concerned the most likely part of a print to lift is the corners, so I would suggest a bed adhesion option of “Corners only brim”. This will save on filament and speed up print times on larger objects.

**Comment by nallath** [comment] 2020-08-11 11:35
Duplicate of https://github.com/Ultimaker/Cura/issues/1349

**Closed by nallath** 2020-08-11 11:35 UTC
Labels: Type: New Feature
