### ISSUE TITLE
Cannot slice a 0.2mm thick object in Cura 4.11

### ISSUE THREAD

**Issue by jk101290** [Ultimaker/Cura#10519] opened 2021-09-27 06:36 UTC
### Application Version

4.11.0

### Platform

Both Windows 10 and Linux Mint 20.1

### Printer

Creality Ender-3 Pro

### Reproduction steps

1. Import STL 
2. Slice at default 0.2 layer height profile

### Actual results

The sliced preview shows no layers to print. 0 minutes and 0g filament estimated. 

### Expected results

Sliced preview should show a layer of five 0.2mm thick circles. 

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

This problem does not exist in Cura 4.10 and earlier. 

[Cura project file](https://github.com/Ultimaker/Cura/files/7233907/CE3PRO_BosZx_Bed_Level_Eco.zip)

**Comment by nallath** [comment] 2021-09-27 07:34
Duplicate of #10394

**Closed by nallath** 2021-09-27 07:34 UTC
Labels: Type: Bug
