### ISSUE TITLE
Blockers are even to the plate when opening project and the object not any more

### ISSUE THREAD

**Issue by DaLimboster** [Ultimaker/Cura#10256] opened 2021-08-09 08:12 UTC
### Application Version

4.10

### Platform

Windows 10

### Printer

Ender 3 V2

### Reproduction steps

1. Open an STL
2. Create Blockers which are not even to the plate (negative Z)
3. Save project
4. (may close Cura)
5. Open project 

### Actual results

The Object has Offset to the plate, the Blockers are now even to the plate

### Expected results

Object even on the plate, blockers with negative offset as original

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

-

**Comment by fvrmr** [comment] 2021-08-09 10:53
Hi @DaLimboster can you share a project file (file - save project) where this is happening.

**Comment by DaLimboster** [comment] 2021-08-09 11:03
I added the 3mf-project-file als a png to upload it here :-)

![3D4U_Coffee_Clip_Large_V2 3mf](https://user-images.githubusercontent.com/77015815/128696806-f71fcc10-4e63-4917-bf31-40cab0096467.png)

**Comment by fvrmr** [comment] 2021-08-09 14:53
Could you zip your 3mf file? Png doesn't work

**Comment by DaLimboster** [comment] 2021-08-10 06:26
[3D4U_Coffee_Clip_Large_V2.zip](https://github.com/Ultimaker/Cura/files/6959409/3D4U_Coffee_Clip_Large_V2.zip)
Sorry, didn´t realize, that it takes zips. Now as zip. Thanks

**Comment by fvrmr** [comment] 2021-08-13 11:28
Hi @DaLimboster thank you, I can now reproduce your issue. And this seems to happen because automatically drop models to the build plate is enabled. You can disable this as a work around for now. (Preferences - configure Cura)
See also this ticket: https://github.com/Ultimaker/Cura/issues/10184 and there we linked a ticket on our backlog to solve this. 
I will close this one as a duplicate. Hope you understand.

**Comment by Ghostkeeper** [comment] 2021-08-17 12:46
This is a different issue than #10184, because the issue here is not that the model is below the build plate (to cut off the bottom side from the model). The issue is that some objects are support blockers and they need to stay aligned to the model. For #10184 the intended solution is to make sure that dropping models to the build plate doesn't move models up, but still drops them down. That solution won't solve this issue, because these support blockers are still above the build plate.

**Comment by konskarm** [comment] 2021-08-23 12:04
Hi @DaLimboster . I've been trying to reproduce your issue on 4.11-beta and I am unable to. Could you give it a try and let me know if it works?

**Comment by konskarm** [comment] 2021-08-23 12:45
This issue is now on our backlog (Devs see CURA-8511).

**Comment by konskarm** [comment] 2021-08-23 12:47
Note: I think that https://github.com/Ultimaker/Cura/issues/9973 has the same root cause as this issue.

**Comment by DaLimboster** [comment] 2021-08-24 17:51
Thank you very much

**Closed** 2021-11-05 15:21 UTC
Labels: Type: Bug, Category: Cura
