### ISSUE TITLE
When using brim with the option only on the outside it does not print the firt 

### ISSUE THREAD

**Issue by Unufry** [Ultimaker/Cura#11644] opened 2022-03-10 18:34 UTC
### Application Version

4.13

### Platform

Windows 10

### Printer

Two trees sp-3

### Reproduction steps

When using brim with the option only on the outside it does not print the first layer of support material!
Upgraded to the latest version, the problem is still ocurring.
Added 3 pictures for visual asistance.

### Actual results

When trying to print it skips the fist layer and the support structure does not stick to the build surface.

### Expected results

Expecting when the option brim only on the outside is activated to include support material where the brim is supposed the be.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![with option not actiavated it will print normally](https://user-images.githubusercontent.com/99325738/157731242-dd85a418-5822-4ba1-9714-03b6f323e7b2.png)
![when option activated it does not print first layer support](https://user-images.githubusercontent.com/99325738/157731246-c9c7e392-a234-4955-b06d-eadf59ae1abc.png)
![Layer 2 is the first support layer](https://user-images.githubusercontent.com/99325738/157731249-35d2b10c-c818-4e56-92ba-d7ffef019243.png)

**Comment by GregValiant** [comment] 2022-03-10 18:58
You may have to enable "Enable Support Brim" in the Support section.  (Those lines should stick though.)

**Comment by Ghostkeeper** [comment] 2022-03-20 18:50
Seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/9996?

**Closed** 2022-03-25 09:27 UTC
Labels: Type: Bug, Status: Needs Info
