### ISSUE TITLE
Support brim AFTER skirt

### ISSUE THREAD

**Issue by mbmosher** [Ultimaker/Cura#4829] opened 2018-11-18 18:20 UTC
**Application Version**

3.6

**Platform**

OSX

**Printer**

Ender3

**Steps to Reproduce**

Use the new 'enable support brim' with build platform adhesion type > skirt (tried 3 line and 4 line skirts)

**Actual Results**

It actually prints the support brim first, then the skirt.  So far in all my prints with PETG the material isn't fully flowing when it starts the support brim and several rounds are missed.  Usually it gets going during the skirt printing.

**Expected results**

I would expect the printer to print the skirt first, then the support brim.  This would also allow for checking placement of modle on the bed via the skirt before the brim starts.

**Additional Information**

**Comment by lsidor** [comment] 2018-12-07 17:43
I have also encountered this error.
The skirt should definitely be printed first since the purpose of it is to prime the extruder.
The support brim on my print was under-extruded at the beginning since the extruder hadn't been primed yet.

**Comment by Derwodaplastik** [comment] 2018-12-07 20:41
Same here. I had to print without the support brim because of that. But it is a great feature so please change this. Beside of that Cura is a great software.

**Comment by MrStump** [comment] 2018-12-12 10:11
Same here, please, fix this.

**Comment by justinianpopa** [comment] 2018-12-13 20:48
+1 for adding an option to control this; My printer doesn't print critical small support adhesion brims and it's ruining the whole print. Temporary fix is to add a "prime-nozzle-in-a-long-line" gcode at the start of the print

**Comment by tobecwb** [comment] 2018-12-15 22:12
same here

**Comment by justinianpopa** [comment] 2019-01-03 05:47
any news on this from the dev team? is it just normal behavior or a bug?

**Comment by cds333** [comment] 2019-01-03 20:10
Yes please fix asap. Supports have trouble adhering at the bast of times, this pretty much ensures they will fail.

**Comment by cds333** [comment] 2019-01-03 20:37
Yes, please fix asap! Supports have trouble adhering at the best of times, this pretty much ensures they will fail. And skirts whole purpose is to prime the nozzle while not printing anything that will be part of the final print or even have a second layer, so no- it is definitely not normal behaviour. Shirts should always print first.

**Comment by paukstelis** [comment] 2019-01-11 16:30
Additionally, at least in 4.0.0 alpha, if Build Plate Adhesion is None, support brim is ignored, even if the box is checked. There would be plenty of cases where you want the support brim but not other types of adhesion.

**Comment by justinianpopa** [comment] 2019-01-15 09:59
@paukstelis That seems pretty useful, you should consider opening a separate issue for this

**Comment by muenznej** [comment] 2019-01-16 17:03
seriously this support brim and skirt print order is a mess...  i want the supports to be properly adhereing not the skirt

**Comment by marekruzicka** [comment] 2019-01-17 12:23
Have the same issue... 
We just need to have the priority set properly:  skirt > any raft/brim

In the mean time, use support floor... not as good as brim, but better than nothing.

**Comment by danspamman** [comment] 2019-01-30 09:25
I would like to request that the order of support brim and skirt get switched as well.  Printing the support brim first makes for a nasty mess - the skirt needs to go first.  I'm assuming this is an accidental bug, rather than a feature ?

**Comment by Kzar42** [comment] 2019-02-11 03:11
I'm having the same problem with the support/support brim being printed before the skirt. With small support features this renders the support brim a problem rather than a solution - the extruder hasn't yet been primed, the support brim isn't printed or doesn't attach, then on the next layer the material prints in the air and is carried and deposited elsewhere on the print... It's all downhill from there.

**Comment by KyleBorth** [comment] 2019-02-13 16:03
Would also like to request this to be fixed ASAP. Printing the support brim first basically causes it to not print at all as the extruder has not had time to prime. Thanks in advance!

**Comment by Jaseduar10** [comment] 2019-02-18 23:09
same here, please fix

**Comment by rburema** [comment] 2019-02-22 10:27
Devs: Ticket is in the board as CURA-6002

**Comment by xkrull** [comment] 2019-03-23 07:56
Version **4.0.0** - nothing has changed!
First border (if, of course, it will work out, especially on PETG), and then skirt too :(

**Comment by rburema** [comment] 2019-03-26 07:06
@xkrull,
Sadly, CURA-6002 isn't done yet. I hope we can start on it this week. CURA-6124 was fixed, but only for the master branch, which means it's a lock-in for 4.1.

**Comment by Schleichmichl** [comment] 2019-04-04 08:15
same here, please fix

**Comment by krz4tw** [comment] 2019-04-04 13:43
Exact same Problem please fix asap.

**Comment by krz4tw** [comment] 2019-04-04 14:06
Also a connected issue:
The support brim direction. What I mean by that is that in some cases it starts to print the support brim "islands" on the outer most line and then spiraling inwards and sometimes it does the opposite, start inside and spiral to the outside.
Starting inside and spiraling out is bad because of the short lines with sudden changes of direction make it really hard to stick.
Better to start outside have one longer continious line with smoother curves and then spiraling inwards. The inner sections adhere much better this way cause they can not only stick to the buildplate but also to the lines next to it.

In any case, please fix the oder of skirt and brim first before you consider this.
Thanks

**Comment by Ghostkeeper** [comment] 2019-04-05 07:26
> The support brim direction. What I mean by that is that in some cases it starts to print the support brim "islands" on the outer most line and then spiraling inwards and sometimes it does the opposite, start inside and spiral to the outside.

It's impossible to make this work for any shape. Take this one for instance:

![drawing](https://user-images.githubusercontent.com/2448634/55611002-829ae680-5784-11e9-9b49-d51fa90c8442.png)

If it's drawing a brim from outside to inside (=far from the shape towards the edge of the shape) then inside the two "lagoons" in that shape it must be drawing the brim from inside to outside (again starting far from the shape, going towards the shape).

**Comment by smartavionics** [comment] 2019-04-07 16:01
Maybe fixed by https://github.com/Ultimaker/CuraEngine/pull/1029.

**Comment by Ghostkeeper** [comment] 2019-05-29 07:43
Fixed in 4.1. Thanks!

**Comment by eugr** [comment] 2020-02-26 06:26
Looks like this is reintroduced in 4.5-beta :(

**Comment by Ghostkeeper** [comment] 2020-02-28 13:39
I'm unable to reproduce that. Here's a print where it printed the skirt first, then the support brim:

![image](https://user-images.githubusercontent.com/2448634/75553161-2003a680-5a38-11ea-87b9-5c8fc7512f65.png)

Do you have a project file that reproduces this bug?

**Comment by eugr** [comment] 2020-02-28 17:57
@Ghostkeeper - the bug appears only when using tree supports. I'm attaching a picture and will try to attach a project file next. As you can see it started to print the support brim for half of the supports first and then the skirt.

![Screen Shot 2020-02-28 at 9 56 03 AM](https://user-images.githubusercontent.com/2192184/75572952-ac9a6e80-5a10-11ea-9b87-633b4e5cc3c1.png)

**Comment by eugr** [comment] 2020-02-28 18:03
Here is the project file in 3MF format. I'm using my own printer profile but that shouldn't matter - exactly the same thing happens when using built-in Prusa MK3S profile too.

Notable settings:

- Adhesion type: Skirt
- Tree supports enabled
- Regular supports disabled
- Support brim enabled with default parameters

[support_brim_bug_example.3mf.zip](https://github.com/Ultimaker/Cura/files/4268382/support_brim_bug_example.3mf.zip)

**Comment by Ghostkeeper** [comment] 2020-03-04 10:13
Indeed with that model it reproduces. In fact, not only with tree support but also with ordinary support.

**Comment by Vandrasc** [comment] 2020-03-06 11:58
Devs, for our internal reference CURA-7284

**Comment by rburema** [comment] 2020-03-17 15:19
@Ghostkeeper Not seeing this with ordinary support, only with tree support. If I turn off tree support and enable normal support, skirt comes first. I've flipped back and forth a few times now to check. Do you have a project file where this happens wit ordinary support as well?

**Comment by rburema** [comment] 2020-03-17 16:06
Ok never mind, I see the skirt happens _in between_ the parts of the tree support for me, which means it's probably not as predictable as all that (which makes me doubt very much if my last comment is always true).

**Comment by gaara92** [comment] 2020-04-02 16:17
This bug also affects me, on Cura 4.5 (AppImage@Ubuntu).
If I deactivate the support border (french translated), the bug disappear.
![Screenshot_20200402_181517](https://user-images.githubusercontent.com/5517870/78272605-04476080-750e-11ea-974d-3f2e963e5682.png)

**Comment by rburema** [comment] 2020-04-02 19:22
@gaara92 It [took](https://github.com/Ultimaker/CuraEngine/pull/1218) [a few](https://github.com/Ultimaker/CuraEngine/pull/1221) [tries](https://github.com/Ultimaker/CuraEngine/pull/1228), but it's considered fixed for the upcoming 4.6 release.

**Closed by rburema** 2020-04-02 19:22 UTC
Labels: Category: Engine, Type: Bug
