### ISSUE TITLE
Could not Connect to Cura Package Database

### ISSUE THREAD

**Issue by penninbd** [Ultimaker/Cura#10552] opened 2021-10-03 02:08 UTC
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Creality Ender 3 Pro

### Reproduction steps

1. Attempted to Connect to the Marketplace by clicking on the Markerplace button in Cura

### Actual results

1. Received error message "Could not connect to the Cura Package Database. Please check your connection"

### Expected results

Expected that the Markeplace would open so I could download plugins 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7272546/cura.log)

**Comment by nallath** [comment] 2021-10-04 08:42
Duplicate of #10548

**Closed by nallath** 2021-10-04 08:42 UTC
Labels: Type: Bug
