### ISSUE TITLE
Feature Request: Minimum line length to prime nozzle for rafts

### ISSUE THREAD

**Issue by logiclrd** [Ultimaker/Cura#8610] opened 2020-10-24 17:12 UTC
**Is your feature request related to a problem? Please describe.**
I have been using rafts with my printer, because the print bed just doesn't adhere well otherwise. I may find a better solution in the future, but as of now, that's what I'm doing. The thick outline around the raft serves to prime the nozzle, but on smaller prints I have found that it is possible for the nozzle to fail to prime before the outline is complete, and then part of the crucial first raft layer doesn't print at all.

**Describe the solution you'd like**
I'd like to be able to configure a minimum "prime length" for that first line drawn before it begins laying down the first raft layer proper, so that for very small models, Cura draws a bit of extra line before beginning the outline itself. This line could be concentric with the raft outline, but separated from it by a few mm. A straight line would serve my needs just fine, but I wonder if there might be issues with there being enough space on the bed if it needs to be configured to a higher value.

**Describe alternatives you've considered**
Right now, when printing very small models, I stand next to the printer right as it's getting started, and right as it touches down for the start of the raft outline, I press the release on the extruder and shove filament through to make sure it's fully primed by the time it starts drawing the lines that fill in the first layer.

**Affected users and/or printers**
People who have long Bowden tubes and use rafts.

**Comment by Ghostkeeper** [comment] 2020-10-27 13:28
Duplicate of https://github.com/Ultimaker/Cura/issues/6162.

**Closed by Ghostkeeper** 2020-10-27 13:28 UTC
Labels: Type: New Feature
