### ISSUE TITLE
Pressing ESC key windows goes to restore size.

### ISSUE THREAD

**Issue by tamarit77** [Ultimaker/Cura#9452] opened 2021-03-25 16:01 UTC
### Application Version

4.8

### Platform

Windows 10

### Printer

Hellbot Magna Dual

### Reproduction steps

1. Pressing ESC key anytime when Cura is on Maximized size

### Actual results

Cura windows goes to restore Size leaving maximized position

### Expected results

I think that ESC key could have a better ussage like unselecting the actual selected function, i.e. if is selected the piece rotation function, could be comfortable to dissable that function pressing ESC key.   Peoples that comes from Autocad are used to use ESC key to dissable actual function.   In my case, I press ESC key many times, and I get Cura windows to size restore position any time.

**Comment by jellespijker** [comment] 2021-03-26 07:41
duplicate of #7499 will close this ticket in favor of the discussion there. Is mentioned in that ticket we defer this issue but we are certainly open for PR's on this

**Closed by jellespijker** 2021-03-26 07:41 UTC
Labels: Status: Deferred, Status: Duplicate, Type: Bug
