### ISSUE TITLE
[4.7.1] Scaling -> fields for mm input don't match the field's for percent input

### ISSUE THREAD

**Issue by svethi** [Ultimaker/Cura#8414] opened 2020-09-19 18:27 UTC
**Application version**
4.7.1

**Platform**
Windows 10 64-bit

**Printer**
Anycubic MegaS

**Reproduction steps**
1. Load an *.stl file
2. mark the object
3. select the scaling tool
4. deselect "Uniform scaling"
5. type in a value only in the Z:mm input field and press enter

**Screenshot(s)**

**Actual results**
The value in the Y:% input field has changed

**Expected results**
 The value in die Z:% field should be changed

**Project file**

**Log file**

**Additional information**

**Comment by nallath** [comment] 2020-09-21 08:42
Duplicate of https://github.com/Ultimaker/Cura/issues/4136

**Closed by nallath** 2020-09-21 08:42 UTC
Labels: Type: Bug
