### ISSUE TITLE
Auto detect feature is dangerous and should be removed

### ISSUE THREAD

**Issue by victornpb** [Ultimaker/Cura#7858] opened 2020-06-02 03:56 UTC
**Application version**
4.6.1

**Platform**
MacOS 10.14.6

**Reproduction steps**
1. Open Cura

**Actual results**
The current implementation of how cura detects usb printers is trying to brute force all serial ports, trying to open then and throw data at them without any regard to what they are until you find something that you recognize as a printer. 

If some data is interpreted or send at the wrong baud rate, the garbage arrived could make some device attached to the other side go bonkers, crash, restart, break, who knows what.
Just the fact that it sends DTR and makes every device connected to the serial port to restart is bad enough, you can lose a print job just by opening cura, if you're currently printing using another software e.g. Repetier. 

This could cause serious issues, I wonder who thought this was a good idea, this can cause data loss, property damage and even harm someone, think a CNC attached to the same computer, even tho this is not the most common setup, **software should not harm people even if its only a few people**.

I feel like I should not justify this further, and this should be enough reason.

**Expected results**
The software should not cause side effects that can cause, data-loss of physical damage.
This is what Repetier does:
![Repetier connection configuration screen](https://user-images.githubusercontent.com/3372598/83477968-fc9f2c00-a46a-11ea-9d46-36d1987fba84.png)

Which is what cura should do. Auto-detect should not be enabled by default, unless there's a side-effect free implementation of it.

**Comment by Ghostkeeper** [comment] 2020-06-03 14:25
Duplicate of https://github.com/Ultimaker/Cura/issues/3449.

**Closed by Ghostkeeper** 2020-06-03 14:25 UTC
Labels: Type: Bug
