### ISSUE TITLE
parts position y direction inverted, parted printed mirrored

### ISSUE THREAD

**Issue by martijnschouten** [Ultimaker/Cura#9950] opened 2021-06-08 14:58 UTC
### Application Version

4.9.0/4.9.1

### Platform

Windows 10

### Printer

Diabase H-series

### Reproduction steps

1. loaded a part in Cura
2. moved the part in the positive y-direction (direction of the arrow in coordinate system in Cura)
3. part get's a negative y position
4. give the prime tower a positive y position, it moves in the positive y-direction (direction of the arrow)

### Actual results

brain starts to hurt, the part is printed mirror over the x axis

### Expected results

- parts is moved in the direction of the arrow in the coordinate system, the part get's a positive y position
- part doesn't get's printed inverted

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CFFFP_sensor_rev2.zip](https://github.com/Ultimaker/Cura/files/6617558/CFFFP_sensor_rev2.zip)

**Comment by fvrmr** [comment] 2021-06-11 13:02
Hi @martijnschouten thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/8908
There you can find an explanation of @Ghostkeeper what is causing this.

I will close this issue as a duplicate.

**Closed by fvrmr** 2021-06-11 13:02 UTC
Labels: Type: Bug
