### ISSUE TITLE
Place objects randomly on built plate (feature suggestion)

### ISSUE THREAD

**Issue by uwe999** [Ultimaker/Cura#5268] opened 2019-02-03 21:15 UTC
**Application Version**

3.5.1
**Platform**

n/a
**Printer**

n/a
**Steps to Reproduce**

n/a
**Actual Results**

objects are placed in the center of the built plate
**Expected results**

because objects are always placed in the center of the built plate there is increased wear and tear on the surface material at that spot. If there would be a "random placement" option in the settings that problem could be prevented.
thanks

**Additional Information**

**Comment by Ghostkeeper** [comment] 2019-02-04 07:32
Duplicate of #4303.

**Closed by Ghostkeeper** 2019-02-04 07:32 UTC
