### ISSUE TITLE
Slicing error

### ISSUE THREAD

**Issue by dimitris254** [Ultimaker/Cura#14242] opened 2023-01-08 14:27 UTC
### Application Version

5.1.0

### Platform

Windows 11 pro

### Printer

Ultimaker S3

### Reproduction steps

1. Sliced 4 models together and printed them fine (one was used as support for the other 3 but not handled any different than the others).
2. Changed the one of those models to "Support" (Per model settings), since -as mentioned- it was placed there to support the others.
3. Hit the Slice button
4. Got an error

### Actual results

Go an Error

### Expected results

Should slice them like before.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[UMS3_Monopteros_V6_ALL_2ndColor.zip](https://github.com/Ultimaker/Cura/files/10368640/UMS3_Monopteros_V6_ALL_2ndColor.zip)

**Comment by GregValiant** [comment] 2023-01-08 15:26
Thanks for the report and the file.
I didn't have any trouble slicing it "as received" so I'm unable to duplicate the problem.
Did you happen to try moving the models around on the Cura build plate?  Sometimes that can fool this bug.
I'm going to mark this as a duplicate of a slicing bug.  Let us know if moving / rotating the model allows it to slice.

**Closed** 2023-01-23 00:17 UTC
Labels: Type: Bug, Status: Duplicate, Status: Needs Info, Status: Under Investigation, Slicing Error :collision:
