### ISSUE TITLE
Inconsistent infill in layers of thin cylinders.

### ISSUE THREAD

**Issue by Flopalop2** [Ultimaker/Cura#17099] opened 2023-10-24 23:45 UTC
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Voron 2.4 350

### Reproduction steps

1. Add cylinder stl to cura that is roughly 4 mm in diameter (there's a range like 3-6 but I know 4 works) and fairly tall. 
2. Slice with 2 walls and 20% infill of type cubic, cubic subdivision, octet, quarter cubic, and partially gyroid as well.  

### Actual results

![Screenshot (2608)](https://github.com/Ultimaker/Cura/assets/69126427/a98592a6-2c34-4ec8-91a3-d41b553103ad)
![Screenshot (2594)](https://github.com/Ultimaker/Cura/assets/69126427/2e8790b1-eb14-4eca-8fe6-e7277cd03041)
![Screenshot (2596)](https://github.com/Ultimaker/Cura/assets/69126427/400ed681-1570-45e4-9dca-0af93b5414d6)
Infill in sections of layers but inconsistent throughout part.

### Expected results

![Screenshot (2596)](https://github.com/Ultimaker/Cura/assets/69126427/d041c119-914e-4e9a-943e-f0f584016637)
Expected infil throughout or not at all.

### Add your .zip and screenshots here ⬇️

[tubetest.zip](https://github.com/Ultimaker/Cura/files/13138098/tubetest.zip)

**Comment by GregValiant** [comment] 2023-10-25 03:50
Thanks for the report.
That is happening because you are using Gyroid infill on a small part.  You have to think of infill as filling your entire build plate and Cura uses the parts of that "giant cube of infill" that intersects your model.  Because Gyroid wanders around; for some layers there is no intersection with your small model.
You can kind of see what is going on by making the "Infill Density" 5% and then 75% and running the preview slider up and down.
Another test would be to scale the part in the X and Y to 25mm with Gyroid at 20% density.
Gyroid is kind of cool to watch print but it's only good for supporting the roof of a model and adds about zero strength to a print.

To print that piece with consistent infill switch to Grid.

I'll go ahead and remove the bug label and close this as it is expected behavior from Gyroid, Octet, Quarter Cubic, and a couple of others.  I hope you understand.

**Closed by GregValiant** 2023-10-25 03:50 UTC
Labels: Type: Discussion, Status: Under Investigation

**Comment by Flopalop2** [comment] 2023-10-25 22:25
Alright that makes sense thanks.
