### ISSUE TITLE
Slicing fails

### ISSUE THREAD

**Issue by Filamentuser** [Ultimaker/Cura#14352] opened 2023-01-21 17:02 UTC
### Application Version

5.2.1

### Platform

windows11

### Printer

flsun sr

### Reproduction steps

tried to clice

### Actual results

![image](https://user-images.githubusercontent.com/100966395/213877616-455e2cb6-c8ac-4d84-abee-813de91f3da0.png)

### Expected results

produced gcode

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/100966395/213877844-a76fcd03-d93b-4478-9818-0ca4fe7bff6a.png)

**Comment by MariMakes** [comment] 2023-01-27 14:29
Hey @Filamentuser,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

Is it possible that your printjob is located at 0, 0, 0, and it slices if you move it a little away from the center of the buildplate? 
Then it might be a duplicate of https://github.com/Ultimaker/Cura/issues/13643

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Comment by Filamentuser** [comment] 2023-01-27 14:51
moved location on build plate and successfully slices.

**Comment by MariMakes** [comment] 2023-01-27 15:38
Thanks for getting back to us. 

Then it looks like a duplicate of https://github.com/Ultimaker/Cura/issues/13643
Luckily we seem to have found a solution direction for that issue this morning, so it is probably going to be fixed int he next release. 

Glad to hear you are unstuck. 
I'll close the issue.

**Closed by MariMakes** 2023-01-27 15:38 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:
