### ISSUE TITLE
Using and Creating profiles for new non ulitmaker materials not possible

### ISSUE THREAD

**Issue by sebther2** [Ultimaker/Cura#3088] opened 2018-01-05 08:51 UTC
Dear all!

By using CURA 3.1.0 (with an ultimaker 3) it is not possible to create / copy profiles (fine / normal etc.) for own created materials (this means non ultimaker materials).

Following steps to reproduce the issue:
- Copy e.g. Ultimaker (also generic) CPE
- Rename the Material to Black PETG
- Company / brand - change from ulitmaker to e.g. renkforce
- Materialtype - PETG

After activating this material it is not possible to use profiles for the printing setup in Cura.
Also it is not possible to create and save a new profile for this non ulitmaker material.

This issue will also happen, if you cancel all relationships to the original (copied) ultimaker material.

![grafik](https://user-images.githubusercontent.com/35130869/34601780-be52a9ee-f1fd-11e7-90a8-3c957a306ceb.png)

Please contact me for further information!

Helmut

**Comment by Spirou42** [comment] 2018-01-09 21:02
I have the same issue (Cura 3.1, UM3 with 4.2.5.20180102) on MacOS Sierra. It does not matter if the Material was created by the [COPY] or by [CREATE] function. Also it does not matter which material you use as a source for your custom material.

On my Machine the profile, or parts of it, is actually saved into ~/Library/Application Support/cura/3.1/quality but the UI does not allow to load it again. 

Contents of cura/3.1/quality
![screen shot 2018-01-09 at 21 56 52](https://user-images.githubusercontent.com/759145/34743025-92ef89f0-f588-11e7-82db-dbf4f023435a.png)

UI:
![screen shot 2018-01-09 at 21 59 17](https://user-images.githubusercontent.com/759145/34743045-a6c00d60-f588-11e7-854b-d9717464662e.png)

![screen shot 2018-01-09 at 21 58 52](https://user-images.githubusercontent.com/759145/34743053-aed873ca-f588-11e7-8586-d969eebe1c39.png)

**Comment by Spirou42** [comment] 2018-01-10 17:28
Some news on this:
I just created a custom entry for ColorFabbs SteelFill by duplicating "Ultimaker Silver PLA". Changed the name, brand, and material type as well as some of the print parameters while Silver PLA is selected AND the RFID tag of the Silver PLA is ON the printers reader.
In this particular case the Material Dropdown got not coloured orange and the profile stays the same. 
BUT if i try to create a profile from the currently made settings: The dialogBox is empty
 
![screen shot 2018-01-10 at 18 25 06](https://user-images.githubusercontent.com/759145/34786232-d6c5a8c0-f633-11e7-8f7d-68ce65585a2b.png)

and after saving, the profile does not show up in the material dialog

**Comment by ChrisTerBeke** [comment] 2018-01-14 11:30
Devs: CURA-4796
Community: we're picking this up asap as it's a regression bug.

**Comment by Spirou42** [comment] 2018-01-23 15:29
After first quick look into cura3.2b this seams to be fixed. I can see and switch profiles in both, the preferences dialog and the drop down menu. Creating new profiles and switching profiles works as expected i think. 

So the material drop down menu stayed orange and a little exclamation sign told me something about "incompatible materials". All materials I have created where copies from existing generic materials which are still linked to the source material.
![screen shot 2018-01-23 at 16 21 34](https://user-images.githubusercontent.com/759145/35283856-9abdc42c-0059-11e8-9401-90dcb18bbf54.png)
The orange marker occurs for all my materials (all Materials where created with cura3.1)
I have linked
CPE -> nGen
CPE+ -> HT
PLA -> SteelFill (PLAH)

- Carsten

**Comment by jackha** [comment] 2018-01-24 09:29
@Spirou42 Good that the regression is gone. Could you provide a project file so we can produce this orange compatibility issue?

**Comment by Spirou42** [comment] 2018-01-24 15:48
@jackha Absolutely, to both the statement and the question. 


[TestProjects.zip](https://github.com/Ultimaker/Cura/files/1660107/TestProjects.zip)
Contains 3 different projects using 4 different custom Materials.

btw.: the graphics performance (zoom, rotate pan) of Cura3.2b is abysmal compared to  3.1 . 
Should I create another Issue for this or is this due to debug settings in the beta?

screen recording showing performance issue is at: https://youtu.be/05LhF0BR3PY

**Comment by jackha** [comment] 2018-01-25 12:58
@Spirou42 Thanks! You should in this case keep the material type to PLA, it was changed to PLAG and therefore it was looking for profiles for that new type of material.

For the slowness you can file a new bug. I fixed something, but that was only applicable to Custom FDM Printer.

**Comment by Spirou42** [comment] 2018-01-27 21:46
@jackha I have changed the material types back to the original value of the linked material. After reloading of the material, the compatibility warning disappears. 

Unfortunately this has another unwanted UI impact. 
The material type not only is a marker for the compatibility but it is also directly used in the material selection menu - leaving me with a single CPE entry for two different materials (nGen and nGen Flex) and also with a single CPE+ entry for HT and XT. The same problem occurs with FormFuturas Atlas and PVA as support materials.  

Maybe the check for compatibility can also take the ancestors material type into account. Such a behaviour would allow the creation of an arbitrary UI hierarchy by material name and would eliminate the compatibility warning. 

I don't have anything against a safe and robust setup that prevents inexperienced users from doing any harm. But i really would appreciate an "expert mode". Such a mode should - in my opinion - disable all warnings in Cura and also on the UM3 so that i don't have to acknowledge any slight and wanted discrepancy to your very safe setup. The flag could be secured by a method like github uses to prevent deletion of a repository.

**Comment by jackha** [comment] 2018-01-29 08:35
@Spirou42 The selection menu uses the display name, if supplied. You can also change the brand field, so it's in its own sub menu. Only the material type field is used to match profiles. Hope this helps.

An "expert mode" without warnings would be handy indeed.

**Comment by Spirou42** [comment] 2018-01-29 11:44
@jackha Yeah, they are used in the menu hierarchy too. Unfortunately it is a threefold hierarchy consisting of:
BrandName->MaterialType->DisplayName at least on the Mac.

![screen shot 2018-01-29 at 12 18 30](https://user-images.githubusercontent.com/759145/35508061-49149ebc-04ef-11e8-9772-9a168f57e619.png)

Due to the current implementation all PLA variation of one Brand has to be sorted into a single MaterialType section including ALL the color variations and material specialities as metal, clay or wood filled materials. 
This leaves the value of MaterialType with two completely different use cases.
1. it marks a material as compatible - machine knowledge 
2. it organises a materials in the UI - UI/UX 

So I have the choice between the devil and the deep blue sea. Either i stay with an incorrect and annoying compatibility marker or i have to use a material hierarchy that is insufficient to keep the zoo of different materials organised.

**Comment by jackha** [comment] 2018-01-30 08:49
@Spirou42 you're right, it's annoying. Currently there's no good solution for this.
You could possibly misuse Brand?

**Comment by Spirou42** [comment] 2018-01-30 16:25
Yeah i think this misuse of the brand name might be a work around for this issue.

**Comment by Ghostkeeper** [comment] 2018-02-21 08:47
It marks the material or nozzle orange when it has no quality profiles for this combination. Because if there are no profiles, Ultimaker can't vet its quality. The printer itself will also give a warning when printing via removable medium.

**Comment by jackha** [comment] 2018-02-22 08:12
@Spirou42 quality profiles refer to the machine / variant / material (i.e. UM3 / AA 0.4 / PLA) specific settings which can be found in resources/quality/<quality profile>. Look at some existing ones, preferably Ultimaker ones (those are the one we create and test thoroughly), and see if you can create your own.

**Comment by Ghostkeeper** [comment] 2018-03-13 14:21
With "quality profiles" we mean the profiles that you select in the drop-down at the word "Profile:". You can select from different qualities there, "Fast", "Normal", "Fine", etc. These profiles are specific to a material, so if you have your custom material then there won't be any quality profiles for it.

The original problem in this issue is not yet solved, even after now having merged our machine manager refactoring.

**Comment by diegopradogesto** [comment] 2018-07-03 07:41
Is this issue fixed? If so, let's close it. Otherwise we need to create a new internal ticket for that.

**Comment by Ghostkeeper** [comment] 2018-08-01 10:35
The original issue is now also fixed. You can create a custom profile for your new material type.

**Closed by Ghostkeeper** 2018-08-01 10:35 UTC
Labels: Category: Cura, Type: Bug
