### ISSUE TITLE
[Cura 4.6] Inconsistent percentage appearing during Scale

### ISSUE THREAD

**Issue by hpandelo** [Ultimaker/Cura#7582] opened 2020-04-23 18:56 UTC
**Application version**
4.6.0-Beta

**Platform**
OS. Windows 10 1909 - Build: 18363.752
CPU. AMD Ryzen 7 3700X
GPU. AMD Radeon RX 5700

**Printer**
Ender 3 PRO (Custom GCode to Beep when starting and finishing the print)

**Reproduction steps**
1. Select the model
2. Click on Scale Menu (or hit S on keyboard)
3. Uncheck all checkboxes to make sure nothing is acting into your values
4. Resize X (by percentage or value)
5. Rezise Y (by percentage or value)
6. Observe value and percentage of Z

**Screenshot(s)**
Attaching a GIF
![BugCuraScale](https://user-images.githubusercontent.com/4274900/80133143-26fbf080-8573-11ea-8f82-3cf92b887ca2.gif)

**Screenshot(s) - EXTRA:**
When I hit "Reset" the value is replaced with the original, but not Y percentage. 
_PS* This isn't happening always!_
![image](https://user-images.githubusercontent.com/4274900/80132819-a4733100-8572-11ea-82aa-6b6cf4f6d16c.png)

**Actual results**
Percentage of Z is getting affected by changes in Y field

**Expected results**
Value and Percentage of Z (or any other) should **not** be affected by changes into unrelated fields

**Project file**
Any

**Comment by rburema** [comment] 2020-04-24 15:13
Have you rotated the object before scaling? (I ask this because if so, then it's probably a known issue.)

**Comment by hpandelo** [comment] 2020-04-24 17:53
@rburema Yeah.. I did it. The original model is placed in Vertical, I rotate to be Horizontal

**Comment by Andy1978** [comment] 2020-04-25 15:17
I guess it's this one: https://github.com/Ultimaker/Cura/issues/4136

**Comment by dxgldotorg** [comment] 2020-04-27 17:30
@rburema Running into scaling issues with rotated parts too.

**Comment by Ghostkeeper** [comment] 2020-04-28 15:07
Yup, duplicate of https://github.com/Ultimaker/Cura/issues/4136. Sorry.

**Closed by Ghostkeeper** 2020-04-28 15:07 UTC
Labels: Type: Bug
