### ISSUE TITLE
Treesupport starts support-parts mid-air

### ISSUE THREAD

**Issue by Orngrimm** [Ultimaker/Cura#12215] opened 2022-05-16 05:45 UTC
### Application Version

5.0.0B+1

### Platform

Windows 10

### Printer

Ultimaker 3

### Reproduction steps

Slice the attached project and see the support change at layer 131 and 132.
See attached 2 screenshots

### Actual results

Tree-Support has islands which start mid-air and arent connected to anywhere: They will be spaghetti and end up glued to somewhere else and potentially messing up the part itself...

### Expected results

Tree-support always "connects" to somewhere to adhere to

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[UM3_Stab-Aligner.zip](https://github.com/Ultimaker/Cura/files/8697440/UM3_Stab-Aligner.zip)
![2022-05-16 07-31-15](https://user-images.githubusercontent.com/74796406/168526929-8d45c145-73ae-4d27-a538-543a918c450e.png)
![2022-05-16 07-31-04](https://user-images.githubusercontent.com/74796406/168526948-e5da6a98-1a2a-4b7f-8f66-0e7926ddc522.png)

**Comment by fvrmr** [comment] 2022-05-19 12:12
Hi @Orngrimm thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/8218, so I will close this issue.

**Closed by fvrmr** 2022-05-19 12:12 UTC
Labels: Type: Bug
