### ISSUE TITLE
Tree supports and anti warping tabs slice fail

### ISSUE THREAD

**Issue by meisterfrogs** [Ultimaker/Cura#15922] opened 2023-06-26 13:42 UTC
### Cura Version

5.4.0-beta1

### Operating System

windows 10

### Printer

creality ender 3 pro

### Name abnormal settings

either tab plus or tab antiwarping with tree supports crashes. 

### Describe model location

Moving from center still crashes. Removing tabs, and rotating the part 45 degrees on Y axis then adding tabs still crashes.

### Describe your model

I have had similar issues with various models, always with tree supports and tabs.

### Add your .zip here ⬇️

[CE3PRO_SATSANA_SPIDER_bltouch_ISAAC.zip](https://github.com/Ultimaker/Cura/files/11869534/CE3PRO_SATSANA_SPIDER_bltouch_ISAAC.zip)
I have had similar failures to slice with cura 5.3.1. I have had some successful slices though. I may have exited and restarted slicer.
Thank you.

**Comment by 5axes** [comment] 2023-06-29 08:38
Ok with Beta 2 
![image](https://github.com/Ultimaker/Cura/assets/11015345/597bdab3-3496-403c-a786-ae0ee3c62032)

**Comment by MariMakes** [comment] 2023-07-05 15:03
Hey @meisterfrogs,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I recognize this issue. 🕵️‍♀️
This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/15836, where using custom supports would result in a slicing crash. 

It's resolved in the 5.4 stable release, you can download the Cura version with the fix here: https://github.com/Ultimaker/Cura/releases/tag/5.4.0
I'll close this issue since it's a duplicate and resolved. 

Feel free to create a ticket if you encounter more issues, together we can make Cura better 💪

**Closed by MariMakes** 2023-07-05 15:03 UTC
Labels: Type: Bug, Status: Triage, Slicing Error :collision:
