### ISSUE TITLE
Slice report error

### ISSUE THREAD

**Issue by JParr91** [Ultimaker/Cura#13578] opened 2022-10-17 18:57 UTC
### Application Version

5.1.1

### Platform

macOS Monterey 12.3.1

### Printer

Custom FFF

### Reproduction steps

Loaded model by clicking folder icon, model loaded, custom profile was selected, hit slice, got error.

### Actual results

error prompt indicated bug, refused to slice

### Expected results

model to be sliced

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Screen Shot 2022-10-17 at 2 52 54 PM](https://user-images.githubusercontent.com/113953273/196258899-777d4c2d-7109-4598-81f5-fa0570d2fecc.png)
[JPD Project 1.3mf.zip](https://github.com/Ultimaker/Cura/files/9803686/JPD.Project.1.3mf.zip)

I could not find the cura.log file as there was no cura folder in the application support library on my computer

**Comment by MariMakes** [comment] 2022-10-18 09:30
Hey @JParr91,

Thanks for your report 💪 

I was able to reproduce your error on my side. 
But I also noticed that by moving the model slightly in the Y direction I was able to slice it. 
![image](https://user-images.githubusercontent.com/40423138/196392816-b23414cb-a224-4c22-83b7-0db106a4561c.png)

Would this help you to get unstuck?

**Comment by JParr91** [comment] 2022-10-18 12:04
Yes that does help.
I also noticed that when I changed my support line thickness, that also fixed it. I change it from 0.6mm to either 0.5mm or 0.7mm and it was fine.
Thanks for the support!
JP
    On Tuesday, October 18, 2022 at 05:31:06 AM EDT, MariMakes ***@***.***> wrote:  
 
 


Hey @JParr91,

Thanks for your report 💪
 
I was able to reproduce your error on my side.
But I also noticed that by moving the model slightly in the Y direction I was able to slice it.


Would this help you to get unstuck?

**Comment by jellespijker** [comment] 2024-01-14 13:30
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.
I'm closing this issue as fixed for the 5.7.0 release

![image](https://github.com/Ultimaker/Cura/assets/8535734/58e1bf00-29ed-40dd-b512-a176e4df75c8)

**Closed by jellespijker** 2024-01-14 13:30 UTC
Labels: Type: Bug, Status: Under Investigation, Slicing Error :collision:
